### ISSUE TITLE
gRPC proxy silently fails to watch

### ISSUE THREAD

**Issue by horkhe** [etcd-io/etcd#10008]
### Setup
Etcd v3.3.8 with TLS (self signed cert) and authentication enabled, 5 node cluster. Application connects via a local gRPC proxy

### Problem
Application occasionally does not receive watches and no errors are reported by the client.

### What we found out
Running gRPC proxy with `--debug` we saw the following error:

```
Aug 15 00:56:27 worker-n01 etcd[9216]: {"level":"info","ts":1534294587.6861775,"caller":"grpcproxy/watch.go:84","msg":"New Watch"}
Aug 15 00:56:27 worker-n01 etcd[9216]: {"level":"info","ts":1534294587.694959,"caller":"grpcproxy/watch.go:245","msg":"New watch request: {Key:[47 118 117 108 99 97 110 100] RangeEnd:[47 118 117 108 99 97 110 101] StartRevision:2302 ProgressNotify:false Filters:[] PrevKv:false WatchId:0 Fragment:false}"}
Aug 15 00:56:27 worker-n01 etcd[9216]: {"level":"info","ts":1534294587.697112,"caller":"grpcproxy/watch.go:250","msg":"checkPermission err: etcdserver: invalid auth token"}
```

However this error is not propagated to the application, more over it is treated as if there were no error at all and success is returned to the application. So the application thinks that the watch has been created successfully and starts waiting for updates that never come: https://github.com/coreos/etcd/blob/94b5071c30e50c1f7c4aa8d7b621ce28238b136b/proxy/grpcproxy/watch.go#L232-L238

**Comment by wenjiaswe** [comment]
@wenjiaswe
