### ISSUE TITLE
could runtime configuration remove member?

### ISSUE THREAD

**Issue by danielzhanghl** [etcd-io/etcd#10015]
hi, in my log, it's found a member is removed from cluster, I don't know why that is happened and how it's removed, the only log from deleted member side is, it's stop seconds ago before it's deleted, which could cause the other member lost connection, but seconds later, this stopped member is deleted.

could the run time reconfiguration delete one member automatically, or it must be a CLI operation to remove it by user itself?

I tried to stop the etcd, but it's not deleted from cluster, just confirm it here.
thanks,

**etcd version: 3.1.11**

log:

one member is stopped manually:
====
Aug 10 16:58:16 sum1man00 journal: 2018-08-10 07:58:16.459532 W | rafthttp: lost the TCP streaming connection with peer ca40b354a78b984b (stream Message reader)
Aug 10 16:58:16 sum1man00 journal: 2018-08-10 07:58:16.459563 W | rafthttp: lost the TCP streaming connection with peer ca40b354a78b984b (stream MsgApp v2 reader)
Aug 10 16:58:16 sum1man00 journal: 2018-08-10 07:58:16.563129 E | rafthttp: failed to dial ca40b354a78b984b on stream Message (read tcp 172.17.0.2:51004->128.101.195.97:2380: read: connection reset by peer)
Aug 10 16:58:16 sum1man00 journal: 2018-08-10 07:58:16.563152 I | rafthttp: peer ca40b354a78b984b became inactive

but who removed it?
=====================

Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.680798 I | **etcdserver/membership: removed member ca40b354a78b984b from cluster 7af95bbe77408863**
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.680819 I | rafthttp: stopping peer ca40b354a78b984b...
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.681547 I | rafthttp: closed the TCP streaming connection with peer ca40b354a78b984b (stream MsgApp v2 writer)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.681558 I | rafthttp: stopped streaming with peer ca40b354a78b984b (writer)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682262 I | rafthttp: closed the TCP streaming connection with peer ca40b354a78b984b (stream Message writer)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682272 I | rafthttp: stopped streaming with peer ca40b354a78b984b (writer)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682305 I | rafthttp: stopped HTTP pipelining with peer ca40b354a78b984b
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682319 I | rafthttp: stopped streaming with peer ca40b354a78b984b (stream MsgApp v2 reader)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682329 I | rafthttp: stopped streaming with peer ca40b354a78b984b (stream Message reader)
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682337 I | rafthttp: stopped peer ca40b354a78b984b
Aug 10 16:58:23 sum1man00 journal: 2018-08-10 07:58:23.682348 I | rafthttp: removed peer ca40b354a78b984b

**Comment by hexfusion** [comment]
> I tried to stop the etcd, but it's not deleted from cluster, just confirm it here.
thanks,

I am not sure I follow, what is the output of `etcdctl member list`. Are you saying peer ca40b354a78b984b is still a member of cluster 7af95bbe77408863?

**Comment by gyuho** [comment]
@danielzhanghl etcd never reconfigures cluster membership itself. That member remove API call must be from your clients.

**Comment by xiang90** [comment]
@gyuho's answer is correct. closing this issue.
