### ISSUE TITLE
Instability of cluster protocol version causes Vault to fail to start

### ISSUE THREAD

**Issue by ymmt2005** [etcd-io/etcd#10038]
I have an issue with etcd 3.3.9 cluster and hashicorp/vault 0.10.4.
The issue was first reported for Vault in https://github.com/hashicorp/vault/pull/5128,
but I am opening this issue as I suggested to do so.

The problem is that Vault sometimes fails to start if it is configured to
use etcd as its storage and to use v3 protocol.  I found that the problem
occurs when etcd reports its cluster version through `/version` API like this:

    {"etcdserver": "3.3.9", "etcdcluster": "3.0.0"}

I observed that `etcdcluster` initially starts with "3.0.0" and will be updated "3.3.0".

However, Vault denies to connect to this cluster because it requires the cluster protocol
version be >= 3.1.0 in order to connect with v3 protocol.
Ref: https://github.com/hashicorp/vault/blob/6c6ead7032d0a78e257ead25c1c3bd08042f0bb1/physical/etcd/etcd.go#L97-L98

Because I heard the code was originally written by CoreOS people, I would like to ask
your help to address this problem.

1. Is it intended that `etcdcluster` starts with "3.0.0" and later be updated?
2. Why Vault requires the cluster protocol be >= "3.1.0"?
3. How should Vault be fixed?
    I thought that simply removing the version check is sufficient and created a pull request:
    https://github.com/hashicorp/vault/pull/5128/files
    Do you agree?

Thanks in advance!

**Comment by xiang90** [comment]
> I observed that etcdcluster initially starts with "3.0.0" and will be updated "3.3.0".

@gyuho https://github.com/coreos/etcd/blob/master/version/version.go#L28

have we tested if etcd 3.3 server can work with 3.0 server? i think we only ensure 3.3 can work with 3.2 server? did we forget to bump the min cluster version?

**Comment by ymmt2005** [comment]
@gyuho @xiang90 
Hi.  Please let me know your thoughts on this.
Specifically, which of etcd or vault should be fixed?  Both?

**Comment by ymmt2005** [comment]
The problem still exists.

**Comment by ymmt2005** [comment]
The problem still exists.
