### ISSUE TITLE
clientv3.New() fails when invoked concurrently

### ISSUE THREAD

**Issue by morimoto-cybozu** [etcd-io/etcd#10035]
`clientv3.New()` returns `Endpoint already exists` error when it is invoked in multiple goroutines at the same time.
[This Gist code](https://gist.github.com/morimoto-cybozu/a6fc624ee507dd19c8aa967b69d07e62) can reproduce errors.
This runs with the latest master branch (commit 2921ab6) of etcd.

```console
$ go build concurrent_new.go
$ for ((i=0; i<1000; i++)) do ./concurrent_new; done
Endpoint already exists for id: client-bntl5iu0z2ns
Endpoint already exists for id: client-bntl5iu1e4v8
:
```

I faced this type of error in `go test`, where many goroutines start etcd connections concurrently.

In `clientv3/client.go`, `newClient()` constructs a client ID with `time.Now().UnixNano()`.
https://github.com/coreos/etcd/blob/master/clientv3/client.go#L479
This timestamp is not provided with high-resolution in some environment, and 2 calls of `time.Now()` can return the same value.
For example, my Ubuntu 16.04 VM on Hyper-V/Win8.1 provides the timestamp in steps of 100 ns.

If the client ID does not need much complexity, it is enough to take ID from a counter with a mutex lock.

**Comment by jpbetz** [comment]
@morimoto-cybozu Which version (or git hash) of the etcd client are you using?

**Comment by morimoto-cybozu** [comment]
@jpbetz 
I'm using commit 2921ab6

**Comment by jpbetz** [comment]
This is almost certainly an issue with the client load balancer rewrite. I'll own getting this fixed.

**Comment by danielzheng** [comment]
any updates for this issue?

**Comment by jpbetz** [comment]
Working on this today

**Comment by jpbetz** [comment]
Switching to a uuid library, will submit a PR shortly
