### ISSUE TITLE
auth. NewAuthStore  return a pointer rather than  interface type auth.AuthStore

### ISSUE THREAD

**Issue by johncming** [etcd-io/etcd#10047]
auth. NewAuthStore  return a pointer rather than  interface type auth.AuthStore.

https://github.com/etcd-io/etcd/blob/1a282a72bec1fb55692698bf3cd06d7d191d1906/auth/store.go#L97

https://github.com/etcd-io/etcd/blob/1a282a72bec1fb55692698bf3cd06d7d191d1906/auth/store.go#L1068

But it assigned to auth.AuthStore type field.

https://github.com/etcd-io/etcd/blob/1a282a72bec1fb55692698bf3cd06d7d191d1906/etcdserver/server.go#L567

https://github.com/etcd-io/etcd/blob/1a282a72bec1fb55692698bf3cd06d7d191d1906/etcdserver/server.go#L237

**Comment by xiaozhan2017** [comment]
*authStore has  implemented the interface AuthStore

**Comment by jingyih** [comment]
Agreed with @mutexlock. auth.NewAuthStore() returns *authStore, which implements interface auth.AuthStore.

Similar examples can be found in 
https://github.com/etcd-io/etcd/blob/1a282a72bec1fb55692698bf3cd06d7d191d1906/etcdserver/api/v3rpc/key.go#L43-L45
where the function NewKVServer() returns &kvServer, which implements interface pb.KVServer
