### ISSUE TITLE
How to expend the max txn opration number, now is 128 ? 

### ISSUE THREAD

**Issue by toranger** [etcd-io/etcd#10048]
etcd Version: 3.3.5

**Comment by wenjiaswe** [comment]
cc @jingyih

**Comment by toranger** [comment]
Is there some value to change? where can i find it ? I use it for save ini configs, want to change file in one operation to keep consistent, the config file changed kvs might be bigger than 12.

**Comment by hexfusion** [comment]
> Is there some value to change? where can i find it ?

@toranger you can define this with etcd server `--max-txn-ops` flag default is 128.

```
--max-txn-ops '128'
     maximum number of operations permitted in a transaction.
```
