### ISSUE TITLE
Why do we make a copy of entries in MemoryStorage.Append?

### ISSUE THREAD

**Issue by guoger** [etcd-io/etcd#10046]
https://github.com/etcd-io/etcd/blob/e52b8611ea8dd746e35df6cf1248272faed4edfd/raft/storage.go#L262-L263

Any particular reason that we couldn't do
```
		ms.ents = append(ms.ents[:offset], entries...)
```
here? thx!

_(of course we need to make a copy of ents to construct fresh `MemoryStorage` in TestStorageAppend in this case)_

**Comment by 85022134** [comment]
I  think  the two ways of implementation above  not  make  the same sence.

		ms.ents = append(ms.ents[:offset], entries...) 
means keep the old ents

**Comment by guoger** [comment]
@85022134 but we do keep the old ents up to `offset`, no?

**Comment by xiaozhan2017** [comment]
I think  it need a dummy entry at term zero.

func NewMemoryStorage() *MemoryStorage {
	return &MemoryStorage{
		// When starting from scratch populate the list with a dummy entry at term zero.
		ents: make([]pb.Entry, 1),
	}
}

**Comment by xiaozhan2017** [comment]
@guoger

**Comment by xiaozhan2017** [comment]
case uint64(len(ms.ents)) > offset:
		ms.ents = append([]pb.Entry{}, ms.ents[:offset]...)
		ms.ents = append(ms.ents, entries...)

it means if you append directly,  will makes entry not continuscous

**Comment by xiaozhan2017** [comment]
@guoger  I understand what you mean. In my opinion, The first writing style may  reduce the capbility of the slice

**Comment by xiang90** [comment]
ms.ents up to the last used index is immutable, since we return it here: https://github.com/etcd-io/etcd/blob/e52b8611ea8dd746e35df6cf1248272faed4edfd/raft/storage.go#L108. It can be used by the caller without locking.

We do not really care about the additional cost of copying since it only happens when there is a conflict.

**Comment by guoger** [comment]
@xiang90 thanks for your response! Although it's still a bit unclear to me. Aren't all public methods on `MemoryStorage` protected by `Mutex` already? In another word, how does direct append affect current locking scheme? Do you mind elaborating a bit? thx

Also, what is _last used index_? 

> We do not really care about the additional cost of copying since it only happens when there is a conflict.

Agreed
