### ISSUE TITLE
enable ppc64le node in https://jenkins-etcd-public.prod.coreos.systems/

### ISSUE THREAD

**Issue by sudeeshjohn** [etcd-io/etcd#10059]
Request to re-enable ppc64le node in https://jenkins-etcd-public.prod.coreos.systems/. The node was down due to hardware issues. We have a new node available for adding to the jenkins. Please let me know how I can share the credentials.

**Comment by gyuho** [comment]
We are currently waiting for CNCF migration to set up public CIs. In the mean time, please reach out to team at CoreOS.
