### ISSUE TITLE
three etcd node alway remind me A:2379 is up but not pinned (already pinned B:2379)

### ISSUE THREAD

**Issue by toranger** [etcd-io/etcd#10061]
PS:etcd3.3.5amd
then the program will stuck. the only thing changed different with one etcd node is add etcd_endpoint=A:2379,B:2379,C:2379   in clientV3.New()'s endpoint.

**Comment by hexfusion** [comment]
@toranger please provide logging and startup flags for the nodes you are having issues with so that we can help debug.

**Comment by wenjiaswe** [comment]
cc @jingyih

**Comment by gyuho** [comment]
@toranger You have to provide more details. In general, you do not need worry about endpoint pinning. It's an internal client balancer logic. In v3.2 and v3.3, it will pin the first connected endpoint with automatic failover. In v3.4, we round-robin. Please see https://etcd.readthedocs.io/en/latest/client-architecture.html for more detail.
