### ISSUE TITLE
Kubernetes 1.11 default etcd server version is v3.2.18,how about etcd v3.2.24?  How stable is etcd v3.2.24 and whether it is suitable for production environment?

### ISSUE THREAD

**Issue by YanLemon** [etcd-io/etcd#10068]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

**Comment by hexfusion** [comment]
@YanLemon Kubernetes team just bumped vendor to 3.2.24 looks like this will be in 1.12, as far as etcd goes 3.2.24 we released Jul 24 and is certainly production ready.

ref: https://github.com/kubernetes/kubernetes/pull/68147
