### ISSUE TITLE
dash.etcd.io: is it gone?

### ISSUE THREAD

**Issue by philips** [etcd-io/etcd#10073]
dash.etcd.io is referenced in `Documentation/op-guide/monitoring.md`. But, it seems to be down/missing. Is it coming back?

**Comment by gyuho** [comment]
@philips We used to serve functional testing status, but haven't maintained it. Once domains get migrated to CNCF, I can rerun them. Or feel free to use it for something else for now.

**Comment by philips** [comment]
Right I guess my question is: are we no longer running functional testing?

**Comment by gyuho** [comment]
@philips We have been running them in CIs https://github.com/etcd-io/etcd/tree/master/functional.

**Comment by philips** [comment]
got it, thanks.

we should either remove the reference to dash.etcd.io in the docs or leave
this bug open.

**Comment by gyuho** [comment]
> remove the reference to dash.etcd.io

Sounds good. Will do today.
