### ISSUE TITLE
etcd use lots of memory, and often OOM.

### ISSUE THREAD

**Issue by yangxuanjia** [etcd-io/etcd#10081]
we has lots of key, and one key is 2.3M,  we start etcd, 5 etcd fast use memory 20G,  and product env, we meet some of OOM event,  5 etcd all down one by one. 

(pprof) top
20063.14MB of 20161.90MB total (99.51%)
Dropped 603 nodes (cum <= 100.81MB)
      flat  flat%   sum%        cum   cum%
20058.51MB 99.49% 99.49% 20058.51MB 99.49%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raftpb.(*Entry).Unmarshal
    4.63MB 0.023% 99.51% 20063.14MB 99.51%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.(*streamReader).decodeLoop
         0     0% 99.51% 20058.51MB 99.49%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/pbutil.MustUnmarshal
         0     0% 99.51% 20058.51MB 99.49%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.(*msgAppV2Decoder).decode
         0     0% 99.51% 20063.14MB 99.51%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.(*streamReader).run
         0     0% 99.51% 20160.40MB   100%  runtime.goexit

**Comment by yangxuanjia** [comment]
by the way, we use etcd 3.2.19

**Comment by yangxuanjia** [comment]
We have about 1000 keys, the others are relatively small, about 1KB, only 1 key is 2.3MB, this key will change, watch, we configure 1 hour compression once. The client probably has 5000-8000 connections to etcd and Keep your heartbeat. Heartbeat 100ms. The current online environment etcd will be beaten down once in about 1 month.

**Comment by xiang90** [comment]
1000 * 2.3MB = 2.3GB. If you update each 2.3 MB keys 10 times within an hour, the accumulated memory usage will be 23GB.

**Comment by wenjiaswe** [comment]
@jingyih

**Comment by jingyih** [comment]
@yangxuanjia Do you know how frequently the large key (of size 2.3 MB) is updated?

**Comment by yangxuanjia** [comment]
not so much,  3 or 4 days only  update the key 1-1000 times


________________________________________
发件人: Jingyi Hu [notifications@github.com]
发送时间: 2018年9月14日 7:09
收件人: etcd-io/etcd
抄送: 杨轩嘉; Mention
主题: Re: [etcd-io/etcd] etcd use lots of memory, and often OOM. (#10081)

@yangxuanjia<https://github.com/yangxuanjia> Do you know how frequently the large key (of size 2.3 MB) is updated?

―

**Comment by jingyih** [comment]
@yangxuanjia forgot to ask: how about the other (small) keys.  Are they updated more frequently?

**Comment by yangxuanjia** [comment]
other small key also not frequently, just use config save.

**Comment by yangxuanjia** [comment]
our system is vitess,  and vitess use etcd to save config.
vschema is the router key,  all database router key merge to one big key,  and the big key is 2.3MB now.
furture the big key will increase.   other small key is user config, keyspace,  master-slave info and so on.

**Comment by jingyih** [comment]
@yangxuanjia can you check if the auto compaction is successful?  In the log you should obeserve something like: 

> completed auto periodic compaction

or 

> Finished auto-compaction at revision
