### ISSUE TITLE
when is the next release?

### ISSUE THREAD

**Issue by h8liu** [etcd-io/etcd#10083]
people are starting to use go modules, but can only use a release before the import path has changed. This has caused incompatibility between `go get` with modules enabled or not.

See https://github.com/google/go-cloud/issues/429 for background.

Is there planning/timeline for a release 4.0.0 (because import path change is not backward compatible now)?

**Comment by gyuho** [comment]
Yeah for v3.4, I will soon switch to go module. Already tried it and works well for etcd.

**Comment by h8liu** [comment]
note that, based on semver spec, after the import path change to `go.etcd.io/etcd`, the version number probably, needs to be 4.0

**Comment by gyuho** [comment]
@h8liu I don't think we need bump up major version? It's only import path change, no API change was made.

**Comment by h8liu** [comment]
because of the import path change, previous code that imports "github.com/coreos/etcd" won't be able to use the code without change. For example:

https://gopkgs.io/builds/20180911-195307-3d66b81f

unless you treat it a completely different package.. where the new version number does not matter.

**Comment by xiang90** [comment]
@h8liu 

The etcd version is not going to get bumped. etcd is a binary program not a library. We have been talking about how to separate the client library versioning from the etcd binary versioning, but have not found a good way to do it.

**Comment by wenjiaswe** [comment]
cc @jpbetz

**Comment by h8liu** [comment]
@xiang90 Thanks for explaining. Then it is wrong for go-cloud (or any repo that uses go mod from 1.11) to reference the version in its `go.mod` or `go.sum`.
