### ISSUE TITLE
Namespace quota for multi-tenancy

### ISSUE THREAD

**Issue by xh4n3** [etcd-io/etcd#10084]
Now etcd has a global storage quota, but for multi-tenant environment, it seems we cannot limit storage usage, key number usage for each user, or each role.

IMHO, if there is a quota for this scenario, it would satisfy these needs.

**Comment by xh4n3** [comment]
My first idea was adding `KeyQuota` and `StorageQuota` to the `Role` struct, `Usage` and `Quota` are created in the following ways:
* List all keys and calculate usage if none usage exists
* Using default quota when creating new roles
* Usage are calculated only when keys matched KeyPermission is being updated
* If Quota.Usage + Cost(Operation) > Quota.Quota, return quota exceeded error.

```
type User struct {
	Name     []byte
	Password []byte
	Roles    []string
}
type Role struct {
	Name          []byte
	KeyPermission []*Permission
	KeyQuota []*Quota
	StorageQuota []*Quota
}
type Quota struct {
	Usage     int64
	Quota      int64
}
```

But multiple users can be bound to a role. If userA, userB are in roleA, when userA exceeds role's quota, userB are impacted as well, this seems unfair.

So I'm thinking maybe creating a new bblot bucket for `quota`, the implementation can be just like leases, mapping key-space to quota.

**Comment by xiang90** [comment]
@xh4n3 

If we want to do multi-tenancy, probably we need to really have separate mvcc store. Or operations like compaction will affect other tenants. The role mechanism is not designed for isolation but simply for auth. The current isolation is pretty weak.

**Comment by CamelCaseNotation** [comment]
I'm interested in this for using multi tenant etcd for kubernetes clusters. Would be nice to restrict certain users from taking up too much key space. Then again, I guess I could handle that at the kubernetes level with object quotas, hmmm

**Comment by agargi** [comment]
I believe this would be an interesting feature. Solution would also need to `address number of requests that each tenant can fire into the cluster (and not only key/ storage quotas).

**Comment by tangcong** [comment]
yes, it also needs a QoS feature #8483. @agargi

**Comment by vivekpatani** [comment]
@tangcong @agargi @xh4n3 do you guys have any POCs for this? Just wanted to check in to see if you guys had something in mind. Thanks.

**Comment by vivekpatani** [comment]
@tangcong @gyuho @jpbetz @xiang90 @wenjiaswe Have we investigated any type of sub buckets within bbolt to implement namespace quota?

I'm just looking to gauge if the community would be interested in something like this? Is this a desirable feature and if it's fitting with the etcd offerings? Thanks.

**Comment by vivekpatani** [comment]
@tangcong @gyuho @jpbetz @xiang90 @wenjiaswe @agargi Here's a technical doc that solves the problem for multi tenancy. Would really appreciate a review and get feedback, would like to implement this once the review is complete and all the issues in the document are addressed. Thank you, appreciate your time and efforts.

Link: https://docs.google.com/document/d/1POdNdFBgpcGqLwurZjy8qQki6beOoVIcElTqHy4DnnA/edit

**Comment by wenjiaswe** [comment]
cc @jingyih @ptabor

**Comment by vivekpatani** [comment]
@tangcong @gyuho @jpbetz @xiang90 @wenjiaswe @agargi @jingyih @ptabor just a gentle reminder.

Link: https://docs.google.com/document/d/1POdNdFBgpcGqLwurZjy8qQki6beOoVIcElTqHy4DnnA/edit

**Comment by vivekpatani** [comment]
@tangcong @gyuho @jpbetz @xiang90 @wenjiaswe @agargi @jingyih @ptabor just a gentle reminder.

We spoke about this at the `kube-sig-api-machinery`. We'd like to get your feedback on this in order to move forward.

Thank you.
