### ISSUE TITLE
etcd 3.3.9 does not parse "wal-dir" configuration correctly

### ISSUE THREAD

**Issue by Saloshp** [etcd-io/etcd#10098]
Configuring etcd to use any destined directory */foo/bar* , causes it to try and create */foo/bar.tmp*, where it has no permissions

**Debugging information**
```bash
[root@ha01 ~]# uname -a
Linux ha01 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux
```
```bash
[root@ha01 ~]# etcd --version
etcd Version: 3.3.9
Git SHA: fca8add78
Go Version: go1.10.3
Go OS/Arch: linux/amd64
```

> ...
> Sep 17 09:53:44 ha01 etcd[9754]: name = ha01
> Sep 17 09:53:44 ha01 etcd[9754]: force new cluster
> Sep 17 09:53:44 ha01 etcd[9754]: data dir = /var/lib/etcd
> Sep 17 09:53:44 ha01 etcd[9754]: member dir = /var/lib/etcd/member
> Sep 17 09:53:44 ha01 etcd[9754]: **dedicated WAL dir = /var/lib/etcd-wal**
> Sep 17 09:53:44 ha01 etcd[9754]: heartbeat = 269ms
> Sep 17 09:53:44 ha01 etcd[9754]: election = 1345ms
> Sep 17 09:53:44 ha01 etcd[9754]: snapshot count = 10000
> Sep 17 09:53:44 ha01 etcd[9754]: advertise client URLs = https://172.16.0.1:2379,https://ha01.munio.io:2379
> Sep 17 09:53:44 ha01 etcd[9754]: initial advertise peer URLs = https://ha01.munio.io:2380
> Sep 17 09:53:44 ha01 etcd[9754]: initial cluster = ha01=https://ha01.munio.io:2380,ha02=https://ha02.munio.io:2380,ha03=https://ha03.munio.io:2380
> Sep 17 09:53:44 ha01 etcd[9754]: **create wal error: mkdir /var/lib/etcd-wal.tmp: permission denied**
> ...

**Comment by gyuho** [comment]
Do you have write access to that directory?

**Comment by hexfusion** [comment]
> Configuring etcd to use any destined directory /foo/bar , causes it to try and create /foo/bar.tmp, where it has no permissions.

Part of the wal initialization is to create this .tmp directory. Perhaps better to set /var/lib/etcd/wal where etcd dir perms allow write for etcd user.
https://github.com/etcd-io/etcd/blob/fca8add78a9d926166eb739b8e4a124434025ba3/wal/wal.go#L92-L109

**Comment by Saloshp** [comment]
@gyuho 
```bash
[root@ha01 ~]# ls -lash /var/lib/etcd*
/var/lib/etcd:
total 12K
4.0K drwxr-xr-x  3 etcd etcd 4.0K Sep 17 16:30 .
4.0K drwxr-xr-x 26 root root 4.0K Sep 17 16:30 ..
4.0K drwx------  3 etcd etcd 4.0K Sep 17 16:28 member

/var/lib/etcd-wal:
total 8.0K
4.0K drwxr-xr-x  2 etcd etcd 4.0K Sep 17 16:30 .
4.0K drwxr-xr-x 26 root root 4.0K Sep 17 16:30 ..
```
```bash
[root@ha01 ~]# cat /etc/etcd/conf.yml | grep dir
# Path to the data directory.
data-dir: /var/lib/etcd
# Path to the dedicated wal directory
wal-dir: /var/lib/etcd-wal
```
@hexfusion 
I was trying to solve some performance issues due to very high load, and so I thought I'd mount the *wal-dir* to a 64M *tmpfs* drive, and I didn't want the mountpoint to be under the working directory of *etcd* to make automation easier.
Setting the *wal-dir* to */var/lib/etcd/wal* does work, but I don't see the point of specifying an unusable var.. (?)

**Comment by hexfusion** [comment]
/var/lib is presumably owned by root of your mount is /var/lib/etcd-wal set the flag to /var/lib/etcd-was/foo ? Point is you need write perms to the containing directory.

**Comment by Saloshp** [comment]
@hexfusion 
IMHO line 100 should be:
```go
 tmpdirpath := filepath.Clean(dirpath) + "/.tmp" 
```
A user should be able to use this var to specify any directory he wishes, assuming he set the right permissions to it, under it the code can do whatever it needs.

**Comment by hexfusion** [comment]
> IMHO line 100 should be:
 tmpdirpath := filepath.Clean(dirpath) + "/.tmp" 

@Saloshp I think you are going to still run into issues. Can you show me a working example of how that would work? Here is the logic condensed.

```golang
package main                                                                                                          
                                                                                                                      
import (                                                                                                              
    "fmt"                                                                                                             
    "os"                                                                                                              
    "path/filepath"                                                                                                   
                                                                                                                      
    "go.etcd.io/etcd/pkg/fileutil"                                                                                    
)                                                                                                                     
                                                                                                                      
func main() {                                                                                                         
    dirpath := "/var/lib/etcd-wal"                                                                                    
    tmpdirpath := filepath.Clean(dirpath) + "/.tmp"                                                                   
    if err := fileutil.CreateDirAll(tmpdirpath); err != nil {                                                         
        fmt.Printf("Opps create failed: %s", err)                                                                     
    }                                                                                                                 
    if err := os.Rename(tmpdirpath, dirpath); err != nil {                                                            
        fmt.Printf("Opps rename failed: %s\n", err)                                                                   
    }                                                                                                                 
}
```

> A user should be able to use this var to specify any directory he wishes, assuming he set the right permissions to it, under it the code can do whatever it needs.

Yes correct you need write permissions create the `--wal-dir` in your case this is not true.

**Comment by hexfusion** [comment]
> What issues? if the user had configured wal-dir = /var/lib/etcd-wal,
and this folder has the correct permissions like I have shown you, why won't the code create /var/lib/etcd-wal/.tmp?

Yes you can create .tmp but the next step for the code is to `mv /var/lib/etcd-wal/.tmp /var/lib/etcd-wal` this will not work right? Have you tested the code?

**Comment by Saloshp** [comment]
No, I have not tested the code, of course it will fail in the current logic,
what I would do, is eliminate the creation and move process, use the provided `wal-dir` and test permissions against it.
Would you accept such pull-request?

**Comment by Saloshp** [comment]
Something like that would do:
```go
package main                                                                                                          
                                                                                                                      
import (                                                                                                              
    "fmt"                                                                                                             
    "os"                                                                                                              
    "path/filepath"                                                                                                   
                                                                                                                      
    "go.etcd.io/etcd/pkg/fileutil"                                                                                    
)                                                                                                                     
                                                                                                                      
func main() {                                                                                                         
    dirpath := "/var/lib/etcd-wal"                                                                                    
    tmpdirpath := filepath.Clean(dirpath) + "/.tmp"                                                                   
    if err := fileutil.CreateDirAll(tmpdirpath); err != nil {                                                         
        fmt.Printf("Opps create failed: %s", err)                                                                     
    }
}
```

I'd be happy to create and test a PR

**Comment by hexfusion** [comment]
If the `data-dir` or `wal-dir` don't exist they will be created. Since these both require write perms. I think we should document this explicitly and be done right? Could you open a PR to that? I would really appreciate it. Changing this logic is not as trivial as it seems or in my opinion justified.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md
