### ISSUE TITLE
etcdctl complete delete wipe

### ISSUE THREAD

**Issue by vorburger** [etcd-io/etcd#10101]
For local testing, I find myself wanting to just completely "wipe" any data etcd from the CLI with etcdctl :

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/ proposes this, but NOK:

    $ etcdctl del "" --prefix
    No help topic for 'del'

    $ etcdctl rm -r ""
    $ Error:  107: Root is read only (/) [3]

Currently I do it like this, but this of course feels more like a workaround:

    $ sudo systemctl stop etcd
    $ sudo rm -rf /var/lib/etcd/default.etcd
    $ sudo systemctl start etcd

PS: Old and close #2385 had something similar, it seems.

**Comment by vorburger** [comment]
@hexfusion oh. Yeah - that seems to work great; thanks!

**Comment by iofirag** [comment]
ETCDCTL_API=3 etcdctl del "*" --from-key=tru

**Comment by coiouhkc** [comment]
Similar to `get` (cannot find the issue to link now), following seems to work as well (jetcd 0.8.2)
```java
ByteSequence key = ByteSequence.from("\0", StandardCharsets.UTF_8);
client.getKVClient().delete(key, DeleteOption.builder().withRange(key).build()).get();
```
