### ISSUE TITLE
etcdctl get option for escaping unprintable bytes

### ISSUE THREAD

**Issue by vorburger** [etcd-io/etcd#10102]
During local testing, I've used `etcdctl ls -r` just wanting to see if it "had any entries" (and perhaps like `wc -l` them), and realized, after some confusion, that `etcdctl ls` seems to just silently skip any keys with unprintable characters?

Perhaps it could instead (have an option to) print them with some sort of escaping.

See also https://github.com/etcd-io/jetcd/issues/399.

**Comment by hexfusion** [comment]
Hi @vorburger for v3 we use something like `etcdctl get  --from-key ''` does this output as expected? My understanding is that jetcd is the official java client for etcd v3 so this would be a more proper comparison.

**Comment by hexfusion** [comment]
For just keys `ETCDCTL_API=3 etcdctl get "" --prefix --keys-only`

**Comment by vorburger** [comment]
@hexfusion indeed using `ETCDCTL_API=3 etcdctl get --from-key ''` instead of `etcdctl ls -r` prints all.

It's "binary" though.. but I guess one could pipe it into some suitable tool - e.g. `ETCDCTL_API=3 etcdctl get --from-key '' | od -c`, although that is far more verbose than some kind of simpler "KV-per-line with any non-printable characters escaped" kind of output format, as proposed in https://github.com/etcd-io/jetcd/issues/399. BTW, for any external UNIX piped utility it's probably not possible to distinguish separate KVs from CR/LF bytes in keys and values.

PS: Shouldn't `ETCDCTL_API=3` become the default at some point?

**Comment by hexfusion** [comment]
> PS: Shouldn't ETCDCTL_API=3 become the default at some point?

Yes sir, v3.4 https://github.com/etcd-io/etcd/issues/9600

**Comment by hexfusion** [comment]
> It's "binary" though.. but I guess one could pipe it into some suitable tool

We also have --hex flag.  `etcdctl get --from-key '' --hex`

Do you have any further questions? Could you give an example of problematic data?

**Comment by vorburger** [comment]
Let's close this (the `--hex` is good enough).
