### ISSUE TITLE
Where to change the Default Client-Request, Heartbeat, Election timeouts?

### ISSUE THREAD

**Issue by ISuckAtPython** [etcd-io/etcd#10107]
EtcdServer 3.3.8 
EtcdCluster 3.3.0

I want to change the default timeouts for client connections, client commands, heartbeats, and elections.

I can only find info on how to adjust these timeouts on a request/command basis, but I want to permanently change these timeouts. Can I do this from etcd command line or edit a config file somewhere? I haven't been able to find this info in documentation.

Also is there a way I can print or lookup these defaults so I can confirm my changes have taken affect?

**Comment by hexfusion** [comment]
> I want to change the default timeouts for client connections, client commands, heartbeats, and elections.

Heartbeats and election timeouts are etcd server these can be defined with configuration file ENV var and flag. The client you can set with flag or ENV var ie `ETCDCTL_DIAL_TIMEOUT`. So if you on a user level added.

`export ETCDCTL_DIAL_TIMEOUT=3s`

to your .bashrc or .bash_profile then source or re-login you would make this persistent on each call with etcdctl same idea as `ETCDCTL_API=3`.

#### server

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--heartbeat-interval

#### client
https://github.com/etcd-io/etcd/blob/master/etcdctl/README.md#etcdctl

**Comment by hexfusion** [comment]
> Also is there a way I can print or lookup these defaults so I can confirm my changes have taken affect?

etcd logs will show the configs when the node starts. On the client, you could do `printenv | grep ETCDCTL_*` * assuming Linux.

**Comment by hexfusion** [comment]
@ISuckAtPython does this answer your questions?

**Comment by ISuckAtPython** [comment]
Yes this was helpful, I successfully increased the election/heartbeat timeouts. I am curious is there anything I can do at a Server level for connection/command related actions or does that have to be done at the client?

**Comment by hexfusion** [comment]
@ISuckAtPython dial timeout is on the client.
