### ISSUE TITLE
raftexample may never serve http request after loading snapshots

### ISSUE THREAD

**Issue by guoger** [etcd-io/etcd#10118]
https://github.com/etcd-io/etcd/blob/2cf47366216a50826aab7c37784eba0c1ced3ee1/contrib/raftexample/kvstore.go#L65
this loop may never return if no new signal is sent on `commitC` or we **have** snapshot to load. It blocks https://github.com/etcd-io/etcd/blob/2cf47366216a50826aab7c37784eba0c1ced3ee1/contrib/raftexample/kvstore.go#L43
so that http server is never started.

To reproduce
- run `raftexample` and repeatedly put key-value until it takes a snapshot,
- restart cluster

**Comment by zhaoxuat** [comment]
if replace "continue" with "return" in  readCommits, it can solve this question
