### ISSUE TITLE
clientv3/concurrency: return error in Mutex.Lock if lock were unlocked due to closed context

### ISSUE THREAD

**Issue by funny-falcon** [etcd-io/etcd#10111]
It is better to return specific error at this place https://github.com/etcd-io/etcd/blob/f32bc507658e287a69d89e0e1a4d083a01d9da3e/clientv3/concurrency/mutex.go#L73-L75
because currently client may assume it acquired lock if error will be nil.

And even if it doesn't (because context were canceled, therefore, outer code may not do anything meaningful), outer code will call to `mtx.Unlock` second time (because it doesn't know that lock were unlocked already).

**Comment by wenjiaswe** [comment]
@jingyih

**Comment by jingyih** [comment]
Firstly I want to make it clear that I am not very familiar with this piece of code.  

My two cents:
Looks like you should call IsOwner() to check if you are actually holding the lock:
https://github.com/etcd-io/etcd/blob/f32bc507658e287a69d89e0e1a4d083a01d9da3e/clientv3/concurrency/mutex.go#L91-L93

My understanding is that even if Lock() returns nil, you cannot assume you are holding the lock after the call is finished (Because your lock may expire due to lease expiration).  So for all the following operations, you still need to check if you are still holding the lock.

@gyuho @xiang90 any comment?

**Comment by funny-falcon** [comment]
> (Because your lock may expire due to lease expiration)

Mutex's lock could not be expired for this particular reason, at least by default. By default Session performs KeepAlive for its lease. Programmer have to do explicit action to orphan Session (Session.Orphan()), or connection to etcd have to be broken.

If there is no any guarantee, then there is no gain from Mutex, then Mutex is useless.

I understand level of Mutex's reliability, and I doesn't more than simpke sanity. The fact Mutex.Lock could return nil when it is certainly not held is damn bad inconvenience. I worked around reliying on `mutex.Key() == "\x00"` after Unlock(). But it is just stupid work around stupid behaviour.

**Comment by jingyih** [comment]
@funny-falcon After a bit more reading of the code, I agree with you that Lock() should not return nil if the call is finished due to context cancellation.

**Comment by jingyih** [comment]
@funny-falcon do you have a test case where the Lock function returns nil when `ctx.Done()` occurs?  
https://github.com/etcd-io/etcd/blob/f32bc507658e287a69d89e0e1a4d083a01d9da3e/clientv3/concurrency/mutex.go#L70-L79
How is `werr` nil when `ctx.Done()` happens?

**Comment by funny-falcon** [comment]
@jingyih it is extremely difficult to write test in a way context is cancelled exactly after `waitDeletes` successfully returns and before `<-ctx.Done()` is checked. I suppose, there should be at least million iterations in average to trigger. 

But while it is hard to catch when you want to catch, it will certainly happen once a week in production, if ctx has small timeout.

This issue is quite obvious to any one who understand multithreaded programming, and especially, multicore multithreaded.

It is simplier to fix it by adding three lines of code instead of arguing:

```
   case <-ctx.Done(): 
     m.Unlock(client.Ctx())
+    if werr == nil {
+      werr = ctx.Err()
+    } 
```

That is all that is need to be done.

**Comment by xiang90** [comment]
@funny-falcon @jingyih 

An easy way to fix the problem is to check werr first. If there is no error (lock acquired), then just return nil regardless of the ctx timed out or not.

**Comment by xiang90** [comment]
this is actually a bug. we should fix it and backport.

**Comment by funny-falcon** [comment]
@xiang90 I agree with you: checking only `werr` without `ctx.Done` is also acceptable and consistent in a sense "either werr == nil or lock is not held at the moment".

**Comment by xiang90** [comment]
@funny-falcon can you please submit a PR to fix it.

**Comment by funny-falcon** [comment]
Done: #10153

**Comment by jingyih** [comment]
@funny-falcon Thanks for your explanation.  I was just trying to get a better understanding.
