### ISSUE TITLE
tests failure while build from source

### ISSUE THREAD

**Issue by ajay-ibm** [etcd-io/etcd#10130]
I've built etcd v3.3.9 from source on ubuntu 16.04 using Go 1.10.1 . When I run `./test` , it fails with the following error:
```
gofmt checking failed:
mvcc/backend/backend.go
diff -u mvcc/backend/backend.go.orig mvcc/backend/backend.go
--- mvcc/backend/backend.go.orig        2018-09-27 13:26:18.713156228 +0000
+++ mvcc/backend/backend.go     2018-09-27 13:26:18.713156228 +0000
@@ -292,7 +292,7 @@

 func (b *backend) defrag() error {
        now := time.Now()
-
+
        // TODO: make this non-blocking?
        // lock batchTx to ensure nobody is using previous tx, and then
        // close previous ongoing tx.
```
Tried with Go 1.11 and also tried with latest master but it still fails. How to resolve this issue?

**Comment by hexfusion** [comment]
@ajay-ibm this has been fixed in master and is a known issue https://github.com/etcd-io/etcd/issues/9995. In your case, if you want to resolve the issue directly your test would pass which is a rouge tab I believe.

**Comment by ajay-ibm** [comment]
@hexfusion Which Go version is required for this? I have tried with Go 1.10.1 and 1.11 but facing same issue on master also.

**Comment by hexfusion** [comment]
@ajay-ibm 1.11 works fine `git branch | grep \* ;git rev-parse HEAD`? are you sure you are on latest master?

a3e242d80ae1a13ae57904fc12e91fe4c9ecf972

**Comment by ajay-ibm** [comment]
@hexfusion after removing the tab I'm facing other error (etcd 3.3.9 + go 1.10.1)
`gopath/src/github.com/coreos/etcd/auth/store_test.go:675: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserAddRequest composite literal uses unkeyed fields` 

On (etcd v3.3.9 with Go 1.9.2) after removing the tab I got:
```
'commit_title' started at Wed Oct 10 08:33:55 UTC 2018
7f421ef remove "github.com/gogo/protobuf/plugin/stringer"...
Expected commit title format '<package>{", "<package>}: <description>'
Got: 7f421ef remove "github.com/gogo/protobuf/plugin/stringer"
```
On (etcd v3.3.9 with Go 1.11.1) I'm getting fmt checking error on different files:
```
embed/config.go
etcdserver/config_test.go
etcdserver/api/v2http/client.go
functional/agent/server.go
mvcc/backend/backend.go
...
```

**Comment by ajay-ibm** [comment]
With etcd v3.3.10 and go1.10.4 got the following: 
First got fmt error in mvcc/backend/backend.go like mentioned in the 1st comment. Removed the tab manually. then got 
```
'govet' started at Tue Oct 23 13:36:58 UTC 2018
# github.com/coreos/etcd/auth
gopath/src/github.com/coreos/etcd/auth/store_test.go:675: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserAddRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:682: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthRoleAddRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:687: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserGrantRoleRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:693: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserGetRequest composite literal uses unkeyed fields
...
```
