### ISSUE TITLE
cant build using go.etcd.io/etcd/embed

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10147]
go 1.11
i'm try to go get in my package that uses go.mod:
```
go get  go.etcd.io/etcd/embed
go: finding go.etcd.io/etcd/embed latest
# github.com/coreos/etcd/mvcc/backend
../../../.cache/go-path/pkg/mod/github.com/coreos/etcd@v3.3.9+incompatible/mvcc/backend/config_linux.go:31:2: unknown field 'NoFreelistSync' in struct literal of type bolt.Options
```

**Comment by gyuho** [comment]
We are moving to go module soon https://github.com/etcd-io/etcd/pull/10112. Hopefully, it would fix your issue.

**Comment by vtolstov** [comment]
gentle ping.... if i can fix this by hand in vendor folder, but my ci can't do tests.
```
/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/mvcc/backend/config_linux.go:31:2: unknown field 'NoFreelistSync' in struct literal of type bolt.Options
```

**Comment by vtolstov** [comment]
also as i see all code contains old import paths github.com/coreos/etcd and not new. So in vendor i have two etcd versions - some of go.etcd.io and some github.com/coreos/etcd.

**Comment by gyuho** [comment]
@vtolstov Works for me?

```
$ go get -v go.etcd.io/etcd/embed
go.etcd.io/etcd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime
go.etcd.io/etcd/vendor/github.com/gorilla/websocket
go.etcd.io/etcd/vendor/github.com/soheilhy/cmux
go.etcd.io/etcd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus
go.etcd.io/etcd/etcdserver/api/rafthttp
go.etcd.io/etcd/vendor/google.golang.org/grpc/health
go.etcd.io/etcd/etcdserver/api/v3election/v3electionpb/gw
go.etcd.io/etcd/etcdserver/etcdserverpb/gw
go.etcd.io/etcd/etcdserver/api/v3lock/v3lockpb/gw
go.etcd.io/etcd/etcdserver/api/v3rpc
go.etcd.io/etcd/embed
```

Run `go mod` commands inside your project that imports etcd should work? 
Do you have reproducible steps?

**Comment by vtolstov** [comment]
As i understand i have older bbolt version in go.mod file.
my go.mod:
github.com/coreos/bbolt v1.3.1-etcd.8 // indirect
go.etcd.io/bbolt v1.3.0 // indirect
github.com/coreos/etcd v3.3.10+incompatible // indirect
go.etcd.io/etcd v3.3.10+incompatible

as i see this bad clush because import inside etcd not changed to new location

**Comment by gyuho** [comment]
Did it work?

**Comment by vtolstov** [comment]
i'm remove all etcd stuff from go.mod file and re-download all to master versions and update go.mod. now all fine. thanks.
