### ISSUE TITLE
How to choose a more stable release?

### ISSUE THREAD

**Issue by rinsozheng** [etcd-io/etcd#10140]
When we begin to use etcd, there are so many releases for us to choose, do you have a recommendation about which is the most stable release on v2 and which is the most stable release on V3? Or do you have any principle in distributing the release?

**Comment by jpbetz** [comment]
We currently support etcd 3.1-3.3.

etcd 3.0 and 2.x are outside of the version window the community is able to support. Until one is able to upgrade to 3.1+, we recommend running the latest patch release of 2.x and 3.0.

Also, note these guidelines we posted recently (https://groups.google.com/forum/#!topic/etcd-dev/nZQl17RjxHQ):

> If you run etcd in production, please read!
> 
> A couple recent issue report on github for both etcd and Kubernetes github have highlighted the fact that some older versions of etcd contain defects severe enough that we should avoid running them in production, including a data corruption bug.  Also, with Kubernetes deprecating etcd 2.x support this year and the officially maintained etcd versions being 3.1+,
> 
> The minimum recommended versions of etcd to run in production are:
> 3.1.11+
> 3.2.10+
> 3.3.0+

**Comment by rinsozheng** [comment]
Thanks a lot!
