### ISSUE TITLE
example of v3 auth via jwt token

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10144]
where i can find info or examples how to auth via jwt tokens?

**Comment by hexfusion** [comment]
@vtolstov the server does the work so once you generate the keys and set the correct values for --auth-token you use the token in the same way as you would a simple token. I will show an example using RS256.

```
# gen key pair for RS256
openssl genrsa -out jwt_RS256 4096
openssl rsa -in jwt_RS256 -pubout > jwt_RS256.pub
```

etcd server flags
```
--auth-token=jwt,pub-key=/srv/jwt_RS256.pub,priv-key=/srv/jwt_RS256,sign-method=RS256
```

next enable auth and when you pass authentication you will see that the jwt signed token is generated by the server and passed to the client.

```
etcd-1_1  | 2018-10-10 01:38:04.925940 N | auth: Role root is created
etcd-1_1  | 2018-10-10 01:40:06.678996 N | auth: added a new user: root
etcd-1_1  | 2018-10-10 01:40:11.336841 N | auth: granted role root to user root
etcd-1_1  | 2018-10-10 01:40:28.163644 N | auth: Authentication enabled
etcd-1_1  | 2018-10-10 01:40:50.448956 D | auth: jwt token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXZpc2lvbiI6NCwidXNlcm5hbWUiOiJyb290In0.TLPHFHP5VnVos6kfndcok-1nrKAWxlH_uSEiadNJUr8lc3MwjdNYaCnJU1OiHeGBVAqjbEhg0M5VHi--ebblVKxA9Yh6t2rzrGJ_R5ssLeV5f0UfvH8lEl92xNqz_sZbkxhKCOCSSuzhO_wWTvK1GcmpWR7pjYTBH6-_bywmPH1VSWsafgGno_fEWq38JYRWsEiMiwkMPQJLfynjr2YfOK1R8ZLzJG1cnXOTvmA3uwfIDtxqhP5l7T4_053d8cqnXXqjxOVCQNrHma1gC4ZalxNGcHKGyRwf6IMhZySqe3sHKCWF_fNwBFKTD0UwjRsnoE9DGXPwvFe4gFAfEuNi5jZBjD5eaaJs9lhEfIM77XM4LCA1kWh6vlgEuj2wLZJuoR28lJfQV9gVpLHFZ8fP-_SJQIjABCIgtyQNW39NLO4enL4CDjqJl1CMY8XNd6Gx65x5_1MSpMnFHk0nejSCtipBPW111oLksnHuYqGdYvCdaPaEq-64-S7NE79uYzMkj0-4_3tNZXZtW8MlzlH0TrgFW5Gn-qFDctNq2XEPc4dcPftJoTHgWWgNxef30DcYWzhC4wBunTuiI28jsIEymYtc57NvQ30_8Hz15E0wV6uTGguhmKRVFTyrScnlu-2dTg7-j9f1yuv_ysgqrsQzGh0811vZHX6t9gUayH2Tv2g
```
I hope this answers your question.

**Comment by vtolstov** [comment]
How can i do that via etcd api ?

**Comment by hexfusion** [comment]
@vtolstov please see this example in the docs and let me know if you have any questions. [gRPC-gateway authentication](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md#authentication)

**Comment by vtolstov** [comment]
@hexfusion thanks! this is enought.

**Comment by ae6rt** [comment]
> @vtolstov the server does the work so once you generate the keys and set the correct values for --auth-token you use the token in the same way as you would a simple token. I will show an example using RS256.
> 
> ```
> # gen key pair for RS256
> openssl genrsa -out jwt_RS256 4096
> openssl rsa -in jwt_RS256 -pubout > jwt_RS256.pub
> ```
> 
> etcd server flags
> 
> ```
> --auth-token=jwt,pub-key=/srv/jwt_RS256.pub,priv-key=/srv/jwt_RS256,sign-method=RS256
> ```
> 
> next enable auth and when you pass authentication you will see that the jwt signed token is generated by the server and passed to the client.
> 
> ```
> etcd-1_1  | 2018-10-10 01:38:04.925940 N | auth: Role root is created
> etcd-1_1  | 2018-10-10 01:40:06.678996 N | auth: added a new user: root
> etcd-1_1  | 2018-10-10 01:40:11.336841 N | auth: granted role root to user root
> etcd-1_1  | 2018-10-10 01:40:28.163644 N | auth: Authentication enabled
> etcd-1_1  | 2018-10-10 01:40:50.448956 D | auth: jwt token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXZpc2lvbiI6NCwidXNlcm5hbWUiOiJyb290In0.TLPHFHP5VnVos6kfndcok-1nrKAWxlH_uSEiadNJUr8lc3MwjdNYaCnJU1OiHeGBVAqjbEhg0M5VHi--ebblVKxA9Yh6t2rzrGJ_R5ssLeV5f0UfvH8lEl92xNqz_sZbkxhKCOCSSuzhO_wWTvK1GcmpWR7pjYTBH6-_bywmPH1VSWsafgGno_fEWq38JYRWsEiMiwkMPQJLfynjr2YfOK1R8ZLzJG1cnXOTvmA3uwfIDtxqhP5l7T4_053d8cqnXXqjxOVCQNrHma1gC4ZalxNGcHKGyRwf6IMhZySqe3sHKCWF_fNwBFKTD0UwjRsnoE9DGXPwvFe4gFAfEuNi5jZBjD5eaaJs9lhEfIM77XM4LCA1kWh6vlgEuj2wLZJuoR28lJfQV9gVpLHFZ8fP-_SJQIjABCIgtyQNW39NLO4enL4CDjqJl1CMY8XNd6Gx65x5_1MSpMnFHk0nejSCtipBPW111oLksnHuYqGdYvCdaPaEq-64-S7NE79uYzMkj0-4_3tNZXZtW8MlzlH0TrgFW5Gn-qFDctNq2XEPc4dcPftJoTHgWWgNxef30DcYWzhC4wBunTuiI28jsIEymYtc57NvQ30_8Hz15E0wV6uTGguhmKRVFTyrScnlu-2dTg7-j9f1yuv_ysgqrsQzGh0811vZHX6t9gUayH2Tv2g
> ```
> 
> I hope this answers your question.

I don't fully understand how to use JWT tokens.  Are you saying that if you set the `--auth-token` option to etcd nodes on startup, then clients that connect via gRPC with username:password will be issued a JWT token?  I'm trying to workaround this bug https://github.com/etcd-io/etcd/issues/9629.  I was under the impression that authenticating with a username:password without `--auth-token` was sufficient, but apparently not.  The documentation around auth tokens does not make it clear when or why you'd want to use them over only simple username:password.

**Comment by ahrtr** [comment]
For anyone reference, please read https://github.com/ahrtr/etcd-issues/blob/master/docs/token_management.md

**Comment by jiweiqing** [comment]
@hexfusion hi.How should I enable jwt using configuration files?
