### ISSUE TITLE
embed etcd in own app without listen to external client connections

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10143]
I want to integrate etcd in my app, but i don't want to listen for client connections from external address and not want to bind to loopback tcp addr. Does it possible to listen for client conns with abstract linux socket? or something that only accessible from my app?

**Comment by jpbetz** [comment]
Looks like the problem is that `embed.Config` is not well documented.  I believe what you need is the `LCUrls` and `ACLurls` config fields, which are equivalent to the `--listen-client-urls` and `--advertise-client-urls` flags.

```
cfg := embed.NewConfig()
lcURLs, err = types.NewURLs([]string{"https://127.0.0.1:1379"})
if err != nil { ...}
cfg.LCUrls = lcURLs
e, err := embed.StartEtcd(cfg)
...
```

**Comment by vtolstov** [comment]
I know about that, thanks. But i mean not listen to loopback addresses too. So avoid all tcp/ip stuff and run GRPC methods directly with provided struct messages...

**Comment by jpbetz** [comment]
Ah, sorry, yes, you can use unix sockets.  The URL format is `unix://<path>` (or `unixs://<path>` for TLS over unix socket).  Provide this to both the etcd server and client.

**Comment by vtolstov** [comment]
But if i don't want use sockets that creates files on disk? Does it possible to use abstract linux sockets?

**Comment by jpbetz** [comment]
@vtolstov AFAIK, That's not currently supported.

**Comment by vtolstov** [comment]
@jpbetz do you plan such feature or prs welcome?=)
