### ISSUE TITLE
Move etcd release process to the cloud

### ISSUE THREAD

**Issue by jpbetz** [etcd-io/etcd#10151]
Current status:
- Pre-signing release process is automated by https://github.com/etcd-io/etcd/blob/master/scripts/release has been in use by patch mangers for 3+ months and includes validation checks throughout process
- CNCF credits can be used to run builds in the cloud

Gaps:
- Community agreement on where/how to run cloud builds - [GCB](https://cloud.google.com/cloud-build/) is what Kubernetes uses, and what CNCF has the most credits available for, so that seems reasonable
- Secure community release signing process. Needed? (see https://github.com/kubernetes/release/issues/636 for Kubernetes status)

see also:
- etcd-release-runbook (https://goo.gl/Gxwysq)

**Comment by gyuho** [comment]
> Current status:
> 
>     * Pre-signing release process is automated by https://github.com/etcd-io/etcd/blob/master/scripts/release has been in use by patch mangers for 3+ months and includes validation checks throughout process
> 
>     * CNCF credits can be used to run builds in the cloud
> 
> 
> Gaps:
> 
>     * Community agreement on where/how to run cloud builds - [GCB](https://cloud.google.com/cloud-build/) is what Kubernetes uses, and what CNCF has the most credits available for, so that seems reasonable
> 
>     * Secure community release signing process. Needed? (see [kubernetes/release#636](https://github.com/kubernetes/release/issues/636) for Kubernetes status)
> 
> 
> see also:
> 
>     * etcd-release-runbook (https://goo.gl/Gxwysq)

**Comment by serathius** [comment]
Duplicates https://github.com/etcd-io/etcd/issues/13980
