### ISSUE TITLE
Lease KeepAlive documentation ambiguity

### ISSUE THREAD

**Issue by ae6rt** [etcd-io/etcd#10170]
* I read [in this documentation paragraph](https://github.com/etcd-io/etcd/blob/master/clientv3/lease.go#L126-L129) that if the context provided to the Lease KeepAlive method is cancelled, the *LeaseKeepAliveResponse* channel will return nil.
* Yet, in the [next paragraph](https://github.com/etcd-io/etcd/blob/master/clientv3/lease.go#L131-L133) I read that if the context is cancelled, "the error" (what error?) is returned.  (Perhaps the *LeaseKeepAliveResponse* is then not nil)?

My motivation is to unit test code that needs to do something when the *LeaseKeepAliveResponse*  channel returns nil.  I am finding that cancelling the context is not inducing a nil value in the *LeaseKeepAliveResponse*.

I'm confused by these two paragraphs.  Would someone be kind enough to explain this?

**Comment by jpbetz** [comment]
@ae6rt I've attempted to clarify/correct the documentation with https://github.com/etcd-io/etcd/pull/10176.  Feel free to comment on that PR with aspects that are still confusing.

**Comment by jpbetz** [comment]
fixed by #10176
