### ISSUE TITLE
v3.3.10 tag reports as being Unverified

### ISSUE THREAD

**Issue by ejpearson** [etcd-io/etcd#10182]
The recently created v3.3.10 tag reports as being Unverified on the tags page.  The GPG Key ID still seems to be that of gyuho, though, if you compare it to the v3.3.9 tag:

https://github.com/etcd-io/etcd/tags

It still would be better to see Verified on the release tag as before.

**Comment by gyuho** [comment]
Hi,

I signed it with my GPG key that was created with my previous email.

In the next release, I will use the key that matches my current email.
