### ISSUE TITLE
Endpoint already exists for id

### ISSUE THREAD

**Issue by billyang** [etcd-io/etcd#10188]
Hi，use the client v3 

 to err: 
``` 
Endpoint already exists for id: 
```
when I see #10035，  Seems to be the same problem.  

Is there any other  way to fix it?
thank you.

**Comment by jpbetz** [comment]
Yes, will be proposing a PR shortly. See https://github.com/etcd-io/etcd/issues/10035 for tracking. Closing this as a duplicate.
