### ISSUE TITLE
listen unix abstract domain socket

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10186]
Now etcd not able to listen unix://@socket sockets because of bugs in go.etcd.io/etcd/pkg/types/urls.go

Firstly in case of unix:// or unixs:// schemes etcd always try to split host port and fail for names like unix://path because it needs port like unix://path:port but this is not looks right. split host port needed only for http/https schemes.

Second issue in net/url Parse function. It not able to parse right names like unix://@socket and @ symbol goes away. 

my ugly hack now is:
```go
diff --git a/vendor/go.etcd.io/etcd/pkg/types/urls.go b/vendor/go.etcd.io/etcd/pkg/types/urls.go
index 9e5d03ff6457..3e93f4c90e9f 100644
--- a/vendor/go.etcd.io/etcd/pkg/types/urls.go
+++ b/vendor/go.etcd.io/etcd/pkg/types/urls.go
@@ -39,12 +39,17 @@ func NewURLs(strs []string) (URLs, error) {
                if u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "unix" && u.Scheme != "unixs" {
                        return nil, fmt.Errorf("URL scheme must be http, https, unix, or unixs: %s", in)
                }
-         if _, _, err := net.SplitHostPort(u.Host); err != nil {
-                 return nil, fmt.Errorf(`URL address does not have the form "host:port": %s`, in)
+               if u.Scheme == "http" || u.Scheme == "https" {
+                       if _, _, err := net.SplitHostPort(u.Host); err != nil {
+                               return nil, fmt.Errorf(`URL address does not have the form "host:port": %s`, in)
+                       }
                }
                if u.Path != "" {
                        return nil, fmt.Errorf("URL must not contain a path: %s", in)
                }
+               if strings.Index(in, "://@") > 0 {
+                       u.Host = "@" + u.Host
+               }
                all[i] = *u
        }
        us := URLs(all)
```

**Comment by vtolstov** [comment]
after this change i'm able to listen unix abstract socket, but now i'm stuck at client. it can't connect because it strips @ sign from address. if you can helps me - i'l be happy =).
This eliminates needing internal api to communicate with etcd without network (not need to listen loopback)

**Comment by jpbetz** [comment]
`@` might be stripped out by the URL parsing library because it's a special delimiter used in the URL format for userinfo part, for example: `http://username:password@example.com`.

Out of curiosity, what happens if you encode `@` as `%40` in the URL? Does that make it through?

**Comment by jpbetz** [comment]
The change to only call `SplitHostPort()` for http or https looks correct to me. Would you be willing to send out a PR for that fix?

**Comment by hexfusion** [comment]
FWIW abstract domain socket support seems to be a long-standing issue for gRPC. https://github.com/grpc/grpc/issues/4677

**Comment by mheese** [comment]
because I run over this issue over and over: the outstanding issue (https://github.com/grpc/grpc/issues/4677) is basically on the C++ gRPC support (and languages which use that core library). With the go grpc implementation you can easily listen on an abstract unix socket, as well as connect to it.

**Comment by bradmwalker** [comment]
I opened a PR for https://github.com/etcd-io/etcd/issues/10186#issuecomment-431530698

**Comment by vtolstov** [comment]
thanks

**Comment by purpleidea** [comment]
hi bot! please stop pinging here
