### ISSUE TITLE
ability to paass or start embed etcd with own listener

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10191]
As i'm use embed etcd i want to listen by my self (mostly for support graceful server restart with https://godoc.org/github.com/cloudflare/tableflip or such solutions) but now i can't do that because i don't have ability to pass listener to etcd start function or via config.

**Comment by gyuho** [comment]
What's your use case for graceful server restart? You would still need handle data replay and peer-to-peer communication when one etcd node restarts.

**Comment by vtolstov** [comment]
hm.. yes.  ok. i'm graceful restart main app and simply start etcd embed server.

**Comment by wenjiaswe** [comment]
@vtolstov how is going? Just want to check if you have it figured out:)

**Comment by vtolstov** [comment]
etcd does not allow to receive precreated listener, so i can' graceful restart of etcd server.
