### ISSUE TITLE
Experiment Prow integration

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#10192]
We am experimenting Prow integration to automate github issue and PR management.

/cc @jpbetz @wenjiaswe @jingyih

**Comment by jingyih** [comment]
Haha I like this
/bark

**Comment by gyuho** [comment]
Yeah, Github API integration is done :)

Now
- [ ] Add OWNERS file
- [ ] Propose to use upstream Prow to migrate current CIs (couldn't get it to work with AWS because it only supports Google storage for log dumper).

**Comment by gyuho** [comment]
Disabling the plugin for a few hours to redeploy.

**Comment by gyuho** [comment]
Enabled.

/joke

**Comment by gyuho** [comment]
Disabled for now. Will revisit after Kubecon 2018.

**Comment by gyuho** [comment]
Talked with @cjwagner in person during KubeCon. We will wait until upstream Kubernetes community migrates its Prow cluster to a shared, public CNCF prow cluster.

**Comment by cjwagner** [comment]
We can get you started on the Kubernetes Prow cluster now if you like. That cluster is basically the CNCF prow cluster for now.

**Comment by fejta** [comment]
Yeah prow.k8s.io is the CNCF prow cluster

**Comment by gyuho** [comment]
@cjwagner @fejta Got it. Thanks! We will clean up current testing jobs, and start working on that.

/cc @jingyih @jpbetz @wenjiaswe
