### ISSUE TITLE
etcd 3.2+ timeout for locks

### ISSUE THREAD

**Issue by rc979** [etcd-io/etcd#10214]
How do you implement timeouts/ttl on the new etcd 3.2+ distributed locks? I see the announcement [here](https://coreos.com/blog/etcd-3.2-announcement) with some examples but they are all based on curl (I need Go) and don't see how to have the lock expire without implementing this on the client. I've also read about sessions and leases but it's not clear to me how to use these in this context. Thank you!

**Comment by gyuho** [comment]
I would start from https://godoc.org/github.com/etcd-io/etcd/clientv3/concurrency#Session

**Comment by rc979** [comment]
Thanks. Do you have an example maybe that shows how leases and sessions are
used? The sessions explanation on Godoc is pretty limited.
