### ISSUE TITLE
How to take backup/restore etcd cluster

### ISSUE THREAD

**Issue by shamimgeek** [etcd-io/etcd#10213]
Could you please refer some tool for reliable backup/restore of etcd cluster ?

**Comment by hexfusion** [comment]
> Could you please refer some tool for reliable backup/restore of etcd cluster ?

etcdctl? https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md#disaster-recovery

**Comment by shamimgeek** [comment]
@hexfusion : Thanks
