### ISSUE TITLE
Do we have feature to support sub-cluster?

### ISSUE THREAD

**Issue by rinsozheng** [etcd-io/etcd#10221]
Suppose we have below situation:

1. Deploy a set of distributed ETCD cluster nodes accross AZs in each Region (small cluster)
2. Deploy another set of distributed ETCD cluster nodes accross Regions (large cluster)

Can these two sets of ETCD clusters be cascaded? For example, the ETCD node of a small cluster is used as a lower-level service node of a large cluster.

Do we support such kind of topology? If no, is there any future plans for this?

**Comment by gyuho** [comment]
> Do we support such kind of topology?

No, but you can try CockroachDB or TiKV. They use Raft groups.

**Comment by rinsozheng** [comment]
Thanks!
