### ISSUE TITLE
Etcd deployment and read data best practices

### ISSUE THREAD

**Issue by wgliang** [etcd-io/etcd#10228]
I want to know where has some documentation on how to deploy best practices?

And is it possible to do the read and write separation of the etcd node, for example, I have three nodes: Node1, Node2 and Node3, I only write data through Node1, read data through Node2 and Node3.

/help

**Comment by ccl0326** [comment]
I dont think  read and write separation is a good idea for performance and throughput.

**Comment by hexfusion** [comment]
> I want to know where has some documentation on how to deploy best practices?

Hi @wgliang I think you should start by spending some time in our [Docs](https://github.com/etcd-io/etcd/tree/master/Documentation) then if you have specific questions please let us know.

> And is it possible to do the read and write separation of the etcd node, for example, I have three nodes: Node1, Node2 and Node3, I only write data through Node1, read data through Node2 and Node3.

etcd uses the raft consensus algorithm to maintain distributed state. For this to work effectively all client requests that require consensus are served by the leader node. In the case of a 3 node cluster where node 1 is the leader. If a write request is made to node 2 or 3 the request will be passed to node 1. Serialized read requests can be made against members but may be behind the quorum state so this trade off will require consideration.

ref: 
* [do-clients-have-to-send-requests-to-the-etcd-leader](https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#do-clients-have-to-send-requests-to-the-etcd-leader)
* [api_guarantees](https://github.com/etcd-io/etcd/blob/master/Documentation/learning/api_guarantees.md)
* [raft](https://raft.github.io/)

**Comment by hexfusion** [comment]
@wgliang let us know if you have any specific questions.
