### ISSUE TITLE
implementation a distributed lock problem

### ISSUE THREAD

**Issue by egmkang** [etcd-io/etcd#10224]
This is not a bug, this is a problem or a question.

is this a correct way to impl a distributed lock?

```
//lock
var lease = etcdClient.LeaseGrant(60, 0);    //60 is ttl, 0 is ID
var lockResponse = etcdClient.Lock(key, lease.ID);

//do something here

//unlock
etcdClient.Unlock(lockResponse);
```

thanks a lot for helping me.

**Comment by brk0v** [comment]
I think you should use this primitive: https://godoc.org/github.com/etcd-io/etcd/clientv3/concurrency#Mutex

**Comment by xiang90** [comment]
@egmkang Agree with @brk0v. So closing.

**Comment by egmkang** [comment]
@xiang90 @brk0v 
i'm not using golang, i'm using C#, there is not a distributed lock right now.

**Comment by xiang90** [comment]
@egmkang You can read etcd go client code, and implement in c#.

**Comment by egmkang** [comment]
@xiang90 so, i cannot use the grpc api?
https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/v3lockpb/v3lock.proto
```
service Lock {
  // Lock acquires a distributed shared lock on a given named lock.
  // On success, it will return a unique key that exists so long as the
  // lock is held by the caller. This key can be used in conjunction with
  // transactions to safely ensure updates to etcd only occur while holding
  // lock ownership. The lock is held until Unlock is called on the key or the
  // lease associate with the owner expires.
  rpc Lock(LockRequest) returns (LockResponse) {}
```

**Comment by AdiaLoveTrance** [comment]
> @xiang90 @brk0v so, i cannot use the grpc api? https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/v3lockpb/v3lock.proto
> 
> ```
> service Lock {
>   // Lock acquires a distributed shared lock on a given named lock.
>   // On success, it will return a unique key that exists so long as the
>   // lock is held by the caller. This key can be used in conjunction with
>   // transactions to safely ensure updates to etcd only occur while holding
>   // lock ownership. The lock is held until Unlock is called on the key or the
>   // lease associate with the owner expires.
>   rpc Lock(LockRequest) returns (LockResponse) {}
> ```

I use the [v3lock.proto](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/v3lockpb/v3lock.proto) with C++, and my thread always blocks even if no other thread hold the key lock, and I don't know why.

**Comment by AdiaLoveTrance** [comment]
@brk0v @xiang90 
Can anyone answer the question?
