### ISSUE TITLE
all keys disappear when a new host is added

### ISSUE THREAD

**Issue by babarismail** [etcd-io/etcd#10239]
We have a one node cluster which is running just fine. I want to add another node to it (I know 2 nodes aren't the recommended way but I will get to 3 nodes once I have successfully been able to add the second node).
As directed in the documentation, I called etcdctl member add:
etcdctl member add host2 http://10.253.170.154:2380
which spit out the configuration required in the second node that I added.

After that I was able to verify that the cluster state is healthy but all the keys that I added in the single node cluster are all gone. However, when I remove the newly added member and restart the service on the original node, I am able to see my data again.

My questions:
1. When I call member add, does it create a new cluster? If yes then what is the best way to make it join the existing cluster so that I see all the data.
2. How does member remove bring back my data.

There is something very basic that I probably don't understand here.

These are my configs:
original node:
ETCD_DATA_DIR=/var/lib/etcd
ETCD_NAME=host1
ETCD_ADVERTISE_CLIENT_URLS="http://10.253.170.146:2379,http://10.253.170.146:4001"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.253.170.146:2380"
ETCD_INITIAL_CLUSTER="host1=http://10.253.170.146:2380"
ETCD_INITIAL_CLUSTER_STATE=new

new node config updated after member add:
ETCD_DATA_DIR=/var/lib/etcd_fresh
ETCD_NAME=host2
ETCD_ADVERTISE_CLIENT_URLS="http://10.253.170.154:2379,http://10.253.170.154:4001"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_INITIAL_CLUSTER="host2=http://10.253.170.154:2380,host1=http://10.253.170.146:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

**Comment by hexfusion** [comment]
> 1. When I call member add, does it create a new cluster? If yes then what is the best way to make it join the existing cluster so that I see all the data.

@babarismail No as you noted in the case of `etcdctl` member add will add the new member url to etcd peerURLs and output the proper configs for you to start the new member to be part of the cluster. From what I can see you have done this correctly.

> 2 .How does member remove bring back my data.

Not sure I follow you here, what do the startup logs look like when 2nd node starts, can you attach them?

> > After that I was able to verify that the cluster state is healthy but all the keys that I added in the single node cluster are all gone.

I doesn't sound like the cluster is healthy what is the output of?

`ETCDCTL_API=3 etcdctl  --endpoints=http://10.253.170.154:2379,http://10.253.170.146:2379 endpoint status -w table`

**Comment by hexfusion** [comment]
Another thing to consider is you should make sure you are reading and writing from the same store. By default, etcdctl uses v2 API so if you wrote to v2 then tried to read v3 (ETCDCTL_API=3 etcdctl get foo) it would appear your data was missing.

**Comment by babarismail** [comment]
@hexfusion through journalctl I see a lot of these. Any ideas?
Nov 06 00:14:19 host2 start-etcd[94030]: 2018/11/6 00:14:19 rafthttp: streaming request ignored (cluster ID mismatch got d71c
Nov 06 00:14:19 host2 start-etcd[94030]: 2018/11/6 00:14:19 rafthttp: streaming request ignored (cluster ID mismatch got d71c
Nov 06 00:14:19 host2 start-etcd[94030]: 2018/11/6 00:14:19 rafthttp: request received was ignored (cluster ID mismatch got d
Nov 06 00:14:19 host2 start-etcd[94030]: 2018/11/6 00:14:19 rafthttp: request received was ignored (cluster ID mismatch got d
N

**Comment by hexfusion** [comment]
> I understand the behavior now but don't know how to fix it. The keys from the node that is just joining are getting selected instead of the node that is already in there.

@babarismail I assume these are test nodes can you stop etcd on each node delete the datadirs and start over? When the nodes are running can you show the output of

`ETCDCTL_API=3 etcdctl --endpoints=http://10.253.170.154:2379,http://10.253.170.146:2379 endpoint status -w table`

I can not reproduce your issue so I need more information, logs, commands tried etc to help you.

**Comment by babarismail** [comment]
@hexfusion 
These are not test nodes and our openstack services depend on the data in them. In our initial design, we just had 1 node which wasn't a smart idea to begin with. My task is to add resilience into the cluster which is why I am adding more nodes to it.

It looks like that if a node (node2) with existing etcd data is asked to join a new cluster with one node (node1), the latest data is used in the cluster and propagated to both nodes. I verified that by adding a new key in node1 and saw that node1's data took precedence in the new cluster.

Can you confirm if this is true or if that is just happening by accident?

I have attached these logs for Node 2:
Nov 07 22:15:42 host2 systemd[1]: Stopping Etcd...
Nov 07 22:15:42 host2 start-etcd[127051]: 2018/11/7 22:15:42 osutil: received terminated signal, shutting down...
Nov 07 22:15:42 host2 systemd[1]: Stopped Etcd.
Nov 07 22:17:19 host2 systemd[1]: Started Etcd.
Nov 07 22:17:19 host2 systemd[1]: Starting Etcd...
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: name = host2
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: heartbeat = 100ms
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: election = 1000ms
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: snapshot count = 10000
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: starting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae became follower at term 0
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: newRaft 4558565fd2ab01ae [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae became follower at term 1
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: starting server... [version: 2.1.1, cluster version: to_be_decided]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 rafthttp: the connection with cdd765cb0d128a4a became active
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae [term: 1] received a MsgHeartbeat message with higher term from cdd765cb0d128a4a [term: 177]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: raft.node: 4558565fd2ab01ae elected leader cdd765cb0d128a4a at term 177
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 1720721, term: 177]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: log [committed=0, applied=0, unstable.offset=1, len(unstable.Entries)=0] starts to restore snapshot [index: 1720721, term: 177]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae restored progress of cdd765cb0d128a4a [next = 1720722, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 raft: 4558565fd2ab01ae [commit: 0] restored snapshot [index: 1720721, term: 177]
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: raft applied incoming snapshot at index 1720721
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: recovered from incoming snapshot at index 1720721
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 rafthttp: the connection with cdd765cb0d128a4a became active
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: published {Name:host2 ClientURLs:[http://10.253.170.154:2379 http://10.253.170.154:4001]} to cluster d71c9bf9f1b065fe
Nov 07 22:23:08 host2 start-etcd[4643]: 2018/11/7 22:23:08 rafthttp: the connection with cdd765cb0d128a4a became inactive
Nov 07 22:23:08 host2 start-etcd[4643]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:08 host2 start-etcd[4643]: 2018/11/7 22:23:08 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:08 host2 start-etcd[4643]: 2018/11/7 22:23:08 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:08 host2 start-etcd[4643]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:08 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:08 host2 systemd[1]: Started Etcd.
Nov 07 22:23:08 host2 systemd[1]: Starting Etcd...
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdmain: the server is already initialized as member before, starting as etcd member...
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: recovered store from snapshot at index 1720721
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: name = host2
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: heartbeat = 100ms
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: election = 1000ms
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: snapshot count = 10000
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: loaded cluster information from store: <nil>
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: restarting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe at commit index 1722152
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 raft: newRaft 4558565fd2ab01ae [peers: [cdd765cb0d128a4a], term: 177, commit: 1722152, applied: 1720721, lastindex: 1722152, lastterm: 177]
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: starting server... [version: 2.1.1, cluster version: 2.1.0]
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:08 host2 start-etcd[14835]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:08 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:08 host2 systemd[1]: Started Etcd.
Nov 07 22:23:08 host2 systemd[1]: Starting Etcd...
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdmain: the server is already initialized as member before, starting as etcd member...
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: recovered store from snapshot at index 1720721
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: name = host2
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: heartbeat = 100ms
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: election = 1000ms
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: snapshot count = 10000
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: loaded cluster information from store: <nil>
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: restarting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe at commit index 1722152
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 raft: newRaft 4558565fd2ab01ae [peers: [cdd765cb0d128a4a], term: 177, commit: 1722152, applied: 1720721, lastindex: 1722152, lastterm: 177]
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: starting server... [version: 2.1.1, cluster version: 2.1.0]
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:08 host2 start-etcd[14843]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:08 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:08 host2 systemd[1]: Started Etcd.
Nov 07 22:23:08 host2 systemd[1]: Starting Etcd...
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdmain: the server is already initialized as member before, starting as etcd member...
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: recovered store from snapshot at index 1720721
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: name = host2
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: heartbeat = 100ms
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: election = 1000ms
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: snapshot count = 10000
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: loaded cluster information from store: <nil>
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: restarting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe at commit index 1722152
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 raft: newRaft 4558565fd2ab01ae [peers: [cdd765cb0d128a4a], term: 177, commit: 1722152, applied: 1720721, lastindex: 1722152, lastterm: 177]
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: starting server... [version: 2.1.1, cluster version: 2.1.0]
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:08 host2 start-etcd[14850]: 2018/11/7 22:23:08 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:09 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:09 host2 systemd[1]: Started Etcd.
Nov 07 22:23:09 host2 systemd[1]: Starting Etcd...
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdmain: the server is already initialized as member before, starting as etcd member...
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: recovered store from snapshot at index 1720721
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: name = host2
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: heartbeat = 100ms
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: election = 1000ms
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: snapshot count = 10000
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: loaded cluster information from store: <nil>
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: restarting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe at commit index 1722152
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 raft: newRaft 4558565fd2ab01ae [peers: [cdd765cb0d128a4a], term: 177, commit: 1722152, applied: 1720721, lastindex: 1722152, lastterm: 177]
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: starting server... [version: 2.1.1, cluster version: 2.1.0]
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:09 host2 start-etcd[14857]: 2018/11/7 22:23:09 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:09 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:09 host2 systemd[1]: Started Etcd.
Nov 07 22:23:09 host2 systemd[1]: Starting Etcd...
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdmain: the server is already initialized as member before, starting as etcd member...
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdmain: listening for peers on http://0.0.0.0:2380
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdmain: listening for client requests on http://0.0.0.0:2379
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdmain: listening for client requests on http://0.0.0.0:4001
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: recovered store from snapshot at index 1720721
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: name = host2
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: data dir = /var/lib/etcd_Nov7_6
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: member dir = /var/lib/etcd_Nov7_6/member
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: heartbeat = 100ms
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: election = 1000ms
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: snapshot count = 10000
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: advertise client URLs = http://10.253.170.154:2379,http://10.253.170.154:4001
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: loaded cluster information from store: <nil>
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: restarting member 4558565fd2ab01ae in cluster d71c9bf9f1b065fe at commit index 1722152
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 raft: 4558565fd2ab01ae became follower at term 177
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 raft: newRaft 4558565fd2ab01ae [peers: [cdd765cb0d128a4a], term: 177, commit: 1722152, applied: 1720721, lastindex: 1722152, lastterm: 177]
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: starting server... [version: 2.1.1, cluster version: 2.1.0]
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: added local member 4558565fd2ab01ae [http://10.253.170.154:2380] to cluster d71c9bf9f1b065fe
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 rafthttp: failed to dial cdd765cb0d128a4a on stream MsgApp v2 (the member has been permanently removed from the cluster)
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: the member has been permanently removed from the cluster
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 etcdserver: the data-dir used by this member must be removed.
Nov 07 22:23:09 host2 start-etcd[14864]: 2018/11/7 22:23:09 rafthttp: failed to dial cdd765cb0d128a4a on stream Message (read tcp 10.253.170.146:2380: use of closed network connection)
Nov 07 22:23:09 host2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Nov 07 22:23:09 host2 systemd[1]: start request repeated too quickly for etcd.service
Nov 07 22:23:09 host2 systemd[1]: Failed to start Etcd.
Nov 07 22:23:09 host2 systemd[1]: Unit etcd.service entered failed state.
Nov 07 22:23:09 host2 systemd[1]: etcd.service failed.

**Comment by hexfusion** [comment]
> Nov 07 22:17:19 host2 start-etcd[4643]: 2018/11/7 22:17:19 etcdserver: starting server... [version: 2.1.1, cluster version: to_be_decided]

@babarismail host2 is running 2.1.1? This is no longer supported is host1 the same?

**Comment by hexfusion** [comment]
> It looks like that if a node (node2) with existing etcd data is asked to join a new cluster with one node (node1), the latest data is used in the cluster and propagated to both nodes. I verified that by adding a new key in node1 and saw that node1's data took precedence in the new cluster.

> Can you confirm if this is true or if that is just happening by accident?

Lets assume this is v3 cluster new node should not reuse data-dir, remove data-dir on host2 and start over. If this is v2 cluster please upgrade.

**Comment by babarismail** [comment]
@hexfusion host1 and host2 are indeed v2. We will try to upgrade as soon as we can.

I think we can resolve this issue as I now understand the behavior. 2 things I need to do:
1. remove all data from the node2
2. upgrade to v3

**Comment by hexfusion** [comment]
If you need help on upgrade let us know.
