### ISSUE TITLE
Change the Storage size limit | etcd:v2.3.8 |flag provided but not defined: -quota-backend-bytes

### ISSUE THREAD

**Issue by jyothish-git** [etcd-io/etcd#10236]
Hi Team,

On my Kubernetes environment, I have two etcd cluster running one is from etcd:v3.2.18 and the other from etcd:v2.3.8. Both deployed using  kubernetes manifest file and both are up and running. I like to change the default storage size limit from 2GB to 4GB, So added  --quota-backend-bytes flag in the config file. It worked on etcd 3.2 but on etcd 2.3 the docker container failed with the error
 
"flag provided but not defined: -quota-backend-bytes"

etcd:v3.2.18 manifest file section
==
 command:
    - /usr/local/bin/etcd
    args:
    - --name=etcd1
    - --data-dir=/etcd-data
    - --advertise-client-urls=http://0.0.0.0:9090
    - --listen-client-urls=http://0.0.0.0:9090
    - --listen-peer-urls=http://0.0.0.0:9092
    - --initial-advertise-peer-urls=http://1.2.3.4:9092
    - --initial-cluster=etcd1=http://1.2.3.4:9092
    - --initial-cluster-token=etcd-token
    - --quota-backend-bytes=4294967296

etcd:v2.3.8 manifest file section
==
    command:
    - /etcd
    args:
    - --name=etcd1
    - --data-dir=/etcd-data
    - --advertise-client-urls=http://0.0.0.0:9094
    - --listen-client-urls=http://0.0.0.0:9094
    - --listen-peer-urls=http://0.0.0.0:9096
    - --initial-advertise-peer-urls=http://1.2.3.4:9096
    - --initial-cluster=no=http://1.2.3.4:9096
    - --initial-cluster-token=etcd-token
    - --quota-backend-bytes=4294967296

Is it possible to change the default storage limit in old version ? Can somebody guide me how to overcome this issue and increase the storage size on etcd 2.3 ?

Thanks,
jyothish

**Comment by hexfusion** [comment]
> I like to change the default storage size limit from 2GB to 4GB, So added --quota-backend-bytes flag in the config file. It worked on etcd 3.2 but on etcd 2.3 the docker container failed with the error

Hi @jyothish-git first of all v2 is no longer supported please consider migrating to v3 for futrure support. But to answer your question th `--quota-backend-bytes` flag was added to v3 and is not available in v2 

ref: https://github.com/etcd-io/etcd/pull/4901

> Is it possible to change the default storage limit in old version ? Can somebody guide me how to overcome this issue and increase the storage size on etcd 2.3 ?

My understanding is this is not possible

ref: https://github.com/etcd-io/etcd/issues/8021

**Comment by jyothish-git** [comment]
Thank you @hexfusion for the clarification.
I'll move to v3 soon.
