### ISSUE TITLE
etcds-conf: a TLS validation and configuration tool for etcd

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#10232]
Problems with configuring TLS for etcd are a very common issue for users. For example, depending on the etcd server version or if the cluster will use IPs vs domain names to define members. These decisions can affect the TLS cert requirements for proper operation resulting in confusion.

I would like to propose a new tool `etcds-conf` that will accept v3 server configurations. Based on those configs the tool will validate the certs.

Once we stabalize the tool the long term goal would be adding the logic/features to etcd/etcdctl directly. Any input is welcome.

Initial Features:
* **x509 validation**: based on the configuration flags and the TLS cert passed to the tool validate if the cert has necessary IPs or domains in SAN. If not provide human readable errors to possible reasons cert SAN is not correct for the existing config.
* **etcd TLS template**: if only `--endpoints` flag is passed etcds-conf it will output a basic etcd boilerplate config to support TLS.

Future Features:
* **cfssl config generation**: based on config `etcds-conf` will output JSON configs required to generate TLS certs and CA to use with etcd.

**Comment by jingyih** [comment]
cc @wenjiaswe
