### ISSUE TITLE
Disable leader election

### ISSUE THREAD

**Issue by fritchie** [etcd-io/etcd#10237]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

This is a feature request.

It would be nice to be able to disable etcd leader election on the fly. This could come in handy during kubernetes upgrades, network flakiness, etc...

**Comment by gyuho** [comment]
@fritchie Can you tell us more about your use case? Are you concerned about etcd availability? Leader election can be also the aftereffect of network faults.

**Comment by hexfusion** [comment]
@fritchie kind ping
