### ISSUE TITLE
Unexpected ":" in connection url

### ISSUE THREAD

**Issue by hoobean1996** [etcd-io/etcd#10249]
# Details 
etcd Version: 3.3.10
Git SHA: GitNotFound
Go Version: go1.11.1
Go OS/Arch: darwin/amd64

# Problem (unexpect colons)
![image](https://user-images.githubusercontent.com/44892834/48251570-0d2d2300-e43d-11e8-8fef-9551ec1b4faa.png)
![image](https://user-images.githubusercontent.com/44892834/48251583-18804e80-e43d-11e8-89e5-8fa8fcaa9dd9.png)

**Comment by hexfusion** [comment]
> etcd Version: 3.3.10
Git SHA: GitNotFound
Go Version: go1.11.1
Go OS/Arch: darwin/amd64

@hoobean1996 I assume you are using release assets to test? https://github.com/etcd-io/etcd/releases

Could you outline full steps to reproduce along with your go version?.

**Comment by hoobean1996** [comment]
> > etcd Version: 3.3.10
> > Git SHA: GitNotFound
> > Go Version: go1.11.1
> > Go OS/Arch: darwin/amd64
> 
> @hoobean1996 I assume you are using release assets to test? https://github.com/etcd-io/etcd/releases
> 
> Could you outline full steps to reproduce along with your go version?.

Thanks
I Used 'brew install etcd' to install etcd ,and the details are 
`
etcd Version: 3.3.10
Git SHA: GitNotFound
Go Version: go1.11.1
Go OS/Arch: darwin/amd64
`
in my Go program, I want to client etcd by etcd/ClientV3,
if I use '127.0.0.1:2378' without http://, it is ok, no unexpected ":".
if I use `http://127.0.0.1:2379`,the test code will panic with unexpect ":" .

Sample:
![image](https://user-images.githubusercontent.com/44892834/48322115-dc2d3800-e660-11e8-9956-9ae9f702bc0a.png)
![image](https://user-images.githubusercontent.com/44892834/48322135-f9620680-e660-11e8-90c9-e959c36a3adb.png)

I follow the docs  to write test demo,but it failed
 I miss any configuration ? thanks

**Comment by hoobean1996** [comment]
I use HTTP to work with etcd server, but the etcdClient still not worked

**Comment by hexfusion** [comment]
@hoobean1996 I cannot reproduce, here are my steps with a slightly modified example from GoDoc https://godoc.org/go.etcd.io/etcd/clientv3#example-KV--Put

```
brew install dep
mkdir $GOPATH/src/hexfusion/clientv3_demo
cd !$
dep init
go run .

put sample_key success!
cluster_id:14841639068965178418 member_id:10276657743932975437 revision:12 raft_term:3
```

```
package main

import (
        "context"
        "fmt"
        "log"
        "time"

        "go.etcd.io/etcd/clientv3"
)

func main() {
        requestTimeout := 5 * time.Second
        cli, err := clientv3.New(clientv3.Config{
                Endpoints:   []string{"http://127.0.0.1:2379"},
                DialTimeout: 5 * time.Second,
        })
        if err != nil {
                log.Fatal(err)
        }
        defer cli.Close()

        key := "sample_key"
        value := "sample_value"
        ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
        resp, rerr := cli.Put(ctx, key, value)
        cancel()
        if rerr != nil {
                log.Fatal(rerr)
        }
        fmt.Printf("put %s success!\n%v\n", key, resp.Header)

}
```
dep vendors reasonable versions of dependencies which might of been your issue?

**Comment by hoobean1996** [comment]
Thank you very much !
