### ISSUE TITLE
can not get gcr.io/etcd-development/etcd:v3.2.25

### ISSUE THREAD

**Issue by 899** [etcd-io/etcd#10241]
docker pull gcr.io/etcd-development/etcd:v3.2.25
error:
Pulling repository gcr.io/etcd-development/etcd
unauthorized: authentication required

**Comment by gyuho** [comment]
Hmm, @jpbetz could you check the container image permission?

**Comment by jpbetz** [comment]
Fixed. Sorry, we had some permission problems as part of the org changes related to the move to etcd-io. All 3.2.25 and 3.1.20 container images should no be available.  Please reopen if you encounter any issues.

**Comment by gyuho** [comment]
Confirmed that this works now. Thanks!
