### ISSUE TITLE
cannot use google.golang.org/grpc/naming

### ISSUE THREAD

**Issue by zdywjj** [etcd-io/etcd#10247]
cannot use "google.golang.org/grpc/naming".Update literal (type "google.golang.org/grpc/naming".Update) as type "go.etcd.io/etcd/vendor/google.golang.org/grpc/naming".Update in argument to r.Update

**Comment by hexfusion** [comment]
@zdywjj Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

To help you we need details such as.
* etcd version:
* go version:
* OS:
* Actions to reproduce:

**Comment by hexfusion** [comment]
@zdywjj ping any more details here?

**Comment by hexfusion** [comment]
@zdywjj if you can provide details feel free to add and we can reopen. Without details, we can not help.
