### ISSUE TITLE
etcd 3.2+ snapshot count reduction

### ISSUE THREAD

**Issue by maddop** [etcd-io/etcd#10240]
Currently using 3 VM's running

RHEL7.5
OKD 1.5
ETCD 3.2.22
32GB memory
Flash SSD 

Having issues with etcd 3.2 cluster. Getting OOM and etcd members are killed.
They restart and then rejoin but this continues to reoccur. Occasionally they'll fail to rejoin the cluster, requiring to be manually cleared down and re-added.  

One possible solution is reducing snapshot threshold to 10k from 100k but wanted to understand if their is anything negative to consider with such an action. 

Also the dataset is so large, it is not possible to list it using 

`ls -r`
`error: context deadline exceeded`

I'm wondering if anyone has seen similar issues and if the snapshot threshold reduction is a good idea?
or am i on the complete wrong track?

**Comment by gyuho** [comment]
v3.2 default snapshot count was changed to 100k to decrease the snapshot sends to slow followers, but you may see memory spikes because it holds raft entries for longer. It's a tradeoff between less spikey memory usage and less snapshot sends.

**Comment by maddop** [comment]
thanks for the clarification. 
Reduction to snapshot applied, now running at 10k and seems to have a positive impact.
