### ISSUE TITLE
tools/benchmark is gone from v3.3 releases

### ISSUE THREAD

**Issue by mrueg** [etcd-io/etcd#10245]
https://github.com/etcd-io/etcd/commit/074e4177707f4daead816c108a06980d77d0aad0 this removed it in release-3.3 and it never got added back since v3.3.3 

Can you readd it?

**Comment by hexfusion** [comment]
> 074e417 this removed it in release-3.3 and it never got added back since v3.3.3
Can you readd it?

Maybe @gyuho can let us know his reason for removal.
