### ISSUE TITLE
Hybrid Bare Metal & Openstack etcd Cluster

### ISSUE THREAD

**Issue by vgoldani** [etcd-io/etcd#10252]
i've working on this Hybrid Bare Metal & Openstack cluster without success.

Heres my topology:

![topologia](https://user-images.githubusercontent.com/7671373/48296959-c272d180-e463-11e8-9d6f-efcfebe0ceba.png)

Im running a Openstack on premise cloud with Ubuntu instances and one physical server also with Ubuntu, both connected with a router.

Server:
Name: M1
IP: 192.168.89.151
OS: Ubuntu 16.04.5
etcd Version: 3.3.10

etcd.service

`
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
Restart=always
RestartSec=5s
LimitNOFILE=40000
TimeoutStartSec=0

ExecStart=/usr/local/bin/etcd \
  --name m1 \
  --cert-file=/etc/kubernetes/pki/etcd/server.pem \
  --key-file=/etc/kubernetes/pki/etcd/server-key.pem \
  --client-cert-auth \
  --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
  --peer-cert-file=/etc/kubernetes/pki/etcd/peer.pem \
  --peer-key-file=/etc/kubernetes/pki/etcd/peer-key.pem \
  --peer-client-cert-auth \
  --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
  --initial-advertise-peer-urls http://192.168.89.151:2380 \
  --listen-peer-urls http://192.168.89.151:2380 \
  --listen-client-urls http://192.168.89.151:2379,http://127.0.0.1:2379,http://192.168.89.151:4001 \
  --advertise-client-urls http://192.168.89.151:2379,http://192.168.89.151:4001 \
  --initial-cluster-token prod-kubernetes \
  --initial-cluster m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380 \
  --initial-cluster-state new \
  --data-dir=/var/lib/etcd

[Install]
WantedBy=multi-user.target

`

Openstack Instance:
Name: M2
Private IP: 172.168.89.26
Float:  192.168.89.152
OS: Ubuntu 16.04.5
etcd Version: 3.3.10

etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
Restart=always
RestartSec=5s
LimitNOFILE=40000
TimeoutStartSec=0

ExecStart=/usr/local/bin/etcd \
  --name m2 \
  --cert-file=/etc/kubernetes/pki/etcd/server.pem \
  --key-file=/etc/kubernetes/pki/etcd/server-key.pem \
  --client-cert-auth \
  --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
  --peer-cert-file=/etc/kubernetes/pki/etcd/peer.pem \
  --peer-key-file=/etc/kubernetes/pki/etcd/peer-key.pem \
  --peer-client-cert-auth \
  --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
  --initial-advertise-peer-urls http://172.168.89.26:2380 \
  --listen-peer-urls http://172.168.89.26:2380 \
  --listen-client-urls http://172.168.89.26:2379,http://127.0.0.1:2379,http://172.168.89.26:4001 \
  --advertise-client-urls http://172.168.89.26:2379 \
  --initial-cluster-token prod-kubernetes \
  --initial-cluster m1=http://192.168.89.151:2380,m2=http://172.168.89.26:2380 \
  --initial-cluster-state new \
  --data-dir=/var/lib/etcd

[Install]
WantedBy=multi-user.target

And im getting this:

request sent was ignored (cluster ID mismatch: peer[bfefd52b2f32ced2]=e668b9f2753c9e74, local=1d061d5af878937d

request cluster ID mismatch (got e668b9f2753c9e74 want 1d061d5af878937d)

Thanks in advance

**Comment by hexfusion** [comment]
> request cluster ID mismatch (got e668b9f2753c9e74 want 1d061d5af878937d)

@vgoldani what happens if you backup the data-dirs for each node moving them out of the way and boostrap the cluster again?

`mv /var/lib/etcd /var/lib/etcd.backup`

Generally, this type of error points to a misconfiguration during the initial bootstrap process. For example, if m2 was started as a single node cluster (e668b9f2753c9e74) then you adjusted the configs as they are above attempting to make it a member of cluster (1d061d5af878937d). Although the configs are correct by appearance the stored configuration is not. Removing the data-dir will reset this, lets start here.

**Comment by vgoldani** [comment]
I've doing some tests but instead of create the backup, i do some rm /var/lib/etcd. Heres the scenario:

M1
1. Run rm /var/lib/etcd.
2. Run sudo systemctl daemon-reload && sudo systemctl enable etcd  && sudo systemctl start etcd
3.- Log show this:
![m1](https://user-images.githubusercontent.com/7671373/48297328-f9001a80-e46a-11e8-9792-ae4177ae6d04.png)

Then i move to M2
4.- Run rm /var/lib/etcd.
5.-  Run sudo systemctl daemon-reload && sudo systemctl enable etcd  && sudo systemctl start etcd
6.- Log show this:
![m2](https://user-images.githubusercontent.com/7671373/48297343-34024e00-e46b-11e8-98c6-2fd9f1e27ae7.png)

Maybe im missing something the way i start the cluster?

Should i try to mv instead of delete /var/lib/etcd ?

**Comment by hexfusion** [comment]
> Run rm /var/lib/etcd. 
Should i try to mv instead of delete /var/lib/etcd

You mean `rm -rf /var/lib/etcd` right? /var/lib/etcd is a directory rm would have no effect. I only said to `mv` so you retained a copy of the original data-dir if this is just a test cluster then that is not nessisary and full delete is fine.

>Maybe im missing something the way i start the cluster?

This appears to be ok but we need to see the complete etcd startup logs to be sure. ssh into these instances and get the log output in txt form, images are not pratical for debugging. Finally please verify that that m1 and m2 can communicate with each other over tcp ports 2379,2380 and no Ubuntu or openstack firewalls  are blocking traffic.

**Comment by vgoldani** [comment]
> > Run rm /var/lib/etcd.
> > Should i try to mv instead of delete /var/lib/etcd
> 
> You mean `rm -rf /var/lib/etcd` right? /var/lib/etcd is a directory rm would have no effect. I only said to `mv` so you retained a copy of the original data-dir if this is just a test cluster then that is not nessisary and full delete is fine.
> 
> > Maybe im missing something the way i start the cluster?
> 
> This appears to be ok but we need to see the complete etcd startup logs to be sure. ssh into these instances and get the log output in txt form, images are not pratical for debugging. Finally please verify that that m1 and m2 can communicate with each other over tcp ports 2379,2380 and no Ubuntu or openstack firewalls are blocking traffic.

@hexfusion My bad, i meant full delete with -rf.

[m1.txt](https://github.com/etcd-io/etcd/files/2568584/m1.txt)
[m2.txt](https://github.com/etcd-io/etcd/files/2568585/m2.txt)

Looking at the logs, seems like each node is starting with a different cluster ID but i cant find anything more :(

**Comment by hexfusion** [comment]
Ok let’s cleanup these configs why are you switching between 192 and 172 networks for peer and client? If you want to do that assuming it is possible the configs need to be properly set. Notice the difference between m1 and m2 member list? These should be the same.

Nov 10 10:54:54 kubernetes-m1 etcd[1930]: initial cluster = m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380

Nov 10 10:55:22 kubernetes-m2 etcd[1354]: initial cluster = m1=http://192.168.89.151:2380,m2=http://172.168.89.26:2380

**Comment by vgoldani** [comment]
> Ok let’s cleanup these configs why are you switching between 192 and 172 networks for peer and client? If you want to do that assuming it is possible the configs need to be properly set. Notice the difference between m1 and m2 member list? These should be the same. Nov 10 10:54:54 kubernetes-m1 etcd[1930]: initial cluster = m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380 Nov 10 10:55:22 kubernetes-m2 etcd[1354]: initial cluster = m1=http://192.168.89.151:2380,m2=http://172.168.89.26:2380
> […](#)
> On Nov 10, 2018, at 12:12 PM, Victor Goldaracena ***@***.***> wrote: Run rm /var/lib/etcd. Should i try to mv instead of delete /var/lib/etcd You mean rm -rf /var/lib/etcd right? /var/lib/etcd is a directory rm would have no effect. I only said to mv so you retained a copy of the original data-dir if this is just a test cluster then that is not nessisary and full delete is fine. Maybe im missing something the way i start the cluster? This appears to be ok but we need to see the complete etcd startup logs to be sure. ssh into these instances and get the log output in txt form, images are not pratical for debugging. Finally please verify that that m1 and m2 can communicate with each other over tcp ports 2379,2380 and no Ubuntu or openstack firewalls are blocking traffic. @hexfusion My bad, i meant full delete with -rf. m1.txt m2.txt Looking at the logs, seems like each node is starting with a different cluster ID but i cant find anything more :( — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

The 172.168.89.26 is unreacheable from outside of the Openstack. its a private network for openstack managment and its assigned directly to the enp3s0 interface when the instance is created. Thats why i need to use the floating IP. Should i try doing something like this?:

m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380, m2=http://172.168.89.26:2380
m2=http://192.168.89.151:2380,m2=http://192.168.89.152:2380, m2=http://172.168.89.26:2380

**Comment by hexfusion** [comment]
@vgoldani any progress?

**Comment by vgoldani** [comment]
> @vgoldani any progress?

Not at all, but trying a couple of things. First of all: We are not following this rules. Maybe forgot to mention it, but its a private openstack in our datacenter. We don't follow the IP rules of the IETF.

A couple of things i tried: Setting a static route on every node (ip route add ...) didnt work how i expected, and using OpenVPN.

Starting to think that it wont work how i wanted. :(

> > The 172.168.89.26 is unreacheable from outside of the Openstack. its a private network for openstack managment and its assigned directly to the enp3s0 interface when the instance is created.
> 
> The 172.168.89.26 is a public IP, 192.168 is reserved as private https://tools.ietf.org/html/rfc3330#section-2.
> 
> > Should i try doing something like this?:
> > m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380, m2=http://172.168.89.26:2380
> > m2=http://192.168.89.151:2380,m2=http://192.168.89.152:2380, m2=http://172.168.89.26:2380
> 
> I think that the best route would be to try something like below and see if you can get the nodes to cluster. Once you get that to work make sure to add back the TLS flags and set all URLs to https. Good luck!
> 
> ### m1
> ```
> --name m1 
> --initial-advertise-peer-urls http://192.168.89.151:2380 
> --listen-peer-urls http://192.168.89.151:2380 
> --listen-client-urls http://192.168.89.151:2379,http://192.168.89.151:4001,http://127.0.0.1:2379 
> --advertise-client-urls http://192.168.89.151:2379
> --initial-cluster-token prod-kubernetes 
> --initial-cluster m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380
> --initial-cluster-state new 
> --data-dir=/var/lib/etcd
> ```
> ### m2
> ```
> --name m2
> --initial-advertise-peer-urls http://192.168.89.152:2380 
> --listen-peer-urls http://192.168.89.152:2380 
> --listen-client-urls http://192.168.89.152:2379,http://192.168.89.152:4001,http://127.0.0.1:2379 
> --advertise-client-urls http://192.168.89.152:2379
> --initial-cluster-token prod-kubernetes 
> --initial-cluster m1=http://192.168.89.151:2380,m2=http://192.168.89.152:2380
> --initial-cluster-state new 
> --data-dir=/var/lib/etcd
> ```
> Finally please consider 3 nodes as having 2 adds no fault tolerance over a single node
> 
> ref: [docs: what-is-failure-tolerance](https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-is-failure-tolerance)

**Comment by hexfusion** [comment]
> Not at all, but trying a couple of things. First of all: We are not following this rules. Maybe forgot to mention it, but its a private openstack in our datacenter. We don't follow the IP rules of the IETF.

@vgoldani this seems like a networking issue vs etcd issue. Try reviewing https://github.com/etcd-io/etcd/issues/10274 which shows a user with a working cluster on openstack. If you get a specific issue with etcd please feel free to add more details here or open a new issue
