### ISSUE TITLE
etcd community meetup at KubeCon

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#10260]
Hi all, we are trying to get folks together from the etcd community during KubeCon in Seattle. We are still working on the details but if you are interested please signup below so we can coordinate. If you have ideas on where to meet or a good place for dinner, please share as well, thanks!

https://www.meetup.com/etcd-io/

**Comment by hexfusion** [comment]
Hey folks KubeCon is next week and we have a Meetup scheduled for Tuesday 12/11 at 6:30pm. The location is short walk (4min) from the conference and a chance to meet community members in person. We have a great menu of goodies which will be served so no excuses!

https://www.meetup.com/etcd-io/events/256851680/

**Comment by gyuho** [comment]
![etcd-meetup-20181211-1](https://user-images.githubusercontent.com/6799218/50071786-be834f00-0187-11e9-8a52-c53342702cfc.jpeg)
![etcd-meetup-20181211-2](https://user-images.githubusercontent.com/6799218/50071787-bf1be580-0187-11e9-8859-2302332f8186.jpeg)
![etcd-meetup-20181211-3](https://user-images.githubusercontent.com/6799218/50071788-bf1be580-0187-11e9-82b3-d1bbedf62329.jpeg)

It was great to see you all. Thanks for organizing this @wenjiaswe and @hexfusion !
