### ISSUE TITLE
Procfile error (and command line error too)

### ISSUE THREAD

**Issue by JJ** [etcd-io/etcd#10272]
The command line 

```
/usr/local/bin/etcd --name infra1 --listen-client-urls http://127.0.0.1:2379 --advertise-client-urls http://127.0.0.1:2379 --listen-peer-urls http://127.0.0.1:12380 --initial-advertise-peer-urls http://127.0.0.1:12380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380' --initial-cluster-state new --enable-pprof --logger=zap --log-outputs=stderr
```

in the procfile issues this error:

```
flag provided but not defined: -logger
```

Is the Procfile out of date?

**Comment by hexfusion** [comment]
@JJ what is `etcd --version` output? Procfile in master branch is 3.4, since this is not yet released you could checkout the version of etcd you are running.

```
cd $etcd_repo
git checkout v3.3.10
..
```
or if you wanted to test against master
```
./build
# leave etcd path as in file `bin/etcd`
goreman ...
```

**Comment by JJ** [comment]
El lun., 19 nov. 2018 a las 22:51, Sam Batschelet (<notifications@github.com>)
escribió:

> @JJ <https://github.com/JJ> what is etcd --version output? Procfile in
> master branch is 3.4, since this is not yet released you could checkout the
> version of etcd you are running.
>

 etcd Version: 3.3.10
Git SHA: 27fc7e2
Go Version: go1.10.4
Go OS/Arch: linux/amd64

**Comment by hexfusion** [comment]
@JJ ok so this should work to build etcd and create 3 node cluster.
```
cd $etcd_repo
git checkout v3.3.10
./build
goreman start
```
Let me know if you run into any trouble.

**Comment by JJ** [comment]
OK, thanks.
