### ISSUE TITLE
ETCD is too sensitive to disk latency

### ISSUE THREAD

**Issue by liurd** [etcd-io/etcd#10271]
ETCD is too sensitive to disk latencies, in cloud environment, it's always a big issue because SSD is not used for all cloud environment. 
https://coreos.com/etcd/docs/latest/tuning.html#disk is not enough.  Not so sensitive to disk latency, or non-SSD solution is needed. "Rely on SSD" is really a restriction to use in cloud ENV.  

Guess you may close my ticket, but I do appreciate your help if any suggestion can be provided. 
"How to make ETCD stable in non-SSD environment ?"

**Comment by vimalk78** [comment]
very basic suggestion would be to use dedicated disk for storing log, but not sure if cloud environment will provide a dedicated disk.
suggest to change question title to "How to make ETCD stable in non-SSD cloud environment ?"

**Comment by xiang90** [comment]
What problem do you hit when running etcd with slow disk? Can you provide a concrete example?

**Comment by spzala** [comment]
Closing it per issue triage guidelines https://github.com/etcd-io/etcd/blob/master/Documentation/triage/issues.md#inactive-issues 
@liurd please feel free to reopen with more information as requested by @xiang90 Thanks!
