### ISSUE TITLE
how to know the limit about disk io

### ISSUE THREAD

**Issue by XiaoJiangWang** [etcd-io/etcd#10276]
In https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/limit.md ， we can see the system limits about Request size and Storage size. But there is no description about the limit about disk io.

So I want to ask what is the recommended value for disk io.

My scenes is that：
I'll use k8s to manage etcd pod, and want it use pvcTemplate. for data, It maybe is a good option. But I don't know how to choose the remote disk type in cloud.

If there is a document for disk io limits, please give me the link. Thks.

**Comment by XiaoJiangWang** [comment]
@gyuho @xiang90  
If there is a document for disk io limits, please give me the link. Thks.

I beg your pardon , may be I was too plain.

**Comment by XiaoJiangWang** [comment]
also I think these links will help others.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md#disks
https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#system-requirements

**Comment by hexfusion** [comment]
@XiaoJiangWang thank you, please let me know if you have any other questions.
