### ISSUE TITLE
Re-Run new benchmarks for etcd and update docs

### ISSUE THREAD

**Issue by mrueg** [etcd-io/etcd#10285]
Since this was run with 3.2.x (+go 1.8.x), and etcd is at 3.3.10 now, it would be awesome if anyone could re-run
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md
and provide more documentation about the environment (e.g. using TLS, using ClientCerts, Token-based Auth, settings on etcd itself). I wanted to use it as a baseline but it's hard to estimate without knowing how the etcd setup looked exactly.

**Comment by hexfusion** [comment]
> Since this was run with 3.2.x (+go 1.8.x), and etcd is at 3.3.10 now, it would be awesome if anyone could re-run
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md

@mrueg yes we are planning this update for 3.4 and we will hopefully be able to extend the details and scope.

https://github.com/etcd-io/etcd/pull/10283#issuecomment-441846508
