### ISSUE TITLE
Threat model for peer DNS validation?

### ISSUE THREAD

**Issue by justinsb** [etcd-io/etcd#10282]
There's been a lot of changes to the peer TLS certificate validation, and it isn't clear what the motivation is, or what threat is being addressed.  It sounds like etcd expects secure DNS?  Some documentation on the original shortcoming and the intention of the changes would be very helpful.

I suspect it would be useful to split the client & server certificates for peers, but it's not clear whether that would bypass the original problem.

**Comment by gyuho** [comment]
Yes, there have been lots of changes (mostly tightening the TLS auth) in v3.2.

I've documented here https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md#notes-for-tls-authentication but they may need more clarification.

> Some documentation on the original shortcoming and the intention of the changes would be very helpful.

Good idea.

**Comment by jingyih** [comment]
cc @wenjiaswe
