### ISSUE TITLE
Question: possible bug in etcd clientv3 or misconfiguration??

### ISSUE THREAD

**Issue by rugwirobaker** [etcd-io/etcd#10288]
I have been trying building a project in which I am importing (I am vendoring using dep):
`- name = "go.etcd.io/etcd"`
`-        version = "3.3.10" `

This is the output for all the three platform builds using gox.

3 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/nanopack/shaman/vendor/google.golang.org/genproto/googleapis/rpc/status
vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:114:28: undefined: proto.InternalMessageInfo

--> darwin/amd64 error: exit status 2
Stderr: # github.com/nanopack/shaman/vendor/google.golang.org/genproto/googleapis/rpc/status
vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:114:28: undefined: proto.InternalMessageInfo

--> windows/amd64 error: exit status 2
Stderr: # github.com/nanopack/shaman/vendor/google.golang.org/genproto/googleapis/rpc/status
vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:114:28: undefined: proto.InternalMessageInfo

Is there something I am doing wrong?? All I am trying to do is to create an instance of the client using the example given by the [README](https://github.com/etcd-io/etcd/blob/master/clientv3/README.md).

**Comment by hexfusion** [comment]
@rugwirobaker please see https://github.com/etcd-io/etcd/issues/10249#issuecomment-439012194. If you can compile client locally and it runs then the issue is probably one for https://github.com/mitchellh/gox ?

**Comment by hexfusion** [comment]
Further research points to a possible issue with your dependency management. Can you please make sure that all of your dependencies are properly filled? For instance `dep ensure -update`

ref: https://github.com/golang/dep/blob/master/docs/daily-dep.md

**Comment by rugwirobaker** [comment]
It's probably a dependency management management problem cause even when I tried to build with `go build` I got the same result. Let try and ensure the deps are well set. But that would be strange since dep is my second attempt after I tried govendor.

**Comment by rugwirobaker** [comment]
My build just finished  successfully.  All I did was `dep ensure update`. Thank you very much for your feedback, I believe that a wrap.

**Comment by rugwirobaker** [comment]
I hope I does work with govendor 2.
