### ISSUE TITLE
Can not use RBAC via grpc proxy

### ISSUE THREAD

**Issue by qd19zzx** [etcd-io/etcd#10294]
Hi,
I have deployed a 3 node etcd server and a grpc proxy, then I create a root user and auth enable. But I can not use root user to access etcd server via grpc proxy.
Reproducible:
1. ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 user create root:123
Success
2. ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 auth enable
Success
3. ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 --user root:123 user list
Success and can list the users.
3. ETCDCTL_API=3 etcdctl --endpoints http://proxyIP:2379 --user root:123 user list
Fail and the response is "Error:  etcdserver: user name not found"

The etcd version is 
etcd Version: 3.2.22
Git SHA: 1674e68
Go Version: go1.9.2
Go OS/Arch: linux/amd64

Did I miss something? Or the etcd doesn't support RBAC via grpc proxy?

**Comment by hexfusion** [comment]
```
ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 user create root:123
Success
ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 auth enable
Success
ETCDCTL_API=3 etcdctl --endpoints http://serverIP:2379 --user root:123 user list
Success and can list the users.
ETCDCTL_API=3 etcdctl --endpoints http://proxyIP:2379 --user root:123 user list
Fail and the response is "Error: etcdserver: user name not found"
```

**Comment by hexfusion** [comment]
> Did I miss something? Or the etcd doesn't support RBAC via grpc proxy?

@qd19zzx I can reproduce in 3.2.{22,24} but it seems to work fine in 3.3.10. If you can use 3.3.x then please do so in the meantime I will review this further.

**Comment by qd19zzx** [comment]
OK，I can use 3.3.x，thanks
