### ISSUE TITLE
Consultation on how to find matching keys

### ISSUE THREAD

**Issue by zonghaishang** [etcd-io/etcd#10293]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

How to match the keys of multiple suffixes? For example, including `abc/providers`, `edf/providers`, I want to find a specific suffix (eg: all keys with end of `/provider`).

Or how do I find a key that matches the beginning and end?

**Comment by jingyih** [comment]
I do not think matching suffix is supported. Ranging with prefix is more efficient given the current data model of etcd.

**Comment by zonghaishang** [comment]
close it now.
