### ISSUE TITLE
benchmark failed with "etcdserver: mvcc: database space exceeded" with --quota-backend-bytes set to 10G

### ISSUE THREAD

**Issue by CindyXing** [etcd-io/etcd#10299]
etcdctl version: 3.3.1
API version: 3.3

benchmark failed with: 
etcdserver: mvcc: database space exceeded
db size is now 2GB. 
--quota-backend-bytes was set to 10G
Benchmark tool was built by cloning the latest code. 

Do I miss anything?

Thanks

**Comment by CindyXing** [comment]
@hexfusion Thanks for checking here. From the log, I saw there was some issue writing the wal log. I've cleaned the db data and will try to repro. Please feel free to close this issue for now.

**Comment by hexfusion** [comment]
>@hexfusion Thanks for checking here. From the log, I saw there was some issue writing the wal log. I've cleaned the db data and will try to repro. Please feel free to close this issue for now.

@CindyXing sounds good if you have any further issues please respond here and we can reopen/investigate.
