### ISSUE TITLE
HTTPS GET request returns a HTTP temporary redirect

### ISSUE THREAD

**Issue by donatello** [etcd-io/etcd#1031]
I am trying to use etcd with client-cert-authenication, but am having a problem (IP addresses redacted below):

```
# curl -X GET  --cacert ca.crt --key peer.key --cert peer.crt https://<STANDBY_NODE_IP>:4001/v2/keys/hello 
<a href="http://<LEADER_NODE_IP>:4001/v2/keys/hello">Temporary Redirect</a>.

```

The standby node returns a HTTP redirect instead of a HTTPS redirect. This causes garbage to be returned by client programs when the redirect is followed. Is this a bug? Any workarounds?

EDIT:

This happens on any redirect - just verified it happens when we set `consistent=true` or `quorum=true` on a GET request to a peer node too (initially I tested this only on a standby server)

**Comment by yichengq** [comment]
For clarity, standby and proxy are different concepts that aim to solve different problems.
Standby is deprecated now. Proxy, which redirects requests too, has solved this issue.
