### ISSUE TITLE
[Questions] How to ensure data propagated?

### ISSUE THREAD

**Issue by 0ctopus13prime** [etcd-io/etcd#10317]
If it's not appropriate to ask a question here, please let me know!

Hello experts.
I'm working on data replication module by extending Etcd raft.
My intention was get data through http api from client first,
after transforming replicate data by passing it to `Propose` method.

And I know data that has been passed to `Propose` can be lost without notice.
So it's up to user to guarantee data was propagated to other followers.

But how can I determine this?
I have to ensure data is replicated before replying 200 status to client and I'm kind of lost in here..

Would you like to recommend or advise those typical ways to achieve this?

Thank you!
Best regard

**Comment by 0ctopus13prime** [comment]
Thank you for your answer!

But how to relate UUID with a single HardState?

```
message HardState {
	optional uint64 term   = 1 [(gogoproto.nullable) = false];
	optional uint64 vote   = 2 [(gogoproto.nullable) = false];
	optional uint64 commit = 3 [(gogoproto.nullable) = false];
}
```

`Propose` method accepts a byte array, and given byte array goes to raft's message buffer ultimately.

```
func (r *raft) send(m pb.Message) {
   ... 
   r.msgs = append(r.msgs, m)  // Buffering
}
```

Should I touch raft source code a little bit for this purpose?

Thank you!

**Comment by xiang90** [comment]
@0ctopus13prime 

The uuid is application specific. You embed that inside the raft entry.

**Comment by 0ctopus13prime** [comment]
Thank you for your answers xiang90!
It helped me a lot.
