### ISSUE TITLE
Can't connect Vault to etcd cluster via grpc-proxy

### ISSUE THREAD

**Issue by ppettina** [etcd-io/etcd#10319]
Hopefully this one is not obscure:
I'm trying to run Vault using etcd as a backend, and I want to use grpc-proxy between Vault and the etcd cluster.
TL;DR: Vault relies on the etcd endpoint to provide a `/version` HTTP GET api. grpc-proxy does not offer this and Vault refuses to start.

I am running grpc-proxy (v3.3.8) with this configuration:
```
      grpc-proxy start                                                                                                 
      --advertise-client-url=https://XXXXX:2379                                                 
      --listen-addr 0.0.0.0:2379                                                                                       
      --resolver-prefix="___grpc_proxy_endpoint"                                                                       
      --resolver-ttl=60                                                                                                
      --endpoints .....
      --cert-file /etc/ssl/etcd/etcd-proxy.pem                                                                         
      --key-file /etc/ssl/etcd/etcd-proxy-key.pem                                                                      
      --trusted-ca-file /etc/ssl/etcd/ca.pem
      --key /etc/ssl/etcd/etcd-proxy-key.pem                                                                           
      --cert /etc/ssl/etcd/etcd-proxy.pem
      --cacert /etc/ssl/etcd/ca.pem
      --debug
```
Then trying to connect to it with Vault (settings irrelevant):
```
Error initializing storage of type etcd: failed to get etcd API version: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.
```

Disabling TLS and sniffing the connection with tcpdump, I realise that Vault is trying to access the `/version` API endpoint:
```
GET /version?quorum=false&recursive=false&sorted=false HTTP/1.1\r\n
```
To which grpc-proxy replies:
```
HTTP/1.1 404 Not Found\r\n
```
As a matter of fact, it's not possible to use etcdv3 via a proxy with Vault until grpc-proxy implements this endpoint. The alternative is to use v2 with a "regular" proxy instance.

**Comment by hexfusion** [comment]
> As a matter of fact, it's not possible to use etcdv3 via a proxy with Vault until grpc-proxy implements this endpoint. The alternative is to use v2 with a "regular" proxy instance.

grpc-proxy is just that so this is expected response. As far as Vault is concerned it could get a list of endpoints from the proxy (MemberList) and then do a GET against a member in that list directly for /version. I am unfamiliar with the etcd back-end implementation for Vault but if it knows it is using grpc-proxy then it could get what it needs in a different way. This is at least my first thought vs hacking on proxy.

**Comment by ppettina** [comment]
Maybe it's worth bumping the issue inside the vault repo...

**Comment by raoofm** [comment]
@ppettina just want to understand your motivation for using proxy instead of the cluster endpoints

**Comment by ppettina** [comment]
@raoofm thanks for your reply.
It does make sense to manage the setup of vault separately from the etcd cluster. It would be good to be able to change the cluster structure transparently without having to update the vault configuration.

I thought that the idea of using a proxy as a frontend for the etcd cluster was a cleaner approach from an architecture POV. It's possible to do this easily using a v2 proxy (what I'm now doing in my setup), and I thought that would naturally translate into grpc-proxy or gateway in v3.

I think it would be a good thing to add support for this, to keep etcd as an alive (i.e. non-legacy) backend for Vault. However it looks like support has to come from the community for it:
> Hi, etcd is community maintained, and coreos publicly committed to  maintaining it a bit ago. I'm going to close this in favor of someone  sending a PR to implement this.
--

From the other bug I raised. Not much love I guess :(

**Comment by raoofm** [comment]
@hexfusion so the reason for getting the version is there was already a vault etcd backend that used v2 and @xiang90 added etcdv3 backend.

Vault authors wanted xiang to handle the existing users and not to break things so the logic was implemented to get the version of etcd and compare it with the config and also check against the data that exists in v2 backend.

This was done I think as part of https://github.com/hashicorp/vault/pull/2168
check https://github.com/hashicorp/vault/blob/master/physical/etcd/etcd.go

I think this could be changed if @jefferai agrees that etcd2 backend is broken and doesn't work as HA and no one is maintaining it. Its ok if v2 is not dropped but v3 should be default without checking the version.

```go
// NewEtcdBackend constructs a etcd backend using a given machine address.
func NewEtcdBackend(conf map[string]string, logger log.Logger) (physical.Backend, error) {
	var (
		apiVersion string
		ok         bool
	)

	// v2 client can talk to both etcd2 and etcd3 thought API v2
	c, err := newEtcdV2Client(conf)
	if err != nil {
		return nil, errors.New("failed to create etcd client: " + err.Error())
	}

	remoteAPIVersion, err := getEtcdAPIVersion(c)
	if err != nil {
		return nil, errors.New("failed to get etcd API version: " + err.Error())
	}

	if apiVersion, ok = conf["etcd_api"]; !ok {
		apiVersion = os.Getenv("ETCD_API")
	}

	if apiVersion == "" {
		path, ok := conf["path"]
		if !ok {
			path = "/vault"
		}
		kAPI := client.NewKeysAPI(c)

		// keep using v2 if vault data exists in v2 and user does not explicitly
		// ask for v3.
		_, err := kAPI.Get(context.Background(), path, &client.GetOptions{})
		if errorIsMissingKey(err) {
			apiVersion = remoteAPIVersion
		} else if err == nil {
			apiVersion = "2"
		} else {
			return nil, errors.New("failed to check etcd status: " + err.Error())
		}
	}

	switch apiVersion {
	case "2", "etcd2", "v2":
		return newEtcd2Backend(conf, logger)
	case "3", "etcd3", "v3":
		if remoteAPIVersion == "2" {
			return nil, errors.New("etcd3 is required: etcd2 is running")
		}
		return newEtcd3Backend(conf, logger)
	default:
		return nil, EtcdVersionUnknown
	}
}

// getEtcdAPIVersion gets the latest supported API version.
// If etcd cluster version >= 3.1, "3" will be returned.
// Otherwise, "2" will be returned.
func getEtcdAPIVersion(c client.Client) (string, error) {
	v, err := c.GetVersion(context.Background())
	if err != nil {
		return "", err
	}

	sv, err := semver.NewVersion(v.Cluster)
	if err != nil {
		return "", nil
	}

	if sv.LessThan(*semver.Must(semver.NewVersion("3.1.0"))) {
		return "2", nil
	}

	return "3", nil
}
```

**Comment by jefferai** [comment]
Is there some other API the response to which could indicate which version of etcd it is? We can't drop v2 as people are using it, but if there is something that can be used heuristically in place of an explicit version call, that would work.

**Comment by hexfusion** [comment]
>Is there some other API the response to which could indicate which version of etcd it is? We can't drop v2 as people are using it, but if there is something that can be used heuristically in place of an explicit version call, that would work.

You could do this with clientv3 call to Status with Maintenance API

https://github.com/etcd-io/etcd/blob/e8b940f268a80c14f7082589f60cbfd3de531d12/clientv3/maintenance.go#L163

[Documentation/dev-guide/api_reference_v3.md#message-statusresponse](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-statusresponse-etcdserveretcdserverpbrpcproto)

**Comment by hexfusion** [comment]
But this will only respond if v3. You can use the same endpoint /version with the method I outlined above.

**Comment by hexfusion** [comment]
I am going to close this as this is not an actual etcd issue but a lack of support for Vault using proxy. I will try and look at adding support in the near feature if possible.

**Comment by jefferai** [comment]
Agree with the closure. This is a proxy issue, not an etcd issue or Vault issue.
