### ISSUE TITLE
I used the etcd/embed cue panic: codecgen version mismatch: current: 8, need 10.

### ISSUE THREAD

**Issue by yeyongyong** [etcd-io/etcd#10325]
panic: codecgen version mismatch: current: 8, need 10. Re-generate file: /Users/yeyongyong/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/coreos/etcd/client.init.0()
	/Users/yeyongyong/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:45 +0x104

**Comment by maps90** [comment]
having the same problem, can anyone help?

**Comment by hexfusion** [comment]
@yeyongyong @maps could you please test #10337

**Comment by maps90** [comment]
@hexfusion superb! it works

**Comment by MatevzFa** [comment]
How can I use this change in my project, while using go.mod file?

**Comment by reefbarman** [comment]
I still see this issue using the latest release, I am using go modules in go 1.11 is there anything specific I need to do to resolve this?

**Comment by reefbarman** [comment]
exact error is here:

panic: codecgen version mismatch: current: 8, need 10. Re-generate file: C:/Go/pkg/mod/github.com/coreos/etcd@v3.3.11+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/coreos/etcd/client.init.0()
        C:/Go/pkg/mod/github.com/coreos/etcd@v3.3.11+incompatible/client/keys.generated.go:45 +0x10b
exit status 2

**Comment by mnajork-palantir** [comment]
When can we expect a release to get cut which contains the fix?

**Comment by lifangmoler** [comment]
Seeing the same issue using the latest version

**Comment by lifangmoler** [comment]
is the latest version containing the fix for this?

**Comment by lifangmoler** [comment]
@mnajork-palantir how to do `vendor in the dependency at the fix's merge commit to pick up the changes.`?

**Comment by mnajork-palantir** [comment]
@lifangmoler what are you using as your dependency management tool?

Here's the commit containing the fix: https://github.com/etcd-io/etcd/commit/f3fbedc88f52527ef4dd051bea53e8c99a569831

**Comment by lifangmoler** [comment]
@mnajork-palantir I am using `go mod`.  I can see the commit and the change. but still not sure how to pick the change

**Comment by lifangmoler** [comment]
trying this `go get github.com/coreos/etcd@f3fbedc`, seeing new errrors: ```go: finding github.com/coreos/etcd f3fbedc
go: github.com/coreos/etcd@v0.0.0-20181221231655-f3fbedc88f52: parsing go.mod: unexpected module path "go.etcd.io/etcd"
go: error loading module requirements```

**Comment by hexfusion** [comment]
Played with this a little and I found if you are using go mod for your project and running into issues with "codecgen version mismatch: current: 8, need 10. Re-generate file:" try:

`go get github.com/ugorji/go@v1.1.1` which is the version we pin https://github.com/etcd-io/etcd/blob/master/go.mod#L45

go.mod
```bash
module github.com/hexfusion/stuffz

require (
             github.com/coreos/etcd v3.3.12+incompatible
[snip]
              github.com/ugorji/go v1.1.1 // indirect
)
```
Curious if this helps folks.

**Comment by hexfusion** [comment]
@lifangmoler @mnajork-palantir @reefbarman ^

**Comment by reefbarman** [comment]
@hexfusion so I have gotten further with the suggestion change but then received this
```
..\Go\pkg\mod\github.com\coreos\etcd@v3.3.12+incompatible\client\keys.generated.go:15:2: unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.1 (C:\Gamedev\Go\pkg\mod\github.com\ugorji\go@v1.1.1\codec)
        github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (C:\Gamedev\Go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```

Will dig to see if I can resolve this but I am not specifically requiring github.com/ugorji/go/codec

**Comment by reefbarman** [comment]
okay I found it was github.com/spf13/viper also requiring go/codec and I forked this and updated it to use the same versions of etcd and go/codec and it built. But ideally etcd would support go mod so things can be versioned correctly

**Comment by lifangmoler** [comment]
@hexfusion It is working for me after i tried  `go get github.com/ugorji/go@v1.1.1`. thanks

**Comment by amarox** [comment]
Still have same problem

**Comment by hexfusion** [comment]
@amarox make sure to bump etcd we updated to a go mod friendly version of `ugorji/go`  recently https://github.com/etcd-io/etcd/pull/10481

**Comment by amarox** [comment]
github.com/coreos/etcd v3.3.12

**Comment by zsounder** [comment]
Still have same problem

> github.com/coreos/etcd v3.3.12+incompatible // indirect
    github.com/ugorji/go v1.1.1 // indirect

**Comment by s4kibs4mi** [comment]
Facing the same issue,
```
panic: codecgen version mismatch: current: 8, need 10. Re-generate file: /Users/sakib/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/coreos/etcd/client.init.0()
        /Users/sakib/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:45 +0x135
```

**Comment by radekg** [comment]
Same problem, this appears to be okay:

```
[[constraint]]
  name = "github.com/etcd-io/etcd"
  revision = "1adc28822343e2f14cc5e493a663fba1adf54186"
```

**Comment by alee792** [comment]
Bcmills' [solution](https://github.com/golang/go/issues/29332#issuecomment-448669442) resolved this for me.

> go get github.com/ugorji/go/codec@none

**Comment by lucasalcantara** [comment]
this [solution](https://github.com/etcd-io/etcd/issues/10325#issuecomment-462176739) worked to me.
I just did `GO111MODULE=on go get -u github.com/ugorji/go@v1.1.1` as worked beautifully.

**Comment by bhechinger** [comment]
That results in this on 1.12:

```
13:07 $ make linux
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w -X main.Version=v1.1.8 -X main.Commit=13d00f2b2b9ac7db906df8b84586a53cbaadbf0c -X main.Branch=master" -o auth-srv-linux-amd64 . ; \

go: downloading github.com/spf13/viper v1.2.1
go: extracting github.com/spf13/viper v1.2.1
go: downloading github.com/ugorji/go v1.1.6
go: extracting github.com/ugorji/go v1.1.6
# github.com/coreos/etcd/client
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:63:14: z.HasExtensions undefined (type codec.genHelperEncoder has no field or method HasExtensions)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:63:35: z.EncExt undefined (type codec.genHelperEncoder has no field or method EncExt)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:75:6: r.WriteArrayElem undefined (type codec.genHelperEncDriver has no field or method WriteArrayElem)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:83:6: r.WriteMapElemKey undefined (type codec.genHelperEncDriver has no field or method WriteMapElemKey)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:84:19: too many arguments in call to r.encDriver.EncodeString
	have (number, string)
	want (string)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:85:6: r.WriteMapElemValue undefined (type codec.genHelperEncDriver has no field or method WriteMapElemValue)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:94:6: r.WriteArrayElem undefined (type codec.genHelperEncDriver has no field or method WriteArrayElem)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:99:20: too many arguments in call to r.encDriver.EncodeString
	have (number, string)
	want (string)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:102:6: r.WriteMapElemKey undefined (type codec.genHelperEncDriver has no field or method WriteMapElemKey)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:103:19: too many arguments in call to r.encDriver.EncodeString
	have (number, string)
	want (string)
/home/wonko/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:103:19: too many errors
Makefile:26: recipe for target 'linux' failed
make: *** [linux] Error 2
```
