### ISSUE TITLE
Please remove gogoproto annotations from .proto files for the public API

### ISSUE THREAD

**Issue by jmillikin-stripe** [etcd-io/etcd#10324]
(moved from https://github.com/etcd-io/etcd/issues/10320)

This applies to the public client API defined in [etcdserver/etcdserverpb/rpc.proto](https://github.com/etcd-io/etcd/blob/v3.3.10/etcdserver/etcdserverpb/rpc.proto), plus its dependencies [auth/authpb/auth.proto](https://github.com/etcd-io/etcd/blob/v3.3.10/auth/authpb/auth.proto) and [mvcc/mvccpb/kv.proto](https://github.com/etcd-io/etcd/blob/v3.3.10/mvcc/mvccpb/kv.proto).

Setting gogoproto annotations on these files makes it more complicated to build etcd clients or proxies in non-Go languages, because they add a hard dependency on the magical `gogo.proto` that gets injected by the gogoproto protoc plugin. See https://github.com/etcd-io/etcd/issues/7490 for an example of this causing trouble for an attempted PHP client.

Gogoproto annotations also make it more difficult for Go clients that use the [standard Go protobuf implementation](https://github.com/golang/protobuf).

**Comment by gyuho** [comment]
I like this idea, and will be super-useful for other language bindings. We have a few more new proto changes coming to v3.4 (learner) that might add extra fields to RPC proto. Since then, it will be in stable state, when we can discuss about moving out of core repository. /cc @xiang90

**Comment by xiang90** [comment]
Moving proto files to another repo is one thing. And not using gogoproto is another. We probably still need to stick with gogoproto unless the standard proto provides comparable performance.
