### ISSUE TITLE
kubernetes_etcd_cluster_error

### ISSUE THREAD

**Issue by gatici** [etcd-io/etcd#10349]
Steps to reproduce

Environment

Installation method: 

Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
Observed result
Dashboard reported Internal Server Error (500):

client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member https://etcd.kubernetes.rancher.internal:2379 has no leader

**Comment by hexfusion** [comment]
@gatici can you provide more etcd related details so that we can help you? Logs from the etcd server 
 and version would be a good start. The steps you provided are not complete for us to provide support.

**Comment by gatici** [comment]
<img width="880" alt="etcd" src="https://user-images.githubusercontent.com/22467749/50756608-c6597f00-126d-11e9-9114-082c9cfd08b6.PNG">

Dear @hexfusion,  at least  once  in a  day I am getting such  errors  both  from  GUI and  CLI.
Kubernetes cluster is  working  on  Rancher.
Using the  below  versions.
KUBECTL_VERSION=1.11.2
RANCHER_VERSION=1.6.22

Here are the  etcd Container  logs at that  time:
07.01.2019 11:17:452019-01-07 08:17:45.555473 E | etcdhttp: error writing event (write tcp 10.42.111.135:2379->10.42.229.24:44232: write: broken pipe)
07.01.2019 11:17:482019-01-07 08:17:48.891905 E | etcdhttp: error writing event (write tcp 10.42.111.135:2379->10.42.229.24:44292: write: connection reset by peer)
07.01.2019 11:17:482019-01-07 08:17:48.987132 E | etcdhttp: error writing event (write tcp 10.42.111.135:2379->10.42.229.24:44304: write: broken pipe)
07.01.2019 11:17:512019-01-07 08:17:51.062591 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 56.364558ms)
07.01.2019 11:17:512019-01-07 08:17:51.062664 W | etcdserver: server is likely overloaded
07.01.2019 11:17:512019-01-07 08:17:51.062683 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 56.576403ms)
07.01.2019 11:17:512019-01-07 08:17:51.062691 W | etcdserver: server is likely overloaded
07.01.2019 11:18:022019-01-07 08:18:02.039681 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 24.50497ms)
07.01.2019 11:18:022019-01-07 08:18:02.039765 W | etcdserver: server is likely overloaded
07.01.2019 11:18:022019-01-07 08:18:02.039791 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 24.611712ms)
07.01.2019 11:18:022019-01-07 08:18:02.039806 W | etcdserver: server is likely overloaded
07.01.2019 11:18:06time="2019-01-07T08:18:06Z" level=info msg="Created backup" name="2019-01-07T08:18:02Z_etcd_1" runtime=3.542199392s
07.01.2019 11:18:06time="2019-01-07T08:18:06Z" level=info msg="Deleted backup" name="2019-01-06T08:18:02Z_etcd_1" runtime=74.30765ms
07.01.2019 11:18:062019-01-07 08:18:06.819981 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 289.454531ms)
07.01.2019 11:18:062019-01-07 08:18:06.820040 W | etcdserver: server is likely overloaded
07.01.2019 11:18:062019-01-07 08:18:06.820058 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 289.564164ms)
07.01.2019 11:18:062019-01-07 08:18:06.820069 W | etcdserver: server is likely overloaded
07.01.2019 11:18:172019-01-07 08:18:17.050801 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 46.583748ms)
07.01.2019 11:18:172019-01-07 08:18:17.050877 W | etcdserver: server is likely overloaded
07.01.2019 11:18:172019-01-07 08:18:17.050904 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 46.708386ms)
07.01.2019 11:18:172019-01-07 08:18:17.050920 W | etcdserver: server is likely overloaded
07.01.2019 11:18:182019-01-07 08:18:18.643452 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 592.654759ms)
07.01.2019 11:18:182019-01-07 08:18:18.643523 W | etcdserver: server is likely overloaded
07.01.2019 11:18:182019-01-07 08:18:18.643549 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 592.645586ms)
07.01.2019 11:18:182019-01-07 08:18:18.643564 W | etcdserver: server is likely overloaded
07.01.2019 11:18:192019-01-07 08:18:19.498838 E | etcdhttp: error writing event (write tcp 10.42.111.135:2379->10.42.229.24:45504: write: broken pipe)
07.01.2019 11:18:222019-01-07 08:18:22.202249 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 697.466761ms)
07.01.2019 11:18:222019-01-07 08:18:22.202619 W | etcdserver: server is likely overloaded
07.01.2019 11:18:222019-01-07 08:18:22.202656 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 697.891539ms)
07.01.2019 11:18:222019-01-07 08:18:22.202674 W | etcdserver: server is likely overloaded
07.01.2019 11:18:242019-01-07 08:18:24.900670 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 396.815659ms)
07.01.2019 11:18:242019-01-07 08:18:24.900738 W | etcdserver: server is likely overloaded
07.01.2019 11:18:242019-01-07 08:18:24.900758 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 396.925508ms)
07.01.2019 11:18:242019-01-07 08:18:24.900770 W | etcdserver: server is likely overloaded
07.01.2019 11:18:372019-01-07 08:18:37.030911 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 28.596215ms)
07.01.2019 11:18:372019-01-07 08:18:37.030975 W | etcdserver: server is likely overloaded
07.01.2019 11:18:372019-01-07 08:18:37.030994 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 28.910486ms)
07.01.2019 11:18:372019-01-07 08:18:37.031498 W | etcdserver: server is likely overloaded
07.01.2019 11:18:392019-01-07 08:18:39.601499 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 1.569874466s)
07.01.2019 11:18:392019-01-07 08:18:39.601568 W | etcdserver: server is likely overloaded
07.01.2019 11:18:392019-01-07 08:18:39.601590 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 1.570702335s)
07.01.2019 11:18:392019-01-07 08:18:39.601606 W | etcdserver: server is likely overloaded
07.01.2019 11:18:422019-01-07 08:18:42.167262 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 165.522842ms)
07.01.2019 11:18:422019-01-07 08:18:42.175338 W | etcdserver: server is likely overloaded
07.01.2019 11:18:422019-01-07 08:18:42.175399 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 173.667832ms)
07.01.2019 11:18:422019-01-07 08:18:42.175412 W | etcdserver: server is likely overloaded
07.01.2019 11:18:442019-01-07 08:18:44.494327 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 1.327066336s)
07.01.2019 11:18:442019-01-07 08:18:44.494399 W | etcdserver: server is likely overloaded
07.01.2019 11:18:442019-01-07 08:18:44.494426 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 1.31903722s)
07.01.2019 11:18:442019-01-07 08:18:44.494442 W | etcdserver: server is likely overloaded
07.01.2019 11:19:182019-01-07 08:19:18.170087 E | etcdhttp: error writing event (write tcp 10.42.111.135:2379->10.42.229.24:46066: write: broken pipe)
07.01.2019 11:20:032019-01-07 08:20:03.555144 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 45.782496ms)
07.01.2019 11:20:032019-01-07 08:20:03.555231 W | etcdserver: server is likely overloaded
07.01.2019 11:20:032019-01-07 08:20:03.555260 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 45.9191ms)
07.01.2019 11:20:032019-01-07 08:20:03.555276 W | etcdserver: server is likely overloaded
07.01.2019 11:20:072019-01-07 08:20:07.033418 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 25.682767ms)
07.01.2019 11:20:072019-01-07 08:20:07.033469 W | etcdserver: server is likely overloaded
07.01.2019 11:20:072019-01-07 08:20:07.033481 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 25.765813ms)
07.01.2019 11:20:072019-01-07 08:20:07.033489 W | etcdserver: server is likely overloaded

**Comment by gatici** [comment]
A CLI  error:
Sometimes  I got  such  kind of  errors.
ubuntu@kub1:~/oom/kubernetes$ helm  list
Error: client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member https://etcd.kubernetes.rancher.internal:2379 has no leader

**Comment by gatici** [comment]
I sometimes  also  got  such  errors in the  kubernetes  cluster  hosts:
ubuntu@kub2:~$ 
Broadcast message from systemd-journald@kub2 (Tue 2019-01-08 06:52:56 UTC):

haproxy[7865]: backend IST_Default_8447 has no server available!


Broadcast message from systemd-journald@kub2 (Tue 2019-01-08 06:53:02 UTC):

haproxy[7865]: backend IST_AAI_8446 has no server available!

**Comment by hexfusion** [comment]
>Kubernetes cluster is working on Rancher.
Using the below versions.
KUBECTL_VERSION=1.11.2
RANCHER_VERSION=1.6.22

what is the etcd version? 

>07.01.2019 11:20:072019-01-07 08:20:07.033469 W | etcdserver: server is likely overloaded
07.01.2019 11:20:072019-01-07 08:20:07.033481 W | etcdserver: failed to send out heartbeat on time 

@gatici it sounds like you are having some I/O issues can you provide details on your etcd, how many members in cluster? Please provide metrics on each member. To do this you can do a GET on for example https://etcd.kubernetes.rancher.internal:2379/metrics you will need proper TLS cert, key and ca to make this call with curl. Please attach the output as file.

**Comment by hexfusion** [comment]
Ping @gatici any update?
