### ISSUE TITLE
Closing Watcher always returns "context canceled"

### ISSUE THREAD

**Issue by Sahasrara** [etcd-io/etcd#10340]
Example:
```
watcher := clientv3.NewWatcher(etcdClient)
channel := watcher.Watch(context.Background(), "test") 
err := watcher.Close()
if err == context.Caneled {
    fmt.Println("this always happens")
}
```

Is this the expected behavior?  I thought for a time it was failing to close the watch, but looking at a profiler, that doesn't seem to be the case.  It was just misleading.

**Comment by spzala** [comment]
@Sahasrara thx for reporting. I could reproduce it and error does seems confusing. 
@gyuho @hexfusion does the PR I created for it makes sense? Please take a look. Thanks!
