### ISSUE TITLE
playground: ranges

### ISSUE THREAD

**Issue by gertcuykens** [etcd-io/etcd#10350]
This is verywell done http://play.etcd.io/play may I suggest the posibility to play with `ranges`. I believe `ranges` are one of does things you need to play with to fully understand.

**Comment by hexfusion** [comment]
> This is verywell done http://play.etcd.io/play may I suggest the posibility to play with ranges. I believe ranges are one of does things you need to play with to fully understand.

Hi @gertcuykens while I agree I think using etcdctl against single node is a pretty strait forward way to play with etcd features. Feel free to create issue or a PR here https://github.com/etcd-io/etcdlabs
