### ISSUE TITLE
playground: etcdctl -d play.etcd.io

### ISSUE THREAD

**Issue by gertcuykens** [etcd-io/etcd#10352]
Think it would be nice if you could allow playing with the cluster using `etcdctl -d play.etcd.io` directly

**Comment by hexfusion** [comment]
> Think it would be nice if you could allow playing with the cluster using etcdctl -d play.etcd.io directly

@gertcuykens the code is open source so you can setup your own and try playing with it, instructions are in the [README](https://github.com/etcd-io/etcdlabs/blob/master/README.md).

https://github.com/etcd-io/etcdlabs

**Comment by gertcuykens** [comment]
Thx but setting up a vanilla etcd to play with etcdctl would be the way top go then. Could be that for security reasons it isn't possible to offer a public play.etcd.io that is accesible by etcdctl. But if you can provide it then you dont have to know anythimg about how to set etcd up and it will lower the entrance barrier especially for windows users :)

**Comment by hexfusion** [comment]
@gertcuykens fair point and we want to help you :).

Windows users can do the following:
```
# download
https://github.com/etcd-io/etcd/releases/download/v3.3.10/etcd-v3.3.10-windows-amd64.zip

# unzip then in terminal run without any flags to start single node etcd. Keep terminal window open or etcd will stop.
etcd-v3.3.10-windows-amd64/etcd.exe

# in a new terminal window
ETCDCTL_API=3 etcd-v3.3.10-windows-amd64/etcdctl.exe put foo bar
```

Please let me know if this doesn't work as expected.

**Comment by gertcuykens** [comment]
For me it's ok thx, anyway it was just a suggestion to have a live visual representation on the playground of etcdctl commands. I was hoping it would be just opening 2 ports on the playground node servers and a few permission tokens.

**Comment by gyuho** [comment]
@gertcuykens Hi,

We only keep the minimum, essential feature for `etcdctl`, so `play.etcd.io` would not be integrated.

But, if you would like to run it locally, you can try https://github.com/etcd-io/etcdlabs#build-and-push-to-gcrio.
