### ISSUE TITLE
Take two members down for a 5-member cluster, cluster health shows "unhealthy cluster"

### ISSUE THREAD

**Issue by zaisongz** [etcd-io/etcd#10353]
# ETCDCTL_API=3 etcdctl --endpoints=http://192.168.3.20:2379,http://192.168.3.21:2379,http://192.168.3.22:2379,http://192.168.3.23:2379,http://192.168.3.24:2379 endpoint health
http://192.168.3.22:2379 is healthy: successfully committed proposal: took = 1.716886ms
http://192.168.3.20:2379 is healthy: successfully committed proposal: took = 2.771621ms
http://192.168.3.23:2379 is healthy: successfully committed proposal: took = 2.039446ms
http://192.168.3.24:2379 is unhealthy: failed to connect: dial tcp 192.168.3.24:2379: getsockopt: connection refused
http://192.168.3.21:2379 is unhealthy: failed to connect: dial tcp 192.168.3.21:2379: getsockopt: connection refused
Error: unhealthy cluster

The failure tolerance is 2 for a 5-member cluster, and the cluster could provide funcationality now. Why report "unhealthy cluster“？

**Comment by xiang90** [comment]
the cluster is still available. unhealthy means not all members are up.

maybe we can make the error message better: "cluster is still alive, but unhealthy: not all members are alive." 

it would be great if you can send a PR to improve it.
