### ISSUE TITLE
Log entries with higher indexes should be discarded when persisting an incoming snapshot

### ISSUE THREAD

**Issue by lni** [etcd-io/etcd#10358]
etcd raft's README file mentions that 

"when writing an Entry with Index i, any previously-persisted entries with Index >= i must be discarded"

My question is when a snapshot with index i is received and persisted, why previously persisted entries with Index >= i are not discarded in the same way? 

Raft paper also mentions the following on page 12 - 

"Usually the snapshot will contain new information not already in the recipient’s log. In this case, the follower discards its entire log;"

Let's consider the following situation - 

For a three nodes Raft cluster with node A, B and C, let's say A is the leader and all three nodes have their log in sync up to index i.  

Node A then makes three proposals and end up having three uncommitted entries with index i+1, i+2 and i+3 in its log. When node A is partitioned away from both B and C, those 3 entries will not be replicated to B and C, they are persisted to A's disk but will not become committed. Let's say A crashes when it is still the leader.

Assume B is later elected as the next leader and proposes two of its own entries at index i+1 and i+2 with a higher term. Those two entries will be committed and applied after their confirmed replication to C.  After that, B takes a snapshot at index i+2 and has its log compacted to that position. When A restart from its failure, it will figure out the new leader and receive that snapshot at index i+2 from B. When persisting this received snapshot to its disk on node A, A's previously persisted entry with index i+3 should be discarded. That is, after another restart of node A, it should see the persisted snapshot index i+2, but not the entry at index i+3. 

Did I miss anything here? Thanks!

**Comment by xiang90** [comment]
> My question is when a snapshot with index i is received and persisted, why previously persisted entries with Index >= i are not discarded in the same way?

It should. I do not think we encourage users to not load any entries received before the snapshot metadata.
