### ISSUE TITLE
grpc-go memory leak

### ISSUE THREAD

**Issue by zeast** [etcd-io/etcd#10362]
[etcd_memory_leak.heap.pprof.zip](https://github.com/etcd-io/etcd/files/2720272/etcd_memory_leak.heap.pprof.zip)

![etcd_memory_leak_prometheus_screenshot](https://user-images.githubusercontent.com/9344800/50585233-f8a25f80-0eae-11e9-8f65-db0da2890966.png)

etcd Version: 3.3.10
Git SHA: 27fc7e2
Go Version: go1.10.4
Go OS/Arch: linux/amd64

top command:
     PID USER   PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
 11613 root      20   0 82.6g  79g 2.5g S  1042 63.4 813:34.28 etcd

endpoints status:
bad_endpoint, 61c7bf58354fae8c, 3.3.10, 2.7 GB, false, 32322, 433403373
good_endpoint, 97eee7aa8c3d026, 3.3.10, 2.7 GB, true, 32322, 433403373
good_endpoint, 7696d1683db35eb5, 3.3.9, 2.7 GB, false, 32322, 433403373

**Comment by hexfusion** [comment]
@zeast is this a leak or is the increase in RAM consumption based on the the size of the DB? What causes this drop in RAM at the start of the graph, compaction? Since you have Prometheus running what does etcd_debugging_mvcc_db_total_size_in_bytes look like during this time series?

**Comment by hexfusion** [comment]
Hi @zeast any update?

**Comment by zeast** [comment]
yeah, I found a way to reproduce. Yesterday and the day before,  I adjusted the request to circumvent this problem, so I didn't notice here, sorry.
If you use http request `/v3beta/kv/range` and want more than `1014 * 1024 * 4` data , you will get error message `{"error":"grpc: received message larger than max (6927780 vs. 4194304)","code":8}` then memory will increase. I try version 3.3.10 and master branch.
@hexfusion

**Comment by zeast** [comment]
bug found: https://github.com/grpc/grpc-go/issues/2444

**Comment by hexfusion** [comment]
@zeast great work we will track the issue, thank you!

**Comment by hexfusion** [comment]
updated title so its easier to see the core problem.

**Comment by cfc4n** [comment]
@hexfusion @gyuho @xiang90 
This bug was fixed at [Fixes established streams leak in the loopy writer.] (https://github.com/grpc/grpc-go/pull/2610) yesterday .

**Comment by xiang90** [comment]
We bumped the gRPC version. So the fix should already be included.
