### ISSUE TITLE
docs: v3 discovery url

### ISSUE THREAD

**Issue by gertcuykens** [etcd-io/etcd#10373]
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md#etcd-discovery

```
curl -X PUT https://myetcd.local/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=3
```

Not sure if the doc is deprecated or there is simple no v3 discovery? related to https://github.com/etcd-io/etcd/issues/8209

Incase there is no v3 discovery url can this be mentioned in the doc please

**Comment by hexfusion** [comment]
> Not sure if the doc is deprecated or there is simple no v3 discovery? related to #8209

@gertcuykens the docs are still accurate if you start a cluster for the purpose of discovery this will still work, have you tried it? If this doesn't work please let us know.

>Incase there is no v3 discovery url can this be mentioned in the doc please

Would you mind creating PR to this? We want users to know that although v2 discovery API uses v2 store that creating a dedicated cluster for the purpose of discovery would be fine IMO. 
 
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md#etcd-discovery

We are still reviewing options for discovery in v3.

**Comment by gertcuykens** [comment]
Ok I will do PR, just wanted to be sure I didn't mis some v3 discovery options. In the end I think we must make sure we can slim down etcd code base removing deprecated code and have no v2 dependencies to build a v3 only build making it easy to maintain. Don't think we want discovery to be the cause holding a v3 only build back. For me `ETCDCTL_API=3` should be more like a compile option then runtime option. Just think of how much it decreases potentially old v2 security bugs you can avoid by just building a v3 only

**Comment by hexfusion** [comment]
> Ok I will do PR, just wanted to be sure I didn't mis some v3 discovery options.

Thanks!

> For me ETCDCTL_API=3 should be more like a compile option then runtime option.

I agree and `ETCDCTL_API=3` is default for 3.4+.

> Just think of how much it decreases potentially old v2 security bugs you can avoid by just building a v3 only build back.

Deprecating v2 store is in the works for 4.0 https://github.com/etcd-io/etcd/issues/9232. But in the meantime feel free to disable v2 if you don't want to worry about it with [--enable-v2](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--enable-v2. ) flag.

Your points are valid but this will take time to decouple and we of course would love your help :)

**Comment by hexfusion** [comment]
FTR we do plan on adding the discovery API to v3. This should happen during the 1st quarter and be part of a future release TBD.
