### ISSUE TITLE
Missing env vars in documentation

### ISSUE THREAD

**Issue by TheKangaroo** [etcd-io/etcd#10381]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

**Comment by hexfusion** [comment]
@TheKangaroo please review this document and let us know what is missing.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md

**Comment by TheKangaroo** [comment]
@hexfusion sorry, i accidentally hit the enter button ;)

The documentation under https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md is missing the env vars for Miscellaneous flags, Profiling flags, Auth flags and Experimental flags.
I just tested to set some of these flags via env var and it worked fine.
I can send a MR with updated docs if you want to :)

**Comment by hexfusion** [comment]
> @hexfusion sorry, i accidentally hit the enter button ;)

no problem!

> I can send a MR with updated docs if you want to :)

@TheKangaroo yes that would be great, thanks!
