### ISSUE TITLE
How to force a compaction error

### ISSUE THREAD

**Issue by 0x1mason** [etcd-io/etcd#10389]
I want to introduce a compaction error for testing purposes. The only way I've been able to do this reliably is with

1. start etcd with `--auto-compaction-retention=1s`
1. start the watcher with go client
1. do a put
1. restart etcd
1. watcher goes boom

That works locally, but restarting etcd in our live test environment isn't a possibility. Is there another way to force a compaction error without restarting the server?

**Comment by jingyih** [comment]
cc @jpbetz

**Comment by 0x1mason** [comment]
Ended up making this work in our environment. Thanks.

**Comment by spzala** [comment]
@0x1mason cool and thanks for closing the issue. If it's OK, can you please share how? That will be help others in future. Thanks!
