### ISSUE TITLE
Push mulit-arch fat manifest image for etcd

### ISSUE THREAD

**Issue by mkumatag** [etcd-io/etcd#10380]
Push mulit-arch fat manifest image for etcd

I already see that we are pushing the images for following [supported architectures](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md) into the gcr: https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd?gcrImageListsize=30. So this task is to push multi-arch fat manifest pointing to all the supported platforms.

**Comment by anguslees** [comment]
Please reopen, this has not been fixed.

**Comment by gyuho** [comment]
@mkumatag Could you help with our release script?

**Comment by mkumatag** [comment]
> @mkumatag Could you help with our release script?

sure, I'm tied up this week with some project deliverables, will take a look next week if you don't mind!

**Comment by invidian** [comment]
Can we re-open it? I feel that multi-arch images should be standard these days.
