### ISSUE TITLE
[question] Does pkg/transport not support multiple tls root ca files?

### ISSUE THREAD

**Issue by Fullstop000** [etcd-io/etcd#10400]
I'm working on a distributed system and use `pkg/transport` and `raft`. When I try to set multiple root ca files in `TLSInfo`, it seems we can only set one ca file because there is only a public string type field called  `TrustedCAFile`.

After a little code digging, I find when generating a normal tls config used by `crypto/tls`, the `cafiles()` only use what is set in `TrustedCAFile` as the root CA
https://github.com/etcd-io/etcd/blob/1eee465a43720d713bb69f7b7f5e120135fdb1ac/pkg/transport/listener.go#L319-L326
https://github.com/etcd-io/etcd/blob/1eee465a43720d713bb69f7b7f5e120135fdb1ac/pkg/transport/listener.go#L371-L376
This behavior confuses me and I come up a few questions:
1. It seems there is no easy way to add root CAs if I want to create a listener by `NewTimeoutListener` or a transport by `NewTransport`
2. If I want to use the same CA for every node ( a node can be both a client and a server) and set it as `TrustedCAFile`, the client auth will be enabled which is not required
https://github.com/etcd-io/etcd/blob/1eee465a43720d713bb69f7b7f5e120135fdb1ac/pkg/transport/listener.go#L335-L338

**Comment by jingyih** [comment]
cc @wenjiaswe
