### ISSUE TITLE
a strange etcd cluster, data inconsistent 

### ISSUE THREAD

**Issue by yourlovemyall** [etcd-io/etcd#10407]
I create a cluster of etcd， now etcd1 has three keys data， but etcd2（leader） and etcd3 has one key data；
only differenet operation ： I stop the etcd process manually on etcd1 node，and modify the etcd cluster data when etcd1 is down， then I not clean the etcd1 node data dir and restart the etcd process， first I found data the same ， but now  the data different ； 

This operation may cause this exception？

**Comment by brk0v** [comment]
What about WAL logs? If I understand you right, you have to delete WAL logs as well,.

**Comment by yourlovemyall** [comment]
wal log , I use the etcd-dump-logs tool; I find three etcd machine logs the same;   So I want to know What cause the strange bug;
