### ISSUE TITLE
etcd-client: expose health endpoint directly from etcd-client

### ISSUE THREAD

**Issue by logicalhan** [etcd-io/etcd#10406]
Currently calling the health endpoint for etcd involves using the 'Get' method (ex. https://github.com/kubernetes/kubernetes/pull/72896). Exposing the a `Health` method directly on the client would make it more discoverable and obvious, while making it less likely that someone will make an error in typing out the string when trying to use the endpoint. If it is easy enough to do, we should probably just expose it. 

/cc @jpbetz

**Comment by hexfusion** [comment]
reviewing the attached PR it seems this is resolved please reopen if that is not the case.
