### ISSUE TITLE
Improve rafthttp prober error logging

### ISSUE THREAD

**Issue by markmc** [etcd-io/etcd#10404]
I got my peer and client URLs mixed up in my cluster config, and I was seeing:

```    
      W | rafthttp: health check for peer XXXX could not connect: json: cannot unmarshal number into Go value of type probing.Health
```
    
turns out $endpoint/raft/probing was returning 404. By checking the response status code, we can improve that to:

```    
      W | rafthttp: health check for peer XXXX could not connect: got 404 Not Found from http://$endpoint/raft/probing
```

**Comment by markmc** [comment]
See xiang90/probing/pull/7

**Comment by hexfusion** [comment]
@markmc if this is resolved by your PR against probing please close this issue. Thanks!

**Comment by markmc** [comment]
> @markmc if this is resolved by your PR against probing please close this issue. Thanks!

Yeah, the issue was just a reminder to revendor the mod - see PR #10423
