### ISSUE TITLE
support  key file with protected password 

### ISSUE THREAD

**Issue by johnyannj** [etcd-io/etcd#10412]
when use SSL.

the private key is not protected with password.

it is not security.

hope the etcd support key file with protected password.

**Comment by hexfusion** [comment]
@johnyannj this is kind of a usability vs security issue. On the server level if etcd needs to restart this would require operator intervention to enter password, probably not optimal. On the client that would be a different thing, have you tried it? I honestly don't know if it would work, please try and let us know if you have issues.

**Comment by hexfusion** [comment]
@johnyannj did you get a chance to try this yet?

**Comment by hexfusion** [comment]
@johnyannj kind ping.

**Comment by johnyannj** [comment]
@hexfusion I know nginx support this，  when start nginx， input the password.
