### ISSUE TITLE
clientv3:import paths error

### ISSUE THREAD

**Issue by Fengxq2014** [etcd-io/etcd#10410]
my import prefix is `go.etcd.io`, but i found type error in follow functions,i found their import prefix is `github.com/coreos`
```golang
concurrency.NewSession()
clientv3util.KeyMissing()
WatchResponse.Events
```

**Comment by Fengxq2014** [comment]
used git tag v3.3.11

**Comment by gyuho** [comment]
For 3.3.x, can you use the old import paths?

**Comment by Fengxq2014** [comment]
i use all import path `github.com/coreos` in travis-ci 
```
language: go

go:
  - "1.11.x"
  - master

script:
  - export GO111MODULE=on
```

and get type error  job log is [log](https://api.travis-ci.org/v3/job/477705387/log.txt)
