### ISSUE TITLE
ETCD Documentation on etcd version skew seems lacking

### ISSUE THREAD

**Issue by imkin** [etcd-io/etcd#10417]
@wenjiaswe pointed me to the version support page in the etcd documentation [here](https://github.com/etcd-io/etcd/blob/master/Documentation/branch_management.md). 

[This] (https://github.com/etcd-io/etcd/pull/8805) is actually well explained but the github-issues are not well indexed and the default etcd documentation should be able to define this clearly.

I discussed with @wenjiaswe and @gyuho during kubecon amongst few others and agreed that this does deserve our attention.

/cc @wenjiaswe @gyuho

**Comment by imkin** [comment]
Some of the things that we could address here are.

- define and declare usage of semver early and use the semver vocabulary in the rest of the doc.
- split the release process from the support policy.
- explain the supported upgrade path. 
- adopt the examples from [here] (https://github.com/etcd-io/etcd/pull/8805) if necessary.

**Comment by hexfusion** [comment]
@imkin would you be interested in spear heading this in a PR we can review and move from there? This looks great to me, not sure if anyone else would like to chime in.

**Comment by imkin** [comment]
@hexfusion yes this is something I could take a look at thanks.

**Comment by wenjiaswe** [comment]
Thanks @imkin ! 
xref: 
https://github.com/kubernetes/website/issues/12233
https://github.com/kubernetes/kubernetes/issues/45506
