### ISSUE TITLE
Start a new select term frequently when deploy an ETCD cluster with TLS

### ISSUE THREAD

**Issue by qd19zzx** [etcd-io/etcd#10413]
Hi, I have deployed a 3 nodes cluster whith tls. But it often starts a new select term, and reports some error like:
W | rafthttp: health check for peer 604ac5c93c0a3635 could not con        nect: <nil> (prober "ROUND_TRIPPER_RAFT_MESSAGE")
E | etcdserver: publish error: etcdserver: request timed out
E | rafthttp: failed to dial 604ac5c93c0a3635 on stream Message (r        ead tcp 192.168.1.17:49978->192.168.1.18:2380: i/o timeout)
E | rafthttp: failed to write 3e96958a1e53ad47 on stream Message (        write tcp 192.168.1.17:2380->192.168.1.19:39230: write: broken pipe)

Here is the detail log: [log](https://gist.github.com/qd19zzx/3b4a562a866848a37bf0febe181a6956)

What are these errors and warnings meaning? How can I prevent them？
Although I have these errors and warnings, I use " endpoint health" to check the health of cluster, each points is healthy.

The cofigure:
 etcd --name hoping-parrot-csdc-0 
--initial-advertise-peer-urls https://hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc:2380 
--listen-peer-urls https://192.168.1.17:2380 
--listen-client-urls https://192.168.1.17:2379 
--advertise-client-urls https://hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc:2379 
--initial-cluster-token etcd-cluster-1 
--initial-cluster hoping-parrot-csdc-0=https://hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc:2380,hoping-parrot-csdc-1=https://hoping-parrot-csdc-1.hoping-parrot-csdc.default.svc:2380,hoping-parrot-csdc-2=https://hoping-parrot-csdc-2.hoping-parrot-csdc.default.svc:2380 
--initial-cluster-state new --data-dir /var/run/etcd/default.etcd 
--client-cert-auth 
--trusted-ca-file=/var/run/etcd/tls/ca-cert/..data/ca.pem 
--cert-file=/var/run/etcd/server.pem 
--key-file=/var/run/etcd/server-key.pem 
--peer-client-cert-auth 
--peer-trusted-ca-file=/var/run/etcd/tls/ca-cert/..data/ca.pem 
--peer-cert-file=/var/run/etcd/peer.pem 
--peer-key-file=/var/run/etcd/peer-key.pem

**Comment by qd19zzx** [comment]
**The info of server cert：**
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a0:6e:ec:7b:53:c7:59:0d
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=CA
        Validity
            Not Before: Jan 16 11:11:18 2019 GMT
            Not After : Jan 13 11:11:18 2029 GMT
        Subject: C=CN, ST=Shan Dong, L=Qingdao, O=NOKIA, OU=CSF, CN=server
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d0:03:35:bb:f1:78:42:03:8c:5e:66:78:25:88:
                    bc:7a:0f:27:72:7b:5f:7d:57:c5:dc:93:e9:44:0c:
                    ea:29:de:87:fd:de:d1:78:43:53:45:5e:c9:b9:d5:
                    1e:4d:84:55:31:ed:77:e9:77:5b:c5:81:07:61:f2:
                    78:b7:7b:8a:5e:bd:47:c8:b0:b5:a8:94:64:e1:73:
                    bf:08:0b:7d:72:40:51:81:94:85:f8:49:08:06:85:
                    dc:a8:ce:75:84:ce:59:41:6f:79:5e:8b:23:8d:11:
                    48:67:e9:9d:79:d3:a1:1d:98:97:5d:1b:dd:d1:53:
                    9d:e1:d9:f7:eb:aa:43:59:a6:08:bb:10:86:b8:68:
                    7a:96:2c:03:b3:98:6e:f1:1f:e3:75:2d:f4:d1:f6:
                    75:13:a9:06:35:e4:0a:ba:18:54:c4:36:79:e8:7a:
                    95:21:fa:5b:5f:b2:a6:24:91:76:10:87:a2:03:1f:
                    66:41:f3:7e:de:f3:60:12:b5:a8:62:17:b8:4c:90:
                    a9:ef:fc:f3:24:fd:71:65:e2:2b:35:23:b5:52:e1:
                    65:da:15:b6:d2:a5:dc:56:c5:39:f3:55:a8:31:7b:
                    b0:bf:09:b0:a2:d8:b8:3c:ef:82:e2:00:da:84:5b:
                    da:e0:7e:de:51:6d:65:4e:51:0f:8c:5f:13:0d:e4:
                    e8:91
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name:
                DNS:hoping-parrot-csdc.default.svc, DNS:hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc, DNS:SDC


**The info of peer cert：**
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            bf:d9:72:00:f2:0a:8c:4c
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=CA
        Validity
            Not Before: Jan 16 11:11:19 2019 GMT
            Not After : Jan 13 11:11:19 2029 GMT
        Subject: C=CN, ST=Shan Dong, L=Qingdao, O=NOKIA, OU=CSF, CN=member
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:bb:df:1a:93:0c:b6:eb:02:35:90:88:a2:94:9d:
                    28:43:f4:9d:1a:d0:26:95:13:6a:ba:53:85:e6:78:
                    83:23:64:a6:ae:90:6b:85:f2:be:75:ce:ab:2a:8d:
                    ae:1c:a3:73:7c:57:d5:75:aa:b8:71:64:98:02:e3:
                    49:af:77:c2:d3:68:c3:55:e7:c3:f3:52:20:de:a4:
                    4c:5b:60:e5:5f:23:00:43:a2:c1:75:15:7f:ba:1a:
                    3b:86:5e:ad:01:dd:09:73:6a:a0:6a:f9:a3:66:55:
                    29:07:a7:ab:94:de:3e:ed:c7:89:6c:b6:5d:4b:a3:
                    15:f9:40:79:d6:7f:e1:2f:ec:92:55:c6:f1:d7:bd:
                    dd:cd:86:e8:7b:cf:37:29:2f:c2:dc:28:df:62:fe:
                    ed:d7:72:0e:ba:d6:a3:6f:25:24:f8:03:51:ca:60:
                    9e:84:de:28:43:e4:83:44:de:0e:de:7b:05:d5:7f:
                    49:ac:78:59:b4:40:8f:ee:22:8c:77:20:97:fd:49:
                    c9:53:de:ea:df:b8:b9:84:9f:40:c9:1f:4e:8b:fa:
                    e8:06:93:f4:96:7d:ca:50:53:9e:07:79:f9:b7:8c:
                    7b:e1:f6:a3:05:ce:f9:55:e1:4f:ef:fd:b5:76:fb:
                    11:64:49:69:d5:c0:8a:0d:8c:7e:04:40:63:bb:4f:
                    43:d7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name:
                DNS:hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc, DNS:hoping-parrot-csdc-0.hoping-parrot-csdc.default.svc.cluster.local

**Comment by qd19zzx** [comment]
When the i/o timeout occur, the logs on peer 192.168.1.18:
2019-01-16 11:12:53.084906 E | etcdserver: publish error: etcdserver: request timed out
2019-01-16 11:12:53.223102 I | raft: 604ac5c93c0a3635 is starting a new election at term 20
2019-01-16 11:12:53.223143 I | raft: 604ac5c93c0a3635 became candidate at term 21
2019-01-16 11:12:53.223154 I | raft: 604ac5c93c0a3635 received MsgVoteResp from 604ac5c93c0a3635 at term 21
2019-01-16 11:12:53.223163 I | raft: 604ac5c93c0a3635 [logterm: 1, index: 3] sent MsgVote request to 765ae403b2d07686 at term 21
2019-01-16 11:12:53.223177 I | raft: 604ac5c93c0a3635 [logterm: 1, index: 3] sent MsgVote request to 3e96958a1e53ad47 at term 21
2019-01-16 11:12:54.820717 I | raft: 604ac5c93c0a3635 [term: 21] ignored a MsgVote message with lower term from 765ae403b2d07686 [term: 19]

I used domain name to generate the server and peer certificates, and this issue occurs, but when I used IP to generate the server and peer cert, the cluster works fine.

**Comment by hexfusion** [comment]
> I used domain name to generate the server and peer certificates, and this issue occurs, but when I used IP to generate the server and peer cert, the cluster works fine.

I don't see any TLS issues in the logs.

**Comment by hexfusion** [comment]
@qd19zzx can you get metrics on these members and attach them as files? you would need to do a GET against the /metrics endpoint to harvest.

**Comment by qd19zzx** [comment]
May be is related with my environment, I cannot reproduce now, thank @hexfusion for your help, I will close this issue.
