### ISSUE TITLE
purpose of NewCtxClient

### ISSUE THREAD

**Issue by vtolstov** [etcd-io/etcd#10415]
Does it possible to use NewCtxClient if i start embed etcd server?
For example i want to use etcd internally from own service, and provide tcp endpoint  for other clients?

**Comment by jingyih** [comment]
cc @wenjiaswe

**Comment by wenjiaswe** [comment]
@vtolstov I believe "Package embed provides bindings for embedding an etcd server in a program", Please checkout this doc and see if it's helpful: https://godoc.org/github.com/coreos/etcd/embed. Thanks!

**Comment by vtolstov** [comment]
I know about this doc, my question about using specific function in case of embed server

**Comment by cretz** [comment]
Can this be reopened? A question about embedded server without grpc connection is reasonable IMO.
