### ISSUE TITLE
Clarification on etcd Range API

### ISSUE THREAD

**Issue by PoojaGidaveer** [etcd-io/etcd#10447]
I am trying to understand the range API.
First I ran put api using benchmark tool with 520000 keys and then run following range command-
benchmark --endpoints=${HOST_1} --conns=100 --clients=1000  range foo --consistency=l --total=100000
Then when I curl forall keys in etcd (curl -L https://{host_id}/v3alpha/kv/range -X POST -d '{"key": "AA==", "range_end": "AA=="}'), ideally it should display 520000 keys but all I get is just 1key value.

Can you please assit here?
This is important for me because I need to run benchmarks for apiserver.

**Comment by hexfusion** [comment]
Yeah I can't say I understand what is going on with the benchmark put, fair to say `--sequential-keys` is broken. Basically it is writing 1 key N times.

```
$ etcd&
$ benchmark --endpoints=127.0.0.1:2379 --target-leader --conns=1 --clients=1 \
    put --key-size=8 --sequential-keys --total=10000 --val-size=256
```

`etcdctl get --from-key '' -w json`
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":10001,"raft_term":2},"kvs":[{"key":"AAAAAAAAAAA=","create_revision":2,"mod_revision":10001,**"version":10000**,"value":"+9Tqq9SzVJY4nyn5kBtGRHsjzZDdEiNuYjRcgboCfMuTZLEtnE3FbKhPh/Ldbpt5JwyaN8IGDKriZQgDF9TrPSq0SAWRLoa/KPzvY5goND0TjaWptvUGd9YZQ+CIRXJcTfFRUQj2caocgEGL5FuV+BoMQMT+3ecN75hzwG8lDx5dB9CKoZQ/opltVpc9zZPAS1JBmhx2u9Xsv9+pvp+xAsIaDhSbJAcjHS+R0xoGlyKVjQjKbnMejela8NxX/cwOOZxK5UPaTFz/YCKm0yC3uC65xFCVnu/hy7NDj0vnK92v5jZb8lIpqTyChLabtm62WT6+7AwHixb0ESz5jW98eQ=="}],"count":1}

**Comment by PoojaGidaveer** [comment]
Any help on how to write different keys from benchmark tool would be appreciated?

**Comment by jingyih** [comment]
Please also specify flag "--key-space-size". Otherwise I think it is defaulted to 1, therefore only 1 key is used. We probably need better documentation on this.
