### ISSUE TITLE
Add license scanning via FOSSA

### ISSUE THREAD

**Issue by caniszczyk** [etcd-io/etcd#10458]
CNCF requires projects to have license scanning for projects: https://fossa.com

We have a license with FOSSA to do it.

**Comment by jingyih** [comment]
@xiang90 @philips Could you please take a look?

**Comment by philips** [comment]
Filed a service desk request for the license @caniszczyk.

**Comment by philips** [comment]
replaced by https://github.com/etcd-io/maintainers/issues/4
