### ISSUE TITLE
boltdb hit panic: pgid above high water mark

### ISSUE THREAD

**Issue by rinsozheng** [etcd-io/etcd#10466]
## Problem: We configured one node eted cluster, and we are doing following test:
--------------------------------
1. Power off the node
2. Power on the node
3. Sleep for some time (2 minutes or so)
4. Continue the above steps for 621 times
--------------------------------

After the test, we we hit below error in ETCD log, and ETCD can not be up again.

**panic: pgid (32300) above high water mark (32300)**

goroutine 99 [running]:
github.com/coreos/etcd/vendor/github.com/boltdb/bolt.(*node).spill(0xc4201fa000, 0xc420d0db40, 0x4)
        /go_lib/src/github.com/coreos/etcd/vendor/github.com/boltdb/bolt/node.go:375 +0x631
github.com/coreos/etcd/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc4250709b8, 0xd7c34e7, 0x136e320)
        /go_lib/src/github.com/coreos/etcd/vendor/github.com/boltdb/bolt/bucket.go:541 +0x17b
github.com/coreos/etcd/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4250709a0, 0xd7c0afb, 0x136e320)
        /go_lib/src/github.com/coreos/etcd/vendor/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc42027d600, 0xedc900)
        /go_lib/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:183 +0x8b
github.com/coreos/etcd/mvcc/backend.(*batchTx).Commit(0xc42027d600)
        /go_lib/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:140 +0x66
github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc4201af140)
        /go_lib/src/github.com/coreos/etcd/mvcc/backend/backend.go:199 +0x13b
created by github.com/coreos/etcd/mvcc/backend.newBackend
        /go_lib/src/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x26a

Please let's know how to fix or workaround the issue?

# ./etcd --version
etcd Version: 3.1.9
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.8
Go OS/Arch: linux/amd64

**Comment by rinsozheng** [comment]
Related issue#7579.

**Comment by xiang90** [comment]
@rinsozheng 

can you provide a script that we can run to reproduce this problem? thanks!

**Comment by rinsozheng** [comment]
Providing...

**Comment by rinsozheng** [comment]
We are using APC to monitor the power on/off , no sure if you can run the same script in your Env. Our script is below:
--------------------------
#!/usr/bin/env python

import os
import time
import random
import sys

def reboot_cycle_snmp(number):
    i=1
    file_time = time.strftime('%Y%m%d%H%M%S',time.localtime(time.time()))

    f=open('./run.log','a+')

    #wait_time = random.randint(mintime, maxtime)
    while i < number:
        stop_line_title = "Stop at " + str(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))) + "\n"
        print (i)
        print time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))
        print >> f,stop_line_title
        snmp=os.system("snmpset -v 1 -c private X.X.X.X Y.Y.Y.Y i 2")
        time.sleep(2)

        start_line_title = "*********************** start at " + str(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))) + "\n"
        print >> f,start_line_title        
        snmp=os.system("snmpset -v 1 -c private X.X.X.X Y.Y.Y.Y i 1")
        time.sleep(1184)

        value = os.system('ping -n 1 Z.Z.Z.Z')
        if value == 0:
            print "We can ping Z.Z.Z.Z"
        else:
            print "We can NOT ping Z.Z.Z.Z"
            error_time = "Ip address Z.Z.Z.Z error at " + str(i) + "\n"
            print >>f,error_time
        i+=1
          
reboot_cycle_snmp (10000)

**Comment by rinsozheng** [comment]
This happens a lot, please take a look.

**Comment by rinsozheng** [comment]
Is there any w/a for the issue?

**Comment by WIZARD-CXY** [comment]
ok I will take a look

**Comment by WIZARD-CXY** [comment]
@rinsozheng I have saw your script, but I don't see any etcd related ops, are you putting the data into the etcd when the node is down?

**Comment by WIZARD-CXY** [comment]
does upgrade the etcd version solve the problem? I saw you are using 3.1.9

**Comment by rinsozheng** [comment]
We have not tried any newer versions for now.

**Comment by rinsozheng** [comment]
Please let's know if newer versions fix the issue, which version do you recommend?

**Comment by xiang90** [comment]
@rinsozheng Can you try etcd 3.3.11? we fixed a few issues in bbolt in that release.

**Comment by rinsozheng** [comment]
When we delete the data directory of Etcd, and re-setup the cluster, the issue disappeared, not sure if there is any dirty data caused the issue.

**Comment by WIZARD-CXY** [comment]
hmm if the data is corrupted once, it continues to be corrupted.

**Comment by rinsozheng** [comment]
Ok, not sure what possible causes for the data corruption.

**Comment by WIZARD-CXY** [comment]
The powerdown

**Comment by jingyih** [comment]
cc @jpbetz
