### ISSUE TITLE
How to ls in etcd v3?

### ISSUE THREAD

**Issue by zhufeizzz** [etcd-io/etcd#10467]
How can I ls "/config" directory to get "/a /b /c" in etcd v3?

I don't want to "get /config --prefix" and compare all keys for 10000 times.  Is there anyway to do this?

    /config
    .../a/
    .../b/
    ....../xxx # about 100000 keys
    .../c/

**Comment by maoling** [comment]
`ls` is missing in the etcd v3. the answer may be No :D

**Comment by cfc4n** [comment]
@zhufeizzz Sorry,I don't understand what you mean ,Can you explain your question more clear please?

**Comment by zhufeizzz** [comment]
> @zhufeizzz Sorry,I don't understand what you mean ,Can you explain your question more clear please?

These are my keys. I can use "ls /config" to get "a b c" in v2. But if I use "get /config --prefix" in v3, I will get 100000 keys.

```
/config/a/
/config/b/1
/config/b/2
/config/b/...  # about 100000 keys
/config/c/
```

**Comment by gyuho** [comment]
We only support prefix matching.

There is no directory hierarchy in v3.
