### ISSUE TITLE
go build failed : cannot use lg (type *"go.uber.org/zap".Logger) as type *"go.etcd.io/etcd/vendor/go.uber.org/zap".Logger in argument to snap.New

### ISSUE THREAD

**Issue by lebentle** [etcd-io/etcd#10471]
I am using go 1.12. beta and just upgraded from go 1.10.
I turned off go modules for the build.

**Comment by hexfusion** [comment]
> I turned off go modules for the build.

@lebentle I assume you are building within GOPATH? How are you building, steps to reproduce please.

**Comment by lebentle** [comment]
I am just running go build inside my go workspace

**Comment by hexfusion** [comment]
please report 

` echo ${PWD} : ${GOPATH} : ${GO111MODULE}`

**Comment by lebentle** [comment]
/usr/myworkspace/go/src/storagegrid/rsm : /usr/myworkspace/go : off

**Comment by hexfusion** [comment]
/usr/myworkspace/go/src/storagegrid/rsm`

This package is not properly using etcd as a dependency then. What are you using to manage dependencies? How does this dependency config look for etcd in your project?

**Comment by lebentle** [comment]
I have manually, put all my all the dependencies I need in my gopath and then I just rely on the import statements in my code to find etcd.  
Feb 11 17:30 github.com
Feb 11 14:29 go.etcd.io
Mar 28  2018 golang.org
 Mar 28  2018 gopkg.in
 Feb 11 17:38 go.uber.org
Jul 10  2018 storagegrid

**Comment by hexfusion** [comment]
@lebentle OK I am going to leave you with a few questions that might steer you in the right direction.

1.) What version of etcd is your project using?
2.) If you wanted to make your project portable how could you achieve that?
3.) Why is etcd looking for it's own dependencies in a vendor/ dir and why isn't it working in your project?
4.) If it was portable how can you guarantee the etcd you use in your project has the same functionality if you were to recreate it?

**Comment by lebentle** [comment]
Yea, I am silly. Figured it out. Thank.
