### ISSUE TITLE
client: panic after updating github.com/ugorji/go to v1.1.2

### ISSUE THREAD

**Issue by hnlq715** [etcd-io/etcd#10477]
go version 1.11.4

go get -v github.com/ugorji/go@v1.1.2

```
panic: codecgen version mismatch: current: 8, need 10. Re-generate file: C:/Users/liqi/go/pkg/mod/github.com/etcd-io/etcd@v3.3.12+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/etcd-io/etcd/client.init.0()
        C:/Users/liqi/go/pkg/mod/github.com/etcd-io/etcd@v3.3.12+incompatible/client/keys.generated.go:45 +0x10b
exit status 2
FAIL    git.dz11.com/vega/invokerx/dyrpc        0.167s
```

This issue was caused by https://github.com/ugorji/go/blob/master/codec/gen-helper.generated.go#L17

The latest ugorji/go's GenVersion=10 and when we update ugorji/go to the latest version like v1.1.2

etcd/client finds out GenVersion != 8, and panic comes out...

please fix this ASAP, thanks a lot

#10370

**Comment by hexfusion** [comment]
@hnlq715 The v2 client requires [regeneration](https://github.com/etcd-io/etcd/blob/master/scripts/update-clientv2.sh) when using different versions of this package. Currently we are pinned to https://github.com/etcd-io/etcd/blob/master/go.mod#L45 v1.1.1 which had some go mod issues. I see the new version apparently better handles this issue.

So the solution would be to bump to 1.1.2 and [regenerate](https://github.com/etcd-io/etcd/blob/master/scripts/update-clientv2.sh) the client keeping in mind the manual changes we made. https://github.com/etcd-io/etcd/pull/10337

Could you help us out with that and raise a PR to resolve?

**Comment by hnlq715** [comment]
Exactly, I'll handle this and raise a PR :-)

**Comment by hnlq715** [comment]
@hexfusion please check if I missed something in this PR
