### ISSUE TITLE
will key's version overflow?

### ISSUE THREAD

**Issue by madkilly** [etcd-io/etcd#10478]
**if i write a already existing key to etcd very frequently, will this key's version overflow**

kvs {
  key: "/test/pushserver/ws://test:8080/inotify"
  create_revision: 12624592
  mod_revision: 12627046
  **version: 18**
  value: "{\"serverName\":\"testserver1\",\"serverAddress\":\"ws://test:8079/inotify\",\"serverPort\":8080,\"channelSize\":0}"
  lease: 7587834067690449324
}

**Comment by xiang90** [comment]
it is uint64.
