### ISSUE TITLE
Can't add new member when has two alive member at three member cluster

### ISSUE THREAD

**Issue by buhe** [etcd-io/etcd#10499]
- Member 9548524201875151909 is down in current cluster ,and other two alive member name is same.
- We use ```etcdctl add member etcd3 xxx``` add new member , cluster return ```etcdserver: unhealthy cluster``` .

## Member list
header {
  cluster_id: 12824827105422720595
  member_id: 200167590347433653
  raft_term: 218
}
members {
  ID: 200167590347433653
  name: "etcd1"
  peerURLs: "http://11.166.83.222:2380"
  clientURLs: "http://11.166.83.222:2379"
}
members {
  ID: 7312067834619313394
  name: "etcd1"
  peerURLs: "http://10.210.190.15:2380"
  clientURLs: "http://10.210.190.15:2379"
}
members {
  ID: 9548524201875151909
  name: "etcd0"
  peerURLs: "http://11.166.83.220:2380"
  clientURLs: "http://11.166.83.220:2379"
}

## Error log

etcdserver: not healthy for reconfigure, rejecting member add {ID:d672771146958876 RaftAttributes:{PeerURLs:[http://11.166.83.221:2380]} Attributes:{Name: ClientURLs:[]}}

**Comment by hexfusion** [comment]
> etcdserver: not healthy for reconfigure, rejecting member add {ID:d672771146958876 RaftAttributes:{PeerURLs:[http://11.166.83.221:2380]} Attributes:{Name: ClientURLs:[]}}

This a feature of etcd called `strict-reconfig-check` that allows you to not make a change that would cause the cluster to lose quorum[1].

When you are planning to replace a failed member of a 3 node cluster you should remove the failed member first[2]. If I understand you report correctly you have a 3 node cluster one member failed and you are now adding another member. This would make the cluster 4 which can sustain a single failure which you already have. If you reconfigure the new member you will lose quorum. This is the reason that you remove a failed member first.. This brings you down to a 2 member cluster which if you add one and misconfigured you would just return back to where you are. 2 working 1 failed[3].

[1] [Documentation/faq.md#why-wont-etcd-accept-my-membership-changes](https://github.com/etcd-io/etcd/blob/34fcabab55585b39835820278da4de65b3463358/Documentation/faq.md#why-wont-etcd-accept-my-membership-changes)
[2] [Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine](https://github.com/etcd-io/etcd/blob/61354ff8ede7dde7839e0df987f37cda931fd740/Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine)
[3] [Documentation/faq.md#what-is-failure-tolerance](https://github.com/etcd-io/etcd/blob/61354ff8ede7dde7839e0df987f37cda931fd740/Documentation/faq.md#what-is-failure-tolerance)

**Comment by hexfusion** [comment]
@buhe did this answer your question?

**Comment by buhe** [comment]
@hexfusion thank your relay, the answer save my time.
