### ISSUE TITLE
mvcc/backend: improve code readability on Lock() and Unlock()

### ISSUE THREAD

**Issue by jingyih** [etcd-io/etcd#10505]
Recently I spent some time reading through the code in backend. I found there are places where we might have code readability issues around the locks and unlocks. This could make it difficult for contributors who are new to the code base. It also potentially makes code maintenance less easy. As an example, if ```t``` is a ```TxBatchBuffered``` structure, you will find (most of) the following calls in our current code (I also commented what the call actually is):
```	
	t.Lock()                      // (*Mutex).Lock()
	t.Unlock()                    // (*batchTxBuffered).Unlock()
	t.batchTx.Lock()              // (*Mutex).Lock()
	t.batchTx.Unlock()            // (*batchTx).Unlock()
	t.batchTx.Mutex.Lock()        // (*Mutex).Lock()
	t.batchTx.Mutex.Unlock()      // (*Mutex).Unlock()
	t.backend.readTx.Lock()       // (*readTx).mu.RLock()!!!
	t.backend.readTx.Unlock()     // (*readTx).mu.RUnlock()!!!
	t.backend.readTx.mu.Lock()    // (*RWMutex).Lock()
	t.backend.readTx.mu.Unlock()  // (*RWMutex).Unlock()
```
It is not easy to keep track of the semantics of these locks and unlocks. Among these, this might be the most interesting:
https://github.com/etcd-io/etcd/blob/17de9bd5268ae8c1e33a63113f0c6028cd21e9ba/mvcc/backend/read_tx.go#L49

At this point, I am exploring a way to refactor some of the code, so that at lease we do not have things like Lock() wrapping RLock().

Please let me know if you have comments or suggestions:)

**Comment by xiang90** [comment]
fixed by #10506
