### ISSUE TITLE
The cluster becomes inconsistent if applied entries before entries are persisted on disk using v3 api

### ISSUE THREAD

**Issue by sryanyuan** [etcd-io/etcd#10508]
First sorry for my poor english

#### What the problem is

Apply (Runs applyAll) routine and raft routine (Process the ready event from raft state machine) is running in parallel.
In a single node cluster, before the committed entries is persisted on disk (Assume the action is put and the key is k1), and after the entries applied in boltDB storage, if the node crashed, the entries was already been applied to persisted storage.
Now restart the node, we can read the k1 from the node. Add a new node to the cluster, now the cluster has 2 nodes. After the election is done, if we read the k1 from the old node, the key is readable, but if we read from the new node, the key is not exist.

Is it a bug or not a bug?

**Comment by xiang90** [comment]
can you write a script or a test case to reproduce it?

**Comment by sryanyuan** [comment]
It is hard to produce the situation that writing to WAL is slower than applying entries, so i add a sleep before writing to WAL.Following is my steps(already add sleep before writing to WAL and add a log after all entries is applied):
1. create a new single node cluster
2. put a key using v3 api, after entries applied, kill the process
3. restart the node, the boltdb has already changed, but no relative entry in WAL.
4. add a new node to the cluster. when the new node is available, we can not read the key from the new node.

It is because in single node cluster, when a propose is accept in raft state machine, the entries and committedEntries are same, rather than in multi node cluster, the committedEntries must has been persisted on disk before we getting them in ready().

**Comment by sryanyuan** [comment]
> can you write a script or a test case to reproduce it?

It is hard to produce the situation that writing to WAL is slower than applying entries, so i add a sleep before writing to WAL.Following is my steps(already add sleep before writing to WAL and add a log after all entries is applied):

1. create a new single node cluster
2. put a key using v3 api, after entries applied, kill the process
3. restart the node, the boltdb has already changed, but no relative entry in WAL.
4. add a new node to the cluster. when the new node is available, we can not read the key from the new node.

It is because in single node cluster, when a propose is accepted by raft state machine, the entries and committedEntries in ready are same, rather than in multi node cluster, the committedEntries must has been persisted on disk before we getting them in ready().

@xiang90

**Comment by xiang90** [comment]
@sryanyuan If you already why it happens, probably just submit a patch to fix it.

**Comment by sryanyuan** [comment]
@xiang90 en. I want to confirm it is a unexpected behavior in this situation first.

**Comment by xiang90** [comment]
it you can reliably reproduce it, then it is a bug.
