### ISSUE TITLE
Pagination attempt with descending order, weird results.

### ISSUE THREAD

**Issue by kromulan** [etcd-io/etcd#10511]
First i would like to say that this works correctly when working with ascending order, however with descending order i get wrong results.

**With empty etcd, generating 10 keys:**
./etcdctl.exe put 1 x
./etcdctl.exe put 2 x
./etcdctl.exe put 3 x
./etcdctl.exe put 4 x
./etcdctl.exe put 5 x
./etcdctl.exe put 6 x
./etcdctl.exe put 8 x
./etcdctl.exe put 7 x
./etcdctl.exe put 9 x

**Ascending example:**

$ ./etcdctl.exe get --keys-only '5' --from-key --order=ASCEND --limit=2
**5
6**

$ ./etcdctl.exe get --keys-only '60' --from-key --order=ASCEND --limit=2
**7
8**

As seen here, ascending example is a success.

**Descending example:**
./etcdctl.exe get --keys-only '5' --from-key --order=DESCEND --limit=2
**9
8**

./etcdctl.exe get --keys-only '80' --from-key --order=DESCEND --limit=2
**9**

As seen here this does not work properly, without limit we can see:
./etcdctl.exe get --keys-only '5' --from-key --order=DESCEND
**9
8
7
6
5**

**VERSION:
        3.3.11**

**API VERSION:
        3.3**

The way it is sorted, it will always take top two records with (limit 2).
Is there something i am missing or is there any other way to implement descending pagination.

**Comment by jingyih** [comment]
What is your expected output? It looks correct to me.

**Comment by kromulan** [comment]
> 
> 
> What is your expected output? In your etcdctl commands, the output looks correct to me.

I expect output to be:

9
8


7
6

5
4
...


But that doesn't work.

**Comment by jingyih** [comment]
Given the API provided by etcd, I am not sure if listing with pagination with descend order is possible.

**Comment by kromulan** [comment]
> 
> 
> Given the API provided by etcd, I am not sure if listing with pagination with descend order is possible.

Any suggestions how could i achieve this ? It's very frustrating that i cannot sort it backwards...

**Comment by kromulan** [comment]
So i guess this is unsolvable and the descending pagination is basically impossible on ETCD ?

**Comment by kromulan** [comment]
Half a no change,....
