### ISSUE TITLE
The "github.com\etcd-io\etcd\clientv3\kv.go" import "go.etcd.io/etcd/etcdserver/etcdserverpb" is error

### ISSUE THREAD

**Issue by YuWenHaiBo** [etcd-io/etcd#10519]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
## "github.com\etcd-io\etcd\etcdserver\etcdserverpb\rpc.pb.go" is also need to change to 
```
	mvccpb "github.com/etcd-io/etcd/mvcc/mvccpb"

	authpb "github.com/etcd-io/etcd/auth/authpb"
```

**Comment by hexfusion** [comment]
@YuWenHaiBo When you use etcd as a dependency you are using 3.3.x. This is still on the old org `github.com/coreos/etcd` . To resolve your problem please import etcd as `github.com/coreos/etcd` this will change when we release 3.4
