### ISSUE TITLE
jepsen tests against etcd

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#10529]
Just to keep track.

Will update here as we go.

/cc @aphyr @philips @xiang90 @jpbetz @hexfusion

**Comment by caniszczyk** [comment]
This is all queued up for Kyle now since the contract is executed.

Timeline for him is "Thank you! You're #5 right now, but I'm almost done with my current client, and 
I think the following ones will be asking for shorter work than usual. Rough estimate, ~4-6 months."

**Comment by philips** [comment]
Will you be available to lead the project at that point @gyuho?

xref https://github.com/etcd-io/maintainers/issues/10

**Comment by gyuho** [comment]
@philips Yes. When Kyle becomes available, will sync up with him. Thanks!

**Comment by philips** [comment]
Done! https://etcd.io/blog/jepsen-343-results/

closing.
