### ISSUE TITLE
One node could not start etcd on Debian 9

### ISSUE THREAD

**Issue by beelesnik** [etcd-io/etcd#10538]
Hello
I have three Debian 9.8 nodes and tried to set up etcd cluster. After creating cluster all three nodes works well.
For example:
`postgres@pg1:~$ export ETCDCTL_API=3
postgres@pg1:~$ ENDPOINTS=10.7.7.186:2379,10.7.7.143:2379,10.7.7.140:2379
postgres@pg1:~$ etcdctl --endpoints=$ENDPOINTS endpoint health
10.7.7.186:2379 is healthy: successfully committed proposal: took = 2.854153ms
10.7.7.143:2379 is healthy: successfully committed proposal: took = 5.160608ms
10.7.7.140:2379 is healthy: successfully committed proposal: took = 3.170217ms
postgres@pg1:~$`

I have restarted nodes and one node could not start etcd.

My configuration:
Common thing for each node:
1. etcd version
`root@pg1:~# etcd --version
etcd Version: 3.3.12
Git SHA: d57e8b8
Go Version: go1.10.8
Go OS/Arch: linux/amd64
root@pg1:~# cat /etc/debian_version
9.8`
2. Systemd service for etcd:
`root@pg1:~# cat /lib/systemd/system/etcd.service
[Unit]
Description=etcd key-value store
Documentation=https://github.com/coreos/etcd
After=network.target
[Service]
User=postgres
Type=notify
ExecStart=/usr/local/bin/etcd --config-file /etc/etcd.conf
Restart=always
RestartSec=10s
LimitNOFILE=40000
[Install]
WantedBy=multi-user.target
root@pg1:~#`

3.1 etcd config on working first node:
`root@pg1:~# cat /etc/etcd.conf
name: pg1
data-dir: /db/etcd
initial-advertise-peer-urls: http://10.7.7.186:2380
listen-peer-urls: http://10.7.7.186:2380
listen-client-urls: http://10.7.7.186:2379,http://localhost:2379
advertise-client-urls: http://10.7.7.186:2379
initial-cluster: "pg1=http://10.7.7.186:2380,pg2=http://10.7.7.143:2380,pg3=http://10.7.7.140:2380"
initial-cluster-state: new
initial-cluster-token: token-01
root@pg1:~#`

3.2 etcd config on not working third node:
`root@pg3:~# cat /etc/etcd.conf
name: pg3
data-dir: /db/etcd
initial-advertise-peer-urls: http://10.7.7.140:2380
listen-peer-urls: http://10.7.7.140:2380
listen-client-urls: http://10.7.7.140:2379,http://localhost:2379
advertise-client-urls: http://10.7.7.140:2379
initial-cluster: "pg1=http://10.7.7.186:2380,pg2=http://10.7.7.143:2380,pg3=http://10.7.7.140:2380"
initial-cluster-state: new
initial-cluster-token: token-01
root@pg3:~#`

4. Logs from not working third node while service starting:
`root@pg3:~# date
Wed Mar 13 06:37:27 EDT 2019
root@pg3:~# systemctl start etcd
Job for etcd.service failed because a timeout was exceeded.
See "systemctl status etcd.service" and "journalctl -xe" for details.
root@pg3:~# journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit etcd.service has finished shutting down.
Mar 13 06:39:12 pg3 systemd[1]: Starting etcd key-value store...
-- Subject: Unit etcd.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit etcd.service has begun starting up.
Mar 13 06:39:12 pg3 etcd[1108]: Loading server configuration from "/etc/etcd.conf"
Mar 13 06:39:12 pg3 etcd[1108]: etcd Version: 3.3.12
Mar 13 06:39:12 pg3 etcd[1108]: Git SHA: d57e8b8
Mar 13 06:39:12 pg3 etcd[1108]: Go Version: go1.10.8
Mar 13 06:39:12 pg3 etcd[1108]: Go OS/Arch: linux/amd64
Mar 13 06:39:12 pg3 etcd[1108]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Mar 13 06:39:12 pg3 etcd[1108]: the server is already initialized as member before, starting as etcd member...
Mar 13 06:39:12 pg3 etcd[1108]: listening for peers on http://10.7.7.140:2380
Mar 13 06:39:12 pg3 etcd[1108]: listening for client requests on 10.7.7.140:2379
Mar 13 06:39:12 pg3 etcd[1108]: listening for client requests on localhost:2379
Mar 13 06:39:12 pg3 etcd[1108]: name = pg3
Mar 13 06:39:12 pg3 etcd[1108]: data dir = /db/etcd
Mar 13 06:39:12 pg3 etcd[1108]: member dir = /db/etcd/member
Mar 13 06:39:12 pg3 etcd[1108]: heartbeat = 100ms
Mar 13 06:39:12 pg3 etcd[1108]: election = 1000ms
Mar 13 06:39:12 pg3 etcd[1108]: snapshot count = 100000
Mar 13 06:39:12 pg3 etcd[1108]: advertise client URLs = http://10.7.7.140:2379
Mar 13 06:39:12 pg3 etcd[1108]: restarting member 4191ae1e94f51d04 in cluster 18333850f5498283 at commit index 19
Mar 13 06:39:12 pg3 etcd[1108]: 4191ae1e94f51d04 became follower at term 72
Mar 13 06:39:12 pg3 etcd[1108]: newRaft 4191ae1e94f51d04 [peers: [], term: 72, commit: 19, applied: 0, lastindex: 19, lastterm: 42]
Mar 13 06:39:12 pg3 etcd[1108]: simple token is not cryptographically signed
Mar 13 06:39:12 pg3 etcd[1108]: starting server... [version: 3.3.12, cluster version: to_be_decided]
Mar 13 06:39:12 pg3 etcd[1108]: added member 2fb03ee8db19deb8 [http://10.7.7.143:2380] to cluster 18333850f5498283
Mar 13 06:39:12 pg3 etcd[1108]: starting peer 2fb03ee8db19deb8...
Mar 13 06:39:12 pg3 etcd[1108]: started HTTP pipelining with peer 2fb03ee8db19deb8
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 2fb03ee8db19deb8 (writer)
Mar 13 06:39:12 pg3 etcd[1108]: started peer 2fb03ee8db19deb8
Mar 13 06:39:12 pg3 etcd[1108]: added peer 2fb03ee8db19deb8
Mar 13 06:39:12 pg3 etcd[1108]: added member 4191ae1e94f51d04 [http://10.7.7.140:2380] to cluster 18333850f5498283
Mar 13 06:39:12 pg3 etcd[1108]: added member 9a16a72710fbb7d0 [http://10.7.7.186:2380] to cluster 18333850f5498283
Mar 13 06:39:12 pg3 etcd[1108]: starting peer 9a16a72710fbb7d0...
Mar 13 06:39:12 pg3 etcd[1108]: started HTTP pipelining with peer 9a16a72710fbb7d0
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 9a16a72710fbb7d0 (writer)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 2fb03ee8db19deb8 (writer)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 2fb03ee8db19deb8 (stream MsgApp v2 reader)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 2fb03ee8db19deb8 (stream Message reader)
Mar 13 06:39:12 pg3 etcd[1108]: started peer 9a16a72710fbb7d0
Mar 13 06:39:12 pg3 etcd[1108]: added peer 9a16a72710fbb7d0
Mar 13 06:39:12 pg3 etcd[1108]: set the initial cluster version to 3.0
Mar 13 06:39:12 pg3 etcd[1108]: enabled capabilities for version 3.0
Mar 13 06:39:12 pg3 etcd[1108]: updated the cluster version from 3.0 to 3.3
Mar 13 06:39:12 pg3 etcd[1108]: enabled capabilities for version 3.3
Mar 13 06:39:12 pg3 etcd[1108]: peer 2fb03ee8db19deb8 became active
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 2fb03ee8db19deb8 (stream MsgApp v2 writer)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 2fb03ee8db19deb8 (stream Message writer)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 9a16a72710fbb7d0 (writer)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 9a16a72710fbb7d0 (stream MsgApp v2 reader)
Mar 13 06:39:12 pg3 etcd[1108]: started streaming with peer 9a16a72710fbb7d0 (stream Message reader)
Mar 13 06:39:12 pg3 etcd[1108]: raft.node: 4191ae1e94f51d04 elected leader 9a16a72710fbb7d0 at term 72
Mar 13 06:39:12 pg3 etcd[1108]: peer 9a16a72710fbb7d0 became active
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 9a16a72710fbb7d0 (stream MsgApp v2 writer)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 9a16a72710fbb7d0 (stream Message writer)
Mar 13 06:39:12 pg3 etcd[1108]: 4191ae1e94f51d04 initialzed peer connection; fast-forwarding 8 ticks (election ticks 10) with 2 active peer(s)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 2fb03ee8db19deb8 (stream Message reader)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 9a16a72710fbb7d0 (stream MsgApp v2 reader)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 2fb03ee8db19deb8 (stream MsgApp v2 reader)
Mar 13 06:39:12 pg3 etcd[1108]: established a TCP streaming connection with peer 9a16a72710fbb7d0 (stream Message reader)
Mar 13 06:39:19 pg3 etcd[1108]: publish error: etcdserver: request timed out, possibly due to connection lost
Mar 13 06:39:26 pg3 etcd[1108]: publish error: etcdserver: request timed out
Mar 13 06:39:33 pg3 etcd[1108]: publish error: etcdserver: request timed out
Mar 13 06:39:40 pg3 etcd[1108]: publish error: etcdserver: request timed out
lines 1140-1210/1210 (END)`

5. Logs from working first node while third node trying to start etcd:
`root@pg1:~# journalctl -xe
Mar 13 06:35:01 pg1 CRON[1643]: pam_unix(cron:session): session closed for user root
Mar 13 06:35:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:35:24 pg1 etcd[364]: failed to read 4191ae1e94f51d04 on stream MsgApp v2 (unexpected EOF)
Mar 13 06:35:24 pg1 etcd[364]: peer 4191ae1e94f51d04 became inactive (message send to peer failed)
Mar 13 06:35:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:35:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:35:25 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:25 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:29 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:29 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:30 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:35:33 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:33 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:35:34 pg1 etcd[364]: peer 4191ae1e94f51d04 became active
Mar 13 06:35:34 pg1 etcd[364]: failed to dial 4191ae1e94f51d04 on stream MsgApp v2 (peer 4191ae1e94f51d04 failed to find local node 9a16a72710fbb7d0)
Mar 13 06:35:34 pg1 etcd[364]: peer 4191ae1e94f51d04 became inactive (message send to peer failed)
Mar 13 06:35:34 pg1 etcd[364]: peer 4191ae1e94f51d04 became active
Mar 13 06:35:34 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:35:34 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:35:34 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:35:34 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:37:04 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:37:04 pg1 etcd[364]: failed to read 4191ae1e94f51d04 on stream Message (unexpected EOF)
Mar 13 06:37:04 pg1 etcd[364]: peer 4191ae1e94f51d04 became inactive (message send to peer failed)
Mar 13 06:37:04 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:37:05 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:37:05 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:05 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:09 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:09 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:10 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:37:13 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:13 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:13 pg1 etcd[364]: health check for peer 4191ae1e94f51d04 could not connect: dial tcp 10.7.7.140:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Mar 13 06:37:13 pg1 etcd[364]: health check for peer 4191ae1e94f51d04 could not connect: dial tcp 10.7.7.140:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Mar 13 06:37:15 pg1 etcd[364]: peer 4191ae1e94f51d04 became active
Mar 13 06:37:15 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:37:15 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:37:15 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:37:15 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:37:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:37:24 pg1 etcd[364]: failed to read 4191ae1e94f51d04 on stream MsgApp v2 (unexpected EOF)
Mar 13 06:37:24 pg1 etcd[364]: peer 4191ae1e94f51d04 became inactive (message send to peer failed)
Mar 13 06:37:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:37:24 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:37:25 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:25 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:28 pg1 ntpd[410]: 149.210.142.45 local addr 10.7.7.186 -> <null>
Mar 13 06:37:29 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:29 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:37:30 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:37:32 pg1 etcd[364]: peer 4191ae1e94f51d04 became active
Mar 13 06:37:32 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:37:32 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:37:32 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:37:32 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:39:02 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:39:02 pg1 etcd[364]: failed to read 4191ae1e94f51d04 on stream Message (unexpected EOF)
Mar 13 06:39:02 pg1 etcd[364]: peer 4191ae1e94f51d04 became inactive (message send to peer failed)
Mar 13 06:39:02 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:39:02 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:39:06 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:39:06 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:39:08 pg1 etcd[364]: lost the TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
Mar 13 06:39:10 pg1 etcd[364]: failed to reach the peerURL(http://10.7.7.140:2380) of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:39:10 pg1 etcd[364]: cannot get the version of member 4191ae1e94f51d04 (Get http://10.7.7.140:2380/version: dial tcp 10.7.7.140:2380: connect: connection refused)
Mar 13 06:39:12 pg1 etcd[364]: peer 4191ae1e94f51d04 became active
Mar 13 06:39:12 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 reader)
Mar 13 06:39:12 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message reader)
Mar 13 06:39:12 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream Message writer)
Mar 13 06:39:12 pg1 etcd[364]: established a TCP streaming connection with peer 4191ae1e94f51d04 (stream MsgApp v2 writer)
lines 1535-1605/1605 (END)`

Right now I have no any firewall configuration because it is test environment.

Please describe what should be done to overcome this issue

**Comment by beelesnik** [comment]
I have discovered that if I create three node cluster and it was successfully started the problem is definitely in the third node.
I could stop/start etcd service on first and second node without any issues. But if I stop the etcd service on the third node it could not start again with same log messages.

**Comment by hexfusion** [comment]
>  dial tcp 10.7.7.140:2380: connect: connection refused

This error is literal, what is the output of `nc -zv 10.7.7.140 2379-2380` from a working node?

**Comment by beelesnik** [comment]
> > dial tcp 10.7.7.140:2380: connect: connection refused
> 
> This error is literal, what is the output of `nc -zv 10.7.7.140 2379-2380` from a working node?

Without this command I could say that  10.7.7.140 is not listening ports 2379-2380 because etcd daemon is not started (it is started only once and could not start after daemon restart).
And real problem is Why the daemon is not started?

BTW, I have rewritten 
`initial-cluster: "pg1=http://10.7.7.186:2380,pg3=http://10.7.7.140:2380,pg2=http://10.7.7.143:2380"` to 
`initial-cluster: "pg1=http://10.7.7.186:2380,pg2=http://10.7.7.143:2380,pg3=http://10.7.7.140:2380"` and issue was gone.
But if I place third node to last position the issue is occured again :(

**Comment by hexfusion** [comment]
I can not reproduce. Here is a docker compose which will setup a 3 node cluster. 

https://gist.github.com/hexfusion/7c9cc03a9c76522982759ef344a6da24

`docker-compose up -d`

```
$ docker  ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                         PORTS                                              NAMES
920cafa3a80a        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    2 seconds ago       Up 1 second                     0.0.0.0:34287->2379/tcp, 0.0.0.0:34286->2380/tcp   3-node_etcd-2_1
77cb777d6428        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    2 seconds ago       Up 2 seconds                    0.0.0.0:34285->2379/tcp, 0.0.0.0:34284->2380/tcp   3-node_etcd-1_1
ca05b763e581        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    2 seconds ago       Up 2 seconds                    0.0.0.0:34283->2379/tcp, 0.0.0.0:34282->2380/tcp   3-node_etcd-3_1
```
I now change the order
 ETCD_INITIAL_CLUSTER: etcd-1=http://etcd-1:2380,etcd-3=http://etcd-3:2380,etcd-2=http://etcd-2:2380
vs
ETCD_INITIAL_CLUSTER: etcd-3=http://etcd-3:2380,etcd-2=http://etcd-2:2380,etcd-1=http://etcd-1:2380

`docker-compose up -d`
verify single container restarted
```
$ docker  ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED              STATUS                          PORTS                                              NAMES
cf91cf25fefc        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    4 seconds ago        Up 3 seconds                    0.0.0.0:34291->2379/tcp, 0.0.0.0:34290->2380/tcp   3-node_etcd-3_1
920cafa3a80a        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    About a minute ago   Up About a minute               0.0.0.0:34287->2379/tcp, 0.0.0.0:34286->2380/tcp   3-node_etcd-2_1
77cb777d6428        gcr.io/etcd-development/etcd:v3.3.12   "/usr/local/bin/etcd"    About a minute ago   Up About a minute               0.0.0.0:34285->2379/tcp, 0.0.0.0:34284->2380/tcp   3-node_etcd-1_1
```
```
docker-compose logs etcd-3
Attaching to 3-node_etcd-3_1
etcd-3_1  | 2019-03-22 12:55:15.823575 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://etcd-3:2379,http://127.0.0.1:2379
etcd-3_1  | 2019-03-22 12:55:15.823654 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
etcd-3_1  | 2019-03-22 12:55:15.823661 I | pkg/flags: recognized and used environment variable ETCD_DEBUG=1
etcd-3_1  | 2019-03-22 12:55:15.823679 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-3:2380
etcd-3_1  | 2019-03-22 12:55:15.823685 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-1=http://etcd-1:2380,etcd-3=http://etcd-3:2380,etcd-2=http://etcd-2:2380
```
```
$ etcdctl --endpoints 172.30.21.41:2379,172.30.21.42:2379,172.30.21.43:2379 endpoint status -w table
+-------------------+------------------+---------+---------+-----------+-----------+------------+
|     ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.30.21.41:2379 | bf42fc71aea495aa |  3.3.12 |   20 kB |     false |         2 |          9 |
| 172.30.21.42:2379 | 3306e07331346cc3 |  3.3.12 |   20 kB |      true |         2 |          9 |
| 172.30.21.43:2379 | aa81aa5294b3b572 |  3.3.12 |   20 kB |     false |         2 |          9 |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
```
After the cluster is bootstrapped initial-cluster is not a runtime flag, meaning no matter what the value is the cluster goes by the member list persisted in the state machine. To verify this you can comment out the flag or put in any members you like. So I am not sure what is happening in your example. It feels like there are 2 clusters or the `data-dir` is not persisted somehow.

**Comment by beelesnik** [comment]
Think it could be VirtualBox fault.
Closed
