### ISSUE TITLE
Anonymous access denied to v3.3.12 release assets in Google Cloud Storage

### ISSUE THREAD

**Issue by mhuxtable** [etcd-io/etcd#10532]
I am unable to download and install the [v3.3.12 release](https://github.com/etcd-io/etcd/releases/tag/v3.3.12) by following the Linux instructions on the release page. When attempting to do so, the download from Google Cloud Storage fails with the following permission error:

```
vagrant@stretch:~$ curl https://storage.googleapis.com/etcd/v3.3.12/etcd-v3.3.12-linux-amd64.tar.gz
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to etcd/v3.3.12/etcd-v3.3.12-linux-amd64.tar.gz.</Details></Error>
```

The equivalent download for `v3.3.11` works correctly, as does GitHub for 3.3.12.

**Comment by hexfusion** [comment]
@mhuxtable please try again

**Comment by mhuxtable** [comment]
Looks better, thanks.
