### ISSUE TITLE
document how to give permissions for locks

### ISSUE THREAD

**Issue by jsfrerot** [etcd-io/etcd#10544]
It took me a while to find how to grant permission for locks to a role. Since this isn't documented it should be added. Here is how I've been able to grant permission

`etcdctl role grant-permission my_rw_locks --prefix=true readwrite _locks//my_service_locks/`

This will allow locks to be created under /my_service_locks/*

**Comment by hexfusion** [comment]
@jsfrerot this is great info would you mind raising a PR and adding this here? https://github.com/etcd-io/etcd/tree/master/etcdctl#lock-options-lockname-command-arg1-arg2-

**Comment by s-m-sufyian** [comment]
Is this still valid ? I want to work on it as a starter issue

**Comment by alwindoss** [comment]
I have fixed and raised a PR [11571](https://github.com/etcd-io/etcd/pull/11575)
