### ISSUE TITLE
(no bugs, just question) about the backup at the k8s cluster

### ISSUE THREAD

**Issue by zhangguanzhang** [etcd-io/etcd#10549]
When I restore the etcd , Should I stop the process of the `etcd` and the `kube-apiserver`?

**Comment by zhangguanzhang** [comment]
use the db files of the `snapshot save` command to restore

**Comment by hexfusion** [comment]
> When I restore the etcd , Should I stop the process of the etcd and the kube-apiserver?

restore operation assumes that the cluster has been destroyed or at least restoring quorum is not possible [1]. In this case etcd would be down and kube. Restore is not a single member opperation if you are adding a new new member for a failed member you would use MemberRemove/MemberAdd [2[.

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster
[2] https://github.com/etcd-io/etcd/blob/b1e8218072baf8c1f5cf890b41b0ffb6a5375f77/Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine

**Comment by zhangguanzhang** [comment]
Thanks, I did it successed
