### ISSUE TITLE
Explore possibility to enable serving etcd health check on a different port so we can have different tls requirement for etcd server and etcd health

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#10545]
**Problem description:**
If we enable TLS between etcd server and its client, for example, kube-apiserver, etcd healthness check will require tls credential as well. For use cases where we do not want anyone to access etcd data, but still want to expose healthness check with no credential required, it won't work. 

**Proposed solution:**
How about enabling serving the healthcheck on a separate port so if needed, we can access etcd health without TLS?

xref: https://github.com/kubernetes/kubernetes/pull/74690#issuecomment-473392999

**Comment by jingyih** [comment]
The metrics and health are served separately from the clients. Currently we use clientTLS when serving metrics, but it is possible to have different TLS configurations for metrics.

Reference:
1. Metrics and health are served separately:
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/embed/etcd.go#L231-L236

2. ClientTLS is used when serving metrics and health:
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/embed/etcd.go#L755-L765

3. But it is possible to have a separate TLS for metrics and health:
#10504 Allow to use own certificate for metrics endpoint

**Comment by wenjiaswe** [comment]
Thanks @jingyih ! I think [--listen-metrics-urls](https://github.com/etcd-io/etcd/pull/8242) (available in 3.3) is probably gonna serve my need. I will try it out.

**Comment by wenjiaswe** [comment]
/close
--listen-metrics-urls works. Thanks!
