### ISSUE TITLE
It's unsafe to remove leader from a 2-node cluster

### ISSUE THREAD

**Issue by guoger** [etcd-io/etcd#10563]
While removing the leader from a 2-node cluster, if the second round of message in Raft protocol is lost, i.e. network partition, leader continues applying ConfChange and terminates itself, however the follower never gets to commit/apply that ConfChange, and the **cluster is basically not functional onwards**. Basically, I don't think etcd currently implements raft thesis 4.2.2 strictly, in particular:
> This approach leads to two implications about decision-making that are not particularly harmful but may be surprising. First, there will be a period of time (while it is committing Cnew) when a leader can manage a cluster that does not include itself; it replicates log entries but does not count itself in majorities. Second, a server that is not part of its own latest configuration should still start new elections, as it might still be needed until the Cnew entry is committed (as in Figure 4.6). It does not count its own vote in elections unless it is part of its latest configuration.

I also believe this problem could be generalized to 3/4 -> 2/3 transition, where 3/4 denotes 3 active members out of 4 total members.

I'd highly appreciate if someone could confirm this observation! thx in advance!

@xiang90 @gyuho @ongardie

**Comment by guoger** [comment]
User can still recover the node by starting with `--force-new-cluster` turned on, but i'm wondering if this is something intended by design:
> thesis 4.2.2 is not implemented to avoid the corner case, and if it does happen, user is expected to bring the node back to work by this config option.

**Comment by jingyih** [comment]
Looks like we have an implementation note matching your observation:
https://github.com/etcd-io/etcd/tree/master/raft#implementation-notes

**Comment by guoger** [comment]
@jingyih ahh, I should've read the implementation note more carefully before diving into code. Thanks!
