### ISSUE TITLE
[question:]hostname/DNS became unresolvable at the time of Leader election,what will etcd do?

### ISSUE THREAD

**Issue by maoling** [etcd-io/etcd#10575]
For example:
- Hostname/DNS became unresolvable and cannot listen to the leader election port at the time of Leader election,what will etcd do?
- A retry mechanism for a configurable retry time or something else?

**Comment by hexfusion** [comment]
> * Hostname/DNS became unresolvable and cannot listen to the leader election port at the time of Leader election,what will etcd do?

Assuming 3 node cluster. For leader election to succeed a candidate in a new term must receive a majority of votes in this case 2. The first vote comes from itself and RequestVote RPCs are sent to other members. If DNS goes down and peer members are setup to use FQDN then the election will not succeed. In this case the election timeout will occur and a new election will take place, forever this loop will continue. So each member will become a candidate.

The cluster will lose quorum and be in an election loop until DNS is restored. Once DNS is restored eventually an election will have successes and etcd will continue on.

> * A retry mechanism for a configurable retry time or something else?

Not sure I follow, etcd has many timeouts in this case election timeout will ensure retry.

**Comment by Lagrang** [comment]
As I understand code correctly, issue described in [ZOOKEEPER-3320](https://github.com/apache/zookeeper/pull/863) also can happen in etcd. 
I found that rafthttp.NewListener create peer listeners without retries. And other code which call it also doesn't contain retries. I can wrong, I'm not very familiar with etcd codebase.

**Comment by maoling** [comment]
I get what I want. Thanks for your involvement @hexfusion  and @Lagrang .
Let me close this issue.
