### ISSUE TITLE
Step blocks indefinitely

### ISSUE THREAD

**Issue by danielmai** [etcd-io/etcd#10585]
I'm seeing a Raft member not receiving vote messages and it's stuck at Step indefinitely. I'm not sure why this is happening.

Here's the goroutine stack showing the blockage (and the [full goroutine stack](https://github.com/etcd-io/etcd/files/3006097/goroutine-alpha1.txt)):
```
goroutine 566 [select, 18 minutes]:
github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft.(*node).stepWithWaitOption(0xc02df85da0, 0x161d460, 0xc016f53dd0, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc025b5e0f0, ...)
	/home/dmai/go/src/github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft/node.go:496 +0x1be
github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft.(*node).step(0xc02df85da0, 0x161d460, 0xc016f53dd0, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc025b5e0f0, ...)
	/home/dmai/go/src/github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft/node.go:471 +0x85
github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft.(*node).Step(0xc02df85da0, 0x161d460, 0xc016f53dd0, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc025b5e0f0, ...)
	/home/dmai/go/src/github.com/dgraph-io/dgraph/vendor/go.etcd.io/etcd/raft/node.go:459 +0xb0
github.com/dgraph-io/dgraph/conn.(*RaftServer).RaftMessage(0x204e2c0, 0x16223e0, 0xc016f5c8f0, 0x161d6a0, 0x204e2c0)
	/home/dmai/go/src/github.com/dgraph-io/dgraph/conn/raft_server.go:242 +0x41c
github.com/dgraph-io/dgraph/protos/pb._Raft_RaftMessage_Handler(0x13f59e0, 0x204e2c0, 0x1620820, 0xc0003df1e0, 0x206dba0, 0xc016f53dd0)
	/home/dmai/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:4039 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00017e540, 0x1623820, 0xc050b8e200, 0xc00043ab00, 0xc0003d1bf0, 0x1f9f6c0, 0x0, 0x0, 0x0)
	/home/dmai/go/src/google.golang.org/grpc/server.go:1160 +0x9dc
google.golang.org/grpc.(*Server).handleStream(0xc00017e540, 0x1623820, 0xc050b8e200, 0xc00043ab00, 0x0)
	/home/dmai/go/src/google.golang.org/grpc/server.go:1253 +0x12aa
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc048332030, 0xc00017e540, 0x1623820, 0xc050b8e200, 0xc00043ab00)
	/home/dmai/go/src/google.golang.org/grpc/server.go:680 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/dmai/go/src/google.golang.org/grpc/server.go:678 +0xa1
```

**Comment by manishrjain** [comment]
My understanding is that, step gets a `MsgProp` message after the leader has stepped down, causing `n.propc` to be nil. So, `stepWithWaitOption` ends up blocking on doing a select case on trying to push to a nil channel, waiting to context timeout, or node being stopped. We use background context, so this blocks forever.

**Comment by manishrjain** [comment]
Would be good to understand why this can happen.

**Comment by sumithreddy** [comment]
@manishrjain how did you get around this issue ? Did you add a context with timeout?

**Comment by manishrjain** [comment]
I'm guessing here, it's been a while -- I think this was probably due to sending messages around slightly out of order. Really important to maintain the ordering of messages over the network.

**Comment by sumithreddy** [comment]
Thanks @manishrjain. This is what I see in my case:
1) node 1 gives out leadership without reboot.
2) immediately after that it tries to process the request which was in its queue (MsgProp)
3) which hangs indefinitely since I am not using context with timeout.

Do you clear out the msg channels when a member looses its leadership ?
