### ISSUE TITLE
Leader does not respond to ReadIndex message from learner

### ISSUE THREAD

**Issue by jingyih** [etcd-io/etcd#10589]
In a cluster with 1 leader and 1 learner (quorum == 1), a linearizable read request sent to learner node will timeout. More detailed logs can be found [in this issue](https://github.com/jingyih/etcd/issues/7). Basically, the learner node will timeout after sending out ReadIndex message to leader and waiting for leader's response.

**What is supposed to happen**

1. A linearizable read request notifies the `LinearizableReadLoop`.
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/etcdserver/v3_server.go#L94-L96

2. Upon being notified, `LinearizableReadLoop` sends a ReadIndex request to local raft node. In this case, this node is a raft learner.
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/etcdserver/v3_server.go#L651

3. The learner node, also as a follower, upon receiving ReadIndex message, forwards the message to leader.
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1291-L1297

4. Leader receives the message, sends out heartbeat to ensure it is not deposed by a more recent leader (for simplicity let's only talk about `ReadOnlySafe` option)
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1025-L1039

5. Eventually leader sends out ReadIndex response after all safety checks are passed.
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1142

**What went wrong**
In a cluster with 1 leader and 1 learner, raft quorum is 1. In step 4, leader automatically assumes the ReadIndex request is from local, appends ReadIndex information to local readState, and return. Therefore in this case, the learner will not get a response from leader, which leads to request timeout.
https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1047-L1049

**Comment by jingyih** [comment]
PTAL @xiang90 @gyuho 
cc @WIZARD-CXY

**Comment by jingyih** [comment]
An unit test to reproduce:
```
func TestReadOnlyOptionSafeWithLearner(t *testing.T) {
	a := newTestLearnerRaft(1, []uint64{1}, []uint64{2}, 10, 1, NewMemoryStorage())
	b := newTestLearnerRaft(2, []uint64{1}, []uint64{2}, 10, 1, NewMemoryStorage())

	nt := newNetwork(a, b)
	setRandomizedElectionTimeout(b, b.electionTimeout+1)

	for i := 0; i < b.electionTimeout; i++ {
		b.tick()
	}
	nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})

	if a.state != StateLeader {
		t.Fatalf("state = %s, want %s", a.state, StateLeader)
	}

	tests := []struct {
		sm        *raft
		proposals int
		wri       uint64
		wctx      []byte
	}{
		{a, 10, 11, []byte("ctx1")},
		{b, 0, 11, []byte("ctx2")},
		{a, 10, 21, []byte("ctx3")},
		{b, 0, 21, []byte("ctx4")},
	}

	for i, tt := range tests {
		for j := 0; j < tt.proposals; j++ {
			nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgProp, Entries: []pb.Entry{{}}})
		}

		nt.send(pb.Message{From: tt.sm.id, To: tt.sm.id, Type: pb.MsgReadIndex, Entries: []pb.Entry{{Data: tt.wctx}}})

		r := tt.sm
		if len(r.readStates) == 0 {
			t.Fatalf("#%d: len(readStates) = 0, want non-zero", i)
		}
		rs := r.readStates[0]
		if rs.Index != tt.wri {
			t.Errorf("#%d: readIndex = %d, want %d", i, rs.Index, tt.wri)
		}

		if !bytes.Equal(rs.RequestCtx, tt.wctx) {
			t.Errorf("#%d: requestCtx = %v, want %v", i, rs.RequestCtx, tt.wctx)
		}
		r.readStates = nil
	}
}
```

Result:
```
--- FAIL: TestReadOnlyOptionSafeWithLearner (0.00s)
    raft_test.go:XXXX: #1: len(readStates) = 0, want non-zero
```

**Comment by jingyih** [comment]
cc @jpbetz

**Comment by jingyih** [comment]
A simple fix **for this scenario** is to replace the following condition with `len(r.prs) + len(r.learnerPrs) > 1`. But I am not sure if this is proper.

https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1026

**Comment by WIZARD-CXY** [comment]
👍

**Comment by jingyih** [comment]
Now that I went through it, I realized there might be a simple fix... Will send out a PR shortly.

**Comment by johncming** [comment]
@jingyih 

remove the limit of `quorum` , is it more appropriate? 

A cluster must have at least one voter,  so check `quorum` during processing `MsgReadIndex` msg.

**Comment by jingyih** [comment]
> @jingyih @xiang90
> 
> remove the limit of `quorum` , is it more appropriate in this case?
> 
> [etcd/raft/raft.go](https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1025-L1026)
> 
> Lines 1025 to 1026 in [9c2b88d](/etcd-io/etcd/commit/9c2b88d783411d2e100385ca5ded21cd5796167c)
> 
>  case pb.MsgReadIndex: 
>  	if r.quorum() > 1 { 
> A cluster must have at least one quorum, so checking `quorum` during processing `MsgReadIndex` msg can be removed.

Not sure I understand your reasoning fully. Can you be more elaborate in the case when quorum is 1?

**Comment by johncming** [comment]
> > @jingyih @xiang90
> > remove the limit of `quorum` , is it more appropriate in this case?
> > [etcd/raft/raft.go](https://github.com/etcd-io/etcd/blob/9c2b88d783411d2e100385ca5ded21cd5796167c/raft/raft.go#L1025-L1026)
> > Lines 1025 to 1026 in [9c2b88d](/etcd-io/etcd/commit/9c2b88d783411d2e100385ca5ded21cd5796167c)
> > case pb.MsgReadIndex:
> > if r.quorum() > 1 {
> > A cluster must have at least one quorum, so checking `quorum` during processing `MsgReadIndex` msg can be removed.
> 
> Not sure I understand your reasoning fully. Can you be more elaborate in the case when quorum is 1?

When quorum is 1, it can be divided into two cases:

First, there has no learner, the number of vote nodes in cluster is 1, indicating that the cluster has only one node (either the initial setting or the result after remove node).

Second, there have learners, the number of vote nodes  is also 1, but cluster has N nodes, and heartbeat signals are generated between these nodes.

The original code distinguishes between a quorum of 1 and greater than 1. One possible reason is that when quorum is 1, there is no need to send MsgReadIndexResp or heartbeat. But in terms of supporting learner, it may not actually be important to determine the value of quorum.

After removing distinguishes, the testcase you submitted can also pass, and the raft tests can also pass(master).

**Comment by gyuho** [comment]
Good find @jingyih! Thanks for handling this!
