### ISSUE TITLE
the client compile for wrong arguments

### ISSUE THREAD

**Issue by caucy** [etcd-io/etcd#10599]
use v2 client , see err 
```
../../../../../../github.com/etcd-io/etcd/client/discover.go:35:28: too many arguments in call to srv.GetClient
	have (string, string, string)
	want (string, string)
```

in client/discover.go, the func Discover use srv.GetClient("etcd-client", domain, serviceName), but the srv.GetClient just has two arg,  is this a bug ?

**Comment by hexfusion** [comment]
> in client/discover.go, the func Discover use srv.GetClient("etcd-client", domain, serviceName), but the srv.GetClient just has two arg, is this a bug ?

In `release-3.3` it takes 2 [1] and in `master` it takes 3 [2] so perhaps you have a mismatch somehow?

> ../../../../../../github.com/etcd-io/etcd/client/discover.go:35:28:

Looks like you are importing master client from the org `etcd-io`

[1] https://github.com/etcd-io/etcd/blob/release-3.3/client/discover.go
[2] https://github.com/etcd-io/etcd/blob/master/client/discover.go

**Comment by caucy** [comment]
tks, it is my fault. i use  main branch of github.com/etcd/client  in my code,  but the discover.go use "go.etcd.io/etcd/pkg/srv",  but the version  of go.etcd.io/etcd srv.go does not match the version github.com/etcd/client.  i am confused， why the client do not use etcd.io/etcd, and use go.etcd.io/etcd ?
