### ISSUE TITLE
Feature request: Txn Compare WithPrefix WithCountOnly() 

### ISSUE THREAD

**Issue by pjz** [etcd-io/etcd#10607]
Now that there's WithPrefix(), it would be nice to be able to get a `.count()` of matching keys - this could be used to limit the number of entries in a directory, for instance, by comparing the count to a maximum number. 

#8241 asks for the same thing, but was satisfied by what looks to me to be an existence check of 'are there things with this prefix?' 
I'm looking for something more like:

```
	cmp := clientv3.Version("pfx/").WithPrefix().WithCountOnly()
	txnresp, _ := c.Txn(context.TODO()).
		If(clientv3.Compare(cmp, "<", 10)).
		Then(clientv3.OpPut("pfx/mainkey", "somevalue")).Commit()
	if txnresp.Succeeded {
		log.Println("Under 10 entries in pfx/ so added mainkey")
	} else {
		log.Println("Already at least 10 entries in pfx/ so not spamming it with more.")
	}
```

**Comment by pjz** [comment]
This would still be useful.

**Comment by ruopuzi** [comment]
I encountered the same issue, that needs a .count() on a prefix to limit the number under a path.

**Comment by style95** [comment]
+1 to this feature.
