### ISSUE TITLE
Why etcdctl check perf --load='l' get a FAIL result

### ISSUE THREAD

**Issue by qd19zzx** [etcd-io/etcd#10609]
Hi, we have deployed an etcd cluster on VMS, each VM with:
vCPU- 8
RAM - 8G
Disk - 80GB (Cinder is separate – 20 GB)
and we use fio to get the IOPS and bw like below:

fio --name=randwrite --ioengine=sync --iodepth=1 --rw=randwrite --bs=16k --direct=1 --size=512M --numjobs=1 --runtime=240 --group_reporting --directory=/BACKUP/

the output is: write: IOPS=8098, BW=127MiB/s (133MB/s)(512MiB/4046msec)

But when we executed "etcdctl check perf --load='l'", it gets a FAIL result

[root@sps-me-oame-0 BACKUP]# ETCDCTL_API=3 etcdctl --endpoints http://192.168.3.21:2379 check perf --load="l"
60 / 60 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%1m0s
FAIL: too many errors
FAIL: ERROR(etcdserver: request timed out) -> 1000
FAIL: Throughput too low: 4790 writes/s
Slowest request took too long: 1.095562s
PASS: Stddev is 0.064833s
FAIL

According to https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md#large-cluster, the example hardware configuration for the large cluster is:

vCPUs | Memory (GB) | Max concurrent IOPS | Disk bandwidth (MB/s)
        8 |       32            |             8000                | 125

Although our CPU and RAM are 8 and 8Gb, we check CPU and RAM at the point when "etcdctl check perf" command is executed. Out of the total available resources, enough CPU and RAM are available. That means the CPU and RAM are not at all a bottleneck and are underutilized in our load operations. And IOPS and BW reach the example hardware config of a large cluster. 
Why did  etcdctl check perf --load='l' get a FAIL result?

**Comment by xiang90** [comment]
> Slowest request took too long: 1.095562s

Most likely it is a disk issue.

**Comment by krishnakhanna** [comment]
Hello  xiang90,
 Thanks for your response, the issues is if the Hardware requirements are satisfied and enough BW and IOPS are available as a result of FIO

Then that should comply to the ETCDctl command output and that should also pass.

In this case ETCDctl command fails although the requirements are fulfilled.

We wish to understand this behaviour.

Regards,
Krishna Khanna

**Comment by xiang90** [comment]
> https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md#example-hardware-configurations

Please read this documentation. It is just a very high level suggested configuration. There are many other factors can affect the performance, and we will not enumerate all of them.

**Comment by law53** [comment]
What does the following error means? getting this while executing "etcdctl check perf"
Error: prefix "/etcdctl-check-perf/" has keys. Delete with etcdctl del --prefix /etcdctl-check-perf/ first

**Comment by sumitKash** [comment]
> What does the following error means? getting this while executing "etcdctl check perf"
> Error: prefix "/etcdctl-check-perf/" has keys. Delete with etcdctl del --prefix /etcdctl-check-perf/ first

I got this message when i was running two performance check on the cluster in parallel.

**Comment by sanamsarath** [comment]
@krishnakhanna Were you able to zero out the issue??

We are seeing something similar, where the fio stats shows the BW and IOPS are good enough but still the check perf --load='l' are failing.

fio stats
```
write: IOPS=8068, BW=126MiB/s (132MB/s)(512MiB/4061msec)
```

load tests stats
```
[root@akash-baid-k8-node-1-a00043-4b2c09f7b129c1b8 ~]# ./etcdctl check perf --load="l"
 60 / 60 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%1m0s
FAIL: Throughput too low: 6470 writes/s
PASS: Slowest request took 0.252745s
PASS: Stddev is 0.025884s
FAIL
```
