### ISSUE TITLE
Getting "remote error: tls: bad certificate", ServerName ""

### ISSUE THREAD

**Issue by pablokbs** [etcd-io/etcd#10608]
I'm getting this error when trying to enable TLS support, I've created a repo with my configs [here](https://github.com/pablokbs/etcd-ssl-test)

How to run:

Create certs:

`make certs`

Start the cluster:

`make up`

It should show errors like:

`etcd1.local | 2019-04-02 18:29:05.514387 I | embed: rejected connection from "172.30.0.13:32802" (error "remote error: tls: bad certificate", ServerName "")`

But if you go into any container with: `make exec`, you can install dig and run a reverse search to the ip:

```
$ apk --update add bind-tools && dig -x 172.30.0.13

; <<>> DiG 9.12.3 <<>> -x 172.30.0.13
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51983
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;13.0.30.172.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
13.0.30.172.in-addr.arpa. 600   IN      PTR     etcd3.local.etcd_main.

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Tue Apr 02 18:25:40 UTC 2019
;; MSG SIZE  rcvd: 101

/ # ping etcd3.local.etcd_main
PING etcd3.local.etcd_main (172.30.0.13): 56 data bytes
64 bytes from 172.30.0.13: seq=0 ttl=64 time=0.113 ms
```

**Comment by pablokbs** [comment]
So my question is: where is etcd getting the "ServerName" from? the `ETCD_INITIAL_ADVERTISE_PEER_URLS` ?

**Comment by spzala** [comment]
Also, https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md should be helpful if you have not looked at it already. It also showcases why the similar error you are getting can happen under `And nodes with different CNs in CSRs or different --peer-cert-allowed-cn will be rejected...`

**Comment by pablokbs** [comment]
Ok so I confirmed that the servername member url is taking from the data that is on the "database" that can be changed by running :

```
etcdctl member update 26f130e771e74f11 https://hostname-of-the-server:7001
```

That way, each member will identify themselves using the name of the server instead of the IP.

**Comment by spzala** [comment]
Thanks @pablokbs
