### ISSUE TITLE
etcd L4 v3gateway ignores ENV VARS

### ISSUE THREAD

**Issue by linxcat** [etcd-io/etcd#10602]
I recently discovered the v3 gateway as a local proxy for gRPC use. This was very difficult to do, as most of the google logic still links strongly to the old "proxy" docs and there is very little mention of using the gateway in any documentation I could find.

My issue is that the v3gateway appears to ignore the standard ENV VAR config flag syntax described at https://coreos.com/etcd/docs/latest/op-guide/configuration.html (just prepend `ETCD_`, all-caps, underscore spaces)

setting `ETCD_LISTEN_ADDR="0.0.0.0:2379"` for the variable listed at https://coreos.com/etcd/docs/latest/op-guide/gateway.html as `--listen-addr` (with no ENV_VAR mentioned as in other docs) it is ignored and I get the following through netstat:
```
tcp        0      0 127.0.0.1:23790         0.0.0.0:*               LISTEN      30888/etcd
```

I think this is just a straight oversight, either in documentation or code, but I'm not sure which.

**Comment by hexfusion** [comment]
> I think this is just a straight oversight, either in documentation or code, but I'm not sure which.

etcd server uses

https://github.com/etcd-io/etcd/blob/4cd0bf8ea846a0d158761d55899f631eb2a423cf/etcdmain/config.go#L30

which we define prefix ETCD for env variable parsing.

https://github.com/etcd-io/etcd/blob/4cd0bf8ea846a0d158761d55899f631eb2a423cf/etcdmain/config.go#L304

but `gateway` uses cobra and does not have the same functionality.

https://github.com/etcd-io/etcd/blob/a621d807f061e1dd635033a8d6bc261461429e27/etcdmain/gateway.go#L26

Ideally we would want `ETCD_GATEWAY_LISTEN_ADDR` to work

Are you interested in helping impliment this?

**Comment by linxcat** [comment]
I'm not a developer. I'm trying to use this feature, not fix it.

**Comment by hexfusion** [comment]
> I'm not a developer. I'm trying to use this feature, not fix it.

Currently, we do not support this functionality but I will leave this issue open as a feature request so we can track.

**Comment by yuqitao** [comment]
@hexfusion  I will do it

**Comment by jingyih** [comment]
Thanks @yuqitao

**Comment by spzala** [comment]
@MPV please see my comment in the PR. Thanks!
