### ISSUE TITLE
config bug report

### ISSUE THREAD

**Issue by zhangguanzhang** [etcd-io/etcd#10613]
version: v3.2.24
the yaml fconfigureation https://github.com/etcd-io/etcd/blob/master/etcd.conf.yml.sample#L140
```
auto-compaction-retention: "1"
```
It could be running after the `"1"` changed to  `1` at the version v3.2.24

**Comment by hexfusion** [comment]
>version: v3.2.24
>the yaml fconfigureation https://github.com/etcd-io/etcd/blob/master/etcd.conf.yml.sample#L140

>auto-compaction-retention: "1"
>It could be running after the "1" changed to 1 at the version v3.2.24

Master docs are etcd `3.4` please review the docs for your minor version. We are working with CNCF on a new documentation system but for now please follow this convention.

https://github.com/etcd-io/etcd/blob/release-3.2/etcd.conf.yml.sample
