### ISSUE TITLE
Possible performance  regression since 3.2.24

### ISSUE THREAD

**Issue by tbe** [etcd-io/etcd#10610]
There are multiple reports of performance issues since 3.2.24 in kubernetes/kubernetes#70082

I can confirm that this issues does not seem to be a DISK performance issue, as even running etcd on a tmpfs leads to these errors, resulting in partial timeouts for client requests and other issues.

I observed the issue with every version since 3.2.24. Currently we still using 3.2.18 on production kubernetes clusters, to avoid this.

**Comment by xiang90** [comment]
@tbe Have you confirmed it is a performance regression or a metric reporting issue?

Probably we added the logging in 3.2.24 but not the version before it?

**Comment by tbe** [comment]
@xiang90 this issue has definitely an performance impact.  The queries do take longer to complete.

For example we have done a benchmkar ( etcd on tmpfs in both cases ) with a complex helm chart.

Applying the chart on a fresh cluster with etcd >=3.2.24 took about 90 seconds. Applying the same chart on a fresh cluster with etcd 3.2.18 about 30 seconds. 

I have currently no way to provide metrics for both versions. But there are examples in the linked issue:
- https://github.com/kubernetes/kubernetes/issues/70082#issuecomment-435696775
- https://github.com/kubernetes/kubernetes/issues/70082#issuecomment-472953330

I am aware that the logging was optimized around 3.2.20.

If i find the time, i will try to provide more numbers and statistics with both version and/or run a bisect

**Comment by jingyih** [comment]
I went through the changelogs between 3.2.18 and 3.2.24. I did not find any changes related to etcd backend apply.

The warning itself is added in 3.2.23.

>Applying the chart on a fresh cluster with etcd >=3.2.24 took about 90 seconds. Applying the same chart on a fresh cluster with etcd 3.2.18 about 30 seconds.
@tbe Is this tested with same or different K8s version?

**Comment by tbe** [comment]
> @tbe Is this tested with same or different K8s version?

The same, 14.0 in the test case before opening this issue. Sadly i currently have no access to a testing environment with compareable specs.

I had a look through the locks also, and maybe the issue is not related to backend apply.

In our test case, the systemd journal was saved on spinning disks. Maybe the logging itself causes the performance regression. Or a change of another part of etcd, like mvcc, is causing this.

If you have an idea for a better test-case (without k8s) i can help in means of running a bisect, testing different filesystems and more. If not, i think this issue should be closed until someone else can help in reproducing it.

**Comment by hustcat** [comment]
Hit the same issue with version 3.2.24

**Comment by jingyih** [comment]
@hustcat Is there a performance regression? Or is it just the warning logs that concerns people.
