### ISSUE TITLE
Error checking snapshot status

### ISSUE THREAD

**Issue by imorti** [etcd-io/etcd#10617]
sudo ETCDCTL_API=3 etcdctl snapshot status snapshot.db --cacert /etc/kubernetes/pki/etcd/server.crt --cert /etc/kubernetes/pk
i/etcd/ca.crt --key /etc/kubernetes/pki/etcd/ca.key
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/boltdb/bolt.Open(0x7fff1c04f80a, 0xb, 0x100, 0x1218860, 0x0, 0x0, 0xb411bd)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/boltdb/bolt/db.go:237 +0x497
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.dbStatus(0x7fff1c04f80a, 0xb, 0x0, 0x0, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapsh
ot_command.go:410 +0xe1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.snapshotStatusCommandFunc(0xc4201dba00, 0xc4201d73b0, 0x1, 0x7)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapsh
ot_command.go:154 +0x62
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201dba00, 0xc4201d72d0, 0x7, 0x7, 0xc4201dba00, 0xc4201d72d0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x203
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x11f01e0, 0xd735a4, 0xb, 0xc4201c7ed8)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x394
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x11f01e0, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3.Start()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/ctl_nocov.go:2
5 +0x8e
main.main()
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcdctl/main.go:40 +0x1d0

**Comment by hexfusion** [comment]
This is a feature that was added in 3.3.10 [1] and it appears your data store has corruption.

[1]https://github.com/etcd-io/etcd/pull/10109

**Comment by jingyih** [comment]
@imjoey Which etcd version are you running? This is a panic in bolt. As far as I am aware, it could be related to:

- #10399, which is a due to a bug recently found in bolt. Fix was sent but not yet merged [1].

- #9704, which is caused by opening a db file created with older version.

- #8813, which is due to freelist corruption in bolt. This was already fixed and backported.

Ref:
[1] https://github.com/etcd-io/bbolt/pull/153.
