### ISSUE TITLE
wrong cluster ID in arm64?

### ISSUE THREAD

**Issue by lpyh** [etcd-io/etcd#10623]
I am trying to construct etcd cluster  on 2 arm64 machine. The command is

`etcd --name infra0 --initial-advertise-peer-urls http://10.67.247.26:2380   --listen-peer-urls http://10.67.247.26:2380   --initial-cluster-token etcd-cluster-1   --initial-cluster infra0=http://10.67.247.26:2380,infra1=http://10.67.247.28:2380  --initial-cluster-state new &`

`etcd --name infra1 --initial-advertise-peer-urls http://10.67.247.28:2380   --listen-peer-urls http://10.67.247.28:2380   --initial-cluster-token etcd-cluster-1   --initial-cluster infra0=http://10.67.247.26:2380,infra1=http://10.67.247.28:2380  --initial-cluster-state new &`

However, it keeps reporting the errors like

> rafthttp: request cluster ID mismatch (got 29a019530d01cebb want 52932bdddb910a97)

the other node shows:

> rafthttp: request sent was ignored (cluster ID mismatch: peer[66bd5c5643d7f6a8]=52932bdddb910a97, local=29a019530d01cebb)

I have succeeded in 2 x86 nodes. 
While one x86 & one arm64 also got error like ' rafthttp: health check for peer cb5e1e2f29c3290d could not connect: <nil> '

Anyone can give some help ?
Thanks.

Some useful information:
> etcd Version: 3.2.22
Git SHA: 1674e682f
Go Version: go1.8.7
Go OS/Arch: linux/arm64

**Comment by jingyih** [comment]
Can you remove the data folder `infra0` and `infra2`, and try again? If the data directory already exist, etcd will not start as a new cluster.

**Comment by lpyh** [comment]
> Can you remove the data folder `infra0` and `infra1`, and try again? If the data directory already exist, etcd will not start as a new cluster.

Yes, you are right. Thank you very much.
