### ISSUE TITLE
ETCD performance problem at regular times every day

### ISSUE THREAD

**Issue by SpeedBlack** [etcd-io/etcd#10638]
Hi,

We have 2 Openshift clusters with 3 masters with ETCD.
```shell
# etcd --version
etcd Version: 3.2.22
Git SHA: 1674e68
Go Version: go1.9.2
Go OS/Arch: linux/amd64

# oc version
oc v3.9.60
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.60
kubernetes v1.9.1+a0ce1bc657
```

Every day at regular times, we receive ETCD "etcdHighCommitDurations" alerts (around 11:45pm, 2:00am,...).
For example, last night at 11:45 pm :

CLUSTER 01 :
![image](https://user-images.githubusercontent.com/24246055/56042617-c8831c00-5d3b-11e9-9770-2c1112b01c88.png)
CLUSTER 02 :
![image](https://user-images.githubusercontent.com/24246055/56042634-d2a51a80-5d3b-11e9-9c10-2cda880c5906.png)

In the ETCD logs we have errors like "failed to send out heartbeat on time", "apply entries took too long", "server is likely overloaded",... (See log file below).
[logs_etcd.log](https://github.com/etcd-io/etcd/files/3073604/logs_etcd.log)

According to our research, the first problem would be the disks.
VMDKs are stored on full flash volumes. From our initial observations, response times on the hpe 3par storage do not exceed 11.5ms.
After that, the CPU and RAM metrics seem correct (4vCPU/16Go RAM).

Please find below the metrics of the 3 ETCD nodes : 
[metrics_etcd_master01.log](https://github.com/etcd-io/etcd/files/3073613/metrics_etcd_master01.log)
[metrics_etcd_master02.log](https://github.com/etcd-io/etcd/files/3073614/metrics_etcd_master02.log)
[metrics_etcd_master03.log](https://github.com/etcd-io/etcd/files/3073615/metrics_etcd_master03.log)

What do you think of these metrics?

Do you have any idea ? Do you have any idea how to troubleshoot this problem ?
Does the ETCD perform regular scheduled tasks at specific times ?
Is it possible to check the requests executed at these specific times ? 

In advance, thank you for your help !

**Comment by roybliss** [comment]
Same issue for me at the same regular times every day, need help...

**Comment by SpeedBlack** [comment]
Hi @roybliss 

That's interesting !
Can you tell us a little more about it ?

Do you use ETCD with Kubernetes ? Openshift ?
Version (ETCD, OCP, Kubernetes,...) ? ETCD storage version ?

What is the system used ? For me, Red Hat Enterprise Linux Server release 7.6 (Maipo).

**Comment by roybliss** [comment]
@SpeedBlack 
Kubernetes: 1.13.2
ETCD: 3.2.24
Linux: CentOS-7.3.1611

**Comment by roybliss** [comment]
@SpeedBlack  Finally, I found the reason，Disk IO performance problem，But still don't know what caused the regular failure

**Comment by SpeedBlack** [comment]
Ok, thanks for your feedback !

How did you validate the problem (iostat,...) ? What disks do you use ?
How did you fix the problem (dedicated disk to etcd, change disks,...) ?

Thanks.

**Comment by roybliss** [comment]
@SpeedBlack We have prometheus server for monitoring, and grafana to view  trend chart. I don't know what disk used because it maintained by another team who still troubleshoot for this issue.
