### ISSUE TITLE
cluster sync issue

### ISSUE THREAD

**Issue by jsfrerot** [etcd-io/etcd#10633]
etcd Version: 3.3.11
Git SHA: 2cf9e51d2
Go Version: go1.10.7
Go OS/Arch: linux/amd64

```
+----------------------------+------------------+---------+---------+-----------+-----------+------------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------------------+------------------+---------+---------+-----------+-----------+------------+
| ord-etcd-001.ludia.me:2379 | 5aa59faaec42a185 |  3.3.11 |  348 kB |     false |       269 |       7784 |
| ord-etcd-002.ludia.me:2379 | 42f2ba1bc991d59e |  3.3.11 |  352 kB |     false |       269 |       7785 |
| ord-etcd-003.ludia.me:2379 | 2d18adf795494711 |  3.3.11 |  348 kB |      true |       269 |       7786 |
+----------------------------+------------------+---------+---------+-----------+-----------+------------+
```

I run etcdctl get / --prefix=true
on node 1 and 3 the result is empty
but on node 2 i get:
```
/ord/dev/luna/million/gameserver/ord-gs-dev-million-101/0/priv_ip
10.4.4.144
/ord/dev/luna/million/gameserver/ord-gs-dev-million-101/0/pub_ip
161.47.109.60
```

adding and removing data from node 1 and 3 works as expected.
But adding data to node 2 doesn't get replicated to the others.

Let me know what you need so we can investigate this.

**Comment by jsfrerot** [comment]
I have tried to remove the node from the cluster, delete the local db of etcd and re-insert the node into the cluster, but the weird thing is the old data that was only present on that node still comes back.
And the issue is still the same, when inserting data into that node, only this one gets the data, the other nodes doesn't get it.

**Comment by jingyih** [comment]
> adding and removing data from node 1 and 3 works as expected.
But adding data to node 2 doesn't get replicated to the others.

Can you be more specific about what happened? Maybe try to write "foo" "bar" to each node, and paste the command and result here. For example:
```
& etcdctl put foo bar --endpoints=first node's endpoint
OK

& etcdctl get foo --endpoints=... (try different nodes)
```

**Comment by jingyih** [comment]
Maybe also post the result of `etcdctl member list`.

**Comment by jsfrerot** [comment]
here is the output for the member list:
```
28fede9db241dfb, started, ord-etcd-002, https://ord-etcd-002.ludia.me:2380, https://ord-etcd-002.ludia.me:2379
7105b779e37a9c9d, started, ord-etcd-003, https://ord-etcd-003.ludia.me:2380, https://ord-etcd-003.ludia.me:2379
d3ccb9c79f3bf5e6, started, ord-etcd-001, https://ord-etcd-001.ludia.me:2380, https://ord-etcd-001.ludia.me:2379
```

The problem is fixed now. Here is what I did to fix it. 
- remove node 2 and 3 from the cluster
- compact and defrag the DB
```
etcdctl compact 2458
etcdctl defrag 
```
- added back node 2 and 3
after that I no longer have the issue where adding/removing data on node 2 doesn't get replicated on the other nodes.
