### ISSUE TITLE
Calculation method of FollowerStats's Sdv is not good enough.

### ISSUE THREAD

**Issue by j2gg0s** [etcd-io/etcd#10644]
[FollowerStats](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v2stats/leader.go#L120) use one textbook formual ``sdv = sqrt(avg(x^2) - avg(x)^2)``.

As mentioned in [this wiki](https://en.m.wikipedia.org/wiki/Algorithms_for_calculating_variance): avg(x^2) and avg(x)^2 can be very similar numbers, cancellation can lead to the precision of the result to be much less than the inherent precision of the floating-point arithmetic used to perform the computation.  

Welford's online algorithm may be one good choice.

**Comment by xiang90** [comment]
v2stats is kind of deprecated. we use prometheus for v3 stuff. so we wont fix it.
