### ISSUE TITLE
Add an observer role

### ISSUE THREAD

**Issue by tuteng** [etcd-io/etcd#10647]
Similar to the observer of zookeeper, it does not participate in voting but copies data and synchronizes data to other systems.Or learner act as read only replica.

**Comment by maoling** [comment]
@tuteng 
[PR-10645]( https://github.com/etcd-io/etcd/pull/10645) will support for learner (non-voting) member in etcd which's already a work in the progress

**Comment by hexfusion** [comment]
> @tuteng
PR-10645 will support for learner (non-voting) member in etcd which's already a work in the progress

@maoling is correct, I am closing this. Please track the progress of the learner feature via PR referenced above.
