### ISSUE TITLE
It's not possible to `ls` in json gateway to get the contents of a key directory

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [etcd-io/etcd#10641]
In `etcdcli`, it's possible to use the command `ls` to check the contents of a key "directory". With [json gateway](https://coreos.com/etcd/docs/latest/dev-guide/apispec/swagger/rpc.swagger.json), the only function available is `range`. This function gets the range in a mathematical form apparently, in a range [a,b), based on the base64 numeric values of the keys. But it doesn't get something like all the contents of `/test/*` or list all the keys in the system.

This seems to be a missing (necessary) feature. Is this really missing or am I not aware how to do it?

**Comment by yuqitao** [comment]
@TheQuantumPhysicist 
see https://coreos.com/etcd/docs/latest/dev-guide/api_grpc_gateway.html
give `key` ,`range_end`, and `key + 1 = range_end`, eg `foo` and `fop`,  will return all the keys with the prefix `key`. just like `etcdctl get key prefix --prefix`.

btw, `v3alpha` maybe wrong. It depends on etcd version.  In master branch, it is `v3`.

**Comment by TheQuantumPhysicist** [comment]
I didn't realize this would work even with a `/` and `/`+1. My preliminary tests show that it works for that. I'll close this issue and reopen it if I see this persisting. 

Thanks @yuqitao for the response. Btw, the link you posted is also in my question, or let's say that's how I reached it. Also I'm using `v3alpha` because on Ubuntu 18.04 it's v3.2 in the package manager.
