### ISSUE TITLE
--cipher-suites ignored for etcd proxies

### ISSUE THREAD

**Issue by rkd-msw** [etcd-io/etcd#10659]
I'm using TLS on etcd 3.3.12 and have a mix of etcd proxies and masters. The proxies don't seem to honour the --cipher-suites setting, as it ends up with `ECDHE-RSA-AES256-GCM-SHA384` despite ` --cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` being set.

```
$ pgrep -laf /usr/bin/etcd
21968 /usr/bin/etcd --listen-client-urls https://0.0.0.0:4000 --advertise-client-urls https://10.230.32.64:4000 --data-dir /var/lib/etcd/10.230.32.64 --name 10-230-32-64 --cert-file=/etc/clearwater/tls/etcd/cert.pem --key-file=key.pem --client-cert-auth --trusted-ca-file=cacert.pem --peer-cert-file=cert.pem --peer-key-file=key.pem --peer-client-cert-auth --peer-trusted-ca-file=cacert.pem --cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 --initial-cluster 10-230-32-60=https://10.230.32.60:2380,10-230-32-62=https://10.230.32.62:2380,10-230-32-61=https://10.230.32.61:2380, --proxy on
$ openssl s_client -connect localhost:4000 | grep Cipher
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
```

On a master node this works fine:

```
$ openssl s_client -connect localhost:4000 | grep Cipher
New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
```

Is this by design, or is it something you'd accept a fix for?

**Comment by hexfusion** [comment]
> Is this by design, or is it something you'd accept a fix for?

Hi @rkd-msw  if you can fix this we would love the help, thanks! Let us know if you need any help.

**Comment by yylt** [comment]
@hexfusion I would like to work on this! As a first time contributor, but @rkday had fixed the bug lerady, and maybe it is not good to change <updateCipherSuites> to External function ?

**Comment by alwindoss** [comment]
Is someone still working on this? I see a PR which is more than 8 months old still open for this.

**Comment by Koshti1907** [comment]
![image](https://user-images.githubusercontent.com/64426631/80589064-2235b180-8a37-11ea-8f00-a3d26ebcce33.png)
![image](https://user-images.githubusercontent.com/64426631/80589153-4abdab80-8a37-11ea-90ad-8c00cbeb7701.png)
![image](https://user-images.githubusercontent.com/64426631/80589166-501af600-8a37-11ea-80d9-9a4fac60c1ee.png)
![image](https://user-images.githubusercontent.com/64426631/80589195-5ad58b00-8a37-11ea-892f-01ef7e91b243.png)
![image](https://user-images.githubusercontent.com/64426631/80589178-55784080-8a37-11ea-965f-b83478d94b45.png)
![image](https://user-images.githubusercontent.com/64426631/80589222-65902000-8a37-11ea-8b0c-2c2181303cfb.png)
![image](https://user-images.githubusercontent.com/64426631/80589195-5ad58b00-8a37-11ea-892f-01ef7e91b243.png)
I Can not connect with database and When I Install any laravel project this error was comming every time
I Show error in below Pic Please Help Me
![image](https://user-images.githubusercontent.com/64426631/80589356-a25c1700-8a37-11ea-9f8b-7f1fd92bbcaf.png)
