### ISSUE TITLE
etcdctl key-value store doesn't share the data with the json gateway interface?

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [etcd-io/etcd#10651]
I kind of don't understand why the results don't match across APIs.

In the terminal (Ubuntu 18.04, etcd 3.2), you call:

    etcdctl set /testx/abc 123

Now we try to get that, and that works fine with etcdctl:

    etcdctl get /testx/abc

BUT, if we do that with json:

    curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "L3Rlc3R4L2FiYw=="}' 

where that key is the base64 representation of `/testx/abc`, we get the response:

    {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2992","raft_term":"6"}}

which indicates that this key doesn't exist.

The same applies if we do it the other way around. If we set a key with `http://localhost:2379/v3alpha/kv/put`, it's not accessible with `etcdctl`.

Is this expected behavior?

**Comment by hexfusion** [comment]
> Is this expected behavior?

Yes 

> etcdctl set /testx/abc 123

This sets `/testx/abc` to a value of 123 in the v2 store

> curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "L3Rlc3R4L2FiYw=="}' 

This command uses gRPC-gateway which uses v3 storage, as you wrote to v2 and did range on v3 no result is expected.

The v2 command to get key would be 

`curl http://127.0.0.1:2379/v2/keys/testx/abc`

Then also to write to v3ETCDCTL_API=3 etcdctl put foo bar

**Comment by hexfusion** [comment]
Closing as this is expected please let us know if you have any additional questions in the issue and I will respond.
