### ISSUE TITLE
Json request gets a plain text response

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [etcd-io/etcd#10653]
If I do such a request to create a least:

    curl --no-buffer -L http://localhost:2379/v3alpha/lease/grant -X POST -d '{"ID": 1234, "TTL": "100"}'

I get the response:

    {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"112056","raft_term":"10"},"ID":"1234","TTL":"100"}

Then I try to to revoke that:

    curl --no-buffer -L http://localhost:2379/v3alpha/lease/revoke -X POST -d '{"ID": "1234"}'

And I get the response:

    Not Found

Now two problems here:

1. Why is it not responding in json? This looks like a bug!
2. Why is it not found? I tried ID as hex, decimal with and without quotes and nothing works. 

It works fine with hex in etcdctl. But with json, it doesn't.

I'm on Ubuntu 18.04, etcd 3.2.

**Comment by yuqitao** [comment]
@TheQuantumPhysicist 
```
curl --no-buffer -L http://localhost:2379/v3alpha/kv/lease/revoke -X POST -d '{"ID": "1234"}'
```

**Comment by TheQuantumPhysicist** [comment]
Oh! Didn't notice that "kv". It's not there in the grant request. 

Thanks.
