### ISSUE TITLE
etcd@v3.3.12+incompatible: checksum mismatch

### ISSUE THREAD

**Issue by mrxliu** [etcd-io/etcd#10665]
verifying github.com/coreos/etcd@v3.3.12+incompatible: checksum mismatch
	downloaded: h1:pAWNwdf7QiT1zfaWyqCtNZQWCLByQyA3JrSQyuYAqnQ=
	go.sum:     h1:5k8nkcBSvltjOO5RLflnXevOJXndlKIMbvVnMTX+cUU=

**Comment by gyuho** [comment]
@mrxliu Have you tried `./script/updatedep.sh`?

**Comment by douxu** [comment]
Using go mod to compile a project in docker fails when downloading etcd

i compile a project in docker with go mod. there is an err when i downloading etcd use go mod.
but i compile the project with same go.sum and go.mod success in local.

err is verifying github.com/coreos/etcd@v3.3.12+incompatible: checksum mismatch
	downloaded: h1:pAWNwdf7QiT1zfaWyqCtNZQWCLByQyA3JrSQyuYAqnQ=
	go.sum:     h1:5k8nkcBSvltjOO5RLflnXevOJXndlKIMbvVnMTX+cUU=

this is etcd in go.sum
github.com/coreos/etcd v3.3.12+incompatible h1:5k8nkcBSvltjOO5RLflnXevOJXndlKIMbvVnMTX+cUU=
github.com/coreos/etcd v3.3.12+incompatible/go.mod h1:uF7uidLiAD3TWHmW31ZFd/JWoc32PjwdhPthX9715RE=

my local env 
MacBook-Pro 18.5.0 Darwin Kernel Version 18.5.0
go version 1.11

docker env 
base image golang:1.12

docker file is 
FROM golang:1.12 as builder
ENV GO111MODULE on
WORKDIR /go/pkg/mod
ADD go.mod .
ADD go.sum .
RUN go mod download 

@gyuho can you tell me why it is happen?

**Comment by guillain** [comment]
Yep, 

I had the same issue.
After having updated the go.cmd file with the current stable version (3.3.15) (and also for the go-rootcerts of hashcorp 1.0.1) it works like a charme ;-)

> @mrxliu Have you tried `./script/updatedep.sh`?
No script folder in 3.3.12: https://github.com/etcd-io/etcd/tree/release-3.3

Enjoy

**Comment by axiaoxin** [comment]
I had the same issue too..
```
> go get -u go.etcd.io/etcd/client                                        dev [ee3ea31]
go: finding go.etcd.io/etcd v3.3.17+incompatible
go: downloading go.etcd.io/etcd v3.3.17+incompatible
go: extracting go.etcd.io/etcd v3.3.17+incompatible
verifying go.etcd.io/etcd@v3.3.16+incompatible: checksum mismatch
	downloaded: h1:Lla8yiEXK3cXjuK+bjzMgMdVLw0qaRJOhAEj35mynAE=
	go.sum:     h1:9BNNn2BNDBt0qoneUyIMIc6TgShBBdx2BFWpmTjqDfo=
```

**Comment by rogchap** [comment]
I'm seeing the same error with `v3.3.10`:
```
verifying github.com/coreos/etcd@v3.3.10+incompatible: checksum mismatch
  downloaded: h1:KjVWqrZ5U0wa3CxY2AxlH6/UcB+PK2td1DcsYhA+HRs=
  sum.golang.org: h1:jFneRYjIvLMLhDLCzuTuU4rSJUjRplcJQ7pD7MnhC04=
```

**Comment by axiaoxin** [comment]
I found this phenomenon may be related to the version of golang. Using 1.13 will have this problem, using 1.12 is normal
