### ISSUE TITLE
CHANGELOG-3.2.md description confused about mininum recommended etcd versions

### ISSUE THREAD

**Issue by Bevisy** [etcd-io/etcd#10669]
CHANGELOG-3.2.md says the mininum recommended etcd versions is 3.1.11+, 3.2.26+, and 3.3.11+. But the provided mail group link says  the mininum recommended etcd versions is 3.1.11+,3.2.10+,3.3.0+.  
Is there some description that does not match?

**Comment by spzala** [comment]
@Bevisy The one in the CHANGELOG-3.2.md is the latest recommendation i.e. 3.1.11+, 3.2.26+, and 3.3.11+  I will update the .md files. Thanks!  /cc @hexfusion
