### ISSUE TITLE
Benchmark range get worse performance with high number of CPU cores

### ISSUE THREAD

**Issue by summerwinter** [etcd-io/etcd#10670]
I set one Etcd cluster with 5 nodes on AWS with m4.2xlarge machine(8 CPUs). Then I used the benchmark tool to test range request. I found that when Etcd cluster uses more CPU cores, performance gets worse.

Firstly, I put one key, value into cluster.
`etcdctl --endpoints=100.96.117.4:2379 put 12345678123456781234567812345678  12345678123456781234567812345678 `

Then, when I set **GOMAXPROCS as 8** to start Etcd cluster, and get below benchmark result.
`benchmark --endpoints=100.96.117.4:2379,100.96.111.4:2379,100.96.119.5:2379,100.96.120.5:2379,100.96.115.5:2379 --conns=1000 --clients=1000 range 12345678123456781234567812345678 --consistency=s --total=1000000`

```
 Summary:
  Total:       	27.6330 secs.
  Slowest:     	6.5918 secs.
  Fastest:     	0.0003 secs.
  Average:     	0.0263 secs.
  Stddev:      	0.0896 secs.
  Requests/sec:	36188.6078

Response time histogram:
  0.0003 [1]   	|
  0.6595 [998156]      	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1.3186 [1305]	|
  1.9778 [472] 	|
  2.6369 [3]   	|
  3.2961 [52]  	|
  3.9552 [7]   	|
  4.6144 [0]   	|
  5.2735 [0]   	|
  5.9327 [0]   	|
  6.5918 [4]   	|

Latency distribution:
  10% in 0.0013 secs.
  25% in 0.0021 secs.
  50% in 0.0034 secs.
  75% in 0.0051 secs.
  90% in 0.0148 secs.
  95% in 0.2082 secs.
  99% in 0.4099 secs.
  99.9% in 0.8274 secs.
```

And when I set **GOMAXPROCS as 2** to start Etcd cluster, and get below much better benchmark result.
```
 Summary:
  Total:       	14.2290 secs.
  Slowest:     	3.4797 secs.
  Fastest:     	0.0004 secs.
  Average:     	0.0137 secs.
  Stddev:      	0.0556 secs.
  Requests/sec:	70279.0999

Response time histogram:
  0.0004 [1]   	|
  0.3483 [993932]      	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.6963 [5457]	|
  1.0442 [533] 	|
  1.3921 [7]   	|
  1.7400 [55]  	|
  2.0880 [13]  	|
  2.4359 [0]   	|
  2.7838 [0]   	|
  3.1318 [0]   	|
  3.4797 [2]   	|

Latency distribution:
  10% in 0.0027 secs.
  25% in 0.0030 secs.
  50% in 0.0036 secs.
  75% in 0.0047 secs.
  90% in 0.0071 secs.
  95% in 0.0124 secs.
  99% in 0.2126 secs.
  99.9% in 0.6185 secs.
```

Besides, here are CPU profiling results corresponding to above results.
[etcd-profile-2cores.pdf](https://github.com/etcd-io/etcd/files/3106421/etcd-profile-2cores.pdf)
[etcd-profile-8cores.pdf](https://github.com/etcd-io/etcd/files/3106425/etcd-profile-8cores.pdf)

Etcd Version:
```
etcd Version: 3.3.12
Git SHA: d57e8b8
Go Version: go1.10.8
Go OS/Arch: linux/amd64
```

**Comment by summerwinter** [comment]
More updates:
The client network bandwidth(1Gbps) is full during benchmark. When we try to benchmark with higher bandwidth(10Gbps), everything works as expected.

With client network bandwidth(1Gbps),
when GOMAXPROCS is 2, client traffic: Incoming(150MB/s)/Outgoing(110MB/s);
when GOMAXPROCS is 8, client traffic: Incoming(94MB/s)/Outgoing(72MB/s).

It's weird that client traffic could reach to 150MB/s with the bandwidth 1Gbps, but this may be caused by AWS traffic limiting on software level.

We suspect the root cause for worse performance with high number of CPU cores is that bandwith limiting caused the growth of go schedule ratio percentage with high number of CPU, which could also be viewed with profiling tool.

It's appreciated that you could have any advice for this issue. Thanks~

**Comment by jingyih** [comment]
Is this possible to try similar benchmark setup on local machine to rule out disk and network variance?

**Comment by xiang90** [comment]
> We suspect the root cause for worse performance with high number of CPU cores is that bandwith limiting caused the growth of go schedule ratio percentage with high number of CPU, which could also be viewed with profiling tool.

This is possible. That can explain the increased latency. Can you try to use more resource at the client side as well? Maybe the server side resources is not saturated.

**Comment by xiang90** [comment]
also for consistency=s, you can just hit one server instead of 5 of them. s-read will only be served a local server anyway.

**Comment by wilsonwang371** [comment]
Today I observed the same thing. On our nvme ssd physical machine, I used one etcd instance and executed benchmark put testing. I found in this particular case 8 seems to be a good number for GOMAXPROCS setting. This might change if we are getting more read requests. But generally this worth further investigation and analysis.
