### ISSUE TITLE
ClientV3: when connecting a non-existent endpoints still

### ISSUE THREAD

**Issue by imxyb** [etcd-io/etcd#10698]
etcd version:
```
etcd Version: 3.3.8
Git SHA: 33245c6b5
Go Version: go1.9.7
Go OS/Arch: darwin/amd64
```
example:
```
func main() {
        // 127.0.0.1:379 is not exist
	c, err := clientv3.New(clientv3.Config{Endpoints:[]string{"127.0.0.1:379"}})
	if err != nil {       // but err is nil
		fmt.Println(err)  
		return
	}
	fmt.Println(c)
}
```

**Comment by spzala** [comment]
The only error where you expect to have it is returned when no endpoint is provided. We should return error for invalid endpoint too. Seems like a bug, investigating.

**Comment by XuHewen** [comment]
+1

**Comment by xiang90** [comment]
@spzala any progress?

**Comment by spzala** [comment]
@xiang90 thanks for the reminder :-) Missed it earlier :(. I will be working on it asap. Thanks!!

**Comment by spzala** [comment]
We are validating the provided endpoint at the operation level, and returning an error if provided endpoint can not be connected. This makes sense that we avoid connecting overhead until an actual op is performed. For example, with the provided fake endpoint in this issue, if I run put or get it will give `Error while dialing dial tcp 127.0.0.1:379: connect: connection refused` as follow:
```
{"level":"warn","ts":"2019-08-13T09:37:28.387-0400","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-a3fab72f-7061-40e7-a4a7-b5bc284d1eb3/127.0.0.1:379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:379: connect: connection refused\""}
```
@gyuho hi, it seems like this is per design, and we can close this issue? If we decide to make any changes, probably should do it after 3.4. Thanks! /cc @xiang90

**Comment by ae6rt** [comment]
If there is more than one endpoint provided, are they tried in-turn if one fails?

**Comment by spzala** [comment]
@ae6rt hello, that's true if I understood your question correctly, if `127.0.0.1:379,127.0.0.1:2379` provided, than that won't be an error case considering one valid endpoint. Thanks!

**Comment by gyuho** [comment]
Use `DialOptions: []grpc.DialOption{grpc.WithBlock()},` with dial time-out then the method returns `context deadline exceeded`

```go
clientv3.Config{
    Endpoints:   []string{"127.0.0.1:379"},
    DialTimeout: 3 * time.Second,
    DialOptions: []grpc.DialOption{grpc.WithBlock()},
}
```
