### ISSUE TITLE
Not able to increase default limit of request by --max-request-bytes, I want to upload a 8 mb file to etcd.

### ISSUE THREAD

**Issue by shrikrishna7744** [etcd-io/etcd#10705]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

**Comment by shrikrishna7744** [comment]
I have increased --max-request-bytes parameter in /usr/lib/systemd/system/etcd.service file and restarted the etcd using systemctl stop/start etcd. but still not able to upload file more than 1.5 mb.

**Comment by hexfusion** [comment]
That increases the server limit but you also need to increase the client [1].

[1] https://github.com/etcd-io/etcd/blob/918f0414ddb5d2bc4fd99b0018601ec596a36ef5/clientv3/config.go#L45-L50

**Comment by yqwang-ms** [comment]
@hexfusion Can we remove the duplicated validation on client side? It may be inconsistent with server side config, but the flag is actually used to protect server, and when server says it can accept larger request payload, client itself should not fail it by its own.

For example, a real problem we met is that, k8s does not provide a flag to increase this on client side.
So, we cannot tune this in k8s cluster.
