### ISSUE TITLE
Survey for etcd community meeting tool

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#10707]
Let's vote for your favorite cyber conference tool! We might get to use it for our [etcd community meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit):) Please help to fill out the [**SURVEY HERE**](https://docs.google.com/forms/d/1E87KR3m7uo3SDL0_Kol4KlDETePEJ9JaaCXDU2iAV1o/viewform?vc=0&c=0&w=1&edit_requested=true)! Thanks!

**Comment by purpleidea** [comment]
Thanks for posting this!

**Comment by wenjiaswe** [comment]
Since most people vote for google hangout as etcd community meeting tool, let's switch to use hangout. Thanks!

![image](https://user-images.githubusercontent.com/33743058/59725523-bf527780-91e2-11e9-9fb8-68b92ebbb3b6.png)
