### ISSUE TITLE
TCP connections between apiserver and etcd looks strange

### ISSUE THREAD

**Issue by sevensees** [etcd-io/etcd#10717]
I have a kubernetes cluster with 3 apiservers and a etcd cluster with 3 instances as the storage backend.

I found that all the TCP connections (totally 198) between apiserver and etcd will be establish on one etcd instance (A), when I set `--etcd-servers="A,B,C"` to 3 apiserver, and the other 2 etcd instance have no connections from apiserver. Then I adjust the order for 3 apiservers respectively, like,
apiserver-1: `--etcd-servers="A,B,C"`
apiserver-2: `--etcd-servers="B,C,A"`
apiserver-3: `--etcd-servers="C,A,B"`

then, tcp connections becomes

apiserver-1 <----------> A (totally 66 connections)
apiserver-2 <----------> B (totally 66 connections)
apiserver-3 <----------> C (totally 66 connections)

It seems that the apiserver will only establish connections to the first etcd server given in `--etcd-servers`. I'd like to know if it is by design or a bug?

**Comment by xiang90** [comment]
please ask this question in Kubernetes project.

**Comment by jingyih** [comment]
FYI. This might be related to a known bug:
https://github.com/etcd-io/etcd/issues/9949
https://github.com/kubernetes/kubernetes/issues/72102

**Comment by sevensees** [comment]
Thanks a lot.
