### ISSUE TITLE
import broken on branch

### ISSUE THREAD

**Issue by i19** [etcd-io/etcd#10720]
https://github.com/etcd-io/etcd/blob/master/clientv3/kv.go#L20

where is the v3 directory ?

**Comment by jpbetz** [comment]
See https://github.com/etcd-io/etcd/pull/10640. What go version are you building with?

**Comment by i19** [comment]
➜  ~ go version
go version go1.12.5 darwin/amd64
➜  ~ GO111MODULE="on" go get -v go.etcd.io/etcd/clientv3

`	
r, _ :=etcd.Client.Get(context.Background(), "/k1")
`

`r`  has only  `OpResponse()` method, but no `Kvs()` which is what i really need.

**Comment by gyuho** [comment]
Please try again with https://github.com/etcd-io/etcd/pull/10766.

**Comment by i19** [comment]
it works, thanks a lot
