### ISSUE TITLE
ectd failed to get all reachable pages

### ISSUE THREAD

**Issue by kong62** [etcd-io/etcd#10722]
after power off，etcd failed and Several times
[root@k8s01 ~]# docker logs f8096edfe698
2019-05-14 05:47:37.483099 I | etcdmain: etcd Version: 3.3.10
2019-05-14 05:47:37.483148 I | etcdmain: Git SHA: 27fc7e2
2019-05-14 05:47:37.483152 I | etcdmain: Go Version: go1.10.4
2019-05-14 05:47:37.483154 I | etcdmain: Go OS/Arch: linux/amd64
2019-05-14 05:47:37.483157 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2019-05-14 05:47:37.483201 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-05-14 05:47:37.483222 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, ca = , trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file = 
2019-05-14 05:47:37.483855 I | embed: listening for peers on https://10.62.10.33:2380
2019-05-14 05:47:37.483888 I | embed: listening for client requests on 10.62.10.33:2379
2019-05-14 05:47:37.483904 I | embed: listening for client requests on 127.0.0.1:2379
panic: freepages: failed to get all reachable pages (page 2475294449906223648: out of bounds: 3758)

goroutine 112 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).freepages.func2(0xc42007e720)
        /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:976 +0xfb
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).freepages
        /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:974 +0x1b7

**Comment by WIZARD-CXY** [comment]
seems powerdown cause db corruption. you can remove this member and add it via etcd member api , and let the leader transfer a new data to k8s01 node to restore

**Comment by kong62** [comment]
@WIZARD-CXY   thanks.

**Comment by timyinshi** [comment]
@WIZARD-CXY do you know how to repair the corrupt db file? when my etcd cluster is not healthy,i must repair the corrupt db file?

**Comment by BedivereZero** [comment]
Same question, how to recover data when ETCD cluster has only one node？

**Comment by lknite** [comment]
@WIZARD-CXY working with a downed cluster, wonder if you might be willing to add a little more detail so that I might (and anyone else running into this might) get things back up and running and can look into a deeper learning of these underlying parts when the pressure is off?

**Comment by lknite** [comment]
@WIZARD-CXY might you be willing to give some additional direction to complete the steps of removing and reading the etc member?  Working with a down cluster situation and it would be nice for myself, and anyone else who comes across this posting to get back up and running.  Then when the pressure is off to take more of a deep dive into etcd.  In my case I do have 3 control plane nodes so it seems your solution should work.  I'm googling to try and find how to perform the steps you gave ...

**Comment by drtechco** [comment]
https://gist.github.com/drtechco/3773a8e0e7a692fabe8cefd3ca102180

**Comment by kernoelpanic** [comment]
Just in case anybody comes across this again pointed here by some search engine and having the `ectd failed to get all reachable pages` error: If you do does not care about repairing the corrupted database (and the data within it), you can also just wipe it like so: 
```
sudo systemctl stop containerd
sudo mv /var/lib/containerd /var/lib/containerd.bak
sudo systemctl start containerd
```
Then it should work again.

**Comment by sudoexec** [comment]
My k8s only has one node. Is it possible to restore the corrupted etcd data?

**Comment by serathius** [comment]
Read the documentation

**Comment by sudoexec** [comment]
> By reading the documentation https://etcd.io/docs/v3.6/op-guide/data_corruption/

@serathius Thanks for your reply. But it looks like that's for etcd cluster.

And I've search many errors like:
```
panic: freepages: failed to get all reachable pages 
```
Can't find any methods.

**Comment by serathius** [comment]
Oh, yes I should mention in the document that there is no way to recover single node cluster without backup. There is some bbolt tooling for doing data surgery and fixing it, but that requires an expertise in bbolt.

What I can share from my experience is that those errors are very rare and usually are caused by a hardware problem.

**Comment by sudoexec** [comment]
@serathius Thanks, maybe I'll try bbolt.
