### ISSUE TITLE
Typo in test file name 

### ISSUE THREAD

**Issue by LinlinDu** [etcd-io/etcd#10733]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
should be "maintenance"

**Comment by spzala** [comment]
> Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
> should be "maintenance"

https://github.com/etcd-io/etcd/blob/master/clientv3/example_maintenence_test.go - should be "maintenance" 

@LinlinDu I have changed the issue title and added the detail here to make it easy to understand.
