### ISSUE TITLE
Example Grafana Dashboard does not render anything in Grafana 6.1.x

### ISSUE THREAD

**Issue by frittentheke** [etcd-io/etcd#10735]
When loading the nicely provided (thank you !)  etcd Grafana-Dashboard (https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/monitoring.md / https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/grafana.json) does not render anything in Grafana anymore.

The dashboard can be imported, but then renders as empty dashboard page in Grafana.

**Comment by jinxiao** [comment]
i'm facing the same problem, i got nothing , settings of "JSON MODEL" only showed this:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 32,
  "links": [],
  "panels": [],
  "schemaVersion": 19,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "etcd",
  "uid": "VK4fKQTWk",
  "version": 1
}
```

**Comment by manicole** [comment]
Same here ... Any help appreciated.

**Comment by jinxiao** [comment]
> To solve it, remove the
> 
> ```json
>     "etcd.json": {
> ```
> 
> line and the matching "}" at the end.

it solved

**Comment by frittentheke** [comment]
@jinxiao @manicole  I created a PR https://github.com/etcd-io/etcd/pull/11994 with this change.
If you don't mind, kindly check it out to verify I changed the dashboard json correctly.

**Comment by frittentheke** [comment]
ping.

**Comment by frittentheke** [comment]
> ping.

My PR "timed out" :-(
