### ISSUE TITLE
Unable to find watch Id in the watch response.

### ISSUE THREAD

**Issue by sanamsarath** [etcd-io/etcd#10743]
etcd version 3.3.2

I am not able to find watch id in the watch request. Do I need to enable any field in the watch request for server to send the watch Id?? Is't watch Id a default value in the response??

```
[root@etcd-server-0-76-0-dbg-b999fd5c9-8xhsl bin]# curl -N http://localhost:2379/v3beta/watch -X POST -d '{"create_request": {"key":"Lw=="} }' &
[1] 91
[root@etcd-server-0-76-0-dbg-b999fd5c9-8xhsl bin]# {"result":{"header":{"cluster_id":"5088677808084591775","member_id":"6822990200676136672","revision":"32492","raft_term":"2"},"created":true}}
[root@etcd-server-0-76-0-dbg-b999fd5c9-8xhsl bin]# 

```

Thanks,
Sarath.

**Comment by jingyih** [comment]
It is probably omitted:
https://github.com/etcd-io/etcd/blob/71881a423fa58b8a37536e47ce82c8e3da61e9a0/etcdserver/etcdserverpb/rpc.pb.go#L1662
Please try to provide an watch ID in the request.

**Comment by sanamsarath** [comment]
@jingyih Thanks for the response.

But our etcd running version is still 3.3.12, looks like from the https://github.com/etcd-io/etcd/pull/9015 clients can provide watchId for etcd versions 3.4 and above.

I was assuming that etcd by default should assign auto generated watchId if it is not provided.

**Comment by jingyih** [comment]
@sanamsarath You are right. Server will auto generate watch ID when a new watcher is created. The issue is that the ID starts with 0, which is omitted in json.

**Comment by jingyih** [comment]
@gyuho Could you take a look?

**Comment by yuqitao** [comment]
@sanamsarath @jingyih 
watch ID is only significant for a `mvcc.watchStream`.
Use `curl`, there will be a new connection with a new  `watchStream`, and the watch ID is all 0. 
The return json didn't contain `watch_id`, maybe `grpc-gateway` handle `int64` `0` as `empty`.  I change `watch_id` to `1`, the json contains `watch_id` as except.

If we use `http` to watch a key, just close the connection to cancel the watch. Canceling with watch_id is use to cancel one  of watchers on a connection.

**Comment by gyuho** [comment]
Correct, the watch ID will be auto-generated https://github.com/etcd-io/etcd/pull/9065/files.
