### ISSUE TITLE
ci: semaphore build passes trivially

### ISSUE THREAD

**Issue by tbg** [etcd-io/etcd#10746]
Looks like it's hitting some variant of https://github.com/etcd-io/etcd/issues/10742 and the test harness fails to realize that the build actually failed.

The likely offender is 9150bf52d64b66d3a791c1a56f0d6479c3e82584. @gyuho, looks like you reviewed this. Any ideas?

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/5076964/58104017-4d3b4280-7be4-11e9-8f63-eb5254e1240a.png">

**Comment by gyuho** [comment]
Will look into this. Sorry for delay!

**Comment by gyuho** [comment]
Semaphore is fixed but finding other set of errors in travis.... will continue working on this, this week (https://semaphoreci.com/etcd-io/etcd/branches/pull-request-10766/builds/7).

**Comment by gyuho** [comment]
It's fixed now.
