### ISSUE TITLE
go get github.com/coreos/etcd/clientv3  error

### ISSUE THREAD

**Issue by Linuxbody** [etcd-io/etcd#10742]
# go get github.com/coreos/etcd/clientv3
# github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3/auth.go:116:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
github.com/coreos/etcd/clientv3/auth.go:121:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
github.com/coreos/etcd/clientv3/auth.go:126:100: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
github.com/coreos/etcd/clientv3/auth.go:131:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
github.com/coreos/etcd/clientv3/auth.go:136:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
github.com/coreos/etcd/clientv3/auth.go:141:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
github.com/coreos/etcd/clientv3/auth.go:146:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
github.com/coreos/etcd/clientv3/auth.go:151:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
github.com/coreos/etcd/clientv3/auth.go:156:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
github.com/coreos/etcd/clientv3/auth.go:161:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.RoleAdd
github.com/coreos/etcd/clientv3/auth.go:161:80: too many errors

**Comment by Linuxbody** [comment]
and 	

/Users/victor/go/src/go.etcd.io/etcd/v3/etcdserver/api/v3rpc/rpctypes (from $GOPATH)
../../../go.etcd.io/etcd/clientv3/auth.go:23:2: cannot find package "go.etcd.io/etcd/v3/etcdserver/etcdserverpb" in any of:
	/Users/victor/go/src/go.etcd.io/etcd/vendor/go.etcd.io/etcd/v3/etcdserver/etcdserverpb (vendor tree)
	/usr/local/go/src/go.etcd.io/etcd/v3/etcdserver/etcdserverpb (from $GOROOT)
	/Users/victor/go/src/go.etcd.io/etcd/v3/etcdserver/etcdserverpb (from $GOPATH)
../../../go.etcd.io/etcd/clientv3/watch.go:26:2: cannot find package "go.etcd.io/etcd/v3/mvcc/mvccpb" in any of:
	/Users/victor/go/src/go.etcd.io/etcd/vendor/go.etcd.io/etcd/v3/mvcc/mvccpb (vendor tree)
	/usr/local/go/src/go.etcd.io/etcd/v3/mvcc/mvccpb (from $GOROOT)
	/Users/victor/go/src/go.etcd.io/etcd/v3/mvcc/mvccpb (from $GOPATH)
../../../go.etcd.io/etcd/clientv3/client.go:34:2: cannot find package "go.etcd.io/etcd/v3/pkg/logutil" in any of:
	/Users/victor/go/src/go.etcd.io/etcd/vendor/go.etcd.io/etcd/v3/pkg/logutil (vendor tree)
	/usr/local/go/src/go.etcd.io/etcd/v3/pkg/logutil (from $GOROOT)
	/Users/victor/go/src/go.etcd.io/etcd/v3/pkg/logutil (from $GOPATH)
../../../go.etcd.io/etcd/clientv3/cluster.go:21:2: cannot find package "go.etcd.io/etcd/v3/pkg/types" in any of:
	/Users/victor/go/src/go.etcd.io/etcd/vendor/go.etcd.io/etcd/v3/pkg/types (vendor tree)
	/usr/local/go/src/go.etcd.io/etcd/v3/pkg/types (from $GOROOT)
	/Users/victor/go/src/go.etcd.io/etcd/v3/pkg/types (from $GOPATH)
exit status 1
Process exiting with code: 1

**Comment by gyuho** [comment]
Please try again.
