### ISSUE TITLE
etcd api does not work when use default config.yaml

### ISSUE THREAD

**Issue by fyqtian** [etcd-io/etcd#10751]
etcd Version: 3.3.0+git
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.11
Go OS/Arch: windows/amd64

It will reset EnableGRPCGateway:false when you use "etcd --config-file=default.yaml" and if you do not set value in config file;
There is no instruction for field "enable-grpc-gateway" in documentation

**Comment by jingyih** [comment]
If I understand this issue correctly, when --config-file is provided, other command line flags and environment variables will be ignored.

**Comment by fyqtian** [comment]
> If I understand this issue correctly, when --config-file is provided, other command line flags and environment variables will be ignored.

Yes you are correctly expreseing what i want to say!
There is no hint in config instruction that puzzle me some time

**Comment by jingyih** [comment]
It is actually documented in [1]. But maybe we should add similar description in usage messge [2].

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md
[2] https://github.com/etcd-io/etcd/blob/c38e965a65c29b5576982096ee2e9cec455f7ad8/etcdmain/config.go#L130
