### ISSUE TITLE
Potential panic when range etcd endpoints

### ISSUE THREAD

**Issue by wrfly** [etcd-io/etcd#10752]
https://github.com/etcd-io/etcd/blob/416a5390c47d225d8c6b702a4656fca24ac2aad9/clientv3/client.go#L292-L295

Why don't just use `range`:

```golang
for _, ep := range c.cfg.Endpoints
```

There is no lock here, so when we range the endpoints, and somehow another function called `SetEndpoints` function, then, gg.

**Comment by xiang90** [comment]
can you try to fix it?

**Comment by wrfly** [comment]
Sure, later after work I'll try to fix it. :)
