### ISSUE TITLE
MemberAdd api : Is it necessary  to use the "now" to create MemberID?

### ISSUE THREAD

**Issue by ACatTom** [etcd-io/etcd#10765]
In function NewClusterFromURLsMap， the memberId is created by cluster_token+Peerurl, while in function MemberAdd， use the Peerurl + now.   Is it necessary  to use the "now" ?

**Comment by jingyih** [comment]
I think the answer is yes. Conceptually if an member is already removed from a cluster, its peerURLs can be used by new (different) member in the same cluster. So just using cluster_token and peerURL is not enough to distinguish different cluster members.

NewClusterFromURLsMap is used during bootstrapping only. Member ID is not populated properly in the function. The correct member ID is either retrieved from another member [1], or when the server applies the ConfChangeAddNode raft log entry [2].

[1] https://github.com/etcd-io/etcd/blob/2ff2755528372bae36ede36ddccd1a77bd118887/etcdserver/server.go#L358
[2] https://github.com/etcd-io/etcd/blob/2ff2755528372bae36ede36ddccd1a77bd118887/etcdserver/server.go#L2137

**Comment by hexfusion** [comment]
I agree with @jingyih, let us know if you have any other questions.
