### ISSUE TITLE
Watch Id not found in watch response

### ISSUE THREAD

**Issue by rahulsinha1** [etcd-io/etcd#10780]
I am trying to get the watch id while creating a watch . I want to use the watch id to cancel the watch later. But the response does not provide a watch id. How do i send the watch request in order to receive the watch id? 

`curl -N http://localhost:2379/v3beta/watch \  -X POST -d '{"create_request": {"key":"Zm9v"} }' 
{"result":{"header":{"cluster_id":"6866596675756210935","member_id":"15119904572795490681","revision":"100747","raft_term":"2"},"created":true}}`

Kindly help. Thank you,
Rahul

**Comment by spzala** [comment]
@rahulsinha1 this issues seems like related to https://github.com/etcd-io/etcd/issues/10743

**Comment by spzala** [comment]
@rahulsinha1 does the discussion in #10743 helpful to you?  i.e. by default the watch id is 0 and it doesn't show in the response (omitted) but if you provide a non-zero id that would be showed in the  response. I am closing this issue but please free to reopen if you see a need. A related description link, https://github.com/etcd-io/etcd/pull/9065/files Thanks!
