### ISSUE TITLE
e2e: TestCtlV3AuthEndpointHealth gets stuck

### ISSUE THREAD

**Issue by tbg** [etcd-io/etcd#10787]
Seen in https://github.com/etcd-io/etcd/pull/10779, but I don't think it's related to that PR. @gyuho could you take a look?

```
=== RUN   TestCtlV3AuthEndpointHealth
panic: test timed out after 20m0s

goroutine 6839 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1334 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:169 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001ca100, 0xcba649, 0x1b, 0xce1508, 0x4b6c01)
	/usr/local/go/src/testing/testing.go:917 +0x381
make: *** [docker-test] Error 1
```

**Comment by spzala** [comment]
@tbg hi, sometime back @xiang90 has created an issue to track/fix flaky tests so I guess we can close this one and track it under https://github.com/etcd-io/etcd/issues/10700 I have added detail of this issue there. Thanks!

**Comment by tbg** [comment]
Thank you @spzala

**Comment by spzala** [comment]
> Thank you @spzala

:) No problem, thanks @tbg
