### ISSUE TITLE
Watching 100 grpc proxies from a single process

### ISSUE THREAD

**Issue by arjunsingri** [etcd-io/etcd#10785]
I have setup 100 grpc proxies for the same etcd cluster on a single machine with 16 cores and 50 GB memory on GCP. The script I used is this:

```
port=2379
for i in {1..100}
do
    /usr/local/bin/etcd grpc-proxy start --endpoints=http://<ip1>:2380,http://<ip2>:2380,http://<ip3>:2380 --listen-addr=<ip4>:$port &
    ((port++))
done
```

Then I wrote a simple golang script to watch a key through each of the above grpc proxies. Each watch happens in a separate go-routine. The watch is cancelled for 99 proxies and only one watcher (against port 2379) succeeds in getting all the events. The 99 other watches that are cancelled don't get any events. Any reason why this happens?

**Comment by hexfusion** [comment]
`etcd --version`?
