### ISSUE TITLE
can not get any output when connect to etcd

### ISSUE THREAD

**Issue by thekingofworld** [etcd-io/etcd#10791]
etcd version: 3.3.10
when etcd is not running, Why is this code without any output?
please help me, thanks

here is my code: 
```
package main

import (
	"context"
	"fmt"
	"go.etcd.io/etcd/clientv3"
	"time"
)

func main() {
	fmt.Println(time.Now().Format("15:04"))
	client, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		fmt.Println("connect etcd err")
		fmt.Println(err)
	}
	fmt.Println("begin watch")
	rch := client.Watch(context.Background(), "/test/lee", clientv3.WithPrefix())
	for resp := range rch {
		for _, ev := range resp.Events {
			fmt.Println(ev)
		}
	}
	defer client.Close()
}
```

**Comment by thekingofworld** [comment]
![image](https://user-images.githubusercontent.com/8169665/58942093-ae9c0d80-87af-11e9-897f-eaa6bd5e47b4.png)

**Comment by hexfusion** [comment]
Are you sure etcd is not running?

```
$ ss -ltn | grep 2379
```
```
$ ./etcd-test 
13:15
connect etcd err
dial tcp [::1]:2379: connect: connection refused
begin watch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8d1e18]

goroutine 1 [running]:
main.main()
	etcd-test/main.go:22 +0x248
[ etcd-test]$ 
```

**Comment by jingyih** [comment]
What is the expected output? There is no key value change after the watch is created, therefore watch channel will not receive any event. To receive events of previous key value changes, specify the start revision via option `Clientv3.WithRev()`.

**Comment by thekingofworld** [comment]
> Are you sure etcd is not running?
> 
> ```
> $ ss -ltn | grep 2379
> ```
> 
> ```
> $ ./etcd-test 
> 13:15
> connect etcd err
> dial tcp [::1]:2379: connect: connection refused
> begin watch
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8d1e18]
> 
> goroutine 1 [running]:
> main.main()
> 	etcd-test/main.go:22 +0x248
> ```

I'm sure.
![image](https://user-images.githubusercontent.com/8169665/59170972-7744ac80-8b73-11e9-914c-adfb2cbb0dd4.png)

**Comment by thekingofworld** [comment]
Is it because of the virtual machine environment?
I use vagrant + virtualBox

**Comment by gsxhnd** [comment]
resolve:  [https://github.com/etcd-io/etcd/issues/9877#issuecomment-458509079](https://github.com/etcd-io/etcd/issues/9877#issuecomment-458509079)
