### ISSUE TITLE
gRPC-JSON watch request is not canceled on minority

### ISSUE THREAD

**Issue by roe85** [etcd-io/etcd#10819]
When etcdctl is watching variables and the server becomes minority the watch gets canceled  with "Error: watch is canceled by the server".

> `# etcdctl watch foo`
> `Error: watch is canceled by the server`

But if the same is done via the JSON-gRPC the connection remains open and one has to resort to polling the range api which defies the purpose of watching. 

> `# curl -N http://localhost:2379/v3beta/watch   -X POST -d '{"create_request": {"key":"Zm9v"} }'`

```
# etcd --version
etcd Version: 3.3.8
Git SHA: 33245c6b5
Go Version: go1.9.7
Go OS/Arch: linux/amd64

```

**Comment by jingyih** [comment]
Please try `curl -N http://localhost:2379/v3/watch -X POST -d '{"create_request": {"key":"Zm9v"} }' -H "Grpc-Metadata-hasleader: true"
`

`etcdctl watch foo` calls `WithRequireLeader()` which writes grpc metadata `MetadataRequireLeaderKey` ([1], [2]) when sending watch create request.

[1] https://github.com/etcd-io/etcd/blob/aa016eebf8a18ca3ced2fca9137c9963d8a648f2/clientv3/client.go#L418-L419
[2] https://github.com/etcd-io/etcd/blob/53891cbf9716b942b4f9c5929bbd2781180bf8e0/etcdserver/api/v3rpc/rpctypes/md.go#L18-L19

**Comment by roe85** [comment]
Thanks, that worked. But, I've 2 questions:
a) Shouldn't aborting be the default?
b) Shouldn't there be more accessible documentation?

**Comment by jingyih** [comment]
It is mentioned in the API description:

https://github.com/etcd-io/etcd/blob/53891cbf9716b942b4f9c5929bbd2781180bf8e0/clientv3/watch.go#L58

There might be backward compatibility reasons that 'requiring leader' is not an default.

**Comment by xiang90** [comment]
inactive. so closing.
