### ISSUE TITLE
clientv3 balancer not remove hang etcd endpoint from sub-connection

### ISSUE THREAD

**Issue by wgkun** [etcd-io/etcd#10816]
ENV:
1. etcd version:
# etcd --version
etcd Version: 3.2.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.11.4
Go OS/Arch: linux/amd64
2. clientv3 version:  source package download from https://github.com/etcd-io/etcd on 2019/4/18

Problem:
We have a C program use etcd v2 APIs before. Currently, I try to update it to use v3 APIs. The implementation plan is to call clientv3 APIs(such as clientv3.New, clientv3.Put ...) from a go wrapper and then compile the go wrapper into a C shared library by CGO tool. It works well.

When I try to run some ET cases, I found one problem of balancer.
The test scenario is:
1. use the C shared library to put/get/delete key-values continuously
2. hang one of the etcd endpoints by kill -19 for a while such as 7~9s
  [root@mn-1:/root]
   # ps -aux | grep etcd
   root      2901  2.5  2.2 11792468 90500 ?      S<sl Jun10  52:54 /usr/bin/etcd
  [root@mn-1:/root]
   # kill -19 2901;sleep 9;kill -18 2901
3. the client has been init with keep alive detection as:
  	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   endpoints_list,
		DialTimeout: time_out * time.Second,
		DialKeepAliveTime: time_out * time.Second,
		DialKeepAliveTimeout: alive_time_out * time.Second})

The result is that balancer will enter a loop to remove and add the hang endpoint again and again during the endpoint hang. When balancer add the hang endpoint, the operation on this endpoint will face context time out error. 
I think this scenario may happen when the etcd endpoint can not occupy the CPU or some OS panic happens.  

Logs attached below:
"
{"level":"warn","ts":1560258039.3271546,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:39.327+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

{"level":"warn","ts":1560258040.3312635,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:40.331+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

{"level":"warn","ts":1560258041.1777122,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = Unavailable desc = transport is closing","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:41.177+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = Unavailable desc = transport is closing"}
{"level":"info","ts":1560258041.1776605,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"READY","new-state":"TRANSIENT_FAILURE"}

{"level":"info","ts":1560258041.1779046,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":3}

{"level":"info","ts":1560258041.1779492,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"info","ts":1560258041.177978,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":true,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"READY"}
{"level":"info","ts":1560258041.178012,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.11:2379 (0xc4202700c0)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":4}

{"level":"warn","ts":1560258042.1818628,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:42.181+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

{"level":"warn","ts":1560258043.1782994,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = Unavailable desc = transport is closing","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:43.178+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = Unavailable desc = transport is closing"}
{"level":"info","ts":1560258043.1783044,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"READY","new-state":"TRANSIENT_FAILURE"}
{"level":"info","ts":1560258043.178481,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":3}
{"level":"info","ts":1560258043.1785226,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"info","ts":1560258043.17855,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"TRANSIENT_FAILURE"}
{"level":"info","ts":1560258043.178595,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"info","ts":1560258043.1788135,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":true,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"READY"}
{"level":"info","ts":1560258043.1788967,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.11:2379 (0xc4202700c0)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":4}

{"level":"warn","ts":1560258044.179831,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:44.179+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

{"level":"info","ts":1560258045.1789258,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"READY","new-state":"TRANSIENT_FAILURE"}
{"level":"info","ts":1560258045.1789773,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":3}
{"level":"info","ts":1560258045.179025,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"info","ts":1560258045.1790545,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"TRANSIENT_FAILURE"}
{"level":"info","ts":1560258045.179076,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"warn","ts":1560258045.1788998,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = Unavailable desc = transport is closing","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:45.179+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = Unavailable desc = transport is closing"}

{"level":"info","ts":1560258045.1792712,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":true,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"READY"}
{"level":"info","ts":1560258045.1793182,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.11:2379 (0xc4202700c0)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":4}

{"level":"warn","ts":1560258046.181984,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:46.182+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

{"level":"warn","ts":1560258047.179621,"caller":"picker/roundrobin_balanced.go:88","msg":"balancer failed","error":"rpc error: code = Unavailable desc = transport is closing","address":"http://192.168.1.11:2379","success":false,"bytes-sent":true,"bytes-received":false}
{"level":"warn","ts":"2019-06-11T16:00:47.179+0300","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-914b6909-27ee-41df-ae86-945af69394b7/192.168.1.11:2379","attempt":0,"error":"rpc error: code = Unavailable desc = transport is closing"}
{"level":"info","ts":1560258047.1796436,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"READY","new-state":"TRANSIENT_FAILURE"}
{"level":"info","ts":1560258047.179965,"caller":"balancer/balancer.go:258","msg":"generated picker","balancer-id":"buqxbanqdvck","policy":"etcd-client-roundrobin-balanced","subconn-ready":["http://127.0.0.1:2379 (0xc420270130)","http://192.168.1.17:2379 (0xc420270100)","http://192.168.1.7:2379 (0xc4202700e0)"],"subconn-size":3}
{"level":"info","ts":1560258047.1801736,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"TRANSIENT_FAILURE","new-state":"CONNECTING"}
{"level":"info","ts":1560258047.1802108,"caller":"balancer/balancer.go:189","msg":"state changed","balancer-id":"buqxbanqdvck","connected":false,"subconn":"0xc4202700c0","address":"http://192.168.1.11:2379","old-state":"CONNECTING","new-state":"TRANSIENT_FAILURE"}
"

**Comment by vimalk78** [comment]
Referring Client Documentation :
https://github.com/etcd-io/etcd/blob/master/Documentation/learning/design-client.md

According to the client design doc, the version `3.2.25` uses `clientv3-grpc1.7` balancer. This version of balancer retries the same endpoint for Transient Failures, which you are also observing.

If possible try using higher version of client.

@gyuho can explain better.
