### ISSUE TITLE
data corruption tocommit(5422980) is out of range

### ISSUE THREAD

**Issue by babarismail** [etcd-io/etcd#10817]
Hello,

I have seen this issue reported in other posts but didn't get a definitive answer regarding why this happens and if there is a way to prevent this from happening. I am currently using version 3.2.7 and was wondering any bug fixes were released after this which may resolve this issue.

In our case, this happens when a machine is rebooted and the node attempts to join the cluster.

**Comment by jingyih** [comment]
Can you provide the server log?

**Comment by babarismail** [comment]
Here is the log


sh-4.2# journalctl  -u etcd
-- Logs begin at Thu 2019-06-13 01:31:11 GMT, end at Fri 2019-06-14 23:15:28 GMT. --
Jun 13 01:31:27 ops0-ccn1-1 systemd[1]: Starting Etcd...
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.x.x.x:2379,http://10.x.x.x:4001
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.x.x.x:2380
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_INITIAL_CLUSTER=ops0-ccn1-1=http://10.x.x.x:2380,
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: recognized and used environment variable ETCD_NAME=ops0-ccn1-1
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: etcd Version: 3.2.7
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: Git SHA: bb66589
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: Go Version: go1.8.3
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: Go OS/Arch: linux/amd64
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: setting maximum number of CPUs to 56, total number of available CPUs is 56
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: listening for peers on http://0.0.0.0:2380
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: listening for client requests on 0.0.0.0:2379
Jun 13 01:31:28 ops0-ccn1-1 etcd[15150]: listening for client requests on 0.0.0.0:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: name = ops0-ccn1-1
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: data dir = /var/lib/etcd
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: member dir = /var/lib/etcd/member
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: heartbeat = 100ms
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: election = 1000ms
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: snapshot count = 100000
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: advertise client URLs = http://10.x.x.x:2379,http://10.x.x.x:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: initial advertise peer URLs = http://10.x.x.x:2380
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: initial cluster = ops0-ccn1-1=http://10.x.x.x:2380,ops0-ccn1-2=http://10.22
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: starting member d2ce2633997c6a24 in cluster 69e86257c344c4b2
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: d2ce2633997c6a24 became follower at term 0
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: newRaft d2ce2633997c6a24 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: d2ce2633997c6a24 became follower at term 1
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: simple token is not cryptographically signed
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: starting peer 4277a52756c33888...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started HTTP pipelining with peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: added peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: starting peer e733aa0c2f2722f7...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer 4277a52756c33888 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer 4277a52756c33888 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started HTTP pipelining with peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer e733aa0c2f2722f7 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: added peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: started streaming with peer e733aa0c2f2722f7 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: starting server... [version: 3.2.7, cluster version: to_be_decided]
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: the member has been permanently removed from the cluster
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: the data-dir used by this member must be removed.
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: added member 4277a52756c33888 [http://10.x.x.194:2380] to cluster 69e86257c344c4b2
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: publish error: etcdserver: request cancelled
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: publish error: etcdserver: request cancelled
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: aborting publish because server is stopped
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: added member d2ce2633997c6a24 [http://10.x.x.x:2380] to cluster 69e86257c344c4b2
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: added member e733aa0c2f2722f7 [http://10.x.x.195:2380] to cluster 69e86257c344c4b2
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: streaming request ignored (ID mismatch got 15dc7c86fbc22c12 want d2ce2633997c6a24)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopping peer 4277a52756c33888...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped HTTP pipelining with peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopping peer e733aa0c2f2722f7...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped HTTP pipelining with peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: Started Etcd.
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: etcd.service holdoff time over, scheduling restart.
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopping peer 4277a52756c33888...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped HTTP pipelining with peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer 4277a52756c33888 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopping peer e733aa0c2f2722f7...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped HTTP pipelining with peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (stream MsgApp v2 reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped streaming with peer e733aa0c2f2722f7 (stream Message reader)
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: stopped peer e733aa0c2f2722f7
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: Started Etcd.
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: etcd.service holdoff time over, scheduling restart.
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: Stopped Etcd.
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: Starting Etcd...
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.x.x.x:2379,http://10.x.x.x:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.x.x.x:2380
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_INITIAL_CLUSTER=ops0-ccn1-1=http://10.x.x.x:2380,
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: recognized and used environment variable ETCD_NAME=ops0-ccn1-1
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: etcd Version: 3.2.7
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: Git SHA: bb66589
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: Go Version: go1.8.3
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: Go OS/Arch: linux/amd64
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: setting maximum number of CPUs to 56, total number of available CPUs is 56
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: the server is already initialized as member before, starting as etcd member...
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: listening for peers on http://0.0.0.0:2380
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: listening for client requests on 0.0.0.0:2379
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: listening for client requests on 0.0.0.0:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: name = ops0-ccn1-1
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: data dir = /var/lib/etcd
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: member dir = /var/lib/etcd/member
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: heartbeat = 100ms
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: election = 1000ms
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: snapshot count = 100000
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: advertise client URLs = http://10.x.x.x:2379,http://10.x.x.x:4001
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: restarting member d2ce2633997c6a24 in cluster 69e86257c344c4b2 at commit index 3
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: d2ce2633997c6a24 became follower at term 1
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: newRaft d2ce2633997c6a24 [peers: [], term: 1, commit: 3, applied: 0, lastindex: 3, lastterm: 1]
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: simple token is not cryptographically signed
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: starting server... [version: 3.2.7, cluster version: to_be_decided]
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: added member 4277a52756c33888 [http://10.x.x.194:2380] to cluster 69e86257c344c4b2
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: starting peer 4277a52756c33888...
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: started HTTP pipelining with peer 4277a52756c33888
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: d2ce2633997c6a24 [term: 1] received a MsgHeartbeat message with higher term from e733aa0c2f2722f7 [term: 338]
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: d2ce2633997c6a24 became follower at term 338
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: started streaming with peer 4277a52756c33888 (writer)
Jun 13 01:31:30 ops0-ccn1-1 etcd[16743]: tocommit(5588980) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: panic: tocommit(5588980) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: goroutine 90 [running]:
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201b8d80, 0x55f10d52bb2e, 0x5d, 0xc4201b8120, 0x2, 0x2)
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/Godeps/_workspace/src/github.com/coreos/pkg/cap
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc420270690, 0x5547f4)
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/log.go:191 +0x1
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4202644b0, 0x8, 0x15dc7c86fbc22c12, 0xe733aa0c2f2722f7, 0x15
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/raft.go:1100 +0
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/etcd/raft.stepFollower(0xc4202644b0, 0x8, 0x15dc7c86fbc22c12, 0xe733aa0c2f2722f7, 0x152, 0x0, 0x0
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/raft.go:1046 +0
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/etcd/raft.(*raft).Step(0xc4202644b0, 0x8, 0x15dc7c86fbc22c12, 0xe733aa0c2f2722f7, 0x152, 0x0, 0x0
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/raft.go:778 +0x
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: github.com/coreos/etcd/raft.(*node).run(0xc4201ab680, 0xc4202644b0)
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/node.go:323 +0x
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: created by github.com/coreos/etcd/raft.RestartNode
Jun 13 01:31:30 ops0-ccn1-1 start-etcd[16743]: /builddir/build/BUILD/etcd-bb66589f8cf18960c7f3d56b1b83753caeed9c7a/src/github.com/coreos/etcd/raft/node.go:223 +0x
Jun 13 01:31:30 ops0-ccn1-1 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by babarismail** [comment]
@jingyih

**Comment by jingyih** [comment]
I am less familiar with some of the logging messages in 3.2. But I found couple interesting ones:

```
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: the member has been permanently removed from the cluster
...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: the data-dir used by this member must be removed.
...
Jun 13 01:31:30 ops0-ccn1-1 etcd[15150]: streaming request ignored (ID mismatch got 15dc7c86fbc22c12 want d2ce2633997c6a24)
```

From the log message, it looks like the member being started was removed from cluster, maybe describe how it ended up into the current situation (did you remove or update any member prior to this)?

Also these would be helpful: how many members do you have in the cluster? Do you only see the "tocommit" error in one of them?

**Comment by babarismail** [comment]
I only see the tocommit error. Once or twice I have had to remove the node and add it back in through runtime configuration but that's it.

**Comment by jingyih** [comment]
Was data directory corrupted or lost for the member you are restarting? Somehow in this situation, the WAL files in new member's data dir does not match with that of the other members. I am still not sure how it ended up in this situation. Could you provide steps for reproduce this (with details on which member was removed, did you remove or modified its data dir, does the new member have same configuration parameters)? To mitigate: if your cluster still has quorum, try to remove the data dir of this member before restarting it.

**Comment by babarismail** [comment]
this issue occurs after the host is rebooted. with earlier versions on etcd, i was able to consistently reproduce this issue. With 3.2 it is relatively better. Mitigating this issue is not a problem but since our servers are rebooted regularly, it becomes an annoyance to re-add the member to the cluster or delete the data-dir.

**Comment by babarismail** [comment]
@jingyih where is the cluster information stored? it looks like there is some storage other than the data directory of the etcd node.
Maybe i can look into that?

**Comment by jingyih** [comment]
Normally rebooting an etcd server will not run into this issue. 

>this issue occurs after the host is rebooted. with earlier versions on etcd, i was able to consistently reproduce this issue.

Could you provide etcd version and the your reprouduce steps? So we can better understand what happened.
