### ISSUE TITLE
a wired phenomenon(duplicate revisions & obtain distributed lock timeout)

### ISSUE THREAD

**Issue by DeepCodeMind** [etcd-io/etcd#10825]
a wired phenomenon(duplicate revisions & obtain distributed lock timeout)
1. we use etcd(standalone deployed) for distributed lock. we find revision in etcd rsp is not unique.
2. A obtain distributed lock timeout(about 10 second), but other clients obtain the same lock during  
A's timeout period.

**Comment by DeepCodeMind** [comment]
is revision extremely unique for different lock requests?
another phenomenon: A and B recv the same revision rsp, A's time cost is normal(about 3~4ms), B's time cost is abnormal(about 30~300ms), A and B recv rsp(from etcd) almost at the same time.

**Comment by jingyih** [comment]
Could you provide more details on this? What is the request from A and B, what is the response? It will be very helpful if you can provide the steps to reproduce.

**Comment by DeepCodeMind** [comment]
Requests A and B are used to obtain different distributed locks. They recv the same revision in the header when request B has a large latency, and A and B recv rsp(from etcd) almost at the same time(the time to send two requests are obviously completely different). Is this meet expectation?

[2019-06-17 15:13:13.976] request A：url=http://127.0.0.1:2379/v3beta/lock/lock, rsp={"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2071443","raft_term":"8"}, latency: 525us
[2019-06-17 15:13:13.976] request B：url=http://127.0.0.1:2379/v3beta/lock/lock, rsp={"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2071443","raft_term":"8"}, latency: 26392us

**Comment by DeepCodeMind** [comment]
As the project is urgent, is it convenient to add QQ(759336561), voice contact?

**Comment by jingyih** [comment]
I am on currently on vacation so all my responses will be delayed. Hopefully someone else can help investigate this, otherwise I can take a closer look sometime next week.
