### ISSUE TITLE
Is it possible to disable fdatasync in bbolt ?

### ISSUE THREAD

**Issue by Sheph** [etcd-io/etcd#10845]
I have the following question: is it possible to disable fdatasync in tx.go in bbolt ? Looking at this code:
```
// write writes any dirty pages to disk.
func (tx *Tx) write() error {
        ...
	// Ignore file sync if flag is set on DB.
	if !tx.db.NoSync || IgnoreNoSync {
		if err := fdatasync(tx.db); err != nil {
			return err
		}
	}
}
```
It looks like there's db.NoSync flag that one can set and fdatasync will be disabled. The question is: how safe is it ? Will etcd still work ? I really don't need strong consistency guarantee, i.e. for my case it's ok if etcdserver returns success to, say, put request, then after a crash or powerdown the value is lost. It's just the cluster should agree on the same value for a key, if that value is not the most recent it's ok.

**Comment by xiang90** [comment]
> I really don't need strong consistency guarantee, i.e. for my case it's ok if etcdserver returns success to, say, put request, then after a crash or powerdown the value is lost. It's just the cluster should agree on the same value for a key, if that value is not the most recent it's ok.

you probably should try redis or run etcd on tempfs. we are not going to loose this constraint in etcd project.
