### ISSUE TITLE
etcd cluster

### ISSUE THREAD

**Issue by houami** [etcd-io/etcd#10844]
Commands I ran on the cluster
```
sudo docker run -d -p 4001:4001 -p 7001:7001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.3 /usr/local/bin/etcd -name=node1 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -advertise-client-urls http://$INTERNAL_IP:2379

sudo docker run -d -p 4001:4001 -p 7001:7001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.3 /usr/local/bin/etcd -name=node2 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -advertise-client-urls http://$INTERNAL_IP:2379

sudo docker run -d -p 4001:4001 -p 7001:7001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.3 /usr/local/bin/etcd -name=node3 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -advertise-client-urls http://$INTERNAL_IP:2379
```

`sudo docker exec -it etcd etcdctl member list`
8sagc52164694d: name=node1 peerURLs=http://localhost:2380 clientURLs=http://172.31.53.49:2379 isLeader=true

Problem:
Why all the nodes are leader nodes set to true

How to solve this.

**Comment by hexfusion** [comment]
> Why all the nodes are leader nodes set to true

Because you are not using the appropriate cluster flags[1], the result is 3 single node etcd clusters. Please review the documentation and let us know if you have any questions.

[1] https://etcd.io/docs/v3.3.12/op-guide/clustering

**Comment by houami** [comment]
@hexfusion how do i mention those with the docker run command
