### ISSUE TITLE
Preferred constant-false etcdserverpbCompare ?

### ISSUE THREAD

**Issue by pjz** [etcd-io/etcd#10846]
For various reasons, i sometimes want to force the evaluation of the failure ops of a transaction. Is there a preferred "always false" etcdserverpbCompare ?   I was thinking of just comparing the revision to a negative number, which should always fail, no?

**Comment by xiang90** [comment]
> I was thinking of just comparing the revision to a negative number, which should always fail, no?

it should always be false.
