### ISSUE TITLE
Potential bug on old cores due to usage of atomic.***64 functions

### ISSUE THREAD

**Issue by lzhfromustc** [etcd-io/etcd#10847]
I noticed that there is a usage of atomic.AddUint64() in File: pkg/idutil/id.go, Line:68
64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users of etcd are using these old cores/

**Comment by spzala** [comment]
@lzhfromustc thanks for reporting. I guess we can close it, if any users report such an issue we can handle it there. Hopefully this does not seems like a common problem as golang has just documented it. Thanks!

**Comment by lzhfromustc** [comment]
Thank you for your reply! I reported the usage of atomic64 because I saw grpc-go developers handled this as a bug and fixed it. Since this is no big deal for etcd, I am closing this issue.

**Comment by spzala** [comment]
@lzhfromustc thanks!
