### ISSUE TITLE
etcdctl unsetting ETCDCTL_API in lock exec

### ISSUE THREAD

**Issue by devinrsmith** [etcd-io/etcd#10840]
`etcdctl lock <lockname> exec` appears to be unsetting the environment variable ETCDCTL_API for the executed command. (And it might be unsetting other ETCDCTL_X variables, I haven't checked...)

For example:

```shell
13:59 $ MY_API=3 ETCDCTL_API=3 etcdctl lock /locks env | grep API
MY_API=3
✔ ~
```

Only `MY_API` shows up in the output.

```shell
13:59 $ etcd --version
etcd Version: 3.3.12
Git SHA: GitNotFound
Go Version: go1.11.5
Go OS/Arch: darwin/amd64
✔ ~
```

**Comment by spzala** [comment]
Investigating
