### ISSUE TITLE
Docs: demo: "auth" section outdated

### ISSUE THREAD

**Issue by fxkr** [etcd-io/etcd#10856]
Referring to this https://github.com/etcd-io/etcd/blob/master/Documentation/demo.md#Auth

The very last command:

```
etcdctl --endpoints=${ENDPOINTS} --user=root:123 get foo1
```

is expected to return a "permission denied" error. But it succeeds instead. I think this is because the "root" role now implicitly has access to everything. To actually demonstrate the feature a different role would need to be created (it's probably best to still create the root user with root role, to not lock people out of their etcd setups).

```
% etcd --version
etcd Version: 3.3.0+git
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.12.2
Go OS/Arch: linux/amd64
```

**Comment by jingyih** [comment]
cc @mitake

**Comment by mitake** [comment]
@fxkr @jingyih thanks for pointing out and let me know. I'll update it.
