### ISSUE TITLE
Docs: demo: "snapshot save" example does not work

### ISSUE THREAD

**Issue by fxkr** [etcd-io/etcd#10855]
This is a documentation issue only!

Following the docs https://github.com/etcd-io/etcd/blob/master/Documentation/demo.md#Snapshot (only with different endpoint IP's, all my etcd's are on localhost) I get an unexpected error at this command:

```
% etcdctl --endpoints=$ENDPOINTS snapshot save my.db
Error: snapshot must be requested to one selected node, not multiple [127.0.0.1:2370 127.0.0.1:2371 127.0.0.1:2372]
```

If I specify a single node (`--endpoints=127.0.0.1:2370`) it works fine. The only problem here is that the docs have the wrong command.

```
% etcd --version
etcd Version: 3.3.0+git
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.12.2
Go OS/Arch: linux/amd64
```
(as packaged by Fedora 30)

ETCDCTL_API=3 as in the demo.

**Comment by spzala** [comment]
@fabxc agree, it's a doc bug. Are you interested in creating a PR to fix it? Thanks!

**Comment by nilsocket** [comment]
@spzala
Don't you think it's good to fix `etcdctl`, to redirect the command to leader in case of snapshot.

Thank you.

**Comment by spzala** [comment]
@nilsocket the current behavior is to support for a single node as the error says. This should be fixed in doc in my opinion. If there is a use case for multiple endpoints, that should be a separate feature and implementation. /cc @fxkr @gyuho

**Comment by nilsocket** [comment]
@spzala No, I don't mean to get snapshots from multiple endpoints. If we have multiple endpoints mentioned, while client is trying to take a snapshot, then we can redirect and get the snapshot from leader rather than throwing out an error.

Thank you.

**Comment by spzala** [comment]
@nilsocket I see but that still can be a little messy and we don't know what exactly the intention of user when multiple endpoints are specified, error seems more cleaner. Regardless if that's a desired output that should be opened as a separate issue in my understanding. Thanks!

**Comment by agargi** [comment]
@fxkr I imagine that multiple endpoints can potentially belong to different clusters too. If multiple endpoints are allowed, it is not possible to say which cluster resulted in generation of snapshot. /cc @gyuho @spzala

**Comment by fxkr** [comment]
@agargi True. But that seems like a corner case that just needs handling somehow, rather than a desirable use case that needs to be supported. Correct me if I'm wrong.

If `--endpoints` was extended to support multiple endpoints (like the `s` in `endpoints` implies), then, as a user, in this situation, I would probably want `etcd` to detect the situation where the endpoints belong to different clusters and issue an error message instead of creating a snapshot.
