### ISSUE TITLE
cluster members behinds NAT

### ISSUE THREAD

**Issue by Grey-Bit** [etcd-io/etcd#10857]
I need to setup a 3 member etcd cluster in the following way:
Members A and B would be in the private network and can freely communicate to each other.
Member C is in the public network. A and B can open connections to C, but C can't open connections to A and B.

Is there a way to setup such a cluster without VPN?

**Comment by spzala** [comment]
@Grey-Bit I would suggest to ask such questions in the etcd user groups like etcd slack channel for quick answer and discussions. Thanks!
