### ISSUE TITLE
integration test not working on Windows

### ISSUE THREAD

**Issue by rustyx** [etcd-io/etcd#10854]
The integration package, which is very useful for integration testing, isn't working on Windows:

```
func TestEtcd(t *testing.T) {
	c := integration.NewClusterV3(t, &integration.ClusterConfig{
		Size: 3,
	})
	defer c.Terminate(t)
}
```

Throws:

`cluster.go:485: listen unix 127.0.0.1:2100111204: bind: The requested address is not valid in its context.`

How to instantiate an in-memory cluster on Windows?

**Comment by fcddk** [comment]
I recommend deploying etcd on a Linux virtual machine. It is easy to get an answer when encountering an error.

**Comment by xkisu** [comment]
I am also experiencing this problem

**Comment by xkisu** [comment]
I believe this is related to #6959, more specifically to how addresses are being handled here https://github.com/etcd-io/etcd/blob/master/integration/bridge.go#L46

**Comment by rustyx** [comment]
This is about the `integration` package which is the recommended way of creating an in-memory temporary cluster. It does not work on Windows. Even though etcd standalone server obviously does.
