### ISSUE TITLE
Does auth in etcd need to be enabled in both v2 and v3 mode?

### ISSUE THREAD

**Issue by arjunsingri** [etcd-io/etcd#10869]
I have enabled authentication in my etcd cluster (v3.3.13). That works fine with etcdctl v2 with and I am required to authenticate for every request through etcdctl v2. But if I use a v3 client in golang, I am able to bypass the auth. Looks like I need to enable auth for both v2 and v3. Is that true? Also, if I enable the auth using ETCDCTL_API=3 etcdctl, would a client in v2 be able to bypass the auth?

**Comment by mitake** [comment]
@arjunsingri Yes, etcd v2 and v3 have different auth mechanisms for each. You need to configure both of them if you want to use v2 and v3 in a single cluster.

**Comment by arjunsingri** [comment]
But isn't this a security issue? If someone is only using v2 api and has enabled auth for v2, someone else can contact the etcd cluster using the v3 api and bypass the auth.

**Comment by mitake** [comment]
No. v2 and v3 APIs don't share any data.

**Comment by spzala** [comment]
Thanks @mitake !! @arjunsingri I hope it's OK to close this issue now, if you run into a specific security issue or use case please feel free reopen or ideally open a new issue. Thanks!
