### ISSUE TITLE
etcdv3 too many wal files cause high cpu (200%) then cause the high mem useage to OOM

### ISSUE THREAD

**Issue by toranger** [etcd-io/etcd#10868]
etcd Version: 3.3.5
Git SHA: 70c872620
Go Version: go1.9.6
Go OS/Arch: linux/amd64

I cut the all the server which connect to etcd, only start the etcd server, although has this problem.
I figure out there are too many wal files(128+), but default wal file number is 5. why there are too many wals? I see the code it has period delete the rest of wals? Does it not work?

How can I compact the these wal files? and start etcd server success?

there are part of the wal dir:
-rw------- 1 user_00 users 64020080 Jul  1 09:24 0000000000002671-0000000001067115.wal
-rw------- 1 user_00 users 64027624 Jul  1 09:30 0000000000002672-0000000001067437.wal
-rw------- 1 user_00 users 64020208 Jul  1 09:35 0000000000002673-0000000001067758.wal
-rw------- 1 user_00 users 64027680 Jul  1 09:41 0000000000002674-0000000001067a7a.wal
-rw------- 1 user_00 users 64019280 Jul  1 09:47 0000000000002675-0000000001067d9c.wal
-rw------- 1 user_00 users 64027624 Jul  1 09:52 0000000000002676-00000000010680be.wal
-rw------- 1 user_00 users 64020168 Jul  1 09:58 0000000000002677-00000000010683df.wal
-rw------- 1 user_00 users 64027576 Jul  1 10:04 0000000000002678-0000000001068701.wal
-rw------- 1 user_00 users 64020208 Jul  1 10:10 0000000000002679-0000000001068a22.wal
-rw------- 1 user_00 users 64027624 Jul  1 10:15 000000000000267a-0000000001068d44.wal
-rw------- 1 user_00 users 64020056 Jul  1 10:21 000000000000267b-0000000001069065.wal
-rw------- 1 user_00 users 64027464 Jul  1 10:27 000000000000267c-0000000001069387.wal
-rw------- 1 user_00 users 64020200 Jul  1 10:33 000000000000267d-00000000010696a8.wal
-rw------- 1 user_00 users 64026504 Jul  1 10:38 000000000000267e-00000000010699ca.wal
-rw------- 1 user_00 users 64020304 Jul  1 10:44 000000000000267f-0000000001069ceb.wal
-rw------- 1 user_00 users 64027624 Jul  1 10:50 0000000000002680-000000000106a00e.wal
-rw------- 1 user_00 users 64019168 Jul  1 10:55 0000000000002681-000000000106a32f.wal
-rw------- 1 user_00 users 64027624 Jul  1 11:01 0000000000002682-000000000106a651.wal
-rw------- 1 user_00 users 64024240 Jul  1 11:07 0000000000002683-000000000106a972.wal
-rw------- 1 user_00 users 64027624 Jul  1 11:13 0000000000002684-000000000106ac9b.wal
-rw------- 1 user_00 users 64022880 Jul  1 11:18 0000000000002685-000000000106afbc.wal
-rw------- 1 user_00 users 64025472 Jul  1 11:24 0000000000002686-000000000106b2e5.wal
-rw------- 1 user_00 users 64020128 Jul  1 11:30 0000000000002687-000000000106b606.wal
-rw------- 1 user_00 users 64027352 Jul  1 11:35 0000000000002688-000000000106b928.wal
-rw------- 1 user_00 users 64006872 Jul  1 11:41 0000000000002689-000000000106bc49.wal
-rw------- 1 user_00 users 64058024 Jul  1 11:47 000000000000268a-000000000106bf74.wal
-rw------- 1 user_00 users 64053984 Jul  1 11:52 000000000000268b-000000000106c290.wal

**Comment by mingyuanzhu** [comment]
Hi guys, do you resolve the issue?

**Comment by futangwa** [comment]
@toranger hello, how's your problem solved? thanks.
