### ISSUE TITLE
Etcd create more than 5 wal files cause the high cpu and high mem useage which can not start etcd normally!

### ISSUE THREAD

**Issue by toranger** [etcd-io/etcd#10872]
1. Etcd verison:
etcd Version: 3.3.5
Git SHA: 70c872620
Go Version: go1.9.6
Go OS/Arch: linux/amd64

2. Questions
1) Etcd create more than default 5 wal files, seem to load and decode all wals in memery finally cause the oom? Look the snap files create time and only flush on disk twice a day, Does not it should create snap file when entry with default number 100000 and why there are too many wal files(128+) over the default limit 5?

2) Three etcd node in cluster, one of these order is:
etcd --name infra0 --initial-advertise-peer-urls http://A:2380 --data-dir /data/cos-config-etcd-data/infra0.etcd --max-txn-ops 4096 --quota-backend-bytes 12589934592 --listen-peer-urls http://A:2380 --auto-compaction-retention=1 --listen-client-urls http://A:2379,http://127.0.0.1:2379 --advertise-client-urls http://A:2379 --initial-cluster-token etcd-cluster-1 --initial-cluster   "infra0=http://A:2380,infra1=http://B:2380,infra2=http://C:2380" --initial-cluster-state new

3. Parts of the wals:
-rw------- 1 user_00 users 64000000 Jul  1 19:41 0.tmp
-rw------- 1 user_00 users 64012952 Jul  1 09:29 0000000000002672-000000000106741a.wal
-rw------- 1 user_00 users 64034912 Jul  1 09:35 0000000000002673-000000000106773b.wal
-rw------- 1 user_00 users 64013008 Jul  1 09:41 0000000000002674-0000000001067a5d.wal
-rw------- 1 user_00 users 64034024 Jul  1 09:46 0000000000002675-0000000001067d7f.wal
-rw------- 1 user_00 users 64012912 Jul  1 09:52 0000000000002676-00000000010680a1.wal
-rw------- 1 user_00 users 64034912 Jul  1 09:58 0000000000002677-00000000010683c2.wal
-rw------- 1 user_00 users 64012920 Jul  1 10:04 0000000000002678-00000000010686e4.wal
-rw------- 1 user_00 users 64034912 Jul  1 10:09 0000000000002679-0000000001068a05.wal
-rw------- 1 user_00 users 64012920 Jul  1 10:15 000000000000267a-0000000001068d27.wal
-rw------- 1 user_00 users 64034720 Jul  1 10:21 000000000000267b-0000000001069048.wal
-rw------- 1 user_00 users 64012920 Jul  1 10:27 000000000000267c-000000000106936a.wal
-rw------- 1 user_00 users 64034912 Jul  1 10:32 000000000000267d-000000000106968b.wal
-rw------- 1 user_00 users 64011880 Jul  1 10:38 000000000000267e-00000000010699ad.wal
-rw------- 1 user_00 users 64035008 Jul  1 10:44 000000000000267f-0000000001069cce.wal
-rw------- 1 user_00 users 64012912 Jul  1 10:49 0000000000002680-0000000001069ff1.wal
-rw------- 1 user_00 users 64033872 Jul  1 10:55 0000000000002681-000000000106a312.wal
-rw------- 1 user_00 users 64012920 Jul  1 11:01 0000000000002682-000000000106a634.wal
-rw------- 1 user_00 users 64038936 Jul  1 11:07 0000000000002683-000000000106a955.wal
-rw------- 1 user_00 users 64012920 Jul  1 11:12 0000000000002684-000000000106ac7e.wal
-rw------- 1 user_00 users 64037664 Jul  1 11:18 0000000000002685-000000000106af9f.wal
-rw------- 1 user_00 users 64010848 Jul  1 11:24 0000000000002686-000000000106b2c8.wal
-rw------- 1 user_00 users 64034912 Jul  1 11:30 0000000000002687-000000000106b5e9.wal
-rw------- 1 user_00 users 64012760 Jul  1 11:35 0000000000002688-000000000106b90b.wal
-rw------- 1 user_00 users 64050152 Jul  1 11:41 0000000000002689-000000000106bc2c.wal
-rw------- 1 user_00 users 64058232 Jul  1 11:47 000000000000268a-000000000106bf58.wal
-rw------- 1 user_00 users 64053984 Jul  1 11:52 000000000000268b-000000000106c274.wal
-rw------- 1 user_00 users 64048232 Jul  1 11:58 000000000000268c-000000000106c585.wal
-rw------- 1 user_00 users 64064440 Jul  1 12:03 000000000000268d-000000000106c896.wal

4. All Snaps files:
-rw-r--r-- 1 user_00 users      14446 Jun 29 09:47 0000000000000053-00000000010059a9.snap
-rw-r--r-- 1 user_00 users      14446 Jun 29 21:41 0000000000000053-000000000101e04a.snap
-rw-r--r-- 1 user_00 users      14445 Jun 30 09:35 0000000000000053-00000000010366eb.snap
-rw-r--r-- 1 user_00 users      14446 Jun 30 21:30 0000000000000053-000000000104ed8c.snap
-rw-r--r-- 1 user_00 users      14446 Jul  1 09:24 0000000000000053-000000000106742d.snap

5. When restart the etcd with these wal files(128+) cause the high cpu and memery usage, the stack trace is there, it seems like to load all files to decode? 
[stacktrace.txt](https://github.com/etcd-io/etcd/files/3357325/stacktrace.txt)

6. You can see the last snap file is before every wal files time, I filter the Jun 30 and Jul 1
etcd logs is there, it seems that only create the snap file twice one day?
[etcdlogJun30.txt](https://github.com/etcd-io/etcd/files/3357339/etcdlogJun30.txt)

[etcdlogJul1.txt](https://github.com/etcd-io/etcd/files/3357340/etcdlogJul1.txt)

7. Summary
I want to know:
1) How does the snap work? why only create twice a day  and why there are too many wals?
2) How to  avoid these and What should I do to restart etcd normal?

Ask for help! ths!

**Comment by hongwozai** [comment]
+1, I also encountered the same problem.

**Comment by Uzay-G** [comment]
I am encountering this issue now. How did you fix it?
