### ISSUE TITLE
how is the best performance of etcd

### ISSUE THREAD

**Issue by itcheng2019** [etcd-io/etcd#10876]
use build-in test tool benchmark to test, the best qps is 30000/s.

Can it be better? 

Hardware Configuration：
CPU: 24cores
Mem：64G
Disk：800M/s+
Network ：100M

none of them is full used ,so it can be better, but i do't know how to do next

 **start.sh**
./etcd \
--data-dir=default.etcd \
--name etcd \
--initial-advertise-peer-urls http://192.168.152.133:2380 \
--listen-peer-urls http://192.168.152.133:2380 \
--advertise-client-urls http://192.168.152.133:2379 \
--listen-client-urls http://192.168.152.133:2379,http://127.0.0.1:2379 \
--initial-cluster etcd=http://192.168.152.133:2380 \
--initial-cluster-state new \
--initial-cluster-token token-01 \
--max-request-bytes '33554432' \
--quota-backend-bytes '8589934592' \
--debug

**test.sh**
benchmark txn-put \
--endpoints=192.168.152.133:2379 \
--conns=10 \
--clients=1000 \
--total=100000 \
--key-size=100 \
--val-size=100 \

**Comment by jingyih** [comment]
What is the etcd version? Maybe remove the --debug flag from your config? How much disk and CPU resource are utilized during the benchmark?

There are some benchmark results here for your reference: https://github.com/etcd-io/etcd/tree/master/Documentation/benchmarks

I think we are going to have new benchmark result for the upcoming 3.4 release.

**Comment by itcheng2019** [comment]
@jingyih 
thanks！
the etcd version is V3.3.13

Resource occupation：
cpu：1000% 
mem: 8%
net: about 20M
disk：about 20M
