### ISSUE TITLE
The interval tree is not complete implementation based on red-black tree

### ISSUE THREAD

**Issue by xkeyideal** [etcd-io/etcd#10877]
Because of Interval Tree of Etcd use golang nil as  red-black tree "NIL", delete someone node The Tree will not according with Property 5. 

For example: 

![image](https://user-images.githubusercontent.com/6369390/60792585-87fb3900-a198-11e9-97f9-be4c15ee9854.png)

Delete Node 514, then delete node 11 should be:

![image](https://user-images.githubusercontent.com/6369390/60792685-bb3dc800-a198-11e9-9eab-ec20b9d87dec.png)

**Comment by xkeyideal** [comment]
Delete Node 11, the interval tree code will not execute `deleteFixup` function, but this wil cause inconsistency with the nature of red-black tree.

**Comment by xiang90** [comment]
@xkeyideal 

Thanks for pointing this out. Can you write a test case and a fix?

**Comment by xkeyideal** [comment]
@xiang90 YES，I will make a pull request for the interval tree

**Comment by xkeyideal** [comment]
@xiang90 

Please see my pull request code, can not pass the case of TestCtlV3AuthAndWatch

**Comment by xkeyideal** [comment]
I find all use interval tree codes, some codes use Union function not use pointer, I change them all, but no use.

**Comment by xkeyideal** [comment]
@xiang90 

Please take a look the pull request, thx
