### ISSUE TITLE
TSL config err

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#10873]
Jul 04 14:52:23 localhost.localdomain etcd[12873]: ClientTLS: cert = /etc/etcd/ssl/client.pem, key = /etc/etcd/ssl/client_key.pem, ca = , trusted-ca = /ssl/ca.pem, client-cert-a...crl-file = 
Jul 04 14:52:24 localhost.localdomain etcd[12873]: 8e9e05c52164694d is starting a new election at term 11
Jul 04 14:52:24 localhost.localdomain etcd[12873]: 8e9e05c52164694d became candidate at term 12
Jul 04 14:52:24 localhost.localdomain etcd[12873]: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 12
Jul 04 14:52:24 localhost.localdomain etcd[12873]: 8e9e05c52164694d became leader at term 12
Jul 04 14:52:24 localhost.localdomain etcd[12873]: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 12
Jul 04 14:52:24 localhost.localdomain etcd[12873]: published {Name:hello ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
Jul 04 14:52:24 localhost.localdomain etcd[12873]: ready to serve client requests
Jul 04 14:52:24 localhost.localdomain systemd[1]: Started Etcd Server.
Jul 04 14:52:24 localhost.localdomain etcd[12873]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged
why? it is insecure.

**Comment by jingyih** [comment]
Can you try using https for the client URL?

**Comment by fcddk** [comment]
cannot listen on TLS for 127.0.0.1:2380: KeyFile and CertFile are not presented.
change to https

**Comment by fcddk** [comment]
etcd.service:

[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
# set GOMAXPROCS to number of processors
ExecStart=/bin/bash -c "GOMAXPROCS=$(nproc) /usr/bin/etcd"
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

etcd.conf:
# [member]
ETCD_NAME=etcd0
ETCD_DATA_DIR="/var/lib/etcd/etcd0.etcd"
ETCD_WAL_DIR="/var/lib/etcd/wal"
ETCD_SNAPSHOT_COUNT="100"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
#ETCD_LISTEN_PEER_URLS="http://192.168.79.132:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.79.132:2379,https://127.0.0.1:2379"
ETCD_MAX_SNAPSHOTS="5"
ETCD_MAX_WALS="5"
#ETCD_CORS=""

# [cluster]
#ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.0.153:2380"
# if you use different ETCD_NAME (e.g. test), set ETCD_INITIAL_CLUSTER value for this name, i.e. "test=http://..."
#ETCD_INITIAL_CLUSTER="etcd0=https://192.168.0.153:2380,etcd1=https://192.168.0.154:2380,etcd2=https://192.168.0.164:2380"
#ETCD_INITIAL_CLUSTER_STATE="new"
#ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
# [cluster]
#ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.0.153:2380"
# if you use different ETCD_NAME (e.g. test), set ETCD_INITIAL_CLUSTER value for this name, i.e. "test=http://..."
#ETCD_INITIAL_CLUSTER="etcd0=https://192.168.0.153:2380,etcd1=https://192.168.0.154:2380,etcd2=https://192.168.0.164:2380"
#ETCD_INITIAL_CLUSTER_STATE="new"
#ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.79.132:2379"

# [security]
ETCD_CERT_FILE="/etc/etcd/ssl/etcd.pem"
ETCD_KEY_FILE="/etc/etcd/ssl/etcd-key.pem"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_TRUSTED_CA_FILE="/etc/etcd/ssl/ca.pem"
ETCD_AUTO_TLS="false"
#ETCD_PEER_CERT_FILE="/etc/etcd/ssl/etcd.pem"
#ETCD_PEER_KEY_FILE="/etc/etcd/ssl/etcd-key.pem"
#ETCD_PEER_CLIENT_CERT_AUTH="true"
#ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/ssl/ca.pem"
#ETCD_PEER_AUTO_TLS="true"

# [logging]
#ETCD_DEBUG="false"
# examples for -log-package-levels etcdserver=WARNING,security=DEBUG
#ETCD_LOG_PACKAGE_LEVELS=""
#ETCD_LOG_OUTPUT="default"
#
#[Unsafe]
#ETCD_FORCE_NEW_CLUSTER="false"
#
#[Version]
#ETCD_VERSION="false"
#ETCD_AUTO_COMPACTION_RETENTION="0"
#
#[Profiling]
#ETCD_ENABLE_PPROF="false"
#ETCD_METRICS="basic"
#
#[Auth]
ETCD_AUTH_TOKEN="simple"


Jul 05 09:18:55 localhost.localdomain polkitd[6277]: Unregistered Authentication Agent for unix-process:8537:495833 (system bus name :1.53, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale
Jul 05 09:18:55 localhost.localdomain etcd[8543]: serving client requests on 127.0.0.1:2379
Jul 05 09:18:55 localhost.localdomain etcd[8543]: serving client requests on 192.168.79.132:2379
Jul 05 09:18:55 localhost.localdomain etcd[8543]: rejected connection from "127.0.0.1:47196" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly becaus
Jul 05 09:18:55 localhost.localdomain bash[8543]: WARNING: 2019/07/05 09:18:55 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad cert
Jul 05 09:18:55 localhost.localdomain etcd[8543]: rejected connection from "192.168.79.132:42628" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly b
Jul 05 09:18:55 localhost.localdomain bash[8543]: WARNING: 2019/07/05 09:18:55 Failed to dial 192.168.79.132:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad
[root@localhost ~]# journalctl -xe
Jul 05 09:19:42 localhost.localdomain etcd[8543]: rejected connection from "127.0.0.1:50118" (error "tls: first record does not look like a TLS handshake", ServerName "")
Jul 05 09:19:42 localhost.localdomain etcd[8543]: rejected connection from "127.0.0.1:50120" (error "tls: first record does not look like a TLS handshake", ServerName "")
Jul 05 09:19:42 localhost.localdomain etcd[8543]: rejected connection from "127.0.0.1:50124" (error "tls: first record does not look like a TLS handshake", ServerName "")

**Comment by fcddk** [comment]
What went wrong?
Single point deployment.

**Comment by fcddk** [comment]
chang to https 

Jul 05 10:52:36 localhost.localdomain polkitd[6277]: Unregistered Authentication Agent for unix-process:9734:1057933 (system bus name :1.92, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UT
Jul 05 10:52:36 localhost.localdomain etcd[9740]: rejected connection from "127.0.0.1:37742" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"cry
Jul 05 10:52:36 localhost.localdomain bash[9740]: WARNING: 2019/07/05 10:52:36 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; 
Jul 05 10:52:36 localhost.localdomain etcd[9740]: rejected connection from "192.168.79.132:33178" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of 
Jul 05 10:52:36 localhost.localdomain bash[9740]: WARNING: 2019/07/05 10:52:36 Failed to dial 192.168.79.132:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certifica

**Comment by fcddk** [comment]
http
Jul 05 11:35:37 localhost.localdomain etcd[10437]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/etcd/ssl/ca.pem, client-cert-auth = true, crl-file = 
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of peer url http://192.168.79.132:2380 is HTTP while peer key/cert files are presented. Ignored peer key/cert files.
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of peer url http://192.168.79.132:2380 is HTTP while client cert auth (--peer-client-cert-auth) is enabled. Ignored client cert auth for this url.
Jul 05 11:35:37 localhost.localdomain etcd[10437]: listening for peers on http://192.168.79.132:2380
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of client url http://127.0.0.1:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of client url http://127.0.0.1:2379 is HTTP while client cert auth (--client-cert-auth) is enabled. Ignored client cert auth for this url.
Jul 05 11:35:37 localhost.localdomain etcd[10437]: listening for client requests on 127.0.0.1:2379
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of client url http://192.168.79.132:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
Jul 05 11:35:37 localhost.localdomain etcd[10437]: The scheme of client url http://192.168.79.132:2379 is HTTP while client cert auth (--client-cert-auth) is enabled. Ignored client cert auth for this url.

**Comment by jingyih** [comment]
Have you tried to follow the instruction and examples in this documentation?
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md

**Comment by fcddk** [comment]
-- The start-up result is done.
Jul 05 16:18:25 localhost.localdomain polkitd[6284]: Unregistered Authentication Agent for unix-process:7456:401116 (system bus name :1.27, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from b
Jul 05 16:18:25 localhost.localdomain etcd[7462]: serving client requests on 192.168.79.132:2379
Jul 05 16:18:25 localhost.localdomain etcd[7462]: serving client requests on 127.0.0.1:2379
Jul 05 16:18:25 localhost.localdomain etcd[7462]: rejected connection from "192.168.79.132:34212" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verificati
Jul 05 16:18:25 localhost.localdomain bash[7462]: WARNING: 2019/07/05 16:18:25 Failed to dial 192.168.79.132:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
Jul 05 16:18:25 localhost.localdomain etcd[7462]: rejected connection from "127.0.0.1:50682" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification er
Jul 05 16:18:25 localhost.localdomain bash[7462]: WARNING: 2019/07/05 16:18:25 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.

**Comment by fcddk** [comment]
i use etcd.pem  and etcd-key.pem

**Comment by xiang90** [comment]
> published {Name:hello ClientURLs:[http://localhost:2379]

the configuration you provided to etcd includes http not https. please check the configuration again.
