### ISSUE TITLE
Add WaitGroup to prevent calling t.Fatalf after TestV3WatchCurrentPutOverlap function return.

### ISSUE THREAD

**Issue by yuzeming** [etcd-io/etcd#10886]
https://github.com/etcd-io/etcd/blob/eb7dd97135a5c60d9d9259886100823114e45815/integration/v3_watch_test.go#L480-L490

It could cause a `panic("Fail in goroutine after " + c.name + " has completed")` [Code](https://golang.org/src/testing/testing.go?s=19950:19973#L547)

**Comment by spzala** [comment]
@yuzeming I guess without preventing watching overlap, adding WaitGroup should be fine. Are you interested in creating a PR? Thanks!
