### ISSUE TITLE
issue when starting etcd

### ISSUE THREAD

**Issue by gregoiremahe** [etcd-io/etcd#10883]
Hi there,

I have a really complex problem with etcd.

We are doing recorvery process for etcd cluster. We are using kubespray ansible playbook on openstack to deploy the etcd cluster. That's working well. When we remove a server from the cluster directly via the cloud (openstack server delete), and we create it again (with the same network configuration, same IPs, mac addr...), etcd cluster fails to start (see logs below). BUT, when we rebuild the server (fresh install from the Debian 9 image), etcd cluster start successfully. Here is the summary of two processes we done : 

Working process : 

1. Create network configuration (IP, Mac addr, private network…)
2. Create server from Debian 9 image
3. Install etcd server (via kubespray)
4. All is working, etcd cluster is healthy :

```
root@master-2:~# etcdctl --endpoints=https://10.0.0.103:2379 --ca-file /etc/ssl/etcd/ssl/ca.pem --key-file /etc/ssl/etcd/ssl/member-master-2-key.pem --cert-file /etc/ssl/etcd/ssl/member-master-2.pem cluster-health
member 9339026b441db39 is healthy: got healthy result from https://10.0.0.103:2379
member 37ca612ea6a9fb18 is healthy: got healthy result from https://10.0.0.48:2379
member 74c470185ecb93e0 is healthy: got healthy result from https://10.0.3.213:2379
cluster is healthy
```

5. We rebuilt one of the server (openstack server rebuild master-2). When we check cluster-health, server is unreachable (logical)

6. We setup etcd cluster to remount it (with kubespray again). After this, cluster-health says that all nodes are reachable and healthy (logical again)

Not working process: 

1. [Same as above] Create network configuration (IP, Mac addr, private network…)
2. [Same as above] Create server from Debian 9 image
3. [Same as above] Install etcd server (via kubespray)
4. [Same as above] All is working, etcd cluster is healthy :

```
root@master-2:~# etcdctl --endpoints=https://10.0.0.103:2379 --ca-file /etc/ssl/etcd/ssl/ca.pem --key-file /etc/ssl/etcd/ssl/member-master-2-key.pem --cert-file /etc/ssl/etcd/ssl/member-master-2.pem cluster-health
member 9339026b441db39 is healthy: got healthy result from https://10.0.0.103:2379
member 37ca612ea6a9fb18 is healthy: got healthy result from https://10.0.0.48:2379
member 74c470185ecb93e0 is healthy: got healthy result from https://10.0.3.213:2379
cluster is healthy
```

5. [Differs from above] We deleted one of the server (openstack server delete master-2). When we check cluster-health, server is unreachable (logical)
6. [Differs from above] We created the server again, with the same network configuration (Same IPs, Mac addresses…)

7. We setup etcd cluster to remount it (with kubespray again). The ansible playbook fails because etcd fails to start… 

Here is the logs :

```
2019-07-09 10:06:15.897461 I | raft: 9339026b441db39 [term: 1] received a MsgHeartbeat message with higher term from 37ca612ea6a9fb18 [term: 5]
2019-07-09 10:06:15.898130 I | raft: 9339026b441db39 became follower at term 5
2019-07-09 10:06:15.898783 C | raft: tocommit(1827) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(1827) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 101 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc420155580, 0xfb6aab, 0x5d, 0xc420605600, 0x2, 0x2)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x15c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc4201babd0, 0x723)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4201e8690, 0x8, 0x9339026b441db39, 0x37ca612ea6a9fb18, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1100 +0x54
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.stepFollower(0xc4201e8690, 0x8, 0x9339026b441db39, 0x37ca612ea6a9fb18, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1046 +0x2b3
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4201e8690, 0x8, 0x9339026b441db39, 0x37ca612ea6a9fb18, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x10f7
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).run(0xc4201ccb40, 0xc4201e8690)
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:323 +0x67b
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode
	/home/ec2-user/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:223 +0x33e
```

So the final question is, why it’s working with a fresh install (disk formatted), but not with a recreate ? The disk is also formatted, for me there is no reason to have this error

**Comment by ridingmotorcycleslove** [comment]
I dont know

**Comment by gregoiremahe** [comment]
Finally I found the problem :) Closing this issue

**Comment by sharkymcdongles** [comment]
What was the problem? @gregoiremahe
