### ISSUE TITLE
cluster id mismatch

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#10897]
When I configured etcd.conf on three centos virtual machines
The following error occurred when starting the second etcd：

Jul 16 16:06:09 localhost.localdomain etcd[52351]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 16 16:06:09 localhost.localdomain etcd[52351]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 16 16:06:09 localhost.localdomain etcd[52351]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)

what's wrong?

**Comment by fcddk** [comment]
etcd.conf
#[Member]
#ETCD_CORS=""
ETCD_DATA_DIR="/var/lib/etcd/node2.etcd"
#ETCD_WAL_DIR=""
ETCD_LISTEN_PEER_URLS="http://192.168.195.129:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.195.129:2379,http://localhost:2379"
#ETCD_MAX_SNAPSHOTS="5"
#ETCD_MAX_WALS="5"
ETCD_NAME="node2"
ETCD_SNAPSHOT_COUNT="100000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_QUOTA_BACKEND_BYTES="0"
ETCD_MAX_REQUEST_BYTES="1572864"
ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
ETCD_GRPC_KEEPALIVE_TIMEOUT="20s"
#
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.195.129:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.195.129:2379"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""
#ETCD_DISCOVERY_SRV=""
ETCD_INITIAL_CLUSTER="node1=http://192.168.195.128:2380,node2=http://192.168.195.129:2380,node3=http://192.168.195.130:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_STRICT_RECONFIG_CHECK="true"
#ETCD_ENABLE_V2="true"

**Comment by jingyih** [comment]
Could you provide config of the other 2 nodes?

**Comment by fcddk** [comment]
only the url and name different.

**Comment by fcddk** [comment]
#[Member]
#ETCD_CORS=""
ETCD_DATA_DIR="/var/lib/etcd/node1.etcd"
#ETCD_WAL_DIR=""
ETCD_LISTEN_PEER_URLS="http://192.168.195.128:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.195.128:2379,https://localhost:2379"
#ETCD_MAX_SNAPSHOTS="5"
#ETCD_MAX_WALS="5"
ETCD_NAME="node1"
ETCD_SNAPSHOT_COUNT="100000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_QUOTA_BACKEND_BYTES="0"
ETCD_MAX_REQUEST_BYTES="1572864"
ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
ETCD_GRPC_KEEPALIVE_TIMEOUT="20s"
#
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.195.128:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.195.128:2379"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""
#ETCD_DISCOVERY_SRV=""
ETCD_INITIAL_CLUSTER="node1=http://192.168.195.128:2380,node2=http://192.168.195.129:2380,node3=http://192.168.195.130:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_STRICT_RECONFIG_CHECK="true"
#ETCD_ENABLE_V2="true"

**Comment by fcddk** [comment]
#[Member]
#ETCD_CORS=""
ETCD_DATA_DIR="/var/lib/etcd/etcd03.etcd"
#ETCD_WAL_DIR=""
ETCD_LISTEN_PEER_URLS="http://192.168.195.130:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.195.130:2379,https://localhost:2379"
ETCD_MAX_SNAPSHOTS="5"
ETCD_MAX_WALS="5"
ETCD_NAME="node3"
ETCD_SNAPSHOT_COUNT="100000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_QUOTA_BACKEND_BYTES="0"
ETCD_MAX_REQUEST_BYTES="1572864"
ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
ETCD_GRPC_KEEPALIVE_TIMEOUT="20s"
#
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.195.130:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.195.130:2379"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""
#ETCD_DISCOVERY_SRV=""
ETCD_INITIAL_CLUSTER="node1=http://192.168.195.128:2380,node2=http://192.168.195.129:2380,node3=http://192.168.195.130:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="existing"
ETCD_STRICT_RECONFIG_CHECK="true"
#ETCD_ENABLE_V2="true"

**Comment by jingyih** [comment]
> ETCD_INITIAL_CLUSTER_STATE="existing"

Should be "New" here for node3.

**Comment by fcddk** [comment]
tested it ,it is not the reason.

**Comment by fcddk** [comment]
i thought so before, and "new" change ro "existing", but still useless.

**Comment by fcddk** [comment]
err: Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)

**Comment by jingyih** [comment]
Could you provide server log?

**Comment by fcddk** [comment]
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 6f786ac7d981f803 on stream MsgApp v2 (dial tcp 192.168.195.130:2380: connect: no route to host)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 6f786ac7d981f803 on stream Message (dial tcp 192.168.195.130:2380: i/o timeout)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: b7c605eed4a1da21 is starting a new election at term 940
Jul 18 09:22:50 node2 etcd[7535]: b7c605eed4a1da21 became candidate at term 941
Jul 18 09:22:50 node2 etcd[7535]: b7c605eed4a1da21 received MsgVoteResp from b7c605eed4a1da21 at term 941
Jul 18 09:22:50 node2 etcd[7535]: b7c605eed4a1da21 [logterm: 1, index: 3] sent MsgVote request to 6f786ac7d981f803 at term 941
Jul 18 09:22:50 node2 etcd[7535]: b7c605eed4a1da21 [logterm: 1, index: 3] sent MsgVote request to 9c64eb1dbc4fc47e at term 941
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: remote[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to write 9c64eb1dbc4fc47e on pipeline (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)
Jul 18 09:22:50 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:51 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:51 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream MsgApp v2 (cluster ID mismatch)
Jul 18 09:22:51 node2 etcd[7535]: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:51 node2 etcd[7535]: failed to dial 9c64eb1dbc4fc47e on stream Message (cluster ID mismatch)

**Comment by fcddk** [comment]
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 09:25:00 node1 etcd[11214]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)

**Comment by jingyih** [comment]
Could you provide full server log? The more interesting part is the beginning of the log when the server starts. We need to understand what happened in bootstrapping process in order to root cause the cluster id mismatch.

**Comment by fcddk** [comment]
Jul 18 09:22:53 node2 etcd: b7c605eed4a1da21 is starting a new election at term 942
Jul 18 09:22:53 node2 etcd: b7c605eed4a1da21 became candidate at term 943
Jul 18 09:22:53 node2 etcd: b7c605eed4a1da21 received MsgVoteResp from b7c605eed4a1da21 at term 943
Jul 18 09:22:53 node2 etcd: b7c605eed4a1da21 [logterm: 1, index: 3] sent MsgVote request to 6f786ac7d981f803 at term 943
Jul 18 09:22:53 node2 etcd: b7c605eed4a1da21 [logterm: 1, index: 3] sent MsgVote request to 9c64eb1dbc4fc47e at term 943
Jul 18 09:22:53 node2 etcd: request sent was ignored (cluster ID mismatch: remote[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:53 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:53 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: publish error: etcdserver: request timed out
Jul 18 09:22:54 node2 etcd: health check for peer 6f786ac7d981f803 could not connect: dial tcp 192.168.195.130:2380: connect: no route to host (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Jul 18 09:22:54 node2 etcd: health check for peer 6f786ac7d981f803 could not connect: dial tcp 192.168.195.130:2380: connect: no route to host (prober "ROUND_TRIPPER_SNAPSHOT")
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 18 09:22:54 node2 etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)

**Comment by fcddk** [comment]
firewall stop ,  but  request timeout

**Comment by fcddk** [comment]
[root@node1 ~]# etcdctl --endpoints=https://[192.168.195.128]:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint health
https://[192.168.195.128]:2379 is healthy: successfully committed proposal: took = 675.205µs
[root@node1 ~]# etcdctl --endpoints=https://[192.168.195.129]:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint health
https://[192.168.195.129]:2379 is healthy: successfully committed proposal: took = 2.043848ms
[root@node1 ~]# etcdctl --endpoints=https://[192.168.195.130]:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint health
https://[192.168.195.130]:2379 is healthy: successfully committed proposal: took = 228.536811ms
[root@node1 ~]# 

but:
[root@node1 ~]# systemctl status etcd
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-07-18 10:18:13 CST; 16min ago
 Main PID: 11549 (etcd)
   CGroup: /system.slice/etcd.service
           └─11549 /usr/bin/etcd --name=node1 --data-dir=/var/lib/etcd/node1.etcd --listen-client-urls=https://192.168.195.128:2379,https://localhost...

Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want f220db43b21e2af0)
Jul 18 10:34:24 node1 etcd[11549]: request cluster ID mismatch (got 2d3173185977a3e4 want

**Comment by jingyih** [comment]
It looks like the new log you added here are still incomplete - logs when server was starting are still missing.

BTW, are data dir empty when they start?

**Comment by fcddk** [comment]
Jul 16 16:03:03 localhost etcd: listening for client requests on localhost:2379
Jul 16 16:03:03 localhost etcd: listening for client requests on 192.168.195.129:2379
Jul 16 16:03:03 localhost etcd: b7c605eed4a1da21 became follower at term 0
Jul 16 16:03:03 localhost etcd: newRaft b7c605eed4a1da21 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Jul 16 16:03:03 localhost etcd: b7c605eed4a1da21 became follower at term 1
Jul 16 16:03:03 localhost etcd: simple token is not cryptographically signed
Jul 16 16:03:03 localhost etcd: starting peer 6f786ac7d981f803...
Jul 16 16:03:03 localhost etcd: started HTTP pipelining with peer 6f786ac7d981f803
Jul 16 16:03:03 localhost etcd: started streaming with peer 6f786ac7d981f803 (writer)
Jul 16 16:03:03 localhost etcd: started streaming with peer 6f786ac7d981f803 (writer)
Jul 16 16:03:03 localhost etcd: started peer 6f786ac7d981f803
Jul 16 16:03:03 localhost etcd: added peer 6f786ac7d981f803
Jul 16 16:03:03 localhost etcd: starting peer 9c64eb1dbc4fc47e...
Jul 16 16:03:03 localhost etcd: started HTTP pipelining with peer 9c64eb1dbc4fc47e
Jul 16 16:03:03 localhost etcd: started peer 9c64eb1dbc4fc47e
Jul 16 16:03:03 localhost etcd: added peer 9c64eb1dbc4fc47e
Jul 16 16:03:03 localhost etcd: started streaming with peer 6f786ac7d981f803 (stream MsgApp v2 reader)
Jul 16 16:03:03 localhost etcd: started streaming with peer 6f786ac7d981f803 (stream Message reader)
Jul 16 16:03:03 localhost etcd: ClientTLS: cert = /etc/etcd/ssl/server.pem, key = /etc/etcd/ssl/server-key.pem, ca = , trusted-ca = /etc/etcd/ssl/ca.pem
, client-cert-auth = true, crl-file = 
Jul 16 16:03:03 localhost etcd: started streaming with peer 9c64eb1dbc4fc47e (writer)
Jul 16 16:03:03 localhost etcd: started streaming with peer 9c64eb1dbc4fc47e (writer)
Jul 16 16:03:03 localhost etcd: started streaming with peer 9c64eb1dbc4fc47e (stream MsgApp v2 reader)
Jul 16 16:03:03 localhost etcd: started streaming with peer 9c64eb1dbc4fc47e (stream Message reader)
Jul 16 16:03:03 localhost etcd: added member 6f786ac7d981f803 [http://192.168.195.130:2380] to cluster 2d3173185977a3e4
Jul 16 16:03:03 localhost etcd: added member 9c64eb1dbc4fc47e [http://192.168.195.128:2380] to cluster 2d3173185977a3e4
Jul 16 16:03:03 localhost etcd: added member b7c605eed4a1da21 [http://192.168.195.129:2380] to cluster 2d3173185977a3e4
Jul 16 16:03:03 localhost etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 16 16:03:03 localhost etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 16 16:03:03 localhost etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 16 16:03:03 localhost etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)
Jul 16 16:03:03 localhost etcd: request sent was ignored (cluster ID mismatch: peer[9c64eb1dbc4fc47e]=f220db43b21e2af0, local=2d3173185977a3e4)

health：
[root@node1 ~]# etcdctl --endpoints=http://192.168.195.128:2379,192.168.195.129:2379,192.168.195.130:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint health
192.168.195.130:2379 is healthy: successfully committed proposal: took = 2.347524ms
192.168.195.129:2379 is healthy: successfully committed proposal: took = 2.100853ms
http://192.168.195.128:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster

**Comment by fcddk** [comment]
[root@node1 ~]# etcdctl --endpoints=http://192.168.195.128:2379,192.168.195.129:2379,192.168.195.130:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem put hello 112
Error: rpc error: code = Unavailable desc = transport is closing

Jul 19 19:28:29 node2 etcd[8274]: failed to send out heartbeat on time (exceeded the 100ms timeout for 154.228128ms)
Jul 19 19:28:29 node2 etcd[8274]: server is likely overloaded
Jul 19 19:28:29 node2 etcd[8274]: failed to send out heartbeat on time (exceeded the 100ms timeout for 154.276145ms)
Jul 19 19:28:29 node2 etcd[8274]: server is likely overloaded
Jul 19 19:28:47 node2 etcd[8274]: rejected connection from "192.168.195.128:36794" (error "tls: first record does not look like a TLS handsh...rName "")
Jul 19 19:29:08 node2 etcd[8274]: failed to send out heartbeat on time (exceeded the 100ms timeout for 115.908902ms)
Jul 19 19:29:08 node2 etcd[8274]: server is likely overloaded
Jul 19 19:29:08 node2 etcd[8274]: failed to send out heartbeat on time (exceeded the 100ms timeout for 116.002751ms)
Jul 19 19:29:08 node2 etcd[8274]: server is likely overloaded
Jul 19 19:29:08 node2 etcd[8274]: rejected connection from "192.168.195.129:59370" (error "tls: first record does not look like a TLS handsh...rName "")
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by fcddk** [comment]
I think it's related to starting the data. But after clearing it, there is still a problem after restarting.

[root@node1 ~]# etcdctl --endpoints=http://192.168.195.128:2379,192.168.195.129:2379,192.168.195.130:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint status
Failed to get the status of endpoint http://192.168.195.128:2379 (context deadline exceeded)
192.168.195.129:2379, b7c605eed4a1da21, 3.3.11, 20 kB, false, 109, 9
192.168.195.130:2379, 6f786ac7d981f803, 3.3.11, 20 kB, false, 109, 9
[root@node1 ~]# etcdctl --endpoints=http://192.168.195.128:2379,192.168.195.129:2379,192.168.195.130:2379 --cacert=/etc/etcd/ssl/ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem endpoint health
192.168.195.130:2379 is healthy: successfully committed proposal: took = 3.189286ms
192.168.195.129:2379 is healthy: successfully committed proposal: took = 3.954625ms
http://192.168.195.128:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster

what's wrong?

**Comment by zky001** [comment]
me 2
