### ISSUE TITLE
Set db size for ETCD after installation

### ISSUE THREAD

**Issue by jyothish-git** [etcd-io/etcd#10896]
Hi Team,

ETCD is deployed as a pod in our Kubernetes cluster and is running fine. I want to change the default storage limit from 2GB to 4GB. So added --quota-backend-bytes flag in the etcd yaml file. Etcd is now running with this change. But in the logs I'm not seeing anything regarding the quota limit. 
So I like to get a clarification on the following. Can anyone helps ?

1. Confirm that it is possible to set the db size for etcd after it is already started ?
2. Is there any way/commands to check the db size limit in etcd.

etcd version: 3.2

**Comment by jingyih** [comment]
I think it should work. You can verify the quota by checking 'etcd_server_quota_backend_bytes' in etcd's metrics.

**Comment by jyothish-git** [comment]
Thank you @jingyih for the clarification. I tested and it works.  

Just a note, the 'etcd_server_quota_backend_bytes' prometheus metric is available only from etcd version 3.2.24 and later.

**Comment by jingyih** [comment]
Thanks for confirming! Yes it was backedported to v3.1.19, v3.2.24, and v3.3.9.

Without this backport, quota information can only be confirmed via server configuration (command line flag or config file). In newer versions, quota information is printed in server log when zap logger is used '--logger=zap'.
