### ISSUE TITLE
Dara Race in TestV3WatchFromCurrentRevision

### ISSUE THREAD

**Issue by yuzeming** [etcd-io/etcd#10899]
Two loop variables are contained in an anonymous function closure.

The loop variables are here `i` and `tt`:
https://github.com/etcd-io/etcd/blob/9fba06ba3b832a6cb6d3342eb719132ad2da4fd6/integration/v3_watch_test.go#L206

Also they are used in a go closure here inside loop:
https://github.com/etcd-io/etcd/blob/9fba06ba3b832a6cb6d3342eb719132ad2da4fd6/integration/v3_watch_test.go#L247-L256
 
May I submit a PR to fix it?

**Comment by jingyih** [comment]
Thanks! Could you help fix it?
