### ISSUE TITLE
`--discovery-srv-name` in etcd is not working

### ISSUE THREAD

**Issue by piontec** [etcd-io/etcd#10916]
I'm trying to use DNS discovery with the ``discovery-srv-name`, but it's not working. Please check the following simple commands:

```bash
piontec@w530:/tmp/etcd-v3.3.13-linux-amd64 $ ./etcd --version                 
etcd Version: 3.3.13
Git SHA: 98d3084
Go Version: go1.10.8
Go OS/Arch: linux/amd64

piontec@w530:/tmp/etcd-v3.3.13-linux-amd64 $ ./etcd --discovery-srv-name="abc" --discovery-srv example.com
flag provided but not defined: -discovery-srv-name
usage: etcd [flags]
       start an etcd server

       etcd --version
       show the version of etcd

       etcd -h | --help
       show the help information about etcd

       etcd --config-file
       path to the server configuration file

       etcd gateway
       run the stateless pass-through etcd TCP connection forwarding proxy

       etcd grpc-proxy
       run the stateless etcd v3 gRPC L7 reverse proxy

```

Tested on 3.3.10 with the same result. Seems to be a bug.

**Comment by spzala** [comment]
@piontec thanks for reporting. I just did a quick test on the master code and it shows that the flag is valid and working.
```
$ ./bin/etcd --discovery-srv-name
flag needs an argument: -discovery-srv-name
Usage:

  etcd [flags]
    Start an etcd server.

  etcd --version
    Show the version of etcd.
......
......
```
It could be a bug in the previous releases as you reported and needs some investigation, but thought I will let you know this, and see if you can try GitHub master code. Thanks!

**Comment by piontec** [comment]
I see, but keep in mind that this option is visible in docs for the version (.13 for sure, .10 - AFAIR)

**Comment by derryos** [comment]
Is this going to be available in a future 3.3 version? (considering this was added as part of https://github.com/etcd-io/etcd/issues/10238 ) Understand its available on master....

**Comment by spzala** [comment]
@piontec thanks and @derryos thank you for the findings. Can you please check out the output of `etcd --help` and see if the `discovery-srv-name` is there? If the option was provided in the 3.3 then I agree this is something that should be fixed. In the changelog for 3.3 I don't see this flag. I only see it in the changelog for upcoming version 3.4 Thanks!

**Comment by derryos** [comment]
@spzala , can confirm the option is not there in e.g. 3.3.13:
```
docker run -it quay.io/coreos/etcd:v3.3.13 sh
/ # etcd -h | grep srv
usage: etcd [flags]
       start an etcd server

       etcd --version
       show the version of etcd

       etcd -h | --help
       show the help information about etcd

       etcd --config-file
       path to the server configuration file

       etcd gateway
       run the stateless pass-through etcd TCP connection forwarding proxy

       etcd grpc-proxy
       run the stateless etcd v3 gRPC L7 reverse proxy

	--discovery-srv ''
		dns srv domain used to bootstrap the cluster.
```

**Comment by spzala** [comment]
@derryos thanks for verifying it. I guess we can close the issue then @piontec ?

**Comment by piontec** [comment]
I don't really think so. This option is still described in the docs for 3.3 series, so there's still a bug - just in the docs, not in code.

**Comment by spzala** [comment]
@piontec thanks, yes I see, I think we should open this same issue on the doc repo https://github.com/etcd-io/website - can you please open an issue there (for both 3.3.13 and 3.3.12 I see the mention of flag) and close this one if that sounds good? Thanks!

**Comment by spzala** [comment]
@gyuho @jingyih does it sounds good to open issue in https://github.com/etcd-io/website for this? Thanks!

**Comment by spzala** [comment]
Here is a related commit on reverting the flag in 3.3.12 https://github.com/etcd-io/etcd/commit/6931dd84427df2d627c1d1763767cc29b5ee3da3  The 3.3.13 has the flag ref though - https://github.com/etcd-io/etcd/blob/v3.3.13/Documentation/op-guide/clustering.md  The etcd.io doc has the flag mentioned in both 3.3.12 and 3.3.13

**Comment by piontec** [comment]
Created issue for the docs webpage: https://github.com/etcd-io/website/issues/40. Closing this one.
