### ISSUE TITLE
communication : unable to open google groups etcd-dev mailing list

### ISSUE THREAD

**Issue by nilsocket** [etcd-io/etcd#10922]
Either remove this from https://groups.google.com/forum/?hl=en#!forum/etcd-dev

if it's request only, please update appropriately.

Thank you.

**Comment by spzala** [comment]
hello @nilsocket what's the issue here?

**Comment by nilsocket** [comment]
![Screenshot_2019-07-24 etcd-dev - Google Groups](https://user-images.githubusercontent.com/29815708/61806567-877bc700-ae55-11e9-9bca-b7fbd967a541.png)

**Comment by nilsocket** [comment]
@spzala I'm unable to open etcd-dev in google groups, I was able to open other groups like golang-nuts and raft-dev

sorry, to ping this here,please see this as well,(not related to this) https://github.com/etcd-io/etcd/issues/10855

Thank you.

**Comment by nilsocket** [comment]
@spzala I was able to open from other network, I'm not sure what the problem is, I'm closing this issue.

Thank you.
