### ISSUE TITLE
etcd fake client

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#10927]
etcd unit test： fake a client to test the funtion put get.
How to deal with it？  help ， help.

**Comment by spzala** [comment]
@fcddk similar my comment in other issue, that please provide details of the problem so that someone can help. Thanks!

**Comment by fcddk** [comment]
situation like this：
// Client is a wrapper around the etcd client
type Client struct {
client *clientv3.Client
}
I write the function to new a client: function newClient()  (*Client, error)

then  defined two functions to put or get value
func (c *Client)GetValue()
func(c *Client)PutValue()

now, I want to fake the Client to accomplish the unit testing.

**Comment by fcddk** [comment]
I want to fake the client to accomplish the unit testing, Instead of connecting the real etcd to create the real client.

**Comment by fcddk** [comment]
Is there any experience for me to learn?

**Comment by spzala** [comment]
@fcddk I am not sure but the code here might be helpful 
https://github.com/etcd-io/etcd/tree/master/pkg/mock 
https://github.com/etcd-io/etcd/blob/master/clientv3/ordering/kv_test.go

**Comment by fcddk** [comment]
thanks, this is what i want.
