### ISSUE TITLE
types: a potential double lock bug

### ISSUE THREAD

**Issue by lzhfromustc** [etcd-io/etcd#10925]
***Description***
In [pkg/types/set.go](https://github.com/etcd-io/etcd/blob/master/pkg/types/set.go), `(*tsafeSet).Equals()` and `(*tsafeSet).Sub()` can produce double lock bug.

Take `Equals()` as an example, if it is used as `s1.Equals(s1)`, then `s1.RLock()` will be invoked twice: _ts.Equals()->us.Equals()->other.Values()_  

This alone is OK, but if there is another goroutine invoking `s1.Add("something")`, and `s1.Lock()` in `Add()` tries to acquire the RWMutex between the two `s1.RLock()`, then both goroutines will be blocked.

***My Test to trigger this bug***
Here is a test file that can trigger this bug by calling Equals() and Add() concurrently. Please put this file in etcd/pkg/types, and run `go test set.go set_Equals_test.go`.
```Go
package types

import (
	"sync"
	"testing"
)

func TestThreadsafeEqualsSet(t *testing.T) {
	driveSetEqualsTests(t)
}


func driveSetEqualsTests(t *testing.T) {

	var wg sync.WaitGroup
	s1 := NewThreadsafeSet()
	wg.Add(2)
	go func(){
		for i := 1; i <= 1000; i++ { // On my computer, 1000 is far enough to trigger this bug
			s1.Equals(s1)
		}
		wg.Done()
	}()

	go func(){
		for i := 1; i <= 1000; i++ { // On my computer, 1000 is far enough to trigger this bug
			s1.Add("abc")
		}
		wg.Done()
	}()

	wg.Wait()

}
```

***Suggestion of patch***
```Go
func (ts *tsafeSet) Equals(other Set) bool {
	ts.m.RLock()
	defer ts.m.RUnlock()
+++	if _other,ok := other.(*tsafeSet);ok { //if ts and other are pointing the same value, return true to avoid double lock
+++		if _other == ts {
+++			return true
+++		}
+++	}
	return ts.us.Equals(other)
}

func (ts *tsafeSet) Sub(other Set) Set {
	ts.m.RLock()
	defer ts.m.RUnlock()
+++	if _other,ok := other.(*tsafeSet);ok { //if ts and other are pointing the same value, return true to avoid double lock
+++		if _other == ts {
+++			usResult := NewUnsafeSet()
+++			return  &tsafeSet{usResult, sync.RWMutex{}}
+++		}
+++	}
	usResult := ts.us.Sub(other).(*unsafeSet)
	return &tsafeSet{usResult, sync.RWMutex{}}
}
```

**Comment by gyuho** [comment]
@jingyih @wenjiaswe  Could you help review

- https://github.com/etcd-io/etcd/pull/10955
- https://github.com/etcd-io/etcd/pull/10975
- https://github.com/etcd-io/etcd/pull/10976

**Comment by jingyih** [comment]
Sure I will take a look.

**Comment by jingyih** [comment]
Closing via #10955.
