### ISSUE TITLE
Documentation : dead link in https://etcd.io/docs/v3.3.12/integrations/

### ISSUE THREAD

**Issue by nilsocket** [etcd-io/etcd#10921]
https://etcd.io/docs/v3.3.12/integrations

deadlink : https://etcd.io/docs/v3.3.12/raft/README.md#notable-users

**Comment by spzala** [comment]
@nilsocket this issue should be opened in the https://github.com/etcd-io/website If you want me to open it there please let me know. I am closing it here. Thanks!

**Comment by nilsocket** [comment]
@spzala  I have opened it there, thank you, for mentioning.

**Comment by spzala** [comment]
@nilsocket cool, you are welcome.
