### ISSUE TITLE
rpc error: code = DeadlineExceeded

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#10931]
_, err := c.Client.Put(ctx, key, strValue)
	if err != nil {
		log.Error("put value error: %s", err)
		return err
	}
{"level":"error","msg":"put value error: rpc error: code = DeadlineExceeded desc = context deadline exceeded","time":"2019-07-25T18:17:24+08:00"}

why？ help, help

**Comment by xiang90** [comment]
how is ctx created?

**Comment by fcddk** [comment]
The problem has been solved， but i still have questions. Why use the etcd native interface without error?  I just encapsulated the client, also using the timeout function.
context.timeout().
// Client is a wrapper around the etcd client
type Client struct {
	client *clientv3.Client
}
/put value to etcd's storage
func (c *Client) PutValue()

**Comment by fcddk** [comment]
The details of the specific death are not very clear now

**Comment by xiang90** [comment]
i do not quite understand your follow up question. and probably you can create a new issue for the new question with more specific information for better discoverability.
