### ISSUE TITLE
Intermittent Error: context deadline exceeded

### ISSUE THREAD

**Issue by shanmugara** [etcd-io/etcd#10942]
I m running 3.3.11 3 node cluster in Centos.

{"etcdserver":"3.3.11","etcdcluster":"3.3.0"}

The server cert has all SANs and IPs:

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            19:00:00:00:51:f3:18:af:80:95:e3:60:e4:00:00:00:00:00:51
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: DC=net, DC=mydomain, CN=mydomain-OMEGADH01-CA
        Validity
            Not Before: Jul 25 22:06:46 2019 GMT
            Not After : Jul 24 22:06:46 2021 GMT
        Subject: C=US, ST=New York, L=New York, O=mydomain, OU=TI, CN=omegaetcd01.mydomain.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b9:05:4a:df:16:85:76:5e:0c:08:c8:99:8a:2a:
                    38:9e:7f:1f:b3:8d:a7:c8:5e:f4:52:18:6b:da:64:
                    d1:a6:ab:39:0c:d2:66:4e:9c:e8:fb:7b:e6:b9:37:
                    24:d9:34:ef:f6:b6:e8:20:57:c6:bd:9f:cf:97:93:
                    ee:16:fd:f8:2b:37:b8:35:05:86:60:44:fa:fa:b7:
                    f1:cb:86:da:c0:2f:6e:f4:57:1a:66:d9:da:4b:9e:
                    38:00:b2:6b:a1:3d:ed:65:ea:3c:00:ef:d7:1f:53:
                    19:42:93:95:5f:7e:b6:85:dc:b1:ad:ed:0a:13:1c:
                    c9:c8:e0:66:95:2b:e0:5a:58:31:33:02:76:54:98:
                    bf:54:2d:0f:6c:d2:cc:da:f3:85:6d:7d:cf:1a:a2:
                    4e:5b:58:15:c5:10:6a:0a:46:26:ff:57:eb:93:00:
                    10:e7:01:63:e2:99:e0:f3:c4:39:b6:b6:73:f9:15:
                    6e:38:b1:b4:e5:9e:13:48:5f:63:d3:af:58:c4:68:
                    e9:47:b4:b3:01:dc:e2:71:58:e3:09:4f:0e:f5:90:
                    2a:c9:97:f9:2e:d9:d2:52:df:ce:b6:a5:04:59:92:
                    f5:0d:27:d8:6c:5f:c3:c9:66:7c:78:41:a7:04:72:
                    a4:70:51:04:ad:b1:f6:8d:05:91:c0:e5:12:2e:c1:
                    ac:59
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:omegaetcd01.mydomain.net, DNS:omegaetcd02.mydomain.net, DNS:omegaetcd03.mydomain.net, DNS:omegaetcd01, DNS:omegaetcd02, DNS:omegaetcd03, DNS:etcd.mydomain.net, DNS:localhost, IP Address:192.168.0.22, IP Address:192.168.0.23, IP Address:192.168.0.24, IP Address:127.0.0.1
            X509v3 Subject Key Identifier: 
                0F:D4:DE:E0:37:92:56:C2:33:28:4A:D5:FF:41:7D:EB:B0:BB:F8:F7
            X509v3 Authority Key Identifier: 
                keyid:BF:9C:0C:76:EF:DD:21:2D:E8:7E:69:D0:03:75:9B:44:0F:F7:CA:EC

            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://omegadh01.mydomain.net/CertEnroll/mydomain-OMEGADH01-CA.crl

            Authority Information Access: 
                CA Issuers - URI:ldap:///CN=mydomain-OMEGADH01-CA,CN=AIA,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=mydomain,DC=net?cACertificate?base?objectClass=certificationAuthority

            1.3.6.1.4.1.311.21.7: 
                0-.%+.....7.....M...$..9...[...~h...P...`..d...
            1.3.6.1.4.1.311.21.10: 
                0.0
..+.......0
..+.......
    Signature Algorithm: sha256WithRSAEncryption

The cert req was generated with openssl

openssl genrsa -out mikey.pem 2048
openssl req -new -sha256 ..... -out myreq.csr

The cert request was signed and issued by Microsoft ADCS.

my /etc/etcd/etcd.conf is:
ETCD_DATA_DIR="/var/lib/etcd/omegaetcd01.etcd"
ETCD_LISTEN_PEER_URLS="https://192.168.0.22:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.0.22:2379,http://127.0.0.1:4001"
ETCD_NAME="omegaetcd01"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.0.22:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.0.22:2379"
ETCD_INITIAL_CLUSTER="omegaetcd01=https://192.168.0.22:2380,omegaetcd02=https://192.168.0.23:2380,omegaetcd03=https://192.168.0.24:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
ETCD_INITIAL_CLUSTER_STATE="existing"
ETCD_ENABLE_V2="false"
ETCD_CERT_FILE="/etc/pki/tls/certs/omegaetcd01.mydomain.net.crt"
ETCD_KEY_FILE="/etc/pki/tls/private/omegaetcd01.mydomain.net.key"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_TRUSTED_CA_FILE="/etc/pki/ca-trust/source/anchors/omegadh01-ca.crt"
ETCD_PEER_CERT_FILE="/etc/pki/tls/certs/omegaetcd01.mydomain.net.crt"
ETCD_PEER_KEY_FILE="/etc/pki/tls/private/omegaetcd01.mydomain.net.key"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="/etc/pki/ca-trust/source/anchors/omegadh01-ca.crt"
ETCD_DEBUG="true"

With this config, all 3 nodes are reporting healthy.
When I try to any etcdctl command, intermittently I get "Error: context deadline exceeded"

[root@omegaetcd01 certs]# /opt/etcd/etcdctl --cert=omegaetcd01.mydomain.net.crt --key=omegaetcd01.mydomain.net.key --endpoints=https://omegaetcd01:2379 get /countries/usa
Error: context deadline exceeded

[root@omegaetcd01 certs]# /opt/etcd/etcdctl --cert=omegaetcd01.mydomain.net.crt --key=omegaetcd01.mydomain.net.key --endpoints=https://omegaetcd01:2379 get /countries/usa
/countries/usa
newyork

If I don't run any etcdctl for a few mins, the very next request will throw this error, then the subsequent requests are fine, until I stop a while. I am using only v3.

I had the same issue with 3.3.9 as well. My systems are KVM VMs. No resource issues. I was able to reproduce this behavior in a different setup with physical machines too.
The issue seems more reproducible when auth is enabled.
What am I missing, please help.

**Comment by mckenziec** [comment]
Well I get "Error: context deadline exceeded" in a case where my system clock between VMs skewed when running some automated testing.

If this is a bug, it might be related to certificate before/after validation checks.

**Comment by gtato** [comment]
I am having the same issue. I have a routine querying periodically etcd and, while most of the time it works, every once in a while I get this error. I am not sure how to reproduce it cause it is quite rare (once per 20 minutes or once per hour)
