### ISSUE TITLE
metrics: promote etcd_debugging put_total and delete_total

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#10950]
Certain applications such as the Kubernetes apiserver uses txn[1] for Puts which results in a hole for `grpc_*` metrics calculations. `etcd_debugging_mvcc_put_total` accurately reflects these metrics for the cluster. Because the `etcd_debugging_*`[2] namespace metrics have been marked as experimental adoption of these metrics has been stunted. I propose promoting the following. We will maintain backward compatibility with old namespace in 3.4 and plan to depreciate in 3.5

`etcd_debugging_mvcc_put_total` -> `etcd_mvcc_put_total` 

`etcd_debugging_mvcc_delete_total` -> `etcd_mvcc_delete_total` 

/cc @gyuho @jpbetz @xiang90 @jingyih 

[1] https://github.com/kubernetes/kubernetes/blob/release-1.14/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L159
[2] https://github.com/etcd-io/etcd/blob/master/Documentation/metrics.md#etcd_debugging-namespace-metrics

**Comment by gyuho** [comment]
Sounds good. Can you create a PR with CHANGELOG?

**Comment by jingyih** [comment]
Do we also want to promote `etcd_debugging_mvcc_txn_total` and `etcd_debugging_mvcc_get_total`?

**Comment by jingyih** [comment]
Actually I need some clarification on this. If, for example, client issue a TXN which includes a GET and DEL such as in [1]. After it is applied, all of the following 3 metrics will increase by 1, correct? Just want to make sure these metrics do not confuse users.

`etcd_debugging_mvcc_txn_total`, `etcd_debugging_mvcc_get_total`, `etcd_debugging_mvcc_del_total`

[1] https://github.com/kubernetes/kubernetes/blob/df8cd112a7369f7904682074588a4687cabc2846/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L194
