### ISSUE TITLE
pkg/adt violates red-black tree black-height property

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#10965]
*Introduction to Algorithms by Charles E. Leiserson, Clifford Stein, Ronald Rivest, and Thomas H. Cormen*: 

> 13.1 Properties of red-black trees
>
> 5. For each node, all simple paths from the node to descendant leaves contain the
same number of black nodes.

Current delete operation violates "black-height" property.

<br>

For example, given this red-black tree:

![red-black-tree-02-delete-514](https://user-images.githubusercontent.com/6799218/62170109-1c137880-b2df-11e9-947d-a78a554807b0.png)

Let's delete the node `11`.

The tree should be rebalanced as below:

```
After deleting 11 (requires rebalancing):

                        [510,511]
                        /      \
                --------        ----------------------------
               /                                            \
           [383,384]                                     [830,831]
           /       \                                    /          \
          /         \                                  /            \
[261,262](red)     [410,411]                  [647,648]           [899,900](red)
        /               \                           \                     /    \
       /                 \                           \                   /      \
    [82,83]           [292,293]                [815,816](red)      [888,889]    [972,973]
        \                                                           /
         \                                                         /
        [238,239](red)                                       [953,954](red)
```

![red-black-tree-09-delete-11](https://user-images.githubusercontent.com/6799218/62169761-02256600-b2de-11e9-8c61-1a13139a4a40.png)

However, current implementation returns:

```
After deleting 11 (requires rebalancing):

                       [510,511]
                        /      \
              ----------        --------------------------
             /                                            \
         [82,83]                                       [830,831]
               \                                      /          \
                \                                    /            \
             [383,384]                        [647,648]           [899,900]
             /       \                              \                 /    \
            /         \                              \               /      \
      [261,262]      [410,411]                      [815,816] [888,889]    [972,973]
        /   \                                                                /
       /     \                                                              /
[238,239]   [292,293]                                                [953,954]
```

This violates "black-height" property.

ref. https://github.com/etcd-io/etcd/issues/10877.

**Comment by gyuho** [comment]
PRs:
- https://github.com/etcd-io/etcd/pull/10959
- https://github.com/etcd-io/etcd/pull/10963
- https://github.com/etcd-io/etcd/pull/10964

**Comment by gyuho** [comment]
Basically we need fix

https://github.com/etcd-io/etcd/blob/3b631e1bb6316abc35e607cccbace3cc81c2765d/pkg/adt/interval_tree_test.go#L255-L303

**Comment by xkeyideal** [comment]
https://github.com/etcd-io/etcd/blob/master/pkg/adt/interval_tree.go#L298

delete node 514 and 11, will not exec the deleteFixUp function, because the node x is nil

I can pass all test cases with my codes.

**Comment by gyuho** [comment]
@xkeyideal I tried your patch. `TestIntervalTreeDelete` passes but not `TestIntervalTreeContains`. Can you try again in a new branch?

**Comment by xkeyideal** [comment]
@gyuho Please see the code https://github.com/xkeyideal/etcd/blob/master/pkg/adt/interval_tree.go

I change it based on your test cases, it can pass `TestIntervalTreeContains`

**Comment by gyuho** [comment]
@xkeyideal Could you create a new PR? Thanks.

**Comment by xkeyideal** [comment]
@gyuho OK， based on the newest master branch?

**Comment by xkeyideal** [comment]
@gyuho #10977

**Comment by gyuho** [comment]
@xkeyideal https://github.com/etcd-io/etcd/pull/10978

**Comment by gyuho** [comment]
Fixed via https://github.com/etcd-io/etcd/commit/003362ef8e0e16e34114bd499dee272a34f6c658.

Thanks @xkeyideal
