### ISSUE TITLE
using etcd on travis

### ISSUE THREAD

**Issue by benitogf** [etcd-io/etcd#10972]
I'm currently using:
```
before_script:
  - go get -v go.etcd.io/etcd
  - $GOPATH/bin/etcd &
```

but I'm getting an unrelased version:
```
2019-08-02 02:38:00.183526 I | etcdmain: etcd Version: 3.4.0-pre
```

and an error that was no happening before the pre-release:
```
{"level":"warn","ts":"2019-08-02T02:38:38.675Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-9906dba7-0ca1-444a-8a0b-72eacf4feeec/localhost:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: not capable"}
```

this one was closed: https://github.com/travis-ci/travis-ci/issues/5464

how would you recommend to install the service on travis so it will default to the latest release?

**Comment by gyuho** [comment]
Please try again with latest master.

It should work now.
