### ISSUE TITLE
Broken links to etcd.redhatdocs.io

### ISSUE THREAD

**Issue by retroflexer** [etcd-io/etcd#10989]
For instance, in the section of "Adding a new member as a learner" in the [Runtime Configuration page](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member) refers to a design doc with a link to https://etcd.readthedocs.io/en/latest/server-learner.html which is unreachable!

**Comment by spzala** [comment]
We should replace the broken link with 
https://github.com/etcd-io/etcd/blob/master/Documentation/learning/design-learner.md#raft-learner
or 
https://etcd.io/docs/v3.3.12/learning/learner/#raft-learner

@gyuho does that make sense? Thanks!

**Comment by gyuho** [comment]
Yeah we moved to etcd.io
