### ISSUE TITLE
concurrency.Campagin always success after leader of etcdserver fail

### ISSUE THREAD

**Issue by MaggieCui** [etcd-io/etcd#11007]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
I use clientV3.concurrency to do election for my service. but i find all Campaign can susccess after raft leader fail.

我是用clientV3.concurrency来做我们元数据服务器的leader选举。在etcd正常的时候leader可以正常选出，但在etcd集群leader挂掉，重新选举leader后另外两个备服务器都可以成为主

**Comment by MaggieCui** [comment]
@hexfusion

**Comment by xiang90** [comment]
@MaggieCui 

Can you write a test case or a simple script to show the problem?

**Comment by MaggieCui** [comment]
my election program:
`package main

import "C"
import (
	"context"
	"flag"
	"go.etcd.io/etcd/clientv3"
	"go.etcd.io/etcd/clientv3/concurrency"
	"log"
	"time"
)

var (
	leaderName = flag.String("leaderName", "", "leader name")
	leaderPrefix = flag.String("leaderPrefix", "WantNumberOne", "leaderPrefix")
	ttlSec = flag.Int("ttlSec", 2, "session interval")
	sleep = flag.Int("sleep", 10, "sleep time")
)


func main() {
	flag.Parse()

	var err error
	client, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"10.187.0.91:22380","10.187.0.91:22382","10.187.0.91:22384"},
		DialTimeout: time.Duration(2000) * time.Millisecond,
	})

	if err != nil {
		log.Printf("new client error：%v", err)
		return
	}

	// 创建带ttl的session
	var sessionOpts concurrency.SessionOption =
		concurrency.WithTTL(*ttlSec)
	session, err := concurrency.NewSession(client, sessionOpts)
	if err != nil {
		log.Printf("%v new session err: %v\n", *leaderName, err)
		return
	}

	// 创建election和超时context
	var election *concurrency.Election = concurrency.NewElection(session, *leaderPrefix)
	var ctx context.Context
	ctx = context.Background()

	// 获取当前leader并打印
	if leader, err := election.Leader(ctx); err == nil {
		log.Printf("current leader is: %v\n", string(leader.Kvs[0].Value))
	} else {
		log.Printf("get current leader err: %v\n", err)
	}

	// 如果contex是'context.TODO()/context.Background()', 竞选会阻塞到该key被删除,
	// 除非返回non-recoverable error(例如: ErrCompacted).
	// 如果context有超时, 在超时或者取消之前, 竞选会阻塞到当选leader
	log.Printf("%v campagin for leader begin\n", *leaderName)
	if err := election.Campaign(ctx, *leaderName); err != nil {
		log.Printf("%v campaign err: %v\n", *leaderName, err)
		return
	} else {
		log.Printf("%v campaign for leader success\n", leaderName)
	}

	time.Sleep(time.Duration(*sleep) * time.Second)`

**Comment by MaggieCui** [comment]
> @MaggieCui
> 
> Can you write a test case or a simple script to show the problem?

my election program:

> package main

import "C"
import (
	"context"
	"flag"
	"go.etcd.io/etcd/clientv3"
	"go.etcd.io/etcd/clientv3/concurrency"
	"log"
	"time"
)

var (
	leaderName = flag.String("leaderName", "", "leader name")
	leaderPrefix = flag.String("leaderPrefix", "WantNumberOne", "leaderPrefix")
	ttlSec = flag.Int("ttlSec", 2, "session interval")
	sleep = flag.Int("sleep", 10, "sleep time")
)


func main() {
	flag.Parse()

	var err error
	client, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"10.187.0.91:22380","10.187.0.91:22382","10.187.0.91:22384"},
		DialTimeout: time.Duration(2000) * time.Millisecond,
	})

	if err != nil {
		log.Printf("new client error：%v", err)
		return
	}

	// 创建带ttl的session
	var sessionOpts concurrency.SessionOption =
		concurrency.WithTTL(*ttlSec)
	session, err := concurrency.NewSession(client, sessionOpts)
	if err != nil {
		log.Printf("%v new session err: %v\n", *leaderName, err)
		return
	}

	// 创建election和超时context
	var election *concurrency.Election = concurrency.NewElection(session, *leaderPrefix)
	var ctx context.Context
	ctx = context.Background()

	// 获取当前leader并打印
	if leader, err := election.Leader(ctx); err == nil {
		log.Printf("current leader is: %v\n", string(leader.Kvs[0].Value))
	} else {
		log.Printf("get current leader err: %v\n", err)
	}

	// 如果contex是'context.TODO()/context.Background()', 竞选会阻塞到该key被删除,
	// 除非返回non-recoverable error(例如: ErrCompacted).
	// 如果context有超时, 在超时或者取消之前, 竞选会阻塞到当选leader
	log.Printf("%v campagin for leader begin\n", *leaderName)
	if err := election.Campaign(ctx, *leaderName); err != nil {
		log.Printf("%v campaign err: %v\n", *leaderName, err)
		return
	} else {
		log.Printf("%v campaign for leader success\n", leaderName)
	}

	time.Sleep(time.Duration(*sleep) * time.Second)

**Comment by MaggieCui** [comment]
> @MaggieCui
> 
> Can you write a test case or a simple script to show the problem?

my election program:
![image](https://user-images.githubusercontent.com/15689619/63150929-b80ce600-c03a-11e9-9710-030028e535c8.png)

**Comment by MaggieCui** [comment]
question is：
I can not confirm the return result nil from Campaign is because of write the smallest revision of the key with prefix or because of wait for the key delete
