### ISSUE TITLE
go mod import package problem

### ISSUE THREAD

**Issue by zjmnssy** [etcd-io/etcd#11008]
when i use go.etcd.io/etcd v3.3.13，on go1.12, open go mod, build will error

![ddd3b30627c94d367241a241e513ac3](https://user-images.githubusercontent.com/21244667/62682295-6cc95680-b9ee-11e9-8546-b52710be2642.png)

this is my go.mod file
![24b24deea9d7084c04a4f1cab2105aa](https://user-images.githubusercontent.com/21244667/62682338-8bc7e880-b9ee-11e9-8df1-ff53e8f5fb41.png)

i use 'go mod why github.com/coreos/etcd' cmd, it show:
![1418618281f8126b56a6bef4842c971](https://user-images.githubusercontent.com/21244667/62682415-b154f200-b9ee-11e9-829d-0a6ea14ad04c.png)
 it look like go.etcd.io/etcd has some import package error in go mod, could someone help, thx

**Comment by hexfusion** [comment]
release-3.3 uses the old org `github.com/coreos`  please import using that org and this issue will resolve. When 3.4 is cut we will move to the new org `go.etcd.io/etcd`

**Comment by zjmnssy** [comment]
@hexfusion ok, i'll try to use 'github.com/coreos' package when import etcd, thank you!

**Comment by ldelossa** [comment]
@hexfusion is this now resolved?

**Comment by hexfusion** [comment]
> @hexfusion is this now resolved?

It would depend on which etcd version you are trying to import.

release-3.3 and before use `github.com/coreos/etcd` IE v3.2.26, v3.3.15
release-3.4 on use vanity url `go.etcd.io/etcd`

Are you seeing a problem?

**Comment by ldelossa** [comment]
@hexfusion 

Was seeing an issue with conflicts pretty hard when using 3.3 - go mod was getting confused and importing `github.com/coreos` `github.com/etcd-io` and `go.etcd.io/etcd`. 

Now that 3.4 is out however I nuked all three of those repos, changed all my import paths to `go.etcd.io` and imported @3.4 - worked like a charm. 

I have no issues with using 3.4 but others may find some problems with the mulitple repo names conflicting when using < 3.4

**Comment by hexfusion** [comment]
Generally, the issue comes when etcd is not explicitly set in go.mod. If you have examples of failure feel free to open a new issue so we can take a closer look.
