### ISSUE TITLE
Feature request: a Watch that returns only keys, not values

### ISSUE THREAD

**Issue by gjcarneiro** [etcd-io/etcd#11019]
Looking at the [RPC](https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L664-L716), there does not seem to exist any way to request watch that returns only the keys, and not the values.

The reason is that I want to watch a prefix, don't care about the values, and will be wasting bandwidth having every value echoed back to me.

**Comment by jewertow** [comment]
I will take care of it.

**Comment by xiang90** [comment]
thanks @jewertow

**Comment by jewertow** [comment]
I still work on this.

**Comment by jewertow** [comment]
@gjcarneiro @xiang90 
I have been very busy recently, but I came back to this issue and want to implement it.
Please give me a feedback on API. There is no implementation yet. I need information if it will be useful.

**Comment by gjcarneiro** [comment]
I would add a new option, something like `bool keys_only`, to WatchCreateRequest.  When this is set to true, the server should only return keys in watch events, with value null.
