### ISSUE TITLE
how to get reversion history list of a key

### ISSUE THREAD

**Issue by FengXingYuXin** [etcd-io/etcd#11027]
firstly this feature is needed in many situations, in docs https://etcd.io/docs/v3.3.12/dev-guide/interacting_v3/ be mentioned, but set --prefix not only a key.
if there are 20w keys in a prefix, and I want to get the latest two or three reversions' value of a key, how can make it？

**Comment by FengXingYuXin** [comment]
etcd has provided api(get key --rev=xxx), but if I cannot know the key's reversion history list, the api(get key --rev=xxx) will not make effects.

**Comment by xqzhang2015** [comment]
I also encounter the same awkward situation...

**Comment by xqzhang2015** [comment]
@xiang90 or @mitake 

Do we have any plan to support such an API to get key revisions by mvcc? BTW, is there any special reason about why there is no such API for now?

Thanks

**Comment by jingyih** [comment]
The API is correctly implemented. Please refer to documentation in [1] regarding how to retrieve past version of keys. Each mutating client request increases store `revision` by 1. Think of store `revision` as the "global time" of the etcd cluster. In the response header, there is a field `revision`, which is set to the store `revision` when the corresponding request was applied to the store [2].

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/interacting_v3.md#read-past-version-of-keys

[2] https://github.com/etcd-io/etcd/blob/8037e6e08727d4a17649f782cb4dbc482b8fe780/etcdserver/etcdserverpb/rpc.proto#L381

**Comment by xqzhang2015** [comment]
@jingyih thanks so much for your attention.

But the precondition for getting historical value is that we know the revisions.

If there are only a few keys, that's fine.
If there are a lot of keys, how could we know the historical revisions for a specific key?

**Comment by jingyih** [comment]
It is important to distinguish two concepts, store `revision` vs. key `version`. store `revision` is the global clock where you can get from a response header, as described above. You can also specify `--rev` in a range request to travel back in time, i.e., to get the store view at a given revision. There is no API to retrieve a key at a given `version`.

**Comment by xqzhang2015** [comment]
So for now, if we hope to get the historical values for a specific key, the only way is to iterate revisions among [create_revision, mod_revision], right?

**Comment by jingyih** [comment]
> So for now, if we hope to get the historical values for a specific key, the only way is to iterate revisions among [create_revision, mod_revision], right?

For this purpose, you might want to use watch API. Specify an old enough revision in watch request, all historical values will be returned. Unless the old values are already compacted (garbage collected).

**Comment by xqzhang2015** [comment]
Watch is a fine approach for now. Thanks so much, @jingyih.

**Comment by FengXingYuXin** [comment]
watch api maybe is a method for this situation, but i don't think it's appropriate for the situation, and if there are history reversions of a key, api(get key --rev=xxx) may make more effects; if not, what's the meaning of api(get key --rev=xxx)?

**Comment by jingyih** [comment]
> watch api maybe is a method for this situation, but i don't think it's appropriate for the situation, and if there are history reversions of a key, api(get key --rev=xxx) may make more effects; if not, what's the meaning of api(get key --rev=xxx)?

This is already answered in https://github.com/etcd-io/etcd/issues/11027#issuecomment-523679482.

**Comment by FengXingYuXin** [comment]
ok, thanks for your replay
