### ISSUE TITLE
Watch gets no notification when key is expired with lease

### ISSUE THREAD

**Issue by gjcarneiro** [etcd-io/etcd#11020]
etcd (3.3.11)

1. Create a lease
2. Put a key, with associated lease
3. Create a Watch on the key
4. Allow the lease to expire -> the key gets deleted
5. The Watch does not receive a DELETE event for that key, so how do I even notice the key got removed?

**Comment by xiang90** [comment]
can you create a script/test case to reproduce it?

**Comment by gjcarneiro** [comment]
Ah, never mind, solved it.  It turns out that it works, but I had to wait a few more seconds for the event.  Cheers.

**Comment by MaggieCui** [comment]
I also has the question:
watch wait a long time to return delete event where etcd leader failover, election-timeout is set 5s
