### ISSUE TITLE
Functional tests SIGQUIT* and SIGTERM* fails(both release3.4 and 3.4.0-rc.0)

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#11022]
The SIGQUIT* and SIGTERM* tests are failing because of the following error:

```
{"level":"warn","ts":1565798738.7095478,"caller":"tester/cluster_run.go:50","msg":"round FAIL","round":0,"case":0,"case-total":1,"error":"recovery error: rpc error: code = Unknown desc = open /tmp/etcd-tester-data/s1/fixtures/client/cert.pem: no such file or directory"}
```

However, I did see in cluster log that all client certs and keys were saved:

```
{"level":"info","ts":1565798704.810509,"caller":"tester/cluster.go:528","msg":"saved client cert file","path":"/tmp/etcd-tester-data/s1/fixtures/client/cert.pem"}
{"level":"info","ts":1565798704.8106043,"caller":"tester/cluster.go:528","msg":"saved client cert file","path":"/tmp/etcd-tester-data/s2/fixtures/client/cert.pem"}
{"level":"info","ts":1565798704.8106625,"caller":"tester/cluster.go:542","msg":"saved client key file","path":"/tmp/etcd-tester-data/s1/fixtures/client/key.pem"}
{"level":"info","ts":1565798704.8108287,"caller":"tester/cluster.go:542","msg":"saved client key file","path":"/tmp/etcd-tester-data/s2/fixtures/client/key.pem"}
{"level":"info","ts":1565798704.8109217,"caller":"tester/cluster.go:528","msg":"saved client cert file","path":"/tmp/etcd-tester-data/s3/fixtures/client/cert.pem"}
{"level":"info","ts":1565798704.811089,"caller":"tester/cluster.go:542","msg":"saved client key file","path":"/tmp/etcd-tester-data/s3/fixtures/client/key.pem"}
```

**Comment by gyuho** [comment]
It's been flaky, but I believe this has been fixed after we relaxed the error count requirements and lower the stress QPS. Can you get the server logs?

**Comment by wenjiaswe** [comment]
It looks like when handle_RECOVER_ETCD called saveTLSAssets and tried to write ClientCertData to ClientCertPath, it couldn't get the data so logged the error above, even though the data were saved at the initial etcd step already.

**Comment by wenjiaswe** [comment]
The functional tests all pass when [run locally](https://github.com/etcd-io/etcd/tree/master/functional#run-locally) but failed when [running with docker](https://github.com/etcd-io/etcd/tree/master/functional#run-with-docker). The reason is that tester saved the certs and keys on tester's docker https://github.com/etcd-io/etcd/blob/8f85f0dc2607fcfb3ec8d812ecf52eb391fb2f74/functional/tester/cluster.go#L505, but agents are trying to get the certs and keys from their docker, and of course it's not there: https://github.com/etcd-io/etcd/blob/8f85f0dc2607fcfb3ec8d812ecf52eb391fb2f74/functional/agent/handler.go#L360.

The test needs to be fixed by pulling file from tester docker when ran with docker.

/assign

**Comment by gyuho** [comment]
Hmm, good find. We never caught this because CI runs without docker

https://github.com/etcd-io/etcd/blob/56f483ae44b67239919476715376ee3723847eb0/test#L199-L242
