### ISSUE TITLE
lease ttl Operations option problem

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#11026]
// WithLease attaches a lease ID to a key in 'Put' request.
func WithLease(leaseID LeaseID) OpOption {
	return func(op *Op) { op.leaseID = leaseID }
}

A client wants to lease a key, must participate in the put operation, generate its own generation?

**Comment by xiang90** [comment]
Can you elaborate your question? What is the generation you refer to?

**Comment by fcddk** [comment]
I want to ask that leaseID establishes association with KEY，which Can only be achieved by the PUT method?

**Comment by fcddk** [comment]
// WithLease attaches a lease ID to a key in 'Put' request.
func WithLease(leaseID LeaseID) OpOption {
return func(op *Op) { op.leaseID = leaseID }
}

**Comment by fcddk** [comment]
I want to implement a program that reports survival status.   And  i find that the key will not be deleted when the lease ttl expired.
I want to create the lease by renting the key that already exists. only get it, but bot put it
eg:
Resp, err := c.Get(ctx, key, clientv3.WithLease(leaseResp.ID))

**Comment by fcddk** [comment]
I have solved this problem.
Method: 
Establish a lease
Build a timer to keep the lease
Save a leaseID

**Comment by fcddk** [comment]
lease := clientv3.NewLease(c.Client)
	leaseResp, err := lease.Grant(ctx, ttl)
	if err != nil {
		log.Error("PutUpdaterInfo 设置租约时间失败 err: %s", err)
		return 0, err
	}

	leaseID := leaseResp.ID
	_, err = c.Client.Put(ctx, key, result, clientv3.WithLease(leaseID))
	if err != nil {
		log.Error("put value error: %s", err)
		return 0, err
	}

	ttlGetResp, err := lease.TimeToLive(ctx, id)

**Comment by xiang90** [comment]
Glad that you figured it out. So I am closing this issue.
