### ISSUE TITLE
raft: group gets stuck when leader is removed

### ISSUE THREAD

**Issue by tbg** [etcd-io/etcd#11038]
See the "document a problem" commit in https://github.com/etcd-io/etcd/pull/11037.

When a leader is removed via a conf change, it will retain its leadership indefinitely (continues to heartbeat followers). However, it does not accept incoming proposals.

**Comment by xiang90** [comment]
The expected behavior is what? The removed leader should stop heartbeating and keep silence?

**Comment by tbg** [comment]
At the very least, the leader should immediately step down when it applies the configuration change. But I think even more so, we probably want to send an MsgTimeoutNow to one follower that has helped commit the config change, which in the very common case would minimize the disruption.

**Comment by xiang90** [comment]
@tbg 

> send an MsgTimeoutNow to one follower that has helped commit the config change (i.e. the one with the largest Match), which in the very common case would minimize the disruption.

For etcd, we did this in the application layer I believe.

**Comment by jingyih** [comment]
Yes, this is handle in application layer. When leader is removed, during its stop process, it will transfer leadership to the longest connected voting member in cluster.

Ref:
https://github.com/etcd-io/etcd/blob/9b29151d3072511f574e7272a5348504086013fa/etcdserver/server.go#L1502-L1503
