### ISSUE TITLE
What is the reason for etcd's 8GB limit on storage?

### ISSUE THREAD

**Issue by arjunsingri** [etcd-io/etcd#11048]
As mentioned here, is the storage size limit of 8GB a hard limit? I tried setting it to more than 8GB but the cluster was not operational after that.

https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/limit.md

etcdctl version: 3.3.13

**Comment by spzala** [comment]
@arjunsingri I hope the discussion here should help you understand it better, https://github.com/etcd-io/etcd/issues/9771
