### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [etcd-io/etcd#11043]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Also, we have a [reward](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) program. If you are interested in implementing the fuzzers and the integration yourself I’ll be happy to reward you as well as to get unbiased feedback on how smooth the integration was.

Cheers,
Yevgeny

**Comment by spzala** [comment]
@yevgenypats thanks for the suggestion. etcd team is busy with upcoming 3.4 release work but meanwhile other team members take a look at this issue and chime in, just curios that is there any CNCF projects using Fuzzit? It seems like some efforts are going to make fuzzing a first class citizen in golang itself. Thanks!

**Comment by yevgenypats** [comment]
@spzala sure no rush. We have [prometheus](https://github.com/prometheus/prometheus/pull/5890) under review and [envoy](https://github.com/prometheus/prometheus/pull/5890) in progress

**Comment by yevgenypats** [comment]
@spzala coredns currently use fuzzit (already merged into master and found some bugs:))

https://github.com/coredns/coredns

**Comment by spzala** [comment]
Thanks @yevgenypats !!

**Comment by yevgenypats** [comment]
Sure!

**Comment by yevgenypats** [comment]
@spzala friendly ping:) would love to know what the status on that.
