### ISSUE TITLE
not foud document for client request restful api

### ISSUE THREAD

**Issue by songlong** [etcd-io/etcd#11050]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

**Comment by spzala** [comment]
@songlong are these documents you were looking for?
https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-kv-etcdserveretcdserverpbrpcproto
https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md
v2 - https://github.com/etcd-io/etcd/blob/master/Documentation/v2/api.md
If not, please feel free to reopen issue with more details. Thanks!
