### ISSUE TITLE
watch wait long time to return result after leader fail

### ISSUE THREAD

**Issue by MaggieCui** [etcd-io/etcd#11058]
the scene as follows:

1. new clientv3: dailtimeout-5s, other is default
2. create key-value with ttl-2s
3. watch key-value
4. kill leader etcd, election-timeout was set 5s
5. 14s after etcd new leader election success watch receive key-value event

my question is:
why watch need 20s+ to know key-value is deleted?

**Comment by sunny821** [comment]
+1

**Comment by xiang90** [comment]
a leader election will partially refresh the TTL on keys (the ttl will be checked pointed though). the only guarantee on TTL is to expire longer than the given TTL eventually. no strong time limit.
