### ISSUE TITLE
On a bug in go.etcd.io/etcd/client v3/concurrency/key.go

### ISSUE THREAD

**Issue by DriftingDw** [etcd-io/etcd#11052]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
When I used the example test in go.etcd.io/etcd/client v3/concurrency, I found that a place in key.go would be blocked all the time, and the waitDeletes function would watch its own deletion events. Here are my modifications. 

![image](https://user-images.githubusercontent.com/32216245/63268220-421caf00-c2c6-11e9-9f7d-3524e170982d.png)

My English is poor. I'm sorry.

**Comment by spzala** [comment]
@DriftingDw no problem at all, but it will be good and ideal if you can provide more details of the problem in the issue and then create a PR as you would suggest to modify. That will be easier for review. Thanks!

**Comment by DriftingDw** [comment]
I did the following tests:
1 Print resp in the waitDeletes function of key.go
2 Print myKey in the Lock function of mutex.go
3 Modify the ExampleMutex_Lock function of example_mutex_test.go as follows, delaying 3 seconds before m1.Unlock executes
![image](https://user-images.githubusercontent.com/32216245/63419676-cb9fbe80-c437-11e9-9067-ab25dfd774a8.png)
![image](https://user-images.githubusercontent.com/32216245/63419810-086bb580-c438-11e9-88d1-8b00e4476601.png)
![image](https://user-images.githubusercontent.com/32216245/63419850-191c2b80-c438-11e9-94aa-d9b931d38df0.png)
The output of the run test is as follows:
![image](https://user-images.githubusercontent.com/32216245/63419607-b460d100-c437-11e9-82cd-0a9b4e163326.png)
When m1 releases the lock, m2 will never get the lock. m2.Lock will always block the waitDelete function of key.go, because it monitors its own deletion events, but it will never happen when the program is running properly.
