### ISSUE TITLE
clinetv3/concurrent/leader_election Campaign return nil make confused

### ISSUE THREAD

**Issue by MaggieCui** [etcd-io/etcd#11051]
Hi~ I use clinetv3/concurrent/leader_election Campaign to implement application leader election, but I found this function return nil in following cases:
1. success campagin, application hold the smallest revision of prfix
2. wait prev key delete

In second case, if key of itself delete as well, it is still return nil,  but in this case, it should not become a leader

**Comment by XxYyKk** [comment]
`
func waitDeletes() {
        ....
		if len(resp.Kvs) == 0 {
			**return resp.Header, nil**
		}
       ....
	}
}
`

**Comment by MaggieCui** [comment]
> `func waitDeletes() { .... if len(resp.Kvs) == 0 { **return resp.Header, nil** } .... } }`

return nil, but does not mean campagin success
