### ISSUE TITLE
testing flaky:  FAIL: TestKVPutError

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#11067]
```
--- FAIL: TestKVPutError (0.26s)
    kv_test.go:56: expected etcdserver: request is too large, got etcdserver: mvcc: database space exceeded
```

**Comment by xiang90** [comment]
should be an easy fix.

**Comment by jingyih** [comment]
A lot of hard coded values. Not able to reproduce locally. Debugging in #11068.

**Comment by spzala** [comment]
> A lot of hard coded values. Not able to reproduce locally. Debugging in #11068.

Thanks @jingyih good idea. I couldn't produce it locally either, I guess it comes from here https://github.com/etcd-io/etcd/blob/master/etcdserver/v3_server.go#L596 Quick thought was, we might need a sleep time before the check? But could be wrong.

**Comment by jingyih** [comment]
@spzala I found some interesting context in #6486. Basically we need to ensure enough overhead in backend quota. Will send out a fix soon.

**Comment by spzala** [comment]
@jingyih oh wow :-), thanks for sharing it!!
