### ISSUE TITLE
auth jwt: is it better to implement something like auto-tls, for auth key?

### ISSUE THREAD

**Issue by xqzhang2015** [etcd-io/etcd#11063]
To use JTW auth, we need to pass key based on the sign method.

Is it possible to make it auto-generated by etcd according to sign method? It will decrease the operation complex significantly.

**Comment by xqzhang2015** [comment]
@mitake @xiang90 would you like to give any comment on this issue?

**Comment by mitake** [comment]
@xqzhang2015 Yeah I think it's good if we can have such a functionality (we need to be careful for security reasons though). If you have a concrete strategy on design and implementation, could you share?

**Comment by xqzhang2015** [comment]
@mitake thanks for your reply. Recently I'm too busy ...
I have no concrete strategy now. I would think about it.
