### ISSUE TITLE
watch auth: is it better to make CancelReason clear?

### ISSUE THREAD

**Issue by xqzhang2015** [etcd-io/etcd#11064]
For now, if sws.isWatchPermitted returns false, CancelReason is static(always rpctypes.ErrGRPCPermissionDenied), not considering the specific not-permit error. It leads to hard for the client to tell if retry or re-auth is worth to do.

For ErrUserEmpty, a client could re-auth if username and password are both non-empty.
For ErrAuthOldRevision, a client should always re-auth.
For ErrPermissionDenied, maybe it's user not found or it's really not permitted. In this case, re-auth is NOT worth too much.

https://github.com/etcd-io/etcd/blob/8037e6e08727d4a17649f782cb4dbc482b8fe780/etcdserver/api/v3rpc/watch.go#L251

is it better to make CancelReason clear?  Or do you have any better proposal?

**Comment by xqzhang2015** [comment]
@mitake @xiang90 would you like to give any comment on this issue?

**Comment by mitake** [comment]
@xqzhang2015 sorry for my late reply. I agree with your idea. It's nice to add additional error codes for making diagnosis easier. Can your work on the change? Or do you need help?

**Comment by xqzhang2015** [comment]
@mitake thanks the reply. I would like to think about it and may disturb you later.
