### ISSUE TITLE
first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by kestesskat** [etcd-io/etcd#11070]
kat>etcd --version
etcd Version: 3.3.11
Git SHA: 2cf9e51d2
Go Version: go1.10.7
Go OS/Arch: windows/amd64
using cmd shell for these examples

I've added a member to the cluster with the rest interface. Checking with etcdctl I find that it is there:
remote_cluster:/var/lib$ etcdctl -C "http://10.0.2.4:12379" member list
6efb51511da4f191[unstarted]: peerURLs=http://10.0.0.4:2380
745d33db725b1d0e: name=infra2 peerURLs=http://10.0.2.4:22380 clientURLs=http://10.0.2.4:22379 isLeader=false
d87aa8769df69aeb: name=infra3 peerURLs=http://10.0.2.4:32380 clientURLs=http://10.0.2.4:32379 isLeader=true
f6573d628e9b4a8c: name=infra1 peerURLs=http://10.0.2.4:12380 clientURLs=http://10.0.2.4:12379 isLeader=false

I try to run the new etcd server like this (after removing the data dir):
etcd --name g000000 --data-dir E:\MyStuff\bin\etcd\data --initial-advertise-peer-urls http://10.0.0.4:2380 --listen-peer-urls infra2=http://10.0.2.4:22380,infra3=http://10.0.2.4:32380,infra1=http://10.0.2.4:12380,g000000=http://10.0.2.4:2380 --listen-client-urls http://0.0.0.0:2379,http://127.0.0.1:2379 --advertise-client-urls http://10.0.0.4:2379 --initial-cluster-token etcd-cluster-1 --initial-cluster-state existing

And I'm rewarded with this:

invalid value "infra2=http://10.0.2.4:22380,infra3=http://10.0.2.4:32380,infra1=http://10.0.2.4:12380,g000000=http://10.0.2.4:2380" for flag -listen-peer-urls: parse infra2=http://10.0.2.4:22380: first path segment in URL cannot contain colon

I've tried many quoting variations in an attempt to make it work and also took off the "http//:" during extended scattershot debugging. Apparently I'm hitting a go issue parsing URLs - how is this supposed to work?

**Comment by jingyih** [comment]
Do not include name in `--listen-peer-urls`.

**Comment by jingyih** [comment]
Closing for now. Please feel free to reopen if the issue still exists.

**Comment by kestesskat** [comment]
thank you - apparently I was looking for something like this the line below:

etcd --name g000000 --data-dir F:\MyDir\bin\etcd\data --initial-advertise-peer-urls http://10.0.0.4:2380 --listen-peer-urls http://10.0.0.4:2380 --listen-client-urls http://0.0.0.0:2379,http://127.0.0.1:2379 --advertise-client-urls http://10.0.0.4:2379 --initial-cluster-token etcd-cluster-1 --initial-cluster-state existing --initial-cluster infra1=http://10.0.2.4:22380,infra2=http://10.0.2.4:32380,infra3=http://10.0.2.4:12380,g000000=http://10.0.0.4:2380
