### ISSUE TITLE
Cannot build latest etcd with latest go on windows

### ISSUE THREAD

**Issue by kestesskat** [etcd-io/etcd#11071]
At this commit: commit 94745a4eed0425653b3b4275a208d38babceeaec (HEAD -> kat/3_3_15, tag: v3.3.15)

Using go version: go version go1.12.9 windows/amd64
CMD shell
GOPATH=F:\src_etcd\etcd
in that directory using "go build" ... and then this:

src\github.com\coreos\etcd\etcdmain\config.go:306:15: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("path", cfg.configFile) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Info
src\github.com\coreos\etcd\etcdmain\etcd.go:66:47: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".Error(err) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Warn
src\github.com\coreos\etcd\etcdmain\etcd.go:73:59: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".Error(err) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Warn
src\github.com\coreos\etcd\etcdmain\etcd.go:102:15: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("host", defaultHost) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Info
src\github.com\coreos\etcd\etcdmain\etcd.go:110:54: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".Error(dhErr) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Info
src\github.com\coreos\etcd\etcdmain\etcd.go:121:15: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("data-dir", cfg.ec.Dir) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Warn
src\github.com\coreos\etcd\etcdmain\etcd.go:131:48: cannot use cfg.ec.GetLogger() (type *"go.etcd.io/etcd/vendor/go.uber.org/zap".Logger) as type *"github.com/coreos/etcd/vendor/go.uber.org/zap".Logger in argument to identifyDataDirOrDie
src\github.com\coreos\etcd\etcdmain\etcd.go:136:15: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("data-dir", cfg.ec.Dir) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Info
src\github.com\coreos\etcd\etcdmain\etcd.go:137:15: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("dir-type", string(which)) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Info
src\github.com\coreos\etcd\etcdmain\etcd.go:151:16: cannot use "github.com/coreos/etcd/vendor/go.uber.org/zap".String("dir-type", string(which)) (type "github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field) as type "go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field in argument to lg.Panic
src\github.com\coreos\etcd\etcdmain\etcd.go:151:16: too many errors

Did the repo just move? The errors are of this form:
github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore".Field
as type
              go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore".Field

**Comment by Thf772** [comment]
I am expriencing a similar error when trying to build Minio on Linux (Raspbian):

    # github.com/coreos/etcd/clientv3
    go/src/github.com/coreos/etcd/clientv3/auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
    go/src/github.com/coreos/etcd/clientv3/auth.go:126:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
    go/src/github.com/coreos/etcd/clientv3/auth.go:131:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
    go/src/github.com/coreos/etcd/clientv3/auth.go:136:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
    go/src/github.com/coreos/etcd/clientv3/auth.go:141:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
    go/src/github.com/coreos/etcd/clientv3/auth.go:146:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
    go/src/github.com/coreos/etcd/clientv3/auth.go:151:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
    go/src/github.com/coreos/etcd/clientv3/auth.go:156:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
    go/src/github.com/coreos/etcd/clientv3/auth.go:161:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
    go/src/github.com/coreos/etcd/clientv3/auth.go:166:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
    go/src/github.com/coreos/etcd/clientv3/auth.go:166:106: too many errors

For information:

    go version go1.12.9 linux/arm

**Comment by anotherGoogleFan** [comment]
Yes, I met the same problem.
My go is ```go version go1.13.1 windows/amd64```
