### ISSUE TITLE
Range performance

### ISSUE THREAD

**Issue by MaggieCui** [etcd-io/etcd#11079]
// Put puts the given key into the key-value store.
  // A put request increments the revision of the key-value store
  // and generates one event in the event history.
  rpc Put(PutRequest) returns (PutResponse) {
      option (google.api.http) = {
        post: "/v3/kv/put"
        body: "*"
    };
  }

I have notice that Range is not defiened by stream, if I have 200w records need (about 2GB) return from range, the question as followers:
1.  how is the performance?
2. successful probability？ Will it often fail because of the large data?

**Comment by MaggieCui** [comment]
help help help

**Comment by MaggieCui** [comment]
> use with limit. so you can do pagination, similar to minibatch.

1. so you do not recommend get all records once?
2. i want get all records before they change and only can do in background because of the time spent. I should record the revision first when i get first batch, the use this revision to get others?

**Comment by MaggieCui** [comment]
> 1. if the total size is large, then yes
> 2. yes
> 3. you can sort it. the end key and more flag will be set in the response for your next request.

will you think about stream range?

**Comment by gjcarneiro** [comment]
This is similar to my question #11001.  As I found out, trying to do Range with limit and pagination doesn't scale for a lot of keys.
