### ISSUE TITLE
grpc_server_handling_seconds_bucket metric missing

### ISSUE THREAD

**Issue by HaveFun83** [etcd-io/etcd#11085]
The following metric is missing `grpc_server_handling_seconds_bucket`
https://github.com/etcd-io/etcd/blob/43fe8c3ee02693053ea1e1a2f9350d9b39c80721/Documentation/op-guide/etcd3_alert.rules.yml#L61

Looks like etcd is missing the following initialization:
grpc_prometheus.EnableHandlingTimeHistogram()

**Comment by alexbrand** [comment]
Hey @HaveFun83, you have to pass `--metrics extended` to the etcd binary to enable those metrics.

**Comment by HaveFun83** [comment]
> Hey @HaveFun83, you have to pass `--metrics extended` to the etcd binary to enable those metrics.

Thanks will try.
