### ISSUE TITLE
[question] OR logic in the guard

### ISSUE THREAD

**Issue by mennanov** [etcd-io/etcd#11089]
As described in https://github.com/etcd-io/etcd/blob/7b4ae58c41b720b8ba1b2ff4ffc1e35c2d707d5f/etcdserver/etcdserverpb/rpc.proto#L582 if there are multiple cmp operations in the IF guard then an "AND" logic is applied to them.

Is there any way to make it an "OR" logic?

I'm trying to achieve the following:
in a single transaction put a value for `key2` only if `key1` does not exist or the value of `key1` is <= some specific value.

Is there a better way of doing that?

Thanks!

**Comment by jingyih** [comment]
How about "If key1 exists AND the value of key1 is > some specific value, then do nothing, else put a value for key2".

**Comment by mennanov** [comment]
Yep, that should work. Thanks!
