### ISSUE TITLE
Metrics backend_commit_duration_seconds P99 latency is floating every 5m.

### ISSUE THREAD

**Issue by jfbai** [etcd-io/etcd#11099]
The P99 of `backend_commit_duration_seconds` is floating every 5m. I did deep dive into mvcc codebase, but did not find any clues. So, I'd like to ask for help from the community to get to know how does this happen.

![image](https://user-images.githubusercontent.com/13513238/64072568-9f036680-ccc3-11e9-8370-a24885053db3.png)

PS: kubernetes apiservers do the compaction with the default `--etcd-compaction-interval duration=5m`.

**Comment by jingyih** [comment]
`backend_commit_duration_seconds` basically measures a fsync syscall. As you noticed, it is aligned with the periodical compaction. In each compaction, potentially lots of keys will be deleted from the data store. The corresponding fsync could be expensive.

**Comment by jfbai** [comment]
> `backend_commit_duration_seconds` basically measures a fsync syscall. As you noticed, it is aligned with the periodical compaction. In each compaction, potentially lots of keys will be deleted from the data store. The corresponding fsync could take a long time.

@jingyih Thanks a lot for explanation.  :)

Is there any best practice to follow to decrease the spike? or it is still in the reasonable range? Also, I'm confusing about why the one of the etcd server's spike(the blue one) is always lower than others? what would be root cause? They are all running on a really fast SSDs.

**Comment by jingyih** [comment]
> Is there any best practice to follow to decrease the spike? or it is still in the reasonable range?

Maybe try to reduce `--etcd-compaction-interval` on kube apiserver? Is this P99 spike affecting etcd's availability to server kube apiserver?

> Also, I'm confusing about why the one of the etcd server's spike(the blue one) is always lower than others?

How about P90, P50? Is there noticeable difference between the servers?

**Comment by jfbai** [comment]
@jingyih Thanks a lot for your help. :)

> > Is there any best practice to follow to decrease the spike? or it is still in the reasonable range?
> 
> Maybe try to reduce `--etcd-compaction-interval` on kube apiserver? Is this P99 spike affecting etcd's availability to server kube apiserver?

I will try to adjust `--etcd-compaction-interval`.

Currently, is has not been affecting the etcd's availability. But, we are on the way to build large k8s clusters at least 5000 nodes in production. So, I'd like to get deep understanding the details about this metrics and how they are affected by scaling the cluster.

> 
> > Also, I'm confusing about why the one of the etcd server's spike(the blue one) is always lower than others?
> 
> How about P90, P50? Is there noticeable difference between the servers?

yes, there is. It may be caused by the differences among the cloud VMs, even though we purchased servers with same spec.

![image](https://user-images.githubusercontent.com/13513238/64158053-6c47a280-ce6a-11e9-9ecd-9db0db3b330f.png)

**Comment by jfbai** [comment]
> `backend_commit_duration_seconds` basically measures a fsync syscall. As you noticed, it is aligned with the periodical compaction. In each compaction, potentially lots of keys will be deleted from the data store. The corresponding fsync could take a long time.

Hi, @jingyih , sorry for bugging you again.

According to the  [performance.md](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md), a etcd requests is committed by `fdatasync`, if so, which metric is collected for measuring the latency that a requests is persistent onto the disk? ( `backend_commit_duration_seconds` measures the latency of `fsync`).
