### ISSUE TITLE
The events etcd watched were lost

### ISSUE THREAD

**Issue by whitetower957** [etcd-io/etcd#11092]
I used etcd3 to write golang project  on windows10,
The problem is when i registered 10 pairs of different key-value,etcd3 watch was only watched 2 pairs of key-value. 
~~~golang
func EtcdWatch() {
watcher := clientv3.NewWatcher(Cli)
   watchChan := watcher.Watch(context.TODO(), DefaultPrefix, clientv3.WithPrefix(), clientv3.WithRev(e.Latestrevision))
   var evType string
   var Evchan chan string
   Evchan = make(chan string,1)
   go func() {
      for v := range watchChan {
         for _, event := range v.Events {
            Rwmutex.Lock()
            switch event.Type {
            case mvccpb.PUT:
               evType = v"put"
            case mvccpb.DELETE:
               evType = "delete"
            }
            Evchan <- evType
            Rwmutex.Unlock()
         }
      }
   }()
} 
~~~
I promised 10 key-value were registered.Because i used client.get(context.todo,key) to get the key-value.
And 10 pairs of key-value had the same DefaultPrefix and leaseID

**Comment by jingyih** [comment]
What is `e.Latestrevision`? Keys that created or modified prior to this revision will not be returned in watch channel.

**Comment by whitetower957** [comment]
~~~golang
resp, err := e.Cli.Get(timeoutctx, DefaultPrefix, clientv3.WithPrefix())
e.Latestrevision = resp.Header.Revision + 1
~~~

**Comment by whitetower957** [comment]
> What is `e.Latestrevision`? Keys that created or modified prior to this revision will not be returned in watch channel.

~~~golang
resp, err := e.Cli.Get(timeoutctx, DefaultPrefix, clientv3.WithPrefix())
e.Latestrevision = resp.Header.Revision + 1
~~~

**Comment by whitetower957** [comment]
I solved it ,because i  used channel to transfer the etcd watched events ,it  blocks the watch channel i guess.
~~~golang
go func(){
     Evchan <- evType
}
~~~
