### ISSUE TITLE
zap logger reports serving client traffic insecurely for https

### ISSUE THREAD

**Issue by rbboulton** [etcd-io/etcd#11107]
I've been trying to learn etcd using the latest etcd Version: 3.4.0 and I noticed when using the zap logger, etcd seems to log that it's listening for client connections "serving client traffic insecurely" even though I have configured https. Further investigation shows the original (capnslog) logger simply reports "serving client requests".

I spent quite some time trying to work out why my configuration may be "insecure" but I'm now wondering if it's simply a typo in the log message as it appears to be inconsistent between the 2 loggers?

logger: zap
{"level":"info","ts":"2019-09-03T09:25:18.672+0100","caller":"embed/serve.go:191","msg":"serving client traffic insecurely","address":"[::]:2379"}

logger: capnslog
2019-09-03 09:25:34.073921 I | embed: serving client requests on [::]:2379

**Comment by gyuho** [comment]
Thanks for report. Should be fixed via https://github.com/etcd-io/etcd/pull/11108.
