### ISSUE TITLE
KeyFile and CertFile are not presented

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#11102]
root@mon01:/home/wushuai/etcd# ./bin/etcd --config-file=/etc/etcd/conf.yml
{"level":"info","ts":"2019-09-02T18:51:10.251+0800","caller":"etcdmain/config.go:304","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"/etc/etcd/conf.yml"}
{"level":"info","ts":"2019-09-02T18:51:10.251+0800","caller":"embed/etcd.go:117","msg":"configuring peer listeners","listen-peer-urls":["https://10.221.128.132:2380"]}
{"level":"info","ts":"2019-09-02T18:51:10.252+0800","caller":"embed/etcd.go:360","msg":"closing etcd server","name":"etcd-1","data-dir":"/var/etcd/data","advertise-peer-urls":["https://10.221.128.132:2380"],"advertise-client-urls":["http://127.0.0.1:2379","https://10.221.128.132:2379"]}
{"level":"info","ts":"2019-09-02T18:51:10.252+0800","caller":"embed/etcd.go:364","msg":"closed etcd server","name":"etcd-1","data-dir":"/var/etcd/data","advertise-peer-urls":["https://10.221.128.132:2380"],"advertise-client-urls":["http://127.0.0.1:2379","https://10.221.128.132:2379"]}
{"level":"warn","ts":"2019-09-02T18:51:10.252+0800","caller":"etcdmain/etcd.go:176","msg":"failed to start etcd","error":"cannot listen on TLS for 10.221.128.132:2380: KeyFile and CertFile are not presented"}
{"level":"fatal","ts":"2019-09-02T18:51:10.252+0800","caller":"etcdmain/etcd.go:271","msg":"discovery failed","error":"cannot listen on TLS for 10.221.128.132:2380: KeyFile and CertFile are not presented","stacktrace":

**Comment by fcddk** [comment]
name: etcd-1
data-dir: /var/etcd/data
listen-client-urls: https://10.221.128.132:2379,http://127.0.0.1:2379
advertise-client-urls: https://10.221.128.132:2379,http://127.0.0.1:2379
listen-peer-urls: http://10.221.128.132:2380
initial-advertise-peer-urls: http://10.221.128.132:2380
initial-cluster: etcd-1=http://10.221.128.132:2380
initial-cluster-token: etcd-cluster-1
initial-cluster-state: new
cert-file: /etc/ssl/etcd/server.pem
key-file: /etc/ssl/etcd/server-key.pem
client-cert-auth: false
trusted-ca-file: /etc/ssl/etcd/ca.pem
auto-tls: false
peer-cert-file: /etc/ssl/etcd/etcd.pem
peer-key-file: /etc/ssl/etcd/etcd-key.pem
peer-client-cert-auth: false
peer-trusted-ca-file: /etc/ssl/etcd/ca.pem
peer-auto-tls: false

**Comment by jingyih** [comment]
This is the same issue as #11101? Please feel free to reopen if I misread.
