### ISSUE TITLE
TSL config run

### ISSUE THREAD

**Issue by fcddk** [etcd-io/etcd#11101]
etcd --config-file=/etc/etcd/conf.yml
conf.yml:
name: etcd-1
data-dir: /var/etcd/data
listen-client-urls: https://10.221.128.132:2379,http://127.0.0.1:2379
advertise-client-urls: https://10.221.128.132:2379,http://127.0.0.1:2379
listen-peer-urls: http://10.221.128.132:2380
initial-advertise-peer-urls: http://10.221.128.132:2380
initial-cluster: etcd-1=http://10.221.128.132:2380
initial-cluster-token: etcd-cluster-1
initial-cluster-state: new
cert-file: /etc/ssl/etcd/server.pem
key-file: /etc/ssl/etcd/server-key.pem
client-cert-auth: false
trusted-ca-file: /etc/ssl/etcd/ca.pem
auto-tls: false
logger: zap

err:
{"level":"info","ts":"2019-09-02T18:22:38.708+0800","caller":"embed/etcd.go:127","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2379","https://10.221.128.132:2379"]}
{"level":"warn","ts":"2019-09-02T18:22:38.708+0800","caller":"embed/etcd.go:681","msg":"closing peer listener","address":"10.221.128.132:2379","error":"TLS key/cert (--cert-file, --key-file) must be provided for client url https://10.221.128.132:2379 with HTTPS scheme"}
{"level":"info","ts":"2019-09-02T18:22:38.708+0800","caller":"embed/etcd.go:360","msg":"closing etcd server","name":"etcd-1","data-dir":"/var/etcd/data","advertise-peer-urls":["http://10.221.128.132:2380"],"advertise-client-urls":["http://127.0.0.1:2379","https://10.221.128.132:2379"]}
{"level":"info","ts":"2019-09-02T18:22:38.709+0800","caller":"embed/etcd.go:364","msg":"closed etcd server","name":"etcd-1","data-dir":"/var/etcd/data","advertise-peer-urls":["http://10.221.128.132:2380"],"advertise-client-urls":["http://127.0.0.1:2379","https://10.221.128.132:2379"]}
{"level":"warn","ts":"2019-09-02T18:22:38.709+0800","caller":"etcdmain/etcd.go:176","msg":"failed to start etcd","error":"TLS key/cert (--cert-file, --key-file) must be provided for client url https://10.221.128.132:2379 with HTTPS scheme"}
{"level":"fatal","ts":"2019-09-02T18:22:38.710+0800","caller":"etcdmain/etcd.go:271","msg":"discovery failed","error":"TLS key/cert (--cert-file, --key-file) must be provided for client url https://10.221.128.132:2379 with HTTPS scheme","stacktrace":"go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2\n\t

**Comment by fcddk** [comment]
the tsl file is exist. I am sure.

**Comment by jingyih** [comment]
Looks like `cert-file` and `key-file` need to be nested under `client-transport-security`, please refer to the sample here:
https://github.com/etcd-io/etcd/blob/master/etcd.conf.yml.sample#L96

I am closing this issue now. Please feel free to reopen if the issue still exists.
