### ISSUE TITLE
Add "export GO111MODULE=on" in Makefile for tls-setup

### ISSUE THREAD

**Issue by kobayashi** [etcd-io/etcd#11119]
Hello,

I was facing to run `make` failure while install go dependencies in [set up tls script](https://github.com/etcd-io/etcd/tree/master/hack/tls-setup). 
I would like to propose to add `export GO111MODULE=on` before starting installation process.

**Comment by jingyih** [comment]
Which go version are you using?

**Comment by kobayashi** [comment]
I tried with go1.12.
