### ISSUE TITLE
etcd panics on adding server to existing cluster

### ISSUE THREAD

**Issue by blagodarin** [etcd-io/etcd#11122]
There is an existing working etcd cluster. To add another server to the cluster, we use this command:

`etcd.exe --name V-GLAVNOV-CL2 --listen-peer-urls http://10.33.68.94:2380 --listen-client-urls http://10.33.68.94:2379,http://127.0.0.1:2379 --advertise-client-urls http://10.33.68.94:2379 --initial-advertise-peer-urls http://10.33.68.94:2380 --data-dir C:\ProgramData\ISS\cluster_data --initial-cluster V-GLAVNOV-CL1=http://10.33.68.93:2380,V-GLAVNOV-CL2=http://10.33.68.94:2380 --initial-cluster-state existing`

It fails with the following output: [etcd1.log](https://github.com/etcd-io/etcd/files/3578674/etcd1.log)

Error message: `panic: rename snapshot file error: rename C:\ProgramData\ISS\cluster_data\member\snap\000000000001b22c.snap.db C:\ProgramData\ISS\cluster_data\member\snap\db: Access is denied.`

However, there are no access restrictions, disk problems or anything, etcd just creates the file and then fails to access it. We have no idea what caused this problem. It was found in production, and we're unable to reproduce it from scratch, but we were able to reproduce it with the etcd data from the problematic cluster: [cluster_data.zip](https://github.com/etcd-io/etcd/files/3578697/cluster_data.zip)

If we start etcd despite this error, the cluster seems to work with the added server:

`etcd.exe  --data-dir C:\ProgramData\ISS\cluster_data --name V-GLAVNOV-CL2 --listen-client-urls http://10.33.68.94:2379,http://127.0.0.1:2379 --listen-peer-urls http://10.33.68.94:2380 --advertise-client-urls http://10.33.68.94:2379 --strict-reconfig-check`

[etcd2.log](https://github.com/etcd-io/etcd/files/3578706/etcd2.log)

etcd version: 3.2.26

**Comment by OlivierDeRivoyre** [comment]
If it may help, I've got the same problem with a etcd 3.3.11 on a Window Server.
It seems the problem occurs only when the joined cluster is aged. Maybe the snapshot must be big enough to raise this bug.

https://github.com/etcd-io/etcd/blob/v3.3.11/etcdserver/server.go#L883
By looking at the code, I suspect that the server try to rename the backend file while this file is still be written. This should be prevented by the [line 879](https://github.com/etcd-io/etcd/blob/v3.3.11/etcdserver/server.go#L879):
	<-apply.notifyc 
Can it be possible that there is intermediate write in the channel that unblock too early the channel 'notifyc'?

**Comment by OlivierDeRivoyre** [comment]
I've got the same error on the latest version (3.3.18) of ETCD 

> 2020-01-17 17:48:08.9575 	FATAL 	 	rename snapshot file error: rename data\etcd-data\member\snap\00000000000190f7.snap.db data\etcd-data\member\snap\db: Access is denied. 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD :panic: rename snapshot file error: rename data\etcd-data\member\snap\00000000000190f7.snap.db data\etcd-data\member\snap\db: Access is denied. 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD : 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD :goroutine 262 [running]: 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD :github.com/coreos/etcd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panic(0xc000143840, 0xc0003553c0, 0x1, 0x1) 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD :	/home/ec2-user/go/src/github.com/coreos/etcd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:89 +0x122 	
> 2020-01-17 17:48:08.9704 	TRACE 	Capsule.SmartLinx.Storage.Server.EtcdLogRelay 	ETCD :github.com/coreos/etcd/etcdserver.(*EtcdServer).applySnapshot(0xc0000d4000, 0xc00010a460, 0xc000524700)

**Comment by CodyBatt** [comment]
I think I hit this same issue today. We have a test that runs with 3 machines and as part of the test it continually removes and adds members to the etcd cluster. After running for 40 hours or so this happened and that machine was effectively broken. Is there anything I can capture or try to help debug it?
 
``` 2020-02-19 05:31:09.040959 I | etcdserver: applying snapshot at index 0...
 2020-02-19 05:31:09.068378 I | etcdserver: raft applied incoming snapshot at index 78879
 2020-02-19 05:31:09.068378 C | etcdserver: rename snapshot file error: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000001341f.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-19 05:31:09.068378 I | etcdserver: finished applying incoming snapshot at index 0
 panic: rename snapshot file error: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000001341f.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 goroutine 130 [running]:
 github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panic(0xc0421ca9a0, 0xc042a39568, 0x1, 0x1)
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:81 +0x157
 github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applySnapshot(0xc04209a000, 0xc0424b8360, 0xc0420f4240)
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:873 +0x33b
 github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc04209a000, 0xc0424b8360, 0xc0420f4240)
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:835 +0x64
 github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func6(0x1636540, 0xc042a0c2c0)
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:797 +0x43
 github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc0424b8300)
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:157 +0xed
 created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
 	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:70 +0x16d
```

The file system looks like this:

```
    Directory: C:\etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/19/2020   9:04 PM                snap
d-----        2/19/2020   9:04 PM                wal


    Directory: C:\etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/19/2020   5:31 AM         302867 00000000000000d2-000000000001341f.snap
-a----        2/19/2020   9:04 PM          32768 db
-a----        2/19/2020   5:47 AM              0 db.lock


    Directory: C:\etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\wal


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/19/2020   9:04 PM       64000000 0.tmp
-a----        2/19/2020   9:17 PM       64000000 0000000000000000-0000000000000000.wal
```

**Comment by CodyBatt** [comment]
I added a retry to see if this is just timing when applying the snapshot, but the snap\db file is locked for the duration. I'm not really sure where to look for the code that is holding this file lock...

```
 2020-02-24 14:13:41.838598 I | etcdserver: raft applied incoming snapshot at index 168973
 2020-02-24 14:13:41.838598 I | etcdserver: attempt rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db => C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db
 2020-02-24 14:13:41.838598 I | etcdserver: rename failed: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:42.838779 I | etcdserver: attempt rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db => C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db
 2020-02-24 14:13:42.838779 I | etcdserver: rename failed: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:44.839758 I | etcdserver: attempt rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db => C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db
 2020-02-24 14:13:44.839758 I | etcdserver: rename failed: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:48.840281 I | etcdserver: attempt rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db => C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db
 2020-02-24 14:13:48.840281 I | etcdserver: rename failed: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:56.840372 I | etcdserver: attempt rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db => C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db
 2020-02-24 14:13:56.840372 I | etcdserver: rename failed: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:56.840372 C | etcdserver: rename snapshot file error: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 2020-02-24 14:13:56.840372 I | etcdserver: finished applying incoming snapshot at index 0
 panic: rename snapshot file error: rename C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\000000000002940d.snap.db C:\Etcd\2ddeb465ba684b2d8659475a23d84f0a.etcd\member\snap\db: Access is denied.
 goroutine 167 [running]:
 github.com/coreos/etcd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panic(0xc000151300, 0xc0002cd388, 0x1, 0x1)
 	C:/Users/skrym/go/src/github.com/coreos/etcd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:89 +0x122
 github.com/coreos/etcd/etcdserver.(*EtcdServer).applySnapshot(0xc0000e6000, 0xc00012a000, 0xc0000f8a80)
 	C:/Users/skrym/go/src/github.com/coreos/etcd/etcdserver/server.go:917 +0x319
 github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc0000e6000, 0xc00012a000, 0xc0000f8a80)
 	C:/Users/skrym/go/src/github.com/coreos/etcd/etcdserver/server.go:876 +0x64
 github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func6(0x1145160, 0xc00010f200)
 	C:/Users/skrym/go/src/github.com/coreos/etcd/etcdserver/server.go:829 +0x43
 github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc00005e0c0)
 	C:/Users/skrym/go/src/github.com/coreos/etcd/pkg/schedule/schedule.go:157 +0xfe
 created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
 	C:/Users/skrym/go/src/github.com/coreos/etcd/pkg/schedule/schedule.go:70 +0x142
```

**Comment by pashagolub** [comment]
Hello. Any news on this? We hit the bug in production.

**Comment by OlivierDeRivoyre** [comment]
For googler, restarting ETCD solve the issue, as mentioned in [patroni-windows-packaging#15](https://github.com/cybertec-postgresql/patroni-windows-packaging/issues/15) in the pashagolub's comment above.

On fist run, I got:
`failed to rename database snapshot file (rename data\etcd-data\member\snap\00000000000cae5e.snap.db data\etcd-data\member\snap\db: Access is denied.)`
On second one:
`skipped unexpected non snapshot file 00000000000cae5e.snap.db`

**Comment by sparkinglu** [comment]
It does not look like a good solution by restarting it. I got same problem for v3.5.2 when a new node is added into an existing cluster.

If my understanding is correct, the issue introduced by the [server.go:1241](https://github.com/etcd-io/etcd/blob/99018a77bea9a9d29962e5169876c64e02739c52/server/etcdserver/server.go#L1241). The openSnapshotBackend tries to rename a snap file to the "db" file. However the "db" file is already opened at the node startup. 

The [server:1275](https://github.com/etcd-io/etcd/blob/99018a77bea9a9d29962e5169876c64e02739c52/server/etcdserver/server.go#L1275) does close the old db after rename it. To avoid such issue, perhaps we need to close the old db before openSnapshotBackend.
