### ISSUE TITLE
migrate storage data from api v2 to api v3，but I can't get the data

### ISSUE THREAD

**Issue by KeepCaim** [etcd-io/etcd#11130]
description：
I'm testing the migration data from api v2 to api v3, result is ok,but I can't get the data whit v3 commond. 

version:
[root@p30699v etcd]# etcdctl -v
etcdctl version: 3.3.13
API version: 2

operation:
[root@p30699v etcd]# etcdctl ls
/a
/b
/v2test
[root@p30699v etcd]# ETCDCTL_API=3 etcdctl get "" --from-key --keys-only --limit 1 | wc -l
0
[root@p30699v etcd]# 
[root@p30699v etcd]# ETCDCTL_API=3 etcdctl migrate
using default transformer
2019-09-06 11:56:36.619544 N | etcdserver/membership: set the initial cluster version to 3.0
2019-09-06 11:56:36.619635 I | etcdserver/api: enabled capabilities for version 3.0
2019-09-06 11:56:36.619652 N | etcdserver/membership: updated the cluster version from 3.0 to 3.3
2019-09-06 11:56:36.619669 I | etcdserver/api: enabled capabilities for version 3.3
finished transforming keys
[root@p30699v etcd]# etcdctl get a
1
[root@p30699v etcd]# ETCDCTL_API=3 etcdctl get a
[root@p30699v etcd]#
[root@p30699v etcd]# ETCDCTL_API=3 etcdctl get "" --from-key --keys-only --limit 1 | wc -l
0
[root@p30699v etcd]#

**Comment by jingyih** [comment]
There are two data stores in v3+ etcd backend. The original v2 data is preserved in v2 store, accessible via v2 API (therefore no application change needed). v3 API can access v3 store. The two stores are separated and isolated.

Ref: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/v2-migration.md

**Comment by KeepCaim** [comment]
Yes, I have checked it.I want to migrate keys in a v2 store to a v3 mvcc-store through migrate command.Am I doing the wrong thing,and How should I do,thanks.

**Comment by KeepCaim** [comment]
I have realized，thank you jinyih

**Comment by 1ea50n** [comment]
> I have realized，thank you jinyih

how do you solve that

**Comment by 1ea50n** [comment]
> There are two data stores in v3+ etcd backend. The original v2 data is preserved in v2 store, accessible via v2 API (therefore no application change needed). v3 API can access v3 store. The two stores are separated and isolated.
> 
> Ref: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/v2-migration.md

I have the same issue.I migrate part of v2 data to v3.
Realy need help, thanks

**Comment by lilic** [comment]
The v2 API is still there, so it should work correctly. This is the migration guide https://etcd.io/docs/v3.4/upgrades/upgrade_3_0/.

**Comment by ptabor** [comment]
Writing of v3 keys should happen in this line: 

https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/etcdctl/ctlv3/command/migrate_command.go#L303


v2 content read is here:
https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/etcdctl/ctlv3/command/migrate_command.go#L243


Intermediate serialization here: 
https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/etcdctl/ctlv3/command/migrate_command.go#L271

Please add `logging` around this places and it should reveal in which 'phase' the date are lost.
