### ISSUE TITLE
bill-of-materials test fails in CI with Go 1.13

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#11132]
https://github.com/etcd-io/etcd/pull/11110

```
Checking bill of materials...

2019/09/06 19:56:12 open /go/pkg/mod/github.com/beorn7/perks@v1.0.0/src/github.com/beorn7/perks/quantile: no such file or directory

1,456d0

< [
```

**Comment by gyuho** [comment]
@spzala @vimalk78 Can you help on this?

**Comment by vimalk78** [comment]
sure, i can take a look.

**Comment by vimalk78** [comment]
@gyuho , this requires modifications in `https://github.com/coreos/license-bill-of-materials`
Tested with local changes, and it works.

Should i send a PR to `https://github.com/coreos/license-bill-of-materials` or fork it as part of `https://github.com/etcd-io` and fix that?

**Comment by gyuho** [comment]
Let's fix `coreos/license-bill-of-materials`, and etcd will automatically pick up the latest.

**Comment by vimalk78** [comment]
ok !!

**Comment by vimalk78** [comment]
@gyuho the PR is merged, we can close this issue.

**Comment by gyuho** [comment]
@vimalk78 Thanks!

**Comment by gyuho** [comment]
@vimalk78 Can we reenable bom tests?

**Comment by jingyih** [comment]
bom test is still failing. Should we reopen this?

**Comment by vimalk78** [comment]
yes we can reopen it.
The tests are failing because the CI is not pulling latest version of `license-bill-of-materials`

**Comment by gyuho** [comment]
@jingyih @vimalk78 Sorry for delay. Rebuilding test image now.

**Comment by gyuho** [comment]
Just pushed a new test image. Please try again.

**Comment by vimalk78** [comment]
Bom test still seems to be failing
