### ISSUE TITLE
mvcc: question on txnReadWrite in kv.go

### ISSUE THREAD

**Issue by YoyinZyc** [etcd-io/etcd#11165]
It looks confusing for me to put `txnReadWrite` struct inside `kv.go` which consists of abstract interfaces. Logically, I think `txnReadWrite` is a kind of txn object which should be put into `kvstore_txn.go` with `storeTxnRead` and `storeTxnWrite`. Please correct me if there are any other design concerns. 

Thanks

**Comment by jingyih** [comment]
For reference, I think you are referring to this: https://github.com/etcd-io/etcd/blob/e84029cc0413a2db2d607532e7560f61b504b148/mvcc/kv.go#L90

Looks like it is used by mvcc transaction-related metrics. If that is the only usage, another option is to move it to metrics_txn.go.
