### ISSUE TITLE
missing metrics for gRPC request duration / service time

### ISSUE THREAD

**Issue by iwinux** [etcd-io/etcd#11177]
I've checked [Documentation/metrics/v3.3.10](https://github.com/etcd-io/etcd/blob/master/Documentation/metrics/v3.3.10) and output of `GET /metrics`, but I could not find any metric that tells:

1. how many seconds in total does the server spend on serving `Range` requests?
1. what is the P99 latency of `Put` requests?

According to [the docs](https://github.com/etcd-io/etcd/blob/master/Documentation/v2/metrics.md), `GET /metrics` in v2 had offered `etcd_http_successful_duration_seconds`. Is it possible for v3 to expose such metrics?

**Comment by jingyih** [comment]
Could you try enabling this flag?

**Comment by iwinux** [comment]
@jingyih That's what I'm looking for. Thanks!

**Comment by iwinux** [comment]
Should we mention this flag in [metrics.md](https://github.com/etcd-io/etcd/blob/master/Documentation/metrics.md)?

**Comment by jingyih** [comment]
Yes that file is outdated.
