### ISSUE TITLE
What should be done to make the cluster of other nodes work normally when one node is abnormal

### ISSUE THREAD

**Issue by timyinshi** [etcd-io/etcd#11183]
We have a three-node etcd cluster. 
When a node hangs up, other nodes in the etcd cluster will look for the node and report the problem of not connecting to it. and the etcd cluster can not work.
What should be done to make the cluster of other nodes work normally when one node is abnormal?

the etcd log is:
2019-09-25 01:25:03.380086 W | rafthttp: health check for peer 828a1d45e099c0cb could not connect: dial tcp 10.71.216.3:2380: getsockopt: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
2019-09-25 01:25:03.380545 W | rafthttp: health check for peer 828a1d45e099c0cb could not connect: dial tcp 10.71.216.3:2380: getsockopt: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")

**Comment by jingyih** [comment]
These are warning messages. A 3-node cluster with 2 healthy nodes should be able to continue to work. Could you elaborate how the etcd cluster was not working in your case?

**Comment by timyinshi** [comment]
i know the reason,i must ensure that the number of members in the 3-node cluster is equal to the number in the etcd node's configuration(ETCD_INITIAL_CLUSTER),and the ETCD_INITIAL_CLUSTER_STATE must be 'existing'.
but when my cluster only one  node is working,i must remove the nodes that not working,and modify the config of ETCD_INITIAL_CLUSTER=workingip:2380 
my question : when only one etcd node can work,i can not remove the nodes that not working by memer remove command ,then how can i remove the nodes that can not work.

**Comment by jingyih** [comment]
Please refer to https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md

**Comment by timyinshi** [comment]
my question is same as another issue,so i close this issue.
https://github.com/etcd-io/etcd/issues/11199
