### ISSUE TITLE
Duplicate check in confchange.Simple

### ISSUE THREAD

**Issue by ghost** [etcd-io/etcd#11189]
https://github.com/etcd-io/etcd/blob/3712a5d045603013f2ea97ba0fca4eb7daa3a2e5/raft/confchange/confchange.go#L146

In the method confchange.Simple(), it calls checkInvariants to check the config, then it calls checkAndReturn which calls checkInvariants  again.

It is better to just remove the checkInvariants in confchange.Simple().

**Comment by jingyih** [comment]
cc @tbg

**Comment by tbg** [comment]
Thanks @Jiafu-Jiang, feel free to send a PR.
