### ISSUE TITLE
What happens when revision overflows int64？

### ISSUE THREAD

**Issue by opriz** [etcd-io/etcd#11187]
Hi,
As the revision always be incremented,I believe it will exceed max of int64, but I didn't find document about this situation.And how do etcd handle this?Should users do something about this?
thanks.

**Comment by xiang90** [comment]
I will not worry about this...

Even if you change the state of the store 20k every seconds, it requires 5.3 billion years to overflow it.

**Comment by wxdao** [comment]
> I will not worry about this...
> 
> Even if you change the state of the store 20k every seconds, it requires 5.3 billion years to overflow it.

Just a minor math correction: It actually comes out to 5.3 billion days, not years. That translates to roughly 14.6 million years. Either way, it's more than enough time.
