### ISSUE TITLE
how to modify the members data by curl or wget?

### ISSUE THREAD

**Issue by timyinshi** [etcd-io/etcd#11199]
how to get members data by curl,i can not get data through this command:
curl -H "Content-Type: application/json" -H "Accept: application/json" --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/member-master2.pem --key /etc/ssl/etcd/ssl/member-master2-key.pem https://192.168.0.93:2380/members 
the error is:
curl: (56) Unexpected EOF

but i can get the data by wget command:
wget  --ca-certificate=/etc/ssl/etcd/ssl/ca.pem --certificate=/etc/ssl/etcd/ssl/member-master2.pem --private-key=/etc/ssl/etcd/ssl/member-master2-key.pem https://192.168.0.93:2380/members

when i use wget to modify the members data,i have the error:
wget --header="Content-Type:application/json,Allow:POST"  --post-data='[{"id":3891187648118914658,"peerURLs":["https://192.168.0.93:2380"],"name":"etcd2","clientURLs":["https://192.168.0.93:2379"]},{"id":8974669153802290281,"peerURLs":["https://192.168.0.77:2380"],"name":"etcd3","clientURLs":["https://192.168.0.77:2379"]},{"id":16618349488166888420,"peerURLs":["https://192.168.0.119:2380"],"name":"etcd1","clientURLs":["https://192.168.0.119:2379"]}]' --ca-certificate=/etc/ssl/etcd/ssl/ca.pem --certificate=/etc/ssl/etcd/ssl/member-master2.pem --private-key=/etc/ssl/etcd/ssl/member-master2-key.pem https://192.168.0.93:2380/members

HTTP request sent, awaiting response... 405 Method Not Allowed
2019-10-03 16:23:17 ERROR 405: Method Not Allowed.

**Comment by jingyih** [comment]
Could you use the client interface? 2380 is the port for communication between the etcd servers.

Please read: https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md

The API path can be found in proto file: https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L164
or the generated swagger: https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/apispec/swagger/rpc.swagger.json#L477

**Comment by jingyih** [comment]
For example, to get member list:

$ curl -L http://localhost:2379/v3/cluster/member/list -X POST

**Comment by timyinshi** [comment]
@jingyih  use this command can not get member data:
curl -L http://localhost:2379/v3/cluster/member/list -X POST --output aaa.log
the aaa.log have nothing

**Comment by timyinshi** [comment]
@jingyih i can get the member data by this command:
curl -L -H "Content-Type: application/json" --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/member-master2.pem --key /etc/ssl/etcd/ssl/member-master2-key.pem https://192.168.0.93:2379/v3alpha/cluster/member/list -X POST -d '{}'

but the remove command can not work when the cluster is not healthy.
curl -L -H "Content-Type: application/json" --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/member-master2.pem --key /etc/ssl/etcd/ssl/member-master2-key.pem https://192.168.0.93:2379/v3alpha/cluster/member/remove -X POST -d '{"ID":16618349488166888420}'
this command can not have result,it is hang.

how can i remove the abnormal member when the cluster is not healthy?use wget to modify the port 2380?

**Comment by jingyih** [comment]
You are right. In my previous example I was just trying to provide the API path.

Regarding member removal, what is the scenario? Do you have 3-node cluster where 1 of them is not available (which is the also the one you are trying to remove)?

**Comment by jingyih** [comment]
If the cluster has already lost quorum, you need to follow https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md

**Comment by timyinshi** [comment]
@jingyih
thanks,when the cluster is unhealthy,i get the new cluster by "snapshot restore",but it take more time.
if i want to modify the member metadata,do the cluster must be healthy?
if i can modify the member metadata when the cluster is unhealthy,i can take very little time to fix my cluster.

**Comment by jingyih** [comment]
cluster runtime reconfiguration requires quorum for safety considerations. Please read: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md

**Comment by timyinshi** [comment]
i  think snapshotting the data is a right method
