### ISSUE TITLE
Add tracing to txn request.

### ISSUE THREAD

**Issue by YoyinZyc** [etcd-io/etcd#11191]
Adding tracing to txn request is kind of different from to range or put request. A txn request could have couple of range, put, delete and txn operations. I think it will be confusing to just put all of these operations' traces together. My first idea is to use subtrace for each operations. The basic structure is like this:
>... 
"msg": "trace[12345] transaction", "details": "...", "duration":"100ms", "start":"...", "end":"...", 
"steps": [
trace[12345] 'compare' (duration: 1ms),
trace[12345]: "msg": "subtrace range", "details": "...", "duration":"20ms", "start":"...", "end":"...", "steps": [...],
trace[12345]: "msg": "subtrace put", "details": "...", "duration":"20ms", "start":"...", "end":"...", "steps": [...],
...
]
>
The potential concern on this approach is that the nested trace is not quite friendly with structure logging.
My second thought is adding the sub requests' information into step's detailed fields. 
> ...
"msg": "trace[12345] transaction", "details": "...", "duration":"100ms", "start":"...", "end":"...", 
"steps": [
trace[12345] 'compare' (duration: 1ms),
trace[12345]: "agreement among raft nodes before linearized reading {"type":"range", "range_start":"foo",...} duration: 20ms",
...
trace[12345]: "raft request"{"type":"put", "key":"fooo"...} duration:1ms",
...
]
>
The drawback of this one is that it will increase the volume of log and may be confusing especially when we have nested transactions.
Do you have some suggestions on the arrangement of txn tracing?

**Comment by YoyinZyc** [comment]
@jpbetz @gyuho Any suggestions?

**Comment by jpbetz** [comment]
My general preference would be that we retain as much structure as possible and try to avoid putting structured data into strings via some serialization. I don't know zap that well, unfortunately. What does `zap.Any` do if we provide a struct that models our desired tracing output?

**Comment by gyuho** [comment]
@YoyinZyc @jpbetz Or just simply tag with level (`zap.Int("tracing-level", 1))? Regarding `Txn`, it will be level 1, and subsequent puts and ranges can be level 2. What do you think

**Comment by gyuho** [comment]
Oh wait, it will be traced in the same message, so we would need better way to differentiate within the message.
