### ISSUE TITLE
etcd shutdown failed due to grpc: addrConn.createTransport connection error

### ISSUE THREAD

**Issue by s2li** [etcd-io/etcd#11208]
Specific:
  etcd Version: 3.3.0+git
  Git SHA: Not provided (use ./build instead of go build)
  Go Version: go1.12.5
  Go OS/Arch: linux/amd64
  
  but we use clientV2.

  etcd cluster deployment
  
  issue was happened on single node shutdown phase.
     loop print  addrConn.createTransport connection error, and etcd server process can't exit after received sigterm.

  logs:
   Sep 25 14:08:28 node1 etcd[2864]: received terminated signal, shutting down...
   Sep 25 14:08:28 node1 etcd-start-up.sh[2864]: WARNING: 2019/09/25 14:08:28 grpc: 
   addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: 
   desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". 
   Reconnecting...
   ... <loop report this log>
  Sep 25 14:09:14 node1 etcd-start-up.sh[2864]: WARNING: 2019/09/25 14:09:14 grpc: 
  addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: 
  desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". 
  Reconnecting...
  -- Reboot --

Reproducible:
  yes, but low, observe  2+ cases by reboot command.

I searched history issues, and found it's similar with #8267, could you confirm whether same one or a new case? thanks!

what we do / WR for this issue:
  we currently set TimeoutStopSec to low value to speed etcd service exit by sigkill.

**Comment by soniadimitrov** [comment]
Also seeing with same with 3.3.18, the only way to recover is to sigkill the etcd process:

2020-01-30 18:21:33.629070 I | etcdmain: etcd Version: 3.3.18
2020-01-30 18:21:33.629117 I | etcdmain: Git SHA: 3c8740a
2020-01-30 18:21:33.629122 I | etcdmain: Go Version: go1.13.4
2020-01-30 18:21:33.629126 I | etcdmain: Go OS/Arch: linux/amd64

2020-01-30 18:15:47.785992 N | pkg/osutil: received terminated signal, shutting down...
WARNING: 2020/01/30 18:15:47 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:15:48 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:15:50 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:15:52 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:15:57 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:16:05 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:16:16 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:16:31 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:16:56 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:17:37 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:18:55 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...
WARNING: 2020/01/30 18:20:28 grpc: addrConn.createTransport failed to connect to {72.247.39.22:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 72.247.39.22:2379: connect: connection refused". Reconnecting...

Is there a fix for this in 3.4?

**Comment by fengzixu** [comment]
same problem

**Comment by aviam** [comment]
Hi,
Any update? getting the same error when configuring vault with etcd as kv storage.
Any estimation when this will be fixed?
