### ISSUE TITLE
Incorporate release tagging into /scripts/release

### ISSUE THREAD

**Issue by jpbetz** [etcd-io/etcd#11226]
@gyuho showed me this nice script he has been using to release. Let's incorporate the additional steps into `scripts/release` so we can release via a single command (modulo release signing).

```
export RELEASE_VERSION=v3.3.16
git tag --sign ${RELEASE_VERSION} --message ${RELEASE_VERSION}
git tag --list "v3.3.*"
git push origin tags/${RELEASE_VERSION};
rm -rf /tmp/etcd-release-3.3.16
cd ${HOME}/go/src/github.com/coreos/etcd
./scripts/release ${RELEASE_VERSION}
```

cc @wenjiaswe @YoyinZyc @jingyih @hexfusion

**Comment by jpbetz** [comment]
@wenjiaswe or @YoyinZyc any interest on incorporating this?

**Comment by YoyinZyc** [comment]
@jpbetz  Sure, I will work on that.

**Comment by YoyinZyc** [comment]
I think the release signing is already done by the current script. Correct me if I am wrong.
https://github.com/etcd-io/etcd/blob/a6a1fdd45786442452ecca8b8d1228666acce584/scripts/release#L119
And seems like we don't need to do git push either.
https://github.com/etcd-io/etcd/blob/a6a1fdd45786442452ecca8b8d1228666acce584/scripts/release#L125

**Comment by gyuho** [comment]
@YoyinZyc Maybe you can help on this as well? https://github.com/etcd-io/etcd/issues/11227

Also, there are some other small improvements we can make

https://github.com/etcd-io/etcd/blob/a6a1fdd45786442452ecca8b8d1228666acce584/scripts/release#L54

can be just `https` endpoint, so we can run the release scripts in any build machine without SSH key.

**Comment by gyuho** [comment]
Also, building `tar` files has been broken in darwin...

https://github.com/etcd-io/etcd/blob/efc154b095b0a25fece7fd117df636c1fd807d70/scripts/build-binary#L60-L63

I am inclined to force linux machine for release builds... Maybe you can change that line to enforce `GOOS=linux`

**Comment by YoyinZyc** [comment]
> Also, building tar files has been broken in darwin...
>
@gyuho  Not quite sure I understand the problem. I think for darwin it will always build a zip file, right?
https://github.com/etcd-io/etcd/blob/efc154b095b0a25fece7fd117df636c1fd807d70/scripts/build-binary#L85-L91
It is redundant to check the os and change the tarcmd there.

**Comment by gyuho** [comment]
@YoyinZyc 

https://github.com/etcd-io/etcd/blob/efc154b095b0a25fece7fd117df636c1fd807d70/scripts/build-binary#L75

When we run this script in darwin, we still run tar command there.

We can prevent darwin release build here

https://github.com/etcd-io/etcd/blob/efc154b095b0a25fece7fd117df636c1fd807d70/scripts/build-binary#L61

by adding some `exit` line.
