### ISSUE TITLE
etcd 3.3.16 reports incorrect version

### ISSUE THREAD

**Issue by ckoehn** [etcd-io/etcd#11230]
Steps to reproduce:

`$ docker run --rm quay.io/coreos/etcd:v3.3.16 etcd --version`

```
etcd Version: 3.3.15
Git SHA: 292182daf
Go Version: go1.12.9
Go OS/Arch: linux/amd64
```

**Comment by jpbetz** [comment]
Checking

**Comment by jpbetz** [comment]
Here's the commit: https://github.com/etcd-io/etcd/commit/292182daf9e5b03920a62557f11a4faf7abc25d7

**Comment by jpbetz** [comment]
Tag is not on the release branch. Moving the tag and re-releasing. We haven't signed the release yet so this should be correctable.

**Comment by jpbetz** [comment]
Fixed.

```
docker run --rm quay.io/coreos/etcd:v3.3.16 etcd --version
etcd Version: 3.3.16
Git SHA: 3fae82862
Go Version: go1.12.9
Go OS/Arch: linux/amd64
```
