### ISSUE TITLE
3-node etcd cluster, one node stop, client get timeout

### ISSUE THREAD

**Issue by MaggieCui** [etcd-io/etcd#11239]
### test program
![image](https://user-images.githubusercontent.com/15689619/66665090-62426c00-ec80-11e9-9f33-ca995f46a0c8.png)

### etcdserver start cmd
etcd --name member1 --listen-client-urls http://10.187.0.91:22379 --advertise-client-urls http://10.187.0.91:22379 --listen-peer-urls http://10.187.0.91:22380 --initial-advertise-peer-urls http://10.187.0.91:22380 --initial-cluster member1=http://10.187.0.91:22380,member2=http://10.187.0.91:22382,member3=http://10.187.0.91:22384 --enable-pprof --data-dir=/home/lixiaocui1/etcd1/default.etcd --election-timeout=3000 --initial-cluster-state=existing --grpc-keepalive-timeout 5s --heartbeat-interval 300 -debug

etcd --name member2 --listen-client-urls http://10.187.0.91:22381 --advertise-client-urls http://10.187.0.91:22381 --listen-peer-urls http://10.187.0.91:22382 --initial-advertise-peer-urls http://10.187.0.91:22382 --initial-cluster member1=http://10.187.0.91:22380,member2=http://10.187.0.91:22382,member3=http://10.187.0.91:22384 --enable-pprof --data-dir=/home/lixiaocui1/etcd2/default.etcd --election-timeout=3000 --initial-cluster-state=existing --grpc-keepalive-timeout 5s --heartbeat-interval 300 --debug

etcd --name member3 --listen-client-urls http://10.187.0.91:22383 --advertise-client-urls http://10.187.0.91:22383 --listen-peer-urls http://10.187.0.91:22384 --initial-advertise-peer-urls http://10.187.0.91:22384 --initial-cluster member1=http://10.187.0.91:22380,member2=http://10.187.0.91:22382,member3=http://10.187.0.91:22384 --enable-pprof --data-dir=/home/lixiaocui1/etcd3/default.etcd --election-timeout=3000 --initial-cluster-state=existing --grpc-keepalive-timeout 5s --heartbeat-interval 300 --debug

### operation: 
kill -STOP 2067241 (member2)

### result
![image](https://user-images.githubusercontent.com/15689619/66665292-d41ab580-ec80-11e9-8ab4-6693f1dee8cf.png)

### question
why? two node-cluster must work as usual

**Comment by MaggieCui** [comment]
need help

**Comment by jingyih** [comment]
Could you try `etcdctl endpoint status -w table --cluster` and `etcdctl endpoint health -w table --cluster` and check their output first?

**Comment by MaggieCui** [comment]
> status -w table --cluster

the result as follows:
![image](https://user-images.githubusercontent.com/15689619/66697960-9e231300-ed0c-11e9-8f4c-e1227b6e534c.png)
![image](https://user-images.githubusercontent.com/15689619/66697997-e0e4eb00-ed0c-11e9-8c37-a7435e5ba781.png)

I just hang one node, why get "context deadline exceeded" error?
client can retry other node?? 3-node-raft cluster  can bear one node fail??

**Comment by MaggieCui** [comment]
> Could you try `etcdctl endpoint status -w table --cluster` and `etcdctl endpoint health -w table --cluster` and check their output first?

the result as follows:
![image](https://user-images.githubusercontent.com/15689619/66698959-4e951500-ed15-11e9-8ab7-3441e9089118.png)
![image](https://user-images.githubusercontent.com/15689619/66698965-59e84080-ed15-11e9-80ee-8b6cdb6471ca.png)

I just hang one node, why get "context deadline exceeded" error?
client can retry other node?? 3-node-raft cluster can bear one node fail??

**Comment by jingyih** [comment]
Looks like the cluster is as expected. You have 1 stopped node in the cluster. The other 2 nodes can still make progress.

If you try `etcdctl put`, does it have the same result as your program?

**Comment by MaggieCui** [comment]
> Looks like the cluster is as expected. You have 1 stopped node in the cluster. The other 2 nodes can still make progress.
> 
> If you try `etcdctl put`, does it have the same result as your program?

'etcdctl put' work as usual.
maybe the etcdclient has establish connect with three-node  before one-node hang?

**Comment by jingyih** [comment]
Could you paste the test program to something like golang playground? (Instead of a screenshot)

**Comment by MaggieCui** [comment]
> Could you paste the test program to something like golang playground? (Instead of a screenshot)

package main

import (
   "context"
   "go.etcd.io/etcd/clientv3"
   "log"
   "time"
)

func main() {
   var err error
   client, err := clientv3.New(clientv3.Config{
      Endpoints:   []string{"10.187.0.91:22379","10.187.0.91:22381","10.187.0.91:22383"},
      DialTimeout: time.Duration(10000) * time.Millisecond,
   })

   ctx, _ := context.WithTimeout(context.Background(), 10 * time.Second)
   _, err = client.Put(ctx, "lixiaocui", "baqilin")
   if err != nil {
      log.Printf("put error : %v", err)
      return
   }

   ticker := time.NewTicker(2 * time.Second)
   defer ticker.Stop()
   for {
      select {
      case <-ticker.C:
         ctx, _ := context.WithTimeout(context.Background(), 10 * time.Second)

         _, err = client.Get(ctx, "lixiaocui")
         if err != nil {
            log.Printf("get from etcd err: %v", err)
            return
         } else {
            log.Printf("get ok")
         }
      }
   }
}


use `kill -19 pid` during the program run and 'kill -CONT pid' to recover

**Comment by MaggieCui** [comment]
help help help

**Comment by jingyih** [comment]
I am not expert on this. Reading from the code:

SIGTERM and SIGINT are caught here:
https://github.com/etcd-io/etcd/blob/61354ff8ede7dde7839e0df987f37cda931fd740/pkg/osutil/interrupt_unix.go#L50

SIGSTOP is not caught by etcd? What would be the expected behavior for etcd when receiving this signal? The signal usually pauses the process in its current state.

**Comment by MaggieCui** [comment]
> I could reproduce when stop the process, but killing the process works as expected. So to narrow it down,
> 
> * `kill -19 pid` or `kill -STOP pid` while running the test program results in client exit with `context deadline exceeded` as mentioned in this issue (but leaving process stopped and re-run client, it works as expected)
> * `kill -9 pid` while running the test program results in client working with 2 member cluster as expected

I want the cluster  provide normal service when a node hang(this situation is the same as server down)，because majority nodes in cluster alive. Why one node hang affect the whole cluster?

I think this situation etcd must solve(server side or client side) as an high availability service?  reboot is simple but time of  cluster abnormal discovery is uncontrollable

**Comment by MaggieCui** [comment]
> I am not expert on this. Reading from the code:
> 
> SIGTERM and SIGINT are caught here:
> https://github.com/etcd-io/etcd/blob/61354ff8ede7dde7839e0df987f37cda931fd740/pkg/osutil/interrupt_unix.go#L50
> 
> SIGSTOP is not caught by etcd? What would be the expected behavior for etcd when receiving this signal? The signal usually pauses the process in its current state.

Regardless of the behavior of this node, clients should always be able to write because another node alive. 

Raft return ok when two node write success  and read ok when leader is alive, why one node hang result in read fail?

**Comment by MaggieCui** [comment]
anybody help?
