### ISSUE TITLE
etcd move the boltdb freelist hashmap feature out of experimental 

### ISSUE THREAD

**Issue by WIZARD-CXY** [etcd-io/etcd#11258]
Now the etcd use boltdbfreelist type as a experimental flag and its default value is array.
```
	// ExperimentalBackendFreelistType specifies the type of freelist that boltdb backend uses (array and map are supported types).
	ExperimentalBackendFreelistType string `json:"experimental-backend-bbolt-freelist-type"`
```
 
I think now we can remove its experimental flag and set its default value to the `hashmap` type after several months test and production use. It's stable now and will boost etcd storage performance a lot. @jingyih @xiang90 .

**Comment by gyuho** [comment]
@WIZARD-CXY Sounds good. Can you work on this?

**Comment by jingyih** [comment]
Sounds good to me.

If the data file is not as large (say only few GBs), is there noticeable performance gain?

**Comment by WIZARD-CXY** [comment]
I will work on that. @gyuho 
Only few GB won't see noticable differences. But hashmap is always better since it is O(1) time complexity  instead of O(n)

**Comment by WIZARD-CXY** [comment]
close now

**Comment by turowicz** [comment]
@WIZARD-CXY  is it possible to migrate an existing etcd database to the freelist?

**Comment by turowicz** [comment]
@WIZARD-CXY  should we use the default map or array for large databases (~100GB).

**Comment by turowicz** [comment]
@WIZARD-CXY do we need to provide the flag for the etcd to use your freelist or is it always on by default?
