### ISSUE TITLE
There is a potential goroutine leak bug in raft/node_test.go

### ISSUE THREAD

**Issue by lzhfromustc** [etcd-io/etcd#11256]
***Description***
The local channel `applyConfChan` created in [TestNodeProposeAddLearnerNode in etcd/raft/node_test.go](https://github.com/etcd-io/etcd/blob/master/raft/node_test.go#L822) can block multiple goroutines. 

I am not sure about the meaning of `applyConfChan`. It has no buffer, 1 receive, but its send is in a loop. If the loop is executed more than 1 time, the child goroutine will be blocked because there is no receive to synchronize with the send, and the main goroutine will also be blocked because `defer close(done)` will not be executed.

***Related code***
https://github.com/etcd-io/etcd/blob/bcc147127d1a33d827f78a0d1bf8fe2363a344f2/raft/node_test.go#L820-L861

***Suggestion***
Maybe we can put `applyConfChan <- struct{}{}` before `n.Advance()`, so it will only be executed one time, and both goroutines will not be blocked.

**Comment by spzala** [comment]
@lzhfromustc thanks and please feel free to create a PR, for a better discussion and, so that the changes run through build process. I am closing the issue but please feel to reopen with errors as needed. Thanks!
