### ISSUE TITLE
Improve the usage of clientv3 for external projects 

### ISSUE THREAD

**Issue by hsyed** [etcd-io/etcd#11251]
1. Clientv3 documentation suggests using the packages prefixed with `go.etcd.io` however the code in concurrency does not accept a [`github.com/coreos/etcd/clientv3.Client`](https://github.com/etcd-io/etcd/blob/3ef2ad8e115449a7004b628a873e2629855ed468/clientv3/concurrency/session.go#L21). 

2. There is quite a bit of dependency sprawl when depending on either version of the package. 

Suggestions:

1. Standardise on one package path for downstream projects.
2. make clientv3 a go submodule and reduce the dependencies down to 
exactly what is needed. 

---
This is what is added to our go.mod file depending on `github.com/coreos/etcd/clientv3` and `github.com/coreos/etcd/clientv3/concurrency`

```
	github.com/coreos/bbolt v1.3.3 // indirect
	github.com/coreos/etcd v3.3.17+incompatible
	github.com/coreos/go-semver v0.3.0 // indirect
	github.com/coreos/go-systemd v0.0.0-20190719114852-fd7a80b32e1f // indirect
	github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f // indirect
	github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0 // indirect
	github.com/grpc-ecosystem/grpc-gateway v1.11.3 // indirect
	github.com/jonboulle/clockwork v0.1.0 // indirect
	github.com/json-iterator/go v1.1.7 // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	github.com/soheilhy/cmux v0.1.4 // indirect
        github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5 // indirect
 	github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2 // indirect
	go.etcd.io/bbolt v1.3.3 // indirect
```

**Comment by hsyed** [comment]
Looking at the code in the repo the references seem to be correct but I can't figure out how to depend on tag v3.4.2 in my `go.mod`. Do I need to add replace directives ?

**Comment by tehsphinx** [comment]
I second pulling out clientv3 into a separate package. My executable gained 7MB just by adding a dependency on the client.

**Comment by hsyed** [comment]
I really want to use etcd in our platform but the dependency sprawl is giving me concern. I am happy to contribute to addressing the problem with some guidance.

As I understand it the client layer should only require grpc, proto (and zap ?)
