### ISSUE TITLE
when would the version 3.2.28 been released? thanks.

### ISSUE THREAD

**Issue by andyliuliming** [etcd-io/etcd#11259]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

**Comment by spzala** [comment]
related #11195

**Comment by andyliuliming** [comment]
Heard about that there're a couple outstanding etcd 3.2 fixes need to be merged before release.

thanks for the response, thanks.

**Comment by spzala** [comment]
@andyliuliming yrw, we can keep this issue open for tracking if you want. Thanks!

**Comment by andyliuliming** [comment]
@spzala any good news? thanks. :)

**Comment by hexfusion** [comment]
Still shooting for this week, but could bleed into weekend.

**Comment by andyliuliming** [comment]
@hexfusion good news? : )

**Comment by hexfusion** [comment]
@andyliuliming the release is built and will go live at 4:00 ET. Thank you for your patience.

**Comment by hexfusion** [comment]
https://github.com/etcd-io/etcd/releases/tag/v3.2.28

**Comment by jingyih** [comment]
Thanks @hexfusion !
