### ISSUE TITLE
etcdctl endpoint --cluster health fails unless v2 api is enabled after upgrading from 3.3 to 3.4

### ISSUE THREAD

**Issue by 2rs2ts** [etcd-io/etcd#11268]
I was upgrading from 3.3.12 to 3.4.1 and after upgrading one server I got this error message from the health command:

```
{"level":"warn","ts":"2019-10-15T22:31:48.553Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-782f2f1a-5da8-410c-823f-3262927c12e7/<my etcd server>:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: remote error: tls: bad certificate\""}
```

Setting `--enable-v2=true` on server startup fixes this. I know however that this command only works if the etcdctl is set to v3 so I don't understand why the v2 API has to be enabled for health to work. Other servers saw this upgraded server as unhealthy too, not sure if that was just the health command failing or if there was actually a problem though.

I'm running etcd on its own servers running Debian stretch, but this etcd cluster is for k8s. Not sure if that detail matters. The certs are generated from a private CA at my company, I didn't change the cert at all for the upgraded server and yet this error happened.

It's probably PEBKAC but in case it's not I felt I should report this.

**Comment by jingyih** [comment]
>  authentication handshake failed: remote error: tls: bad certificate

Is this issue specific to TLS? Could you try without TLS?

**Comment by 2rs2ts** [comment]
@jingyih non-TLS traffic is off the table at my company. Do you want me to try it as a diagnostic tool or are you recommending I disable TLS permanently? The latter will not pass my company's security review :)

**Comment by jingyih** [comment]
Just for diagnostic purpose. Because the error message from your report looks like TLS error, not sure why it is related to `--enable-v2`.

**Comment by 2rs2ts** [comment]
I think enabling the v2 API was a fluke. I don't understand my problem but I'm closing this issue to avoid confusion.
