### ISSUE TITLE
The log-outputs parameter value cannot be the log file path?

### ISSUE THREAD

**Issue by dxvgef** [etcd-io/etcd#11286]
The zap logger supports logging to files. Why can't the etcd `log-outputs` parameter set the log file path?

**Comment by gyuho** [comment]
It should work? You can just pass file path to that flag.

**Comment by dxvgef** [comment]
My config file set up `log-outputs: [/data/logs/]`, but no log files are generated.

**Comment by dxvgef** [comment]
It’s normal now, I don’t know why 😅

**Comment by liujiang0529** [comment]
I set the logger: zap, log-outputs: [/etcd/log/], when i run the "./etcd --config-file=/etcd/conf.yml", why  i find any log file in the dir of log?  seek fot help

**Comment by liujiang0529** [comment]
> My config file set up `log-outputs: [/data/logs/]`, but no log files are generated.

need your help

**Comment by faith2god** [comment]
`log-outputs: ['stdout', '/data/etcd/log/etcd.log','stderr','/data/etcd/log/error.log']`

 works well in this way

**Comment by JasonCrease** [comment]
I believe the docs are largely incorrect on the exact behavior of this setting. From the command-line, it's more like:
`etcd --log-outputs log1.txt,stdout,log2.txt,stderr`

For each item on the list, etcd will output everything to that item. As such, you'll see log1.txt, log2.txt, stdout and stderr all containing every log line.

Here's a real example showing this working. Notice that all log files end up being the same size (some names have been changed and lines elided).
```
$ ./etcd --log-outputs stdout,stderr,error.log,info.log 2> test2.log 1> test1.log
^C
$ ll
-rw-rw-r-- 1 someuser megacorp     8683 Feb 14 14:21 error.log
-rwxr-xr-x 1 someuser megacorp 23760896 Sep 28 15:13 etcd*
-rw-rw-r-- 1 someuser megacorp     8683 Feb 14 14:21 info.log
-rw-rw-r-- 1 someuser megacorp     8683 Feb 14 14:21 test1.log
-rw-rw-r-- 1 someuser megacorp     8683 Feb 14 14:21 test2.log
```

In the absence of that `--log-outputs` option, it outputs logging to stderr.

There is a mutually exclusive undocumented option, `systemd/journal`, which makes it output to the journal log:
```
--log-outputs systemd/journal
```
