### ISSUE TITLE
Flaky test: TestRoundRobinBalancedResolvableFailoverFromRequestFail

### ISSUE THREAD

**Issue by jingyih** [etcd-io/etcd#11297]
Found multiple PRs with this test failed.

`TARGET=linux-amd64-unit`
--- FAIL: TestRoundRobinBalancedResolvableFailoverFromRequestFail (0.03s)
    balancer_test.go:308: expected balanced loads for 20 requests, got switches 6

**Comment by spzala** [comment]
Reopening, noticed it in a recent PR https://travis-ci.com/github/etcd-io/etcd/jobs/379019377#L917

**Comment by teddylear** [comment]
I can take a look into this

**Comment by jingyih** [comment]
@teddylear Thanks!
