### ISSUE TITLE
use curl , illegal base64 data at input byte 4

### ISSUE THREAD

**Issue by BestUO** [etcd-io/etcd#11291]
i use v3.4.3 and when i use curl like this :
curl -XPOST http://172.17.0.2:2379/v3/kv/put -d '{"key": "Zm9v", "value":"smFy"}' etcd work well
but when i use curl like this:
curl -XPOST http://172.17.0.2:2379/v3/kv/put -d '{"key": "Zm9v", "value":"smFsy"}' (only different in value) etcd response me like this
{"error":"illegal base64 data at input byte 4","message":"illegal base64 data at input byte 4","code":3}
any wrong with me ?

**Comment by spzala** [comment]
@BestUO I believe smFsy is invalid encoded value. Please try a different valid value, it should work fine.
