### ISSUE TITLE
conflicting environment variable "ETCD_NAME" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)

### ISSUE THREAD

**Issue by LouieGuo** [etcd-io/etcd#11298]
when I use V3.4.3 to create etcd cluster,I met a problem is 
"conflicting environment variable "ETCD_NAME" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)"

![image](https://user-images.githubusercontent.com/29138525/67664656-ff044980-f9a2-11e9-88b7-e3cc1b5e7e9e.png)

**Comment by jingyih** [comment]
I think this is dup of #11111. Feel free to reopen if you think otherwise.
