### ISSUE TITLE
Test case "TestCorruptedBackupFileCheck" failed on big_endian platform(s390x)

### ISSUE THREAD

**Issue by samding01** [etcd-io/etcd#11306]
Build and test the latest release version v3.43 is possible on s390x Linux platform(big_endian). But one test case
`TestCorruptedBackupFileCheck` is failed on s390x. Here is the output:
```
 go test  go.etcd.io/etcd/clientv3/snapshot -run TestCorruptedBackupFileCheck

    v3_snapshot_test.go:184: expected error message to contain the following keywords:
        snapshot file integrity check failed
        actual error message:
        invalid database
FAIL
FAIL    go.etcd.io/etcd/clientv3/snapshot       0.010s
```
This test case reads/checks an exist file : `clientv3/snapshot/testdata/corrupted_backup.db` (belong to etcd package). However this db file is generated based on a little_endian platform.
etcd uses `go.etcd.io/bbolt@v1.3.3/db.go: 178` (178 func Open(path string, mode os.FileMode, options *Options) (*DB, error) { ) to read the db file. 
Note following code:
```
 259                 if bw, err := db.file.ReadAt(buf[:], 0); err == nil && bw == len(buf) {
 260                         if m := db.pageInBuffer(buf[:], 0).meta(); m.validate() == nil {
```
Here "db.pageInBuffer(buf[:], 0)" reads into buf in bytes and then cast to "meta" structure, so the values in meta are in little endian but "magic" and "version" are in big_endian on a big_endian , 
which causes the "m.validate()" return none nil  on s390x.  There are also errors in the next codes.

Wonder how test data file "clientv3/snapshot/testdata/corrupted_backup.db" is generated on a little-endian machine? Is it possible to generate a similar test data file in big_endian?

Further, are there any potential problem in "Etcd"  on s390x if only this test case is failed because of the test data?

Thanks,

**Comment by jingyih** [comment]
> Wonder how test data file "clientv3/snapshot/testdata/corrupted_backup.db" is generated on a little-endian machine? Is it possible to generate a similar test data file in big_endian?

Yes. I generated the test file on my local machine which is little endian.

> Further, are there any potential problem in "Etcd" on s390x if only this test case is failed because of the test data?

If this is the only failing test and it is due to different endian, I do not think it should worry you. Is this test blocking you? Is there a way to skip this test for big endian architecture?
