### ISSUE TITLE
error initializing the store: etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by nandeeshb09** [etcd-io/etcd#11309]
Hi Team,

Please help to solve this, we are using sensu 5.12 with etcd cluster -latest image.

all of sudden we are getting this below error.

"error":"error initializing the store: etcdserver: mvcc: database space exceeded","level":"fatal","msg":"error executing sensu-backend","time":"2019-10-30T09:27:15Z"Unexpected Error: "500" 

I tried to defrag in all the etcd nodes ,but still getting this error, please help on this.

**Comment by jingyih** [comment]
Please refer to https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota

After defrag, do `ETCDCTL_API=3 etcdctl alarm disarm`. It is a cluster wide operation, removing NOSPACE alarm on all nodes.

**Comment by nandeeshb09** [comment]
@jingyih  Thank You.
