### ISSUE TITLE
Warning "retry stream intercept" on etcd snapshot

### ISSUE THREAD

**Issue by ghouscht** [etcd-io/etcd#11310]
We regularly save snapshots of our etcd clusters (used for k8s) and since upgrading to version `3.3.15` from `3.3.11` we see this warning on each snapshot save:

```bash
#> etcdctl snapshot save /tmp/snapshot
{"level":"warn","ts":"2019-10-30T12:49:06.832+0100","caller":"clientv3/retry_interceptor.go:116","msg":"retry stream intercept"}
Snapshot saved at /tmp/snapshot
```
Warning comes from: https://github.com/etcd-io/etcd/blob/84e2788c2e41937a851ceb9f365b8e3933b59083/clientv3/retry_interceptor.go#L116
and it looks like this log statement should be inside the `if err != nil` block, right?

# etcd version info
```bash
#> etcdctl version
etcdctl version: 3.3.15
API version: 3.3
```

```bash
#> etcdctl endpoint status
https://e1-k8s-mlsu101.pnet.ch:7002, a9cc9b4fc64d2817, 3.3.15, 29 MB, true, 669, 89819156
https://e1-k8s-mlsu102.pnet.ch:7002, 3ee0c7069a03b0b2, 3.3.15, 29 MB, false, 669, 89819156
https://e1-k8s-mlsu103.pnet.ch:7002, 414e1bec2e2adf47, 3.3.15, 29 MB, false, 669, 89819156
```

**Comment by jingyih** [comment]
cc @gyuho @jpbetz 
Should the warning appear only when `err != nil`? Or maybe change log level to `debug`?

**Comment by gyuho** [comment]
@jingyih Let me take a look
