### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by Cjen1** [etcd-io/etcd#11311]
I'm running an etcd cluster on top of a mininet network.

I am trying to connect to the cluster from various clientv3's around the network. The issue is that I am getting no route to host on each of these clients.

Running etcdctl from the points where the clients are, is successful for cluster-health, put and get.

The etcdctl request is 
```
ETCDCTL_API=3 etcdctl --endpoints http://10.0.0.31:2379,http://10.0.0.32:2379,http://10.0.0.33:2379 get test
```

The client is getting created:
```
        cli, err := clientv3.New(clientv3.Config{
                Endpoints:              []string{"http://10.0.0.31:2379","http://10.0.0.32:2379","http://10.0.0.33:2379"},
                DialTimeout:            dialTimeout,
                DialKeepAliveTime:      dialTimeout/2,
                DialKeepAliveTimeout:   dialTimeout*2,
                AutoSyncInterval:       dialTimeout/2,
        })
        defer cli.Close()
        check(err)
```
From reading the docs I believe that these should be equivalent, however evidently there is some difference causing the error.

Each member of the cluster is getting started with:
```
etcd --data-dir=etcd_h1 --name etcd_h1 --initial-advertise-peer-urls http://10.0.0.31:2380 --listen-peer-urls http://10.0.0.31:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://10.0.0.31:2379 --initial-cluster etcd_h1=http://10.0.0.31:2380,etcd_h2=http://10.0.0.32:2380,etcd_h3=http://10.0.0.33:2380 --initial-cluster-token urop_cluster --initial-cluster-state new
```

And the version of etcd is:
```
etcd Version: 3.3.8
Git SHA: 33245c6b5
Go Version: go1.9.7
Go OS/Arch: linux/amd64
```

and for etcdctl:
```
etcdctl version: 3.3.8
API version: 2
```

Any help on this would be greatly appreciated!

**Comment by xiang90** [comment]
what is the problem? can you tell us how to reproduce and also paste the error message to github?

**Comment by Cjen1** [comment]
Hi this issue is on the mininet end of thing. Sorry for the bother.
