### ISSUE TITLE
Procfile Issue when running Goreman after "Getting started" in README

### ISSUE THREAD

**Issue by el10savio** [etcd-io/etcd#11329]
Found an issue with the Procfiles used after setting up etcd in the [Getting started](https://github.com/etcd-io/etcd#running-etcd) section.

After moving the release to /usr/local/bin as indicated in the command below:

`mv /tmp/etcd-download-test/etcd /usr/local/bin/`

Which successfully adds etcd to bin so that we can run `etcd` via the command line. Now, there comes an issue with Goreman not initiating the etcd cluster as the Procfile indicates  /bin/etcd and not /usr/local/bin [(as indicated here)](https://github.com/etcd-io/etcd/blob/edd011c6d1f8b9c80d22a2c4c78b81fce3861437/Procfile#L2) The following error then gets logged out:

`19:26:46 etcd1 | /bin/sh: 1: bin/etcd: not found`

The same happens for Procfile.learner also. A solution I have found is to then modify the Procfile & Procfile.learner by replacing /bin/etcd to /usr/local/bin/etcd

Is this modification alright to get Goreman running easily or is there a possibility that the path to where the etcd release gets moved to gets changed from /usr/local/bin to /bin?

**Comment by jingyih** [comment]
They are example files. Please feel free to customize them based on where the etcd binary is located.

**Comment by spzala** [comment]
Current instructions seems using master branch. If you are thinking to modify instruction with a PR, I think it's good enough to leave instructions as such and add a comment in both files that use etcd binary location of your env as @jingyih mentioned.

**Comment by el10savio** [comment]
Thanks for reaching out. 

Yes, this is true. I think indicating to change the etcd location in the Procfiles if it is not in /bin/etcd as comments is a good option. Can I add comments into Procfile & Procfile.learner indicating the above and create a PR?

**Comment by spzala** [comment]
Sure, that sounds good. Thank you!
