### ISSUE TITLE
leader transferring should abort if the target is demoted

### ISSUE THREAD

**Issue by hicqu** [etcd-io/etcd#11326]
The relative code is https://github.com/etcd-io/etcd/blob/master/raft/raft.go#L1570.

We can know in the current implementation, leader transferring will abort after the target is not in the progress list.

However, if the target is demoted from voter to learner, I guess the leader transferring needs also to abort, but seems it's not covered in the current implementation.

Suppose that the configuration is transmuting from `voters: [1, 2, 3]` to `voters: [1, 2], learners: [3]`, and the leadership is transferring from 1 to 3. After the peer enters joint, the leader transferring won't abort because the target is still in progress. And then after the peer leaves joint, the leader transferring sitll won't abort because of the same reason.

I'm not sure my guess is correct. Could you take a look to check it? @tbg . If you also can't make sure that it's correct or not, I can write some test cases to test it.

**Comment by hicqu** [comment]
Could you take a look? @tbg thanks!

**Comment by tbg** [comment]
Thanks @hicqu, I think that's spot on! Mind sending a fix?

**Comment by hicqu** [comment]
Thank you! It's my plesure to send a PR to fix this!
