### ISSUE TITLE
A small mistake that append object to a new allocated slice with size

### ISSUE THREAD

**Issue by lijianwh** [etcd-io/etcd#11320]
I found a small mistake here: https://github.com/etcd-io/etcd/blob/bbe1e78e6242a57d54c4b96d8c49ea1e094c3cbb/etcdserver/corrupt.go#L316

```go
mbs := s.cluster.Members()
	pss := make([]peerHashKVResp, len(mbs))
	for _, m := range mbs {
		if m.ID == s.ID() {
			continue
		}
		pss = append(pss, peerHashKVResp{id: m.ID, eps: m.PeerURLs})
	}
```
pss is a new slice with size len(mbs) and append to this slice make the [0:len(mbs)-1] elements are empty and useless. `pss := make([]peerHashKVResp, len(mbs))` should be `pss := make([]peerHashKVResp, 0, len(mbs))`

**Comment by gyuho** [comment]
This is a bug...

Can you help fix?

**Comment by lijianwh** [comment]
sure, I will raise a PR to fix it.
