### ISSUE TITLE
Changing MaxCallRecvMsgSize for gRPC-gateway

### ISSUE THREAD

**Issue by pjz** [etcd-io/etcd#11327]
Hi! I'm currently using etcd via etc3-py which uses the JSON/grpc gateway.  I ran into the size limit:
```
result = await self.db.range(key_prefix, prefix=True, keys_only=True)
File "/usr/local/lib/python3.7/dist-packages/etcd3/aio_client.py", line 32, in __modelize
await self.client._raise_for_status(self._resp)
File "/usr/local/lib/python3.7/dist-packages/etcd3/aio_client.py", line 233, in _raise_for_status
raise get_client_error(error, code, status, resp)
etcd3.errors.go_etcd_rpctypes_error.ErrUnknownError: <ErrUnknownError error:'grpc: received message larger than max (14757329 vs. 4194304)', code:8>
```
and so am looking to figure out how to up the limit from the default 4MB.   I can find plenty of docs on how to increase MaxCallRecvMsgSize for the golang client, but I can't seem to find a way to adjust it for the gateway.  Am I missing something?

**Comment by bochencwx** [comment]
Hello, I have encountered the same problem with you using JSON/grpc gateway. How did you solve this problem finally?

**Comment by pjz** [comment]
I rewrote the code to page responses.  If you're using etcd3-py, my workaround is in the code on https://github.com/Revolution1/etcd3-py/issues/113 .  Hope this helps!

**Comment by bochencwx** [comment]
> I rewrote the code to page responses. If you're using etcd3-py, my workaround is in the code on [Revolution1/etcd3-py#113](https://github.com/Revolution1/etcd3-py/issues/113) . Hope this helps!

Thanks for your advice! According to the ideas you provided, I probably have a solution to solve my needs. But I still think page-responses is too cumbersome. I will try to find a easy way to set the upper limit directly, and if there is no other way, I will try your method. Thank you again for your reply.
