### ISSUE TITLE
can't use etcd by go mod?

### ISSUE THREAD

**Issue by smallnest** [etcd-io/etcd#11336]
Go version: 1.13

If I download etcd by go mod, it shows an error:

```sh
➜  protocol git:(master) ✗ go get -u -v github.com/coreos/etcd@latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sys latest
go: finding github.com/coreos/pkg latest
go: finding golang.org/x/crypto latest
go: finding github.com/golang/groupcache latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/lint latest
go: finding google.golang.org/genproto latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/coreos/go-systemd latest
go: finding golang.org/x/time latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding go.uber.org/tools latest
go: finding github.com/xiang90/probing latest
build github.com/coreos/etcd: cannot load google.golang.org/grpc/resolver/dns: module google.golang.org/grpc@latest (v1.25.0) found, but does not contain package google.golang.org/grpc/resolver/dns
```

The package `google.golang.org/grpc/resolver/dns` has becomed "internal" and etcd has use its own the package in vendor, but if I use go module or imported etcd in my go.mod, an error was thrown and the operation failed.

**Comment by kaisawind** [comment]
[google.golang.org/grpc/internal/resolver/dns](https://godoc.org/google.golang.org/grpc/internal/resolver/dns)
[google.golang.org/grpc/internal/resolver/passthroug](https://godoc.org/google.golang.org/grpc/internal/resolver/passthrough)

**Comment by owend** [comment]
I ran into this same build issue today, it's due to the latest release of grpc moving that package. The build error can be worked around if the grpc 1.24.0 version is used. 

This ticket could probably use a better name, but the corresponding issue on the grpc side is here: https://github.com/grpc/grpc-go/issues/3157

The long term fix is that etcd probably shouldn't be using this package directly, the public interface is resolver.Get("dns")

**Comment by menghanl** [comment]
FYI, The moved packages will be added back in https://github.com/grpc/grpc-go/pull/3162. Those packages will be thin wrappers of the public APIs (e.g. `resolver.Get("dns")`). A minor release will be made for this change.

**Comment by dfawley** [comment]
> The long term fix is that etcd probably shouldn't be using this package directly, the public interface is resolver.Get("dns")

_If_ it's necessary to get a DNS resolver builder.  It's unclear why etcd is importing the DNS package, however, as this is unexpected - can anyone explain?

**Comment by philips** [comment]
I think this is fixed via https://github.com/etcd-io/etcd/pull/11823.

I am closing this under that assumption. Please correct me if I am wrong.
