### ISSUE TITLE
some questions  about the implementation of  intervalTree

### ISSUE THREAD

**Issue by liyue201** [etcd-io/etcd#11337]
https://github.com/etcd-io/etcd/blob/b852e37895e7ddd36816c0f4f76e281d50551cb3/pkg/adt/interval_tree.go#L237

i don't think  the implementation of intervalTree is good. why don't use go nil as  NIL leaf node. i have saw this issue  https://github.com/etcd-io/etcd/pull/10881#issue-295622324

i not  think the reason is go nil, but  this function  https://github.com/etcd-io/etcd/blob/b852e37895e7ddd36816c0f4f76e281d50551cb3/pkg/adt/interval_tree.go#L362   it does not supports nil parameter.

**Comment by spzala** [comment]
@liyue201 for code related changes/proposals, I would suggest to create PR for a better discussion and review. Hope makes sense. I am closing this issue but please feel free to create a PR or reopen this if you want. Thanks!
