### ISSUE TITLE
Release question: do we have an estimated date for v3.3.18?

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#11332]
@gyuho @jpbetz @hexfusion do we have an estimated date for v3.3.18?

**Comment by hexfusion** [comment]
@wenjiaswe I can look at cutting **v3.3.18** maybe this week.

**Comment by wenjiaswe** [comment]
Thanks @hexfusion !

**Comment by wenjiaswe** [comment]
@hexfusion friendly ping:)

**Comment by gyuho** [comment]
@wenjiaswe Have we backported all patched? If so, I can help.

**Comment by wenjiaswe** [comment]
Thanks @gyuho ! Let's wait for backport of https://github.com/etcd-io/etcd/pull/11374, I will ping you when we are ready:) 

cc @jingyih @YoyinZyc

**Comment by wenjiaswe** [comment]
https://github.com/etcd-io/etcd/pull/11394 merged, @gyuho please help to cut 3.3.18 release when you have time. Thanks!

**Comment by gyuho** [comment]
https://github.com/etcd-io/etcd/releases/tag/v3.3.18 has been released.

**Comment by wenjiaswe** [comment]
Thanks @gyuho !
