### ISSUE TITLE
etcdctl v3.3 "watch --prev-kv" not working

### ISSUE THREAD

**Issue by fhmily** [etcd-io/etcd#11343]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

With a brand new brew installed etcd on Macos X

`etcdctl version`
> etcdctl version: 3.3.13
> API version: 3.3

`etcdctl endpoint status`
> 127.0.0.1:2379, 8e9e05c52164694d, 3.3.13, 25 kB, true, 2, 8

put some values and then

`etcdctl watch --rev=1 foo`

> PUT
> foo
> bar1
> PUT
> foo
> bar

but the following cmd just stuck there and give no outputs
`etcdctl watch --prev-kv foo`

**Comment by spzala** [comment]
@fhmily have you put anything after starting `etcdctl watch --prev-kv foo`? It seems working fine with my master copy. 

```
./bin/etcdctl watch --prev-kv foo3
PUT
foo2
bar2

```

**Comment by spzala** [comment]
From https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/interacting_v3.md#watch-historical-changes-of-keys 

```Here is an example to watch only from the last historical change:
watch for changes on key `foo` and return last revision value along with modified value
$ etcdctl watch --prev-kv foo
in another terminal: etcdctl put foo bar_latest
PUT
foo         # key
bar_new     # last value of foo key before modification
foo         # key
bar_latest  # value of foo key after modification
```

**Comment by fhmily** [comment]
> @fhmily have you put anything after starting `etcdctl watch --prev-kv foo`? It seems working fine with my master copy.
> 
> ```
> ./bin/etcdctl watch --prev-kv foo3
> PUT
> foo2
> bar2
> ```

Yes, it works if I invoke a new value input from another process. But it confuse me that what is the difference between this and a normal watch command?

And moreover, if this command works for listening on future Puts, why it is listed under "Watch historical changes of keys" chapter. What is the scenario for using this option with Watch?

**Comment by spzala** [comment]
I am not sure about the use case related to creation of the --prev-kv option but that's the usage and also how it's clearly documented. The difference is as the usage says that it gives you the previous key-value pair along with normal watch.

**Comment by xiang90** [comment]
Previous kv returns the value that the watched operation overwrote. it is useful when some cleaning up needs to be done for an old overwritten value.

**Comment by spzala** [comment]
Thanks @xiang90
