### ISSUE TITLE
cannot find module providing package github.com/coreos/go-systemd/journal

### ISSUE THREAD

**Issue by woshitang1990** [etcd-io/etcd#11345]
when i use go get -v go.etcd.io/etcd/clientv3, it shows cannot find module providing package github.com/coreos/go-systemd/journal

who know how to fix it?

**Comment by lummie** [comment]
@woshitang1990 did you find a fix?

**Comment by woshitang1990** [comment]
first download github.com/go-systemd/journal to local, then use go module replace to make the package point to local path.
example:  
replace github.com/coreos/go-systemd/journal => /Users/miketang/go/src/github.com/go-systemd/journal

**Comment by woshitang1990** [comment]
> @woshitang1990 did you find a fix?
first download github.com/go-systemd/journal to local, then use go module replace to make the package point to local path.
example:
replace github.com/coreos/go-systemd/journal => /Users/miketang/go/src/github.com/go-systemd/journal

**Comment by Clivern** [comment]
i think this is related https://github.com/coreos/go-systemd/issues/325

**Comment by dselans** [comment]
> > @woshitang1990 did you find a fix?
> > first download github.com/go-systemd/journal to local, then use go module replace to make the package point to local path.
> > example:
> > replace github.com/coreos/go-systemd/journal => /Users/miketang/go/src/github.com/go-systemd/journal

Thanks for posting this @woshitang1990. This is what I did:

```
$ mkdir -p $GOPATH/src/github.com/coreos/go-systemd/
$ git clone git@github.com:coreos/go-systemd.git $GOPATH/src/github.com/coreos/go-systemd/
$ cd $myproject
$ go mod edit -replace github.com/coreos/go-systemd/=/Users/dselans/Code/go/src/github.com/coreos/go-systemd
$ go get go.etcd.io/etcd/clientv3
```

Followed by prompt vendoring...

**Comment by MilosSimic** [comment]
> > @woshitang1990 did you find a fix?
> > first download github.com/go-systemd/journal to local, then use go module replace to make the package point to local path.
> > example:
> > replace github.com/coreos/go-systemd/journal => /Users/miketang/go/src/github.com/go-systemd/journal

Thanks for posting  @woshitang1990 and @dselans
i followed both of your answers and kinda combine them to work for me. so steps:
1) download/clone github.com/coreos/go-systemd to your local go/src package
2) inside that folder there should be journal folder, go inside and run go mod init
3) goto your project and run go mod init as well
4) open go.mod and below module line add this lie: replace github.com/coreos/go-systemd/journal => ../../coreos/go-systemd/journal or use absolute path as @dselans did.
5) install other libs and run go build

**Comment by gogrisohil** [comment]
I am still getting this error with the latest release version 3.3.18. 
```
go get -v go.etcd.io/etcd/clientv3 
go: finding github.com/coreos/go-systemd/journal latest
go: finding github.com/coreos/go-systemd latest
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/pkg/logutil/zap_journal.go:29:2: no matching versions for query "latest"
```

**Comment by shaodan** [comment]
I fixed it  by add a line to my go.mod:

`replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0`

refer to https://github.com/coreos/go-systemd/issues/321

**Comment by gun1x** [comment]
There are already multiple issues opened on github for this problem. Also, fixes written above don't work for me any more.

Are there any plans to commit a permanent fix?

**Comment by chrboe** [comment]
I cannot currently find any way to import the etcd client in a Go project, all suggestions above are broken at time of writing.
Why has there been no reaction to this whatsoever for several months?

**Comment by gun1x** [comment]
> I cannot currently find any way to import the etcd client in a Go project, all suggestions above are broken at time of writing.
> Why has there been no reaction to this whatsoever for several months?

try adding this to `go.mod`:
```
require google.golang.org/grpc v1.26.0
replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
```

I was as triggered as you are. I guess they probably didn't have time to keep up with upgrades happening on all libraries. I also think we don't really have the right to QQ on github, since we are not fixing the issue either, though we are all go devs and we all have access to the source code. :rofl:

**Comment by jingyih** [comment]
FYI, dependency of "github.com/coreos/go-systemd/journal" is removed in etcd codebase as part of #11426 (the specific commit is https://github.com/etcd-io/etcd/commit/09304a4d82635678fab68923cf61bdc792ec7679).

**Comment by gogrisohil** [comment]
The reason why this came up is due to go modules. It would be great if there would be a release for the same which would eventually work with go modules rather than going off of a commit.

**Comment by faith2god** [comment]
> require google.golang.org/grpc v1.26.0
> replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0

thanks a lot! it works on my machine: ubuntu 14.04

**Comment by g00nix** [comment]
> thanks a lot! it works on my machine: ubuntu 14.04

why don't you upgrade?
