### ISSUE TITLE
etcd db's size continually increase

### ISSUE THREAD

**Issue by lijianwh** [etcd-io/etcd#11352]
Hi, 

I found my etcd cluster's db size continually increase by the prometheus monitor. I just store 12 small key-value pairs in etcd and their size should be less than 100kb.

And I also use etcd's election and lease API. Is there any easy way to profile the data store in bolt db? Does etcd provides any tool to check why db is so large with only 12 items. Thanks.

OS: Linux version 3.10.0-957.el7.x86_64
ETCD：etcdctl version: 3.3.11 API version: 3.3

![image](https://user-images.githubusercontent.com/10823800/68760655-52d28c00-064d-11ea-9523-516c2ff589b6.png)

**Comment by jingyih** [comment]
As an experiment, you can turn on "--debug" flag which will print out per request debugging information. I think the user value is redacted but user key is printed in the debugging info.

This is not traversing the key space in data store. But it can tell which key is being added or updated.

**Comment by xiang90** [comment]
do you keep on updating these 12 items?

**Comment by lijianwh** [comment]
@jingyih thanks,  I will try to use --debug flag to check the detail information. By the way, I use `etcdctl --endpoints=$ENDPOINTS get '\0' --from-key=true` to scan out all the key-value, does this right? 

@xiang90 I use etcd for service discovery and these 12 items are address info registered by 6 nodes with lease, the nodes also use election API for leader role campaign. I think the nodes will only renew the address info's lease but not update the items. Does etcd has any metrics can show what kind of data store in db, key-value, lease data or distributed lock data? 

thanks for your help.

**Comment by jingyih** [comment]
Use `ETCDCTL_API=3 etcdctl get --prefix ""` to get all keys. Then for individual key, use `ETCDCTL_API=3 etcdctl get <key> -w json` which will print the version of that key. It is basically the number of updates happened to that key since last time it was created.

**Comment by lijianwh** [comment]
@jingyih I use `ETCDCTL_API=3 etcdctl get --prefix ""` to get all keys and there is only 12 keys. That meet what I found before. Below is one of the item which wipe out sensitive information. I find the create_revision is quite large, in usual case, the etcd will compact the reversion, the db's size should not be so large， right?
```json



{"header":{"cluster_id":16119643827339558547,"member_id":2970753422962603549,"revision":4463554,"raft_term":145},"kvs":[{"key":"xxxxxxxx,"create_revision":597918,"mod_revision":3901305,"version":2,"value":"xxxxxxxxx","lease":8124612758787032422}],"count":1}
```
The command of my etcd cluster.
```
${WORK_PATH}/etcd \
--data-dir=data.etcd \
--name ${THIS_NAME} \
--initial-advertise-peer-urls http://${THIS_IP}:2380 \
--listen-peer-urls http://${THIS_IP}:2380 \
--advertise-client-urls http://${THIS_IP}:2379 \
--listen-client-urls http://${THIS_IP}:2379 \
--initial-cluster ${CLUSTER} \
--initial-cluster-state ${CLUSTER_STATE} \
--initial-cluster-token ${TOKEN}
```

**Comment by jingyih** [comment]
First of all, the etcd store revision in the response is 4463554, that means the store has been updated about 4463553 times. If there is no compaction, the store keeps all history data.

Looks like you did not enable any automatic compaction on server side. Does your client periodically issue compaction request to server?

To free the space, you can manually run `ETCDCTL_API=3 etcdctl compact <rev>`, just use a recent rev, for example 4463000. This should make the server delete most of the history data. Then you might need to do `ETCDCTL_API=3 etcdctl defrag` to make the internally freed space in etcd back to file system.

The following 2 metrics could be helpful:
`etcd_mvcc_db_total_size_in_bytes`, this should match your db file size
`etcd_mvcc_db_total_size_in_use_in_bytes`, this is what is actually needed. If you do defrag, the resulting db file size should be close to this number.

**Comment by lijianwh** [comment]
Great ! it works.

BTW, is there any flag that I can set to make the etcd delete history data and free space automatically. My cluster seems need I do these actions manually.

**Comment by jingyih** [comment]
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--auto-compaction-retention
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--auto-compaction-mode

**Comment by xiang90** [comment]
i am closing this issue since i believe compaction should solve the problem.
