### ISSUE TITLE
Replace capnslog with logrus

### ISSUE THREAD

**Issue by saschagrunert** [etcd-io/etcd#11351]
To update the package to go-systemd v22.0.0 we would need to get rid of the capnslog implementation. This blocks the update in other projects as well, like Kubernetes. (see https://github.com/kubernetes/kubernetes/pull/85097)

I know that it is already planned to replace capnslog with logrus, so I'd like to suggest in moving forward with this plan now. Is there anything to consider for the implementation? I saw that you have a deprecation policy, right?

**Comment by jingyih** [comment]
Currently etcd supports both capnslog and zap logger. I believe capnslog will be deprecated in the next minor release 3.5.

**Comment by saschagrunert** [comment]
Hey @spzala 👋, do you have any idea how to move forward with this issue? Is the implementation already ongoing or do you still need assistance? :)

**Comment by jingyih** [comment]
Hi @saschagrunert, I am currently working on removing capnslog from etcd. Should be able to sent out a PR in the next few days.

**Comment by saschagrunert** [comment]
Awesome @jingyih, thank you for the update. :)

**Comment by jingyih** [comment]
@saschagrunert FYI, removing of capnslog is tracked here #11426. I am trying to get all the changes ready by the end of this week.

**Comment by saschagrunert** [comment]
> @saschagrunert FYI, removing of capnslog is tracked here #11426. I am trying to get all the changes ready by the end of this week.

Awesome, thank you for the heads-up :green_heart:

**Comment by jingyih** [comment]
@saschagrunert FYI, #11426 is done. `capnslog` is removed from etcd codebase.

**Comment by saschagrunert** [comment]
Cool, thanks! Do you have any timeline for the next release to be cut?

**Comment by jingyih** [comment]
I am not aware of any timeline. I would prefer to have v3.5 released mid this year.

**Comment by kevinburkemeter** [comment]
Hi, it's 2021 and I don't believe 3.5 is released yet. Any chance you can cut a release?

I am trying to update the etcd version that Terraform relies on, but the capnslog import hijacks the Terraform log.SetOutput call which is causing the build to fail.
