### ISSUE TITLE
Proposal: Introduce Follower Replication in Raft

### ISSUE THREAD

**Issue by Fullstop000** [etcd-io/etcd#11357]
## Summary
In the origin raft protocol, a follower can only receive new raft logs and snapshots from the leader, which could be insufficient in some situations. For example, when a raft cluster is distributed in different data centers, log replication can is expensive due to the frequent cross-DC network transmission. In this case, internal follower-to-follower transfer in one data center can be far more efficient than the traditionally stipulated leader-to-follower transfer.

## Relate docs
https://github.com/tikv/rfcs/pull/33

**Comment by siddontang** [comment]
@Fullstop000 maybe it is better for us to paste the benchmark result here.

**Comment by siddontang** [comment]
Another benefit I think is to reduce the pressure of the leader when the leader has more followers or learners.

**Comment by xiang90** [comment]
This is an OK idea. Just need to justify the complexity from some benchmark results, ideally from practical experience/use cases.

**Comment by Fullstop000** [comment]
@xiang90 is it ok to add some extra fields in `Message` like below: 
```
message Message {
	optional MessageType type        = 1  [(gogoproto.nullable) = false];
	optional uint64      to          = 2  [(gogoproto.nullable) = false];
	optional uint64      from        = 3  [(gogoproto.nullable) = false];
	optional uint64      term        = 4  [(gogoproto.nullable) = false];
	optional uint64      logTerm     = 5  [(gogoproto.nullable) = false];
	optional uint64      index       = 6  [(gogoproto.nullable) = false];
	repeated Entry       entries     = 7  [(gogoproto.nullable) = false];
	optional uint64      commit      = 8  [(gogoproto.nullable) = false];
	optional Snapshot    snapshot    = 9  [(gogoproto.nullable) = false];
	optional bool        reject      = 10 [(gogoproto.nullable) = false];
	optional uint64      rejectHint  = 11 [(gogoproto.nullable) = false];
	optional bytes       context     = 12;

	repeated uint64  members = 13 [(gogoproto.nullable) = false];
	optional uint64  group_id = 14 [(gogoproto.nullable) = false];
	optional bool is_broadcasting = 15 [(gogoproto.nullable) = false];
	optional uint64 from_delegate = 16 [(gogoproto.nullable) = false];
}
```
Not all of new fields will be used in different message types.
