### ISSUE TITLE
CHANGELOG-3.4 missing entries

### ISSUE THREAD

**Issue by bootc** [etcd-io/etcd#11353]
The [CHANGELOG-3.4.md](https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md) file is missing an entry for the [3.4.3](https://github.com/etcd-io/etcd/releases/tag/v3.4.3) release and shows [3.4.2](https://github.com/etcd-io/etcd/releases/tag/v3.4.2) as unreleased.

**Comment by spzala** [comment]
@bootc thanks for reporting. I will update it.
