### ISSUE TITLE
some keys is not deleted when the bound lease expires even after the leaser revoked.

### ISSUE THREAD

**Issue by timestee** [etcd-io/etcd#11369]
some keys is not deleted when the bound lease expires even after the leaser revoked.
```
etcd -version
etcd Version: 3.4.1
Git SHA: a14579fbf
Go Version: go1.12.9
Go OS/Arch: linux/amd64
```

**Comment by hexfusion** [comment]
Thanks for the report. Could you also confirm client version? In general a simple reproducible example would help us understand “some keys not deleted”. This to me means some keys are and some are not. Could you please clarify?

**Comment by timestee** [comment]
client version : go.etcd.io/etcd v3.3.13+incompatible
has tried update to latest version ,but lots madness things like: https://github.com/etcd-io/etcd/issues/10398 and `cannot use s.client (type *"go.etcd.io/etcd/clientv3".Client) as type *"github.com/coreos/etcd/clientv3".Client in argument to concurrency.NewSession`.

Just put tens of kvs with 30s ttl and enable leaser keepalive like this:
```golang
	keepAliveChan, err := s.client.KeepAlive(context.Background(), leaseId)
	if err != nil {
		log.Errorf(" etcdv3 lease id:%d keepalive with err:%s",leaseId, err.Error())
		return
	}
	for {
		select {
		case <-s.done:
			return
		case ch := <-li.keepAliveChan:
			if ch == nil {
				//the lease expired, all key under this lease will lost
				return
			}
		}
	}
```
Befor exit the process, revoke the leaser from another goroutine, is it ok? Should i stop the keepalive operation before revoke the leaser?
```golang
_, _ = s.client.Revoke(context.Background(), leaseId)
```

Most of the keys under the leaser have been deleted，but only one or two have not been deleted.
I am trying to reproduce through testcase.

**Comment by timestee** [comment]
sorry, seems its a mistake, will keep on the observation, close now.
