### ISSUE TITLE
The picture in doc page has gone

### ISSUE THREAD

**Issue by foxman209** [etcd-io/etcd#11366]
## The pictures of the following two pages are gone
https://etcd.io/docs/v3.4.0/learning/design-client/
https://etcd.io/docs/v3.4.0/learning/design-learner/

**Comment by spzala** [comment]
@foxman209 thanks for reporting. 
There is a related PR in the doc repo - https://github.com/etcd-io/website/issues/48 
The GH page shows images fine https://github.com/etcd-io/website/blob/master/content/docs/v3.4.0/learning/design-learner.md 
I am closing this issue in favor of the issue already created on the Website repo. Thanks!
