### ISSUE TITLE
clientv3/concurrency: Mutex isn't locally thread safe

### ISSUE THREAD

**Issue by afking** [etcd-io/etcd#11360]
Creating a single mutex and locking both can race as each Lock mutates the *Mutex. E.g: 
```
m := concurrency.NewMutex(s1, "/my-lock/")
go m.Lock(context.TODO())
go m.Lock(context.TODO()) // race
```
https://github.com/etcd-io/etcd/blob/master/clientv3/concurrency/mutex.go#L97

The API for concurrency.Mutex is very similar to sync.Mutex but the local behaviour is very different. Should there be a local lock so the go routines would block each other?

**Comment by xiang90** [comment]
can you help to make that func thread-safe? thanks.

**Comment by vimalk78** [comment]
@afking why do you think `Mutex.Lock` is '"thread" unsafe?

better to list the behavior you were expecting and what you observed.
