### ISSUE TITLE
etc compaction when no keys exist results in inconsistent watch and get

### ISSUE THREAD

**Issue by tagarwal** [etcd-io/etcd#11370]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
etcd version 3.3.2
Try etcd compaction when no keys are entered
`etcdctl --endpoints=localhost:2379 get --prefix ""` (returns nothing which is correct as no keys are entered)
`etcdctl --endpoints=localhost:2379 compact 1`
compacted revision 1
We have an auto compacter policy hence this issue

Put a key
`etcdctl --endpoints=localhost:2379 put foo bar`
OK

Now when we try to watch on the version 1, the expectation is that it should throw an error saying the version is already compacted but 
`etcdctl --endpoints=localhost:2379 watch --prefix --rev 1 foo`
PUT
foo
bar

And try to get 
`etcdctl --endpoints=localhost:2379 get --prefix --rev 1 foo`
It returns nothing

Attached is the etcd server log 
[etcdsrv.log](https://github.com/etcd-io/etcd/files/3861793/etcdsrv.log)

What is the expected behavior in this case

**Comment by jingyih** [comment]
https://github.com/etcd-io/etcd/blob/b373cb905135de13097beeee2d3cf89a8d17ed00/clientv3/kv.go#L53-L54
"Compact compacts etcd KV history before the given rev." So  `--rev 1` is valid after `etcdctl compact 1`.

After compaction, `etcdctl put foo bar` writes key foo at rev x (x > 1).

The result of `watch` and `get` in your post is expected.
