### ISSUE TITLE
make-mirror, not working with username:password authentication

### ISSUE THREAD

**Issue by schlitzered** [etcd-io/etcd#11383]
i am running two test clusters of etcd 3.4.3. with password authentication enabled, and client-cert auth disabled.

lb address is:
https://etcd-a-svc.example.com:2379
member:
etcd-a-1.example.com:2379
etcd-a-2.example.com:2379
etcd-a-3.example.com:2379

https://etcd-b-svc.example.com:2379
member:
etcd-b-1.example.com:2379
etcd-b-2.example.com:2379
etcd-b-3.example.com:2379

both clusters have the user "root" with the password "root_password" enabled, and the "root" role attached.

i like to mirror a prefixed from cluster a to cluster b like this:

```
etcdctl --user root:root_password --endpoints=https://etcd-a-svc.example.com:2379 make-mirror https://etcd-b-svc.example.com:2379 --dest-prefix=/cluster_a --prefix=/cluster_a
```

but i get this error message:

```
{"level":"warn","ts":"2019-11-22T10:06:02.680-0500","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-50156780-f3e6-4237-bb1b-b78a6cf6b068/etcd-a-svc.example.com:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
Error: etcdserver: user name is empty
```

i guess that the a option like "--dest-user" and "--dest-password" are missing, which would be needed to supply the credentials for the target etcd cluster?

there are only options for client cert auth, which i cannot support in my environment.

**Comment by jsok** [comment]
It appears that these options haven't been documented in https://github.com/etcd-io/etcd/blob/master/etcdctl/README.md#make-mirror-options-destination
