### ISSUE TITLE
about initial-cluster-state flag

### ISSUE THREAD

**Issue by cuiyuan** [etcd-io/etcd#11397]
This is more of a question than an issue; 

If an old node restart , --initial-cluster-state should be new or existing?
I tried, both can work, why?

And after cluster add new member ，when old node restart， --initial-cluster flag should add new member？

**Comment by WIZARD-CXY** [comment]
The old node does not depend on flags any more

**Comment by jingyih** [comment]
Correct. I assume 'old node' means there is existing data directory for the node. The flag is used in bootstrapping (static bootstrap, discovery-service bootstrap or runtime reconfiguration) a new member, and ignored when restarting an existing member.
