### ISSUE TITLE
Documentation does not show how to enable v2 in 3.4 via config file

### ISSUE THREAD

**Issue by joedborg** [etcd-io/etcd#11402]
I'm looking to enable API v2 on 3.4, but I'd like to do this via the config file rather than as a flag on the server binary.

https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md

Is it possible this way?

**Comment by jingyih** [comment]
I found a sample here:

https://github.com/etcd-io/etcd/blob/419ffb77ab4f0e263f23b5cba2b323502015fc75/etcd.conf.yml.sample#L72-L73

**Comment by jingyih** [comment]
Closing. Please reopen if there is follow up question.

**Comment by xsKaisx** [comment]
i followed this document and don't know how to enable v2, can someone help
https://computingforgeeks.com/setup-etcd-cluster-on-centos-debian-ubuntu/#comment-7605

**Comment by spzala** [comment]
https://github.com/etcd-io/etcd/tree/main/etcdctl also has this mentioned - `For the v2 API, make sure to set environment variable ETCDCTL_API=2. See also READMEv2.`
