### ISSUE TITLE
I have an error，I don't know how to solve it.please help.

### ISSUE THREAD

**Issue by helintongh** [etcd-io/etcd#11406]
src\github.com\coreos\etcd\clientv3\auth.go:135:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
src\github.com\coreos\etcd\clientv3\auth.go:140:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
src\github.com\coreos\etcd\clientv3\auth.go:145:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
src\github.com\coreos\etcd\clientv3\auth.go:150:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
src\github.com\coreos\etcd\clientv3\auth.go:155:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
src\github.com\coreos\etcd\clientv3\auth.go:160:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
src\github.com\coreos\etcd\clientv3\auth.go:165:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
src\github.com\coreos\etcd\clientv3\auth.go:165:106: too many errors

Compilation finished with exit code 2

**Comment by helintongh** [comment]
My golang version is 1.13.
grpc latest.
ubuntu 18.10 and windows 10.
I create a micro-service,source code is :
```
package main

import (
	"golang.org/x/net/context"
	pb "hello_micro/proto"
	"fmt"
	"log"
	"github.com/micro/go-micro"
)
//声明结构体
type Hello struct {

}

//实现接口方法
func (g *Hello)Info(ctx context.Context, req *pb.InfoRequest,rep *pb.InfoResponse) error {
	rep.Msg = "你好" + req.Username
	return nil
}

func main() {
	
	service := micro.NewService(
		
		micro.Name("hello"),

	)
	//2.init
	service.Init()
	//3.register
	err := pb.RegisterHelloHandler(service.Server(),new(Hello))
	if err != nil {
		fmt.Println(err)
	}
	//4.start
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```
I found a issues https://github.com/grpc/grpc-go/issues/3078.they say it's etcd's error.

**Comment by helintongh** [comment]
ubuntu 18.04  is not compatible with the mysql5.7.use mysql8.0 solve it

**Comment by kevin576** [comment]
I got this problem too.

**Comment by wangjian138** [comment]
I got this problem too.
