### ISSUE TITLE
Some  doubts about etcd new future learner

### ISSUE THREAD

**Issue by andyzheung** [etcd-io/etcd#11401]
I am interested in learner feature, but have some problem when I try to use it?

1、why does only one learner in the cluster?

2、why the cluster health instance etcd is less than quorum size, that I can't  promote the learner to a vote member?
When I use learner endponit:
![image](https://user-images.githubusercontent.com/22912347/69718228-c9d94b80-1148-11ea-9ae7-4900d12d3b9b.png)

or when I use that still health instance endpoint:
![image](https://user-images.githubusercontent.com/22912347/69718181-aa422300-1148-11ea-8871-0063ef197e1f.png)

**Comment by jingyih** [comment]
> 1、why does only one learner in the cluster?

Leaner is a new feature. We currently set the maximum of learners to be 1, to prevent leader from being potentially overloaded by newly added learners. This limit could be increased in the future when learner feature is more stable.

> 2、why the cluster health instance etcd is less than quorum size, that I can't promote the learner to a vote member?
Promoting learner to voting member is quorum operation.

**Comment by andyzheung** [comment]
> > 1、why does only one learner in the cluster?
> 
> Leaner is a new feature. We currently set the maximum of learners to be 1, to prevent leader from being potentially overloaded by newly added learners. This limit could be increased in the future when learner feature is more stable.
> 
> > 2、why the cluster health instance etcd is less than quorum size, that I can't promote the learner to a vote member?
> 
> Promoting learner to voting member is quorum operation.

Thank you for your reply.

About the second question, I have some case that I want to need use learner to backup for the cluster.Just like the following picture, we only have two nodes, that use only two instances, other two are learners, we want to when one node is down, that I can promote the other node learner to vote, so that qurum size still 2, 


![image](https://user-images.githubusercontent.com/22912347/69772659-88d64b00-11cb-11ea-86de-45f24f88b94c.png)

We want to solve the two node use case about etcd, but etcd is raft protocal, any other suggestion?

**Comment by jingyih** [comment]
If you need fault tolerance, the minimum voting member is 3. When one member is down, you can restart or replace that member. Running a cluster with 2 voting member does not provide better cluster availability as compared to a single member.

**Comment by andyzheung** [comment]
> If you need fault tolerance, the minimum voting member is 3. When one member is down, you can restart or replace that member. Running a cluster with 2 voting member does not provide better cluster availability as compared to a single member.

I want to solve the problem how to Running etcd in only two nodes. We have only two nodes in our use case.
That I see the learner can recieve the data from the leader,  and think it can treat as the data backup in the cluster, when I need to it become voter I will promote.I don't know if what I think can be Ok?

@jingyih

**Comment by jingyih** [comment]
If you want the cluster to make progress (meaning able to serve APIs that require quorum, such as linearizable read, member reconfiguration) in the case of 1 voting member is down, you need minimum 3 voting members. You can run 3 voting members on 2 nodes but this is not an ideal situation. If the node with 2 members is down, you lose 2 members all together.
