### ISSUE TITLE
In memory mode, etcd, etcd data dir directory mount to tmpfs. If the node is restarted and the cluster information is lost, how to rejoin the cluster

### ISSUE THREAD

**Issue by zhangschunfeng** [etcd-io/etcd#11410]
because  etcd cluster information lost and  ETCD_INITIAL_CLUSTER_STATE="new"  ,
Etcd generates a new member ID，The following error occurred
**member 58720b382fc5f0b7 has already been bootstrapped**
if not set   ETCD_INITIAL_CLUSTER_STATE="existing"， how to rejoin to etcd cluster.

**Comment by hexfusion** [comment]
Once the data-dir is lost the member is also lost. You will need to remove the member and then add again with Cluster API.

The durability of data-dir is important for healthy members.
