### ISSUE TITLE
How to get the list of available revisions after compacting

### ISSUE THREAD

**Issue by malbertone** [etcd-io/etcd#11422]
Hi,

we have:
etcdctl version: 3.2.18
API version: 3.2
we  have auto compacting set to 1 and we can see each 5 minutes in messages file the compacting taking place showing:
2019-12-04T16:40:01.128949+09:00 ktc4ocsspsme1-auxiliary-0 etcd: store.index: compact 19444596
2019-12-04T16:40:01.129228+09:00 ktc4ocsspsme1-auxiliary-0 etcd: finished scheduled compaction at 19444596 (took 510.743Âµs)

We can get the latest avaialble revision by querying the status of the nodes and assume the available revisions are between the last compacted one and the last available one, but is there any API to use in order to get that list explicitly printed out?

Thanks
Mike

**Comment by jingyih** [comment]
`/metrics` endpoint reports `etcd_debugging_mvcc_current_revision` and `etcd_debugging_mvcc_compact_revision`. The debugging prefix means they are newly added and are subject to change (not stable). They are available in 3.2.27+, 3.3.17+, 3.4.1+.

Technically, the HashKV API [1] returns the compact revision (and the response header includes current store revision). But itself could be a very expensive read, if the store size is large. So probably not an ideal solution to get the revisions.

[1] https://github.com/etcd-io/etcd/blob/9f81002a11b55c5f53b76b3c00b1e83529d0eaab/clientv3/maintenance.go#L58
