### ISSUE TITLE
Unsupported config params for older versions in docker release scripts

### ISSUE THREAD

**Issue by kaustubhmallik** [etcd-io/etcd#11423]
Hi,

I was just trying to set up a local etcd environment to play around, and it was failing saying `flag provided but not defined`.

etcd version: v3.3.18
system: mac OS Catalina, v 10.15.1
docker:
```Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
````
[docker script (release link)](https://github.com/etcd-io/etcd/releases/tag/v3.3.18)

Below is the script, which I just copied from the release link:

```
rm -rf /tmp/etcd-data.tmp && mkdir -p /tmp/etcd-data.tmp && \
  docker rmi gcr.io/etcd-development/etcd:v3.3.18 || true && \
  docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --mount type=bind,source=/tmp/etcd-data.tmp,destination=/etcd-data \
  --name etcd-gcr-v3.3.18 \
  gcr.io/etcd-development/etcd:v3.3.18 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://0.0.0.0:2379 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls http://0.0.0.0:2380 \
  --initial-cluster s1=http://0.0.0.0:2380 \
  --initial-cluster-token tkn \
  --initial-cluster-state new \
  --log-level info \
  --logger zap \
  --log-outputs stderr

docker exec etcd-gcr-v3.3.18 /bin/sh -c "/usr/local/bin/etcd --version"
docker exec etcd-gcr-v3.3.18 /bin/sh -c "/usr/local/bin/etcdctl version"
docker exec etcd-gcr-v3.3.18 /bin/sh -c "/usr/local/bin/etcdctl endpoint health"
docker exec etcd-gcr-v3.3.18 /bin/sh -c "/usr/local/bin/etcdctl put foo bar"
docker exec etcd-gcr-v3.3.18 /bin/sh -c "/usr/local/bin/etcdctl get foo"
```

And, finally below is the failing output (cropped for brevity):
<img width="1440" alt="Screenshot 2019-12-04 at 15 07 26" src="https://user-images.githubusercontent.com/4466799/70149528-93e81a00-16a8-11ea-81d4-f06e58ace981.png">

I got the reason behind it when I visited the [configuration README](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--logger). I guess accidentally someone just used the latest version docker script for older versions also, without checking if the arguments are actually supported for those versions too. Similarly, there are some other arguments also like **log-level**

I know it's a very small issue, and any non-beginner developer will easily fix it. But, just for the sake of perfect documentation, I guess it should be updated. If you want, I would love to provide a helping hand and fix it. Let me know if it's possible.

**Comment by heyuanchao** [comment]
```

flag provided but not defined: -log-level
usage: etcd [flags]
       start an etcd server

       etcd --version
       show the version of etcd

       etcd -h | --help
       show the help information about etcd

       etcd --config-file
       path to the server configuration file

       etcd gateway
       run the stateless pass-through etcd TCP connection forwarding proxy

       etcd grpc-proxy
       run the stateless etcd v3 gRPC L7 reverse proxy

```

**Comment by spzala** [comment]
@kaustubhmallik thanks and as you mentioned if you can provide a fix that would be great. /cc @gyuho

**Comment by kaustubhmallik** [comment]
@spzala thanks for reviewing it. I guess as release pages are not part of the codebase, it can only be edited by repo admins/maintainers. Please correct me, if I am wrong.

**Comment by spzala** [comment]
@kaustubhmallik yrw and thanks for reporting it. OK, no worries, I thought so but wasn't sure if you had any other thoughts. I would update it after having it discussed with @gyuho

**Comment by kaustubhmallik** [comment]
@spzala Love to help! 😃

**Comment by spzala** [comment]
@gyuho hi, when you get a chance, can you please take a look -- as discussed in this issue the `--logger` and `--log-level` options in v3.3.18 (I think from 3.3.14 onward) release Docker script are giving error and we should remove them because they were added starting 3.4. Thanks!
