### ISSUE TITLE
Some doubts about etcd linearizability description

### ISSUE THREAD

**Issue by cuiyuan** [etcd-io/etcd#11420]
In [linearizability](https://github.com/etcd-io/etcd/blob/master/Documentation/learning/api_guarantees.md#linearizability)

> For example, consider a client completing a write at time point 1 (t1). A client issuing a read at t2 (for t2 > t1) should receive a value at least as recent as the previous write, completed at t1. However, the read might actually complete only by t3. Linearizability guarantees the read returns the most current value. Without linearizability guarantee, the returned value, current at t2 when the read began, might be "stale" by t3 because a concurrent write might happen between t2 and t3.

I don't think ReadIndex can ensure return the value written between t2 and t3, it can only return the value written before t2

>As with all distributed systems, it is impossible for etcd to ensure strict consistency. etcd does not guarantee that it will return to a read the “most recent” value (as measured by a wall clock when a request is completed) available on any cluster member.

Can I understand strict consistency is what you said above as read between t2 and t3? 

>All API calls ensure sequential consistency, the strongest consistency guarantee available from distributed systems. 

If sequential consistency is the strongest, but etcd ensures linearizability , is this conflict?

**Comment by xiang90** [comment]
This part of the documentation has been modified and improved. I think it should resolve your questions.
