### ISSUE TITLE
Use zap as default logger

### ISSUE THREAD

**Issue by jingyih** [etcd-io/etcd#11426]
Let's make `--logger=zap --log-outputs=stderr` as default in current master branch, as currently this branch is for developing etcd 3.5.

TODO
- [x] Set zap as default logger. Remove capnslog logger option. Remove deprecated logging flags. (#11578)
- [ ] Remove capnslog everywhere in etcd code base.

**Comment by gyuho** [comment]
Yes. Also, let's deprecate `capnslog`... We've already highlighted this coming change in CHANGELOG. Can you work on this?

**Comment by YoyinZyc** [comment]
I can work on this.

**Comment by gyuho** [comment]
@YoyinZyc Thanks.

**Comment by jingyih** [comment]
Thanks @YoyinZyc 

So to clarify, besides changing the default logger to `zap`, we also want to remove `capnslog` entirely? @gyuho

**Comment by gyuho** [comment]
@jingyih Yes. Just remove `capnslog` and its dependencies :)
