### ISSUE TITLE
Scheduled compaction latency increase significantly after upgrading to 3.4.2

### ISSUE THREAD

**Issue by jfbai** [etcd-io/etcd#11421]
**ETCD version:**  3.4.2
**K8s version:** 1.14.4

I upgrade etcd server from 3.3.10 to 3.4.2 in the test k8s cluster, then I observed the compaction latency increased significantly about 15 times.

3.3.10

![image](https://user-images.githubusercontent.com/13513238/70124377-a4e85980-16af-11ea-93f7-730a01e51df8.png)

3.4.2

![image](https://user-images.githubusercontent.com/13513238/70124356-91d58980-16af-11ea-9bf4-a34717b60efd.png)

**Updates:**

> Reduced default compaction batch size from 10k revisions to 1k revisions to improve p99 latency during compactions and reduced wait between compactions from 100ms to 10ms.

Is it relevant to this change? I do observed the p99 (backend commit latency spike) is decreased in another large scale staging cluster (only one etcd member is upgraded.).

PS: the total compaction time is increased about 300ms on average.) observed in log.

![image](https://user-images.githubusercontent.com/13513238/70131922-1a5b2680-16be-11ea-97ac-263b8b3d55ae.png)

**Comment by jfbai** [comment]
I set `--experimental-compaction-batch-limit=10000`, then the total time decreases to 2ms.

**Comment by jingyih** [comment]
etcd 3.4 reduced compaction batch limit from 10k to 1k, so that the compaction is less intrusive to other workloads. As the result, it will take more batches to finish a scheduled compaction. It's not clear to me why it takes a much longer time to finish, because the wait time between batches were reduced from 100ms to 10ms.

**Comment by xiang90** [comment]
@jingyih 

I believe that the compaction can be finished in one batch before, which has to be put into 4 batches in 3.4. So there are 3 * 10 ms delays.

**Comment by xiang90** [comment]
> Is it relevant to this change? I do observed the p99 (backend commit latency spike) is decreased in another large scale staging cluster (only one etcd member is upgraded.).

yes. the smaller compaction size will improve the latency. 

> PS: the total compaction time is increased about 300ms on average.) observed in log.

i do not understand what does this mean.

**Comment by jingyih** [comment]
> @jingyih
> 
> I believe that the compaction can be finished in one batch before, which has to be put into 4 batches in 3.4. So there are 3 * 10 ms delays.

Thanks!

**Comment by jfbai** [comment]
@jingyih @xiang90 Thanks a lot.

> > PS: the total compaction time is increased about 300ms on average.) observed in log.
> 
> i do not understand what does this mean.

In one of out large scale cluster (4500+ nodes), there are 160k revisions being compacted every time and it will take 2.7s to finish in 3.3.10. After upgrading to 3.4.2, I observed the compaction takes about 3s to finish.

**Comment by xiang90** [comment]
> In one of out large scale cluster (4500+ nodes), there are 160k revisions being compacted every time and it will take 2.7s to finish in 3.3.10. After upgrading to 3.4.2, I observed the compaction takes about 3s to finish.

that is kind of expected. trading off larger batch size (thus higher throughput) for better p99 latency.

**Comment by jfbai** [comment]
> > In one of out large scale cluster (4500+ nodes), there are 160k revisions being compacted every time and it will take 2.7s to finish in 3.3.10. After upgrading to 3.4.2, I observed the compaction takes about 3s to finish.
> 
> that is kind of expected. trading off larger batch size (thus higher throughput) for better p99 latency.

Thanks for explanation :)
