### ISSUE TITLE
Python3 install etcd error 

### ISSUE THREAD

**Issue by forusforyou** [etcd-io/etcd#11436]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
 FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\zzz\\appdata\\local\\temp\\pip-install-64n0wku8\\etcd\\etcd\\resources\\requ
irements.txt'

**Comment by xiang90** [comment]
this has nothing to do with etcd I believe. etcd is a go program and has no dependency on python itself.
