### ISSUE TITLE
http Range problem

### ISSUE THREAD

**Issue by magicsupery** [etcd-io/etcd#11435]
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64

I use lua， so need to use the httpproxy with etcd.

After send a range request, the etcd response use chunk to return,
but the body json data is deviced to two parts as below:

 {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"253","raft_term":"19"},"kvs":[{"key":"MTAwMS8zMjUzL0dBTUU=","create_revision":"80","mod_r

 evision":"89","version":"10","value":"eyJlbnRpdGllcyI6W10sInR5cGUiOiJHQU1FIiwicG9ydCI6MzI1MywiaXAiOiIxMC4yNDYuNDQuMTM5In0=","lease":"7587842899566242611"},{"key":"MTAwMS81MjUzL0dBTUU=","create_revision":"232","mod_revision":"233","version":"2","value":"eyJwb3J0Ijo2MTAxLCJlbnRpdGllcyI6eyJSb2xlQ2VudGVyIjp7ImlkIjoiXe9E3ZyDiVisXHUwMDA2XCKvIn19LCJpcCI6IjEwLjEuNDQuMTM5In0=","lease":"7587842924476535363"},{"key":"MTAwMS81NDc4L0dBTUU="  etc...

=========================================================
I'm confused how to deal with it? how to make sure that i got all the json data?

**Comment by xiang90** [comment]
need more information. can you give the full HTTP response including metadata instead of just body?
