### ISSUE TITLE
benchmark: add file output option to benchmark tool

### ISSUE THREAD

**Issue by anson627** [etcd-io/etcd#11459]
Currently the benchmark tool outputs performance summary and details to console in human readable format, but the results cannot be parsed programmatically.

The proposal here is to add an option to output to a file specified by user input, potentially in JSON format.

This output file option opens the opportunity for automated analysis or data visualization.

This will also be prerequisite for #6002

**Comment by spzala** [comment]
Reopening as a related PR under review.
