### ISSUE TITLE
Cannot Identify the Restore Command in v3.3.15-0

### ISSUE THREAD

**Issue by knoxknot** [etcd-io/etcd#11464]
Please I can't seem to identify the snapshot restore command in the above named version. It also appears there is no more the snapshot command. How can I restore the etcd backup please.

**Comment by jingyih** [comment]
Did you try `ETCDCTL_API=3 etcdctl snapshot restore`?

**Comment by knoxknot** [comment]
@jingyih yes I did. It practical appeared the snapshot command it gone with this version. I rather used `etcdctl backup --data-dir /var/lib/etcd/ --backup-dir /tmp/clusterstate2019-12-17` to backup my cluster but couldn't find a way to restore.

**Comment by jingyih** [comment]
`etcdctl backup` is a v2 command. Which etcd version are you using?

**Comment by knoxknot** [comment]
@jingyih many thanks for the help. I sorted that out.

**Comment by jingyih** [comment]
Glad to hear that:)
