### ISSUE TITLE
mips64 etcd binary problem

### ISSUE THREAD

**Issue by xianxiaozhuge** [etcd-io/etcd#11468]
Hello, I want to submit etcd binary package based on MIPS64 architecture. What is the process?

**Comment by liupeng0518** [comment]
> Hello, I want to submit etcd binary package based on MIPS64 architecture. What is the process?

Just build it.

**Comment by xianxiaozhuge** [comment]
> > Hello, I want to submit etcd binary package based on MIPS64 architecture. What is the process?
> 
> Just build it.

I have compiled on the MIPS64 machine locally. What I want to ask is how to publish the binary package of MIPS64 to the release version of the community, so that I can download it directly from the release later.
