### ISSUE TITLE
go mod error, why etcd go mod is so hard to use

### ISSUE THREAD

**Issue by zjmnssy** [etcd-io/etcd#11472]
- go version
![image](https://user-images.githubusercontent.com/21244667/71306311-958c3e80-2419-11ea-8d78-290fcf6a2a98.png)
and go mod is on
- my problem 
i use etcd in my code like this:
![image](https://user-images.githubusercontent.com/21244667/71306332-c8cecd80-2419-11ea-9532-e7e103ecd014.png)
then the go mod auto add in go.mod file like this:
![image](https://user-images.githubusercontent.com/21244667/71306348-ec921380-2419-11ea-9796-f226356db764.png)
bug i want use etcd 3.4.3, not the go mod auto give to me, so i use cmd like 
![image](https://user-images.githubusercontent.com/21244667/71332597-bebfe280-2571-11ea-880f-03d351609bbe.png)

 i don't know how to fix

**Comment by zjmnssy** [comment]
@obsider thx, i use this:  
require go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738  
it not effect, will be modify to 3.3.18 by go mod auto,but i use like this:  
replace go.etcd.io/etcd => go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738  
it is ok, but i think this is not in accordance with the specifications. Is there a schedule for repairing this problem?

**Comment by obsider** [comment]
Hi @zjmnssy ,

The etcd team is aware of it. I just created this tool to help until they find a good solution. I'll add the replace into the README, thanks !
