### ISSUE TITLE
All images are broken on https://etcd.io/docs/v3.4.0/learning/design-learner/ page

### ISSUE THREAD

**Issue by arianvp** [etcd-io/etcd#11497]
All the diagrams on https://etcd.io/docs/v3.4.0/learning/design-learner/ return 404.

**Comment by spzala** [comment]
@arianvp thanks for reporting but this is a known issue and fix is underway. Also, this is an issue with the https://github.com/etcd-io/website repo. There are multiple dups like https://github.com/etcd-io/website/issues/48 so I am closing this one. Thanks!

**Comment by arianvp** [comment]
Ah thanks! :)
