### ISSUE TITLE
etcd stuck in voting loop when second peer is not available

### ISSUE THREAD

**Issue by non7top** [etcd-io/etcd#11500]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
version 3.4.3

I was trying to add a second control plane to kubernetes, after successfully running the join command, the new (second) plane got hosed due to diskspace issue and some pods didn't get deployed correctly, including second etcd pod. After that the only remaining etcd instance started a vote for a master which ended up in endless loop. At the same thsi instance was not reachableby any client (apiserver was down and etcdctl couldn't connect with rpc error).

After all I finally managed to figure out the proper command line to start an instance of etcd on the second master node (`--initial-cluster-state=existing` was the key). Once the etcd cluster was running again apiserver started and I was able to remove teh second peer using etcdctl.

Suggested change: etcd shouldn't end up[ being inaccessible, there should be some way to restore it from the voting loop.

```
raft2020/01/07 01:43:46 INFO: 40f1e9f856640698 became candidate at term 6221
raft2020/01/07 01:43:46 INFO: 40f1e9f856640698 received MsgVoteResp from 40f1e9f856640698 at term 6221
raft2020/01/07 01:43:46 INFO: 40f1e9f856640698 [logterm: 16, index: 24494] sent MsgVote request to 1885f70dae0473c0 at term 6221
2020-01-07 01:43:46.859354 W | rafthttp: health check for peer 1885f70dae0473c0 could not connect: dial tcp 192.168.11.105:2380: connect: connection refused
2020-01-07 01:43:46.859482 W | rafthttp: health check for peer 1885f70dae0473c0 could not connect: dial tcp 192.168.11.105:2380: connect: connection refused
2020-01-07 01:43:47.173995 E | etcdserver: publish error: etcdserver: request timed out
raft2020/01/07 01:43:48 INFO: 40f1e9f856640698 is starting a new election at term 6221
raft2020/01/07 01:43:48 INFO: 40f1e9f856640698 became candidate at term 6222
raft2020/01/07 01:43:48 INFO: 40f1e9f856640698 received MsgVoteResp from 40f1e9f856640698 at term 6222
raft2020/01/07 01:43:48 INFO: 40f1e9f856640698 [logterm: 16, index: 24494] sent MsgVote request to 1885f70dae0473c0 at term 6222
raft2020/01/07 01:43:49 INFO: 40f1e9f856640698 is starting a new election at term 6222
raft2020/01/07 01:43:49 INFO: 40f1e9f856640698 became candidate at term 6223
raft2020/01/07 01:43:49 INFO: 40f1e9f856640698 received MsgVoteResp from 40f1e9f856640698 at term 6223
raft2020/01/07 01:43:49 INFO: 40f1e9f856640698 [logterm: 16, index: 24494] sent MsgVote request to 1885f70dae0473c0 at term 6223
raft2020/01/07 01:43:51 INFO: 40f1e9f856640698 is starting a new election at term 6223
raft2020/01/07 01:43:51 INFO: 40f1e9f856640698 became candidate at term 6224
raft2020/01/07 01:43:51 INFO: 40f1e9f856640698 received MsgVoteResp from 40f1e9f856640698 at term 6224
raft2020/01/07 01:43:51 INFO: 40f1e9f856640698 [logterm: 16, index: 24494] sent MsgVote request to 1885f70dae0473c0 at term 6224
2020-01-07 01:43:51.860043 W | rafthttp: health check for peer 1885f70dae0473c0 could not connect: dial tcp 192.168.11.105:2380: connect: connection refused
2020-01-07 01:43:51.860080 W | rafthttp: health check for peer 1885f70dae0473c0 could not connect: dial tcp 192.168.11.105:2380: connect: connection refused
```

**Comment by non7top** [comment]
Stale is bad

**Comment by yogeek** [comment]
Same here : a 3-members etcd cluster has lost 2 members (one of which being the leader) and the only member left is blocked into a voting loop.
The cluster is then unavailable...

**Comment by yogeek** [comment]
If that can help, I have documented the steps to reproduce the issue here :

https://github.com/yogeek/etcd-demo

```
etcdctl version: 3.4.7
API version: 3.4
```

**Comment by jingyih** [comment]
Please refer to https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/failures.md#majority-failure
