### ISSUE TITLE
etcd DB size Increasing

### ISSUE THREAD

**Issue by liubing-sky** [etcd-io/etcd#11504]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
etcd version 3.3.13 
/usr/k8s/bin/etcd --data-dir=/home/wondertek/etcd/data/ --wal-dir=/home/wondertek/etcd/wal/ --name=10.186.51.136 --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --trusted-ca-file=/etc/kubernetes/ssl/ca.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/etcd/ssl/etcd-key.pem --peer-trusted-ca-file=/etc/kubernetes/ssl/ca.pem --peer-client-cert-auth --client-cert-auth --listen-peer-urls=https://10.186.51.136:2380 --initial-advertise-peer-urls=https://10.186.51.136:2380 --listen-client-urls=https://10.186.51.136:2379,https://127.0.0.1:2379 --advertise-client-urls=https://10.186.51.136:2379 --initial-cluster-token=etcd-cluster-0 --initial-cluster=10.186.51.136=https://10.186.51.136:2380,10.186.51.137=https://10.186.51.137:2380,10.186.51.72=https://10.186.51.72:2380 --initial-cluster-state=new --auto-compaction-mode=periodic --auto-compaction-retention=1 --quota-backend-bytes=34359738368 --snapshot-count=5000 --max-request-bytes=33554432 --heartbeat-interval=250 --election-timeout=2000

i find , etcd's db is 3.7GB,and DB size have increasing.
6.8G    /home/wondertek/etcd/data/member/snap/

**Comment by spzala** [comment]
@liubing-sky I didn't understand issue much based on the little info your have provided but I would suggest to check revisions, and compact and defrag manually. Also https://github.com/etcd-io/etcd/issues/11352 is not same but similar so some of the discussions there can be helpful. Thanks!

**Comment by liubing-sky** [comment]
Can't the size of DB be reduced？
Keep only the size, such as 3G。
thank you.

**Comment by spzala** [comment]
Please see this https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota Seems like your current space quota is way higher. Thanks!
