### ISSUE TITLE
allow to custom quorum

### ISSUE THREAD

**Issue by hicqu** [etcd-io/etcd#11506]
### What we want

Custom `quorum` function for a given raft:
```go
func (r *raft) set_quorum(quorum func (uint64) uint64) error {
    let q1 = builtin_quorum(len(r.voters))
    let q2 = quorum(len(r.voters))
    if q2 >= q1 && q2 <= len(r.voters)) {
        r.quorum = quorum
        return nil
    }
    return error("Inavlid quorum function")
}
```

The `quorum` function will be used both for election and replication, so it will be safe because the returned value is mut greater than `builtin_quorum`.

### Why we want it

Suppose a raft group with 4 replicas in 2 data centers. Data lost is not allowed, but availability is not cared.
It's easy to know that the group can tolarate one data center fails.  However, If we are doing configuration change, it won't be safe anymore. For example, suppose there are machine X, Y, Z in data center A, and we want to transfer a replica from X to Z. Without joint consensus, we need to add a new replica on Z first, and then remove the replica on X. So in one moment the raft group will have 5 replicas, and 3 of them are in one data center. If the data center fails, data could be lost.

The problem can be resolved by joint consensus, but in `raft-rs` it's not ready for now. If we can custom `quorum`, we can resolve it easily.

### Relative issues
https://github.com/tikv/raft-rs/issues/331

**Comment by xiang90** [comment]
if joint consensus can solve the problem, i suggest you help to make it stable.

if the rust impl needs some short term solution, i guess you can implement in the rust version first :)
