### ISSUE TITLE
Should etcd server be able to handle client requests from peer port?

### ISSUE THREAD

**Issue by YoyinZyc** [etcd-io/etcd#11509]
It is known that etcd has two official port, 2379 for client requests, and 2380 for peer communication. 
However, etcd server with default config can also answer client requests like put, range from peer port(2380). I wonder does it make sense?

**Comment by gyuho** [comment]
Are we talking about v2 API? Can we check how we pass client port to gRPC server? I know `/health` endpoint would not work for `2380`...

**Comment by YoyinZyc** [comment]
I used v3 API. 
I tried to send request to `2380` via clientV3 and also grpc gateway. The server can handle the request with the first approach. The gateway will respond with `404 page not found` which makes sense to me.

**Comment by gyuho** [comment]
Peer port is used for corruption checks.

**Comment by gyuho** [comment]
We can discuss more in community meeting

**Comment by gyuho** [comment]
Corruption check could use client port instead of peer port, if there's any reason to block v3 API traffic to peer ports. I can't remember why we allow client requests through peer ports in the first place. Maybe @xiang90 has some historical contexts :)

Otherwise, let's close this issue.

**Comment by xiang90** [comment]
I do not remember the exact reason either. :(

**Comment by gyuho** [comment]
@YoyinZyc Can you help document the current peer port usage?

https://github.com/etcd-io/etcd/blob/0c787e26bcd102c3bb14050ac893b07ba9ea029f/etcdserver/corrupt.go#L312-L322

Maybe around here https://github.com/etcd-io/etcd/blob/master/README.md#etcd-tcp-ports?

**Comment by YoyinZyc** [comment]
> Yuchen Zhou Can you help document the current peer port usage?
> 
> https://github.com/etcd-io/etcd/blob/0c787e26bcd102c3bb14050ac893b07ba9ea029f/etcdserver/corrupt.go#L312-L322
> 
> Maybe around here https://github.com/etcd-io/etcd/blob/master/README.md#etcd-tcp-ports?

Thank you @gyuho.  I will document it.

**Comment by jingyih** [comment]
If we do corruption check via client port, server needs to have client certs?

Generally I do not feel we need to expose v3 API via peer port. Maybe as the first step, we can disable it and see which test fails?

**Comment by xiang90** [comment]
@jingyih 

disabling the peer port access can be a backward incompatible change. we need to be careful about it.

**Comment by agargi** [comment]
@xiang90 Can this be targeted to a major version upgrade? /cc @jingyih
