### ISSUE TITLE
Minimum recommended production version

### ISSUE THREAD

**Issue by devinrsmith** [etcd-io/etcd#11503]
I see that the minimum recommended production version are

`The minimum recommended etcd versions to run in production are 3.1.11+, 3.2.26+, and 3.3.11+` (as seen in the CHANGELOGS).

Due to https://github.com/etcd-io/etcd/pull/11308, does it make sense to update the minimum recommendation? Or is the bug so rare it doesn't have any practical impact for normal workflows?

**Comment by jingyih** [comment]
The bug in #11308 is rare but the severity is high. Also 3.1.x is out of the supporting window. I will update the recommended versions. Thanks!

**Comment by devinrsmith** [comment]
Thanks!
