### ISSUE TITLE
ETCDCTL can not access etcd cluster through 2380 with ssl  

### ISSUE THREAD

**Issue by Hank00AAA** [etcd-io/etcd#11512]
I want to access a ssl etcd cluster through peer communication port(2380), but failed. Does etcd support this?

Cluster:
```
//etcd0
./etcd --name infra0 --initial-advertise-peer-urls http://127.0.0.1:2381 --listen-peer-urls http://127.0.0.1:2381 --listen-client-urls http://127.0.0.1:2379 --advertise-client-urls http://127.0.0.1:2379 --initial-cluster-token etcd-cluster-1 --initial-cluster $ETCD_INIT_CLUSTER --initial-cluster-state new

//etcd1
./etcd -name infra1 --initial-advertise-peer-urls http://127.0.0.1:2382 --listen-peer-urls http://127.0.0.1:2382 --listen-client-urls http://127.0.0.1:2579 --advertise-client-urls http://127.0.0.1:2579 --initial-cluster-token etcd-cluster-1 --initial-cluster $ETCD_INIT_CLUSTER --initial-cluster-state new

//etcd2
./etcd -name infra2 --initial-advertise-peer-urls http://127.0.0.1:2383 --listen-peer-urls http://127.0.0.1:2383 --listen-client-urls http://127.0.0.1:2679  --advertise-client-urls http://127.0.0.1:2679 --initial-cluster-token etcd-cluster-1 --initial-cluster $ETCD_INIT_CLUSTER --initial-cluster-state new
```
etcdctl 
```
./etcdctl --endpoints=https://127.0.0.1:2381 --cacert="$ETCD_PATH/ca.crt" --cert="$ETCD_PATH/server2.crt" --key="$ETCD_PATH/server2.key.insecure"  get /foo
```

this command failed!

![截图](https://user-images.githubusercontent.com/32003283/72199331-9db62780-3475-11ea-8d9d-82bd595b01ab.PNG)

2379 is ok, but I want to figure out if etcd support accessing cluster through  2380?

**Comment by spzala** [comment]
@Hank00AAA a related discussion on the usage in this issue and PR you may want to look at https://github.com/etcd-io/etcd/issues/11509

**Comment by Hank00AAA** [comment]
Thank you @spzala . This discussion is useful. But I still want to know why etcdctl can't access 2380 with ssl while it can work without ssl. I find etcd cluster will return at the following code, but I don't know why it will happen.
![etcdctl1](https://user-images.githubusercontent.com/32003283/72319754-ffc39680-36da-11ea-806f-78c355c61f9d.PNG)

**Comment by jingyih** [comment]
For client requests such as the requests issued by etcdctl tool, please use the client port.

**Comment by Hank00AAA** [comment]
@jingyih ok~
