### ISSUE TITLE
etcdctl member list cannot get the leader

### ISSUE THREAD

**Issue by zhangguanzhang** [etcd-io/etcd#11537]
`etcdctl member list`
```
7e7a0308e6c2067f, started, etcd-003, https://172.16.2.7:2380, https://172.16.2.7:2379, false
be8c6e0b5f5f6157, started, etcd-002, https://172.16.2.6:2380, https://172.16.2.6:2379, false
f15c8d27ccf66395, started, etcd-001, https://172.16.2.3:2380, https://172.16.2.3:2379, false
```
`etcdctl endpoint status --write-out=table`
```
+-------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://172.16.2.3:2379 | f15c8d27ccf66395 |   3.4.3 |  2.2 MB |     false |      false |         6 |      41219 |              41219 |        |
| https://172.16.2.6:2379 | be8c6e0b5f5f6157 |   3.4.3 |  2.2 MB |      true |      false |         6 |      41219 |              41219 |        |
| https://172.16.2.7:2379 | 7e7a0308e6c2067f |   3.4.3 |  2.2 MB |     false |      false |         6 |      41219 |              41219 |        |
+-------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
`etcd --version`
```
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64
```
`etcdctl version`
```
etcdctl version: 3.4.3
API version: 3.4
```

**Comment by vimalk78** [comment]
you expect `etcdctl member list` to support showing `Leader` column?

**Comment by zhangguanzhang** [comment]
yes

**Comment by spzala** [comment]
> yes, `etcdctl member list`
> 
> ```
> [root@k8s-m1 Kubernetes-ansible]# etcdctl member list --help
> NAME:
> 	member list - Lists all members in the cluster
> 
> USAGE:
> 	etcdctl member list [flags]
> 
> DESCRIPTION:
> 	When --write-out is set to simple, this command prints out comma-separated member lists for each endpoint.
> 	The items in the lists are ID, Status, Name, Peer Addrs, Client Addrs, Is Learner.
> ```
> 
> there is the `Is Learner.` at the description

@zhangguanzhang so that seems working fine, your output of member list does have the last item for Is Learner, as you mentioned in the help text and similar to Is Learner column of the status output, with all set to false. I guess you might have mixed up `Is Leaner` and `Is Leader`?

**Comment by xiang90** [comment]
closing since leader is showed in the table.

**Comment by zhangguanzhang** [comment]
@spzala not the text, According to the text description of the command help, the last column should show whether it is a leader, but all are false

**Comment by zhangguanzhang** [comment]
I guess leaner has special meaning？

**Comment by vimalk78** [comment]
pls check Learner here : https://github.com/etcd-io/etcd/blob/master/Documentation/learning/design-learner.md

**Comment by zhangguanzhang** [comment]
thanks

**Comment by spzala** [comment]
> @spzala not the text, According to the text description of the command help, the last column should show whether it is a leader, but all are false
yes, false because it correctly shows learner as described in the command help
