### ISSUE TITLE
The security risk about the private key stored in plaintext

### ISSUE THREAD

**Issue by weopm** [etcd-io/etcd#11543]
A security risk that the private key(eg, --key-file used for TLS) is stored in plaintext exists in ETCD 3.3.18. If an attacker obtains the key, he can use the V2 interface to store some key-value data to the ETCD database. This affects availability of the V3 database even though user authentication is enabled for the ETCD V3 database.

**Comment by xiang90** [comment]
Where is the key file stored in etcd?

**Comment by mitake** [comment]
Also how v2 data can affect v3 database?

**Comment by weopm** [comment]
Even though we can use this flag (https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--enable-v2) to close V2 interface, but we need set --enable-v2=false becase the default value is of no effect. 

The key file is loaded by etcd when start a etcd with the command (etcd --name 100.120.169.51:22101 --initial-advertise-peer-urls https://100.120.169.51:22101 --listen-peer-urls https://100.120.169.51:22101 --listen-client-urls https://100.120.169.51:22100,https://127.0.0.1:22100 --advertise-client-urls https://100.120.169.51:22100 --initial-cluster-token test--initial-cluster 100.120.169.51:22101=https://100.120.169.51:22101,100.120.201.222:22101=https://100.120.201.222:22101,100.120.233.149:22101=https://100.120.233.149:22101 --initial-cluster-state existing --cert-file /opt/app/zcluster/keys/server.crt --key-file /opt/app/zcluster/keys/server.key --trusted-ca-file /opt/app/zcluster/keys/ca.crt --peer-client-cert-auth --peer-trusted-ca-file /opt/app/zcluster/keys/ca.crt --peer-cert-file /opt/app/zcluster/keys/members.crt --peer-key-file /opt/app/zcluster/keys/members.key --client-cert-auth=true --heartbeat-interval 300 --election-timeout 1500 --max-snapshots 10000 --auto-compaction-retention 6 --auth-token jwt,pub-key=/opt/app/zcluster/keys/ca.crt,priv-key=/opt/app/zcluster/keys/ca.key,sign-method=RS256 --log-output stdout --data-dir /opt/data/data_etcd).

If we get the key file loaded by etcd, we can execute the command (etcdctl.exe --ca-file=ca.crt --cert-file=client.crt --key-file=client.key --endpoint="https://100.120.169.51:22100" role add testrole) with etcd v2 interface sucesssfully.

**Comment by mitake** [comment]
In such a case the attacker can steal the files of etcd db directly, I guess?
