### ISSUE TITLE
 not allowed

### ISSUE THREAD

**Issue by RainingSince** [etcd-io/etcd#11542]
../../../go.etcd.io/etcd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:28:2: use of internal package google.golang.org/grpc/internal/buffer not allowed
../../../go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go:49:2: use of internal package google.golang.org/grpc/internal/resolver/dns not allowed
../../../go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go:50:2: use of internal package google.golang.org/grpc/internal/resolver/passthrough not allowed

**Comment by RainingSince** [comment]
run go test -v 
only import (
	"context"
	"encoding/json"
	"fmt"
	"go.etcd.io/etcd/clientv3"
	path2 "path"
	"sync"
	"time"
)

**Comment by spzala** [comment]
@RainingSince Thanks for reporting! Closing this as dup of https://github.com/etcd-io/etcd/issues/11532 and https://github.com/etcd-io/etcd/issues/11529 We will track it there.
