### ISSUE TITLE
vendor directory for grpc seems incomplete - go get etcd fails without go modules

### ISSUE THREAD

**Issue by dfawley** [etcd-io/etcd#11553]
```
$ go get go.etcd.io/etcd
/usr/local/google/home/dfawley/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:28:2: use of internal package not allowed
/usr/local/google/home/dfawley/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go:49:2: use of internal package not allowed
/usr/local/google/home/dfawley/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go:50:2: use of internal package not allowed
```

I believe this is happening because grpc was updated to a new version recently, but some files were omitted from new directories, e.g. `grpc/internal/buffer` and `grpc/internal/resolver/{dns,passthrough}`.

**Comment by dfawley** [comment]
Note that you will also need to set `GO111MODULE=off` to reproduce this issue if using a recent version of go.

**Comment by spzala** [comment]
@dfawley thanks for reporting! We have couple of other similar issues reported around it and briefly discussed it there like https://github.com/etcd-io/etcd/issues/11532 We should have it resolved soon.

**Comment by dfawley** [comment]
Thanks for following up.  Looks like this is indeed a dupe of #11532, so I'll close this one.

**Comment by spzala** [comment]
@dfawley you are welcome, and thanks for closing it!

**Comment by spzala** [comment]
@dfawley fyi, this should be fixed under https://github.com/etcd-io/etcd/pull/11557 Thanks!
