### ISSUE TITLE
Error for import resolution for "go.etcd.io/etcd/mvcc/mvccpb" package

### ISSUE THREAD

**Issue by gh67uyyghj** [etcd-io/etcd#11558]
I am new to etcd client package and having this error in this code snippet

```

import "go.etcd.io/etcd/mvcc/mvccpb"

....

switch ev.Type {
	case mvccpb.PUT:
		....
```

```
invalid case "go.etcd.io/etcd/mvcc/mvccpb".PUT in switch on ev.Type (mismatched types "go.etcd.io/etcd/mvcc/mvccpb".Event_EventType and "github.com/coreos/etcd/mvcc/mvccpb".Event_EventType)
```

It seems this is due to moving the package address from coreos to etcd-io. I am not sure how to solve this.

**Comment by spzala** [comment]
@gh67uyyghj what version of etcd are you using? I couldn't reproduce it with the master branch. If you haven't tried master, can you please try it or provide a full test for program? Thanks!

**Comment by gh67uyyghj** [comment]
@spzala I am not sure whether this is my fault but I tried it on 2 different machines with the same error. I solved it by replacing the package name `go.etcd.io/etcd/mvcc/mvccpb` with `github.com/coreos/etcd/mvcc/mvccpb`. It seems you renamed the package or the github repo lately (after the coreos acquisition?) and this is why the name conflicts are happening everywhere for me.

**Comment by spzala** [comment]
@gh67uyyghj that's true, after etcd project moved under CNCF there were naming changes etc. The coreos etcd repo is replaced with the https://github.com/etcd-io/etcd Please use the latest etcd if possible at your end. One of the old PRs in this context  https://github.com/etcd-io/etcd/pull/10044 Can we close this issue? Thanks!

**Comment by gh67uyyghj** [comment]
@spzala thanks, I still see this behavior on more than one machine with Vscode whenever I add code that use etcd packages. I suspect it can be more related to goimports or vscode-go extension. I am closing the issue for now and hope that anyone came here after googling may find a good solution
