### ISSUE TITLE
Docs: missing files on branch release-3.3

### ISSUE THREAD

**Issue by burningalchemist** [etcd-io/etcd#11550]
Hi! It seems that branch `release-3.3` is missing several files:

- `Documentation/docs.md`
- `Documentation/upgrades/upgrade_3_4.md`

The first is probably less critical, but the upgrade is quite important as far as I understand.

I wanted to provide a PR to the `etcd/website` to update the documentation for this particular release, and then found this out.

**Comment by jingyih** [comment]
My understanding is that `Documentation/upgrades/upgrade_3_4.md` should be included in release-3.4 and later branches. It is not needed to backport docs to earlier release branches, especially if those docs are specifically for later releases.

**Comment by burningalchemist** [comment]
@jingyih Got it, thanks! But should `upgrade_3_5.md` be removed from `release-3.3` then as well?

Currently, the page looks slightly inconsistent for 3.3.18:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/18210256/72823838-990f2180-3c74-11ea-9016-f6a3dc5c3ace.png">

For 3.2.28 we have the following options:
```
Upgrade etcd from 2.3 to 3.0
Upgrade etcd from 3.0 to 3.1
Upgrade etcd from 3.1 to 3.2
Upgrade etcd from 3.2 to 3.3
Upgrade etcd from 3.3 to 3.4
```

For 3.1.20:
```
Upgrade etcd from 2.3 to 3.0
Upgrade etcd from 3.0 to 3.1
Upgrade etcd from 3.1 to 3.2
Upgrade etcd from 3.2 to 3.3
Upgrade etcd from 3.3 to 3.4
```

In this case, it seems that we need to remove some items for previous releases as well.

**Comment by jingyih** [comment]
Thanks for all the details. Let me defer this question to @gyuho and @lucperkins
