### ISSUE TITLE
clientv3: grpc-go (v1.27.0) made API changes to balancer / resolver.

### ISSUE THREAD

**Issue by eddycjy** [etcd-io/etcd#11563]
After the release of grpc-go v1.27.0, an error occurred while pulling etcd / clientv3. The steps to reproduce it are as follows:

1. go.mod:

```
go 1.13

require (
	github.com/coreos/etcd v3.3.18+incompatible // indirect
	github.com/coreos/go-systemd v0.0.0-00010101000000-000000000000 // indirect
	github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/google/uuid v1.1.1 // indirect
	go.etcd.io/etcd v3.3.18+incompatible // indirect
	go.uber.org/zap v1.13.0 // indirect
	google.golang.org/grpc v1.27.0 // indirect
)

replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
```

2. command: 

```
$ go get go.etcd.io/etcd/clientv3
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

3. PR：https://github.com/etcd-io/etcd/pull/11564

**Comment by nieaowei** [comment]
版本不兼容，指定grpc的版本为1.26即可解决问题。

**Comment by eddycjy** [comment]
> 版本不兼容，指定grpc的版本为1.26即可解决问题。
> google.golang.org/grpc v1.26.0

嗯嗯，但这样子治标不治本，不是解决问题的本意，追求的不是临时方案。

**Comment by eddycjy** [comment]
@nieaowei Yes, but we need to solve the problem fundamentally.

**Comment by gun1x** [comment]
Did you find any workaround?

**Comment by eddycjy** [comment]
@gun1x You can first downgrade grpc to v1.26.0 to temporarily avoid this problem.

**Comment by gun1x** [comment]
> @gun1x You can first downgrade grpc to v1.26.0 to temporarily avoid this problem.

ok, so the actual fix is adding this to `go.mod`:
```
require google.golang.org/grpc v1.26.0
replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
```

**Comment by mostfamiliar** [comment]
@gun1x can i see your full go.mod for that fix? your suggestion does not fix the issue for me and i'm wondering if i'm missing something.
```go 1.13

replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0

require (
	github.com/coreos/etcd v3.3.18+incompatible // indirect
	github.com/go-log/log v0.2.0 // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/json-iterator/go v1.1.9 // indirect
	github.com/lucas-clemente/quic-go v0.14.3 // indirect
	github.com/marten-seemann/qtls v0.7.1 // indirect
	github.com/micro/go-micro v1.18.0
	github.com/miekg/dns v1.1.27 // indirect
	github.com/mostfamiliar/shippy-service-consignment v0.0.0-20200212041600-94c659f72b79
	github.com/nats-io/jwt v0.3.2 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	go.uber.org/atomic v1.5.1 // indirect
	go.uber.org/multierr v1.4.0 // indirect
	go.uber.org/zap v1.13.0 // indirect
	golang.org/x/crypto v0.0.0-20200210222208-86ce3cb69678 // indirect
	golang.org/x/lint v0.0.0-20200130185559-910be7a94367 // indirect
	golang.org/x/tools v0.0.0-20200211205636-11eff242d136 // indirect
	google.golang.org/genproto v0.0.0-20200211111953-2dc5924e3898 // indirect
	google.golang.org/grpc v1.27.1
)
```

error:
```# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

**Comment by eddycjy** [comment]
@mostfamiliar Your google.golang.org/grpc v1.27.1 should be modified to google.golang.org/grpc v1.26.0.

**Comment by gun1x** [comment]
> @gun1x can i see your full go.mod for that fix? your suggestion does not fix the issue for me and i'm wondering if i'm missing something.

https://git.spiderweber.network/spiderweber/spider/src/a36722e7d7aca2118266a5e29d55b78f1137c139/lib/etcd/go.mod

**Comment by arCzWw** [comment]
I have to use version 1.27.0 or I can't use micro, but I need to use etcd to get service information.

**Comment by arges** [comment]
I have a fix for this issue here: https://github.com/etcd-io/etcd/pull/11580. How do I get a review for it?

**Comment by jbhannah** [comment]
@arCzWw Micro still [uses](https://github.com/micro/go-micro/blob/v2.1.0/go.mod#L60) 1.26.0, so you should be able to pin to that version in your `go.mod` (this solved the issue for me).

**Comment by yezihack** [comment]
遇到同样的问题.  meet the same problem
`# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
vendor\github.com\coreos\etcd\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
vendor\github.com\coreos\etcd\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
`

**Comment by 13642212901** [comment]
if modified to google.golang.org/grpc v1.26.0...
then protobuf build pb error undefined: grpc.SupportPackageIsVersion6..

**Comment by eddycjy** [comment]
@13642212901 The consideration is caused by the high version of protoc.

**Comment by 13642212901** [comment]
> @13642212901 The consideration is caused by the high version of protoc.

I know. I hope etcd-io/etcd support grpc v1.27.*,it,s so easy.

**Comment by hesongkang** [comment]
I meet the same issue.

I use the latest version protobuf in  https://github.com/protocolbuffers/protobuf/releases

and I go get -u github.com/golang/protobuf/protoc-gen-go

then if I modified to google.golang.org/grpc v1.26.0

protobuf build pb error undefined: grpc.SupportPackageIsVersion6.

if I modified to google.golang.org/grpc v1.27.0

then etcd will report err:

**Comment by eddycjy** [comment]
#### Workaround:
1. If it is grpc> = 1.27.0, then just change grpc v1.26.0 in the go.mod file, as follows:
```
require (
	...
	google.golang.org/grpc v1.26.0
)
```

2. If the version of protoc is too high and grpc v1.26.0 is not compatible, you can downgrade protoc.

**Comment by yezihack** [comment]
> 遇到同样的问题. meet the same problem
> 
> ```
> # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
> vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
> # github.com/coreos/etcd/clientv3/balancer/picker
> vendor\github.com\coreos\etcd\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
> vendor\github.com\coreos\etcd\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> ```

resolve method:
https://segmentfault.com/q/1010000021762281

**Comment by OGKevin** [comment]
> #### Workaround:
> 1. If it is grpc> = 1.27.0, then just change grpc v1.26.0 in the go.mod file, as follows:
> 
> ```
> require (
> 	...
> 	google.golang.org/grpc v1.26.0
> )
> ```
> 
> 1. If the version of protoc is too high and grpc v1.26.0 is not compatible, you can downgrade protoc.
> 
> fix needs to wait for #11564.

@eddycjy do you know which version of protoc is compatible ? Im stuck as i cant use 26 because of 
```
internal/storage/storage.pb.go:540:11: undefined: grpc.SupportPackageIsVersion6
internal/storage/storage.pb.go:551:5: undefined: grpc.ClientConnInterface
```
and cant use 27 because of this issue 😑  Any tips for other work arounds ?

**Comment by OGKevin** [comment]
> @arCzWw Micro still [uses](https://github.com/micro/go-micro/blob/v2.1.0/go.mod#L60) [](/micro/go-micro/blob/HEAD@{2020-02-14T17:40:33Z}/go.mod#L60) 1.26.0, so you should be able to pin to that version in your `go.mod` (this solved the issue for me).

@jbhannah Unfortunately this is not the case for me. I get the issue `internal/storage/storage.pb.go:540:11: undefined: grpc.SupportPackageIsVersion6`  and according to the docs and code found on https://github.com/grpc/grpc-go, v1.27.0 introduced v6 and for v5 i indeed need to pin to v1.26.0. But still the generated code is using v6, i cant seem to get protoc to generate v5 code. Any pointers ?

**Comment by jbhannah** [comment]
@OGKevin Depends on the structure of your particular project, but I would remove the existing generated files and keep trying to get `protoc` to regenerate them from the protobuf definitions. I have this comment at the top of a Go file in the same directory as the `.proto` file and use Go's `generate` command in my workflow:

```go
//go:generate protoc --gogofaster_out=plugins=grpc:. --micro_out=. --proto_path=$GOPATH/src:$GOPATH/pkg/mod:. api.proto
```

**Comment by medusar** [comment]
I have also encountered this problem, i have solved it with @gun1x's approach.

**Comment by SoftTacos** [comment]
@gun1x's approach didn't work for me, if it doesn't for others, try adding:

replace github.com/coreos/etcd v3.3.17+incompatible => github.com/coreos/etcd v3.3.4+incompatible

To your go.mod, didn't need to change grpc or proto versions

**Comment by gogrisohil** [comment]
Can a new release be created that can be used for the fix ?

**Comment by phpstudyer** [comment]
> 版本不兼容，指定grpc的版本为1.26即可解决问题。
> google.golang.org/grpc v1.26.0

但是最新版的protoc编译出来的pb文件会提示undefined: grpc.SupportPackageIsVersion6 等问题

**Comment by phpstudyer** [comment]
> > 遇到同样的问题. meet the same problem
> > ```
> > # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> > vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
> > vendor\github.com\coreos\etcd\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
> > # github.com/coreos/etcd/clientv3/balancer/picker
> > vendor\github.com\coreos\etcd\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
> > vendor\github.com\coreos\etcd\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> > ```
> 
> resolve method:
> https://segmentfault.com/q/1010000021762281

高版本protoc 一样抓瞎  protoc version 3.6.1

**Comment by phpstudyer** [comment]
> github.com/coreos/etcd v3.3.17+incompatible => github.com/coreos/etcd v3.3.4+incompatible

good job ,thanks

**Comment by cjb21sj** [comment]
强制绑定grpc 1.26.0

```
module kratos-demo

go 1.13

require (
	github.com/bilibili/kratos v0.3.4-0.20200306133340-7c946dc919c1
	github.com/gogo/protobuf v1.3.1
	github.com/golang/protobuf v1.3.5
	github.com/google/wire v0.4.0
	github.com/pkg/errors v0.9.1 // indirect
	google.golang.org/genproto v0.0.0-20200318110522-7735f76e9fa5
	google.golang.org/grpc v1.27.0
)

replace (
	github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
	google.golang.org/grpc => google.golang.org/grpc v1.26.0
)

```

**Comment by monaShe520** [comment]
I encountered the same problem as OGKevin, I need to use etcd to get the configuration, but now etcd does not support v1.27.0 of grpc, so I use my commonly used v1.25.1 to ensure that etcd works properly.
But the go file I generated with protoc is SupportPackageIsVersion6. Is there any way for me to generate a Go file for SupportPackageIsVersion4, so as to ensure the successful start of the project, I do n’t know why the generated SupportPackageIsVersion6, how to get it when compiling?
If someone gives pointers, I will be very grateful (I am a novice, sorry)

**Comment by OGKevin** [comment]
@shreesha21 i removed the GRPC plugin in the protoc command and this seems to generate valid spec.

**Comment by teone** [comment]
is there any plan to upgrade `etcd` to support `google.golang.org/grpc v1.26.0` and newer?

**Comment by vooon** [comment]
@teone i already uses grpc 1.29.1, but you should use replace like that:
```
replace go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200329194405-dd816f0735f8
```

**Comment by neetuom** [comment]
Hi I'm facing issue .

 github.com/micro/go-micro/v2/registry/etcd
../../../pkg/mod/github.com/micro/go-micro/v2@v2.6.0/registry/etcd/etcd.go:79:10: config.LogConfig undefined (type clientv3.Config has no field or method LogConfig)

**Comment by neetuom** [comment]
module ship-microservice-vessel.com/ship-microservice-vessel

go 1.14

require (
	github.com/golang/protobuf v1.4.1
	github.com/grpc-ecosystem/grpc-gateway v1.14.5
	github.com/micro/go-micro/v2 v2.6.0
	google.golang.org/grpc v1.29.1
	google.golang.org/protobuf v1.22.0
)

replace github.com/coreos/etcd v3.3.18+incompatible => github.com/coreos/etcd v3.3.4+incompatible

**Comment by neetuom** [comment]
github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions

above given issue is solved after  downgrading the etcd version  mentioned below github.com/coreos/etcd v3.3.18+incompatible => github.com/coreos/etcd v3.3.4+incompatible

**Comment by neetuom** [comment]
Please help to sort out the issue

**Comment by invidian** [comment]
@neetuom I recently managed to upgrade all my dependencies using the following set of `replace` statements, maybe that's helpful: https://github.com/flexkube/libflexkube/commit/f9cb8bda14eccbb2747eaac2c5007ef5d60d3939#diff-37aff102a57d3d7b797f152915a6dc16L85-R99

**Comment by neetuom** [comment]
> @neetuom I recently managed to upgrade all my dependencies using the following set of `replace` statements, maybe that's helpful: [flexkube/libflexkube@f9cb8bd#diff-37aff102a57d3d7b797f152915a6dc16L85-R99](https://github.com/flexkube/libflexkube/commit/f9cb8bda14eccbb2747eaac2c5007ef5d60d3939#diff-37aff102a57d3d7b797f152915a6dc16L85-R99)

Thanks Bro!

**Comment by AlexanderJLiu** [comment]
@vooon 
> replace go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200329194405-dd816f0735f8

How did you find the version `v0.5.0-alpha.5.0.20200329194405-dd816f0735f8` ? 😄

**Comment by johnbellone** [comment]
I'm still struggling here. Anyone have working example I can lurk?

**Comment by refs** [comment]
@invidian replacements did the job for me:

```go
replace (
	github.com/coreos/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547
	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547
)
```

which is a little odd, since that branch is [6 years old](https://github.com/etcd-io/etcd/tree/v0.5.0-alpha.5).

**Comment by johnbellone** [comment]
I ended up nuking my attempt to get Bazel to work as a build environment and went back to simply using `go mod` and `go build`. I was able to quickly get it working with only the following:
```
go 1.14

require (
	github.com/golang/protobuf v1.4.2
	github.com/micro/go-micro/v2 v2.9.0
	google.golang.org/genproto v0.0.0-20191216164720-4f79533eabd1
)
```

**Comment by xmlking** [comment]
wish we move etcd dependency out of go-micro, maybe move it to plugins.
this is giving bad experience for first-time go-micro users.

**Comment by PVince81** [comment]
> @invidian replacements did the job for me:
> 
> ```go
> replace (
> 	github.com/coreos/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547
> 	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547
> )
> ```
> 
> which is a little odd, since that branch is [6 years old](https://github.com/etcd-io/etcd/tree/v0.5.0-alpha.5).

doesn't seem to work, I get conflicts:

```
go: go.etcd.io/etcd@v0.5.0-alpha.5.0.20200425165423-262c93980547 used for two different module paths (github.com/coreos/etcd and go.etcd.io/etcd)
```

**Comment by vtolstov** [comment]
i'm use this trick - 
replace (
  google.golang.org/grpc => google.golang.org/grpc v1.27.0
  github.com/coreos/etcd => github.com/ozonru/etcd v3.3.20-grpc1.27-origmodule+incompatible
)

**Comment by refs** [comment]
nice, this commit fixes it: https://github.com/ozonru/etcd/commit/68cd771cf28cfe61aeb6969f7a54970ca0b94785 :(

**Comment by refs** [comment]
[hmmmm](https://github.com/ozonru/etcd/commit/68cd771cf28cfe61aeb6969f7a54970ca0b94785), right. Thanks for sharing! I'll be using that one.

**Comment by KyteProject** [comment]
> 
> 
> i'm use this trick -
> replace (
> google.golang.org/grpc => google.golang.org/grpc v1.27.0
> github.com/coreos/etcd => github.com/ozonru/etcd v3.3.20-grpc1.27-origmodule+incompatible
> )

Thanks mate, seems to have worked for me!

**Comment by zxpan** [comment]
Seems that etcd maintainer did not take serious to fix the issue. I still got this issue, where I do need latest gRPC (1.31+)

# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/home/alpha/go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
/home/alpha/go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
/home/alpha/go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
/home/alpha/go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions

How I get the latest etcd golang module if there is a fix?

**Comment by ptabor** [comment]
@zxpan 

The fix is in unreleased 3.5 branch: 
  https://github.com/etcd-io/etcd/commit/4258cdd2efdf79a145067ae426f93b9f220c05f1#diff-c3bc35973ca604ca1c88d111806c06c4

and backported to 3.4:
https://github.com/etcd-io/etcd/blob/release-3.4/clientv3/balancer/picker/roundrobin_balanced.go

Please try using etcd 3.4

**Comment by clarkmcc** [comment]
Why is this closed? I'm still having this issue and it looks like several others are as well.

**Comment by jr-smith** [comment]
> Why is this closed? I'm still having this issue and it looks like several others are as well.

yes, still an issue. Please fix, thanks

**Comment by Ayanrocks** [comment]
> replace (
> google.golang.org/grpc => google.golang.org/grpc v1.27.0
> github.com/coreos/etcd => github.com/ozonru/etcd v3.3.20-grpc1.27-origmodule+incompatible
> )

This seems to be the only workaround even in 2021. This needs to be fixed as a lot of packages is dependent on it. Apparently it's a wide known bug

**Comment by pan2za** [comment]
> github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> ../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
> ../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
> 
> # github.com/coreos/etcd/clientv3/balancer/picker
> ../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
> ../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> 
> above given issue is solved after downgrading the etcd version mentioned below github.com/coreos/etcd v3.3.18+incompatible => github.com/coreos/etcd v3.3.4+incompatible

This solved my issue

**Comment by aka-achu** [comment]
```
replace (
	github.com/coreos/bbolt => go.etcd.io/bbolt v1.3.5
	google.golang.org/grpc => google.golang.org/grpc v1.26.0
)

require (
	github.com/coreos/bbolt v0.0.0-00010101000000-000000000000 // indirect
	github.com/coreos/etcd v3.3.25+incompatible // indirect
	github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f // indirect
	github.com/go-playground/validator/v10 v10.5.0
	github.com/google/btree v1.0.1 // indirect
	github.com/google/uuid v1.2.0
	github.com/grpc-ecosystem/go-grpc-middleware v1.3.0 // indirect
	github.com/grpc-ecosystem/grpc-gateway v1.16.0 // indirect
	github.com/jonboulle/clockwork v0.2.2 // indirect
	github.com/prometheus/client_golang v1.10.0 // indirect
	github.com/soheilhy/cmux v0.1.5 // indirect
	github.com/tmc/grpc-websocket-proxy v0.0.0-20201229170055-e5319fda7802 // indirect
	go.etcd.io/etcd v3.3.25+incompatible
	go.uber.org/zap v1.16.0 // indirect
	golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba // indirect
)
```
This is working for me.

**Comment by BoyChai** [comment]
Can it only be solved by downgrading the grpc version https://github.com/etcd-io/etcd/issues/18344
