### ISSUE TITLE
request cluster ID mismatch (got cdf818194e3a8c32 want 37fcd

### ISSUE THREAD

**Issue by bs70-sketch** [etcd-io/etcd#11562]
i have a 5-node cluster and it is healthy but one of the nodes is given this error request cluster ID mismatch (got cdf818194e3a8c32 want 37fcdb...4df), though it is running but it is showing in the service.

**Comment by bs70-sketch** [comment]
The error is persisting even after i removed it and rejoined it back, still giving error request cluster ID mismatch (got cdf818194e3a8c32 want 37fcdb...4df).

**Comment by jingyih** [comment]
Normally this is caused by the existing data dir on the machine. When starting, if data dir exists, etcd server will resume its previous identity stored in data file. Could you try to remove the data dir (backup it if needed) and try again.

**Comment by bs70-sketch** [comment]
Here is what i have done so far: I backed up the data dir to temp location then remove it,  stopped and started the service again but it is still showing the error.
Also i stopped the cluster and started again using the etcd service the issue persists

**Comment by ahrtr** [comment]
FYI.  https://github.com/ahrtr/etcd-issues/blob/master/docs/cluster_id_mismatch.md
