### ISSUE TITLE
Only one of Stats or Run can be called only once

### ISSUE THREAD

**Issue by anson627** [etcd-io/etcd#11571]
In current implementation, only one of Stats or Run functions in report package can be called only one time to get the correct results since they both call processResults function which mutate the internal state. The API name Stats indicates it's a getter function and therefore should not mutate internal state. This also makes client code complex to support different output formats: 

```
if isRawOutput {
    sc = r.Stats()
} else {
    rc = r.Run()
}
   ...

if isRawOutput {
    s = <- sc
} else {
    r = <- rc
}
```

The proposal is to change Stats function to not call processResults, instead it just make a copy of internal state, do additional calculation (e.g. getTimeSeries).  This API change would make client code much simpler and cleaner:
```
rc := r.Run()
   ...
  
r := <-rc
if isRawOutput {
    s = r.Stats()
}
```

**Comment by anson627** [comment]
Hi @xiang90, I want to check if you are ok with this proposal before I start implementing it.

**Comment by spzala** [comment]
Removing `stale`considering it's related to https://github.com/etcd-io/etcd/pull/11514
