### ISSUE TITLE
Security concern:  etcd is logging JWT tokens

### ISSUE THREAD

**Issue by ae6rt** [etcd-io/etcd#11579]
etcd version:  3.4.2

Expected behavior:  JWT tokens are bearer tokens.  etcd can and probably should log that a JWT token was issued, but should not log the token itself.

Actual behavior:  etcd is logging the JWT token at level INFO.

```
{"level":"info","ts":"2020-02-03T16:43:30.055Z","caller":"auth/jwt.go:121","msg":"created/assigned a new JWT token","user-name":"bob","revision":8,"token":"(ELIDED)"}
```

See https://github.com/etcd-io/etcd/blob/master/auth/jwt.go#L120-L129

**Comment by ae6rt** [comment]
cc @mitake

**Comment by jingyih** [comment]
Hi @ae6rt, I created #11586 to correct the logging level. Originally it was using `debug` logging level.

**Comment by mitake** [comment]
Thanks for reporting this @ae6rt !

**Comment by ae6rt** [comment]
Thank you.  Logging at Debug is better than Info, and I appreciate the effort.  I still think it's risky to log the token at any level -- credentials should never be logged.
