### ISSUE TITLE
/health does not expose alarm status in server

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#11599]
https://github.com/etcd-io/etcd/blob/aea335485436aba950a94c66699379f9f57cf661/etcdserver/api/etcdhttp/metrics.go#L47-L64

still returns `{"health": "true"}` when:

- etcd has exceeded DB quota with `AlarmType_NOSPACE`
- etcd has detected DB corruption with `AlarmType_CORRUPT`

We can extend the `/health` response with `{"health": "false", "reason": "NOSPACE/CORRUPT"}` and possibly mark a cluster with alarms as "unhealthy". Or we can introduce something like `/health/v3` or emit `{"health": "NOSPACE"}` since the value type of `"health"` key is already `string`.

When such alarms are raised, the cluster goes into maintenance mode, rejecting writes anyway.

/cc @wenjiaswe @yczhou @xiang90 @jpbetz @jingyih @liggitt

**Comment by xiang90** [comment]
adding reason is better. the "false" string thing is by mistake :( but hard to fix...

**Comment by gyuho** [comment]
> adding reason is better. the "false" string thing is by mistake :( but hard to fix...

For contexts, https://github.com/kubernetes/kubernetes/pull/58270 by @liggitt 

ref. https://github.com/kubernetes/kubernetes/issues/58240

**Comment by gyuho** [comment]
Fixed via https://github.com/etcd-io/etcd/issues/11599
