### ISSUE TITLE
Images 404 inside page etcd.io/docs/v3.4.0/learning/design-learner/

### ISSUE THREAD

**Issue by Colstuwjx** [etcd-io/etcd#11593]
As the title, all images inside [this page](https://etcd.io/docs/v3.4.0/learning/design-learner/) show 404 not found, for example, https://etcd.io/docs/v3.4.0/learning/design-learner/img/server-learner-figure-01.png .

**Comment by spzala** [comment]
@Colstuwjx thanks for reporting, but it belongs to etcd-io/website repo and there already is an issue created for this - 
https://github.com/etcd-io/website/issues/48 I am closing this one. /cc @lucperkins
