### ISSUE TITLE
V3 api introduction video shown unavailable 

### ISSUE THREAD

**Issue by Colstuwjx** [etcd-io/etcd#11591]
Hi team,

The youtube video [link](https://www.youtube.com/watch?v=J5AioGtEPeQ&feature=youtu.be&t=211) from [the v3 api doc](https://github.com/etcd-io/etcd/blame/a621d807f061e1dd635033a8d6bc261461429e27/Documentation/rfc/v3api.md#L5) shown unavailable, shall we update this link?

Thanks.

**Comment by spzala** [comment]
@Colstuwjx I doubt finding the correct link or recording is easy. We probably should remove the link. Would you like to send a PR? 
@xiang90 - this is about your video so you can advise better :-) Thanks!

**Comment by Colstuwjx** [comment]
@spzala I have been proposed a quick fix PR for this, thanks.
