### ISSUE TITLE
get dir exits when snapshot restore

### ISSUE THREAD

**Issue by zhanw15** [etcd-io/etcd#11618]
**Problems**
when I use `etcdctl snapshot restore --data-dir=/var/lib/etcd xxx`, I get `Error:  data-dir "/var/lib/etcd" exists`, (There is nothing in the data-dir /var/lib/etcd), is this a bug?

I can't delete dir "/var/lib/etcd", because I mounted a ssd on the dir.

**etcd version**
```
etcd Version: 3.2.26
Git SHA: 06cec4091
Go Version: go1.8.7
Go OS/Arch: linux/amd64
```

**Comment by maoling** [comment]
@zhanw15 
Is `etcdctl snapshot restore --data-dir=/var/lib/etcd/snapshots` OK ?

**Comment by zhanw15** [comment]
yeah, I think it can solve this, but the data-dir chages.
I just want know why can't use the dir exists but empty. @maoling

**Comment by spzala** [comment]
The only reason I can think is to prevent any accidental overwrite strongly as mentioned here, https://github.com/etcd-io/etcd/blob/f0faa5501d936cd8c9f561bb9d1baca70eb67ab1/clientv3/snapshot/v3_snapshot.go#L66 And here is a related old issue having some discussion on this topic and a doc PR to clarify it https://github.com/etcd-io/etcd/issues/9248 So it's not really a bug but something that seems was agreed upon by the etcd team, but I guess, if you want we can keep this issue open for more discussion with your use case /cc @gyuho
