### ISSUE TITLE
Publish open source security audit for etcd

### ISSUE THREAD

**Issue by caniszczyk** [etcd-io/etcd#11615]
CNCF recently funded a security audit for etcd.

The @etcd-io/maintainers-etcd should review the audit, address any major issues and then publish the audit results.

**Comment by caniszczyk** [comment]
You may also want to use this as an excuse to publish your first advisories via GitHub: https://github.com/etcd-io/etcd/security/advisories

**Comment by caniszczyk** [comment]
any updates here @gyuho or @spzala

**Comment by spzala** [comment]
@caniszczyk hi sorry I missed the ping above from @gyuho I will soon get back with updates soon. Thanks!

**Comment by spzala** [comment]
@caniszczyk hello, this is still under discussion but hopping to provide update soon. Thanks!

**Comment by caniszczyk** [comment]
@spzala any update here on this?

**Comment by xiang90** [comment]
@caniszczyk @spzala do we have a deadline or target date on publishing this?

**Comment by spzala** [comment]
@caniszczyk @xiang90 I don't think we have a target date but we should be doing it as soon as possible now that we have audit report. I have been trying to coordinate among the maintainers but I think with work related challenges we all going through lately I haven't heard back from everyone. @philips is kindly helping to take it further per discussion we had last week. I will follow up with Brandon later this week. /cc @gyuho @mitake

**Comment by caniszczyk** [comment]
thanks, no worries, I understand things are crazy

**Comment by spzala** [comment]
> thanks, no worries, I understand things are crazy

Thanks Chris!

**Comment by gyuho** [comment]
@spzala Can you start an email thread? I don't see any reason to delay as long as we address all critical ones (sorry for late response).

**Comment by spzala** [comment]
@gyuho thank you and no worries, and I totally agree on not delaying it any further. I actually already sent an email couple of weeks back and did get response from Mitake and Brandon but not from everyone. Let me send a friendly reminder again :)

**Comment by caniszczyk** [comment]
friendly ping here @spzala I know the world is a bit crazy now :)

**Comment by spzala** [comment]
Hi @caniszczyk :) thank you! This is my priority and I am working on coordinating..I couldn't share something here but I will update you soon.

**Comment by caniszczyk** [comment]
@spzala any update here? I think we're close

**Comment by spzala** [comment]
@caniszczyk yes, we are getting close. I couldn't reach out to couple of maintainers, who are working on items related to the recent updates in the audit, due to their schedule but we are meeting tomorrow so I will have a better update afterwards. Thanks!  /cc @xiang90

**Comment by ostackbrian** [comment]
I think this can be closed now.  See announcement https://www.cncf.io/blog/2020/08/05/etcd-security-audit/ and the report https://github.com/etcd-io/etcd/blob/master/security/SECURITY_AUDIT.pdf

**Comment by spzala** [comment]
> I think this can be closed now. See announcement https://www.cncf.io/blog/2020/08/05/etcd-security-audit/ and the report https://github.com/etcd-io/etcd/blob/master/security/SECURITY_AUDIT.pdf

Good reminder, thanks @ostackbrian

**Comment by spzala** [comment]
Closing as audit results are made public. Thanks @caniszczyk
