### ISSUE TITLE
etcd public discovery down?

### ISSUE THREAD

**Issue by dselans** [etcd-io/etcd#11635]
Hi,

Apologies if I overlooked something but is etcd public discovery no longer available?

https://discovery.etcd.io redirs to `https://github.com/etcd-io/etcd/blob/master/Documentation/v2/clustering.md#public-etcd-discovery-service` which is a 404.

A lot of the documentation still points to the public documentation.

Thanks!

**Comment by spzala** [comment]
@dselans about the dead doc link, some restructuring work is going on by @lucperkins and v2 docs are removed and moved, from the `etcd-io/etcd` to `etcd-io/website`. 
e.g. this link should work,  https://github.com/etcd-io/website/blob/master/content/docs/v2/clustering.md#public-etcd-discovery-service
