### ISSUE TITLE
Question: promote learning member on a 1 size cluster

### ISSUE THREAD

**Issue by ereslibre** [etcd-io/etcd#11633]
etcd version: 3.4.3

Given a cluster setup with a single member,

```
# etcdctl member list
ab75c79a2c3090aa, started, controlplane, http://172.17.0.2:30002, http://172.17.0.2:30003, false
```

I added a new learner member, and started it.

```
Member f9d1e8f6c55eb887 added to cluster a9c95578e770c6db

ETCD_NAME="controlplane2"
ETCD_INITIAL_CLUSTER="controlplane=http://172.17.0.2:30002,controlplane2=http://172.17.0.2:30004"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.17.0.2:30004"
ETCD_INITIAL_CLUSTER_STATE="existing"
```

The member list afterwards adding the learner member, and after having started it.

```
# etcdctl member list
ab75c79a2c3090aa, started, controlplane, http://172.17.0.2:30002, http://172.17.0.2:30003, false
f9d1e8f6c55eb887, started, controlplane2, http://172.17.0.2:30004, http://172.17.0.2:30005, true
```

I see that if I now try to promote it to a voting member, I get the following error:

```
# etcdctl member promote f9d1e8f6c55eb887 
{"level":"warn","ts":"2020-02-16T18:41:05.652Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-0d90d825-371b-4a77-b1e1-bcf99ab3fab2/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
Error: etcdserver: re-configuration failed due to not enough started members
```

This error looks like it's coming from [`IsReadyToPromoteMember`](https://github.com/etcd-io/etcd/blob/3cf2f69b5738fb702ba1a935590f36b52b18979b/etcdserver/api/membership/cluster.go#L659-L687), called when the [strict reconfig check is enabled](https://github.com/etcd-io/etcd/blob/3cf2f69b5738fb702ba1a935590f36b52b18979b/etcdserver/server.go#L1734-L1749).

This is the error present on the only `etcd` instance with voting rights during that time:

```
2020-02-16 18:41:05.651445 W | etcdserver/membership: Reject promote member request: the number of started member (1) will be less than the quorum number of the cluster (2)
2020-02-16 18:41:05.651501 W | etcdserver: not enough started members, rejecting promote member f9d1e8f6c55eb887
```

I can disable the strict reconfig check, but I'm wondering if even with strict reconfiguration this should not be possible at all by design, or if it's a bug. I'm following the recommendation of only joining one learner node at a time, but seems impossible to succeed if you start with a single instance cluster.

Thank you!

**Comment by ereslibre** [comment]
At first sight looks like this case would be solved by changing https://github.com/etcd-io/etcd/blob/f0faa5501d936cd8c9f561bb9d1baca70eb67ab1/etcdserver/api/membership/cluster.go#L600 to 0, because right now `IsReadyToPromoteMember` thinks it has two voting members, when there is only one in reality.

I might be missing many important nuances here, though.

**Comment by jingyih** [comment]
Looks like a bug to me. A cluster with 1 started voting member and 1 started learner member should allow promoting of that learner member.

**Comment by ereslibre** [comment]
I'll open a PR.

**Comment by jingyih** [comment]
cc @WIZARD-CXY

**Comment by jingyih** [comment]
>I'll open a PR.

@ereslibre Sounds great! I am thinking it will be helpful if we could have a unit test for that function, something similar to https://github.com/etcd-io/etcd/blob/d6a3c995cf86b479cb5a44b48d000feb33e3d8f8/etcdserver/api/membership/cluster_test.go#L627

**Comment by ereslibre** [comment]
@jingyih I created https://github.com/etcd-io/etcd/pull/11640 to fix this issue, but as I comment on the PR I would be eager to increase coverage for the promotion logic on other parts of the code as well.
