### ISSUE TITLE
etcd custom discovery error: 404 not found

### ISSUE THREAD

**Issue by tangname** [etcd-io/etcd#11646]
etcd version: 3.5.0-pre
go version: 1.13.7
go os/arch: linux/amd64

i'm try to bring up a cluster with etcd discovery.
i follow this doc:  [https://etcd.io/docs/v3.4.0/op-guide/clustering/#etcd-discovery](https://etcd.io/docs/v3.4.0/op-guide/clustering/#etcd-discovery)
```
$ curl -X PUT http://192.168.157.129:2379/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=3
```
but it occured an error: `404 not found`

an etcd is started
```
$ etcd --listen-client-urls=http://192.168.157.129:2379 --advertise-client-urls=http://192.168.157.129:2379
```

I have no idea about that error,could you help me?thank you very much!

**Comment by tangname** [comment]
additional,i have set api=v2 by using `export ETCDCTL_API=2`
and view the member status,it also occur a 404 error
```
curl http://192.168.157.129:2379/v2/stats/self
```

**Comment by tangname** [comment]
i  need  set  ETCD_ENABLE_V2=true

**Comment by abdasgupta** [comment]
How did you fix it? I am still getting `404 error`

**Comment by tangname** [comment]
> How did you fix it? I am still getting `404 error`

have try bellow:
```
export ETCD_ENABLE_V2=true
export ETCDCTL_API=2
```
