### ISSUE TITLE
Is there a plan to update google.golang.org/grpc?

### ISSUE THREAD

**Issue by guanwenbogit** [etcd-io/etcd#11650]
Do you mind update the  google.golang.org/grpc to v1.27.0?

**Comment by xutaox** [comment]
```
# github.com/coreos/etcd/clientv3/balancer/picker
/Users/klook1/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
/Users/klook1/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/Users/klook1/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
/Users/klook1/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
```
I got this 😢

**Comment by fproulx-eoscanada** [comment]
Yeah, that'd be nice to address that... 
otherwise it makes integrating etcd as a lib in another project with other grpc components problematic....

**Comment by medusar** [comment]
> ```
> # github.com/coreos/etcd/clientv3/balancer/picker
> .../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
> .../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> .../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
> .../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
> ```
> 
> I got this 😢

I got this when i was downloading the package: `go get go.etcd.io/etcd/clientv3`..

**Comment by dliuproduction** [comment]
Would be great if we can get the PR merged :), also seeing issues with grpc incompatibility.

**Comment by immesys** [comment]
Clientv3 from release 3.4.4 does not build because of this. Surely there should be something that checks to see if a release even builds before it is released?

**Comment by luxuze** [comment]
I got this error when use go-micro/v2/web package

../../../../go/pkg/mod/github.com/coreos/etcd@v3.3.20+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../../../go/pkg/mod/github.com/coreos/etcd@v3.3.20+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../../../go/pkg/mod/github.com/coreos/etcd@v3.3.20+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../../../go/pkg/mod/github.com/coreos/etcd@v3.3.20+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption

**Comment by frodriguez-sr** [comment]
The same issue has been found on the next steps:
package main

```golang
import (
	"context"
	"flag"
	"fmt"
	"log"
	"time"

	"go.etcd.io/etcd/clientv3"
	"go.etcd.io/etcd/clientv3/concurrency"
)

func main() {
	var name = flag.String("name", "", "give a name")
	flag.Parse() // Create a etcd client
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"localhost:2379"}})
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close() // create a sessions to aqcuire a lock
	s, _ := concurrency.NewSession(cli)
	defer s.Close()
	l := concurrency.NewMutex(s, "/distributed-lock/")
	ctx := context.Background() // acquire lock (or wait to have it)
	if err := l.Lock(ctx); err != nil {
		log.Fatal("cannot get lock")
	}
	fmt.Println("acquired lock for ", *name)
	fmt.Println("Do some work in", *name)
	time.Sleep(5 * time.Second)
	if err := l.Unlock(ctx); err != nil {
		log.Fatal(err)
	}
	fmt.Println("released lock for ", *name)
}
```
Works when I run
`go run main.go -name first`

But at the time to vendoring it has the same issue 
`go mod init && go mod tidy`
and then

I got
```
go: src.srconnect.io/frodriguez/etcd_poc imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        github.com/coreos/etcd/auth imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.5: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```
If I run
`go mod vendor`
and then 
`go run -mod=vendor main.go -name first`

I get 
```
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
vendor/github.com/coreos/etcd/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
vendor/github.com/coreos/etcd/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
vendor/github.com/coreos/etcd/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
vendor/github.com/coreos/etcd/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

Is this a know bug or related to this issue?

**Comment by ptabor** [comment]
This is being worked on in: 
 https://github.com/etcd-io/etcd/pull/12398

**Comment by ptabor** [comment]
Please use: https://github.com/etcd-io/etcd/issues/12124 is canonical for grpc update problem.
