### ISSUE TITLE
What is the execution order of etcd's processing queue

### ISSUE THREAD

**Issue by pjhdld** [etcd-io/etcd#11672]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

  3 nodes etcd and etcd-2 were rebuilt, and they sent member remove and member add requests to the cluster and rejoined the cluster; however, it is unknown what causes other nodes to receive the member add request before receiving the member remove request. Because the node information is not in the cluster, the node has been unable to get up

Due to company reasons, it is not possible to put log information, only to talk about the phenomenon

**Comment by jingyih** [comment]
Did "member remove" command finish and return before you issue "member add"?

**Comment by pjhdld** [comment]
> Did "member remove" command finish and return before you issue "member add"?

Yes, member remove runs successfully, but I sent a member remove request first, before sending a member add request; only member add was run before member remove

**Comment by pjhdld** [comment]
> > 在发出“成员添加”之前，“成员删除”命令是否完成并返回？
> 
> 是的，成员删除成功运行，但是在发送成员添加请求之前，我先发送了成员删除请求；在删除成员之前仅运行成员添加

So I would like to ask how etcd handles incoming requests. In this case, do I need to send a few seconds later?

**Comment by jingyih** [comment]
If you want request A to be guaranteed to apply in etcd cluster before request B, the client should wait for the response of request A before issuing request B.
