### ISSUE TITLE
failed to send out heartbeat on time p99 less than 10ms

### ISSUE THREAD

**Issue by webPageDev** [etcd-io/etcd#11681]
In etcd faq, it answers the reason why apply entries took too long. 
To rule out a slow disk from causing this warning, monitor backend_commit_duration_seconds (p99 duration should be less than 25ms) to confirm the disk is reasonably fast.
It answers the reason why failed to send out heartbeat on time. 
To rule out a slow disk from causing this warning, monitor wal_fsync_duration_seconds (p99 duration should be less than 10ms) to confirm the disk is reasonably fast.
I have some questions that need your answers.
First, how is this p99 less than 25ms or less than 10ms calculated?
What kind of test method is used to obtain this value? Are there any test tools and test methods recommended?
Second, what kind of disks do I need if the leader of the etcd cluster does not change? What is the value of p99 of the disk that etcd will not change?

**Comment by agargi** [comment]
Please look at following article to see if it helps. Couple of important points are:

1. etcd sends out heartbeat and before a heartbeat is sent out, it writes metadata to disk. If disk is slow, it will cause delay in heartbeats. IMHO, the recommendation for 10 ms limit is based on heartbeat timeout (which is by default, set to 100 ms) to ensure there is no delay in sending out heartbeats on time and provision time for additional processing.
2. To see if your disk is up to mark to support etcd cluster and not lead to problems (such as leader reelections), use [Fio](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd)

https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-failed-to-send-out-heartbeat-on-time-mean
