### ISSUE TITLE
3.4.4 missing on GCR

### ISSUE THREAD

**Issue by bastianeicher** [etcd-io/etcd#11688]
The Docker image for [Release v3.4.4](https://github.com/etcd-io/etcd/releases/tag/v3.4.4) seems to be missing from GCR:

```
$ docker pull gcr.io/etcd-development/etcd:v3.4.4
Error response from daemon: manifest for gcr.io/etcd-development/etcd:v3.4.4 not found
```

Pulling from `quay.io/coreos/etcd:v3.4.4` instead works.

**Comment by frittenlab** [comment]
We are seeing the same error:

Back-off pulling image "gcr.io/etcd-development/etcd:v3.4.4"

Just switching our deployments to use quay now. Has something changed? Or was the upload just forgot?

**Comment by jingyih** [comment]
cc @gyuho
