### ISSUE TITLE
How to export/import etcd data to/from json file?

### ISSUE THREAD

**Issue by akshaysharama** [etcd-io/etcd#11680]
ETCD-Version  3.4(v3)
Running as pod in kubernetes enviroment (v1.16.3)

can we fetch all etcd key/values pair in json format?
using etcdctl API or curl command without metadata.

if yes,then how to dump again key/value to etcd from json file.

**Comment by pariminaresh** [comment]
You can try this:

$ kubectl exec <pod> -n kube-system -- sh -c \
"ETCDCTL_API=3 etcdctl \
--endpoints \"https://IP:2379\"  \
--cacert /etc/kubernetes/pki/etcd/ca.crt \
--key /etc/kubernetes/pki/etcd/server.key \
--cert /etc/kubernetes/pki/etcd/server.crt \
get \"\" --prefix=true -w json" > data.json
