### ISSUE TITLE
etcdctl does not honor --insecure-skip-tls-verify unless --cacert is set

### ISSUE THREAD

**Issue by ae6rt** [etcd-io/etcd#11693]
## Versions

etcdctl version

```
$ etcdctl version
etcdctl version: 3.4.4
API version: 3.4
```
etcd version
```
etcd Version: 3.4.4
Git SHA: c65a9e2dd
Go Version: go1.12.12
Go OS/Arch: linux/amd64
```

## Expected behavior

etcdctl should honor `--insecure-skip-tls-verify` without setting `--cacert`

## Actual behavior

etcdctl does not honor `--insecure-skip-tls-verify` unless `--cacert` is set, even if  the certs in `--cacert` do not anchor the certificate chain returned by the server.

The etcd server endpoints are secured with TLS using an internal CA.  The file `google.pem` contains an essentially random cert that does not anchor the certificate chain returned by the server.  

This produces the desired output, but should not require `--cacert` being set

```
$ etcdctl --cacert=google.pem  --insecure-skip-tls-verify --endpoints=https://a.b.c.d:2379 -w table endpoint status
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://a.b.c.d:2379 | e93876419109b8da |   3.4.4 |   20 kB |     false |      false |         9 |        162 |                162 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

This should work, but does not

```
$ etcdctl --insecure-skip-tls-verify --endpoints=https://a.b.c.d:2379 -w table endpoint status
{"level":"warn","ts":"2020-03-13T13:48:04.084-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://a.b.c.d:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""}
Failed to get the status of endpoint https://a.b.c.d:2379 (context deadline exceeded)
```

**Comment by integrii** [comment]
We should reopen this.

**Comment by thanaphat1991** [comment]
add more param in below work for me
--cacert="/etc/ssl/certs/ca-certificates.crt"  --cert="/var/lib/etcd/fixtures/client/cert.pem" --key="/var/lib/etcd/fixtures/client/key.pem" --insecure-skip-tls-verify

**Comment by JeremieRodon** [comment]
After investigating the code, it appears that if `--insecure-skip-tls-verify` is the only TLS related flag, not TLS config is created for the client and therefore the flag is ignored because `cgf.TLS` is nil:

https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/global.go
line 238
```
	// If the user wants to skip TLS verification then we should set
	// the InsecureSkipVerify flag in tls configuration.
	if scfg.insecureSkipVerify && cfg.TLS != nil {
		cfg.TLS.InsecureSkipVerify = true
	}
```

You can solve this without giving a CA certificate by using `--insecure-transport=false` to force the creation of a TLS config.


Thus, `etcdctl --insecure-transport=false --insecure-skip-tls-verify <your command>` will work.
