### ISSUE TITLE
Does etcd support TLS1.3?

### ISSUE THREAD

**Issue by hehechen** [etcd-io/etcd#11692]
Try to connect etcd with openssl s_client -tls1_3, handshake failed, openssl log:
140144542844736:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1544:SSL alert number 70
etcd log:
 embed: rejected connection from "127.0.0.1:34692" (error "tls: client offered only unsupported versions: [304]", ServerName "")
Does etcd Support TLS1.3?

**Comment by hehechen** [comment]
etcd version : 3.4.4

**Comment by terorie** [comment]
@hehechen Can you share some system details? Did you build etcd yourself, if yes what version? Did you install it, if yes what package and package manager?

Older versions of Go required opt-in for TLSv1.3. Can you try starting the server with environment variable `GODEBUG` set to `tls13=1`?
