### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by zltl** [etcd-io/etcd#11707]
It just failed on `go get github.com/etcd-io/etcd`

```
...
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
go/pkg/mod/github.com/coreos/etcd@v3.3.19+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
go/pkg/mod/github.com/coreos/etcd@v3.3.19+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
go/pkg/mod/github.com/coreos/etcd@v3.3.19+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
go/pkg/mod/github.com/coreos/etcd@v3.3.19+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```
Why all ci tags on your README.md still green?

**Comment by marwan-at-work** [comment]
Same issue here. 

And I also noticed that the go.mod file is not following Semantic Import Versioning so I cannot use clientv3 at all.

**Comment by tangname** [comment]
You  need  manutually modify the go.mod file.

From google.golang.org/grpc v1.26.1  to   google.golang.org/grpc v1.25.1

It'll work well.

**Comment by utrack** [comment]
I believe https://github.com/etcd-io/etcd/pull/11564 should be backported to v3.3

**Comment by Heusini** [comment]
i did not change it in the go.mod but did this:
_go get google.golang.org/grpc@v1.26.0_
