### ISSUE TITLE
build failure on FreeBSD aarch64

### ISSUE THREAD

**Issue by MikaelUrankar** [etcd-io/etcd#11717]
Hi,
I have the following error on FreeBSD aarch64:
vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

It's fixed upstream, is it possible to update golang.org/x/sys ?
https://github.com/golang/sys/commit/33540a1f603772f9d4b761f416f5c10dade23e96

Thanks

**Comment by jhvst** [comment]
This seems a bit larger issue. On `v3.5.0-alpha.0` branch the error is suppressed, but now I get `etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set` error when running the Makefile.

Hopefully, we can eventually see etcd being supported on arm64!
