### ISSUE TITLE
Why does etcd break SIV

### ISSUE THREAD

**Issue by marwan-at-work** [etcd-io/etcd#11722]
Hi there, 
I'm curious to find out why etcd is at v3 with Go Modules enabled, yet it breaks the Semantic Import Versioning by not having a s3 suffix in its import path: `go.etcd.io/etcd` 

This means that any third party importing the etcd client, can only import v3.3.19 and lower, but not 3.4.5. 

Introducing Go Modules when you are >= v2, means you must upgrade import paths, which means you must bump the major version. Converting to modules while not following this rules only leaves modules at a broken state :) 

Thanks for all of your work, etcd is awesome

**Comment by lucab** [comment]
I think this is a duplicate of https://github.com/etcd-io/etcd/issues/11154.
