### ISSUE TITLE
etcdserver: timeout should be set when check health

### ISSUE THREAD

**Issue by zhanw15** [etcd-io/etcd#11729]
https://github.com/etcd-io/etcd/blob/a04b74d4b4ebced2aca96dde08cb73b04bcdc484/etcdserver/api/etcdhttp/metrics.go#L97
https://github.com/etcd-io/etcd/blob/a04b74d4b4ebced2aca96dde08cb73b04bcdc484/etcdserver/api/etcdhttp/metrics.go#L123
Should `time.Second` be set as a variable ? Just like `ETCD_ELECTION_TIMEOUT`.

**Comment by zhanw15** [comment]
@gyuho @GSokol

**Comment by GSokol** [comment]
@gyuho, @zhanw15 I would implement this one weekends...

**Comment by zhanw15** [comment]
> @gyuho, @zhanw15 I would implement this one weekends...

Thanks, that would be great !
