### ISSUE TITLE
backport: etcd > v3.3.13, <= v3.3.20 (latest v3.3) doesn't compile

### ISSUE THREAD

**Issue by utrack** [etcd-io/etcd#11721]
etcd v3.3.15 to v3.3.20 use gRPC API that was renamed in `grpc@v1.27`. 
Right now etcd doesn't compile when not using modules, or if current module or any child module had used grpc@v1.27 or higher.

Problem was fixed in #11564, but it wasn't backported to v3.3 as I see.

Refs #11650 #11707

**Comment by utrack** [comment]
@gyuho sorry for ping, pinging as you seem to be the person responsible for releases (?)

**Comment by utrack** [comment]
JFYI - we at @ozonru forked v3.3.20 and applied the patch; we'll be maintaining this fork until the patch is merged to some release.
https://github.com/ozonru/etcd/releases/tag/v3.3.20%2Bgrpc1.27.1

**Comment by MilosSimic** [comment]
@utrack Thank you so much man! this fork worked for me with new grpc versions and etcd v3.3.20!!

**Comment by utrack** [comment]
@gyuho ping

**Comment by vtolstov** [comment]
gentle ping...
