### ISSUE TITLE
allowed-hostname only supports a single hostname

### ISSUE THREAD

**Issue by ryanmcnamara** [etcd-io/etcd#11728]
[--client-cert-allowed-hostname](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md) and [--peer-cert-allowed-hostname](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--peer-cert-allowed-hostname) only support setting a single hostname for validation.

The limitation on peer-cert-allowed-hostname isn't problematic for us, but it is problematic for --client-cert-allowed-hostname. We have multiple clients that need to communicate with etcd
* the k8s apiserver
* a sidecar to etcd that we use to exfil metrics and automate some manual actions
* a daemon that performs move leader actions preemptively on host termination

While as a workaround we *can* add an additional SAN to each of these clients that is common and configure etcd to allow *that* SAN, it would be much more convenient if we could just specify a list of valid hostnames. This is an FR to support this in some way, would be willing to try PRing this. Thanks!

etcd version: master a04b74d4b4ebced2aca96dde08cb73b04bcdc484

**Comment by jmhbnz** [comment]
Re-opening stale issue to track pr https://github.com/etcd-io/etcd/pull/18015.
