### ISSUE TITLE
Lease TTL less than 1 second?

### ISSUE THREAD

**Issue by Iulian7** [etcd-io/etcd#11746]
I am using the `clientv3/concurrency` package to elect leaders. This makes use of leases where the TTL can only be specified in seconds. I am wondering how this would work as it means even if set to the minimum value of 1 second, it would take at least 1 second for a master to be detected as down. 

Is there a way to set lease TTLs to < 1 second? 

Or perhaps I am missing a common pattern here? How is leader election normally achieved with the help of etcd? Or is this not a common use case?

**Comment by polyrabbit** [comment]
FYI, in current implementation, lessor will check for expired keys at least every [500 milli-seconds](https://github.com/etcd-io/etcd/blob/release-3.4/lease/lessor.go#L592).

**Comment by bugall** [comment]
> FYI, in current implementation, lessor will check for expired keys at least every [500 milli-seconds](https://github.com/etcd-io/etcd/blob/release-3.4/lease/lessor.go#L592).

？

**Comment by soul12345** [comment]
---Original---
