### ISSUE TITLE
Windows 10 Error. 

### ISSUE THREAD

**Issue by tebrizetayi** [etcd-io/etcd#11741]
I want to install etcd on my local machine. but get this error. My local pc is Windows 10 professional. How can I solve this issue?

**_> {"level":"info","ts":"2020-04-01T17:18:11.346+0200","caller":"etcdmain/etcd.go:84","msg":"failed to detect default host","error":"default host not supported on windows_amd64"}
> {"level":"warn","ts":"2020-04-01T17:18:11.347+0200","caller":"etcdmain/etcd.go:89","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
> {"level":"info","ts":"2020-04-01T17:18:11.348+0200","caller":"etcdmain/etcd.go:100","msg":"server has been already initialized","data-dir":"default.etcd","dir-type":"member"}
> {"level":"info","ts":"2020-04-01T17:18:11.351+0200","caller":"embed/etcd.go:113","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
> {"level":"info","ts":"2020-04-01T17:18:11.358+0200","caller":"embed/etcd.go:121","msg":"configuring client listeners","listen-client-urls":["http://localhost:2379"]}
> {"level":"info","ts":"2020-04-01T17:18:11.359+0200","caller":"embed/etcd.go:263","msg":"starting an etcd server","etcd-version":"3.5.0-pre","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.13.3","go-os":"windows","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd\\member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":false,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
> {"level":"info","ts":"2020-04-01T17:18:11.365+0200","caller":"etcdserver/backend.go:79","msg":"opened backend db","path":"default.etcd\\member\\snap\\db","took":"5.0455ms"}
> {"level":"info","ts":"2020-04-01T17:18:11.369+0200","caller":"etcdserver/raft.go:468","msg":"restarting local member","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","commit-index":18}
> {"level":"info","ts":"2020-04-01T17:18:11.370+0200","caller":"raft/raft.go:1521","msg":"8e9e05c52164694d switched to configuration voters=()"}
> {"level":"info","ts":"2020-04-01T17:18:11.370+0200","caller":"raft/raft.go:699","msg":"8e9e05c52164694d became follower at term 9"}
> {"level":"info","ts":"2020-04-01T17:18:11.370+0200","caller":"raft/raft.go:383","msg":"newRaft 8e9e05c52164694d [peers: [], term: 9, commit: 18, applied: 0, lastindex: 18, lastterm: 9]"}
> {"level":"info","ts":"2020-04-01T17:18:11.371+0200","caller":"api/capability.go:74","msg":"enabled capabilities for version","cluster-version":"3.5"}
> {"level":"info","ts":"2020-04-01T17:18:11.371+0200","caller":"membership/cluster.go:268","msg":"set cluster version from store","cluster-version":"3.5"}
> {"level":"warn","ts":"2020-04-01T17:18:11.376+0200","caller":"auth/store.go:1224","msg":"simple token is not cryptographically signed"}
> {"level":"info","ts":"2020-04-01T17:18:11.382+0200","caller":"etcdserver/quota.go:94","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
> {"level":"info","ts":"2020-04-01T17:18:11.384+0200","caller":"etcdserver/server.go:730","msg":"starting etcd server","local-member-id":"8e9e05c52164694d","local-server-version":"3.5.0-pre","cluster-id":"cdf818194e3a8c32","cluster-version":"3.5"}
> {"level":"warn","ts":"2020-04-01T17:18:11.384+0200","caller":"etcdserver/metrics.go:192","msg":"failed to get file descriptor usage","error":"cannot get FDUsage on windows"}
> {"level":"info","ts":"2020-04-01T17:18:11.384+0200","caller":"etcdserver/server.go:643","msg":"starting initial election tick advance","election-ticks":10}
> {"level":"info","ts":"2020-04-01T17:18:11.387+0200","caller":"raft/raft.go:1521","msg":"8e9e05c52164694d switched to configuration voters=(10276657743932975437)"}
> {"level":"info","ts":"2020-04-01T17:18:11.387+0200","caller":"membership/cluster.go:375","msg":"added member","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","added-peer-id":"8e9e05c52164694d","added-peer-peer-urls":["http://localhost:2380"]}
> {"level":"info","ts":"2020-04-01T17:18:11.387+0200","caller":"membership/cluster.go:505","msg":"updated cluster version","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","from":"3.5","from":"3.5"}
> {"level":"info","ts":"2020-04-01T17:18:11.388+0200","caller":"embed/etcd.go:510","msg":"serving peer traffic","address":"127.0.0.1:2380"}
> {"level":"info","ts":"2020-04-01T17:18:11.390+0200","caller":"embed/etcd.go:232","msg":"now serving peer/client/metrics","local-member-id":"8e9e05c52164694d","initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[]}
> {"level":"info","ts":"2020-04-01T17:18:12.573+0200","caller":"raft/raft.go:922","msg":"8e9e05c52164694d is starting a new election at term 9"}
> {"level":"info","ts":"2020-04-01T17:18:12.573+0200","caller":"raft/raft.go:712","msg":"8e9e05c52164694d became candidate at term 10"}
> {"level":"info","ts":"2020-04-01T17:18:12.574+0200","caller":"raft/raft.go:823","msg":"8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 10"}
> {"level":"info","ts":"2020-04-01T17:18:12.574+0200","caller":"raft/raft.go:764","msg":"8e9e05c52164694d became leader at term 10"}
> {"level":"info","ts":"2020-04-01T17:18:12.574+0200","caller":"raft/node.go:327","msg":"raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 10"}
> {"level":"info","ts":"2020-04-01T17:18:12.576+0200","caller":"etcdserver/server.go:1850","msg":"published local member to cluster through raft","local-member-id":"8e9e05c52164694d","local-member-attributes":"{Name:default ClientURLs:[http://localhost:2379]}","request-path":"/0/members/8e9e05c52164694d/attributes","cluster-id":"cdf818194e3a8c32","publish-timeout":"7s"}
> {"level":"info","ts":"2020-04-01T17:18:12.576+0200","caller":"embed/serve.go:97","msg":"ready to serve client requests"}
> {"level":"info","ts":"2020-04-01T17:18:12.576+0200","caller":"etcdmain/main.go:53","msg":"notifying init daemon"}
> {"level":"info","ts":"2020-04-01T17:18:12.576+0200","caller":"etcdmain/main.go:59","msg":"successfully notified init daemon"}
> {"level":"info","ts":"2020-04-01T17:18:12.580+0200","caller":"embed/serve.go:139","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"127.0.0.1:2379"}
> etcd
> 
>_**

**Comment by agargi** [comment]
@tebrizetayi I get this error when there is a bad configuration. For example, I specified the URL endpoints as HTTPS but did not provide any corresponding key/ cert configuration. Can you share the configuration you are using to start etcd?
