### ISSUE TITLE
cannot listen on TLS for 192.168.119.129:2380: KeyFile and CertFile are not presented

### ISSUE THREAD

**Issue by LIUKQSGITHUB** [etcd-io/etcd#11765]
command "systemctl start etcd" failed to start etcd service
command "journalctl -f" got detail message like title described :
cannot listen on TLS for 192.168.119.129:2380: KeyFile and CertFile are not presented
please help me find the reason.Thanks

my etcd version: v3.4

this is my etcd config file conf.yml:

name: etcd-01
data-dir: /opt/k8s/etcd/data
listen-client-urls: https://192.168.119.129:2379,https://127.0.0.1:2379
advertise-client-urls: https://192.168.119.129:2379
listen-peer-urls: https://192.168.119.129:2380
initial-advertise-peer-urls: https://192.168.119.129:2380
initial-cluster: etcd-01=https://192.168.119.129:2380
initial-cluster-token: etcd-cluster-token
initial-cluster-state: new
enable-grpc-gateway: true
auto-tls: true
cert-file: /opt/k8s/etcd/ssl/etcd.pem
key-file: /opt/k8s/etcd/ssl/etcd-key.pem
trusted-ca-file: /opt/k8s/etcd/ssl/rootca.pem
peer-auto-tls: true
peer-cert-file: /opt/k8s/etcd/ssl/etcd.pem
peer-key-file: /opt/k8s/etcd/ssl/etcd-key.pem
peer-trusted-ca-file: /opt/k8s/etcd/rootca.pem

**Comment by Orobas-D** [comment]
#11101

**Comment by Orobas-D** [comment]
You can Look as this #11101
