### ISSUE TITLE
How should i get the initialise key and then remove it.

### ISSUE THREAD

**Issue by ghost** [etcd-io/etcd#11761]
how would i get my initialise key of etcd cluster , and wan't to remove it,
i am using RHEL 7 but did not get anywhere how to get my initialise key.

**Comment by amadhaka** [comment]
please someone help ?  etcdctl get '' isn't working,

VERSION:
   3.2.26


Any changes in command with this version, did not found any documentation.

**Comment by jingyih** [comment]
`etcdctl get` is a v3 command. Doc [1] says if using released version earlier than 3.4, the command should include `ETCDCTL_API=3`.

[1] https://github.com/etcd-io/etcd/tree/master/etcdctl
