### ISSUE TITLE
v3 api returns 404 when start etcd with --config-file

### ISSUE THREAD

**Issue by Suse130224** [etcd-io/etcd#11767]
etcd Version: 3.4.0
Go Version: go1.12.9
Go OS/Arch: linux/amd64

1、when I start etcd with command "etcd", the v3/maintenance/status performs normally:
`charisu@pubbeta1-nostest1 ~> curl -X POST http://localhost:2379/v3/maintenance/status
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"95","raft_term":"8"},"version":"3.4.0","dbSize":"40960","leader":"10276657743932975437","raftIndex":"158","raftTerm":"8","raftAppliedIndex":"158","dbSizeInUse":"32768"}⏎  `
2、However, when I start etcd with a config file （yml） which is empty,  it started normally,  but v3/maintenance/status returns 404:
`charisu@pubbeta1-nostest1 ~> curl -X POST http://localhost:2379/v3/maintenance/status
404 page not found
`
3、In addition, other v3 api also returns 404

Should I specify something in the config file?

**Comment by yuuu11** [comment]
hi，I want to know how it was solved.
