### ISSUE TITLE
What characters should I use or not use in usernames on etcd?

### ISSUE THREAD

**Issue by hehechen** [etcd-io/etcd#11785]
`etcdctl --endpoints=https://localhost:2389 --ca-file=cn0/cacert.crt --cert-file=tem.crt --key-file=tem.pem -u root user add "A:B"`
I want to add user with username "A:B", But actually etcd add username "A", it showes
`User A created`
What characters should I use or not use in usernames on etcd?
ETCD version: 3.3.13

**Comment by tangcong** [comment]
A is username，B is password,character : is special

**Comment by hehechen** [comment]
> A is username，B is password,character : is special

Is there any other way to add a user name with character `:` ?

**Comment by tangcong** [comment]
etcdctl  can not  add a user name  with character ; , you can try to add special user name by clientv3. [example](https://github.com/etcd-io/etcd/blob/master/clientv3/example_auth_test.go).

**Comment by tangcong** [comment]
```
etcdctl user add hello:123 --no-password
etcdctl user passwd hello:123
```
it also works.

**Comment by tangcong** [comment]
it is better if username supports special characters :, can we add a password flag to optimize this issue?  how do you think so?  @mitake

**Comment by hehechen** [comment]
> ```
> etcdctl user add hello:123 --no-password
> etcdctl user passwd hello:123
> ```
> 
> it also works.

It doesn't work in etcd 3.3.13, showes `flag provided but not defined: -no-password`
what etcd version  support `--no-password` ?

**Comment by tangcong** [comment]
> > ```
> > etcdctl user add hello:123 --no-password
> > etcdctl user passwd hello:123
> > ```
> > 
> > 
> > it also works.
> 
> It doesn't work in etcd 3.3.13, showes `flag provided but not defined: -no-password`
> what etcd version support `--no-password` ?
3.4+

**Comment by tangcong** [comment]
> it is better if username supports special characters :, can we add a password flag to optimize this issue? how do you think so? @mitake

 this [pr](https://github.com/etcd-io/etcd/pull/9730) solved this issue.  etcd version 3.4+.

**Comment by mitake** [comment]
@hehechen yeah the problem comes from the old flag (it comes from v2)like `etcdctl user add <username:password>`. `A:B` will be interpreted as user A whose password is B. As @tangcong shared `--password` flag can avoid this problem. I feel the behavior is confusing so I personally want to remove `<username:password>` notation...
