### ISSUE TITLE
Broken link in issue template

### ISSUE THREAD

**Issue by MikeSpreitzer** [etcd-io/etcd#11780]
When I start to create a new issue, it is pre-filled with this remark:

> Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

But that link is broken.  The correct link uses a dash rather than an underscore.

**Comment by krukkrz** [comment]
can I pick this?

**Comment by spzala** [comment]
Thanks for reporting @MikeSpreitzer Fixed here https://github.com/etcd-io/etcd/pull/11832
