### ISSUE TITLE
Cannot get the golang package of clientv3

### ISSUE THREAD

**Issue by dxvgef** [etcd-io/etcd#11808]
I imported `go.etcd.io/etcd/clientv3` in the project, and I get an error when executing the `go mod tidy` command:
```
github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.4: parsing go.mod:
         module declares its path as: go.etcd.io/bbolt
                 but was required as: github.com/coreos/bbolt
```
I am in a hurry to work now, how can I solve it quickly?

**Comment by gdbelvin** [comment]
use etcd v3.4.x

**Comment by dxvgef** [comment]
> use etcd v3.4.x

I use 'go get' command could not find the v3.4 version, how did you do it?

**Comment by gdbelvin** [comment]
With the script here: https://github.com/etcd-io/etcd/issues/11154

**Comment by asmexcaliburwoods** [comment]
This can be fixed with `go mod download go.etcd.io/etcd@v3.5.0`

**Comment by lishaoshu1240** [comment]
i have the same issue.
