### ISSUE TITLE
etcd 3.2.25(3.4.1) high memory usage  16G with kubernetes 1.18 

### ISSUE THREAD

**Issue by pacoxu** [etcd-io/etcd#11800]
![memory](https://user-images.githubusercontent.com/2010320/79822784-997a9e00-83c4-11ea-9ca9-4cc2a454c430.png)

here is the heap of etcd 

ETCD version 3.2.25 （tried to upgrade to 3.4.1，is still not solved）
Kubernetes Version 1.18.0

After etcd start, it uses about 16G memory of host(24G ).
Any suggestions about how to reduce the memory usage of etcd ? 

-  we tried to set --snapshot-count to 5000(default 10000), to make snapshot mem usage down. But according to the heap file, snapshot use about 20% memory which is about 3GB mem. 

Other clues:
![企业微信截图_e9ee4b26-ff66-4bf0-802c-d4f032b58aea](https://user-images.githubusercontent.com/2010320/79823023-376e6880-83c5-11ea-8bd6-f201bd7044f7.png)
wal_fsync_duration_seconds is about 20.
Does this mean that the disk is so slow? Will slow disk result in high memory usage ? 

Some other metrics info:
` process_resident_memory_bytes 1.4309425152e+10 `

SVG of the heap file is like below:

**Comment by tangcong** [comment]
can you provide heap profile and all metrics?  
```
--enable-pprof
Enable runtime profiling data via HTTP server. Address is at client URL + "/debug/pprof/"
default: false
env variable: ETCD_ENABLE_PPROF
```
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md

**Comment by pacoxu** [comment]
heap file
http://qiniu-download-public.daocloud.io/memory.svg

pprof file
http://qiniu-download-public.daocloud.io/profile.svg

metrics file 
http://qiniu-download-public.daocloud.io/metric.file

@tangcong

**Comment by pacoxu** [comment]
My cluster which works well
`[root@paco307 dce]# dd if=/dev/urandom of=/dev/sda2  bs=4k count=1000 oflag=dsync
1000+0 records in
1000+0 records out
4096000 bytes (4.1 MB) copied, 0.379357 s, 10.8 MB/s`

Problem cluster
`dd if=/dev/random of=./testdd bs=4k count=1000 oflag=dsync
1000+0 records in
1000+0 records out
82232 bytes (82 kB) copied, 1.4 s, 58.4 MB/s`

However, I am confused whether bad disk io would make etcd mem so high

**Comment by tangcong** [comment]
problem cluster enable v2 API? how much keys? 
```
etcd_debugging_store_reads_total{action="get"} 7871
etcd_debugging_store_reads_total{action="getRecursive"} 2
# HELP etcd_debugging_store_watch_requests_total Total number of incoming watch requests (new or reestablished).
# TYPE etcd_debugging_store_watch_requests_total counter
etcd_debugging_store_watch_requests_total 0
# HELP etcd_debugging_store_watchers Count of currently active watchers.
# TYPE etcd_debugging_store_watchers gauge
etcd_debugging_store_watchers 0
# HELP etcd_debugging_store_writes_total Total number of writes (e.g. set/compareAndDelete) seen by this member.
# TYPE etcd_debugging_store_writes_total counter
etcd_debugging_store_writes_total{action="compareAndSwap"} 125
etcd_debugging_store_writes_total{action="create"} 11
etcd_debugging_store_writes_total{action="set"} 2212
```

**Comment by pacoxu** [comment]
More than 10000 keys.

However I change etcd boot params to --enable-v2=false, the memory is still high.

**Comment by tangcong** [comment]
it will also load v2 data into memory if it is a test cluster, can you backup old data and  try to delete all v2 keys and restart etcd?

**Comment by pacoxu** [comment]
@tangcong  they may save about 100 millions keys in an etcd key dir. 

Those keys cause memory bomb. After remove those etcd v2 keys, it works well now. Thanks a lot. 

Is there a limitation of etcd key limits？
