### ISSUE TITLE
First few etcd writes are missing during init time

### ISSUE THREAD

**Issue by Sunanda-S2** [etcd-io/etcd#11827]
Using "github.com/coreos/etcd/clientv3"

In my application, to ensure that etcd service is ready, I wait until etcd client Status() returns a nil error. Then I write my key/value to it. However, I see that the initial writes are missing in etcd. Is status() not the right API to wait for etcd to be fully ready?

Here is a wrapper I wrote around status check.

// Status of etcd client endpoints, returns error if any endpoint failed status check
func (e *S2Etcd) Status() error {
	for _, ep := range e.Endpoints {
		ctx, cancel := context.WithTimeout(context.Background(), e.Timeout)
		_, err := e.client.Status(ctx, ep)
		cancel()
		if err != nil {
			e.logger.Debugwt(e.logFlag, "S2Etcd: Status failed", "err", err)
			e.Stats.StatusErr++
			return err
		}
		e.logger.Debugwt(e.logFlag, "S2Etcd: Status ok")
	}
	return nil
}

**Comment by xiang90** [comment]
Not for write operations. You need to wrap it. Or you can check how etcdctl implements the healthy checking.
