### ISSUE TITLE
10~80kB/s disk write by etcd every a few second in new kubernetes cluster

### ISSUE THREAD

**Issue by windayski** [etcd-io/etcd#11831]
I have a newly  installed small k8s cluster of 3 masters and 1 worker.  
Using iotop command, I saw 10~80kB/s disk write by etcd every a few second (<5s). 
This is new k8s cluster with no workload, so it's quite strange to get this disk write frequency.

Is this normal?

etcd 3.4.2
kubernetes 1.16.2

**Comment by hexfusion** [comment]
If you watched the keyspace you would probably see a fair amount of event chatter. I think this is probably normal. 

The below one-liner does not provide TLS flags etc but you can fairly easily see exactly what is happening. The out file will contain all of the data written during that time and can grow very quickly so keep that in mind. 

```
etcdctl watch / --prefix -w fields > out | watch 'cat out | grep -oP "(?<=/kubernetes.io\/).+?(?=\/)" | sort | uniq -c'
```

**Comment by windayski** [comment]
@hexfusion  Thanks! 
I got some output of `etcdctl watch`
Maybe it's normal.

`"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320535
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/masterleases/192.168.202.156"
"CreateRevision" : 319734
"ModRevision" : 320535
"Version" : 38
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12+\n\x12\n\x00\x12\x00\x1a\x00\"\x00*\x002\x008&B\x00z\x00\x12\x15\n\x13\n\x0f192.168.202.156\x1a\x00\x1a\x00\"\x00"
"Lease" : 8357680126742175034
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320536
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/leases/kube-node-lease/slave1"
"CreateRevision" : 102
"ModRevision" : 320536
"Version" : 12327
"Value" : "k8s\x00\n$\n\x1bcoordination.k8s.io/v1beta1\x12\x05Lease\x12\xa9\x01\n\x8d\x01\n\x06slave1\x12\x00\x1a\x0fkube-node-lease\"\x00*$952748f9-8aea-11ea-ae68-fa163e21647d2\x008\x00B\b\b߲\xab\xf5\x05\x10\x00j8\n\x04Node\x1a\x06slave1\"$8f1f3ede-8aea-11ea-ae68-fa163e21647d*\x02v1z\x00\x12\x17\n\x06slave1\x10(\"\v\b\x8b\xaf\xb3\xf5\x05\x10\xa9\x85\xb9-\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320537
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-controller-manager"
"CreateRevision" : 270
"ModRevision" : 320537
"Version" : 51362
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xe5\x02\n\xe2\x02\n\x17kube-controller-manager\x12\x00\x1a\vkube-system\"\x00*$b7d09800-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x99\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_87c909cf-8afe-11ea-8b44-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T13:00:53Z\",\"renewTime\":\"2020-05-02T02:14:35Z\",\"leaderTransitions\":5}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320538
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/cloud-controller-manager"
"CreateRevision" : 4551
"ModRevision" : 320538
"Version" : 51703
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xee\x02\n\xeb\x02\n\x18cloud-controller-manager\x12\x00\x1a\vkube-system\"\x00*$22571341-8aed-11ea-ae68-fa163e21647d2\x008\x00B\b\b\xa7\xbb\xab\xf5\x05\x10\x00b\x87\x02\n(control-plane.alpha.kubernetes.io/leader\x12\xda\x01{\"holderIdentity\":\"cloud-controller-manager-54b7c4fc7-jptv2_f67838d4-29cd-41aa-979b-623543ee3160\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-05-01T18:30:48Z\",\"renewTime\":\"2020-05-02T02:14:36Z\",\"leaderTransitions\":8}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320539
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-scheduler"
"CreateRevision" : 262
"ModRevision" : 320539
"Version" : 51304
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xdc\x02\n\xd9\x02\n\x0ekube-scheduler\x12\x00\x1a\vkube-system\"\x00*$b66f36a4-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x97\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_3158e118-8b9e-11ea-9d2f-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T17:32:12Z\",\"renewTime\":\"2020-05-02T02:14:35Z\",\"leaderTransitions\":6}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320540
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/leases/kube-node-lease/master3"
"CreateRevision" : 101
"ModRevision" : 320540
"Version" : 12326
"Value" : "k8s\x00\n$\n\x1bcoordination.k8s.io/v1beta1\x12\x05Lease\x12\xad\x01\n\x8f\x01\n\amaster3\x12\x00\x1a\x0fkube-node-lease\"\x00*$952734d5-8aea-11ea-ae68-fa163e21647d2\x008\x00B\b\b߲\xab\xf5\x05\x10\x00j9\n\x04Node\x1a\amaster3\"$8effdc35-8aea-11ea-ae68-fa163e21647d*\x02v1z\x00\x12\x19\n\amaster3\x10(\"\f\b\x8d\xaf\xb3\xf5\x05\x10\x8e\xb9\xef\xfc\x02\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320541
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/cloud-controller-manager"
"CreateRevision" : 4551
"ModRevision" : 320541
"Version" : 51704
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xee\x02\n\xeb\x02\n\x18cloud-controller-manager\x12\x00\x1a\vkube-system\"\x00*$22571341-8aed-11ea-ae68-fa163e21647d2\x008\x00B\b\b\xa7\xbb\xab\xf5\x05\x10\x00b\x87\x02\n(control-plane.alpha.kubernetes.io/leader\x12\xda\x01{\"holderIdentity\":\"cloud-controller-manager-54b7c4fc7-jptv2_f67838d4-29cd-41aa-979b-623543ee3160\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-05-01T18:30:48Z\",\"renewTime\":\"2020-05-02T02:14:39Z\",\"leaderTransitions\":8}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320542
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-controller-manager"
"CreateRevision" : 270
"ModRevision" : 320542
"Version" : 51363
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xe5\x02\n\xe2\x02\n\x17kube-controller-manager\x12\x00\x1a\vkube-system\"\x00*$b7d09800-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x99\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_87c909cf-8afe-11ea-8b44-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T13:00:53Z\",\"renewTime\":\"2020-05-02T02:14:38Z\",\"leaderTransitions\":5}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320543
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-scheduler"
"CreateRevision" : 262
"ModRevision" : 320543
"Version" : 51305
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xdc\x02\n\xd9\x02\n\x0ekube-scheduler\x12\x00\x1a\vkube-system\"\x00*$b66f36a4-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x97\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_3158e118-8b9e-11ea-9d2f-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T17:32:12Z\",\"renewTime\":\"2020-05-02T02:14:38Z\",\"leaderTransitions\":6}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320544
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/minions/master1"
"CreateRevision" : 15
"ModRevision" : 320544
"Version" : 2173
"Value" : "k8s\x00\n\n\n\x02v1\x12\x04Node\x12\x84+\n\xff\x03\n\amaster1\x12\x00\x1a\x00\"\x00*$8f3dd4ff-8aea-11ea-ae68-fa163e21647d2\x008\x00B\b\bղ\xab\xf5\x05\x10\x00Z \n\x17beta.kubernetes.io/arch\x12\x05amd64Z\x1e\n\x15beta.kubernetes.io/os\x12\x05linuxZ\x1b\n\x12kubernetes.io/arch\x12\x05amd64Z!\n\x16kubernetes.io/hostname\x12\amaster1Z\x19\n\x10kubernetes.io/os\x12\x05linuxZ&\n\x1enode-role.kubernetes.io/master\x12\x04trueZ'\n\x1fnode-role.kubernetes.io/monitor\x12\x04trueZ$\n\x1cnode-role.kubernetes.io/node\x12\x04trueb!\n\x1cnode.alpha.kubernetes.io/ttl\x12\x010bK\n#node.beta.kubernetes.io/instance-id\x12$32d91e27-127d-4b1b-a5c9-b70ca8f84dc0b4\n&node.beta.kubernetes.io/node-resources\x12\n4C/8G/200Gz\x00\x12#\n\x00\x12\x00\x1a\x00 \x00*\x19\n\x03pro\x12\x06master\x1a\nNoSchedule\x1a\xda&\n\n\n\x03cpu\x12\x03\n\x014\n\"\n\x11ephemeral-storage\x12\r\n\v206159828Ki\n\x14\n\rhugepages-1Gi\x12\x03\n\x010\n\x14\n\rhugepages-2Mi\x12\x03\n\x010\n\x15\n\x06memory\x12\v\n\t7968904Ki\n\f\n\x04pods\x12\x04\n\x0250\x12\n\n\x03cpu\x12\x03\n\x013\x12\"\n\x11ephemeral-storage\x12\r\n\v200916948Ki\x12\x14\n\rhugepages-1Gi\x12\x03\n\x010\x12\x14\n\rhugepages-2Mi\x12\x03\n\x010\x12\x15\n\x06memory\x12\v\n\t6444616Ki\x12\f\n\x04pods\x12\x04\n\x0250\x1a\x00\"[\n\x12NetworkUnavailable\x12\x05False\x1a\b\bǴ\xab\xf5\x05\x10\x00\"\b\bǴ\xab\xf5\x05\x10\x00*\nCalicoIsUp2\x1eCalico is running on this node\"p\n\x0eMemoryPressure\x12\x05False\x1a\b\b\x8d\xaf\xb3\xf5\x05\x10\x00\"\b\bղ\xab\xf5\x05\x10\x00*\x1aKubeletHasSufficientMemory2'kubelet has sufficient memory available\"a\n\fDiskPressure\x12\x05False\x1a\b\b\x8d\xaf\xb3\xf5\x05\x10\x00\"\b\bղ\xab\xf5\x05\x10\x00*\x18KubeletHasNoDiskPressure2\x1ckubelet has no disk pressure\"g\n\vPIDPressure\x12\x05False\x1a\b\b\x8d\xaf\xb3\xf5\x05\x10\x00\"\b\bղ\xab\xf5\x05\x10\x00*\x17KubeletHasSufficientPID2$kubelet has sufficient PID available\"b\n\x05Ready\x12\x04True\x1a\b\b\x8d\xaf\xb3\xf5\x05\x10\x00\"\b\b\xc1\xb3\xab\xf5\x05\x10\x00*\fKubeletReady21kubelet is posting ready status. AppArmor enabled*\x1d\n\nInternalIP\x12\x0f192.168.202.181*\x13\n\bHostname\x12\amaster12\x05\n\x03\b\x8aP:\xc5\x01\n baff2a34ece3474eb19aff48aad941bc\x12$32d91e27-127d-4b1b-a5c9-b70ca8f84dc0\x1a$ff9c50c8-d97a-40a1-9f94-e12f7c626d42\"\x105.0.0-29-generic*\x12Ubuntu 18.04.3 LTS2\x0fdocker://18.9.8:\av1.14.3B\av1.14.3J\x05linuxR\x05amd64B\xda\x01\n\x86\x01registry.inspurcloud.cn/library/cke/kubernetes/hyperkube-amd64@sha256:187915d9621cb2e3d41dbf166f979179313a36b658bac40c1833f439d6dc959f\nIregistry.inspurcloud.cn/library/cke/kubernetes/hyperkube-amd64:v1.14.3-10\x10\xf6\x87\xfd\x84\x02B\xc2\x01\n}registry.inspurcloud.cn/library/cke/calico/node-amd64@sha256:24258a33488dbb39c4c54260a43e4d8c7b16283d53dfcc757ba6580ea833a87a\n<registry.inspurcloud.cn/library/cke/calico/node-amd64:v3.8.0\x10\x82\xb2\xe6IB\xc0\x01\n|registry.inspurcloud.cn/library/cke/calico/cni-amd64@sha256:0dfb30856abb7fa3b4dc747a2fc240adc32030b960740948b0951624a5be14e3\n;registry.inspurcloud.cn/library/cke/calico/cni-amd64:v3.8.0\x10\xa4\xb0\xacDB\xbc\x01\nzregistry.inspurcloud.cn/library/iop/fluentd-plugin@sha256:092ea4d8b888ab8746cd517cc6831ce550ad46df4498a6d820429933417201ad\n9registry.inspurcloud.cn/library/iop/fluentd-plugin:v2.3.1\x10\xec\xb7\xdbBB\xeb\x01\n\x90\x01registry.inspurcloud.cn/library/cke/provisioner/local-static-provisioner@sha256:833a2151f6a466a69afcee8e9107b0c003c9552741346631098693d68ac63293\nQregistry.inspurcloud.cn/library/cke/provisioner/local-static-provisioner:v2.3.3-2\x10\xaf\x8c\xa7<B\xbc\x01\nzregistry.inspurcloud.cn/library/common/nginx-amd64@sha256:501215e3d4493a07ee00fd4b81fb1c8f63b4e9e565cd826d7fd3f4a36707cdad\n9registry.inspurcloud.cn/library/common/nginx-amd64:1.17.5\x10\x89˗<B\xc0\x01\n{registry.inspurcloud.cn/library/cke/etcd/etcd-amd64@sha256:d5ec1db190af6cc87f2603035aec0b6b861564d5945307843ab2acaf2ebf27de\n<registry.inspurcloud.cn/library/cke/etcd/etcd-amd64:v3.4.2-1\x10\xa7է/B7\n0registry.icp.com:5000/cke/indiskcsi-amd64:sctest\x10\xb4\xc0\xf9-B\xd0\x01\n\x84\x01registry.inspurcloud.cn/library/iop/vpa-admission-controller@sha256:b6d5fa8314a3ab9c2916df6a3422443ac4d435cccc1e4a527f47e07de1deb9b8\nBregistry.inspurcloud.cn/library/iop/vpa-admission-controller:0.5.1\x10\xd2\xfd\xf4%B\xd9\x01\n\x88\x01registry.inspurcloud.cn/library/iop/k8s-prometheus-adapter-amd64@sha256:e38391526a0078ac6f16d39997371741484446d6eb2b5928b1575537976ad83e\nGregistry.inspurcloud.cn/library/iop/k8s-prometheus-adapter-amd64:v0.4.1\x10\xa4\xdc\xfb\x1cBQ\nJregistry.icp.com:5000/library/cke/provisioner/csi-provisioner-amd64:v1.4.0\x10\xec\xb4\xcb\x1aBN\nGregistry.icp.com:5000/library/cke/provisioner/csi-attacher-amd64:v2.1.0\x10\xca\xfe\xb7\x18BM\nFregistry.icp.com:5000/library/cke/provisioner/csi-resizer-amd64:v0.4.0\x10\xb9\x9d\xb5\x18BQ\nJregistry.icp.com:5000/library/cke/provisioner/csi-snapshotter-amd64:v1.2.2\x10\xed\xdf\xcf\x17B\xad\x01\nsregistry.inspurcloud.cn/library/iop/coredns@sha256:8941e19d711e9a18dbc73decf216db2457c88af515c7a88768126c4a4e1722dc\n1registry.inspurcloud.cn/library/iop/coredns:1.6.5\x10\xe3\xdd\xe9\x13B\xc0\x01\n|registry.inspurcloud.cn/library/cke/calico/ctl-amd64@sha256:2c976b3d60c54037d23b310698163142678dac1fd8bc0506fd4ed7473d4b201e\n;registry.inspurcloud.cn/library/cke/calico/ctl-amd64:v3.8.0\x10\x99\xb7\x9e\x13B\xdd\x01\n\x87\x01registry.inspurcloud.cn/library/iop/iop_containers/alertmanager@sha256:b5cebc62b40edbbe98b44764dead913847453f18c3a7b105e8b6d3ca98ad7441\nLregistry.inspurcloud.cn/library/iop/iop_containers/alertmanager:v0.15.0-rc.1\x10\xad\xcb\xd2\x12B\xdd\x01\n\x8a\x01registry.inspurcloud.cn/library/cke/provisioner/cinder-provisioner@sha256:a88fc768543f98c2630ce6a23e7e2209a82741ecc19210f1ceba5036b8bfe624\nIregistry.inspurcloud.cn/library/cke/provisioner/cinder-provisioner:3.17.3\x10ޒ\xda\x11B\xcf\x01\n\x83\x01registry.inspurcloud.cn/library/iop/lachlanevenson/k8s-helm@sha256:742e01deb0b33feb74898e8caac43bef418f0f56d26a25b6970ae64a9bf5fbc3\nBregistry.inspurcloud.cn/library/iop/lachlanevenson/k8s-helm:v2.9.1\x10݃\xc9\x10B\xda\x01\n\x88\x01registry.inspurcloud.cn/library/iop/iop_containers/node-exporter@sha256:3c42a1967c65c53fdf7256f900925e848a765931a572fac32cc8b9165feb380c\nHregistry.inspurcloud.cn/library/iop/iop_containers/node-exporter:v0.16.0\x10\xa5\xd5\xf6\nB\xe2\x01\n\x8c\x01registry.inspurcloud.cn/library/iop/iop_containers/blackbox-exporter@sha256:db976d7d511caa0426ea326fcb25ed732eb62914d512fbfec80ca8fc13b03593\nLregistry.inspurcloud.cn/library/iop/iop_containers/blackbox-exporter:v0.12.0\x10\x9a\xfd\xf2\bB\xc9\x01\n\x82\x01registry.inspurcloud.cn/library/cke/kubernetes/pause-amd64@sha256:759c3f0f6493093a9043cc813092290af69029699ade0e3dbe024e968fcb7cca\n>registry.inspurcloud.cn/library/cke/kubernetes/pause-amd64:3.1\x10Ȩ-\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320545
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/leases/kube-node-lease/master2"
"CreateRevision" : 100
"ModRevision" : 320545
"Version" : 12343
"Value" : "k8s\x00\n$\n\x1bcoordination.k8s.io/v1beta1\x12\x05Lease\x12\xad\x01\n\x8f\x01\n\amaster2\x12\x00\x1a\x0fkube-node-lease\"\x00*$95272597-8aea-11ea-ae68-fa163e21647d2\x008\x00B\b\b߲\xab\xf5\x05\x10\x00j9\n\x04Node\x1a\amaster2\"$8f4ace98-8aea-11ea-ae68-fa163e21647d*\x02v1z\x00\x12\x19\n\amaster2\x10(\"\f\b\x90\xaf\xb3\xf5\x05\x10\xb0\x8e\xbf\xc0\x03\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320546
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/cloud-controller-manager"
"CreateRevision" : 4551
"ModRevision" : 320546
"Version" : 51705
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xee\x02\n\xeb\x02\n\x18cloud-controller-manager\x12\x00\x1a\vkube-system\"\x00*$22571341-8aed-11ea-ae68-fa163e21647d2\x008\x00B\b\b\xa7\xbb\xab\xf5\x05\x10\x00b\x87\x02\n(control-plane.alpha.kubernetes.io/leader\x12\xda\x01{\"holderIdentity\":\"cloud-controller-manager-54b7c4fc7-jptv2_f67838d4-29cd-41aa-979b-623543ee3160\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-05-01T18:30:48Z\",\"renewTime\":\"2020-05-02T02:14:41Z\",\"leaderTransitions\":8}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320547
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-controller-manager"
"CreateRevision" : 270
"ModRevision" : 320547
"Version" : 51364
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xe5\x02\n\xe2\x02\n\x17kube-controller-manager\x12\x00\x1a\vkube-system\"\x00*$b7d09800-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x99\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_87c909cf-8afe-11ea-8b44-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T13:00:53Z\",\"renewTime\":\"2020-05-02T02:14:40Z\",\"leaderTransitions\":5}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320548
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/masterleases/192.168.202.154"
"CreateRevision" : 286023
"ModRevision" : 320548
"Version" : 1245
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12,\n\x13\n\x00\x12\x00\x1a\x00\"\x00*\x002\x008\xdd\tB\x00z\x00\x12\x15\n\x13\n\x0f192.168.202.154\x1a\x00\x1a\x00\"\x00"
"Lease" : 3921071543826917135
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320549
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/kube-scheduler"
"CreateRevision" : 262
"ModRevision" : 320549
"Version" : 51306
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xdc\x02\n\xd9\x02\n\x0ekube-scheduler\x12\x00\x1a\vkube-system\"\x00*$b66f36a4-8aea-11ea-8a48-fa163e4d211b2\x008\x00B\b\b\x97\xb3\xab\xf5\x05\x10\x00b\xff\x01\n(control-plane.alpha.kubernetes.io/leader\x12\xd2\x01{\"holderIdentity\":\"inspurtest14-9ktj2yndgv-master-2_3158e118-8b9e-11ea-9d2f-fa163e21647d\",\"leaseDurationSeconds\":25,\"acquireTime\":\"2020-05-01T17:32:12Z\",\"renewTime\":\"2020-05-02T02:14:41Z\",\"leaderTransitions\":6}z\x00\x1a\x00\"\x00"
"Lease" : 0
"ClusterID" : 8705533058034212713
"MemberID" : 13754997003954009706
"Revision" : 320550
"RaftTerm" : 18
"Type" : PUT
"Key" : "/registry/services/endpoints/kube-system/cloud-controller-manager"
"CreateRevision" : 4551
"ModRevision" : 320550
"Version" : 51706
"Value" : "k8s\x00\n\x0f\n\x02v1\x12\tEndpoints\x12\xee\x02\n\xeb\x02\n\x18cloud-controller-manager\x12\x00\x1a\vkube-system\"\x00*$22571341-8aed-11ea-ae68-fa163e21647d2\x008\x00B\b\b\xa7\xbb\xab\xf5\x05\x10\x00b\x87\x02\n(control-plane.alpha.kubernetes.io/leader\x12\xda\x01{\"holderIdentity\":\"cloud-controller-manager-54b7c4fc7-jptv2_f67838d4-29cd-41aa-979b-623543ee3160\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-05-01T18:30:48Z\",\"renewTime\":\"2020-05-02T02:14:43Z\",\"leaderTransitions\":8}z\x00\x1a\x00\"\x00"
"Lease" : 0`

**Comment by xiang90** [comment]
Kubelet is updating its lease for heartbeats. This is a normal behavior of k8s.
