### ISSUE TITLE
Can etcd use public IP communication? Can only use intranet IP address?

### ISSUE THREAD

**Issue by zhuyouzhufu** [etcd-io/etcd#11839]
Now, I have three public servers and want to build a 3-node cluster. But he had a communication timeout. If you change all IP addresses to public IP addresses, the following error messages will appear:"listen tcp 47.xxx.xxx.163:2380: bind: cannot assign requested address"

**Comment by zhuyouzhufu** [comment]
Novice, if the questions asked are very low-level, please forgive me a lot

**Comment by agargi** [comment]
@zhuyouzhufu It depends on where you are running the servers. For example, if its AWS, AWS does not allow you to bind to public IP addresses and you can bind to private IP addresses alone. You can bind using IP address: 0.0.0.0. For example,

etcd --listen-client-urls http://0.0.0.0:2838 --advertise-client-urls http://0.0.0.0:2838
