### ISSUE TITLE
High availability is not working, when main leader is down. 

### ISSUE THREAD

**Issue by knraju483** [etcd-io/etcd#11842]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
HI, 

Could you please let us know, if i have to make any separate configuration to make the other nodes also master, when main leader is going down. 

Due to this, K8s clustering is not working. 

Regards
RAJU KARRI

**Comment by tedyu** [comment]
```
K8s clustering is not working.
```
Can you describe in more detail the problem you observed ?
