### ISSUE TITLE
How to get a mock Etcd for unit test?

### ISSUE THREAD

**Issue by wjhuang2016** [etcd-io/etcd#11849]
I want to use etcd to test my program, and I need a mock etcd (used it in my unit test). However, I'm confused that which API I should use. After I read the document of the etcd, I found that there may be two options for me.
1. start a cluster like the example in /embed/doc.go, then use the client to connect it.
2. start a cluster and get the client by integration.NewClusterV3
It seems that option two is convenient. However, the document says it's used in internal testing, and I'm not sure is it ok to use it in my unit test.

Can anyone give me some advice? Thanks.

**Comment by dongzerun** [comment]
use testify library to create mock of KV, TXN,WATCHER ....etcd
```
			etcdFn: func() *clientv3.Client {
				resp := &clientv3.GetResponse{}
				kv := &mocks.KV{}
				kv.On("Get", mock.Anything, "/leader").Return(resp, nil)
				return &clientv3.Client{KV: kv}
			}
```
like this to mock etcd client @wjhuang2016

**Comment by wjhuang2016** [comment]
Hi, @dongzerun.
Thank you for your reply, however, it's not convenient to use the testify library. I want to do many operations like put, get, and watch. It's tough to mock every response. What I need is an etcd cluster that behaves like real etcd cluster and providing some functionality and good performance.

**Comment by dongzerun** [comment]
unit test shouldn't rely on thirdpart services, testify is enough for your case

**Comment by tisonkun** [comment]
@wjhuang2016 I think in pingcap/tidb repo where might be the background of the question, we are migrate tests to testify by https://github.com/pingcap/tidb/issues/26022 and the mock utilities are there. You can try to make use of them and create a mock such as for `TestFailNewSession` and reduce the overhead.
