### ISSUE TITLE
`go get` error getting new v3 pkg

### ISSUE THREAD

**Issue by TisonKun** [etcd-io/etcd#11854]
```
$ go get -v go.etcd.io/etcd/v3
go get go.etcd.io/etcd/v3: module go.etcd.io/etcd@upgrade found (v3.3.20+incompatible), but does not contain package go.etcd.io/etcd/v3
```

**Comment by TisonKun** [comment]
Now it works. But why?

**Comment by xiang90** [comment]
What do you mean by "now it works"? does it work for you or not?

**Comment by TisonKun** [comment]
> What do you mean by "now it works"? does it work for you or not?

Now I can get etcd source code by `go get -v go.etcd.io/etcd/v3`

**Comment by xiang90** [comment]
OK. Glad it works now.
