### ISSUE TITLE
balancer.go : too many errors

### ISSUE THREAD

**Issue by vashish1** [etcd-io/etcd#11875]
In the **etcd/clientv3/balancer/balancer.go** file there are many errors which are causing issue while building the project which uses this.

It shows `.\..\github.com\coreos\etcd\clientv3\balancer\balancer.go:276:3: too many errors`

Few of those errors are:

`cannot use b.cfg.Logger (type *"github.com/coreos/etcd/vendor/go.uber.org/zap".Logger) as type *"go.etcd.io/etcd/vendor/go.uber.org/zap".Logger in argument to "go.etcd.io/etcd/clientv3/balancer/connectivity".New`

`cannot use old (type "github.com/coreos/etcd/vendor/google.golang.org/grpc/connectivity".State) as type "go.etcd.io/etcd/vendor/google.golang.org/grpc/connectivity".State in argument to bb.connectivityRecorder.RecordTransition`

**Comment by Gaukas** [comment]
Are you building the master branch or one of the release? The version might help.

**Comment by vashish1** [comment]
I am building the version. v3

**Comment by Gaukas** [comment]
v3.?.? 
I assume you might not be building from an officially released version. If that's not the case and you did download the source from the release page, please keep looking for help.
