### ISSUE TITLE
How to run ETCD benchmark tool

### ISSUE THREAD

**Issue by Sindica** [etcd-io/etcd#11887]
I have read issue https://github.com/etcd-io/etcd/issues/8386 and https://github.com/etcd-io/etcd/issues/10453, still don't have a successful run of ETCD benchmark tool.

Steps I used (mostly in AWS, also tried GCP, had the same result):
1. Got 1 ubuntu 1604 VM for ETCD server. Installed ETCD 3.4.4
2. One ubuntu 1604 VM for benchmark tool. Checked out ETCD branch release 3.4, built benchmark tool using go build; installed etcdctl 3.4.4
3. Started ETCD server 1, followed the instruction on https://etcd.io/docs/v3.4.0/demo/
4. Tried "etcdctl --endpoints=$ENDPOINTS member list" on benchmark test host (ETCD client), it returned correct value
5. Followed instruction on https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md, run command "benchmark --endpoints=${HOST_1} --target-leader --conns=1 --clients=1 put --key-size=8 --sequential-keys --total=10 --val-size=256"
6. Benchmark tool just halts there and not print out anything after 30 minutes. I tried total 100 and 10000 as well. Same behavior

I have checked the following:
1. Debug benchmark tool, it starts a server, halts there and does nothing
2. "top -p {etcd_process_id}" on ETCD server, the cpu and memory usage is very little, not changing
3. "top -p {benchmark_process_id}" on ETCD client, the cpu and memory usage is very little, not changing
4. Checked timestamp and file size of etcd db file and wal folders. Files have the same timestamps as installed and db file size is very small (20,480 bytes)
5. tcpdump on both ETCD client and server host, no traffic from/to the other host

Questions:
1. Shouldn't the tool run very fast when total is very small, say < 100?
2. How long it is supposed to run for total=100, total=10000, total=1000000 respectively?
3. Does it run in AWS? Or it only works on GCP? (I tried both, it has the same behavior, but on GCP I only waited for a minute for total=1)

**Comment by Sindica** [comment]
Can someone taking a look at this issue? Thanks

**Comment by spzala** [comment]
> I have read issue #8386 and #10453, still don't have a successful run of ETCD benchmark tool.
> 
> Steps I used (mostly in AWS, also tried GCP, had the same result):
> 
>     1. Got 1 ubuntu 1604 VM for ETCD server. Installed ETCD 3.4.4
> 
>     2. One ubuntu 1604 VM for benchmark tool. Checked out ETCD branch release 3.4, built benchmark tool using go build; installed etcdctl 3.4.4
> 
>     3. Started ETCD server 1, followed the instruction on https://etcd.io/docs/v3.4.0/demo/
> 
>     4. Tried "etcdctl --endpoints=$ENDPOINTS member list" on benchmark test host (ETCD client), it returned correct value
> 
>     5. Followed instruction on https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md, run command "benchmark --endpoints=${HOST_1} --target-leader --conns=1 --clients=1 put --key-size=8 --sequential-keys --total=10 --val-size=256"
> 
>     6. Benchmark tool just halts there and not print out anything after 30 minutes. I tried total 100 and 10000 as well. Same behavior
> 
> 
> I have checked the following:
> 
>     1. Debug benchmark tool, it starts a server, halts there and does nothing
> 
>     2. "top -p {etcd_process_id}" on ETCD server, the cpu and memory usage is very little, not changing
> 
>     3. "top -p {benchmark_process_id}" on ETCD client, the cpu and memory usage is very little, not changing
> 
>     4. Checked timestamp and file size of etcd db file and wal folders. Files have the same timestamps as installed and db file size is very small (20,480 bytes)
> 
>     5. tcpdump on both ETCD client and server host, no traffic from/to the other host
> 
> 
> Questions:
> 
>     1. Shouldn't the tool run very fast when total is very small, say < 100?
> 
>     2. How long it is supposed to run for total=100, total=10000, total=1000000 respectively?
> 
>     3. Does it run in AWS? Or it only works on GCP? (I tried both, it has the same behavior, but on GCP I only waited for a minute for total=1)

I have not run it on AWS or GCP but I tried running benchmark, from the master branch, recently on my local VM and it works fine. Can you please try similarly and see how that works for you? I installed benchmark using go get go.etcd.io/etcd/tools/benchmark
The only reason I can think of tool hanging is that the endpoint is not responding, so please try it locally for a test while making sure etcd server is running.
As you would expect, it should run very fast for the small tests you are running.

**Comment by Sindica** [comment]
I cannot run it from master branch as it's requires higher go version, which is not compatible with my project. I am currently using golang 1.12.12.
I am sure ETCD is working as I can access it locally and remotely via etcdctl

**Comment by Sindica** [comment]
I was able to fix the problem by adding port to HOST. Many related doc did not mention host needs to have port #, such as https://etcd.io/docs/v3.4.0/demo/

**Comment by spzala** [comment]
> I was able to fix the problem by adding port to HOST. Many related doc did not mention host needs to have port #, such as https://etcd.io/docs/v3.4.0/demo/

@Sindica that's great, glad it worked out. If doc is not clear or missing the info, would you see if you can create a PR to make your findings available in the doc. Also, I believe we can close this issue now? Thanks!
