### ISSUE TITLE
Is it possible to disable disk I/O to make it memory-based?

### ISSUE THREAD

**Issue by Gaukas** [etcd-io/etcd#11883]
I am working on a latency-sensitive project and don't want to have the disk I/O to slow it down.
The tmpfs would be my worst solution but I wonder if it is possible to disable the disk I/O internally to make the storage memory-based? 
I didn't see any instructions or relative discussions. Any guidance/suggestions are welcomed. Thank you.

**Comment by xiang90** [comment]
no memory storage support yet. i guess temfs is your best bet right now.

**Comment by Gaukas** [comment]
Fair enough. Thanks!

**Comment by warmchang** [comment]
Part of this: https://github.com/etcd-io/etcd/pull/11946
