### ISSUE TITLE
Sanity check .snap.db files before swapping them in

### ISSUE THREAD

**Issue by jpbetz** [etcd-io/etcd#11895]
During snapshot recovery, a `.snap.db` file is created and then moved to replace the main `db` file:

https://github.com/etcd-io/etcd/blob/7cc2f8a4114bbc9ca5fe5381504b9c4096fca1ac/etcdserver/backend.go#L55-L64

Before doing the file rename, it seems like we should do a final sanity check of the `.snap.db` file. For example, we could make sure we are able to open it and also check the consistent index is what we expect.

cc @YoyinZyc @jingyih

**Comment by jpbetz** [comment]
@YoyinZyc is this something you have time for? It should be a pretty small change.

**Comment by YoyinZyc** [comment]
> @YoyinZyc is this something you have time for? It should be a pretty small change.

Sure.

**Comment by jpbetz** [comment]
We should probably do the same sanity before doing this rename too:

https://github.com/etcd-io/etcd/blob/96cce208c2cb9e70ac3573b3f76eed7c84d262d1/etcdserver/api/snap/db.go#L60

**Comment by YoyinZyc** [comment]
@jpbetz 
I checked two callers of `openSnapshotBackend`. Both of them has already checked whether the snapshot is outdated.
https://github.com/etcd-io/etcd/blob/5e2815e9cd657702fd798aed041e0bf3590e56d2/etcdserver/backend.go#L101-L103

https://github.com/etcd-io/etcd/blob/5e2815e9cd657702fd798aed041e0bf3590e56d2/etcdserver/server.go#L1074-L1082
And `ss.DbFilePath` has already checked the existence of the file.
https://github.com/etcd-io/etcd/blob/5e2815e9cd657702fd798aed041e0bf3590e56d2/etcdserver/api/snap/db.go#L79-L96

As for the rename in here https://github.com/etcd-io/etcd/blob/5e2815e9cd657702fd798aed041e0bf3590e56d2/etcdserver/api/snap/db.go#L60
I think it just renames tmp film to new snap file?

Is it necessary to add more check or did I miss something?
