### ISSUE TITLE
prometheus etcd exporter on kubernetes

### ISSUE THREAD

**Issue by SrinivReddy** [etcd-io/etcd#11891]
Hi Team,

I have configured etcd ccluster on kubernetes cluster and I have prometheus server.  I need to export etcd metrics to prometheus. Is there any prometheus etcd exporter available?

**Comment by polyrabbit** [comment]
I suppose etcd already exported metrics by default.

You can enable it by `etcd --listen-metrics-urls http://localhost:8080`, and get the metrics from `http://localhost:8080/metrics`.

**Comment by SrinivReddy** [comment]
closed
