### ISSUE TITLE
etcd: export version as prometheus metric

### ISSUE THREAD

**Issue by miekg** [etcd-io/etcd#11893]
etcd doesn't report it's version in the metrics it exports. I.e coredns export a `coredns_build_info` with labels containing the version and the go version that was used to build the binary.

Is there a reason this is not supported? If not I'll gladly add a `etcd_build_info` metrics that export this information.

**Comment by gmarek** [comment]
@wojtek-t - in case you're also interested in this.

**Comment by wojtek-t** [comment]
@ptabor

**Comment by hexfusion** [comment]
`etcd_server_version` ?

etcd_server_version{server_version="3.4.7"}
