### ISSUE TITLE
etcd performance: ssd and hdd got same performance ？

### ISSUE THREAD

**Issue by nicktming** [etcd-io/etcd#11908]
Test Env: 
- 1 machine of etcd server （16vcpus, 263G, 50G ssd and 100G hdd）
- etcd client and etcd server are the same machine

Test script: 

- ./benchmark --cacert=ca.pem --cert=etcd.pem --key=etcd-key.pem --endpoints=https://${IP}:2379 --target-leader --conns=100 --clients=1000 put --key-size=8 --sequential-keys --total=100000000 --val-size=256

Test Result:
ssd:
Summary:
  Total:	6505.5082 secs.
  Slowest:	0.9784 secs.
  Fastest:	0.0003 secs.
  Average:	0.0650 secs.
  Stddev:	0.0378 secs.
  Requests/sec:	15371.5893

hdd:
Summary:
  Total:	6610.4594 secs.
  Slowest:	1.0960 secs.
  Fastest:	0.0003 secs.
  Average:	0.0661 secs.
  Stddev:	0.0402 secs.
  Requests/sec:	15127.5416

The result between ssd and hdd got almost the same performance, which let me a little confused, so is there any suggestion for me ？

**Comment by agargi** [comment]
One plausible reason can be that you are running only one etcd server node. The disk write performance will have more profound impact when you are an etcd cluster (at least 3 nodes). You might want to refer to article below & more specifically use the disk benchmarking tool recommended in the article.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md
