### ISSUE TITLE
Base image referenced in Dockerfile-release does not exist

### ISSUE THREAD

**Issue by brianredbeard** [etcd-io/etcd#11901]
Attempting to build a release container image presently fails, unable to find the image `us.gcr.io/k8s-artifacts-prod/build-image:v2.1.0`:

```
$ docker build -t etcd -f Dockerfile-release .
Sending build context to Docker daemon     54MB
Step 1/8 : FROM us.gcr.io/k8s-artifacts-prod/build-image:v2.1.0
manifest for us.gcr.io/k8s-artifacts-prod/build-image:v2.1.0 not found
```

**Comment by gyuho** [comment]
ref. https://github.com/etcd-io/etcd/pull/11885

@jchauncey can you take a look?

**Comment by jchauncey** [comment]
@gyuho pr submitted. sorry about that
