### ISSUE TITLE
etcdctl del --prefix=true as curl command

### ISSUE THREAD

**Issue by Tobias4872** [etcd-io/etcd#11914]
Hi,

this is a question not an issue - I am using the etcd version 3.4.7 with API version 3.4 and am trying to achieve "etcdctl del --repfix=true <key>" via a curl command. I know that I have to pass the key and a range_end, but unfortunately cannot make anything out of the protobuf description of the range_end parameter. Can someone help me to figure out what the curl command needs to look like for a) deleting keys with a given prefix and b) is there a way to clean all keys?

`curl --request POST --url http://localhost:2379/v3/kv/deleterange --header 'content-type: application/json' --data '{"key": "my_key_base64","range_end": "???"}'`

Thanks so much,
   Tobias.

**Comment by spzala** [comment]
a)For a specific range your value to range_end would be base64 ending key (e.g. ` '{"key": "Zm9v", "range_end": "AA=="}' ` to delete foo*`) 
b)To clean up all the keys (similar to `etcdctl del --prefix ""`) please try 
`curl -L http://localhost:2379/v3/kv/deleterange -X POST -d '{"key": "AA==", "range_end": "AA=="}'`
As it says in the related doc, "If range_end is '\0', the range is all keys greater than or equal to the key argument.", https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-deleterangerequest-etcdserveretcdserverpbrpcproto 
`range_end is the key following the last key to delete for the range [key, range_end). If range_end is not given, the range is defined to contain only the key argument. If range_end is one bit larger than the given key, then the range is all the keys with the prefix (the given key). If range_end is '\0', the range is all keys greater than or equal to the key argument.`
