### ISSUE TITLE
Change the GRPC version

### ISSUE THREAD

**Issue by velann21** [etcd-io/etcd#11915]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

Things noticed.

1) google.golang.org/grpc v1.26.0 version is having the known issue as below
undefined: grpc.SupportPackageIsVersion6
undefined: grpc.ClientConnInterface

The suggested fix for this issue to migrate the GRPC from 1.26.0 to 1.27.0
Reference:
----------
(https://github.com/grpc/grpc-go/issues/3347)

1. Since am using the both the grpc and etcd hand in hand I couldn't upgrade the grpc alone on my local to fix.

2. As of now I have forked the etcd library and did a fix for the same by changing the google.golang.org/grpc v1.26.0 to google.golang.org/grpc v1.27.0, If you guys could change this in next release that should be great.

**Comment by limingyao** [comment]
+1

**Comment by velann21** [comment]
> Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
> 
> Things noticed.
> 
> 1. google.golang.org/grpc v1.26.0 version is having the known issue as below
>    undefined: grpc.SupportPackageIsVersion6
>    undefined: grpc.ClientConnInterface
> 
> ## The suggested fix for this issue to migrate the GRPC from 1.26.0 to 1.27.0
> Reference:
> ([grpc/grpc-go#3347](https://github.com/grpc/grpc-go/issues/3347))
> 
> 1. Since am using the both the grpc and etcd hand in hand I couldn't upgrade the grpc alone on my local to fix.
> 2. As of now I have forked the etcd library and did a fix for the same by changing the google.golang.org/grpc v1.26.0 to google.golang.org/grpc v1.27.0, If you guys could change this in next release that should be great.

If anyone is facing show stopper then you guys can use etcd from forked repo of mine where I had put a patch to it.
`https://github.com/velann21/etcd`

**Comment by jiayiming001** [comment]
+1
