### ISSUE TITLE
read-only range request took too long to execute

### ISSUE THREAD

**Issue by shayan09** [etcd-io/etcd#11912]
```
2020-05-13 16:45:22.917467 W | etcdserver: read-only range request "key:\"key_form_submission:60af673b-f414-41b6-866f-469c805ef783\" limit:1 " with result "range_response_count:0 size:6" took too long (10.208785021s) to execute
2020-05-13 16:45:22.917539 W | etcdserver: read-only range request "key:\"key_form_submission:11362e39-c617-40a1-b348-5d661ad3ca05\" limit:1 " with result "range_response_count:0 size:6" took too long (10.208789166s) to execute
2020-05-13 16:45:22.917613 W | etcdserver: read-only range request "key:\"key_form_submission:b65247d2-8bf1-4cff-a33f-61153e729c74\" limit:1 " with result "range_response_count:0 size:6" took too long (10.208897537s) to execute
2020-05-13 16:45:22.917676 W | etcdserver: read-only range request "key:\"key_form_submission:6eaa4cda-ceed-495c-bd31-31d37441837f\" limit:1 " with result "range_response_count:0 size:6" took too long (10.208934491s) to execute
2020-05-13 16:45:22.917756 W | etcdserver: request "header:<ID:7587846245096180226 > authenticate:<name:root simple_token:REDACTED>" with result "size:54" took too long (10.152343941s) to execute
```
I have a server with one node, and it do not even write to it very often. Most times it works fine, but I get such performance issues at times. It is running on a SSD and most of the CPUs are idle. So that's not the problem. Network connectivity is fine as well.

Version: 3.4.4

**Comment by agargi** [comment]
Can you monitor your hard disk and see if you notice an issue when you run into issue again?

**Comment by theonlijuan** [comment]
Any updates on this? I run into this error everytime I install a k8s cluster on vmware.

**Comment by acidwars** [comment]
Same issue here. We run a Vanilla Kubernetes on VMWare. The disk is not utilized too much, nor is the cpu.

We use quay.io/coreos/etcd:v3.3.10

**Comment by iamtakingiteasy** [comment]
Happens with tmpfs for wal/snapshot directories too.

**Comment by NorseGaud** [comment]
Happens for me using gp2, ios1/2 SSD EBS volumes in AWS. May be related to Memory... I'll run some tests and report back.

**Comment by NorseGaud** [comment]
Definitely not memory... I increased it by a ton
Here are my messages:
```
anka.etcd          | 2020-11-03 18:46:18.144612 W | etcdserver: read-only range request "key:\"queue/cmd/ready\" range_end:\"queue/cmd/readz\" limit:40 " with result "range_response_count:0 size:6" took too long (111.37924ms) to execute
anka.etcd          | 2020-11-03 18:46:18.340691 W | etcdserver: read-only range request "key:\"queue/controller/ready\" range_end:\"queue/controller/readz\" limit:1 " with result "range_response_count:1 size:2086" took too long (147.638765ms) to execute
anka.etcd          | 2020-11-03 18:46:18.340800 W | etcdserver: request "header:<ID:4386353820461489069 > txn:<compare:<result:LESS target:MOD key:\"nodes/7f8bf240-14b7-4bcd-bd50-32088ae2437b\" mod_revision:9223372036854775807 > success:<request_put:<key:\"nodes/7f8bf240-14b7-4bcd-bd50-32088ae2437b\" value_size:1004 >> failure:<>>" with result "size:18" took too long (107.483526ms) to execute
```

**Comment by NorseGaud** [comment]
I've tested a single etcd docker container on t2.small, t2.medium, t2.xlarge, and they all eventually start throwing this error. It doesn't seem like a resource problem.

**Comment by jingyih** [comment]
A hardcoded 100ms warning threshold is probably not suitable for everyone. #12448 is making it configurable. It will be added as an experimental flag first.

However in the original post, it is concerning that reading a single key takes about 10s to finish. It is most likely due to disk performance, https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean

**Comment by sfgroups-k8s** [comment]
Hi, I am seeing same issue on VMWare VM master node. any way to optimize the etcd cluster in VM?

```
too long (9.9998502s) to execute
 too long (9.999858261s) to execute
 too long (9.999863625s) to execute
 too long (9.999876738s) to execute
 too long (9.999879021s) to execute
 too long (9.999892579s) to execute
 too long (9.999911021s) to execute
 too long (9.999914692s) to execute
 too long (9.99993079s) to execute
 too long (9.999945029s) to execute
 too long (9.999957859s) to execute
 too long (9.999959511s) to execute
 too long (9.999964315s) to execute
 too long (9.999968704s) to execute
 too long (9.999975803s) to execute
 too long (9.999995903s) to execute
```

**Comment by ptabor** [comment]
I would recommending sending (more, but smaller) requests (like with limit of 10000 objects). 
They should finish in reasonable time:
 - not keeping (RO) transactions for too long (bad for fragmentation)
 - not pilling up in RAM - risking OOMs both server and client side
 - not creating long-tail in monitoring
 - not risking bumping on gRPC limits [100MB](https://github.com/grpc/grpc-java/blob/2d15af53c7a9129b53c6ac6ac510d38f23276117/core/src/main/java/io/grpc/internal/GrpcUtil.java#L137)
