### ISSUE TITLE
Recently, the cluster began to decay several times a day.

### ISSUE THREAD

**Issue by newman0089** [etcd-io/etcd#11925]
Hello!
I am using a cluster of three instances of etcd to store the patroni cluster leader key.
The etcd instances are located on three cloud virtual machines.
Two instances are located on the instances with the DBMS and patroni, and the third instance on the instance with docker. instances are installed locally on the server. All three servers use HDD drives.
My version of etcd 3.2.17
I launch each instance of etcd using the systemd etcd.service file:
```
[Unit]
Description=etcd key-value store
Documentation=https://github.com/etcd-io/etcd
After=network.target

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/home/work_user/etcd/data
Environment=ETCD_NAME=etcd1
Environment=ETCD_LISTEN_PEER_URLS="http://192.168.0.2:2380,http://127.0.0.1:7001"
Environment=ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379, http://192.168.0.2:2379"
Environment=ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.0.2:2380"
Environment=ETCD_INITIAL_CLUSTER="etcd1=http://192.168.0.2:2380,etcd2=http://192.168.0.3:2380,etcd3=http://192.168.0.4:2380"
Environment=ETCD_ADVERTISE_CLIENT_URLS="http://192.168.0.4:2379"
Environment=ETCD_INITIAL_CLUSTER_TOKEN="t0k3n"
Environment=ETCD_INITIAL_CLUSTER_STATE="new"
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target
```

For a long time, the system worked fine, however, recently, the cluster began to decay, and there is an error in the log:

```
etcd[45637]: 474d3572f696de93 [logterm: 2433, index: 59420338, vote: 474d3572f696de93] ignored MsgVote from a396971c1f31c763 [logterm: 2433, index: 59420335] at term 2433: lease is not expired (remaining ticks: 9)
etcd[45637]: 474d3572f696de93 [term: 2433] received a MsgApp message with higher term from a396971c1f31c763 [term: 2434]
etcd[45637]: 474d3572f696de93 became follower at term 2434
etcd[45637]: found conflict at index 59420336 [existing term: 2433, conflicting term: 2434]
etcd[45637]: truncate the unstable entries before index 59420336
etcd[45637]: raft.node: 474d3572f696de93 changed leader from 474d3572f696de93 to a396971c1f31c763 at term 2434
etcd[45637]: sync duration of 3.175555515s, expected less than 1s
etcd[45637]: sync duration of 1.64261662s, expected less than 1s
etcd[45637]: sync duration of 1.567979939s, expected less than 1s
etcd[45637]: 474d3572f696de93 is starting a new election at term 2434
etcd[45637]: 474d3572f696de93 became candidate at term 2435
etcd[45637]: 474d3572f696de93 received MsgVoteResp from 474d3572f696de93 at term 2435
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to e2db9469cb05a237 at term 2435
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to a396971c1f31c763 at term 2435
etcd[45637]: raft.node: 474d3572f696de93 lost leader a396971c1f31c763 at term 2435
etcd[45637]: got unexpected response error (etcdserver: request timed out)
etcd[45637]: 474d3572f696de93 is starting a new election at term 2435
etcd[45637]: 474d3572f696de93 became candidate at term 2436
etcd[45637]: 474d3572f696de93 received MsgVoteResp from 474d3572f696de93 at term 2436
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to e2db9469cb05a237 at term 2436
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to a396971c1f31c763 at term 2436
etcd[45637]: 474d3572f696de93 is starting a new election at term 2436
etcd[45637]: 474d3572f696de93 became candidate at term 2437
etcd[45637]: 474d3572f696de93 received MsgVoteResp from 474d3572f696de93 at term 2437
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to a396971c1f31c763 at term 2437
etcd[45637]: 474d3572f696de93 [logterm: 2434, index: 59420362] sent MsgVote request to e2db9469cb05a237 at term 2437

```

I suspect the problem is due to this reason:
```
etcd[45637]: sync duration of 3.175555515s, expected less than 1s
etcd[45637]: sync duration of 1.64261662s, expected less than 1s
etcd[45637]: sync duration of 1.567979939s, expected less than 1s
```

What can I do about it?
Can I add an additional HDD, mount it to some partition and reassign the ETCD_DATA_DIR variable to this partition? Or should I use ETCD_WAL_DIR instead of ETCD_DATA_DIR?

Thanks for any help!

**Comment by newman0089** [comment]
Now I tried the following steps:
1. Added a 200GB ssd disk
2. Created a disk partition equal to 200GB
3. Created the directory `/home/work_user/etcd/data2` and mounted a new partition there
4. In the etcd.service file, commented out the `ETCD_DATA_DIR` variable and added` ETCD_WAL_DIR=/home/work_user/etcd/data2`, but when restarting etcd, I get the error:
```
etcd[11297]: cannot access data directory: mkdir etcd1.etcd: permission denied
systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: etcd.service: Failed with result 'exit-code'.
systemd[1]: Failed to start etcd key-value store.
```

It looks like etcd does not see the ETCD_WAL_DIR variable

5. Commented out the variable `ETCD_WAL_DIR` and changed ` ETCD_DATA_DIR to the value /home/work_user/etcd/data2`. But that didn't work either. I get an error:

```
etcd[11765]: member a396971c1f31c763 has already been bootstrapped
systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: etcd.service: Failed with result 'exit-code'.
systemd[1]: Failed to start etcd key-value store.
```

Etcd only works with the old path.

What am I doing wrong?

**Comment by newman0089** [comment]
Any ideas?

**Comment by paulcaskey** [comment]
You saw this, right? `etcd[11297]: cannot access data directory: mkdir etcd1.etcd: permission denied` That may still be a problem. Check owner/perms on /home/work_user/etcd/data2.

I have never touched ETCD_WAL_DIR. I have changed ETCD_DATA_DIR but only when essentially starting over and then rebuilding my keys from a backup script or something. (I've never had luck with restoring etcd snapshots.)

Did you stop etcd and copy/move its old data dir to the new location? Again, with correct permissions? It seems like you must have, if the new one is saying "has already been bootstrapped" -- check your `ETCD_INITIAL_CLUSTER_STATE="existing"` and make sure that isn't set to "new". But it gets that info from its "member" dir under ETCD_DATA_DIR. 

V 3.2 is also old at this point and I would highly recommend upgrading to 3.4.9.
But most of this feels like file permission issues to me.
