### ISSUE TITLE
Guidance on writing many keys in parallel

### ISSUE THREAD

**Issue by yebrahim** [etcd-io/etcd#11923]
I'm looking at setting a large number of keys as fast as possible using the Go client for etcd. One way to do this is to split the keys into bundles of N keys each, and using a transaction to write the N keys in each bundle, and potentially doing this in parallel. Something like:
```
// split keys into bundles
// for each bundle of N keys, do:
go func() {
  // prepare opPuts
  client.Txn(ctx).Then(opPuts...).Commit()
}()
// somehow collect and return errors
```

If this is a viable approach, I'd appreciate some guidance on choosing the number `N`, as well as the number of goroutines I can spawn with this code before the client starts having issues, if any.
Otherwise, is there a better way to do this?

EDIT
I'm aware of the `MaxTxnOps` option, which is set to 128 by default. I can consider raising this if it there's a reasonable limit that won't cause my system to slow down parallel transactions, but my question is more about other limits that can cause failures. For example, I saw some mention of a max transaction size in bytes.

Related but not very helpful: https://github.com/etcd-io/etcd/issues/860.

**Comment by ptabor** [comment]
AFAIR the rpc request is limited by 2MBs. 
Editing <1000 keys in a single transaction should work well.
