### ISSUE TITLE
Embedded Etcd Fails on Windows

### ISSUE THREAD

**Issue by cretz** [etcd-io/etcd#11920]
Fails with:

    cannot access data directory: directory "my/data/dir" exist without desired file permission. "drwxrwxrwx"

Platform-specific code added in https://github.com/etcd-io/etcd/pull/11798 breaking Windows. Need to avoid directory permission checks on Windows.

**Comment by rudy2steiner** [comment]
assign @rudy2steiner

**Comment by cretz** [comment]
This was fixed in #11945
