### ISSUE TITLE
How to display wal log timestamp by etcd/tools/etcd-dump-logs ?

### ISSUE THREAD

**Issue by zhanglei216** [etcd-io/etcd#11927]
term	     index	type	data
   7	        13	norm	ID:8 txn:<success:<request_delete_range:<key:"a" range_end:"k8s\000\n\025\n\002v1\022\017RangeAllocation\022#\n\022\n\000\022\000\032\000\"\000*\0002\0008\000B\000z\000\022\01310.0.0.0/16\032\000\032\000\"\000" > > failure:<request_delete_range:<key:"a" range_end:"k8s\000\n\025\n\002v1\022\017RangeAllocation\022#\n\022\n\000\022\000\032\000\"\000*\0002\0008\000B\000z\000\022\01310.0.0.0/16\032\000\032\000\"\000" > > >

**Comment by agargi** [comment]
@zhangbaitong IMHO, WAL does not contain timestamp information. WAL entries contain data (that is what we see starting & including ID). It might not be possible (or at least that easy to change this since its written by RAFT itself.
