### ISSUE TITLE
--nosync development flag

### ISSUE THREAD

**Issue by crawshaw** [etcd-io/etcd#11930]
### Background

I regularly spin up a single-node etcd in unit tests and read/write many keys. Experiments with tmpfs on linux suggest that most of the time in my tests is spent writing to disk. Unfortunately macOS does not have a tmpfs, and standard dev/CI environments do not have one configured so typically the tests are slow, dominated by ephemeral etcd writes.

### Proposal

Add an unsafe `--nosync` flag to etcd that disables fsync.

The implementation is straightforward as the underlying bbolt already exposes options for this, `NoSync` and `NoFreelistSync`, it's a matter of plumbing them through.

I would be happy to implement this if the idea is generally acceptable.

**Comment by gyuho** [comment]
>  implementation is straightforward as the underlying bbolt already exposes options for this, NoSync 

Yeah think it can be exposed as an unsafe option `--unsafe-no-sync`?

etcd also writes WAL (no option to disable).
