### ISSUE TITLE
I have compiled and run on the mips platform, how can I submit the adaptation code

### ISSUE THREAD

**Issue by duchuanLX** [etcd-io/etcd#11940]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

**Comment by duchuanLX** [comment]
What to do to support mips64le

Etcd version: v3.3.12
Operating System and version: loongnixserver 3.10.0-693.lns7.8.mips64el

@fanminshi   What should I do, please guide, thank you.

**Comment by agargi** [comment]
@duchuanLX Open a pull request & submit. The maintainers will look at it and accept/ reject. IMHO, folks might not be inclined to support MIPS.

**Comment by agargi** [comment]
@duchuanLX You might also want to read this: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md

**Comment by duchuanLX** [comment]
> @duchuanLX You might also want to read this: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md

Thank you for your guidance, I coordinate resources here, follow up。
