### ISSUE TITLE
etcdctl member list  NO leader

### ISSUE THREAD

**Issue by redfoxfox** [etcd-io/etcd#11952]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
[root@zabbix ~]# etcdctl member list
a4260e614ee580b, started, etcd1, http://10.0.0.5:2380, http://10.0.0.5:2379, false
d3cd49bf905a75d0, started, etcd3, http://10.0.0.7:2380, http://10.0.0.7:2379, false
d3fe9bbbe94d4e27, started, etcd2, http://10.0.0.6:2380, http://10.0.0.6:2379, false

[root@zabbix ~]# /etc/init.d/network restart 
Restarting network (via systemctl):                        [  OK  ]

logs for three nodes as follows:
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: a4260e614ee580b is starting a new election at term 6
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: a4260e614ee580b became candidate at term 7
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: a4260e614ee580b received MsgVoteResp from a4260e614ee580b at term 7
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: a4260e614ee580b [logterm: 6, index: 17] sent MsgVote request to d3cd49bf905a75d0 at term 7
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: a4260e614ee580b [logterm: 6, index: 17] sent MsgVote request to d3fe9bbbe94d4e27 at term 7
May 28 14:09:59 zabbix etcd[293226]: raft2020/05/28 14:09:59 INFO: raft.node: a4260e614ee580b lost leader d3cd49bf905a75d0 at term 7
May 28 14:10:01 zabbix etcd[293226]: raft2020/05/28 14:10:01 INFO: a4260e614ee580b [logterm: 6, index: 17, vote: a4260e614ee580b] rejected MsgVote from d3fe9bbbe94d4e27 [logterm: 6, index: 17] at term 7
May 28 14:10:01 zabbix etcd[293226]: raft2020/05/28 14:10:01 INFO: a4260e614ee580b became follower at term 7
May 28 14:10:01 zabbix etcd[293226]: raft2020/05/28 14:10:01 INFO: raft.node: a4260e614ee580b elected leader d3fe9bbbe94d4e27 at term 7

May 28 14:09:59 agent_01.org etcd[142681]: raft2020/05/28 14:09:59 INFO: d3fe9bbbe94d4e27 [logterm: 6, index: 17, vote: d3cd49bf905a75d0] ignored MsgVote from a4260e614ee580b [logterm: 6, index: 17] at term 6: lease is not expired (remaining ticks: 9)
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 is starting a new election at term 6
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 became candidate at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 received MsgVoteResp from d3fe9bbbe94d4e27 at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 [logterm: 6, index: 17] sent MsgVote request to a4260e614ee580b at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 [logterm: 6, index: 17] sent MsgVote request to d3cd49bf905a75d0 at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: raft.node: d3fe9bbbe94d4e27 lost leader d3cd49bf905a75d0 at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 received MsgVoteResp rejection from a4260e614ee580b at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 has received 1 MsgVoteResp votes and 1 vote rejections
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 received MsgVoteResp from d3cd49bf905a75d0 at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 has received 2 MsgVoteResp votes and 1 vote rejections
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: d3fe9bbbe94d4e27 became leader at term 7
May 28 14:10:01 agent_01.org etcd[142681]: raft2020/05/28 14:10:01 INFO: raft.node: d3fe9bbbe94d4e27 elected leader d3fe9bbbe94d4e27 at term 7

May 28 14:09:59 agent_02.org etcd[73316]: raft2020/05/28 14:09:59 INFO: d3cd49bf905a75d0 [logterm: 6, index: 17, vote: d3cd49bf905a75d0] ignored MsgVote from a4260e614ee580b [logterm: 6, index: 17] at term 6: lease is not expired (remaining ticks: 3)
May 28 14:10:00 agent_02.org etcd[73316]: raft2020/05/28 14:10:00 INFO: d3cd49bf905a75d0 [term: 6] received a MsgAppResp message with higher term from a4260e614ee580b [term: 7]
May 28 14:10:00 agent_02.org etcd[73316]: raft2020/05/28 14:10:00 INFO: d3cd49bf905a75d0 became follower at term 7
May 28 14:10:00 agent_02.org etcd[73316]: raft2020/05/28 14:10:00 INFO: raft.node: d3cd49bf905a75d0 lost leader d3cd49bf905a75d0 at term 7
May 28 14:10:01 agent_02.org etcd[73316]: raft2020/05/28 14:10:01 INFO: d3cd49bf905a75d0 [logterm: 6, index: 17, vote: 0] cast MsgVote for d3fe9bbbe94d4e27 [logterm: 6, index: 17] at term 7
May 28 14:10:01 agent_02.org etcd[73316]: raft2020/05/28 14:10:01 INFO: raft.node: d3cd49bf905a75d0 elected leader d3fe9bbbe94d4e27 at term 7

 logs  show the process for election , and d3fe9bbbe94d4e27 as leader

[root@zabbix ~]# etcdctl member list          
a4260e614ee580b, started, etcd1, http://10.0.0.5:2380, http://10.0.0.5:2379, false
d3cd49bf905a75d0, started, etcd3, http://10.0.0.7:2380, http://10.0.0.7:2379, false
d3fe9bbbe94d4e27, started, etcd2, http://10.0.0.6:2380, http://10.0.0.6:2379, false

[root@zabbix ~]# etcdctl endpoint  status
127.0.0.1:2379, a4260e614ee580b, 3.4.8, 43 MB, false, false, 7, 19003, 19003, 

[root@agent_01 ~]# etcdctl endpoint  status   
127.0.0.1:2379, d3fe9bbbe94d4e27, 3.4.8, 43 MB, true, false, 7, 19003, 19003,       #isLeader

[root@agent_02 ~]# etcdctl endpoint  status   
127.0.0.1:2379, d3cd49bf905a75d0, 3.4.8, 43 MB, false, false, 7, 19003, 19003,

**Comment by guanxingfeng** [comment]
@redfoxfox 
Why is it closed ？how to solve it？
