### ISSUE TITLE
TestStartEtcdWrongToken fails if another etcd is running

### ISSUE THREAD

**Issue by mbanck** [etcd-io/etcd#11956]
On Debian CI (see https://ci.debian.net/data/autopkgtest/unstable/amd64/e/etcd/5695459/log.gz) using etcd-3.2.26 for now (but there is no indication this should be different for master), `TestStartEtcdWrongToken` fails if another etcd is running already:

```
=== RUN   TestStartEtcdWrongToken
    TestStartEtcdWrongToken: serve_test.go:36: expected auth: invalid auth options, got listen tcp 127.0.0.1:2380: bind: address already in use
--- FAIL: TestStartEtcdWrongToken (0.00s)
FAIL
FAIL	github.com/coreos/etcd/embed	0.014s
```

I think all(?) the other tests use random/incremental ports and not the default port. Should this be the case here as well, or is this not possible on principle?

**Comment by mbanck** [comment]
I think this is still a problem.

**Comment by jingyih** [comment]
I don't see why this test cannot be changed to use a random port.

**Comment by teddylear** [comment]
@jingyih I can take a look into this

**Comment by jingyih** [comment]
@teddylear Thanks!

**Comment by teddylear** [comment]
@jingyih I have opened PR but looks like some of the TravisCI runs failed and insight into the failures 
* [4142.3](https://travis-ci.com/github/etcd-io/etcd/jobs/383428505) -> --- FAIL: TestBalancerUnderNetworkPartitionWatchLeader (3.25s), this is an unrelated test to my changes. 
* [4142.2](https://travis-ci.com/github/etcd-io/etcd/jobs/383428503) -> Not sure why this failed from reading the logs, need some guidance on what failed here. 

Please assist so I can know what failed and update PR accordingly, thanks!

**Comment by jingyih** [comment]
@teddylear Thanks for your PR!
> 4142.3 -> --- FAIL: TestBalancerUnderNetworkPartitionWatchLeader (3.25s), this is an unrelated test to my changes.

You are right, this test failure is not related to your PR.


> 4142.2 -> Not sure why this failed from reading the logs, need some guidance on what failed here.

Here it says gofmt check failed. https://travis-ci.com/github/etcd-io/etcd/jobs/383428503#L362
Please use gofmt tool to format the go files you changed. (The code indentation looks incorrect to me)
```
gofmt -s -w ./the/path/to/file
```

**Comment by teddylear** [comment]
@jingyih Looks like lasted update after applying the go fmt resolved that issue, but other tests failed because of the structure of the my commit message for running gofmt. Should I rebase and edit my commit history so that all these changes are in one commit/ fix the commit message. Not sure what the process is for this repo for this situation.
