### ISSUE TITLE
Test failure - TestGetTokenWithoutAuth 

### ISSUE THREAD

**Issue by spzala** [etcd-io/etcd#11966]
Lately, TestGetTokenWithoutAuth is failing in CI on and off with different errors as below:

- 

=== RUN   TestGetTokenWithoutAuth

{"level":"warn","ts":"2020-06-02T14:12:10.250Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3df348ac-cffb-4bb3-9885-55d0dbc74eb8/localhost:22786975200386313290","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

    TestGetTokenWithoutAuth: user_test.go:147: not expected result:context deadline exceeded with endpoint:[unix://localhost:22786975200386313290]

--- FAIL: TestGetTokenWithoutAuth (10.01s)

- 

=== RUN   TestGetTokenWithoutAuth

{"level":"warn","ts":"2020-05-24T17:03:30.102Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-1a4757cb-8755-439d-bd7f-187b410766da/localhost:23962333397874439080","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: leader changed"}

    TestGetTokenWithoutAuth: user_test.go:151: other errors:etcdserver: leader changed

--- FAIL: TestGetTokenWithoutAuth (15.86s)

/cc @mitake

**Comment by mitake** [comment]
@spzala thanks for sharing it, let me take a look.

**Comment by spzala** [comment]
Thank you @mitake !
