### ISSUE TITLE
[QUESTION] What errors can be returned in StatusResponse?

### ISSUE THREAD

**Issue by adirg** [etcd-io/etcd#11965]
Hi,

According to the API reference (https://etcd.io/docs/v3.3.12/dev-guide/api_reference_v3/) the `StatusResponse` contains `errors` field, which "contains alarm/health information and status".
1. What kind of errors/alarms can be returned via this field? 
2. What is the severity of such errors/alarms? I mean, does it indicate that etcd KV store is not accessible?

Currently, I'm only familiar with the `NoLeader` error. 

Thanks,
Adir

**Comment by hexfusion** [comment]
https://github.com/etcd-io/etcd/blob/a04b74d4b4ebced2aca96dde08cb73b04bcdc484/etcdserver/etcdserverpb/rpc.proto#L953-L957

So you have NOSPACE and CORRUPT I believe they both but cluster into RO mode. to use corrupt check you would need to enable `--experimental-corrupt-check-time` flag.

https://github.com/etcd-io/etcd/blob/31b6e5a0871a1fb4e30e30503bc587dc82f71933/etcdserver/api/v3rpc/maintenance.go#L213-L234

**Comment by hexfusion** [comment]
let us know if you have additional questions.

**Comment by adirg** [comment]
@hexfusion thanks!
