### ISSUE TITLE
cannot enable authentication, "auth: root user does not exist"

### ISSUE THREAD

**Issue by lummie** [etcd-io/etcd#11971]
etcd v3.4.9 server and client.

### Issue
1) New etcd 3 node cluster with auth not yet enabled.
2) Add a role `root`
3) Add a user `myrootuser`
4) Grant role `root` to `myrootuser`
5) Enable auth

### Outcome
Authentication is not enabled and the following error is in the server logs 
```
2020-06-03 23:17:21.445405 W | etcdserver: failed to apply request "header:<ID:17344050993887825676 > auth_enable:<> " with response "" took (2.5088ms) to execute, err is auth: root user does not exist
```

The resolution is self explanatory, I need to create a user called "root", however I feel this is increasing the attack surface for etcd, as all instances must have a known user called `root`.  

In my opinion the validation should be to allow authentication if there is a user whom has a grant to the role `root`, not that a user called `root` exists. This allows root users to be created with a different identifier, reducing the chances of gaining unsolicited root access.

**Comment by cfc4n** [comment]
The username must be `root` and defined in store.go L75.
https://github.com/etcd-io/etcd/blob/d8c8f903eee10b8391abaef7758c38b2cd393c55/auth/store.go#L74-L83

So,you can do it with that step
```
$bin/etcdctl role add root
Role root created
$bin/etcdctl user add root
Password of root:
Type password of root again for confirmation:
User root created
$bin/etcdctl user  grant-role  root root
Role root is granted to user root
$bin/etcdctl auth enable
Authentication Enabled
```
