### ISSUE TITLE
That code report “index out of range”

### ISSUE THREAD

**Issue by pjhdld** [etcd-io/etcd#11972]
https://github.com/etcd-io/etcd/blob/570e55db6541448ca123131b78e1444486d42c9a/etcdctl/ctlv3/command/util.go#L46

I took out this method to run and found that this method reported "panic: runtime error: index out of range" error.

Could you help me to see the array overflow situation in this function?

**Comment by pjhdld** [comment]
> https://github.com/etcd-io/etcd/blob/570e55db6541448ca123131b78e1444486d42c9a/etcdctl/ctlv3/command/util.go#L46
> 
> I took out this method to run and found that this method reported "panic: runtime error: index out of range" error.
> 
> Could you help me to see the array overflow situation in this function?

@xiang90  Please help me take a look, thank you

**Comment by lsytj0413** [comment]
what is the etcd version？what is the command do you run？

**Comment by tedyu** [comment]
addHexPrefix() is not exported.

Can you outline your use case ?

**Comment by pjhdld** [comment]
> addHexPrefix() is not exported.
> 
> Can you outline your use case ?

@tedyu  It is overflow when the export is running
like:
var a string = "index"
b := addHexPrefix(a)
func addHexPrefix(s string) string {
	ns := make([]byte, 0)
	for i := 0; i < len(s); i += 2 {
		ns[i*2] = '\\'
		ns[i*2+1] = 'x'
		ns[i*2+2] = s[i]
		ns[i*2+3] = s[i+1]
	}
	return string(ns)
}
