### ISSUE TITLE
Difference between etcdctl endpoint health and checking the /health REST endpoint

### ISSUE THREAD

**Issue by nnathan** [etcd-io/etcd#11973]
Hi,

I was wondering if there is a difference between checking the metrics `/health` endpoint to determine a etcd member nodes' health or using the `etcdctl endpoint health`.

Looking at the code for the `/health` endpoint it runs this routine:https://github.com/etcd-io/etcd/blob/master/etcdserver/api/etcdhttp/metrics.go#L97 which checks alarms, if there is a leader, and performs a QGET ("Quorum" GET).

Whereas the `etcdctl endpoint health` command performs a GET on the "health" key as found here: https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/ep_command.go#L126

The reason I am asking is that I'm writing a script to automate rolling upgrades which involves checking the health of a cluster member after it has been cycled from a previous version to a new version, before proceeding to the next node to cycle. RIght now I'm using the `/health` endpoint which makes things easy since I can use a HTTP client, but I'm wondering if I'm missing out on any checks by doing an application level GET as the `etcdctl endpoint health` does.

Thanks.

**Comment by jingyih** [comment]
Good question. "/health" endpoint is probably more comprehensive for checking health. `etcdctl endpoint health` probably returns "healthy" when the server has alarms raised.
