### ISSUE TITLE
Why only the client's grpc keepalive config can enable PermitWithoutStream?

### ISSUE THREAD

**Issue by HunDunDM** [etcd-io/etcd#11996]
PermitWithoutStream is the grpc keepalive config.

I have found

* `PermitWithoutStream` can be enabled in the [client's config](https://github.com/etcd-io/etcd/blob/master/clientv3/config.go#L85).
* `PermitWithoutStream` is [always false in server](https://github.com/etcd-io/etcd/blob/master/embed/etcd.go#L641).

So I have some questions:

* What consideration does the server not allow `PermitWithoutStream` to be true?
* When do I need to enable `PermitWithoutStream` in the client?

**Comment by mig824** [comment]
Would like to bring this back to life...AFAICT PermitWithoutStream has no effect on the client-side if the server doesn't explicitly allow it

Here's the spec
https://pkg.go.dev/google.golang.org/grpc/keepalive#:~:text=//%20If%20true%2C%20server%20allows%20keepalive%20pings%20even%20when%20there%20are%20no%20active%0A%09//%20streams(RPCs).%20If%20false%2C%20and%20client%20sends%20ping%20when%20there%20are%20no%20active%0A%09//%20streams%2C%20server%20will%20send%20GOAWAY%20and%20close%20the%20connection.%0A%09PermitWithoutStream%20bool%20//%20false%20by%20default.

**Comment by yeya24** [comment]
I think this issue is still valid.
