### ISSUE TITLE
The health endpoint should have its own listener TLS configuration

### ISSUE THREAD

**Issue by ironcladlou** [etcd-io/etcd#11993]
# Problem

It seems there is no way to simultaneously support mTLS authenticated /metrics and HTTP/S (not mTLS) /health endpoints.

The /health endpoint [shares a listener](https://github.com/etcd-io/etcd/blob/master/embed/etcd.go#L668) with the /metrics endpoint. Using the `-–client-cert-auth` option thus subjects both endpoints to mTLS authentication. However, the use cases for metrics and health probing could be quite different. Metrics might tend to be secured, while health endpoints may be subject to less strict authentication requirements.

The [health check docs](https://etcd.io/docs/v3.4.0/op-guide/monitoring/#health-check) seem to acknowledge this problem area, but in a way that's slightly confusing to me:
>Since v3.3.0, in addition to responding to the /metrics endpoint, any locations specified by --listen-metrics-urls will also respond to the /health endpoint. This can be useful if the standard endpoint is configured with mutual (client) TLS authentication, but a load balancer or monitoring service still needs access to the health check.

The health endpoint seems like the practical choice for a Kubernetes HTTP health probe, but the probe APIs don't support mTLS.

This leaves users left implementing health checks through something like `exec` probes, which can add unnecessary complexity and [inefficiency](https://github.com/kubernetes/kubernetes/issues/82440).

# Solutions

One solution might be to decouple the health and metrics endpoint listeners. Then health authentication must be addressed in some way to provide the needed flexibility. For example:

* For the health listener, honor global the global TLS configuration by default (for compatibility with today's behavior), but provide a new flag to allow control over health endpoint client certificate auth (e.g. `--health-client-cert-auth=false`).
* For the health listener, introduce a complete parallel set of TLS configurations to allow granular control of the health endpoint independent of metrics.

# Notes

Of course, if I've missed something and my core claim is invalid:
>It seems there is no way to simultaneously support mTLS authenticated /metrics and HTTP/S (not mTLS) /health endpoints.

I'd love to understand how to implement this without any changes.

**Comment by wenjiaswe** [comment]
> It seems there is no way to simultaneously support mTLS authenticated /metrics and HTTP/S (not mTLS) /health endpoints.

I think you are right, like you said "The /health endpoint shares a listener with the /metrics endpoint."

> One solution might be to decouple the health and metrics endpoint listeners. 

I think that makes sense. But I would like to defer to @gyuho @xiang90 @jingyih  for opinion.

**Comment by wenjiaswe** [comment]
cc @hexfusion

**Comment by ptabor** [comment]
I wonder if usage of gRPC proxy is an option for your use-case: 

It seems to register /health and /metrics handlers [1].
The /metrics request is being forwarded to underlying etcd server [2].

So e.g. you might expose mTLS protected etcd server and not-mTLS protected proxy. 
Is your goal to guarantee that /metrics can be only accessed over mTLS or availability of not protected endpoint is still OK ? 

Finally the proxy seems to define a pattern (flag --grpcProxyMetricsListenAddr) [3] to expose additional listeners.

[1] https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/etcdmain/grpc_proxy.go#L21
[2] https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/proxy/grpcproxy/metrics.go#L79
[3] https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/etcdmain/grpc_proxy.go#L125

**Comment by ironcladlou** [comment]
@ptabor 

> I wonder if usage of gRPC proxy is an option for your use-case:
> 
> It seems to register /health and /metrics handlers [1].
> The /metrics request is being forwarded to underlying etcd server [2].
> 
> So e.g. you might expose mTLS protected etcd server and not-mTLS protected proxy.
> Is your goal to guarantee that /metrics can be only accessed over mTLS or availability of not protected endpoint is still OK ?
> 
> Finally the proxy seems to define a pattern (flag --grpcProxyMetricsListenAddr) [3] to expose additional listeners.
> 
> [1]
> 
> https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/etcdmain/grpc_proxy.go#L21
> 
> 
> [2]
> https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/proxy/grpcproxy/metrics.go#L79
> 
> 
> [3]
> https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/etcdmain/grpc_proxy.go#L125

Thanks for the idea. We are using grpc-proxy, but I'm not clear the approach you've describes allows us to continue securing the /metrics endpoint with mTLS, which is a requirement. Ultimately the client (the proxy being an example) is limited to communicating with the single TLS-configured listener on the etcd side, so I'm not sure yet how the proxy can ovecome the coupling issue.

**Comment by ironcladlou** [comment]
https://github.com/etcd-io/etcd/pull/10504 adds independent TLS configuration for metrics, and just based on the commentary there it seems that PR is still desirable. If so I wonder if the metrics TLS work should come first. I could do a PR that essentially copies the approach for health, but it really feels like overkill. I still wonder if something like an opinionated `--insecure-health-endpoint=true` would be easier and just as useful.

**Comment by ironcladlou** [comment]
https://github.com/etcd-io/etcd/pull/12370 is an attempt to address the problem in a much narrower and less intrusive way.

**Comment by ironcladlou** [comment]
Turns out we can use `--listen-metrics-urls` with an HTTP endpoint to solve this. Thanks for all the discussion and sorry for the confusion. (See https://github.com/etcd-io/etcd/pull/12370#issuecomment-714676715.)

/close

**Comment by ironcladlou** [comment]
>Turns out we can use --listen-metrics-urls with an HTTP endpoint to solve this. Thanks for all the discussion and sorry for the confusion. (See #12370 (comment).)

So after implementing this, we discovered a new constraint which renders the `--listen-metrics-urls` solution insufficient: by doing this, because of the shared health/metrics listener, we expose the /metrics endpoint insecurely over HTTP, which is an unacceptable security regression in the context of our use case.

**Comment by gyuho** [comment]
> So after implementing this, we discovered a new constraint which renders the --listen-metrics-urls solution insufficient: by doing this, because of the shared health/metrics listener, we expose the /metrics endpoint insecurely over HTTP

Understood. Yes, by default, the URL serves `/metrics` + `/health`. Adding a new flag `listen-metrics-paths=metrics,health` would help? That way, we can exclude insecure `/metrics` endpoint.

**Comment by ironcladlou** [comment]
@gyuho 

> > So after implementing this, we discovered a new constraint which renders the --listen-metrics-urls solution insufficient: by doing this, because of the shared health/metrics listener, we expose the /metrics endpoint insecurely over HTTP
> 
> Understood. Yes, by default, the URL serves `/metrics` + `/health`. Adding a new flag `listen-metrics-paths=metrics,health` would help? That way, we can exclude insecure `/metrics` endpoint.

I think I could be misunderstanding the suggestion. How would that flag interact with `--listen-metrics-urls`? For example, given:

```
etcd ... --listen-metrics-urls=https://0.0.0.0:12345,http://0.0.0.0:12346
```

How would I use `--listen-metrics-paths` to indicate that I want the HTTPS URL to serve only /metrics and the HTTP URL to serve only /health?

**Comment by ptabor** [comment]
I understand that @gyuho suggestion assumes that there are still 2 types of urls: 
  - standard (serves everything)
  - metrics (serves only metrics or health or metrics & health). [Yes - the name is not the best one. ]

So
```
etcd ... --listen-metrics-urls=http://0.0.0.0:12345  --listen-client-urls=https://0.0.0.0:12346 --listen-metrics-paths=health
```
would expose health on http and everything on https. 

Do you have use-case for fine-grained exposing everything, metrics & health. This would lead to syntax like: 

```
--listen-metrics-urls=metrics+health:http://0.0.0.0:12345,health:http://0.0.0.0:12346,
```
