### ISSUE TITLE
etcd-v3.4.9: etcdctl command failed and return Error: context deadline exceeded

### ISSUE THREAD

**Issue by mandyqcx** [etcd-io/etcd#12006]
Hello,
I have installed ecd-v3.4.9 in centos 7.6. I have two node. After I used etcd command to start etcd, the logs seems without errors.But etcdctl command failed and return Error: context deadline exceeded.
the following is installation process.

1.[root@pgsrv2 ~]# yum -y install python3-psycopg2 python3-pip PyYAML

2.download etcd backage from https://github.com/etcd-io/etcd/releases
[root@pgsrv2 soft]# ll
-rw-r--r--.  1 root root 17364053 Jun 11 17:20 etcd-v3.4.9-linux-amd64.tar.gz
[root@pgsrv2 soft]# tar -zxvf etcd-v3.4.9-linux-amd64.tar.gz -C /usr/local

[root@pgsrv2 soft]# cd /usr/local
[root@pgsrv2 local]# ll
drwxr-xr-x.  3 630384594 600260513  123 May 22 03:54 etcd-v3.4.9-linux-amd64
[root@pgsrv2 local]# mv etcd-v3.4.9-linux-amd64 etcd-v3.4.9
[root@pgsrv2 local]# chown -R postgres:postgres etcd-v3.4.9
[root@pgsrv2 local]# ll
drwxr-xr-x.  3 postgres postgres  123 May 22 03:54 etcd-v3.4.9
[root@pgsrv2 local]# cd etcd-v3.4.9/
[root@pgsrv2 etcd-v3.4.9]# ll
total 40540
drwxr-xr-x. 14 postgres postgres     4096 May 22 03:54 Documentation
-rwxr-xr-x.  1 postgres postgres 23827424 May 22 03:54 etcd
-rwxr-xr-x.  1 postgres postgres 17612384 May 22 03:54 etcdctl
-rw-r--r--.  1 postgres postgres    43094 May 22 03:54 README-etcdctl.md
-rw-r--r--.  1 postgres postgres     8431 May 22 03:54 README.md
-rw-r--r--.  1 postgres postgres     7855 May 22 03:54 READMEv2-etcdctl.md

[root@pgsrv2 etcd-v3.4.9]# mkdir etcd-data
[root@pgsrv2 etcd-v3.4.9]# chown -R postgres:postgres etcd-data
[root@pgsrv2 etcd-v3.4.9]# ll
total 40540
drwxr-xr-x. 14 postgres postgres     4096 May 22 03:54 Documentation
-rwxr-xr-x.  1 postgres postgres 23827424 May 22 03:54 etcd
-rwxr-xr-x.  1 postgres postgres 17612384 May 22 03:54 etcdctl
drwxr-xr-x.  2 postgres postgres        6 Jun 11 19:46 etcd-data
-rw-r--r--.  1 postgres postgres    43094 May 22 03:54 README-etcdctl.md
-rw-r--r--.  1 postgres postgres     8431 May 22 03:54 README.md
-rw-r--r--.  1 postgres postgres     7855 May 22 03:54 READMEv2-etcdctl.md

3.rewrite /etc/hosts.I have two node
[root@pgsrv2 etc]# vim /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.163.102  pgsrv2
192.168.163.103  pgsrv3

4. wirte etcd.yml in two nodes 
[root@pgsrv2 etcd-v3.4.9]# su - postgres
Last login: Thu Jun 11 18:41:15 CST 2020 on pts/0

node1：pgsrv2
[postgres@pgsrv2 etcd-v3.4.9]$ vim etcd.yml
```
name: pgsrv2
data-dir: /usr/local/etcd-v3.4.9/etcd-data
initial-advertise-peer-urls: http://192.168.163.102:2380
listen-peer-urls: http://192.168.163.102:2380
listen-client-urls: http://192.168.163.102:2379,http://127.0.0.1:2379
advertise-client-urls: http://192.168.163.102:2379
initial-cluster: pgsrv2=http://192.168.163.102:2380,pgsrv3=http://192.168.163.103:2380
initial-cluster-token: etcd-cluster-token
initial-cluster-state: new
```

node2：pgsrv3
[postgres@pgsrv3 etcd-v3.4.9]$ vim etcd.yml
```
name: pgsrv3
data-dir: /usr/local/etcd-v3.4.9/etcd-data
initial-advertise-peer-urls: http://192.168.163.103:2380
listen-peer-urls: http://192.168.163.103:2380
listen-client-urls: http://192.168.163.103:2379,http://127.0.0.1:2379
advertise-client-urls: http://192.168.163.103:2379
initial-cluster: pgsrv2=http://192.168.163.102:2380,pgsrv3=http://192.168.163.103:2380
initial-cluster-token: etcd-cluster-token
initial-cluster-state: new
```

5.mkdir log dir in two nodes
[postgres@pgsrv2 etcd-v3.4.9]$ exit
logout
[root@pgsrv2 etcd-v3.4.9]# mkdir /var/log/etcd
[root@pgsrv2 etcd-v3.4.9]# chown -R postgres:postgres /var/log/etcd

6.add "export ETCDCTL_API=3" in /home/postgres/.bashrc
[postgres@pgsrv2 ~]$ vim .bashrc
```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export ETCDCTL_API=3
```

7.excute etcd command in two nodes 
[postgres@pgsrv2 etcd-v3.4.9]$ /usr/local/etcd-v3.4.9/etcd --config-file /usr/local/etcd-v3.4.9/etcd.yml &>/var/log/etcd/etcd.log

[postgres@pgsrv3 etcd-v3.4.9]$ /usr/local/etcd-v3.4.9/etcd --config-file /usr/local/etcd-v3.4.9/etcd.yml &>/var/log/etcd/etcd.log

8.excute etcdctl command in any node,it seems normal.
[postgres@pgsrv2 etcd]$ /usr/local/etcd-v3.4.9/etcdctl version
```
etcdctl version: 3.4.9
API version: 3.4
```

8.excute etcdctl command but return Error: context deadline exceeded
[postgres@pgsrv2 ~]$ /usr/local/etcd-v3.4.9/etcdctl member list
[postgres@pgsrv2 etcd]$ /usr/local/etcd-v3.4.9/etcdctl member list --endpoints=192.168.163.102:2379
```
{"level":"warn","ts":"2020-06-13T23:46:16.617+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-828ded7a-1207-4b00-8572-ed24303fb330/192.168.163.102:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```

[postgres@pgsrv2 etcd]$ /usr/local/etcd-v3.4.9/etcdctl member list
```
{"level":"warn","ts":"2020-06-13T23:46:33.248+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-e58feff1-9369-4867-9a1b-0291cc6827d3/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```

I don't know what happened. How can I do about it ? The logs don't have any errors.
If you need more information,please let me know.
Thanks for you help!

**Comment by tvannahl** [comment]
Could you include the log files of both servers?
