### ISSUE TITLE
How to tune etcd when it is running on those not performance best storage

### ISSUE THREAD

**Issue by luwang-vmware** [etcd-io/etcd#12027]
Hi ETCD experts,

For the internal experiment environment, if we do not have high performance storage for ETCD, then how to tune ETCD config in K8S env?  Besides tuning ETCD, do I need to tune other parameter for K8S control plan as well to meet functional usage of K8S? 

BTW, using fio --size=22m --bs=2300, the data of my HDD's is : 99% fsync costs 39ms and 90% fsync costs 6ms. 

My env is using the default heartbeat interval as 100ms and election timeout as 1000ms.  With the current configuration, I could see the log such as ''failed to send out heartbeat on time" and similar as  "2020-06-18 13:54:06.848777 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-scheduler\" " with result "range_response_count:1 size:564" took too long (133.447929ms) to execute" and "wal: sync duration of 1.252521491s, expected less than 1s".

**Comment by dingsongjie** [comment]
https://etcd.io/docs/v3.4.0/tuning/
