### ISSUE TITLE
Watch API. Handle connection loss.

### ISSUE THREAD

**Issue by bm0** [etcd-io/etcd#12022]
Hey.
I found that when the connection is disconnected, due to a restart of the etcd server or for other reasons, reading from the watch channel is blocked forever.

I am not an GRPC expert, maybe this problem can be solved if the connection is configured correctly (I'm talking about grpc.DialOption)

Is there a way to handle connection loss?
I would like to get an error from the watcher channel so that I can reconnect later when network or other problems are resolved. Help me please. If possible, then with an example. Thanks in advance.

**Comment by agargi** [comment]
@bm0 Looks like you are looking to something like this (refer link below). It basically wraps the context with 'WithRequireLeader' which ensures that a failure is returned when cluster is unable to determine a leader (after 3 re-election timeouts and each election timeout defaulting to 1000 ms).

https://github.com/kubernetes/kubernetes/issues/89488
