### ISSUE TITLE
etcdctl endpoint health should check for alarms

### ISSUE THREAD

**Issue by jingyih** [etcd-io/etcd#12032]
Today, `etcdctl endpoint health` only performs a quorum GET. If server is corrupted or exceeded quota (which put the server into read only mode), this command incorrectly returns `healthy`.

**Comment by cfc4n** [comment]
Do you have any more information?

**Comment by jingyih** [comment]
Yes. Ref: https://github.com/etcd-io/etcd/issues/11973

**Comment by agargi** [comment]
@jingyih Should "endpoint health" not call '/health' endpoint on each member instead of performing a quorum read on cluster?

**Comment by dvtkrlbs** [comment]
i can take look at this issue but the problem is am not that familiar with the project. so can anyone guide me through this

**Comment by jingyih** [comment]
> @jingyih Should "endpoint health" not simply call '/health' endpoint on each member instead of performing a quorum read on cluster?

I think by design `etcdctl` uses `clientv3` library, for example the KV API [1]. The library communicates with etcd server via gRPC, not via HTTP. I think we just need to add additional call to make sure there is no alarm raised at the server by calling the clinetv3 maintenance API [2].

[1] https://github.com/etcd-io/etcd/blob/ebdccedbdec1a20503d61dc7b5c2cc8bccca3a2e/clientv3/kv.go#L33

[2] https://github.com/etcd-io/etcd/blob/ebdccedbdec1a20503d61dc7b5c2cc8bccca3a2e/clientv3/maintenance.go#L36-L38

**Comment by jingyih** [comment]
@gyuho @spzala Just want to double check with you. Is the current behavior of `etcdctl endpoint health` by design? I think if the server has alarms, this should return false.

$ etcdctl put foo bar
{"level":"warn","ts":"2020-06-22T02:44:40.368-0700","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-1fb6632a-4ac3-4f99-a1c3-c84860cddfb1/127.0.0.1:2379","attempt":0,"error":"rpc error: code = ResourceExhausted desc = etcdserver: mvcc: database space exceeded"}
Error: etcdserver: mvcc: database space exceeded

$ etcdctl endpoint health -w json
[{"endpoint":"127.0.0.1:2379","health":true,"took":"1.339424ms"}]
```

**Comment by cfc4n** [comment]
use `endpoint status`  can do it .
```
$ ./bin/etcdctl endpoint status -w json  
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":1,"raft_term":4},"version":"3.5.0-pre","dbSize":24576,"leader":10276657743932975437,"raftIndex":11,"raftTerm":4,"raftAppliedIndex":11,"errors":["memberID:10276657743932975437 alarm:NOSPACE "],"dbSizeInUse":24576}}]
```

**Comment by agargi** [comment]
> > @jingyih Should "endpoint health" not simply call '/health' endpoint on each member instead of performing a quorum read on cluster?
> 
> I think by design `etcdctl` uses `clientv3` library, for example the KV API [1]. The library communicates with etcd server via gRPC, not via HTTP. I think we just need to add additional call to make sure there is no alarm raised at the server by calling the clinetv3 maintenance API [2].
> 
> [1]
> 
> https://github.com/etcd-io/etcd/blob/ebdccedbdec1a20503d61dc7b5c2cc8bccca3a2e/clientv3/kv.go#L33
> 
> [2]
> 
> https://github.com/etcd-io/etcd/blob/ebdccedbdec1a20503d61dc7b5c2cc8bccca3a2e/clientv3/maintenance.go#L36-L38

@jingyih I have made the change and issued a pull request. /cc @gyuho @xiang90
