### ISSUE TITLE
Potential issue with etcdctl endpoint health command

### ISSUE THREAD

**Issue by agargi** [etcd-io/etcd#12036]
**Problem**
If endpoint list in command - "etcdctl --endpoints=<> endpoint health" - includes an endpoint which is not valid, the command reports that the cluster is unhealthy. 

**What might be ideal response**
Command can respond back that cluster is healthy but indicate that one of specified endpoints is not a valid endpoint.

**Commands to re-produce it**
`
> etcdctl --endpoints=127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383 member list
8e9e05c52164694d, started, default, http://localhost:2380, http://localhost:2379, false
f45398e617bc947e, started, infra4, http://localhost:2384, http://localhost:2383, false

> etcdctl --endpoints=127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383 endpoint health
{"level":"warn","ts":"2020-06-21T06:58:55.119-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-5b719c42-e6f7-4478-b6c6-78c618298aa7/127.0.0.1:2381","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2381: connectex: No connection could be made because the target machine actively refused it.\""}
127.0.0.1:2383 is healthy: successfully committed proposal: took = 14.5208ms
127.0.0.1:2379 is healthy: successfully committed proposal: took = 16.5169ms
127.0.0.1:2381 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster

> etcdctl --endpoints=127.0.0.1:2379,127.0.0.1:2383 endpoint health
127.0.0.1:2383 is healthy: successfully committed proposal: took = 13.9781ms
127.0.0.1:2379 is healthy: successfully committed proposal: took = 13.9781ms`

**Comment by jingyih** [comment]
The endpoint list provided to the command might not be of the same cluster? For example if there are 3 clusters, each of size 1. Asking this command to figure out which endpoints belong to which cluster is probably too much to ask. The command `etcdctl endpoint`, as the name suggests, works on the concept of `endpoint` (server) as opposed to `cluster`.

I think the command works best if we first do `member list` to figure out the endpoints of the same cluster, then use `endpoint health` or `endpoint status` to check those endpoints.

**Comment by agargi** [comment]
@jingyih Understood. Makes sense.
