### ISSUE TITLE
arm dockerfile build  error

### ISSUE THREAD

**Issue by huzhao37** [etcd-io/etcd#12061]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

ADD failed: stat /var/lib/docker/tmp/docker-builder557629296/var/etcd: no such file or directory
![image](https://user-images.githubusercontent.com/17268060/85491103-845cfe00-b605-11ea-8dcd-c057cf2e6dcc.png)
so,what should  i do ? tks

**Comment by huzhao37** [comment]
after build success image,i received new error when i run "docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --mount type=bind,source=/tmp/etcd-data.tmp,destination=/etcd-data \
  --name etcdtest10 \
  etcdv3 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://0.0.0.0:2379 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls http://0.0.0.0:2380 \
  --initial-cluster s1=http://0.0.0.0:2380 \
  --initial-cluster-token tkn \
  --initial-cluster-state new \
  --log-level info \
  --logger zap \
  --log-outputs stderr "
error:
etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set

**Comment by gyuho** [comment]
@huzhao37 

Please see https://github.com/etcd-io/etcd/pull/12929/files. arm64 is now official supported.

**Comment by huzhao37** [comment]
thanks！
