### ISSUE TITLE
JWT 5-minute timeout: etcd + Go clientv3 v3.4.9

### ISSUE THREAD

**Issue by paulcaskey** [etcd-io/etcd#12085]
I am getting subscribe (watch) timeouts in clientv3 after 300 seconds. This is with JWT tokens enabled, using cert files that are definitely not expired, which I used in 3.3 without ever seeing this problem. Now in 3.4.9 it's like clockwork: my client can subscribe for 5 minutes. Then any Get() triggers this:

```
2020-06-26 14:04:37.886234 W | auth: failed to parse jwt token: Token is expired
2020-06-26 14:04:37.886246 W | auth: invalid auth token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiO [...]
```
I must be really doing something wrong because web-searching on this turns up almost nothing. Hopefully someone can take pity on me and give me the magic. I've been reading docs and can't find it. I need to renew this token - how? I can set a ticker to do this every 4 minutes, if I must. Specify > 300 seconds somewhere? 

This is software I'm writing that will run for days, weeks, years. I really don't need this token to timeout, ever.

**Comment by cfc4n** [comment]
This feature has been added at #11978 , please wait for the new version.

**Comment by paulcaskey** [comment]
Being impatient, I'm off to build 3.4.9 myself with that single 300sec number *= 1000 or something.

**Comment by paulcaskey** [comment]
Done! :-D
```
diff --git a/auth/simple_token.go b/auth/simple_token.go
index 934978c98..8188651c0 100644
--- a/auth/simple_token.go
+++ b/auth/simple_token.go
@@ -37,8 +37,8 @@ const (

 // var for testing purposes
 var (
-       simpleTokenTTL           = 5 * time.Minute
-       simpleTokenTTLResolution = 1 * time.Second
+       simpleTokenTTL           = 1008 * time.Hour // 6 weeks
+       simpleTokenTTLResolution = 16 * time.Minute
 )
```

**Comment by paulcaskey** [comment]
```
> -       simpleTokenTTL           = 5 * time.Minute
> -       simpleTokenTTLResolution = 1 * time.Second
> +       simpleTokenTTL           = 1008 * time.Hour // 6 weeks
> +       simpleTokenTTLResolution = 16 * time.Minute
>  )
> ```

It didn't work. 😢 I replaced **etcd** in my cluster with this rebuild. Still get 5-min timeout. This is driving me nuts! 
```
{"level":"warn","ts":"2020-07-05T14:22:26.244-0700","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-37394693-0263-4217-949f-5602de42f7f1/myhost.foo.net:2379","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
```

**Comment by paulcaskey** [comment]
Duh, "simpleToken" is not JWT. Checking auth/jwt.go for something similar. Tracing code .... okay you must be kidding me. This is already a config option? 
```
ETCD_AUTH_TOKEN="jwt,pub-key=....,ttl=1008h"
```
Testing!

**Comment by paulcaskey** [comment]
The above test worked. I can already set that JWT TTL as a workaround. Now I'm confused. Ignoring the bad reference in here to the SimpleTokenTTL issue, this is JWT and does not matter there. But something changed here from v3.3. to v3.4. Did the default JWT TTL drop significantly? WAS there a TTL? 

What I'd really like is for the client/server to renegotiate a new JWT token when the old one expires.

**Comment by cfc4n** [comment]
sorry,I mistook `simpleTokenTTL` for `JWT`.
JWT TTL was  5 minutes default in
https://github.com/etcd-io/etcd/blob/d3a702a09d925c37ccc44f6843492bc521fba57e/auth/options.go#L43

and It can customize by `auth-token` config string with `jwt,pub-key=....,ttl=1008h`, some param like

https://github.com/etcd-io/etcd/blob/d3a702a09d925c37ccc44f6843492bc521fba57e/auth/options.go#L26-L32
