### ISSUE TITLE
 v3 api is not available when etcd uses config file

### ISSUE THREAD

**Issue by DenisRazinkin** [etcd-io/etcd#12093]
-bash-4.4# etcd --version
etcd Version: 3.4.9
Git SHA: 54ba95891
Go Version: go1.12.17
Go OS/Arch: linux/amd64

There is no problem with v3 api  when I start etcd with command line
`
-bash-4.4# etcd --data-dir=/tmp/node1 --name node1 --listen-peer-urls=http://127.0.0.1:2380 --listen-client-urls=http://127.0.0.1:2379 --initial-advertise-peer-urls=http://127.0.0.1:2380  --advertise-client-urls=http://127.0.0.1:2379`

```
-bash-4.4# curl -L -s http://127.0.0.1:2379/v3/cluster/member/list -X POST -d '{"linearizable": false}' | jq
{
  "header": {
    "cluster_id": "2037210783374497686",
    "member_id": "13195394291058371180",
    "raft_term": "3"
  },
  "members": [
    {
      "ID": "13195394291058371180",
      "name": "node1",
      "peerURLs": [
        "http://127.0.0.1:2380"
      ],
      "clientURLs": [
        "http://127.0.0.1:2379"
      ]
    }
  ]
}

```

When I use config file with same parameters there is 404 error.
```
-bash-4.4# cat /tmp/node1/etcd.conf 
# This is the configuration file for the etcd server.

# Human-readable name for this member.
name: node1

# Path to the data directory.
data-dir: /tmp/node1/

#List of comma separated URLs to listen on for peer traffic.
listen-peer-urls: http://127.0.0.1:2380

# List of comma separated URLs to listen on for client traffic.
listen-client-urls: http://127.0.0.1:2379

# List of this member's peer URLs to advertise to the rest of the cluster.
# The URLs needed to be a comma-separated list.
initial-advertise-peer-urls: http://127.0.0.1:2380

# List of this member's client URLs to advertise to the public.
# The URLs needed to be a comma-separated list.
advertise-client-urls: http://127.0.0.1:2379

# Initial cluster configuration for bootstrapping.
initial-cluster: 

# Initial cluster state ('new' or 'existing').
initial-cluster-state: 'new'
```
Start etcd with:
`-bash-4.4# etcd --config-file /tmp/node1/etcd.conf `

Send curl http request, got 404
```
-bash-4.4# curl -L -s http://127.0.0.1:2379/v3/cluster/member/list -X POST -d '{"linearizable": false}'     
404 page not found
```

**Comment by spzala** [comment]
@DenisRazinkin please try enabling enable-grpc-gateway in the config file i.e. `enable-grpc-gateway: true`

**Comment by spzala** [comment]
Closing as fixed. Thanks!

**Comment by pgodfrin-nov** [comment]
Say folks, would you add this parameter to the docs please? I spent quite a few hours wondering what was missing until CyberDem0n pointed me to this issue. See https://github.com/zalando/patroni/issues/1939

While you're at it, maybe a way to search the docs?

**Comment by spzala** [comment]
Updating changelog https://github.com/etcd-io/etcd/pull/13034 and will add in doc appropriately in the etcd.io repo https://github.com/etcd-io/website

**Comment by robinchrist** [comment]
This is still missing in the docs @spzala - can we please add it to https://github.com/etcd-io/website?
