### ISSUE TITLE
use etcd 3.4.10, connection refused

### ISSUE THREAD

**Issue by lanyyyy** [etcd-io/etcd#12146]
*  start etcd on one linux machine：
```
[root@server-1902201410 ~]# /tmp/etcd-download-test/etcd
```

*  on current linux machine, it operates correcttly:
```
[root@server-1902201410 ~]# /tmp/etcd-download-test/etcdctl --endpoints=127.0.0.1:2379 put x y
OK

```

*  but when I do this on another centos machine，an error occurs:

![image](https://user-images.githubusercontent.com/4739622/87774919-d6d1b900-c857-11ea-9374-b1f0b146499a.png)

*  do anyone knows?

**Comment by hexfusion** [comment]
If you want the server to listen to a specific address it needs to defined in `--listen-client-urls`[1] explicitly. I assume the red arrows are to hide the address? Unless your dialing endpoint  http://127.0.0.1:2379 then the above is expected.

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--listen-client-urls

**Comment by lanyyyy** [comment]
thanks, I hava found the solution:
```
 /tmp/etcd-download-test/etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://0.0.0.0:2379
```
