### ISSUE TITLE
Upgrade to grpc 1.30.0

### ISSUE THREAD

**Issue by pracucci** [etcd-io/etcd#12153]
We're using the etcd `clientv3` in the [Cortex project](https://github.com/cortexproject/cortex). We're currently blocked from upgrading some dependencies (ie. Prometheus) because of a breaking change introduced in grpc `1.30.0`: the deprecated `naming` package (in grpc) has been removed.

What's the feeling about upgrading etcd to grpc `1.30.0`?

**Comment by pracucci** [comment]
To better understand how widespread the issue is in etcd, I've upgraded to grpc 1.30 *forking* the `naming` package:
https://github.com/etcd-io/etcd/compare/master...pracucci:upgrade-to-grpc-1.30

**Comment by pracucci** [comment]
Handling the removal of `naming` package looks relative easy. However, grpc `1.30.0` has also moved `Balancer` and `Picker` to V2 (and deleted the old one) in https://github.com/grpc/grpc-go/pull/3431.

**Comment by pracucci** [comment]
_We should be able to solve this issue in Cortex using the `replace` directive in `go.mod`, but considering upgrading etcd to grpc 1.30 would be great._

**Comment by beorn7** [comment]
Sadly, the `replace` directive doesn't work to downgrade because grpc 1.30 is in a multi-module repo, but 1.29 is in a mono-module repo. The new `example` module that sprang into existence with 1.30 is incompatible with the old `example` subdir in 1.29, and we haven't found a way to `replace` a module with a subdir…

**Comment by xiegeo** [comment]
Duplicate of #12124

**Comment by pracucci** [comment]
Closing because it's a duplicate of #12124.
