### ISSUE TITLE
Basic Auth token expire, what watch stream will be happened?

### ISSUE THREAD

**Issue by xkeyideal** [etcd-io/etcd#12157]
https://github.com/etcd-io/etcd/blob/master/clientv3/client.go#L254

See the codes, i see when unary invoke `rpctypes.ErrInvalidAuthToken` will `c.authTokenBundle.UpdateAuthToken(resp.Token)` and retry the operate, but stream no retry.

When create or reconnect stream connection  return ErrInvalidAuthToken, the etcd clientv3 will not work?

**Comment by xkeyideal** [comment]
https://github.com/etcd-io/etcd/blob/master/clientv3/watch.go#L282
https://github.com/etcd-io/etcd/blob/master/clientv3/watch.go#L526

`// start a stream with the etcd grpc server
	if wc, closeErr = w.newWatchClient(); closeErr != nil {
		return
	}`

The `Watch` function will not return error

**Comment by xkeyideal** [comment]
So the etcd clientv3 can export `getToken` function to user

**Comment by cfc4n** [comment]
Can you give a demo for it ?

**Comment by xkeyideal** [comment]
I think this is a bug or feature, when the authtoken expired, watch stream need reconnect will be failed always.

https://github.com/etcd-io/etcd/pull/12135, the pr say same problem.

I suggest solution:

1.  `authenticate` function return token ttl
```go
auth, err = newAuthenticator(ctx, target, dOpts, c)
if err != nil {
	continue
}
defer auth.close()

var resp *AuthenticateResponse
resp, err = auth.authenticate(ctx, c.Username, c.Password)
if err != nil {
	// return err without retrying other endpoints
	if err == rpctypes.ErrAuthNotEnabled {
		return err
	}
	continue
}

c.authTokenBundle.UpdateAuthToken(resp.Token)
```

2. etcd client exec scheduled task for update auth token

3. export the `getToken` function to user, can refresh auth token

**Comment by cfc4n** [comment]
I got it. I'll give a PR after PR #12162 merged

**Comment by jschwinger23** [comment]
Sorry for chiming in, but in my opinion, grpc-go already provides a perfect interface to refresh credential: https://godoc.org/google.golang.org/grpc/credentials#PerRPCCredentials

```
type PerRPCCredentials interface {
    // GetRequestMetadata gets the current request metadata, refreshing
    // tokens if required. This should be called by the transport layer on
    // each request, and the data should be populated in headers or other
    // context. If a status code is returned, it will be used as the status
    // for the RPC. uri is the URI of the entry point for the request.
    // When supported by the underlying implementation, ctx can be used for
    // timeout and cancellation. Additionally, RequestInfo data will be
    // available via ctx to this call.
    // TODO(zhaoq): Define the set of the qualified keys instead of leaving
    // it as an arbitrary string.
    GetRequestMetadata(ctx context.Context, uri ...string) (map[string]string, error)
    // RequireTransportSecurity indicates whether the credentials requires
    // transport security.
    RequireTransportSecurity() bool
}
```

I noted a ancient bug https://github.com/grpc/grpc-go/issues/3749 which was fixed in the latest grpc https://github.com/grpc/grpc-go/pull/3677, so there will be no concern.

I know it's aggressive to upgrade grpc from ancient version to the latest release, even I can foresee a number of incompatibility like grpc.WithBalancer has been deprecated, but it's better we follow the best practice.
