### ISSUE TITLE
etcd version 3.3.22 in v3.3.23 packages

### ISSUE THREAD

**Issue by vitabaks** [etcd-io/etcd#12154]
fyi

wget https://github.com/etcd-io/etcd/releases/download/v3.3.23/etcd-v3.3.23-linux-amd64.tar.gz
tar -xf etcd-v3.3.23-linux-amd64.tar.gz
cd etcd-v3.3.23-linux-amd64
chmod +x etcd*
etcd --version
```
etcd Version: 3.3.22
Git SHA: 4873f5516
Go Version: go1.12.17
Go OS/Arch: linux/amd64
```
etcdctl --version
```
etcdctl version: 3.3.22
API version: 
```

**Comment by spzala** [comment]
@vitabaks thanks for reporting it!

**Comment by gyuho** [comment]
My bad. It had correct git tag but wrong version string. Will fix.

**Comment by spzala** [comment]
Thanks @gyuho !!

**Comment by cfc4n** [comment]
> My bad. It had correct git tag but wrong version string. Will fix.

Can you update v3.3.23 to https://pkg.go.dev/go.etcd.io/etcd/?tab=doc ?

**Comment by zhangguanzhang** [comment]
same with docker images:
```
$ docker run --rm quay.io/coreos/etcd:v3.3.23 /usr/local/bin/etcd --version
etcd Version: 3.3.22
Git SHA: 4873f5516
Go Version: go1.12.17
Go OS/Arch: linux/amd64

```

**Comment by sw919678915** [comment]
please  merge ,thanks
