### ISSUE TITLE
clientv3: slice bounds out of range panic when using multiple watches with namespaces

### ISSUE THREAD

**Issue by brumhard** [etcd-io/etcd#12167]
Hi,
I'm having trouble with the clientv3 `Watch` method.
When I use a namespace client, and try to listen to multiple watch channels in this namespace I get a panic `slice bounds out of range` in `[...]/github.com/coreos/etcd@v3.3.22+incompatible/clientv3/namespace/watch.go:54`.
Without the namespaces everything works fine.

For reproduction see code below:
```go
package test

import (
	"context"
	"github.com/brumhard/fancy_scheduler/pkg/kv"
	"github.com/coreos/etcd/clientv3"
	"github.com/coreos/etcd/clientv3/namespace"
	"github.com/stretchr/testify/assert"
	"testing"
	"time"
)

const testPrefix = "test/"

type service struct {
	kv clientv3.Client
}

func New(client clientv3.Client) *service {
	client.KV = namespace.NewKV(client.KV, testPrefix)
	client.Watcher = namespace.NewWatcher(client.Watcher, testPrefix)
	client.Lease = namespace.NewLease(client.Lease, testPrefix)
	return &service{
		kv: client,
	}
}

func (e *service) Watch(ctx context.Context) chan bool {
	// watch whole namespace
	watchChan := e.kv.Watch(ctx, "\x00", clientv3.WithFromKey())
	targetChan := make(chan bool)
	go func(ctx context.Context, watchChan clientv3.WatchChan, targetChan chan bool) {
		defer func() { close(targetChan) }()
		for {
			select {
			case <-ctx.Done():
				return
			case <-watchChan:
				select {
				case targetChan <- true:
				// TODO: add to config
				case <-time.After(5 * time.Second):
				}
			}
		}
	}(ctx, watchChan, targetChan)
	return targetChan
}

func Test_WatchWorking(t *testing.T) {
	// notifies when queue is changed
	ctx := context.TODO()
	client, closeFunc, err := kv.NewTestEtcd()
	assert.NoError(t, err)
	defer closeFunc()
	s := service{kv: *client}

	var chans []chan bool
	for i := 0; i < 5; i++ {
		newChan := s.Watch(ctx)
		chans = append(chans, newChan)
	}
	_, err = client.Put(ctx, testPrefix+"anyKey", "anyVal")
	assert.NoError(t, err)
	for _, c := range chans {
		test := <-c
		assert.NotNil(t, test)
	}
}

func Test_WatchPanics(t *testing.T) {
	// notifies when queue is changed
	ctx := context.TODO()
	client, closeFunc, err := kv.NewTestEtcd()
	assert.NoError(t, err)
	defer closeFunc()
	s := New(*client)

	var chans []chan bool
	for i := 0; i < 5; i++ {
		newChan := s.Watch(ctx)
		chans = append(chans, newChan)
	}
	_, err = client.Put(ctx, testPrefix+"anyKey", "anyVal")
	assert.NoError(t, err)
	for _, c := range chans {
		test := <-c
		assert.NotNil(t, test)
	}
}
```
The goal is to just get values from the watch channel, work on the resulting WatchResponse and forward the result it to the other channel. In this example it just pushes `true` in the channel.

In this case `kv.NewTestEtcd` just generates a local embedded etcd for testing purposes.
So i created a test case that uses the namespace client `Test_WatchPanics`  which panics and a test using the normal client called `Test_WatchWorking`  which works perfectly fine.
In my case I could also see that when im only using 2 channels concurrently (instead of the 5 that i currently create) the namespace client works without panics, too.

(Using version: `github.com/coreos/etcd v3.3.22+incompatible`)

**Comment by yurilaaziz** [comment]
try add this line in your go.mod file 
replace go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547

**Comment by brumhard** [comment]
Hi, thank you for the answer.
I will try that soon and give you an update about the outcome.

**Comment by brumhard** [comment]
So when using your version i get another error which is described in #11920. Maybe the fix isn't available in your version?

Also I tried using the current master version `github.com/etcd-io/etcd v0.5.0-alpha.5.0.20200418042003-0461b3fa51eb` which has the same error as described in this issue.

**Comment by brumhard** [comment]
Ok nvm I've just unterstood that your mentioned version is in fact the master version, I just didn't update in a while I guess.
Still I've got the #11920 issue, which should actually be fixed on master. I don't get it.
Any thoughts on this?

**Comment by brumhard** [comment]
Looking at the master it seems like all the necessary files are there. Any clue why I don't get the same files with `go get go.etcd.io/etcd@master`?

**Comment by brumhard** [comment]
I now also tried with `go get go.etcd.io/etcd/v3@master` (commit `3e1a64913ad9ff9534775f2d8a2b971de3fa6722` which also includes the bug for multiple watches.
