### ISSUE TITLE
etcd promoting standby learner instance when the quorum is affected

### ISSUE THREAD

**Issue by avairava** [etcd-io/etcd#12186]
Hello Team,

We are running Kubernetes in a two-node cluster. As etcd needs three instances for a quorum, in addition to two etcd instances in two nodes, the third etcd instance is created as a stateful set of replica 2 where one pod of the stateful set is active and other pod is learning mode. We are wondering if etcd has the capability to promote the learning instance as a member when the quorum is lost. Is there any plan to support it in the future?

**Comment by jingyih** [comment]
> As etcd needs three instances for a quorum

I don't understand this. I think you meant failure tolerance? Please see https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-is-failure-tolerance

> We are wondering if etcd has the capability to promote the learning instance as a member when the quorum is lost

Promoting a learner is a type of configuration change, which requires quorum to be active.
