### ISSUE TITLE
Periodically db sync latency on one node (spikes once-per hours)

### ISSUE THREAD

**Issue by retinio** [etcd-io/etcd#12185]
Hi ETCD experts,

We are using kubernetes version 1.18.2 and etcd version 3.4.7.
Etcd and k8s-master work on the same server but etcd uses separate ssd disk: 

> lsblk -f
NAME      FSTYPE            LABEL          UUID                                 MOUNTPOINT
sda
└─sda1    ext4                                                                  /var/lib/etcd

> fio --rw=write --ioengine=sync --fdatasync=1 --directory=var/lib/etcd --size=39m --bs=4096 --name=mytest
...
  fsync/fdatasync/sync_file_range:
    sync (usec): min=303, max=5445, avg=396.53, stdev=154.94
    sync percentiles (usec):
     |  1.00th=[  318],  5.00th=[  322], 10.00th=[  326], 20.00th=[  334],
     | 30.00th=[  338], 40.00th=[  347], 50.00th=[  359], 60.00th=[  367],
     | 70.00th=[  383], 80.00th=[  408], 90.00th=[  486], 95.00th=[  709],
     | 99.00th=[  766], 99.50th=[  799], 99.90th=[ 2474], 99.95th=[ 3458],
     | 99.99th=[ 5473]

But I periodically (once an hour) see a sync latency on one node (iscresed from 2ms to ~16-37ms ). This node is etcd leader.
![etcd-1](https://user-images.githubusercontent.com/36562344/88802412-b852b280-d1b3-11ea-9fb3-47d1287940dd.png)
![etcd-3](https://user-images.githubusercontent.com/36562344/88803750-9e19d400-d1b5-11ea-95f0-c82e65101721.png)
![etcd-2](https://user-images.githubusercontent.com/36562344/88803049-93ab0a80-d1b4-11ea-9fff-e15ec535d196.png)
![cpu](https://user-images.githubusercontent.com/36562344/88803112-aa516180-d1b4-11ea-95e0-cd3dcad06522.png)

I don't understand why this is happening. Please help me understand the reason latencies. Should I be worried about this?

Thanks!
Sorry for any mistakes. English is not my native language.

**Comment by ptabor** [comment]
Spikes once-per hours might be related to periodic compaction of etcd storage.

Please see:
https://etcd.io/docs/v3.4.0/op-guide/maintenance/#auto-compaction

**Comment by retinio** [comment]
Thanks! @ptabor I still don't understand what causes the sync latency in ~16-30ms. Compact duration is ~3ms.
Now it happens by accident.

![image](https://user-images.githubusercontent.com/36562344/88914664-9e74a680-d26b-11ea-9612-e9629b630a2a.png)

![image](https://user-images.githubusercontent.com/36562344/88917354-4a1ff580-d270-11ea-8fa1-36bb0af3f3be.png)

etcd logs from servers 

Jul 30 13:33:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:33:59.513+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38096972}
Jul 30 13:33:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:33:59.517+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38096972,"took":"2.848201ms"}
Jul 30 13:36:28 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:36:28.782+0300","caller":"wal/wal.go:698","msg":"created a new WAL segment","path":"/var/lib/etcd/member/wal/0000000000000249-000000000283d90c.wal"}
Jul 30 13:36:46 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:36:46.018+0300","caller":"fileutil/purge.go:79","msg":"purged","path":"/var/lib/etcd/member/wal/0000000000000244-00000000027e4835.wal"}
Jul 30 13:38:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:38:59.518+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38098827}
Jul 30 13:38:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:38:59.521+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38098827,"took":"2.899995ms"}
Jul 30 13:43:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:43:59.523+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38100681}
Jul 30 13:43:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:43:59.527+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38100681,"took":"3.12104ms"}
Jul 30 13:48:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:48:59.528+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38102537}
Jul 30 13:48:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:48:59.532+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38102537,"took":"3.150228ms"}
Jul 30 13:49:18 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:49:18.477+0300","caller":"etcdserver/server.go:1390","msg":"triggering snapshot","local-member-id":"84888d87b4780bbe","local-member-applied-index":42200443,"local-member-snapshot-index":42100442,"local-member-snapshot-count":100000}
Jul 30 13:49:18 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:49:18.480+0300","caller":"etcdserver/server.go:2381","msg":"saved snapshot","snapshot-index":42200443}
Jul 30 13:49:18 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:49:18.480+0300","caller":"etcdserver/server.go:2423","msg":"compacted Raft logs","compact-index":42195443}
Jul 30 13:49:46 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:49:46.016+0300","caller":"fileutil/purge.go:79","msg":"purged","path":"/var/lib/etcd/member/snap/000000000000034a-00000000027c4c56.snap"}
Jul 30 13:53:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:53:59.532+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38104388}
Jul 30 13:53:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:53:59.535+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38104388,"took":"2.826819ms"}
Jul 30 13:58:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:58:59.536+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38106245}
Jul 30 13:58:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T13:58:59.540+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38106245,"took":"2.909863ms"}
Jul 30 14:03:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:03:59.540+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38108101}
Jul 30 14:03:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:03:59.544+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38108101,"took":"2.895378ms"}
Jul 30 14:08:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:08:59.545+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38109974}
Jul 30 14:08:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:08:59.549+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38109974,"took":"2.8805ms"}
Jul 30 14:13:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:13:59.550+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38111827}
Jul 30 14:13:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:13:59.553+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38111827,"took":"2.854777ms"}
Jul 30 14:18:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:18:59.555+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38113684}
Jul 30 14:18:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:18:59.559+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38113684,"took":"2.883817ms"}
Jul 30 14:23:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:23:59.560+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38115536}
Jul 30 14:23:59 master-01 etcd[9258]: {"level":"info","ts":"2020-07-30T14:23:59.563+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38115536,"took":"2.897895ms"}

Jul 30 13:33:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:33:59.512+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38096972}
Jul 30 13:33:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:33:59.516+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38096972,"took":"2.924181ms"}
Jul 30 13:38:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:38:59.516+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38098827}
Jul 30 13:38:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:38:59.520+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38098827,"took":"3.07747ms"}
Jul 30 13:43:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:43:59.521+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38100681}
Jul 30 13:43:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:43:59.532+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38100681,"took":"9.506858ms"}
Jul 30 13:48:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:48:59.526+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38102537}
Jul 30 13:48:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:48:59.530+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38102537,"took":"3.086721ms"}
Jul 30 13:53:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:53:59.532+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38104388}
Jul 30 13:53:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:53:59.535+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38104388,"took":"2.83699ms"}
Jul 30 13:58:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:58:59.535+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38106245}
Jul 30 13:58:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:58:59.539+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38106245,"took":"2.846863ms"}

Jul 30 13:33:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:33:59.512+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38096972}
Jul 30 13:33:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:33:59.516+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38096972,"took":"2.924181ms"}
Jul 30 13:38:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:38:59.516+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38098827}
Jul 30 13:38:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:38:59.520+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38098827,"took":"3.07747ms"}
Jul 30 13:43:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:43:59.521+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38100681}
Jul 30 13:43:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:43:59.532+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38100681,"took":"9.506858ms"}
Jul 30 13:48:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:48:59.526+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38102537}
Jul 30 13:48:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:48:59.530+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38102537,"took":"3.086721ms"}
Jul 30 13:53:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:53:59.532+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38104388}
Jul 30 13:53:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:53:59.535+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38104388,"took":"2.83699ms"}
Jul 30 13:58:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:58:59.535+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38106245}
Jul 30 13:58:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T13:58:59.539+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38106245,"took":"2.846863ms"}
Jul 30 14:03:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:03:59.539+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38108101}
Jul 30 14:03:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:03:59.543+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38108101,"took":"2.955803ms"}
Jul 30 14:08:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:08:59.544+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38109974}
Jul 30 14:08:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:08:59.548+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38109974,"took":"2.892884ms"}
Jul 30 14:13:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:13:59.549+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38111827}
Jul 30 14:13:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:13:59.552+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38111827,"took":"2.915689ms"}
Jul 30 14:18:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:18:59.554+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38113684}
Jul 30 14:18:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:18:59.558+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38113684,"took":"2.842496ms"}
Jul 30 14:23:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:23:59.125+0300","caller":"etcdserver/server.go:1390","msg":"triggering snapshot","local-member-id":"74d87de777c36d9b","local-member-applied-index":42214592,"local-member-snapshot-index":42114591,"local-member-snapshot-count":100000}
Jul 30 14:23:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:23:59.127+0300","caller":"etcdserver/server.go:2381","msg":"saved snapshot","snapshot-index":42214592}
Jul 30 14:23:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:23:59.127+0300","caller":"etcdserver/server.go:2423","msg":"compacted Raft logs","compact-index":42209592}
Jul 30 14:23:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:23:59.559+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38115536}
Jul 30 14:23:59 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:23:59.562+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38115536,"took":"2.874136ms"}
Jul 30 14:24:09 master-02 etcd[10706]: {"level":"info","ts":"2020-07-30T14:24:09.523+0300","caller":"fileutil/purge.go:79","msg":"purged","path":"/var/lib/etcd/member/snap/000000000000034a-00000000027c839a.snap"}

Jul 30 13:33:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:33:59.512+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38096972}
Jul 30 13:33:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:33:59.515+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38096972,"took":"2.709666ms"}
Jul 30 13:38:44 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:38:44.883+0300","caller":"wal/wal.go:698","msg":"created a new WAL segment","path":"/var/lib/etcd/member/wal/000000000000000f-000000000283dca8.wal"}
Jul 30 13:38:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:38:59.517+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38098827}
Jul 30 13:38:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:38:59.520+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38098827,"took":"2.736166ms"}
Jul 30 13:39:03 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:39:03.371+0300","caller":"fileutil/purge.go:79","msg":"purged","path":"/var/lib/etcd/member/wal/000000000000000a-00000000027e3f2d.wal"}
Jul 30 13:43:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:43:59.522+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38100681}
Jul 30 13:43:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:43:59.525+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38100681,"took":"2.748017ms"}
Jul 30 13:48:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:48:59.527+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38102537}
Jul 30 13:48:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:48:59.537+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38102537,"took":"6.349875ms"}
Jul 30 13:53:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:53:59.532+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38104388}
Jul 30 13:53:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:53:59.535+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38104388,"took":"2.638989ms"}
Jul 30 13:58:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:58:59.535+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38106245}
Jul 30 13:58:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T13:58:59.540+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38106245,"took":"3.328782ms"}
Jul 30 14:03:32 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:32.622+0300","caller":"etcdserver/server.go:1390","msg":"triggering snapshot","local-member-id":"d00e45ffe6a40a1b","local-member-applied-index":42206264,"local-member-snapshot-index":42106263,"local-member-snapshot-count":100000}
Jul 30 14:03:32 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:32.625+0300","caller":"etcdserver/server.go:2381","msg":"saved snapshot","snapshot-index":42206264}
Jul 30 14:03:32 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:32.625+0300","caller":"etcdserver/server.go:2423","msg":"compacted Raft logs","compact-index":42201264}
Jul 30 14:03:33 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:33.369+0300","caller":"fileutil/purge.go:79","msg":"purged","path":"/var/lib/etcd/member/snap/000000000000034a-00000000027c6312.snap"}
Jul 30 14:03:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:59.540+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38108101}
Jul 30 14:03:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:03:59.543+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38108101,"took":"2.733979ms"}
Jul 30 14:08:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:08:59.545+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38109974}
Jul 30 14:08:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:08:59.549+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38109974,"took":"2.7224ms"}
Jul 30 14:13:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:13:59.549+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38111827}
Jul 30 14:13:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:13:59.553+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38111827,"took":"2.730662ms"}
Jul 30 14:18:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:18:59.555+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38113684}
Jul 30 14:18:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:18:59.558+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38113684,"took":"2.739966ms"}
Jul 30 14:23:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:23:59.559+0300","caller":"mvcc/index.go:189","msg":"compact tree index","revision":38115536}
Jul 30 14:23:59 master-03 etcd[30005]: {"level":"info","ts":"2020-07-30T14:23:59.562+0300","caller":"mvcc/kvstore_compaction.go:56","msg":"finished scheduled compaction","compact-revision":38115536,"took":"2.726653ms"}
