### ISSUE TITLE
What are the analogues in API v3 to get information as in API v2?

### ISSUE THREAD

**Issue by newman0089** [etcd-io/etcd#12182]
Hello!
I used to use the APIv2 version of etcd in conjunction with patroni, and to get various information about the patroni cluster, I used the following commands:
`etcdctl ls --recursive --sort -p /service/<patroni_cluster_name>` - to get stored information in etcd
`etcdctl get /service/<patroni_cluster_name>/history` - history of the last failover

In v3, these commands do not work. I tried to execute etcdctl get <patroni_cluster_name> but the command returns nothing.

Please tell me if there are similar commands in v3?

**Comment by polyrabbit** [comment]
Try the `--prefix` flag
