### ISSUE TITLE
transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused

### ISSUE THREAD

**Issue by SHUFIL** [etcd-io/etcd#12190]
I getting below error when i connect etcd from `micro/micro` .
Userd  `etcd 3.4.10`   version from bitnami/etcd , with `--set auth.rbac.enabled=false`,  how to resolve this issue ?

I have tryed to direct etcd service name with port and forward to localhost:port , but still getting same issue , also i tryed to install different version etcd , with cluster and non cluster .

```
2020-07-31 12:44:30  file=runtime/service.go:217 level=error service=micro Service micro.web terminated with error exit status 1
{"level":"warn","ts":"2020-07-31T12:44:30.900Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-39326eaa-43d2-46ad-9139-e0a5df665c06/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
```

**Comment by spzala** [comment]
I think you should check with them, possibly some users there might have ran into a similar problem previously.

**Comment by sw919678915** [comment]
etcd version 3.4.10
When I use the command " etcdctl member list"
error:{"level":"warn","ts":"2020-08-22T15:07:31.359+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3123f51f-bbf8-4c96-a383-05e6afd88ff9/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}

**Comment by ash7985** [comment]
Got the same issue
I was just following => https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md#configure-the-etcd-server

**Comment by gregroe** [comment]
getting the same issue as ash7985.   is there a resolution.  it seems at though the master-1 errors on-listen-client-urls https://${INTERNAL_IP}:2379,https://127.0.0.1:2379    


vagrant@master-1:~$ {
>   sudo systemctl daemon-reload
>   sudo systemctl enable etcd
>   sudo systemctl start etcd
> }
vagrant@master-1:~$ sudo ETCDCTL_API=3 etcdctl member list   --endpoints=https://127.0.0.1:2379   --cacert=/etc/etcd/ca.crt   --cert=/etc/etcd/etcd-server.crt   --key=/etc/etcd/etcd-server.key


**Error: dial tcp 127.0.0.1:2379: connect: connection refused**

**Comment by koehn** [comment]
I'm seeing this in `k8s.gcr.io/etcd:3.4.13-0` under k8s 1.20.1:

```
2020-12-15 21:22:50.878774 N | pkg/osutil: received terminated signal, shutting down...
WARNING: 2020/12/15 21:22:50 grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
2020-12-15 21:22:50.983176 I | etcdserver: skipped leadership transfer for single voting member cluster
```

**Comment by santoshverma608** [comment]
You're using cloud Instance, please use private IP of instance while running "kubeadm init"

**Comment by shahGnp** [comment]
Dealing with same issue. The ETCD connection on 127.0.0.1 2379 takes a lot of time to come online ~5 minutes. The system usage are normal: Disk RW speed, CPU usage and network bandwidth. The firewall is disabled.

```Jan 20 06:25:56 rke2[2769]: time="2025-01-20T06:25:56Z" level=info msg="Waiting for API server to become available"
Jan 20 06:25:56 rke2[2769]: time="2025-01-20T06:25:56Z" level=info msg="Waiting for etcd server to become available"
Jan 20 06:26:01 rke2[2769]: time="2025-01-20T06:26:01Z" level=info msg="Failed to test data store connection: failed to get etcd status: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""
Jan 20 06:26:04 rke2[2769]: time="2025-01-20T06:26:04Z" level=error msg="Failed to check local etcd status for learner management: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""
Jan 20 06:26:06 rke2[2769]: time="2025-01-20T06:26:06Z" level=info msg="Failed to test data store connection: failed to get etcd status: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""
Jan 20 06:26:11 rke2[2769]: time="2025-01-20T06:26:11Z" level=info msg="Failed to test data store connection: failed to get etcd status: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""
Jan 20 06:26:16 rke2[2769]: time="2025-01-20T06:26:16Z" level=info msg="Connected to etcd v3.5.16 - datastore using 16384 of 20480 bytes"
Jan 20 06:26:16 rke2[2769]: time="2025-01-20T06:26:16Z" level=info msg="Defragmenting etcd database"
Jan 20 06:26:16 rke2[2769]: time="2025-01-20T06:26:16Z" level=info msg="Datastore using 12288 of 20480 bytes after defragment"
Jan 20 06:26:16 rke2[2769]: time="2025-01-20T06:26:16Z" level=info msg="etcd data store connection OK"
Jan 20 06:26:16 rke2[2769]: time="2025-01-20T06:26:16Z" level=info msg="Saving cluster bootstrap data to datastore"
```
