### ISSUE TITLE
raftexample: join a new node got panic

### ISSUE THREAD

**Issue by nicktming** [etcd-io/etcd#12191]
when a etcd cluster works well, currently joining a new node will get panic.

**Reproduce**
```
raftexample --id 1 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 --port 12380
raftexample --id 2 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 --port 22380
raftexample --id 3 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 --port 32380
--- 
got a leader and joins a new node 4
curl -L http://127.0.0.1:12380/4 -XPOST -d http://127.0.0.1:42379
./raftexample --id 4 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379,http://127.0.0.1:42379 --port 42380 --join
```
will get the following error
```
2020/08/01 11:45:36 replaying WAL of member 4
2020/08/01 11:45:36 loading WAL at term 0 and index 0
panic: no peers given; use RestartNode instead

goroutine 27 [running]:
go.etcd.io/etcd/v3/raft.StartNode(0xc000107f20, 0x0, 0x0, 0x0, 0x0, 0xc00010e660)
	/Users/xxx/gocode/src/go.etcd.io/etcd/raft/node.go:218 +0x421
main.(*raftNode).startRaft(0xc0000e2b00)
	/Users/xxx/gocode/src/go.etcd.io/etcd/contrib/raftexample/raft.go:293 +0x613
created by main.newRaftNode
	/Users/xxx/gocode/src/go.etcd.io/etcd/contrib/raftexample/raft.go:106 +0x35f
```

**Why**
when joining a new node, raftexample will use raft.StatNode with setting startPeers = nil at **contrib/raftexample/raft.go** to avoid executing **rn.Bootstrap**.
As i know rn.Bootstrap will initializes the init entries&commits and apply changes for the supplied peers, but these entries should come from log replication and conf changes will also be applied to the new node after joining the cluster sucessfully, which is the reason why this should panic here.
```
// contrib/raftexample/raft.go
func (rc *raftNode) startRaft() {
      ...
       if oldwal {
		rc.node = raft.RestartNode(c)
	} else {
		startPeers := rpeers
		if rc.join {
			startPeers = nil
		}
		rc.node = raft.StartNode(c, startPeers)
	}
        ...
}

// raft/node.go
func StartNode(c *Config, peers []Peer) Node {
	if len(peers) == 0 {
		panic("no peers given; use RestartNode instead")
	}
	...
	rn.Bootstrap(peers) 
        ...
	return &n
}
```

**Fix**
this node should not be allowed to execute Bootstrap function while joining an existing cluster, then it could use RestartNode to avoid Bootstrap function at **contrib/raftexample/raft.go**
```
// contrib/raftexample/raft.go
func (rc *raftNode) startRaft() {
	...
	if oldwal || rc.join {
		rc.node = raft.RestartNode(c)
	} else {
		rc.node = raft.StartNode(c, rpeers)
	}
	...
	go rc.serveRaft()
	go rc.serveChannels()
}
```
After these changes, it works well.

**Comment by achenet** [comment]
Not sure why this is marked as stale/closed, as it it still not resolved. 

Another solution is calling if there is a call to join, call the StartNode method with the peers list set to just the new node. 

`
if oldwal {
rc.node = raft.RestartNode(c)
} else {
startPeers := rpeers
if rc.join {
startPeers := append([]raft.Peers{}, rpeers[len(rpeers)-1])
}
rc.node = raft.StartNode(c, startPeers)
}
`
