### ISSUE TITLE
 What are the consequences of this warning, which print "took too long to execute"?

### ISSUE THREAD

**Issue by xmwilldo** [etcd-io/etcd#12205]
I built a k8s cluster with three etcd server. But  my network is not good possibility. About 200ms delay between each etcd server, so I find the etcd's log print the warning. 
![image](https://user-images.githubusercontent.com/16560252/89600962-ed3ac580-d895-11ea-99b8-e5d16f37a36e.png)
but my cluster work good and healthy.
![image](https://user-images.githubusercontent.com/16560252/89601573-7acae500-d897-11ea-817e-13e5ed46b9c6.png)
I tried to google what effect this warning will cause. But I find nothing.
I am very eager to get an official answer！Thanks!

**Comment by feilengcui008** [comment]
see issue #9111 and this pr：https://github.com/etcd-io/etcd/pull/9288
