### ISSUE TITLE
Is there any way to watch etcd membership change

### ISSUE THREAD

**Issue by xrmzju** [etcd-io/etcd#12207]
user can  watch membership change in the same way as watching a normal key and act according the change.

**Comment by jingyih** [comment]
The answer is no. But you might find etcd operator helpful. My understanding is that it creates CRD that represents etcd server, watches the corresponding CRs, and acts according to the watch events.

**Comment by xrmzju** [comment]
> The answer is no. But you might find etcd operator helpful. My understanding is that it creates CRD that represents etcd server, watches the corresponding CRs, and acts according to the watch events.

yeah, but your cr controller should have the same problem.

**Comment by jingyih** [comment]
> > The answer is no. But you might find etcd operator helpful. My understanding is that it creates CRD that represents etcd server, watches the corresponding CRs, and acts according to the watch events.
> 
> yeah, but your cr controller should have the same problem.

In this case, CR (which represents an etcd server) is a key, which can be watched.

**Comment by spzala** [comment]
Thanks @jingyih for answering the question!
