### ISSUE TITLE
Is there a viewer to lookup data inside etcd snapshot?

### ISSUE THREAD

**Issue by sridhav** [etcd-io/etcd#12220]
As etcd3 uses boltdb internally, is it possible if we can use boltdb browsers/any viewer to lookup the data inside the snapshot?

**Comment by jingyih** [comment]
Yes you can use bbolt tool. https://github.com/etcd-io/bbolt/tree/master/cmd/bbolt

**Comment by sridhav** [comment]
@jingyih I tried using that, but am unable to lookup by etcd key name, all keys are in hexadecimal format. Looks like etcd keys are stored inside the values of bolt key. Can you suggest some documentation on how to use this bbolt viewer?

**Comment by jingyih** [comment]
Could you also try this tool?

https://github.com/etcd-io/etcd/tree/master/tools/etcd-dump-db

**Comment by jingyih** [comment]
If your etcd stores kubernetes data, this tool is very useful: https://github.com/jpbetz/auger

**Comment by polyrabbit** [comment]
> If your etcd stores kubernetes data, this tool is very useful: https://github.com/jpbetz/auger

Another tool to view Kubernetes data is to mount it to your local filesystem, and do whatever you want: [etcdfs](https://github.com/polyrabbit/etcdfs).
