### ISSUE TITLE
Remove references to now-dead "etcd-operator"?

### ISSUE THREAD

**Issue by cakoose** [etcd-io/etcd#12223]
https://etcd.io/docs/v3.4.0/platforms/aws/ says:

> **Next steps**
> 
> The operational life cycle of an etcd cluster can be greatly simplified through the use of the etcd-operator. The open source etcd operator is a Kubernetes control plane operator which deploys and manages etcd clusters atop Kubernetes. While still in its early stages the etcd-operator already offers periodic backups to S3, detection and replacement of failed nodes, and automated disaster recovery from backups in the event of permanent quorum loss.

However, if I search for "etcd-operator", the first link is https://github.com/coreos/etcd-operator which says:

> **Project status: archived**
>
> This project is no longer actively developed or maintained. The project exists here for historical reference. If you are interested in the future of the project and taking over stewardship, please contact etcd-dev@googlegroups.com.

Should the reference to etcd-operator be removed?

**Comment by tooolbox** [comment]
Or perhaps updated with the [fork](https://github.com/cbws/etcd-operator) that apparently [has someone who cares about keeping it alive](https://blog.cloudbear.nl/reviving-etcd-operator/).
