### ISSUE TITLE
etcd 2.3.7 data loss due to `—initial-cluster-state=new` flag

### ISSUE THREAD

**Issue by krmayankk** [etcd-io/etcd#12227]
**What happened:**

A 3 node etcd cluster was running with static configuration. Lets call them 1-1, 2-1 and 3-1. All of these nodes were running with `—initial-cluster-state=new`. As per documentation this is supposed to be ignored after quorum formation, so it was not changed.

- 3-1 lost its data and started a new cluster id with an empty data set
- 2-1 had an unexpected IO error , it restarted thinking it had an empty data directory, and paired up with 3-1 to form a new quorum and they shared the empty data set with each other.
- 1-1 restarted, and since the `—initial-cluster-state=new`, it joined the cluster of 3-1 and 2-1 who were already in quorum. 1-1 never lost its data, but since it joined the new cluster with 3-1 and 2-1, the quorum members convinced 1-1 to replicate their empty data to it.

**Logs**

- 1-1 and 2-1 start receiving mismatched clusterId requests from 3-1
```
Jan 13 08:47:28 <1-1 machine name> docker[119145]:
2018-01-13 08:47:28.025145 E | rafthttp: request cluster ID mismatch
(got eb9cd3f16ca99464 want 6fd48c0f31dacced)
```
This  indicates that 3-1 lost its data first, created a new raft instance, and was trying to join the others.

- 2-1 received termination message
```
Jan 13 08:58:29 <2-1 machine name> docker[172020]:
2018-01-13 08:58:29.716982 N | osutil: received terminated signal, shutting down...
```
Etcd on 2-1 comes back up, but immediately exits because it got permission denied trying to write to its data directory.

```
Jan 13 08:58:41<2-1 machine name> docker[192352]:
2018-01-13 08:58:41.349269 C | etcdmain: cannot access data directory*:** *
open /cowdata/etcd/.touch: permission denied
```
The next etcd start on 2-1 show no indication of seeing any data on its disk.  Logs show it taking the code path for empy data directory, in which case it reaches out to its peers to get data from one of them.  It talks to 3-1 and the two establish quorum on this new Cluster ID, sharing the essentially empty data set. 

```
Jan 13 08:58:51 <2-1 machine name>  docker[192644]:
 2018-01-13 08:58:51.875376 I | etcdserver: starting member 72e421768592731f
 in cluster eb9cd3f16ca99464
 
 Jan 13 08:58:51 <2-1 machine name> docker[192644]:
 2018-01-13 08:58:51.875425 I | raft: 72e421768592731f became follower at term 0
 
 an 13 08:58:51 <2-1 machine name> docker[192644]:
 2018-01-13 08:58:51.875442 I | raft: newRaft 72e421768592731f [peers: [], term: 0,
  commit: 0, applied: 0, lastindex: 0, lastterm: 0]
  
 Jan 13 08:58:51 <2-1 machine name> docker[192644]:
 2018-01-13 08:58:51.875448 I | raft: 72e421768592731f became follower at term 1
```

we can see etcd on 2-1 rejecting requests from 1-1 because it was on the old ClusterID.  At this point 1-1 probably had a complete good data set, but it was not part of quorum so nobody could query it.

```
Jan 13 09:00:35 <2-1 machine name> docker[192644]:
2018-01-13 09:00:35.615530 E | rafthttp: request sent was ignored (cluster ID 
mismatch: remote[c36bf78c0fcb16cc]=6fd48c0f31dacced, local=eb9cd3f16ca99464)
```

Later, etcd on 1-1 restarts and it joins the other 2 with the new cluster ID and syncs the empty raft data. 
```
Jan 13 12:08:05 shared0-samkubeapi1-1-prd.eng.sfdc.net docker[142968]:
2018-01-13 12:08:05.933206 I | raft: 3df4c8b397e699d1 [logterm: 6, index: 316480] 
sent vote request to 82b6d29c56329bb9 at term 7
```

**What you expected to happen:**
- etcd to not loose data
- after loosing data, etcd to not come up with a new cluster id 
- if there was data loss on two etcd members, they should both form a new cluster id, why did they join each other in quorum
- etcd 1-1 to not join the quorum and replicate loose its data by replicating the empty set

It seems that on data loss or io error, etcd code paths is to create an empty data set and start a new cluster id. But if the flag was `—initial-cluster-state=new`, then it should have formed a new cluster id on both etcd machines where data loss occured(3-1 and 2-1).

**How to reproduce it (as minimally and precisely as possible):**

**Environment:**

Kubernetes version (use kubectl version): v1.10.8
etcd version: v2.3.7
Cloud provider or hardware configuration: Bare Metal
OS (e.g: cat /etc/os-release): centos 7
Kernel (e.g. uname -a): 3.10.0

I want to inform the community that keeping `—initial-cluster-state=new` is a very dangerous configuration in this situation and if it was. `—initial-cluster-state=existing`, it could have prevented the last etcd node(1-1) from joining the empty quorum members(3-1 and 2-1) and thus losing all data. This is not highlighted in the documentation anywhere and we should update it. Also if there is anything wrong in my understanding so far, would like to learn from etcd experts.

**Comment by jingyih** [comment]
Both etcd v2 and k8s v1.10 is out of support window. Please use etcd v3.2+.

**Comment by krmayankk** [comment]
thanks @jingyih ,we are already in the process of upgrading. But any comment on my conclusion, does that make sense ?

**Comment by jingyih** [comment]
Sorry I have not directly worked on etcd v2 in the past. So I do not know if the flag semantics have changed or not from v2 to v3.

**Comment by krmayankk** [comment]
thanks @jingyih just from v3 perspective, do you think its dangerous to run into this if the flag remains new and we run into corruption issues ?
More specifically, what is the behavior of etcd v3 if the flag remains 'new'
- when an etcd member restarts with complete data loss, would it get a new cluster id ?
- if two of three members form a quorum with empty set, would they replicate the empty data set to the third member with flag as new ?

Do we need to clarify any documentation or build more safe guards in the code ?

**Comment by jingyih** [comment]
> do you think its dangerous to run into this if the flag remains new and we run into corruption issues ?

I am not aware of any corruption that is due to the setting of this flag.

> when an etcd member restarts with complete data loss, would it get a new cluster id ?

No. It should cross check with existing members in the cluster [1].

> if two of three members form a quorum with empty set, would they replicate the empty data set to the third member with flag as new ?

No. Only leader can replicate its data to followers. Members with empty set will not become a raft leader in the case you described.

[1] https://github.com/etcd-io/etcd/blob/0526f461e1d35f13a85836674951cb12c6bee187/etcdserver/server.go#L376
