### ISSUE TITLE
etcd release 3.3.23 seems to report the wrong version

### ISSUE THREAD

**Issue by xperimental** [etcd-io/etcd#12230]
I've just downloaded the linux release tarball of [3.3.23](https://github.com/etcd-io/etcd/releases/tag/v3.3.23) and noticed that the binaries are reporting the wrong version. The commit-hash reported by the binary seems to be fine (4873f5516). The SHA-256 sum of the downloaded tarball matches the sum in the supplied file.

The same issue is also present on the Docker image. I have not checked the other release files but I assume that the issue is also present for the other operating systems.

Example output of Docker image:

```bash
> docker run --rm -it gcr.io/etcd-development/etcd:v3.3.23 etcd --version
etcd Version: 3.3.22
Git SHA: 4873f5516
Go Version: go1.12.17
Go OS/Arch: linux/amd64
> docker run --rm -it gcr.io/etcd-development/etcd:v3.3.23 etcdctl --version
etcdctl version: 3.3.22
API version: 2
```

**Comment by wenjiaswe** [comment]
3.3.25 is good, I think it's probably introduced by #12073 when importing a go.etcd.io path and now fixed by #12246.

**Comment by xperimental** [comment]
Yes, the issue is not present in versions 3.3.24 or 3.3.25 released since I have created the issue. It looks as if the trade-off was to remove the `go.mod` and `go.sum` files from the `release-3.3` branch (see fd9a5b0be547c9d54fe0554ac71028a381d26fe2). I don't know if it is planned to reinstate those files.

Either way, I think it would be a good idea to mention that 3.3.23 is reporting the wrong version somewhere on the release documentation for that release and mention this as fixed in the changelog so that nobody gets confused.

**Comment by spzala** [comment]
@xperimental @wenjiaswe I believe this is a dup of https://github.com/etcd-io/etcd/issues/12154 - so we can close this one and track the progress in the #12154 if that sounds OK? @gyuho has mentioned that he will be fixing the version string in the github tag for 3.3.23. Thanks!

**Comment by wenjiaswe** [comment]
@spzala you are right, sorry my mistake. Closing this one and track in #12154 sounds good to me.

**Comment by spzala** [comment]
@wenjiaswe oh no worries, and that's great, thanks Wenjia!

**Comment by spzala** [comment]
@xperimental closing as a dup but please feel free to reopen if needed. Thanks!

**Comment by xperimental** [comment]
@spzala No worries, while I checked to see if this issue was already known I did not spot the other issue. Should have spent more time on that.
