### ISSUE TITLE
Feature Request: expose maximum database size in metrics

### ISSUE THREAD

**Issue by neilschelly** [etcd-io/etcd#12248]
It would be helpful to monitor the database size against the configured `--quota-backend-bytes` limit so that you can head off any issues where the database is growing up to the maximum limit size.

I propose a new metric called `etcd_mvcc_db_max_size_in_bytes` that can be easily compared to `etcd_mvcc_db_total_size_in_bytes` and `etcd_mvcc_db_total_size_in_use_in_bytes` to track database size.

**Comment by jingyih** [comment]
Please refer to `etcd_server_quota_backend_bytes` metric.

**Comment by neilschelly** [comment]
Well, there it is then. I swear I spent an hour looking for that before putting in this feature request. Thank you!
