### ISSUE TITLE
Understanding etcd code of RawNode

### ISSUE THREAD

**Issue by microyahoo** [etcd-io/etcd#12253]
Hi,

I am currently trying to understand the code implementation for etcd. I am trying to understand different workflows, but I have two questions want to clarify when reading RawNode code.

1. I notice the `RawNode.Ready()` method isn't been referenced anymore, instead of unit tests. Why does it still exist in etcd code?
https://github.com/etcd-io/etcd/blob/ae66916226f4dad3e13c1a52dffc34ce41859879/raft/rawnode.go#L125

2. There is a `msgs` field in raft struct which works as a queue to cache messages wanted to send to peers, they will be populated to `Ready` struct and send to application(with regards to raft), it will invoke `RawNode.acceptReady` to reset `raft.msgs` cache after send `Ready` to `readyc` channel. Since messages  are still being produced **when and after** populate `Ready` struct, and `raft.msgs` has no lock to gurantee mutex. So my question is, is it possible to discard messages that have not been processed? I think the probability is very high, please correct me if I am wrong. Thanks.

https://github.com/etcd-io/etcd/blob/ae66916226f4dad3e13c1a52dffc34ce41859879/raft/raft.go#L275
```
func newReady(r *raft, prevSoftSt *SoftState, prevHardSt pb.HardState) Ready {
    rd := Ready{
        Entries:          r.raftLog.unstableEntries(),
        CommittedEntries: r.raftLog.nextEnts(),
        Messages:         r.msgs,         // ---> Ready will read msgs at a certain moment
    }
    if softSt := r.softState(); !softSt.equal(prevSoftSt) {
        rd.SoftState = softSt
    }
    if hardSt := r.hardState(); !isHardStateEqual(hardSt, prevHardSt) {
        rd.HardState = hardSt
    }
    if r.raftLog.unstable.snapshot != nil {
        rd.Snapshot = *r.raftLog.unstable.snapshot
    }
    if len(r.readStates) != 0 {
        rd.ReadStates = r.readStates
    }
    rd.MustSync = MustSync(r.hardState(), prevHardSt, len(rd.Entries))
    return rd
}
```
```
// acceptReady is called when the consumer of the RawNode has decided to go
// ahead and handle a Ready. Nothing must alter the state of the RawNode between
// this call and the prior call to Ready().
func (rn *RawNode) acceptReady(rd Ready) {
    if rd.SoftState != nil {
        rn.prevSoftSt = rd.SoftState
    }
    if len(rd.ReadStates) != 0 {
        rn.raft.readStates = nil
    }
    rn.raft.msgs = nil  // ---> raft.msgs will be flushed after send to readyc
}
```
Thanks for your clarification.

**Comment by microyahoo** [comment]
@tangcong  @jingyih @agargi

**Comment by NeverSayYouCanNot** [comment]
hello, have you solved this problem？

**Comment by NeverSayYouCanNot** [comment]
> hello, have you solved this problem？

Sorry to bother you, i have understand that problem beacuse operations execute sequentially
