### ISSUE TITLE
Client requests ignore WithRequireLeader except for RequestProgress

### ISSUE THREAD

**Issue by yebrahim** [etcd-io/etcd#12254]
Using Golang1.14.1 and clientv3, running on a local etcd v3.4.7.

While building some code around the `RequestProgress` feature, I noticed that I was able to do watches and puts with a `WithRequireLeader` context, but `RequestProgress` would fail to work with this turned on. If I omit the leader require things work as expected.
It's worth noting this repros both for an local embedded etcd on my mac (which likely doesn't have a leader by default?), *and* on my prod cluster, which *does* have a leader elected.

Here's some code to reproduce this, you can toggle between the two `client.Watch` lines and see the difference in the output. I'd expect things to work consistently one way or the other.

```
package main

import (
	"context"
	"fmt"
	"go.etcd.io/etcd/clientv3"
	"time"
)

func main() {
	client, err := clientv3.New(clientv3.Config{Endpoints: []string{"http://localhost:2379"}, DialTimeout: 5 * time.Second})
	if err != nil {
		panic(err)
	}
	fmt.Println("connected to etcd")

	// ch := client.Watch(context.Background(), "foo")
	ch := client.Watch(clientv3.WithRequireLeader(context.Background()), "foo")

	go func() {
		for {
			fmt.Println("Requesting progress and putting value..")
			client.RequestProgress(context.Background())
			client.Put(context.Background(), "foo", "x")
			time.Sleep(time.Second)
		}
	}()

	for resp := range ch {
		if resp.IsProgressNotify() {
			fmt.Println("Received progress notification")
		} else {
			fmt.Printf("Received PUT for %q: %q\n", resp.Events[0].Kv.Key, resp.Events[0].Kv.Value)
		}
	}
}
```

**Comment by agargi** [comment]
@yebrahim I generated table below. Its against 2 node cluster (etcd0 and etcd1) and x indicates the case where the node was killed. Problematic cases are 3 & 5. Is this what you are highlighting in this as well?

S. No. | Request type | WithRequireLeader | Endpoints | etcd0 | etcd1 | Outcome
-- | -- | -- | -- | -- | -- | --
1 | RequestProgress | Y | 79, 81 | x |   | Stopped with panic
2 | RequestProgress | Y | 79, 81 |   | x | Stopped with panic
3 | RequestProgress | Y | 79 | x |   | Running
4 | RequestProgress | Y | 81 |   | x | Stopped with panic
5 | Put | Y | 79 | x |   | Running
6 | Put | Y | 79 |   | x | Stopped with panic
7 | Put | Y | 79, 81 | x |   | Stopped with panic
8 | Put | Y | 79, 81 |   | x | Stopped with panic
9 | RequestProgress | N | 79, 81 | x |   | Running
10 | RequestProgress | N | 79, 81 |   | x | Running
11 | RequestProgress | N | 79 | x |   | Running
12 | RequestProgress | N | 81 | x |   | Running
13 | Put | N | 79 | x |   | Running
14 | Put | N | 81 |   | x | Running

**Comment by yebrahim** [comment]
Interesting. What do you mean by the ports under use?
For me, I was basically pointing out that `WithRequireLeader` works inconsistently across different APIs (`RequestProgress` vs `Put` for example).

**Comment by agargi** [comment]
I mean the ports used in endpoints. So I have captured the endpoints used.

I did not see inconsistency between the API themselves as you can see from the table. FYI, I used the code from master (which might be few commits behind the master branch).

`client, err := clientv3.New(clientv3.Config{Endpoints: []string{"http://localhost:2379","http://localhost:2380"}, DialTimeout: 5 * time.Second})`
