### ISSUE TITLE
memory leak: looks like KeyValue Unmarshal or txReaderBuffer cause

### ISSUE THREAD

**Issue by yangxuanjia** [etcd-io/etcd#12256]
k8s range all data in lots of concurrent connections, memory raise rapidly and never decline, may be memory leak.
we see the memory raise to 110G or 240G on physical machine, and never decline.
we stop all k8s server and restart the k8s, but do nothing. the high memory always keep in etcd.

Centos8.1
ETCD master

![Screenshot from 2020-08-25 15-07-10](https://user-images.githubusercontent.com/2627712/91159888-49f20900-e6fb-11ea-8849-7ce945b4fe2c.png)
![Screenshot from 2020-08-25 15-44-50](https://user-images.githubusercontent.com/2627712/91159754-0eefd580-e6fb-11ea-80a5-e0f6f5e89a1c.png)

**Comment by yangxuanjia** [comment]
[profile001_heap_inuse_space.svg.zip](https://github.com/etcd-io/etcd/files/5122947/profile001_heap_inuse_space.svg.zip)

**Comment by tangcong** [comment]
can you provide more info，such as etcd version，using v2 or v3，etcd log，etcd metrics?

**Comment by yangxuanjia** [comment]
[4.zip](https://github.com/etcd-io/etcd/files/5123053/4.zip)

**Comment by yangxuanjia** [comment]
[pprof.zip](https://github.com/etcd-io/etcd/files/5123056/pprof.zip)

**Comment by yangxuanjia** [comment]
> can you provide more info，such as etcd version，using v2 or v3，etcd log，etcd metrics?
etcd master branch,  using v3.
no etcd log.
I can support pprof heap metrics.

**Comment by tangcong** [comment]
it seems caused by concurrently readtx buffer. can you provide db_open_read_transactions metric value?

**Comment by yangxuanjia** [comment]
![Screenshot from 2020-08-26 09-55-35](https://user-images.githubusercontent.com/2627712/91246409-55d4de00-e782-11ea-97bd-690421da3bbb.png)

**Comment by tangcong** [comment]
How many keys does your cluster have? why there is no etcd log?  slow query will print warning message.  When did you restart the apiserver,  process_open_fds did not drop significantly?

**Comment by yangxuanjia** [comment]
this is a test etcd cluster for 10k k8s nodes, not online, so we not logger the etcd log.
We benchmark 1 billion proposals, I have not exact key cout.
We restart the apiserver after the memory raise, I want know whether memory will decline if connections interrupt,
because I guess txn readbuffer copy will release when connection interrupt.

**Comment by yangxuanjia** [comment]
maybe I catch the bug, it's really the txn read buffer bug cause the memory leak,
I will try to resolve it and then pull a PR for this bug.

**Comment by yangxuanjia** [comment]
I make test, watch the memory use, I find etcd occupy the big memory by txn read buffer,
and when txn read buffer run over, memory will release to [HeapReleased], then back to [HeapIdle].
golang doc say [HeapIdle] mean memory will go back to OS, but I need see it back to [HeapSys],
not back to real OS.

if there have other read OP, it will allocate memory from [HeapSys] to [HeapInuse]/[HeapAlloc],
OS top see memory will not raise again, it looks like etcd will hold the allocated memory as big memory cache.

I have 2 question,
1. how can I release etcd [HeapSys] memory to real OS?
2. concurrent txn read will make OOM when range all keys(billion level keys and 100 concurrents, 100G-200G easy to occupied),
memory will raise rapidly.


runtime.MemStats.HeapInuse, value, 1.68GB
runtime.MemStats.HeapAlloc, value, 1.68GB
runtime.MemStats.HeapReleased, value, 57.24GB 
runtime.MemStats.HeapIdle, value, 57.94GBNN
runtime.MemStats.HeapSys, value, 59.62GB
runtime.MemStats.TotalAlloc, value, 393.16GB 
------------------------------------------------
runtime.MemStats.HeapObjects, value, 17.17MB 
debug.GCStats.NumGC, value, 333.00B 
runtime.MemStats.StackInuse, value, 2.47MB 
runtime.MemStats.MSpanInuse, value, 5.81MB 
runtime.MemStats.HeapReleased, value, 57.24GB 
runtime.MemStats.GCCPUFraction, value, 0.00B 
runtime.NumGoroutine, value, 6.00B 
debug.GCStats.LastGC, value, 1.39EB 
runtime.MemStats.HeapAlloc, value, 1.43GB 
runtime.MemStats.DebugGC, value, 0.00B 
runtime.MemStats.MSpanSys, value, 49.14MB 
runtime.MemStats.MCacheSys, value, 128.00KB 
runtime.MemStats.StackSys, value, 2.47MB 
runtime.MemStats.HeapIdle, value, 58.19GB 
runtime.MemStats.Lookups, value, 0.00B 
debug.ReadGCStats, mean.rate, 0.00B 
debug.ReadGCStats, count, 94.00B 
debug.ReadGCStats, stddev, 4.03MB 
debug.ReadGCStats, 95%, 551.29KB 
debug.ReadGCStats, 5m.rate, 0.00B 
debug.ReadGCStats, 1m.rate, 0.00B 
debug.ReadGCStats, median, 24.76KB 
debug.ReadGCStats, 75%, 40.43KB 
debug.ReadGCStats, 99%, 39.27MB 
debug.ReadGCStats, 99.9%, 39.27MB 
debug.ReadGCStats, 15m.rate, 0.00B 
debug.ReadGCStats, min, 3.61KB 
debug.ReadGCStats, max, 39.27MB 
debug.ReadGCStats, mean, 528.17KB 
runtime.MemStats.PauseTotalNs, value, 213.50MB 
runtime.MemStats.NextGC, value, 2.25GB 
runtime.MemStats.Alloc, value, 1.43GB 
runtime.MemStats.NumGC, value, 4.00B 
debug.GCStats.Pause, min, 109.23KB 
debug.GCStats.Pause, max, 13.42MB 
debug.GCStats.Pause, mean, 965.72KB 
debug.GCStats.Pause, stddev, 2.09MB 
debug.GCStats.Pause, median, 569.84KB 
debug.GCStats.Pause, 99%, 13.42MB 
debug.GCStats.Pause, 99.9%, 13.42MB 
debug.GCStats.Pause, count, 87.00B 
debug.GCStats.Pause, 75%, 710.93KB 
debug.GCStats.Pause, 95%, 1.07MB 
runtime.MemStats.BuckHashSys, value, 1.38MB 
runtime.MemStats.PauseNs, max, 13.42MB 
runtime.MemStats.PauseNs, mean, 656.54KB 
runtime.MemStats.PauseNs, stddev, 1.10MB 
runtime.MemStats.PauseNs, 75%, 699.76KB 
runtime.MemStats.PauseNs, 99%, 7.60MB 
runtime.MemStats.PauseNs, count, 333.00B 
runtime.MemStats.PauseNs, min, 43.23KB 
runtime.MemStats.PauseNs, 99.9%, 13.42MB 
runtime.MemStats.PauseNs, median, 553.80KB 
runtime.MemStats.PauseNs, 95%, 992.23KB 
runtime.MemStats.MCacheInuse, value, 108.50KB 
runtime.ReadMemStats, min, 78.55KB 
runtime.ReadMemStats, 99%, 5.95GB 
runtime.ReadMemStats, 1m.rate, 0.00B 
runtime.ReadMemStats, mean.rate, 0.00B 
runtime.ReadMemStats, count, 94.00B 
runtime.ReadMemStats, 75%, 622.42KB 
runtime.ReadMemStats, 99.9%, 5.95GB 
runtime.ReadMemStats, 15m.rate, 0.00B 
runtime.ReadMemStats, max, 5.95GB 
runtime.ReadMemStats, mean, 144.82MB 
runtime.ReadMemStats, stddev, 871.26MB 
runtime.ReadMemStats, median, 320.45KB 
runtime.ReadMemStats, 95%, 347.13MB 
runtime.ReadMemStats, 5m.rate, 0.00B 
runtime.MemStats.Mallocs, value, 42.91KB 
runtime.MemStats.HeapInuse, value, 1.43GB 
runtime.MemStats.LastGC, value, 1.39EB 
runtime.NumThread, value, 70.00B 
runtime.MemStats.HeapSys, value, 59.62GB 
runtime.NumCgoCall, value, 0.00B 
runtime.MemStats.EnableGC, value, 1.00B 
runtime.MemStats.Frees, value, 41.86KB 
runtime.MemStats.Sys, value, 61.64GB 
runtime.MemStats.TotalAlloc, value, 393.16GB 
debug.GCStats.PauseTotal, value, 213.50MB

**Comment by yangxuanjia** [comment]
https://github.com/golang/go/issues/14521

**Comment by yangxuanjia** [comment]
maybe the resolve method is let k8s to modify.
k8s can't range all pods concurrently, k8s can range pods under their namespace to avoid txn reader buffer allocate big memory concurrently.

**Comment by yangxuanjia** [comment]
Hi tangcong,
I have some question, hope you can disabuse me.
If etcd have 10k nodes and 300k pods data on disk.
1. is backend txn read buffer has all data? 
I see the backend txn read buffer only write point when writeback, 
and the buffer can reset data when defrag and batchTxBuffered commit.
so how much data on txn read buffer, all data or only have recently write data?
2. If backend txn read buffer have lots of data.
Is any concurrent txn read need copy the backend txn read buffer?
2.1 if one txn read just get one key(short read), need I copy all txn read buffer?
2.2 if one txn read just range 100 keys(short read), need I copy all txn read buffer?
2.3 if one txn read just range large keys (long read), need I copy all txn read buffer?
I think the goal of concurrent read is resolve long read and write lock conflict, but short read and write conflict is very little.
so I have a new idea, split short read and long read, only long read copy backend txn read buffer, 
short read also add RLock to backend txn read buffer, maybe it can reduce the memory raise rapidly.

**Comment by tangcong** [comment]
txn read buffer only has recently write data,backend will commit data per 100ms(default) and reset read buffer,so in the case of normal commit data and db_open_read_transactions value is small , the buffer does not contain too much data.

The key issue is that you have to avoid ranging all data and it costs too much memory.  please follow some best practices and see k8s sla.
https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md

**Comment by yangxuanjia** [comment]
Hi tangcong,

If read buffer have little cache data,  why pprof show the most memory allocate through func (bb *bucketBuffer) Copy()???
Even if I have 100+ connections range all data concurrently, the most memory I think will cost on Add(), but not Copy().
How about your thinking?

**Comment by tangcong** [comment]
can you reproduce it stably? we can add some debug logs to see if commit is blocked and print buffer size.

**Comment by yangxuanjia** [comment]
Yes, k8s staff help me to press the etcd cluster, and I reproduce it 3 times.
And I code the testcase, just prove Copy() is really cost memory and memory release to golang HeadIdle but not back to OS.

```
package main

import (
	"bytes"
	"fmt"
	"net/http"
	"sort"
	"sync"
	"time"

	_ "net/http/pprof"
    go_metrics "github.com/rcrowley/go-metrics"
	go_bytesize "github.com/inhies/go-bytesize"
)

// txBuffer handles functionality shared between txWriteBuffer and txReadBuffer.
type txBuffer struct {
	buckets map[string]*bucketBuffer
}

func (txb *txBuffer) reset() {
	for k, v := range txb.buckets {
		if v.used == 0 {
			// demote
			delete(txb.buckets, k)
		}
		v.used = 0
	}
}

// txWriteBuffer buffers writes of pending updates that have not yet committed.
type txWriteBuffer struct {
	txBuffer
	seq bool
}

func (txw *txWriteBuffer) put(bucket, k, v []byte) {
	txw.seq = false
	txw.putSeq(bucket, k, v)
}

func (txw *txWriteBuffer) putSeq(bucket, k, v []byte) {
	b, ok := txw.buckets[string(bucket)]
	if !ok {
		b = newBucketBuffer()
		txw.buckets[string(bucket)] = b
	}
	b.add(k, v)
}

func (txw *txWriteBuffer) writeback(txr *txReadBuffer) {
	for k, wb := range txw.buckets {
		rb, ok := txr.buckets[k]
		if !ok {
			delete(txw.buckets, k)
			txr.buckets[k] = wb
			continue
		}
		if !txw.seq && wb.used > 1 {
			// assume no duplicate keys
			sort.Sort(wb)
		}
		rb.merge(wb)
	}
	txw.reset()
}

// txReadBuffer accesses buffered updates.
type txReadBuffer struct{ txBuffer }

func (txr *txReadBuffer) Range(bucketName, key, endKey []byte, limit int64) ([][]byte, [][]byte) {
	if b := txr.buckets[string(bucketName)]; b != nil {
		return b.Range(key, endKey, limit)
	}
	return nil, nil
}

func (txr *txReadBuffer) ForEach(bucketName []byte, visitor func(k, v []byte) error) error {
	if b := txr.buckets[string(bucketName)]; b != nil {
		return b.ForEach(visitor)
	}
	return nil
}

// unsafeCopy returns a copy of txReadBuffer, caller should acquire backend.readTx.RLock()
func (txr *txReadBuffer) unsafeCopy() txReadBuffer {
	txrCopy := txReadBuffer{
		txBuffer: txBuffer{
			buckets: make(map[string]*bucketBuffer, len(txr.txBuffer.buckets)),
		},
	}
	for bucketName, bucket := range txr.txBuffer.buckets {
		txrCopy.txBuffer.buckets[bucketName] = bucket.Copy()
	}
	return txrCopy
}

type kv struct {
	key []byte
	val []byte
}

// bucketBuffer buffers key-value pairs that are pending commit.
type bucketBuffer struct {
	buf []kv
	// used tracks number of elements in use so buf can be reused without reallocation.
	used int
}

func newBucketBuffer() *bucketBuffer {
	return &bucketBuffer{buf: make([]kv, 512), used: 0}
}

func (bb *bucketBuffer) Range(key, endKey []byte, limit int64) (keys [][]byte, vals [][]byte) {
	f := func(i int) bool { return bytes.Compare(bb.buf[i].key, key) >= 0 }
	idx := sort.Search(bb.used, f)
	if idx < 0 {
		return nil, nil
	}
	if len(endKey) == 0 {
		if bytes.Equal(key, bb.buf[idx].key) {
			keys = append(keys, bb.buf[idx].key)
			vals = append(vals, bb.buf[idx].val)
		}
		return keys, vals
	}
	if bytes.Compare(endKey, bb.buf[idx].key) <= 0 {
		return nil, nil
	}
	for i := idx; i < bb.used && int64(len(keys)) < limit; i++ {
		if bytes.Compare(endKey, bb.buf[i].key) <= 0 {
			break
		}
		keys = append(keys, bb.buf[i].key)
		vals = append(vals, bb.buf[i].val)
	}
	return keys, vals
}

func (bb *bucketBuffer) ForEach(visitor func(k, v []byte) error) error {
	for i := 0; i < bb.used; i++ {
		if err := visitor(bb.buf[i].key, bb.buf[i].val); err != nil {
			return err
		}
	}
	return nil
}

func (bb *bucketBuffer) add(k, v []byte) {
	bb.buf[bb.used].key, bb.buf[bb.used].val = k, v
	bb.used++
	if bb.used == len(bb.buf) {
		buf := make([]kv, (3*len(bb.buf))/2)
		copy(buf, bb.buf)
		bb.buf = buf
	}
}

// merge merges data from bbsrc into bb.
func (bb *bucketBuffer) merge(bbsrc *bucketBuffer) {
	for i := 0; i < bbsrc.used; i++ {
		bb.add(bbsrc.buf[i].key, bbsrc.buf[i].val)
	}
	if bb.used == bbsrc.used {
		return
	}
	if bytes.Compare(bb.buf[(bb.used-bbsrc.used)-1].key, bbsrc.buf[0].key) < 0 {
		return
	}

	sort.Stable(bb)

	// remove duplicates, using only newest update
	widx := 0
	for ridx := 1; ridx < bb.used; ridx++ {
		if !bytes.Equal(bb.buf[ridx].key, bb.buf[widx].key) {
			widx++
		}
		bb.buf[widx] = bb.buf[ridx]
	}
	bb.used = widx + 1
}

func (bb *bucketBuffer) Len() int { return bb.used }
func (bb *bucketBuffer) Less(i, j int) bool {
	return bytes.Compare(bb.buf[i].key, bb.buf[j].key) < 0
}
func (bb *bucketBuffer) Swap(i, j int) { bb.buf[i], bb.buf[j] = bb.buf[j], bb.buf[i] }

func (bb *bucketBuffer) Copy() *bucketBuffer {
	bbCopy := bucketBuffer{
		buf:  make([]kv, len(bb.buf)),
		used: bb.used,
	}
	copy(bbCopy.buf, bb.buf)
	return &bbCopy
}



func main(){
	
	cc := make(chan []int, 1)

	go func() {
		http.ListenAndServe("0.0.0.0:8080", nil)
	}()

	go func() {
		registry := go_metrics.NewRegistry()
		go_metrics.RegisterRuntimeMemStats(registry)
		go_metrics.RegisterDebugGCStats(registry)

		go go_metrics.CaptureRuntimeMemStats(registry, 10 * time.Second)
		go go_metrics.CaptureDebugGCStats(registry, 10 * time.Second)

		t := time.NewTimer(10 * time.Second)
		defer t.Stop()
		for {
			select {
			case <-t.C:
				for kk, vv := range registry.GetAll() {
					for k, v := range vv {
						var ff float64
						switch vvv := v.(type) {
						case int64:
							ff = float64(vvv)
						    break
						case float64:
							ff = float64(vvv)
							break
						default:
							fmt.Printf("not handle this value type, kk:%s, k: %s, v: %s", kk, k, vvv)
						}

						bb := go_bytesize.New(ff)
						fmt.Printf("%s, %s, %s \n", kk, k, bb.String())
					}
				}
				fmt.Println("---------------------------------------")
				t.Reset(10 * time.Second)
			}
		}
	}()

	txReadBuf := new(txReadBuffer)
	txReadBuf.buckets = make(map[string]*bucketBuffer)
	for i:=0; i<3000; i++ {
		txReadBuf.buckets[string(i)] = newBucketBuffer()
		for j:=0; j<3000; j++ {
			txReadBuf.buckets[string(i)].add([]byte("aaaaa"+string(i)+"_"+string(j)), []byte("bbbbb"+string(i)+"_"+string(j)))
		}
	}

	wg := sync.WaitGroup{}

	allocCopy := func () {
		for k:=0; k<100; k++ {
			wg.Add(1)
			go func(kk int) {
				defer wg.Done()
				a1 := txReadBuf.unsafeCopy()
				fmt.Printf("golang thread %d, len: %d\n", kk, len(a1.buckets))
			}(k)

			time.Sleep(200*time.Millisecond)
		}
		return
	}

	allocCopy()

	wg.Wait()
	fmt.Printf("golang thread run finish!!! \n")
	fmt.Printf("single run start!!! \n")

	for k:=0; k<10000; k++ {
		a1 := txReadBuf.unsafeCopy()
		fmt.Printf("single run time number %d, len: %d\n", k, len(a1.buckets))
		time.Sleep(200*time.Millisecond)
	}

	select {
	case <-cc:
	}
}

```

**Comment by yangxuanjia** [comment]
Hi tangcong,

My thinking is wrong, the most memory used is truely storeTxnRead.rangeKeys()->KeyValue.Unmarshal().
it can prove by heap_inuse_space.svg in pprof.zip. So 100+ concurrent range keys request, will cost most of memory.

txReadBuffer.unsaftCopy()->bucketBuffer.Copy(), this we only can see in heap_alloc_space, it is an accumulated memory cost.

So you are right by "The key issue is that you have to avoid ranging all data and it costs too much memory."

**Comment by tangcong** [comment]
good. got it. rate-limiting is necessary for expensive read and it can avoid costing too much memory. 
I will add rate-limiting for expensive reads in future work. thanks.

**Comment by chinazj** [comment]
hi yangxuanjia

I encountered a difficulty, I cannot use `-tls_ca=ca.crt -tls_cert=server.crt -tls_key=server.key` in pprof

```
go tool pprof -tls_ca=ca.crt -tls_cert=server.crt -tls_key=server.key  https://10.55.58.31:2380/debug/pprof/profile
Fetching profile over HTTP from https://10.55.58.31:2380/debug/pprof/profile
https://10.55.58.31:2380/debug/pprof/profile: Get "https://10.55.58.31:2380/debug/pprof/profile": remote error: tls: bad certificate
failed to fetch any source profiles
```

please help me.

thanks

**Comment by yangxuanjia** [comment]
curl -k --cert client.pem --key client-key.pem 'https://172.28.200.99:2379/debug/pprof/heap' -o ppppp1.dump
go tool pprof --svg -inuse_space -output profile001_inuse_space.svg  ppppp1.dump
