### ISSUE TITLE
Issue 11154 was locked

### ISSUE THREAD

**Issue by jefferai** [etcd-io/etcd#12255]
And as a result, those of us dealing with this problem no longer have a central location to exchange workarounds/suggestions or provide some advice to the maintainers.

Brandon's remark before closing it is well and good, but ignores the fact that people have been dealing with this problem for nearly a year and it was caused not simply by not having go modules but in large part by go modules being introduced incorrectly.

There's an easy way that the maintainers could address this given no release date for 3.5: release 3.5 as 3.4 with fixed go modules; then, rename the current 3.5 to 3.6. That's the kind of suggestion that could have been put on that issue had it not been locked.

**Comment by jefferai** [comment]
@philips

**Comment by xiang90** [comment]
> There's an easy way that the maintainers could address this given no release date for 3.5: release 3.5 as 3.4 with fixed go modules;

Agree, it could be an quicker fix.

**Comment by jefferai** [comment]
Keeping it open
