### ISSUE TITLE
Etcd snapshot/backup directories keep on increasing.

### ISSUE THREAD

**Issue by akshaysharama** [etcd-io/etcd#12267]
Hi,

I'm running kubernetes, deployed using kubespray, could see etcd is creating snapshots in /var/backups directory due to which rootfs disk size is increasing and pods are going to evicted state. 

Is there any way to limit snapshots dir creation or is there any way to introduce retention policies for etcd snapshots?

**Comment by liujiang0529** [comment]
you ignore setting:
# Maximum number of snapshot files to retain (0 is unlimited).
max-snapshots: 5
