### ISSUE TITLE
Empty keys (still/again) do not work 

### ISSUE THREAD

**Issue by jeffrson** [etcd-io/etcd#12263]
I'd try to list all keys via v3 API by etcdctl. I tried on Windows with versions from scoop or built via `go get`.

According to https://github.com/etcd-io/etcd/issues/5323 and https://github.com/etcd-io/etcd/issues/9833 I would expect
`etcdctl.exe get "" --prefix`
or
`etcdctl.exe get "" --from-key`
to work. However I get this error message:

`Error: get command needs one argument as key and an optional argument as range_end`

So I wonder - should this work? How do I get all keys?

**Comment by spzala** [comment]
Both command works fine on my Linux env with the master branch. Would you debug it further and provide more info/PR if needed? Thanks!

**Comment by jeffrson** [comment]
Hmmm, okay. AFAICT after testing in more detail this is a PowerShell problem (which of course I didn't mention, because I was heading for the old issues).

I could "fix" this for PowerShell with
`etcdctl ... get --% "" --prefix`
or
``etcdctl ... get `"`" --prefix``

**Comment by spzala** [comment]
@jeffrson thanks for the quick look and update. Should we close the issue then?

**Comment by jeffrson** [comment]
Yes - done.

**Comment by spzala** [comment]
Thanks @jeffrson
