### ISSUE TITLE
Allow for configuring WatchProgressNotifyInterval in integration tests

### ISSUE THREAD

**Issue by wojtek-t** [etcd-io/etcd#12265]
I'm working on utlizing progress-notify feature in Kubernetes as part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption

I have it working already in my branch and working on extending tests. Unfortunately, the existing etcd integration server doesn't allow for configuring that now.

The ask is to allow setting that at the level of integration.ClusterConfig:
https://github.com/etcd-io/etcd/blob/c20cc05fc54849b193c11702afda17782a1d9f7f/integration/cluster.go#L122

and pipe it down to etcdserver.ServerConfig so that we can utlize it in tests (ideally also cherrypick it back to 3.4 branch).

@jingyih @jpbetz

**Comment by jingyih** [comment]
I can help with this. @wojtek-t

**Comment by wojtek-t** [comment]
@jingyih - can you please cherrypick to 3.4 (I'm not able to reopen to track the cherrypick)
