### ISSUE TITLE
Watch only Create and update events and suppress delete events.

### ISSUE THREAD

**Issue by sanamsarath** [etcd-io/etcd#12277]
Is it possible to suppress the Watch updates for the Delete events alone?? 

We have thousands of keys stored in etcd and if they are deleted via deleteRange request all the the watching clients will be flooded with delete watch updates, so is there any knob to disable only deletes. If not is there any suggested way to handle this kind of use case??

Thanks,
Sarath.

**Comment by jingyih** [comment]
Yes. Please refer to
https://github.com/etcd-io/etcd/blob/cc564110bddeadc1d806ef0698745be702cb17ea/clientv3/op.go#L486-L487

**Comment by jingyih** [comment]
Please feel free to reopen if you have follow up questions.
