### ISSUE TITLE
clientv3/namespace: empty key not allowed for range requests

### ISSUE THREAD

**Issue by thsnr** [etcd-io/etcd#12282]
# Description

clientv3 range requests (`WithFromKey()`) with an empty key are allowed since #10445 was merged. These requests return all keys (unless an explicit end key is also given).

However, when using a KV wrapped with `clientv3/namespace` these requests no longer work and require that `"\x00"` is used instead of the empty string.

It would be nice if range requests with empty keys worked in both cases.

# Steps to reproduce

1. Wrap a client using `clientv3/namespace.NewKV`.
2. Perform a range request with an empty key.

# Expected results

All keys in the namespace are returned.

# Actual results

`etcdserver: key is not provided`

# Details

clientv3 version: 3.4.13

This might also apply to other wrappers in `clientv3/namespace`, e.g., `NewWatcher`, but I did not test those.

# Code

```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"

	"go.etcd.io/etcd/clientv3"
	"go.etcd.io/etcd/clientv3/namespace"
	"go.etcd.io/etcd/embed"
	"go.etcd.io/etcd/etcdserver/api/v3client"
)

func main() {
	cfg := embed.NewConfig()

	// Use temporary data directory.
	dir, err := ioutil.TempDir("", "etcd-")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)
	cfg.Dir = dir

	// Suppress server log to keep output clean.
	cfg.Logger = "zap"
	cfg.LogLevel = "error"

	etcd, err := embed.StartEtcd(cfg)
	if err != nil {
		panic(err)
	}
	defer etcd.Close()
	<-etcd.Server.ReadyNotify()

	client := v3client.New(etcd.Server)
	defer client.Close()

	_, err = client.Put(context.Background(), "my-namespace/foobar", "data")
	if err != nil {
		panic(err)
	}

	// Range over all keys.
	resp, err := client.Get(context.Background(), "", clientv3.WithFromKey())
	if err != nil {
		panic(err)
	}
	for _, kv := range resp.Kvs {
		fmt.Println(string(kv.Key), "=", string(kv.Value))
	}

	// Range over all keys in a namepsace.
	client.KV = namespace.NewKV(client.KV, "my-namespace/")
	resp, err = client.Get(context.Background(), "", clientv3.WithFromKey())
	if err != nil {
		panic(err)
	}
	for _, kv := range resp.Kvs {
		fmt.Println(string(kv.Key), "=", string(kv.Value))
	}
}
```

Expected output:
```
my-namespace/foobar = data
foobar = data
```

Actual output:
```
my-namespace/foobar = data
panic: etcdserver: key is not provided
```

**Comment by cfc4n** [comment]
@thsnr Please try PR #12307 ,thanks.

**Comment by thsnr** [comment]
@cfc4n I tested PR #12307 and it fixed my issue. Thank you.
