### ISSUE TITLE
unable to go get with latest version v3.3.15

### ISSUE THREAD

**Issue by babulalsph** [etcd-io/etcd#12284]
i am not able to go get with latest version getting below error.
`go get github.com/coreos/etcd@v3.3.25
go: github.com/coreos/etcd v3.3.25 => v3.3.25+incompatible
github.com/coreos/etcd/mvcc/backend
../../../../pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/mvcc/backend/backend.go:324:9: options.OpenFile undefined (type bbolt.Options has no field or method OpenFile)
`
looks like it's internally used package github.com/coreos/bbolt v1.3.2

**Comment by hakeemfsz** [comment]
You could add bbolt into your go.mod
