### ISSUE TITLE
Q: observabiltiy of changes

### ISSUE THREAD

**Issue by ivanjaros** [etcd-io/etcd#12294]
I have not yet used etcd but I might in an upcoming project with the goal being to sync configuration for 50-100 servers. The thing is that I might need to perform some actions on each machine once some change is made. Does etcd support some kind of observability that I can hook into?

**Comment by jingyih** [comment]
Please refer to this API: https://github.com/etcd-io/etcd/blob/76e769ce95ca0d4d0e3486712d96956260db04b8/clientv3/watch.go#L75

As an example, the command line tool `etcdctl` uses this API. Free feel to play with it so see if this is what you need.
https://github.com/etcd-io/etcd/tree/master/etcdctl#watch-options-key-or-prefix-range_end----exec-command-arg1-arg2-

**Comment by ivanjaros** [comment]
great, thanks!
