### ISSUE TITLE
Q: cluster size

### ISSUE THREAD

**Issue by ivanjaros** [etcd-io/etcd#12302]
In docs it cays:
`What is maximum cluster size?
Theoretically, there is no hard limit. However, an etcd cluster probably should have no more than seven nodes. `

I need to sync configuration for 50-100 servers across the globe. Does it mean etcd is not a good choice for this use case?

---
In my case there is only one origin that will write and the rest will only read.

**Comment by jingyih** [comment]
The max cluster size in the doc refers to the size of the etcd cluster. You could have a 3-node etcd cluster which stores configuration, and 100 servers watching the configuration changes. A single etcd server could serve many watchers efficiently.

**Comment by ivanjaros** [comment]
so watcher is like read replica and "cluster" is like write/origin?

**Comment by jingyih** [comment]
No. In the example I described, there will be 3 etcd servers running, which form an etcd cluster. Each of your 100 servers will be using etcd client (either embed clientv3 library, or use etcdctl tool) to interact with the etcd cluster. The etcd cilent on each of your server can perform write, update, watch, etc.

**Comment by ivanjaros** [comment]
ok, so client vs server. but i need to sync the config to all servers, doing it manually over client makes no sense. essentially there will be no clients whatsoever. the server is the client by itself.
