### ISSUE TITLE
what the difference of .snap and db

### ISSUE THREAD

**Issue by liujiang0529** [etcd-io/etcd#12321]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
in my etcd-0.etcd/member/ dir,have the file *.snap and db file，what the difference of them?

**Comment by agargi** [comment]
db file is the actual database file used by etcd's MVCC store. *.snap files seem to be manual snapshot files taken by etcd. It is not necessary to name the snapshot file with an extension .snap though.

Refer: https://etcd.io/docs/v3.3.12/op-guide/recovery

**Comment by ptabor** [comment]
I wrote a detailed doc about the files content: 

https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#

**Comment by ook** [comment]
> I wrote a detailed doc about the files content:

Thank you, I was desperately searching for such doc 💪🏻
