### ISSUE TITLE
[Logs] Consider accepting a zap.Logger rather than zap.Config in embed & client

### ISSUE THREAD

**Issue by Quentin-M** [etcd-io/etcd#12326]
Embed currently accepts `ZapLoggerBuilder`, and clientv3 accepts a `LogConfig`, which in both cases basically takes a zap.Config. However, in order for clients to be able to filter out noisy messages (e.g. clientv3/retry_interceptor.go, or LB Health Checks spamming with bogus TLS connections), a wrapped zapcore.Core must be used, which requires calling `(cfg Config) Build(opts ...Option) (*Logger, error)`, which constructs a full logger out of a config struct. Ops could then very simply pass assign the logger a filtering core. A zapcore.Core override could also be used by Ops to do things such as exporting extra metrics based on logs, etc.  

It really should not change much on the etcd code base side of things - especially as 3.5 is not out yet, but will allow the amount of log noise configuration that once was available with capnslog. For instance:

```
capnslog.MustRepoLogger("go.etcd.io/etcd").SetLogLevel(map[string]capnslog.LogLevel{"etcdserver/api/v3rpc": capnslog.CRITICAL})
```
 
x-ref https://github.com/etcd-io/etcd/pull/11147

*edit* May 2021: [client.WithLogger](https://github.com/etcd-io/etcd/blob/c46e96d519a38947188243c859e71ddd733e5065/client/v3/client.go#L104) lets us override a `zap.Logger` onto clientv3, that's amazing! The very same method could be implemented on Embed.

**Comment by Quentin-M** [comment]
Bot, come on.

**Comment by ptabor** [comment]
Agree. I don't see reasons why we just not support passing logger to embedded &  clientv3. 

clientv3 requires 'wrapping' with: 
   c := c.WithLogger(logger) that is error prone (as some objects take the logger before wrapping). 

I think I already did a lot of logging simplifications such that RAFT logs and GRPC loggers are 
derived from the zap.Logger and not from the core configs.

**Comment by ptabor** [comment]
@serathius

**Comment by gyuho** [comment]
> I don't see reasons why we just not support passing logger to embedded & clientv3.

As long as we support both, sounds good.

If logger is not empty, we can overwrite the existing zap log config?

**Comment by serathius** [comment]
Hmm, looked through embed config code
https://github.com/etcd-io/etcd/blob/450fd9a0b158a7eb5c5a3718850d6e6454eeef02/server/embed/config.go#L347-L364

`logger` field is protected by mutex `loggerMu`, so I don't think we should expose it.
On the other hand, ZapLoggerBuilder already allows overriding logger using https://github.com/etcd-io/etcd/blob/450fd9a0b158a7eb5c5a3718850d6e6454eeef02/server/embed/config_logging.go#L201-L211

```
c := embed.NewConfig()
c.ZapLoggerBuilder = embed.NewZapCoreLoggerBuilder(logger)
```

**Comment by gyuho** [comment]
> I wonder whether there are resons to build RaftLogger from LoggerConfig or LoggerCore

No specific reason. Please feel free to make change. The only reason why we required log config is that we wanted to have consistent "default" logging format.

**Comment by lilic** [comment]
@serathius is there anything else left for this issue, as I noticed it has a 3.5 nice to have label and with the release approaching. Thank you!

**Comment by Quentin-M** [comment]
@lilic Yes, while clientv3 and server allows passing a zap.Logger directly, embed still does not, it still only supports being passed a ZapLoggerBuilder which is pretty pointless when a logger could just be given directly.
