### ISSUE TITLE
bug: gRPC gateway not support `cancel-request`

### ISSUE THREAD

**Issue by Yiyiyimu** [etcd-io/etcd#12333]
Hi community,

I'm developing [etcd client for lua/openresty](https://github.com/api7/lua-resty-etcd), and since it does not support grpc, we're using grpc gateway to use RESTful API. I know it would be hard to reproduce the problem, since it's in another language, but I try to make myself clear.

1. For example, if I would like to create watch request, I would do
```lua
res, err = http_cli:request({
        method  = "POST",
        path    = /v3/watch,
        body    = {"create_request":{"watch_id":100,"key":"L3Rlc3Q="}}
    })
```
2. And here is the problem, when I set body to `create_request` or `progress_request`, there would be normal responce.
But when I set body to `cancel_request`, the request would always return `timeout`, the same when I set body to `foo_request`. So I guess `cancel_request` might not be supported in gRPC gateway. 
Also I tried to find other etcd client in non-grpc-supported language, but it seems none of them support this feature that cancel the watch. I would be also grateful if there are some reference to implement this feature.

**Comment by Yiyiyimu** [comment]
I tried to directly close the http connection that `watch` inside, it does close `watch` where no more change would be get, but the connection keeps there so when we do `netstat -an | grep 2379` we could find 1000+ of connection, while it should be ~100

**Comment by ptabor** [comment]
I think I've seen it in integration tests as well. 

I suspect it might be related to this comment: 
https://github.com/etcd-io/etcd/blob/add86bbd1a7a2fe7c4e071457d510286ec97512a/clientv3/watch.go#L72

Proxy cannot close underlying watch request to etcd-server  without closing the whole underlying connection,  so it also does not support it on its surface. 
In PR https://github.com/etcd-io/etcd/pull/12319 I decouple ctx of Watch server from context of underlying connection, but its only beginning of the story.

**Comment by Yiyiyimu** [comment]
It's so great you're working on it! Hope this problem could get fixed soon.

**Comment by ptabor** [comment]
I must have been not precise: I find it important, but I don't claim ownership of this problem (yet).

**Comment by Yiyiyimu** [comment]
> I must have been not precise: I find it important, but I don't claim ownership of this problem (yet).

No problem I mean it would be better if it could get fixed, but we'll also try to fix it on our side since it is confirmed the etcd native way is not supported for now so we need to find our own way to deal with it. Anyway thank you for your explanation!

**Comment by Yiyiyimu** [comment]
fixed on our side
