### ISSUE TITLE
When I only start a node in the etcd cluster and use curl to access this node(curl -L https://localhost:2379/health), why is there message blocking?

### ISSUE THREAD

**Issue by liujiang0529** [etcd-io/etcd#12345]
Set the etcd cluster with three etcd nodes. When I only start one etcd node and the other two nodes are not started, I use command(curl -L https://localhost:2379/health) a to access the started nodes. Why does the command cause message blocking?

**Comment by zjyuan** [comment]
Are you sure the started node is listening on port 2379? In my case, I get following response:
{"health":"false","reason":"RAFT NO LEADER"}
