### ISSUE TITLE
Confuse about "etcd_server_slow_apply_total"

### ISSUE THREAD

**Issue by garysdevil** [etcd-io/etcd#12340]
version:  {"etcdserver":"3.3.10","etcdcluster":"3.3.0"}
1. My understanding for "etcd_server_slow_apply_total" : request that is related do add,delete,update in disk，and handle slowly.

2. We didn't operate Kubernetes and etc; the pod didn't restart, why did the delta(etcd_server_slow_apply_total{project="XX"}[3m]) increase 40? It is shown below.

![image](https://user-images.githubusercontent.com/41293784/94365244-b8aef180-0101-11eb-8284-e9a22c5936fd.png)

**Comment by agargi** [comment]
This increase may be due to slow disk. You might want to benchmark using a tool such as: Fio. Refer links below:

https://etcd.io/docs/v3.3.12/op-guide/hardware/
https://github.com/axboe/fio

**Comment by garysdevil** [comment]
> This increase may be due to slow disk. You might want to benchmark using a tool such as: Fio. Refer links below:
> 
> https://etcd.io/docs/v3.3.12/op-guide/hardware/
> https://github.com/axboe/fio

Thanks. You give me valuable help. I assume the IOPS is lower than standard configuration, but why does it only occur sometimes and we don't operate etcd or k8s at that time?
