### ISSUE TITLE
can anyone help to migrate etcd v0.4.6 data  to v3.x

### ISSUE THREAD

**Issue by bessyosper** [etcd-io/etcd#12348]
currently i have 0.4.6 etcd node. And i was trying to upgrade the instance to 2.x then to 3.x. for etcdctlv2.3.7 could not found the 'migrate ' option. when i tried with etcdctlv3.4.13 migrate option, it shows 'no v2 keys to migrate' .

how could i upgrade the v0.4.6 etcd to latest version?

**Comment by ptabor** [comment]
I would assume you need manually keep running newer and newer etcd tar balls one by one (for each minor version) on the file

**Comment by bessyosper** [comment]
let me try with minor versions too

**Comment by bessyosper** [comment]
when i tried to upgrade to 0.4.9 from 0.4.6 its worked fine. The next version i am trying is 2.0.0. to jump to this version we need to migrate the data directory . I tried as follows
```
etcd-migrate --data-dir /var/lib/etcd/

```
but it throws error as follows. 
2020/09/30 04:30:04 Decoding snapshot from /var/lib/etcd/snapshot/3_15118.ss
2020/09/30 04:30:04 Failed migrating data-dir: Couldn't figure out the node ID from the log or flags, cannot convert

any idea?

**Comment by bessyosper** [comment]
ohh after removing the wal directory migration worked. let me try to upgrade to next versions too

**Comment by bessyosper** [comment]
until 2.3.1 i could migrate. from there i am trying to upgrade to 3.0. So first i tried to migrate the 2.3 data 
```ETCDCTL_API=3 ./etcdctl migrate --data-dir="/var/lib/etcd/"` 
using default transformer
finished transforming keys```
then i tried to start the etcd. but get the error as follows:
``` etcdmain: database file (/var/lib/etcd/member/snap/db index 133) does not match with snapshot (index 25119).```
