### ISSUE TITLE
Can anyone provide information on practical limits on distance between nodes?

### ISSUE THREAD

**Issue by rbuck-som** [etcd-io/etcd#12351]
I have a quick question for anyone out there about the practical distance limits between etcd nodes. What are the furthest distances that people have run etcd nodes before the cluster becomes unstable? I am presently running a cluster than spans us-west-2, us-east-1, and eu-west-2. But, what are the implications of such a choice? Or is etcd only stable spanning 3 fairly near-to-oneanother availability zones?

I tried IRC, no answer. I tried Google Groups, inaccessible. Sorry to spam here.

**Comment by paulcaskey** [comment]
https://etcd.io/docs/v3.4.0/tuning/
This describes what you need to tune a global cluster based on latency, with reference and examples in the text for a global cluster under the first section, **Time Parameters**.
