### ISSUE TITLE
Question: remove hostname using api

### ISSUE THREAD

**Issue by ahrechushkin** [etcd-io/etcd#12360]
Hello
Hostname was added by this request
```
 curl -v -L http://<etcd-host>:2379/v3beta/kv/put  -X POST -d '{"key": "", "value": ""}'
```
How i can remove hostname using api?

**Comment by spzala** [comment]
Are you trying to remove a key? You can use `deleterange` e.g curl -v -L http://<etcd-host>:2379/v3beta/kv/deleterange -X POST -d '{"key": "test"}'
couple of reference links:
https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-kv-etcdserveretcdserverpbrpcproto
https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md

**Comment by ahrechushkin** [comment]
@spzala yeap, thanks!
