### ISSUE TITLE
etcdserver took too long to execute

### ISSUE THREAD

**Issue by liakouras** [etcd-io/etcd#12373]
Hello,

I have the following logs that from a node of 3-node cluster (v3.2.24):

`2020-10-08 06:07:47.596706 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:476" took too long (2.462722808s) to execute`
`2020-10-08 06:07:47.597731 W | etcdserver: read-only range request "key:\"/registry/controllers\" range_end:\"/registry/controllert\" count_only:true " with result "range_response_count:0 size:7" took too long (1.684441895s) to execute`
`2020-10-08 06:07:47.597983 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-scheduler\" " with result "range_response_count:1 size:458" took too long (632.527956ms) to execute`
`2020-10-08 06:07:47.598176 W | etcdserver: read-only range request "key:\"/registry/validatingwebhookconfigurations\" range_end:\"/registry/validatingwebhookconfigurationt\" count_only:true " with result "range_response_count:0 size:7" took too long (1.05573002s) to execute`
`2020-10-08 06:07:47.599069 W | etcdserver: read-only range request "key:\"/registry/namespaces/default\" " with result "range_response_count:1 size:172" took too long (567.839045ms) to execute`
`2020-10-08 06:07:47.599440 W | etcdserver: read-only range request "key:\"/registry/secrets/kube-system/cronjob-controller-token-xw78r\" " with result "range_response_count:1 size:2360" took too long (573.503566ms) to execute`
`2020-10-08 06:07:50.554302 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:476" took too long (948.450298ms) to execute`
`2020-10-08 06:07:50.555443 W | etcdserver: read-only range request "key:\"/registry/volumeattachments\" range_end:\"/registry/volumeattachmentt\" count_only:true " with result "range_response_count:0 size:7" took too long (571.916356ms) to execute`
`2020-10-08 06:07:50.555465 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-scheduler\" " with result "range_response_count:1 size:458" took too long (256.837789ms) to execute`
`2020-10-08 06:07:57.133094 W | wal: sync duration of 2.565317283s, expected less than 1s`

Health at all nodes looks ok:
`https://10.10.10.1:2379 is healthy: successfully committed proposal: took = 1.941836ms`
`https://10.10.10.2:2379 is healthy: successfully committed proposal: took = 1.36041ms`
`https://10.10.10.3:2379 is healthy: successfully committed proposal: took = 1.587391ms`

is this a performance (disk I/O) issue? how can I confirm that operation and performance of each node? 

thank you.

**Comment by agargi** [comment]
It may be a disk issue and etcd recommends to run benchmark test. Refer [etcd fio](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd). However, following issue also points out to the fact that it may not be a disk issue at all. So it's better to run benchmark test.

https://github.com/etcd-io/etcd/issues/10860
