### ISSUE TITLE
export EtcdServer.leaderChangedNotify function for application which using embed etcd to detect leader changes

### ISSUE THREAD

**Issue by Yanhao** [etcd-io/etcd#12378]
Now the only way to know etcd leader changes is to poll the EtcdServer.Lead for embed etcd and that isn't handy. So I wonder   if there is possible to export the  EtcdServer.leaderChangedNotify so that the application will be notified when etcd leader has changed. This way the application can easily move the application level leadership to follow etcd's, reduce the extra network overhead when the application level leader and the embed etcd leader aren't same.

**Comment by Yanhao** [comment]
any thoughts please

**Comment by NHAS** [comment]
Sorry to ping such an old issue, but I have noticed that `LeaderChangeNotify()` doesnt get triggered when there is no leader. I.e the "leader has changed to nothing" 

I was wondering if Im overlooking something here, and whether I should open a feature request to be able to get nice notifications when the embedded server has become disconnected/leaderless. 

Thanks!
