### ISSUE TITLE
adding raft to a project needs clarity

### ISSUE THREAD

**Issue by mathiasxx** [etcd-io/etcd#12375]
Apologies in advance is this is just my misunderstanding of how to use go modules properly.  I attempted to get raft running without etcd, so I imported:

```
import (
"go.etcd.io/etcd/raft"
"go.etcd.io/etcd/raft/raftpb"
)
```

Which ends up adding this in my go.mod:
`go.etcd.io/etcd v3.3.25+incompatible`

And when I compile (go 1.15.2), I get errors like this:
```
cannot use cc (type "go.etcd.io/etcd/raft/raftpb".ConfChange) as type "github.com/coreos/etcd/raft/raftpb".ConfChange in argument to rn.Node.ProposeConfChange
```

I also tried to import the "v3" versions (eg, `go.etcd.io/etcd/v3/raft`...) and that leads to terrifying import errors.

Switching to this:
```
import (
 "github.com/coreos/etcd/raft"
 "github.com/coreos/etcd/raft/raftpb"
)
```

Yields this in my go.mod:
`github.com/coreos/etcd v3.3.10+incompatible`

And does allow my code to compile.  However now I'm using what looks to me like a fairly old version.

So, i'm wishing for a little extra documentation on the `etcd/raft` README describing the correct import statements to use, especially if you want to use the latest release (at time of this writing that is 3.4.13).

**Comment by mathiasxx** [comment]
I was able to get all the way up to 3.3.25:
```
go get github.com/coreos/etcd@v3.3.25

# Which puts this into go.mod:
#	github.com/coreos/etcd v3.3.25+incompatible
```

**Comment by ptabor** [comment]
FYI: I'm working on making: 
  `go.etcd.io/etcd/raft/v3@v3.5.x`
a module on its own.
