### ISSUE TITLE
404 Errors on curl requests but etcdctl works. Single Instance Vagrant VM

### ISSUE THREAD

**Issue by phoenixNull** [etcd-io/etcd#12377]
Hi,

I'm trying to experiment with etcd for a use case we might need it and I'm having quite a few troubles. I have installed etcd on a Ubuntu 20.04.1 VM and launched etcd as a single node. What I'm experiencing is quite strange.

.etcdctl works perfectly out of the box. But all curl requests to most endpoints return 404 except for /version /health which return the version (3.4.13) and the health return true. Meanwhile I have launched etcd with --debug to get more info but I see no output on the failed requests. 

What is going on? Can you guys help me out?

**Comment by spzala** [comment]
Can you please provide more details on the calls and the errors you are getting? The curl requests examples provided here should work fine - https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md

**Comment by tsharju** [comment]
I had a similar issue. Adding `enable-grpc-gateway` to `true` in config fixed it. Apparently that is `false` by default only when providing config file. This PR https://github.com/etcd-io/etcd/pull/12297 has more info.
