### ISSUE TITLE
when the TTL of lease is reduced to 0s，it occur counter rollover（0s roll over 9223372036s）

### ISSUE THREAD

**Issue by ZilRan** [etcd-io/etcd#12381]
### **System info:**
etcd Version: 3.4.6
Git SHA:
Go Version: go1.14.6
Go OS/Arch: linux/amd64

### **Problem:**
I deploy 5 ETCD nodes on 5 VM，then apply for a lease with a TTL value of 4 seconds。ETCD nodes communicate through the eth0 port of theVM
`lease 334c750b362a5026 granted with TTL(4s), remaining(3s)`

I renewed the lease on VM A, then downed the eth0 port for 3s, and then up again.
Euler:/opt/VNFP/0_tmpfs/vrpv8/var/log # date;ifconfig eth0 down;sleep 3;ifconfig eth0 up;date;
Fri Oct  9 10:09:42 NOS 2020
Fri Oct  9 10:09:45 NOS 2020

I observe the changes of this lease in the cluster on VM B, and found that when the eth0 port of VM A was up, the lease in the cluster rolled over to the maximum（9223372036s） at 10:09:46
This problem caused the lease to delay aging

Fri Oct  9 10:09:39 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(3s)
Fri Oct  9 10:09:40 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(3s)
Fri Oct  9 10:09:41 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(3s)
Fri Oct  9 10:09:42 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(2s)
Fri Oct  9 10:09:43 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(1s)
Fri Oct  9 10:09:44 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(0s)
Fri Oct  9 10:09:45 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(9223372036s)
Fri Oct  9 10:09:46 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(4s)
Fri Oct  9 10:09:48 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(3s)
Fri Oct  9 10:09:49 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(2s)
Fri Oct  9 10:09:50 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(1s)
Fri Oct  9 10:09:51 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(4s), remaining(0s)
Fri Oct  9 10:09:52 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(0s), remaining(-1s)
Fri Oct  9 10:09:53 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(0s), remaining(-1s)
Fri Oct  9 10:09:54 NOS 2020
lease 52b9750ca50c4e54 granted with TTL(0s), remaining(-1s)
Fri Oct  9 10:09:55 NOS 2020

**PS:etcd leader is not on VM A and B**

**Comment by ZilRan** [comment]
> Problem

Enabling auth on etcd v3 when it is used by any Kubernetes cluster will force the cluster into read only mode after less than a few days.

The database slowly (or rapidly on a high load cluster) uses more and more memory for its database due to extra revisions until it maxes out and goes into read-only mode.

This is because the Kubernetes API server no longer has access to perform compaction every five minutes (see here for the source). Enabling etcd auth will restrict all administration functions to users granted the "root" role only.

**Comment by cfc4n** [comment]
Can you give a demo to reproduce it?
