### ISSUE TITLE
Need Latest Revision from WALs file

### ISSUE THREAD

**Issue by ishan16696** [etcd-io/etcd#12389]
**Description**:
It is quite possible that etcd can terminates abnormally and fails to flush the changes from the WALs to the bolt DB.
So, WALs file can have uncommitted data which are ahead of data present in DB file and before etcd can commit this data to DB , it terminates abnormally .
In that case we can lose the data which are present in WALs file. That's why I need Latest Revision from WALs file, so I can compare it with latest Revision of DB file.

**Comment by agargi** [comment]
@ishan16696 Will etcd not run through WAL records (which are not committed to Bolt DB) and try to commit the same? Also IIUC, WAL records do not interpret the actual data and just sends the records in a transparent manner. Doing a comparison may not help much here.

**Comment by ishan16696** [comment]
> Will etcd not run through WAL records (which are not committed to Bolt DB) and try to commit the same?

yes, if we restarted the etcd then it will definitely try to commit the uncommitted data. 


>  Doing a comparison may not help much here.

Actually it will help, so we can know whether to restart the etcd or not.

**Comment by jingyih** [comment]
db file should persist the consistent index [1] so it knows where to replay the wal log next time the server restarts. I do not remember all the details. But you can look for it in the meta bucket [2].

[1] https://github.com/etcd-io/etcd/blob/6e800b9b0161ef874784fc6c679325acd67e2452/server/etcdserver/cindex/cindex.go#L26
[2] https://github.com/etcd-io/etcd/blob/6e800b9b0161ef874784fc6c679325acd67e2452/server/etcdserver/cindex/cindex.go#L28

**Comment by ptabor** [comment]
FTR: https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww# documents this field (consistent_index) as well 

(or how to get last comitted index from WAL log file format.)
