### ISSUE TITLE
 "etcdserver: open wal error: fileutil: file already locked" encountered after a short NFS short outage (V3.3.3)

### ISSUE THREAD

**Issue by hongweijia** [etcd-io/etcd#12419]
We encountered the "etcdserver: open wal error: fileutil: file already locked" error after a short NFS short outage with ETCD version V3.3.3. This maybe caused by the file corruption due to NFS short outage . Any idea how to fix this issue? Appreciate your help!

**Comment by agargi** [comment]
@hongweijia Not sure where you are running etcd but looks like you have to clear the NFS lock since the client (i.e. etcd) died.
