### ISSUE TITLE
Modify whether TSL is enabled, no need to restart ETCD

### ISSUE THREAD

**Issue by wxxxx123456** [etcd-io/etcd#12413]
My ETCD has used the certificate。

> like this
> etcd -name etcd -data-dir /var/lib/etcd  -advertise-client-urls=https://172.17.0.2:4001 -listen-client-urls=https://172.17.0.2:4001  -cert-file=/root/cfssl/server.pem -key-file=/root/cfssl/server-key.pem -client-cert-auth -trusted-ca-file=/root/cfssl/ca.pem &
>  
But sometimes I need  the certificate,sometimes i do not.And I don’t want to restart ETCD because of this.
So, Are there some switches to enable or disable Etcd to use certificates.

**Comment by ptabor** [comment]
There are no such switches. There is only PR in progress to allow healthchecking without certificates. 

What are your use-cases ?
