### ISSUE TITLE
etcd: Force a new cluster

### ISSUE THREAD

**Issue by philips** [etcd-io/etcd#1242]
Currently we don't provide a tool to let a user recover if they lose quorum of their cluster. 
- [x] build a tool that lets the user dump the current log and rewrites the node ID and cluster ID to protect the current cluster
- [x] add a flag to force log entries to make a single machine cluster by removing all old nodes and making the member the one and only member - #1647 

I imagine the workflow would be something like:

```
etcdctl backup /var/lib/etcd ./backup
etcd -force-new-cluster -data-dir ./backup
```

**Comment by geofffranks** [comment]
Was this completed, closed as wont fix? Other issues reference this ticket indicating that this will be the one to solve them, and so they were closed, but i can't tell what happened with this ticket.
