### ISSUE TITLE
How does etcd handle expired certificates when using auto-tls or peer-auto-tls

### ISSUE THREAD

**Issue by Num2** [etcd-io/etcd#12427]
Hello,
when using the auto-tls or peer-auto-tls option, I see etcd generates certificates that are valid for 1 year.
I can't find any information on what happens, when these generated certificates expire.
Will etcd automatically detect the expiry of the certificates and create new ones?

**Comment by tangcong** [comment]
etcd will not automatically detect the expiry of the certificates and create new ones. I will submit a pr to fix it, let you can specify the certificates validity period, and add notes for certificates that are only valid for 1 year. thanks.
