### ISSUE TITLE
Change data dir

### ISSUE THREAD

**Issue by cihantunali** [etcd-io/etcd#12420]
Hi there.

I have 3 node cluster. I need to change their data directory from /var/lib/etcd to /data/etcd. Is there any procedure to do this? 

I tried 
- stop etcd and copy /var/lin/etcd contents to /data/etcd
- change ownership of files
- run etcd
but no luck, it crashed. After i roll-back, it started to work. Any help will be helpfull. Thanks.

**Comment by agargi** [comment]
@cihantunali Please share the command, configuration & error to help comment on the issue.

**Comment by jingyih** [comment]
Did you update the value to flag `--data-dir` when you restart etcd?
