### ISSUE TITLE
Backport updated Dockerfile base image to release branches

### ISSUE THREAD

**Issue by tghartland** [etcd-io/etcd#12432]
The Dockerfile base image was updated 6 months ago in #11885 but this is still not available in any release build.  
Is this too big of a change to backport for a point release or was it just never considered?

To include updates for CVEs that have been fixed since that PR, the base image could now be updated to `debian-base:v2.1.3` before backporting.

**Comment by ptabor** [comment]
FYI: There is another update coming:  https://github.com/etcd-io/etcd/pull/12648.

I think that if anyone proposes PRs with back-port, it has high chances to get merged, and it was just not considered.
