### ISSUE TITLE
China go Get installs Benchmark

### ISSUE THREAD

**Issue by lianzhang132** [etcd-io/etcd#12436]
Hi, I can't use Go Get to install Benchmark in China due to network problems.Do you know how to solve installing Benchmark?

**Comment by cfc4n** [comment]
> Hi, I can't use Go Get to install Benchmark in China due to network problems.Do you know how to solve installing Benchmark?

Please give your code and errors.

**Comment by lianzhang132** [comment]
> > Hi, I can't use Go Get to install Benchmark in China due to network problems.Do you know how to solve installing Benchmark?
> 
> Please give your code and errors.
![image](https://user-images.githubusercontent.com/39590516/97654034-10dc6900-1a9d-11eb-9dd9-a6f80ebfe557.png)
Hello, this is my message.Looking forward to your reply

**Comment by cfc4n** [comment]
try use GOPROXY to fix it.
```
$ export GO111MODULE=on
$ export GOPROXY=https://goproxy.cn
```

**Comment by lianzhang132** [comment]
> > Hi, I can't use Go Get to install Benchmark in China due to network problems.Do you know how to solve installing Benchmark?
> 
> Please give your code and errors.



> try use GOPROXY to fix it.
> 
> ```
> $ export GO111MODULE=on
> $ export GOPROXY=https://goproxy.cn
> ```
![image](https://user-images.githubusercontent.com/39590516/97655508-2f902f00-1aa0-11eb-861f-0554e2dd855a.png)


This still doesn't work, my environment can ping Baidu, but it doesn't ping Google

**Comment by cfc4n** [comment]
It should be the problem of GFW, you should use an overseas VPN. 😔

**Comment by lianzhang132** [comment]
> It should be the problem of GFW, you should use an overseas VPN. 😔

I wonder if there are so many users in China, and if you encounter this problem again, do you always use VPN to solve it?Do etCD bosses need to solve this problem?

**Comment by jiusanzhou** [comment]
Make sure the version of Go is greater than `1.11`
