### ISSUE TITLE
What perms are required for a non-root user

### ISSUE THREAD

**Issue by perezjasonr** [etcd-io/etcd#12433]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

Sorry but the reporting-bugs.md page gives me a 404 so I will do my best to make this easy to understand. We are trying to run etcd as non-root, I am telling the container to run as user etcd, and the certs are owned by etcd:etcd

I keep getting the error:

`2020-10-28 18:43:11.053592 C | etcdmain: open /etc/kubernetes/pki/etcd/peer.crt: permission denied`

I've tried 600, 640, 660, i kept climbing up.

No matter what it will not stop saying its denied without rwx perms or 7xx bit. Since its a cert I'm confused, but just wanted to make sure, does it really require +x bit for the certs? I would assume it just needs read, or maybe rw. I feel like most people put 600 for the certs...but then again usually their etcd is running as root. Just wanted to confirm whether or not this was the case...perhaps could be something else. For the record here is the relevant section from my dockerfile:

```docker
RUN mkdir -p /var/lib/etcd && \
    mkdir -p /etc/etcd && \
    groupadd --system etcd && \
    useradd -s /sbin/nologin --system -g etcd etcd && \
    chown -R etcd:etcd /var/lib/etcd

COPY --from=base --chown=root:root /usr/local/bin/etcd /usr/local/bin/etcd
COPY --from=base --chown=root:root /usr/local/bin/etcdctl /usr/local/bin/etcdctl

USER etcd
```
so if running as non-root what are the minimum permissions required on the cert files? I just wanted to confirm this.

**Comment by djosh34** [comment]
Directories in linux require execute permissions to list files: https://superuser.com/questions/168578/why-must-a-folder-be-executable
