### ISSUE TITLE
go mod etcd client/v3 module failed

### ISSUE THREAD

**Issue by xkeyideal** [etcd-io/etcd#12431]
get "go.etcd.io/etcd/pkg/v3": found meta tag get.metaImport{Prefix:"go.etcd.io/etcd", VCS:"git", RepoRoot:"https://github.com/etcd-io/etcd"} at //go.etcd.io/etcd/pkg/v3?go-get=1
get "go.etcd.io/etcd/pkg/v3": verifying non-authoritative meta tag
get "go.etcd.io/etcd/api/v3": found meta tag get.metaImport{Prefix:"go.etcd.io/etcd", VCS:"git", RepoRoot:"https://github.com/etcd-io/etcd"} at //go.etcd.io/etcd/api/v3?go-get=1
get "go.etcd.io/etcd/api/v3": verifying non-authoritative meta tag
go: go.etcd.io/etcd/client/v3@v3.0.0-20201026174226-7da5182f1d02 requires
        go.etcd.io/etcd/api/v3@v3.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by ptabor** [comment]
We need to tag the repository properly as 3.5.0-pre to make it work. Will try to do this this week. 

For now please depend on the 3.4 branch where client is part of the server.

If you want to depend on release 3.4.13, please use: 
  go get go.etcd.io/etcd@ae9734e.

Don't worry about: 
  > go.etcd.io/etcd ae9734e => v0.5.0-alpha.5.0.20200824191128-ae9734ed278b
You will find in the file.

**Comment by sagikazarmark** [comment]
Alternatively, you can replace those modules:

```
replace (
	go.etcd.io/etcd/api/v3 => go.etcd.io/etcd/api/v3 v3.0.0-20201103155942-6e800b9b0161
	go.etcd.io/etcd/pkg/v3 => go.etcd.io/etcd/pkg/v3 v3.0.0-20201103155942-6e800b9b0161
)
```

**Comment by tuhao1020** [comment]
still not woking
```
go: go.etcd.io/etcd imports
        github.com/coreos/etcd/etcdmain imports
        github.com/coreos/etcd/etcdserver imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.5: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```

**Comment by sagikazarmark** [comment]
I don't think you are supposed import `go.etcd.io/etcd` directly.

**Comment by tuhao1020** [comment]
```
# go get -u  go.etcd.io/etcd/client/v3
go: go.etcd.io/etcd/client/v3 upgrade => v3.0.0-20201109164711-01844fd28560
go get: go.etcd.io/etcd/client/v3@v3.0.0-20201109164711-01844fd28560 requires
        go.etcd.io/etcd/api/v3@v3.0.0-00010101000000-000000000000: reading https://goproxy.cn/go.etcd.io/etcd/api/v3/@v/v3.0.0-00010101000000-000000000000.mod: 404 Not Found
        server response: not found: go.etcd.io/etcd/api/v3@v3.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by zhenyuxie** [comment]
> We need to tag the repository properly as 3.5.0-pre to make it work. Will try to do this this week.
> 
> For now please depend on the 3.4 branch where client is part of the server.
> 
> If you want to depend on release 3.4.13, please use:
> go get go.etcd.io/etcd@ae9734e.
> 
> Don't worry about:
> 
> > go.etcd.io/etcd [ae9734e](https://github.com/etcd-io/etcd/commit/ae9734ed278b7a1a7dfc82e800471ebbf9fce56f) => v0.5.0-alpha.5.0.20200824191128-ae9734ed278b
> 
> You will find in the go.mod file.

I don't find tag  3.5.0-pre. So when you solve this problem?

**Comment by kuchaguangjie** [comment]
Still get this issue, none of above comment solve it, any solution ?

**Comment by kuchaguangjie** [comment]
Should import:
```
import (
    "go.etcd.io/etcd/clientv3"
)
```

`go.mod` contains:

> require go.etcd.io/etcd v0.5.0-alpha.5.0.20201125193152-8a03d2e9614b

then the issue is gone.

**Comment by wnagzhilei** [comment]
> 或者，您可以替换这些模块：
> 
> ```
> replace (
> 	go.etcd.io/etcd/api/v3 => go.etcd.io/etcd/api/v3 v3.0.0-20201103155942-6e800b9b0161
> 	go.etcd.io/etcd/pkg/v3 => go.etcd.io/etcd/pkg/v3 v3.0.0-20201103155942-6e800b9b0161
> )
> ```

你成功的解决了我的问题，谢谢你

**Comment by GeorgeGuo2018** [comment]
go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200819165624-17cef6e3e9d5

resolved my problem. thx
