### ISSUE TITLE
[feedback] best practice on service discovery but worst compatible opensource etcd packge.

### ISSUE THREAD

**Issue by fwhezfwhez** [etcd-io/etcd#12466]
Delete package randomly , 
rename a function or add function argument number capriciously,
commit always reset fail,
even publish plenty of tags but none of it keeps consistent.

To well use a correct version of etcd package is exactly a difficult challenge. Is it help to provide such amount of tags?

Sincerely suggests that,
- never delete a package which has put to release version.
- using a new named function on the case you want to extend an exised fixed-arg-num function.
- stop using rebase to avoid commit loss.

**Comment by ptabor** [comment]
I agree in general that etcd is not clear about public and private API surface. 
I'm starting to introduce 'internal' tree to enforce it a little more (but it means breaking changes). 
Is your problem mostly about using etcd clientV3 API or  embedded etcd ?

**Comment by fwhezfwhez** [comment]
@ptabor  clientV3 API
GOPATH and GOMODULE require complicated ajustment to well use it.

**Comment by fwhezfwhez** [comment]
@ptabor 
```bash
go: finding go.etcd.io/etcd/client/v3 latest
go: finding go.etcd.io/etcd/client/v3/naming latest
go: downloading go.etcd.io/etcd/client/v3 v3.0.0-20210219204649-3d7aac948b1c
go: extracting go.etcd.io/etcd/client/v3 v3.0.0-20210219204649-3d7aac948b1c
go: finding go.etcd.io/etcd/pkg/v3 v3.5.0-pre
go: go.etcd.io/etcd/pkg/v3@v3.5.0-pre: unknown revision pkg/v3.5.0-pre
go: finding go.etcd.io/etcd/api/v3 v3.5.0-pre
go: go.etcd.io/etcd/api/v3@v3.5.0-pre: unknown revision api/v3.5.0-pre
go: error loading module requirements
```

**Comment by fwhezfwhez** [comment]
How can I use gomodule to use etcd-client, so hard

**Comment by fwhezfwhez** [comment]
Finally work by change another GOPROXY and use this go.mod. Too hard.
```json
module shangraomajiang

go 1.12

require (
	go.etcd.io/etcd/api/v3 v3.5.0-pre
	go.etcd.io/etcd/client/v3 v3.0.0-20210204162551-dae29bb719dd
	google.golang.org/protobuf v1.25.0
)

replace (
	github.com/golang/protobuf v1.4.3 => github.com/golang/protobuf v1.3.4
	go.etcd.io/etcd/api/v3 => go.etcd.io/etcd/api/v3 v3.0.0-20210204162551-dae29bb719dd
	go.etcd.io/etcd/pkg/v3 => go.etcd.io/etcd/pkg/v3 v3.0.0-20210204162551-dae29bb719dd

	google.golang.org/api => github.com/googleapis/google-api-go-client v0.40.0
	google.golang.org/appengine => github.com/golang/appengine v1.6.7
	google.golang.org/genproto => github.com/googleapis/go-genproto v0.0.0-20180601223552-81158efcc9f2
	google.golang.org/grpc => github.com/grpc/grpc-go v1.27.0
	google.golang.org/protobuf => github.com/protocolbuffers/protobuf-go v1.25.0
)

```
