### ISSUE TITLE
Documentation/v2/errorcode.md not found?

### ISSUE THREAD

**Issue by spacewander** [etcd-io/etcd#12462]
It is mentioned that there is an error code page for v2 protocol:
https://github.com/etcd-io/etcd/blob/ae7862e8bc8007eb396099db4e0e04ac026c8df5/server/etcdserver/api/v2error/error.go#L16

However, I can't find `Documentation/v2/errorcode.md` in this repo. Is the comment stale?

**Comment by spzala** [comment]
@spacewander the v2 docs are completely moved to `etcd-io/website/tree/master/content/docs/v2` - there are couple of broken references on top of what you noticed, and they should be fixed - are you interested in creating a PR? Thanks!
