### ISSUE TITLE
Please upgrade grpc version used in etcd go.mod 

### ISSUE THREAD

**Issue by dims** [etcd-io/etcd#12470]
In kubernetes, we have been jumping through hoops trying to ensure that we can work with the old versions of grpc used in etcd. example

- In https://github.com/kubernetes/kubernetes/pull/94942, we will end up using a REALLY old version of go.telemetry.io as newer go.telemetry.io modules use newer grpc
- In https://github.com/google/cadvisor/pull/2724, we rolled back to older grpc so we could vendor cadvisor into kubernetes
- In https://github.com/kubernetes/kubernetes/issues/93320#issuecomment-685237947, you can see that other folks who need to use newer grpc AND kubernetes are stuck because we end up limiting kubernetes to the the older versions of grpc

@jpbetz @jingyih @spzala @wenjiaswe Can you please take a look?

**Comment by ptabor** [comment]
There are 2 related PRs in flight: 
  https://github.com/etcd-io/etcd/pull/12439
  https://github.com/etcd-io/etcd/pull/12398

And a duplicate issue: 
  https://github.com/etcd-io/etcd/issues/11650

BTW: 
  Do you know whether k8s is planning to migrate out of gogo-protobuf ?

**Comment by dims** [comment]
my apologies. let me find out the answer for your question and then close this @ptabor

**Comment by dims** [comment]
Exhibits for the record
- https://github.com/gogo/protobuf/issues/691 : "GoGo Protobuf looking for new ownership"
- https://groups.google.com/g/kubernetes-sig-api-machinery/c/tcwFubV9Boo/m/MAdQfLY_AgAJ

Looks like we don't have a way of dropping gogo-protobuf in k8s yet.
