### ISSUE TITLE
Consider to migrate to a different jwt library

### ISSUE THREAD

**Issue by mitake** [etcd-io/etcd#12475]
It seems that https://github.com/dgrijalva/jwt-go isn't maintained actively (according to https://github.com/dgrijalva/jwt-go/pull/426). If we cannot expect important updates, we should consider to migrate to a different jwt library.

**Comment by goku321** [comment]
How about I try working on this?

**Comment by brumhard** [comment]
This is also addressed in #12580 and should be merged cause as of right now etcd contains this vulnerability reported by snyk.

**Comment by dlorenc** [comment]
Whoops, missed this issue. Yep, my PR should be ready for review.
