### ISSUE TITLE
raftexample: sending snapshot to a new node in cluster not working

### ISSUE THREAD

**Issue by olearczuk** [etcd-io/etcd#12473]
Scenario below represents situation when we add new node to a cluster that have been operating for a while and produced a snapshot already (e.g. version update).

I am using raftexample on branch release-3.4
In order to trigger saving snapshot faster I changed 2 variables in `raftexample/raft.go` file

```go
var defaultSnapshotCount uint64 = 5
var snapshotCatchUpEntriesN uint64 = 5
```

## Commands
Start cluster
```sh
./raftexample --id 1 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379 --port 12380
./raftexample --id 2 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379 --port 22380
```

Trigger saving snapshot
```sh
# do it couple of times (3 - 4 should be enough)
curl -L 127.0.0.1:12380/foo -XPUT -d bar
```

Add new node to cluster
```sh
curl -L 127.0.0.1:12380/3 -XPOST -d http://127.0.0.1:32379
./raftexample --id 3 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 --port 32380 --join
```

## Logs
Logs of node 3
```
raft2020/11/13 19:26:32 WARN: 3 attempted to restore snapshot but it is not in the ConfState {[1 2] [] [] [] false []}; should never happen
raft2020/11/13 19:26:32 INFO: 3 [commit: 0] ignored snapshot [index: 6, term: 4]
```
After that no snapshots nor log entries are propagated to node 3.
Sending GET request on address `curl -L 127.0.0.1:32380/foo` results in `Failed to GET`, so changes have not been propagated to this node.

Am I missing something?
What changes in raftexample will make this work?

**Comment by WuK0** [comment]
I have the same question, do you know how to deal with it ?

**Comment by olearczuk** [comment]
Hi,
as far as I remember the problem was that few functions in `raft.go` were left empty.
I think 2d25f7f should have fixed the problem.

**Comment by zhenyuxie** [comment]
Same to me, did you fix it?
