### ISSUE TITLE
etcd server was unresponsible 

### ISSUE THREAD

**Issue by todaygood** [etcd-io/etcd#12482]
My etcd cluster was only one etcd node , and was booted by kubelet  within docker, I found the etcd was unresponsibe , but didn't report any error logs.  my k8s version is v1.19.2 and etcd version is 3.4.13.
the following snapshot showed the etcd was booted repeatedly .

![image-20201121204844232](https://raw.githubusercontent.com/todaygood/pichub0/main/image-20201121204844232.png)

**Comment by todaygood** [comment]
I found it is caused by kubevirt , before the issue happened , I created one kubevirt vm.  

now , I kill the vm's kvm process , the etcd has been recovered.

**Comment by spzala** [comment]
> I found it is caused by kubevirt , before the issue happened , I created one kubevirt vm.
> 
> now , I kill the vm's kvm process , the etcd has been recovered.

@todaygood cool, so can we please close this issue now? Thanks!
