### ISSUE TITLE
Can not go get go.etcd.io/etcd/client/v3@master

### ISSUE THREAD

**Issue by haunt98** [etcd-io/etcd#12484]
I try to use latest etcd v3 client but failed with message:

```txt
go: go.etcd.io/etcd/client/v3 master => v3.0.0-20201119180542-b5cefb5b3dfb
go get: go.etcd.io/etcd/client/v3@v3.0.0-20201119180542-b5cefb5b3dfb requires
	go.etcd.io/etcd/api/v3@v3.5.0-pre: reading go.etcd.io/etcd/api/api/go.mod at revision api/v3.5.0-pre: unknown revision api/v3.5.0-pre
```

**Comment by csx2hen** [comment]
The README.md says:

> For full compatibility, it is recommended to install released versions of clients using go modules.

Maybe you can use `go get go.etcd.io/etcd/clientv3@release-3.4` right now.

**Comment by haunt98** [comment]
Thank for your information.

**Comment by ptabor** [comment]
FTR. https://github.com/etcd-io/etcd/issues/12498 is blocking experimental:
```
go get go.etcd.io/etcd/client/v3@master
```

**Comment by charleszheng44** [comment]
@haunt98 have you been able to fix the issue? I still get the same error even after running  `go get go.etcd.io/etcd/clientv3@release-3.4`.

**Comment by haunt98** [comment]
@charleszheng44 im just waiting for the 3.5 release :)

**Comment by kuchaguangjie** [comment]
Still get the same issue, any idea ???
