### ISSUE TITLE
v3.4.9 Due to power failure, etcd cannot be started. Is there any solution

### ISSUE THREAD

**Issue by liwh1111** [etcd-io/etcd#12487]
Due to power failure, etCD cannot be started. Is there any solution
![image](https://user-images.githubusercontent.com/63097736/100065084-51e25600-2e6e-11eb-9ee8-50b23f980150.png)
![image](https://user-images.githubusercontent.com/63097736/100065190-72aaab80-2e6e-11eb-9651-efc6db6ffaa9.png)

**Comment by tangcong** [comment]
can you provide more detailed information, such as detailed etcd log, operating system, file system information? what are the wal and snap files in your etcd data directory?

**Comment by liwh1111** [comment]
My system is centos7.8 and etcd3.4.9. The following link has the same problem

https://github.com/etcd-io/etcd/issues/11949#issuecomment-650245742

**Comment by tangcong** [comment]
ok, i will take a look and can you share detail etcd log? @liwh1111
