### ISSUE TITLE
Panic of snapshot not find after power failure does it have any solution!

### ISSUE THREAD

**Issue by mamiapatrick** [etcd-io/etcd#12492]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Power failure of rancher node (RancherOS)

**Result:**
By inspecting the log I got an error
```
etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path 
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3.2
- Installation option (single install/HA): HA (3 nodes of etcd and 2 master)

**Cluster information**

```
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8 CPU, 8 Gb RAM
- Kubernetes version (use `kubectl version`): v1.15.5
```

- Docker version (use `docker version`):

```
Rancher 2.3.1
RKE 0.3.1
Kubernetes v1.15.5
docker: 18.06.3-ce
```

**Comment by tedyu** [comment]
Can you ls the contents of snap directory ?

Was there SIGSEGV stack trace similar to the one shown in #12237 ?

**Comment by mamiapatrick** [comment]
`[root@rancheros etcd]# tree
.
`-- member
    |-- snap
    |   |-- 000000000000007c-0000000002a271fa.snap
    |   |-- 000000000000007c-0000000002a3f89b.snap
    |   |-- 000000000000007e-0000000002a57f3c.snap
    |   |-- 000000000000007f-0000000002a705dd.snap
    |   |-- 0000000000000080-0000000002a88c7e.snap
    |   `-- db
    `-- wal
        |-- 0000000000000566-0000000002a77322.wal
        |-- 0000000000000567-0000000002a8010a.wal
        |-- 0000000000000568-0000000002a888f5.wal
        |-- 0000000000000569-0000000002a90594.wal
        |-- 000000000000056a-0000000002a985c6.wal
        `-- 1.tmp

3 directories, 12 files`

**Comment by ptabor** [comment]
```
{"log":"2020-11-14 10:31:52.571703 I | etcdserver: recovered store from snapshot at index 44600446\n","stream":"stderr","time":"2020-11-14T10:31:52.572105412Z"} {"log":"2020-11-14 10:31:52.595485 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist\n","stream":"stderr","time":"2020-11-14T10:31:52.595732324Z"} {"log":
```

44600446 = 0x2a88c7e

So the file seems to exists :
   0000000000000080-0000000002a88c7e.snap

Does it have a regular size, proper permissions ? 
Can you inspect this file using this tool: 

https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#heading=h.wmsrr7l6rw5k  ?

BTW: There is no good reason etcd depends on the file existence as they contain V2 store content that is redundant to snap/db file content. I think we should develop a flag that allows to ignore the files and depend on snap from WAL files alone.

**Comment by veerendra2** [comment]
I had similar issue. etcd pod was failed start due to unexpected Azure VM reboot. 
```
2021-06-28 16:12:32.246822 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/etcd/ca.crt
2021-06-28 16:12:32.246900 I | etcdmain: etcd Version: 3.2.22
2021-06-28 16:12:32.246910 I | etcdmain: Git SHA: 1674e682f
2021-06-28 16:12:32.246915 I | etcdmain: Go Version: go1.8.7
2021-06-28 16:12:32.246922 I | etcdmain: Go OS/Arch: linux/amd64
2021-06-28 16:12:32.246928 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2021-06-28 16:12:32.246984 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2021-06-28 16:12:32.247035 I | embed: peerTLS: cert = /etc/etcd/peer.crt, key = /etc/etcd/peer.key, ca = , trusted-ca = /etc/etcd/ca.crt, client-cert-auth = true
2021-06-28 16:12:32.248344 I | embed: listening for peers on https://10.0.1.21:2380 
2021-06-28 16:12:32.248912 I | embed: listening for client requests on 10.0.1.21:2379
2021-06-28 16:12:32.281703 I | etcdserver: recovered store from snapshot at index 444604492
2021-06-28 16:12:32.303933 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb7bbdc]
goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc4201cc398, 0xc4201cc170)
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:284 +0x3c
panic(0xdb1280, 0xc42000e230)
 /usr/local/google/home/jpbetz/.gvm/gos/go1.8.7/src/runtime/panic.go:489 +0x2cf
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201c2020, 0xf98878, 0x2a, 0xc4201cc1e0, 0x1, 0x1)
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x15c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc420056ea0, 0x0, 0x14b0580, 0xc42000e0b0)
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:379 +0x2e75
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42004c800, 0xc420074a80, 0x0, 0x0)
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:157 +0x76a
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42004c800, 0x6, 0xf73bf3, 0x6, 0x1)
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x58
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:103 +0x1579
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:39 +0x61
main.main()
 /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
```
In my case, there are 2 members up and running. Below is thigs I did
```
## 0. Start failed etcd pod(etcd-01) in debug mode in openshift dashboard

## 2. Take backup snapshot on etcd-0(etcd-01 is already running fine)
$ oc exec -it master-etcd-ocp-master-prd-0 -c etcd -- /bin/sh -c "ETCDCTL_API=3 etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints 10.0.1.20:2379 snapshot save /var/lib/etcd/snapshot-node0-$(date +%m%d).db"; 

## 3. Copy snapshot file to your local machine from etcd-0
$ oc rsync master-etcd-ocp-master-prd-0:/var/lib/etcd/snapshot-node0-$(date +%m%d).db .

## 4. Sync the directory (snapshot fil)e to file debug pod
oc rsync ./snapshot/ master-etcd-ocp-master-prd-1-debug:/var/lib/etcd/

## 5. Move snapshot db file /var/lib/etcd/member/snap/
## These commands shoud run in debug pod
$ cp /var/lib/etcd/snapshot-node0-0630.db /var/lib/etcd/member/snap/db

## 6. Wait for it restart, then etcd-1 came up, joined in cluster
```

**Comment by csidiro** [comment]
> I had similar issue. etcd pod was failed start due to unexpected Azure VM reboot.
> 
> ```
> 2021-06-28 16:12:32.246822 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/etcd/ca.crt
> 2021-06-28 16:12:32.246900 I | etcdmain: etcd Version: 3.2.22
> 2021-06-28 16:12:32.246910 I | etcdmain: Git SHA: 1674e682f
> 2021-06-28 16:12:32.246915 I | etcdmain: Go Version: go1.8.7
> 2021-06-28 16:12:32.246922 I | etcdmain: Go OS/Arch: linux/amd64
> 2021-06-28 16:12:32.246928 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
> 2021-06-28 16:12:32.246984 N | etcdmain: the server is already initialized as member before, starting as etcd member...
> 2021-06-28 16:12:32.247035 I | embed: peerTLS: cert = /etc/etcd/peer.crt, key = /etc/etcd/peer.key, ca = , trusted-ca = /etc/etcd/ca.crt, client-cert-auth = true
> 2021-06-28 16:12:32.248344 I | embed: listening for peers on https://10.0.1.21:2380 
> 2021-06-28 16:12:32.248912 I | embed: listening for client requests on 10.0.1.21:2379
> 2021-06-28 16:12:32.281703 I | etcdserver: recovered store from snapshot at index 444604492
> 2021-06-28 16:12:32.303933 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
> panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
>  panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb7bbdc]
> goroutine 1 [running]:
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc4201cc398, 0xc4201cc170)
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:284 +0x3c
> panic(0xdb1280, 0xc42000e230)
>  /usr/local/google/home/jpbetz/.gvm/gos/go1.8.7/src/runtime/panic.go:489 +0x2cf
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201c2020, 0xf98878, 0x2a, 0xc4201cc1e0, 0x1, 0x1)
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x15c
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc420056ea0, 0x0, 0x14b0580, 0xc42000e0b0)
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:379 +0x2e75
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42004c800, 0xc420074a80, 0x0, 0x0)
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:157 +0x76a
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42004c800, 0x6, 0xf73bf3, 0x6, 0x1)
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x58
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:103 +0x1579
> github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:39 +0x61
> main.main()
>  /tmp/etcd-release-3.2.22/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
> ```
> 
> In my case, there are 2 members up and running. Below is thigs I did
> 
> ```
> ## 0. Start failed etcd pod(etcd-01) in debug mode in openshift dashboard
> 
> ## 2. Take backup snapshot on etcd-0(etcd-01 is already running fine)
> $ oc exec -it master-etcd-ocp-master-prd-0 -c etcd -- /bin/sh -c "ETCDCTL_API=3 etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints 10.0.1.20:2379 snapshot save /var/lib/etcd/snapshot-node0-$(date +%m%d).db"; 
> 
> ## 3. Copy snapshot file to your local machine from etcd-0
> $ oc rsync master-etcd-ocp-master-prd-0:/var/lib/etcd/snapshot-node0-$(date +%m%d).db .
> 
> ## 4. Sync the directory (snapshot fil)e to file debug pod
> oc rsync ./snapshot/ master-etcd-ocp-master-prd-1-debug:/var/lib/etcd/
> 
> ## 5. Move snapshot db file /var/lib/etcd/member/snap/
> ## These commands shoud run in debug pod
> $ cp /var/lib/etcd/snapshot-node0-0630.db /var/lib/etcd/member/snap/db
> 
> ## 6. Wait for it restart, then etcd-1 came up, joined in cluster
> ```

Thanks @veerendra2 for this. Had the same issue and the steps you mentioned here worked for me as well to recover a failing etcd node.
