### ISSUE TITLE
YCSB benchmarking for etcd

### ISSUE THREAD

**Issue by riteshsinha-ritz** [etcd-io/etcd#12494]
Hi etcd community,
  I had a question regarding the YCSB benchmarking for etcd. Has this been done before? If yes, can someone please point me to that.
  I see that there is a `benchmark` tool in the repo. Can it be used to update the same keys?
Thanks.

**Comment by tjungblu** [comment]
I've added etcd to the golang port of YCSB here: https://github.com/pingcap/go-ycsb/pull/247
