### ISSUE TITLE
Number of "conns" in benchmark tool produce no effect in throughput

### ISSUE THREAD

**Issue by rachitmanit** [etcd-io/etcd#12505]
As per benchmark performance guide: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md

Setup: 
- 3 etcd nodes distributed in 3 Zone
- Have ping latency 13-14ms between each nodes

While benchmarking **WRITEs**, increasing number of connections has no significant effect in benchmarking results

**Example:**

**Test1:**
benchmark --endpoints=${HOST_1} --target-leader **--conns=1 --clients=3** put --key-size=8 --sequential-keys --total=10000 --val-size=256

`
Time: 98.0503s
Avg Latency: 30.9ms
Throughput (rps): 101.9885
`

**Test2:**
benchmark --endpoints=${HOST_1} --target-leader **--conns=3 --clients=3** put --key-size=8 --sequential-keys --total=10000 --val-size=256

`
Time: 92.3117s
Avg Latency: 29.2ms
Throughput (rps): 108.3286
`

**Test3:**
benchmark --endpoints=${HOST_1} --target-leader **--conns=10 --clients=3** put --key-size=8 --sequential-keys --total=10000 --val-size=256

`
Time: 94.7404s
Avg Latency: 30.6ms
Throughput (rps): 105.5516
`

Please help me in knowing use of **connection** option?

**Comment by christiansicari** [comment]
For me, the difference between connections and clients params is not clear.
Maybe if you have client < connection you cannot parallelism the requests, instead with connection > client you have unused connections
