### ISSUE TITLE
limitSize function detect？

### ISSUE THREAD

**Issue by benlatern** [etcd-io/etcd#12501]
vendor/go.etcd.io/etcd/3/raft/util.go line 212
`func limitSize(ents []pb.Entry, maxSize uint64) []pb.Entry`
The ent[0] will be returned regardless of whether the limit is exceeded
In this case, can this function still limit the size?

**Comment by spzala** [comment]
The limitSize func, https://github.com/etcd-io/etcd/blob/master/raft/util.go#L212, looks good to me but please feel free to send a PR. There is also an associated test TestLimitSize in the util_test.
