### ISSUE TITLE
Convert master branch to main

### ISSUE THREAD

**Issue by BensonCasey7** [etcd-io/etcd#12504]
In order to help make the etcd community a little bit more inclusive, it would be great to follow the lead of many in the larger open source community and convert the master branch to main. The cost is very minimal and the benefits are important.

There are many resources as to how to carry this out and more reasons as to why this is a good idea, for example: http://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/

**Comment by cfc4n** [comment]
MDZZ
