### ISSUE TITLE
This dependence is incorrect

### ISSUE THREAD

**Issue by seefan** [etcd-io/etcd#12527]
go get: go.etcd.io/etcd/client/v3@v3.0.0-20201204010209-ca866c02422f requires
	go.etcd.io/etcd/api/v3@v3.5.0-pre: reading go.etcd.io/etcd/api/api/go.mod at revision api/v3.5.0-pre: unknown revision api/v3.5.0-pre

**Comment by ptabor** [comment]
This is blocked on: https://github.com/etcd-io/etcd/issues/12498

And dup of: 
  https://github.com/etcd-io/etcd/issues/12412
  https://github.com/etcd-io/etcd/issues/12484

**Comment by ptabor** [comment]
v3.5.0-alpka.0 got released.
