### ISSUE TITLE
Can not go get benchmark CLI tool

### ISSUE THREAD

**Issue by StephenLee1991** [etcd-io/etcd#12526]
go version go1.15.1 linux/amd64
Using  `go get go.etcd.io/etcd/tools/benchmark` results in:

`go get go.etcd.io/etcd/tools/benchmark: module go.etcd.io/etcd@upgrade found (v3.3.25+incompatible), but does not contain package go.etcd.io/etcd/tools/benchmark`

**Comment by ericsuhong** [comment]
Seeing same issue here

**Comment by christiansicari** [comment]
I solved pulliing the repo and building by myself the package
```
go build ; 
go install
```

**Comment by agoddard** [comment]
This is still an issue when attempting the original command in the issue

**Comment by tracetechnical** [comment]
Very much still an issue.

**Comment by serathius** [comment]
Command pasted above is outdated. Benchmark documentation https://github.com/etcd-io/etcd/blob/main/tools/benchmark/README.md uses:
```
go get go.etcd.io/etcd/v3/tools/benchmark
```
I have verified that running this commend, as so I don't see a reason to reopen this issue.

**Comment by tracetechnical** [comment]
This still gives a deprecation warning on my machine.

**Comment by tracetechnical** [comment]
Running go 1.17 on Ubuntu 20.04 still gives the error from the start of this issue.

**Comment by tracetechnical** [comment]
Running go 1.17 on Ubuntu 20.04 yeilds a deprecation warning. Are there any plans to actually move to go install?

**Comment by serathius** [comment]
Not to my knowledge, however we are open for contributions!
