### ISSUE TITLE
Why auth model method Authenticate() run with raft???

### ISSUE THREAD

**Issue by yangxuanjia** [etcd-io/etcd#12539]
Why auth model method Authenticate() run with raft???
and add it to wal?
UserGet, UserList, RoleGet, RoleList too.

**Comment by mitake** [comment]
In the case of Authenticate(), the main reason is the simple token. Unlike jwt token and CN based authn, it needs to update etcd server's state. So it needs to go through raft.

For other operations, I think handling them like linearizable Range or read only Txn would be possible. But in many cases these operations don't happen so much. So I think their overhead is trivial.
