### ISSUE TITLE
Facing “ENV ETCD_UNSUPPORTED_ARCH=arm64” issue using arm64 docker image 

### ISSUE THREAD

**Issue by odidev** [etcd-io/etcd#12543]
I was trying to build the [dubbo ](https://github.com/apache/dubbo)package where it was having jetcd dependency which uses the etcd docker image.  I was trying to use the pre build docker [image  ](https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd?gcrImageListsize=30)of etcd for arm64 and found that the image is not working properly. The container is getting exited with  below error

`etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set
`

I have tried building the docker image locally by providing the etcd , etcdl arm64 binaries and adding the argument **"ENV ETCD_UNSUPPORTED_ARCH=arm64”**. The Dockerfile of the etcd docker image built locally is as follows: 

```
FROM us.gcr.io/k8s-artifacts-prod/build-image/debian-base-arm64:v2.1.0
ADD bin/etcd /usr/local/bin/
ADD bin/etcdctl /usr/local/bin/
ENV ETCD_UNSUPPORTED_ARCH=arm64
EXPOSE 2379 2380
CMD ["/usr/local/bin/etcd"]

```
After these changes it is working fine for arm64. It seems that we should add the  **“ENV ETCD_UNSUPPORTED_ARCH=arm64”** in arm64 dockerfile.

It will be helpful if arm64 docker images are uploaded with these changes. If required I will raise the PR for the same.

**Comment by anthr76** [comment]
I'm looking to kubeadm init with etcd and cannot find a way to set this environment variable. It would be incredibly helpful to have this in the images.

**Comment by oldthreefeng** [comment]
use `k8s.gcr.io/etcd:xxx` instead  🔢

**Comment by huminhua2024** [comment]
pre-built release binaries:

ETCD_VER=v3.5.11

# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/etcd-io/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}

mkdir -p /tmp/etcd-download-test

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-arm6464.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-arm64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-arm64.tar.gz -C /tmp/etcd-download-test --strip-components=1

cd  /tmp/etcd-download-test/

cp -a etc /usr/local/bin/
cp -a etcdctl /usr/local/bin/


root@master01:~# etcdctl version
etcdctl version: 3.5.11
API version: 3.5
root@master01:~# etcd --version
etcd Version: 3.5.11
Git SHA: 3b252db4f
Go Version: go1.20.12
Go OS/Arch: linux/arm64
