### ISSUE TITLE
etcd-mixin: etcdExcessiveDatabaseGrowth Prometheus alert should use delta instead of increase

### ISSUE THREAD

**Issue by manfredlift** [etcd-io/etcd#12550]
https://github.com/etcd-io/etcd/blob/a3174d0f8ec6ec58827d7d86448bb4df08ae69e4/Documentation/etcd-mixin/mixin.libsonnet#L263-L275

Both `etcd_mvcc_db_total_size_in_bytes` and `etcd_server_quota_backend_bytes` are Prometheus gauges and the [`increase()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) Prometheus function should only be used for counters. I suggest using [`delta()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta), which is designed for gauges.

One of the issues encountered with this specific alarm is that it gets triggered for 50% decrease of etcd disk space (e.g after running compact and defrag).

**Comment by hexfusion** [comment]
great input, thank you.

cc @chaitanyaenr

**Comment by chaitanyaenr** [comment]
+1 great suggestion, will fix it. Thanks.

**Comment by nic-chen** [comment]
I would like to fix it. could you please assign to me？ thanks

**Comment by lilic** [comment]
👋 @chaitanyaenr seems to be assigned to it already, @chaitanyaenr do you have the fix for this already, otherwise maybe @nic-chen can tackle this one?

**Comment by lilic** [comment]
Also note here, I would say we use `deriv` rather than `delta`, as delta only takes first and last sample into account. More info here https://www.robustperception.io/functions-to-avoid

**Comment by chaitanyaenr** [comment]
Sorry, I missed this issue. @lilic Thanks for the pointers, will take a shot at fixing it.
