### ISSUE TITLE
How to get previous keys

### ISSUE THREAD

**Issue by jiashiwen** [etcd-io/etcd#12566]
Hi
   I use clientv3.WithLimit() and clientv3.WithFromKey() to implement paginte.And get the keys after "fromkey".The question is how to get previous keys fromkey and I want to implement previous page

thx

**Comment by agargi** [comment]
@jiashiwen AFAIK, etcd does not support backward pagination. IIUC, supporting this means implementing additional comparison capability in the Interval Tree ADT that etcd uses to manage the keys.
