### ISSUE TITLE
Is there a way to configure grpc.MaxCallRecvMsgSize

### ISSUE THREAD

**Issue by spacewander** [etcd-io/etcd#12576]
After https://github.com/etcd-io/etcd/issues/9043, the grpc client can set MaxCallRecvMsgSize when creating a request.

But when the client accesses etcd via http (through the proxy of grpc-gateway), it seems there is not a way to configure `grpc.MaxCallRecvMsgSize`?

**Comment by agargi** [comment]
@spacewander Should this not be a gRPC Gateway question? I believe gRPC Gateway may be providing this kind of capability through metadata sent as part of request header.

**Comment by spacewander** [comment]
@agargi 
MaxCallRecvMsgSize is a client option, not a metadata name. AFAIK, gRPC Gateway doesn't provide a feature to set it via HTTP request.

**Comment by spacewander** [comment]
Does the problem still exist?

**Comment by simonhou** [comment]
@spacewander Our apisix  use etcd v3.4, still exist.

**Comment by spacewander** [comment]
@simonhou 
I have just submitted a PR to solve the issue
