### ISSUE TITLE
Get clientv3 error with grpc v1.33.2

### ISSUE THREAD

**Issue by yu31** [etcd-io/etcd#12571]
We needs to use gRPC server and client with version v1.33.2 in own projects. But when I try get the clientv3 of latest version always wrong.  It looks to be a compatibility problems with  gRPC v1.33.2. 

Is there any plans to solve this?

My go.mod file is:
`go 1.15

require (
	github.com/golang/protobuf v1.4.3
	github.com/grpc-ecosystem/go-grpc-middleware v1.2.2
	github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
	github.com/pkg/errors v0.9.1
	github.com/prometheus/client_golang v1.8.0
	github.com/stretchr/testify v1.6.1
	github.com/yu31/snowflake v0.0.0-20201212140846-eca7f34c6cd3
	google.golang.org/grpc v1.33.2
	google.golang.org/protobuf v1.25.0
	gorm.io/driver/mysql v1.0.3
	gorm.io/gorm v1.20.6
)`

Some error:
go get  -v go.etcd.io/etcd/clientv3

`github.com/coreos/etcd/clientv3/balancer/picker
../../../go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../../go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
 github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../../go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../../go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOptionl`

**Comment by ptabor** [comment]
Please see: 
https://github.com/etcd-io/etcd/pull/12398
and attached issues.

**Comment by yu31** [comment]
@ptabor  Thanks for a reply,  I'll take a look.

**Comment by ptabor** [comment]
Please use: #12124 is canonical for grpc update problem.

**Comment by ramil600** [comment]
Currently as I see clientv3 still uses deprecated resolver:

`func (c *Client) Dial(ep string) (*grpc.ClientConn, error) {
	creds := c.credentialsForEndpoint(ep)

	// Using ad-hoc created resolver, to guarantee only explicitly given
	// endpoint is used.
	return c.dial(creds, grpc.WithResolvers(resolver.New(ep)))`

If we try to update it with the new implemented resolver it will create import cycle, as I tried to do:
`package go.etcd.io/etcd/client/v3
        imports go.etcd.io/etcd/client/v3/naming/resolver
        imports go.etcd.io/etcd/client/v3: import cycle not allowed`

What is the best way around for refactoring it? what do you think?
