### ISSUE TITLE
Give increased lease timeout if etcd is under load

### ISSUE THREAD

**Issue by agargi** [etcd-io/etcd#12594]
Problem statement:

There is a TODO in code that asks for lessor to give higher duration leases in case etcd is under load.

Questions:

1. Is this problem statement valid?
2. Is there a single metric that indicates that etcd is under load? 
3. If yes, I believe metric by itself may not be enough to indicate a high load condition and its increase over a certain duration may indicate high load condition. How to measure increase (I believe Prometheus does it on its side)?
4. I believe maximum lease duration is 9 seconds. And recommendation is to not grant short leases (2-3 seconds) anyway, How should increased duration of lease look like?

@tangcong Welcome your inputs on this. /cc @xiang90 @jingyih

**Comment by tangcong** [comment]
are you talking about this? https://github.com/etcd-io/etcd/blob/master/server/lease/lessor.go#L270-L277

**Comment by agargi** [comment]
> are you talking about this? https://github.com/etcd-io/etcd/blob/master/server/lease/lessor.go#L270-L277

@tangcong Yes

**Comment by tangcong** [comment]
this statement is commit by this [pr](https://github.com/etcd-io/etcd/commit/25f82b25f7ca7e97fb4c258ea7ae17fda72d9dbf),  it is very old and the code has restricted the minimum TTL of lease, so i guess this statement is invalid.

**Comment by agargi** [comment]
@tangcong I understand minimum lease duration is specified but does this TODO not mean that - Even if client asks for let's say 6 seconds, when etcd is under high load, etcd can decide to grant a lease of say 8 seconds?
