### ISSUE TITLE
go get client v3 error 

### ISSUE THREAD

**Issue by febelery** [etcd-io/etcd#12599]
```shell
> go get go.etcd.io/etcd/client/v3@v3.5.0-pre

go get: go.etcd.io/etcd/client/v3@v3.5.0-pre: invalid version: unknown revision client/v3.5.0-pre
```

**Comment by PatrLind** [comment]
How did you solve this issue? I am unable to install any etcd client version at the moment...

**Comment by Q1mi** [comment]
> How did you solve this issue? I am unable to install any etcd client version at the moment...

https://github.com/etcd-io/etcd/issues/12484#issuecomment-735515940
