### ISSUE TITLE
Issues with logging 

### ISSUE THREAD

**Issue by anandrgitnirman** [etcd-io/etcd#12596]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
We have configured ETCD as a Linux Service.
Currently all the logs that is been generated by etcd are getting written to journalctl.
When configured to output the stderr & stdout to a file as a part of the service, it did not write to the file rather it continued writing journalctl.
Difficicult to set up alerts say on cloudwatch with the above described issue.

**Comment by agargi** [comment]
@anandrgitnirman Although I have not tried the etcd stdout, stderr options, one other option might be to make jounrnalctl log persistent and then use it the way you want to.
