### ISSUE TITLE
Review documentation about etcd storage files.

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#12598]
I wrote a documentation about etcd storage files, as I found this important to:
  - understand how etcd works
  - understand data-recovery procedures if things go wrong. 

https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#

For efficient iterations its currently a Google Doc, but when its declared to be "good enough", 
I will transform it to a markdown language PR. 

@gyuho @xiang90 @tangcong @jpbetz @nate-double-u @spzala - looking for your feedback/contributions. Thank you.

**Comment by jpbetz** [comment]
Huge thanks for writing this.

Reading this points out a bunch of opportunities for future improvements. For example, etcd v2 support should be removed at some point. There are a bunch of minor fixups suggested here too.

The full list of buckets stored in etcd is really great to have too.

**Comment by spzala** [comment]
Agree with @jpbetz This will be a great addition to the Doc so looking forward to the PR :). As he mentioned, it also identifies needed work to remove some of the dependencies on the v2 to eventually phase it out. I had one in-line comment in the doc,  and some of the docs specific review we can do it better once the markdown is ready. Thanks @ptabor

**Comment by agargi** [comment]
@ptabor Where would this document eventually go? I'm thinking of writing a doc too but want to make sure it is useful and addresses certain audience.

**Comment by ptabor** [comment]
I'm targeting it here: https://etcd.io/docs/v3.4.0/dev-guide/. 
Also @nate-double-u is working on reorganization of the docs, so there will be a cleaner structure.

**Comment by embano1** [comment]
Just found this issue! Glad someone is working on improving the docs for this great piece of technology!
Not sure if it's useful, but I wrote a blog post about some etcd internals https://www.mgasch.com/2021/01/listwatch-part-1/

Happy to contribute since it's already in markdown. Let me know if it helps.

**Comment by ptabor** [comment]
@embano1 the blog-post is awesome. Thank you.

**Comment by nate-double-u** [comment]
Hi @ptabor, I've gone through and done a copy-edit pass. Hope it's not too late to be helpful. I'd be happy to do another pass once you've converted it to a markdown file.
