### ISSUE TITLE
Missing limit guidelines and understanding

### ISSUE THREAD

**Issue by fredczj** [etcd-io/etcd#12603]
After 12 months of running ETCD cluster without issues, we have just faced a first huge failure.

ETCD cluster became `unhealthy` with `file description` limit error: `80% of the file descriptor limit is used [used = 901, limit = 1024]`.

`ulimit` is also no 1024 (soft or hard): 

```
ubuntu@lorn1:/var/log$ ulimit -n
100000
```

I went through multiple posts on this without finding a clear answer about how to monitor `file` usage of ETCD. 

I finally went to [remove all the limits](https://github.com/etcd-io/etcd/issues/2477#issuecomment-231043226) from the system; this helps, but the situation is unhealthy on machine's side, no?

> 
> Implementation in /etc/systemd/system/etcd.service:
> ```
> LimitAS=infinity
> LimitRSS=infinity
> LimitCORE=infinity
> LimitNOFILE=65536
> ExecStart= /usr/local/bin/etcd \
>   --name etcd-lorn1 \
>   --data-dir=/data/etcd \
>   --initial-cluster-token etcd-cluster-1 \
>   --initial-advertise-peer-urls http://lorn1:2380 \
>   --advertise-client-urls http://lorn1:2379 \
>   --listen-peer-urls http://10.3.30.1:2380 \
>   --listen-client-urls http://10.3.30.1:2379 \
>   --initial-cluster etcd-lorn1=http://lorn1:2380,etcd-lorn2=http://lorn2:2380,etcd-lorn3=http://lorn3:2380 \
>   --initial-cluster-state new
> ```
> 

Since this configuration, I can see new messages in the syslog. One machine says: 
```
Jan  7 12:36:45 lorn2 etcd[2087]: failed to send out heartbeat on time (exceeded the 100ms timeout for 15.926719ms, to 67da352b3dbed904)
Jan  7 12:36:45 lorn2 etcd[2087]: server is likely overloaded
```

or and another signals long operation:

```
... with result "size:18" took too long (483.34048ms) to execute
```

BTW, for every restart, I needed to clear the /data/member directory to make the cluster restart, which was acceptable based on our usage, as we use ETCD mostly for parameter sharing and concurrent mutex (= many watches).

My cluster contains 3 nodes. 

|               ENDPOINT               |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
|--------------------------------------|------------------|---------|---------|-----------|------------|-----------|------------|--------------------|--------|
| http://lorn1:2379 | 67da352b3dbed904 |   3.4.4 |  1.2 MB |     false |      false |         2 |      10955 |              10955 |        |
| http://lorn2:2379 | 985320a8548a0ef5 |   3.4.4 |  1.2 MB |      true |      false |         2 |      10955 |              10955 |        |
| http://lorn3:2379 | cfa2a45ff7f080dc |   3.4.4 |  1.2 MB |     false |      false |         2 |      10955 |              10955 |        |

Healthcheck says: 

```
lorn1:2379 is healthy: successfully committed proposal: took = 34.943621ms
lorn3:2379 is healthy: successfully committed proposal: took = 43.072256ms
lorn2:2379 is healthy: successfully committed proposal: took = 47.381314ms
```

## Questions

It sounds I have some network limitations, but I don't know how to track this. Would it cause file descriptor limitation to trigger?

What information can I collect?

Which configuration sounds more suitable instead of removing all the limitation ?

**Comment by agargi** [comment]
@fredczj IMHO, here are relevant points:

1. Your limit of 1024 might be user specific soft limit
2. The FD usage on etcd is combined fds required for both files & transport (i.e. client connections)
3. etcd reserves 150 fds for its own use
4. Rest of fds should be available for client connections/ transport use
5. It might be worthwhile to check number of anticipated client connections and accordingly set the limit

Hope this helps!

**Comment by fredczj** [comment]
OK, Thank you. There are information here I had not. 
I will check it. I close the issue while it make my situation match with your description.
