### ISSUE TITLE
Benchmark conns and client options

### ISSUE THREAD

**Issue by christiansicari** [etcd-io/etcd#12601]
In the https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md is not clear how to deal with the conns and client params, is there a relationship?
It seems that the total request R are divided among all the clients (for example: 100 R, 20 C -> 5 requests for client).
But, how does the conn parameter impact? Maybe, is it the maximum number of parallel connections available?

**Comment by agargi** [comment]
@christiansicari 

Yes. That is correct. Benchmark utility establishes the number of connections specified by 'conns' parameter and then shares them equally with clients.
