### ISSUE TITLE
No repair record has been found for a websocket vulnerability. Is there any impact?

### ISSUE THREAD

**Issue by zhousam** [etcd-io/etcd#12605]
The current websocket version used by etcd is:
`github.com/gorilla/websocket v0.0.0-20170926233335-4201258b820c // indirect`

The websocket of this version has the following security vulnerability:
[GHSA-jf24-p9p9-4rjh](https://github.com/gorilla/websocket/security/advisories/GHSA-jf24-p9p9-4rjh)

Question:

No repair record of the websocket vulnerability is found in etcd 3.4.0 to 3.4.14. 
**Does this vulnerability have no security risk for etcd version 3.4.0 or above?**

**Comment by spzala** [comment]
Thakns for reporting! Closing per above mentioned PR. The fix will go in the upcoming point release of 3.4
