### ISSUE TITLE
inconsistent context package in etcdserver/etcdserverpb/rpc.pb.go

### ISSUE THREAD

**Issue by zaoying** [etcd-io/etcd#12616]
Hi, I am developing on a tool which scans recursively *.go file by using `go/ast` and `go/types` package.

Recently, I ran into a trouble when the tool I developed scanning etcd's code, which version is `v3.4.10` .

It took me two days to locate the code causes this trouble.

[etcdserver/etcdserverpb/rpc.pb.go](https://github.com/etcd-io/etcd/blob/v3.4.10/etcdserver/etcdserverpb/rpc.pb.go)

```go
package etcdserverpb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/gogo/protobuf/gogoproto"

	mvccpb "go.etcd.io/etcd/mvcc/mvccpb"

	authpb "go.etcd.io/etcd/auth/authpb"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"

	io "io"
)

//**
// skipping irrelevant code
//**

func _KV_Range_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Range(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdserverpb.KV/Range",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Range(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

//**
// skipping irrelevant code
//**

var _KV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "etcdserverpb.KV",
	HandlerType: (*KVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Range",
			Handler:    _KV_Range_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KV_Put_Handler,
		},
		{
			MethodName: "DeleteRange",
			Handler:    _KV_DeleteRange_Handler,
		},
		{
			MethodName: "Txn",
			Handler:    _KV_Txn_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _KV_Compact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
```

compare the code,  the `context` package is referrenced to `golang.org/x/net/context`, while the `grpc.MethodDesc` itself using the builtin `context` pakcage.

[vendor/google.golang.org/grpc/server.go](https://github.com/etcd-io/etcd/blob/v3.4.10/vendor/google.golang.org/grpc/server.go)

```go
package grpc

import (
	"context"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"reflect"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"golang.org/x/net/trace"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/encoding"
	"google.golang.org/grpc/encoding/proto"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/internal/binarylog"
	"google.golang.org/grpc/internal/channelz"
	"google.golang.org/grpc/internal/grpcsync"
	"google.golang.org/grpc/internal/transport"
	"google.golang.org/grpc/keepalive"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/stats"
	"google.golang.org/grpc/status"
	"google.golang.org/grpc/tap"
)

const (
	defaultServerMaxReceiveMessageSize = 1024 * 1024 * 4
	defaultServerMaxSendMessageSize    = math.MaxInt32
)

var statusOK = status.New(codes.OK, "")

type methodHandler func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor UnaryServerInterceptor) (interface{}, error)

...
```

It seems the code try to assign `methodHandler` with `_KV_Range_Handler` , but they referrenced different 'context' package, which cause my developing tool gave me this error message below

```
ERRO[0238] /root/src/etcd/etcdserver/etcdserverpb/rpc.pb.go:3637:16: cannot use _KV_Range_Handler (value of type func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error)) as grpc.methodHandler value in struct literal
```

Is there something to do with `code generator` ? Referenced the wrong 'context' package ?

please help! I am working on a code analysing tool.

**Comment by ptabor** [comment]
1. https://pkg.go.dev/golang.org/x/net/context#Context states: 

Package context defines the Context type, which carries deadlines, cancelation signals, and other request-scoped values across API boundaries and between processes. As of **Go 1.7 this package is available in the standard library under the name context. https://golang.org/pkg/context**.

2. Context is an interface: https://golang.org/pkg/context/#Context
It means that the type implementing one Context's interface is also fulfilling requirements of the other Context, so can be used, as the requirements in both files are the same.

**Comment by zaoying** [comment]
Thank you very much, guys.

 I figure it out. 

There are four files in the `golang.org/x/net/context` pakcage, the first is  `go17.go`, the second is `go19.go` , the third is `pre_go17.go` and the fourth is `pre_go19.go`. 

I just add 'go19=true' into config file, then my tools selective compile the `go19.go`，but ignore the `pre_go19.go`.

Finally, there is no more error message in the console. Problem solved !!!

//close
