### ISSUE TITLE
etcd premission questions

### ISSUE THREAD

**Issue by maxucheng0** [etcd-io/etcd#12613]
I have two questions?please answer.
1、Why use 700 instead of 600 on data files?
2、Do you change only directory permissions or data file permissions?

**Comment by maxucheng0** [comment]
[
![1](https://user-images.githubusercontent.com/21236162/104282300-cdb16400-54e9-11eb-9bd1-117dc5400953.PNG)
](url)

**Comment by maxucheng0** [comment]
![1](https://user-images.githubusercontent.com/21236162/104282343-dd30ad00-54e9-11eb-8047-e1f43fe6a82f.PNG)

**Comment by ptabor** [comment]
The dir must be 0700 to allow listing of content of the directory. 
It's sufficient when the files have 0600 permissions. It's even encoded here: 

https://github.com/etcd-io/etcd/blob/c632042bb96cc3e3649b5e94bd08a07b100bbc6c/pkg/fileutil/fileutil.go#L29

Do you see etcd-data executable files  ?

**Comment by maxucheng0** [comment]
Yes, I found that the permission of the data file is 700 after I restart the container
![etcd权限设置](https://user-images.githubusercontent.com/21236162/104535896-f94f5e00-5651-11eb-93a9-322791204692.PNG)
