### ISSUE TITLE
Broadcast for peer discovery

### ISSUE THREAD

**Issue by dminkovsky** [etcd-io/etcd#1262]
Hi etcd,

I've been wondering whether broadcast was ever considered for peer discovery. This wouldn't scale beyond a local CIDR, but that's probably the case with the majority of etcd, CoreOS installations. Was this ever proposed? If so, was it ever rejected for some particular reason?

Thank you

**Comment by mercuriete** [comment]
+1

when deploying on baremetal will be useful to have a multicast/zeroconf discovery service.

im not confortable relying in external services as https://discovery.etcd.io  and i am to lazy to follow this tutorial https://coreos.com/etcd/docs/latest/clustering.html

Thanks for your work :)
