### ISSUE TITLE
"Key Not Found" error removed in v3

### ISSUE THREAD

**Issue by Gunakk** [etcd-io/etcd#12627]
HI there,

I installed etcd v2 and etcd v3.4.0.  Did etcdctl get for a non existing key in both. Got "Key not found" error in v2 and but, in v3 there isn't any response. May I know why this change was introduced ?

Thanks,
Guna

**Comment by ptabor** [comment]
I don't know, but I would guess the motivation was to allow safer usage in scripting, like: 

MY_KEY=$(etcdctl get mykey)

But, personally I would expect at least exit_code ~= 0 if no key matching the requirements was found. 

@xiang90 What do you think about such contribution to: https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/get_command.go ? For backward compatibility it would need to be an opt-in flag.

**Comment by xiang90** [comment]
> But, personally I would expect at least exit_code ~= 0 if no key matching the requirements was found.

This should be better. 

The motivation is to keep the stdout clean and consistent. So we do not print out "key not found" to stdout anymore in v3.

**Comment by ptabor** [comment]
Thank you @xiang90.
BTW: I approved similar (error-code) related contribution in: https://github.com/etcd-io/etcd/pull/12829
