### ISSUE TITLE
how to put a value within which there exist an 'enter'

### ISSUE THREAD

**Issue by GeorgeGuo2018** [etcd-io/etcd#12628]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

**Comment by ptabor** [comment]
Depends what tool/lib you need to use to perform the write: 

In case of etcdctl you just need to provide the formatted stdin: 
```
echo -e "one line\nsecond_line" | ./bin/etcdctl put foo
```

**Comment by GeorgeGuo2018** [comment]
> Depends what tool/lib you need to use to perform the write:
> 
> In case of etcdctl you just need to provide the formatted stdin:
> 
> ```
> echo -e "one line\nsecond_line" | ./bin/etcdctl put foo
> ```

Thanks for your reply. That works for me.

**Comment by GeorgeGuo2018** [comment]
./bin/etcdctl put test <<EOF
value1
value2
EOF


this can also works
