### ISSUE TITLE
Why createinorder is removed from etcd client v3?

### ISSUE THREAD

**Issue by tomasliu-agora** [etcd-io/etcd#12625]
In client v2, we can use CreateInOrder to implement distributed queue on etcd.

From https://www.bookstack.cn/read/etcd-v3.4.0/b05a806fd6f9e58a.md

```
// curl http://127.0.0.1:2379/v2/keys/queue -XPOST -d value=Job2
{
    "action": "create",
    "node": {
        "createdIndex": 29,
        "key": "/queue/00000000000000000029",
        "modifiedIndex": 29,
        "value": "Job2"
    }
}
```

However, in v3 I failed to find a way to create the CreatInOrder Put Operation.

1. Can anyone tell me why we removed that feature?
2. If that feature is removed for good, what is the best practice to work around?

**Comment by ptabor** [comment]
If you watch a particular prefix, you will get the stream of updates in the mutation's revisions order. 
It should allow to implement a queue.
