### ISSUE TITLE
Question about how to get watch id for multiple create watch request

### ISSUE THREAD

**Issue by mrwwheat7** [etcd-io/etcd#12644]
Hi Etcd team,

I am using etcd watch mechanism to keep my local cache updated. Currently I am using rust [grpcio](https://docs.rs/grpcio/0.7.1/grpcio/) to maintain a single watch stream channel in my local, then whenever a new key-value is added to the etcd server and my local cache, I need to create a watch request for this key, then get the watch id from watch response and save the watch id for this key locally, whenever this key is removed from local cache, I need to send cancel watch request for this watch id, right?

Problem:
Since the watch channel is streaming, if I send multiple create watch requests for different key simultaneously, from the streaming watch response, how can I know which response (with watch id) corresponds to which key (I need to know it to save the watch id for each key)? Or for each create watch request, should I create a new watch channel for it?

Appreciate for any help, thanks!

**Comment by agargi** [comment]
@mrwwheat7 Will this work for you? ch is watch channel.

```
	for resp := range ch {
		for _, ev := range resp.Events {
			fmt.Println(string(ev.Kv.Key))
		}
        }
```
