### ISSUE TITLE
bug: PageWriter deadloop

### ISSUE THREAD

**Issue by EricYT** [etcd-io/etcd#12647]
Branch:  master
commit: 330b157dbbf757d20c2e000d8f6dac957e22fdbd
package: go.etcd.io/etcd/pkg/ioutil/pagewriter.go

```golang
func (pw *PageWriter) Write(p []byte) (n int, err error) {
  if len(p)+pw.bufferedBytes <= pw.bufWatermarkBytes {
    // no overflow
    copy(pw.buf[pw.bufferedBytes:], p)
    pw.bufferedBytes += len(p)
    return len(p), nil
  }
...
```

desc:
1. len(p) > pw.bufWatermarkBytes && pw.bufferedBytes == 0 && pw.pageOffset == 0 && len(p) < pw.pageBytes
2. dead loop triggered.

But I don't figure out why should it works for len(p) > pw.bufWatermarkBytes and len(p) < pw.pageBytes in this package,
cause the code set a buf water mark to pending data.

**Comment by xiang90** [comment]
@EricYT 

Can you write a unit test to illustrate the problem?
