### ISSUE TITLE
Fixed raft http timeouts

### ISSUE THREAD

**Issue by truemaximkas** [etcd-io/etcd#12656]
Is it possible to redefine those constants as configurable values (doesn't matter, by envs or by command line parameters)?
https://github.com/etcd-io/etcd/blob/855eeb75c551879fe11b9718bceb8bee9b178905/server/etcdserver/api/rafthttp/peer.go#L40
https://github.com/etcd-io/etcd/blob/855eeb75c551879fe11b9718bceb8bee9b178905/server/etcdserver/api/rafthttp/peer.go#L41

Without that it is pointless to set "store timeouts" (or "dial timeouts" or any other "timeouts") more than this fixed 5s - we'll get "context: Deadline exceeded" or "context: Canceled" in any case.
For example, this is necessary for tests in slow configurations.

**Comment by xialeistudio** [comment]
configuration
```
raft-read-timeout
raft-write-timeout
```
