### ISSUE TITLE
lease not found on one member of cluster after restart

### ISSUE THREAD

**Issue by AALOON** [etcd-io/etcd#12651]
Hi.
We have a problem. After unexpected restart service/reboot one member of the cluster, this member returns to the cluster and missing a lot of leases and as a result a lot of keys (lease not found on add/update and not found on get keys). On other hand other two members work properly and have such leases => keys.
Our configuration is 3 members cluster, etcd version 3.4.13
From clent side is Include="dotnet-etcd" Version="4.1.1"
![image](https://user-images.githubusercontent.com/14330773/106246144-b0390580-621e-11eb-90ea-e3921e8a351c.png)

Usage flow:
1. creating leases
2. creating and updating some keys with such lease
3. reding some keys

Logs from members of cluster.

[logs.zip](https://github.com/etcd-io/etcd/files/5893330/logs.zip)

**Comment by ptabor** [comment]
@tangcong Might be the same issue as the one addressed in https://github.com/etcd-io/etcd/pull/12531 ?

**Comment by jiapeish** [comment]
Could you try this PR https://github.com/etcd-io/etcd/pull/12531 and see if this issue still occurs?

**Comment by AALOON** [comment]
@jiapeish It didn't work.

**Comment by tangcong** [comment]
@AALOON can you provide more detail info to reproduce it ? it does not seem to be the same issue as #12531 .

**Comment by AALOON** [comment]
@tangcong Hi.
I couldn't reproduce it by synthetic test, but we had such flow:
1. We create two leases for each session with it is timeout (from few minutes to few days). id = 2, lease1 = 2, lease2 = -2 (we do  keep alive leases, leases revoked (remove) in the end of session or by expiration)
2. During session We Create keys with specified leases depending on business logic. 
3. During session Using this keys , search, lookup, update, delete
4. but after restart one of instance cluster, it returns, but cluster inconsistent
5. two instances have keys and leases. the one which was restarted does not have some of leases
6. but interesting thing some of keys (not all) is presented in cluster if search them without specify lease and I think problem is here.

For now we just removed usage of leases from our application. And it works fine. But we have to manage expiration logic and some other logic by application. 
Seems to me leases not synced by raft or revoked on start of broken node.
