### ISSUE TITLE
grpc bump: Implement master/client/v3/naming new endpointManager & resolver

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#12652]
## Naming

In order to migrate out of decommissioned in grpc-1.30 APIs of naming (and picker), 
still addressing the use-cases documented in: 
  https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/grpc_naming.md

We execute following plan: 
   1. Introduce new interfaces as defined in: https://github.com/etcd-io/etcd/pull/12614 
   2. Implement them [**help needed**]
   3. Migrate grpc proxy on the new implementation. This is hopefully ready:(https://github.com/ptabor/etcd/commit/142b9a324552e4b859f453ac9ab6dd1a090eb2a6)
   
## Picker

Apart of dealing with clientv3/naming as documented above, 
we need to migrate clientv3/balancer on a new picker.
The code from contributions like:  
  https://github.com/etcd-io/etcd/pull/12384
  https://github.com/etcd-io/etcd/pull/12636
  https://github.com/etcd-io/etcd/pull/12439
Might be good for this (when isolated and passing test).
Mid term I would think why/whether etcd needs own balancer and why just: 
  https://pkg.go.dev/google.golang.org/grpc@v1.35.0/balancer/roundrobin
  on top of some 'passthrough' like https://pkg.go.dev/google.golang.org/grpc/resolver

**Comment by lemonlinger** [comment]
I'd like to claim this task. Is there a deadline for this?

**Comment by ptabor** [comment]
@lemonlinger Thank you. Many users are waiting for moving that dependency forward, so I hope to have it completed in O(2) weeks. We can decouple this into smaller pieces: 

1. Write variant of the resolver_test(https://github.com/etcd-io/etcd/blob/50ca440c49d85c6b88284af08248a43118b2ae68/tests/integration/clientv3/naming/resolver_test.go#L56) that uses the old API: https://etcd.io/docs/v3.3.12/dev-guide/grpc_naming/

2. EndpointManager add/delete (https://github.com/etcd-io/etcd/blob/50ca440c49d85c6b88284af08248a43118b2ae68/client/v3/naming/endpoints/endpoints_impl.go#L22) implementation

3. Write variant of the resolver_test(https://github.com/etcd-io/etcd/blob/50ca440c49d85c6b88284af08248a43118b2ae68/tests/integration/clientv3/naming/resolver_test.go#L56) that uses new endpointManager, but all resolver code

4. Implementation of new Endpoint Watch & List

5. Resolver on top of Endpoint Watch & List. 

6. Final resolver_test that entirelly uses new API. 

I think 1&2 can be done in parallel and its better to claim smaller pieces of work.

**Comment by lemonlinger** [comment]
@peterbourgon OK

**Comment by ptabor** [comment]
2 more PRs to merge: 
 - https://github.com/etcd-io/etcd/pull/12671 (replace custom balancer with upstream grpc)
 - https://github.com/etcd-io/etcd/pull/12675 (migrate grpcproxy and cleanup)
And that's a wrap.

**Comment by ptabor** [comment]
In my fork (https://github.com/ptabor/etcd/tree/20210210-grpc-bump)  I have version with the PR applies + 1 test fix + grpc-1.32 bump that **passes all the tests**
