### ISSUE TITLE
go mod go.etcd.io/etcd/clientv3 fail

### ISSUE THREAD

**Issue by IvanWhisper** [etcd-io/etcd#12650]
when go mod tidy my app with `import "go.etcd.io/etcd/clientv3"`, failed.
Error:
github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.5: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
Soluation:
github.com/coreos/bbolt => go.etcd.io/bbolt v1.3.5
google.golang.org/grpc => google.golang.org/grpc v1.26.0 

(v1.26.+ is not support clientV3 errormsg:`undefined: resolver.BuildOption`)

It is not friendly，please improve experience

**Comment by regel** [comment]
workaround: Use clientv3 in release-3.4 branch

`go get go.etd.io/etcd/clientv3@release-3.4`

**Comment by spzala** [comment]
`go get go.etcd.io/etcd/client/v3` should work. Related/dup https://github.com/etcd-io/etcd/issues/11931 Closing per issue triage guidelines. Thanks!
