### ISSUE TITLE
coreos/etcd 3.4.14 go mod pkg not available in pkg.go.dev

### ISSUE THREAD

**Issue by amalrajmani** [etcd-io/etcd#12666]
hi 
I am using etcd/raft as go module in my project.
I want to use latest version (3.4.14) as go module but its not available in [versions](https://pkg.go.dev/go.etcd.io/etcd?tab=versions)
Currently i am using 3.3.25(this is the latest available version), entry in my _go.mod_ file is _github.com/coreos/etcd v3.3.25+incompatible_

When would **version 3.4.14** be available ?

**Comment by FlyingOnion** [comment]
+1. All versions after v3.4.0 are unavailable to get using `go mod tidy`. Seems `GOPRIVATE` is the only method.
