### ISSUE TITLE
Why does a leader not ignore MsgVote requests

### ISSUE THREAD

**Issue by Cjen1** [etcd-io/etcd#12673]
My understanding of the purpose of [CheckQuorum](https://github.com/etcd-io/etcd/blob/3fddea966919b9ef14b830775e92352f962111af/raft/raft.go#L164), is that if a leader does not have a quorum of nodes commit to it will step down.
This means that followers can also ignore `MsgVote` requests when they have a stable leader.

Per [this line](https://github.com/etcd-io/etcd/blob/3fddea966919b9ef14b830775e92352f962111af/raft/raft.go#L844) when a follower with a stable leader receives either a `MsgVote` or `MsgPreVote` request with a higher term, it will ignore that message.

Since a leader either has a stable quorum which, because of the follower behavior above, will continue to be stable; or if it doesn't have a stable quorum it will step down itself; then I'd have expected a leader to have the same behavior with regards to `MsgVote` requests with a higher term.

However that doesn't appear to be whats happening. Specifically in testing (v3.4.14) `r.lead` is equal to `None` when a node is the leader and hence upon receiving a election request the leader will step down.

Is this a bug? The current behavior is safe, but could cause unnecessary the leader to step down unnecessarily.

**Comment by xiang90** [comment]
> Since a leader either has a stable quorum which, because of the follower behavior above, will continue to be stable; or if it doesn't have a stable quorum it will step down itself; then I'd have expected a leader to have the same behavior with regards to MsgVote requests with a higher term.

This applies to both leader and followers. Basically, if any member knows there is a stable leader it should just ignore msgVote and msgPreVote (followers receive message from current leader or leader receives messages from a quorum). It only grants votes if there is no known leader for the past election timeout.

**Comment by xiang90** [comment]
@Cjen1 

Do you mind writing a raft unit test to show the case?

**Comment by Cjen1** [comment]
@xiang90 Sure I can have a go.
