### ISSUE TITLE
large range request triggered OOM

### ISSUE THREAD

**Issue by wilsonwang371** [etcd-io/etcd#12678]
in our cluster with a large number of pods. range request getting all the pods can trigger etcd node OOM.

Do we have a plan to add another RPC call to provide range() response as a stream instead of the whole data in one shot?

**Comment by ptabor** [comment]
1. https://github.com/etcd-io/etcd/pull/12343 seems like some experiment / proposal around this. 
2. Clients can simulating 'streaming' by paginating (requests with "limit" set to e.g. 10k)
3. There is no decision / committed plan.
