### ISSUE TITLE
The cluster has no leader

### ISSUE THREAD

**Issue by ak476565** [etcd-io/etcd#12682]
![搜狗截图21年02月08日1212_3](https://user-images.githubusercontent.com/3871722/107489618-cbfbbe80-6bc3-11eb-9d26-7b701915bea9.png)
![搜狗截图21年02月10日1719_2](https://user-images.githubusercontent.com/3871722/107489949-31e84600-6bc4-11eb-9555-7c1e1ee884a8.png)

**Comment by ptabor** [comment]
learner != leader

learner is cluster member that is not (yet) voting and need to be added explicitly.
