### ISSUE TITLE
Update new issue template

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/etcd#12684]
Currently when opening a new issue, the following is shown in the text feild:
```
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.
```

As the documentation has been migrated to the website, it should read:

```suggest
Please read https://etcd.io/docs/current/reporting_bugs/
```

**Comment by ptabor** [comment]
Fixed in https://github.com/etcd-io/etcd/issues/12684
