### ISSUE TITLE
Move Documentation/etcd-mixin files

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/etcd#12685]
# Issue

Migrating the [Documentation to the website](https://github.com/etcd-io/etcd/pull/12660) caused the [kube-prometheus build to break](https://github.com/prometheus-operator/kube-prometheus/issues/931).

At issue in the kube-prometheus case was the removal of the `Documentation/etcd-mixin` files. [Restoring them](https://github.com/etcd-io/etcd/pull/12683) solved the kube-prometheus break, but as these files are in the Documentation folder they shouldn't be relied upon for builds.

# Solution

Organize with the [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) and remove the [Documentation/etcd-mixin](https://github.com/etcd-io/etcd/tree/master/Documentation/etcd-mixin) from the Documentation folder.

**Comment by ptabor** [comment]
https://github.com/etcd-io/etcd/tree/master/contrib looks like a place for this-type of 'integration' code.

**Comment by paulfantom** [comment]
Hi, kube-prometheus maintainer here :wave: 

Most projects store their mixins in `jsonnet/mixin/` (for example [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/tree/master/jsonnet/mixin)) or `mixin` (for example [thanos](https://github.com/thanos-io/thanos/tree/master/mixin)) directories, but usually `contrib` is also a good place.
