### ISSUE TITLE
v3.4.14; etcd flag provided but not defined: -experimental-warning-apply-duration

### ISSUE THREAD

**Issue by trisomeyr** [etcd-io/etcd#12693]
Hi devs,
i've set up a 3 node etcd cluster on some raspberry pi 4s using docker. etcd is compiled from source during docker image build using go version 1.15.8. Perhabs because i am using sdcards instead of ssd for storage during testing, i get lots of "request took too long" warnings flooding my logs. Therefore, i wanted to increase the warning threshold time using the flag -experimental-warning-apply-duration introduced in 3.4.14 (https://github.com/etcd-io/etcd/pull/12448) as adviced here: https://github.com/etcd-io/etcd/issues/10860

Expected behaviour:
The Flag gets processed by etcd at program start

Actual behaviour:
Getting the error "flag provided but not defined: -experimental-warning-apply-duration" at program start

Greets
triso

**Comment by hexfusion** [comment]
This was never backported to release-3.4[1] so I think this is expected.

[1]https://github.com/etcd-io/etcd/blob/release-3.4/etcdmain/config.go#L253

**Comment by hexfusion** [comment]
Backport https://github.com/etcd-io/etcd/pull/12740

**Comment by trisomeyr** [comment]
TOP! Thank you very much. Meanwhile worked around it by changing the code of 3.4 by myself before compiling ist :)
