### ISSUE TITLE
Max Storage Size Update

### ISSUE THREAD

**Issue by rcollina** [etcd-io/etcd#12690]
Hello,
Could anyone please confirm whether the improvements mentioned in [this post](https://www.alibabacloud.com/blog/how-does-alibaba-ensure-the-performance-of-system-components-in-a-10000-node-kubernetes-cluster_595469) have actually been merged into v3.4?

Docs still say the recommended limit is 8GB. 

Thank you

**Comment by xiang90** [comment]
Yes, it is merged in 3.4. You can go beyond 8GB with good hardware. But you need to verify it on your own.
