### ISSUE TITLE
etcd cluster replication

### ISSUE THREAD

**Issue by ltagliamonte-dd** [etcd-io/etcd#12694]
Dear community,
I'd like to understand if currently there is a project or a feature that could allow me to replicate the whole content of an etcd cluster to another cluster and keep it in sync.

The end goal here is to replicate multiple k8s cluster etcd backends to a centralized one in order to offer service discovery and other feature to developers, in a simple way.

This centralized etcd will just work for read operations no writes.
Thank you in advance !!

**Comment by Tyraelone** [comment]
you can try etcdctl make-mirror
