### ISSUE TITLE
cut 3.3.26 release

### ISSUE THREAD

**Issue by kolyshkin** [etcd-io/etcd#12698]
Please make a release in 3.3 branch to have a tagged version that includes https://github.com/etcd-io/etcd/pull/12552

Changes since the last release: https://github.com/etcd-io/etcd/compare/v3.3.25...release-3.3

**Comment by hexfusion** [comment]
/assign

I will try to cut this over the weekend

**Comment by joakim-tjernlund** [comment]
@hexfusion , ping?
