### ISSUE TITLE
Question: lease read safty when transfer leader?

### ISSUE THREAD

**Issue by Yriuns** [etcd-io/etcd#12704]
Suppose there are 3 nodes, A, B and C. Hearbeat interval = 1s, election timeout = 10s
In the beginning(0s), A is leader, each node has identical log.
At 0s, A receives a transfer leader command and sends TimeoutNow to B.
At 0.1s, A sends heartbeat to C successfully, regards it self as leader in [0.1, 10.1s].
At 0.2s, A is isolated.
At 0.3s B receives TimeoutNow and starts election and win C's vote, becomes leader.
At 10s, A thinks the leader transfer fails, resume to leader.
At 10.1s, A leader lease expires.

During [10, 10.1s], A will regard itself as leader and responds to read request, which may result in stale read.

How etcd handle this case?

**Comment by xiang90** [comment]
A should not extend its lease if it sends out a timenow request. If what you describe is true, it is probably a bug in the raft implementation? Can you write a unit test to reproduce the sequence you described?

**Comment by Yriuns** [comment]
> A should not extend its lease if it sends out a timenow request. If what you describe is true, it is probably a bug in the raft implementation? Can you write a unit test to reproduce the sequence you described?

A can extend its lease. But C will not vote B.
> We modify the RequestVote RPC to achieve this: if a server receives a RequestVote request within the minimum election timeout of hearing from a current leader, it does not update its term or grant its vote.
    (CONSENSUS: BRIDGING THEORY AND PRACTICE - p42)
