### ISSUE TITLE
The link of reporting-bugs.md is outdated

### ISSUE THREAD

**Issue by vvdvortsova** [etcd-io/etcd#12717]
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting-bugs.md.

**Comment by spzala** [comment]
Yes, thanks for reporting - few links are broken due to moving Doc to etcd-io/website repo. A generic issue is opened sometime back - https://github.com/etcd-io/etcd/issues/12700 to fix all broken links.

**Comment by ptabor** [comment]
Merged fix for this: https://github.com/etcd-io/etcd/pull/12720
