### ISSUE TITLE
What's the exact maximum db quota in etcd?

### ISSUE THREAD

**Issue by FogDong** [etcd-io/etcd#12715]
In official docs, the maximum recommend db quota is 8 GB, ref: https://github.com/etcd-io/website/blob/master/content/docs/current/dev-guide/limit.md

But in this CNCF official blog , it says that the read and write operations when etcd stores 100GB of data can be as quickly as storing 2GB. I wonder which one is correct 🤔.
> https://www.cncf.io/blog/2019/05/09/performance-optimization-of-etcd-in-web-scale-data-scenario
The new optimization reduces time complexity of the internal freelist allocation algorithm in etcd from O(n) to O(1) and the page release algorithm from O(nlgn) to O(1), which solves the performance problem of etcd under the large database size. Literally, the etcd’s performance is not bound by the storage size anymore. The read and write operations when etcd stores 100GB of data can be as quickly as storing 2GB. This new algorithm is fully backward compatible, you can get the benefit of this new algorithm without data migration or data format changes! At present, the optimization has been tested repeatedly in Alibaba for more than 2 months and no surprise happened. It has been contributed to the open source community link. You can enjoy it in the new versions of boltdb and etcd.

**Comment by xiang90** [comment]
It really depends on your hardware. The recommended setup has been tested on relatively small cloud VM (4core + 32GB + remote SSD). I know people have pushed limit to 64GB+ with better hardware setup.

So you need to test it on your own environment.
