### ISSUE TITLE
dependency conflict with three name

### ISSUE THREAD

**Issue by chenyiping111** [etcd-io/etcd#12721]
I got an error like this
    "go.etcd.io/bbolt@v1.3.3 used for two different module paths (github.com/coreos/bbolt and github.com/etcd-io/bbolt)"
and my replace is :
	github.com/coreos/bbolt => go.etcd.io/bbolt v1.3.3
	github.com/etcd-io/bbolt => go.etcd.io/bbolt v1.3.3

why there are three names? It's really confuse me，and I want to know how resolve it. thank you everyone!

**Comment by ptabor** [comment]
go.etcd.io/bbolt v1.3.5 is the current naming. The other namings are historical/legacy.

**Comment by chenyiping111** [comment]
> .thank you very much, but when I used "go mod tidy", this problem is gone.
