### ISSUE TITLE
Lock contention discovered in large put request scenario

### ISSUE THREAD

**Issue by wilsonwang371** [etcd-io/etcd#12731]
In our recent etcd performance analysis, we found that wait.go can have lock contentions during large put requests.

https://github.com/etcd-io/etcd/blob/master/pkg/wait/wait.go

![image](https://user-images.githubusercontent.com/3913185/109362869-c13a5e00-7840-11eb-9015-a813c929e2ca.png)

I added a patch which uses an array of lists in Wait struct and use mod to calculate which one to use using mod operation. I can see instant put performance improvements.

Before:
Summary:
  Total:        64.4823 secs.
  Slowest:      0.0799 secs.
  Fastest:      0.0002 secs.
  Average:      0.0021 secs.
  Stddev:       0.0051 secs.
  Requests/sec: 31016.2797

After:
Summary:
  Total:        58.2040 secs.
  Slowest:      0.0785 secs.
  Fastest:      0.0002 secs.
  Average:      0.0019 secs.
  Stddev:       0.0052 secs.
  Requests/sec: 34361.9063

benchmark command:
`
GOMAXPROCS=6 ./tools/benchmark/benchmark put --conns=64 --clients=64 --key-size=256 --val-size=4096 --key-space-size=50000 --total=2000000 --endpoints "http://127.0.0.1:23790" 2> /dev/null;
`

etcd single server command:
`
GOMAXPROCS=10 ./bin/etcd --quota-backend-bytes=17179869184 --listen-client-urls http://0.0.0.0:23790 --advertise-client-urls http://127.0.0.1:23790 --log-level error
`

I can submit a pull request for this change. This is not a big change. I am posing an issue here is just I want to have a throughout discussion before sending a pull request.

**Comment by wilsonwang371** [comment]
The diff is here: https://github.com/wilsonwang371/etcd/commit/6ad438462e10c97f1e044d02886d36a41b9c8082

**Comment by ptabor** [comment]
Nice.

Could, you, please check the performance with:
https://golang.org/src/sync/map.go?s=1149:2596#L17

pt., 26 lut 2021, 23:59 użytkownik Wilson Wang <notifications@github.com>
napisał:

**Comment by wilsonwang371** [comment]
@ptabor 

I did this and it seems like the performance is better than master branch but still not lower than my patch.

Summary:
  Total:	62.2275 secs.
  Slowest:	0.0725 secs.
  Fastest:	0.0002 secs.
  Average:	0.0020 secs.
  Stddev:	0.0051 secs.
  Requests/sec:	32140.1557

**Comment by wilsonwang371** [comment]
@ptabor 

Hi Piotr,

Do we need extra evaluation on this? I think this is not a big change and it is not changing the current etcd design so I think with a small patch pull request this would be fine.

How do you think? Do we need few others to review it?

Wilson

**Comment by ptabor** [comment]
Thank you for experimenting. That's definitely worth merging. I'm curious how the chart look after the change. 

Please send a PR and I will merge it.
