### ISSUE TITLE
[v3.4.14] etcdctl make-mirror does not reognize dest-user option

### ISSUE THREAD

**Issue by yvanadamov** [etcd-io/etcd#12746]
etcdctl make-mirror http://$IP:2379 --prefix=test --dest-user $USER:$PASSWORD

And I received:
Error: unknown flag: --dest-user

etcd version - 3.4.14

For reference: https://github.com/etcd-io/etcd/pull/11384

**Comment by spzala** [comment]
@yvanadamov this was added in the master branch https://github.com/etcd-io/etcd/pull/11384 so if you clone the repo you should see it's working. It was not backported in 3.4 but if there is a need it can be done.

**Comment by yvanadamov** [comment]
@spzala In which version I can find it fixed? If it can be ported for 3.4, it will be great.

**Comment by yvanadamov** [comment]
@spzala any update?

**Comment by yvanadamov** [comment]
@spzala  any update?

**Comment by spzala** [comment]
@yvanadamov I think this was added from 3.4.15 - can you please check it? Thanks!

**Comment by yvanadamov** [comment]
> @yvanadamov I think this was added from 3.4.15 - can you please check it? Thanks!

I checked now, I still receive the same error:

etcdctl version
etcdctl version: 3.4.15

etcdctl make-mirror http:10.102.7.182:2379 --dest-user=user:userpass
Error: unknown flag: --dest-user

**Comment by spzala** [comment]
@yvanadamov thanks for checking. I checked it too and seems like it was never backported, so 3.5 or master are the one that you can use or we can try backporting it to 3.4 and make it available in the next point release of 3.4.
