### ISSUE TITLE
etcd cluster revision sync

### ISSUE THREAD

**Issue by wilsonwang371** [etcd-io/etcd#12743]
Hi guys,

I am just curious how does this etcd make sure the leader and follower in the cluster use the same revision number when applying a KV put operation? Otherwise, with the same key, we may end up having different revision numbers on different etcd cluster nodes.

Thanks

Wilson

**Comment by wilsonwang371** [comment]
posted at wrong place

**Comment by ptabor** [comment]
Each operation goes to RAFT. RAFT guarantees that the operations are in the same order and complete on each node. 
Only when entry is comitted to the RAFT log its applied on the backend.

**Comment by wilsonwang371** [comment]
> Each operation goes to RAFT. RAFT guarantees that the operations are in the same order and complete on each node.
> Only when entry is comitted to the RAFT log its applied on the backend.

Sorry Piotr, I was posting on someone else’s fork branch and accidentally posted here. They modified the revision logic. Sorry about this.
