### ISSUE TITLE
Unable to install v3 client through go command line

### ISSUE THREAD

**Issue by pramodrj07** [etcd-io/etcd#12754]
go get "github.com/etcd-io/etcd/client/v3"

`use of internal package go.etcd.io/etcd/client/v3/internal/endpoint not allowed`

`use of internal package go.etcd.io/etcd/client/v3/internal/resolver not allowed`

I am trying to use the v3 client in my application and it seems like I am unable to fetch the package. I saw some people are having the same issue. It would be great if someone can help me resolve this issue

**Comment by ptabor** [comment]
Please use: 

```
go get go.etcd.io/etcd/client/v3
```

That is the canonical name of the module.

**Comment by ptabor** [comment]
[please reopen if it didn't solve the issue]

**Comment by pramodrj07** [comment]
Thanks for the reply!! It is working now
