### ISSUE TITLE
etcd SIGILL: illegal instruction

### ISSUE THREAD

**Issue by Ccaomei** [etcd-io/etcd#12761]
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2021/02/28 08:58:04 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"

2021-03-06 01:17:30.793617 W | etcdserver: read-only range request "key:\"/tong/task/\" range_end:\"/tong/task0\" " with result "range_response_count:20790 size:2404126" took too long (161.040615ms) to execute
2021-03-06 01:22:30.795492 W | etcdserver: read-only range request "key:\"/tong/task/\" range_end:\"/tong/task0\" " with result "range_response_count:20790 size:2404126" took too long (174.261855ms) to execute
2021-03-06 01:27:30.922990 W | etcdserver: read-only range request "key:\"/tong/task/\" range_end:\"/tong/task0\" " with result "range_response_count:20790 size:2404126" took too long (285.583231ms) to execute
2021-03-06 01:32:30.774748 W | etcdserver: read-only range request "key:\"/tong/task/\" range_end:\"/tong/task0\" " with result "range_response_count:20790 size:2404126" took too long (147.896259ms) to execute
SIGILL: illegal instruction
PC=0x57e118 m=14 sigcode=128

goroutine 2838840 [running]:
sync.(*Mutex).Unlock(...)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/sync/mutex.go:187
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc003d91270, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/internal/transport/controlbuf.go:394 +0xf0 fp=0xc007f40f18 sp=0xc007f40e58 pc=0x57e118
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc004e7db60, 0x0, 0x0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/internal/transport/controlbuf.go:513 +0x204 fp=0xc007f40f90 sp=0xc007f40f18 pc=0x57ecdc
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc001f90300)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/internal/transport/http2_server.go:286 +0xf0 fp=0xc007f40fd0 sp=0xc007f40f90 pc=0x5a43c0
runtime.goexit()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/runtime/asm_mips64x.s:646 +0x4 fp=0xc007f40fd0 sp=0xc007f40fd0 pc=0x82fb4
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/internal/transport/http2_server.go:283 +0xe84

goroutine 1 [select, 13968 minutes]:
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdmain/etcd.go:286 +0x11b8
go.etcd.io/etcd/etcdmain.Main()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdmain/main.go:46 +0x64
main.main()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/main.go:28 +0x34

goroutine 69 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001c0de0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:173 +0x358
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:91 +0xa4

goroutine 106 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001c15a0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:173 +0x358
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:91 +0xa4

goroutine 109 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001c1740)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:173 +0x358
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/logutil/merge_logger.go:91 +0xa4

goroutine 96 [select]:
go.etcd.io/etcd/mvcc/backend.(*backend).run(0xc000257500)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/backend/backend.go:323 +0x144
created by go.etcd.io/etcd/mvcc/backend.newBackend
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/backend/backend.go:185 +0x484

goroutine 64 [syscall, 13968 minutes]:
os/signal.signal_recv(0x0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/runtime/sigqueue.go:147 +0x150
os/signal.loop()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/os/signal/signal_unix.go:23 +0x34
created by os/signal.init.0
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/os/signal/signal_unix.go:29 +0x54

goroutine 150 [select, 1752 minutes]:
go.etcd.io/etcd/wal.(*filePipeline).run(0xc00023a140)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/wal/file_pipeline.go:98 +0x128
created by go.etcd.io/etcd/wal.newFilePipeline
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/wal/file_pipeline.go:52 +0x154

goroutine 151 [select]:
go.etcd.io/etcd/raft.(*node).run(0xc00022e120)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/raft/node.go:337 +0x340
created by go.etcd.io/etcd/raft.StartNode
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/raft/node.go:226 +0x33c

goroutine 153 [select]:
go.etcd.io/etcd/lease.(*lessor).runLoop(0xc000234160)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/lease/lessor.go:590 +0x10c
created by go.etcd.io/etcd/lease.newLessor
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/lease/lessor.go:222 +0x2c8

goroutine 154 [select, 13968 minutes]:
go.etcd.io/etcd/pkg/schedule.(*fifo).run(0xc00022e5a0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/schedule/schedule.go:143 +0x28c
created by go.etcd.io/etcd/pkg/schedule.NewFIFOScheduler
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/schedule/schedule.go:70 +0x188

goroutine 163 [select]:
go.etcd.io/etcd/etcdserver.(*raftNode).start.func1(0xc00029cb30, 0xc0000020e0, 0x3b9aca00)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/raft.go:170 +0x12c
created by go.etcd.io/etcd/etcdserver.(*raftNode).start
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/raft.go:165 +0x68

goroutine 157 [select]:
go.etcd.io/etcd/mvcc.(*watchableStore).syncWatchersLoop(0xc000166be0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/watchable_store.go:227 +0x1d4
created by go.etcd.io/etcd/mvcc.newWatchableStore
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/watchable_store.go:91 +0x3f4

goroutine 158 [select, 13968 minutes]:
go.etcd.io/etcd/mvcc.(*watchableStore).syncVictimsLoop(0xc000166be0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/watchable_store.go:253 +0x170
created by go.etcd.io/etcd/mvcc.newWatchableStore
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/mvcc/watchable_store.go:92 +0x41c

goroutine 162 [select]:
go.etcd.io/etcd/pkg/schedule.(*fifo).run(0xc000144420)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/schedule/schedule.go:143 +0x28c
created by go.etcd.io/etcd/pkg/schedule.NewFIFOScheduler
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/schedule/schedule.go:70 +0x188

goroutine 134 [select]:
go.etcd.io/etcd/etcdserver.(*EtcdServer).run(0xc00029cb00)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:1036 +0x6a0
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).start
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:805 +0x7b4

goroutine 210 [select]:
go.etcd.io/etcd/pkg/fileutil.purgeFile.func1(0xc00013a090, 0x24, 0xc00022e2a0, 0xd47fa1, 0x7, 0x5, 0x0, 0x0, 0x6fc23ac00, 0xc0001a2060)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:80 +0x984
created by go.etcd.io/etcd/pkg/fileutil.purgeFile
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:34 +0xc0

goroutine 245 [select]:
go.etcd.io/etcd/etcdserver/api/v3rpc.monitorLeader.func1(0xc00029cb00, 0xc0005a23d0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/api/v3rpc/interceptor.go:247 +0xf0
created by go.etcd.io/etcd/etcdserver/api/v3rpc.monitorLeader
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/api/v3rpc/interceptor.go:242 +0xa4

goroutine 137 [select, 13968 minutes]:
go.etcd.io/etcd/etcdserver.(*EtcdServer).purgeFile(0xc00029cb00)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:819 +0x12c
go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc00029cb00, 0xc00022c220)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2632 +0x7c
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2630 +0x1f8

goroutine 138 [select]:
go.etcd.io/etcd/etcdserver.monitorFileDescriptor(0x0, 0xc0001a2120)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/metrics.go:215 +0x2cc
go.etcd.io/etcd/etcdserver.(*EtcdServer).Start.func3()
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:733 +0x5c
go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc00029cb00, 0xc00022c230)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2632 +0x7c
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2630 +0x1f8

goroutine 139 [select]:
go.etcd.io/etcd/etcdserver.(*EtcdServer).monitorVersions(0xc00029cb00)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2456 +0xd8
go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc00029cb00, 0xc00022c240)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2632 +0x7c
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2630 +0x1f8

goroutine 140 [runnable]:
sync.(*RWMutex).Unlock(0xc00029ce78)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/go-linux-mips64le-bootstrap/src/sync/rwmutex.go:118 +0x1c
go.etcd.io/etcd/etcdserver.(*EtcdServer).linearizableReadLoop(0xc00029cb00)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/v3_server.go:697 +0x24c
go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc00029cb00, 0xc00022c250)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2632 +0x7c
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/server.go:2630 +0x1f8

goroutine 142 [select]:
go.etcd.io/etcd/etcdserver/api/v3rpc.monitorLeader.func1(0xc00029cb00, 0xc00022c2c0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/api/v3rpc/interceptor.go:247 +0xf0
created by go.etcd.io/etcd/etcdserver/api/v3rpc.monitorLeader
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/etcdserver/api/v3rpc/interceptor.go:242 +0xa4

goroutine 211 [select]:
go.etcd.io/etcd/pkg/fileutil.purgeFile.func1(0xc00013a690, 0x24, 0xc00022e600, 0xd44cf5, 0x4, 0x5, 0x0, 0x0, 0x6fc23ac00, 0xc0001a2060)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:80 +0x984
created by go.etcd.io/etcd/pkg/fileutil.purgeFile
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:34 +0xc0

goroutine 212 [select]:
go.etcd.io/etcd/pkg/fileutil.purgeFile.func1(0xc00013a6c0, 0x23, 0xc00022e780, 0xd444fc, 0x3, 0x5, 0x0, 0x0, 0x6fc23ac00, 0xc0001a2060)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:80 +0x984
created by go.etcd.io/etcd/pkg/fileutil.purgeFile
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/pkg/fileutil/purge.go:34 +0xc0

goroutine 143 [chan receive, 12298 minutes]:
github.com/soheilhy/cmux.muxListener.Accept(...)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:229
google.golang.org/grpc.(*Server).Serve(0xc0002b4160, 0xf55320, 0xc00058f5e0, 0x0, 0x0)
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/go_install/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:586 +0x26c
created by go.etcd.io/etcd/embed.(*Etcd).servePeers
	/home/ljq/weilh/etcd_source/3.4.3/TongEtcdcode/src/etcd-3.4.3/embed/etcd.go:542 +0x28c

The log print information is as above, ETCD process core, please help to check the reason, or how I can solve this problem, thank you.

**Comment by spzala** [comment]
The discussion on `took too long to execute` might help you understand the issue and debugging options - https://github.com/etcd-io/etcd/issues/10860 
Closing this issue as dup but please open new issue/reopen with more details if needed. Thanks !
