### ISSUE TITLE
Release-3.2 Maintainership

### ISSUE THREAD

**Issue by retroflexer** [etcd-io/etcd#12767]
As we prepare for the release of 3.5, it becomes clear that release 3.2 will not be actively maintained by the community. However, since our organization still have customers on a release that requires the maintenance of release 3.2 at least for one more year our team will be owing the maintenance of release 3.2. While we do not intend to backport any features, we will be applying the security patches and issuing new releases, as needed.

Cc: @hexfusion, @ironcladlou, @marun 

I am creating this issue as a follow-up to the discussion on this topic during the etcd community meeting today (Mar 11, 2021) for general information to the members of the community.

**Comment by retroflexer** [comment]
We will be shooting for a release next week with #12638 and #12639.

**Comment by gyuho** [comment]
@retroflexer Yeah, we should continue to support 3.2 for critical bug fixes. Please work with @hexfusion to publish the release.
