### ISSUE TITLE
[Question] Reconfigure whole cluster while watching keys

### ISSUE THREAD

**Issue by berauser** [etcd-io/etcd#12778]
Hello everybody,

I have a question about runtime reconfiguration. Unfortunately I couldn't find anything about this in the documentation (or overlooked it).

I have a cluster in which I want to gradually move all nodes to new servers with new addresses. At the same time there are several services that are watching for changes on some keys. I don't want to restart these services during the reconfiguration.

During a test, I found out that the services stopped receiving updates after all of the initial nodes were replaced.

For example:
1. I have a cluster consisting of three nodes "A", "B" and "C".
2. Now I start a service that knows the three endpoints of these nodes and watches a key.
For example:
`etcdctl --endpoints http://A:2379,http://B:2379,http://C:2379 watch my_key`
3. Now I add a new etcd node "D" to the cluster and then remove the old etcd node "A".
4. Afterwards, I do the same with "B" and "C" ("B" replaced by "E" and "C" replaced by "F")
5. The cluster now only contains the nodes "D", "E" and "F". The initial nodes "A", "B" and "C" are no longer active.

At this point, the previously started service does not receive any changes from my_key.

Has anyone experienced this type of problem and a solution to it?
Is there any way I can avoid restarting the services?
Is it better to change the DNS entry to the new address?

Thanks in advance

**Comment by ptabor** [comment]
Are you using .WithRequireLeader: 

https://github.com/etcd-io/etcd/blob/e599f4a482836ea4bf5802b34a7ea2a660f44c98/tests/integration/clientv3/connectivity/network_partition_test.go#L247

Are the nodes A,B,C still 'alive' when your watch is unresponsive or the nodes are deleted. 

I would expect: 
  - without WithRequireLeader setting: watch to break the connection (so probably reconnect) when the target member is stopped
  -  with WithRequireLeader: watch to break the connection (so probably reconnect) as soon as watch is connected to a 'removed' node. 

If any of the above is not true, please provide a repro scenario in form of a test. 
https://github.com/etcd-io/etcd/blob/master/tests/integration/clientv3/connectivity/network_partition_test.go 
has a lot of simillar scenarios.
