### ISSUE TITLE
etcd v3.3.11 - log flooding with error rejected connection from "<<ip>>:<<random ports>>" (error "EOF", ServerName "")

### ISSUE THREAD

**Issue by TrushneshGawande** [etcd-io/etcd#12779]
Hi, 
we are deploying etcd v3.3.11 on Kubernetes cluster.
Once the service is up and running, the log starts flooding with mentioned message.
[etcd_error_log.txt](https://github.com/etcd-io/etcd/files/6148180/etcd_error_log.txt)

we have configured the ETCDCTL_ENDPOINTS with client port 2379 with all pods.
But in startup logs, we see below message,
W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag

Also, when logged in into one of the etcd pod and list the env variables, below are the values for the variables I think are relevant for the issue.
ETCDCTL_ENDPOINTS=<servicename>.<namespace>:2379
ETCD_LISTEN_METRICS_URLS=https://0.0.0.0:2381

**Comment by hexfusion** [comment]
Looks like an unauthenticated health check of some kind firing every 10s. Are you using a tcpSocket for readinessProbe? If yes then your spammer is the kubelet.

**Comment by TrushneshGawande** [comment]
@hexfusion yes we are using tcpSocket for readinessProbe.
          readinessProbe:
            tcpSocket:
              port: 2379
            initialDelaySeconds: 10

do we need to configure anything on kubelet or we should change the readinessProbe configuration?

**Comment by TrushneshGawande** [comment]
Hi @hexfusion 

It would be of great help if you could suggest on above.

Thanks!
