### ISSUE TITLE
Using client in v3.5.0 and etcd server with v3.4.14 tar, will it have any problem?

### ISSUE THREAD

**Issue by TinaTong-coder** [etcd-io/etcd#12788]
Hi,
I installed etcd server with v3.4.14 tar and write client code using v3.5.0(to get around the multiple issue that I have with v3.4.x, like can't go get the client library and incompatible with grpc v1.30). I have not started to test it with all my use cases, I want to pick your experience to see whether there are any serious hidden issues.
Thanks!

**Comment by ptabor** [comment]
The clients should be wire-compatible. 
As long as you don't use any new features of 3.5 (e.g. administrative change of cluster version), it should work well.
