### ISSUE TITLE
learner should proxy unhandled requests to full members rather than rejecting

### ISSUE THREAD

**Issue by anguslees** [etcd-io/etcd#12789]
I'm running v3.4.14, and trying to use the new 'learner' functionality (with Kubernetes).  This is probably a known limitation, but I didn't find an existing open bug with a few quick keyword searches, please close/merge if it's a duplicate.

I added a 'learner' member to my cluster as a preliminary step to replacing another node.  Part of my update included adding the (potential) new member to the apiserver --etcd-servers list.  Unfortunately, this resulted in frequent permanent gRPC errors to apiserver of the form "rpc not supported for learner" - and these etcd errors turn into k8s apiserver error responses.

This is unfortunate, because it introduces a difficult failure case between "member is not running, fails healthchecks, and won't be used by apiserver" and "member is completely functional".  It would make the replacement workflow _much_ easier if the learner member either A/ fails to respond to any etcd api requests (including basic connection/healthchecks) _xor_ B/ serves all requests correctly, presumably by forwarding any unhandled requests to the existing cluster/leader.

The current behaviour, where learners accept some requests but reject others, is difficult to handle - and I suggest undesirable.

https://github.com/etcd-io/etcd/blob/3d7aac948b1cde9de96f24363c8a790883d56c1d/server/etcdserver/api/v3rpc/interceptor.go#L51-L53

**Comment by gyuho** [comment]
@jingyih Can learner work the similar way as mirroring cluster https://github.com/etcd-io/etcd/blob/master/etcdctl/doc/mirror_maker.md but only reject writes (or writes will be forwarded anyways so should be ok)?
