### ISSUE TITLE
Release ETCD v3.4.15 not distribute ETCD binaries as tar.gz file

### ISSUE THREAD

**Issue by pierreilki** [etcd-io/etcd#12783]
Hello ETCD team ! :)

I just realize that there is no **tar.gz** archive for ECTD v3.4.15 binaries in https://github.com/etcd-io/etcd/releases/tag/v3.4.15. Only **tar** files are available.

In all older releases, ETCD was distributed with **tar.gz** instead just a **tar** file. Does it's just a mistake for ETCD v3.4.15, or do i have to plan using ETCD download links ending with ".tar" for all next ETCD releases > v1.4.14 ?

Thank for help

Have a nice day :)

**Comment by ptabor** [comment]
I would assume that lack of tar.gz files was unintented. 

The scripts in 'master' branch are producing .tar.gz files.
It's visible e.g. in experimental [v3.5.0-alpha.0](https://github.com/etcd-io/etcd/releases/tag/v3.5.0-alpha.0) release.

**Comment by Stephan-Walter** [comment]
Not only this, also the reported SHA256SUMS file container other hashes for the files. So right now I can't advise the usage of the new release, since it is not possible to distinguish between a valid tar archive and a compromised one.

```grep linux-a SHA256SUMS
3797ab06bebe218d5636fa0fb5d127adcace4ca4c1eed959d361dd5b4ba84c1d  etcd-v3.4.15-linux-amd64.tar.gz
```
vs
```
sha256sum etcd-v3.4.15-linux-amd64.tar
817addc542d5ecf94b779f09a51fc6fd1e64cd976030eb2db28d38ccf1626a52  etcd-v3.4.15-linux-amd64.tar
```

**Comment by hswong3i** [comment]
Also see #12734
