### ISSUE TITLE
Would someone update the release note link for upgrade?

### ISSUE THREAD

**Issue by pacoxu** [etcd-io/etcd#12794]
correct link maybe https://etcd.io/docs/latest/upgrades/upgrade_3_4/

@gyuho 

The release note here is 
![image](https://user-images.githubusercontent.com/2010320/112114597-35bfad00-8bf3-11eb-8fad-0347a71b7479.png)

wrong link: https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md

**Comment by spzala** [comment]
@pacoxu thanks for reporting. Fixed it, and working on fixing old releases. The broken links are because of the recent changes in the file structure.  /cc @gyuho
