### ISSUE TITLE
how to solve ambiguous import

### ISSUE THREAD

**Issue by gitsang** [etcd-io/etcd#12791]
```
****** imports
        github.com/coreos/etcd/clientv3 tested by
        github.com/coreos/etcd/clientv3.test imports
        github.com/coreos/etcd/integration imports
        github.com/soheilhy/cmux tested by
        github.com/soheilhy/cmux.test imports
        google.golang.org/grpc/examples/helloworld/helloworld: ambiguous import: found package google.golang.org/grpc/examples/helloworld/helloworld in multiple modules:
        google.golang.org/grpc v1.32.0 (/root/go/pkg/mod/google.golang.org/grpc@v1.26.0/examples/helloworld/helloworld)
        google.golang.org/grpc/examples v0.0.0-20200828165940-d8ef479ab79a (/root/go/pkg/mod/google.golang.org/grpc/examples@v0.0.0-20200828165940-d8ef479ab79a/helloworld/helloworld)
```

**Comment by ptabor** [comment]
Which version of cmux do you depend on ? 

To make it work, you need to depend on unstable one: 

github.com/soheilhy/cmux v0.1.5-0.20210205191134-5ec6847320e5

As cmux with https://github.com/soheilhy/cmux/pull/83 was not yet released.

@rmfitzpatrick

I'm not sure what happend in: 
https://github.com/soheilhy/cmux/pull/83/commits/995a22bd60b6a905778891efdae6b4a3806358e0

**Comment by gitsang** [comment]
Thanks, it work.

By the way, my project depend on cmux@v0.1.4

**Comment by soheilhy** [comment]
I just created the v0.1.5 release: https://github.com/soheilhy/cmux/releases/tag/v0.1.5
