### ISSUE TITLE
DCO check is missing for the etcd project

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/etcd#12799]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use. Ref.: cncf/foundation#130

During the audit, we've noticed that one or a few repositories of your project doesn't have the DCO check enabled. Please enable the DCO check for all repositories in your GitHub organization. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by spzala** [comment]
@nate-double-u ack, thanks for reporting.

**Comment by spzala** [comment]
@gyuho @xiang90 @ptabor thoughts here? We should be doing this. I can work on it if it sounds good. Thanks!

**Comment by ptabor** [comment]
I think we should configure DCO.

**Comment by jingyih** [comment]
SGTM

**Comment by wenjiaswe** [comment]
Sounds good to me too. Thanks Sahdev for volunteering to work on this!

**Comment by serathius** [comment]
friendly ping, any progress on this?
