### ISSUE TITLE
./test.sh报错：cannot use t (variable of type *testing.T) as TB value in argument to SkipTestIfShortMode: missing method TempDir

### ISSUE THREAD

**Issue by hecomlilong** [etcd-io/etcd#12806]
Please read https://etcd.io/docs/latest/reporting_bugs/
branch master
commit  8ee1dd9e23bce4d9770816edf5816b13767ac51d

'govet' started at Sat Mar 27 11:28:14 CST 2021
% (cd api && go vet ./...)
% (cd pkg && go vet ./...)
stderr: # go.etcd.io/etcd/pkg/v3/testutil
stderr: vet: testutil/leak_test.go:37:22: cannot use t (variable of type *testing.T) as TB value in argument to SkipTestIfShortMode: missing method TempDir

**Comment by ptabor** [comment]
Which version of go are you using?  
etcd-3.5.x-pre (masdter) requires 1.15+ (and likely will switch to 1.16+)
