### ISSUE TITLE
Why this kind of broken dependencies occur over and over again?

### ISSUE THREAD

**Issue by hitzhangjie** [etcd-io/etcd#12813]
../../go/pkg/mod/github.com/coreos/etcd@v3.3.25+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption

**Comment by ptabor** [comment]
Braking changes in grpc-1.30+. 
With grpc-1.30+ you must use >=etcd 3.5.0-alpha.0
