### ISSUE TITLE
does ETCD support HSTS?

### ISSUE THREAD

**Issue by TangqiFeng** [etcd-io/etcd#12822]
Hi,

I got a vulnerability when do tenable scan for ETCD - Plugin ID – 84502
it complaint about missing HSTS configuration.

I have checked the etcd [documentation](https://etcd.io/docs/v3.4/op-guide/security/), etcd.io documentation, I see example about client-server communication based on HTTPS but I don’t see the configuration of HSTS.

May I ask if the HSTS feature been supported?

/Tangqi

**Comment by spzala** [comment]
AFAIK, no - etcd allows http to reduce friction for users getting started with the database. A note is added to this doc - https://etcd.io/docs/next/op-guide/security/ Closing this issue. Thanks!
