### ISSUE TITLE
What is the correct version of grpc that the latest version of etcd(v3.5.0) depends on ？

### ISSUE THREAD

**Issue by Jun10ng** [etcd-io/etcd#12827]

**Comment by Jun10ng** [comment]
Hi etcd team
I want to know the correct version of grpc for some version of etcd 
v3.5
v3.4
v3.3
v3.2 -> grpc 1.26 (right?)
thanks!

**Comment by ptabor** [comment]
3.5 -> 1.36.1
3.4 -> 1.29.1

**Comment by Jun10ng** [comment]
cloesed
