### ISSUE TITLE
`proto.Size` takes up to 30% memory usage in excesively large range requests

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#12835]
It can be reproduced by listing 3000 kubernetes pods across all namespaces with 50 concurrency which takes up to 70% of 8GiB RAM

The following is the heap_alloc profiling data

![leader_heap_alloc](https://user-images.githubusercontent.com/54131596/113753809-6576b680-96c3-11eb-9dd3-e0e3f815fdbd.png)

Looks like `proto.Size` takes up to 30% memory usage in excesively large range requests
Personally I think it may reduce some cost on RAM and reduce the possibility of etcd out of memory.  

After making a custom patch to remove the `proto.Size` call in warn logging.  
```
func warnOfExpensiveReadOnlyRangeRequest(lg *zap.Logger, now time.Time, reqStringer fmt.Stringer, rangeResponse *pb.RangeResponse, err error) {
	var resp string
	if !isNil(rangeResponse) {
		// resp = fmt.Sprintf("range_response_count:%d size:%d", len(rangeResponse.Kvs), proto.Size(rangeResponse))
		resp = fmt.Sprintf("range_response_count:%d size:%s", len(rangeResponse.Kvs), "TBD")
	}
	warnOfExpensiveGenericRequest(lg, now, reqStringer, "read-only range ", resp, err)
}
```

We do see overall 7% memory usage drop, why it's not 30% theoretically is the  `UnMarshal` in MVCC layer claims more memory than last time.

<img width="1662" alt="Screen Shot 2021-04-06 at 10 48 22 AM" src="https://user-images.githubusercontent.com/54131596/113755925-b4255000-96c5-11eb-93f8-f1c55fc146ca.png"> 

![2021-04-04-i-09b638bcd740e26da-heap-alloc-leader1](https://user-images.githubusercontent.com/54131596/113754879-8be92180-96c4-11eb-8470-76c61b157b2a.png)

Can we get some insights from grpc/etcd experts to explain this behavior and what's the next step? @gyuho

**Comment by ptabor** [comment]
1. It's interesting that proto.Size() is performing full marshalling process to compute the size. Somehow similar to discussion we had in https://github.com/etcd-io/etcd/pull/12790 about XXX_sizecache in RAFT. 

2. In general the data should get paginated or streamed (see https://github.com/etcd-io/etcd/pull/12343) to reduce memory footprint on etcd. 

3. heap_alloc is tracking where the memory is allocated. If the memory is deallocated quickly, its not contributing to the overall heap usage. So turning off   response.Size() reduced some temporary 'buffer' memory but not the overall Range request payload that is dominating here.  I'm rather wonder what's the impact of 'Size()' call for the overall server throughput.

**Comment by ptabor** [comment]
BTW: Please verify what happens if you call `rangeResponse.Size()` instead.

The implementation seems to not require 'marshalling' to compute the size:
https://github.com/etcd-io/etcd/blob/7168409e6b89e26932f681956150ed7075f88ae8/api/etcdserverpb/etcdserver.pb.go#L337

**Comment by chaochn47** [comment]
Will come back to the thread after getting the results.

**Comment by gyuho** [comment]
Could be related https://github.com/etcd-io/etcd/issues/12842

**Comment by chaochn47** [comment]
Here is the before and after comparision regarding `proto.Size()` to `rangeResponse.Size()`

1. mem_used_percent reduced to half while CPU is roughly the same

<img width="1197" alt="Screen Shot 2021-04-16 at 1 55 52 AM" src="https://user-images.githubusercontent.com/54131596/115000136-52987a80-9e57-11eb-8ed4-32888be06120.png">

2. kube-apiserver list pods call pattern is similar

<img width="1286" alt="Screen Shot 2021-04-16 at 1 38 31 AM" src="https://user-images.githubusercontent.com/54131596/115000179-5f1cd300-9e57-11eb-8e44-d3d20e11c335.png">

**Comment by chaochn47** [comment]
However, I am not turn off the `madvise`, so the RSS mem_percent_used may not be accurate, will return back when get the result after `GODEBUG=madvdontneed=1`

ref: 
[1] https://github.com/golang/go/issues/42330
[2] https://github.com/golang/go/issues/33376

**Comment by ptabor** [comment]
But I think we are sufficiently confident that proto.Size() -> rangeResponse.Size() [and similar] is a good move to justify a PR. 
Thank you for making this experiments and proposing this improvement.
