### ISSUE TITLE
a lot of tmp file in snap dir  as a result of etcd restart

### ISSUE THREAD

**Issue by pervadepyy** [etcd-io/etcd#12837]
Hi，
we deployed three etcd node，one of etcd node abnormal then keep restarting per 5 minutes，then a lot of tmp file in snap dir as shown in the picture.
![image](https://user-images.githubusercontent.com/12962161/113838717-9dfcba00-97c1-11eb-9959-7932594b66d8.png)

we supposed this problem as a result of SaveDBFrom method not get remove tmp file when etcd restart.
![image](https://user-images.githubusercontent.com/12962161/113824325-3d19b580-97b2-11eb-9f08-2ff8fb002d79.png)

How can this be fixed and I feel like this might cause space insufficient of etcd data disk.

**Comment by ptabor** [comment]
Thank you for filling this issue. I've also spotted this problem and its mentioned here: 

https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#bookmark=id.mhhwhipsg70u

I think etcd should be expanded to cleanup these files when the server is starting, so probably here: 
```
https://github.com/etcd-io/etcd/blob/63c25bf3780b1e64adaaf636f69279fadb00e7e8/server/etcdserver/server.go#L328
```

A helper function in https://github.com/etcd-io/etcd/tree/master/client/pkg/fileutil might need to be added:

If anyone wants to contribute - please send a PR that deletes `tmp*` files my way.

**Comment by pyiyun** [comment]
Thanks for your attention, we send a PR that fix this issue: https://github.com/etcd-io/etcd/pull/12846
