### ISSUE TITLE
Increase release cadence frequency 

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#12847]
As discussed in the 8th of April community meeting and as per the https://github.com/etcd-io/etcd/issues/12840#issuecomment-815534131, we discussed we wanted for etcd to have more frequent releases. This issue is to collect the tasks needed to achieve that new workflow.

I will update the issue based on feedback in the comments below.

**Comment by ptabor** [comment]
[ ] We should have an automated workflow where new release / RC is matter of a decision, and not requires difficult environment setup. 
[ ] I think we should cleanup how we redact changelogs (as they are too long). But if the releases would be more frequently, the changelogs would be manageable as well.
