### ISSUE TITLE
Getting Error **resp.Kvs undefined (type *clientv3.DeleteResponse has no field or method Kvs**

### ISSUE THREAD

**Issue by pramodrj07** [etcd-io/etcd#12844]
func DeleteTravelEvent(u uuid.UUID) error {
	resp, err := cli.Delete(context.TODO(), u.String(), clientv3.WithPrefix())
	for _, ev := range resp.Kvs {
		fmt.Printf("%s : %s\n", ev.Key, ev.Value)
	}
}

Error when trying to build: resp.Kvs undefined (type *clientv3.DeleteResponse has no field or method Kvs

Could anyone let me know how to fix this?

**Comment by tpepper** [comment]
As per eg:https://pkg.go.dev/github.com/etcd-io/etcd@v3.3.25+incompatible/client#Response the
