### ISSUE TITLE
start etcd grpc-proxy with client cert, which contain  the CN.

### ISSUE THREAD

**Issue by ABlueCy** [etcd-io/etcd#12865]
Please read https://etcd.io/docs/latest/reporting_bugs/

**env:**
etcd Version: 3.4.15
Git SHA: aa7126864
Go Version: go1.12.17
Go OS/Arch: linux/amd64

**Operations:**
start etcd grpc-proxy with client cert param, which contains  the CN(common name).
the certificate is generated by cfssl, (https://pkg.cfssl.org/R1.2/cfssl_linux-amd64)
the start cmd:
 ETCDCTL_API=3; ./etcd grpc-proxy start   --endpoints https://11.80.28.56:2379,https://11.80.29.112:2379,https://11.80.27.239:2379   --
metrics-addr https://0.0.0.0:4443   --advertise-client-url  11.80.10.207:23790   --listen-addr 11.80.10.207:23790   --key /etcd/ssl/client-key.pem   --key-file /etcd
/ssl/proxy-server-key.pem   --cert /etcd/ssl/client.pem   --cert-file /etcd/ssl/proxy-server.pem   --cacert /etcd/ssl/ca.pem   --trusted-ca-file /etcd/ssl/ca.pem

**error:**
{"level":"info","ts":"2021-04-16T09:39:00.922+0800","caller":"etcdmain/grpc_proxy.go:199","msg":"gRPC proxy server TLS","tls-info":"cert = /etcd/ssl/proxy-server.pem, key = /etcd/ssl/proxy-server-key.pem, trusted-ca = /etcd/ssl/ca.pem, client-cert-auth = false, crl-file = "}
{"level":"info","ts":"2021-04-16T09:39:00.922+0800","caller":"etcdmain/grpc_proxy.go:374","msg":"listening for gRPC proxy client requests","address":"11.80.10.207:23790"}
cert has non empty Common Name (etcd): /etcd/ssl/proxy-client.pem

**my confusion：**
I checked the etcd source code about the etcd grpc-proxy startting. the source code forbids the client certificate with CN(common name).
Firstly, why is there forbidding the the client certificate with CN(common name)?

Secondly, while I changed the etcd program to allow starting the etcd grpc-proxy with client certificate, containing the CN(common name), all of etcd servers, grpc-proxy and client seemed to work correctly. So, if it allow the proxy with client certificate containing the CN, is there any issues?

**Comment by ABlueCy** [comment]
@ptabor

**Comment by ABlueCy** [comment]
@ptabor . Hi, ptabor, I saw your commit #12273.  Would you mind to answer my above questions and explain why ? THX~

**Comment by ptabor** [comment]
Please see the comment to this CL: 
https://github.com/etcd-io/etcd/pull/12273/commits/2d0ce9de3d875f9cd2227cc6c67aad9ec407c45f

I assume (because its pre-me code) that the goal is to enforce etcd-server to see end-user credentials instead of grpc-proxy's CN identity.
