### ISSUE TITLE
cannot find module providing package go.etcd.io/etcd/api/mvccpb

### ISSUE THREAD

**Issue by fwhezfwhez** [etcd-io/etcd#12869]
Is there any solutions to stop using ""go.etcd.io/etcd/api/mvccpb""? 

As soon as I start a new app project, a same error will report:

```
cannot load go.etcd.io/etcd/api/mvccpb: cannot find module providing package go.etcd.io/etcd/api/mvccpb
```

No more disgusting things than this.

A project with etcd involved is never runnable on its first time attempt.

I've tried all my old past solutions but do not work.

Please, is it so hard to run with etcd go client using default gomodule downloads?

I bet this is your way to make all users impressed of etcd.
It really works.

**Comment by ptabor** [comment]
3.5 will solve that. 

Please try with alpha: 

```
% go get go.etcd.io/etcd/v3
go: downloading go.etcd.io/etcd/v3 v3.5.0-alpha.0
```

**Comment by skypexu** [comment]
go: downloading github.com/golang/protobuf v1.5.3
go: downloading google.golang.org/protobuf v1.31.0
go: downloading golang.org/x/net v0.12.0
go: downloading golang.org/x/sys v0.10.0
go: extracting github.com/golang/protobuf v1.5.3
go: extracting google.golang.org/protobuf v1.31.0
go: extracting golang.org/x/sys v0.10.0
go: extracting golang.org/x/net v0.12.0
go: downloading golang.org/x/text v0.11.0
go: extracting google.golang.org/genproto v0.0.0-20230711160842-782d3b101e98
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230711160842-782d3b101e98
go: extracting google.golang.org/genproto/googleapis/rpc v0.0.0-20230711160842-782d3b101e98
go: extracting golang.org/x/text v0.11.0
build command-line-arguments: cannot load go.etcd.io/etcd/mvcc/mvccpb: cannot find module providing package go.etcd.io/etcd/mvcc/mvccpb
---
I still get this.
