### ISSUE TITLE
Bad url on "check datascale" command

### ISSUE THREAD

**Issue by ssbostan** [etcd-io/etcd#12860]
When "check datascale" command is executed, Requested metrics URL is not parsed correctly.

Client version:
etcdctl version: 3.4.15
API version: 3.4

```sh
ETCDCTL_API=3 ./etcdctl --cacert etcd-ca.crt --cert etcd-admin.crt --key etcd-admin.key --endpoints https://192.168.10.56:2379,https://192.168.10.55:2379,https://192.168.10.57:2379 check datascale
```

fetch error: Get http://https//192.168.10.56:2379/metrics: dial tcp: lookup https on 8.26.56.26:53: no such host
FAIL: Could not read process_resident_memory_bytes before the put operations.

**Comment by lilic** [comment]
Yes can confirm seems like it's a valid bug when you use secure endpoints, it seems like there is a check that always prefixes the query to the metrics endpoint with `http://`. Are you interested in submitting the fix for this?

**Comment by ssbostan** [comment]
Yes of course, Welcome to fix it. I'm not familiar with etcd developing rules.

**Comment by lilic** [comment]
@ssbostan I am sorry, not sure I understood, do you want me to fix it or are you interested in learning about the etcd the dev rules so you can fix it? :)

**Comment by ssbostan** [comment]
I fixed it and the pull request submitted.
Thanks for your attention Lili.

**Comment by lilic** [comment]
I believe you can close this one now that your PR was merged, thank you! 🎉
