### ISSUE TITLE
Fetch all the keys of a specific path

### ISSUE THREAD

**Issue by pramodrj07** [etcd-io/etcd#12879]
I am trying to PUT a value with an additional path prefixed to the key.
Example
`_, err := client.Put(context.TODO(), "/event/"+newuuidString.String(), string(zzzz))`

I am able to retrieve all the keys using 

`resp, err := client.Get(context.TODO(), "\x00", clientv3.WithFromKey())`

I would like to retrieve only the specific keys which are in the path "/event/" and not all the keys in etcd.

Is there a way to do it from client v3?

**Comment by spzala** [comment]
@pramodrj07 I guess this is what you are looking for `resp, err := cli.Get(ctx, "/event/", clientv3.WithPrefix(), clientv3.WithKeysOnly())`

**Comment by pramodrj07** [comment]
@spzala - This is exactly what I want. Thanks a lot

**Comment by spzala** [comment]
@pramodrj07 - cool, you are welcome! Closing the issue :)
