### ISSUE TITLE
Command to get responses in JSON format

### ISSUE THREAD

**Issue by pramodrj07** [etcd-io/etcd#12877]
I am currently using the below command to get a response of all keys/values in my local etcd instance
`resp, err := cli.Get(context.TODO(), "\x00", clientv3.WithFromKey())`
I would like to know if there is any way to get the response in JSON format directly?

**Comment by davidlanouette** [comment]
This appears to be a duplicate of #12591

That one is stale, but does have a PR that looks like it's waiting for some love.

**Comment by xiang90** [comment]
the response you get is a proto struct. It should have a toJSON func attached. Or you can just use Go std json lib to do that.
