### ISSUE TITLE
Remove container builds for 3.5 release

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#12872]
Our [release script](https://github.com/etcd-io/etcd/blob/master/scripts/release) depends on docker for release image builds, which makes release automation hard, due to docker push dependency on 3rd party docker registry. This includes quay and gcr, which currently requires manual login with user name and password + GCP credential. Now, quay required red hat account.

https://github.com/etcd-io/etcd/blob/f3c518025e284d3d070a63d5969c69176f247b33/scripts/release#L225-L229

To simplify our release process, I am proposing to drop all docker registry dependency starting from etcd 3.5 release.

Ideally, etcd upstream just provides binaries, and let downstream community build container images of their own preference.

Reference
- https://github.com/kubernetes/release/issues/1887

/cc @wenjiaswe

**Comment by gyuho** [comment]
This is just a proposal. Please feel free to provide feedback and raise any concerns you may have.

Please note that we are not removing the existing container images.

**Comment by gyuho** [comment]
To use automation tools like https://goreleaser.com, we may want to remove `gsutil` dependency as well

https://github.com/etcd-io/etcd/blob/f3c518025e284d3d070a63d5969c69176f247b33/scripts/release#L211-L216

**Comment by lilic** [comment]
I agree that building images should be down to the user! 💯  But by now even I am sadly used to a project providing at least one image build and I fear this will cause a lot of users to demand them.

If I can propose maybe to keep gcr image registry only if quay requires red hat account and that complicates things? And to automate building images completely. This can be achieved by either something like a preexisting action https://github.com/marketplace/actions/push-to-gcr-github-action for pushing images on tags or as described here https://cloud.google.com/community/tutorials/cicd-cloud-run-github-actions? This would only require a `service account key` from what I can tell and can be configured to be run on tag creation only.

**Comment by ptabor** [comment]
I don't have strong opinion about the images releases. Intuitively I wouldn't break customer's expectations about the location of images, but rather look for a process that makes population of them easy.

I think we should definitely decouple release process into independent phases: 

A) git-release

1. tag locally repository
2. dry run all tests, build tar-balls, create images (to make sure all the processes work), but do_not_push_them (so no creds needed)
3. push the git tag changes to upstream repository. 

B)  binaries release:
  1. For given git 'hash/tag' -> build tarballs, zip 
  2. (optionally) Upload them using:  https://github.com/cli/cli

C) images release: 
  1. For given git 'hash/tag' -> build images 
  2. (optionally) Upload them repos

B & C:  seems to be a common problem, so there should trusted be systems good at it. 
If there are no, it seems pretty easy to have a VM that does the work.

**Comment by gyuho** [comment]
> If I can propose maybe to keep gcr image registry only if quay requires red hat account and that complicates things

Yes, I think requirement for 3rd party log-in in the release process slows us down in the long term. Right now, only a "few" maintainers have access to the password, whereas we want to be more inclusive to other contributors to easily publish a release.

> https://github.com/marketplace/actions/push-to-gcr-github-action

Yes, as long as it doesn't rely on an individual release manager to manually type password, this is so much better :)

> I think we should definitely decouple release process into independent phases:

Sounds great!

**Comment by sagikazarmark** [comment]
How about publishing images to GitHub Container Registry? Maybe automated using GitHub Actions? That would only requires a GitHub PAT (for now, but later the token used by GHA should be able to push images on its own) placed in the GitHub secret store.

There is a great GitHub action for automatically building and pushing images: https://github.com/marketplace/actions/build-and-push-docker-images
