### ISSUE TITLE
Missing proc_* metrics

### ISSUE THREAD

**Issue by wpedrak** [etcd-io/etcd#12899]
etcd Version: 3.5
Go Version: go1.16
OS/Arch: darwin/amd64

I'm not able to see any `proc_*` metrics when building etcd out of master branch.

### Repro steps
```
git clone https://github.com/etcd-io/etcd.git etcd-tmp
cd etcd-tmp
./build.sh
./bin/etcd
```
and from different terminal:
```
curl localhost:2379/metrics | grep process
```

### Expected behaviour
Bunch of process_* metrics as specified in https://etcd.io/docs/next/metrics/#prometheus-supplied-metrics

### Actual behaviour
No such metrics

---

As a follow up:
```
./bin/etcdctl check datascale
```
is throwing
> could not find: process_resident_memory_bytes
    FAIL: Could not read process_resident_memory_bytes before the put operations.

which in fact is how I found out that those are missing.

**Comment by lilic** [comment]
Those metrics come via promethus client_golang and on those metrics exist on windows and Linux but not for mac/darwin. The process_resident_memory_bytes are based on the `/proc/PID/stat` file. If you deploy etcd on Linux you should be able to see them.

**Comment by wpedrak** [comment]
I see. Indeed, those are present on linux. I guess that nothing we can do here, so closing

Thanks a lot @lilic

**Comment by hexfusion** [comment]
do we want to adjust the client to be smarter about Arch vs throw error?

**Comment by lilic** [comment]
Yes I believe we could do that. But I wonder if it could be solved in client_golang @beorn7 do you by any chance know if client_golang will ever support darwin for the `process_` metrics?

**Comment by hexfusion** [comment]
interesting, I prefer the newest Prometheus UI, it does autocmplete really nicely and has nice suggestions.

**Comment by hexfusion** [comment]
https://github.com/prometheus/node_exporter/issues/1965

**Comment by hexfusion** [comment]
or operator seems to be a possible solution if there is another mapping.

**Comment by lilic** [comment]
Nice, thank you @beorn7! I will put it on my list for a hack day at some point. :)
