### ISSUE TITLE
[Question] Does the  --initial-cluster arg must be the same in each node?

### ISSUE THREAD

**Issue by lianghao208** [etcd-io/etcd#12909]
I have a Kubernetes cluster with 3 master using etcd v3.3.12.
Each etcd has the same  `--initial-cluster` arg configured in manifest file.
```
- --initial-cluster=node1=ip1,node2=ip2,node3=ip3
```
Now I join 3 master nodes into the cluster( node4, node5, node6), which has a different   `--initial-cluster` arg configured in manifest file.
```
- --initial-cluster=node1=ip1,node2=ip2,node3=ip3,node4=ip4,node5=ip5,node6=ip6
```
Do I need to modify the 3 old masters' etcd  `--initial-cluster` arg into this?
```
- --initial-cluster=node1=ip1,node2=ip2,node3=ip3,node4=ip4,node5=ip5,node6=ip6
```
What's the impact if I do not modify those file to keep the `--initial-cluster` the same?

**Comment by xiang90** [comment]
yes. it needs to be the same to avoid potential inconsistency on initial configuration. but once the cluster is bootstrapped, the initial cluster will take no effect.
