### ISSUE TITLE
3.5 decision making for alpha/beta/experimental feature stability

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#12905]
We either need promote the stability of these features or keep it as it is with changes to CHANGELOG:
- [gRPC gateway](https://github.com/grpc-ecosystem/grpc-gateway) only supports [`/v3`](TODO) endpoint.
- Change [`etcd --experimental-enable-v2v3`](TODO) flag to `etcd --enable-v2v3`; v2 storage emulation is now stable.
- [`etcd --enable-v2v3`](TODO) flag is now stable.

**Comment by ptabor** [comment]
Do we have significant user's of V2 API ? 

IMHO: Ideally in 3.5 should be the last release that exposes V2 apis at all. 
  In worst case the only way to use V2 API starting in 3.6 is through v2->v3 bridge.

**Comment by hexfusion** [comment]
> Do we have active user's of V2 APIs that cannot stay on 3.5 ?

Speaking for Red Hat all supported v2 is still isolated to release-3.2

My vote is we take a  harder line approach towards 1. The cost of support for this API has taxed maintainers (thanks Piotr). If folks would like to defend option 2 I think we would like to see that need directly from the community. If we send out a notice through typical channels and provide time for community input I guess that input can drive the decision. From that input if organizations or users feel strongly that support should continue. Then perhaps they can own part/all of this maintenance.

Thanks for bringing up this subject.

**Comment by gyuho** [comment]
> 3.5 is the last release that exposes V2 apis at all.

https://github.com/etcd-io/etcd/blob/c46e96d519a38947188243c859e71ddd733e5065/server/etcdmain/help.go#L125-L126

https://github.com/etcd-io/etcd/blob/release-3.4/etcdmain/help.go#L119-L120

I don't think we need remove v2 code until etcd v4. It's still used internally for health checks. We already disabled v2 API by default in v3.4. While we mark `v2v3` API stable, we can mark `--enable-v2` to something like `enable-legacy-v2`>

**Comment by ptabor** [comment]
@gyuho: Do I understand correctly that you are postulating not decommissioning v2 store (backend) code in v3 completely ? 

I find this storev2 code:
  - significant source of complexity (partial redundancy of data between stores)
  - cost during bootstrap (scanning of both -snap.db files and WAL log to find matching entries). 
  - gotches:   `etcdctl snapshot`, `etcdctl restore` silently ignoring storeV2 content. 

I don't think we have engineering capacity (and ideas for technical value added) to plan for V4 in foreseeable future. 

As stated in https://github.com/etcd-io/etcd/issues/12913,   3.7 would be the release without v2store backend. 

v2v3 needs to have capability to be mounted as 'root' if we need a drop-in-replacement to preserve the API.

**Comment by gyuho** [comment]
@ptabor As we discussed during the meeting, let's keep `etcd --experimental-enable-v2v3` as experimental and deprecate for 3.7.

**Comment by ptabor** [comment]
The code changes backed by this decision were incorporated in: 
  https://github.com/etcd-io/etcd/pull/12940

**Comment by gyuho** [comment]
@hexfusion Can you help us with the grpc-gateway v3 promotion?
