### ISSUE TITLE
raft/raft.go: is it stable enough for removing  these panic statements?

### ISSUE THREAD

**Issue by MakDon** [etcd-io/etcd#12912]
I found some [TODOs](https://github.com/etcd-io/etcd/blob/master/raft/raft.go#L690) in raft/raft.go made in 2014.     
For example: 
```Golang
// TODO(xiangli) remove the panic when the raft implementation is stable
if r.state == StateLeader {
	panic("invalid transition [leader -> candidate]")
}
```
is it stable enough to remove these TODOs and panic statement?

**Comment by hexfusion** [comment]
I have never seen that panic in the wild, saying that this would be a terrible panic worthy failure. What do we gain by removal?

**Comment by MakDon** [comment]
> I have never seen that panic in the wild, saying that this would be a terrible panic worthy failure. What do we gain by removal?

Is it a good idea that keep the panic statement but remove these TODOs?

**Comment by xiang90** [comment]
> Is it a good idea that keep the panic statement but remove these TODOs?

Correct. Probably remove the TODOs.
