### ISSUE TITLE
How to create CertFile KeyFile and TrustedCAFile?

### ISSUE THREAD

**Issue by XueCangQiuYe** [etcd-io/etcd#12926]
Hello, sorry to bother you.
I take over a serivce from my ex-colleague.
This service is used to read data from etcd and it's based on etcd APIv2.
```shell
/var/lib/etcd # etcdctl --version

etcdctl version: 3.2.22

API version: 2
```
Now, I need to update it to adapt new environment.
```shell
[root@matrix ~]# etcdctl --version

etcdctl version: 3.3.11

API version: 2
```
But, It need some auth file like CertFile KeyFile and TrustedCAFile that cann't find in my OS.
```go
tlsInfo := &transport.TLSInfo{
	KeyFile:        "../../tests/fixtures/server.key.insecure",
	CertFile:       "../../tests/fixtures/server.crt",
	TrustedCAFile:  "../../tests/fixtures/ca.crt",
}
```
I have seen the Doc, But I cann't find the method to create those file.
So, please to help me to create CertFile KeyFile and TrustedCAFile.

OS : CentOS7.6

**Comment by ptabor** [comment]
Please see how the test environment is generating the certificates: Please see file: tests/fixtures/gencerts.sh

**Comment by ptabor** [comment]
BTW: v2 API is being deprecated and will be gone as etcd-3.6. So please migrate the service to V3 API.
