### ISSUE TITLE
Instructions from releases page need copyedits due to broken links, etc.

### ISSUE THREAD

**Issue by chalin** [etcd-io/etcd#12923]
Here is an excerpt from the (v3.4) [Download and build][] page:

> ## Download the pre-built binary
>
> The easiest way to get etcd is to use one of the pre-built release binaries which are available for OSX, Linux, Windows, appc, and Docker. Instructions for using these binaries are on the [GitHub releases page][etcd releases].

The reader is told to get instructions for using pre-built binaries from the [etcd releases][] page, but those instructions, e.g., for [v3.2.32][], contain at least two broken links, and otherwise would be in need of copyedits.

Are the release notes taken from a template? If so, where is this template and how can suggested changes be submitted for it?

Also, rather than repeat detailed "installation and test" instructions for each release, wouldn't it make more sense to have such instructions under etcd.io (under the appropriate docs version), and simply direct users to the etcd.io docs?

Related:
- v3.5 release - #12970

cc @nate-double-u 

[Download and build]: https://etcd.io/docs/v3.4/dl-build/
[etcd releases]: https://github.com/etcd-io/etcd/releases/
[v3.2.32]: https://github.com/etcd-io/etcd/releases/tag/v3.2.32

**Comment by chalin** [comment]
@hexfusion, I don't know if you're using a template for the release notes, but if so, could you use the following text instead?

## Updated text to accompany [releases](https://github.com/etcd-io/etcd/releases), with updated links

For guidance with etcd installation and operation, see the following pages:

- [Supported platforms][]
- [Download and build][]
- [Operations guide][]
- [play.etcd.io][]

**IMPORTANT**: If you're upgrading, read the relevant [upgrade guide][] since there may be breaking changes. For a complete list of changes, see the [CHANGELOG][].

[CHANGELOG]: https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md
[Download and build]: https://etcd.io/docs/next/dl-build/
[play.etcd.io]: http://play.etcd.io
[Operations guide]: https://etcd.io/docs/next/op-guide/
[Supported platforms]: https://etcd.io/docs/next/op-guide/supported-platform/
[upgrade guide]: https://etcd.io/docs/next/upgrades/

**Comment by chalin** [comment]
Here are the link definitions for the text above:

    [CHANGELOG]: https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md 
    [Download and build]: https://etcd.io/docs/next/dl-build/
    [Operations guide]: https://etcd.io/docs/next/op-guide/
    [play.etcd.io]: http://play.etcd.io
    [Supported platforms]: https://etcd.io/docs/next/op-guide/supported-platform/
    [upgrade guide]: https://etcd.io/docs/next/upgrades/

**NOTE**: the change of branch name from `master` to `main` in the `CHANGELOG` URL.

/cc @gyuho

**Comment by chalin** [comment]
#### For sake of comparison, here's the original release text:

Please check out [CHANGELOG][] for a full list of changes. And make sure to read [upgrade guide](https://github.com/etcd-io/website/blob/main/content/en/docs/next/upgrades/upgrade_3_5.md) before upgrading etcd (there may be breaking changes).

For installation guides, please check out [play.etcd.io][] and [operating etcd](https://github.com/etcd-io/etcd/tree/master/Documentation#operating-etcd-clusters). Latest support status for common architectures and operating systems can be found at [supported platforms](https://github.com/etcd-io/website/blob/main/content/en/docs/next/op-guide/supported-platform.md).

[CHANGELOG]: https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md
[Download and build]: https://etcd.io/docs/next/dl-build/
[play.etcd.io]: http://play.etcd.io
[Operations guide]: https://etcd.io/docs/next/op-guide/
[Supported platforms]: https://etcd.io/docs/next/op-guide/supported-platform/
[upgrade guide]: https://etcd.io/docs/next/upgrades/

**Comment by hexfusion** [comment]
Thanks for doing this. Few questions/ideas.

- can we update the release details via GitHub API?
- would it make sense to create a template for each release branch and incorporate into release pipeline tooling?

**Comment by ptabor** [comment]
I used to update push artifacts using github cli: 

```
#!/bin/bash

gh release create -d -p v3.5.0-alpha.0 -F changelog.md ../etcd-release-3.5.0-alpha.0/etcd/release/*.zip ../etcd-release-3.5.0-alpha.0/etcd/release/*.gz
```

**Comment by chalin** [comment]
Thanks @ptabor! Is `changelog.md` your own local file? If so, can you attach a copy to this issue? I'll use it as a base for an updated template -- which I'll submit as a PR soon if y'all agree!

**Comment by ptabor** [comment]
It was my local, but it was completely dummy. I post-edited the release notes later and used the commands only to avoid sending tar-balls between  VM -> workstation -> github and clicking this manually. If we could have generator of the changelog.md it would be awesome.

**Comment by gyuho** [comment]
> That certainly makes sense to me. I'd be glad to contribute such template(s) if we can find them a home.
Thoughts @gyuho @ptabor? I'll submit something and we can gather feedback from that PR.

There's no automation. I just manually string replace version names and keep using the same text from previous releases. Feel free to make changes.

**Comment by chalin** [comment]
Thanks all for your feedback so far.

I noticed that there's a **[Release guide][]** - from `etcd.io/docs/next/dev-internal/release/`. A few questions about this guide:

- Is [Release guide][] actively being used?
- Is it considered up-to-date?
  - If not, who can update it?
- It probably makes more sense to add a template for release notes to the [Release guide][], rather than as a separate `.md` file under etcd (as I had proposed in #13009). Thoughts?

[Release guide]: https://etcd.io/docs/next/dev-internal/release/

**Comment by chalin** [comment]
Let's use https://github.com/etcd-io/website/issues/298 for any discussions concerning the Release guide, thanks.
