### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#12921]
Etcd development/PR merging is bottle necked by time it takes to test changes. Travis CI free trier allows only 5 workers which makes the feedback loop take time in order of 1-3 hours ([recent pull requests](https://travis-ci.com/github/etcd-io/etcd/pull_requests)) 

CNCF projects like etcd are encouraged to use Git Hub Actions and increasing number of workers is not possible util etcd will migrate from Travis CI to GitHub actions. With that I propose a multi stage plan to execute this migration:

1. Run unit tests using GitHub Actions configured to allow failures
2. When enough confidence is built, require unit test in GitHub Actions to pass
3. Request increase of GitHub Actions workers
4. Remove Travis CI testing go1.16.3

Remaining Travis Config will test that are allowed to fail:
* Go tip - not supported ([context](https://github.com/actions/setup-go/issues/21))
* coverage - not stable
    
This is my first proposal to etcd repo, please let me know if this plan makes sense.
I'm happy to contribute this.

**Comment by xiang90** [comment]
@serathius Sounds like a good plan. Let us get started with the unit test, and if things go well we will move everything (probably including the semaphoreci) there. 

I am not sure how easy to get logging from Github actions runs. That is one of the reasons we still keep semaphoreci.

**Comment by serathius** [comment]
Stage one is done. We have a new "Unit tests" action added that runs on every git push. 
Link to dashboard where we can monitor results https://github.com/etcd-io/etcd/actions/workflows/unit-tests.yaml

**Comment by serathius** [comment]
Stage two was done and we see great improvement in CI latency **from 2h to 20 minutes**. Coverage is still being run by Travis and taking 50 minutes, but should not be considered blocking for merging PRs.

@xiang90 Could you describe what is the blocker from migrating SemaphoreCI to GitHub actions. What kind of logs we could be missing?

**Comment by xiang90** [comment]
@serathius If there is a way to download the full log from failed tests from Github Actions, then it should be fine. Some hosted CI systems truncate logs and provide no easy way to search around.

**Comment by xiang90** [comment]
@serathius lgtm. thanks for checking!

**Comment by serathius** [comment]
With latency of CI execution vastly improved and all migrated to GitHub actions goal of this issue was achieved. 

There are still leftovers from migration that should be tackled in future:
* Testing Golang TIP - still uses Travis
* Coverage - needs fixing, still uses Travis
* Semaphore CI - Disabled on main branch, but still enabled to run on other branches.
