### ISSUE TITLE
Questions about "took too long" in the troubleshooting specification

### ISSUE THREAD

**Issue by mengshi02** [etcd-io/etcd#12939]
The occurrence of "took too long" exceeding the quorum leads to frequent leader node elections. The cluster is restored by adjusting the heartbeatTimeout and electionTimeout parameters. I would like to ask whether this downgrade measure is a formal practice, and is there a better way?

**Comment by spzala** [comment]
A related doc and best practices -
Handling took too long - https://etcd.io/docs/v3.4/faq/#what-does-the-etcd-warning-apply-entries-took-too-long-mean 
Heartbeat interval and election timeout settings - https://etcd.io/docs/next/tuning/
Hope this helps. Closing the issue but feel free to reopen if needed. Thanks!
