### ISSUE TITLE
Rename master branch to main/mainline

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#12949]
`etcd-io/website` is already changing to `main` branch https://github.com/etcd-io/website/issues/149. We should make the same change. I prefer `mainline` but also open to `main` :)

Please comment for feedback.

> In conformance to the inclusive naming initiatives of various organizations (including LF/CNCF, GH), `master` should be renamed to `main`. Note that it's been safe to do this for a while now given that GitHub handles the necessary redirects. For details, see:

- [github/renaming][]
- [Links to deleted branches now redirect to the default branch][]

> Examples of repos across LF/CNCF that have renamed their default branches include: [grpc.io](https://github.com/grpc/grpc.io) and [grpc-community](https://github.com/grpc/grpc-community).

[github/renaming]: https://github.com/github/renaming
[Links to deleted branches now redirect to the default branch]: https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch

/cc @chalin @nate-double-u @ptabor @xiang90

**Comment by xiang90** [comment]
I prefer `main` so that we can stay consistent with other projects. :)

**Comment by spzala** [comment]
> I prefer `main` so that we can stay consistent with other projects. :)

Sounds great to me too!

**Comment by chalin** [comment]
FYI, the website's default branch has been renamed to `main` (https://github.com/etcd-io/website/issues/149).

**Comment by gyuho** [comment]
The master branch is now renamed to `main`.
