### ISSUE TITLE
Cleanup docker makefile rules and gcr.io/etcd-development images

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#12955]
With completion of https://github.com/etcd-io/etcd/issues/12921 all CI tests were migrated out of docker. With that we can look into cleaning up not used rules in makefile. Creating this issue to collect feedback and decide which commands should be removed

Goal: Reduce maintenance cost and simplify onboarding of contributions by removing unused makefile tooling.

Targets that are not invoked in codebase or automation will be marked for removal. Feel free to point out any target that is manually, we should discuss automating/documenting them.

Targets that can be imminently removed
* docker-clean - Wrapper for docker commands
* docker-start  - Wrapper for docker commands
* docker-kill  - Wrapper for docker commands
* docker-remove  - Wrapper for docker commands
* build-docker-functional - Not needed after migrating Travis test to Github Actions
* push-docker-functional  - Not needed after migrating Travis test to Github Actions
* pull-docker-functional - Not needed after migrating Travis test to Github Actions
* compile-with-docker-test - Not used 
* compile-setup-gopath-with-docker-test - Not used

Targets that can be removed after we stop depending on docker for tests.
* docker-test - Used by Semaphore CI
* docker-test-coverage - Used by Travis
* build-docker-test - Needed to build docker test image 
* push-docker-test - Needed to build docker test image
* pull-docker-test - Needed to build docker test image
* build-docker-release-master - Used for releases? (not docummented)
* push-docker-release-master - Used for releases? (not docummented)

Targets for manual tests - move to sub makefile.
* build-docker-static-ip-test
* push-docker-static-ip-test
* pull-docker-static-ip-test
* docker-static-ip-test-certs-run
* docker-static-ip-test-certs-metrics-proxy-run
* build-docker-dns-test 
* build-docker-dns-test 
* push-docker-dns-test 
* pull-docker-dns-test
* docker-dns-test-insecure-run
* docker-dns-test-certs-run
* docker-dns-test-certs-gateway-run
* docker-dns-test-certs-wildcard-run
* docker-dns-test-certs-common-name-auth-run
* docker-dns-test-certs-common-name-multi-run
* docker-dns-test-certs-san-dns-run
* build-docker-dns-srv-test
* push-docker-dns-srv-test
* pull-docker-dns-srv-test
* docker-dns-srv-test-certs-run
* docker-dns-srv-test-certs-gateway-run
* docker-dns-srv-test-certs-wildcard-run

**Comment by gyuho** [comment]
> build-docker-dns-test - Not used

These are used for manual SRV testing. If we need cleanup, can we use all the unused one to a separate Makefile?

**Comment by serathius** [comment]
@gyuho I think we should have a plan on what to do with manual tests. Could we maybe automate them?
