### ISSUE TITLE
Question abount etcdctl endpoint status

### ISSUE THREAD

**Issue by horizonzy** [etcd-io/etcd#12961]
```
 $> etcdctl endpoint status
127.0.0.1:2379, 8e9e05c52164694d, 3.4.15, 33 kB, true, false, 3, 144, 144,
```
Hi, the output of etcdctl endpoint status is not match docs saying.
what's the meaning of the last column?

docs saying:
![image](https://user-images.githubusercontent.com/22524871/118112602-cfe3ea80-b417-11eb-9d4c-53f2d699b789.png)

**Comment by horizonzy** [comment]
The last column refer to `apply Index`?

**Comment by xiang90** [comment]
@horizonzy 

Can you run `etcdctl endpoint --write-out=table status` (add the table option) and paste the output here?

**Comment by horizonzy** [comment]
Oh, I see. the docs is not the latest.
