### ISSUE TITLE
A problem with tuning for election time

### ISSUE THREAD

**Issue by mengshi02** [etcd-io/etcd#12982]
**Is there a solution to this problem? I have an idea: Followers perceive the change of the leader through the network connection, and call the `Campaign()` to trigger an election,Is this okay?**

<img width="854" alt="屏幕快照 2021-05-15 下午10 15 11" src="https://user-images.githubusercontent.com/76758833/118428925-1a5cb400-b703-11eb-8df9-fe4f2a45aa75.png">

**Comment by spzala** [comment]
@mengshi02 thanks but if you have a better solution, please propose a PR with test/test results so that you get a better feedback. I am closing this, please feel free to create a PR or another issue if needed. Thanks!
