### ISSUE TITLE
etcdmain: listen tcp 127.0.0.1:2380: bind: address already in use

### ISSUE THREAD

**Issue by naanuswaroop** [etcd-io/etcd#13005]
start of etcd is failing in mac with below error:
 "etcdmain: listen tcp 127.0.0.1:2380: bind: address already in use"

But, netstat shows that its indeed etcd which is bound to 2380.

I have tried reinstalling etcd.
I have tried restart of mac.
I have tried restart of etcd brew service.

### **etcd logs:**

> swsp@SWSP-M-73V4 /usr % etcd
> [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
> 2021-05-19 19:39:19.536488 I | etcdmain: etcd Version: 3.4.16
> 2021-05-19 19:39:19.536585 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
> 2021-05-19 19:39:19.536589 I | etcdmain: Go Version: go1.16.3
> 2021-05-19 19:39:19.536592 I | etcdmain: Go OS/Arch: darwin/amd64
> 2021-05-19 19:39:19.536595 I | etcdmain: setting maximum number of CPUs to 12, total number of available CPUs is 12
> 2021-05-19 19:39:19.536599 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)
> 2021-05-19 19:39:19.536605 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
> [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
> 2021-05-19 19:39:19.537896 C | etcdmain: listen tcp 127.0.0.1:2380: bind: address already in use

### **Issue reproduction logs:**

**Before start of etcd:**

> swsp@SWSP-M-73V4 /usr % ps ax | grep etcd      
> 24156 s004  S+     0:00.00 grep etcd
> swsp@SWSP-M-73V4 /usr % 
> swsp@SWSP-M-73V4 /usr % netstat -vanp tcp | grep 2380
> swsp@SWSP-M-73V4 /usr % 

**After start of etcd:**

> swsp@SWSP-M-73V4 /usr % brew services run etcd  
> ==> Successfully ran `etcd` (label: homebrew.mxcl.etcd)
> swsp@SWSP-M-73V4 /usr % 
> swsp@SWSP-M-73V4 /usr % ps ax | grep etcd            
> 24431   ??  U      0:01.66 /usr/local/opt/etcd/bin/etcd
> 24458 s004  R+     0:00.00 grep etcd
> swsp@SWSP-M-73V4 /usr % netstat -vanp tcp | grep 2380
> tcp4       0      0  127.0.0.1.2380         *.*                    LISTEN      131072 131072  24431      0 0x0100 0x00000006
> swsp@SWSP-M-73V4 /usr %                              
> swsp@SWSP-M-73V4 /usr % etcd
> [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
> 2021-05-19 19:39:19.536488 I | etcdmain: etcd Version: 3.4.16
> 2021-05-19 19:39:19.536585 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
> 2021-05-19 19:39:19.536589 I | etcdmain: Go Version: go1.16.3
> 2021-05-19 19:39:19.536592 I | etcdmain: Go OS/Arch: darwin/amd64
> 2021-05-19 19:39:19.536595 I | etcdmain: setting maximum number of CPUs to 12, total number of available CPUs is 12
> 2021-05-19 19:39:19.536599 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)
> 2021-05-19 19:39:19.536605 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
> [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
> 2021-05-19 19:39:19.537896 C | etcdmain: listen tcp 127.0.0.1:2380: bind: address already in use

**Comment by Casper-Mars** [comment]
I think `brew services` already run etcd. Then executing command `etcd` is run another etcd. So the second one can`t bind the address.

**Comment by naanuswaroop** [comment]
My bad. Thank you Casper-Mars
