### ISSUE TITLE
Socket reuse port and socket reuse address panics on Darwin

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#13004]
When starting etcd with `--socket-reuse-port --socket-reuse-address` I see a panic on Darwin:

```
{"level":"info","ts":"2021-05-19T15:50:43.482+0200","caller":"embed/serve.go:139","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"[::]:2379"}
panic: interface conversion: transport.timeoutConn is not transport.keepAliveConn: missing method SetKeepAlive

goroutine 191 [running]:
go.etcd.io/etcd/client/pkg/v3/transport.(*keepaliveListener).Accept(0xc00010b5d0, 0xc0000444b0, 0x46, 0x8b, 0x21473c3)
	/tmp/etcd-release-3.5.0-beta.3/etcd/release/etcd/client/pkg/transport/keepalive_listener.go:53 +0x89
github.com/soheilhy/cmux.(*cMux).Serve(0xc0001a85a0, 0x0, 0x0)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:170 +0x96
go.etcd.io/etcd/server/v3/embed.(*serveCtx).serve(0xc0005933b0, 0xc000590300, 0xc00002e760, 0x1f7b780, 0xc00022cb00, 0xc0004963e0, 0xc0000ffa20, 0x2, 0x2, 0x0, ...)
	/tmp/etcd-release-3.5.0-beta.3/etcd/release/etcd/server/embed/serve.go:194 +0x282
go.etcd.io/etcd/server/v3/embed.(*Etcd).serveClients.func1(0xc00002e600, 0xc000227320, 0xc00022a4e0, 0xc0005933b0)
	/tmp/etcd-release-3.5.0-beta.3/etcd/release/etcd/server/embed/etcd.go:733 +0xb6
created by go.etcd.io/etcd/server/v3/embed.(*Etcd).serveClients
	/tmp/etcd-release-3.5.0-beta.3/etcd/release/etcd/server/embed/etcd.go:732 +0x506
```

I suspect we have to do something similar to how windows was handled? https://github.com/etcd-io/etcd/blob/main/client/pkg/transport/sockopt_windows.go

**Comment by hexfusion** [comment]
nice find and agree

**Comment by danishprakash** [comment]
Does etcd accept first time contributors? I'd like to pick this up. @lilic @hexfusion

**Comment by lilic** [comment]
@danishprakash of course, thank you! Feel free to pick it up, let me know if you have any questions!

**Comment by danishprakash** [comment]
It seems like socket port/addr reuse is supported out of the box for darwin [as well](https://golang.org/src/syscall/syscall_unix.go). Just confirming, what we want here is not to return an error for darwin like how we do it for windows, right?

**Comment by lilic** [comment]
Yes, I found that as well, ideally we want it to work on darwin yes, but if its too much work we can work around it by doing something similar as for windows. Unless you need it to work for darwin yourself?

**Comment by danishprakash** [comment]
Yes, I think ideally it should work on Darwin. I'd love to work on it, might require a little more time and might ask a few more questions though. Will update this thread soon.

**Comment by danishprakash** [comment]
Missed following up on this, will take a look over the weekend cc/ @lilic
