### ISSUE TITLE
Why lease is not expired after ttl time？remaining negative

### ISSUE THREAD

**Issue by AAJCN** [etcd-io/etcd#13019]
Etcd Version 3.3.18
DB Size： 4G
lease timetolive 504f7988b11dc28c  
lease 504f7988b11dc28c granted with TTL(120s), remaining(-1928s)
How does this happen?

**Comment by xiang90** [comment]
Is there a way to reproduce it?

**Comment by zhangboqi** [comment]
I also encountered this problem

**Comment by zhangboqi** [comment]
how to resolve it ?

**Comment by zhangboqi** [comment]
I think it was caused by modifying the server time
