### ISSUE TITLE
Add ability to trigger benchmark jobs on pull requests

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#13025]
I noticed in a couple of PRs if they have any potential performance improvements or regressions, we direct the users to run a `benchmark` command. Often these are run on their local machines, which can skew the results as, you know, it depends on their machine. It would be nice, in my opinion, to have those benchmarks run in GitHub actions CI or in dedicated machines. As in an ideal scenario, we would want to run those benchmarks with no noisy neighbours, but starting with setting up with github actions might be better than the current solution. This would also be easier for contributors as they would not need to run this manually.

In other projects, they have triggers via comment command or PR labels that trigger a run of a benchmark on either dedicated machines. One example is the Prometheus project, an example of an output of such a result can be seen in https://github.com/prometheus/prometheus/pull/8833#issuecomment-843522107. 

Is this something etcd is interesting in and would be beneficial? I am happy to help contribute something like this if this is the case! We can go more into details if we think it's worth the effort.

**Comment by gyuho** [comment]
This will be awesome. Happy to help with infra setup on AWS.

(I know there was a thread on this, let me revive that thread.)
