### ISSUE TITLE
Goroutine leak in TestEtcdGrpcResolver 

### ISSUE THREAD

**Issue by timmyyuan** [etcd-io/etcd#13023]
I tried to figure out if there might be goroutine leaks in unit tests. So I used [goleak](https://github.com/uber-go/goleak) to guard all test functions (`main` branch) and run `PASSES=unit ./test`. I finally found a test leaking goroutines:

```
--- FAIL: TestEtcdGrpcResolver (4.43s)
    resolver_test.go:51: Cannot create clusters in --short tests
     leak.go:117: Test appears to have leaked :
         google.golang.org/grpc.(*Server).Serve.func1(0xc00042ee00)
         	/root/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:715 +0xe5
         google.golang.org/grpc.(*Server).Serve(0xc00042ee00, 0x18485f0, 0xc0004a11a0, 0x0, 0x0)
         	/root/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:769 +0x88a
                created by go.etcd.io/etcd/pkg/v3/grpc_testing.(*StubServer).Start
        	/root/actions-runner/_work/path/to/etcd/pkg/grpc_testing/stub_server.go:53 
FAIL
FAIL	go.etcd.io/etcd/tests/v3/integration/clientv3/naming	39.512s
```

In normal situations, there should be no alive goroutines after a test function  finished. Is this goroutine leak intentional or expected?

**Comment by ptabor** [comment]
Thanks for checking. 
In etcd for integration tests we are using our own leak checker: 
  https://github.com/etcd-io/etcd/blob/main/client/pkg/testutil/leak.go
Good to know that there exists 'more standard' solution.

It didn't got integrated in the unit test yet (but that's definitely good to have). 

Seems `ss.s.Stop()` is missing in: grpc_testing/stub_server.go:62. 

Would you mind sending a PR ?

**Comment by timmyyuan** [comment]
Gotcha, I have send a PR in #13024
