### ISSUE TITLE
new feature for dump & replay etcd requests.

### ISSUE THREAD

**Issue by wilsonwang371** [etcd-io/etcd#13041]
In our current enterprise DC k8s environment, it is very hard to diagnose some complex performance issues to find the root cause and bottlenecks.

In a real k8s cluster, the load of the etcd cluster is different. It is usually a mixed workload of both read and write operations. To run real-world workloads on the etcd cluster is a need to get a better understanding of the etcd cluster's real performance.

To enable etcd to run the real-world workload, we want to implement a feature that record/replay etcd cluster requests. Using this feature, we can record the real-world k8s cluster requests to the etcd cluster and play it later on modified etcd cluster without setting up a real k8s cluster environment.

Can you guys give some suggestions on this? Do you guys think this can be beneficial?

@gyuho @ptabor @xiang90

**Comment by gyuho** [comment]
I think something similar to kube-apiserver audit logs will be useful, so long as it's optional.

**Comment by Jeffwan** [comment]
https://github.com/etcd-io/etcd/issues/10662  It might be better to support etcd audit log first.

**Comment by lilic** [comment]
Yes, nice! We (OpenShift team) already brainstormed for a very similar idea - a  tool that replays the request patterns based on the size of the load and the type/pattern of requests. This would give us a great way to also do proper benchmark and perf testing for etcd as well.

@wilsonwang371 what do you think of having it part of `etcdutl` maybe? Or where were you thinking?

**Comment by wilsonwang371** [comment]
> Yes, nice! We (OpenShift team) already brainstormed for a very similar idea - a tool that replays the request patterns based on the size of the load and the type/pattern of requests. This would give us a great way to also do proper benchmark and perf testing for etcd as well.
> 
> @wilsonwang371 what do you think of having it part of `etcdutl` maybe? Or where were you thinking?

This is still at the initial design stage. Good to hear that you guys also need this feature. Putting it inside `etcdutil` makes sense. Do you guys also have some ideas to share on this?

This is not urgent. Since you guys are also interested in this one, we will definitely also like to put this at a higher priority.

**Comment by lilic** [comment]
We had some ideas around a tool that is standalone not tied to etcd itself that somehow gathers request patterns, either via network or tracing, but we haven't gone further than that. 

Our main use case was to use that to record customer requests when there is a bug we could not reproduce easily, so it would have to include request size and request type, which we could then replay easily against a standalone etcd setup. 

The second use case would be to easier run performance and scale for etcd by mocking apiserver patterns for example.

We mainly thought of tracing as we have duration and size of requests, but haven't experimented since then really, might have a look at it this Friday.

**Comment by wilsonwang371** [comment]
> We had some ideas around a tool that is standalone not tied to etcd itself that somehow gathers request patterns, either via network or tracing, but we haven't gone further than that.
> 
> Our main use case was to use that to record customer requests when there is a bug we could not reproduce easily, so it would have to include request size and request type, which we could then replay easily against a standalone etcd setup.
> 
> The second use case would be to easier run performance and scale for etcd by mocking apiserver patterns for example.
> 
> We mainly thought of tracing as we have duration and size of requests, but haven't experimented since then really, might have a look at it this Friday.

Cool, let me know if there is any update from your side. We will also post the updates here in case we have some further discussions. Later if we can have a more detailed plan, we may have some joined meeting to talk about this.

**Comment by lilic** [comment]
Made a bit of progress (it's a side effort) I managed to extract data from tracing backend (jaeger in my case), but I am missing keys, so will be adding that to the traces.

After that I should have the timestamps to calculate the frequency of the request pattern, size of the payload, key and request type. This would create a pattern on the requests that we can then replay against another etcd. I am trying to make the replay part generic enough so you can feed other data other than tracing to it, like files or use the API. It's still WIP and will try to update more when I have more. 

Let me know if its roughly what you had in mind, and if tracing would work for your use case?

**Comment by wilsonwang371** [comment]
> Made a bit of progress (it's a side effort) I managed to extract data from tracing backend (jaeger in my case), but I am missing keys, so will be adding that to the traces.
> 
> After that I should have the timestamps to calculate the frequency of the request pattern, size of the payload, key and request type. This would create a pattern on the requests that we can then replay against another etcd. I am trying to make the replay part generic enough so you can feed other data other than tracing to it, like files or use the API. It's still WIP and will try to update more when I have more.
> 
> Let me know if its roughly what you had in mind, and if tracing would work for your use case?

Nice!

Recently, in our company's etcd cluster we observed some abnormal behaviors. **The pod creating in 3.3 is faster than 3.4.** In 3.3, it can be around 1K pods/s but in 3.4, it is only around 500~600 pods/s.

I did an evaluation of the performance difference between 3.3 and 3.4. From the graph, I can see that in some cases, 3.3 performance is better than 3.4 but still the graph is not very persuasive. It cannot explain the reason for slow pods creation in 3.4.

**That's why I believe being able to dump the etcd access data and replay it is very important.** I am going to spend some extra time on this. Being able to observer the real apiserver access patterns is more urgent for me to find out the root cause of slow throughput in 3.4.

Let me know if any of you guys have some suggestions. @lilic @ptabor @gyuho @Jeffwan 

![output_write](https://user-images.githubusercontent.com/3913185/121260086-be9acc00-c865-11eb-993f-b6232b5891e5.png)


![output_read](https://user-images.githubusercontent.com/3913185/121260071-ba6eae80-c865-11eb-8087-5d9853faf4d5.png)

**Comment by lilic** [comment]
Two thoughts/ideas:
- Are the go versions different?
- Have you tried continuous profiling (e.g. https://github.com/conprof/conprof), might give a better insight into the diffs.

**Comment by wilsonwang371** [comment]
> Two thoughts/ideas:
> 
> * Are the go versions different?
> * Have you tried continuous profiling (e.g. https://github.com/conprof/conprof), might give a better insight into the diffs.

Hi Lili,

I tried to use opentelemetry but I am worried about the extra overhead for the dumping functionalities. Therefore, I implemented some initial code to dump rpc requests. The #13102 pull request contains the code. I am still working on it now and let me know if you have any suggestions.

**Comment by lilic** [comment]
Nice, thank you for the PR! 🎉  

Yeah, I was worried about overhead if it's on by default all the time as well, I am hoping they improve it over time.

**Comment by wilsonwang371** [comment]
Update to this issue: I already captured some data in our enterprise environment and I am working on some initial analysis. Depending on the result, I will discuss with you guys and we can see how to push forward this.

**Comment by lilic** [comment]
Nice, thanks for the update!

**Comment by mahadevan-k** [comment]
Hi Guys,

This looks like a very interesting feature, we need it to audit our etcd cluster.

Let me know when it might be ready or if I can help in anyway with the development or testing.
