### ISSUE TITLE
etcd connection to cluster node not use hostname

### ISSUE THREAD

**Issue by eliteaz** [etcd-io/etcd#13044]
Use etcd cluster of three nodes (2 nodes on CentOS 7 and 1 node on CentOS 8)
- etcd version 3.2.10

Starting cluster i got such a message:
`rejected connection from "[2a01:4f8:1c1c:3exe::1]:58782" (tls: "2a01:4f8:1c1c:3exe::1" does not match any of DNSNames ["*.example.com" "cluster.example.com" "2a04:3541:1000:500:85b:71ff:fe6d:c8a" "2001:19f0:7402:a25:5400:1ff:fe48:c741" "2a03:d0c0:1:e0::84:e001" "2a03:b0c0:2:d0::cea:3001"]`

i have generated certificate with additional `2a01:4f8:1c1c:3exe::1` and cluster works correctly even my certificate had such a wildcard record `*.example.com` 
Is there any option that forces connection to cluster node using hostnames instead IP ?

**Comment by nic-chen** [comment]
hi @eliteaz  
Could you please provide more detailed information, such as the startup command and configuration?

**Comment by eliteaz** [comment]
Paste my etcd config via systemd unit file
[root@hostname ~]# systemctl cat etcd
```
# /etc/systemd/system/etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos/etcd
After=network.target

[Service]
Type=notify
Restart=no
RestartSec=5s
LimitNOFILE=40000
TimeoutStartSec=0

ExecStart=/usr/local/bin/etcd --name hostname \
    --data-dir /var/lib/etcd \
    --listen-client-urls https://0.0.0.0:2379 \
    --advertise-client-urls https://hostname.example.com:2379 \
    --listen-peer-urls https://0.0.0.0:2380 \
    --initial-advertise-peer-urls https://hostname.example.com:2380 \
    --initial-cluster-token hostname-cluster.example.com \
    --initial-cluster-state new \
    --discovery-srv hostname-cluster.example.com \
    --peer-client-cert-auth \
    --peer-trusted-ca-file /etc/pki/tls/private/etcd.ca.pem \
    --peer-cert-file /etc/pki/tls/private/etcd.server.pem \
    --peer-key-file /etc/pki/tls/private/etcd.server.key \
    --client-cert-auth \
    --trusted-ca-file /etc/pki/tls/private/etcd.ca.pem \
    --cert-file /etc/pki/tls/private/etcd.server.pem \
    --key-file /etc/pki/tls/private/etcd.server.key \

[Install]
WantedBy=multi-user.target

```
Paste generated server.pem cert info
[root@hostnam ~]# openssl x509 -in /etc/pki/tls/private/etcd.server.pem -text -noout

```
Certificate:
    Data:
.
.....
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:*.example.com, DNS:hostname-cluster.example.com, DNS:2a03:d0e0:2:d0::bea:3001, DNS:2a03:c0cd:1:d0::84:e001, DNS:2a01:4d8:1c1c:3bde::1
.....
.
```
and why i should generate certificate with detached IPv6 addresses, if i have wildcard hostname `*.example.com`

**Comment by korenlev** [comment]
Facing the same issue, so ETCD cluster can only work with static IPs ??
