### ISSUE TITLE
How to get a list of historical versions of a key

### ISSUE THREAD

**Issue by guyueyimu** [etcd-io/etcd#13046]
According the range of mod_revision， i want to get a list of historical versions of a key，
but like this, it doesn't work：

key := "/sme/light/v1/ns/content/eop.ni/conf.slrun.json"
resp, err := client.Get(context.TODO(), key, clientv3.WithMaxModRev(200), clientv3.WithMinModRev(100))

How can I do this？

**Comment by spzala** [comment]
The answer from @xiang90 in this old issue should help you https://github.com/etcd-io/etcd/issues/7292 The revision option is mentioned here as well https://github.com/etcd-io/etcd/tree/main/etcdctl#options-1 
Closing it as a dup but please reopen if needed. Thanks!
