### ISSUE TITLE
etcd account does not have the ability to prevent cracking

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#13096]
Please read https://etcd.io/docs/latest/reporting_bugs/
etcd account does not have the ability to prevent authentication failure

**Comment by lilic** [comment]
Hello, can you provide a bit more details about the issue please, thank you!

**Comment by SingleThread** [comment]
For example, when I use an incorrect password to access etcd data, the etcd account can still be authenticated no matter how many incorrect passwords are entered. Although the account password is incorrect, there is no locking mechanism. The account can be locked based on the access IP address or account.

**Comment by daotoulangzi** [comment]
> For example, when I use an incorrect password to access etcd data, the etcd account can still be authenticated no matter how many incorrect passwords are entered. Although the account password is incorrect, there is no locking mechanism. The account can be locked based on the access IP address or account.

Does the problem of explosive attack still exist?

**Comment by hexfusion** [comment]
I will reopen this for conversation but as etcd RBAC is not used in k8s use case the cycles for improving it is limited. If you are interested in moving this forward we would gladly review a PR.
