### ISSUE TITLE
etcd behind haproxy

### ISSUE THREAD

**Issue by Yamakasi** [etcd-io/etcd#13106]
Is it possible to put an etcd cluster just behind a haproxy instance with http frontends ?

Or are there special requirement ?

I have tried to lookup some haproxy examples for etcd and most where not very recent but showed http as frontend. I was wondering if also can do simply tcp mode.

Maybe someone has an example as well that could be useful here.

**Comment by agargi** [comment]
@Yamakasi Does this help? Apologies if this is not what you are looking for. If not, let me know and I'll dig deeper.

https://www.inap.com/blog/deploying-kubernetes-on-bare-metal/

**Comment by karuppiah7890** [comment]
TCP mode works :)

etcd Server uses gRPC and I noticed this in gRPC - https://grpc.io/blog/grpc-load-balancing/#recommendations-and-best-practices which has a reference for HA Proxy config - https://gist.github.com/thpham/114d20de8472b2cef966

I tried it too - https://github.com/karuppiah7890/issues-info/tree/main/etcd-io/etcd/issue-13106

It may not be perfect though, as I'm new to both etcd and HAProxy. So if you are talking about production cluster, I guess you could follow some more better and more secure configurations with TLS, etc

**Comment by raindylong** [comment]
Nginx stream module is another good way to do this . http://nginx.org/en/docs/stream/ngx_stream_core_module.html

**Comment by ReachableCEO** [comment]
@karuppiah7890 Is this working for you? you can point etcd clients at the haproxy port and set/get key/values? It wasn't clear from the links if the config actually worked or not. :)
