### ISSUE TITLE
Explore using vtprotobuf

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#13107]
Recently the Vitess folks have posted a blog on their optimizations on protobuf generator https://vitess.io/blog/2021-06-03-a-new-protobuf-generator-for-go/. The project source is located at https://github.com/planetscale/vtprotobuf.

The findings and benchmarks were very interesting and impressive, and it would be interesting to try it out and benchmark and compare the differences. Any thoughts against this? 

Opening this issue mainly to get the conversation started as I believe it would be good to find alternatives as the gogo/protobuf project is looking for new maintainers, so we either need to take that on, or consider alternatives.

**Comment by wilsonwang371** [comment]
sounds like a good idea

**Comment by lilic** [comment]
> so it should be possible to upgrade to proto-v2 compatible proto surface without breaking end-users.

Thanks! I should be able to get to this for this release.

**Comment by serathius** [comment]
Can you verify that vtprotobuf supports custom options used in https://github.com/etcd-io/etcd/pull/13216 and needed to implement https://github.com/etcd-io/etcd/pull/13216

**Comment by serathius** [comment]
Created PR that migrates proto generation to vtproto https://github.com/etcd-io/etcd/pull/13719
There is still work related to:
* Update code to match generated go files (name changes, pointer changes etc)
* Verify if there are any breaking changes due to dropped gogo annotations
