### ISSUE TITLE
Solution for CMD parameters #6088

### ISSUE THREAD

**Issue by Yamakasi** [etcd-io/etcd#13105]
Hi,

I'm running into the following issue like described here: #6088

What is the right way to run etcd in docker now as links are broken there ?

Thank you very much!

**Comment by spzala** [comment]
@Yamakasi please see https://github.com/etcd-io/etcd/releases 'Docker` section if that helps. Thanks!

**Comment by Yamakasi** [comment]
@spzala Thanks a lot, sure it does! Can you add it to the docs again as well ?

I assume that the RC is stable enough that you point at it ?

**Comment by Yamakasi** [comment]
@spzala yes perfectly, thanks! 

I'm really not sure why I wasn't able to find the docker part fort this version, sorry but thanks again!

**Comment by spzala** [comment]
@Yamakasi no problem at all, happens with all of us :) I am glad that you are good now, and thanks for closing the issue.
