### ISSUE TITLE
etcd  bug   v3.4.16

### ISSUE THREAD

**Issue by icetech233** [etcd-io/etcd#13103]
goroutine 8709 [running]:
github.com/rpcxio/rpcx-etcd/store/etcdv3.(*EtcdV3).Close(0xc000518500)
        /Users/atta/GolandProjects/pkg/mod/github.com/rpcxio/rpcx-etcd@v0.0.0-20210525110612-180740a8f3d6/store/etcdv3/etcdv3.go:454 +0x39
github.com/rpcxio/rpcx-etcd/client.(*EtcdV3Discovery).watch.func1(0xc0005d13b0)
        /Users/atta/GolandProjects/pkg/mod/github.com/rpcxio/rpcx-etcd@v0.0.0-20210525110612-180740a8f3d6/client/etcdv3_discovery.go:161 +0x3b
github.com/rpcxio/rpcx-etcd/client.(*EtcdV3Discovery).watch(0xc0005d13b0)
        /Users/atta/GolandProjects/pkg/mod/github.com/rpcxio/rpcx-etcd@v0.0.0-20210525110612-180740a8f3d6/client/etcdv3_discovery.go:266 +0xd3e
created by github.com/rpcxio/rpcx-etcd/client.NewEtcdV3DiscoveryStore
        /Users/atta/GolandProjects/pkg/mod/github.com/rpcxio/rpcx-etcd@v0.0.0-20210525110612-180740a8f3d6/client/etcdv3_discovery.go:96 +0x85b

**Comment by lilic** [comment]
Hey @icetech233 can you provide a bit more information about the potential bug. Like which specific version you used, how did this happen (after which actions), which env. Thank you!

**Comment by icetech233** [comment]
> Hey @icetech233 can you provide a bit more information about the potential bug. Like which specific version you used, how did this happen (after which actions), which env. Thank you!

exe program  auto close and then queit

**Comment by lilic** [comment]
@icetech233 I am running 3.4.16 but have not come across this. What environment are you running, maybe sharing the flags or config would be useful. Thank you!
