### ISSUE TITLE
the hyperlink of bug fixes(5) in the blog is incorrect

### ISSUE THREAD

**Issue by halleyshx** [etcd-io/etcd#13116]
[bug fixes of the new blog](https://etcd.io/blog/2021/announcing-etcd-3.5/#bug-fixes)
![image](https://user-images.githubusercontent.com/24284940/122350114-7ffcc400-cf7f-11eb-929c-c15339f1b677.png)
it's same to bug fixes 4, should be 'https://github.com/etcd-io/etcd/pull/11850'

**Comment by lilic** [comment]
Thanks for noticing! Do you want to do the fix? The source is actually located here https://github.com/etcd-io/website/blob/ba37eaa5861d0304ef104b5061af4afb497d9bb6/content/en/blog/2021/announcing-etcd-3.5.md#bug-fixes

**Comment by halleyshx** [comment]
@lilic I would like to do this, but now I found someone had fix the hyperlink problem and pushed ( 'https://github.com/etcd-io/website/pull/384' ) . Contribute again next time if have another chance. ^_^

**Comment by lilic** [comment]
Ah, yes etcd is open for contributing, so looking forward to that! Opening issues tends to be good if its larger feature or change, but feel free to just open PR next time there is something like this! 🎉

**Comment by spzala** [comment]
Closing as it's fixed :) Thanks!
