### ISSUE TITLE
raft learner limit increase proposal

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#13148]
Today we limit the raft learner count to 1[1] which rightfully was set in 3.4[2] as a gate against leader stress of log replication. I think the time has come to consider lifting this limit. Perhaps as a gate to additional learners, we can scale learners only if existing learners are promotable (in sync with the leader). Open to other ideas but I think for the feature to evolve user needs to be able to explore learners further even if this is under an experimental flag.

cc @jingyih @gyuho @xiang90 @ptabor 

[1] https://github.com/etcd-io/etcd/blob/46b49a6ecf4f2a38406fa49fbc580493702ee732/server/etcdserver/api/membership/cluster.go#L339-L340
[2] https://github.com/etcd-io/etcd/pull/10730#discussion_r284514596

**Comment by hexfusion** [comment]
cc @marun @lilic

**Comment by anguslees** [comment]
> Perhaps as a gate to additional learners, we can scale learners only if existing learners are promotable
I'm ignorant - why is this necessary?

Other than the additional replication log load, I feel like the whole point of learners is that they don't affect anything important.  So it should be safe to have lots of them (on an unloaded cluster, and for small values of 'lots'), added/removed fairly arbitrarily afaics? .. Do we care how the existing learners are doing before adding/removing other learners?

**Comment by hexfusion** [comment]
The concern is stress on leader to provide log replication to learners. If you add them unbounded leader will take a performance hit. Think of 6GB state file replicated N times. So one approach I see is ensuring current learners are promotable before scaling another.

If you wanted to add learner unbounded for experimental purposes it should probably be under an unsafe flag.

**Comment by hexfusion** [comment]
This all needs testing if your interested in doing a performance review that would help with validation.

**Comment by hexfusion** [comment]
I have been working on the performance review will update when completed.
