### ISSUE TITLE
etcd 3.5 health endpoint not usable when authentication is enabled

### ISSUE THREAD

**Issue by tdolphin** [etcd-io/etcd#13144]
Cannot query 127.0.01:2739/health when auth enabled in version 3.5
Steps to reproduce:
```
❯ ./etcdctl endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 6.168636ms
❯ ./etcdctl user add root:passw0rd
User root created
❯ ./etcdctl user grant-role root root
Role root is granted to user root
❯ ./etcdctl auth enable
Authentication Enabled
❯ ./etcdctl endpoint health
```
```json
{"level":"warn","ts":1624550312.4325728,"logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00014a700/#initially=[127.0.0.1:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
```
**127.0.0.1:2379 is unhealthy: failed to commit proposal: etcdserver: user name is empty
Error: unhealthy cluster**

GET request to gateway doesn't give expected result 
![image](https://user-images.githubusercontent.com/7492772/123296483-afae4d80-d4e4-11eb-9070-29bf796127bb.png)

```
❯ etcdctl --user root:passw0rd auth disable
Authentication Disabled
❯ ./etcdctl endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 2.579161ms
```

Expected: `GET 127.0.0.1:2739/health` would still work after authentication is enabled **_without_** requiring authentication.
Actual: errors giving unhealthy.
This means http GET cannot be used any more as liveness probe.

Note that:
```
etcdctl --user root:passw0rd endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 22.706843ms
```

**Comment by tangcong** [comment]
thanks @tdolphin. pr #13145 will fix it.
