### ISSUE TITLE
Alert rule etcdHighNumberOfFailedGRPCRequests in Prometheus

### ISSUE THREAD

**Issue by aldelsa** [etcd-io/etcd#13147]
ISSUE TYPE

    Bug Report

SUMMARY

We have a k8s cluster using kube-prometheus-stack for monitoring. This prometheus have a several alert rules to check all the cluster. One of those alert is to check request on etcd of kubernetes. The problem is that this rule is persistently alerting: 
message = etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd instance ". But the cluster is running properly.
We have changed the image of etcd to new one and we have the same problem.

ENVIRONMENT

    Kubernetes version: 1.21.1
    Etcd version: gcr.io/etcd-development/etcd:v3.4.16
    Kube-prometheus-stack: 15.4.4
    Operating System: Ubuntu 18.04

EXPECTED RESULTS

No receive any alert about etcd

ACTUAL RESULTS
Labels
alertname = etcdHighNumberOfFailedGRPCRequests
grpc_method = Watch
grpc_service = etcdserverpb.Watch
instance = 192.168.251.221:2381
job = kube-etcd
prometheus = monitoring/kube-prometheus-stack-prometheus
severity = warning
Annotations
message = etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd instance 192.168.251.221:2381.

**Comment by ksa-real** [comment]
I wonder if https://github.com/etcd-io/etcd/issues/9166 is related

**Comment by ksa-real** [comment]
I see that according to Prometheus data the grpc calls to etcd's Watch method have either "Cancelled" or "Unknown" grpc code. Check the graph of below expression e.g. last 24 hours:
```
sum by (grpc_code) (grpc_server_handled_total{job=~".*etcd.*",grpc_service="etcdserverpb.Watch",instance="10.10.10.5:2379",grpc_method="Watch", job="kube-etcd"})
```
So effectively if there are no calls to Watch API, the service looks healthy. If there are calls, they fail with !="OK" grpc code. Can someone comment on whether this behavior is expected?

**Comment by allenporter** [comment]
I believe when I've looked into this before it is #10289

**Comment by allenporter** [comment]
(The fix appears in the etcd 3.5 [changelog](https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md), though I have not upgraded yet)

**Comment by allenporter** [comment]
That issue was about remapping the error code --  but the alert still fires since Canceled != Ok

**Comment by allenporter** [comment]
@lilic updated the rules for etcdHighNumberOfFailedGRPCRequests in https://github.com/etcd-io/etcd/pull/13127

roughly:

`grpc_code=~"Unknown|FailedPrecondition|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded"`

Now i think upstream projects that copied these rules just need to be updated.  Great!

**Comment by allenporter** [comment]
kube-prometheus-stack is currently not able to be easily updated with the latest etcd rules due to https://github.com/prometheus-community/helm-charts/issues/225

**Comment by allenporter** [comment]
I think this issue is fixed and can be closed.

**Comment by spzala** [comment]
@allenporter thanks for findings! 
@aldelsa closing the issue per @allenporter comment and https://github.com/etcd-io/etcd/pull/13127 Please free to reopen if needed. Thanks!
