### ISSUE TITLE
Will the old password be verified when the etcd user changes the password?

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#13191]
When the etcd user changes the password, don’t he need to change the old password? Can I only use the administrator account to reset the password?

**Comment by agargi** [comment]
@SingleThread 

When the etcd user changes the password, don’t he need to change the old password?
>>> etcd is not checking old password before updating. I'll check & write a PR for this, if necessary. 

Can I only use the administrator account to reset the password?
>>> Yes. Pls refer snapshot. 

![image](https://user-images.githubusercontent.com/11611178/126083225-75e11a29-773b-4043-b6b9-44e156c2d5a4.png)
