### ISSUE TITLE
Issue with Raft Add or Remove node with `proposeConfChange`

### ISSUE THREAD

**Issue by Emon46** [etcd-io/etcd#13212]
I am using a 3 node cluster with raft leader election. Now I need to make it 5 nodes. Or sometimes need to remove a node. I have tried to add or remove nodes one by one with `proposeConfChange` where I have created a request like this
```   
  cc := raftpb.ConfChange{
        Type:    raftpb.ConfChangeRemoveNode,
        NodeID:  uint64(*node.NodeId),
      }
```
Followed the raft example API.
Then I have passed this cc in `ProposeConfChange(ctx, cc)` I have done this in a continuous loop until the node is added or removed into the cluster.
But After trying to remove node 4, I am facing the below error.
```
raft2021/07/12 21:14:25 INFO: 1 ignoring conf change {ConfChangeRemoveNode 4 [] 747} at config voters=(1 4) learners=(2 3): possible unapplied conf change at index 44 (applied to 39)
raft2021/07/12 21:14:26 INFO: 1 ignoring conf change {ConfChangeRemoveNode 4 [] 748} at config voters=(1 4) learners=(2 3): possible unapplied conf change at index 44 (applied to 39)
raft2021/07/12 21:14:29 INFO: 1 ignoring conf change {ConfChangeRemoveNode 4 [] 749} at config voters=(1 4) learners=(2 3): possible unapplied conf change at index 44 (applied to 39)
```
Is it a network latency problem? or I am missing something?

**Comment by alexanderstephan** [comment]
I am running into the same issue. Did you manage to fix this?
