### ISSUE TITLE
bug with log-level flag for etcd version 3.4.14

### ISSUE THREAD

**Issue by Dorsosiv** [etcd-io/etcd#13229]
Hi, I'm trying to run etcd from a startup script with --log-level flag but for some reason. When I set the value of the flag to warn or fatal and other levels I still get INFO logs from the containers.

I run the etcd in the container with the following command: 
`/etcd --max-snapshots 1 --max-wals 1 --auto-compaction-retention 1m --snapshot-count 400 --name ${HOSTNAME}.etcdsvc --log-level "${LOGLEVEL}" --data-dir /etcddata/etcd --initial-advertise-peer-urls http://${HOSTNAME}.etcdsvc:2380   --listen-peer-urls http://${IP}:2380   --listen-client-urls http://${IP}:2379,http://127.0.0.1:2379   --advertise-client-urls http://${IP}:2379   --initial-cluster-token etcd-cluster-1  --initial-cluster=${HOSTNAME}.etcdsvc=http://${HOSTNAME}.etcdsvc:2380   --initial-cluster-state ${CLUSTERSTATE} `

Is there something wrong in the usage of flags ? 

In addition, when I have set the log-level to "FATAL" , the etcd crashed....
I think it is related to the capital letters.
I tired "FATAL" because in the logs info log-level is sometimes addressed as INFO. 

Thanks in advance.

**Comment by lilic** [comment]
Hey, It's lower case `fatal`, you can read some docs around this here https://etcd.io/docs/v3.4/op-guide/configuration/#--log-level. Info log level is the default logging priority.

**Comment by Dorsosiv** [comment]
Hi @lilic , I have read and as I told in the description, the lower case does not work for me. is there something I should be changing in the way I use the flag in the command I run ? (see command in the description.)

Thanks :)

**Comment by lilic** [comment]
Can you try `etcd --log-level=fatal --logger=zap`?

**Comment by Dorsosiv** [comment]
Thank you it worked :)

What is the difference, why the flag --logger made all the difference ?
