### ISSUE TITLE
Possible to implement backend as rocksdb?

### ISSUE THREAD

**Issue by hiqsociety** [etcd-io/etcd#13232]
Possible to implement backend as rocksdb?

write speed is slow with boltdb

**Comment by wilsonwang371** [comment]
Actually, in my previous experience, we didn't see the boltdb as the bottleneck. The bottleneck is mainly affected by the storage latency. But we are talking about making it possible to use different storage backends.

**Comment by hiqsociety** [comment]
insertion rate of boltdb is too slow. once ur app gets popular, it'll become the bottleneck.
rocksdb possible?

**Comment by wilsonwang371** [comment]
> insertion rate of boltdb is too slow. once ur app gets popular, it'll become the bottleneck.
> rocksdb possible?

I would say slow insertion is due to etcd is using a single raft. The insertion is not really happening all the time. It is buffered and done in batches.

**Comment by wilsonwang371** [comment]
I actually tried to use badgerdb and the result did not change much.

**Comment by smsufyian** [comment]
However , for the tool it will be nice addition to support multiple storage backends.

**Comment by raindylong** [comment]
In a high load etcd cluster , I think SSD is the important choose for the data storage, however what backends you choose.

**Comment by cfz** [comment]
just curious, has any one tried [pebble db](https://github.com/cockroachdb/pebble), the pure golang alternative of rocksdb?

**Comment by rupurt** [comment]
@cfz it would be awesome to use pebble now that it's more mature.
