### ISSUE TITLE
ETCD OOM after restarting one of the nodes.

### ISSUE THREAD

**Issue by sanamsarath** [etcd-io/etcd#13231]
etcd version - 3.3.22

We are running etcd in kubernets environment on a high speed i/o storage. Some times the etcd pods are running out of memory - not sure what's triggering this, but we observe following when the issue happens: 

- Then there is flood of snapshot and wal file purges in the logs.
- Eventually 2 of the 3 pods OOM killed by k8s.
- db size incremented from ~250MB to ~1.4GB
- We also noticed there was huge spike in the mvcc_put metrics (while we have only 286 keys currently and the mvcc_delete is 18). The equation doesn't amtch Total keys = put - delete
- Our snapshot count is set to 100000. This is high, but not sure how to determine the right value - we usually have not more than 5000 operations per 10 mins. Will this value be calculated only on the mvcc ops alone or we should consider any additional parameters as well.

Any kind of help is appreciated.

[etcd-cluster-bfsltvzs62_etcd.txt](https://github.com/etcd-io/etcd/files/6857714/etcd-cluster-bfsltvzs62_etcd.txt)
[etcd-metrics.txt](https://github.com/etcd-io/etcd/files/6857716/etcd-metrics.txt)

**Comment by lilic** [comment]
Seems a somewhat similar version and issue as reported in https://github.com/etcd-io/etcd/issues/13222. Obviously, the best would be to upgrade to the latest etcd version if at all possible, as it had a lot of performance improvements.

**Comment by raindylong** [comment]
Upgrade to the new version is one of the good choose as @lilic 's commit , another is do defrag every week/month , and random restart the cluster member one by one every month(this is a chaos test for your app too)

**Comment by sanamsarath** [comment]
Thanks @lilic and @raindylong. 

Definitely we need to upgrade our ETCD to newer version, it has been long due. But the issue we are seeing is on our testing clusters that are frequently redeployed (at max 30 days).

Do we have some user guide (examples) that throw some light on calculating the math for the performance related parameters. Like the the frequency of running defrag, compaction or choosing the snapshot count, max wal files etc.,

**Comment by lilic** [comment]
https://etcd.io/docs/v3.3/op-guide/maintenance/ there are metrics and alerts for this, for example`etcdBackendQuotaLowSpace ` https://github.com/etcd-io/etcd/blob/main/contrib/mixin/mixin.libsonnet#L211-L220.

**Comment by sanamsarath** [comment]
Thanks @lilic
