### ISSUE TITLE
encodeFrameSize code understanding

### ISSUE THREAD

**Issue by Caskia** [etcd-io/etcd#13234]
hello,
I am learning etcd's code, but don't quite understand the effect of calling mod in one place twice.

encoder.go
```go
func encodeFrameSize(dataBytes int) (lenField uint64, padBytes int) {
	lenField = uint64(dataBytes)
	// force 8 byte alignment so length never gets a torn write
	padBytes = (8 - (dataBytes % 8)) % 8
	if padBytes != 0 {
		lenField |= uint64(0x80|padBytes) << 56
	}
	return lenField, padBytes
}
```

I think ```8 - (dataBytes % 8)``` already got the padBytes, another ```% 8``` has any magic usage?

If it's not good to ask a code question here, I will close the issue.

**Comment by Caskia** [comment]
dataBytes can be negative.

**Comment by jpittis** [comment]
A few years late, but I happen to know the answer: Yes they are subtly different.

You can try it out yourself by sticking em both in the Go playground and you'll see they provide slightly different answers.

In short, the extra mod converts the 8 sometimes produced by `8 - (dataBytes % 8)` to a 0.

This code figures out the number of bytes to append to the end of record data such that it's total size is some multiple of 8 (ensuring that the next record to be written will be 8 byte aligned). The code then encodes that "padding" number (between 0 and 8) in the first 8 bits of the uint64, and encodes the actual length of the data in the remaining 56 bits of the uint64.
