### ISSUE TITLE
Remove unused indirect certifi/gocertifi dependency

### ISSUE THREAD

**Issue by jlisee** [etcd-io/etcd#13253]
### Issue

`gocertifi` bundles root certs into your application, and our security team wants to be able to centrally manage root certificates.  Therefore we would like to make sure we are not pulling this package in, even transitively.

### Fix

This transitive dependency can be dropped by updating `cockroachdb/datadriven` to commit cockroachdb/datadriven@c9e8355525148c6ef1ede0f757e0c4111cc318f2 or newer.

### Details

If we check we see that ~master~ main 4cbb949595b7bbdc01a9d68a32b332e79025934c as of 2021-07-29 of `etcd` does not directly use `gocertifi` package.
```
$ git grep -l gocertifi
bill-of-materials.json
etcdctl/go.sum
etcdutl/go.sum
go.sum
raft/go.mod
raft/go.sum
server/go.sum
tests/go.sum
```

When we check external dependencies we see it's being brought in by an older version of `cockroachdb/datadriven`, but the latest version [does not use gocertifi at all](https://github.com/cockroachdb/datadriven/search?q=gocertifi).

```
$ ~/files/go/go/bin/go mod graph | grep certifi
github.com/cockroachdb/datadriven@v0.0.0-20200714090401-bf6692d28da5 github.com/certifi/gocertifi@v0.0.0-20191021191039-0944d244cd40
go.etcd.io/etcd/raft/v3@v3.5.0 github.com/certifi/gocertifi@v0.0.0-20200922220541-2c3bb06c6054
```

**Comment by lilic** [comment]
Thanks, makes sense, but do you mind explaning what other changes were done towards cockroachdb/datadriven? Is there anything related to how datadriven actually functions?

(Side note: its called the main branch not master branch :))

**Comment by jlisee** [comment]
The explicitly linked commit is the only one being pulled in, it bumps `cockroachdb/errors`  a minor version.

**Details**

So right now etcd/raft is on cockroachdb/datadriven@bf6692d28da5:

https://github.com/etcd-io/etcd/blob/8f9829cd2dd65479cca9b1497b6e62fdc74df2b6/raft/go.mod#L7

When we compare the two commits the module changes are it, with the only direct change being http://github.com/cockroachdb/errors going from `v1.2.4` to `v1.6.1`:

https://github.com/cockroachdb/datadriven/compare/bf6692d28da5...c9e8355525148c6ef1ede0f757e0c4111cc318f2
