### ISSUE TITLE
Help, why is my readIndex request so slow? Does it involve disk IO?

### ISSUE THREAD

**Issue by yuchunyu97** [etcd-io/etcd#13258]
I use etcd 3.5 for 3 node cluster, but my disk speed is a bit slow, I want to know is the slow disk IO affect my lineariable read?

The following is a log of a slow request:

```json
{
  "msg": "trace[1574152414] linearizableReadLoop",
  "detail": "{readStateIndex:423077; appliedIndex:423077; }",
  "duration": "2.40227865s",
  "start": "2021-07-30T01:13:07.068Z",
  "end": "2021-07-30T01:13:09.470Z",
  "steps": [
    "trace[1574152414] 'read index received'  (duration: 2.402268354s)",
    "trace[1574152414] 'applied index is now lower than readState.Index'  (duration: 6.708µs)"
  ],
  "step_count": 2
}
```

The `read index received` is too slow, I want to know why this is happening. Does this process involve disk IO?

**Comment by raindylong** [comment]
Same etcd 3.5 and 3 node cluster,about 19% access log is >1s of "read index received" step,everything seems ok.
Any problem or error log about etcd cluster of you app process?

**Comment by lilic** [comment]
Is this issue new for 3.5 for you, or did you have it before in older versions? 

Disk latency can affect performance. https://etcd.io/docs/v3.5/op-guide/performance/

**Comment by yuchunyu97** [comment]
> Is this issue new for 3.5 for you, or did you have it before in older versions?
> 
> Disk latency can affect performance. https://etcd.io/docs/v3.5/op-guide/performance/

There is no detailed trace data before version 3.5.

Especially the latency data of `read index received`.
