### ISSUE TITLE
Replace github.com/form3tech-oss/jwt-go with https://github.com/golang-jwt/jwt

### ISSUE THREAD

**Issue by Haimantika** [etcd-io/etcd#13254]
The maintained fork of https://github.com/form3tech-oss/jwt-go seems now to be https://github.com/golang-jwt/jwt, we might need to make some changes accordingly to: https://github.com/etcd-io/etcd/blob/4cbb949595b7bbdc01a9d68a32b332e79025934c/server/go.mod#L9
For more information on this please refer to https://github.com/kubernetes/kubernetes/issues/104007

**Comment by ysksuzuki** [comment]
etcd 3.4 still depends on github.com/dgrijalva/jwt-go v3.2.0 which has the CVE https://github.com/advisories/GHSA-w73w-5m7g-f7qc.
https://github.com/etcd-io/etcd/blob/release-3.4/go.mod#L12

Is it OK to send a PR to update github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt on release-3,4 branch?
