### ISSUE TITLE
a security problem in using etcd v3.4.15

### ISSUE THREAD

**Issue by ChrisCCheng** [etcd-io/etcd#13269]
etcd is an open source distributed key-value store widely used to hold and manage critical information about distributed systems. However, I have discovered an etcd security issue.
The NewCert function included in the pkg/tlsutil/tlsutil.go file on etcd presents certificate content in plaintext.
I have prepared a straightforward method to handle this issue. Use the code below to enable the certificate content to be read into RAM and then deleted from the storage directory, so the certificate content is not exposed.
This simple method could help you improve your data security when using etcd. Try it out!

insert a variable fileCache and a function readFile，as follows：
```
var fileCache = map[string][]byte{}
func readFile(filename string) ([]byte, error) {
	if content, ok := fileCache[filename]; ok {
		return content, nil
	}
	content, err := ioutil.ReadFile(filename)
	if err != nil {
		return nil, err
	}
	fileCache[filename] = content
	return content, nil
}
```

then，modify the function NewCert, as follows:

```
func NewCert(certfile, keyfile string, parseFunc func([]byte, []byte) (tls.Certificate, error)) (*tls.Certificate, error) {
	cert, err := readFile(certfile)
	if err != nil {
		return nil, err
	}
	key, err := readFile(keyfile)
	if err != nil {
		return nil, err
	}
	...
}
```

**Comment by hardis2003** [comment]
I've had the same problem, and it's a good idea.

**Comment by CriProphet** [comment]
I've had the same problem, and it's a good idea.
