### ISSUE TITLE
e2e test coverage for newly created warning flag for unary request

### ISSUE THREAD

**Issue by spzala** [etcd-io/etcd#13264]
A new experimental flag, `experimental-warning-unary-request-duration`, was recently created to allow user a more configurable option. Please see @serathius comment in the PR - https://github.com/etcd-io/etcd/pull/13236 stating that good to have an e2e tests that sets this flag to very low value and checks for log present. Normal logs are not as important but those performance warnings might be very important for some users. 
cc @roytman

**Comment by lilic** [comment]
@roytman are you interested in implementing this, otherwise, I think a help wanted flag might be nice here.

**Comment by roytman** [comment]
sorry @lilic, I'm not sure that I'll have time for that, please set the flag

**Comment by spzala** [comment]
@lilic yup, thanks!
