### ISSUE TITLE
does base64 encoding always needed when using curl command?

### ISSUE THREAD

**Issue by fffffreedom** [etcd-io/etcd#13263]
hi 
i am doing test accroding to the following page:
https://etcd.io/docs/v3.5/dev-guide/api_grpc_gateway/

as it mentioned:
Note that key and value fields are defined as byte arrays and therefore must be base64 encoded in JSON

but when it comes to the Authentication session, the content of the key and value are not base64 encoded ！
why?

and when i did the test following the examples, i came across the problem:

$ curl -k -L https://localhost:2379/v3/auth/authenticate   -X POST -d '{"name": "root", "password": "pass"}'
{"error":"etcdserver: authentication failed, invalid user ID or password","message":"etcdserver: authentication failed, invalid user ID or password","code":3}

my test version:
$ etcd --version
etcd Version: 3.4.16
Git SHA: d19fbe541
Go Version: go1.12.17
Go OS/Arch: darwin/amd64

$ curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

thanks

**Comment by raindylong** [comment]
I test all the command examples of https://etcd.io/docs/v3.5/dev-guide/api_grpc_gateway/ , all ok to run on etcd ver3.5.
Do you confirm that create the "root" account already ?

My example:
❯ curl -L http://localhost:2379/v3/auth/authenticate   -X POST -d '{"name": "root1", "password": "pass1"}'
{"error":"etcdserver: authentication failed, invalid user ID or password","code":3,"message":"etcdserver: authentication failed, invalid user ID or password"}
❯ curl -L http://localhost:2379/v3/auth/authenticate   -X POST -d '{"name": "root", "password": "pass"}'
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"10","raft_term":"4"},"token":"xxxxxxxx"}

**Comment by fffffreedom** [comment]
i redo the test, and it's ok, thanks

but the root and password are not base64, does this mean the Authentication api need no base64?
while other types of api need？
