### ISSUE TITLE
etcd snap 中数据丢了

### ISSUE THREAD

**Issue by wwj-2017-1117** [etcd-io/etcd#13274]
环境： etcd v3.3.15 ,  arm64 ,
reboot之后，发现数据丢了很多 ，原来db有3M数据，reboot之后只有1.2M数据。
同样的版本，在x86上，reboot之后，没有丢任何数据。

**Actively monitored security email alias for our project:**

**1. Have a user base not limited to your own organization.**

**2. Have a publicly verifiable track record up to present day of fixing security issues.**

**3. Not be a downstream or rebuild of another distribution.**

**4. Be a participant and active contributor in the community.**

**5. Accept the Embargo Policy.**

**6. Be willing to contribute back.**

**7. Have someone already on the list vouch for the person requesting membership on behalf of your distribution.**

**Comment by spzala** [comment]
Hello, please reopen with clear details if this is indeed an issue. Thanks!
