### ISSUE TITLE
The github release body has a broken link to "upgrade guide"

### ISSUE THREAD

**Issue by joejulian** [etcd-io/etcd#13276]
https://github.com/etcd-io/etcd/releases/tag/v3.5.0

The release description links to an incorrect path:
https://github.com/etcd-io/website/blob/main/content/en/docs/next/upgrades/upgrade_3_5.md
should be
https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/upgrades/upgrade_3_5.md

**Comment by spzala** [comment]
@joejulian thanks for reporting, fixed now.
