### ISSUE TITLE
Which is the ETCD3 officially recommended python client?

### ISSUE THREAD

**Issue by hqsh** [etcd-io/etcd#13285]
I have use some ETCD3 clients in python. The best one of these is https://github.com/kragniz/python-etcd3.

But all of these have a lot of bugs or the projects are not maintained now.

So, I wonder which is the ETCD3 officially recommended python client?

Thank you!

**Comment by davissp14** [comment]
That's the main client for Etcdv3 to my knowledge.  

They maintain a list of clients here: 
https://etcd.io/docs/v3.5/integrations/#python

**Comment by spzala** [comment]
@davissp14 thanks! Closing as question is answered.

**Comment by Machoney** [comment]
This list may be in need of updating as none of the packages are currently under active maintenance.
As of the day of June 21, 2024:

[kragniz/python-etcd3](https://github.com/kragniz/python-etcd3) - Client for v3  
Last commit: Aug 17 **2020**, Last Release: Mar 31 **2020**

[jplana/python-etcd](https://github.com/jplana/python-etcd) - Supports v2 
Last commit: Oct 31 2023, Last Release Mar 3,** 2017**

[russellhaering/txetcd](https://github.com/russellhaering/txetcd) - a Twisted Python library
Last Commit: Oct 28 **2013**, Last Release: Oct 1, **2013**

[cholcombe973/autodock](https://github.com/cholcombe973/autodock) - A docker deployment automation tool
Last Commit: Mar 26 **2014**

[lisael/aioetcd](https://github.com/lisael/aioetcd) - (Python 3.4+) Asyncio coroutines client (Supports v2) 
Last Commit: Dec 18, **2014**

[txaio-etcd](https://github.com/crossbario/txaio-etcd) - Asynchronous etcd v3-only client library for Twisted (today) and asyncio (future)
Last Commit: Feb 22, **2019**, Last Release: Oct 11, **2018**

[dims/etcd3-gateway](https://github.com/dims/etcd3-gateway) - etcd v3 API library using the HTTP grpc gateway
Last Commit: Aug 13, **2020**, Last Release: Jun 30, **2020**

[aioetcd3](https://github.com/gaopeiliang/aioetcd3) - (Python 3.6+) etcd v3 API for asyncio - Last Commit: Sep 30, **2020**
[Revolution1/etcd3-py](https://github.com/Revolution1/etcd3-py) - (python2.7 and python3.5+) Python client for etcd v3, using gRPC-JSON-Gateway - Last Commit: May 10, **2022**, Last Release: May 10, **2019**

Packages that are not maintained anymore, should not be officially supported as a preferred packages.

**Comment by chrislalos** [comment]
@Machoney Can you recommend an actively maintained alternatives? I haven't had any luck finding one.

**Comment by socketpair** [comment]
Personally, I stick to its http API (and websockets for watching). UNFORTUNATELY.
