### ISSUE TITLE
etcd compaction using auto-compaction-retention" param from YAML

### ISSUE THREAD

**Issue by vperi1730** [etcd-io/etcd#13296]
Please read https://etcd.io/docs/latest/reporting_bugs/

Hi Team,

I would be needing inputs on enabling auto-compaction within the etcd YAML as I am un-aware of how to configure it?

However within my 3 replicas etcd cluster, i was able to enter into one of the etcd pods to run manual commands, it seems to be working.  Following are the commands

```
To get the number for the compact
etcdctl get number -w json

To run compact:
etcdctl compact <num_from_previous_step>

To run defrag
etcdctl defrag --cluster
```

Version is 3.4.7

Now the Q is as part of etcd 3.4.7 is there a placeholder to support the compaction as well as defragmentation if incase?

**Comment by davissp14** [comment]
As far as auto-compaction goes, something like this should work. 

```
auto-compaction-mode: periodic
auto-compaction-retention: "1"
```

https://etcd.io/docs/v3.4/op-guide/configuration/#--auto-compaction-retention

**Comment by jiapeish** [comment]
Another method is by revision:

```
auto-compaction-mode: revision
auto-compaction-retention: 10000
```
