### ISSUE TITLE
Impossible to configure logging format when using zap logger

### ISSUE THREAD

**Issue by socketpair** [etcd-io/etcd#13295]
zap logger is the best, but unfortunately it's impossible in Etcd  server to change logging format. zap logger is able to log as plaintext, but JSON format settings is hardcoded in Etcd. Please add an option to change format to "console" i.e. plaintext. My use case is logging to Journald. It's not convenient for me to log JSONs to journald.

**Comment by socketpair** [comment]
Still actual

**Comment by hexfusion** [comment]
fixed via https://github.com/etcd-io/etcd/pull/13339

**Comment by hexfusion** [comment]
```
etcd --log-format console
```

**Comment by tipame** [comment]
In which version was this flag added? It is not in version 3.5...

**Comment by BBQing** [comment]
@tipame according to changelog, it is in version 3.6

**Comment by tipame** [comment]
@BBQing you are right - it is in version 3.6 (I checked on version 3.5) and not seeing the flag in the documentation for version 3.6, I decided that the feature was never delivered since 2021.
