### ISSUE TITLE
Token expiration errors

### ISSUE THREAD

**Issue by davissp14** [etcd-io/etcd#13299]
Our logs are littered with these JWT errors.  
```
{"level":"warn","ts":"2021-08-19T13:02:02.500Z","caller":"auth/jwt.go:63","msg":"failed to parse a JWT token","token":"<jwt-token>..","error":"Token is expired"}
```

I don't think it makes sense to log these as warnings, or at all for that matter.  Tokens are expected to expire and this kind of logging should be reserved for debugging.   

Etcd version: 3.5

**Comment by mitake** [comment]
Yeah I agree, let me open a PR for fixing it.

**Comment by ennekein** [comment]
Hi @mitake, we've been getting these errors with etcd v3.5.7 every time the client tries to use an expired JWT token and then naturally retries and gets a new one. Is it supposed to be fixed in that version?
