### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by zhoub** [etcd-io/etcd#13303]
Is that possible to offer an official docker image ?

Now it seems that there are images `bitname/etcd` and `rancher/etcd`, but it's still preferred to have an official distribution.

Thanks in advance.

**Comment by ptabor** [comment]
- gcr.io/etcd-development/etcd:v3.5.0
- quay.io/coreos/etcd:v3.5.0

are the 2 populated by etcd release process.
