### ISSUE TITLE
there is no progress on updating the gRPC

### ISSUE THREAD

**Issue by KaymeKaydex** [etcd-io/etcd#13316]
gRPC 1.40.0 is now available, etcd supports gRPC 1.26.0. These are 14 major versions!

**Comment by lilic** [comment]
Hey, are you talking about grpc go version? As etcd used v1.38.0 which was the latest available when we bumped last. https://github.com/etcd-io/etcd/blob/main/go.mod#L35

**Comment by KaymeKaydex** [comment]
Sorry, my bad.
