### ISSUE TITLE
How to get value size or directory size by etcdctl?

### ISSUE THREAD

**Issue by zhangkun1117** [etcd-io/etcd#13310]
I want to get value's size or dirctory's size , but not found any method ? would someone help me ?

etcdctl --endpoints="https://...:2379" --prefix --keys-only=false get /registry/leases/kube-node-lease

I can get this, but I want to get total size of prefix key by "kube-node-lease" ?

**Comment by zhangkun1117** [comment]
etcdctl --endpoints="https://*.*.*.*:2379"  --prefix --keys-only=false get /registry/leases/kube-node-lease

I can get this, but I want to  get total size of  prefix key by "kube-node-lease"  ?

**Comment by xuejipeng** [comment]
@kkkkun  Did you find a way to get the key size?

**Comment by kkkkun** [comment]
> @kkkkun Did you find a way to get the key size?

No，I just estimate its size by multi-version *  size of value.
