### ISSUE TITLE
LockServer cannot delete key from disconnected client with auth enabled

### ISSUE THREAD

**Issue by cfz** [etcd-io/etcd#13330]
here is the way to reproduce the issue:

1. start an etcd, then enable auth
```
etcd &
etcdctl user add root --new-user-password=root
etcdctl use grant-role root root
etcdctl auth enable
```
2. run the following program to simulate a disconnected lock client
```
cfz@cfz-desktop:~/ws/test-go$ cat main.go 
package main

import (
        "context"
        "fmt"
        "time"

        clientv3 "go.etcd.io/etcd/client/v3"
        "go.etcd.io/etcd/client/v3/concurrency"
        "go.etcd.io/etcd/server/v3/etcdserver/api/v3lock/v3lockpb"
)

func main() {
        cli, _ := clientv3.New(clientv3.Config{
                Endpoints:   []string{"localhost:2379"},
                Username:    "root",
                Password:    "root",
                DialTimeout: 3 * time.Second,
        })

        defer cli.Close()

        lc := v3lockpb.NewLockClient(cli.ActiveConnection())

        lockFunc := func() {
                s, _ := concurrency.NewSession(cli, concurrency.WithTTL(10))
                lc.Lock(context.TODO(), &v3lockpb.LockRequest{Name: []byte("/lock"), Lease: int64(s.Lease())})
                fmt.Printf("locked %x\n", s.Lease())
        }

        go lockFunc()
        go lockFunc()

        time.Sleep(100 * time.Millisecond)
}
cfz@cfz-desktop:~/ws/test-go$ 
cfz@cfz-desktop:~/ws/test-go$ 
cfz@cfz-desktop:~/ws/test-go$ 
cfz@cfz-desktop:~/ws/test-go$ go run main.go && etcdctl --user root:root get "" --prefix 
locked 694d7bc9c8ed382f
/lock/694d7bc9c8ed382f

/lock/694d7bc9c8ed3831

cfz@cfz-desktop:~/ws/test-go$
```
3. will observe following error log form etcd:
```
{"level":"warn","ts":"2021-09-09T17:00:45.999+0800","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"3.887µs","request":"header:<ID:7587857053778786360 > delete_range:<key:\"/lock/694d7bc9c8ed3831\" > ","response":"","error":"auth: user name is empty"}
```

the second lock is **not** expected to survive after program exit.

i think this issue is caused by the code in [concurrency/mutex](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/mutex.go#L95), in which uses server's context to delete stale keys belonged to the disconnected client. and server's context has no auth info, which will lead to the error log when kv server try to apply the delete operation.

[concurrency/election](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/election.go#L98) has similar logic, therefore, should also be vulnerable to this issue. 

passing a 'auth.AuthStore' to lock server, and using a root ctx to clientv3.NewCtxClient() should fix this.

i will submit a PR for this later

**Comment by cfz** [comment]
i cannot find a easy way to fix the problem:

the [Unlock](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/mutex.go#L95) action is performed in concurrency package, it calls 'client.Ctx()' to retrieve a context. and the 'client.Ctx()' return its internal ctx member directly.

the target  is to generate a root context with valid token on-demand, i cannot find a place neither in concurrency nor v3.Client to insert the logic without breaking the api.

AFAMHO, possible solutions are:
1. add a member in Client (i.e. ctxFunc()) to dynamic generate context, and make Client.Ctx() to use it precedently if available.
2. make concurrency package to use a Interface rather than concrete *v3.Client object. then we can decorate the behavior of the raw client.

any suggestions?

**Comment by mitake** [comment]
hi @cfz , thanks for reporting the issue. Let me check sometime next week.

**Comment by cfz** [comment]
hi @mitake, nice to see you again 😄

**Comment by mitake** [comment]
sorry for keeping you waiting @cfz … I’ve been busy for a while. I’ll take a look at this issue when I can have a time 🙏

**Comment by cfz** [comment]
no problem! take your time 😃
