### ISSUE TITLE
Expose defaultUnaryMaxRetries and to make it configurable 

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#13344]
https://github.com/etcd-io/etcd/blob/4cbb949595b7bbdc01a9d68a32b332e79025934c/client/v3/client.go#L241 uses the `defaultUnaryMaxRetries` to set the max retries, which is then [checked if it is 0 ](https://github.com/etcd-io/etcd/blob/a08cc733bb5e29f374fbc5a48b913130888cdae3/client/v3/retry_interceptor.go#L45-L46)and if it is we skip retries. But from my understanding, this can never be set or configured by users so it will always retry 100 times.

Retrying 100 times can result in very noisy logs (if the log level is warning for example), but also unnecessary retries if this is not something the user wants. I am proposing to make max retries configurable. In our (OpenShift) use case of the operator, we reconcile often enough that we do not require to retry 100 times.

Sorry if I missed something while going through the code!

**Comment by lilic** [comment]
cc @hexfusion for context, this comes from our noisy logs, where we see the retrying of unary invoker failed.

**Comment by MatteoGioioso** [comment]
Hello, was this implemented? I cannot find a way to configure it.
