### ISSUE TITLE
etcd patch release plan

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#13369]
etcd 3.5 is ready for a new patch release. We plan on cutting to cut 3.5.1 by end of the week.  Please get in any patches or communicate here if you need more time.

In addition, we are also planning a new release of 3.4.x and 3.3.x.

- [x] v3.4.17
- [x] v3.3.26
- [x] v3.5.1
- [x] v3.4.18
- [x] v3.3.27

cc @gyuho @ptabor @serathius @lilic @hasbro17

**Comment by hexfusion** [comment]
ref: https://github.com/etcd-io/etcd/issues/13244

**Comment by serathius** [comment]
I think we should wait with v3.5.1 for cherry-pick https://github.com/etcd-io/etcd/pull/13359
This is a fix for etcdctl that sends invalid authority header in v3.5.0, this causes etcd not work all all if there is a proxy/loadbalancer before etcd instance that validates authority field.

**Comment by serathius** [comment]
There is also an issue of zombie members https://github.com/etcd-io/etcd/issues/13196 
I have implemented a workaround https://github.com/etcd-io/etcd/pull/13348 that allows users to remove/fix zombie members, but we didn't implement a proper fix. @ptabor proposed to fix zombie members during wal snapshot, so a proper fix might be to force a wal snaphost during server bootstrap, but implementing and testing this would be non trivial. 

I think we should discuss if current fix is enough or we need more time to implement proper one. I think that major problem with current fix is bad user experience. If user cluster is affected and after they upgrade to v3.5 they will see zombie members (members that were previously removed). With the current fix they should be able to remove them themselves, but we might see increased number of issues people asking about this for a long time (as it will take a long time for people to adopt v3.5)

**Comment by hexfusion** [comment]
This makes sense to me thanks @serathius. I am going to raise an internal issue on this so we can get some more cycles to assist you in reviews.

**Comment by ptabor** [comment]
I think both issues are pretty serious, so we should release v3.5.1 as soon as we have reasonable mitigations. 
Postponing automated membership fixing process to v3.5.2 SGTM.

**Comment by serathius** [comment]
Both fixes planned for v3.5.1 got merged into release-3.5 branch
* https://github.com/etcd-io/etcd/pull/13375
* https://github.com/etcd-io/etcd/pull/13348

**Comment by hexfusion** [comment]
3.5.1 release is delayed `ppc64le/debian:bullseye-20210927` tag is missing from registry I have engaged maintainers for help. Once resolved I will cut the release.

**Comment by hexfusion** [comment]
New versions just cut 
- [v3.4.17](https://github.com/etcd-io/etcd/releases/tag/v3.4.17)
- [v3.3.26](https://github.com/etcd-io/etcd/releases/tag/v3.3.26)

**Comment by hexfusion** [comment]
Once the above is resolved I will cut a new version with an updated base image for release-3.4 and release-3.3

**Comment by hexfusion** [comment]
> 3.5.1 release is delayed `ppc64le/debian:bullseye-20210927` tag is missing from registry I have engaged maintainers for help. Once resolved I will cut the release.
> 
> ref: https://dockercommunity.slack.com/archives/C7GKACWDV/p1633277275351000

This issue has been resolved I will attempt new releases this week.

**Comment by super1t** [comment]
so?today can release a new tag?

**Comment by hexfusion** [comment]
Yes release will happen today

**Comment by hexfusion** [comment]
v3.5.1
 v3.4.18
 v3.3.27
 
 were released today changelog and announcements are pending.

**Comment by ptabor** [comment]
Thank you, Sam !
