### ISSUE TITLE
Error while dialing dial tcp 127.0.0.1:2379

### ISSUE THREAD

**Issue by hy0619** [etcd-io/etcd#13367]
when i start etc sever ， and use "etcdctl put foo bar"   
![image](https://user-images.githubusercontent.com/20480464/134635129-69f96b21-6de2-491a-b9cc-c9b5ec4d565c.png)
i dont know why  , help !!!

**Comment by ardaguclu** [comment]
@hy0619 I think your etcd server is unhealthy, that's why,  it returns `connection refused` error.

**Comment by spzala** [comment]
Yes, not sure what is your env and how your etcd server was started but please make you are using needed configurations - https://etcd.io/docs/v3.5/op-guide/clustering/ Also make sure no firewall issue etc that can prevent access.
