### ISSUE TITLE
My etcd instance is restarting very often and I don't know why

### ISSUE THREAD

**Issue by antoinep92** [etcd-io/etcd#13373]
I apologize in advance if it turns out this is in fact not a bug or a duplicate, but I took some time to look around and was not able to resolve this.

I have 2 identical (production and staging) bare-metal kubernetes clusters, that I deployed with kubeadm, using a single etcd node.

For a few days now our staging cluster is very unstable, and I think the culprit is etcd. We deploy pods regularly to this cluster, but other than that there has not been a major change related to the issue (like a kubernetes upgrade, etc.)

From the etcd pod's description I get:
```
Image: k8s.gcr.io/etcd:3.4.13-0
Liveness: ... #success=1 #failure=8
Startup:  ... #success=1 #failure=24
```

In the logs startup sequence seems fine (compared to another cluster), then I get a lot of warnings:
```
etcdserver: [...] request ... took too long to execute
```
But I don't think it's hardware related because `etcd_disk_backend_commit_duration_seconds` 99th percentile is at 16ms which is fine according to the [FAQ](https://etcd.io/docs/v3.5/faq/#what-does-the-etcd-warning-apply-entries-took-too-long-mean). I also checked that the disk was not full and CPU usage is reasonable.

Anyways, this goes on for a few minutes, and then I guess this causes the restart:
```
etcdserver/api/etcdhttp: /health error; QGET failed etcdserver: request timed out (status code 503)
```

I have no idea how to proceed from here, from the logs I don't understand what the underlying issue is and have no idea how to diagnose/debug this. I'd be happy to share any further info that might help.

**Comment by ahrtr** [comment]
Can you provide the etcd's yaml file and the complete etcd log?

**Comment by antoinep92** [comment]
The log: [etcd.log](https://github.com/etcd-io/etcd/files/7276146/etcd.log)
The manifest: [etcd.yaml.txt](https://github.com/etcd-io/etcd/files/7276156/etcd.yaml.txt)
 
Thanks

**Comment by ahrtr** [comment]
I see that you use hostPath volume, is there only one worker node in the K8S cluster? If not, then you need to use a volume dynamically provisioned by a CSI Driver.  Otherwise, continue to read the following comment. 

I also see that you hard code the IP address in the "advertise-xxx-urls, I assume that you define a NodePort service and the IP address is the worker node's host IP. Please confirm this. 

Please change all the listen-{client|peer|metrics}-urls to "https://0.0.0.0:{2379|2380|2381}. 

Please check the size of the file "/var/lib/etcd/member/snap/db". Please also double confirm the CPU & memory usage & disk I/O. 

Please execute the following command on the worker node as well, 
`etcdctl --endpoints=https://10.12.173.147:2379 member list -w table`

**Comment by antoinep92** [comment]
Regarding the volume mount, from a kubernetes perspective, I have multiple worker nodes, but a single master (non high availability), from an etcd perspective, I have a single node that's bound to the kubernetes master (as is kube api, scheduler, etc.). I'm aware that it's not ideal as the master node is a SPOF, but for now it's enough for me.

Regarding the IP address, it is indeed the node's host address. Keep in mind that etcd has been configured by `kubeadm` and I haven't altered the generated conf. There is no NodePort but I guess this works because the etcd pod has `hostNetwork: true` which means it can actually listen on the host address.

I changed the listen address to 0.0.0.0, I'll report back in a bit if it changes anything.

Memory seems ok (12Gb used, 2Gb cache, 2Gb free out of 16Gb available), cpu usage is below 20% with no significant spikes, disk IO is a bit more tricky. According to iotop, etcd is the main io consumer currently, frequently at about 20kb/s per etcd process, and there are multiple processes, so it often spikes at 100kb/s. The disk is an SSD, but it is shared, so the actual performance may be a bit random. That being said the cluster (including this etcd POD) has been running without etcd-related issues for 3 years now. Here is hdparm output:
```
 Timing cached reads:   13238 MB in  2.00 seconds = 6629.67 MB/sec
 Timing buffered disk reads: 1554 MB in  3.00 seconds = 517.66 MB/sec
```
So from what I can see resources usage is not an issue, but if you have suggestions on some metrics to look up, I can check them.

Thanks.

**Comment by antoinep92** [comment]
Update: problem fixed when listening on 0.0.0.0 !
Thanks again for your help :+1:

**Comment by ahrtr** [comment]
Use a command something like below,
`etcdctl --cacert path-to-ca.crt --cert path-to-cert.crt --key path-to-key.key --endpoints=https://10.12.173.147:2379 member list -w table`

Make sure the ca file used here can be used to verify etcd's certificate. For simplicity, you can use the same ca file as etcd.

**Comment by ahrtr** [comment]
Is there a flag "--initial-advertise-peer-urls=xxx" when starting the etcd?

**Comment by antoinep92** [comment]
--initial-advertise-peer-urls=https://10.12.173.147:2380

**Comment by ahrtr** [comment]
What's the etcd version? 3.4.13?  

If possible, can you share your db file (${data-dir}/member/snap/db) or the snapshot etcd.db you created previously so that I can take a look?

**Comment by kycfeel** [comment]
My life saver today. My etcd db was malfunctioning after the restore. The problem was the client and server version mismatch. I was able to restore the data properly and confirmed it's all working fine after I set the client version exactly same as the server's one. Heck yes.
