### ISSUE TITLE
etcd helm chart

### ISSUE THREAD

**Issue by rbs-cloud** [etcd-io/etcd#13379]
Hi Team.
i want to create the helm chart to store the some of the user's around 50 users.

we are working on minio for file transfer and along with providing the ldap details in minio for security purpose
i need to apply the policy through mc command and when applied the policy with user that details needs to be store in etcd db.
we have to provide the etcd endpoints in minio so that all policy details will be stored in etcd db.

for this please provide the etcd helm chart for reference.

meanwhile i have tried with below snippet code
command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
              exec etcd --name ${HOSTNAME} \
                --listen-peer-urls http://0.0.0.0:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
                --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
                --initial-cluster-token etcd-cluster-1 \
                --initial-cluster ${PEERS} \
                --initial-cluster-state new \
                --data-dir /var/run/etcd/default.etcd

i have deployed as a pod with kubectl cmd and pod is running but when i execute below cmd inside etcd application
curl http://pod-address:2379-----its gives error like 404 page not found

Could you please help on this

**Comment by ahrtr** [comment]
The error "page not found" is expected, because etcd doesn't expose a handler for path "/". Try other paths, i.e. "/health".

**Comment by baswa-cloud** [comment]
@ahrtr ,
Curl http://pod up address:2379/version---- shows the etcdserver version and cluster version 

But
How can I check if my etcd is working or not

**Comment by ahrtr** [comment]
You can try commands below, 
```
etcdctl --endpoints=xxx member list
etcdctl --endpoints=xxx endpoint status -w table
etcdctl --endpoints=xxx endpoint health -w table
```

**Comment by baswa-cloud** [comment]
Getting below error:

sh-4.4# etcdctl  --endpoints=xxx member list
{"level":"warn","ts":"2021-10-05T03:44:25.097Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002ac000/#initially=[xxx]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address xxx: missing port in address\""}
Error: context deadline exceeded
sh-4.4# etcdctl  --endpoints=http://192.168.36.70:2379  member list
2e80f96756a54ca9, started, etcd-0, http://etcd-0.etcd:2380, http://etcd-0.etcd:2379, false
7fd61f3f79d97779, started, etcd-1, http://etcd-1.etcd:2380, http://etcd-1.etcd:2379, false
b429c86e3cd4e077, started, etcd-2, http://etcd-2.etcd:2380, http://etcd-2.etcd:2379, false
sh-4.4# etcdctl  --endpoints=xxx endpoint status -w table
{"level":"warn","ts":"2021-10-05T03:46:13.165Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00000a1e0/#initially=[xxx]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address xxx: missing port in address\""}
Failed to get the status of endpoint xxx (context deadline exceeded)
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
sh-4.4# etcdctl  --endpoints=xxx endpoint health -w table
{"level":"warn","ts":1633405590.9931643,"logger":"client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00000a1e0/#initially=[xxx]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address xxx: missing port in address\""}
+----------+--------+--------------+---------------------------+
| ENDPOINT | HEALTH |     TOOK     |           ERROR           |
+----------+--------+--------------+---------------------------+
|      xxx |  false | 5.000927643s | context deadline exceeded |
+----------+--------+--------------+---------------------------+
Error: unhealthy cluster
sh-4.4#

**Comment by ahrtr** [comment]
Execute command below, 
`etcdctl --endpoints= http://etcd-0.etcd:2379, http://etcd-1.etcd:2379, http://etcd-2.etcd:2379 endpoint status -w table`

Make sure the DNS "etcd-{0|1|2|.etcd" is accessible.

**Comment by baswa-cloud** [comment]
Below is the output and about DNS command , i did not understand
sh-4.4# etcdctl --endpoints=http://etcd-0.etcd:2379,http://etcd-1.etcd:2379,http://etcd-2.etcd:2379 endpoint status -w table
+-------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT         |        ID        |  VERSION  | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://etcd-0.etcd:2379 | 2e80f96756a54ca9 | 3.6.0-pre |   20 kB |      true |      false |        15 |         75 |                 75 |        |
| http://etcd-1.etcd:2379 | 7fd61f3f79d97779 | 3.6.0-pre |   20 kB |     false |      false |        15 |         75 |                 75 |        |
| http://etcd-2.etcd:2379 | b429c86e3cd4e077 | 3.6.0-pre |   20 kB |     false |      false |        15 |         75 |                 75 |        |
+-------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
sh-4.4#

**Comment by ahrtr** [comment]
The etcd server is working well.

**Comment by baswa-cloud** [comment]
May i know the reason why we are getting below issue.
sh-4.4# etcdctl --endpoints=xxx member list
{"level":"warn","ts":"2021-10-05T06:09:12.611Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00000a1e0/#initially=[xxx]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address xxx: missing port in address\""}
Error: context deadline exceeded
sh-4.4# etcdctl --endpoints=\$ETCDCTL_ENDPOINT member list
{"level":"warn","ts":"2021-10-05T06:11:06.361Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00000a1e0/#initially=[$ETCDCTL_ENDPOINT]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address $ETCDCTL_ENDPOINT: missing port in address\""}
Error: context deadline exceeded
sh-4.4#

**Comment by baswa-cloud** [comment]
@ahrtr 
I am trying to do liveness and readiness using below
Github.com/etcd-io/etcd/issues/13340

But liveness and readiness failed,connection refused

**Comment by ahrtr** [comment]
> But liveness and readiness failed,connection refused

We are discussing and working on this issue. Please refer to the discussion in [issues/13340](https://github.com/etcd-io/etcd/issues/13340)  to get more detailed info.
