### ISSUE TITLE
The tools mode has two dependencies which license file is GPL v3

### ISSUE THREAD

**Issue by ysongshan** [etcd-io/etcd#13372]
The tools mode has two dependency，it is github.com/hexfusion/schwag with GPL v3 license file, and second is  github.com/chzchzchz/goword whitout license file.  Can we replace the software to remove dependencies.

**Comment by SwadhinMangaraj** [comment]
There is a license file associated with "chzchzchz/goword" right from the initial commit on 31st January 2016 (found at https://github.com/chzchzchz/goword/blob/117972fd7ac5b3f3deb518ca9c17ab174d06a40a/LICENSE). The license in this case is BSD 2-clause. However, the GNU GPL v3 license of hexfusion/schwag looks bad as a dependency.

**Comment by ysongshan** [comment]
Sorry，I hava a mistake, it is "github.com/akhenakh/hunspellgo" without a license file.  And it is the dependency of "chzchzchz/goword".

**Comment by hexfusion** [comment]
We can probably look at removing github.com/hexfusion/schwag I believe it is no longer needed but I have aligned the licence with etcd apache 2.0
