### ISSUE TITLE
potential memory leak when calling clientv3.Range periodically

### ISSUE THREAD

**Issue by jiapeish** [etcd-io/etcd#13410]
Hi, we observed a memory leak bug when using clientv3 Range method.

Several days ago, our production environment reported an alarm of high memory usage. After go pprof collection, it turns out that one docker running clientv3 costs about 4GB memory, which far exceeds the normal 200MB memroy usage level.

### Usage scenario
1. The etcd cluster has 3 nodes, and our business logic needs calling 'Range' every 8 seconds;
2. Our application has 3 endpoints to new the etcd client, but the log shows that it only connected to 1 etcd node(follower). It seems that the GRPC balancer don't work.
3. Ping costs about 0.1ms from client to etcd server, but the 5s-Get is timeout.

### Code:
![image](https://user-images.githubusercontent.com/23369919/136649836-2bd127e5-c8de-445f-8fa6-2d51f20198d4.png)

### ETCD logs:
ETCD clientv3/retry_interceptor.go:62 complains rpc error (code = DeadlineExceeded desc = context deadline exceeded)

### The go prof file:
![image](https://user-images.githubusercontent.com/23369919/136649201-998b892f-a1ec-4b43-9be2-52a0a815e4cb.png)

Do we have sugggestions to pinpoint this problem or any idea about what's happened to the clientv3??

Thanks,
Jiapei

**Comment by ahrtr** [comment]
If you can share a simplified prototype of your application code, and the detailed steps on how to reproduce this issue, then I may help to take a look.
