### ISSUE TITLE
Disable SemaphoreCI

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#13448]
Follow up https://github.com/etcd-io/etcd/pull/13440

Disabling it allow us to stop maintaining etcd-test images making it much easier to maintain codebase.

What we need to do:
* Confirm that supported Etcd versions don't depend on SemaphoreCI (v3.4, v3.5 should be migrated to Github Actions)
* Disable SemathoreCI
* Cleanup etcd-test images and make docker-test command.

cc @hexfusion @lilic

**Comment by serathius** [comment]
https://etcd.io/docs/v3.5/op-guide/versioning/#service-versioning-and-supported-versions states `The etcd project maintains release branches for the current version and two minor releases, 3.5, 3.4 and 3.3 currently.`
This means that before removing SemaphoreCI we should make sure that GitHub actions cover branches `release-3.5`, `release-3.4` and `release-3.3`.

**Comment by serathius** [comment]
Looks like SemaphoreCI started failing https://semaphoreci.com/etcd-io/etcd/branches/pull-request-13655/builds/4
From what I see it timesout on downloading docker image dependencies. 

I think we should start ignoring SemaphoreCI failures until problem is resolved. I could also consider removing it, however this would leave `release-3.3` branch without any testing. Based on my experiments it will be hard to migrate it to Github actions due to very old golang version. Would appreciate help with that.

cc @ptabor @ahrtr @spzala

**Comment by serathius** [comment]
Hmm, tried to enable SemaphoreCI only on release-3.3 branch. Got 500 response on their configuration page :(

**Comment by serathius** [comment]
Hmm looks like SemaphoreCI was disabled last week (around 18 April).  I don't think I did it, however I'm happy that someone did. 

![image](https://user-images.githubusercontent.com/5873433/164976523-04ade8d8-1528-43fb-be28-86100879b6d6.png)
![image](https://user-images.githubusercontent.com/5873433/164976640-ea1c7491-584c-46a6-87fe-65d2aa96f09c.png)

**Comment by ptabor** [comment]
I did... To mitigate the signal due to docker hub throttling.

niedz., 24 kwi 2022, 14:32 użytkownik Marek Siarkowicz <
***@***.***> napisał:
