### ISSUE TITLE
check perf: pass on (XL) but fail on (L) load

### ISSUE THREAD

**Issue by ant31** [etcd-io/etcd#13455]
Hi there, 

I've just performed the check perf command and I've noticed an inconsistency in the report. 

When runnig with the load=l  the test fail, but not with load=xl. Which is counter-intuitive. 

with --load=l: 
```shell
$  etcdctl  check perf --load=l      
FAIL: Throughput too low: 6643 writes/s
PASS: Slowest request took 0.026905s
PASS: Stddev is 0.001281s
FAIL
```

with --load=xl:
```shell
$ etcdctl check perf --load=xl
PASS: Throughput is 14230 writes/s
PASS: Slowest request took 0.064211s
PASS: Stddev is 0.007452s
PASS
```

The network latency between nodes is low ~0.05ms, and using good nvme drives. 

seems related to this error: 
https://github.com/etcd-io/etcd/issues/10609

**Comment by ahrtr** [comment]
When the throughput / limit <=0.9, then you will see the error message "`FAIL: Throughput too low: 6643 writes/s`".  See [check.go#L239](https://github.com/etcd-io/etcd/blob/release-3.5/etcdctl/ctlv3/command/check.go#L239)

While different loads have different sent rate, please see [check.go#L53-L74](https://github.com/etcd-io/etcd/blob/release-3.5/etcdctl/ctlv3/command/check.go#L53-L74). So " --load=xl" PASS doesn't mean that the "--load=l" will definitely result in PASS as well.

**Comment by ahrtr** [comment]
Do you always get a FAIL result for the "--load=l"?

**Comment by ant31** [comment]
> Do you always get a FAIL result for the "--load=l"?
Yes for the few times tested. Not a big deal overall... 
Could it be because of it s rate-limited around the target:  https://github.com/etcd-io/etcd/blob/release-3.5/etcdctl/ctlv3/command/check.go#L153?

**Comment by tonycasanova** [comment]
The "Large" etcdctl perf benchmark will pass around 7529 writes per second to higher.    The topology (Network/Disk/etc) might be changing or different between the L and XL tests.   I would expect L to pass if     XL passes.

**Comment by patrocinio** [comment]
I am working on this issue

**Comment by serathius** [comment]
@spzala too much K8s :)

**Comment by serathius** [comment]
Closing per https://github.com/etcd-io/etcd/pull/14111
