### ISSUE TITLE
etcd request logs

### ISSUE THREAD

**Issue by PaulFurtado** [etcd-io/etcd#13454]
As far as I can tell, etcd does not currently support any type of access logging. It would be incredibly useful for debugging if access logs were supported with information like the client IP+port and the request that was made.

I'm assuming that there is a reason why etcd does not currently support access logs after all this time, however, I could not find another issue for this or any other related documentation, so now I'm wondering if I'm missing something.

Thanks!

**Comment by ahrtr** [comment]
It's a good discussion. 

The most important use case for etcd is in K8S cluster, and the client ip should be the api-server's IP. So it makes more sense for K8S to support access log.  

Even in a non-k8s environment, usually it's the reverse proxy's (such as nginx) responsibility to provide the access log.

I will also introduce some performance decrease to print lots of access log. 

So I don't see there are any needs to add access log in etcd. But I am open to get more feedback from other engineers.

**Comment by PaulFurtado** [comment]
The biggest motivation on our end is for being able to debug issues with etcd. For example, we're repeatedly having issues where memory will jump by 100GB in just a fee minutes and we can't determine which requests led to the issue

**Comment by ahrtr** [comment]
You can set the --log-level as debug, and the log info should be enough.

BTW. It makes more sense to do a profile analysis using pprof.

**Comment by PaulFurtado** [comment]
> You can set the --log-level as debug, and it should be enough.

Thanks, we'll give this a shot. Although the concern with debug might be if there is a lot of other logging that adds further overhead than just access logs alone. Does debug log much more?

> BTW. It makes more sense to do a profile analysis using pprof.

The issue is that once etcd is down, it's too late to use pprof and we can't reproduce the problem because we don't actually know what happened without any logs after the fact.

> It will also introduce some performance decrease to print lots of access log.

Yeah, access logging does typically add CPU cost, but if etcd took even a 5-10% performance hit, it wouldn't matter much to infrastructure workloads like kubernetes, that's a tiny cost compared to everything that goes on within a request at the API server, and we've been fighting similar etcd outages for years now that are challenging to debug and reproduce without logs.

I'd also add that from a security perspective, access logs are typically an enterprise auditing requirement for databases. It's true that kubernetes provides much richer audit logs for most requests, but that doesn't help if something other than the API servers manages to gain access to etcd and directly manipulates objects.

**Comment by ahrtr** [comment]
> The issue is that once etcd is down, it's too late to use pprof and we can't reproduce the problem because we don't actually know what happened without any logs after the fact.

You can generate a core dump and then analyze it afterwards.

**Comment by PaulFurtado** [comment]
@ahrtr Unfortunately, you cannot take a core dump of etcd once it has been killed by the OOM-killer and even if you could, it would not tell you which requests led up to the OOM condition. It would also likely be slow to take the core dump on a process that is using more than 100GB of memory, especially when the primary goal is restoring service to a production cluster.

I very much agree that pprof, core dumps, etc are preferable tools for debugging memory use. However, they're really not substitutes for logs in a production environment. Especially when etcd is able to eat such a massive amount of memory in fewer seconds than it takes for a human to get paged for the memory usage.

**Comment by hexfusion** [comment]
> The biggest motivation on our end is for being able to debug issues with etcd. For example, we're repeatedly having issues where memory will jump by 100GB in just a fee minutes and we can't determine which requests led to the issue

etcd client metrics should provide more details on the traffic pattern which should help you conclude the root cause have you dug into those at all? Generally speaking, we use kube-apiserver audit logs and metrics for this type of triage. Also with debug you do have a fair amount of data in the logs itself, remote being the caller. What else would you want?

```
{
  "level": "debug",
  "ts": "2021-11-08T18:01:59.303-0500",
  "caller": "v3rpc/interceptor.go:182",
  "msg": "request stats",
  "start time": "2021-11-08T18:01:59.301-0500",
  "time spent": "2.019328ms",
  "remote": "127.0.0.1:37928",
  "response type": "/etcdserverpb.KV/Put",
  "request count": 1,
  "request size": 10,
  "response count": 0,
  "response size": 28,
  "request content": "key:\"/kubernetes.io/secrets/......................\" value_size:30 "
}
```

**Comment by hexfusion** [comment]
Another more recent tool for triage is continuous profiling[1], which has auto-discovery mechanism which makes setup easy.

[1] https://www.parca.dev/
