### ISSUE TITLE
support grpc middleware for embed server

### ISSUE THREAD

**Issue by Ehco1996** [etcd-io/etcd#13468]
i think it's helpful for many projects, i can do this work if anyone can help with the code review

**Comment by rleungx** [comment]
It's better to also support the stream interceptor.

**Comment by Ehco1996** [comment]
> It's better to also support the stream interceptor.

thanks! i will try impl stream and  unary interceptor in server ServerOption

**Comment by jiacai2050** [comment]
Anyone working on this?

I'm glad to help if maintainers still think this is useful.
