### ISSUE TITLE
request cluster ID mismatch (got 81a36b1dcb21d06f want 1e104cfab6443ed5)

### ISSUE THREAD

**Issue by lynn447742** [etcd-io/etcd#13462]
I added a new etcd node, copied the execution file and configuration file, executed "etcdctl add" in the cluster, and executed "systemctl restart etcd" on the new node, and the error was reported as follows:
"request cluster ID mismatch (got 81a36b1dcb21d06f want 1e104cfab6443ed5), request sent was ignored (cluster ID mismatch: peer[e6666cb368e6daf8]=81a36b1dcb21d06f, local=1e104cfab6443ed5)"

**Comment by ahrtr** [comment]
You need set the flag "--initial-cluster-state=existing" for the new member.

**Comment by lynn447742** [comment]
> You need set the flag "--initial-cluster-state=existing" for the new member.

thanks a lot, it works...
