### ISSUE TITLE
Consider allowing `ErrLogTemporarilyUnavailable` for Entries()

### ISSUE THREAD

**Issue by Connor1996** [etcd-io/etcd#13471]
When one node is down and back online after a while, it may probably cause other nodes to fetch a lot of entries in a short time. If the entries are not cached in storage level, it blocks for a while to fetch the entires when stepping raft message which leads to latency spike in the upper level. 

To make `Entries()` not block the whole process for a long time, maybe we can allow logs temporarily unavailable when calling `Entries()` and enable the storage level to fetch the logs in another thread.

Looking forward to hearing from your advice on that, and willing to make a contribution of it.

**Comment by BusyJay** [comment]
Besides handling `ErrLogTemporarilyUnavailable`, raft should also provide a hook to send message explicitly, which is used after entries are fetched into cache.

This is another attempt to make raft asynchronous besides #12257. #12257 makes writes asynchronous, this issue can make read asynchronous. And it's an easier and smaller change.

/cc @tbg @bdarnell

**Comment by Connor1996** [comment]
@BusyJay Maybe not bother to add a hook, just check it on ticks?

**Comment by BusyJay** [comment]
Ticks is not enough. In most cases, ticks can be triggered in seconds, and fetching entries can only takes microseconds. Waiting for ticks can lead to unnecessary commit latency.

**Comment by BusyJay** [comment]
@tbg @bdarnell @xiang90 any suggestions?
