### ISSUE TITLE
minor version downgrades instructions ?

### ISSUE THREAD

**Issue by grosser** [etcd-io/etcd#13482]
I saw a few PRs and issues around downgrading like 
https://github.com/etcd-io/etcd/pull/11919
https://github.com/etcd-io/etcd/pull/13022
https://github.com/etcd-io/etcd/issues/11716

but no instructions on how to actually do that `--unsafe-allow-cluster-version-downgrade` does not exist and neither does `etcd downgrade`, so how is this supposed to work ?

@gyuho

**Comment by serathius** [comment]
Hey, original effort on downgrade is no longer active. I have proposed a alternative design and I'm tracking implementation in https://github.com/etcd-io/etcd/issues/13168. However we are not yet ready to make this work available to users as we are still testing and verifying correctness. 

Please follow up on the issue linked above if you want to get involved.
