### ISSUE TITLE
etcd3.5.0: Is it normal that the watch module has a change from version 3.4?

### ISSUE THREAD

**Issue by redriverhong** [etcd-io/etcd#13517]
In 3.4.x, if a key is deleted, the key and value are returned. However, in 3.5.0, only the key is returned.
Verification Procedure：
3.4.10
![image](https://user-images.githubusercontent.com/11647782/144805598-1110b5ca-1b5c-4264-a3b9-9e355422063a.png)
![image](https://user-images.githubusercontent.com/11647782/144805667-c509db84-89a6-4e09-8e91-60fbb937e352.png)

3.5.0
![image](https://user-images.githubusercontent.com/11647782/144806007-444fb897-546e-4d26-94fa-082f1da0a24d.png)
![image](https://user-images.githubusercontent.com/11647782/144806044-fb9a5590-bce2-496f-b730-2306d28e7445.png)

**Comment by ahrtr** [comment]
I can't reproduce this issue on 3.4.10. Instead, the behavior is consistent between 3.4.10 and 3.5.0. Please run  `etcd --version` and `etcdctl version` to double confirm the versions. 

Did you update source code and build the binaries yourself?

**Comment by redriverhong** [comment]
> I can't reproduce this issue on 3.4.10. Instead, the behavior is consistent between 3.4.10 and 3.5.0. Please run `etcd --version` and `etcdctl version` to double confirm the versions.
> 
> Did you update source code and build the binaries yourself?

Yes, we made a modification, thank you.
