### ISSUE TITLE
Little mistake at install command for macOS (Darwin)

### ISSUE THREAD

**Issue by Zjmainstay** [etcd-io/etcd#13512]
There is a little mistake at the install command for macOS (Darwin), not only the version at v3.5.1.
Please repair it, thank you!

<img width="907" alt="error-command" src="https://user-images.githubusercontent.com/3349634/143863809-ade3dd9b-b136-4e1b-b1c7-94ae2389a3c3.png">

**Comment by serathius** [comment]
Fixed in last minor release, v3.5.0, v3.5.1, v3.5.2.
