### ISSUE TITLE
etcdctl make-mirror crashed without any error information.

### ISSUE THREAD

**Issue by laixintao** [etcd-io/etcd#13511]
Hi, we have an `etcdctl make-mirror` process running for backup purpose. It runs normally until one day we did a stress test (which created high qps again our etcd server), after that, the etcdctl mirror process crashed, and can not finish the `SyncBase`.

I find no error information nor logs from etcdctl process, any suggestions for me about where can I check this? thanks.

some information about our setup:
```
systemctl cat etcd_mirror
# /etc/systemd/system/etcd_mirror.service
[Unit]
Description=Making mirror from old to new etcd cluster
Documentation=https://github.com/etcd-io/etcd

[Service]
User=root
Group=root
ExecStart=etcdctl make-mirror http://<ip-omitted>:2379 --user=xxx:yyy
Restart=always
RestartSec=20

[Install]
WantedBy=multi-user.target
```

```
systemd[1]: Started Making mirror from old to new etcd cluster.
etcdctl[232812]: 15126
etcdctl[232812]: 30299
etcdctl[232812]: 45098
etcdctl[232812]: 60294
etcdctl[232812]: 72321
etcdctl[232812]: 80344
etcdctl[232812]: 87954
etcdctl[232812]: 94798
etcdctl[232812]: 101501
etcdctl[232812]: 107981
etcdctl[232812]: 114677
etcdctl[232812]: 120958
etcdctl[232812]: 128069
etcdctl[232812]: 135138
etcdctl[232812]: Error: <nil>
```

```
etcd --version
etcd Version: 3.4.9
Git SHA: 54ba95891
Go Version: go1.12.17
Go OS/Arch: linux/amd64
```

**Comment by ahrtr** [comment]
Looks like the messages are printed by your application? Note that etcd printes an error to os.Stderr when this command fails. 
```
etcdctl[232812]: 128069
etcdctl[232812]: 135138
etcdctl[232812]: Error: <nil>
```

**Comment by laixintao** [comment]
hi @ahrtr thanks for replying.

This message was from systems (syslog), I think it is printed by `etcdctl make-mirror` process.

I guess this is the line of printing code. It means total keys that have been synced I guess?

https://github.com/etcd-io/etcd/blob/7572a61a39d4eaad596ab8d9364f7df9a84ff4a3/etcdctl/ctlv3/command/make_mirror_command.go#L136

**Comment by laixintao** [comment]
BTW, we have tried to delete every thing from target etcd cluster, it didn't work. We end up with rebuild a new hot backup etcd cluster (make mirror target).

**Comment by ahrtr** [comment]
The point is that the Error printed by syslog was nil. Just as I mentioned previously, etcd prints an error to os.Stderr when the command fails. So probably the error was not printed correctly by syslog? 

Another big concern is about the behavior of the make-mirror command. When the process(`etcdctl make-mirror ...`) is restarted for whatever reason, then it will try to copy (get from the source, and put to the destination) the whole key spaces again. Obviously it will take a long long time if the key space is huge. I am thinking whether it's possible to enhance the command to support incrementally copying the key space, otherwise it makes little sense. What do you think? @ptabor @xiang90 @sinsharat

**Comment by laixintao** [comment]
> Just as I mentioned previously, etcd prints an error to os.Stderr when the command fails. So probably the error was not printed correctly by syslog?

Maybe, I checked every where, there is no more logs from etcd make mirror process. But our systemd file is too simple to be wrong.

> ... then it will try to copy (get from the source, and put to the destination) the whole key spaces again.

Yes, this is indeed a problem. In our case, the etcd make-mirror is restarting all the time, then try to copy data from scratch again, then it crashed halfway, then it gets restarted again, and again. It ends up with a super huge database(previous data is not deleted). However, I have no solutions for this, only posting our situations. Hope it can help.

**Comment by ahrtr** [comment]
> Maybe, I checked every where, there is no more logs from etcd make mirror process. But our systemd file is too simple to be wrong.

You can try to manually run the `etcdctl make-mirror ...` command, to check what's the error. My PR [pull/13519](https://github.com/etcd-io/etcd/pull/13519) could be a solution for this issue. But it may need some additional effort for your application to remember & configure the rev on startup.

**Comment by laixintao** [comment]
Hi sorry I lost the scene. We need to rebuild Etcd cluster to make it work.

But I actually did this, IIRC the output is the same as `journalctl` shows:

```
etcdctl[232812]: 15126
etcdctl[232812]: 30299
etcdctl[232812]: 45098
etcdctl[232812]: 60294
etcdctl[232812]: 72321
etcdctl[232812]: 80344
etcdctl[232812]: 87954
etcdctl[232812]: 94798
etcdctl[232812]: 101501
etcdctl[232812]: 107981
etcdctl[232812]: 114677
etcdctl[232812]: 120958
etcdctl[232812]: 128069
etcdctl[232812]: 135138
etcdctl[232812]: Error: <nil>
```

sth like this without `etcdctl[232812]:`.

**Comment by ahrtr** [comment]
If the error is nil, then the only possible reason is that it returns at [make_mirror_command.go#L220](https://github.com/etcd-io/etcd/blob/20bf96dc40f5f3b27d1130a0c9bd21f0888a41f8/etcdctl/ctlv3/command/make_mirror_command.go#L220).  So need further investigation.
