### ISSUE TITLE
tcd Version: 3.5.1 watch chan error: etcdserver: no leader 

### ISSUE THREAD

**Issue by vupv** [etcd-io/etcd#13510]
I have used ETCD as external for the Kubernetes cluster but got an error during the init about no leader related to ETCD

So how can I verify the ETCD cluster is working fine or not even I can list members and put the key

root@master01:~# ETCDCTL_API=3 etcdctl member list
123c02beae00dc2d, started, 192.168.1.85, https://192.168.1.85:2380, https://192.168.1.85:2379, false
163611f60028fb12, started, 192.168.1.87, https://192.168.1.87:2380, https://192.168.1.87:2379, false
531a86cf76f6bb38, started, 192.168.1.86, https://192.168.1.86:2380, https://192.168.1.86:2379, false

root@master01:~# cat /etc/systemd/system/etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
ExecStart=/usr/local/bin/etcd \
  --name 192.168.1.85 \
  --cert-file=/etc/etcd/kubernetes.pem \
  --key-file=/etc/etcd/kubernetes-key.pem \
  --peer-cert-file=/etc/etcd/kubernetes.pem \
  --peer-key-file=/etc/etcd/kubernetes-key.pem \
  --trusted-ca-file=/etc/etcd/ca.pem \
  --peer-trusted-ca-file=/etc/etcd/ca.pem \
  --peer-client-cert-auth \
  --client-cert-auth \
  --initial-advertise-peer-urls https://192.168.1.85:2380 \
  --listen-peer-urls https://192.168.1.85:2380 \
  --listen-client-urls https://192.168.1.85:2379,http://127.0.0.1:2379 \
  --advertise-client-urls https://192.168.1.85:2379 \
  --initial-cluster-token etcd-cluster-1 \
  --initial-cluster 192.168.1.85=https://192.168.1.85:2380,192.168.1.86=https://192.168.1.86:2380,192.168.1.87=https://192.168.1.87:2380 \
  --initial-cluster-state new \
  --data-dir=/var/lib/etcd
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
root@master01:~#

[api.log](https://github.com/etcd-io/etcd/files/7612060/api.log)

**Comment by ahrtr** [comment]
I see there were some "leader changed" error. It means that the performance or network of the etcd cluster isn't good.  

```
$ cat api.log  | grep "leader chang"
E1127 16:04:43.466112       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:04:45.733151       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:04:45.733424       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:05:39.900682       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:05:40.301624       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:05:57.471574       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:06:14.938107       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:06:45.474876       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:07:47.106187       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:08:46.877598       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
E1127 16:08:47.851990       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: leader changed"}: etcdserver: leader changed
```

Please change the etcd command line parameters as below firstly,
```
--listen-peer-urls https://0.0.0.0:2380
--listen-client-urls https://0.0.0.0:2379
```


If you still see the issue, then please check the following info:
1. The network connectivity & latency between the etcd members, you can try to ping each other;
2. The disk IO, try to get the metrics, see [metrics](https://etcd.io/docs/v3.5/metrics/);
3. The memory & CPU usage of each etcd node;
4. Run "etcdctl --endpoints https://192.168.1.85:2379,https://192.168.1.86:2379,https://192.168.1.87:2379 endpoint status -w table"

**Comment by vupv** [comment]
root@master01:~# etcdctl --endpoints http://127.0.0.1:2379 endpoint status -w table
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|       ENDPOINT        |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://127.0.0.1:2379 | 123c02beae00dc2d |   3.5.1 |  2.2 MB |     false |      false |       793 |      48378 |              48378 |        |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
root@master01:~#

**Comment by vupv** [comment]
[localhost.txt](https://github.com/etcd-io/etcd/files/7612599/localhost.txt)
[ip.txt](https://github.com/etcd-io/etcd/files/7612600/ip.txt)

I try to query to endpoint from localhost is okay, but though IP with HTTPS they didn't work

**Comment by vupv** [comment]
[IP_include_cert.txt](https://github.com/etcd-io/etcd/files/7612609/IP_include_cert.txt)

**Comment by vupv** [comment]
After increasing the two below agurment I see another error 
  --heartbeat-interval '1000'
  --election-timeout '10000'

[api.log](https://github.com/etcd-io/etcd/files/7612645/api.log)


E1128 00:59:04.979967       1 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
E1128 00:59:04.979990       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1128 00:59:04.980015       1 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 10.2µs, panicked: false, err: context deadline exceeded, panic-reason: <nil>
E1128 00:59:04.981675       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout

**Comment by ahrtr** [comment]
You need to provide the following flags when executing etcdctl,
```
--cacert
--cert 
--key
```

Have you tried the following command parameters?
```
--listen-peer-urls https://0.0.0.0:2380
--listen-client-urls https://0.0.0.0:2379
```

**Comment by vupv** [comment]
After changing the etcd.service like as below. Right?

root@master01:~# cat  /etc/systemd/system/etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos


[Service]
ExecStart=/usr/local/bin/etcd \
  --name 192.168.1.85 \
  --cert-file=/etc/etcd/kubernetes.pem \
  --key-file=/etc/etcd/kubernetes-key.pem \
  --peer-cert-file=/etc/etcd/kubernetes.pem \
  --peer-key-file=/etc/etcd/kubernetes-key.pem \
  --trusted-ca-file=/etc/etcd/ca.pem \
  --peer-trusted-ca-file=/etc/etcd/ca.pem \
  --peer-client-cert-auth \
  --client-cert-auth \
  --initial-advertise-peer-urls https://192.168.1.85:2380 \
  --listen-peer-urls https://0.0.0.0:2380 \
  --listen-client-urls https://0.0.0.0:2379 \
  --advertise-client-urls https://192.168.1.85:2379 \
  --initial-cluster-token etcd-cluster-1 \
  --initial-cluster 192.168.1.85=https://192.168.1.85:2380,192.168.1.86=https://192.168.1.86:2380,192.168.1.87=https://192.168.1.87:2380 \
  --initial-cluster-state new \
  --data-dir=/var/lib/etcd \
  --heartbeat-interval '1000' \
  --election-timeout '10000'
Restart=on-failure
RestartSec=5


[Install]
WantedBy=multi-user.target
root@master01:~#

**Comment by vupv** [comment]
root@master01:~#  etcdctl --endpoints https://192.168.1.85:2379,https://192.168.1.86:2379,https://192.168.1.87:2379 endpoint status -w table --cert=/etc/etcd/kubernetes.pem --key=/etc/etcd/kubernetes-key.pem --cacert=/etc/etcd/ca.pem
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|         ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://192.168.1.85:2379 | 123c02beae00dc2d |   3.5.1 |  2.2 MB |      true |      false |       918 |      75031 |              75031 |        |
| https://192.168.1.86:2379 | 531a86cf76f6bb38 |   3.5.1 |  2.2 MB |     false |      false |       918 |      75031 |              75031 |        |
| https://192.168.1.87:2379 | 163611f60028fb12 |   3.5.1 |  2.2 MB |     false |      false |       918 |      75031 |              75031 |        |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
root@master01:~#

**Comment by vupv** [comment]
[kube-apiserver.log](https://github.com/etcd-io/etcd/files/7613032/kube-apiserver.log)

**Comment by vupv** [comment]
[kube-controller-manager.log](https://github.com/etcd-io/etcd/files/7613033/kube-controller-manager.log)

**Comment by vupv** [comment]
The init still fail

**Comment by ahrtr** [comment]
Read my previous comments and also [Transport security model](https://etcd.io/docs/v3.5/op-guide/security/)

**Comment by suning2012** [comment]
要区分这两个： IS LEADER ，  IS LEARNER 

```[root@240 etcd-v3.5.1-linux-amd64]# ./etcdctl --endpoints=$ENDPOINTS  -w=table endpoint status
+---------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|      ENDPOINT       |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+---------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 192.168.58.241:2379 | 9ae67dc7516ed9c9 |   3.5.1 |   20 kB |      true |      false |         3 |         11 |                 11 |        |
| 192.168.58.242:2379 | 2b09c84a2331e706 |   3.5.1 |   20 kB |     false |      false |         3 |         11 |                 11 |        |
| 192.168.58.243:2379 | ac586ed50b785b91 |   3.5.1 |   20 kB |     false |      false |         3 |         11 |                 11 |        |
+---------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
[root@240 etcd-v3.5.1-linux-amd64]# ./etcdctl --endpoints=$ENDPOINTS  --write-out=table  member list
+------------------+---------+-----------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |   NAME    |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+-----------+----------------------------+----------------------------+------------+
| 2b09c84a2331e706 | started | machine-2 | http://192.168.58.242:2380 | http://192.168.58.242:2379 |      false |
| 9ae67dc7516ed9c9 | started | machine-1 | http://192.168.58.241:2380 | http://192.168.58.241:2379 |      false |
| ac586ed50b785b91 | started | machine-3 | http://192.168.58.243:2380 | http://192.168.58.243:2379 |      false |
+------------------+---------+-----------+----------------------------+----------------------------+------------+
```
