### ISSUE TITLE
Etcd doesn't catch recreated control files

### ISSUE THREAD

**Issue by aryabchenko** [etcd-io/etcd#13522]
Etcd v: 3.4.13
kubernetes v: 1.20.9

I deleted backup control files using S3 lifecycle rule and backups stopped to work.
I recreated both etcd-cluster-created (with current timestamp in nanoseconds) and etcd-cluster-spec (with correct version and number of members) but ectd doesn't want to catch them. In logs I see:

I1208 04:22:45.576528    3862 s3fs.go:290] Reading file "s3:/mybucket/backups/etcd/main/control/etcd-cluster-created"
I1208 04:22:45.722643    3862 controller.go:392] no cluster spec set - must seed new cluster

It looks like it doesn't want to read etcd-cluster-spec at all.
I deleted leader etcd-manager-main pod and checked logs - all in vain.
The same issue for events control files/pods. 

How to fix it?

**Comment by aryabchenko** [comment]
For a reference:
etcd-cluster-created:
`{"timestamp":1638935701000000000}`

etcd-cluster-spec
`{
  "memberCount": 3,
  "etcdVersion": "3.4.13"
}
`

**Comment by skamchiline** [comment]
I have the same issue. Was the solution found? 
I've tried steps from here: https://githubmate.com/repo/kopeio/etcd-manager/issues/299 no result.

**Comment by skamchiline** [comment]
```
I deleted leader etcd-manager-main pod
```
You don't need to delete not the pod but the container on the host. Then it works. Use this command on the host with  LEADER main etcd. Non leader would not do the trick. 
```
sudo docker ps | grep k8s_etcd-manager_etcd-manager-main | cut -d" " -f1 | xargs sudo docker kill
```
Then find the events leader and run this on the host with events leader:
```
sudo docker ps | grep k8s_etcd-manager_etcd-manager-events | cut -d" " -f1 | xargs sudo docker kill
```
