### ISSUE TITLE
metrics are reported for removed members

### ISSUE THREAD

**Issue by acastong** [etcd-io/etcd#13520]
After a member is removed, etcd 3.4.18 will still report statistics for that member.  For example, if member 1b177284aa65b0fd is removed, the following metrics will be displayed:

```
etcd_network_active_peers{Local="61c4f4f756036f56",Remote="1b177284aa65b0fd"} 0
etcd_network_active_peers{Local="61c4f4f756036f56",Remote="1d6e8617d416b003"} 1
etcd_network_active_peers{Local="61c4f4f756036f56",Remote="4de616742959b729"} 1
```

Restarting the etcd process removes the reporting of that old member.

### Why is it a problem

Alerting rules proposed on awesome-prometheus-alert to detect a problem with etcd members (see https://awesome-prometheus-alerts.grep.to/rules.html#rule-etcd-1-1 ) uses  `count(etcd_server_id) % 2 == 0`: it just check that the number of active servers is odd.  In most 3-membercluster, if you are down to 2 membersthis will correctly report the problem.  But in a 5-membercluster that was down to 3, it would report everything as ok: this is not what we want.

Ideally we should be able to use metrics to detect how many nodes are present and if we have inactive peers instead.  The `etcd_network_active_peers` metrics seems perfect for that: if it is reporting 0 for some peers, we would want to raise an alert.

But since it continues reporting 0 after a member is removed, that strategy cannot be used: as soon as the topology would change, an alert would be raised.

### How to reproduce

1. Start a 3-member etcd cluster, set variable `$members` to the list of members  
2. List members: `etcdctl --endpoints=$members member list`, set `$member3` as the last member ID and `$member3_name` as its name, `$member3_ip` as its IP
2. Stop member 3 `etcdctl --endpoints=$members  member remove $member3`
3. Wipe the data of member 3, make sure its configuration file is set to `initial-cluster-state: 'existing'`
4. Add member 3 again: `etcdctl --endpoints=$members member add $member3_name --peer-urls=http://$member3_ip:2380'`
5. Display metrics for member 1: `http://$member1_ip:2379/metrics`
6. Look for `etcd_network_active_peers metrics`, it will show both the new ID of the third member, as well as the original `$member3`

**Comment by ahrtr** [comment]
Based on the [CHANGELOG-3.4.md#metrics-monitoring](https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.4.md#metrics-monitoring-8), it's expected behavior. 

It seems that `count(etcd_server_id) ` just means the number of members instead of the number of active members.

**Comment by acastong** [comment]
Hi @ahrtr , the [CHANGELOG-3.4.md#metrics-monitoring](https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.4.md#metrics-monitoring-8) says:

>  This indicates that the local node "7339c4e5e833c029" currently has two active remote peers "729934363faa4a24" and "b548c2511513015" in a 3-node cluster.

In the example data I am showing, we see three `etcd_network_active_peers` reported even though we are still in a three node cluster (`etcdctl member list` still reports 3 nodes). So I believe this is not expected behavior.

I also attached the full metrics from such a situation ([etcd_metrics.txt](https://github.com/etcd-io/etcd/files/7676204/etcd_metrics.txt) ).  We can see etcd_server_id being reported correctly, so that part is correct.  Since every responding etcd node produces one etcd_server_id, the `count(etcd_server_id) ` promql only displays the number of currently responding nodes. 

So we have no way of telling what is the expected size of the cluster from metrics currently.

**Comment by ahrtr** [comment]
See
`If the node "b548c2511513015" is down, the local node "7339c4e5e833c029" will show etcd_network_active_peers{Local="7339c4e5e833c029",Remote="729934363faa4a24"} 1 and etcd_network_active_peers{Local="7339c4e5e833c029",Remote="b548c2511513015"} 0.`

Either a member is down or it's removed, the value for etcd_network_active_peers will be 0. My understanding is that Prometheus is a time-series database, it can only change the value of a metrics over time. In other words, it can't remove a metrics or it can't change the history.  Because all the local metrics are just in memory, so restarting etcd can "remove" the metrics for removed member.  But if you have a centralized Prometheus server, then it will have all the history metrics; of course, it also depends on how long of the history data it keeps. 

Can you just count the etcd_network_active_peers with 1?

**Comment by acastong** [comment]
When you create [Prometheus alerting rules](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/), you create a condition to trigger the alert and it will be evaluated on the instantaneous latest data.  When the condition is met for a specified amount of time (the for clause), then the alert is triggered.

Yes we can certainly create an alerting rules that counts the number of etcd_network_active_peers, but from the current metrics, currently it's not possible to know what is the target value for that count (what is the size of the cluster). 

One alternative is that if the prometheus server is automatically configured to monitor all the nodes. You can check how many etcd targets are configured `count(up{job="etcd-exporter-job-name"})`: that could be used in a rule to work around this issue.  But this requires hardcoding the job-name in the rule so it is not ideal.

**Comment by ahrtr** [comment]
The metrics `etcd_network_known_peers` should can be used to figure out the number of cluster members, see [metrics.go#L27](https://github.com/etcd-io/etcd/blob/29292aa7bdafaf65cb5e054591fe0ff07b36f5ee/server/etcdserver/api/membership/metrics.go#L27). 

But unfortunately, it is only in the main branch (3.6).

**Comment by ahrtr** [comment]
FYI. test result on 3.6/main on a cluster with 3 members,

```
$ curl http://127.0.0.1:2379/metrics  | grep etcd_network_known_peers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP etcd_network_known_peers The current number of known peers.
# TYPE etcd_network_known_peers gauge
etcd_network_known_peers{Local="8211f1d0f64f3269",Remote="8211f1d0f64f3269"} 1
etcd_network_known_peers{Local="8211f1d0f64f3269",Remote="91bc3c398fb3c146"} 1
etcd_network_known_peers{Local="8211f1d0f64f3269",Remote="fd422379fda50e48"} 1
100  155k    0  155k    0     0  50.6M      0 --:--:-- --:--:-- --:--:-- 50.6M
```
