### ISSUE TITLE
Need some information about etcd data dir failures

### ISSUE THREAD

**Issue by ishan16696** [etcd-io/etcd#13521]
This is the directory structure of etcd data dir.
```console
default.etcd
└── member
    ├── snap
    │   └── db
    └── wal
        └── 0000000000000000-0000000000000000.wal
```
**In a single node etcd**, the deletion of the either member dir or db file  will leads to etcd will get crash and I'm unable to put any data .... this seems to be a expected behaviour.
But in a **multi node etcd**, I have deleted the member dir or db file of all `etcd cluster members` but still etcd is running fine and even I'm able to put some data .... Isn't it supposed to be crashed ? Please enlighten 

etcd Version: 3.5.0 which I'm using

**Comment by ahrtr** [comment]
The behavior is consistent between a single node and an etcd cluster with multiple members. 

When removing the member directory, then the etcd instance will crash for sure, and the error message is something like "no such file or directory". 

When removing the db file, the etcd can still serve client request, and this could be an issue. I will try to figure out the root cause and provide a PR. When you try to start the crashed etcd again, if there are some local snapshot files, then the etcd will crash again, and the error message is something like "failed to find [SNAPSHOT-INDEX].snap.db".  If there is no local snapshot file, then etcd will replay the WAL file, and regenerate the db file automatically.

**Comment by ahrtr** [comment]
The etcd instance can still serve client requests after removing the db file, and it should be expected behavior. The db file is actually not really removed by OS until the the process(etcd) stops and closes the file.

**Comment by ishan16696** [comment]
> The etcd instance can still serve client requests after removing the db file, and it should be expected behavior. The db file is actually not really removed by OS until the the process(etcd) stops and closes the file.

If that is the case then why we are not seeing the same behaviour in single node etcd when we removed the db file?
And how we are still able to put data when all db files of all etcd members has been already removed?

**Comment by ahrtr** [comment]
Actually it has nothing to do with etcd. Please see the following example. If you add a break-point at line 18, and remove the "/tmp/db" file when the program stops at the break-point; afterwards, continue to run the program, everything will be working well.

```
package main

import (
	"fmt"
	"os"
)

func main() {
		f, err := os.OpenFile("/tmp/db", os.O_RDWR | os.O_CREATE, 0666)
		if err != nil {
			panic(err)
		}

		if n, err := f.Write([]byte{1, 2, 3, 4, 5}); err != nil || n != 5 {
			panic (err)
		}

		if n, err := f.Write([]byte{6, 7, 8}); err != nil || n != 3 {   //############# line 18
			panic (err)
		}

		if err := f.Sync(); err != nil {
			panic (err)
		}

		if err := f.Close(); err != nil {
			panic(err)
		}

		fmt.Println("Done!")
}
```

What's the platform you performed your test on? Please also double confirm both the etcd and etcdctl versions.

**Comment by ishan16696** [comment]
Hi @ahrtr ,
thanks for your explanation .... I got your  point.

> What's the platform you performed your test on? Please also double confirm both the etcd and etcdctl versions.

etcd Version: 3.5.0
etcdctl version: 3.5.0
Platform: MacOS Monterey and running multi-node etcd as a process as well as I tried with multi-node etcd running as k8s pods, exec into the each pods and removed the db file.

**Comment by ishan16696** [comment]
Closing  this issue.
I will reopen it if I found some more information or some suspicious behaviour.
Thanks @ahrtr for your useful input.
