### ISSUE TITLE
etcd gateway to ipv6 peer

### ISSUE THREAD

**Issue by LetoLetoD** [etcd-io/etcd#13548]
Versions: 3.2.32, 3.3.27, 3.5.1.
Reproducible: always
Steps:
1. Start gateway to ipv6 peer:
etcd gateway start **--endpoints=[fc00::ccf0]:2379** --listen_addr=127.0.0.1:2379 --retry_delay=3s
Result: gateway started with wrong target ip format:
{"level":"info","ts":1640030987.3506703,"caller":"tcpproxy/userspace.go:87","msg":"ready to proxy client requests","endpoints":["**fc00::ccf0:2379**"]}
2. To ensure that ip format is wrong just try to put some value through gateway:
etcdctl put greeting "Hello, etcd"
Result: value save error, and at etcd gateway console window log message:
{"level":"warn","ts":1640030987.7910593,"caller":"tcpproxy/userspace.go:178","msg":"deactivated endpoint","address":"fc00::ccf0:2379","interval":3,"error":"dial tcp: address **fc00::ccf0:2379: too many colons in address**"}

**Comment by ahrtr** [comment]
It looks like a bug of the etcd gateway. Thanks @LetoLetoD for the finding. 

I will submit a PR soon.
