### ISSUE TITLE
Got: Error from server: etcdserver: mvcc: required revision is a future revision  from command: kubectl get nodes 

### ISSUE THREAD

**Issue by superkjp** [etcd-io/etcd#13547]
Configuration for our ETCD cluster: 
Version: 3.5.0
Configuration: 3 nodes, with 8 CPU and 16 MEM

For one day our Kubernetes cluster is running okay, but suddenly I got data inconsistent from Grafana dashboard which I keep looking for the gap between ETCD endpoints. 
At the same time, sometimes I got an error from the command line using: 
kubectl get nodes  -> "Error from server: etcdserver: mvcc: required revision is a future revision"

Our ETCD cluster current status:
+----------------------+------------------+--------+-------+-----+------+-----+-------------+---------------+----+
|     ENDPOINT    |   ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------+------------------+--------+-------+-----+------+-----+-------------+---------------+----+
| https://endpoint1:2379 | bf5b1f2859cb61ac    | 3.5.0 |  1.7 GB |  true |  false |     15 | 1772018932 |     1772018932 |        |
| https://endpoint2:2379 | 9ed7367646c1b52a | 3.5.0 |  1.7 GB | false |  false |     15 | 1772018941 |     1772018941  |        |
| https://endpoint3:2379 | 3e3ec693f79ba907  | 3.5.0 |  1.7 GB | false |  false |     15 | 1772018950 |     1772018947 |        |
+----------------------+------------------+---------+-------+-----+----- +-----+-------------+---------------+----+

There are 1285 Kubernetes nodes (6 master nodes and 1279 worker nodes)

The moment that data inconsistent happened 

<img width="624" alt="file_diff1" src="https://user-images.githubusercontent.com/12517273/146683347-36fbbfd4-1134-467d-a231-2543db7a8a11.png">

![WechatIMG1257](https://user-images.githubusercontent.com/12517273/146683446-b1a1483d-60b4-4c35-af34-12d8feb83164.jpeg)

After 1 week our ETCD cluster now:
![WechatIMG1259](https://user-images.githubusercontent.com/12517273/146683734-a343aca8-6628-472d-a7ea-262aa43568f9.jpeg)

And we still get the error with:
"Error from server: etcdserver: mvcc: required revision is a future revision" after we tried to get the whole info related with nodes/pods/namespaces etc through our Kubernetes cluster.

Any idea how does this happen

**Comment by ahrtr** [comment]
It looks like a serious problem. The leader's applied index is behind the followers' values. Could you provide the complete log of each etcd instance? 

What's the exactly K8s version? It looks like 1.22.x?

**Comment by ptabor** [comment]
Could you, please check 2 things across the replicas:

1. RAFT consistent index across the members:
```
go  install go.etcd.io/bbolt/cmd/bbolt@latest

go run go.etcd.io/bbolt/cmd/bbolt get ./default.etcd/member/snap/db meta consistent_index  | hexdump
```

2. What revisions got replicated to specific bbolt files: 

For this I had created a variant of bbolt cmd: https://github.com/ptabor/bbolt/tree/20211220-bbolt_cmd_format that supports: `keys --format=hex flag`: https://github.com/etcd-io/bbolt/pull/306

```
~/go/bin/bbolt keys --format=hex .//default.etcd/member/snap/db key | tail
```

Does the different backends containing different revisions ?

**Comment by superkjp** [comment]
> It looks like a serious problem. The leader's applied index is behind the followers' values. Could you provide the complete log of each etcd instance?
> 
> What's the exactly K8s version? It looks like 1.22.x?

Thanks for the quick response, let me provide more info in order to make things clear.

Our Kubernetes version: v1.18.6
Our ETCD version: 3.5.0

How to provision ETCD cluster: 
with 3 virtual machines, 8CPU, 16GB of MEM, 10GB for data persistent(HDD), installed via binary ETCD yum package 
Authentication: TLS, with peer to peer authentication

To get our etcd_log, by typing: wget https://github.com/superkjp/ETCD_Issue/blob/main/etcd-log.tar.gz (can be extracted via tar -zxvf etcd-log.tar.gz) 
Or direct download the file from: https://github.com/superkjp/ETCD_Issue/blob/main/etcd-log.tar.gz

We can only extract the log from Dec 17th as the data-inconsistent happened the week before that day Dec 9th(forgot to keep the log persistently). And because I also noticed that the index on the follower is faster than the leader's as well. I switched the leader to the one that has the latest index by using: etcdctl move-leader 3e3ec693f79ba907(the one that gets the most updated index), hope that works, but unfortunately, no good news.

Then I began trying to fix ETCD cluster by:
1. making sure the leader owns the latest index(as I describe in the pre-procedure, etcdctl move-leader ... command)
2. removing the rest followers(for those 2 followers, /data folder had been completely removed, uninstalled ETCD. You can imagine that the host as been completely initialized)
3. installing version-3.5.0 etcd again and add them back to the cluster

Timeline(to make it as simple as easy understanding as possible):
<img width="1802" alt="ETCD" src="https://user-images.githubusercontent.com/12517273/146789451-0c6aaa1d-5ba5-4086-8495-a27856da420c.png">

**Comment by ahrtr** [comment]
Thanks for the detailed info. 

Please note that K8s 1.18.6 is supposed to work with etcd 3.4.3, please see [v1.18.6/go.mod#L123](https://github.com/kubernetes/kubernetes/blob/v1.18.6/go.mod#L123), in which the 3cf2f69b5738 is the SHA for git tag v3.4.3.  If you setup etcd 3.5.0, then it means that K8s uses v3client of 3.4.3 to communicate with etcdserver of 3.5.0.  There is a similar issue reported by others, see [issues/13514](https://github.com/etcd-io/etcd/issues/13514). 

Did you configured "--auto-compaction-retention" and "--auto-compaction-mode", or do you have a script to run the "etcdctl compaction <rev>" command periodically? 

Please also provide the info required by @ptabor .

**Comment by superkjp** [comment]
Hey @ptabor and @ahrtr

Because of the restriction for our product environment(ACL and firewall limitations), it took me sometime to get bbolt work.
And here is the result for "get ./default.etcd/member/snap/db meta consistent_index  | hexdump":
etcd-instance1: 
```
panic: freepages: failed to get all reachable pages (page 161630: multiple references)
goroutine 6 [running]:
go.etcd.io/bbolt.(*DB).freepages.func2()
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
created by go.etcd.io/bbolt.(*DB).freepages
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6
exit status 2
```
etcd-instance2:
```
0000000 62 75 63 6b 65 74 20 6e 6f 74 20 66 6f 75 6e 64
exit status 1
0000010 0a
0000011
```
etcd-instance3:
```
panic: freepages: failed to get all reachable pages (page 3473458688754463801: out of bounds: 416769)
goroutine 18 [running]:
go.etcd.io/bbolt.(*DB).freepages.func2()
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
created by go.etcd.io/bbolt.(*DB).freepages
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6
exit status 2
```

for the command: "~/go/bin/bbolt keys --format=hex .//default.etcd/member/snap/db key | tail":
etcd-instance1:
```
panic: freepages: failed to get all reachable pages (page 161630: multiple references)
goroutine 18 [running]:
go.etcd.io/bbolt.(*DB).freepages.func2()
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
created by go.etcd.io/bbolt.(*DB).freepages
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6
```

etcd-instance2:
```
bucket not found
```

etcd-instance3:
```
panic: freepages: failed to get all reachable pages (page 3473458688754463801: out of bounds: 416769)
goroutine 20 [running]:
go.etcd.io/bbolt.(*DB).freepages.func2()
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
created by go.etcd.io/bbolt.(*DB).freepages
	/root/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6
```

As to retention, we did not setup for auto-retention(99% of our clusters are running okay and 'okay' means, etcd consumes usually 20%-30% disk space in total so we did not open the retention). At least this time, we learned something. 
But before the data-inconsistent happened, we actually met the "mvcc：database space exceeded" at the beginning of Dec.
Under that circumstance, I did the compact and defrag, and here is how I made it:

1. Look for the leader and get the up-to-date revision:
```
rev=$(ETCDCTL_API=3 etcdctl --endpoints=leader-instance:2379 endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*')
```
2. Compact all etcd-instances one by one
```
etcdctl --endpoints=instance1:2379 compact $rev
etcdctl --endpoints=instance2:2379 compact $rev
etcdctl --endpoints=instance3:2379 compact $rev
```
3. defrag all etcd-instances one by one 
```
etcdctl --endpoints=instance1:2379 defrag
etcdctl --endpoints=instance2:2379 defrag
etcdctl --endpoints=instance3:2379 defrag
```
4. disarm alarm(same for all members)
```
etcdctl --endpoints=instance1:2379  alarm disarm
etcdctl --endpoints=instance2:2379  alarm disarm
etcdctl --endpoints=instance3:2379  alarm disarm
```
5. test puts is working again (it did work)
We did not disconnect our ETCD to the Kubernetes cluster since I was running the compact related job(our cluster is on night duty and I did that in the daytime and I knew defrag will block system from reading and writing as well)

After a week, we are under the data-inconsistent situation.

**Comment by ahrtr** [comment]
Unfortunately, It seems that the data files are somehow corrupted, and it's the second time I see such kind of issue, see [13406](https://github.com/ahrtr/etcd-issues/tree/master/13406). It could be an issue of the [bbolt](https://github.com/etcd-io/bbolt), although the root cause is not clear yet. @ptabor 

The formal solution is to recover the data using a snapshot which is with a known good state for sure, but the data after the point when the snapshot was generated are lost. The default value for --snapshot-count is 100000, which means that there could be 100000 log entries being lost at most when recovering the db from a snapshot. 

Again, just as I mentioned previously, please make sure the K8s version is using a matched etcd version.

**Comment by ptabor** [comment]
Thank you for the details and I'm sorry for long duration since the last response. 

It's interesting that both files: For 'etcd-instance1' and 'etcd-instance3' are corrupted. One is unlikely... but both
make me wonder how the files were extracted.  We know that copying a bbolt file when etcd instance is running on top of that file is likely to produce an inconsistent result due to ongoing writes ... might this be a case here ?
