### ISSUE TITLE
db file is flocked by another process, or taking too long

### ISSUE THREAD

**Issue by turowicz** [etcd-io/etcd#13557]
I am having a problem with a 5GB database on a slow disk. The database will not come up as there is a HARDCODED timeout value of 10s to try and load the file. I am able to `cat` the file contents so the filoe is not `flocked`.

Please make that timeout configurable because otherwise the database is not usable in production for me. The slow disks in question are SSDs running Longhorn, so they are not THAT slow.

**Comment by turowicz** [comment]
Line in questions:

https://github.com/etcd-io/etcd/blob/1e46145b29764f9e65f4164bb777fbf275a63d8a/server/storage/backend.go#L84

**Comment by turowicz** [comment]
cc @ahrtr @gyuho @xiang90

**Comment by ahrtr** [comment]
Please note that `you are able to cat the file` doesn't mean that the file is not flocked. Please see the following example.  When the file "/tmp/db" is flocked by the program, you are still able to `cat` the file. But if you run the program again, then you will see the panic.

```
package main

import (
	"fmt"
	"os"
	"syscall"
	"time"
)

func main() {
	file, err := os.OpenFile("/tmp/db", os.O_RDWR|os.O_CREATE, 0600)
	if err != nil {
		panic(err)
	}

	fmt.Println("Attempting to obtain the exclusive lock")
	if err = syscall.Flock(int(file.Fd()), syscall.LOCK_NB | syscall.LOCK_EX); err != nil {
		panic (err)
	}
	fmt.Println("Locked successfully")

	time.Sleep(10*time.Second)

	fmt.Println("Releasing the lock")
	if err = syscall.Flock(int(file.Fd()), syscall.LOCK_UN); err != nil {
		panic(err)
	}
	fmt.Println("Lock released")

	if err = file.Close(); err != nil {
		panic(err)
	}
}
```


Usually it will not take a long time. If it takes a long time, then it's most likely meaning that it takes a long time at the mmap operation or db.loadFreelist(). Please note that:
1. It's just one time operation on etcd startup, so I do not get it why it is not usable in production for you. 
2. 5GB is a big file, I would suggest you to perform the de-fragmentation (see [maintenance](https://etcd.io/docs/v3.5/op-guide/maintenance/) ) on the file so as to release the free pages in the db file. Please let me know whether the operation can reduce the db file size.

**Comment by turowicz** [comment]
@ahrtr with autoscale, we can't have database instances not coming up for unknown time. The situation described in this thread has fixed itself after a couple of days. 

Compaction and defragmentation does clear the space but only for a short while. Our databases reach up to 25GB.

Why is it such a problem to make the timeout configurable?

**Comment by ahrtr** [comment]
Note that making the timeout configurable can't really resolve the performance issue you are running into. Do you mean that your databases reach up to 25GB soon after the compaction and defragmentation operations?  The default space quota is 2GB, and 8GB is maximum number of bytes suggested for a backend. So 25GB will definitely lead to degraded performance.

Do you set "--auto-compaction*" flags for the etcd? 

Note that your RAM needs to be > the db size as well, otherwise it can be a bottleneck as well.

**Comment by turowicz** [comment]
@ahrtr I am well aware of the performance impact when the DB file is too large. If you follow the optimisations closely you may end up with larger databases than 8GB (https://www.cncf.io/blog/2019/05/09/performance-optimization-of-etcd-in-web-scale-data-scenario/)

Therefore we should have a configurable timeout in order to be able to load up larger files. This should be up to the user to decide.

**Comment by turowicz** [comment]
I do have the following auto compaction
```
{"level":"info","ts":1641907924.2733092,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_COMPACTION_MODE","variable-value":"revision"}
{"level":"info","ts":1641907924.2733204,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_COMPACTION_RETENTION","variable-value":"1000"}
```

**Comment by ahrtr** [comment]
The related PR has already been closed, and no plan to add a configurable timeout (for opening the backend db), so closing this ticket. Feel free to reopen it if you still think it's an issue which needs to be resolved.

**Comment by turowicz** [comment]
👍🏻
