### ISSUE TITLE
peer listen address can serve client requests

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#13564]
etcd listens on 2379 for client requests, and listens on 2380 for peer requests by default. But actually the port 2380 can also serve client requests.

Steps to reproduce this issue:
1. start etcd using command `etcd`, so all the default flags/values are used;
2. In another terminal, execute command `etcdctl  --endpoints http://localhost:2380 put k1 v1`. You will see it's successful. 

@gyuho @serathius @ptabor

**Comment by ptabor** [comment]
It was added in: https://github.com/etcd-io/etcd/pull/8420. 
Agree that full client surface support is misleading and promotes bad usage patterns. 
We probably need to define explicit subset of supported rpcs.
