### ISSUE TITLE
[test] The test case TestUtlCtlV2Backup isn't stable

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#13585]
The test case [TestUtlCtlV2Backup](https://github.com/etcd-io/etcd/blob/96a9fd0a1e2a2887ebcf3b8eba90d8f0a881e77b/tests/e2e/ctl_v2_test.go#L215) isn't stable. Sometimes it passes, but sometimes it fails. 

Please see more info in [pull/13582#issuecomment-1008563270](https://github.com/etcd-io/etcd/pull/13582#issuecomment-1008563270)

cc @spzala

**Comment by spzala** [comment]
@ahrtr thanks for opening it.

**Comment by lavacat** [comment]
I'll try to reproduce this 
/assign

**Comment by ahrtr** [comment]
Thanks  @lavacat , but it seems that the test file ctl_v2_test.go is gone. 

Feel free to pick up another issue to work on.
