### ISSUE TITLE
Newly initalized/joined members join in a non defragged state leading to extra storage utilization on initialization

### ISSUE THREAD

**Issue by relyt0925** [etcd-io/etcd#13583]
New etcd members that are initialized from scratch and join an existing cluster are initialized in a non defragged state. This means that when they join they start consuming extra unnecessary space. I would expect a new member would before joining issue a local defrag but maybe that's not expected.

Reproduction steps:
1) Add data to an etcd cluster (3 members total)
```
[{"Endpoint":"https://localhost:2379","Status":{"header":{"cluster_id":14230970882531428267,"member_id":10626741503881765424,"revision":2311690,"raft_term":2},"version":"3.4.18","dbSize":90685440,"leader":10196984487233561844,"raftIndex":2674294,"raftTerm":2,"raftAppliedIndex":2674294,"dbSizeInUse":52662272}}]
```

2) Then remove all data from the cluster
```
[{"Endpoint":"https://localhost:2379","Status":{"header":{"cluster_id":14230970882531428267,"member_id":10626741503881765424,"revision":2311690,"raft_term":2},"version":"3.4.18","dbSize":90685440,"leader":10196984487233561844,"raftIndex":2674297,"raftTerm":2,"raftAppliedIndex":2674297,"dbSizeInUse":139264}}]
```
(Note the decrease in dbSizeInUse)

3) Then proceed to remove a member and add a new member from scratch. It will still be using the same data as the existing members although the database has been compacted
```
[{"Endpoint":"https://localhost:2379","Status":{"header":{"cluster_id":14230970882531428267,"member_id":8752301895422502330,"revision":2311690,"raft_term":2},"version":"3.4.18","dbSize":90685440,"leader":10196984487233561844,"raftIndex":2674303,"raftTerm":2,"raftAppliedIndex":2674303,"dbSizeInUse":36864}}]
```

Is this expected? I would think it would be a good optimization for any new members joining a cluster to be initialized in a optimal state from a storage perspective besides potentially being initialized at a state that is using excess storage for no reason and then needing to be followed with a defrag

**Comment by ahrtr** [comment]
It should be expected behavior, because the leader just sends a complete snapshot of the db file to the new member.

**Comment by relyt0925** [comment]
Ok do you think the strategy makes sense to consider? Or am I missing something potentially

**Comment by ahrtr** [comment]
Note that defragment is an expensive operation, and there is no auto defragment. Users are supposed to run the maintenance steps themselves, see [maintenance](https://etcd.io/docs/v3.5/op-guide/maintenance/).

The suggestion is to configure the etcd to automatically compact the keyspace with the --auto-compaction-* option, so that etcd can reuse the internal free pages instead of always allocate new space.  But once the db file exceeds the maximum value, users still need to run the de-fragment operation.

**Comment by relyt0925** [comment]
closing as question answered
