### ISSUE TITLE
repeating warming logs of 2021-09-28 20:31:13.797566 W | etcdmain: found invalid file/dir extra.args under data dir /data/datav3 (Ignore this if you are upgrading etcd) while etcd is not in update

### ISSUE THREAD

**Issue by AlexShu88** [etcd-io/etcd#13596]
Please read https://etcd.io/docs/latest/reporting_bugs/
since etcd 3.4.16
repeating warming logs of 2021-09-28 20:31:13.797566 W | etcdmain: found invalid file/dir extra.args under data dir /data/datav3 (Ignore this if you are upgrading etcd) 

while etcd is not in update

**Comment by serathius** [comment]
What log describes is self explanatory. I expect that incorrect use of shell lead you to create a file `extra.args` in your data dir directory. I don't see any evidence that etcd has created the file by itself. Based on that I'm closing the issue.
