### ISSUE TITLE
[CI] Enhance the CI workflow to support gofmt check

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#13604]
If the golang source code is not properly formatted by gofmt, then the CI should raise an error on PRs. 

The format issue in [pull/13603](https://github.com/etcd-io/etcd/pull/13603) is not discovered, so we need to enhance the CI workflow.

**Comment by spzala** [comment]
@ahrtr we have static checks that has gofmt and more, and the failure is reported in that issue https://github.com/etcd-io/etcd/runs/4828699828?check_suite_focus=true#step:5:137
Closing this issue, but please reopen if I misunderstood anything. Thanks!
