### ISSUE TITLE
etcd has a high CPU usage

### ISSUE THREAD

**Issue by dimon-v** [etcd-io/etcd#13609]
we use etcd 3.4.16, use thress nodes. Vm1 has a high CPU usage
[root@iZ2ze8r74rpnnxsuh7y3u5Z ~]# /data/etcd/etcdctl endpoint --cluster status -w table
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://vm1:2379 | 9c1b710c2e00bcfe |  3.4.16 |  324 MB |     false |      false |        23 |    2347259 |            2347259 |        |
| http://vm2:2379 | d4802525c5258b29 |  3.4.16 |  324 MB |     false |      false |        23 |    2347259 |            2347259 |        |
| http://vm3:2379 | fa497251a0388ad1 |  3.4.16 |  324 MB |      true |      false |        23 |    2347259 |            2347259 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
vm1:
top
![image](https://user-images.githubusercontent.com/16206290/149736171-d26283ea-6acb-45c4-8aa3-dfe4a3162c4f.png)

iostat
![image](https://user-images.githubusercontent.com/16206290/149736289-50cbf741-5f64-4013-bb3f-182d3bcab6fe.png)

perf info
![image](https://user-images.githubusercontent.com/16206290/149737326-0c283429-e559-4f34-8c17-325ce68720f6.png)

journal log:
![image](https://user-images.githubusercontent.com/16206290/149737449-9f550ace-da45-4424-a21b-6551dc7e5272.png)

vm2:
top
![image](https://user-images.githubusercontent.com/16206290/149736516-5fe0e9ba-dc19-4b15-bdda-f5e560b23faa.png)

vm3:
top
![image](https://user-images.githubusercontent.com/16206290/149736649-c0615a41-cc41-4594-873c-3bdcddc81418.png)

**Comment by serathius** [comment]
This issue doesn't provide any information why high CPU is abnormal nor does it provides any information on how to reproduce it.
Please provide more context or issue will be closed due to lack of evidence of a problem on Etcd side.

**Comment by dimon-v** [comment]
Thank you very much for your reply. Upstream is an apisix gateway with a small number of requests. Random IOPs 3000 using FIO disks. I don't know much about golang. Please give me some analysis suggestions
