### ISSUE TITLE
gcr.io/etcd-development/etcd:latest is outdated

### ISSUE THREAD

**Issue by Jille** [etcd-io/etcd#13606]
The docker image at gcr.io/etcd-development/etcd:latest is v3.3.12.

We should (remove the latest tag or):

- Bump it to a newer version
- Set up automation to update it with new releases automatically

**Comment by serathius** [comment]
I'm for removing the development image for sake of simplification. Maybe I'm not aware of all the use cases, however I would be happy to discuss how we can reduce number of artifacts we need to maintaining without negative impact on development.

**Comment by serathius** [comment]
Disregard my previous comment, Problem is that `latest` tag for etcd release points to old release instead of the `latest` one.

**Comment by serathius** [comment]
Overall I not a fan of `latest` flag. Users should always hardcode version they want.  especially for etcd it might be harmful to do unexpected upgrade that is not reversible.

**Comment by Jille** [comment]
This is still an issue.

**Comment by serathius** [comment]
@spzala @ahrtr I would vote for removing `latest` tag as it's a known anti-pattern. Using latest could lead users to have unexpected minor version upgrade. Alternative would be to have a docker tag per each release branch, but I would still think that we should steer administrators to  explicit rather than implicit versioning.

**Comment by serathius** [comment]
@ahrtr @spzala @ptabor your thoughts?

**Comment by ahrtr** [comment]
I agree to remove the `latest` tag. Tags are supposed to immutable, but we need to update `latest` tag each time when we release a new patch or minor version. It may also cause confusion to end users.

Removing it can make the life easier.

**Comment by serathius** [comment]
Done, latest tag was removed.

**Comment by armelvil** [comment]
The same behavior is happening on quay.io - the etcd image that is pulled with this command:

`podman pull quay.io/coreos/etcd`

podman claims is five years old.

Actual version appears old also:

`2023-06-26 17:23:56.615957 I | etcdmain: etcd Version: 3.3.8
2023-06-26 17:23:56.616006 I | etcdmain: Git SHA: 33245c6b5
2023-06-26 17:23:56.616009 I | etcdmain: Go Version: go1.9.7
2023-06-26 17:23:56.616011 I | etcdmain: Go OS/Arch: linux/amd64
`

I've been getting into a sticky mess between v2 or v3 curl apparently resulting in 404 errors and etcdctl-client not being packaged in Fedora.
