### ISSUE TITLE
Replace gobin with `go run`

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#13615]
etcd depends on gobin (https://github.com/myitcv/gobin) that since go 1.16 can get replaced with `go run $pkg@$version`:

Please refactor the scripts to use upstream `go run`: 

```
scripts/test_lib.sh:# Ensure gobin is available, as it runs majority of the tools
scripts/test_lib.sh:if ! command -v "gobin" >/dev/null; then
scripts/test_lib.sh:    GOARCH="" run env GO111MODULE=off go get github.com/myitcv/gobin || exit 1
scripts/test_lib.sh:  tool_exists "gobin" "GO111MODULE=off go get github.com/myitcv/gobin" || return 2
scripts/test_lib.sh:    run gobin ${GOBINARGS:-} -p "${tool}" || return 2
scripts/test_lib.sh:    run_for_module ./tools/mod run gobin ${GOBINARGS:-} -p -m --mod=readonly "${tool}" || return 2
tests/Dockerfile:RUN GO111MODULE=off go get github.com/myitcv/gobin
tools/mod/install_all.sh:go list --tags tools -f '{{ join .Imports "\n" }}' | xargs gobin -p
```

**Comment by RishiKumarRay** [comment]
Do we have to change every line with go run instead of go bin

**Comment by ptabor** [comment]
It seems there is 8 lines to fix (and test)

**Comment by ahrtr** [comment]
It seems that it isn't that simple, let me work on this issue.

**Comment by ghadi2005** [comment]
pkg install hhh

**Comment by kfirufk** [comment]
any updates ?

**Comment by kfirufk** [comment]
is it not implemented yet? i'm trying to create an ebuild for gentoo for v3.5.9 and it still uses gobin

**Comment by jmhbnz** [comment]
> is it not implemented yet? i'm trying to create an ebuild for gentoo for v3.5.9 and it still uses gobin

Hey @kfirufk - There is a merged pull request which appears to address go run vs gobin.  Rather than re-open this quite old issue if you are having issues can you please open a new detailed bug report or support discussion so we can take a look. Please include relevant console output or logs so we can replicate, thanks.
