### ISSUE TITLE
client v3 Watch may cause goroutine leaks

### ISSUE THREAD

**Issue by guoyuanchao1202** [etcd-io/etcd#13610]
# clientv3 implement
When I use clientv3.Watch api to listen an etcd path, clientv3 will finaly create a goroutine for this watch, source code is this:
![image](https://user-images.githubusercontent.com/55007214/149735390-056f9918-0d8d-4a0f-bebd-5ee4bcbddff1.png)

# Issue
If i watch more then one key with same client, client will start new groutine for every watch, but the problem is, if I can't stop the watch of one of the keys, so once I don't need to watch some keys, then the goroutine created by the client for that key can't be recycled, which actually causes goroutinex. 

# Test
As shown in the figure, I started 2000 watches on the same client, when I don't need to watch these keys, the system still has 2000 goroutines, only restart the client can close these goroutines:
![image](https://user-images.githubusercontent.com/55007214/149736430-d0c45859-4312-4b2b-be6d-a789608cf456.png)
![image](https://user-images.githubusercontent.com/55007214/149736474-70d32a02-2448-4cda-9b70-7a07af59d00e.png)

**Comment by guoyuanchao1202** [comment]
The problem can be solved by providing an api that closes the specified key watch. Btw I can provide the appropriate modifications if needed

**Comment by kkkkun** [comment]
In this cases, i think you should use `etcdClient.Close()`  to solve.

**Comment by guoyuanchao1202** [comment]
> In this cases, i think you should use `etcdClient.Close()`  to solve.
> 
> 
Yeah, but close will close all watch, if i only want to close one watch this not work.

**Comment by xiang90** [comment]
Can you try to pass in a real context instead of the context.TODO()? Then you can close the watcher by canceling the context.
