### ISSUE TITLE
Is it possible to sync two etcd clusters?

### ISSUE THREAD

**Issue by srbhklkrn** [etcd-io/etcd#13622]
Greetings,

I'm working on creating two etcd clusters, one will be primary, and the second will be backup to create these clusters I'm using Bitnami etcd Helm chart and running Kubernetes v1.20. With these two clusters, I'm trying to achieve a DR scenario if the primary cluster fails all traffic will be routed to the backup cluster, and then I will not have to manually backup/restore the cluster. In order to make this scenario working I need these two clusters to sync their data with each other (Similar to Elasticsearch Cross-Cluster Replication), which means no matter where the request lands it will get the latest data and this is where I'm stuck, is this even possible?

**Comment by ahrtr** [comment]
I think `etcdctl make-mirror` should be what you want. I recently enhanced the command to support incremental mirror, see [pull/13519](https://github.com/etcd-io/etcd/pull/13519) .

**Comment by srbhklkrn** [comment]
@ahrtr really appreciate you for pointing me in the right direction, from the documentation it looks like `etcdctl make-mirror` with Learner pod will do the trick, but I'm curious about whats the recommended way to implement this should I deploy two separate pods first one being Learner and second will be running Mirror or single pod can be used as Lerner and Mirror?

Additionally, Mirror is unidirectional, how should I set up Mirror from cluster B -> A, deploy a similar Mirror& Learner pod in cluster B?

**Comment by ahrtr** [comment]
I think you might need to implement an operator/controller to do this.  

Is it better to raise questions in the [etcd-dev](https://groups.google.com/g/etcd-dev)? @ptabor @serathius @spzala
