### ISSUE TITLE
Timeout should be set a non-zero value when creating an http client

### ISSUE THREAD

**Issue by qixiaoyang0** [etcd-io/etcd#13623]
I used a 3 node etcd cluster and did the following.

1. Stop two of the etcd nodes
2. Remove the data-dir completely
3. Reboot 2 nodes after a few seconds, the configuration parameter is ClusterState:existing

The restarted node does not join the cluster normally after etcdserver.NewServer runs. After debugging, it is found that the access to /downgrade/enabled is blocked internally. Because the http client does not set the timeout parameter, it keeps connecting to another restarted node to obtain downgrade/enabled.

Timeout should be set a non-zero value when creating an http client.
```
func getDowngradeEnabled(lg *zap.Logger, m *membership.Member, rt http.RoundTripper) (bool, error) {
	cc := &http.Client{
		Transport: rt,
	}
	var (
		err  error
		resp *http.Response
	)

	...
}
```

```
func getVersion(lg *zap.Logger, m *membership.Member, rt http.RoundTripper) (*version.Versions, error) {
	cc := &http.Client{
		Transport: rt,
	}
	var (
		err  error
		resp *http.Response
	)

	...
}
```

**Comment by serathius** [comment]
This is critical for new downgrade functionality for v3.6.
