### ISSUE TITLE
Implement discovery protocol on v3 api

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#13624]
Motivation removal of V2 API in https://github.com/etcd-io/etcd/issues/12913

Context Etcd supports Discovery protocol https://etcd.io/docs/v3.4/dev-internal/discovery_protocol/ based on V2 API. In v3.6 we are removing V2 API so we need a replacement that will work in v3.6+ versions. In v3.6 discovery v2 should still be able to do on older vclusters

Goal:
* Add `--discovery-version` flag that accepts `v2` (default) and `v3` value. Using `v3` will switch Etcd to use discovery protocol using V3 API
* Update documentation https://etcd.io/docs/v3.4/dev-internal/discovery_protocol/ 
* Mark for v2 discovery as deprecated

Deprecation plan:
* Make `v3` default in v3.7
* Remove `v2` option in v3.8

**Comment by serathius** [comment]
cc @ptabor

**Comment by serathius** [comment]
@ahrtr would you be interested in implementing this?

**Comment by ahrtr** [comment]
> @ahrtr would you be interested in implementing this?

@serathius  Sure. Based on the [Plans for v3.6.0 release](https://github.com/etcd-io/etcd/issues/13538), I assume this should be completed by the end of this month or the very early of next month?

**Comment by serathius** [comment]
> > @ahrtr would you be interested in implementing this?
> 
> @serathius Sure. Based on the [Plans for v3.6.0 release](https://github.com/etcd-io/etcd/issues/13538), I assume this should be completed by the end of this month or the very early of next month?

Yes, I hope be done with deprecation and downgrades by then.

**Comment by ahrtr** [comment]
> > > @ahrtr would you be interested in implementing this?
> > 
> > 
> > @serathius Sure. Based on the [Plans for v3.6.0 release](https://github.com/etcd-io/etcd/issues/13538), I assume this should be completed by the end of this month or the very early of next month?
> 
> Yes, I hope be done with deprecation and downgrades by then.

No problem.

**Comment by ahrtr** [comment]
@serathius It took me a couple of hours to go through the existing discovery source code and try out the v2discovery using the public endpoint `https://discovery.etcd.io`. It's pretty simple.  

But the original discovery project [discovery.etcd.io](https://github.com/coreos/discovery.etcd.io) has already been archived, and obviously is out of date. So we have two directions:
1. Create a new project to provide the similar functionality as [discovery.etcd.io](https://github.com/coreos/discovery.etcd.io) for v3 discovery , and we can still use etcd as the backend store.
2. Get rid of [discovery.etcd.io](https://github.com/coreos/discovery.etcd.io) completely in v3 discovery. We just need to start an standalone etcd instance or an etcd cluster directly to serve the v3 discovery service/requests, the bootstraped etcd instances in a new cluster just communicate with the discovery etcd instance or cluster using clientv3 API.  We may need to define some `discovery protocol` used between the bootstrapped etcd instances and the discovery etcd server. 

I prefer to the second approach/direction. What do you think? @ptabor

**Comment by ahrtr** [comment]
@serathius  I'd like to breakdown this task into 3 three smaller tasks:
1. Implement the v3discovery;
2. Add unit test and e2e or integration test;
3. Update the [documentation](https://etcd.io/docs/v3.5/dev-internal/discovery_protocol/). 

I am planning to submit a PR for #1 today or tomorrow, so as to:
1.  get feedback before moving on. 
2. reduce the burden on the reviewers to review a huge PR.

**Comment by serathius** [comment]
Small PRs are highly encouraged! Thanks for proposing this.

**Comment by ptabor** [comment]
Thank you @ahrtr . We should not depend/support discovery.etcd.io in any way. 

Ad. deprecation plan, is my understanding correct: 

Assuming there is discovery protocol customer using: 
  1. v3.4 (or v3.5) discovery server not using the --enable-v2v3 mode (so v2 api state is kept in store v2)
  2. etcd v3.5 using the discovery server using for bootstrapping. 
  
 If we consider upgrading scenario of the 2. keeping 1. as is. 
   - 1) upgrade to 3.6... according to the plan the v2 protocol is still being used. The state is persisted in 1. in `v2store`.
       the discovery keep working
   - 2) upgrade to 3.7. The server does not finds the state in discovery service (as its not in store v3) so generates new cluster is and bootstraps new disconnected instance from scratch. 

So upgrade to 3.7 is very disruptful and we pushed the problem forward to 3.7 but it will still hit users.

---------------------------------------------------------------

What options we have: 
 
## 1. Make upgrade to 3.6 require explicit user action without migration path

- v3.6 only supports --discovery=v3. The flag is mandatory. 
- The flag description contains warnings that switching to v3 protocol will establish new cluster and there is no good migration. 
 - This is acceptable option if discovery usage is small. 

## 2. Make upgrade to 3.6 require explicit user action without migration path

Like 1. but we provide e.g. as part of etcd 3.5.3+:  `etcdctl discovery migrate` command that connects using v2 protocol and copies the state to v3 state.  The problem with this solution that it's racy. If some clients use v2 protocol and some v3 protocol the state can get out of sync - but should be sufficiently good for performing quick transparent migration and upgrade. 

## 3. Enable discovery server owners to transparently migrate to --enable-v2v3. 
 
 This seems to be difficult but puts the migration solution on the discovery service owner side. Then for some time customers can mix connection to the server with v2 & v3 versions. 

---------------------------------------------------------

My intuitions are that adoption of  discovery is not very high so we can go for 1. with fallback plan being 2.

**Comment by ahrtr** [comment]
Thanks for the comment. Since v2 discovery will be decommissioned in 3.8, so the tool should only be available in 3.5 ~ 3.7? 

> Orthogonally we could consider some tooling like etcdctl discover-clone-v2v3 that migrates the config from v2store to v3 such that update without coordinated restart of all members is possible.

**Comment by ahrtr** [comment]
The implementation should have already been done in PR [pull/13635](https://github.com/etcd-io/etcd/pull/13635), please take a look. @serathius @ptabor @spzala 

With regard to the documentation, my understanding is we only need to update document for 3.6, any the previous document should be keep as it is. But I do not see the sub-directory v3.6 in [content/en/docs](https://github.com/etcd-io/website/tree/main/content/en/docs). My understanding is the sub-directory v3.6 will not be added until etcd v3.6 is released. 

Could you please provide guide on how & where should I update the [discovery](https://etcd.io/docs/v3.5/dev-internal/discovery_protocol/) document?

**Comment by serathius** [comment]
Any work left?

**Comment by ahrtr** [comment]
Just raised https://github.com/etcd-io/website/issues/653 to track the left documentation work
