### ISSUE TITLE
ETCD server shows error when localhost wants to connect with it (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "").

### ISSUE THREAD

**Issue by nish2312** [etcd-io/etcd#13630]
While connecting to etcd server a message is thrown like 2022-01-17 21:02:17.4563 I | embed: rejected connection from "127.0.0.1:12345" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "".
The same message is appearing multiple times for different localhost id.

**Comment by nish2312** [comment]
Hi,any updates on this issue?

**Comment by kkkkun** [comment]
May be you should use 'ETCDCTL_API=3'?  Have a try?

**Comment by nish2312** [comment]
Yes,by default it uses ETCDCTL_API=3.

**Comment by kkkkun** [comment]
If use ETCDCTL_API=3, it still has this error?

**Comment by nish2312** [comment]
Yes using ETCDCTL_API=3 still getting this message  (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "").

**Comment by kkkkun** [comment]
> Yes using ETCDCTL_API=3 still getting this message (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "").

We need help.

**Comment by serathius** [comment]
https://go.dev/src/crypto/x509/verify.go

Line 36-38
```
	// IncompatibleUsage results when the certificate's key usage indicates
	// that it may only be used for a different purpose.
	IncompatibleUsage
```

Please provide more information how certificate and key cluster is using were generated.

**Comment by nish2312** [comment]
Hi,could you please explain what you meant by "how certificate and key cluster is using were generated".
Thanks

**Comment by nish2312** [comment]
Hi,any update?

**Comment by ahrtr** [comment]
1. Have you specified the` --client-cert-auth` flag? Please provide the complete configuration for etcd.
2. Have you specified "client auth" when generating the certificate and CA for the client? Please provide detailed steps on how do you generate the certificates.
