### ISSUE TITLE
High io load on low load cluster, causes range errors and leader re-election

### ISSUE THREAD

**Issue by FireDrunk** [etcd-io/etcd#13648]
I'm trying to debug a performance issue with Etcd, and doing so, I'm not sure whether I've stumbled onto a bug, or something else.

Here's my situation:
3-node Kubernetes Cluster running stacked etcd, with minimal load (50 pods).

The logs of etcd frequently show "Range request took too long", "WAL timeouts" and "Leader Re-elections".
All nodes are running on SSD's, and I've benchmarked them all with:
```shell
fio --randrepeat=1   --ioengine=libaio   --direct=1    --gtod_reduce=1    --name=etcd-disk-io-test    --filename=etcd_read_write.io    --bs=4k --iodepth=64 --size=4G    --readwrite=randrw --rwmixread=75
```
They can all do about at least 6000/2000 (r/w) iops simultaneously (and this is while etcd is running, so the actual number might be much higher).
CPU and Memory are not taxed.

To see the actual load on etcd, I've run a watch for 5 minutes using:
```shell
ETCDCTL_API=3 etcdctl --debug --endpoints https://<node-ip>:2379 --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --cacert=/etc/kubernetes/pki/etcd/ca.crt watch /registry --prefix | strings |grep /registry > /run/etcdctl_log
```
When counting the number of key changes with:
```shell
cat /run/etcdctl_log | wc -l
1967
```
It seems etcd is not *that* busy (2k key changes in 300s, would amount to roughly 7 changes per second).

Watching the disk io using blktrace:
```shell
blktrace -w 300 -d /dev/sda -o sda
```
And getting the number of actions done by etcd:
```shell
blkparse -i sda | grep etcd | wc -l
53962
```
I'm seeing >50k io's in a 300s window done by etcd. This would mean that for every action, there are >25 io's issued by etcd per key operation. I know this includes reads.
Filtering out only writes using:
```shell
blkparse -i sda | grep etcd | grep WS | wc -l
44974
```
I'm still seeing > 20 IO's issued per key write operation.

The Write log contains mostly kubernetes lease requests from a few operators (2 from kubernetes, 2 manually installed), some node and pod leases.

My points are:
- Is this IO profile expected? Because I would assume a key operation would not require 20 IO's to complete?
- When my SSD's can all take > 6000/3000 io's, and evidently they are not taxed at the moment, how is it possible ETCD is still hitting the Range & WAL timeouts?
- Can I debug this further with specific tracing tools?

Versions:
etcd: 3.4.13-0
kubernetes: v1.21.8

PS: Upon request I can share the blktrace & etcd write logs, but I don't think they contain that much valuable information for now.

**Comment by ahrtr** [comment]
Things to check:
1. The db file size, which locates at `${ETCD_HOME}/member/snap/db`;
2. The network connectivity & latency between each pair of etcd instances;
3. What's the `--election-timeout` and `--heartbeat-interval` of each etcd instance?

**Comment by FireDrunk** [comment]
1. DB size is 150MB
2. All 3 nodes are on the same switch, with no firewall in between. Measured ping latency is ~0.3ms
3. Those are not explicitly set, so default.

My configuration:
```shell
- etcd
    - --advertise-client-urls=https://<ip>:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://<ip>:2380
    - --initial-cluster=m1=https://<ip>:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://<ip>:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://<ip>:2380
    - --name=m1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```

**Comment by FireDrunk** [comment]
1. Not that I can recall, this has been managed by Kubeadm from the beginning.
2. 3
3. 
```
+---------------------------+------------------+---------+---------+-----------+-----------+------------+
|         ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+---------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://192.168.1.40:2379 | 812dd29a7ca1c57b |  3.4.13 |  216 MB |      true |     14097 |  128827828 |
| https://192.168.1.41:2379 | 3766b40c683b302f |  3.4.13 |  215 MB |     false |     14097 |  128827828 |
| https://192.168.1.42:2379 | 500e40391198880d |  3.4.13 |  215 MB |     false |     14097 |  128827828 |
+---------------------------+------------------+---------+---------+-----------+-----------+------------+
```

**Comment by FireDrunk** [comment]
@ahrtr I've just spun up a KinD cluster with 3 control nodes, to check how the etcd cluster is spun up.

```shell
root       15899   15560 11 12:32 ?        00:00:13 etcd --advertise-client-urls=https://172.18.0.3:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://172.18.0.3:2380 --initial-cluster=kind-control-plane=https://172.18.0.3:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.3:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://172.18.0.3:2380 --name=kind-control-plane --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
root       18885   18637 10 12:33 ?        00:00:06 etcd --advertise-client-urls=https://172.18.0.6:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://172.18.0.6:2380 --initial-cluster=kind-control-plane=https://172.18.0.3:2380,kind-control-plane2=https://172.18.0.6:2380 --initial-cluster-state=existing --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.6:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://172.18.0.6:2380 --name=kind-control-plane2 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
root       20644   20396 40 12:34 ?        00:00:02 etcd --advertise-client-urls=https://172.18.0.5:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://172.18.0.5:2380 --initial-cluster=kind-control-plane=https://172.18.0.3:2380,kind-control-plane3=https://172.18.0.5:2380,kind-control-plane2=https://172.18.0.6:2380 --initial-cluster-state=existing --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.5:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://172.18.0.5:2380 --name=kind-control-plane3 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```
Kind uses kubeadm to spin up the cluster to my knowledge: https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches
It seems it's not using the `--initial-cluster-state` you are mentioning above.

Does that mean that `kubeadm` is using the wrong arguments to spin up the etcd cluster?

**Comment by ahrtr** [comment]
The default value for `--initial-cluster-state` is `new`.  kubeadm starts the first etcd instance as a standalone instance, and let the other two members join the existing cluster, so it's OK. 

Note that etcd needs to create buckets in bbolt db, and I believe K8s may have some writes as well. If you want to figure out all the writes, then you can try to analyze all the buckets and keys in bbolt db.  See an example [here](https://github.com/ahrtr/etcd-issues/tree/master/bolt/bucketDemo) on how to use bbolt CMD to do such analysis.  

But it still does not answer your original question why it causes range errors and leader re-election in your cluster. You might need to do some performance analysis, such as enable & investigate the profile, or look at the [metrics](https://etcd.io/docs/v3.5/metrics/).

**Comment by FireDrunk** [comment]
After a lot of debugging, I found out that one of the SSD reported a load of 100% during only light load. After further investigation, it had service time over 100ms from time to time.

After installing 3 new write optimized SSDs, and reinstalling the cluster, eveything calmed down. It seemed that Etcd was intensely trying to mitigate the slow node.

Thanks all for the help!

**Comment by SowAbdoul** [comment]
I need help with an issue in my Kubernetes cluster, which is set up with 3 control-plane nodes and 3 worker nodes using kubeadm. The etcd pods are located on the control-plane nodes. Initially, everything was working fine, but after a few months of usage, I've started encountering errors in etcd that are causing other pods to crash.

The error message I see is:

```javascript
Error from server: etcdserver: leader changed
```

After researching online, I added the following options to my etcd manifests:

```yaml
etcd.yaml
---
spec:
  containers:
  - command:
    - --snapshot-count=10000
    - --heartbeat-interval=500
    - --election-timeout=2500
    - --pre-vote=true
    ...
    resources: {}
```
While the frequency of errors has decreased, they are still persisting, and it feels like I've only moved the problem rather than fully resolving it.

Currently, the `/var/lib/etcd` directory is mounted on the system partition. I want to mount a new partition on `sdb` and then move `etcd` to it. Do you think this will resolve the performance issues with etcd?

Could you please help me with this issue?
