### ISSUE TITLE
etcd revision occurs Inconsistent  

### ISSUE THREAD

**Issue by didihongsheng** [etcd-io/etcd#13654]
etcd version : 3.5.0
k8s version : 1.20

we are in production environment, the k8s log  shown below, it shows the revision has a problem :

![image](https://user-images.githubusercontent.com/19987261/151509566-baa2c658-47a9-441e-81d7-31b5bf1059d6.png)

so we check endpoints status  in etcd cluster, as shown below:
![image](https://user-images.githubusercontent.com/19987261/151510041-fe5c9907-39f6-42ba-ae32-f9367487dc68.png)

etcd raft index seems healthy, but revision is inconsistent, one node is too far behind. I know the revision is maintained in mvcc , but in normal case , if etcd raft index is heathy in cluster ,revision should not occurs like this, I don't known the reason.

**Comment by ahrtr** [comment]
Any reason why you setup etcd cluster of 3.5.0 for K8s 1.20? Note that K8s 1.20 is supposed to work with etcd 3.4.13, see [go.mod#L447](https://github.com/kubernetes/kubernetes/blob/release-1.20/go.mod#L447). There is a similar issue [13547](https://github.com/etcd-io/etcd/issues/13547).

Can you always see this issue when running K8s  1.12 together with etcd 3.5.0?

**Comment by serathius** [comment]
@didihongsheng One idea is that you run Etcd instances with slightly different apply logic. This could be caused by incorrectly doing cluster upgrade.

Could you specify if this cluster was created in version v3.5.0 or it was upgraded? What versions you run before this? Did you have any problems during upgrade?

**Comment by didihongsheng** [comment]
> an you always see this is

this issue only appear once when the k8s's control plane crash ，then I remove the problematic member and delete its datadir ,and member add it back

**Comment by didihongsheng** [comment]
> 

the version before 3.5 is 3.3，we update 3.3 to 3.4, then 3.4 to 3.5,  I didn't  meet with problems  .

**Comment by serathius** [comment]
Data corruption issue was found in v3.5.[0-2] release. Please upgrade to v3.5.3.
