### ISSUE TITLE
go.opentelemetry.io/otel: Plans to Upgrade to v1 for 3.5.x?

### ISSUE THREAD

**Issue by trynity** [etcd-io/etcd#13664]
One of the things we've run into, is that `etcd` for `v3.5.x` depends on an older version of `otel` for `semconv`. They moved things around in their `v1` versions, and this had lead to breakage with vendoring when having `etcd` and other packages.

I notice that it has been updated on the `main` branch, and am wondering if there are plans to merge this into the `3.5.x` branch.

Let me know if I can help out on this at all.

**Comment by serathius** [comment]
I don't think should backport an upgrade to major version of package. Backports should include only fixes and patch updates to dependencies.
