### ISSUE TITLE
etcd/raft: adding a new node to existing cluster panics

### ISSUE THREAD

**Issue by Param-S** [etcd-io/etcd#13666]
### What happened?

Adding a new node to existing cluster as it is described in the [README](https://github.com/etcd-io/etcd/blob/main/raft/README.md) fails with panic

> To allow a new node to join this cluster, do not pass in any peers. First, add the node to the existing cluster by calling ProposeConfChange on any existing node inside the cluster. Then, start the node with an empty peer list, like so:
         **n := raft.StartNode(c, nil)**

node fails with the following message & stack:
```
panic: no peers given; use RestartNode instead

goroutine 25 [running]:
go.etcd.io/etcd/raft/v3.StartNode(0xc0003bff50, 0x0, 0x0, 0x0, 0x0, 0xc00011c0f0)
	/root/hyperledger/src/go.etcd.io/etcd/raft/node.go:220 +0x4cc
```

### What did you expect to happen?

As per the documentation, the new node should be able to join the cluster successfully.  But, It is clear from the error message, application should be updated to use `RestartNode` instead of `StartNode` & the same modification is made in raftexample https://github.com/etcd-io/etcd/pull/12696/files.  

As there is change in behaviour of raft.StartNode interface, trying to understand is there any difference in functionality b/w 

1.  joining a new node 
    a. using StartNode with nil peers based on the earlier version of etcdraft library 
       > n := raft.StartNode(c, nil) 

    b. using RestartNode with the latest etcdraft library 
       > raft.RestartNode(c)
       

### How can we reproduce it (as minimally and precisely as possible)?

It is reproducible using `raftexample` by reverting this PR https://github.com/etcd-io/etcd/pull/12696/files 

### Etcd version (please run commands below)

v3.5.1

**Comment by ahrtr** [comment]
Please provide the exact steps you did. 

FYI. [https://github.com/ahrtr/etcd-issues/tree/master/13418](https://github.com/ahrtr/etcd-issues/tree/master/13418)

**Comment by ahrtr** [comment]
This should be a question instead of a bug, so removing the `area/bug` label.... 
Please refer to the link I provided previously.

**Comment by ahrtr** [comment]
Please refer to [13666](https://github.com/etcd-io/etcd/issues/13666).
