### ISSUE TITLE
Defrag unsets backend options

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#13678]
### What happened?

After running defrag backend options will be unset. For example FreelistType will be ""

### What did you expect to happen?

Defrag should preserve original backend options

### How can we reproduce it (as minimally and precisely as possible)?

See unit test in PR.

### Etcd version (please run commands below)

affects 3.5 and 3.4 releases

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Thanks, can you propose a backport to 3.5 and 3.4 after merge?

**Comment by lavacat** [comment]
> Thanks for sending PR, can you create a backport PRs to 3.5 and 3.4 after merge?

Yes, I'll submit similar PRs for 3.5 and 3.4
