### ISSUE TITLE
Source code file structure in zip does not match repo structure

### ISSUE THREAD

**Issue by temperedf4te** [etcd-io/etcd#13688]
### What happened?

Repo structure for v3.5.2 has a v3 directory in the packages. Doing go get will create a mod folder with v3 in the folder structure for etcd. 

When unzipping the source code however, it does not contain a v3 directory so the import paths cannot find the package on a system with the etcd package unzipped. 

### What did you expect to happen?

I expected unzipping the source code to match the file paths of the repo (so contains v3 directory)

### How can we reproduce it (as minimally and precisely as possible)?

Unzip source code and observe the file structure does not match repo structure. 

### Etcd version (please run commands below)

v3.5.2

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
I am not fully understand what's the exact issue you are running into.  It seems that you import some etcd packages in your program, while your IDE complains that it can't find the packages? 

Note that you don't need to download the source code of [etcd v3.5.2](https://github.com/etcd-io/etcd/archive/refs/tags/v3.5.2.zip).  Instead, you just need to add entry below into your go.mod, and run "`go mod tidy"`. 
```
require go.etcd.io/etcd/client/v3 v3.5.2
```

Please let me know whether it resolves your issue. Actually this isn't an issue at all.
