### ISSUE TITLE
Add s390x to currently supported architectures.

### ISSUE THREAD

**Issue by shivaburade** [etcd-io/etcd#13685]
As etcd binary and Docker image is available for s390x arch, We would like to add the same in the supported platform page https://etcd.io/docs/v3.5/op-guide/supported-platform/

**Comment by serathius** [comment]
If you want to update documentation please send a PR and modify https://github.com/etcd-io/website/blob/138926b5de44b5116fdbe63830eeaf73596e4c2c/content/en/docs/v3.5/op-guide/supported-platform.md

**Comment by yankay** [comment]
HI , @serathius . There is a PR to add the document .
Would you please review it?
