### ISSUE TITLE
etcdctl SRV discovery

### ISSUE THREAD

**Issue by udf2457** [etcd-io/etcd#13691]
### What happened?

etcdctl version: 3.5.2
API version: 3.5

`etcdctl --write-out=table --user root --discovery-srv="example.com" endpoint status`

Gives:

> Error: dns lookup errors: lookup _etcd-client-ssl._tcp.example.com on _my_dns_server_ip_goes_here_:53: no such host and lookup _etcd-client._tcp.example.com on _my_dns_server_ip_goes_here_:53: no such host

And yet, on the exact same machine:

etc1:~$ dig +noall +answer SRV _etcd_client._tcp.example.com
_etcd_client._tcp.example.com. 300 IN    SRV     0 0 2379 etc1.example.com.
_etcd_client._tcp.example.com. 300 IN    SRV     0 0 2379 etc2.example.com.
_etcd_client._tcp.example.com. 300 IN    SRV     0 0 2379 etc3.example.com.
etc1:~$ dig +noall +answer SRV _etcd_client-ssl._tcp.example.com
_etcd_client-ssl._tcp.example.com. 300 IN SRV    0 0 2379 etc2.example.com.
_etcd_client-ssl._tcp.example.com. 300 IN SRV    0 0 2379 etc3.example.com.
_etcd_client-ssl._tcp.example.com. 300 IN SRV    0 0 2379 etc1.example.com.

(sorry, I don't know why github is applying strinkethrough to some of the output above !!)

### What did you expect to happen?

Command should have run as expected. SRV records are in place and validated.

### How can we reproduce it (as minimally and precisely as possible)?

Setup SRV records, test etcdctl against it

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.2
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
It should be `*etcd-client*` instead of `*etcd_client*`. Note that it is NOT underscore

**Comment by ahrtr** [comment]
Please reopen this ticket if you still have any issue.
