### ISSUE TITLE
No DATA RACE/Leaked goroutine validations for the integration test runs in github actions

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [etcd-io/etcd#13699]
### What happened?

The Integration suites that are run as part of [`Tests`](https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests.yaml#L28) github workflow is not checking for `DATA RACE` , `panic: test timed out` and `leaked goroutines` errors.
Hence the workflows are passing inspite of such Errors.
Example: https://github.com/etcd-io/etcd/runs/5191576634?check_suite_focus=true
Search for "leaked goroutine" in `Search logs`

### What did you expect to happen?

The integration workflows should have `DATA RACE`, `panic: test timed out` and `leaked goroutines` error validations as in e2e workflow at https://github.com/etcd-io/etcd/blob/main/.github/workflows/e2e.yaml#L25

Also suggest the usage of make tool for running this workflows as the Makefile at https://github.com/etcd-io/etcd/blob/main/Makefile#L100 already has this validation.

### How can we reproduce it (as minimally and precisely as possible)?

1. See missing validation in https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests.yaml#L28
2. Look at the existing `leaked goroutine` failures in https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests.yaml#L28 that are missed to be reported.

### Anything else we need to know?

Depends on https://github.com/etcd-io/etcd/issues/13698
This issue has to wait till https://github.com/etcd-io/etcd/issues/13698 is fixed.

**Comment by serathius** [comment]
Is this a duplicate of https://github.com/etcd-io/etcd/issues/13698? Let's close it if so.

**Comment by Rajalakshmi-Girish** [comment]
https://github.com/etcd-io/etcd/issues/13698 is not a duplicate of this.
That issue was created to look into **why the "Goroutine leaks are happening"** and to fix the tests that are causing Leaks.
Where as, this issue is for fixing the missing validation.

**Comment by serathius** [comment]
ok, however those issues are strictly dependent. We cannot re-enable validation if tests are not fixed. It's prefer to split issues based on fact that they are a single independent unit that can be worked by single person. Still I'm ok with leaving it as it is. 

Please add links to other issue in the top comment, so it's clear the relation between those issues to other contributors.

**Comment by Rajalakshmi-Girish** [comment]
> ok, however those issues are strictly dependent. We cannot re-enable validation if tests are not fixed. It's prefer to split issues based on fact that they are a single independent unit that can be worked by single person. Still I'm ok with leaving it as it is.
> 
> Please add links to other issue in the top comment, so it's clear the relation between those issues to other contributors.

Please confirm if I understand it right.
- Must NOT enable validation unless the Goroutine leaks are fixed.
- Also you suggest to split the leaks by each test into a different issue so that they can be worked by different people.
(But I am not sure on how to identify which tests are causing those `Found leaked goroutined BEFORE test appears to have leaked`)

**Comment by serathius** [comment]
> Please confirm if I understand it right.
> 
> * Must NOT enable validation unless the Goroutine leaks are fixed.

No, it just until we have goroutine leaks, PR that enables validation cannot be merged as it will cause CI to fail. We first need to fix the gourutine leaks and then we can enable validation that will prevent regressions.

> * Also you suggest to split the leaks by each test into a different issue so that they can be worked by different people.

No, I meant to say that having two separate issues (https://github.com/etcd-io/etcd/issues/13699, https://github.com/etcd-io/etcd/issues/13698) doesn't really help as they are directly dependant on each other. As mentioned in above comment, we cannot enable validation before we fix all the issues. This means that issue about enabling validation cannot be picked up by other contributions as they need to wait for other to be done.

I think we can skip discussion about issue organisation. As for fixing the leak problem, are you planning to work on this? Do you need any help?

**Comment by Rajalakshmi-Girish** [comment]
> As for fixing the leak problem, are you planning to work on this? Do you need any help?

Yes I plan to work on this. But would need help as I have not worked on goroutine leaks before.

I got to know about this tool recently- https://golangrepo.com/repo/uber-go-goleak-go-utilities
Request for guidance.

**Comment by serathius** [comment]
We use custom leak detection https://github.com/etcd-io/etcd/blob/main/client/pkg/testutil/leak.go, that I'm not super familiar with.

I would look into recent work by @[timmyyuan](https://github.com/timmyyuan) https://github.com/etcd-io/etcd/pull/13563 https://github.com/etcd-io/etcd/pull/13562. They apparently used https://github.com/uber-go/goleak, looks like we have a TODO to migrate to it.

I see two approaches:
* Use existing leak detection. Try to identify which test is leaking by running each test separately and check if there is any leak reported.
* Try to migrating to https://github.com/uber-go/goleak
