### ISSUE TITLE
Add tests for correct TLS verification against multi-server etcd cluster 

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#13707]
Discussion in https://github.com/kubernetes/kubernetes/pull/106591#discussion_r780357459

Proposed scenario
* client failover when the first server listed goes unavailable after the client has established a connection
* client failover when the first server listed is unavailable when the client is first created

**Comment by serathius** [comment]
cc @liggitt

**Comment by ahrtr** [comment]
Let me add a couple of tests.
