### ISSUE TITLE
More warnings around "etcdctl del"

### ISSUE THREAD

**Issue by mac-chaffee** [etcd-io/etcd#13705]
### What happened?

Not really a bug, but maybe unexpected behavior. Since `etcdctl del` accepts an optional second parameter which deletes all keys in a range, these are very easy mistakes to make:

```
# Oh no, there was a space in the key I copied!
etcdctl del /registry/persistentvolumes/pvc-eef4ec4b-326d-47e6- f11c-6474a5fd4d89
# <deletes thousands of keys>
```
```
etcdctl put 'key space' somevalue
# Oh no! I forgot to quote my key that intentionally contains a space!
etcdctl del key space
# <deletes thousands of keys>
```
```
# Oh no! I forgot to add -- to my flag!
etcdctl del a-key cacert=/some/file
# <deletes hundreds of keys>
```

### What did you expect to happen?

Of course we could just tell people to pay super close attention when they run `etcdctl del`, but there's lots of advice scattered around the internet for fixing broken Kubernetes clusters that involves `etcdctl del`. Here's one example: https://github.com/kubernetes/kubernetes/issues/90585#issuecomment-848717022

Here's more: https://www.google.com/search?q=etcdctl+del+site%3Agithub.com%2Fkubernetes

As a result, I think having that optional parameter to delete a range of keys might constitute a footgun. Perhaps we should require an extra flag like `--range` or something so that there's never an implicit deletion of more than 1 key. Other options include placing a warning/confirmation if the command would result in more than one key being deleted (may be performance-intensive).

### How can we reproduce it (as minimally and precisely as possible)?

```
docker run -d --name etcd quay.io/coreos/etcd:v3.5.0
docker exec -it etcd sh
<run etcdctl put and del commands from example>
```

### Etcd version (please run commands below)

<details>

```
v3.5.0
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>
n/a
</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>
n/a
</details>

**Comment by ptabor** [comment]
I think it's a valid concern. If not an issue with backward compatibility, it would be a definitely right thing to fix. 



- In 3.5 we could add a warning on stderr. 
- In 3.6 we could add support for `--range` and sleep (2s) if the `--range` is not given: 
 a) let the operation be cancelled by human operator
 b) trigger attention of the script owners to start using the new flag.

**Comment by kkkkun** [comment]
Let me have a try.
/assign

**Comment by ahrtr** [comment]
> I think it's a valid concern. If not an issue with backward compatibility, it would be a definitely right thing to fix.
> 
>     * In 3.5 we could add a warning on stderr.
> 
>     * In 3.6 we could add support for `--range` and sleep (2s) if the `--range` is not given:
>       a) let the operation be cancelled by human operator
>       b) trigger attention of the script owners to start using the new flag.

I would propose to deprecate the existing range delete operation, and add a new flag "`--to-key`" to explicitly state that it's a range delete operation, otherwise raise an error. Since it's not backward compatible, so we can raise a warning for now and sleep 2 seconds.  cc @ptabor @serathius @spzala  WDYT?
