### ISSUE TITLE
[test] The semaphoreci fails from time to time

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#13702]
The error message is

```
Step 1/14 : FROM ubuntu:21.10
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
make[1]: *** [build-docker-test] Error 1
make[1]: Leaving directory `/home/runner/etcd'
make: *** [ensure-docker-test-image-exists] Error 2
```

The [base image in Dockerfile is ubuntu:21.10](https://github.com/etcd-io/etcd/blob/main/tests/Dockerfile#L1) , each time when running the [build-docker-test](https://github.com/etcd-io/etcd/blob/main/Makefile#L67) , it pulls the base image. Sometimes it may fail due to the docker hub's rate limitation. 

I think we may need to put the base image to another image registry. cc @serathius @ptabor @spzala

**Comment by chaochn47** [comment]
@ahrtr, vote for aws ECR public gallery for pulling docker images from my knowledge. The quota is 1 image pull per second for unauthenticated user which is better than the following docker policy. 
> Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours
https://www.docker.com/increase-rate-limits

Docker already automatically pushed their public images to ECR public https://www.docker.com/blog/news-from-aws-reinvent-docker-official-images-on-amazon-ecr-public/. 

So `ubuntu:21.10` will be changed to `public.ecr.aws/docker/library/ubuntu:21.10`. 

Pushing and pulling the ubuntu images from the gcr etcd account may be another option.

**Comment by ahrtr** [comment]
Looks good to me, at lease we can resolve the semaphoreci failure for now. The `public.ecr.aws/docker/library/ubuntu:21.10` is already available, 

```
$ docker pull public.ecr.aws/docker/library/ubuntu:21.10
21.10: Pulling from docker/library/ubuntu
24496884391b: Pull complete 
Digest: sha256:1108598c6469492b0ec61c4c9bab6868a3d335ecf76deb4d31ff3b2615170ae9
Status: Downloaded newer image for public.ecr.aws/docker/library/ubuntu:21.10
public.ecr.aws/docker/library/ubuntu:21.10
```

**Comment by serathius** [comment]
I don't think we should pick up another dependency, especially when we are almost ready to disable those tests https://github.com/etcd-io/etcd/issues/13448. 

Only think blocking us from removal is fact that branch `release-3.3` depends on those tests and apparently there is no way to configure semaphore to just run on selected branches. I don't have access so I could not confirm that.

I previously tried to do migration to github actions (https://github.com/etcd-io/etcd/pull/13613), but didn't had time to fix all the errors. In the end decided to wait for v3.6 release as it would move the support window allowing us to ignore `release-3.3` problems.

**Comment by ahrtr** [comment]
Thanks @serathius for the info. I missed the info in [13448](https://github.com/etcd-io/etcd/issues/13448). 

It's OK just to ignore the SemaphoreCI errors for now.

**Comment by ahrtr** [comment]
Or  can we just replace it with` public.ecr.aws/docker/library/ubuntu:21.10 `for now, so as to make the CI green? We can remove the SemaphoreCI when 3.6 is out. WDYT @serathius ?

**Comment by serathius** [comment]
cc @ptabor

**Comment by ahrtr** [comment]
There is already a related ticket [13448](https://github.com/etcd-io/etcd/issues/13448), so let's close this one.
