### ISSUE TITLE
Inconsistent etcd member list

### ISSUE THREAD

**Issue by FerminCastro** [etcd-io/etcd#13724]
Using etcd v3.5 in a K8 cluster
[opc@olk8-m1 ~]$ k exec etcd-olk8-m1 -n kube-system -- etcdctl
NAME:
        etcdctl - A simple command line client for etcd3.

USAGE:
        etcdctl [flags]

VERSION:
        3.5.0

Although RAFT INDEX is the same, the cluster seems healthy etc., the list of members returned by etcdctl is DIFFERENT depending on the member queried...
[opc@olk8-m1 ~]$ export ADVERTISE_URL=10.11.0.18:2379
[opc@olk8-m1 ~]$ sudo $etcdctlhome/etcdctl -w table member list --endpoints $ADVERTISE_URL --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
+------------------+---------+---------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |  NAME   |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
|  7a23c67093a3029 | started | olk8-m3 |       https://olk8-m3:2380 |    https://10.11.0.18:2379 |      false |
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380 | https://10.11.210.212:2379 |      false |
| 63c63522f0be24a6 | started | olk8-m1 |       https://olk8-m1:2380 |    https://10.11.0.16:2379 |      false |
+------------------+---------+---------+----------------------------+----------------------------+------------+
[opc@olk8-m1 ~]$ export ADVERTISE_URL=10.11.210.212:2379
[opc@olk8-m1 ~]$ sudo $etcdctlhome/etcdctl -w table member list --endpoints $ADVERTISE_URL --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
+------------------+---------+---------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |  NAME   |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
|  7a23c67093a3029 | started | olk8-m3 |       https://olk8-m3:2380 |    https://10.11.0.18:2379 |      false |
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380 | https://10.11.210.212:2379 |      false |
| 63c63522f0be24a6 | started | olk8-m1 |       https://olk8-m1:2380 |    https://10.11.0.16:2379 |      false |
+------------------+---------+---------+----------------------------+----------------------------+------------+
[opc@olk8-m1 ~]$ export ADVERTISE_URL=10.11.0.16:2379
[opc@olk8-m1 ~]$ sudo $etcdctlhome/etcdctl -w table member list --endpoints $ADVERTISE_URL --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
+------------------+---------+---------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |  NAME   |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
|  7a23c67093a3029 | started | olk8-m3 |       https://olk8-m3:2380 |    https://10.11.0.18:2379 |      false |
**| 12fdb31d793952ad | started | olk8-m1 |    https://10.10.0.23:2380 |    https://10.10.0.23:2379 |      false |**
**| 239afc0b6ba2be87 | started | olk8-m3 |    https://10.10.0.25:2380 |    https://10.10.0.25:2379 |      false |**
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380 | https://10.11.210.212:2379 |      false |
| 63c63522f0be24a6 | started | olk8-m1 |       https://olk8-m1:2380 |    https://10.11.0.16:2379 |      false |
**| 65f140f7892df7ea | started | olk8-m2 |    https://10.10.0.24:2380 |    https://10.10.0.24:2379 |      false |**
+------------------+---------+---------+----------------------------+----------------------------+------------+

Those extra members (12fdb31d793952ad , 239afc0b6ba2be87, 65f140f7892df7ea ) should just NOT BE THERE (they are actually in a different subnet from this K8 cluster). What could cause this inconsistency?

What makes things worse is that the cluster cannot be cleaned up. i.e :
[opc@olk8-m1 ~]$ export ADVERTISE_URL=10.11.0.16:2379
[opc@olk8-m1 ~]$ sudo $etcdctlhome/etcdctl -w table member list --endpoints $ADVERTISE_URL --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
+------------------+---------+---------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |  NAME   |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
|  7a23c67093a3029 | started | olk8-m3 |       https://olk8-m3:2380 |    https://10.11.0.18:2379 |      false |
**| 12fdb31d793952ad | started | olk8-m1 |    https://10.10.0.23:2380 |    https://10.10.0.23:2379 |      false |
| 239afc0b6ba2be87 | started | olk8-m3 |    https://10.10.0.25:2380 |    https://10.10.0.25:2379 |      false |**
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380 | https://10.11.210.212:2379 |      false |
| 63c63522f0be24a6 | started | olk8-m1 |       https://olk8-m1:2380 |    https://10.11.0.16:2379 |      false |
**| 65f140f7892df7ea | started | olk8-m2 |    https://10.10.0.24:2380 |    https://10.10.0.24:2379 |      false |**
+------------------+---------+---------+----------------------------+----------------------------+------------+

[opc@olk8-m1 ~]$ sudo $etcdctlhome/etcdctl  member remove **12fdb31d793952ad** --endpoints $ADVERTISE_URL --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
{"level":"warn","ts":"2022-02-21T16:44:05.455Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-1f1a487f-c491-4a0f-a5e2-556b11bcdf3f/10.11.0.16:2379","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: member not found"}
Error: etcdserver: **member not found**

This is causing issues on k8 upgrade because the upgrade is actually checking all the members listed in that  INCORRECT member list returned by 10.11.0.16:2379 and, obviously, some of those nodes are not reachable...

**Comment by serathius** [comment]
This is known issue for v3.5.0, please upgrade to v3.5.2.

**Comment by FerminCastro** [comment]
Thanks, can you point me to the precise issue if reported/fixed before? Also, would a plain update of the pod's image to 3.5.2 work at all? Notice that a "formal" upgrade would require upgrading kubeadm/kubernetes but it is precisely that kubernetes upgrade which is failing with this "incorrect" list of etcd members

**Comment by serathius** [comment]
https://github.com/etcd-io/etcd/issues/13196

**Comment by serathius** [comment]
Upgrading to v3.5.2 should make `etcdctl member remove` calls to succeed allowing you to remove the inconsistent members

**Comment by FerminCastro** [comment]
Ok, not sure if this is helpful but actually, after updating the k8 etcd image to 3.5.2, the zombie members do not show up anymore. i.e. it is not that with the new etcd we can remove those BUT that they are not showing up anymore. Before we upgraded to 3.5.2, this is what we were getting:

| ID | STATUS | NAME | PEER ADDRS | CLIENT ADDRS | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
| 7a23c67093a3029 | started | olk8-m3 | https://olk8-m3:2380/ | https://10.11.0.18:2379/ | false |
| 12fdb31d793952ad | started | olk8-m1 | https://10.10.0.23:2380/ | https://10.10.0.23:2379/ | false |
| 239afc0b6ba2be87 | started | olk8-m3 | https://10.10.0.25:2380/ | https://10.10.0.25:2379/ | false |
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380/ | https://10.11.210.212:2379/ | false |
| 63c63522f0be24a6 | started | olk8-m1 | https://olk8-m1:2380/ | https://10.11.0.16:2379/ | false |
| 65f140f7892df7ea | started | olk8-m2 | https://10.10.0.24:2380/ | https://10.10.0.24:2379/ | false |

And this is what we get now after upgrading:
+------------------+---------+---------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |  NAME   |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------+----------------------------+----------------------------+------------+
|  7a23c67093a3029 | started | olk8-m3 |       https://olk8-m3:2380 |    https://10.11.0.18:2379 |      false |
| 2784ae4111f5d7fd | started | olk8-m2 | https://10.11.210.212:2380 | https://10.11.210.212:2379 |      false |
| 63c63522f0be24a6 | started | olk8-m1 |       https://olk8-m1:2380 |    https://10.11.0.16:2379 |      false |
+------------------+---------+---------+----------------------------+----------------------------+------------+


So the zombie members have been removed.

**Comment by FerminCastro** [comment]
No problem and thanks for the help. That said, let me point to people to https://github.com/kubernetes/website/issues/31822 in case it helps others (because although the etcd behavior seems correct once upgraded to 3.5.2, things get really nasty for kubeadm users (which was the reason why this was so relevant: we could not upgrade k8 clusters because of this etcd bug). I will describe there the stpes we had to go through to get the kubeadm cluster finally upgraded. Thanks again

**Comment by FerminCastro** [comment]
Oh, and by the way, the zombie nodes REMAIN as soon as you revert the image (i.e. they disapeared when we upgraded to 3.5.2 but came back when we reverted/downgraded to 3.5.0)  So I think that when they did not show in 3.5.2 they were still there but did not show in the member list. It would be great to provide a solid list to clean up also in 3.5.2
