### ISSUE TITLE
Create a etcdctl command for coordinating downgrade

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#13735]
One of the problem of current downgrade process is lack of visibility into the process. Process is pretty complicated as it requires to manipulate multiple binaries and the only way to check the progress is via logs. 

The etcdctl downgrade procedure described in https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#downgrade-subcommand requires administrator to look for specific logs like `The server is ready to downgrade`. This is not only bad experience for users, but also very hard to debug. 

Without dedicated tooling I expect that debugging/reproducing user reported issues for downgrade will be impossible. 

As so I would like to propose to add a new command `etcdctl version status` that will provide information about status of versions within the cluster and process of downgrade/upgrade operations in process. 

As for output I would expect that user should get information about:
* Cluster version - informs minimal etcd version that can join
* Downgrade - informs if cluster is downgrading
* Etcd Binary version of each member - informs which members are left for downgrade upgrade
* Storage Version of member - informs if member managed to downgrade it's storage, replaces looking up `The server is ready to downgrade` log

The main problem here is that some information is decided by quorum (cluster version) and some is decided by member (binary version). One option is to show quorum decided information only on leader row.

Ideas on the output for downgrading cluster:
```
etcdctl version status -w table
+--------+-----------+--------+---------+---------+-----------+
|  NAME  | IS LEADER | SERVER | STORAGE | CLUSTER | DOWNGRADE |
+--------+-----------+--------+---------+---------+-----------+
| infra1 |   true    | v3.6.0 |   3.5   |  3.5    |    3.5    |
| infra2 |   false   | v3.5.2 |   3.5   |         |           |
| infra3 |   false   | v3.5.3 |   3.5   |         |           |
+--------+-----------+--------+---------+---------+-----------+
```
for upgrading cluster
```
etcdctl version status -w table
+--------+-----------+--------+---------+---------+-----------+
|  NAME  | IS LEADER | SERVER | STORAGE | CLUSTER | DOWNGRADE |
+--------+-----------+--------+---------+---------+-----------+
| infra1 |   true    | v3.6.0 |   3.6   |  3.5    |           |
| infra2 |   false   | v3.5.2 |   3.5   |         |           |
| infra3 |   false   | v3.5.3 |   3.5   |         |           |
+--------+-----------+--------+---------+---------+-----------+
```
and for normal cluster
```
etcdctl version status -w table
+--------+-----------+--------+---------+---------+-----------+
|  NAME  | IS LEADER | SERVER | STORAGE | CLUSTER | DOWNGRADE |
+--------+-----------+--------+---------+---------+-----------+
| infra1 |   true    | v3.6.0 |   3.6   |  3.6    |           |
| infra2 |   false   | v3.6.2 |   3.6   |         |           |
| infra3 |   false   | v3.6.3 |   3.6   |         |           |
+--------+-----------+--------+---------+---------+-----------+
```

Implementing this command is not a blocker for Alpha, however we should have something ready for v3.6 release.
cc @ahrtr @ptabor @spzala

**Comment by serathius** [comment]
This could also technically prompt us to switch `etcdctl downgrade` command to `etcdctl version downgrade`

**Comment by ahrtr** [comment]
The other proposal is to enhance the existing `etcdctl endpoint status `command. The existing output is something like below. We can change the `VERSION` to `MEMBER VERSION`, and add `STORAGE VERSION` and `TARGET VERSION`. Users can tell whether it's in progress of downgrade by comparing the `MEMBER VERSION` and `TARGET VERSION`, and also by looking at the `TARGET VERSION`'s value.

```
$ etcdctl endpoint status --cluster -w table
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT        |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|  http://127.0.0.1:2379 | 8211f1d0f64f3269 |   3.5.1 |   25 kB |      true |      false |         2 |          8 |                  8 |        |
| http://127.0.0.1:22379 | 91bc3c398fb3c146 |   3.5.1 |   25 kB |     false |      false |         2 |          8 |                  8 |        |
| http://127.0.0.1:32379 | fd422379fda50e48 |   3.5.1 |   25 kB |     false |      false |         2 |          8 |                  8 |        |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

```

The value of `TARGER VERSION` can be one of:
1. Something like "3.6, in progress", it means that the users have already issued the downgrade command, but the server is not ready yet;
2. Something like "3.6, ready", it means that the users have already issued the downgrade command, and the server is ready to downgrade;
3. Something like "3.6" or "", it means the cluster/server isn't in progress of downgrade or upgrade.

With regard to the existing `etcdctl downgrade` command, we can keep it as it's for now. One minor comment is that we can change `etcdctl downgrade enable <target_version>` to `etcdctl downgrade <target_version>`, and `etcdctl downgrade validate <target_version>` to `etcdctl downgrade <target_version> --dry-run`. It doesn't make much sense to have two actions in one command.  

cc @serathius @ptabor @spzala

**Comment by ahrtr** [comment]
Adding `etcdctl version status ` will also break the existing `etcdctl version` command, so it may not be good.  The third proposal is to enhance the existing `etcdctl version` command. We could add some additional flags to `etcdctl version` below, 

```
--server   It will display the versions (including both etcd binary version and storage version) of the etcd servers included in the "--endpoints"
--cluster  it will get the member list firstly, and then display the versions of all members.
```

If there is no any flags, then it keeps the existing behavior. 

We could implement both proposal 2 & 3, which means we can enhance both `etcdctl endpoint status` and `etcdctl version`.  I believe both of them can share some common code & logic.  

If you are OK, I can help to work on this for 3.6. Of course, I will provide more detailed document in the first step. WDYT? cc @serathius @ptabor @spzala

**Comment by serathius** [comment]
I think your proposal makes more sense as it doesn't complicate the server. We can just extend the `/version` endpoint on server to add remaining information and extend `etcdctl endpoint status` command.

**Comment by ahrtr** [comment]
Glad that we are on the same page. I will add one more field "storageVersion" for both `etcdctl endpoint status` and the `/version` endpoint. 

Just to be clear, we don't need the cluster version, because users can tell the cluster version themselves by comparing all members' versions. 

Regarding to the "target version" in the proposal 2, I will not add it for now, because:
1. It's specific to downgrade, which means it isn't generic.  In other words, it doesn't make sense for upgrade case, because upgrade is a natural and automatic process, users just need to replace the binary and start etcd again. 
2. Users can tell whether it's ready to be downgraded by looking at the storageVersion returned by either `etcdctl endpoint status` or `/version`. Once the storageVersion is equal to the targetVersion in the command `etcdctl downgrade enabled <targetVersion> `, then it means that it's ready to be downgraded.  Of course, we need to update the document to clarify this.

**Comment by ahrtr** [comment]
This task should have already been resolved by [13773](https://github.com/etcd-io/etcd/pull/13773) and [13772](https://github.com/etcd-io/etcd/pull/13772)
