### ISSUE TITLE
Different data in different etcd pods

### ISSUE THREAD

**Issue by sanjitp** [etcd-io/etcd#13734]
### What happened?

While checking the keys in the etcd pod , it was seen that the values for the key inside etcd database was different in one the pods,meaning pod-1 and pod-2 have same keys but pod-2 has different keys 

Etcd version used -3.3.11

### What did you expect to happen?

The data across all the pod in the database should be same 

### How can we reproduce it (as minimally and precisely as possible)?

Install the etcd with 3 replicas and put some keys in the database and check the keys in all the three replicas

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.3.11
Git SHA: 2cf9e51d2
Go Version: go1.10.7
Go OS/Arch: linux/amd64

$ etcdctl version
# paste output here
```
etcdctl version: 3.3.11
API version: 3.3

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
This issue lacks basic information about etcd configuration. `I run etcd in pods` is not enough to reproduce the issue. 

Please provide exact pod yaml configuration.

**Comment by sanjitp** [comment]
Please find the pod yaml configuration below:

microservice_SEC_KEY_MANAGEMENT_PORT_8210_TCP=tcp://10.102.60.80:8210
VALID_PARAMETERS=valid
ETCD_INITIAL_CLUSTER_TOKEN=microservice-data-distributed-coordinator-ed
ETCD_MAX_SNAPSHOTS=3
TZ=UTC
HOSTNAME=microservice-data-distributed-coordinator-ed-0
COMPONENT_VERSION=v3.3.11
ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
ETCD_HEARTBEAT_INTERVAL=100
ETCD_AUTO_COMPACTION_RETENTION=100
DISARM_ALARM_PEER_INTERVAL=6
ETCD_TRUSTED_CA_FILE=/data/combinedca/cacertbundle.pem
MONITOR_ALARM_INTERVAL=5
microservice_SEC_KEY_MANAGEMENT_SERVICE_HOST=10.102.60.80
microservice_SEC_KEY_MANAGEMENT_PORT_8200_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
microservice_SEC_KEY_MANAGEMENT_SERVICE_PORT_HTTPS_SHELTER=8210
ETCDCTL_CERT=/run/sec/certs/client/clicert.pem
DEFRAGMENT_ENABLE=true
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_SERVICE_HOST=10.100.140.81
KUBERNETES_PORT=tcp://10.96.0.1:443
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_SERVICE_PORT=2379
PWD=/
ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
HOME=/home/dced
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_SERVICE_PORT_CLIENT_PORT_TLS=2379
ETCD_AUTO_COMPACTION_MODE=revision
KUBERNETES_SERVICE_PORT_HTTPS=443
microservice_SEC_KEY_MANAGEMENT_PORT_8210_TCP_ADDR=10.102.60.80
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_PORT_2379_TCP_ADDR=10.100.140.81
KUBERNETES_PORT_443_TCP_PORT=443
ETCD_DEBUG=false
microservice_SEC_KEY_MANAGEMENT_SERVICE_PORT_HTTPS_KMS=8200
ETCD_CERT_FILE=/run/sec/certs/server/srvcert.pem
ETCD_FIFO_DIR=/fifo
ETCD_PEER_AUTO_TLS=true
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_PORT_2379_TCP_PORT=2379
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_PORT_2379_TCP=tcp://10.100.140.81:2379
DEFRAGMENT_PERIODIC_INTERVAL=60
COMPONENT=etcd
ETCD_DATA_DIR=/data
ETCD_LOG_PACKAGE_LEVELS=etcdserver=INFO,security=INFO
ETCD_CLIENT_CERT_AUTH=true
TERM=xterm
microservice_SEC_KEY_MANAGEMENT_PORT_8210_TCP_PROTO=tcp
microservice_SEC_KEY_MANAGEMENT_PORT=tcp://10.102.60.80:8200
ETCDCTL_ENDPOINTS=microservice-data-distributed-coordinator-ed.zmorrah:2379
ETCD_METRICS=basic
ETCDCTL_API=3
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_PORT=tcp://10.100.140.81:2379
ETCD_SNAPSHOT_COUNT=5000
ETCD_MAX_WALS=3
SHLVL=1
microservice_SEC_KEY_MANAGEMENT_PORT_8200_TCP_ADDR=10.102.60.80
KUBERNETES_SERVICE_PORT=443
ETCD_INITIAL_ADVERTISE_PEER_URLS=https://microservice-data-distributed-coordinator-ed-0.microservice-data-distributed-coordinator-ed-peer.zmorrah.svc.cluster.local:2380
microservice_SEC_KEY_MANAGEMENT_PORT_8210_TCP_PORT=8210
ETCD_KEY_FILE=/run/sec/certs/server/srvprivkey.pem
ETCD_ENABLE_V2=false
ETCD_ELECTION_TIMEOUT=1000
ETCDCTL_CACERT=/data/combinedca/cacertbundle.pem
ETCD_NAME=microservice-data-distributed-coordinator-ed-0
ETCD_QUOTA_BACKEND_BYTES=268435456
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ETCD_ADVERTISE_CLIENT_URLS=https://microservice-data-distributed-coordinator-ed-0.microservice-data-distributed-coordinator-ed.zmorrah:2379
microservice_SEC_KEY_MANAGEMENT_SERVICE_PORT=8200
KUBERNETES_SERVICE_HOST=10.96.0.1
FLAVOUR=etcd-v3.3.11-linux-amd64
microservice_SEC_KEY_MANAGEMENT_PORT_8200_TCP=tcp://10.102.60.80:8200
microservice_DATA_DISTRIBUTED_COORDINATOR_ED_PORT_2379_TCP_PROTO=tcp
microservice_SEC_KEY_MANAGEMENT_PORT_8200_TCP_PORT=8200
ETCDCTL_KEY=/run/sec/certs/client/cliprivkey.pem
_=/usr/bin/env

**Comment by ahrtr** [comment]
It seems this issue is a duplicate to [13503](https://github.com/etcd-io/etcd/issues/13503). There is a long discussion back and forth in the issue. 

Please attach the exact POD manifest files and detailed steps to reproduce this issue. @rahulbapumore @sanjitp
