### ISSUE TITLE
cluster version is different with server version

### ISSUE THREAD

**Issue by zaunist** [etcd-io/etcd#13742]
### What happened?

When I send a request to `localhost:2379/version`, I get this message 

```
{"etcdserver":"3.6.0-pre","etcdcluster":"3.6.0"}
```

The etcdcluster version always `3.4.0`、`3.5.0`、`3.6.0`, why is the cluster version number always an integer?

I'm very appreciate if anyone can tell me why?

### What did you expect to happen?

The cluster version is same to server version.

### How can we reproduce it (as minimally and precisely as possible)?

curl etcdendpoint:2379/version

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.6.0-pre

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by xiang90** [comment]
> why is the cluster version number always an integer?

Not exactly sure what you mean. But the cluster version only cares about the minor version, not the patch version or any pre-release annotation. All releases within the minor versions are compatible, so the cluster version does not need to be aware of the patch version. See https://semver.org/.
