### ISSUE TITLE
Can't start two cluster by integration package? 

### ISSUE THREAD

**Issue by lance6716** [etcd-io/etcd#13758]
### What happened?

we upgrade our etcd from v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9 to v3.5.2, found many unit tests are broken

Most of them I can find the root cause, but this one I have no idea

```
func TestUpgrade(t *testing.T) {
	integration.BeforeTestExternal(t)
	mockCluster := integration.NewClusterV3(t, &integration.ClusterConfig{Size: 1})
	defer mockCluster.Terminate(t)

	bigCluster := integration.NewClusterV3(t, &integration.ClusterConfig{Size: 1, MaxTxnOps: 2048})
	defer bigCluster.Terminate(t)
// omitted
}
```

it will fail without printing the reason. Can you help me?

### What did you expect to happen?

no error

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Etcd version (please run commands below)

<details>

v3.5.2

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
The listen address conflicts. Please add `UseTCP: true`, see example below,

```
func TestUpgrade(t *testing.T) {
	integration.BeforeTestExternal(t)
	mockCluster := integration.NewCluster(t, &integration.ClusterConfig{Size: 1, UseTCP: true})
	defer mockCluster.Terminate(t)

	bigCluster := integration.NewCluster(t, &integration.ClusterConfig{Size: 1, MaxTxnOps: 2048, UseTCP: true})
	defer bigCluster.Terminate(t)
	// omitted
}
```

**Comment by lance6716** [comment]
@ahrtr Thanks! I'll close it.

**Comment by lance6716** [comment]
Oh I still think the socket conflict error should be more readable, just a little advice.
