### ISSUE TITLE
How to change S3 backup bucket region?

### ISSUE THREAD

**Issue by aryabchenko** [etcd-io/etcd#13755]
### What happened?

I changed S3 backup bucket region (made backup, deleted old bucket, recreated in a new region, restored backup).
Now both etcd-manager-main and etcd-manager-events pods give me error:
```
W0302 14:25:00.430618    3752 controller.go:163] unexpected error running etcd cluster reconciliation loop: error checking control store: error reading cluster-creation marker file s3://mybucket/k8s/backups/etcd/main/control/etcd-cluster-created: error fetching s3://mybucket/k8s/backups/etcd/main/control/etcd-cluster-created: BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region at endpoint ''
```
How to change bucket region?

### What did you expect to happen?

Easy way to change or changed automagically

### How can we reproduce it (as minimally and precisely as possible)?

steps above

### Etcd version (please run commands below)

<details>
3.4.13
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
This issue looks unrelated to etcd. Please provide etcd's log and configuration if you see any issue in etcd.

**Comment by aryabchenko** [comment]
@ahrtr how this issue can be unrelated to etcd if the description contains log from etcd pods?
I got this piece of logs using 
`for i in `kubectl get pods -A | grep etcd| awk '{print $2}'`; do kubectl logs $i | grep backup; done`
moreover in the log you can see that it cannot fetch the following file:
s3://mybucket/k8s/backups/**etcd**/main/control/**etcd-cluster-created**
so it's totally related to etcd!
The file is there, but cause I moved bucket into different region - it complains it cannot find this bucket in the old region.
How can I change it?

**Comment by ahrtr** [comment]
The log is coming from `controller.go`, note that etcd doesn't even have the file.

**Comment by serathius** [comment]
Etcd project doesn't handle backups or provide any tooling for backup. Problem is handled by external tools like etcdadm etc. Please identify the backup tools you use for etcd and file issue to proper project.

**Comment by aryabchenko** [comment]
Yep, you are right and sorry, It was kops issue, it couldn't find a reallocated bucket until I updated cluster with new version of kubernetes with kops, so it changed its internal config to the correct location.
