### ISSUE TITLE
Is snapshot the only way to recover when lost quorum ? 

### ISSUE THREAD

**Issue by rayliu419** [etcd-io/etcd#13765]
Hi guys, 

I searched some offical documents and found it looks like Etcd can only be recovered using snapshot when lost quorum, do we have any other methods to rebuild a Etcd cluster without losing data? E.g., if Etcd now has 1000 records and snapshot only has 800 records, when the Etcd cluster fails due to quorum, can we restore the rest 200 records? 

Thanks

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
