### ISSUE TITLE
Etcd has some security issues involving password complexity, sensitive information leakage, interfaces that do not require authentication, and accounts that cannot be locked

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#13768]
1. Reuse of wrong password to access interface /v2/auth/users, account will not be locked out
2. Call etcd api to use weak password to perform user creation and update user password operations, there is no weak password checking mechanism
3. Open etcd debug log, call etcd api to perform user creation and update user password operations, the password ciphertext will be 
4. Etcd has interfaces that can be accessed without authentication, health and version interfaces

**Comment by SingleThread** [comment]
> 1. I’m not sure what’s the actual issue, but recommend not to use v2 interface. Note that v2 API and v3 API are completely separated including authentication mechanism.
> 2. It’s documented in https://etcd.io/docs/v3.5/op-guide/authentication/rbac/#notes-on-password-strength Defining password strength is difficult so I think it’s not reasonable to check in etcd side.
> 3. I think it’s fixed in the stable releases. Could you share the version you are using?
> 4. These endopints don’t leak sensitive information. Do you have motivation for protecting these endpoints?

3.currently using version 3.5.0

**Comment by mitake** [comment]
That's the debug log, so you are using `--log-level=debug` right? I think that shouldn't be used in production environments so practically not harmful. But if you have motivation to change the behavior, I think we can fix.
