### ISSUE TITLE
The new(-ish) etcdutl utility isn't included in etcd container image

### ISSUE THREAD

**Issue by pcgeek86** [etcd-io/etcd#13764]
### What happened?

Apparently `etcdctl snapshot restore` has been deprecated in favor of a command called `etcdutl` instead.
However, the new utility isn't included in the `etcd` container image, requiring separate steps to install it directly onto the host.

### What did you expect to happen?

`etcdutl` should be included in the `etcd` container image, so it doesn't require separate steps to install. If `etcdctl` is available, then `etcdutl` should be as well.

### How can we reproduce it (as minimally and precisely as possible)?

```
docker run --rm --interactive --tty k8s.gcr.io/etcd:3.5.1-0
```

### Etcd version (please run commands below)

n/a

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
`k8s.gcr.io/etcd:3.5.1-0` is not etcd community owned image, but K8s one. Please file an issue to kubernetes/kubernetes repo.
