### ISSUE TITLE
Track stabilization of --experimental-warning-unary-request-duration flag

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#13783]
This is tracking issue that tracks graduation of this feature. Let's work towards stabilization of the feature by discussing what steps   should be taken for graduation.
Context https://github.com/etcd-io/etcd/issues/13775

**Comment by lavacat** [comment]
Flag was originally added here https://github.com/etcd-io/etcd/pull/13236
Before the value was hardcoded to 300. 

The need is this flag is clear - depending on latency, one can have too much noise in the logs with default 300.
Imo, there is nothing experimental about this flag, so it's ok to rename. It will be less confusing compared to other experimental flags.
cc @spzala
