### ISSUE TITLE
build benchmark fail

### ISSUE THREAD

**Issue by aRanhy** [etcd-io/etcd#13795]
Execute "go the get go. etcd. io/etcd/tools/benchmark" ，
But prompt "package crypto/ed25519: Unrecognized import path crypto/ ED25519 (import path does not begin with hostname) ", 
And then to download git clone https://github.com/golang/crypto.git, and then suggests 
"the import cycle not allowed
package go.etcd.io/etcd/v3/tools/benchmark
imports go.etcd.io/etcd/v3/tools/benchmark/cmd
imports go.etcd.io/etcd/server/v3/lease
imports go.etcd.io/etcd/server/v3/storage/schema
imports go.etcd.io/etcd/server/v3/auth
imports github.com/golang-jwt/jwt
imports crypto/ed25519
imports crypto/ed25519".

How do I build Benchmark correctly?

**Comment by serathius** [comment]
Please read https://github.com/etcd-io/etcd/tree/main/tools/benchmark
```
$ go get go.etcd.io/etcd/v3/tools/benchmark
$ benchmark --help
```

**Comment by aRanhy** [comment]
The problem has been solved, which is caused by the low go version. Thank you very much for your reply.
