### ISSUE TITLE
Add integration test for etcd tracing

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#13814]
We can follow the same way as Kubernetes did in [pull/103234](https://github.com/kubernetes/kubernetes/pull/103234). 

It's also the prerequisite to graduate/stable the experimental tracing flags. [12460](https://github.com/etcd-io/etcd/issues/12460)

**Comment by VinozzZ** [comment]
Hi there, I would like to pick up this issue

**Comment by ahrtr** [comment]
Thanks @VinozzZ ,  please feel free to deliver a PR for this.
