### ISSUE TITLE
What are the best practices to get a good perfomance disk with least possible latency for ETCD?

### ISSUE THREAD

**Issue by rakeshk121** [etcd-io/etcd#13827]
What are the best practices to get a good perfomance disk with least possible latency for ETCD?

As etcd is a consistent and highly-available key value store used as Kubernetes' backing store for all cluster data.
Im looking for best practices that can be applied to get the disk latency to least value so as to get a best perfomance disk for etcd.
Using SSD disks would get the best performace but im looking for other options available to achive this i.e, it could be anything in infrastructure in terms of hardware or software configurations.

Hypervisor : VMware/ Openstack
Orchestration : Openshift/okd 4.x

**Comment by yankay** [comment]
HI @rakeshk121 , the question may be answered in the https://app.slack.com/client/T09NY5SBT/C3HD8ARJ5/thread/C3HD8ARJ5-1647851939.693229.

The OpenShift Docs give us suggestion at: https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-host-practices.html#recommended-etcd-practices_

And the Etcd Docs is at:  https://etcd.io/docs/v3.5/tuning/#disk

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
