### ISSUE TITLE
error verifying flags, 'Restart=on-failure' is not a valid flag. See 'etcd --help'

### ISSUE THREAD

**Issue by QiuToo** [etcd-io/etcd#13833]
[root@two-master1 ~]# cat  /etc/etcd/etcd.conf 
#[Member]
ETCD_NAME="etcd1"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://192.168.2.101:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.2.101:2379,http://127.0.0.1:2379"
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.2.101:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.2.101:2379"
ETCD_INITIAL_CLUSTER="etcd1=https://192.168.2.101:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
[root@two-master1 ~]# 
[root@two-master1 ~]# cat  /usr/lib/systemd/system/etcd.service 
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target
 
[Service]
Type=notify
EnvironmentFile=-/etc/etcd/etcd.conf
WorkingDirectory=/var/lib/etcd/
ExecStart=/usr/local/bin/etcd \
  --cert-file=/etc/etcd/ssl/etcd.pem \
  --key-file=/etc/etcd/ssl/etcd-key.pem \
  --trusted-ca-file=/etc/etcd/ssl/ca.pem \
  --peer-cert-file=/etc/etcd/ssl/etcd.pem \
  --peer-key-file=/etc/etcd/ssl/etcd-key.pem \
  --peer-trusted-ca-file=/etc/etcd/ssl/ca.pem \
  --peer-client-cert-auth \
  --client-cert-auth \
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
[root@two-master1 ~]# systemctl start etcd
Job for etcd.service failed because the control process exited with error code. See "systemctl status etcd.service" and "journalctl -xe" for details.
[root@two-master1 ~]# 
[root@two-master1 ~]# 
[root@two-master1 ~]# systemctl status  etcd  -l
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 二 2022-03-22 22:35:35 CST; 46s ago
  Process: 1584 ExecStart=/usr/local/bin/etcd --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --trusted-ca-file=/etc/etcd/ssl/ca.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/etcd/ssl/etcd-key.pem --peer-trusted-ca-file=/etc/etcd/ssl/ca.pem --peer-client-cert-auth --client-cert-auth Restart=on-failure (code=exited, status=1/FAILURE)
 Main PID: 1584 (code=exited, status=1/FAILURE)

3月 22 22:35:35 two-master1 systemd[1]: Starting Etcd Server...
3月 22 22:35:35 two-master1 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
3月 22 22:35:35 two-master1 systemd[1]: Failed to start Etcd Server.
3月 22 22:35:35 two-master1 systemd[1]: Unit etcd.service entered failed state.
3月 22 22:35:35 two-master1 systemd[1]: etcd.service failed.
[root@two-master1 ~]# 
[root@two-master1 ~]# /usr/local/bin/etcd --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --trusted-ca-file=/etc/etcd/ssl/ca.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/etcd/ssl/etcd-key.pem --peer-trusted-ca-file=/etc/etcd/ssl/ca.pem --peer-client-cert-auth --client-cert-auth Restart=on-failure
2022-03-22 22:36:56.135393 E | etcdmain: error verifying flags, 'Restart=on-failure' is not a valid flag. See 'etcd --help'.
[root@two-master1 ~]# 
[root@two-master1 ~]# ls  /etc/etcd/
etcd.conf  ssl
[root@two-master1 ~]# ls  /etc/etcd/ssl/
ca-key.pem  ca.pem  etcd-key.pem  etcd.pem
[root@two-master1 ~]# 
[root@two-master1 ~]# 
[root@two-master1 ~]# ls  /var/lib/etcd/
default.etcd
[root@two-master1 ~]#

**Comment by serathius** [comment]
This is an error in your systemd configuration, not an bug in Etcd.
