### ISSUE TITLE
etcd v3.4.13 compact failed after defrag

### ISSUE THREAD

**Issue by nomorer** [etcd-io/etcd#13841]
### What happened?

I am running etcd V3.4.13 as cluster used by a large K8s Cluster, which db size over 4GB.
Etcd compaction is triggered by the api-server every 5min by default. 

Why sometimes  "finished scheduled compaction"  is not showing up in etcd's log , after then Etcd request latencies increases (over 1s) when compacting
<img width="741" alt="image" src="https://user-images.githubusercontent.com/3734078/160252279-172d2530-831d-4d8f-bddc-ae2a173e49a3.png">

### What did you expect to happen?

the compaction can be finished expectedly

### How can we reproduce it (as minimally and precisely as possible)?

run a defrag for a endpoint.
it is unexpected behavior

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.13
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.16.6
Go OS/Arch: linux/amd64
```

</details>

**Comment by nomorer** [comment]
@tangcong

**Comment by lavacat** [comment]
>run a defrag for a endpoint.

Are you running with --experimental-backend-bbolt-freelist-type=hashmap?
If yes, there is a bug that causes reset of bolt db options after defrag

https://github.com/etcd-io/etcd/pull/13713

**Comment by nomorer** [comment]
> 



> > run a defrag for a endpoint.
> 
> Are you running with --experimental-backend-bbolt-freelist-type=hashmap? If yes, there is a bug that causes reset of bolt db options after defrag
> 
> #13713



> > run a defrag for a endpoint.
> 
> Are you running with --experimental-backend-bbolt-freelist-type=hashmap? If yes, there is a bug that causes reset of bolt db options after defrag
> 
> #13713

**Comment by nomorer** [comment]
> 
yes.
compare to before,  latency slow down significantly during compactions after the PR merged.
but etcd compaction is still abnormal, it doesn't print "finished scheduled compaction"
