### ISSUE TITLE
Non-error logs poured into stderr

### ISSUE THREAD

**Issue by Teja327r** [etcd-io/etcd#13851]
### What happened?

Non-error , info related logs are coming in stderr stream instead of stdout stream.

### What did you expect to happen?

Non-error and info related logs coming into correct path. i.e stdout.

### How can we reproduce it (as minimally and precisely as possible)?

we can check info messages coming in stderr stream.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
3.4.16
$ etcdctl version
3.4.16
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by lavacat** [comment]
I think this was answered [here](https://github.com/etcd-io/etcd/issues/4052#issuecomment-166898533) 
> stderr is not just for errors, it's for any diagnostic information. 

and [here](https://github.com/etcd-io/etcd/issues/9179#issuecomment-363557292) 
> it is wrong that only error should go to stderr.

**Comment by serathius** [comment]
@lavacat thanks for context.
