### ISSUE TITLE
etcdctl or etcdutl that is the question (shakespeare) 

### ISSUE THREAD

**Issue by dazmc** [etcd-io/etcd#13863]
On the [v3.5 restore a cluster](https://etcd.io/docs/v3.5/op-guide/recovery/#restoring-a-cluster) page it has `etcdutl` as the command to use for restore 

When you run etcdctl to do a restore
`sudo ETCDCTL_API=3 ./etcdctl.....`
**it says**
`"Deprecated: Use etcdutl snapshot restore instead."`

However on [v3.6 restore a cluster](https://etcd.io/docs/v3.6/op-guide/recovery/#restoring-a-cluster) page it has etcdctl as the restore command..

So which one is it? 

Also should I be using etcdctl for backups and etcdutl for restores? it isn't really clear to me as etcdutl has a backup command as well (but is marked as legacy in the help)

**Comment by kkkkun** [comment]
Thanks 
Duplicated  https://github.com/etcd-io/website/issues/382

In 3.6， we should use `etcdctl save ...` and  `etcdutl restore/status ...`. it updated in https://github.com/etcd-io/etcd/blob/main/etcdutl/README.md. 

[v3.6 restore a cluster](https://etcd.io/docs/v3.6/op-guide/recovery/#restoring-a-cluster) still no update. 

I will commit PR to update this.
