### ISSUE TITLE
AuthStore::Recover is not invalidating caches. 

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#13883]
### What happened?

No repro in practice yet attempted. Adding FTR.

The method: 
https://github.com/etcd-io/etcd/blob/a08d479463960948d5d9c3508623ade915c6e66f/server/auth/store.go#L374

is used when a new snapshot is received over raft (e.g. server was lagging). 

The method is not invalidating: 
https://github.com/etcd-io/etcd/blob/a08d479463960948d5d9c3508623ade915c6e66f/server/auth/store.go#L237

This creates risk that data server read out of the cache might be stale (e.g. permission got revoked in the 'meantime') but the cache is missing updates skipped in the WAL log application (because it loaded a fresher snapshot). 

### What did you expect to happen?

Reinitialize the cache. 

### How can we reproduce it (as minimally and precisely as possible)?

We need a test that will: 
  - run 3 etcd instances
  - grant some permissions on ranges
  - diconnect a single member
  - revoke the permissions
  - commit a lot of transactions (or force the disconnected member run out of log horizont) 
  - reconnect the member... the member is expected to download the snapshot...
  - check whether the member revokes the access to the given key-range.

### Etcd version (please run commands below)

Spotted in the `main` tree. But the logic was rather not changed recently.

**Comment by mitake** [comment]
@ptabor Thanks for figuring out this. I'll try to reproduce and analyze related code this weekend.

**Comment by mitake** [comment]
@ptabor I'm still trying to reproduce, but invalidating `rangePermCache` in `authStore.Recover()` is fine and good for defensive purpose. I'll open a PR for the change.

**Comment by serathius** [comment]
Fixed with https://github.com/etcd-io/etcd/pull/14358
