### ISSUE TITLE
etcd momory usage grows slowly until OOM with small data size [3.3.18&3.4.13]

### ISSUE THREAD

**Issue by fistomina** [etcd-io/etcd#13918]
**What happened?**
etcd node memory usage grows slowly for hours, and finally execeeds 90%, cuasing OOM. Generally, the memory of the leader node increases the fastest.

**cluster info**
3 nodes 4U8G
db-size:101M
etcd Version: 3.3.18
Go Version: go1.11.2
This etcd cluster is not used by k8s, but a customized service with range/lock/put oprations.

**go pprof dumped at memory usage 80%**
Showing nodes accounting for 4664.19MB, 100% of 4664.19MB total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                         4627.81MB   100% |   github.com/coreos/etcd/etcdserver/api/v3rpc.(*codec).Marshal D:\01 GitLab\etcd\04 etcdCMW\src\github.com\coreos\etcd\etcdserver\api\v3rpc\codec.go:22
 4627.81MB 99.22% 99.22%  4627.81MB 99.22%                | github.com/coreos/etcd/vendor/github.com/gogo/protobuf/proto.Marshal D:\01 GitLab\etcd\04 etcdCMW\src\github.com\coreos\etcd\vendor\github.com\gogo\protobuf\proto\table_marshal.go:2938
![image](https://user-images.githubusercontent.com/37359796/166853304-4e452033-dc70-4dd8-9647-c0f9e519f80a.png)
(inuse_objects png size is too big to show)
![inuse-objs](https://user-images.githubusercontent.com/37359796/162600895-435f8052-3d3d-47b4-9156-6e69b7b6dd9c.png)

compare between memory pprof in different mem usage, I found the proto.Marshal object is increasing, and it's average size is 12.17M.
![image](https://user-images.githubusercontent.com/37359796/162601014-b7ae068a-396f-4a9e-a7e7-c05924f5accd.png)
In what circumstances does the object accumulate without being recycled? How does this happen?

I found some expensive put and range in logs, but the qps is not so high. About 5 opts/s from time to time with 10-30K kv size. Would this cause memory keep increasing?

**Comment by ptabor** [comment]
Could you, please, repro this with version 3.5.* ?

`3.3.*` is end of live and potentially only a security fixes are being cherry-picked.

**Comment by fistomina** [comment]
> Could you, please, repro this with version 3.5.* ?
> 
> `3.3.*` is end of life and potentially only a security fixes are being cherry-picked.

thx, v3.5.* is not yet used in our production environment, I repreduced it in v3.4.13, and will show details later.

**Comment by fistomina** [comment]
> Could you, please, repro this with version 3.5.* ?
> 
> `3.3.*` is end of life and potentially only a security fixes are being cherry-picked.

I have reproduced it in 3.4.13, almost all memory is in etcdserverpb.(*RangeResponse).Marshal, I can find these objects in "inuse_space", but not in "inuse_object".
**inuse_space view**
![image](https://user-images.githubusercontent.com/37359796/166851779-9352ecde-73c7-46a3-acf1-14541a999bd1.png)
**inuse_object view**
![image](https://user-images.githubusercontent.com/37359796/166853122-dcbd0f7c-51b3-4cf6-b44d-015fb7d4dd3d.png)
memory is used by code: etcdserver\etcdserverpb\rpc.pb.go:5264
![image](https://user-images.githubusercontent.com/37359796/166853232-393f890f-1eaa-425d-b410-442551d62265.png)

**Comment by Limnotation** [comment]
Any updates on this issue?

**Comment by serathius** [comment]
It has not been reproduced on latest supported version of etcd (v3.4.21, v3.5.5) so there is no progress.
