### ISSUE TITLE
etcdserver: large snapshots cause missing leader heartbeat events

### ISSUE THREAD

**Issue by donalhunt** [etcd-io/etcd#13913]
### What happened?

Over the course of several months, I've observed frequent "leader failed to send out heartbeat on time" warnings in etcd server logs for 3-node clusters. Despite some efforts to tune the performance of the filesystem and perform compaction / defragmentation tasks on the clusters, we still see frequent warnings several times a day.

I have been unable to identify a trend with regard what might be influencing the snapshot/heartbeat issue but do not consider myself an etcd expert. Previously reported issues that seem similar in nature typically do not provide enough information and/or the reporter lets the issue go stale.

### What did you expect to happen?

Performing snapshots should not result in lost leader heartbeats.

### How can we reproduce it (as minimally and precisely as possible)?

Reproducing this issue is non-trivial.

Environment setup:
- etcd 3.5.1
- 3 node cluster (instances are running on VMware VMs - VM hosts are running ESXi hypervisors with all-flash storage volumes provisioned over NFS3 protocol. Currently provisioned for 1000 IOPS)
- max-txn-ops = 2048
- certificates in use for peers and clients
- RBAC using username/password

Some observations to date:
- large etcd DB size (50-200MB) seems to be a factor. In clusters with <10MB DB size, warnings rarely surface.
- clusters with large amounts of reads and writes is a factor. In an environments where we are frequently making lots of changes to key value pairs, we see many more warnings.
- network latency does not appear to be an issue. All nodes are within the same datacenter.
- review of similar issues being reported suggests that variable IO can be seen when vmware snapshots are used. this may be propagating up to the performance we then see in etcd. Have not exhausted this avenue yet but certainly can if it's likely to be a contributing factor.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.1
Git SHA: e8732fb5f
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.1
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here
unable to provide at this time.

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
+------------------+---------+-------------------+-----------------------+-----------------------+------------+
|        ID        | STATUS  |       NAME        |       PEER ADDRS      |      CLIENT ADDRS     | IS LEARNER |
+------------------+---------+-------------------+-----------------------+-----------------------+------------+
| 2bbcb93380c87c30 | started | node3.example.com | https://10.0.0.3:2380 | https://10.0.0.3:2379 |      false |
| 848f1b1c5433f65a | started | node1.example.com | https://10.0.0.4:2380 | https://10.0.0.4:2379 |      false |
| fba1802d633b824f | started | node2.example.com | https://10.0.0.2:2380 | https://10.0.0.2:2379 |      false |
+------------------+---------+-------------------+-----------------------+-----------------------+------------+


+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT     |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://10.0.0.3:2379 | 2bbcb93380c87c30 |   3.5.1 |   39 MB |     false |      false |        43 |    6500311 |            6500311 |        |
| https://10.0.0.2:2379 | fba1802d633b824f |   3.5.1 |   39 MB |     false |      false |        43 |    6500312 |            6500312 |        |
| https://10.0.0.4:2379 | 848f1b1c5433f65a |   3.5.1 |   39 MB |      true |      false |        43 |    6500313 |            6500313 |        |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

</details>

### Relevant log output

```shell
Mar 30 03:31:01 node1 etcd[18599]: {"level":"info","ts":"2022-03-30T03:31:01.762Z","caller":"v3rpc/maintenance.go:125","msg":"sending database snapshot to client","total-bytes":34729984,"size":"35 MB"}
Mar 30 03:31:02 node1 etcd[18599]: {"level":"info","ts":"2022-03-30T03:31:02.024Z","caller":"v3rpc/maintenance.go:165","msg":"sending database sha256 checksum to client","total-bytes":34729984,"checksum-size":32}
Mar 30 03:31:02 node1 etcd[18599]: {"level":"info","ts":"2022-03-30T03:31:02.025Z","caller":"v3rpc/maintenance.go:174","msg":"successfully sent database snapshot to client","total-bytes":34729984,"size":"35 MB","took":"now"}

Mar 30 03:31:02 node1 etcd[18599]: {"level":"warn","ts":"2022-03-30T03:31:02.325Z","caller":"etcdserver/raft.go:369","msg":"leader failed to send out heartbeat on time; took too long, leader is overloaded likely from slow disk","to":"fba1802d633b824f","heartbeat-interval":"100ms","expected-duration":"200ms","exceeded-duration":"26.524094ms"}
Mar 30 03:31:02 node1 etcd[18599]: {"level":"warn","ts":"2022-03-30T03:31:02.325Z","caller":"etcdserver/raft.go:369","msg":"leader failed to send out heartbeat on time; took too long, leader is overloaded likely from slow disk","to":"2bbcb93380c87c30","heartbeat-interval":"100ms","expected-duration":"200ms","exceeded-duration":"26.635636ms"}
```

**Comment by donalhunt** [comment]
Waiting on #13906 so the logs provide a little more insight (how many ms the snapshot is taking). Current working theory is that is greater than 100ms which then causes the leader heartbeat to be missed.

**Comment by lavacat** [comment]
Do you have access to the metrics?
1. How frequent is rate(etcd_server_heartbeat_send_failures_total[1m]) spiking?
2. If its snapshot related, do you see correlation with rate(etcd_disk_backend_snapshot_duration_seconds_count[1m]) ?

**Comment by donalhunt** [comment]
Sorry for the delay (was on vacation for a few weeks). We don't currently use prometheus / grafana for monitoring so need to setup monitoring to gather those metrics.

Will try and provide an update in the next week or so.
