### ISSUE TITLE
how to know history versions of a key

### ISSUE THREAD

**Issue by ABlueCy** [etcd-io/etcd#13921]
I know that we can get a key with a special reversion and the treeindex has stroed the generations info that recorded history reversions of key. 
my question is how to get those key history reversions.

**Comment by ptabor** [comment]
Please use Watch API. It allows you to specify both: key-range and start-revision you want to load the history from. 

Please notice that 'compaction' might limit the history that etcd stores.

**Comment by ABlueCy** [comment]
thx ptabor. I tried to use Watch API and got the  history from.
however, based compaction model, I have no idea of which revisions  are stored and just try many times to inputing start-revision .
how can I get the  revision that etcd stores with compaction model.
best wish.

**Comment by ABlueCy** [comment]
@ptabor
