### ISSUE TITLE
[Test Infra] Jepsen Testing

### ISSUE THREAD

**Issue by endocrimes** [etcd-io/etcd#13939]
As part of the 3.5.3 release process we realized that a lot of etcd release qualification and testing is currently adhoc and manual.

To gain more confidence in new features and releases, we want to make a set of improvements to test and release infrastructure. One of those is modernizing the [jepsen](https://jepsen.io) tests, and using them to test etcd's correctness as a distributed system.

I've started making progress on that in a fork of the existing jepsen suite for etcd [here](https://github.com/endocrimes/etcd-1), although a lot of the changes are currently in a messy state on my system as I figure out what we need.

**Comment by shalinmangar** [comment]
Thanks @endocrimes! Let me know when you feel comfortable pushing your changes to a branch. In the meanwhile, I will set up Jepsen's etcd tests on an instance in the cloud and get up to speed (it's been a few years since I used them).
