### ISSUE TITLE
I want etcd to compress automatically by time (and keep revision 1000)

### ISSUE THREAD

**Issue by MagicStarTrace** [etcd-io/etcd#13958]
### What happened?

My current configuration for etcd automatic compression is like this：

auto-compaction-mode: revision
auto-compaction-retention: "1000"

it will automatically compress

### What did you expect to happen?

I see etcd's config file description can be based on time , we expect to implement stress test once a day and keep 1000, but now it is 5 minutes which is a bit frequent

-------------------------------------
auto-compaction-mode: periodic
auto-compaction-retention: "1"

### How can we reproduce it (as minimally and precisely as possible)?

No need to reproduce

### Etcd version (please run commands below)

etcd: 3.5.3

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by xiaods** [comment]
> I see etcd's config file description can be based on time , we expect to implement stress test once a day and keep 1000, but now it is 5 minutes which is a bit frequent
which size is your prefer for every interval writes. such as 100?  How long you want to keep the data? one day or one year?

**Comment by xiaods** [comment]
etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h
`Compact` happens for every 1-hour.

**Comment by MagicStarTrace** [comment]
> etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h `Compact` happens for every 1-hour.

If I want to keep 1000(revision), is this revision configuration still supported?


auto-compaction-retention: "1000"

**Comment by xiaods** [comment]
> > etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h `Compact` happens for every 1-hour.
> 
> If I want to keep 1000(revision), is this revision configuration still supported?
> 
> auto-compaction-retention: "1000"

no, only one config is valid

**Comment by MagicStarTrace** [comment]
> > > etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h `Compact` happens for every 1-hour.
> > 
> > 
> > If I want to keep 1000(revision), is this revision configuration still supported?
> > auto-compaction-retention: "1000"
> 
> no, only one config is valid

If I set 10 hour compression, will all versions be compressed?

**Comment by xiaods** [comment]
> > > > etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h `Compact` happens for every 1-hour.
> > > 
> > > 
> > > If I want to keep 1000(revision), is this revision configuration still supported?
> > > auto-compaction-retention: "1000"
> > 
> > 
> > no, only one config is valid
> 
> If I set 10 hour compression, will all versions be compressed?

I just read source code and comments on it. you need validate the rule by yourself.

**Comment by MagicStarTrace** [comment]
> > > > > etcd --auto-compaction-mode=periodic --auto-compaction-retention=24h `Compact` happens for every 1-hour.
> > > > 
> > > > 
> > > > If I want to keep 1000(revision), is this revision configuration still supported?
> > > > auto-compaction-retention: "1000"
> > > 
> > > 
> > > no, only one config is valid
> > 
> > 
> > If I set 10 hour compression, will all versions be compressed?
> 
> I just read source code and comments on it. you need validate the rule by yourself.

I get this error when I upgrade, restore and start etcd
discovery failed","error":"member 15e5394f5ace5e93 has already been bootstrapped
Does this have any effect? 
Thank you!

**Comment by xiaods** [comment]
> has already been bootstrapped

the error report duplicate member lunching.

**Comment by MagicStarTrace** [comment]
> > has already been bootstrapped
> 
> the error report duplicate member lunching.

Is there anything wrong with this? I upgraded from 3.3 to 3.4
Thank you!

**Comment by xiaods** [comment]
@MagicStarTrace  It is recommended that you reinstall Etcd version 3.4 to verify the results.
