### ISSUE TITLE
etcd configuration item client-cert-auth: true Difference between different versions

### ISSUE THREAD

**Issue by MagicStarTrace** [etcd-io/etcd#13961]
### What happened?

client-cert-auth configuration items, differences in different etcd versions

Results in etcd 3.5.3

etcdctl --cacert=/data/etcd/certs/rootcert.pem  --endpoints=192.168.100.1:2379,192.168.100.2:2379,192.168.100.3:2379  member list

{"level":"warn","ts":"2022-04-19T22:30:36.219+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00041e380/192.168.100.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: authentication handshake failed: remote error: tls: bad certificate\""}

Results in etcd 3.3.13

etcdctl --cacert=/data/etcd/certs/rootcert.pem    --endpoints=192.168.100.1:2379,192.168.100.2:2379,192.168.100.3:2379 member list
3238ecccdb6a9c5c, started, etcd3, https://192.168.100.3:2380, https://192.168.100.3:2379
d18d6c0089ccf434, started, etcd1, https://192.168.100.1:2380, https://192.168.100.1:2379
e4d4f56a23226741, started, etcd2, https://192.168.100.2:2380, https://192.168.100.2:2379

client-cert-auth: true , It seems to be invalid in version 3.3.13?

### What did you expect to happen?

Excuse me, what's the situation?
3.5.3 Is the verification of client-cert stricter?

### How can we reproduce it (as minimally and precisely as possible)?

The configuration file is the same and can be reproduced with different versions

### Etcd version (please run commands below)

etcdctl version: 3.5.3

### Etcd configuration (command line flags or environment variables)

name: etcd1
initial-cluster: etcd1=https://192.168.100.1:2380,etcd2=https://192.168.100.2:2380,etcd3=https://192.168.100.3:2380
initial-cluster-state: new

listen-peer-urls: https://192.168.100.1:2380
initial-advertise-peer-urls: https://192.168.100.1:2380

listen-client-urls: https://192.168.100.1:2379
advertise-client-urls: https://192.168.100.1:2379

quota-backend-bytes: 8589934592
data-dir: /data/etcd/data
wal-dir: /data/etcd/wal
snapshot-count: 1000
client-transport-security:
  trusted-ca-file: /data/etcd/certs/rootcert.pem
  cert-file: /data/etcd/certs/etcd-nodecert.pem
  key-file: /data/etcd/certs/etcd-nodekey.pem
peer-transport-security:
  client-cert-auth: true
  trusted-ca-file: /data/etcd/certs/rootcert.pem
  cert-file: /data/etcd/certs/etcd-nodecert.pem
  key-file: /data/etcd/certs/etcd-nodekey.pem

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

Higher versions can use the following command to return the member list:

etcdctl --cacert=/data/etcd/certs/rootcert.pem  --cert=/data/etcd/certs/etcd-nodecert.pem  --key=/data/etcd/certs/etcd-nodekey.pem --endpoints=192.168.100.1:2379,192.168.100.2:2379,192.168.100.3:2379 member list

**Comment by xiaods** [comment]
it mean 3.5 need set  there params : --cacert and  --cert= and  --key

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
