### ISSUE TITLE
Etcd disk usage and memory consumption not going down after defragmentation

### ISSUE THREAD

**Issue by klolos** [etcd-io/etcd#13968]
When performing maintenance in an etcd deployment that had a few gigabytes of memory consumption, we observed that the memory consumption of the server does not go down as expected after deleting data, compacting and defragmenting.

We were able to reproduce this behavior in a toy deployment, by writing a few GB of keys, deleting them, compacting and defragmenting. There, we also saw that even though the DB size had gone down to 13MB, the memory consumption was still at nearly 17GiB:

```
/ # etcd --version
etcd Version: 3.3.13
Git SHA: 98d3084
Go Version: go1.10.8
Go OS/Arch: linux/amd64
```
```
/ # ETCDCTL_API=3 etcdctl --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 69b60ba94f21e626 |  3.3.13 |   13 MB |      true |        26 |    4263932 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
```
```
/ # cat /proc/1/status | grep VmRSS
VmRSS:  18066300 kB
```
```
/ # du -hs /var/etcd/data/member/snap/
16.2M   /var/etcd/data/member/snap/
/ # du -hs /var/etcd/data/member/wal/
16.2G   /var/etcd/data/member/wal/
/ # ls /var/etcd/data/member/wal/ | wc -l
272
```

The above picture did not change, even after waiting for a few hours. However, we were able to eventually make etcd reduce its memory and disk consumption after performing a large number of new writes. This leads us to believe that the data we had initially deleted still existed in WAL files referenced by the snapshots etcd automatically creates, and was only completely removed after the snaphots had been rotated out.

As far as we know though, there is no way to disable automatic snapshots, and manually creating a new snapshot does not rotate out the old ones. This means that in order for the memory and disk consumption to go down, we have to wait for etcd to eventually trigger enough snapshots on its own, which can take a very long time depending on incoming traffic.

Is there something we can do better? We want to be able to bring the memory and disk usage of the server down to a reasonable amount in a meaningful amount of time.

**Comment by lavacat** [comment]
3.3.* is end of life. Can you try this in 3.5.*?

Similar to this reply https://github.com/etcd-io/etcd/issues/13918#issuecomment-1096845232

**Comment by klolos** [comment]
I repeated the same steps in a 3.5.4 deployment, I think the behavior is the same:

```
# etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/amd64
```

Write 10K keys, 1M each:
```
# dd if=/dev/urandom of=randfile bs=1M count=1
# for i in `seq 10000`; do cat randfile | etcdctl put /test/key-$(printf "%06d" $i); echo $i/10000; done
```
Delete them:
```
# etcdctl del --prefix /test
10000
```
Compact and defragment:
```
# rev=$(ETCDCTL_API=3 etcdctl --endpoints=:2379 endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9]*')
# etcdctl compact $rev --command-timeout=3600s
compacted revision 4894254
# etcdctl defrag --command-timeout=3600s
Finished defragmenting etcd member[127.0.0.1:2379]
```
After the first defragmentation the db size went down to 5G:
```
# etcdctl --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 127.0.0.1:2379 | 69b60ba94f21e626 |   3.5.4 |  5.3 GB |      true |      false |        46 |  421437422 |          421437422 |        |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
Defragment again:
```
# ETCDCTL_API=3 etcdctl defrag --command-timeout=3600s
Finished defragmenting etcd member[127.0.0.1:2379]
```
After the second defragmentation the size went down to ~500M
```
# etcdctl --write-out=table endpoint status
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 127.0.0.1:2379 | 69b60ba94f21e626 |   3.5.4 |  470 MB |      true |      false |        46 |  421437425 |          421437425 |        |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
After waiting for ~30 minutes, the memory is still at 13G:
```
# cat /proc/1/status | grep VmRSS
VmRSS:  13472380 kB 
```
Disk usage is at ~10G, with lots of WAL files:
```
# du -hs /var/etcd/data/member/snap/
474M    /var/etcd/data/member/snap/
# du -hs /var/etcd/data/member/wal/
9.9G    /var/etcd/data/member/wal/
# ls /var/etcd/data/member/wal/ | wc -l
163
```

**Comment by turowicz** [comment]
I am having the same issue
