### ISSUE TITLE
I found more test file with invalid content

### ISSUE THREAD

**Issue by xiaods** [etcd-io/etcd#13964]
### What happened?

I am reading etcd sourcecode and familiar with the code logic. when I run testing , it report some file is invalid.

such as :
```bash
e:\go\src\github.com\etcd-io\etcd\client\v3\example_auth_test.go:1:1: expected 'package', found '.'
```

### What did you expect to happen?

does it effective? if it is not , i can send a pr to clean the invalid files.

### How can we reproduce it (as minimally and precisely as possible)?

open the etcd sourcecode and run testing

### Etcd version (please run commands below)

upstream etcd codebase

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
e:\go\src\github.com\etcd-io\etcd\client\v3\example_auth_test.go:1:1: expected 'package', found '.'
```
```

**Comment by serathius** [comment]
I guess those are symlinks. Development on Windows is currently not supported. Sorry!

**Comment by xiaods** [comment]
> I guess those are symlinks. Development on Windows is currently not supported. Sorry!

Oops. thanks for your reminder. @serathius
