### ISSUE TITLE
Watchers limit

### ISSUE THREAD

**Issue by kentahikaru** [etcd-io/etcd#13997]
Hello, just a question ... i didn't find answer in documentation.

Is there a limit how many watcher can i have for one "element under watch" ?

If i set "x" processes to watch for key "KeyY", all will get notification ? Is there max limit for "x" ?

**Comment by liyaodev** [comment]
I found this [doc](https://etcd.io/docs/v3.5/benchmarks/etcd-3-watch-memory-benchmark/).

**Comment by kentahikaru** [comment]
> I found this [doc](https://etcd.io/docs/v3.5/benchmarks/etcd-3-watch-memory-benchmark/).

Thanks you.
