### ISSUE TITLE
etcd-dump-db not working

### ISSUE THREAD

**Issue by IamSatyaonline** [etcd-io/etcd#13991]
### What happened?

etcdctl tool is working fine but unable to run the etcdctl-dump-db.
below is the error we are getting.

bash-4.4$ etcd-dump-db -help
bash: etcd-dump-db: command not found

### What did you expect to happen?

 etcd-dump-db should be run to debug the dump file. Please help us to configure this command.

### How can we reproduce it (as minimally and precisely as possible)?

By running the command etcd-dump-db

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
bash-4.4$ etcd --version
etcd Version: 3.3.11
Git SHA: 2cf9e51d2
Go Version: go1.10.7
Go OS/Arch: linux/amd64


$ etcdctl version
bash-4.4$ etcdctl version
etcdctl version: 3.3.11
API version: 3.3
bash-4.4$

```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
bash-4.4$
bash-4.4$ etcd-dump-db
bash: etcd-dump-db: command not found
```

**Comment by spzala** [comment]
@IamSatyaonline did you install the tool? The tools, https://github.com/etcd-io/etcd/tree/main/tools, are not installed by default like etcdctl.

**Comment by IamSatyaonline** [comment]
Hi @spzala 
I have installed etcd-3.4.16 and it is running inside container. is it possible to run the etcd-dump-db inside container with etcdctl client ? Could you please share the steps to install/enable etcd-dump-db tool along with etcdctl ? 
I see, etcd-dump-db is the part of 3.4.16 etcd package.

bash-4.4$ etcd --version
etcd Version: 3.4.16
Git SHA: d19fbe541
Go Version: go1.12.17
Go OS/Arch: linux/amd64

bash-4.4$ etcdctl version
etcdctl version: 3.4.16
API version: 3.4
bash-4.4$

**Comment by ahrtr** [comment]
Please refer to the comment in [issuecomment-1110774613](https://github.com/etcd-io/etcd/pull/13994#issuecomment-1110774613)

You can also run the tool using command `go run ./tools/etcd-dump-db`.

**Comment by spzala** [comment]
> Hi @spzala I have installed etcd-3.4.16 and it is running inside container. is it possible to run the etcd-dump-db inside container with etcdctl client ? Could you please share the steps to install/enable etcd-dump-db tool along with etcdctl ? I see, etcd-dump-db is the part of 3.4.16 etcd package.
> 
> bash-4.4$ etcd --version etcd Version: 3.4.16 Git SHA: [d19fbe5](https://github.com/etcd-io/etcd/commit/d19fbe541bf9c81e2d69d71d1068bd40c04de200) Go Version: go1.12.17 Go OS/Arch: linux/amd64
> 
> bash-4.4$ etcdctl version etcdctl version: 3.4.16 API version: 3.4 bash-4.4$

@IamSatyaonline please see @ahrtr comment above.

**Comment by ahrtr** [comment]
[The installation guide](https://github.com/etcd-io/etcd/tree/main/tools/etcd-dump-db) has already been updated, so closing this ticket.
