### ISSUE TITLE
How locking or election ordering work?

### ISSUE THREAD

**Issue by lotus-x** [etcd-io/etcd#14008]
Hi,

When leader election or locking requests are coming for an individual key, does ownership for the lock/election granted according to the requested order?

For an example,

Let's say all the three sessions (B,C,D) request the lock while A is still acquired the lock, so what happen when etcd grant the ownership for those sessions after A released the lock?

<pre>
           A
|------------------|
                 B
        |-----------------|
                       C
            |-------------------|
                             D
                |-----------------------|
</pre>

Sorry for opening this as an issue, I wanted to know this exactly.

**Comment by xiaods** [comment]
hi, the election request  is based on raft consensus.  No relation to other.

**Comment by lotus-x** [comment]
So maybe the lock system works the way I want?

Like acquired one by one according to the order they requested?

**Comment by xiaods** [comment]
> So maybe the lock system works the way I want?
> 
> Like acquired one by one according to the order they requested?

maybe this articles can give you some insight. https://programmer.ink/think/implementation-of-etcd-distributed-lock.html
