### ISSUE TITLE
--key-file=<path>: Key for the certificate. Must be unencrypted

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#14015]
### What happened?

When I start the etcd service through the command, I need to add the certificate private, and the private must be in clear text, and the encrypted certificate private cannot be used.

### What did you expect to happen?

etcd needs to support encrypted certificate private key

### How can we reproduce it (as minimally and precisely as possible)?

etcd security policy

### Etcd version (please run commands below)

etcd version 3.5.0

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Sorry for my ignorance, but could you provide examples of projects that support encrypted private key.

**Comment by xiaods** [comment]
@SingleThread  your issue is feature request, not bug issue.
