### ISSUE TITLE
Checking for key existence - `create_revision` vs `version`

### ISSUE THREAD

**Issue by joshua-sp** [etcd-io/etcd#14028]
I've seen a common idiom to check for the non-existence of a key within a `Compare` by checking if the `create_revision` is equal to 0. (as discussed here https://github.com/etcd-io/etcd/issues/6740)

I was wondering: If the key is created, and then deleted, is the `create_revision` of the key reset to 0?
The [data model](https://etcd.io/docs/v3.5/learning/data_model/) states that the `version` of a key is reset, but doesn't speak about the `create_revision`.

>  A key’s life spans a generation, from creation to deletion. Each key may have one or multiple generations. Creating a key increments the version of that key, starting at 1 if the key does not exist at the current revision. Deleting a key generates a key tombstone, concluding the key’s current generation by resetting its version to 0

**Comment by zaozaoniao** [comment]
I think   there is  no sense  when  the key  is deleted.

you can use  etcdctl  --endpoints=http:127.0.0.1  get  aa  --write-out=fields"  to  see the result:
```
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 1680
"RaftTerm" : 118
"More" : false
"Count" : 0
```

 do  not show  the deleted key's  version , createrevision , modrevision
