### ISSUE TITLE
ResourceExhausted when reading large number of keys

### ISSUE THREAD

**Issue by liaojie** [etcd-io/etcd#14037]
Hi,

We have a etcd cluster and did some high load tests for our server, putting approximate 10M keys, and read them all when server starts. We get the following error:

`
etcd/etcd_client.go:148        Failed to get all objects of a key prefix from ETCD.        {"key": "/vpc_remote_data/", "error": "rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (3176934157 vs. 2147483647)"}`

We set the **MaxCallSendMsgSize**/**MaxCallRecvMsgSize**,  and still fails. After exploring the grpc document:
https://developers.google.com/protocol-buffers/docs/encoding

we learned that the grpc message should not be larger than 2GB, while our data reaches more than 10GB~

It seems that grpc streaming could solve this problem, does etcd support this mode ?

Any best practice  suggestion for reading large datas would be appreciated.

**Comment by xiaods** [comment]
why not use redis to store your keys. it's not limited for 2GB size keys.

**Comment by liaojie** [comment]
@xiaods yes we use Redis in our system when there is a need to store large keys, and for this specified situation we could only  use etcd, which could not be replaced immediately
