### ISSUE TITLE
Can't connect to etcd via etcdctl

### ISSUE THREAD

**Issue by tamanna2702** [etcd-io/etcd#14055]
Hi,

Could you please take a look at this question on Stackoverflow.

https://stackoverflow.com/questions/71966255/cant-connect-to-etcd-via-etcdctl

Thanks,
Tam

**Comment by ptabor** [comment]
No windows experience, but would look around firewalls & port binding permissions. 
Is there `netstat` on windows to show what ports are open by each process ?
