### ISSUE TITLE
Missing command: migrate

### ISSUE THREAD

**Issue by kvaikla** [etcd-io/etcd#14058]
### What happened?

```
# etcdctl version
etcdctl version: 3.5.1
API version: 3.5
# etcdctl migrate
Error: unknown command "migrate" for "etcdctl"
Run 'etcdctl --help' for usage.
Error: unknown command "migrate" for "etcdctl"
```

### What did you expect to happen?

Migrate of v2 data

### How can we reproduce it (as minimally and precisely as possible)?

My etcd binary is from:
https://github.com/etcd-io/etcd/releases/download/v3.5.1/etcd-v3.5.1-linux-amd64.tar.gz

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.1
Git SHA: e8732fb5f
Go Version: go1.16.3
Go OS/Arch: linux/amd64


$ etcdctl version
etcdctl version: 3.5.1
API version: 3.5

```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Please use `etcdutl` binary and not `etcdctl`.

**Comment by ptabor** [comment]
Please reopen if the suggestion does not work.

**Comment by kvaikla** [comment]
Still same
```
# etcdutl migrate --help
Error: unknown command "migrate" for "etcdutl"
Run 'etcdutl --help' for usage.
Error: unknown command "migrate" for "etcdutl"
```

**Comment by ahrtr** [comment]
The command `etcdctl migrate` had already been decommissioned in 3.5.0 in [pull/12971](https://github.com/etcd-io/etcd/pull/12971).  Please use a version <=v3.4. 

The changelog item isn't accurate, I just submitted a PR to correct it. Refer to [pull/14069](https://github.com/etcd-io/etcd/pull/14069)

**Comment by kvaikla** [comment]
https://etcd.io/docs/v3.5/upgrades/upgrade_3_5: 
If all members have been upgraded to v3.5, the cluster will be upgraded to v3.5, and downgrade from this completed state is not possible.

What are steps, to get etcd 3.5 data from v2 to v3?

**Comment by serathius** [comment]
This is no longer supported for v3.5. It should still be possible using v3.4 etcdctl as there were no breaking changes, however please take appropriate precautions as this is not officially supported and was never tested.
