### ISSUE TITLE
use go install instead of go get in /contrib/raftexample/Procfile

### ISSUE THREAD

**Issue by spongecaptain** [etcd-io/etcd#14059]
### What happened?

The go version of etcd is go 1.17 right now.

Please see golang/go#40276

```
With this change, go install would overlap with go get even more, so we also
propose deprecating and removing the ability for go get to install packages.

In Go 1.16, when go get is invoked outside a module or when go get is
invoked without the -d flag with arguments matching one or more main
packages, go get would print a deprecation warning recommending an
equivalent go install command.
In a later release (likely Go 1.17), go get would no longer build or install
packages. The -d flag would be enabled by default. Setting -d=false would
be an error. If go get is invoked outside a module, it would print an error
recommending an equivalent go install command.
```
If you run `go get github.com/mattn/goreman` in go1.17(or later), it will not build or install packages.

By `go get`, if you run the following command, you will get the following error:
```
$ ./goreman start
command not found: goreman
``` 

### What did you expect to happen?

Use `go install github.com/mattn/goreman@latest` instead.

### How can we reproduce it (as minimally and precisely as possible)?

none.

### Etcd version (please run commands below)

none.

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
The PR [14060](https://github.com/etcd-io/etcd/pull/14060) has already been merged, so closing this ticket.
