### ISSUE TITLE
Reopen Missing command: migrate #14058

### ISSUE THREAD

**Issue by kvaikla** [etcd-io/etcd#14068]
### What happened?

Described in #14058, same error

### What did you expect to happen?

Described in #14058

### How can we reproduce it (as minimally and precisely as possible)?

Described in #14058

### Etcd version (please run commands below)

Described in #14058

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Please see my comment [issuecomment-1136466246](https://github.com/etcd-io/etcd/issues/14058#issuecomment-1136466246)
