### ISSUE TITLE
Auto-recover if database directory is locked

### ISSUE THREAD

**Issue by ishan16696** [etcd-io/etcd#14061]
### What happened?

In a single node etcd it has been observed that some times due to abruptly termination of `etcd container` the lock on the `etcd db` file was still held by previous etcd process. And this stop new etcd process to come up as [new etcd process unable to access db file.](https://github.com/etcd-io/etcd/blob/v3.4.13/etcdserver/backend.go#L69-L98) as it is unable to [open bolt db](https://github.com/etcd-io/etcd/blob/ae9734ed278b7a1a7dfc82e800471ebbf9fce56f/mvcc/backend/backend.go#L158-L165).

Log:
```
etcdserver: another etcd process is using "/var/etcd/data/new.etcd/member/snap/db" and holds the file lock, or loading backend file is taking >10 seconds
etcdserver: waiting for it to exit before starting..
```

Till now this scenario is very rarely observed but in `multi-node etcd` the chances of this kind of scenarios can also be increased.

### What did you expect to happen?

Using the timeout, I'm able to detect that other process is still holding the lock over the db file. 
```
db, err := bolt.Open(path, 0400, &bolt.Options{Timeout: timeoutToOpenBoltDB, ReadOnly: true})
if err != nil {
		return -1, err
}
defer db.Close()
```
1. ) BoltDB takes the exclusive lock over the database file, Is there a way when we detects this scenario we can forcefully take away an exclusive lock ?
2. ) Any other suggestions to handle this kind of situation.

### How can we reproduce it (as minimally and precisely as possible)?

It has been observed rarely but it requires manual intervention.

### Anything else we need to know?

A pod restart usually resolves the issue but it requires manual intervention.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.13
Git SHA: ae9734ed2
Go Version: go1.12.17
Go OS/Arch: linux/amd64
```

```console
$ etcdctl version
etcdctl version: 3.4.13
API version: 3.4
```
</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by EmPRio93** [comment]
Im facing this situation right now, and i don't know what to do. Is there a way to release the lock ?

**Comment by EmPRio93** [comment]
My cluster was completely unavailable, my issue was that i did not enabled the --auto-compaction=* on revision's and defrag the db. My instances was 2 cpu and 2 ram that could not read the db in 10 seconds, after i updated the amount of resources on the instances the cluster started and i was able to provide compaction and dfrag of db. But the error message is triggered me to search the lock :D  I think it would be nice to document this error and its causes in the doc's of etcd, it is not so obvious.
