### ISSUE TITLE
Linux Packages

### ISSUE THREAD

**Issue by jsirianni** [etcd-io/etcd#14073]
The main website says "help wanted" under OS packages https://etcd.io/docs/v3.5/install/#installation-via-os-packages. I have working deb and rpm packages and would love to contribute them. Is that something the maintainers and community would be interested in? If so, I am happy to discuss the details.

**Comment by spzala** [comment]
@jsirianni thanks for your contribution interest! If you can provide doc that fits in the installation section in the link you provided, I would suggest to create a PR/draft PR to have discussion/review around it. The docs belongs to https://github.com/etcd-io/website so please use that repo for this issue related discussion. Thanks!
