### ISSUE TITLE
Tests are failing for release-3.4 in go 1.15.15 because of grpc dependency

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#14074]
2 latests runs for release-3.4 branch are failing
https://github.com/etcd-io/etcd/actions/workflows/tests.yaml?query=branch%3Arelease-3.4

>Error: clientv3/naming/grpc.go:25:2: module google.golang.org/grpc@latest found (v1.46.0), but does not contain package google.golang.org/grpc/naming

I can reproduce this locally. Tests work for go 1.12.17

Similar discussion is [here](https://github.com/etcd-io/etcd/issues/12124).

Shall we downgrade to 1.12.17?

**Comment by ahrtr** [comment]
I added a discussion item into next community meeting. Feel free to discuss it by then. 
But I may not join the call because it's 2AM my time.

**Comment by lavacat** [comment]
Here is a fix for 'naming' issue + another fix for test failure because of old bolt db
https://github.com/etcd-io/etcd/pull/14075

Tests still failed in GitHub. (worked for me locally). I'll investigate more

**Comment by ahrtr** [comment]
This issue should be already fixed.
