### ISSUE TITLE
Inconsistent data in etcd

### ISSUE THREAD

**Issue by didihongsheng** [etcd-io/etcd#14083]
### What happened?

etcd version: 3.4.9

three members in etcd cluster.

 the brief description as:  leader's revison lag far behind followers

etcd leader status
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/19987261/171200753-0465686b-b88d-46a2-888f-947fa17d3137.png">

revision diff
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/19987261/171200610-febe30d0-a172-4a61-8f6a-96e6072a738e.png">

peer network send bytes
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/19987261/171200238-de106429-b9cd-4a63-bf25-e1ad72fa6c57.png">

### What did you expect to happen?

1、leader's revision should not lag far behind followers

### How can we reproduce it (as minimally and precisely as possible)?

this is not easy to happened, I meet it in product env when I publish some apps, and txn requst great growth:

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/19987261/171204480-846c1504-51af-412b-b2da-80cf56e8c64e.png">

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Could you try to reproduce this issue in 3.5.4 or main, please?
