### ISSUE TITLE
Leases expire on adding cluster members

### ISSUE THREAD

**Issue by ahdekkers** [etcd-io/etcd#14096]
### What happened?

Not sure if this is meant to happen or not, but when adding an etcd cluster node, leases on keys (for example, leases used in leader election) get deleted. 

### What did you expect to happen?

I expected leases to stay alive

### How can we reproduce it (as minimally and precisely as possible)?

1. Start an etcd server as follows:
```
etcd --data-dir=data.etcd --name machine-1 \
        --initial-advertise-peer-urls http://localhost:2380 --listen-peer-urls http://localhost:2380 \
        --advertise-client-urls http://localhost:2379 --listen-client-urls http://localhost:2379 \
        --initial-cluster-state new --initial-cluster-token helloworld
```
2. Start a leader election with two candidates. In one terminal window run `etcdctl --endpoints=localhost:2379 elect lead v1` and in another terminal window run `etcdctl --endpoints=localhost:2379 elect lead v2`. v1 should become leader and v2 should block.
3. Add a member to the cluster as follows: `etcdctl --endpoints=localhost:2379 member add machine-2 --peer-urls=http://localhost:2381`
4. Start the second member in another terminal window: 
```
etcd --data-dir=data2.etcd --name machine-2 \
        --initial-advertise-peer-urls http://localhost:2381 --listen-peer-urls http://localhost:2381 \
        --advertise-client-urls http://localhost:2378 --listen-client-urls http://localhost:2378 \
        --initial-cluster-state existing --initial-cluster-token helloworld
```
5. Check either of the elections - you should see `Error: elect: session expired`.

### Anything else we need to know?

MacOS Monterey version 12.0.1 M1 chip

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.18.1
Go OS/Arch: darwin/arm64

$ etcdctl version
etcdctl version: 3.5.4
API version: 3.5
```

</details>

**Comment by ahrtr** [comment]
When you started the second member at step4, you should specify the correct value for `--initial-cluster`.
