### ISSUE TITLE
Use GRPC url standard 

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#14112]
Etcd code and tests depend on In particular our tests depend a lot on `unix://localhost:port` url schema, while
according to grpc standard: https://grpc.github.io/grpc/cpp/md_doc_naming.html the supported names are: `unix:path` or `unix://absolute_path` (so `unix:///tmp/foo`). This issue blocks grpc upgrade as etcd tests will not pass until we stop using `unix://localhost:port`.

Context https://github.com/etcd-io/etcd/pull/14104

First issue that we need to address is stop depending on  `unix://localhost:port` schema in tests to unblock dependency upgrade. Later we should propose a plan to match grpc standard. I expect this might require multiple releases to avoid introducing breaking changes.

**Comment by serathius** [comment]
@ptabor Thanks for fixing the connection format, any followups needed or we can close the issue?

**Comment by serathius** [comment]
ping

**Comment by ptabor** [comment]
It's good enough for now. I don't think we have cycles to review all URL schemes proactively.
