### ISSUE TITLE
Cherrypick pull/12992 to v3.5.5

### ISSUE THREAD

**Issue by biosvs** [etcd-io/etcd#14131]
Bug with broken auth token upgrades was fixed in [pull/12992](https://github.com/etcd-io/etcd/pull/12992) almost a year ago, but still not presented in latest releases.

It's quite painful bug, is it possible to include (cherrypick) fix into client v3.5.5?

Thanks!

**Comment by ahrtr** [comment]
FYI. [pull/14132](https://github.com/etcd-io/etcd/pull/14132)

**Comment by biosvs** [comment]
Awesome, thank you!
