### ISSUE TITLE
etcd data in etcd3 format

### ISSUE THREAD

**Issue by kvaikla** [etcd-io/etcd#14130]
Hi,
Before etcd3, using an etcd2, etcd database size was constantly 20 Kb. After change to etcd3, database started rapidly growing, about 8Kb/1min.
It stopped, when I added to etcd configuration file:
```
auto-compaction-retention: '15m'
auto-compaction-mode: 'periodic'
````
Now I have a stable etcd database with size 196 Kb.
In my case etcd is as DCS for patroni.
Database was not growing when etcd binary was etcd3 and etcd data was in etcd2 format.
My question is, how to get back my old situation, is it possible if etcd data is in etcd3 format?

graphs: stable since 06/13 evening.
br
Kaido

![etcd3](https://user-images.githubusercontent.com/71779927/174246561-e2f47b30-6bf3-4bb1-98b7-521cd6784892.jpg)

**Comment by xiaods** [comment]
etcdv2 and v3 use different engine, so this is no chance to get back your old situation. only use etcd v2 backup data to restore your old etcdv2 cluster

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/etcd/issues/14329#issuecomment-1246451584
