### ISSUE TITLE
Let etcd skip storage replication since cloud does storage replication for availability

### ISSUE THREAD

**Issue by hasethuraman** [etcd-io/etcd#14137]
### What happened?

ETCD replicates the data with its peer.

In cloud deployment, the storage engine does internal replication and provide availability at rack, datacenter, region level. Said that, if I deploy etcd, it turns out that replication happens 3x times (where x is the number of replications in a cloud storage and 3 is when i have 3 instances of etcd instances).

Is there a way I can share the storage to all etcd instances and let application level replication can be skipped safely but still run 3 instances of etcd.

When I tried using an NFS, the second etcd fails to come up due to lock held by first etcd instance.

Please advice.

### What did you expect to happen?

Allow end user to do replication at disk (or storage engine) level  and etcd skip application level replication.

### How can we reproduce it (as minimally and precisely as possible)?

It is straightforward as explained.

### Etcd version (please run commands below)

Any version

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
It isn't supported.
