### ISSUE TITLE
ETCD server PUT request key starts with \000 when sent from benchmark tool

### ISSUE THREAD

**Issue by hasethuraman** [etcd-io/etcd#14147]
### What happened?

When I called this benchmark command, I see the key string starts with \000 in etcd server .log. So I couldnt retrieve it.

./benchmark --endpoints=${HOST_1} --target-leader --conns=1 --clients=1 put --key-size=...

4.2.6:45930, response type = /etcdserverpb.KV/Put, request count = 1, request size = 1230, response count = 0, response size = 30, request content = key:"\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000" value_size:1024

I tried to fix this benchmark too by sending some meaningful key, I see etcdserver logs shows a prefix \000

Key in request from benchmark tool (ensure in rpc client code too) testXVlBzgbaiCMRAj0
Response from server: header:<cluster_id:9574527182359163021 member_id:17148931354422644456 revision:95719 raft_term:8 > prev_kv:<key:"**\000**testXVlBzgbaiCMRAj0" create_revision:94198 mod_revision:95717 version:16 value:"valWwhTHctcuAxhxKQFDaFpLSjFbcXoEFfRsWxPL" >

### What did you expect to happen?

The key must not prepend with \000 in server

### How can we reproduce it (as minimally and precisely as possible)?

Using benchmark tool

### Anything else we need to know?

So, I couldnt take a benchmark against a large number of key values

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here
{"etcdserver":"3.4.15","etcdcluster":"3.4.0"}

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by peiminmin** [comment]
@hasethuraman When benchmark performs put pressure measurement, you can specify the number of pressure measurement keys by specifying the `--key-space-size` parameter. If the `--key-space-size` parameter is not specified, it defaults to 1. The phenomenon at this time is the same as what you described

**Comment by hasethuraman** [comment]
Thanks @peiminmin I will try that. Will I be able to retrieve or delete those keys? Why I am asking is, the '\000' prepending is stopping from doing get using prefix.

**Comment by hasethuraman** [comment]
I dont know how to get or delete these keys

![image](https://user-images.githubusercontent.com/10446093/175470518-a03a8a54-a80d-400b-99ec-087995520a16.png)

**Comment by hasethuraman** [comment]
Never mind, I just removed the binary encoding and continue. Closing it now.
But please let me know why it is being encoded it in benchmark tool (etcdctl doesnt do this).
