### ISSUE TITLE
[3.4] Test failure on TestRoundRobinBalancedResolvableFailoverFromRequestFail 

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14158]
We are going to release [3.4.19](https://github.com/etcd-io/etcd/issues/14105), and the top priority is to make the pipeline as stable as possible. 

```
--- FAIL: TestRoundRobinBalancedResolvableFailoverFromRequestFail (0.00s)
    balancer_test.go:308: expected balanced loads for 20 requests, got switches 6
```

Refer to https://github.com/etcd-io/etcd/runs/7049120841?check_suite_focus=true

**Comment by lavacat** [comment]
yes, I'll submit PR tomorrow

**Comment by ahrtr** [comment]
Sure, thanks.

**Comment by ahrtr** [comment]
Fixed by https://github.com/etcd-io/etcd/pull/14204
