### ISSUE TITLE
tcpproxy is not an OSI level 4 proxy

### ISSUE THREAD

**Issue by fananchong** [etcd-io/etcd#14167]
doc.go line 15 :
```go
// Package tcpproxy is an OSI level 4 proxy for routing etcd clients to etcd servers.
```

but actually tcpproxy is an OSI level 7 proxy

**Comment by xiaods** [comment]
<img width="987" alt="截屏2022-07-03 上午10 48 41" src="https://user-images.githubusercontent.com/37678/177022516-d6126f47-1703-4fd9-8af3-57b2dc4a269c.png">
@fananchong  are you sure?
