### ISSUE TITLE
Unreachable code in `tests/functional/runner/lease_renewer_command.go`

### ISSUE THREAD

**Issue by chavacava** [etcd-io/etcd#14162]
In the following code, the `for` statement at line 74 and the `break` statement at line 81 are unreachable.

https://github.com/etcd-io/etcd/blob/cabdb13dadad2d853bb2f4be226bce3c220b94eb/tests/functional/runner/lease_renewer_command.go#L69-L89

Found with [`revive`]() rule `unreachable-code`

**Comment by ahrtr** [comment]
I think we should remove the unreachable code, please feel free to submit a PR for this.
