### ISSUE TITLE
How to handle the key loss caused by a lease renewal failure

### ISSUE THREAD

**Issue by zhangtong007** [etcd-io/etcd#14189]
etcd server version: v3.4.13
In my service, a key is renewed every four seconds. In some abnormal scenarios, the lease renewal may fail and the key is lost. How can I discover and recover this key from the service?

**Comment by zhangtong007** [comment]
I find that if the key is lost in time, the lease renewal logic does not return error.

I use 'client.KeepAliveOnce(ctx context.Context, id LeaseID)' for renewal logic

**Comment by xiaods** [comment]
show some code to simplify your context. I don't understand the question.

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
