### ISSUE TITLE
go mod tidy complains after adding etcd embed server to the project

### ISSUE THREAD

**Issue by nomionz** [etcd-io/etcd#14226]
### What happened?

The same issue #14225 but now I try it on my linux and got the same output. I have already tried to force add "go.etcd.io/etcd/server/v3/embed" in go.mod and nothing is happend, also I tried to add cloud.google.com/go/compute v1.7.0 and nothing.

> go.etcd.io/etcd/server/v3/embed imports
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
google.golang.org/grpc/interop imports
golang.org/x/oauth2/google imports
cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
cloud.google.com/go v0.93.3 (/home/nikita/go/pkg/mod/cloud.google.com/go@v0.93.3/compute/metadata)
cloud.google.com/go/compute v1.7.0 (home/nikita/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata)

### What did you expect to happen?

No messages after `go mod tidy`

### How can we reproduce it (as minimally and precisely as possible)?

Just add `"go.etcd.io/etcd/server/v3/embed"` to import then `go get go.etcd.io/etcd/server/v3` and you will see the same message after `go mod tidy`

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
Git SHA: 08407ff76
Go Version: go1.16.15
OS/Arch: linux/amd64
$ etcdctl version
# paste output here
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
I did not reproduce this issue, please try steps below,

```
$ go version
go version go1.16.15 darwin/amd64
$ go mod init example.com/demo
$ go get go.etcd.io/etcd/server/v3@v3.5.4
$ go mod tidy
```

My example code is,
```
package main

import (
	"fmt"

	"go.etcd.io/etcd/server/v3/embed"
)

func main() {
	fmt.Println("Hello world")
	embed.StartEtcd(nil)
}
```

**Comment by nomionz** [comment]
I don't know what I did, I took the go.mod from the last commit and tried the solution above and it seems to work. Thanks, closing the issue
