### ISSUE TITLE
Is etcd FIPS 140 compliant 

### ISSUE THREAD

**Issue by ppadashe** [etcd-io/etcd#14223]
I want to know if  etcd is FIPS 140-2 or 140-3 compliant ? How do I verify if its compliant ?

**Comment by spzala** [comment]
Afaik, no such compliance efforts were ever made in the community. Please refer to the FIPS doc to know more about FIPS standards and requirements. 
You can read more about security assessment of etcd here, https://github.com/etcd-io/etcd/tree/main/security and about security model here, https://etcd.io/docs/v3.5/op-guide/security/
I am closing this issue but please feel free to reopen or create a new one if ever needed. Thanks!
