### ISSUE TITLE
go mod tidy complains after adding etcd embed to the project

### ISSUE THREAD

**Issue by nomionz** [etcd-io/etcd#14225]
### What happened?

I use the `"go.etcd.io/etcd/server/v3/embed"` dependency to run the embedded etcd server and test my code with it. Code works fine but after `go mod tidy` I get that message  

>  go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
        google.golang.org/grpc/interop imports
        golang.org/x/oauth2/google imports
        cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
        cloud.google.com/go v0.93.3 (D:\goPackages\pkg\mod\cloud.google.com\go@v0.93.3\compute\metadata)
        cloud.google.com/go/compute v1.7.0 (D:\goPackages\pkg\mod\cloud.google.com\go\compute@v1.7.0\metadata)

### What did you expect to happen?

No messages after  `go mod tidy` 

### How can we reproduce it (as minimally and precisely as possible)?

Just add `"go.etcd.io/etcd/server/v3/embed"` to import then go get `go get go.etcd.io/etcd/server/v3` and you will see the same message after `go mod tidy` 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: windows/amd64
$ etcdctl version
# paste output here
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Windows development environment is not supported.

**Comment by serathius** [comment]
Context https://github.com/etcd-io/etcd/issues/13667#issuecomment-1096358961

**Comment by nomionz** [comment]
> Windows development environment is not supported.

And what if I don't use etcd binary and just an embed server?  Does it still count?
