### ISSUE TITLE
Expose alarms as metrics

### ISSUE THREAD

**Issue by stek29** [etcd-io/etcd#14234]
Currently the only way to know about alarms is to issue an maitenance/alarm grpc call to list currently active alarms (by using etcdctl alarm list, for example).

It would be great to have expose etcd alarms in prometheus metrics so they're easier to monitor and know about.

**Comment by stek29** [comment]
@ahrtr @serathius is there any chance to get this in next 3.5.x release?
I'm not familiar with etcd release process and backporting, and I haven't been able to find any docs on it.

**Comment by ahrtr** [comment]
@stek29  FYI. https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/release.md#patch-version-release 

Usually we only cherry pick bug fixes and security patches. So normally we shouldn't backport the PR https://github.com/etcd-io/etcd/pull/14276 to 3.5.
