### ISSUE TITLE
islead only set when rd.SoftState != nil

### ISSUE THREAD

**Issue by sniperHW** [etcd-io/etcd#14233]
in func (r *raftNode) start(rh *raftReadyHandler){} 

islead only set when rd.SoftState != nil 

this means the optimization of  
”the leader can write to its disk in parallel with replicating to the followers and them
writing to their disks" would not work when current node is leader but rd.SoftState == nil。

Is this really the design intent?

**Comment by xiaods** [comment]
SoftState will be nil if there is no update.

**Comment by sniperHW** [comment]
SoftState == nil not means len(rd.Messages ) == 0。the purpose of islead is to "let the leader can write to its disk in parallel with replicating to the followers and them writing to their disks"。In most cases,SoftState would be nil,This means that this optimization only works in a few cases.

**Comment by xiaods** [comment]
> SoftState == nil not means len(rd.Messages ) == 0。the purpose of islead is to "let the leader can write to its disk in parallel with replicating to the followers and them writing to their disks"。In most cases,SoftState would be nil,This means that this optimization only works in a few cases.

i read the source code and found only handle SoftState != nil  logic.

**Comment by sniperHW** [comment]
I've figured it out.islead is define outside the for loop.Its value is held between state changes。
