### ISSUE TITLE
ETCD fails to come up when using CIFS file share (as etcd storage) and with cache=none in mount option

### ISSUE THREAD

**Issue by hasethuraman** [etcd-io/etcd#14263]
### What happened?

I had etcd:3.4.15-debian-10-r43 running and mounted a cifs file sharing with below mount option. Please note cache=none 

rw,relatime,vers=3.1.1,cache=none,username=myname,uid=0,noforceuid,gid=1001,forcegid,addr=1.10.90.14,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,mfsymlinks,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=30

The etcd is failing to comeup with below panic

Since per discussion in https://github.com/etcd-io/etcd/issues/9670 , I tried cache=none for cifs. With same mount option, if I make it cache=strict, everything works fine.

![image](https://user-images.githubusercontent.com/10446093/180464880-8b8f65ce-4dd9-4cc4-9d6d-e998d6dbab7b.png)

### What did you expect to happen?

Etcd must not panic

### How can we reproduce it (as minimally and precisely as possible)?

Its very straightforward with the given mount option

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```
etcdctl version: 3.4.15
API version: 3.4
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
In the screenshot
```

**Comment by xiaods** [comment]
why use cifs as etcd storage? any benefits from cifs?

**Comment by hasethuraman** [comment]
1) We are looking at to ensure data is not lost due to cache. So trying with cache=none

2)
> this is not bug, this is default behavior
When you say this is default behaviour, the panic is expected?

**Comment by xiaods** [comment]
> 1. We are looking at to ensure data is not lost due to cache. So trying with cache=none
> 2. When you say this is default behaviour, the panic is expected?
> 
> > this is not bug, this is default behavior

for question 2, the panic is expected. see source  code: https://github.com/etcd-io/bbolt/blob/master/freelist.go#L175

**Comment by hasethuraman** [comment]
Yes, I saw that. Does it mean etcd won't work without caching?

**Comment by hasethuraman** [comment]
Meanwhile, I need fsync to happen. What I am looking for is, if I have cache enabled with CIFS, there is a potential possibility of data loss. So I tried disabling cache.

But  --unsafe-no-fsync means, dont do fsync correct? A put(key,value), must write to the stable storage immediately. If my understanding is correct I cant use  --unsafe-no-fsync flag.

**Comment by hasethuraman** [comment]
@xiaods  FYI I tried using cache=none option along with --unsafe-no-fsync. Didnt help.

**Comment by xiaods** [comment]
> unsafe-no-fsync

sad news, i review and see the --unsafe-no-fsync comments, it warning: "Disables fsync, unsafe, will cause data loss"
so it's not match your requirements. don't use it anymore.

**Comment by hasethuraman** [comment]
Can anyone help me how do I stop etcd/bbolt panicking from given cifs + cache=none option?

**Comment by tjungblu** [comment]
hey @hasethuraman,

I've been looking a bit into this today, since I have a samba share at home and wanted to debug bbolt a little.
I don't have a fix for you just yet, but I just want to mentally write down what I found so far.

The panic can be easily reproduced by running this simple test case on the share:
https://github.com/etcd-io/bbolt/blob/master/manydbs_test.go#L33-L60

The panic is caused by a bucket that is not found after it was created in this method:
https://github.com/etcd-io/bbolt/blob/master/bucket.go#L165-L183

The cursor seek does not return an existing bucket for the root node, thus it will create a new one with the same page id, which causes the panic on the freelist.

**Comment by ahrtr** [comment]
@hasethuraman  @tjungblu  could you try to reproduce this issue with etcd 3.5.4?

**Comment by hasethuraman** [comment]
I will try this in 3.5.4 too

I spent some time and kind of getting some direction. When we have the cache=none, it looks like the page cache wont reflect any changes as the latest commits flushes to the db; as page cache wont reflect (because of cache is disabled) the db.meta will never reflect new page id and so the free will try to release the same page (since db.meta still points to same pageid) causing this panic.

**Comment by tjungblu** [comment]
yep that's about it, the guarantees for mmap are different via CIFS with cache=none. 

>  @hasethuraman @tjungblu could you try to reproduce this issue with etcd 3.5.4?

Yes, but it's not really related to an etcd version, it is due to the mmap usage of bbolt.

**Comment by hasethuraman** [comment]
I tried to see if refreshing the first two pages (length = 2*4KB in my case) can help in tx.init(). It throws invalid arg. Everything looks good. Any other way I can try a fix locally to validate my theory?

Syscall6(SYS_REMAP_FILE_PAGES, ptr, uintptr(length), uintptr(syscall.PROT_READ), uintptr(0), uintptr(syscall.MAP_POPULATE|syscall.MAP_SHARED), 0)

**Comment by hasethuraman** [comment]
Can someone help me in with this below understanding?

- User calls etcdctl put key value
- etcd server first writes to WAL
- then get consensus through RAFT
- RAFT is in progress
- at this point - physical machine restarts and assuming that raft changes were about to flush to permanent storage
- after the server restart, will the entry in WAL be replayed and data loss is avoided?

**Comment by ahrtr** [comment]
FYI.  https://github.com/ahrtr/etcd-issues/blob/master/docs/cncf_storage_tag_etcd.md

> I will try this in 3.5.4 too

@hasethuraman Have you tried this? What's the test result?

**Comment by hasethuraman** [comment]
Thank you @ahrtr for sharing. I think that confirms. 

I am planning to close the issue because WAL cover up the main reason (data loss) for me to disable the cache. I will wait for a week and close. Please let me know if any one think that I need to keep this open.

> @hasethuraman Have you tried this? What's the test result?

Its the same

**Comment by ahrtr** [comment]
> Its the same

Please provide the log and panic call stack for 3.5.4.

**Comment by ahrtr** [comment]
I tried to setup a CIFS on a linux server, but failed somehow:-(.  I am not sure if it's possible for someone share a CIFS share for me to debug this. 

Previously based on the discussion in https://github.com/etcd-io/etcd/issues/9670, CIFS doesn't support `sync`. Not sure whether it's still the case.  Would love to double confirm it if possible.

**Comment by hasethuraman** [comment]
@ahrtr I dont see any difference in call stack. Atleast with the CIFS (cache=strict) I tried, I dont see any error related to sync.

![image](https://user-images.githubusercontent.com/10446093/183817585-ebb1245b-55b8-4210-8abe-11523198f121.png)

**Comment by hasethuraman** [comment]
@ahrtr do you think we can document before closing this defect? I dont know if etcd or boltdb can cover up this issue.

**Comment by ahrtr** [comment]
Probably we can add a known issues section in [boltDB/README.md](https://github.com/etcd-io/bbolt/blob/master/README.md). 

```
boltDB doesn't work with CIFS file share mounted with cache=none, but it works CIFS mounted with cache=strict. 
```

What do you think? @spzala
