### ISSUE TITLE
The lessor.Checkpoint always return nil

### ISSUE THREAD

**Issue by spongecaptain** [etcd-io/etcd#14260]
- version: release-3.5

- code:  https://github.com/etcd-io/etcd/blob/release-3.5/server/lease/lessor.go#L378

```go
func (le *lessor) Checkpoint(id LeaseID, remainingTTL int64) error {
	le.mu.Lock()
	defer le.mu.Unlock()

	if l, ok := le.leaseMap[id]; ok {
		// when checkpointing, we only update the remainingTTL, Promote is responsible for applying this to lease expiry
		l.remainingTTL = remainingTTL
		if le.shouldPersistCheckpoints() {
			l.persistTo(le.b)
		}
		if le.isPrimary() {
			// schedule the next checkpoint as needed
			le.scheduleCheckpointIfNeeded(l)
		}
	}
	return nil
}
```

Should it return ErrLeaseExists instead when the LeaseID does not exist.

**Comment by serathius** [comment]
> Should it return ErrLeaseExists instead when the LeaseID does not exist.

Is this a question?

**Comment by spongecaptain** [comment]
> > Should it return ErrLeaseExists instead when the LeaseID does not exist.
> 
> 
> 
> Is this a question? 

I mean that it returns error may be better.

**Comment by serathius** [comment]
> I mean that it returns error may be better.

Sure, fill free to present arguments that it will be better. I don't this is a trivial case, however I don't have context on the original code.

**Comment by xiaods** [comment]
need more context to correct this quesiton.

**Comment by ahrtr** [comment]
There may be a race condition between `Checkpoint` and `revoke`. The existing design/implementation on lease is too complicated, a lease may be revoked during the `Checkpoint`. 

I may consider to refactor the design later.
