### ISSUE TITLE
Compaction does not make free space usable

### ISSUE THREAD

**Issue by cenkalti** [etcd-io/etcd#14267]
### What happened?

After compacting the database and clearing NOSPACE alarm, the server still does not accept new write requests.

### What did you expect to happen?

After I compacted the database and cleared the alarm, I expect from server to accept new write requests.

### How can we reproduce it (as minimally and precisely as possible)?

- Start a single node etcd server with default settings.
- Fill the database quota by putting data into etcd server.
  - `while [ 1 ]; do dd if=/dev/urandom bs=1024 count=1024 | ETCDCTL_API=3 etcdctl put key  || break; done`
- When database space exceeded, NOSPACE alarm is set by the server.
- Compact the database to the latest revision.
  - `etctctl compact $(etctctl get / -w json | jq .header.revision)`
- Cleared NOSPACE alarm.
  - `etcdctl alarm disarm`
- Tried to put a value to the server.
  - `etcdctl put key value`
- Server rejected the request with "database space exceeded" error.

### Anything else we need to know?

After compaction, there must be free pages inside the db file. etcd must be able to use them. I suspect there is another check before db layer that prevents the usage of free pages (perhaps a size check).

Running defrag after compaction solves the issue but is shouldn't be required.

Restarting etcdserver after clearing the alarm also does not have any effect on resolving this issue.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.18.1
Go OS/Arch: darwin/amd64

$ etcdctl version
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

Default configuration, nothing special.

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
+------------------+---------+---------+-----------------------+-----------------------+------------+
|        ID        | STATUS  |  NAME   |      PEER ADDRS       |     CLIENT ADDRS      | IS LEARNER |
+------------------+---------+---------+-----------------------+-----------------------+------------+
| 8e9e05c52164694d | started | default | http://localhost:2380 | http://localhost:2379 |      false |
+------------------+---------+---------+-----------------------+-----------------------+------------+

$ etcdctl --endpoints=<member list> endpoint status -w table
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX |             ERRORS             |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
| 127.0.0.1:2379 | 8e9e05c52164694d |   3.5.4 |  2.1 GB |      true |      false |         5 |       4498 |               4498 |  memberID:10276657743932975437 |
|                |                  |         |         |           |            |           |            |                    |                 alarm:NOSPACE  |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------------------------------+
```

</details>

**Comment by serathius** [comment]
Run defrag after compaction.

**Comment by cenkalti** [comment]
As indicated prior, defrag solves the issue. However, it should not be required. After compaction, there is free space available in the database. etcd should be able the use that.

**Comment by ahrtr** [comment]
> However, it should not be required

This isn't correct. Two comments:
1. Although compaction deletes some K/V, but the real disk space usage will **NOT** be reclaimed automatically. You must perform a de-fragmentation to reclaim the disk space used by BoltDB. 
2. BoltDB indeed tries to reuse the free space, but it isn't guaranteed it will always reuse the free space. It is indeed a good point, we may consider to enhance the design/implementation on calculating on quota of the disk space in the future. But I don't think it is a priority for now. On the other hand, it (the enhancement) will also complicate the implementation, personally I would suggest to keep it as it's for now.

**Comment by ahrtr** [comment]
There is no plan for this enhancement, I suggest to close this ticket for now. WDYT? cc  @serathius @spzala @ptabor

**Comment by cenkalti** [comment]
> BoltDB indeed tries to reuse the free space, but it isn't guaranteed it will always reuse the free space.

@ahrtr Can you elaborate a bit more on this?

From my understanding of the code, boltdb first tries to find requested number of consecutive pages from the freelist. If not found, it looks larger number of consecutive pages. If not found again, the database grows. The only possible case for wasted space that comes to my mind is when there are free pages in the freelist but they are not consecutive to fulfill the request.
https://github.com/etcd-io/bbolt/blob/ef8fde548e11f2f468257c7c71e120dab1a78ed9/db.go#L1057

Under what conditions boltdb cannot use the space available in freelist?
