### ISSUE TITLE
etcdctl lease id json output bug

### ISSUE THREAD

**Issue by jordan-da** [etcd-io/etcd#14294]
### What happened?

Getting a key attached to a lease with `-w json` results in what seems to be rounded lease id

```
▶ etcdctl get /foo -w json | jq
{
  "header": {
    "cluster_id": 3857049431318267400,
    "member_id": 5819150906786784000,
    "revision": 49,
    "raft_term": 3
  },
  "kvs": [
    {
      "key": "L2Zvbw==",
      "create_revision": 49,
      "mod_revision": 49,
      "version": 1,
      "value": "YmFy",
      "lease": 2658674479976362000
    }
  ],
  "count": 1
}
```

### What did you expect to happen?

I expected to see the correct lease id

```
▶ etcdctl get /foo -w fields
"ClusterID" : 3857049431318267579
"MemberID" : 5819150906786784485
"Revision" : 49
"RaftTerm" : 3
"Key" : "/foo"
"CreateRevision" : 49
"ModRevision" : 49
"Version" : 1
"Value" : "bar"
"Lease" : 2658674479976361868
"More" : false
"Count" : 1
```

### How can we reproduce it (as minimally and precisely as possible)?

```
▶ etcdctl lease grant 7000000000
Handling connection for 2379
lease 24e5825a70632f8c granted with TTL(7000000000s)
▶ etcdctl put /foo bar --lease 24e5825a70632f8c
OK
▶ etcdctl get /foo -w json | jq
{
  "header": {
    "cluster_id": 3857049431318267400,
    "member_id": 5819150906786784000,
    "revision": 49,
    "raft_term": 3
  },
  "kvs": [
    {
      "key": "L2Zvbw==",
      "create_revision": 49,
      "mod_revision": 49,
      "version": 1,
      "value": "YmFy",
      "lease": 2658674479976362000
    }
  ],
  "count": 1
}
▶ etcdctl get /foo -w fields
Handling connection for 2379
"ClusterID" : 3857049431318267579
"MemberID" : 5819150906786784485
"Revision" : 49
"RaftTerm" : 3
"Key" : "/foo"
"CreateRevision" : 49
"ModRevision" : 49
"Version" : 1
"Value" : "bar"
"Lease" : 2658674479976361868
"More" : false
"Count" : 1
```

### Anything else we need to know?

My bet is, somewhere the `etcdctl` client is casting an `int64` into an `int` or something. In golang `int` size is platform specific, so my gut says that one may see a test for this pass on some computers (like ci) but not others like locally on your mac (for example).

### Etcd version (please run commands below)

<details>

```console
root@etcd-0:/# etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/amd64

17:09:01 ▶ etcdctl version
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

n/a

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

n/a

**Comment by ahrtr** [comment]
It should the jq issue. Please execute `etcdctl get /foo -w json` (without `| jq `) and checkout the IDs.

**Comment by jordan-da** [comment]
oh my gosh... i never knew `jq` did that, pardon me while my world crumbles around me

sorry for the static, closing issue 🤦
