### ISSUE TITLE
Should we restart client side when it's using watch and etcd restored with a snapshot?

### ISSUE THREAD

**Issue by likakuli** [etcd-io/etcd#14303]
Is this a feature?

My client-side uses etcd client pkg to use its watch func. My problem is when client side is watching etcd, but etcd restored with a snapshot, what should client side to do. Restart client side or just keep running?

It seems that the client side doesn't receive any error about etcd restore and will keep running if we don't restart it manually. Thus may lost some event because the revision in client side may large than real revision in etcd when restored.

**Comment by ahrtr** [comment]
> the revision in client side may large than real revision in etcd when restored.

This will never happen, otherwise it's an issue. A follower will not receive a snapshot with older index or revision.

**Comment by likakuli** [comment]
I mean the revision used in etcd client side.

I can reproduce it in k8s.

1. create a k8s cluster and write some object.
2. backup etcd
3. write some object to k8s cluster.
4. use backup file generated in step 2 to restore k8s etcd
5. data in kube-apiserver are the same with step 3.

**Comment by chenk008** [comment]
In my case, this may affect the data consistency of the kube-apiserver.

**Comment by serathius** [comment]
We are not responsible for incorrectly restored cluster.
