### ISSUE TITLE
[v3.5] Update OpenTelemetry to v1.0+

### ISSUE THREAD

**Issue by dashpole** [etcd-io/etcd#14311]
Part of https://github.com/etcd-io/etcd/issues/12460.

Given the release delays for v3.6, I'd like to propose updating the OpenTelemetry version used in etcd release-3.5 to v1.0+.  A quick `go get -u` shows that it would also require updating `github.com/stretchr/testify` from `v1.7.0` to `v1.7.1`.  That would help unblock using 1.0+ in kubernetes, which would unblock users that have a dependency on the kubernetes client as well.

cc @logicalhan @damemi @CatherineF-dev @dgrisonnet @serathius @sallyom

**Comment by ahrtr** [comment]
It's already in my to do list. Will get it resolved.

**Comment by ahrtr** [comment]
cc @spzala @nikhita

**Comment by ahrtr** [comment]
Fixed by https://github.com/etcd-io/etcd/pull/14312
