### ISSUE TITLE
Unable to use client with Web Assembly

### ISSUE THREAD

**Issue by lzakharov** [etcd-io/etcd#14337]
### What happened?

I get an error when building WASM application with the etcd client.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import (
	clientv3 "go.etcd.io/etcd/client/v3"  // v3.5.4
)

func main() {
	_, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"localhost:2379"},
	})
	if err != nil {
		panic(err)
	}
}
```

Build with:

```
GOARCH=wasm GOOS=js go build -o app.wasm
```

Got error:

```
# github.com/coreos/go-systemd/v22/journal
../../../go/pkg/mod/github.com/coreos/go-systemd/v22@v22.3.2/journal/journal_unix.go:120:20: undefined: syscall.UnixRights
```

Everything okay when I build program for unix/windows platforms.

### What did you expect to happen?

No error output.

**Comment by ahrtr** [comment]
AFAIK, We never tried the etcd client on `GOARCH=wasm GOOS=js` before. It isn't supported for now.

**Comment by xiaods** [comment]
syscall.UnixRights can't support for go web Assembly.
https://go-review.googlesource.com/c/go/+/150477/2/src/syscall/syscall_js.go#71
