### ISSUE TITLE
Checksum mismatch on github.com/coreos/go-systemd/v22@v22.3.2

### ISSUE THREAD

**Issue by tc1148** [etcd-io/etcd#14350]
I cannot download, install or even run "go mod tidy" when I include "go.etcd.io/etcd/client/v3" in my go application. The application previously was fine, but I need the Go etcd client. The recommended "go get go.etcd.io/etcd/client/v3@latest" produces the same result. I did a "go clean -modcache" and "rm go.sum" but continue to get the security error no matter what I do. Here is the output I get:

> go mod tidy
go: finding module for package go.etcd.io/etcd/client/v3
go: found go.etcd.io/etcd/client/v3 in go.etcd.io/etcd/client/v3 v3.5.4
go: downloading github.com/coreos/go-systemd/v22 v22.3.2
lm imports
	go.etcd.io/etcd/client/v3 imports
	go.etcd.io/etcd/client/pkg/v3/logutil imports
	github.com/coreos/go-systemd/v22/journal: github.com/coreos/go-systemd/v22@v22.3.2: verifying module: checksum mismatch
	downloaded: h1:drqFq/zp7QbjZIUfsiFQUic3QEo64w/MiTojKoCcLiI=
	sum.golang.org: h1:D9/bQk5vlXQFZ6Kwuu6zaiXJ9oTPe68++AzAJc1DzSI=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

**Comment by tc1148** [comment]
FYI, we finally solved this **but it took 2 senior SW engineers 2 days!!** This is pretty ridiculous that this is not better identified and published in github! We finally added the following to our go.mod file:

replace github.com/coreos/go-systemd/v22 **v22.3.2** => github.com/coreos/go-systemd/v22 v22.0.0

None of the published responses to this issue in github supplied this specific line, many variations, none of which worked. Through googling and experimentation we finally hit on this solution - it required the initial go-systemd full version, as shown above, due to the go.etcd.io/etcd/client/v3 requirement for v22 v22.3.2.

**Comment by ahrtr** [comment]
I do not reproduce this issue with steps below,
1. Create a simple golang program below,
```
package main

import (
	"context"
	"google.golang.org/grpc"

	clientv3 "go.etcd.io/etcd/client/v3"
)

func main() {
	//etcdHosts := []string{"127.0.0.1:2379", "127.0.0.1:22379", "127.0.0.1:32379"}
	etcdHosts := []string{"127.0.0.1:2379"}
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   etcdHosts,
		DialTimeout: 5 * time.Second,
		DialOptions: []grpc.DialOption{grpc.WithBlock()},
	})
	if err != nil {
		panic (err)
	}
	defer cli.Close()

	key, val := "key1", "val1"
	_, err = cli.Put(context.Background(), key, val)
	if err != nil {
		panic(err)
	}
}
```
2. `go mod init example.com/demo`
3. `go mod tidy`

Everything is working well, and the generated go.mod file is below.  Please provide a detailed steps on how to reproduce your issue. 

```
$ cat go.mod 
module example.com/demo

go 1.17

require (
	go.etcd.io/etcd/client/v3 v3.5.4
	google.golang.org/grpc v1.48.0
)

require (
	github.com/coreos/go-semver v0.3.0 // indirect
	github.com/coreos/go-systemd/v22 v22.3.2 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	go.etcd.io/etcd/api/v3 v3.5.4 // indirect
	go.etcd.io/etcd/client/pkg/v3 v3.5.4 // indirect
	go.uber.org/atomic v1.7.0 // indirect
	go.uber.org/multierr v1.6.0 // indirect
	go.uber.org/zap v1.17.0 // indirect
	golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4 // indirect
	golang.org/x/sys v0.0.0-20210603081109-ebe580a85c40 // indirect
	golang.org/x/text v0.3.5 // indirect
	google.golang.org/genproto v0.0.0-20210602131652-f16073e35f0c // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)
```
