### ISSUE TITLE
[Help] Graceful delete of lots of objects

### ISSUE THREAD

**Issue by BlueBlue-Lee** [etcd-io/etcd#14369]
I would like to store a lot of objects into etcd and want to implement graceful deletion( or delayed deletion) for every object.

There are two solutions:
-  Solution A: etcd lease. When delete one object, attach a lease to it
-  Solution B: not use etcd lease, implement it on higher application logic, for example add one field `deletionTimestamp` into value and periodically list and finally delete objects

I don't know if there is performance issue if lots of leases are created in etcd. Could you please give some suggestions? Thanks.

**Comment by ahrtr** [comment]
What's the "a lot of"? It should be fine for thousands. It also depends on the size of the each object. Previously we ran out of the default disk space quota (2GB) with about 100K K8s events.

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
