### ISSUE TITLE
[Help Wanted] Is it possible to rollback etcd database via *.snap or *.wal files?

### ISSUE THREAD

**Issue by yahaa** [etcd-io/etcd#14365]
Hi,
In our production k8s cluster, we accidentally deleted some very important CRDs and  don't take a snapshot by `etcdctl snapshot save` command, so I would like to ask, is it possible to rollback the etcd database to a certain point in time through the .snap or .wal files in the etcd data directory? Such as following picture, is it possible to rollback etcd database via `Aug 18 17:48 0000000000000004-0000000006886152.snap`  to the time point `Aug 18 17:48`. 

![image](https://user-images.githubusercontent.com/16364111/185626915-09edb3fd-8155-465b-b5d6-e11a3b93bd39.png)

Thanks!

🥺

**Comment by yahaa** [comment]
```
[root@k8s ~]# etcd --version
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64

```

**Comment by ahrtr** [comment]
In theory, it's doable, but there isn't such a tool so far. It isn't guaranteed either; if the history data has already been compacted, then there is no way to restore it. 

The best choice for now is to recreate the resource from the client side.

**Comment by yahaa** [comment]
> In theory, it's doable, but there isn't such a tool so far. It isn't guaranteed either; if the history data has already been compacted, then there is no way to restore it.
> 
> The best choice for now is to recreate the resource from the client side.

Thanks

**Comment by ahrtr** [comment]
Please feel free to raise new issue if you have any new queries/questions.
