### ISSUE TITLE
data integrity guarantees on power loss of machine with SSD with volatile write cache and -o nobarrier

### ISSUE THREAD

**Issue by b10s** [etcd-io/etcd#14385]
Hi,

I'm asking strange :) First answer to my question would be - don't do what I'm asking. It is not recommended to [disabling write barriers](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/writebarrieronoff) on disks with volatile disk write caches e.g. DRAM without battery.

However theoretically there might be cases, especially in the world of distributed systems, where we can allow one node to be broken because we can detect it and catch up/repair. Theoretically.

Let me clarify etcd details.

How will etcd cluster behave in case of sudden power loss of one node with SSD disk which has only DRAM volatile (no battery) write cache?

What may happen in the worst case and what in the best case?

---

_Probably in the best case, cluster can repair this node: somehow catch up quickly by detecting revision id difference._

_Probably in the worst case, cluster will not mention data loss of one node, if the node after start can maintain the same revision id but actual data somehow is broken. In future it may be detected during read operation and then.. since there is consensus algorithm envloved all must be good even in the worst case?_

**Comment by jberkus** [comment]
It's really going to depend on what happens with the other nodes in the cluster.  If it's a general datacenter outage and all nodes shut down without time to flush, that's a different situation than just one node losing power.

**Comment by lavacat** [comment]
>How will etcd cluster behave in case of sudden power loss of one node with SSD disk which has only DRAM volatile (no battery) write cache?
I think this falls into category of "Avoiding persistent storage writes" (part 11.7.3 of raft [paper](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf)). Also see [discussion](https://groups.google.com/g/raft-dev/c/Ci9KE6mdiu4/) in raft-dev

My understanding is the following:
1. If you have stable storage. In case of majority/all of the nodes going down you loose only availability. When nodes are back, they can form quorum and there will be no data loss.
2. In your example  storage is 'partially' stable. So in case of majority/all nodes going down at the same time - you loose availability and durability. When nodes are back, some data might be missing.
3. In both cases - if majority of the nodes are operational at all times - you have durability and availability.

Also, during our discussion at the meeting I've mentioned byzantine failure. I don't think it's applicable here. I was thinking about situation when raft follower will end up writing data that's not is AppendEntries request from Leader. But in your scenario we just have cache that can disappear.

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
