### ISSUE TITLE
[makefile can't set GO_BUILD_FLAGS through env ]

### ISSUE THREAD

**Issue by rensx5514** [etcd-io/etcd#14396]
### What happened?

Makefile
`
.PHONY: build
build:
	GO_BUILD_FLAGS="-v" ./scripts/build.sh
	./bin/etcd --version
	./bin/etcdctl version
	./bin/etcdutl version
`
GO_BUILD_FLAGS="-v"  will overwrite GO_BUILD_FLAGS in env.

### What did you expect to happen?

Makefile
`
.PHONY: build
build:
	GO_BUILD_FLAGS="-v" ./scripts/build.sh
	./bin/etcd --version
	./bin/etcdctl version
	./bin/etcdutl version
`
It should set as following.
` GO_BUILD_FLAGS +=" -v"  `

### How can we reproduce it (as minimally and precisely as possible)?

Repair it in Makefile!!!
`
.PHONY: build
build:
	GO_BUILD_FLAGS="-v" ./scripts/build.sh
	./bin/etcd --version
	./bin/etcdctl version
	./bin/etcdutl version
`
It should set as following.
` GO_BUILD_FLAGS +=" -v"  `

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

It affects all etcd versions obviously.

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by rensx5514** [comment]
/important , We need it to add compile-security-option like "-buildmode=pie -trimpath" @bmizerany @technoweenie @drnic @pjjw

**Comment by theVJagrawal** [comment]
Can i work on this one?

**Comment by serathius** [comment]
Sure, Makefile definetly needs more love.

**Comment by rensx5514** [comment]
> Sure, Makefile definetly needs more love.

wuwuwuwu, I also want to work on this one.

**Comment by Bhargav-InfraCloud** [comment]
PR #14868 for reading go build flags from env `GO_BUILD_FLAGS`.
`-trimpath` already exists in building [etcd][1], [etcdutl][2] & [etcdctl][3].

[1]: https://github.com/etcd-io/etcd/blob/main/scripts/build_lib.sh#L23
[2]: https://github.com/etcd-io/etcd/blob/main/scripts/build_lib.sh#L34
[3]: https://github.com/etcd-io/etcd/blob/main/scripts/build_lib.sh#L45
