### ISSUE TITLE
Implement distributed lock by other language problem

### ISSUE THREAD

**Issue by AdiaLoveTrance** [etcd-io/etcd#14403]
Hi,
I want to implement distributed lock using etcd, and I found there is a proto file in "server/etcdserver/api/v3lock/v3lockpb/v3lock.proto". My question is can other language except Go directly use those grpc services to implement distributed lock, or there are some other steps I need to do.

**Comment by jbml** [comment]
Hi @AdiaLoveTrance ,
I would suggest you to take a look at https://etcd.io/docs/v3.5/integrations/ and see a list of etcd clients available in different languages, in case that suits your needs.
