### ISSUE TITLE
[Documentation] confused about snapshot save command

### ISSUE THREAD

**Issue by durzo** [etcd-io/etcd#14412]
When scheduling automatic snapshots via cron - should `etcdctl snapshot save` be run on each cluster member, or is it a cluster-wide operation? does it matter if the node running the snapshot is a leader or follower? the docs are not very clear on this.

**Comment by ahrtr** [comment]
`etcdctl snapshot save fileName` just writes a point-in-time snapshot of the etcd backend database, of the member it connects to ,to a file. It doesn't care whether it's a leader or follower. So it seems that it's better & safer to perform the operation against the leader.
