### ISSUE TITLE
etcd has no mechanism to prevent brute force cracking

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#14444]
etcd does not limit the number of connections with incorrect passwords, which may lead to the cracking of the administrator password, which poses a certain security risk.

**Comment by mitake** [comment]
You can create a user with no password based authentication with `etcdctl user add <user name> --no-password`. Such a user only allows CN based authnz. If you really want to avoid the brute force risk, I think it works for the purpose.

**Comment by xiaods** [comment]
> CN based authnz
hi mitake, could you please give more steps on authnz, thanks a lot.
