### ISSUE TITLE
ETCD DB increased when leader etcd pods being killed

### ISSUE THREAD

**Issue by geotransformer** [etcd-io/etcd#14446]
ETCD  3.4.13, K8S 1.21

The test was to delete leader etcd pods once per minute. The test lasted about an hour, and the etcd leaders moved around successfully.  

However, the DB size increased from 24 MB to 86 MB 
Is this expected behavior?

**Comment by ahrtr** [comment]
would you mind reproduce this using 3.5.4 or binaries built from `main`, and provide the `db` file?

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/etcd/issues/14329

**Comment by serathius** [comment]
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions
