### ISSUE TITLE
Stability level for etcd metrics

### ISSUE THREAD

**Issue by CatherineF-dev** [etcd-io/etcd#14448]
### What happened?

ETCD has some very useful metrics https://etcd.io/docs/v3.4/metrics/. But they don't have stability level. 

If some etcd metrics are marked as stable, down-stream can leverage these metrics with less risks of deprecation.

### What did you expect to happen?

Introduce stability level for etcd metrics. Experimental/Stable

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>
NA

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Only the metrics under the etcd_debugging prefix are not stable. FYI. https://etcd.io/docs/v3.5/metrics/#etcd_debugging-namespace-metrics 

All other metrics are stable.

**Comment by ahrtr** [comment]
Please let me know if you still have any concern.

**Comment by CatherineF-dev** [comment]
Thanks! Could we document other metrics as stable in etcd public doc https://etcd.io/docs/v3.5/metrics?

**Comment by serathius** [comment]
Please file an issue to https://github.com/etcd-io/website
