### ISSUE TITLE
Presubmit checks for stable metrics

### ISSUE THREAD

**Issue by CatherineF-dev** [etcd-io/etcd#14509]
### What would you like to be added?

A presubmit to validate stable metrics don't change metric name, add labels or delete labels.

Similar to this [stable metrics presubmit](https://github.com/kubernetes/kubernetes/tree/master/test/instrumentation).

### Why is this needed?

Metrics are very important to monitor health of ETCD. 
Most non-debug etcd metrics are declared as [stable](https://github.com/etcd-io/etcd/issues/14448), but without a presubmit to guarantee stable metrics won't be changed. 

Changed metrics will break existing monitoring/alerts, and bring some migration work.

**Comment by serathius** [comment]
Hey @CatherineF-dev, thanks for proposing. I was one of the people that designed and implemented metric stability for K8s. It's a great tool for large repo. Kubernetes had thousands of contributors grouped in tens of special interest groups. Each group is responsible for part of the codebase and has their own code approvers that can merge code. This mans that there are tens if not hundreds of people that can add/remove/change metrics. 

On the other hand etcd project has maybe 10 contributors and 3-4  maintainers that can merge code. I think we don't need a dedicated tool to make sure that everyone doesn't break stable metrics by mistake.

I don't think we need a automatic tool, however I'm not sure if there was an official agreement about metric stability in etcd repo.
https://etcd.io/docs/v3.4/metrics/#etcd-namespace-metrics mentions that some metrics are "stable" but doesn't provide exact definition of what that means (apart of that their changes should be included in changelog). 

I think we could add metrics section to [contributor guide](https://github.com/etcd-io/etcd/tree/main/Documentation/contributor-guide) and metric stability definition to [feature stability]https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/features.md#stable-1. cc @spzala @ahrtr

**Comment by ahrtr** [comment]
Basically I agree with @serathius . Points:
1. We already have process on how to add & deprecate [feature](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/features.md), so in general we just need to follow it to add or deprecate metrics. 
2. We can add a separate doc (e.g. `metrics.md`) to clearly clarify the details on metrics update. 
3. With regard to the tool to validate stable metrics, probably it's a little overkill for now.

**Comment by spzala** [comment]
I agree with @serathius and @ahrtr that we can cover it with documentation leveraging guidelines and policies we recently added for features. Thanks!

**Comment by serathius** [comment]
> Maybe it's optional to have a presubmit check now, given 10 contributors and 3-4 maintainers. But things might change in the future.

It might be negative, but I don't expect us to 100x contributors to reach K8s numbers.

**Comment by xiaods** [comment]
> 2\. We can add a separate doc (e.g. `metrics.md`) to clearly clarify the details on metrics update.

prefer 2

**Comment by bsdnet** [comment]
Since etcd is moving to sig-etcd, should we revisit this topic, and enforce the stable check during presubmit?
