### ISSUE TITLE
Improve slow follower reliability/performance

### ISSUE THREAD

**Issue by tjungblu** [etcd-io/etcd#14501]
### What would you like to be added?

I was debugging a couple test failures today in our CI environment, we're running three node v3.5.3 on a cloud with a V in it. 
Looking at the metrics I saw one follower being consistently very slow (high fsync latency), now theoretically this shouldn't impact any writes as we still have the leader and another fast follower to persist the messages safely.

![image](https://user-images.githubusercontent.com/85170409/191543122-c2f2b007-7023-4f51-b668-8f71de1f4830.png)

Sorry, this should've been a sequence diagram, but that's all I got between meetings :) Effectively the message should be sent to slow etcd-2, but etcd-3 would be faster to respond back with the entry committed and we can move on. etcd-2 can eventually catch up on the log.

What I do see in reality, however, is overall bad latency on the whole write operation which suspiciously makes it look like it waits for both (fast+slow) follower to apply the entry.

I found this code path explaining why this was done that way, which makes sense:
https://github.com/etcd-io/etcd/blob/main/server/etcdserver/raft.go#L287-L313

Did I get this right or does it work as described initially? In the former case, how can we mitigate the slow-follower issue?

### Why is this needed?

A slow follower causes a lot of negative impact (eg slow writes and higher error rates) on an otherwise healthy quorum.

**Comment by tjungblu** [comment]
I just created a cluster where I injected a sleep into the above code lines, then just run the perf check against this. Then just changed the endpoints to directly target individual members.


all healthy three endpoints:

```
/ # etcdctl check perf
60 / 60 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
PASS: Throughput is 151 writes/s
PASS: Slowest request took 0.043940s
PASS: Stddev is 0.001628s
PASS
```

one slow follower in three endpoints:

```
FAIL: too many errors
FAIL: ERROR(etcdserver: request timed out) -> 1
FAIL: Throughput too low: 23 writes/s
Slowest request took too long: 6.983128s
Stddev too high: 2.643286s
FAIL
```

slow follower excluded in endpoints:

```
/ # etcdctl check perf 
60 / 60 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
PASS: Throughput is 151 writes/s
PASS: Slowest request took 0.044842s
PASS: Stddev is 0.001814s
PASS
```

writes directly going to slow follower:

```
/ # ETCDCTL_ENDPOINTS=etcd1:2379
/ # etcdctl check perf 
60 / 60 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s
FAIL: Throughput too low: 8 writes/s
Slowest request took too long: 7.002202s
Stddev too high: 0.251630s
FAIL
```

So it seems that my initial assumption was wrong, it does not wait for a slow follower when writing. The writes going directly to the slow follower are what's causing the trouble.

I'll close this for now, as this can be mitigated by tweaking GRPC clients and/or circuit breakers.

**Comment by tjungblu** [comment]
Thanks @serathius. I'm still figuring out the GRPC behavior here, it seems like the graceful switch load balancer only pulls out an endpoint when the Ready connection goes to any other state (eg TransientFailure). The connection is slow, just not as bad to fail on timeouts yet. 

I have to research a bit more and open a new issue up with a proposal. Do you guys have some kind of design process?

**Comment by serathius** [comment]
No official design process, but feel free to check out previous design proposals if you need a template. For example one of mine https://github.com/etcd-io/etcd/issues/14039

**Comment by SowAbdoul** [comment]
I need help with an issue in my Kubernetes cluster, which is set up with 3 control-plane nodes and 3 worker nodes using kubeadm. The etcd pods are located on the control-plane nodes. Initially, everything was working fine, but after a few months of usage, I've started encountering errors in etcd that are causing other pods to crash.

The error message I see is:

```javascript
Error from server: etcdserver: leader changed
```

After researching online, I added the following options to my etcd manifests:

```yaml
etcd.yaml
---
spec:
  containers:
  - command:
    - --snapshot-count=10000
    - --heartbeat-interval=500
    - --election-timeout=2500
    - --pre-vote=true
    ...
    resources: {}
```
While the frequency of errors has decreased, they are still persisting, and it feels like I've only moved the problem rather than fully resolving it.

Currently, the `/var/lib/etcd` directory is mounted on the system partition. I want to mount a new partition on `sdb` and then move `etcd` to it. Do you think this will resolve the performance issues with etcd?

Could you please help me with this issue?

**Comment by LiuJinghao** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by aneesh1** [comment]
👋 Hi! I'm running into an issue similar to this. I have a question for @tjungblu - what do you mean by this?

> So it seems that my initial assumption was wrong, it does not wait for a slow follower when writing. The writes going directly to the slow follower are what's causing the trouble.

**Comment by LiuJinghao** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
