### ISSUE TITLE
How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### ISSUE THREAD

**Issue by luomengY** [etcd-io/etcd#14518]
### What happened?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### What did you expect to happen?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### How can we reproduce it (as minimally and precisely as possible)?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### Anything else we need to know?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### Etcd version (please run commands below)

etcd v3.5.4

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
You should can get the info from log something like below,
```
{"level":"info","ts":"2022-09-26T10:12:14.374+0800","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"08407ff76","go-version":"go1.16.15","go-os":"darwin","go-arch":"amd64","max-cpu-set":16,"max-cpu-available":16,"member-initialized":true,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
```

**Comment by spzala** [comment]
+1 @ahrtr Please look at the log.

**Comment by mbanck-cd** [comment]
I don't see those above log message for a regular etcd startup, are those from some wrapper script or something K8S-specific?

In any case, I find it weird to refer the question of "what is the current runtime-configuration of my etcd cluster?" to refer to "just look at the startup message in the log".
