### ISSUE TITLE
Cannot restart or scale in/out etcd instances when deploying etcd cluster in K8s

### ISSUE THREAD

**Issue by TridentZZ** [etcd-io/etcd#14519]
### What happened?

在重启和伸缩后etcd出现成员加入失败的错误

2022-09-26 00:56:10.055385 N | etcdserver/membership: updated member 47324e080c98137d [http://apisix-etcd-1.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380] in cluster b9ae902a9398fd61
2022-09-26 00:56:10.055401 I | rafthttp: updated peer 47324e080c98137d
raft2022/09/26 00:56:10 INFO: 39e3f227d2d33a6d switched to configuration voters=(4171443932729916013 5130248722006414205 16309538207480531017)
2022-09-26 00:56:10.055533 N | etcdserver/membership: updated member 47324e080c98137d [http://apisix-etcd-1.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380] in cluster b9ae902a9398fd61

------------------------------------------

raft2022/09/26 00:57:07 INFO: 47324e080c98137d is starting a new election at term 92365
raft2022/09/26 00:57:07 INFO: 47324e080c98137d became candidate at term 92366
raft2022/09/26 00:57:07 INFO: 47324e080c98137d received MsgVoteResp from 47324e080c98137d at term 92366
raft2022/09/26 00:57:07 INFO: 47324e080c98137d [logterm: 8, index: 35] sent MsgVote request to 8f5925ccd9e6ad0c at term 92366
raft2022/09/26 00:57:08 INFO: 47324e080c98137d is starting a new election at term 92366
raft2022/09/26 00:57:08 INFO: 47324e080c98137d became candidate at term 92367
raft2022/09/26 00:57:08 INFO: 47324e080c98137d received MsgVoteResp from 47324e080c98137d at term 92367
raft2022/09/26 00:57:08 INFO: 47324e080c98137d [logterm: 8, index: 35] sent MsgVote request to 8f5925ccd9e6ad0c at term 92367
2022-09-26 00:57:08.981751 W | rafthttp: health check for peer 8f5925ccd9e6ad0c could not connect: dial tcp 172.17.8.8:2380: connect: connection refused
2022-09-26 00:57:08.981780 W | rafthttp: health check for peer 8f5925ccd9e6ad0c could not connect: dial tcp 172.17.8.8:2380: connect: connection refused
raft2022/09/26 00:57:10 INFO: 47324e080c98137d is starting a new election at term 92367
raft2022/09/26 00:57:10 INFO: 47324e080c98137d became candidate at term 92368
raft2022/09/26 00:57:10 INFO: 47324e080c98137d received MsgVoteResp from 47324e080c98137d at term 92368
raft2022/09/26 00:57:10 INFO: 47324e080c98137d [logterm: 8, index: 35] sent MsgVote request to 8f5925ccd9e6ad0c at term 92368

### What did you expect to happen?

etcd容器重启和伸缩后能够自动加入集群中

### How can we reproduce it (as minimally and precisely as possible)?

部署ETCD到K8S集群，然后进行重启和伸缩

### Etcd version (please run commands below)

etcd:3.4.18-debian-10-r14

### Etcd configuration (command line flags or environment variables)

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: apisix
    meta.helm.sh/release-namespace: ingress-apisix
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-8.3.4
  name: apisix-etcd
  namespace: ingress-apisix
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: etcd
  serviceName: apisix-etcd-headless
  template:
    metadata:
      annotations:
        checksum/token-secret: 4de68d46e85f5b22e60fc3fbe3cb464e73bd2bbedd9faf40dee8bc5de2bfc4b4
        redeploy-timestamp: '1663917023681'
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: etcd
        helm.sh/chart: etcd-8.3.4
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: apisix
                    app.kubernetes.io/name: etcd
                namespaces:
                  - ingress-apisix
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - env:
            - name: BITNAMI_DEBUG
              value: 'true'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_STS_NAME
              value: apisix-etcd
            - name: ETCDCTL_API
              value: '3'
            - name: ETCD_ON_K8S
              value: 'yes'
            - name: ETCD_START_FROM_SNAPSHOT
              value: 'no'
            - name: ETCD_DISASTER_RECOVERY
              value: 'no'
            - name: ETCD_NAME
              value: $(MY_POD_NAME)
            - name: ETCD_DATA_DIR
              value: /bitnami/etcd/data
            - name: ETCD_LOG_LEVEL
              value: info
            - name: ALLOW_NONE_AUTHENTICATION
              value: 'yes'
            - name: ETCD_AUTH_TOKEN
              value: >-
                jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: >-
                http://$(MY_POD_NAME).apisix-etcd-headless.ingress-apisix.svc.cluster.local:2379,http://apisix-etcd.ingress-apisix.svc.cluster.local:2379
            - name: ETCD_LISTEN_CLIENT_URLS
              value: 'http://0.0.0.0:2379'
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: >-
                http://$(MY_POD_NAME).apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380
            - name: ETCD_LISTEN_PEER_URLS
              value: 'http://0.0.0.0:2380'
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: etcd-cluster-k8s
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: new
            - name: ETCD_INITIAL_CLUSTER
              value: >-
                apisix-etcd-0=http://apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380,apisix-etcd-1=http://apisix-etcd-1.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380,apisix-etcd-2=http://apisix-etcd-2.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380
            - name: ETCD_CLUSTER_DOMAIN
              value: apisix-etcd-headless.ingress-apisix.svc.cluster.local
          image: 'harbor.yeemiao.com:8443/library/etcd:3.4.18-debian-10-r14'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/bitnami/scripts/etcd/prestop.sh
          livenessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: etcd
          ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /bitnami/etcd
              name: data
            - mountPath: /opt/bitnami/etcd/certs/token/
              name: etcd-jwt-token
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: data
        - name: etcd-jwt-token
          secret:
            defaultMode: 256
            secretName: apisix-etcd-jwt-token
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: alicloud-disk-ssd
        volumeMode: Filesystem
      status:
        phase: Pending

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Please read https://etcd.io/docs/v3.5/op-guide/runtime-configuration/

**Comment by TridentZZ** [comment]
i can not change the config ETCD_INITIAL_CLUSTER_STATE and ETCD_INITIAL_CLUSTER in the new pod when i scale in etcd. as the result:
2022-09-26 03:23:34.699910 W | rafthttp: health check for peer 3c483d3e7f6dddf8 could not connect: dial tcp 172.17.174.107:2380: connect: connection refused
2022-09-26 03:23:37.551066 W | etcdserver: failed to reach the peerURL(http://apisix-etcd-3.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380) of member 3c483d3e7f6dddf8 (Get http://apisix-etcd-3.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380/version: dial tcp 172.17.174.107:2380: connect: connection refused)
2022-09-26 03:23:37.551101 W | etcdserver: cannot get the version of member 3c483d3e7f6dddf8 (Get http://apisix-etcd-3.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380/version: dial tcp 172.17.174.107:2380: connect: connection refused)

**Comment by ahrtr** [comment]
You need an operator or application to do it.
