### ISSUE TITLE
Extending CI pipeline, on behalf of 64bit  RISC-V environment

### ISSUE THREAD

**Issue by advancedwebdeveloper** [etcd-io/etcd#14522]
### What would you like to be added?

On behalf of https://github.com/etcd-io/etcd/pull/14517 :

1. Qemu related
2. Board related (hosting Github Actions runner, on a 64bit RISC-V Linux & board)
3. Cross-compilation

I am currently using Ubuntu 22.04 under Qemu. OpenSUSE's support is not up-to-date. Didn't check on Fedora - can try later, to diversify.
Existing Github Actions script can perform (3) - and we could use (1) and (2) for testing. However (1) and (2) means compilation and running within the same environment.

### Why is this needed?

Providing an explanation of what should be executed on a guest VM, for the CI.

**Comment by serathius** [comment]
I don't think it's clear what this issue is proposing. Are you proposing to add a RISC-V runner?

**Comment by advancedwebdeveloper** [comment]
RISC-V runner requires porting .NET to RISC-V. So that can't be done quickly. Self-hosted runner is not an option, as for now - so Github's hosted runner can perform (3).

As for testing (build env. == test env.) - Qemu and the board could be used.
