### ISSUE TITLE
Peer occasionally becomes and stays inactive after member restart

### ISSUE THREAD

**Issue by dimara** [etcd-io/etcd#14523]
### What happened?

We tried to add a new  member to a two node cluster (rok-etcd-0, rok-etcd-1) and failed with:
```
{"level":"warn","ts":"2022-09-23T09:52:00.805Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000458a80/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: unhealthy cluster"}
Error: etcdserver: unhealthy cluster
```
The cluster seemed to be healthy and we were able to make requests.

Looking at the logs of rok-etcd-1 member we saw:
```
{"level":"warn","ts":"2022-09-23T09:52:00.805Z","caller":"etcdserver/server.go:1600","msg":"rejecting member add request; local member has not been connected to all peers, reconfigure breaks active quorum","local-member-id":"fa1fea7afbd1b4e9","requested-member-add":"{ID:193702e543b0c6da RaftAttributes:{PeerURLs:[http://rok-etcd-2.rok-etcd-cluster.rok:2380] IsLearner:true} Attributes:{Name: ClientURLs:[]}}","error":"etcdserver: unhealthy cluster"}
```

And before that it reported that the other member `rok-etcd-0` became active and then inactive again:
```
{"level":"info","ts":"2022-09-23T09:50:23.476Z","caller":"rafthttp/peer_status.go:53","msg":"peer became active","peer-id":"69b60ba94f21e626"}
...
{"level":"warn","ts":"2022-09-23T09:50:25.291Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"69b60ba94f21e626","error":"failed to write 69b60ba94f21e626 on pipeline (read tcp 192.168.211.158:45680->192.168.254.246:2380: read: connection reset by peer)"
```

We were constantly getting this error and couldn't recover. But when we tried to talk to the other member (rok-etcd-0) the command succeeded.

### What did you expect to happen?

1. etcd to recover from a temporary failure and try to reconnect to the member.
2. We expected the same behavior from both members, in our case fail member add on both members.
3. If member add fails we expected reads/writes to fail as well since the quorum for two members is two.

### How can we reproduce it (as minimally and precisely as possible)?

We managed to reproduce it occasionally by restarting rok-etcd-0 Pod and observing the logs of rok-etcd-1. In case of failure rok-etcd-1 would report rok-etcd-0 as inactive without becoming active again.

### Anything else we need to know?

We also managed reproduce this with a slightly different error:
```
{"level":"warn","ts":"2022-09-26T16:32:32.125Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"b2ff88bb2eae13b7","error":"failed to write b2ff88bb2eae13b7 on pipeline (unexpected http status Service Unavailable while posting to \"http://rok-etcd-0.rok-etcd-cluster.rok:2380/raft\")"}
```
In this case the 503 came from Istio sidecar:
```
[2022-09-26T10:04:51.251Z] "POST /raft HTTP/1.1" 503 UF upstream_reset_before_response_started{connection_failure} - "-" 50 91 8131 - "-" "Go-http-client/1.1" "ca907b8d-672c-9ef8-be8d-6f99d97aa3fd" "rok-etcd-0.rok-etcd-cluster.rok:2380" "192.168.188.162:2380" PassthroughCluster - 192.168.188.162:2380 192.168.172.148:45388 - allow_any
```

Note that for some reason the first IP reported there is the IP of the **previous** rok-etcd-0 Pod. 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.4
API version: 3.5
```
</details>

### Etcd configuration (command line flags or environment variables)

```
/usr/local/bin/etcd \
  --name=rok-etcd-1.rok-etcd-cluster.rok \
  --data-dir=/var/etcd/data \
  --enable-v2=true \
   --max-request-bytes=104857600 \
   --quota-backend-bytes=-1 \
   --auto-compaction-retention=3 \
   --initial-advertise-peer-urls=http://rok-etcd-1.rok-etcd-cluster.rok:2380 \
   --initial-cluster=rok-etcd-0.rok-etcd-cluster.rok=http://rok-etcd-0.rok-etcd-cluster.rok:2380,rok-etcd-1.rok-etcd-cluster.rok=http://rok-etcd-1.rok-etcd-cluster.rok:2380 \
   --initial-cluster-state=existing \
   --initial-cluster-token=rok-token \
   --advertise-client-urls=http://rok-etcd-1.rok-etcd-cluster.rok:2379 \
   --listen-client-urls=http://0.0.0.0:2379 \
   --listen-peer-urls=http://0.0.0.0:2380 \
   --snapshot-count=10000 \
   --max-snapshots=1
```

Note that this is a StatefulSet with two replicas using Istio sidecar with Istio 1.14.1.

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
+------------------+---------+---------------------------------+---------------------------------------------+---------------------------------------------+------------+
|        ID        | STATUS  |              NAME               |                 PEER ADDRS                  |                CLIENT ADDRS                 | IS LEARNER |
+------------------+---------+---------------------------------+---------------------------------------------+---------------------------------------------+------------+
| 457f2659d59730c8 | started | rok-etcd-1.rok-etcd-cluster.rok | http://rok-etcd-1.rok-etcd-cluster.rok:2380 | http://rok-etcd-1.rok-etcd-cluster.rok:2379 |      false |
| b2ff88bb2eae13b7 | started | rok-etcd-0.rok-etcd-cluster.rok | http://rok-etcd-0.rok-etcd-cluster.rok:2380 | http://rok-etcd-0.rok-etcd-cluster.rok:2379 |      false |
+------------------+---------+---------------------------------+---------------------------------------------+---------------------------------------------+------------+


$ etcdctl --endpoints=<member list> endpoint status -w table
+---------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|                  ENDPOINT                   |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+---------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://rok-etcd-0.rok-etcd-cluster.rok:2379 | b2ff88bb2eae13b7 |   3.5.4 |   10 MB |     false |      false |       106 |   18770384 |           18770384 |        |
| http://rok-etcd-1.rok-etcd-cluster.rok:2379 | 457f2659d59730c8 |   3.5.4 |   10 MB |      true |      false |       106 |   18770386 |           18770386 |        |
+---------------------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

</details>

**Comment by serathius** [comment]
Etcd was never tested under istio and I don't expect we will provide any support. Please provide steps to reproduce the issue without istio.

**Comment by ahrtr** [comment]
The reason should be that the network between peers isn't stable. When adding a new member, etcd requires that the member, receiving the request, must be kept connecting to all other peers in the past 5 seconds.

**Comment by klolos** [comment]
> Please provide steps to reproduce the issue without istio.

@serathius We were able to reproduce this without Istio as well, by simply restarting one of the members. By looking at the logs of member 1 (`rok-etcd-1`), we noticed that when restarting member 0 (`rok-etcd-0`), member 1 logged that node 0 became active approximately 10 seconds after it started. So to trigger the bug, we restarted node 0 **again** at approximately the time when node 1 reported it becoming active. It only took a few attempts to trigger it:

```
{"level":"info","ts":"2022-09-27T08:42:26.593Z","caller":"rafthttp/peer_status.go:53","msg":"peer became active","peer-id":"b2ff88bb2eae13b7"}
...
{"level":"warn","ts":"2022-09-27T08:42:28.170Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"b2ff88bb2eae13b7","error":"failed to write b2ff88bb2eae13b7 on pipeline (dial tcp: i/o timeout)"}
```


After this, the cluster remained **permanently** in the seemingly inconsistent state we described above:
* Member 1 refuses to accept member add requests, but accepts other reads/writes
* Member 0 accepts both member add and read/write requests
```
{"level":"warn","ts":"2022-09-27T08:43:20.168Z","caller":"etcdserver/server.go:1600","msg":"rejecting member add request; local member has not been connected to all peers, reconfigure breaks active quorum","local-member-id":"457f2659d59730c8","requested-member-add":"{ID:1962ea70790f51a8 RaftAttributes:{PeerURLs:[http://rok-etcd-2.rok-etcd-cluster.rok:2380/] IsLearner:true} Attributes:{Name: ClientURLs:[]}}","error":"etcdserver: unhealthy cluster"}
```

> The reason should be that the network between peers isn't stable. When adding a new member, etcd requires that the member, receiving the request, must be kept connecting to all other peers in the past 5 seconds.

@ahrtr This makes sense but what we have seen is that the cluster remains in that state ever after everything is up and running, and never recovers.

We have included the full logs of `rok-etcd-1` for reference:
[rok-etcd-1.log](https://github.com/etcd-io/etcd/files/9653978/rok-etcd-1.log)

Additionally, by taking a brief look at the code, we think that the "peer became inactive" log is triggered when this request fails:
https://github.com/etcd-io/etcd/blob/08407ff7600eb16c4445d5f21c4fafaf19412e24/server/etcdserver/api/rafthttp/pipeline.go#L100

As far as we can tell, if this fails in any way then the cluster remains in this state and does not recover. Additionally, we see that there are multiple goroutines performing this request, so there could be an extra race where the final state may depend on which request completed last.

**Comment by klolos** [comment]
@serathius @ahrtr Have you had the chance to look into this?

**Comment by serathius** [comment]
No, we are unfortunately busy with handling another data inconsistency issue.
Thanks for reproducing it without istio, however I'm still unsure how to reproduce it myself. Could you provide a short script that shows the behavior?

**Comment by ahrtr** [comment]
I see lots of "`prober detected unhealthy status`" warning message, it seems that it's still caused by peer network communication issue.

**Comment by klolos** [comment]
> No, we are unfortunately busy with handling another data inconsistency issue.
> Thanks for reproducing it without istio, however I'm still unsure how to reproduce it myself. Could you provide a short script that shows the behavior?

@serathius We were able to reproduce it on Kubernetes with Istio simply by restarting an etcd member (see https://github.com/etcd-io/etcd/issues/14523#issue-1386472947). Also, we reproduced it without Istio by restarting an etcd member around the time the other member reported it becoming active (see https://github.com/etcd-io/etcd/issues/14523#issuecomment-1259234399). In both cases we used a two node cluster, and it took a few attempts to trigger the bug. Can you attempt to do the same and see if you can also reproduce it?

**Comment by niharkawli** [comment]
Saw similar issue on our test bed while issuing a member remove from 3 node etcd cluster with all the members seen as healthy in etcdctl endpoint status -w table --cluster output.

etcd version:
```
kubectl --kubeconfig ~cloud-user/.kube/config exec etcd-tb2-s1-c1-server1  -n kube-system -- etcd --version
etcd Version: 3.5.5
Git SHA: 19002cfc6
Go Version: go1.16.15
Go OS/Arch: linux/amd64
```
**Command Issued:**
```
kubectl --kubeconfig ~cloud-user/.kube/config exec etcd-tb2-s1-c1-server1 -n kube-system -- etcdctl member remove --cert=/data/kubernetes/pki/etcd/server.crt  --key=/data/kubernetes/pki/etcd/server.key --cacert=/data/kubernetes/pki/etcd/ca.crt  42dbcfb64cae624d
{"level":"warn","ts":"2023-02-13T15:09:03.936Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000e2540/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: unhealthy cluster"}
Error: etcdserver: unhealthy cluster
```

**Process logs:**
```
Feb 14 10:04:47 etcd-tb2-s1-c1-server1 ee7075451714[4866]: {"level":"warn","ts":"2023-02-14T10:04:46.305Z","caller":"etcdserver/server.go:1808","msg":"rejecting member remove request; local member has not been connected to all peers, reconfigure breaks active quorum","local-member-id":"42dbcfb64cae624d","requested-member-remove":"42dbcfb64cae624d","active-peers":2,"error":"etcdserver: unhealthy cluster"} 
```

Restarting this particular etcd process helped fix this condition and the member remove worked.
Don't know the trigger as this was a system running since 20 days but there seems to be some inconsistent state in the process and just restarting the process fixed it.

Any pointers ?

**Comment by jamesreprise** [comment]
I'm also finding this issue (without the use of istio). @klolos were you able to find a workaround?
