### ISSUE TITLE
integration TestAuthority failed due to "bind: address already in use"

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14541]
### Which github workflows are flaking?

linux-amd64-integration-4-cpu

### Which tests are flaking?

TestAuthority

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/3153014723/jobs/5128969677

### Reason for failure (if possible)

=== FAIL: integration TestAuthority/Size:_3,_Scenario:_"http://address[:port]" (0.00s)
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134105778
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134205778
    logger.go:130: 2022-09-29T16:45:35.996Z	INFO	m0	LISTEN GRPC	{"member": "m0", "grpcAddr": "127.0.0.1:33400", "m.Name": "m0", "workdir": "/tmp/TestAuthoritySize_3,_Scenario_httpaddressport382019041/001"}
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134405778
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134505778
    logger.go:130: 2022-09-29T16:45:35.996Z	INFO	m1	LISTEN GRPC	{"member": "m1", "grpcAddr": "127.0.0.1:33431", "m.Name": "m1", "workdir": "/tmp/TestAuthoritySize_3,_Scenario_httpaddressport382019041/001"}
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134705778
    cluster.go:535: Creating listener with addr: 127.0.0.1:2134805778
    logger.go:130: 2022-09-29T16:45:35.997Z	INFO	m2	LISTEN GRPC	{"member": "m2", "grpcAddr": "127.0.0.1:33462", "m.Name": "m2", "workdir": "/tmp/TestAuthoritySize_3,_Scenario_httpaddressport382019041/001"}
    cluster.go:731: listenGRPC FAILED: listen failed on grpc socket 127.0.0.1:33462 (listen tcp 127.0.0.1:33462: bind: address already in use)

**Comment by xiaods** [comment]
retry run below cmd 
```
    linux-amd64-integration-4-cpu)
      GOARCH=amd64 CPU=4 PASSES='integration' RACE='false' ./scripts/test.sh
      ;;
```
get err output:
```bash
'integration' started at Thu Oct  6 08:16:08 CST 2022
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '-timeout=15m' '--race=false' '--cpu=4' '-p=2' './integration/...')
ok      go.etcd.io/etcd/tests/v3/integration    (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3   (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/concurrency       (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/connectivity      (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/examples  (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/experimental/recipes      (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/lease     (cached)
ok      go.etcd.io/etcd/tests/v3/integration/clientv3/naming    (cached)
--- FAIL: TestSaveSnapshotFilePermissions (0.00s)
    logger.go:130: 2022-10-06T08:16:40.893+0800 INFO    default configuring peer listeners      {"listen-peer-urls": ["unix://localhost:39938"]}
    logger.go:130: 2022-10-06T08:16:40.894+0800 INFO    default closing etcd server     {"name": "default", "data-dir": "/tmp/TestSaveSnapshotFilePermissions3637715647/001", "advertise-peer-urls": ["unix://localhost:39938"], "advertise-client-urls": ["unix://localhost:24811"]}
    logger.go:130: 2022-10-06T08:16:40.894+0800 INFO    default closed etcd server      {"name": "default", "data-dir": "/tmp/TestSaveSnapshotFilePermissions3637715647/001", "advertise-peer-urls": ["unix://localhost:39938"], "advertise-client-urls": ["unix://localhost:24811"]}
    logger.go:130: 2022-10-06T08:16:40.894+0800 INFO    default verification of persisted state {"data-dir": "/tmp/TestSaveSnapshotFilePermissions3637715647/001"}
    logger.go:130: 2022-10-06T08:16:40.895+0800 PANIC   default failed to open database {"path": "/tmp/TestSaveSnapshotFilePermissions3637715647/001/member/snap/db", "error": "open /tmp/TestSaveSnapshotFilePermissions3637715647/001/member/snap/db: no such file or directory"}
    logger.go:130: 2022-10-06T08:16:40.895+0800 ERROR   default verification of persisted state failed  {"data-dir": "/tmp/TestSaveSnapshotFilePermissions3637715647/001"}
panic: failed to open database [recovered]
        panic: failed to open database [recovered]
        panic: failed to open database
```

**Comment by xiaods** [comment]
> Looks like the error is `open /tmp/TestSaveSnapshotFilePermissions3637715647/001/member/snap/db: no such file or directory`. Possibly there is a race between opening and removing the file.

use WSL  came across above issue, when switch macos, it run testing with hang out:
```
❯ GOARCH=amd64 CPU=4 PASSES='integration' RACE='false' ./scripts/test.sh
Running with --race=false --cpu=4
Starting at: 日 10  9 23:37:37 CST 2022

'integration' started at 日 10  9 23:37:37 CST 2022
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '-timeout=15m' '--race=false' '--cpu=4' '-p=2' './integration/...')

```
don't know what reason.

**Comment by xiaods** [comment]
running on macos:

```
ok  	go.etcd.io/etcd/tests/v3/integration	541.305s
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3	(cached)
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/concurrency	(cached)
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/connectivity	(cached)
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/examples	(cached)
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/experimental/recipes	(cached)
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/lease	128.768s
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/naming	3.011s
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/snapshot	2.369s
ok  	go.etcd.io/etcd/tests/v3/integration/embed	4.637s
ok  	go.etcd.io/etcd/tests/v3/integration/proxy/grpcproxy	4.002s
ok  	go.etcd.io/etcd/tests/v3/integration/snapshot	19.184s
ok  	go.etcd.io/etcd/tests/v3/integration/v2store	1.041s
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '--tags=integration' '-timeout=15m' '--race=false' '--cpu=4' '-p=2' './common/...')
ok  	go.etcd.io/etcd/tests/v3/common	262.676s
% 'env' 'ETCD_VERIFY=all' 'go' 'test' '-timeout=5m' '--race=false' '--cpu=4' 'go.etcd.io/etcd/v3/contrib/raftexample'
ok  	go.etcd.io/etcd/v3/contrib/raftexample	11.829s
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '-timeout=5m' '--race=false' '--cpu=4' 'go.etcd.io/etcd/tests/v3/integration/v2store')
ok  	go.etcd.io/etcd/tests/v3/integration/v2store	0.990s
'integration' completed at 日 10  9 23:51:24 CST 2022
SUCCESS
```

**Comment by tjungblu** [comment]
I'm taking a look at this right now, but I'm wondering what the purpose of this mutex is:
https://github.com/etcd-io/etcd/blob/7fff4c4241f9ade681f22c7356199f8849479b56/tests/framework/integration/cluster.go#L182

It doesn't actually protect much and virtually every tests directly accesses the Members, while you can also add and remove them. I haven't seen anyone doing this across goroutines, but shall we make this fully thread-safe maybe?

--

Regarding the initial error on the port being in use already...

https://github.com/etcd-io/etcd/blob/7fff4c4241f9ade681f22c7356199f8849479b56/tests/framework/integration/cluster.go#L617-L639

Do you think we should instead pick a random port from a range, then test if we can listen on it and retry if not? The counting logic works well within that integration suite, not sure if there's potentially something else running that can conflict.

**Comment by serathius** [comment]
Ad 1, depends on what you have in mind. I think the overall expectation is tests frameworks to be thread safe. For example creating a watch on main routing and creating goroutine to send updates in background. Especially when there are plans to extend it to support adding/removing members during test. 

My suggestion would be to evolve integration framework in direction of common framework interface https://github.com/etcd-io/etcd/blob/main/tests/framework/interface.go

Ad 2
This code was to mitigate exactly the same problem with port collision that also happen by picking random port. I hoped that having a global counter for port number will help that, unfortunately I didn't know that `go test` runs separate process per each directory. As result the counter gets reset for each directory, so there can be a race between old test shutdown and new test start.

Best option here would be to delegate picking random port to OS. You can do that by binding port `0` (for example `127.0.0.1:0`) as result you will get random port. Main downside of this approach is that you don't know the port a priori and need to parse it. It's even more complicated to pass this port to etcd without rebinding it. For
* integration test we might create listener and pass it down to the server instance
* e2e test we could try to utilize SO_REUSEPORT, however I don't have much experience with using it. It might also result in tests being harder to port to other OS.

**Comment by tjungblu** [comment]
Thanks for the input. 

> Best option here would be to delegate picking random port to OS. You can do that by binding port 0 (for example 127.0.0.1:0) as result you will get random port. 

Yeah I was trying this out as a first option instead of generating a random integer. I'll fix the remaining tests and will send a PR for that, I reckon we can discuss further on that.

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/etcd/pull/14585
