### ISSUE TITLE
etcd/proxy/grpcproxy imports google.golang.org/grpc/naming which is a deprecated module

### ISSUE THREAD

**Issue by sujeet01** [etcd-io/etcd#14580]
### What happened?

My project makes use of `github.com/coreos/etcd/proxy/grpcproxy` package which imports `google.golang.org/grpc/naming` package which is deprecated after version v1.29.0 of `google.golang.org/grpc`

### What did you expect to happen?

I need to use the latest version of `google.golang.org/grpc` > v1.40.0 which does not contain a deprecated `google.golang.org/grpc/naming` package used by `github.com/coreos/etcd/proxy/grpcproxy`

### How can we reproduce it (as minimally and precisely as possible)?

Run https://github.com/rexray/gocsi#quick-start

### Etcd version (please run commands below)

v3.3.13

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
go: finding module for package google.golang.org/grpc/naming
        github.com/rexray/gocsi imports
        github.com/rexray/gocsi/middleware/serialvolume/etcd imports
        github.com/coreos/etcd/clientv3 tested by
        github.com/coreos/etcd/clientv3.test imports
        github.com/coreos/etcd/integration imports
        github.com/coreos/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.50.0), but does not contain package google.golang.org/grpc/naming
```

**Comment by ahrtr** [comment]
3.3.x is already out of support, so could you upgrade to 3.4 firstly and then to 3.5?

**Comment by sujeet01** [comment]
> 3.3.x is already out of support, so could you upgrade to 3.4 firstly and then to 3.5?

When I try to go get any of these versions, I get following error

**Comment by sujeet01** [comment]
> 3.3.x is already out of support, so could you upgrade to 3.4 firstly and then to 3.5?

When I try to go get any of these versions, I get the following error <br> `go get github.com/coreos/etcd@v3.5.5` <br>`go: github.com/coreos/etcd@v3.5.5: invalid version: go.mod has post-v3 module path "go.etcd.io/etcd/v3" at revision v3.5.5`

**Comment by sujeet01** [comment]
> 3.3.x is already out of support, so could you upgrade to 3.4 firstly and then to 3.5?

I still get the same error after upgrading to v3.5.5 <br> `
go: finding module for package google.golang.org/grpc/naming
        github.com/rexray/gocsi imports
        github.com/rexray/gocsi/middleware/serialvolume/etcd imports
        github.com/coreos/etcd/clientv3 tested by
        github.com/coreos/etcd/clientv3.test imports
        github.com/coreos/etcd/integration imports
        github.com/coreos/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.50.0), but does not contain package google.golang.org/grpc/naming
`

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/modules.md

**Comment by antboard** [comment]
new version import is  	"go.etcd.io/etcd/client/v3" not 	"go.etcd.io/etcd/clientv3"

**Comment by bingochen87** [comment]
Get the same error for this. So how to fix it?
