### ISSUE TITLE
Put requests should be able to go thru when there is space in freelist

### ISSUE THREAD

**Issue by geetasg** [etcd-io/etcd#14598]
### What would you like to be added?

As of today , etcd evaluates available space using Size api of backend storage layer - https://github.com/etcd-io/etcd/blob/main/server/storage/quota.go#L133
This should be changed to evaluate using SizeInUse api because the space in freelist can be utilized without increasing the db file size.

### Why is this needed?

We have environments that hit no space quota. If the quota evaluation is done based on SizeInUse, put requests will be able to get in after compaction. The put requests need not wait for defrag (which is operator driven operation).  This will help enable a self service experience to bounce back from no space condition.

Listing additional related requests for completeness -
Related - As of today, compaction cannot run under no space either - related - https://github.com/etcd-io/etcd/issues/14595

**Comment by geetasg** [comment]
This is created as a feature request because this can perhaps be added with a new flag. When flag is not enabled, current behavior (to use Size() api) will be preserved.

**Comment by microyahoo** [comment]
Hi @geetasg, I think there is also a problem with changing `Size` to `SizeInUse`. When boltdb allocates space, it needs continuous free pages, and there may not be enough continuous space for allocation, which will cause the database to be remapped, thereby expanding the capacity.
