### ISSUE TITLE
Provide a gRPC alternative of HTTP's `/version` API

### ISSUE THREAD

**Issue by spacewander** [etcd-io/etcd#14599]
### What would you like to be added?

There is a version API in HTTP part which returns the `server` / `cluster` / `storage` versions:
https://github.com/etcd-io/etcd/blob/main/server/etcdserver/api/etcdhttp/version.go

It seems there is no corresponding API in the gRPC part.
The closest one I found is the `Maintenance.Status` API:
https://github.com/etcd-io/etcd/blob/e24402d39fd08ebca46beeb1f16d214e37fea74f/api/etcdserverpb/rpc.proto#L1140
https://github.com/etcd-io/etcd/blob/e24402d39fd08ebca46beeb1f16d214e37fea74f/server/etcdserver/api/v3rpc/maintenance.go#L228

But it doesn't have the cluster version field.

### Why is this needed?

By providing the gRPC alternative of HTTP's `/version` API, we can access all the features of etcd via gRPC connection, without using an extra HTTP client.

**Comment by ahrtr** [comment]
The cluster version is actual the minimal member version. Users/Client can easily get the clusterVersion themselves from the response of endpoint status (see example below).


```
$ ./etcdctl endpoint status -w table --cluster
+------------------------+------------------+---------------+-----------------+---------+----------------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT        |        ID        |    VERSION    | STORAGE VERSION | DB SIZE | DB SIZE IN USE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------+------------------+---------------+-----------------+---------+----------------+-----------+------------+-----------+------------+--------------------+--------+
|  http://127.0.0.1:2379 | 8211f1d0f64f3269 | 3.6.0-alpha.0 |           3.6.0 |   25 kB |          25 kB |      true |      false |         2 |          8 |                  8 |        |
| http://127.0.0.1:22379 | 91bc3c398fb3c146 | 3.6.0-alpha.0 |           3.6.0 |   25 kB |          25 kB |     false |      false |         2 |          8 |                  8 |        |
| http://127.0.0.1:32379 | fd422379fda50e48 | 3.6.0-alpha.0 |           3.6.0 |   25 kB |          25 kB |     false |      false |         2 |          8 |                  8 |        |
+------------------------+------------------+---------------+-----------------+---------+----------------+-----------+------------+-----------+------------+--------------------+--------+
```

**Comment by spacewander** [comment]
I read the source code of `etcdctl endpoint status`. It is implemented in two steps:
1. call `Cluster.MemberList` to get all endpoints
2. For each endpoint, call `Maintenance.Status` to get its version. The cluster version is the min of the versions

It works but isn't perfect in my case. Previously we only need an HTTP call, but now in gRPC we need N+1 call (N is the num of endpoints).

If permitted, I can implement a separate `Version` rpc call in `Maintenance` service. What do you think about it?

**Comment by ahrtr** [comment]
Instead of adding a new API, enhancing the existing Maintenance.Status might be make more sense. 

Could you elaborate why do you need the `clusterVersion` value or how will you use the value in your application?

**Comment by spacewander** [comment]
> Could you elaborate why do you need the clusterVersion value or how will you use the value in your application?

I use the `clusterVersion` as the heartbeat of the etcd cluster to monitor their status. It would be better to make this operation cheap enough for the heartbeat use case. Replacing `clusterVersion` to `Version` is not so perfect to me as I can't guarantee the node in the etcd cluster only uses the same version.

**Comment by ahrtr** [comment]
OK. We can either add a separate gRPC API which is similar to the `/version` HTTP endpoint, or enhance the `Maintenance.Status` to add one more field `clusterVersion`. Personally I prefer to the latter.

**Comment by kjin97** [comment]
A use case that I've seen is fairly specific, but this is a case where we've had to resort to the HTTP API when we're using grpc for everything else -- when a node goes unhealthy during a rolling etcd upgrade, it would be helpful to know what version the cluster is on, so that we can start a new node to replace the unhealthy member at that version.

The proposed method to call MemberList, then Maintenance.Status on each individual member fails when some of the members are unreachable. In these cases, instead of guessing at what the unhealthy member's version based on the rest of the cluster, we've been relying on the cluster's internal understanding of its version -- which is only accessible via the HTTP API.
