### ISSUE TITLE
Is it feasible to migrate functional test cases to Jepsen?

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#14606]
### What would you like to be added?

Created a quick proposal [outline](https://docs.google.com/document/d/1qX7VNwZbtiEDUSXrlC3QjuZJfLzwL7bRLcVnKXmKsow/edit). 

This is not well flushed out idea, but would like to get feedback if this is worth evaluating.

Let me know if more investigation needed.

### Why is this needed?

No new test cases were added to internal framework since original work in 2018
Less framework code to maintain
Community relies on running Jepsen tests to verify releases

**Comment by lavacat** [comment]
cc @endocrimes

**Comment by serathius** [comment]
This duplicates https://github.com/etcd-io/etcd/issues/14045
