### ISSUE TITLE
Leases are not revoked when JWT authentication enabled

### ISSUE THREAD

**Issue by michoello** [etcd-io/etcd#14616]
### What happened?

When ETCD is configured to run with JWT authentication specifying public key only, the keys under leases stay alive indefinitely.

When auth token is configured with `--auth-token=jwt,pub-key=jwt_cert.pem,sign-method=ES256,ttl=5m` with no `priv-key` specified, the keys created under lease are not revoked after their TTL is expired.

### What did you expect to happen?

Temporary keys are deleted automatically when their TTL expired.

### How can we reproduce it (as minimally and precisely as possible)?

The auth token is configured with `--auth-token=jwt,pub-key=jwt_cert.pem,sign-method=ES256,ttl=5m`

* Run etcd with `--auth-token=jwt,pub-key=jwt_cert.pem,sign-method=ES256,ttl=5m` argument
*
```
# Enable auth
etcdctl auth enable

# Create lease
etcdctl lease grant 10
lease abcdef12345 granted with TTL(10s)

# Create key with the lease
etcdctl put foo1 bar1 --lease=abcdef12345

# Wait 10+ seconds

# Check the key
etcdctl get foo1
foo1
bar1
```
The key is alive

### Anything else we need to know?

The root cause can be the following:
* as the `priv-key` is not configured, the internal [verifyOnly](https://github.com/etcd-io/etcd/blob/main/server/auth/jwt.go#L33) flag is set to true
* [revokeExpiredLease](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/server.go#L877) method attempts to [sign](https://github.com/etcd-io/etcd/blob/3b8b432b23a85ad3470aa8d760165983221c5f34/server/auth/store.go#L1161) `root` token to delete the keys, but fails because see above.

One of possible solutions is a local update to `jwt.go` and `options.go` that would do the following:
* use configured `--key-file` arg to sign `root` token in `revokeExpiredLease` method
* extend `tokenJwt` to be able to use several [keys](https://github.com/etcd-io/etcd/blob/main/server/auth/jwt.go#L31) for Jwt token verification

Example command line:
```
etcd \
... \
--key-file=etcd-key.pem \
--cert-file=etcd-cert.pem \
--auth-token=jwt,pub-key=jwt_cert.pem,priv-key=etcd-key.pem,sign-method=ES256,ttl=5m
```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
API version: 3.5

$ etcdctl version
etcdctl version: 3.5.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

`--auth-token=jwt,pub-key=jwt_cert.pem,sign-method=ES256,ttl=5m` 

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
16:36:39.721428 {"level":"error","ts":"2022-10-24T16:36:39.721Z","caller":"auth/store.go:1280","msg":"failed to assign token for lease revoking","error":"auth: token signing attempted with verify-only key","stacktrace":"
  server/v3/auth.(*authStore).WithRoot
    auth/store.go:1280
  server/v3/etcdserver.(*EtcdServer).revokeExpiredLeases.func1.1.1
    etcdserver/server.go:1154
  server/v3/etcdserver.(*EtcdServer).GoAttach.func1
    etcdserver/server.go:2746
"}

16:36:39.721621 {"level":"warn","ts":"2022-10-24T16:36:39.721Z","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"20.344µs","request":"header:<ID:3145909521866627899 > lease_revoke:<id:2ba8840ada611b2e>","response":"","error":"auth: user name is empty"}

16:36:39.721626 {"level":"warn","ts":"2022-10-24T16:36:39.721Z","caller":"etcdserver/server.go:1159","msg":"failed to revoke lease","lease-id":"2ba8840ada611b2e","error":"auth: user name is empty"}
```

**Comment by ahrtr** [comment]
You must provide a private key in this case. It may be incorrect to use other private key to generate the token, because the public key should match the private key. cc @mitake

**Comment by mitake** [comment]
Thanks for reporting @michoello . I think etcd shouldn't accept such an argument and cause error during  initialization phase. What do you think?

**Comment by michoello** [comment]
As of today yes, etcd will fail if both `priv-key` and `pub-key` are provided, but are not a pair, thanks to [this check](https://github.com/etcd-io/etcd/blob/main/server/auth/options.go#L148).

Afer that, if the keys match, `pub-key` is never used.
But if `priv-key` is not provided, then lease revoke does not work.

It will be more consistent if etcd allows unrelated `priv-key` and `pub-key`, or use etcd main key (provided by `--key-file` argument) to sign the root token in [revokeExpiredLease](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/server.go#L877).

**Comment by ahrtr** [comment]
> As of today yes, etcd will fail if both `priv-key` and `pub-key` are provided, but are not a pair, thanks to [this check](https://github.com/etcd-io/etcd/blob/main/server/auth/options.go#L148).
> 
> Afer that, if the keys match, `pub-key` is never used. But if `priv-key` is not provided, then lease revoke does not work.
> 

Yes, it's true. 

> My suggestion is to allow unrelated `priv-key` and `pub-key`, or use the main key `--key-file` to sign the root token in [revokeExpiredLease](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/server.go#L877).

I would suggest to rethink the JWT authentication design & implementation. cc @mitake @serathius @ptabor @spzala

**Comment by mitake** [comment]
@ahrtr Got it, let me check that. But for a while it will be hard for me to allocate bandwidth for this issue...
@michoello Could you try CommonName based authentication as a workaround?

**Comment by yishuT** [comment]
The problem we are solving is that we want to put a proxy between clients and etcd. However, we don't want to create etcd client per user in the proxy process. Therefore, we use certs manager to sign jwt token so that clients can pass the token in the request context.
