### ISSUE TITLE
There is a bug in function NewMaintenance of  client/v3/maintenance.go

### ISSUE THREAD

**Issue by new-dream** [etcd-io/etcd#14619]
### What happened?

Won't close connection when net meets problem and cause memory leak.

### What did you expect to happen?

The connection should be closed.

### How can we reproduce it (as minimally and precisely as possible)?

call NewMaintenance in your own code and do some net chaos.

### Anything else we need to know?

err = c.getToken(dctx)
	cancel()
	if err != nil {
		 **_conn.Close()_**
		return nil, nil, fmt.Errorf("failed to getToken from endpoint %s with maintenance client: %v", endpoint, err)
	}
	cancel = func() { conn.Close() }
	return RetryMaintenanceClient(c, conn), cancel, nil

conn need to close here.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>
3.5.4

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by tjungblu** [comment]
How are you using the client? You can close the underlying dial by terminating the whole client:

```
	v3c := v3client.New(s)
        defer v3c.Close()
	v3c.Defragment(...)
	
```

**Comment by ahrtr** [comment]
Already fixed in https://github.com/etcd-io/etcd/pull/14635
