### ISSUE TITLE
[test] Enhance (*ExpectProcess) ExpectFunc

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14638]
### What would you like to be added?

Please read https://github.com/etcd-io/etcd/pull/14574/files#r1007427389

### Why is this needed?

See link above

**Comment by serathius** [comment]
+1 for short running commends like etcdctl we should wait till commands exits instead of waiting for specific log.

**Comment by tjungblu** [comment]
prepared something in https://github.com/etcd-io/etcd/pull/14672, let me know what you guys think.

**Comment by halegreen** [comment]
@tjungblu hi, are you still working on this ?

**Comment by tjungblu** [comment]
yep, I'm busy with some downstream work for the next couple of days, but I pick it up again on Thursday.

**Comment by ahrtr** [comment]
Completed in https://github.com/etcd-io/etcd/pull/14672
