### ISSUE TITLE
A way to view all the prefixes in the etcd cluster.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [etcd-io/etcd#14645]
### What would you like to be added?

Ideally, a command line argument like `etcdctl get prefixes --all`.

### Why is this needed?

I noticed that it's not quite trivial to have detailed information about whatever is stored in my etcd cluster db. Although it is highly possible that I feel so because of my unfamiliarity with etcd/etcdctl.

I realized a need for this when I was playing around with my local kubernetes cluster trying to understand how kubernetes stores key-value pairs in etcd. So I decided to query all the keys (and their values) like so:

`etcdctl get a z` # get all keys lexicographically ranging from a to z. But this did not yield the expected result not sure why.

So if there was a way to look for all the prefixes in the db. I think it would be pretty neat, mostly because a user won't know how the different components (mostly kubernetes and internal implementation of etcd) are interacting with etcd, and in which different prefixes they are storing their keys.

**Comment by shreemaan-abhishek** [comment]
I would be more than happy to work on this issue with some guidance from the maintainers. I am totally new to the etcd codebase.

**Comment by lavacat** [comment]
Try this command `etcdctl get "" --prefix --keys-only`.
