### ISSUE TITLE
`campagin` maybe stuck, when send SIGSTOP to etcd server leader

### ISSUE THREAD

**Issue by zeminzhou** [etcd-io/etcd#14641]
### What happened?

[`campagin` ](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/election.go#L69)maybe stuck, when send SIGSTOP to etcd server leader

### What did you expect to happen?

`campagin` should return

### How can we reproduce it (as minimally and precisely as possible)?

1. startup 3 etcd servers
2. startup process to run 2 etcd client to campagin
3. send SIGSTOP(kill -19) to etcd servers' leader
4.  the proecss which is not leader will stuck(If not, repeat step 3)

### Anything else we need to know?

Wather https://github.com/etcd-io/etcd/blob/main/client/v3/watch.go#L53 &&
Issue https://github.com/etcd-io/etcd/issues/8980

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
v3.5.2

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
This might be expected behavior. When you start the etcdserver, can the client continue to work?

**Comment by ahrtr** [comment]
Duplicate to https://github.com/etcd-io/etcd/issues/14631

**Comment by zeminzhou** [comment]
> This might be expected behavior. When you start the etcdserver again, can the client continue to work?

Yesh, when I start etcdserver again, the client will continue to work.

**Comment by zeminzhou** [comment]
> This might be expected behavior. When you start the etcdserver again, can the client continue to work?
Is this as expected? I think campagin should return

**Comment by zeminzhou** [comment]
> This might be expected behavior. When you start the etcdserver again, can the client continue to work?

And I don't think this is a `expected behavior`. Because `campagin` can't return even if `cancel` is called or timeout when etcd server leader was SIGSTOP.
