### ISSUE TITLE
A way to watch events stream on leases.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [etcd-io/etcd#14654]
### What would you like to be added?

Something like this: `etcdctl watch --lease <name>`

### Why is this needed?

Because, why not? This would show consistency in the functionality for the command line tool. Not having a `watch` feature for a dynamic entity like `lease` does not make sense to me.

Again, I would be more than happy to contribute this feature with some guidance from the maintainers.

**Comment by serathius** [comment]
> Because, why not?

Because it would require a lot of work with no benefit.
