### ISSUE TITLE
Automatically use latest golangci-lint tool

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#14670]
### What would you like to be added?

https://github.com/etcd-io/etcd/blob/5073af65210397012e85abfa9c7cd24777cf443f/.github/workflows/static-analysis.yaml#L14 - here we see the version is out of date (v.1.50.1 is latest - https://github.com/golangci/golangci-lint/releases)

Can we always use the latest version so requires less maintenance.

### Why is this needed?

Simplifies the build process, makes it more robust.

**Comment by serathius** [comment]
Picking latest introduces a risk of getting unrelated failures on PR. I'm more for reproducability of runs. I think that sending a PR that bumps a version is not big cost.  

> Simplifies the build process, makes it more robust.

Don't agree with that. It makes CI process hard to predict or reproduce.

**Comment by vivekpatani** [comment]
Versions will keep lagging if we pin it to a specific version. It’s a linter, imagine this to pretty benign.

Feel free to close the issue if you feel otherwise.

**Comment by vivekpatani** [comment]
@serathius I think https://github.com/dependabot is a much better solution/extensible. Appreciate the feedback, can we just enable that, and then define a ruleset around it? I can assist if that is something the community is interested in? Thanks. CC: @ahrtr

**Comment by ahrtr** [comment]
Basically I agree with @serathius . Please feel free to deliver a PR to bump the version to 1.50.1, and we can discuss any other topics (e.g `dependabot`) separately.

**Comment by vivekpatani** [comment]
@ahrtr understood. Will deliver by the weekend at most.

**Comment by vivekpatani** [comment]
https://github.com/etcd-io/etcd/issues/14673
