### ISSUE TITLE
Benchmark Tool Error- grpc: addrConn.createTransport failed

### ISSUE THREAD

**Issue by PoojaGidaveer** [etcd-io/etcd#14679]
### What happened?

Hi,

I am trying to execute performance Tests for etcd. 
Tool Used- benchmark 

Test Execution-
1. deployed the benchmark pod of image- `fangruo/etcd-benchmark:1.0`
2. Ssh into the benchmark-pod and executed below command
`benchmark --endpoints={HOST_IP} --sample=true --conns=100 --clients=1000 put --key-size=256 --sequential-keys --total=400 --val-size=1024`

Instead of putting the keys into etcd DB. i am getting below error-
`INFO: 2022/11/02 09:55:21 parsed scheme: "endpoint"
INFO: 2022/11/02 09:55:21 ccResolverWrapper: sending new addresses to cc: [{http://HOST_IP:2379 HOST_IP:2379 <nil> 0 <nil>}]
WARNING: 2022/11/02 09:56:47 grpc: addrConn.createTransport failed to connect to {http://HOST_IP:2379 HOST_IP:2379 <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp HOST_IP:2379: i/o timeout". Reconnecting...`

### What did you expect to happen?

keys added to etcd

### How can we reproduce it (as minimally and precisely as possible)?

Run the above benchmark command

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.13
Git SHA: ae9734ed2
Go Version: go1.12.17
Go OS/Arch: linux/amd64

$ etcdctl version
# etcdctl version: 3.4.13
API version: 3.4
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
We don't support `fangruo/etcd-benchmark:1.0`

**Comment by serathius** [comment]
Recommend figuring out why `http://HOST_IP:2379` is not a proper address.
