### ISSUE TITLE
Use StringVar instead of DurationVar

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#14671]
### What happened?

When used with other orchestration systems, the `StringVar` is much more versatile than a `DurationVar`.

```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field configYAML.experimental-corrupt-check-time of type time.Duration
```

### What did you expect to happen?

For variable to be parsed.

### How can we reproduce it (as minimally and precisely as possible)?

Run it with a build system that uses JSON conversion.

### Anything else we need to know?

Can Deliver PR.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# 3.5

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field configYAML.experimental-corrupt-check-time of type time.Duration
```

**Comment by tjungblu** [comment]
Can you be a bit more specific on what you're doing?
I read that you create a etcd config using JSON and then it chokes on the `experimental-corrupt-check-time` converting to yaml?

**Comment by vivekpatani** [comment]
Sorry, my point being, if you use a build system like [Puppet](https://github.com/puppetlabs/puppet), it is practically impossible to pass a DurationVar, since puppet (or for the most part other build/config management systems too) doesn’t have context of this specific type of variable and is a Golang construct only.


My proposal is to use a simple StringVar to make it easier to work with such build/config management systems and then internally convert it to a DurationVar after accepting the use input via flags/environment variable.


Let me know if I need to add more context please. Thank you.

**Comment by tjungblu** [comment]
Could you please specify what Puppet outputs and how you run etcd here? I think it would make it easier to understand.
The DurationVar will just parse a string using [time.ParseDuration](https://pkg.go.dev/time#ParseDuration), so what prevents you from passing that from Puppet?

**Comment by ahrtr** [comment]
Please let me know whether the [workaround](https://github.com/ahrtr/etcd-issues/tree/master/issues/13480) works for you.

**Comment by vivekpatani** [comment]
Couldn't have put it in better words, thanks @ahrtr, I was just working on providing a config, but this makes sense in a much more intuitive way, and is more generalised as a solution.

**Comment by ahrtr** [comment]
Good to know it works for you.

**Comment by vivekpatani** [comment]
@ahrtr If I understand the CLI will still fail after this
```
Running etcd-3.5
./bin/etcd --log-level debug --experimental-corrupt-check-time "40000000000"
invalid value "40000000000" for flag -experimental-corrupt-check-time: parse error
```
Was the solution you suggested work only when parsing via JSON?

I'm going to try it for that, but this seems inconsistent. Can you please tell me, if I doing something wrong? Thanks.

**Comment by ahrtr** [comment]
> Was the solution you suggested work only when parsing via JSON?

Yes.  CLI supports format something like "40s", but JSON doesn't.

**Comment by vivekpatani** [comment]
So the scenarios here seem a little bit complicated (maybe?).

CLI
- Doesn't support raw numbers, need to pass a unit of time.


JSON
- Supports raw numbers, but not units.
 

While I understand this is a `golang` expected behavior, it seems to be confusing to some extent.

**Comment by ahrtr** [comment]
I think applications need to take care of this difference for now.  For this specific example, you need to pass "40" to CLI, while put `40000000000` in config file for JSON to unmarshal.

**Comment by vivekpatani** [comment]
> I think applications need to take care of this difference for now. For this specific example, you need to pass "40" to CLI, while put 40000000000 in config file for JSON to unmarshal.

I think you meant
"40s" - CLI
"40000000000" - JSON

I think I get your point, my point was just that, instead of having to accept a `DurationVar`, we should instead accept a `StringVar` to standardise it, instead of having it this way. I don't have a strong preference either way.

**Comment by ahrtr** [comment]
It might make some sense. 

## Proposal
The rough proposal is to change all user facing duration parameters to string, and etcd uses [time.ParseDuration](https://github.com/golang/go/blob/go1.19.2/src/time/format.go#L1522) to parse the value. If it's a integer (no unit, e.g. `40`), then it defaults to seconds. 

## Pros
This solution has no any impact on existing users, so it should be safe. The only benefit is that it makes the configuration between CLI and config-file consistent. 

## Cons
It needs some non-trivial effort, and complicates the implementation. Are there any potential risks which I miss? 

## Approaches
1. Keep it as it's. Applications take care of it, just as I mentioned above https://github.com/etcd-io/etcd/issues/14671#issuecomment-1299295437.  @vivekpatani does that need big effort for you to do this? Or how easy or difficult is the task? 
2. Enhance etcd per the proposal in this comment. The concern is whether the benefit worth the cost.

cc @mitake @ptabor @serathius @spzala thoughts?

**Comment by vivekpatani** [comment]
Thank you for the @ahrtr.

> Keep it as it's. Applications take care of it, just as I mentioned above https://github.com/etcd-io/etcd/issues/14671#issuecomment-1299295437. @vivekpatani does that need big effort for you to do this? Or how easy or difficult is the task?

@ahrtr can do a little bit of recon work to figure out how involved the task will be, while we debate if this needs to be done.

**Comment by tjungblu** [comment]
> Yes. CLI supports format something like "40s", but JSON doesn't.

@ahrtr so you're saying that go's encoding/json has troubles with parsing this:

```
{  "time": "20m" }
```

into a struct like this?

```
type x struct {
	Time time.Duration `json:"time,omitempty"`
}
```

**Comment by ahrtr** [comment]
Right, FYI. 

- [https://github.com/ahrtr/etcd-issues/blob/master/issues/13480/main.go](https://github.com/ahrtr/etcd-issues/blob/master/issues/13480/main.go)
- [https://github.com/ahrtr/etcd-issues/tree/master/issues/13480](https://github.com/ahrtr/etcd-issues/tree/master/issues/13480)

**Comment by tjungblu** [comment]
We could also wrap the `time.Duration` into our own type that parses the JSON correctly, eg like described here: https://robreid.io/json-time-duration/

**Comment by ahrtr** [comment]
It also needs to convert the user-facing parameter to `string`. What you suggested is the detailed implementation after converting the user-facing parameter from `time.Duration` to `string`.

**Comment by ahrtr** [comment]
We need to define a type to implement the following interfaces, so that it can elegantly process both command-line parameter parsing and JSON/YAML parsing. 

- [flag.Value](https://github.com/golang/go/blob/81efd7b347dd6d7f12fd49c6eee0274005734c71/src/flag/flag.go#L350)
- [json.Marshaler](https://github.com/golang/go/blob/81efd7b347dd6d7f12fd49c6eee0274005734c71/src/encoding/json/encode.go#L223)
- [json.Unmarshaler](https://github.com/golang/go/blob/81efd7b347dd6d7f12fd49c6eee0274005734c71/src/encoding/json/decode.go#L119)

**Comment by ahrtr** [comment]
FYI.
[uint32](https://github.com/etcd-io/etcd/blob/main/pkg/flags/uint32.go) implements `flag.Value`.
The [link](https://robreid.io/json-time-duration/) you provided is a good example on `json.Marshaler` and `json.Unmarshaler`.
