### ISSUE TITLE
ETCDCTL_API=3 etcdctl member list - getsockopt: connection refused

### ISSUE THREAD

**Issue by kavita1205** [etcd-io/etcd#14680]
### What happened?

Hi Team,

When I am running this command , I am getting below error.

$ETCDCTL_API=3 etcdctl member list                                            
Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused

Can someone help me how can we fix this.

### What did you expect to happen?

This command should run and provide me member list.

### How can we reproduce it (as minimally and precisely as possible)?

Run this command for etcdctl

etcdctl --version
etcdctl version: 3.2.18
API version: 2

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcdctl version: 3.2.18
API version: 2

$ etcdctl version
# paste output here
```
etcdctl version: 3.2.18
API version: 2

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
` 3.2.18` is no longer supported.
