### ISSUE TITLE
raft: use testify package in unit tests

### ISSUE THREAD

**Issue by pavelkalinnikov** [etcd-io/etcd#14709]
### What would you like to be added?

Use `github.com/stretchr/testify/require` and `github.com/stretchr/testify/assert` packages in all unit tests.

Demo PR: #14708

### Why is this needed?

This removes much boilerplate from the tests, and improves speed and quality of understanding and modifying them.

**Comment by serathius** [comment]
@falser101 I think the issue is already worked on. https://github.com/etcd-io/etcd/pull/14708

**Comment by serathius** [comment]
Closed by https://github.com/etcd-io/etcd/pull/14708

**Comment by pavelkalinnikov** [comment]
This is not done, there will be a few commits making more tests to take advantage of this package, notably `raft_test.go`.
