### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by cjl7** [etcd-io/etcd#14700]
### What happened?

reading the docs I found that etcdctl was typo:ed to etcdutl.

Link: https://etcd.io/docs/v3.5/op-guide/recovery/#restoring-a-cluster

First paragraph, second sentence.

### What did you expect to happen?

N/A

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

Nothing that stopped me of course, just trying to help keep things stellar! (thanks for the awesome product!)

### Etcd version (please run commands below)

3.5

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by spzala** [comment]
It's not a typo, `etcdutl` is a relatively new utility. You can read more here - https://github.com/etcd-io/etcd/tree/main/etcdctl#snapshot-restore-options-filename Closing but please feel free to reopen if I misunderstood issue. Thanks!
