### ISSUE TITLE
Implement remaining gofailpoints in linearizability tests

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#14726]
### What would you like to be added?

This is followup to https://github.com/etcd-io/etcd/pull/14687 that introduced triggering random failpoint.
Failpoints are injected by sending http request to modified etcd server that will panic on when it reaches specific part of code. 
Problem is that some failpoints will not be naturally triggered and require additional action to server to reach the code. For example  `defragBeforeCopy` and `defragBeforeRename` require starting a Defrag. 

There are still failpoints that require implementing their triggers. Goal of this issue is to implement triggers for failpoints and adding them to `RandomFailpoint` which is used by automated testing. Code: https://github.com/etcd-io/etcd/blob/main/tests/linearizability/failpoints.go#L33-L53

Failpoints to be implemented:
* [x] `etcdserver/raftBeforeLeaderSend` (@serathius, https://github.com/etcd-io/etcd/pull/14752)
* [x] `etcdserver/raftBeforeApplySnap`
* [x] `etcdserver/raftAfterApplySnap`
* [x] `etcdserver/raftAfterWALRelease`
* [x] `etcdserver/raftBeforeFollowerSend`
* [x] `etcdserver/raftBeforeSaveSnap`
* [x] `etcdserver/raftAfterSaveSnap`

### Why is this needed?

Increases the coverage of linearizability tests.

**Comment by lavacat** [comment]
@serathius please assign this to me. I'm already working on all `Snap` endpoints. The way to reproduce is outlined here https://github.com/etcd-io/etcd/issues/10219.
I got it working within current framework using trigger hook, but sometimes it's flaky. Will submit draft pr after it's passing consistently.

**Comment by jmhbnz** [comment]
Hey @serathius, @lavacat - Can this one be closed now?

I'm looking at the list of tasks on the issue and to me it looks like #15104 and #15268 completed all these tasks?

**Comment by serathius** [comment]
Yep, looks like we are done!
