### ISSUE TITLE
etcd server causes goroutine leak if client v2 is used

### ISSUE THREAD

**Issue by pnhoang75** [etcd-io/etcd#14745]
### What happened?

After embed.Etcd Server closes, there are goroutines leaks if client v2 is used.  No leak if client v3 is used because client v3 has "Close()" function.

### What did you expect to happen?

After embed.Etcd server closes, all goroutines should terminate.

### How can we reproduce it (as minimally and precisely as possible)?

Step to reproduce:
- Create embed.Etcd server with embed.StartEtcd.
- Create client v2 and its KeysAPI then use it to call Get.
- After that, close the Etcd server.
==> goleak detect 3 goroutine leaks including http.Server.Serve.   This also cause the etcd server hold on to the client port which makes subsequence use of the same client port failed.

Note that this behavior is only for client v2.  If I use client v3, it comes with Close() and when I call client v3 Close() before the end of the function, no leaks detected.  I cannot find the same Close() function in client v2 API.  Not sure if this is a known issue of client v2 or there is a workaround in client v2 to help clean up all of these goroutines.

 func TestEmbedEtcd(t *testing.T) {
	defer goleak.VerifyNone(t, goleak.IgnoreTopFunction("github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop"))
	scp := scope.NewTestScope(t)
	defer scp.Shutdown()
	
	peerURL, err := url.Parse("http://[localhost]:34532")
	assert.NilError(t, err)
	clientEndpoint := "http://[localhost]:34533"
	clientURL, err := url.Parse(clientEndpoint)
	assert.NilError(t, err)
	cfg := embed.NewConfig()
	cfg.Name = "testEmbedEtcd"
	cfg.Dir = t.TempDir()
	cfg.TickMs = 10
	cfg.ElectionMs = 100
	cfg.APUrls = []url.URL{*peerURL}
	cfg.LPUrls = []url.URL{*peerURL}
	cfg.ACUrls = []url.URL{*clientURL}
	cfg.LCUrls = []url.URL{*clientURL}
	cfg.InitialCluster = fmt.Sprintf("testEmbedEtcd=%s", peerURL.String())
	cfg.Debug = true
	cfg.LogPkgLevels = "DEBUG"
	cfg.EnableV2 = true
	e, err := embed.StartEtcd(cfg)
	assert.NilError(t, err)
	defer e.Close()
	config := clientv2.Config{
		Endpoints:     []string{clientEndpoint},
		SelectionMode: clientv2.EndpointSelectionPrioritizeLeader,
	}
	client, err := clientv2.New(config)
	assert.NilError(t, err)
	kapi := clientv2.NewKeysAPI(client)
	_, err = kapi.Get(scp.Ctx(), "/", &clientv2.GetOptions{
		Sort:      true,
		Recursive: true,
		Quorum:    true})
	assert.NilError(t, err)
}

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
clientv2 has already been deprecated. Is there any case clientv3 can't satisfy your requirement?

**Comment by pnhoang75** [comment]
We are migrating away from client v2.  Client v3 works for us.
We just want to know whether this is a known issue and there is any workaround for it in client v2.
