### ISSUE TITLE
T1 support for Arm64 

### ISSUE THREAD

**Issue by kevinzs2048** [etcd-io/etcd#14748]
### What would you like to be added?

Support Arm64 as the stable release.

### Why is this needed?

According to upstream's website (https://etcd.io/docs/v3.3/op-guide/supported-platform/), the Arm64 is not classed as a stable architecture.

There are many the Kubernetes cluster running on Arm64 and already use Arm64 etcd for quite a lot time, but some users are a little concerned, since the ETCD on Arm64 is not sanctioned by upstream. E.g, Etcd works quite well on Arm64 and there are still some blog recording this, like this [ETCD optimization doc on Arm64](https://community.arm.com/arm-community-blogs/b/infrastructure-solutions-blog/posts/improve-etcd-performance-by-18-percent-by-deploying-on-aws-graviton2).

We are from [Linaro](https://www.linaro.org/) and our targeting is to enrich the Arm64 open source ecosystem. Actually from the Arm ecosystem, we do have several companies raise this topic and we do want to see if there is some gaps/TODO we can do for ETCD to support Arm64 as the stable release.

**Comment by serathius** [comment]
Please read https://etcd.io/docs/v3.6/op-guide/supported-platform/#supporting-a-new-platform

**Comment by kevinzs2048** [comment]
Hi @serathius, thanks for that info, it's quite clear and I find the main gaps for Arm64 to be a Tier 1 platform. I will discuss internally and adding more CI on linux-arm64 for ETCD to cover the test scenario.

**Comment by dims** [comment]
/assign @dims 

xref: https://github.com/cncf/cluster/issues/226

**Comment by dims** [comment]
We have 2 machines, machine spec is as follows:
![image](https://user-images.githubusercontent.com/23304/214130923-7cd8ae70-444e-4635-ab73-d3265bf3ae29.png)

**Comment by dims** [comment]
To get access to the Equinix console, please reach out to me or folks in https://github.com/cncf/cluster/issues/226 and ask for access to the `etcd` project under `CNCF` org. Direct url is https://console.equinix.com/projects/1b8c1eb7-983c-4b40-97e0-e317406e232e

the two machines are:
- etcd-c3-large-arm64-runner-01 / 86.109.7.233
- etcd-c3-large-arm64-runner-02 / 147.28.151.226

**Comment by dims** [comment]
testing a CI job in https://github.com/etcd-io/etcd/pull/15172

**Comment by dims** [comment]
We are green!

![image](https://user-images.githubusercontent.com/23304/214131554-0f273047-bc87-4f08-8506-fd3d139f679d.png)

**Comment by kevinzs2048** [comment]
@dims Thanks for your help!

We are dedicating to make etcd on Arm64 as the Tier-1 support, the plan is:
- firstly to add more equivalent CI's for Arm64, and I will also get some donation VM machines if more machine resources are needed.
- After the CI is ready, we will monitor the Etcd CI and fix bugs on Arm64 to make it always Green.

So today I'm writing to ask for the access of the 2 Ampere nodes in Etcd under CNCF.org. My pubkey is sending to you via email just in case it is needed.

**Comment by dims** [comment]
@kevinzs2048 here are the details of what we have:

![image](https://user-images.githubusercontent.com/23304/215492208-f25df799-5b55-4881-94f2-084cdcb08066.png)

![image](https://user-images.githubusercontent.com/23304/215492258-c50eb53b-97c4-4ee1-8b97-8837451fb1e1.png)

**Comment by dims** [comment]
@kevinzs2048 what's needed now is to add  other `arm64` based CI jobs that run periodically similar to the one i added in https://github.com/etcd-io/etcd/pull/15172/files 

I don't know if we have a list of CI jobs for `Tier 1`, so we need to make a list first

cc @geetasg @chaochn47

**Comment by geetasg** [comment]
Based on https://etcd.io/docs/v3.6/op-guide/supported-platform/#supporting-a-new-platform, seems like arm64 needs to pass following tests to be qualified as Tier1 platform -

* Build - already passes - ci job is github/workflows/build.yaml
* Unit tests -  ci job can be in .github/workflows/tests.yaml
* Integration tests - ci job can be in .github/workflows/tests.yaml
* e2e tests - ci job can be in .github/workflows/e2e.yaml
* functional tests - ci job is as shown in https://github.com/etcd-io/etcd/pull/15172/files
* stress test - seems to be part of functional tests. @serathius @ahrtr - please confirm.

@serathius @ahrtr - can you please confirm if this list of tests is good to support the new platform? /cc @dims @chaochn47

**Comment by kevinzs2048** [comment]
Thanks for the info @dims @geetasg @serathius 
I've submitted a PR to add e2e tests on Arm64.

**Comment by geetasg** [comment]
https://github.com/etcd-io/etcd/actions/runs/4089389816/jobs/7052024952#step:5:336 shows unit and integration tests passing as well. What additional work needs to be completed to make arm64 T1?  /cc @serathius @dims @ahrtr @kevinzs2048

**Comment by kevinzs2048** [comment]
@geetasg Good question. It looks that the test jobs are all added, but just a periodically one, not sure if the periodically job is sufficient.

**Comment by kevinzs2048** [comment]
Hi @dims, there are something wrong with the E2E jobs. Could you add me the login credentials? So that I can login the node to do some debug. https://github.com/etcd-io/etcd/actions/workflows/e2e-arm64.yaml

**Comment by dims** [comment]
@kevinzs2048 added your keys from https://github.com/kevinzs2048.keys to one of the boxes. please ssh in as root, sent you the ip address via email

**Comment by ahrtr** [comment]
I would suggest to add some test on the image as well. FYI. https://github.com/etcd-io/etcd/issues/15139#issuecomment-1437978152

**Comment by kevinzs2048** [comment]
@ahrtr Thanks, will do

**Comment by kevinzs2048** [comment]
Hi @ahrtr @chaochn47, thanks for working on this, and I wonder that does #15310 still relevant with the T1 support?

**Comment by jmhbnz** [comment]
Have opened https://github.com/etcd-io/etcd/issues/15832 to ask if there is any appetite to backport the arm testing workflows to `release-3.5`.

**Comment by chaochn47** [comment]
> Hi @ahrtr @chaochn47, thanks for working on this, and I wonder that does #15310 still relevant with the T1 support?

Yeah, I think so @kevinzs2048. Robustness test is used to guarantee etcd correctness. Best point of contact would be @serathius 

> Purpose of etcd robustness tests is to validate that etcd upholds [API guarantees](https://etcd.io/docs/latest/learning/api_guarantees/) and [watch guarantees](https://etcd.io/docs/latest/learning/api/#watch-streams) under any condition or failure.

Hi @serathius @ahrtr Could you please suggest what's the next step on this PR #15310 ?

**Comment by serathius** [comment]
> Hi @serathius @ahrtr Could you please suggest what's the next step on this PR #15310 ?

I would like to reuse same template for both x86 and arm tests, however GitHub Actions are bullying me. If someone knows how to do that, please pick up the PR.

**Comment by jmhbnz** [comment]
Have raised #15886 to complete the work to bring robustness tests to `arm64` 🙏🏻

**Comment by jmhbnz** [comment]
Closing, tier 1 support for `arm64` has now been announced, refer https://groups.google.com/g/etcd-dev/c/s3srSmDN92k
