### ISSUE TITLE
Release v3.5.6

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#14750]
This issue tracks fixes for next v3.5.5 patch release.

Issues blocking the release:

* [x] https://github.com/etcd-io/etcd/issues/14736
* [x] https://github.com/etcd-io/etcd/issues/14764
  * [x] https://github.com/etcd-io/etcd/pull/14770
  * [Backport to v3.5](https://github.com/etcd-io/etcd/pull/14790)
* [x] https://github.com/etcd-io/etcd/pull/14685
  * [x] https://github.com/etcd-io/etcd/pull/14730
  * [x] https://github.com/etcd-io/etcd/pull/14733
* [x] https://github.com/etcd-io/etcd/issues/14571
  * [x] https://github.com/etcd-io/etcd/pull/14647
  * [x] https://github.com/etcd-io/etcd/pull/14648 
* [x] https://github.com/etcd-io/etcd/issues/12385
  * [x] https://github.com/etcd-io/etcd/pull/14322
  * [x] https://github.com/etcd-io/etcd/pull/14547
* [x] https://github.com/etcd-io/etcd/pull/14296
  * [x] https://github.com/etcd-io/etcd/pull/14563
* [x] https://github.com/etcd-io/etcd/issues/7798
  * [x] https://github.com/etcd-io/etcd/pull/13224
  * [x] https://github.com/etcd-io/etcd/pull/14573
* [x] https://github.com/etcd-io/etcd/pull/14556
  * [x] https://github.com/etcd-io/etcd/pull/14582
* [x] https://github.com/etcd-io/etcd/issues/14603
  * [x] https://github.com/etcd-io/etcd/pull/14604
  * [x] https://github.com/etcd-io/etcd/pull/14658
  
Skipped
  * https://github.com/etcd-io/etcd/issues/14749

**Comment by serathius** [comment]
cc @ahrtr

**Comment by ahrtr** [comment]
Most likely https://github.com/etcd-io/etcd/issues/14749 is the same issue as https://github.com/etcd-io/etcd/pull/14685. FYI. https://github.com/etcd-io/etcd/issues/14749#issuecomment-1314189657

**Comment by serathius** [comment]
With https://github.com/etcd-io/etcd/pull/14799 merged and https://github.com/etcd-io/etcd/issues/14749 not going anywhere I'm starting the release process.

**Comment by serathius** [comment]
Release was published
