### ISSUE TITLE
Use consistent version of gofail 

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#14806]
### What would you like to be added?

Gofail is used in two ways:
* gofail binary installed via `cd tools/mod; go install go.etcd.io/gofail` to transform comments into failpoints
* `go.etcd.io/gofail/runtime` library installed via `cd server; go get go.etcd.io/gofail/runtime` when building etcd with failpoints

https://github.com/etcd-io/etcd/pull/14804 showed that change in gofail interface breaks our CI. 

I think the reason was that  `cd tools/mod; go install go.etcd.io/gofail`  took gofail version from `tools/mod/go.mod` and `cd server; go get go.etcd.io/gofail/runtime` tool the latest version. 

We should update our scripts so both ways use the same version of gofail.
cc @ahrtr 

### Why is this needed?

Using consistent version of gofail will prevent breakages in CI and make it easier to predict failpoint behavior.

**Comment by ahrtr** [comment]
It's exactly the reason why I raised https://github.com/etcd-io/gofail/pull/32. Let's pin the gofail version after we release gofail v0.1.0

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/gofail/issues/33

**Comment by serathius** [comment]
I was more thinking about using version from `tools/mod/go.sum` when building etcd with failpoints. I assume that you are planning to release v0.1.0 just to update `go get go.etcd.io/gofail/runtime@v0.1.0` however this doesn't the underlying problem that we have to different sources of truth for gofail version.

**Comment by ahrtr** [comment]
> I assume that you are planning to release v0.1.0 just to update `go get go.etcd.io/gofail/runtime@v0.1.0`

This isn't correct. We need to bump gofail to v0.1.0 in all places in etcd, including go install `go.etcd.io/gofail@v0.1.0` and go `get go.etcd.io/gofail/runtime@v0.1.0`

**Comment by serathius** [comment]
Fixed by https://github.com/etcd-io/etcd/pull/14859
