### ISSUE TITLE
error/info log when TTL is <= 0

### ISSUE THREAD

**Issue by shreemaan-abhishek** [etcd-io/etcd#14811]
### What would you like to be added?

This is an enhancement rather than a feature.

Currently, if I try to create a session as such: `concurrency.NewSession(etcdClient, concurrency.WithTTL(0))` it automatically defaults to 60 without any notice.

It would be nice to have a log getting printed. Example: `"TTL should be > 0, defaulting to 60"`

### Why is this needed?

To improve usability.

**Comment by ramil600** [comment]
Please review my PR, with suggested code fix and unit test added: #14993

**Comment by jmhbnz** [comment]
Hey @serathius - #14993 has been merged so I think this one can be closed.
