### ISSUE TITLE
Fix issue in a comment.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [etcd-io/etcd#14821]
### What would you like to be added?

I am not totally sure if I am correct but I think [here](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/key.go#L48-L49), we should mention:

> waitDeletes efficiently waits until all keys matching the prefix and no greater than the create revision **_are deleted_**

Instead of just:

> waitDeletes efficiently waits until all keys matching the prefix and no greater than the create revision.

I tried to verify this with [the PR](https://github.com/etcd-io/etcd/pull/7444/files) related to the above change (found using git blame)

### Why is this needed?

For clarity. Especially for newbies.

**Comment by serathius** [comment]
Fixing comment is not a thing that needs an dedicated issue. Feel free to create an PR where we can discuss it.
