### ISSUE TITLE
add new function in etcdutl to check if wal and db files is fine.

### ISSUE THREAD

**Issue by new-dream** [etcd-io/etcd#14837]
### What would you like to be added?

add new function in etcdutl to check if wal and db files is fine.
such as `etcdutl check broken`

### Why is this needed?

The function will detect wrong data files in one of etcd instance and then delete this file and recover to join the cluster.

**Comment by lavacat** [comment]
Can you describe what type of `broken`? Is this to avoid `data-dir used by this member must be removed` message during etcd joining cluster?

If yes, I think the idea is to leave data intact so operator can inspect it and make decision.

**Comment by new-dream** [comment]
I added a pr [14844](https://github.com/etcd-io/etcd/pull/14844) to do this.

This command checks whether the wal file is normal .
Second, check whether the db file can be opened normally.
Finally, try to read the consistent index from the db file.
If there are no errors and panics, the command returns 0.

How to use this command:
1. This command is invoked when the etcd process exits with error codes ranging from 1 to 127.
2. If a non-zero value is returned, check whether all other etcd processes in the cluster are normal.
3. If yes, delete the etcd data on the node, delete the member from the cluster, and add the member to the cluster again.

**Comment by new-dream** [comment]
we have encountered the following panic:
```panic: tocommit(1808562) is out of range [1808561]. Was the raft log corrupted, truncated, or lost?```
```panic: freepages: failed to get all reachable pages (page 633: multiple references)```
etc.
