### ISSUE TITLE
limit the size of the etcd wal file

### ISSUE THREAD

**Issue by new-dream** [etcd-io/etcd#14832]
### What would you like to be added?

add a startup flag to limit the size of the WAL file.

### Why is this needed?

The size of disk is strictly limited in our product so the disk storage space for etcd cannot be sufficient. Therefore, we want to limit the size of the etcd wal file.

**Comment by ptabor** [comment]
Currently the wal needs to be at least 128MB + 64MB for 'preallocated page' for next WAL segment. 
How low do you need to go ?
