### ISSUE TITLE
Plan to upgrade goVersion for etcdctl?

### ISSUE THREAD

**Issue by caixiangibm** [etcd-io/etcd#14848]
### What happened?

Downloaded the latest etcd-v3.5.6 and check etcdctl go version information.
We found its go version still with go1.16.15
```
# go version etcd-v3.5.6-linux-amd64/etcdctl
etcd-v3.5.6-linux-amd64/etcdctl: go1.16.15 
```

### What did you expect to happen?

When will etcd use latest go version of go 1.19.3 or 1.18.8 to build and release newer version?

### How can we reproduce it (as minimally and precisely as possible)?

just run: go version etcd-v3.5.6-linux-amd64/etcdctl

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.6
Git SHA: cecbe35ce
Go Version: go1.16.15
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.6
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
No, we don't usually backport golang minor version upgrades and go1.17 has some breaking changes. Details in https://github.com/etcd-io/etcd/issues/14105#issuecomment-1153018727

**Comment by caixiangibm** [comment]
But it seems there was PR for go version 1.19.3?
https://github.com/etcd-io/etcd/pull/14678

**Comment by serathius** [comment]
This is the `main` branch used for development.

**Comment by caixiangibm** [comment]
Given that there is go version 1.19.3 master branch for development , the newer go version for etcd is in development and evaluation ?

**Comment by serathius** [comment]
Next release of etcd (v3.6) is expected to launch with (+/-) latest available go version on the time of the release.
