### ISSUE TITLE
 Allow to config the max number of keys that the server is allowed to return in the Range API call

### ISSUE THREAD

**Issue by YokkiShi** [etcd-io/etcd#14841]
### What would you like to be added?

Capability to config an upper limit for the server response similar to –max-txn-ops and –max-request-bytes for request? The intent is to prevent callers from stressing the server.

Refer to the discussion here https://github.com/etcd-io/etcd/discussions/14808

### Why is this needed?

One of our dynamic security scan reports indicated the ETCD server **Lack Of Resources And Rate Limiting** which might be a security vulnerability.

**Comment by ahrtr** [comment]
Is [WithLimit](https://github.com/etcd-io/etcd/blob/b6a35947100f98920e4adbb80f475f08a44cdff7/client/v3/op.go#L342) what you want?

**Comment by ahrtr** [comment]
You can also set `--limit` when executing `etcdctl get `command.
