### ISSUE TITLE
WAL permission denied error when restoring etcd on different storage

### ISSUE THREAD

**Issue by FerminCastro** [etcd-io/etcd#14851]
### What happened?

For many months we have been able to restore etcd snapshots and start etcd using a data dir on NFS. Now we need to change the storage where we place etcd-data and etcd-wal. We basically restore the snapshot and bring up etcd from the new storage. Even though the file system permissions are exactly the same ones on the new storage server as in the old NFS one we are now facing this error:

failed to open WAL","error":"permission denied"

More detailed message:
```
{"level":"info","ts":"2022-11-24T16:19:22.380Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.2","git-sha":"99018a77b","go-version":"go1.16.3","go-os":"linux","go-arch":"amd64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":true,"name":"olk8-m1","data-dir":"/var/lib/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://10.11.0.16:2380"],"listen-peer-urls":["https://10.11.0.16:2380"],"advertise-client-urls":["https://10.11.0.16:2379"],"listen-client-urls":["https://10.11.0.16:2379","https://127.0.0.1:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"warn","ts":1669306762.381188,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory \"/var/lib/etcd\" exist, but the permission is \"drwxrwxrwx\". The recommended permission is \"-rwx------\" to prevent possible unprivileged access to the data"}
{"level":"warn","ts":1669306762.4027245,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory \"/var/lib/etcd/member/snap\" exist, but the permission is \"drwxrwxrwx\". The recommended permission is \"-rwx------\" to prevent possible unprivileged access to the data"}
{"level":"info","ts":"2022-11-24T16:19:22.436Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"9.905917ms"}
{"level":"info","ts":"2022-11-24T16:19:22.486Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":3,"snapshot-size":"7.5 kB"}
{"level":"info","ts":"2022-11-24T16:19:22.487Z","caller":"etcdserver/server.go:521","msg":"recovered v3 backend from snapshot","backend-size-bytes":44806144,"backend-size":"45 MB","backend-size-in-use-bytes":4636672,"backend-size-in-use":"4.6 MB"}
{"level":"fatal","ts":"2022-11-24T16:19:22.495Z","caller":"etcdserver/storage.go:95","msg":"failed to open WAL","error":"permission denied","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.readWAL\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/storage.go:95\ngo.etcd.io/etcd/server/v3/etcdserver.restartNode\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/raft.go:481\ngo.etcd.io/etcd/server/v3/etcdserver.NewServer\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/server.go:533\ngo.etcd.io/etcd/server/v3/embed.StartEtcd\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/embed/etcd.go:245\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcd\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/etcd.go:227\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/etcd.go:122\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.3/src/runtime/proc.go:225"}
```

i.e  etcd seems to be failing in the permissions for the wal dir. Just for the sake of checking if there was really some error with the permissions, before bringing up etcd we are changing permissions on wal and the entire etcd dirs (data and wal):
```
[root@olk8-m1 ~]# ls -lart /u02/data/dbfs_root/dbfsdir/olk8-m1/member/
total 0
drwxrwxrwx. 3 root root 0 Nov 24 16:24 ..
drwxrwxrwx. 2 root root 0 Nov 24 16:24 snap
drwxrwxrwx. 4 root root 0 Nov 24 16:24 .
drwxrwxrwx. 2 root root 0 Nov 24 16:24 wal
```
But it makes no difference, we keep getting back the "failed to open WAL","error":"permission denied","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.readWAL error

If this is failing it looks clear it should not be because of file permissions

### What did you expect to happen?

etcd comes up correctly

### How can we reproduce it (as minimally and precisely as possible)?

We are not sure this can be reproduced in ANY storage, but here are the steps we are taking
1.-Take etcd snapshot
```
$etcdctlhome/etcdctl --endpoints $host:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt snapshot save $host_dir/etcd-snapshot-$host.db
```
2.-Stop etcd
3.-Restore snapshot
```
$etcdctlhome/etcdctl snapshot restore ${backup_dir}/${mnode1}/etcd-snapshot-${mnode1}.db --name $host  --initial-cluster $initialclusteretcd  --initial-cluster-token etcd-cluster-1  --initial-advertise-peer-urls https://$host:2380 --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt
```
4.-Copy snapshot to new etcd storage 
```
rsync -avxHAX ${backup_dir}/restore_attempted_${dt}/$host/$host.etcd/member $new_etcd_dir"

5.-Bring up etcd pointing to this new dir/storage (i.e. pointing to $new_etcd_dir)




### Anything else we need to know?

The new file system is DBFS (https://docs.oracle.com/database/121/VLDBG/GUID-6B5634D3-D539-4D1F-ABA3-0C903AC28639.htm#VLDBG14099) but to all extents this is a totally standard file system mounted with fuse

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
# paste output here
```
etcdctl version: 3.5.2
API version: 3.5

</details>

### Etcd configuration (command line flags or environment variables)

<details>

 etcd --advertise-client-urls=https://10.11.0.16:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://10.11.0.16:2380 --initial-cluster=olk8-m1=https://10.11.0.16:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://10.11.0.16:2379 --listen-metrics-urls=http://127.0.0.1:2381 --listen-peer-urls=https://10.11.0.16:2380 --name=olk8-m1 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --t

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>
Etcd is failing to even come up so we cant get member list etc
</details>

### Relevant log output

```shell
{"level":"info","ts":"2022-11-24T16:19:22.370Z","caller":"etcdmain/etcd.go:72","msg":"Running: ","args":["etcd","--advertise-client-urls=https://10.11.0.16:2379","--cert-file=/etc/kubernetes/pki/etcd/server.crt","--client-cert-auth=true","--data-dir=/var/lib/etcd","--initial-advertise-peer-urls=https://10.11.0.16:2380","--initial-cluster=olk8-m1=https://10.11.0.16:2380","--key-file=/etc/kubernetes/pki/etcd/server.key","--listen-client-urls=https://127.0.0.1:2379,https://10.11.0.16:2379","--listen-metrics-urls=http://127.0.0.1:2381","--listen-peer-urls=https://10.11.0.16:2380","--name=olk8-m1","--peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt","--peer-client-cert-auth=true","--peer-key-file=/etc/kubernetes/pki/etcd/peer.key","--peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt","--snapshot-count=10000","--trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt"]}
{"level":"info","ts":"2022-11-24T16:19:22.375Z","caller":"etcdmain/etcd.go:115","msg":"server has been already initialized","data-dir":"/var/lib/etcd","dir-type":"member"}
{"level":"info","ts":"2022-11-24T16:19:22.375Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["https://10.11.0.16:2380"]}
{"level":"info","ts":"2022-11-24T16:19:22.375Z","caller":"embed/etcd.go:479","msg":"starting with peer TLS","tls-info":"cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, client-cert=, client-key=, trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file = ","cipher-suites":[]}
{"level":"info","ts":"2022-11-24T16:19:22.376Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["https://10.11.0.16:2379","https://127.0.0.1:2379"]}
{"level":"info","ts":"2022-11-24T16:19:22.380Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.2","git-sha":"99018a77b","go-version":"go1.16.3","go-os":"linux","go-arch":"amd64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":true,"name":"olk8-m1","data-dir":"/var/lib/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://10.11.0.16:2380"],"listen-peer-urls":["https://10.11.0.16:2380"],"advertise-client-urls":["https://10.11.0.16:2379"],"listen-client-urls":["https://10.11.0.16:2379","https://127.0.0.1:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"warn","ts":1669306762.381188,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory \"/var/lib/etcd\" exist, but the permission is \"drwxrwxrwx\". The recommended permission is \"-rwx------\" to prevent possible unprivileged access to the data"}
{"level":"warn","ts":1669306762.4027245,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory \"/var/lib/etcd/member/snap\" exist, but the permission is \"drwxrwxrwx\". The recommended permission is \"-rwx------\" to prevent possible unprivileged access to the data"}
{"level":"info","ts":"2022-11-24T16:19:22.436Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"9.905917ms"}
{"level":"info","ts":"2022-11-24T16:19:22.486Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":3,"snapshot-size":"7.5 kB"}
{"level":"info","ts":"2022-11-24T16:19:22.487Z","caller":"etcdserver/server.go:521","msg":"recovered v3 backend from snapshot","backend-size-bytes":44806144,"backend-size":"45 MB","backend-size-in-use-bytes":4636672,"backend-size-in-use":"4.6 MB"}
{"level":"fatal","ts":"2022-11-24T16:19:22.495Z","caller":"etcdserver/storage.go:95","msg":"failed to open WAL","error":"permission denied","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.readWAL\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/storage.go:95\ngo.etcd.io/etcd/server/v3/etcdserver.restartNode\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/raft.go:481\ngo.etcd.io/etcd/server/v3/etcdserver.NewServer\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdserver/server.go:533\ngo.etcd.io/etcd/server/v3/embed.StartEtcd\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/embed/etcd.go:245\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcd\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/etcd.go:227\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/etcd.go:122\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.3/src/runtime/proc.go:225"}
```

**Comment by ahrtr** [comment]
Can you please write a simple golang program to call `os.Open(walDir)` and `dir.Readdirnames`?

FYI. https://github.com/etcd-io/etcd/blob/f18ac02e0f60da33dd818812f7f7f6d7856670a5/client/pkg/fileutil/read_dir.go#L48-L54

**Comment by FerminCastro** [comment]
[opc@olk8-m1 scriptsFRA]$ cat  /scratch/docker/scripts/scriptsFRA/read_dir.go
package main

import (
        "os"
        "fmt"
)


func main() {
    fmt.Println("Reading dir...")
    dir, err := os.Open("/u02/data/dbfs_root/dbfsdir/olk8-m1/member/wal/")
        if err != nil {
                fmt.Println("Error!")
                fmt.Println(err)
        }
        defer dir.Close()

        names, err := dir.Readdirnames(-1)
        if err != nil {
                fmt.Println(err)
        }
        fmt.Println(names)
}

[opc@olk8-m1 scriptsFRA]$ go run read_dir.go
Reading dir...
[0000000000000000-0000000000000000.wal]
[opc@olk8-m1 scriptsFRA]$

[opc@olk8-m1 scriptsFRA]$ ls -lart /u02/data/dbfs_root/dbfsdir/olk8-m1/member/wal/
total 62500
-rw-rwxrwx. 1 root root 64000000 Nov 24 16:16 0000000000000000-0000000000000000.wal
drwxrwxrwx. 4 root root        0 Nov 24 16:24 ..
drwxrwxrwx. 2 root root        0 Nov 24 16:24 .
[opc@olk8-m1 scriptsFRA]$

**Comment by ahrtr** [comment]
Thanks for the feedback. Then the only possible reason is etcd failed to lock the file.

FYI. https://github.com/etcd-io/etcd/blob/488e5413d7447109e4260abbc9c29e6eb75a053e/client/pkg/fileutil/lock_flock.go#L30-L36

Please code something like below, 
```
	f, err := os.OpenFile("/u02/data/dbfs_root/dbfsdir/olk8-m1/member/wal/0000000000000000-0000000000000000.wal", os.O_RDWR, 0600)
	if err != nil {
		return nil, err
	}
	if err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		f.Close()
		if err == syscall.EWOULDBLOCK {
			err = ErrLocked
		}
		return nil, err
	}
```

**Comment by FerminCastro** [comment]
[opc@olk8-m1 ~]$ cat /scratch/docker/scripts/scriptsFRA/check_dir.go

`package main

import (
        "os"
        "fmt"
        "syscall"
        "errors"
)


func main() {
    fmt.Println("Checking wal file...")
    f, err := os.OpenFile("/u02/data/dbfs_root/dbfsdir/olk8-m1/member/wal/0000000000000000-0000000000000000.wal", os.O_RDWR, 0600)
        if err != nil {
                 fmt.Println("Some other error!")
                 fmt.Println(err)
        } else{
                fmt.Println("All good opening file buddy!")
        }
        if err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
                f.Close()
                if err == syscall.EWOULDBLOCK {
                        err = errors.New("Locked out buddy")
                        fmt.Println("EWOULDBLOCK error")
                        fmt.Println(err)
                }
                fmt.Println("FLock error!")
                fmt.Println(err)
        } else {
                fmt.Println("NO lock error either")
        }
}
`
[opc@olk8-m1 ~]$  go run /scratch/docker/scripts/scriptsFRA/check_dir.go
Checking wal file...
All good opening file buddy!
NO lock error either

**Comment by FerminCastro** [comment]
One thing though, notice that OBVIOUSLY now etcd is STOPPED (i.e. it has not come up) Saying this in case you were expecting the checks above to be run while etcd was in fact trying to access or start etc... (we won't be able to try that because etcd does not even come up as I said)

**Comment by ahrtr** [comment]
Thanks for the feedback. It's interesting.  How did you run etcd? As processes or container? 

Could you try to reproduce this issue using https://github.com/etcd-io/etcd/pull/14864 and provide the complete log?  Please build etcd using golang 1.16.15, because we test and release 3.5 using the Golang version.

**Comment by FerminCastro** [comment]
ETCD is running as kubernetes pod (this was a kubeadm generated system). Hence I think it will be eve more difficult to use the version you point to. Isn't there any other way to add additional debugging? Any additional flags for etcd that would trigger a mode detailed error information?

**Comment by ahrtr** [comment]
Unfortunately, there isn't much debug log in the related code path. My immediately feeling is it might be due to the POD in which the etcd is running doesn't have correct permission to access the PV. 

The suggestion is to run another POD and consume the same PV, and then log into the POD to check the WAL directory permission.

**Comment by ahrtr** [comment]
This seems not an etcd issue. Instead, it might be due to the StorageClass/PVC/volume mis-configuration.

**Comment by FerminCastro** [comment]
We are not using PVC. We are using hostpath for the etcd pod mount. The file system is totally up an ready, writable, readable and behaving properly for all operations. i.e. has to be some issue with etcd not behaving properly with this file system. Does etcd have any specific file system requirements? What checks would be required?

**Comment by FerminCastro** [comment]
I am not sure I understand why you have removed the bug label. At a minimum it is clear that the error messages IS INCORRECT

**Comment by ahrtr** [comment]
> Does etcd have any specific file system requirements? What checks would be required?

With regard to  WAL files, the suggested code/check in https://github.com/etcd-io/etcd/issues/14851#issuecomment-1326774285 and https://github.com/etcd-io/etcd/issues/14851#issuecomment-1327383684 are all how etcd access the filesystem. You have already confirmed that the filesystem is working well.

FYI. etcd needs to mmap the db file, but I do not see any error on that. Instead, the error is only related to WAL directory/files.



> We are not using PVC. We are using hostpath for the etcd pod mount.

Could you double check the WAL directory permission inside a POD/container(e.g. with image `ubuntu` instead of `etcd`) mounted with the same hostPath? And re-run the programs above inside the POD/container? 



> I am not sure I understand why you have removed the bug label. At a minimum it is clear that the error messages IS INCORRECT

Just as I mentioned above, etcd really doesn't do anything special on the WAL directories/files. Based on the error message "permission denied", it seems that the etcd container has no permission to read/write the WAL directory or files. I don't think it's an issue of etcd.

**Comment by FerminCastro** [comment]
But it has to be something different with the WAL dir/file Right? I mean, before we get the error with WAL we see this other message:

{"level":"info","ts":"2022-11-24T16:19:22.436Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"9.905917ms"}

"/lib/etcd/member/snap/db" resides in the exact same physical storage and directory as WAL (/u02/data/dbfs_root/dbfsdir/olk8-m1/member). And both are using hostpath in the pod. And etcd is reporting it can open it. So there is something specific with WAL UNLESS the message about opening snap/db is false. Would you agree?

**Comment by ahrtr** [comment]
etcd mmap the db file, but uses standard filesystem interface(e.g. os.Open, dir.Readdirnames, os.OpenFile and syscall.Flock) to operate WAL directory and files.

I suggest you to double check per my suggestion above. Pasted again below,

> Could you double check the WAL directory permission inside a POD/container(e.g. with image ubuntu instead of etcd) mounted with the same hostPath? And re-run the programs above inside the POD/container?

**Comment by FerminCastro** [comment]
[opc@olk8-m1 ~]$ cat /scratch/docker/sample-dbfs-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: httpd:latest
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
        path: /u02/data/dbfs_root/dbfsdir/olk8-m1
        type: DirectoryOrCreate
  nodeSelector:
    testtype: etcd

[opc@olk8-m1 ~]$ kubectl apply -f /scratch/docker/sample-dbfs-pod.yaml

[opc@olk8-m1 ~]$ k get pods -A | grep test
default       test-pd                             1/1     Running   0             99s


[opc@olk8-m1 ~]$ k exec test-pd -n default -- ls  -lart /test-pd/member
total 0
drwxrwxrwx. 3 root root 0 Nov 24 16:24 ..
drwxrwxrwx. 2 root root 0 Nov 24 16:24 snap
drwxrwxrwx. 4 root root 0 Nov 24 16:24 .
drwxrwxrwx. 2 root root 0 Nov 24 16:24 wal


[opc@olk8-m1 ~]$ ls -lart /u02/data/dbfs_root/dbfsdir/olk8-m1/member/
total 0
drwxrwxrwx. 3 root root 0 Nov 24 16:24 ..
drwxrwxrwx. 2 root root 0 Nov 24 16:24 snap
drwxrwxrwx. 4 root root 0 Nov 24 16:24 .
drwxrwxrwx. 2 root root 0 Nov 24 16:24 wal
[opc@olk8-m1 ~]$

**Comment by ahrtr** [comment]
> And re-run the programs above inside the POD/container?

Can you try this? If you still can't reproduce this, then please try to build & run etcd using https://github.com/etcd-io/etcd/pull/14864 inside the POD/container. Probably you need to use image ubuntu?

**Comment by FerminCastro** [comment]
Thats a good test... unfortunately the results are "good" (i.e. we can't reproduce an probs with the wal file inside the pod)

[opc@olk8-m1 olk8-m1]$ cat /u02/data/dbfs_root/dbfsdir/olk8-m1/check_dir.go
package main

import (
        "os"
        "fmt"
        "syscall"
        "errors"
)


func main() {
    fmt.Println("Checking wal file...")
    f, err := os.OpenFile("/test-pd/member/wal/0000000000000000-0000000000000000.wal", os.O_RDWR, 0600)
        if err != nil {
                 fmt.Println("Some other error!")
                 fmt.Println(err)
        } else{
                fmt.Println("All good opening file buddy!")
        }
        if err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
                f.Close()
                if err == syscall.EWOULDBLOCK {
                        err = errors.New("Locked out buddy")
                        fmt.Println("EWOULDBLOCK error")
                        fmt.Println(err)
                }
                fmt.Println("FLock error!")
                fmt.Println(err)
        } else {
                fmt.Println("NO lock error either")
        }
}

[opc@olk8-m1 olk8-m1]$ go build check_dir.go

[opc@olk8-m1 olk8-m1]$ k exec test-pd -n default -- /test-pd/check_dir
Checking wal file...
All good opening file buddy!
NO lock error either


Will look into your suggestion to build https://github.com/etcd-io/etcd/pull/14864

**Comment by ahrtr** [comment]
Please format the source code using code. Already updated your comment to format it. Please try to do it yourself next time.

Please also try https://github.com/etcd-io/etcd/issues/14851#issuecomment-1327193200

**Comment by FerminCastro** [comment]
Yeah, apologies for the format, thought I had marked it. Anyways, we also included the check for the dir, and is also working without any errors.
`[opc@olk8-m1 olk8-m1]$ k exec test-pd  -- /test-pd/check_dir
Checking wal file...
All good opening file buddy!
NO lock error either
Now checking dir...
All good in opening dir also!
[0000000000000000-0000000000000000.wal]`
