### ISSUE TITLE
`make verify-shellcheck` only warns, doesn't fail when tool doesn't exist

### ISSUE THREAD

**Issue by Bhargav-InfraCloud** [etcd-io/etcd#14869]
### What happened?

Make target `verify-shellcheck` only warns and doesn't fail in absence of shellcheck binary.

### What did you expect to happen?

When `shellcheck` is missing in local, `verify-shellcheck` should fail.

### How can we reproduce it (as minimally and precisely as possible)?

1. Uninstall (or unset path to) `shellcheck`.
2. Run `make verify-shellcheck`.
    It gives warning:
    ```console
    Tool: 'shellcheck' not found on PATH. https://github.com/koalaman/shellcheck#installing
    ```
    But doesn't fail, due to which the [test.sh][1] marks it as `SUCCESS`.

[1]: https://github.com/etcd-io/etcd/blob/main/scripts/test.sh#L700

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.6.0-alpha.0
Git SHA: 61e9ec983
Go Version: go1.19.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.6.0-alpha.0
API version: 3.6
```

</details>

### Relevant log output

```shell
$ which shellcheck
shellcheck not found

$ make verify-shellcheck             
PASSES="shellcheck" ./scripts/test.sh
Running with --race
Starting at: Tuesday 29 November 2022 11:01:36 PM IST

'shellcheck' started at Tuesday 29 November 2022 11:01:36 PM IST
Tool: 'shellcheck' not found on PATH. https://github.com/koalaman/shellcheck#installing
'shellcheck' completed at Tuesday 29 November 2022 11:01:36 PM IST
SUCCESS
```

**Comment by ahrtr** [comment]
Thanks @Bhargav-InfraCloud for raising this. I would suggest to add `install-shellcheck` in Makefile, and make `verify-shellcheck` depend on it

```
verify-shellcheck: install-shellcheck

.PHONY: install-shellcheck
install-shellcheck:
	cd tools/mod; go install honnef.co/go/tools/cmd/staticcheck
```

**Comment by Bhargav-InfraCloud** [comment]
@ahrtr [staticcheck][1] is a linter for go files and [shellcheck][2] is for shell files. Are you sure staticcheck also works on shell files?

[1]: https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck
[2]: https://github.com/koalaman/shellcheck

**Comment by ahrtr** [comment]
> @ahrtr As far as I know, [staticcheck](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck) is a linter for go files and [shellcheck](https://github.com/koalaman/shellcheck) is for shell files. Are you sure staticcheck also works on shell files?

Please see my comments in https://github.com/etcd-io/etcd/pull/14872

**Comment by ptabor** [comment]
Thank you @Bhargav-InfraCloud  for looking into this. 
There are currently 2 proposals: 
  - https://github.com/etcd-io/etcd/pull/14872 (solving it in test.sh) 
  - https://github.com/etcd-io/etcd/pull/14888 (solving it Makefile)
 Are we considering one of them obsolete ? 

I'm rather on the side of salving it in `test.sh` by installing the binary within `./etcd/.tmp/...` directory, 
as test.sh is sometimes used without make.

**Comment by Bhargav-InfraCloud** [comment]
Hi @ptabor. Thanks for checking!
Since func `run_pass` has an `exit 255`, the func `shellcheck_pass` has to be called with a wrapped shell (like in make, github actions or another shell). Else, in case of failure, the terminal itself will exit. And when we are relying on an extra layer, my thoughts from initial discussion with @ahrtr & @serathius, was why not have a new `make` target that installs binary.

Also, personally I feel that moving the installations into `test.sh` will only bloat it in future. Hence, the second PR. But I'm cool if the other approach makes more sense to everyone.
