### ISSUE TITLE
OpenTelemetry-go related changes

### ISSUE THREAD

**Issue by diffusedlogic** [etcd-io/etcd#14866]
### What happened?

While using etcd now in my golang project, following dependencies related error is coming:

go.etcd.io/etcd/v3 imports
go.etcd.io/etcd/tests/v3/integration imports
go.etcd.io/etcd/server/v3/embed imports
go.opentelemetry.io/otel/exporters/otlp/otlpgrpc imports
go.opentelemetry.io/otel/exporters/otlp/internal/transform tested by
go.opentelemetry.io/otel/exporters/otlp/internal/transform.test imports
go.opentelemetry.io/otel/sdk/metric/aggregator/exact: module go.opentelemetry.io/otel/sdk/metric@latest found (v0.33.0), but does not contain package go.opentelemetry.io/otel/sdk/metric/aggregator/exact

while running go.mod which means the dependencies resolution is failing and cannot build the project

### What did you expect to happen?

go mod tidy should succeed and update dependencies properly

### How can we reproduce it (as minimally and precisely as possible)?

Use go.etcd.io/etcd/v3 in any project and try running go mod tidy

### Etcd version (please run commands below)

<details>

etcd version - v3.5.6
etcd client version - v3.5.6
etcdctl version - v3.5.6
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Please use the same go version as the version in go.mod
