### ISSUE TITLE
Set Github workflows default permissions to read-only 

### ISSUE THREAD

**Issue by joycebrum** [etcd-io/etcd#14878]
### What would you like to be added?

It is a [scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) recommendation to set the [github workflow permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to read only by default.  Thus, any action that would need a greater permission should be specified to have the permission, otherwise it will be read-only.

Can I suggest a PR with this changes?

### Why is this needed?

When the default permission of a workflow is not set to read-only, it is consider "write", by default. This allows any action listed in the workflow the write permission in the repository, even when they are not supposed to be able to write. 

The [Token Permission Check Documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) list some security concerns that allowing write permission to actions raises.

**Comment by ahrtr** [comment]
Looks good to me.
