### ISSUE TITLE
Update modules.svg: replace go.etcd.io/etcd/raft/v3 with go.etcd.io/raft/v3

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14883]
### What would you like to be added?

We have already migrated raft to a [separate repo](https://github.com/etcd-io/raft), and the module name was changed from `go.etcd.io/etcd/raft/v3` to `go.etcd.io/raft/v3`. Please anyone feel free to raise a PR to update the module name in
[modules.svg](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/modules.svg).

Linked to https://github.com/etcd-io/etcd/issues/14713

### Why is this needed?

We need to keep the name consistent at all places.

**Comment by Bhargav-InfraCloud** [comment]
@ahrtr Should it be updated in [modules-future.svg][1] as well?

[1]: [Documentation/contributor-guide/modules-future.svg](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/modules-future.svg)

**Comment by ahrtr** [comment]
> @ahrtr Should it be updated in [modules-future.svg](%5BDocumentation/contributor-guide/modules-future.svg%5D(https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/modules-future.svg)) as well?

Yes, good catch. The final goal should be there is no any `go.etcd.io/etcd/raft/v3` in etcd.
