### ISSUE TITLE
Leader re-election when member have a network problem and recovery

### ISSUE THREAD

**Issue by saneryao** [etcd-io/etcd#14893]
### What happened?

shutdown one member's network(mock network failure), and then up this memer, as this member's term id is greater than the existed cluster's termid, this will leads to leader re-election.

### What did you expect to happen?

leader re-election

### How can we reproduce it (as minimally and precisely as possible)?

shudown one follower's network; and sleep 30s; and ifup this follower's network.

### Anything else we need to know?

whether the previous leader can be directly elected?

modify func (r *raft) Step in raft/raft.go as:

```
@@ -861,7 +861,19 @@ func (r *raft) Step(m pb.Message) error {
 			if m.Type == pb.MsgApp || m.Type == pb.MsgHeartbeat || m.Type == pb.MsgSnap {
 				r.becomeFollower(m.Term, m.From)
 			} else {
-				r.becomeFollower(m.Term, None)
+				if m.Type == pb.MsgAppResp && r.hasLeader() {
+					if r.state == StateLeader {
+						r.Term = m.Term
+						r.pendingConfIndex = r.raftLog.lastIndex()
+						emptyEnt := pb.Entry{Data: nil}
+						if !r.appendEntry(emptyEnt) {
+							// This won't happen because we just called reset() above.
+							r.logger.Panic("empty entry was dropped")
+						}
+					}
+				} else {
+					r.becomeFollower(m.Term, None)
+				}
 			}
 		}
```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
related issue: [#14027](https://github.com/etcd-io/etcd/issues/14027)
```

**Comment by tbg** [comment]
CheckQuorum and PreVote are on with etcd, right? Without it, PreVote can succeed if there hasn't been any appends to the log. There is some discussion of this [here](https://github.com/cockroachdb/cockroach/issues/92088#issuecomment-1320544968) (CRDB doesn't use CheckQuorum).

**Comment by ahrtr** [comment]
Thanks @tbg for the feedback.



> CheckQuorum and PreVote are on with etcd, right?

Yes, `CheckQuorum` is hard coded `true`, and `PreVote` defaults to true, but users can change the value using flag --pre-vote".  @saneryao Did you change the flag ?

**Comment by saneryao** [comment]
Thanks for the feedback, @tbg @ahrtr.

**Comment by saneryao** [comment]
Thanks for the feedback, @tbg @ahrtr.
PreVote defaults to false in etcd version 3.4.13 and 3.5.6.
When I set it to true, etcd works normally.
