### ISSUE TITLE
auto-compaction-mode don't have default value when server configed with --config-file

### ISSUE THREAD

**Issue by monsterxx03** [etcd-io/etcd#14894]
### What happened?

config.yaml:

```
auto-compaction-retention: "2"
```

start etcd:

```
./etcd --config-file  config.yaml
```

check log:

"starting an etcd server","etcd-version":"3.6.0-alpha.0","git-sha":"9cc2f645c","go-version":"go1.19.1","go-os":"darwin","go-arch":"arm64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","wait-cluster-ready-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"max-wals":5,"max-snapshots":5,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s",**"auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s"**,"discovery-url":"","discovery-proxy":"","discovery-token":"","discovery-endpoints":"","discovery-dial-timeout":"2s","discovery-request-timeout":"5s","discovery-keepalive-time":"2s","discovery-keepalive-timeout":"6s","discovery-insecure-transport":false,"discovery-insecure-skip-tls-verify":false,"discovery-cert":"","discovery-key":"","discovery-cacert":"","discovery-user":"","downgrade-check-interval":"5s","max-learners":1}

etcd is expected to do auto compaction every 2 hour, but compaction didn't happen.

if started with cli flag:  ./etcd --auto-compaction-retention 2, compaction mode and interval will be set correctly:

```
"auto-compaction-mode":"periodic","auto-compaction-retention":"2h0m0s","auto-compaction-interval":"2h0m0s
```

seems configFromFile didn't set default value for auto-compaction-mode. 

If set **auto-compaction-mode: periodic** in config.yaml explictly, auto compaction can works.

### What did you expect to happen?

if only auto-compaction-retention is set in config.yaml, auto compaction should still work.  Same behavior as cli flag

### How can we reproduce it (as minimally and precisely as possible)?

use my example in issue

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
My immediate feeling is this is a good first issue.

**Comment by CaojiamingAlan** [comment]
Is it still open? Can I work on this?
