### ISSUE TITLE
Security scanning for etcd container images using trivy

### ISSUE THREAD

**Issue by akhilerm** [etcd-io/etcd#14908]
### What would you like to be added?

A trivy github action to perform a nightly scan on the generated container images of etcd. This will scan the image, along with the `etcd`, `etcdctl` and `etcdutl` binaries. 

The results (accessible only to maintainers) of the security scan will be show in the Security tab of the repo in the following format.
![Screenshot 2022-12-06 at 12 42 07](https://user-images.githubusercontent.com/7610845/206110958-6d8c59e7-f7d7-4c0b-9f48-609c4aabdcf8.png)

### Why is this needed?

Proactively get the CVEs for the dependent libraries as well as the base image being used for creating the container image. This helps to fix the vulnerability as soon as a fix version is available.

The scan can be done nightly instead of on PRs or code changes

**Comment by ahrtr** [comment]
Thanks @akhilerm for raising this feature request, and it Looks good to me. cc @spzala
