### ISSUE TITLE
Build etcd and perform security scan on container images weekly 

### ISSUE THREAD

**Issue by ArkaSaha30** [etcd-io/etcd#14991]
### What would you like to be added?

A github action to perform a weekly build of the latest etcd commits and run a Trivy security scan on respective container images. This will scan the image, along with the etcd, etcdctl and etcdutl binaries.

Note: Images build with the latest commits will be available in build cache and not pushed to any registry. 

Extends : Issue #14908
Discussion: https://github.com/etcd-io/etcd/pull/14928#discussion_r1046757079 

### Why is this needed?

Proactively get the CVEs for the dependent libraries as well as the base image being used for creating the container image. This helps to fix the vulnerability as soon as a fix version is available.

The scan can be done weekly with the latest commits and identify vulnerabilities before it makes it to a release version.

**Comment by ahrtr** [comment]
Looks good to me. cc @ptabor @serathius @spzala for opinion.

**Comment by ArkaSaha30** [comment]
Hello @serathius, even though they use distroless its base is Debian11. So the binaries will still be there and we might need to scan the image.
