### ISSUE TITLE
etcd response sizes >4MB are failing with --max-request-bytes=10485760 (10MB)

### ISSUE THREAD

**Issue by sanamsarath** [etcd-io/etcd#14997]
### What happened?

Upgraded our ETCD in our application clusters from v3.3.21 to v3.4.3, and started noticing that server responds with error code "429" for the data sizes greater than 4MB.

Following is the debug log from the etcd server 

> 2022-12-13 22:23:27.395298 D | etcdserver/api/v3rpc: start time = 2022-12-13 22:23:27.369209787 +0000 UTC m=+257.195842887, time spent = 25.897887ms, remote = 127.0.0.1:49534, response type = /etcdserverpb.KV/Range, request count = 0, request size = 66, response count = 5000, response size = 4786372, request content = key:"xxxxxxxxxxxxxxxxxxx" range_end:"xxxxxxxxxxxxxxxxxxx" 

Logs from the c++ curl client
> {.........................................,"responseCode":429,"MsgBuffer":"{\"error\":\"grpc: received message larger than max (4778467 vs. 4194304)\",\"message\":\"grpc: received message larger than max (4778467 vs. 4194304)\",\"code\":8}","level":"debug1",".........................}

The failure is happening at gRPC gateway.

### What did you expect to happen?

The responses should succeed upto response sizes of 10MB.

### How can we reproduce it (as minimally and precisely as possible)?

- Start etcd server 3.4.3 with config flag (cmd line or env variable)  --max-request-bytes=10485760
- Generate a data file of size 5MB or greater (I used linux urandom tool, tr -dc A-Za-z0-9 </dev/urandom | head -c 6291456 > testfile)
- Add a key with above generated 5MB data as value. (export value=$( cat testfile ); etcdctl put foo $value)
- Run get key command with etcdctl, this will succeed and verify the response size greater than 5MB
- Now, run the curl request to get the same key-value (curl -L http://localhost:2379/v3/kv/range  -X POST -d '{"key": "Zm9v"}')
- The curl command will get error response code 429 and msg "grpc: received message larger than max"

### Anything else we need to know?

This is where we are setting the Max response size to math.MazInt32 (which should be greater than 4MB) in 3.4.3 and above, and not setting this value in 3.3.21 (which is working fine).

https://github.com/etcd-io/etcd/blob/3cf2f69b5738fb702ba1a935590f36b52b18979b/etcdserver/api/v3rpc/grpc.go#L55

According to below stackoverflow comment it was mentioned that the gRPC maxSend and maxRecive size should be set on client side and not server side. (Not sure if this is entirely true, I didn't find any documentation regarding the same).
https://stackoverflow.com/questions/54137846/updating-receive-and-send-message-size-for-grpc-in-golang

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.3
API version: 3.4

```

</details>

We use json client in our application.

### Etcd configuration (command line flags or environment variables)

<details>

      /usr/local/bin/etcd
      --data-dir=/var/etcd/data
      --name=etcd-cluster-xxxxxxxxxx
      --initial-advertise-peer-urls=xxxxxxxxxx:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd-cluster-xxxxxxxxxx.svc.cluster.local:2379
      --initial-cluster=xxxxxxxxxx1:2380,xxxxxxxxxx2:2380,xxxxxxxxxx3:2380
      --initial-cluster-state=existing

      cpu:      500m
      memory:   256Mi
    Liveness:   exec [/bin/sh -ec ETCDCTL_API=3 etcdctl endpoint status] delay=10s timeout=10s period=60s #success=1 #failure=3
    Readiness:  exec [/bin/sh -ec ETCDCTL_API=3 etcdctl endpoint status] delay=1s timeout=5s period=5s #success=1 #failure=3
    Environment:
      ETCD_AUTO_COMPACTION_RETENTION:  5m
      ETCD_HEARTBEAT_INTERVAL:         400
      ETCD_ELECTION_TIMEOUT:           3000
      ETCDCTL_API:                     3
      ETCD_MAX_REQUEST_BYTES:          10485760
      ETCD_SNAPSHOT_COUNT:             3000
      ETCD_MAX_SNAPSHOTS:              3
      ETCD_MAX_WALS:                   5
      ETCD_QUOTA_BACKEND_BYTES:        8000000000
      ETCD_LOG_LEVEL:                  debug
</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
I did not reproduce this issue with 3.4.22 and 3.5.5. can you upgrade your etcd version?
