### ISSUE TITLE
[Security] Add Trivy scan workflows for release-3.4 and release-3.5 branches respectively

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15003]
### What would you like to be added?

Since the adding of [trivy-nightly-scan.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/trivy-nightly-scan.yaml), some security alerts are reported. But it's hard to tell which image (`v3.4.22` or `v3.5.6`) each alert was raised against. 

It would be better if we can differentiate the target image from each alert. The most stupid solution I can think of for now is to use different registries. For example, use `gcr.io/etcd-development/etcd` for 3.5 image, and quay.io/coreos/etcd for 3.4 image, if there is no other better way.

<img width="1039" alt="Screen Shot 2022-12-16 at 10 20 47" src="https://user-images.githubusercontent.com/30739825/208007102-5a5ea29a-2089-447a-9adf-e320b47a5781.png">

### Why is this needed?

See above

ccc @ArkaSaha30

**Comment by ahrtr** [comment]
The other solution is to add `Trivy scan workflow` for `release-3.4` and `release-3.5` respectively, and scan v3.4.22 and  3.5.6 respectively. We should can easily tell the target image on which each alert is raised.

**Comment by ArkaSaha30** [comment]
Hello @ahrtr, I like the second solution - separate workflows to be added in  release-3.4 and release-3.5. Creating 3 PRs as suggested:

- Remove exsisting trivy workflow from master
- Add trivy workflow to release-3.4 branch to scan v3.4.22
- Add trivy workflow to release-3.5 branch to scan v3.5.6
