### ISSUE TITLE
etcd 3.5 releases should call out etcdutl binary is released in installation script

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15030]
### What happened?

I cannot find `etcdutl` from https://github.com/etcd-io/etcd/releases/tag/v3.5.6 in the installation script. 

Compared to https://github.com/etcd-io/etcd/releases/tag/v3.4.22. 

`etcdctl` snapshot restore was moved to `etcdutl` in 3.5. 

### What did you expect to happen?

I expect `etcdutl` is released in 3.5. 

### How can we reproduce it (as minimally and precisely as possible)?

It is packaged in `etcd-v3.5.6-linux-amd64.tar.gz` but not called out in the installation script. 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by chaochn47** [comment]
Closing as `etcdctl snapshot restore` only has a deprecation notice. It's still usable.

**Comment by serathius** [comment]
Still this is a issue with v3.5 release.

**Comment by ahrtr** [comment]
Probably I am missing something. The `etcdutl` binary has already been included in the released package, e.g. 
`etcd-v3.5.6-linux-amd64.tar.gz `. @chaochn47 please clarify this issue.

```
$ ls -lrt
total 112552
-rwxr-xr-x@ 1 wachao  staff  15970304 Nov 21 22:55 etcdutl
-rwxr-xr-x@ 1 wachao  staff  17891328 Nov 21 22:55 etcdctl
-rwxr-xr-x@ 1 wachao  staff  23691264 Nov 21 22:55 etcd
-rw-r--r--@ 1 wachao  staff      7896 Nov 21 22:55 READMEv2-etcdctl.md
-rw-r--r--@ 1 wachao  staff      9394 Nov 21 22:55 README.md
-rw-r--r--@ 1 wachao  staff      7359 Nov 21 22:55 README-etcdutl.md
-rw-r--r--@ 1 wachao  staff     42066 Nov 21 22:55 README-etcdctl.md
drwxr-xr-x@ 4 wachao  staff       128 Nov 21 22:55 Documentation
```

**Comment by chaochn47** [comment]
aha! Thanks @ahrtr for checking. The `etcdutl` binary is already packaged in `etcd-v3.5.6-linux-amd64.tar.gz`

It just not being called out in the installation script. The issue title and description is updated. 

```
/tmp/etcd-download-test/etcdutl version
etcdutl version: 3.5.6
API version: 3.5
```

**Comment by ahrtr** [comment]
Thanks @chaochn47 for the clarification. It makes sense. We need to get `etcdutl` included in each 3.5 release's description, which currently only includes `etcd` and `etcdctl` (see below).

```
/tmp/etcd-download-test/etcd --version
/tmp/etcd-download-test/etcdctl version
```

**Comment by serathius** [comment]
Will take a look into this, however I think we should migrate installation script from releases to repo.

**Comment by serathius** [comment]
Latest release https://github.com/etcd-io/etcd/releases/tag/v3.5.9 calls out etcdutl
