### ISSUE TITLE
ETCD node skyrocketing to the maximum of available memory on the node (16GB) in a matter of seconds

### ISSUE THREAD

**Issue by bshaun8** [etcd-io/etcd#15049]
### What happened?

We saw that memory on ETCD node skyrocketing to the maximum of available memory on the node (16GB) in a matter of seconds. 

![image](https://user-images.githubusercontent.com/121470737/209606525-39709eb0-ca91-4594-8383-c6bf6a78bc2f.png)

Is anything in the etcd architecture that would cause it to consume 16GB of memory in seconds? Our etcd DB size is less than 800MB.

### What did you expect to happen?

The cluster to start up normally without a large spike in memory usage.

### How can we reproduce it (as minimally and precisely as possible)?

Restarting the kubernetes cluster.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.4.13
Git SHA: GitNotFound
Go Version: go1.15.8
Go OS/Arch: linux/amd64

$ etcdctl version
# paste output here
etcdctl version: 3.4.13
API version: 3.4
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here
+------------------+---------+------------------+---------------------------+---------------------------+------------+
|        ID        | STATUS  |       NAME       |        PEER ADDRS         |       CLIENT ADDRS        | IS LEARNER |
+------------------+---------+------------------+---------------------------+---------------------------+------------+
| 20db1dfdde84d300 | started | <obfuscated> | https://<obfuscated>:2380 | https://<obfuscated>:2379 |      false |
| 46fa1903d0e73fed | started | <obfuscated> | https://<obfuscated>:2380 | https://<obfuscated>:2379 |      false |
| 621e0ad80f4b7107 | started | <obfuscated> | https://<obfuscated>:2380 | https://<obfuscated>:2379 |      false |
| 790a135280172971 | started | <obfuscated> | https://<obfuscated>:2380 | https://<obfuscated>:2379 |      false |
| bff106870c7c1525 | started | <obfuscated> | https://<obfuscated>:2380 | https://<obfuscated>:2379 |      false |
+------------------+---------+------------------+---------------------------+---------------------------+------------+

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|         ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://<obfuscated> | 790a135280172971 |  3.4.13 |  817 MB |     false |      false |      1145 | 3225584887 |         3225584887 |        |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

```

</details>

**Comment by ahrtr** [comment]
FYI.  https://github.com/ahrtr/etcd-issues/blob/master/docs/troubleshooting/how_to_debug_performance_issue.md

**Comment by ptabor** [comment]
I understand that only one instance out of five is consuming that much memory. 
Are there any interesting logs out of the instance ? 
Is it running/serving or it fails to start-up ? 

Maybe bbolt file is corrupted and it drives bbolt lib towards an infinite allocation. 
I fixed similar problem in bbolt tool (https://github.com/etcd-io/bbolt/pull/354/files).
