### ISSUE TITLE
etcd  "error":"dial tcp xx.xx.xx.xx:2380: i/o timeout"

### ISSUE THREAD

**Issue by lspjx** [etcd-io/etcd#15076]
### What happened?

{"level":"warn","ts":"2023-01-10T03:09:43.846Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:09:48.846Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:09:53.847Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:09:58.847Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:03.848Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:08.848Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:13.849Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:18.850Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:23.851Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:28.851Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:33.851Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:38.853Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:43.853Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:48.854Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:53.855Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:10:58.855Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}{"level":"warn","ts":"2023-01-10T03:11:03.856Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout"}

### What did you expect to happen?

kubernetes cluster etcd pod outputs a large number of "error": "dial tcp 192.168.2.11:2380: i/o timeout"

### How can we reproduce it (as minimally and precisely as possible)?

"level":"warn","ts":"2023-01-10T03:11:03.856Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"84df05261edb
239e","rtt":"16.62287ms","error":"dial tcp 192.168.2.11:2380: i/o timeout

### Etcd version (please run commands below)

<details>

```console
# ./etcd -version
etcd Version: 3.5.0
Git SHA: 946a5a6f2
Go Version: go1.16.3
Go OS/Arch: linux/amd64

# ./etcdctl version
etcdctl version: 3.5.0
API version: 3.5


### Etcd configuration (command line flags or environment variables)

<details>

spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://192.168.2.11:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://192.168.2.11:2380
    - --initial-cluster=node-03=https://10.82.192.163:2380,node-01=https://192.168.2.11:2380,node-02=https://192.168.2.12:2380
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://192.168.2.11:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://192.168.2.11:2380
    - --name=node-01
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt

</details>


### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
It looks like just a network issue to me. It's also possible you did not setup/start the etcd cluster correctly.

Please follow [sanity_check_and_collect_basic_info.md](https://github.com/ahrtr/etcd-issues/blob/master/docs/troubleshooting/sanity_check_and_collect_basic_info.md)

**Comment by y2k2005** [comment]
Hi, I recently seeing this error in my etcd cluster as well, do we know what actually causing this error?
