### ISSUE TITLE
[Linearizability tests] Merge PutWithLease into Lease

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15085]
### What would you like to be added?

There is no real distinction between Puting with and without lease in etcd. Linearizability model shouldn't distinguish them either. Problem is that currently etcd model and traffic generator share an enum

### Why is this needed?

Simplifies implementation.

**Comment by pchan** [comment]
@serathius 
> There is no real distinction between Puting with and without lease in etcd. 

Can you give more info on this ? There is a semantic difference where keys are no longer present when the lease expires ([link](https://etcd.io/docs/v3.5/tutorials/how-to-create-lease/)).

>  Merge PutWithLease into Lease

What do you mean by "merging" PutWithLease with Lease.  Put [1] is the only mechanism by which you associate the key with the lease.  I am guessing the enum you are referring to is the one defined in model ([link](https://github.com/etcd-io/etcd/blob/fab8474ef8370a089fe0174e28c197b5b93898df/tests/linearizability/model/model.go#L33)).

If I have more context, I can attempt to solve this issue.

[1] etcdctl put --lease=32695410dcc0ca06 foo bar

**Comment by serathius** [comment]
In linearizability framework we incorrect merge of Txn operations types (Get, Put, Delete) and request generated by traffic (Put, PutWithLease). This change is pretty complicated so I decided that it will be much faster implemented it myself. Sorry 

https://github.com/etcd-io/etcd/pull/15159

**Comment by geetasg** [comment]
Thanks Marek.
