### ISSUE TITLE
etcd_network_peer_round_trip_time_seconds_bucket problem

### ISSUE THREAD

**Issue by xiexg** [etcd-io/etcd#15089]
### What happened?

“etcd_network_peer_round_trip_time_seconds_bucket“ output contains information about old members， content like:
etcd_network_peer_round_trip_time_seconds_bucket{To="111584258b110ef8",le="0.0001"} 0
etcd_network_peer_round_trip_time_seconds_bucket{To="111584258b110ef8",le="0.0002"} 0
etcd_network_peer_round_trip_time_seconds_bucket{To="111584258b110ef8",le="0.0004"} 0
......

the member id "111584258b110ef8" is old member, it's been deleted for a long time
why is old member information displayed in monitoring data？

### What did you expect to happen?

The old member has been deleted and should not appear in the monitoring data

### How can we reproduce it (as minimally and precisely as possible)?

View metrics monitoring data，etcd_network_peer_round_trip_time_seconds_bucket output content

### Etcd version (please run commands below)

version：3.4.3

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by lavacat** [comment]
Most likely you are running into the fact that prometheus doesn't allow to delete [labels](https://stackoverflow.com/questions/43207960/deleting-labels-in-prometheus). So you need to control it with data retention.

But there is also a chance that [monitorProbingStatus](https://github.com/etcd-io/etcd/blob/e2d67f2e3bfa6f72178e26557bb22cc1482c418c/server/etcdserver/api/rafthttp/probing_status.go#L94) isn't properly stopped. I'll try to reproduce this is the test.

**Comment by ahrtr** [comment]
Note that there is no way to remove metrics history, if you restart etcd instance and read metrics from the etcd instance directly, then the stale metrics should disappear automatically. But if you have a centralized prometheus server, then it depends on how long history data you preserve.
