### ISSUE TITLE
Do not literally compare IPv6 addresses

### ISSUE THREAD

**Issue by WilliamDEdwards** [etcd-io/etcd#15127]
### What happened?

etcd can't bootstrap a cluster because the IPv6 address in `ETCD_INITIAL_CLUSTER` does not literally match the one in `ETCD_INITIAL_ADVERTISE_PEER_URLS`, even though it's the same IPv6 address.

Error:

```
--initial-cluster has etcd1.cyberfusion.cloud=https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380 but missing from --initial-advertise-peer-urls=https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380 ("https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380"(resolved from "https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380") != "https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380"(resolved from "https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380"))
```

`2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a` != `2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a` (the `0` misses from `0e5f`).

### What did you expect to happen?

The cluster should be bootstrapped. etcd should not compare IPv6 addresses literally.

### How can we reproduce it (as minimally and precisely as possible)?

See 'Etcd configuration (command line flags or environment variables)'.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.3.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.15.9
Go OS/Arch: linux/amd64

$ etcdctl version
No help topic for 'version'
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

```
ETCD_INITIAL_CLUSTER="etcd0=https://[2a0c:eb00:0:f7:ec83:5509:1618:8a97]:2380,etcd1=https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380,etcd2=https://[2a0c:eb00:0:f7:6b30:74f7:ef4e:6ada]:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380"
```

</details>

**Comment by ahrtr** [comment]
It seems that the [URLStringsEqual](https://github.com/etcd-io/etcd/blob/09b56633012bd1cf0af15c0502240b33c776fd28/pkg/netutil/netutil.go#L184) or [urlsEqual](https://github.com/etcd-io/etcd/blob/09b56633012bd1cf0af15c0502240b33c776fd28/pkg/netutil/netutil.go#L147) doesn't handle IPv6 correctly. 

It looks like a good first issue.

**Comment by Kidsan** [comment]
@WilliamDEdwards does my linked PR address your issue?

**Comment by WilliamDEdwards** [comment]
I am unable to test any PRs at the moment.

I would like to ask you not to use my IPv6 addresses in `netutil_test.go` though ;)

**Comment by Kidsan** [comment]
@WilliamDEdwards good point, fixed!
