### ISSUE TITLE
Typo in issue form: ‘blow’

### ISSUE THREAD

**Issue by WilliamDEdwards** [etcd-io/etcd#15134]
### What happened?

The issue form contains the following question:

> Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

It should say:

> Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

### What did you expect to happen?

N/A

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Etcd version (please run commands below)

N/A

### Etcd configuration (command line flags or environment variables)

N/A

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

N/A

**Comment by ahrtr** [comment]
Thanks for raising this issue. 

Please feel free to deliver a PR to update https://github.com/etcd-io/etcd/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml

**Comment by Niravprajapati1** [comment]
Can i work on this issue ?

**Comment by WilliamDEdwards** [comment]
> Can i work on this issue ?

It’s open source.

**Comment by ahrtr** [comment]
> Can i work on this issue ?

Thanks @Niravprajapati1 . Assigned to you.
