### ISSUE TITLE
EtcdServer can not start 

### ISSUE THREAD

**Issue by xiaofan-luan** [etcd-io/etcd#15136]
### What happened?

![image](https://user-images.githubusercontent.com/83447078/213062984-efd6985c-aba9-47cf-ae55-6ec9595758f1.png)

The etcd service exited and could not be started with the above error message.

similar issues at https://github.com/etcd-io/etcd/issues/11444， any suggestions？

### What did you expect to happen?

Should be recovered as expected.

### How can we reproduce it (as minimally and precisely as possible)?

we can offer etcd data files if necessary

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by xiaofan-luan** [comment]
> Just check the log of your case, change the data-dir to "700" ( chmod 700 data-dir ), and try to restart the etcd again ?
> 
> ![image](https://user-images.githubusercontent.com/1438526/213101459-e4dcf407-eb7c-4ddf-b857-6d90c29ebdf0.png)

Thanks, let us check~

**Comment by serathius** [comment]
This is on version v3.5.0, which is known to have multiple critical issues. Please upgrade.
