### ISSUE TITLE
etcd gateway does not split IPv6 address and port

### ISSUE THREAD

**Issue by WilliamDEdwards** [etcd-io/etcd#15143]
### What happened?

etcd gateway incorrectly parses IPv6 addresses.

When the IPv6 address is written in brackets, and the port is placed after the brackets, they are mistakenly concatenated. The resulting string (IPv6 address + colon + port) is regarded as the IPv6 address.

This causes the following error:

    deactivated endpoint [2a0c:eb00:0:f7:6b30:74f7:ef4e:6ada:2379] due to dial tcp: address 2a0c:eb00:0:f7:6b30:74f7:ef4e:6ada:2379: too many colons in address for 1m0s

### What did you expect to happen?

The IPv6 address and port should not be concatenated.

### How can we reproduce it (as minimally and precisely as possible)?

```
etcd gateway start --endpoints "[2a0c:eb00:0:f7:ec83:5509:1618:8a97]:2379"
```

### Anything else we need to know?

Omitting the port is not possible. See https://github.com/etcd-io/etcd/issues/15144.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.3.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.15.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.3.25
API version: 3.3
```

</details>

### Etcd configuration (command line flags or environment variables)

N/A

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

N/A

**Comment by shogohida** [comment]
Hi @WilliamDEdwards, can I work on this issue?

**Comment by WilliamDEdwards** [comment]
> Hi @WilliamDEdwards, can I work on this issue?

I'm not planning on it.

**Comment by Avinashanakal** [comment]
hey @WilliamDEdwards can i look into this bug?

**Comment by sanmai-NL** [comment]
@Avinashanakal I think @WilliamDEdwards indicates everyone is free to do that, he just reported this issue.

**Comment by gdhuper** [comment]
@WilliamDEdwards Could you provide more details on how to reproduce this? I tried the repro steps but I do not see the same error message. Even tried with the `3.3.25` version.

**Comment by WilliamDEdwards** [comment]
> @WilliamDEdwards Could you provide more details on how to reproduce this? I tried the repro steps but I do not see the same error message. Even tried with the `3.3.25` version.

The only relevant detail that I can think of: the Debian stable package is used.

**Comment by anirudhRowjee** [comment]
Likewise - I cannot reproduce this either on the git build or on the debian stable version (as shown in the reproduce steps, following a `sudo apt install etcd`).
(I'm running Pop! 22.04)

**Comment by bartossh** [comment]
When I am building the version tagged as 3.3.25 according to the docs using `./build` script I produce this:
```
➜  etcd git:(v3.3.25) ✗ ./build             
➜  etcd git:(v3.3.25) ✗ ./bin/etcd --version
etcd Version: 3.3.27
Git SHA: 2c834459e
Go Version: go1.20.1
Go OS/Arch: linux/amd64
➜  etcd git:(v3.3.25) ✗ ./bin/etcd gateway start --endpoints "[2a0c:eb00:0:f7:ec83:5509:1618:8a97]:2379"
2023-02-16 13:36:45.904700 E | etcdmain: forgot to set Type=notify in systemd service file?
2023-02-16 13:36:45.904776 I | proxy/tcpproxy: ready to proxy client requests to [2a0c:eb00:0:f7:ec83:5509:1618:8a97:2379]
```

It looks like the port gets into the brackets. 
I cannot understand why I have a different version than the tag. 
The rest looks like an issue.

**Comment by serathius** [comment]
v3.3.X is no longer supported.
