### ISSUE TITLE
Plan for v3.5.7 release

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15141]
### What would you like to be added?

Changes included in v3.5.7:
* https://github.com/etcd-io/etcd/pull/14852
* https://github.com/etcd-io/etcd/pull/14884
* https://github.com/etcd-io/etcd/pull/14852
* https://github.com/etcd-io/etcd/pull/14899
* https://github.com/etcd-io/etcd/pull/15069
* https://github.com/etcd-io/etcd/pull/15096
* https://github.com/etcd-io/etcd/pull/14995
* https://github.com/etcd-io/etcd/pull/15016
* https://github.com/etcd-io/etcd/pull/15037
* https://github.com/etcd-io/etcd/pull/15018
* https://github.com/etcd-io/etcd/pull/15019

Pending PRs for reelase-3.5 branch.
* https://github.com/etcd-io/etcd/pull/14864

Open bugs for v3.5 (might skip some if they are not critical and not resolved in reasonable time):
* https://github.com/etcd-io/etcd/issues/14931
* https://github.com/etcd-io/etcd/issues/14894
* https://github.com/etcd-io/etcd/issues/14653
* https://github.com/etcd-io/etcd/issues/14631
* https://github.com/etcd-io/etcd/issues/14362
* https://github.com/etcd-io/etcd/issues/14252

Please let me know if I missed some issue. 

### Why is this needed?

Triaging issues to ensure that all important change are included and documented in changelog.

**Comment by ahrtr** [comment]
Thanks @serathius . 

None of the open bugs is blocker to 3.5.7.  We can get them fixed in the next patch. I think we are ready to release 3.5.7.

**Comment by ahrtr** [comment]
FYI. I manually verified that the etcd image built from branch `release-3.5` is working well.

**Comment by serathius** [comment]
Release published https://github.com/etcd-io/etcd/releases/tag/v3.5.7
