### ISSUE TITLE
v3.5.0 panic: runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by jaime0815** [etcd-io/etcd#15140]
### What happened?

![image](https://user-images.githubusercontent.com/4024711/213143204-59725f83-4be9-48c3-ae58-944ce76a28a7.png)

### What did you expect to happen?

restore finished normally..

### How can we reproduce it (as minimally and precisely as possible)?

No idea

### Etcd version (please run commands below)

v3.5.0

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jaime0815** [comment]
related to #11444

**Comment by serathius** [comment]
v3.5.0 has multiple known issues, including multiple critical ones. Please upgrade to v3.5.6

Feel free to reopen the issue if you reproduce it on newer version.

**Comment by jaime0815** [comment]
I try to print illegal keys and skip them.
![image](https://user-images.githubusercontent.com/4024711/213144298-4195e8c8-2f27-437a-a6d8-f7a98f551e52.png)

All illegal keys are system key words of ETCD, It is so wired, such https://github.com/etcd-io/etcd/blob/946a5a6f25c3b6b89408ab447852731bde6e6289/server/mvcc/buckets/bucket.go#L23 key words as key save into Key bucket

[long_text_2023-01-18-17-28-12.txt](https://github.com/etcd-io/etcd/files/10444638/long_text_2023-01-18-17-28-12.txt)
