### ISSUE TITLE
etcd gateway requires port, but not documented

### ISSUE THREAD

**Issue by WilliamDEdwards** [etcd-io/etcd#15144]
### What happened?

etcd gateway requires each endpoint to contain a port.

However, according to the documentation, specifying the port is optional.

### What did you expect to happen?

When the port is not specified, it should default to 2379.

The [documentation](https://etcd.io/docs/v3.3/op-guide/gateway/#start-etcd-gateway) implies that this is the intended behaviour, as the example command (`etcd gateway start --endpoints=infra0.example.com,infra1.example.com,infra2.example.com`) does not contain ports.

### How can we reproduce it (as minimally and precisely as possible)?

See 'What did you expect to happen?'.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.3.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.15.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.3.25
API version: 3.3
```

</details>

### Etcd configuration (command line flags or environment variables)

N/A

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

N/A

**Comment by jmhbnz** [comment]
This looked like it might be a good first issue for someone new to the project so I have had a go at raising a pull request with a fix to ensure a port  would be defaulted if not supplied #15148.
