### ISSUE TITLE
Remove /bin/sh from documenation and release text

### ISSUE THREAD

**Issue by nberlee** [etcd-io/etcd#15173]
### What happened?

`/bin/sh` got removed in a patch version (3.5.7): https://github.com/etcd-io/etcd/pull/15016

### What did you expect to happen?

* Change the documententation page https://etcd.io/docs/v3.5/op-guide/container/#docker to not use `/bin/sh`
* Change the RELEASE text of 3.5.7: https://github.com/etcd-io/etcd/releases/tag/v3.5.7
```
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcd --version"
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcdctl version"
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcdutl version"
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcdctl endpoint health"
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcdctl put foo bar"
docker exec etcd-gcr-v3.5.7 /bin/sh -c "/usr/local/bin/etcdctl get foo"
```
to:
```
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcd --version
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcdctl version
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcdutl version
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcdctl endpoint health
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcdctl put foo bar
docker exec etcd-gcr-v3.5.7 /usr/local/bin/etcdctl get foo
```

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

I am all for minimalistic containers, but please consider these changes for a minor version, not a patch version. A lot of stuff can break. See my changes in for example `etcd-operator`:  https://github.com/on2itsecurity/etcd-operator/commit/14c27ceb08b2bd496546fbcddcd0e20ee6958e58

### Etcd version (please run commands below)

3.5.7

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Thanks @nberlee for raising this issue.  Please anyone feel free to deliver a PR to update [container.md](https://github.com/etcd-io/website/blob/main/content/en/docs/v3.6/op-guide/container.md).



> A lot of stuff can break. See my changes in for example `etcd-operator`: [on2itsecurity/etcd-operator@14c27ce](https://github.com/on2itsecurity/etcd-operator/commit/14c27ceb08b2bd496546fbcddcd0e20ee6958e58)

Sorry for that. We removed the dependency on busybox due to license issue, and also removed /bin/sh as well.. FYI. https://github.com/etcd-io/etcd/issues/15034

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/website/pull/640

**Comment by ahrtr** [comment]
@serathius please change the RELEASE text of 3.5.7 to remove `/bin/sh`,  please read https://github.com/etcd-io/etcd/issues/15173#issue-1553886579

**Comment by chetanguptaa** [comment]
can I do it? #15173

**Comment by ahrtr** [comment]
> @serathius please change the RELEASE text of 3.5.7 to remove `/bin/sh`, please read [#15173 (comment)](https://github.com/etcd-io/etcd/issues/15173#issue-1553886579)

Just updated it myself.




> can I do it? #15173

This issue has already resolved. Thank you anyway.
