### ISSUE TITLE
etcd downgrade support

### ISSUE THREAD

**Issue by logicalhan** [etcd-io/etcd#15184]
### What would you like to be added?

I would like the ability to downgrade etcd, given the [host of issues we've discovered in 3.5](https://github.com/etcd-io/etcd/blob/main/Documentation/postmortems/v3.5-data-inconsistency.md#action-items). 

### Why is this needed?

https://github.com/etcd-io/etcd/blob/main/Documentation/postmortems/v3.5-data-inconsistency.md#action-items

**Comment by serathius** [comment]
Duplicates https://github.com/etcd-io/etcd/issues/13168 and https://github.com/etcd-io/etcd/issues/11716
