### ISSUE TITLE
All docker images of Architecture show amd64

### ISSUE THREAD

**Issue by zhangguanzhang** [etcd-io/etcd#15266]
### What happened?

```
$ docker pull quay.io/coreos/etcd:v3.5.7-arm64
$ docker inspect quay.io/coreos/etcd:v3.5.7-arm64  --format '{{.Architecture}}'
amd64
```

### What did you expect to happen?

```
$ docker pull quay.io/coreos/etcd:v3.5.7-arm64
$ docker inspect quay.io/coreos/etcd:v3.5.7-arm64  --format '{{.Architecture}}'
aarch64
```

### How can we reproduce it (as minimally and precisely as possible)?

```
bash scripts/build-release.sh main
docker  inspect quay.io/coreos/etcd:main-arm64  --format '{{.Architecture}}'
```

### Etcd version (please run commands below)

<details>
all the version

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by sober-wang** [comment]
I'm try use --platform when pull this aarch64 image  .
```shell
docker pull quay.io/coreos/etcd:v3.5.7-arm64 --platform=aarch64
docker inspect quay.io/coreos/etcd:v3.5.7-arm64 --format '{{.Architecture}}'                                                                                                                         amd64
```

: (

**Comment by zhangguanzhang** [comment]
> 
```
$ docker pull quay.io/coreos/etcd:v3.5.7-arm64 --platform=aarch64
v3.5.7-arm64: Pulling from coreos/etcd
Digest: sha256:82aa51752864de767380d9d5770f5628d2f68a561f7c98c65ae13f69cd4440af
Status: Image is up to date for quay.io/coreos/etcd:v3.5.7-arm64
quay.io/coreos/etcd:v3.5.7-arm64
$ docker images | grep v3.5.7
quay.io/coreos/etcd                                v3.5.7-arm64                   91fed2f97665   2 weeks ago      55.4MB
$ docker inspect quay.io/coreos/etcd:v3.5.7-arm64 --format '{{.Architecture}}' 
amd64
```
????

**Comment by serathius** [comment]
cc @justinsb

**Comment by justinsb** [comment]
@serathius  Do you think we should try creating new & simplified build scripts, as we were chatting about?

**Comment by serathius** [comment]
The scripts you linked looks nice (https://github.com/etcd-io/etcd/compare/main...justinsb:etcd:simpler_dist), if only you could integrate them with existing release/build scripts to avoid duplication.

**Comment by pchan** [comment]
@zhangguanzhang Should this be backported to 3.4 ? See https://github.com/etcd-io/etcd/pull/15609 for context. cc: @ahrtr

**Comment by ahrtr** [comment]
> @zhangguanzhang Should this be backported to 3.4 ? See #15609 for context. cc: @ahrtr

Yes, please see https://github.com/etcd-io/etcd/issues/15680. Please anyone feel free to backport it. Or let me take care of it tomorrow my time.
