### ISSUE TITLE
Rename linearizability tests

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15285]
### What would you like to be added?

Would like gather proposals for new name for linerazibility tests. My proposal would be [Model tests](https://en.wikipedia.org/wiki/Model-based_testing). This term is much easier to comprehend and  already exists in testing terminology. Also when trying to document the framework I found myself using it more often. https://github.com/etcd-io/etcd/pull/14838/files 

Expected changes:
* `tests/linearizability` -> `tests/model`

### Why is this needed?

Linearizability is a property of distributed system, however it's not a term used in context of testing. Not everyone is familiar with concept of linearizability so it creates a steep learning curve for new contributors.

**Comment by serathius** [comment]
cc @ahrtr @ptabor @lavacat

**Comment by serathius** [comment]
cc @mitake @spzala

**Comment by ptabor** [comment]
Ideas: 
  - reliability tests    
         ("the quality of being trustworthy or of performing consistently well")
         ("the degree to which the result of a measurement, calculation, or specification can be depended on to be accurate.")
  - guarantees tests  
  - semantic tests

**Comment by ahrtr** [comment]
`reliability test` or `robustness test`

**Comment by mitake** [comment]
How about `concurrency test` or `failure-scenario test`?

**Comment by spzala** [comment]
I think the word `Model` can be mixed up with AI models specially with it being in so much in focus lately :). All good suggestions so far, I like the `reliability test` better if we want to keep it easy to understand by anyone.

**Comment by chaochn47** [comment]
Vote for `Robustness testing` https://en.wikipedia.org/wiki/Robustness_testing

**Comment by serathius** [comment]
Looks like `Model` is not as popular as I expected :(. 

> I think the word `Model` can be mixed up with AI models specially with it being in so much in focus lately :).

The name would make sense as this is the same concept. Create a separate simplified representation of the real thing. 

I would go with `robustness test` proposed by @ahrtr. Like @chaochn47 pointed out it's an existing concept (at least on wikipedia) and has some existing research in this area https://link.springer.com/chapter/10.1007/11430230_23. Nice to know other people came with the same idea.

**Comment by serathius** [comment]
Let's go with robustness tests!
