### ISSUE TITLE
change default listen-urls to 0.0.0.0

### ISSUE THREAD

**Issue by jonboulle** [etcd-io/etcd#1529]
Following up from #1308, it will greatly simplify the default/basic use case if we listen on all interfaces by default if the `listen-urls-` flags are unset. (The `advertise-` flags should continue to be explicit.)

We should be careful to communicate the security implications, i.e. make users aware that etcd is accessible on all interfaces if the flag is not supplied.

**Comment by analytically** [comment]
+1
