### ISSUE TITLE
Linearizability test duplicate event mod revision

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15317]
### Which github workflows are flaking?

Linearizability & Linearizability Nightly

### Which tests are flaking?

TestLinearizability/Issue14370 x2 https://github.com/etcd-io/etcd/actions/runs/4173051956/jobs/7224915747 https://github.com/etcd-io/etcd/actions/runs/4172783085/jobs/7224313444
TestLinearizability/Issue14685 x3 https://github.com/etcd-io/etcd/actions/runs/4172779926/jobs/7224306295 https://github.com/etcd-io/etcd/actions/runs/4167747802/jobs/7213715136 https://github.com/etcd-io/etcd/actions/runs/4172334944/jobs/7223305362
 
 

### Github Action link

Above

### Reason for failure (if possible)

```
watch.go:105: Expect event revision to grow by 1, last: 198, mod: 198
```

I think the reason is that watch validation assumes one operation per revision. This is almost true, however exception is LeaseRevoke which might delete multiple keys bound to single lease.

### Anything else we need to know?

Will implement the fix.
cc @ahrtr @ptabor

**Comment by serathius** [comment]
On second thought I don't think the tests that flaked here could be impacted by leases. Those two specific scenarios do not use traffic that uses leases. I will fix the duplicate mod revision and wait for more data.

**Comment by ptabor** [comment]
Maybe it makes sense to print the type/key of the problematic Watch event to have more clue in case of such problems.

**Comment by serathius** [comment]
Please see https://github.com/etcd-io/etcd/pull/15282
It add dumping whole watch response history into json file.

**Comment by ahrtr** [comment]
Can we close this issue since https://github.com/etcd-io/etcd/pull/15318 is already merged?

**Comment by serathius** [comment]
> Can we close this issue since #15318 is already merged?

It's not clear if duplicate operations could be caused by lease as they were not present in the scenario that flaked. We relaxed the revision validation in https://github.com/etcd-io/etcd/pull/15318, however I think there might still be incorrect behavior. I'm considering adding validation for duplicate watch events.

**Comment by serathius** [comment]
Added https://github.com/etcd-io/etcd/pull/15324
Let's wait for couple of runs of linearizability tests. Maybe one nightly run too.

**Comment by serathius** [comment]
No issues with duplicated event mod revision since yesterday
