### ISSUE TITLE
Incorrect etcd docker images architecture - amd64 images tagged as arm64

### ISSUE THREAD

**Issue by southwolf** [etcd-io/etcd#15334]
### What happened?

When I pulled etcd docker images from both `quay.io/coreos/etcd` and `gcr.io/etcd-development/etcd`, I cannot run it in Apple Silicon (arm64). So I inspected the image and saw the images are actually `amd64`

```bash
docker pull quay.io/coreos/etcd:v3.5.7-arm64
docker image inspect quay.io/coreos/etcd:v3.5.7-arm64
```

Result output: `"Architecture": "amd64"` (See detailed output below)

### What did you expect to happen?

The image should be correctly build with multiple archs

### How can we reproduce it (as minimally and precisely as possible)?

```bash
docker pull quay.io/coreos/etcd:v3.5.7-arm64
docker image inspect quay.io/coreos/etcd:v3.5.7-arm64
```

### Etcd version (please run commands below)

 v3.5.7

### Relevant log output

```shell
[
    {
        "Id": "sha256:82aa51752864de767380d9d5770f5628d2f68a561f7c98c65ae13f69cd4440af",
        "RepoTags": [
            "quay.io/coreos/etcd:v3.5.7-arm64"
        ],
        "RepoDigests": null,
        "Parent": "",
        "Comment": "",
        "Created": "0001-01-01T00:00:00Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Platform": {
                "architecture": "",
                "os": ""
            },
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "2379/tcp": {},
                "2380/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
            ],
            "Cmd": [
                "/usr/local/bin/etcd"
            ],
            "Image": "",
            "Platform": {
                "architecture": "",
                "os": ""
            },
            "Volumes": null,
            "WorkingDir": "/var/lib/etcd/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 17815786,
        "VirtualSize": 17815786,
        "GraphDriver": {
            "Data": null,
            "Name": "stargz"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:cb60fb9b862c6a89f92e484bc3b72bbc0352b41166df5c4a68bfb52f52504a7d",
                "sha256:2a5e682f294921b78ca9d1143a1b4aa6f709091201d8e7d7f0697f1ffb21639d",
                "sha256:2dd855ed263e373bb7e4249e0a4b5578456c8d218a84ae0fa2374c409f7c3646",
                "sha256:a7e41bf22b8f61875c832a8f77cce4bf19c598725427e0d0b065be5ea831f561",
                "sha256:ca2fc5fccb847adef977f18926c09407f6267e05b865f3003fe8558d342c57d7",
                "sha256:5e21f6018dfd9b1395851392f9a79d4bafdf1d7bc795973ec434a1dc7574c4c8"
            ]
        },
        "Metadata": {
            "LastTagTime": "2023-02-17T09:30:29.740780631Z"
        }
    }
]
```

**Comment by geetasg** [comment]
Confirmed repro using steps provided in the issue
docker pull quay.io/coreos/etcd:v3.5.7-arm64
docker image inspect quay.io/coreos/etcd:v3.5.7-arm64 --format '{{.Architecture}}'
amd64


Tested the docker file in etcd repo - architecture ok

[root@ip-172-31-2-51 etcd]# docker build -f Dockerfile-release.arm64 -t geetasg/etcd --no-cache bin
Sending build context to Docker daemon  2.523GB
Step 1/8 : FROM --platform=linux/arm64 gcr.io/distroless/static-debian11
 ---> b1f6671512b6
Step 2/8 : ADD etcd /usr/local/bin/
 ---> 60c0e114dc99
Step 3/8 : ADD etcdctl /usr/local/bin/
 ---> 92f007b321ba
Step 4/8 : ADD etcdutl /usr/local/bin/
 ---> a4032c8cb3a7
Step 5/8 : WORKDIR /var/etcd/
 ---> Running in 47b06fd6a84f
Removing intermediate container 47b06fd6a84f
 ---> 7dd8e124a56c
Step 6/8 : WORKDIR /var/lib/etcd/
 ---> Running in d45bee99e198
Removing intermediate container d45bee99e198
 ---> 685a592c42e3
Step 7/8 : EXPOSE 2379 2380
 ---> Running in 38d530a56710
Removing intermediate container 38d530a56710
 ---> 711f279e78ab
Step 8/8 : CMD ["/usr/local/bin/etcd"]
 ---> Running in 6b4d0f7eed85
Removing intermediate container 6b4d0f7eed85
 ---> d8d3bc78f9fb
Successfully built d8d3bc78f9fb
Successfully tagged geetasg/etcd:latest

[root@ip-172-31-2-51 etcd]# docker inspect geetasg/etcd:latest --format '{{.Architecture}}'
arm64


Investigating how  quay.io/coreos/etcd:v3.5.7 is published. /cc @serathius @ahrtr

**Comment by geetasg** [comment]
looks related  - https://github.com/etcd-io/etcd/issues/15266

**Comment by ahrtr** [comment]
Duplicated to https://github.com/etcd-io/etcd/issues/15266

**Comment by southwolf** [comment]
Thanks. Weird I searched but did not see that issue.
