### ISSUE TITLE
Should we version pin or use latest for govulncheck action?

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15355]
### What would you like to be added?

We have a github action to check for known vulnerabilities that affect Go code `.github/workflows/govuln.yaml`.

Currently this is version pinned to a specific release in late last year as it looks like at that time there was no `@latest`. Refer: https://github.com/etcd-io/etcd/commit/808099dc2483803ea1cf881b6054a26315431f41

There have been some recent releases for `govulncheck` and it's not something that we have dependabot etc picking up. Given this is security related I think we should try and stay up to date so should we revert to using `latest` or should I just raise a PR to maintain the version pin?

Alternatively if someone knows of an easy way to get dependabot or something similar to pick it up please outline below.

### Why is this needed?

Keeping up to date with static security analysis for project go code.

**Comment by ahrtr** [comment]
Thanks @jmhbnz . Please feel free to deliver a PR for this.
