### ISSUE TITLE
Flacky test TestLeasingDeleteRangeContendTxn

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15352]
### Which github workflows are flaking?

Failed in the forked repo github workflow https://github.com/chaochn47/etcd/actions/runs/4258007188/jobs/7408759584

The flacky test has been mentioned in the PR comment https://github.com/etcd-io/etcd/pull/14918#issuecomment-1344137224 and it still can be reproduced now. 

### Which tests are flaking?

TestLeasingDeleteRangeContendTxn

### Anything else we need to know?

Reproduced in the local box

```
cd tests

taskset -c 1 go test -v -failfast -count=100 -run TestLeasingDeleteRangeContendTxn  ./integration/clientv3/lease
```

**Comment by serathius** [comment]
Thanks for report and repro!

**Comment by tjungblu** [comment]
> leasing_test.go:1313: #0: expected [key:"key/0" create_revision:1120 mod_revision:1121 version:2 value:"123" ], got [key:"key/0" create_revision:1120 mod_revision:1120 version:1 value:"123" ]

just adding another error message here, in the test linked above the result was empty [].
