### ISSUE TITLE
Support for Codespaces and remote container development

### ISSUE THREAD

**Issue by craiglpeters** [etcd-io/etcd#15377]
### What would you like to be added?

I would like to add a dev container (https://containers.dev) to the repository to help make working in the project easy in GitHub Codespaces and VS Code Remote Containers easy.

### Why is this needed?

This configuration will make it easy for new community members to be able to make contributions easily by eliminating the need to download or configure any dependencies. This a simple motion on GitHub, contributors and maintainers will be able to have a cloud hosted development environment up and running in minutes, with monthly free usage. Additionally the dev container cli and VS Code support for development containers means that anyone can run the same container locally.

**Comment by jmhbnz** [comment]
Have raised an initial propose for this, please let me know if you have any feedback.

/assign @jmhbnz
