### ISSUE TITLE
Update error message for ErrGRPCNoSpace to include user direction

### ISSUE THREAD

**Issue by geetasg** [etcd-io/etcd#15406]
### What would you like to be added?

Update error message for ErrGRPCNoSpace to include user direction

Current message is "etcdserver: mvcc: database space exceeded"

Update proposal is "etcdserver: mvcc: database space exceeded. Please delete unwanted objects"

### Why is this needed?

Current error message does not prompt for user action. New error message will guide the user.

Example of user experience with the new message -

```
[prompt]# ./run_a_pod
++ kubectl run ng2 --image=nginx --restart=Never
Error from server: rpc error: code = ResourceExhausted desc = etcdserver: mvcc: database space exceeded. Please delete unwanted objects
```

**Comment by geetasg** [comment]
Please let me know if anyone has questions/suggestions on this request. I can submit the PR.
/cc @chaochn47  

code change notes -
```
git diff
diff --git a/api/v3rpc/rpctypes/error.go b/api/v3rpc/rpctypes/error.go
index 350bec16b..96515a412 100644
--- a/api/v3rpc/rpctypes/error.go
+++ b/api/v3rpc/rpctypes/error.go
@@ -29,7 +29,7 @@ var (
        ErrGRPCDuplicateKey  = status.New(codes.InvalidArgument, "etcdserver: duplicate key given in txn request").Err()
        ErrGRPCCompacted     = status.New(codes.OutOfRange, "etcdserver: mvcc: required revision has been compacted").Err()
        ErrGRPCFutureRev     = status.New(codes.OutOfRange, "etcdserver: mvcc: required revision is a future revision").Err()
-       ErrGRPCNoSpace       = status.New(codes.ResourceExhausted, "etcdserver: mvcc: database space exceeded").Err()
+       ErrGRPCNoSpace       = status.New(codes.ResourceExhausted, "etcdserver: mvcc: database space exceeded. Please delete unwanted objects").Err()

        ErrGRPCLeaseNotFound    = status.New(codes.NotFound, "etcdserver: requested lease not found").Err()
```

**Comment by ahrtr** [comment]
Deleting unwanted objects might not be a proper action. 

Please read https://github.com/ahrtr/etcd-issues/blob/master/docs/troubleshooting/how_to_debug_large_db_size_issue.md

**Comment by ahrtr** [comment]
Or https://etcd.io/blog/2023/how_to_debug_large_db_size_issue/

**Comment by chaochn47** [comment]
> If the behavior (db size exceeds the quota) isn’t expected, then you’d better figure out the root cause and resolve it firstly. If you insist on applying solutions mentioned above, it can mitigate the issue instead of resolving it.
Quoted from the blog post https://etcd.io/blog/2023/how_to_debug_large_db_size_issue/

I think It's a shared responsibility between etcd/kubernetes users and managed etcd service/platform. 

User will delete unwanted objects based on the error message and the platform will compact and defrag the db to fit in `quota`.

**Comment by geetasg** [comment]
How about - 
"etcdserver: mvcc: database space exceeded. Please delete unwanted objects. Space will be freed up after compaction and defragmentation"

The request is to guide towards recovery.

**Comment by cenkalti** [comment]
How about putting a tiny link to the blog post?
https://etcd.io/blog/2023/how_to_debug_large_db_size_issue/

**Comment by ahrtr** [comment]
When running into "etcdserver: mvcc: database space exceeded", usually it means something wrong happened. For example, I saw a couple of times that CNI issue caused K8s to generate huge number of events, eventually hitting etcd space quota. The top priority is to figure out the root cause in this case.

It's also possible that etcd space quota (e.g. the default 2GB) doesn't meet scale requirement. In this case, what users need to do is tuning `--quota-backend-bytes`.

Deleting unwanted objects might mitigate the issue a little bit, but I really don't think it's the point. I do not against mentioning compaction and defragmentation, but it seems not a big deal.

**Comment by serathius** [comment]
Discussed during community meeting. Conclusion was that we should not put playbooks into error codes.
