### ISSUE TITLE
fuzzy query for etcd 

### ISSUE THREAD

**Issue by shdluan** [etcd-io/etcd#15407]
### What would you like to be added?

support fuzzy query for etcd

### Why is this needed?

For etcd query in my work, fuzzy query is needed at many times.
But I found that the etcd does not support fuzzy query by now.
So, I must get all the data and then matching query data I needed.
I wonder if there is a plan for etcd to support fuzzy query?

**Comment by serathius** [comment]
No, etcd is a key value store, it is not designed to support fuzz query which is characteristic element of document databases.
