### ISSUE TITLE
Bump golang 1.19.7

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15426]
### What would you like to be added?

golang 1.19.7 includes a security fix.

FYI. https://groups.google.com/g/golang-dev/c/3wmx8i5WvNY/m/AEOlccrGAwAJ?utm_medium=email&utm_source=footer

### Why is this needed?

Improve security.

**Comment by serathius** [comment]
Don't think the email link works :P

**Comment by ahrtr** [comment]
> Don't think the email link works :P

Updated. I meant to paste google group link.

**Comment by jmhbnz** [comment]
Happy to pick this up, have raised for main :)

/assign @jmhbnz

**Comment by ahrtr** [comment]
Completed.
