### ISSUE TITLE
Provide TLS 1.3 support for 3.5.

### ISSUE THREAD

**Issue by ramses** [etcd-io/etcd#15436]
### What would you like to be added?

TLS 1.3 support was (re-)added to the main branch in https://github.com/etcd-io/etcd/pull/15156

... thus resolving https://github.com/etcd-io/etcd/issues/13506

However, organizations running etcd 3.4 and 3.5 are starting to require TLS 1.3 for security compliance.

---

The "3.4 version" analogue issue: https://github.com/etcd-io/etcd/issues/15437

### Why is this needed?

As stated above, organizations running etcd 3.4 and 3.5 are starting to require TLS 1.3 for security compliance. Also, waiting for etcd 3.6 is not compatible with their timelines.

**Comment by serathius** [comment]
LGTM
cc @ptabor @spzala @ahrtr

**Comment by ahrtr** [comment]
Makes sense to me. Please feel free to deliver a PR, thx

**Comment by jmhbnz** [comment]
Initial backport pr merged and docs pr open here https://github.com/etcd-io/website/pull/650.

I will raise pr for 3.5.8 changelog shortly, quick question @ahrtr the change touches several aspects of the codebase, do you want just one section updated in the changelog, or under all impacted?

/assign
/remove help

**Comment by ahrtr** [comment]
> I will raise pr for 3.5.8 changelog shortly, quick question @ahrtr the change touches several aspects of the codebase, do you want just one section updated in the changelog, or under all impacted?

NO strong opinion on this. Only adding changelog item for etcdserver seems OK to me. Please backport the PR to 3.4 as well if you have bandwitdh, and after changelog for both 3.5 and 3.4 afterwards. thx.
