### ISSUE TITLE
grpc load balancing algorithm supports strategies

### ISSUE THREAD

**Issue by Aaron-PanJi** [etcd-io/etcd#15442]
### What would you like to be added?

The grpc load balancing algorithm should supports the different strategies such as using master or slave first

### Why is this needed?

The current grpc load balancing algorithm only supports polling.

**Comment by ptabor** [comment]
Please reopen the issue with more detailed description. For now it's not clear whether: 
 - you ask about etcd-client -> etcd communication, the strategy is a 'round robin'. 
       https://github.com/etcd-io/etcd/blob/e2a5df534cf6b0a12859e61bfc2758d56a1e1971/client/v3/internal/resolver/resolver.go#L44

  - https://github.com/etcd-io/etcd/blob/main/client/v3/naming/doc.go package where etcd is used as source of endpoints. In such situation the LB strategy is outside of scope of etcd.
