### ISSUE TITLE
The txn command of etcdctl does not have any effective help information

### ISSUE THREAD

**Issue by Aaron-PanJi** [etcd-io/etcd#15441]
### What happened?

The txn command of etcdctl does not have any effective help information, nor does it have automatic completion and other promotion information.
Help info is no help
![image](https://user-images.githubusercontent.com/120549770/224209562-adb571df-f502-44c2-9a33-0e331a05eed9.png)

### What did you expect to happen?

No promotion information.
![image](https://user-images.githubusercontent.com/120549770/224209692-0cccf1f9-3705-415b-800d-60baa015bc79.png)

### How can we reproduce it (as minimally and precisely as possible)?

Add detailed help information and automatic completion function to etcdctl txn command。

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>
etcd version：3.4.13

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment]
Thanks for raising this @Aaron-PanJi, I agree for someone that hasn't used the command before the current `--help` output is not enough.

I have put forward a proposal for some more detailed help output in #15494 which I welcome your thoughts on.

/assign @jmhbnz
/remove help
