### ISSUE TITLE
add `verify-goimport` to verify all import items are well sorted.

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15469]
### What would you like to be added?

We have [go_imports_fix](https://github.com/etcd-io/etcd/blob/bea9c95b7732950e2d04a33dc21e82acf5bf76c2/scripts/fix.sh#L47), but we don't have related verification. 

Let's add a `verify-goimport` in [Makefile#L46](https://github.com/etcd-io/etcd/blob/bea9c95b7732950e2d04a33dc21e82acf5bf76c2/Makefile#L46) to prevent https://github.com/etcd-io/etcd/pull/15467 from happening again in future.

### Why is this needed?

Improve test workflow

**Comment by HanningLin** [comment]
I'd like to work on it and contribute to etcd!

**Comment by ahrtr** [comment]
Thanks. Just assigned to you. @HanningLin

**Comment by HanningLin** [comment]
Can we close this issue?

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/etcd/pull/15485
