### ISSUE TITLE
Flaking TestConnectionMultiplexing

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15495]
### Which github workflows are flaking?

e2e tests

### Which tests are flaking?

TestConnectionMultiplexing

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/4439049893/jobs/7790956875

**Comment by serathius** [comment]
Blocks https://github.com/etcd-io/etcd/pull/15446

**Comment by serathius** [comment]
cc @fuweid

**Comment by serathius** [comment]
Problem I encountered is lack of proper logs from etcdctl spawn. Because we don't pass logger to `SpawnCmd` we don't get logs about the process execution. Will send PR to fix that.

**Comment by chaochn47** [comment]
All the unrelated successful sub tests are commented out. Only `ServerTLSAndNonTLS` and `clientScenarios = []e2e.ClientConnType{e2e.ClientNonTLS}` is left. 

```
cd tests
ETCD_CLIENT_DEBUG=true EXPECT_DEBUG=true taskset -c 1 go test -v -failfast -count=1 \
  -run TestConnectionMultiplexing ./e2e/
```

```
/home/chaochn/bin/etcd (TestConnectionMultiplexingServerTLSAndNonTLS-test-0) (1121874): 
{
    "level": "info",
    "ts": "2023-03-18T07:44:35.806311Z",
    "caller": "zapgrpc/zapgrpc.go:178",
    "msg": "[core] [Server #4] grpc: Server.Serve failed to create ServerTransport: 
        connection error: desc = \"ServerHandshake(\\\"127.0.0.1:34630\\\") failed: 
        tls: first record does not look like a TLS handshake\""
}
```

Not sure why client is configured to use NonTLS but server requires TLS handshake.. only when CPU core is low.  From the tcpdump, without setting CPU core, TLS traffic can go through.. I hope the information is useful

**Comment by serathius** [comment]
Great find @chaochn47.

Running `ETCD_CLIENT_DEBUG=true EXPECT_DEBUG=true taskset -c 1 go test -v -failfast -count=1  -run TestConnectionMultiplexing ./e2e/`
```
--- FAIL: TestConnectionMultiplexing (11.75s)
    --- PASS: TestConnectionMultiplexing/ServerTLS (2.24s)
        --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS (1.89s)
            --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/etcdctl (0.02s)
            --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/clientv3 (0.01s)
            --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl (1.86s)
                --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl/http2 (0.44s)
                --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl/http1.1 (0.48s)
                --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl/http1.0 (0.48s)
                --- PASS: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl/default (0.46s)
    --- PASS: TestConnectionMultiplexing/ServerNonTLS (1.71s)
        --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS (0.68s)
            --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/etcdctl (0.01s)
            --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/clientv3 (0.00s)
            --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/curl (0.66s)
                --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/curl/http2 (0.13s)
                --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/curl/http1.1 (0.18s)
                --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/curl/http1.0 (0.18s)
                --- PASS: TestConnectionMultiplexing/ServerNonTLS/ClientNonTLS/curl/default (0.18s)
    --- FAIL: TestConnectionMultiplexing/ServerTLSAndNonTLS (7.80s)
        --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS (1.94s)
            --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/etcdctl (0.01s)
            --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/clientv3 (0.00s)
            --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/curl (1.92s)
                --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/curl/http2 (0.42s)
                --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/curl/http1.1 (0.48s)
                --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/curl/http1.0 (0.47s)
                --- PASS: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientTLS/curl/default (0.56s)
        --- FAIL: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientNonTLS (5.01s)
            --- FAIL: TestConnectionMultiplexing/ServerTLSAndNonTLS/ClientNonTLS/etcdctl (5.01s)
```

Interesting, `clientv3` works while `etcdctl` don't. Possibly due to higher overhead, still would be good to look into client configuration difference.
cc @aojea

**Comment by fuweid** [comment]
https://github.com/etcd-io/etcd/blob/736c89398bcffbb5445fc45529a8405335042a80/server/embed/serve.go#L130

The `gs` has been overrided by the secure one 😂 , since the `serve` shares the same context with the grpc serve one.

```diff
--- a/server/embed/serve.go
+++ b/server/embed/serve.go
@@ -134,7 +134,7 @@ func (sctx *serveCtx) serve(
                        sctx.serviceRegister(gs)
                }
                grpcl := m.Match(cmux.HTTP2())
-               go func() { errHandler(gs.Serve(grpcl)) }()
+               go func(gs *grpc.Server) { errHandler(gs.Serve(grpcl)) }(gs)
```

It works....

anyway, we need to update the defer as well since it just cares one gs instance.

https://github.com/etcd-io/etcd/blob/736c89398bcffbb5445fc45529a8405335042a80/server/embed/serve.go#L118

**Comment by serathius** [comment]
Amazing, but disturbing bug. I read the and this seemed weird that we didn't pass variable via argument, but I didn't have time to investigate it. I didn't want to believe etcd could have bug like this. Great work @fuweid and @chaochn47.

@fuweid Can you send a PR with the fix?

Follow up. Is there any static analysis that can any cases where we reassign to variable used by goroutine?

**Comment by fuweid** [comment]
> Can you send a PR with the fix?
@serathius sure. will file a pr later.

**Comment by ahrtr** [comment]
> The `gs` has been overrided by the secure one 😂 , since the `serve` shares the same context with the grpc serve one.

Great finding. It happens when we listen both http and https endpoints on the same address.

```
--listen-client-urls=http://127.0.0.1:2379,https://127.0.0.1:2379
```
