### ISSUE TITLE
Flaky Test TestMemberPromoteMemberNotLearner

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15528]
### Which github workflows are flaking?

Integration Test

### Which tests are flaking?

TestMemberPromoteMemberNotLearner

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/4469937666/jobs/7852763845

second time: https://github.com/etcd-io/etcd/actions/runs/4548835671/jobs/8020273443?pr=15580

### Reason for failure (if possible)

```
     logger.go:130: 2023-03-20T15:29:08.541Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}

     logger.go:130: 2023-03-20T15:29:08.542Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}

     logger.go:130: 2023-03-20T15:29:13.743Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = Unavailable desc = etcdserver: request timed out"}

     cluster_test.go:326: expect error to contain can only promote a learner member, got etcdserver: request timed out
```

The test just created 3 member cluster and expect member promote 

### Anything else we need to know?

Also has been caught in https://github.com/etcd-io/etcd/issues/12372

https://github.com/etcd-io/etcd/blob/22bdc913025de198ef2759e9f534ed8dd555de66/server/etcdserver/server.go#L1487 is unnecessary if the local node is not leader. 

It could be a culprit but test cluster does not have much traffic.

**Comment by chaochn47** [comment]
### Happy case

1. PromoteMember forward the request to leader node via HTTP https://github.com/etcd-io/etcd/blob/caed563e088adb6a381b6ff12fc190bf961ad2ea/server/etcdserver/server.go#L1406
2. Leader will send a configuration changes through raft and then applied it to the server https://github.com/etcd-io/etcd/blob/caed563e088adb6a381b6ff12fc190bf961ad2ea/server/etcdserver/server.go#L1458
3. During apply stage, https://github.com/etcd-io/etcd/blob/caed563e088adb6a381b6ff12fc190bf961ad2ea/server/etcdserver/server.go#L1977 will fail the check due to member is not learner. 

### Failed test case
etcd server apply and `raftLog.applied` increment is asynchronous. Because the test tries member promote back to back 3 consecutive times immediately, the configuration change apply failed as expected but `raftLog.applied` may not yet advanced so raft rejects the next configuration change until the current pending one finished. 

If 10ms delay is injected right before `r.Advance()`, the test is easy to be reproduced. 


```
    logger.go:130: 2023-04-08T09:16:51.977Z	INFO	m1.raft	fb1ea72004cfe7d1 ignoring conf change {ConfChangeAddNode 18095084108782757841 [123 34 105 100 34 58 49 56 48 57 53 48 56 52 49 48 56 55 56 50 55 53 55 56 52 49 44 34 112 101 101 114 85 82 76 115 34 58 110 117 108 108 44 34 105 115 80 114 111 109 111 116 101 34 58 116 114 117 101 125] 16704281339942603016} at config voters=(6405474625522971017 17128636064163883618 18095084108782757841): possible unapplied conf change at index 10 (applied to 9)	{"member": "m1"}
```

```golang
alreadyPending := r.pendingConfIndex > r.raftLog.applied

var refused string
if alreadyPending {
    refused = fmt.Sprintf("possible unapplied conf change at index %d (applied to %d)", r.pendingConfIndex, r.raftLog.applied)
}

Thanks to @lavacat [comment](https://github.com/etcd-io/etcd/issues/14040#issuecomment-1323254093) which inspired me. :)

if refused != "" {
    r.logger.Infof("%x ignoring conf change %v at config %s: %s", r.id, cc, r.prs.Config, refused)
    m.Entries[i] = pb.Entry{Type: pb.EntryNormal}
```
https://github.com/etcd-io/raft/blob/main/raft.go#L1221-L1223

**Comment by chaochn47** [comment]
Thanks to @lavacat [comment](https://github.com/etcd-io/etcd/issues/14040#issuecomment-1323254093) that inspired me. 

I will provide a fix to resolve the failed test.

**Comment by lavacat** [comment]
Thanks for looking into this. I've also opened raft [issue](https://github.com/etcd-io/raft/issues/43) to fail fast in ProposeConfChange. You fix is still relevant and won't require fail-fast.

**Comment by serathius** [comment]
Do I read it correctly that `PromoteMember` is not linearizable? If so this is a second grpc call (https://github.com/etcd-io/etcd/issues/13915) that properties don't align with https://etcd.io/docs/v3.5/learning/api_guarantees/. 

With that I think it would be reasonable to start an effort to scan through etcd APIs to validate their guarantees and start tracking real state vs assumed one. I will file an issue for that. Please note that I don't tracking and fixing are not the same, and we should not try to rush fixing all the APIs, understanding our current position is most important.

**Comment by ahrtr** [comment]
I think the API is still linearizable, because the confChange is visible to following read requests. 

But confChange is a special case. raft supports processing multiple normal entries concurrently, but only support one conf Change at a time. So if users send two confChanges very fast, the second one may be rejected by raft because it may still be pending on processing the first one. 

Note that this isn't a raft issue. Instead, it's a etcdserver issue. etcd should ensure that the raft side is notified / advanced before responding to the client.  We only need to apply this logic on confChange.  cc  @tbg @pavelkalinnikov  @nvanbenschoten

See my draft PR https://github.com/etcd-io/etcd/pull/15703 . Please anyone feel free to continue to work on top of my PR.  cc @chaochn47 @fuweid

**Comment by serathius** [comment]
> the second one may be rejected by raft because it may still be pending on processing the first one.

*may* is critical word that shows that it's not linearizable. It's either is, or is not. From the issue I understood that other etcd members already processed `confChanges` but member still rejects it because it is not up to date with leader. Ergo member rejects request based on local state and without confirming with other members.

**Comment by chaochn47** [comment]
> From the issue I understood that other etcd members already processed confChanges but member still rejects it because it is not up to date.

That's not correct. Leader does not get a chance to replicate the MsgConfChange entries to other followers. The request stops at raft module before consensus is built. 

```
case pb.MsgProp:
       refused = fmt.Sprintf("possible unapplied conf change at index %d (applied to %d)", r.pendingConfIndex, r.raftLog.applied)

if !r.appendEntry(m.Entries...) {
	return ErrProposalDropped
}
r.bcastAppend()
```

I don't think it's a linearizability problem since client cannot read stale data. The worst case is membership re-configuration will timeout and retry will succeed. To mitigate your concern @serathius, remove/add member into robustness work should be prioritized on my list... https://github.com/etcd-io/etcd/issues/15508

> etcd should ensure that the raft side is notified / advanced before responding to the client. We only need to apply this logic on confChange.

That sounds correct.

Also In theory, it will not cause performance degradation since only apply configuration change will wait for the signal that etcd server has notified raft to advance the applied index. It should zero effect on normal entries apply. I will benchmark the performance especially when member reconfiguration + high ratio of r/w anyway to double confirm.

**Comment by ahrtr** [comment]
Note this issue is **NOT** a blocker for 3.5.8 (cc  @serathius ) and 3.4.25. 

It's almost impossible to see this issue in production environment. Usually users won't concurrently perform confChange, it they do it, it's also very low possibility to reproduce this issue.

**Comment by serathius** [comment]
> I don't think it's a linearizability problem since client cannot read stale data. The worst case is membership re-configuration will timeout and retry will succeed. 

Not sure we understand each other. Breaking linearizability is not only about read nor stale data, it's about any discrepancy that prevents concurrent operations (like MemberPromote) taking affect instantaneously at some point in time between their request and response. Basically whole operation needs to take effect within the time of request. 

All the fixes that were implemented by @chaochn47, @ahrtr and @lavacat introduce some type of delay either before writing response to client or wait after response was received by client. It means that before the changes operation didn't finish in time between request and response. Which by definition is breaking linearizability. I strongly recommend reading https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf and https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf

> To mitigate your concern @serathius, remove/add member into robustness work should be prioritized on my list... https://github.com/etcd-io/etcd/issues/15508

Please don't. It's not part of core API. It's not something easy to test. There are more important things we should test.

**Comment by ahrtr** [comment]
Strictly speaking, I agree with @serathius that it breaks the linearizability. But let's do not focus on the term linearizability vs non-linearizability.  Just as we mentioned, the good news is (1) the confChange is visible to following read requests, and (2) it's almost impossible to reproduce this issue in production. 

It's an issue of etcdserver instead of raft, that's it.  I think https://github.com/etcd-io/etcd/pull/15708 is the right direction to fix it.

**Comment by serathius** [comment]
Just to clarify my stance from https://github.com/etcd-io/etcd/issues/15528#issuecomment-1504816228. Fact that we break linearizability in PromoteMember is not important to writing a fix, but it's important for us to notice that we have large API surface which was already discovered to have two non-linearizable methods that were not documented nor known by anyone.  

I want to propose to take time and revisit all API we expose to confirm if there are more things we missed.
