### ISSUE TITLE
Remove e2e test coverage calculation

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15522]
### What would you like to be added?

Remove calculating coverage on e2e tests. E2e support compiling etcd binaries with coverage calculation which greatly complicate codebase without any benefits. With effort to unify e2e and integration tests there are no benefits of collecting coverage from binaries as we can get same signal from unit tests.

### Why is this needed?

It will greatly simplify ./scripts/test.sh and allow us to remove remove `*_nocov.go` files.

Before committing this to work, I would love to get other maintainers feedback.
cc @ahrtr @ptabor

**Comment by jmhbnz** [comment]
I've made a start on this (just looking at `scripts/test.sh` initially), refer #15544.

Provided maintainer consensus is to go ahead with this, and someone can give a little gentle guidance on what else should be cleaned up I'm happy to complete the remainder.

**Comment by serathius** [comment]
ping @ahrtr for confirmation.

Commented on PR with more info.

**Comment by jmhbnz** [comment]
Hey @serathius, @ahrtr  - I think we can close this as we have merged #15544 now. Apologies I missed the "Fixes" keyword for auto close when I referenced the issue in pr description.
