### ISSUE TITLE
Flaking `TestV3WatchRestoreSnapshotUnsync`

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15557]
### Which github workflows are flaking?

test (linux-amd64-integration-4-cpu)

### Which tests are flaking?

TestV3WatchRestoreSnapshotUnsync

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/4516121595/jobs/7954130220

### Reason for failure (if possible)

```
    v3_watch_restore_test.go:34: Waiting for metric: etcd_network_snapshot_receive_inflights_total
    v3_watch_restore_test.go:126: sleeping for 2 seconds
    v3_watch_restore_test.go:128: sleeping for 2 seconds DONE
    v3_watch_restore_test.go:153: wStream.Recv error: expected 12 events, got [kv:<key:"foo" create_revision:2 mod_revision:5 version:4 value:"bar" > ]
```

**Comment by chaochn47** [comment]
Duplicate of https://github.com/etcd-io/etcd/issues/15545

**Comment by ahrtr** [comment]
Thanks @chaochn47
