### ISSUE TITLE
Fix link for maintainers role and responsibilities in readme

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15671]
### What happened?

We merged https://github.com/etcd-io/etcd/pull/15593 this week. One of the key changes was extracting the community membership to a separate file and moving maintainer role info from `GOVERNANCE.md` to that new file.

In our project `README.md` we have the following paragraph:

> ### Maintainers
> [MAINTAINERS](https://github.com/etcd-io/etcd/blob/main/MAINTAINERS) strive to shape an inclusive open source project culture where users are heard and contributors feel respected and empowered. MAINTAINERS maintain productive relationships across different companies and disciplines. Read more about [MAINTAINERS role and responsibilities](https://github.com/etcd-io/etcd/blob/main/GOVERNANCE.md#maintainers).

The maintainers roles and responsibilities link needs to be updated to point to https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#maintainers 

### What did you expect to happen?

Links should go to the right place.

### How can we reproduce it (as minimally and precisely as possible)?

1) View project `README.md`
2) Click link for Maintainers roles and responsibilities
3) Be taken to `GOVERNANCE.md` which no longer contains this content.

### Anything else we need to know?

We should think about updating the main project readme contributing section to also mention and link to our new community membership page.

**Comment by jmhbnz** [comment]
This will be a good issue for the upcoming etcd contribfest at kubecon eu for any participant that is less familiar with github and/or golang and wants to get some practice with etcd pull request process.

**Comment by HeavenTonight** [comment]
i can try it! /assign
