### ISSUE TITLE
Static Analysis fails

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15692]
### What happened?

The PR https://github.com/etcd-io/etcd/pull/15281 is causing a format error. Just execute "./scripts/fix.sh" should can fix it. cc @jmhbnz @chaochn47 

```
gofmt' started at Mon Apr 10 22:34:42 UTC 2023
fileutil/preallocate.go
FAIL: 'go_fmt_for_package ./...' checking failed (printed output)
diff fileutil/preallocate.go.orig fileutil/preallocate.go
FAIL: 'gofmt' failed at Mon Apr 10 22:34:42 UTC 2023
--- fileutil/preallocate.go.orig
+++ fileutil/preallocate.go
@@ -19,8 +19,8 @@
make: *** [Makefile:73: verify-gofmt] Error 255
 	"os"
 )
 
-// Preallocate tries to allocate the space for given file. This 
-// operation is only supported on darwin and linux by a few 
+// Preallocate tries to allocate the space for given file. This
+// operation is only supported on darwin and linux by a few
 // filesystems (APFS, btrfs, ext4, etc.).
 // If the operation is unsupported, no error will be returned.
 // Otherwise, the error encountered will be returned.
Error: Process completed with exit code 2.

```

https://github.com/etcd-io/etcd/actions/runs/4661867210/jobs/8251618403

### What did you expect to happen?

see above

### How can we reproduce it (as minimally and precisely as possible)?

See https://github.com/etcd-io/etcd/actions/runs/4661867210/jobs/8251618403

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Lesson learned: we should request contributors to rebase their PR/dev_branch if it's far behind the head even there is no conflict.

**Comment by chaochn47** [comment]
> Lesson learned: we should request contributors to rebase their PR/dev_branch if it's far behind the head even there is no conflict.

Why the PR does not trigger the Static Analysis checks? This could have captured the issue without asking the rebase.

**Comment by chaochn47** [comment]
Got it! Thanks for the explanation. I just checked the PR branch was 200+ commits behind main.. We should ask the rebase regardless.
