### ISSUE TITLE
Tests: etcd graceful shutdown

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15702]
### What would you like to be added?

> Last time I looked, leader will try to pass leadership before exiting. So we should have a tests for that behavior:
> 1. Test that in 3 member cluster leader will try to pass leadership when shut down
> 2. Test that in 3 member cluster leader will still shutdown if it cannot pass down leadership.
> 3. Test that in 1 member cluster passing leader is skipped

> It would be better to have some assertions in the tests instead of just testing that process can be killed.

https://github.com/etcd-io/etcd/pull/15637#issuecomment-1503989615

> FYI. If the second stopped member is the leader, it also might lead to some delay (e.g. about 7s in this case) under sequentially stopping.

```
/Users/wachao/go/src/github.com/ahrtr/etcd/bin/etcd (TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1) (85679): {"level":"info","ts":"2023-04-12T13:21:47.724134+0800","caller":"etcdserver/server.go:1178","msg":"leadership transfer starting","local-member-id":"d70245c72180528a","current-leader-member-id":"d70245c72180528a","transferee-member-id":"c61f33e98087dec2"}
...
/Users/wachao/go/src/github.com/ahrtr/etcd/bin/etcd (TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1) (85679): {"level":"warn","ts":"2023-04-12T13:21:54.724839+0800","caller":"etcdserver/server.go:1257","msg":"leadership transfer failed","local-member-id":"d70245c72180528a","error":"etcdserver: request timed out, leader transfer took too long"}
```

https://github.com/etcd-io/etcd/pull/15637#issuecomment-1504682944

### Why is this needed?

Improve test coverage and transfer leadership if necessary..

**Comment by chaochn47** [comment]
Another thing is peer listener closing..

**Comment by ahrtr** [comment]
> Hi @ahrtr, with the help of @serathius, I can find out the reason is leadership transfer request was sent to a downed member due to a race condition.

Due to the "race condition", the transferee might be selected as the longestConnected member, just as you mentioned in https://github.com/etcd-io/etcd/pull/15637#issuecomment-1504666723 ?

**Comment by chaochn47** [comment]
Yeah.
