### ISSUE TITLE
Cover txn.CheckTxnAuth logic with unit tests

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#15707]
### What would you like to be added?

checkTxnReqsPermission isn't fully [covered](https://app.codecov.io/gh/etcd-io/etcd/blob/main/server/etcdserver/txn/txn.go) with tests.

I've found 2 integration tests that test txn with auth: 
1. [clientv3_test.ExampleAuth](https://github.com/etcd-io/etcd/blob/6d8139dcea972ca0cb3ab1fd9cc22c959bcf930a/tests/integration/clientv3/examples/example_auth_test.go#L30)
2. [TestAuthTxn](https://github.com/etcd-io/etcd/blob/5e0119eadc5ce9ec7f1d904e8f8c20d21e58f2ed/tests/common/auth_test.go#L317)

But they use basic txn setup, without multiple compare predicates or RequestOp_RequestDeleteRange.

I think it would be good to add some unit tests to txn_test.go to cover these edge cases.

### Why is this needed?

increase test coverage

**Comment by vianamjr** [comment]
I can try as my first contribution.

**Comment by vianamjr** [comment]
I guess it can be closed since it's now [covered](https://app.codecov.io/gh/etcd-io/etcd/blob/main/server/etcdserver/txn/txn.go#L646).
