### ISSUE TITLE
Nominate @tjungblu @cenkalti and @pavelkalinnikov as members

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15714]
### What would you like to be added?

I'd like propose @tjungblu, @cenkalti, @pavelkalinnikov as new members based on their contributions, 

- @tjungblu:  contribution to both etcd and bboltDB, and is also helping the community for a long time.
  - fix flaky etcd test: https://github.com/etcd-io/etcd/pull/15401
  - add linearizability nightlies for release 3.4/3.5: https://github.com/etcd-io/etcd/pull/15106
  - actively analyze/discuss issues like 
     - https://github.com/etcd-io/etcd/issues/15705
     - https://github.com/etcd-io/etcd/issues/15488, 
     - https://github.com/etcd-io/etcd/issues/15477
   - reviewed bbolt PRs:
     - https://github.com/etcd-io/bbolt/pull/433 
     - https://github.com/etcd-io/bbolt/pull/417 

- @cenkalti: contribution to bbolt
  - Resurrected multiple unresponsive PRs:
    - https://github.com/etcd-io/bbolt/pull/419 
    - https://github.com/etcd-io/bbolt/pull/420 
    - https://github.com/etcd-io/bbolt/pull/421 
    - https://github.com/etcd-io/bbolt/pull/426 
  - actively triage issue and review boltdb PRs, for example,
    - https://github.com/etcd-io/bbolt/pull/433 
    - https://github.com/etcd-io/bbolt/pull/417 

- @pavelkalinnikov: contribution to raft, Pavel is also super active in raft
  -  https://github.com/etcd-io/raft/pull/31
  - https://github.com/etcd-io/raft/pull/33
  - https://github.com/etcd-io/raft/pull/36
  - actively discuss/analyze issues, for example,
    - https://github.com/etcd-io/etcd/issues/15595
    - https://github.com/etcd-io/etcd/issues/15704
  
Thank you @tjungblu @cenkalti and @pavelkalinnikov .

cc @mitake @ptabor @serathius @spzala 

### Why is this needed?

recognize active contributors and grow the community

**Comment by cenkalti** [comment]
Hi @ahrtr . Not sure if they count but I had few contributions to etcd itself in past: https://github.com/etcd-io/etcd/pulls?q=author%3Acenkalti

**Comment by ahrtr** [comment]
@cenkalti Yes, I saw all your contributions, and I just list part of them. Thanks.

**Comment by serathius** [comment]
Please read https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md

**Comment by ahrtr** [comment]
> @ahrtr Thank you for nominating! What does the proposed membership mean? In my case, is it a membership in `etcd` or `raft`? Is it basically a line in [this](https://github.com/etcd-io/raft/blob/main/OWNERS) file?

Please read the link provided by @serathius . You will be added as a member of etcd-io org. Eventually I expect that you can be promoted to a raft reviewer later, and you will be added into https://github.com/etcd-io/raft/blob/main/OWNERS by then.

**Comment by tbg** [comment]
➕ on adding raft to the maintainer roster in raft. Thanks Benjamin for your effort to grow the set of maintainers.

**Comment by mitake** [comment]
I'm supportive, thanks for your great contribution @tjungblu @cenkalti @pavelkalinnikov !

**Comment by ahrtr** [comment]
> Thank you! Also had a couple more contributions https://github.com/etcd-io/etcd/pulls?q=+is%3Apr+author%3A%40me+

Yes, I just like part of your contributions. Just as I mentioned, you are also helping the community for a long time. Thank you for your contribution for both etcd and bboltDB. I am longing for more active contributors like you to be active in bboltDB. cc @tjungblu

**Comment by ptabor** [comment]
Thank you. I support all the 3 nominations. Thank you Thomas, Cenk & Pavel.

**Comment by spzala** [comment]
+1 Thanks for the nomination @ahrtr 
Thank you for your contributions @tjungblu, @cenkalti, @pavelkalinnikov !!!

**Comment by serathius** [comment]
Invites sent 
![image](https://user-images.githubusercontent.com/5873433/232229824-3d8dfc1d-1be9-48a8-9f72-465fdf0377cc.png)

**Comment by pavelkalinnikov** [comment]
@serathius Sorry, by the time I got to act on the invite it has expired. Could you send another one please?

**Comment by ahrtr** [comment]
> @serathius Sorry, by the time I got to act on the invite it has expired. Could you send another one please?

Done.
