### ISSUE TITLE
Membership nomination for @lavacat (Bogdan Kanivets)

### ISSUE THREAD

**Issue by ptabor** [etcd-io/etcd#15712]
### What would you like to be added?

I would like to nominate Bogdan Kanivets (@lavacat) as etcd community member. 

Bogdan is helping the community for a long time. First contributions (defrag fixes in bbolt: 01347a8f53802565049064eb077bcca33f60dac1) in Feb'22. 

Bogdan fixed several prod issues:
  -  mvcc: update minRev when watcher stays synced (#15271)
  - #13783
  - #14110
 
Bogdan is taking care of test quality/flakiness and coverage. For example: 
 - Test deflaking 757910958e689cf155724557c08486e452656662, #13940
 -  Improvements to robustness tests: d2ccb12f36951ef55eee2a4efd1c81a299bc2a54, 4b91ae2800729afe1a6f0fd1817d23f637bde31b, 91b056968d0968a8f150a1dbbfcadab204c3e61e
 - Functional tests fixes: #14384

Bogdan is reviewing  PRs and raising valid concerns and proposing simplifications. 

Bogdan already had triage permission assigned by me, before we introduced the new formal process. 

I think that Bogdan also fulfilled the Member duties for some time, and we soon should graduate him to the reviewer role.

Thank you, @lavacat

@serathius 
@ahrtr
@spzala 
@mitake 

### Why is this needed?

 - To recognise active contributors 
 - To respect the process

**Comment by ahrtr** [comment]
+1. Thanks @lavacat for your great work!

**Comment by mitake** [comment]
+1 I’m also very supportive, thanks for your contribution @lavacat !

**Comment by serathius** [comment]
Invitation sent 
![image](https://user-images.githubusercontent.com/5873433/231761053-e32d9a52-9804-4ddd-81cb-a1df56bb5620.png)

**Comment by ptabor** [comment]
[ Reopening the issue let Bogdan ack the new status ;) ]

**Comment by lavacat** [comment]
Thanks folks, appreciate this. 👋 @ptabor thanks for the nomination
