### ISSUE TITLE
improve description of `--initial-cluster-state` flag

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#15743]
### What would you like to be added?

Currently `etcd -h` show following description of `--initial-cluster-state` flag
```
  --initial-cluster-state 'new'
    Initial cluster state ('new' or 'existing').
```
But this poorly summarizes logic of [bootsrapCluster](https://github.com/etcd-io/etcd/blob/e04da89030316b3dc49e6167605fa0edea54c842/server/etcdserver/bootstrap.go#L264).

1. Description just repeats the name of the flag.
2. The flag is only applicable when Wal doesn't exist/readonly, but that's never mentioned.
3. Meaning of `new` and `existing` isn't clear.

### Why is this needed?

I think folks are getting confused by the meaning of this flag. See https://github.com/etcd-io/etcd/issues/15705#issuecomment-1505669736

**Comment by sharathsivakumar** [comment]
I am interested to work on this.

**Comment by lavacat** [comment]
keeping the issue open to track backports https://github.com/etcd-io/etcd/pull/15752#issuecomment-1518933456
