### ISSUE TITLE
BOM should not depend on archived repo

### ISSUE THREAD

**Issue by jberkus** [etcd-io/etcd#15747]
### What happened?

The BOM check: https://github.com/etcd-io/etcd/blob/main/scripts/updatebom.sh depends on the old CoreOS repo https://github.com/coreos/license-bill-of-materials.  That repo was archived a year ago, and can cause "make verify" to fail.

```
Checking bill of materials...
% 'cp' 'go.sum' 'go.sum.tmp'
% 'cp' 'go.mod' 'go.mod.tmp'
% (cd tools/mod && 'go' 'install' 'github.com/coreos/license-bill-of-materials')
stderr: go: downloading github.com/coreos/license-bill-of-materials v0.0.0-20190913234955-13baff47494e
% '/var/home/jberkus/go/bin/license-bill-of-materials' '--override-file' './bill-of-materials.override.json' 'go.etcd.io/etcd/api/v3/...' 'go.etcd.io/etcd/pkg/v3/...' 'go.etcd.io/etcd/client/pkg/v3/...' 'go.etcd.io/etcd/client/v2/...' 'go.etcd.io/etcd/client/v3/...' 'go.etcd.io/etcd/server/v3/...' 'go.etcd.io/etcd/etcdutl/v3/...' 'go.etcd.io/etcd/etcdctl/v3/...' 'go.etcd.io/etcd/tests/v3/...' 'go.etcd.io/etcd/v3/...'
```

### What did you expect to happen?

Either we should be using something more currently maintained for BOM, or we should unarchive license-bill-of-materials.

### How can we reproduce it (as minimally and precisely as possible)?

Do a clean etcd checkout, followed by "make verify".  Or just look at the code for updatebom.sh and several other files for references:

```
scripts/test.sh
scripts/updatebom.sh
tools/mod/go.mod
tools/mod/go.sum
tools/mod/tools.go
```

### Etcd version (please run commands below)

<details>

Current git checkout

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment]
A suitable alternative could be https://github.com/appscodelabs/license-bill-of-materials. This fork of the coreos repository has had some relatively recent maintenance and is otherwise essentially the same.

We would need to validate this by updating `scripts/updatebom.sh` and running `make verify-bom` followed by `make fix-bom` to ensure everything works as expected.

**Comment by tessapham** [comment]
KubeCon ContribFest: I can give this a try!

**Comment by qhuai** [comment]
@wenjiaswe , is this issue taken? I don't see an assignee and I think I have a fix.
