### ISSUE TITLE
Merge/cleanup Procfiles

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15778]
### What would you like to be added?

Procfiles are nice and all, but why do we need to have 3 in root directory `Procfile`, `Procfile.learner`, `Procfile.v2`.

I propose one of three things:
* Merge/remove `Procfile.learner` and `Procfile.v2` so only `Procfile` is left.
* Move procfiles to `Documentation/contributor-guide` or similar place for contributors.
* Remove after confirming they are not used by any contributor.

### Why is this needed?

Root directory should be minimal to improve readability and avoid overwhelming new contributors.
It's not clear which one of them they should use, nor where it is documented.

**Comment by sharathsivakumar** [comment]
@serathius and @jmhbnz I would like to work on this.

**Comment by serathius** [comment]
Let's discuss which option we should do. I don't use procfile as much so I don't want to pick myself.

**Comment by sharathsivakumar** [comment]
Cool. I am doing a bit of digging around. I will get back to you soon and we can go ahead. In the meantime, do you think it might be a good idea to ask around in the etcd channel if other contributors have any opinions on this as well?

**Comment by serathius** [comment]
Sure, cc @ahrtr @ptabor @jmhbnz @chaochn47 @lavacat

**Comment by ahrtr** [comment]
`Profile` is super useful to launch a local etcd cluster in seconds, let's keep it as it's. 
- Remove `Procfile.v2`, since we only support `zap` for the structure log starting from 3.5. And 3.4 also support zap.
- Append the content of `Profile.learner` to `Profile` as comment.

**Comment by jmhbnz** [comment]
Suggested approach from @ahrtr sounds good to me.  That would cut two files out of root directory which is a great win.

**Comment by sharathsivakumar** [comment]
Based on the inputs provided by everyone, I will make the changes and create a PR.

**Comment by shivanshu1333** [comment]
@jmhbnz this is a small one, I've opened up a [PR](https://github.com/etcd-io/etcd/pull/16040), if you've time, kindly review.
Assign this issue to me if needed.
Thanks!

**Comment by jmhbnz** [comment]
Thanks for your pull request @shivanshu1333, I've reassigned the issue to you.

This issue was originally assigned to another contributor, so in future from a contributor experience perspective my preference would be for you to check in with the assigned contributor first and ask for them to release the issue before raising a pr.

**Comment by shivanshu1333** [comment]
Thanks @jmhbnz and apologies, suggestion noted!
