### ISSUE TITLE
Refreshing issue triage for etcd

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15773]
### What would you like to be added?

Our etcd community contributions have been growing lately, particularly with the introduction of our new [community membership](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md) model which is based on the kubernetes community membership model.

The new community membership model establishes our new entry level role of [Member](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#member) which comes with responsibility and privilege of being granted "triage" access to the etcd project repositories.

We now have a number of new members in place who have this triage access, so I believe it is timely to refresh our existing [issue triage](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md) guidelines to ensure these are effective and can be applied by our new Members to ease burden for Maintainers.

This issue is intended to be a meta issue that will have a series of sub tasks in order for the overall refresh to be completed in a number of stages.

Below is a brief summary of what I believe this will involve:
- [x] Propose and document a set of issue priorities in [triage_issues.md](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md). This should strongly consider adoption of the broadly used kubernetes project [issue priorities.](https://www.kubernetes.dev/docs/guide/issue-triage/#step-three-define-priority). 
- [x] Remove old issue `priority/important` label and update as required to new issue priority labels.
- [x] Update [triage_issues.md](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md) to add some more granular/practical guidelines on how etcd Members should assist with triage.
- [ ] Review list of `area/x` labels and propose adding new labels to address any gaps. This should strongly consider adoption of labels matching kubernetes project [area labels](https://github.com/kubernetes/kubernetes/labels).
- [x] Review current suite of etcd issue templates and propose changes based on how these have been working and any observed issues.
- [ ] As proposed recently on [etcd-dev mailing list](https://groups.google.com/g/etcd-dev/c/Xwcqdo6Q5Zw) review older issues that have been closed by stale bot and re-open and freshly triage any important items to ensure we don't lose sight of them.
- [x] Update [triage_issues.md](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md) to add a clearer support policy statement to the aim to shift away from providing 1:1 support and instead addressing broader themes and concerns in a way that helps all etcd users.
- [x] Raise the profile of our [frequently asked questions](https://etcd.io/docs/v3.5/faq) page by adding it to key areas like issue templates and readme.

This is an area I'm keen to contribute towards so happy do the work, just keen for feedback before taking any action.

cc @etcd-io/maintainers-etcd cc @etcd-io/members 

### Why is this needed?

- We now have many more people in the project who have triage issue permissions.
- We need to equip and unify members with effective guidelines for triaging issues to reduce maintainer workload.
- We should consider aligning to standard kubernetes ecosystem approaches where it makes sense.

**Comment by jmhbnz** [comment]
A quick note on approach, I will:
  - Let this issue sit as is for at least a couple of weeks to give people time to consider it.
  - Mention it at next weeks community meeting to again raise awareness.

After those two things have happened I will begin with the first pull request, I don't think there  is any rush to complete this work and want to make sure every has time to provide feedback along the way.

**Comment by pchan** [comment]
We have a number of issues where the contributor is no longer looking active or is not looking at the issue ([example](https://github.com/etcd-io/etcd/issues/14729)), in such cases can we spell out a policy of resetting the assignee.

**Comment by jmhbnz** [comment]
Closing - The main issue triage refresh work has been completed.
