### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ArturiaPendragon** [etcd-io/etcd#15793]
### What happened?

<details>

```console
$ etcdctl member list -w table
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+
|        ID        |  STATUS   |        NAME         |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+
| 2502fe5d84b78245 |   started | etcd-pre-k8s-mst-02 | https://172.17.110.47:2380/ | https://172.17.110.47:2379/ |      false |
| 36a2d24e4bc7cb8e | unstarted |                     | https://172.17.110.46:2380/ |                            |      false |
| 3dfe1ae0ae5493db |   started | etcd-pre-k8s-mst-03 | https://172.17.110.48:2380/ | https://172.17.110.48:2379/ |      false |
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+

$ etcdctl endpoint status -w table
The container restart every seconds.
``Kubernetesls>


### What did you expect to happen?

ETCD was working as intended without any errors. All of a sudden this is the error we are experiencing and etcd is not correcting itself.

We have tried restoring the etcd from snapshot, and the /var/lib/etcd database was recreated but the error remains. What are our next steps ??

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce: Restart master node VM until problem occurs
We are not aware of any other way to do this, because we are not sure of the source of the error.

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.15
Git SHA: aa7126864
Go Version: go1.12.17
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.15
API version: 3.4
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

   "Env": [
                "ETCDCTL_API=3",
                "ETCDCTL_CACERT=/etc/kubernetes/ssl/kube-ca.pem",
                "ETCDCTL_CERT=/etc/kubernetes/ssl/kube-etcd-172-17-110-46.pem",
                "ETCDCTL_KEY=/etc/kubernetes/ssl/kube-etcd-172-17-110-46-key.pem",
                "ETCDCTL_ENDPOINTS=https://127.0.0.1:2379",
                "ETCD_UNSUPPORTED_ARCH=x86_64",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/usr/local/bin/etcd",
                "--peer-cert-file=/etc/kubernetes/ssl/kube-etcd-172-17-110-46.pem",
                "--initial-cluster-token=etcd-cluster-1",
                "--trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
                "--peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
                "--key-file=/etc/kubernetes/ssl/kube-etcd-172-17-110-46-key.pem",
                "--advertise-client-urls=https://172.17.110.46:2379",
                "--cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                "--enable-v2=true",
                "--peer-client-cert-auth=true",
                "--listen-client-urls=https://0.0.0.0:2379",
                "--listen-peer-urls=https://0.0.0.0:2380",
                "--initial-cluster-state=new",
                "--cert-file=/etc/kubernetes/ssl/kube-etcd-172-17-110-46.pem",
                "--election-timeout=5000",
                "--heartbeat-interval=500",
                "--peer-key-file=/etc/kubernetes/ssl/kube-etcd-172-17-110-46-key.pem",
                "--client-cert-auth=true",
                "--data-dir=/var/lib/rancher/etcd/",
                "--name=etcd-pre-k8s-mst-01",
                "--initial-advertise-peer-urls=https://172.17.110.46:2380",
                "--initial-cluster=etcd-pre-k8s-mst-03=https://172.17.110.48:2380,etcd-pre-k8s-mst-02=https://172.17.110.47:2380,etcd-pre-k8s-mst-01=https://172.17.110.46:2380"

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+
|        ID        |  STATUS   |        NAME         |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+
| 2502fe5d84b78245 |   started | etcd-pre-k8s-mst-02 | https://172.17.110.47:2380/ | https://172.17.110.47:2379/ |      false |
| 36a2d24e4bc7cb8e | unstarted |                     | https://172.17.110.46:2380/ |                            |      false |
| 3dfe1ae0ae5493db |   started | etcd-pre-k8s-mst-03 | https://172.17.110.48:2380/ | https://172.17.110.48:2379/ |      false |
+------------------+-----------+---------------------+----------------------------+----------------------------+------------+

$ etcdctl endpoint status -w table
The container restarts every seconds.
``Kubernetesls>


### Relevant log output

```shell
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2023-04-28 09:59:15.034211 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-172-17-110-46.pem, key = /etc/Kubernetes/ssl/kube-etcd-172-17-110-46-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file =
2023-04-28 09:59:15.034964 I | embed: name = etcd-pre-k8s-mst-01
2023-04-28 09:59:15.034972 I | embed: data dir = /var/lib/rancher/etcd/
2023-04-28 09:59:15.034976 I | embed: member dir = /var/lib/rancher/etcd/member
2023-04-28 09:59:15.034980 I | embed: heartbeat = 500ms
2023-04-28 09:59:15.034983 I | embed: election = 5000ms
2023-04-28 09:59:15.034986 I | embed: snapshot count = 100000
2023-04-28 09:59:15.035005 I | embed: advertise client URLs = https://172.17.110.46:2379
2023-04-28 09:59:15.035010 I | embed: initial advertise peer URLs = https://172.17.110.46:2380
2023-04-28 09:59:15.035029 I | embed: initial cluster =
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbbb260]

goroutine 1 [running]:
go.etcd.io/etcd/etcdserver.openBackend(0x7ffc7bcd5d93, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc000280b80, 0x1, 0x1, 0xc000281000, ...)
/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/backend.go:69
go.etcd.io/etcd/etcdserver.NewServer(0x7ffc7bcd5d93, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc000280b80, 0x1, 0x1, 0xc000281000, ...)
/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/server.go:330 +0xa28
go.etcd.io/etcd/embed.StartEtcd(0xc000288000, 0xc000298000, 0x0, 0x0)
/tmp/etcd-release-3.4.15/etcd/release/etcd/embed/etcd.go:214 +0x988
go.etcd.io/etcd/etcdmain.startEtcd(0xc000288000, 0x109fe59, 0x6, 0x1, 0xc0001ff140)
/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/etcd.go:302 +0x40
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/etcd.go:144 +0x2ef9
go.etcd.io/etcd/etcdmain.Main()
/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/main.go:46 +0x38
main.main()
/tmp/etcd-release-3.4.15/etcd/release/etcd/main.go:28 +0x20
```

**Comment by ahrtr** [comment]
3.4.15 is too old, could you try 3.4.25 or 3.5.8?

**Comment by ArturiaPendragon** [comment]
To minimize the impact on service how we would update etcd on an existing production cluster with 3 masters on RKE imported to Rancher.

**Comment by ahrtr** [comment]
> We have tried restoring the etcd from snapshot

When you restore from a snapshot, you need to do it for all members. Please read https://etcd.io/docs/v3.5/op-guide/recovery/.

If you just want to recover one member, the other option is to remove the member from the cluster, and clear its local data, then add the member into the cluster again.

**Comment by ArturiaPendragon** [comment]
Hello,

I have recovered a snapshot with a correct etcd.

Since the container is rebooting in a loop I wanted to create a temporary etcd to make an etcd snapshot restore but the test is not conclusive

I moved the content of /var/lib/etcd/ to test

I tried to launch an etcd_temp with the parameters (env and arguments) but I have the following error : 

`2023-05-02 09:48:18.148239 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=x86_64
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2023-05-02 09:48:18.148352 I | etcdmain: etcd Version: 3.4.15
2023-05-02 09:48:18.148358 I | etcdmain: Git SHA: aa7126864
2023-05-02 09:48:18.148363 I | etcdmain: Go Version: go1.12.17
2023-05-02 09:48:18.148368 I | etcdmain: Go OS/Arch: linux/amd64
2023-05-02 09:48:18.148374 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2023-05-02 09:48:18.148490 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-172-17-110-46.pem, key = /etc/kubernetes/ssl/kube-etcd-172-17-110-46-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file =
2023-05-02 09:48:18.149675 I | embed: name = etcd-pre-k8s-mst-01
2023-05-02 09:48:18.149689 I | embed: data dir = /var/lib/rancher/etcd/
2023-05-02 09:48:18.149695 I | embed: member dir = /var/lib/rancher/etcd/member
2023-05-02 09:48:18.149700 I | embed: heartbeat = 500ms
2023-05-02 09:48:18.149705 I | embed: election = 5000ms
2023-05-02 09:48:18.149710 I | embed: snapshot count = 100000
2023-05-02 09:48:18.149719 I | embed: advertise client URLs = https://172.17.110.46:2379
unexpected fault address 0x1278c80
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1278c80 pc=0xbbb260]

goroutine 1 [running]:
runtime.throw(0x109ecd8, 0x5)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0002e2660 sp=0xc0002e2630 pc=0x42d862
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0002e2690 sp=0xc0002e2660 pc=0x442f41
go.etcd.io/etcd/etcdserver.openBackend(0x7ffdf3274d93, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc000170f00, 0x1, 0x1, 0xc000171380, ...)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/backend.go:69 fp=0xc0002e2698 sp=0xc0002e2690 pc=0xbbb260
go.etcd.io/etcd/etcdserver.NewServer(0x7ffdf3274d93, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc000170f00, 0x1, 0x1, 0xc000171380, ...)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/server.go:330 +0xa28 fp=0xc0002e4b88 sp=0xc0002e2698 pc=0xbd4698
go.etcd.io/etcd/embed.StartEtcd(0xc0002aa000, 0xc0002b4000, 0x0, 0x0)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/embed/etcd.go:214 +0x988 fp=0xc0002e6910 sp=0xc0002e4b88 pc=0xde4968
go.etcd.io/etcd/etcdmain.startEtcd(0xc0002aa000, 0x109dc48, 0x3, 0x109ec01, 0x5)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/etcd.go:302 +0x40 fp=0xc0002e69a8 sp=0xc0002e6910 pc=0xe3c890
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
        /tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/etcd.go:160 +0x3164 fp=0xc0002e9f10 sp=0xc0002e69a8 pc=0xe3b474
go.etcd.io/etcd/etcdmain.Main()
        /tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/main.go:46 +0x38 fp=0xc0002e9f88 sp=0xc0002e9f10 pc=0xe463d8
main.main()
        /tmp/etcd-release-3.4.15/etcd/release/etcd/main.go:28 +0x20 fp=0xc0002e9f98 sp=0xc0002e9f88 pc=0xe4ac30
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0002e9fe0 sp=0xc0002e9f98 pc=0x42f1cc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002e9fe8 sp=0xc0002e9fe0 pc=0x45cb61

goroutine 78 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001cf580)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 129 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000149660)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 132 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000149800)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 24 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 150 [IO wait]:
internal/poll.runtime_pollWait(0x7fbb9259d050, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000171418, 0x72, 0x0, 0x0, 0x10a0b59)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000171400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000171400, 0x7fbb9484eb48, 0xc000056ec8, 0x40bbb9)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000be150, 0xc000056f00, 0x40bbb9, 0xc000070400)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000be150, 0x10, 0x10, 0xc000070400, 0xc00007e900)
        /usr/local/go/src/net/tcpsock.go:260 +0x48
go.etcd.io/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc00026ad00, 0xc000056f30, 0xc000056f30, 0x40c448, 0x10)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/transport/timeout_listener.go:48 +0x37
crypto/tls.(*listener).Accept(0xc00026ba80, 0xc000070400, 0xc0000703f0, 0xc000042038, 0xc00012a1b0)
        /usr/local/go/src/crypto/tls/tls.go:62 +0x37
go.etcd.io/etcd/pkg/transport.(*tlsListener).acceptLoop(0xc0002ae780)
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/transport/listener_tls.go:126 +0x20f
created by go.etcd.io/etcd/pkg/transport.newTLSListener
        /tmp/etcd-release-3.4.15/etcd/release/etcd/pkg/transport/listener_tls.go:84 +0x3a6`
        
      Any suggestions ?

**Comment by ahrtr** [comment]
It seems like an issue of golang 1.12 https://github.com/golang/go/issues/31163. Please consider to upgrade to 3.4.25 or 3.5.8.

> To minimize the impact on service how we would update etcd on an existing production cluster with 3 masters on RKE imported to Rancher.

Usually it's recommended to perform rolling upgrade. Please discuss this with your cloud provider.
