### ISSUE TITLE
Error: context deadline exceeded

### ISSUE THREAD

**Issue by chenzuozhou** [etcd-io/etcd#15836]
### What happened?

I use three nodes run a etcd cluster, it can run success and the health check also success. But it seems the connection bettween the cluster is refused. All the nodes firewall are not running.

[root@k8s-master ~]# /opt/ray/etcd/bin/etcdctl --cacert=/opt/ray/etcd/ssl/ca.pem --cert=/opt/ray/etcd/ssl/server.pem --key=/opt/ray/etcd/ssl/server-key.pem --endpoints="https://192.168.1.153:2379,https://192.168.1.154:2379,https://192.168.1.155:2379" endpoint health
https://10.50.32.153:2379 is healthy: successfully committed proposal: took = 23.34261ms
https://10.50.32.154:2379 is healthy: successfully committed proposal: took = 24.570284ms
https://10.50.32.155:2379 is healthy: successfully committed proposal: took = 32.225478ms

[root@k8s-master ~]# /opt/ray/etcd/bin/etcdctl member list
{"level":"warn","ts":"2023-05-06T20:11:14.323263+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-cc0a46a8-1a84-45a1-87ff-35debfb3ee98/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded

### What did you expect to happen?

when run "/opt/ray/etcd/bin/etcdctl member list", it can show the etcd member list

### How can we reproduce it (as minimally and precisely as possible)?

cat <<EOF >/usr/lib/systemd/system/etcd.service
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target
[Service]
Type=notify
EnvironmentFile=${WORK_DIR}/cfg/etcd
ExecStart=${WORK_DIR}/bin/etcd 
--cert-file=${WORK_DIR}/ssl/server.pem 
--key-file=${WORK_DIR}/ssl/server-key.pem 
--peer-cert-file=${WORK_DIR}/ssl/server.pem 
--peer-key-file=${WORK_DIR}/ssl/server-key.pem 
--trusted-ca-file=${WORK_DIR}/ssl/ca.pem 
--peer-trusted-ca-file=${WORK_DIR}/ssl/ca.pem
Restart=on-failure
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable etcd
systemctl restart etcd

### Etcd version (please run commands below)

[root@k8s-master ~]# /opt/ray/etcd/bin/etcd --version
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
        A future release of golang/protobuf will delete this package,
        which has long been excluded from the compatibility promise.

etcd Version: 3.4.25
Git SHA: 94593e63d
Go Version: go1.19.8
Go OS/Arch: linux/amd64

### Etcd configuration (command line flags or environment variables)

[root@k8s-master ~]# cat /opt/ray/etcd/cfg/etcd 
#[Member]
ETCD_NAME="etcd01"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://192.168.1.153:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.1.153:2379"

#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.1.153:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.1.153:2379"
ETCD_INITIAL_CLUSTER="etcd01=https://192.168.1.153:2380,etcd02=https://192.168.1.154:2380,etcd03=https://192.168.1.155:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"

[root@k8s-node1 ~]# cat /opt/ray/etcd/cfg/etcd
#[Member]
ETCD_NAME="etcd02"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://192.168.1.154:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.1.154:2379"

#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.1.154:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.1.154:2379"
ETCD_INITIAL_CLUSTER="etcd01=https://192.168.1.153:2380,etcd02=https://192.168.1.154:2380,etcd03=https://192.168.1.155:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"

[root@k8s-node2 ~]# cat /opt/ray/etcd/cfg/etcd
#[Member]
ETCD_NAME="etcd03"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://192.168.1.155:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.1.155:2379"

#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.1.155:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.1.155:2379"
ETCD_INITIAL_CLUSTER="etcd01=https://192.168.1.153:2380,etcd02=https://192.168.1.154:2380,etcd03=https://192.168.1.155:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
[root@k8s-master ~]# /opt/ray/etcd/bin/etcdctl member list -w table
{"level":"warn","ts":"2023-05-06T17:26:26.313439+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ff254983-9f3d-4261-939f-88b0c0b9fde9/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded

[root@k8s-master ~]# /opt/ray/etcd/bin/etcdctl member list -w table
{"level":"warn","ts":"2023-05-06T17:26:26.313439+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ff254983-9f3d-4261-939f-88b0c0b9fde9/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
[root@k8s-master ~]# /opt/ray/etcd/bin/etcdctl --endpoints="https://192.168.1.153:2379,https://192.168.1.154:2379,https://192.168.1.155:2379" endpoint status -w table
{"level":"warn","ts":"2023-05-06T17:28:30.01249+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://192.168.1.153:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""}
Failed to get the status of endpoint https://192.168.1.153:2379 (context deadline exceeded)
{"level":"warn","ts":"2023-05-06T17:28:35.013001+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://192.168.1.154:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""}
Failed to get the status of endpoint https://192.168.1.154:2379 (context deadline exceeded)
{"level":"warn","ts":"2023-05-06T17:28:40.013726+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://192.168.1.155:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""}
Failed to get the status of endpoint https://192.168.1.155:2379 (context deadline exceeded)
```

</details>

**Comment by jmhbnz** [comment]
Hey @chenzuozhou - When you run `etcdctl member list` can you please try while specifying endpoints, i.e:

```bash
/opt/ray/etcd/bin/etcdctl --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 member list 
```

**Comment by ahrtr** [comment]
One more comment on top of @jmhbnz 's comment, please also add certificates flags as well,
```
-cacert=/opt/ray/etcd/ssl/ca.pem --cert=/opt/ray/etcd/ssl/server.pem --key=/opt/ray/etcd/ssl/server-key.pem
```

**Comment by chenzuozhou** [comment]
@jmhbnz @ahrtr thanks for yours suggestion, it works
