### ISSUE TITLE
Run arm64 integration and e2e workflows against a supported release branch

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15832]
### What would you like to be added?

There have been recent efforts to resolve issues with arm64 tests and improve overall support for arm64, refer:
- https://github.com/etcd-io/etcd/pull/15829
- https://github.com/etcd-io/etcd/pull/15233
- https://github.com/etcd-io/etcd/pull/15230

These tests have been running more reliably now:
- https://github.com/etcd-io/etcd/actions/workflows/tests-arm64.yaml
- https://github.com/etcd-io/etcd/actions/workflows/e2e-arm64.yaml

With that in mind, should we run these workflows against `release-3.5` to get them running against a stable release branch?

cc @ahrtr, @serathius, @geetasg, @chaochn47 

### Why is this needed?

There have been several discussions and questions lately on improving tier of support for arm64. I believe this would be required step to progressing that?

**Comment by jmhbnz** [comment]
I think https://github.com/etcd-io/etcd/issues/15647 is a blocking issue for this. Once that has been closed off I think this backport could proceed.

**Comment by natusameer** [comment]
Hello @jmhbnz , I can help you with backporting the tests to release-3.5

**Comment by jmhbnz** [comment]
Hey @natusameer - Thanks for volunteering to help with this!  As discussed, please start with a pull request for `release-3.5` initially.

Feel free to comment here or ping me on kubernetes slack if you have any questions along the way 🙏🏻

**Comment by jmhbnz** [comment]
A backport to `release-3.5` has been raised here: https://github.com/etcd-io/etcd/pull/16119 

Once merged we will monitor scheduled runs to confirm tests passing as expected.

**Comment by jmhbnz** [comment]
The backport needs to be reverted, explanation is in this pr: https://github.com/etcd-io/etcd/pull/16151.   Basically scheduled github actions only work if they exist in `default` branch.

I've raised https://github.com/etcd-io/etcd/pull/16151 to revert.

I will raise the pr to re-introduce the scheduled workflows under `main` with `release-3.5` as the ref arg to the checkout action.
