### ISSUE TITLE
Run `tests/failpoint` test suite by default

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15879]
### What would you like to be added?

Follow up from https://github.com/etcd-io/etcd/pull/15865#pullrequestreview-1421414639 leads me to create a tracking issue to complete the work. 

Checklist: 
- [ ] Update the Makefile and workflow to enable gofailpoint for cases under `tests/failpoint`

/cc @ahrtr @serathius for comments to add anything worthwhile to this test suite or in robustness test. 

### Why is this needed?

Improve test coverage and correctness of the etcd under fail points injected. 

The motivation of this test suite comes from 
1. section "Test" in https://docs.google.com/document/d/1U9hAcZQp3Y36q_JFiw2VBJXVAo2dK2a-8Rsbqv3GgDo/edit#heading=h.wwktogcu1ekk.
2. Test properly in https://github.com/etcd-io/etcd/pull/15708

**Comment by serathius** [comment]
For me this is an e2e test that should skipped if etcd binary used doesn't have compiled in gofail. For CI integration we should just enable gofail in e2e tests.

**Comment by ahrtr** [comment]
The benefit of creating a dedicated test type (e.g. `failpoint` or `negative` test):
1. We have a centralized place to review all such cases;
2. We can add cases which are supposed to be executed only with failpoint enabled.

**Comment by fuweid** [comment]
> The benefit of creating a dedicated test type (e.g. failpoint or negative test):

Agree with this. And from developer, currently number of failpoint test cases is lower than normal cases. If we enable failpoint by default, the git-status might be pain-point. At least, to me. Or consider to add these failpoint cases into robustness category.

**Comment by chaochn47** [comment]
> For CI integration we should just enable gofail in tests.
It seems overkill to enable it by default. From change control perspective, I am more inclined to only enable it in a set of test cases to avoid break current CI potentially. WDYT?
