### ISSUE TITLE
Plan for v3.4.26

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15872]
### What would you like to be added?

Issues/PRs to be included in 3.4.26:
* [X] https://github.com/etcd-io/etcd/pull/15823
* [X] LeaseTimeToLive API may return keys to clients which have no read permission on the keys
  * [X] https://github.com/etcd-io/etcd/pull/15814

### Why is this needed?

go 1.19.9 resolves a couple of CVEs, and etcd also resolved a leaseTimeToLive related CVE.

**Comment by ahrtr** [comment]
cc @mitake @ptabor @serathius @spzala

**Comment by serathius** [comment]
LGTM

**Comment by ahrtr** [comment]
Done https://github.com/etcd-io/etcd/releases/tag/v3.4.26
