### ISSUE TITLE
go.etcd.io/etcd/pkg/v3/grpc_testing compatibility with google.golang.org/grpc since v1.55.0

### ISSUE THREAD

**Issue by roger2hk** [etcd-io/etcd#15877]
### What happened?

According to https://github.com/grpc/grpc-go/issues/6264, package was moved from `test/grpc_testing` to `/interop/grpc_testing` in https://github.com/grpc/grpc-go/pull/6164 since v1.55.0. The current [etcd/pkg/go.mod](https://github.com/etcd-io/etcd/blob/9a922091ed07c56c0c09575c2328e9576c76d942/pkg/go.mod#LL14C32-L14C32) depends on `google.golang.org/grpc v1.51.0`.

https://github.com/etcd-io/etcd/blob/9a922091ed07c56c0c09575c2328e9576c76d942/pkg/grpc_testing/stub_server.go#L25

The following error message happens when there are dependencies on the latest version of both go.etcd.io/etcd/v3 and google.golang.org/grpc.
```
go.etcd.io/etcd/v3 imports
go.etcd.io/etcd/tests/v3/integration imports
go.etcd.io/etcd/pkg/v3/grpc_testing imports
google.golang.org/grpc/test/grpc_testing: module google.golang.org/grpc@latest found (v1.55.0), but does not contain package google.golang.org/grpc/test/grpc_testing
```

### What did you expect to happen?

Bump google.golang.org/grpc from 1.51.0 to 1.55.0 in etcd/pkg/go.mod and update the package path from `test/grpc_testing` to `/interop/grpc_testing`.

### How can we reproduce it (as minimally and precisely as possible)?

Create a new Go project and then add dependencies on the latest version of both `go.etcd.io/etcd/v3` and `google.golang.org/grpc`.

Expected to see the following when `go mod tidy` is executed.
```
go.etcd.io/etcd/v3 imports
go.etcd.io/etcd/tests/v3/integration imports
go.etcd.io/etcd/pkg/v3/grpc_testing imports
google.golang.org/grpc/test/grpc_testing: module google.golang.org/grpc@latest found (v1.55.0), but does not contain package google.golang.org/grpc/test/grpc_testing
```

### Anything else we need to know?

Consider backward compatibility for those Go projects relying on google.golang.org/grpc before v1.55.0.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by chaochn47** [comment]
Hi @roger2hk, thanks for the report. There is a known gRPC incompatible issue mentioned in https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#about-grpc. I guess the reported issue needs to be fixed after that as well.

**Comment by roger2hk** [comment]
The commit https://github.com/etcd-io/etcd/commit/24c6fb4b4d2467743661281064ac5a834981270b has resolved the dependency conflict.

**Comment by ahrtr** [comment]
> @chaochn47 Is this commit going to be released in v3.6.0 or possibly earlier in v3.5.10?

It has already been resolved in the main branch (target for 3.6.0), and there is no plan to backport it to 3.5.x.

**Comment by rsafonseca** [comment]
Can we add a plan to backport it to 3.5.x @ahrtr @chaochn47?

**Comment by ahrtr** [comment]
@rsafonseca thx for the feedback. Could you raise an issue to track it? 

@chaochn47 do you have bandwidth to backport the change to 3.5? thx

**Comment by felipejfc** [comment]
+1 for porting this to 3.5.x. Also having problems here because of this dependency. thx!

**Comment by rsafonseca** [comment]
I can open a PR if @chaochn47 doesn't have the bandwidth :)

**Comment by chaochn47** [comment]
Feel free to take it @rsafonseca. I can help review.

**Comment by rsafonseca** [comment]
@chaochn47 @ahrtr I've linked a MR for this, could you review? :)

**Comment by serathius** [comment]
Fixed with https://github.com/etcd-io/etcd/pull/16781
