### ISSUE TITLE
After updating certificates of existing etcd nodes from ip in san to Dns we are getting error

### ISSUE THREAD

**Issue by Singh02306** [etcd-io/etcd#15917]
### What would you like to be added?

We recently updated our certificate for etcd members and new certificate doesn't caontain ip in San, while starting etcd nodes error is coming that certificate doesn't have ip San.
If we change data directory and then start the nodes with certs cluster is coming up fine. 

### Why is this needed?

How do we make etcd work in this scenario.

**Comment by jmhbnz** [comment]
Hi @Singh02306 - Thanks for raising this question. For us to investigate any further can you please provide:
- Your etcd version & configuration options used
- A test certificate in text format
- The logs of the etcd instance that is not starting as you expect

I note there is some related discussion for issues around subject alternative names here which might be of interest https://github.com/etcd-io/etcd/issues/8603.

**Comment by Singh02306** [comment]
Hi @jmhbnz 

etcd 3.4.13
config:
_name: 'infra2'
data-dir: /home/infra2/
listen-peer-urls: https://10.0.219.56:2380
listen-client-urls: https://127.0.0.1:2379,https://10.0.219.56:2379
initial-advertise-peer-urls: https://etcd-controlplane1.uat.hk.net:2380
advertise-client-urls: https://etcd-controlplane1.uat.hk.net:2379
initial-cluster: infra0=https://etcd-controlplane2.uat.hk.net:2380,infra1=https://etcd-controlplane2.uat.hk.net:2301,infra2=https://etcd-controlplane1.uat.hk.net:2380
initial-cluster-token: 'cluster1'
initial-cluster-state: 'new'
client-transport-security:
  # Path to the client server TLS cert file.
  cert-file: /home/infra2/certs/etcd1.pem

  # Path to the client server TLS key file.
  key-file: /home/infra2/certs/etcd1.key

  # Enable client cert authentication.
  client-cert-auth: true

  # Path to the client server TLS trusted CA cert file.
  trusted-ca-file: /home/infra2/certs/hCA.crt

  # Client TLS using generated certificates
  auto-tls: false

peer-transport-security:
  # Path to the client server TLS cert file.
  cert-file: /home/infra2/certs/etcd1.pem

  # Path to the client server TLS key file.
  key-file: /home/infra2/certs/etcd1.key

  # Path to the client server TLS trusted CA cert file.
  trusted-ca-file: /home/infra2/certs/hCA.crt

  # Client TLS using generated certificates
  auto-tls: false_

Error:  **x509: cannot validate certificate for 10.0.219.57 because it doesn't contain any IP SANs"}**

**Comment by Singh02306** [comment]
same config in other two nodes as well.....
my old config was like below:
name: 'infra2'
data-dir: /home/infra2/
listen-peer-urls: https://10.0.219.56:2380
listen-client-urls: https://127.0.0.1:2379,https://10.0.219.56:2379
initial-advertise-peer-urls: https://10.0.219.56:2380
advertise-client-urls: https://10.0.219.56:2379
initial-cluster: infra0=https://10.0.219.57:2380,infra1=https://10.0.219.57:2301,infra2=https://10.0.219.56:2380
initial-cluster-token: 'cluster1'
initial-cluster-state: 'new'
followed by certificate paths

**Comment by Singh02306** [comment]
Hi @jmhbnz ,

updated the etcd version to 3.5.0 still same error....sorry certificate contents i won't be able to update here.

**Comment by Singh02306** [comment]
hi @jmhbnz ,

 X509v3 extensions:
            X509v3 Subject Key Identifier:
                E0:6C:CC:2A:**:**
            X509v3 Subject Alternative Name:
                DNS:etcd-controlplane1.uat.hk.net
            X509v3 Authority Key Identifier:
                keyid:**:**
            X509v3 Key Usage:
                Digital Signature, Key Encipherment
            1.3.6.1.4.1.311.21.7:
                0..&+.....7.....C...:.......'...3.h...c..f..d..(
            X509v3 Extended Key Usage:
                TLS Web Client Authentication, TLS Web Server Authentication

**Comment by jmhbnz** [comment]
Thanks @Singh02306 - You mention updating to `3.5.0`, that is a two year old release, can you please confirm the issue is still present on the latest patch release of 3.5, i.e. `3.5.9`?
