### ISSUE TITLE
Etcd could not connect: x509: certificate is valid  after update certificate

### ISSUE THREAD

**Issue by prometheus-tao** [etcd-io/etcd#15949]
### What happened?

Kubernetes cluster present x509 errors about certs expired, Then restart the kube-apiserver, kube-controller-manager, kube-scheduler and etcd after execute "kubeadm alpha certs renew all " command successfully at one master node, Copy apiserver*, front* and etcd certs file to other two master node, Restart component the same , So that etcd and kube* container cannot running, See log file found many erros as follow.

CERTIFICATE EXPIRES RESIDUAL TIME CERTIFICATE AUTHORITY EXTERNALLY MANAGED
admin.conf May 23, 2024 01:45 UTC 364d no
apiserver May 23, 2024 01:45 UTC 364d ca no
apiserver-etcd-client May 23, 2024 01:45 UTC 364d etcd-ca no
apiserver-kubelet-client May 23, 2024 01:45 UTC 364d ca no
controller-manager.conf May 23, 2024 01:45 UTC 364d no
etcd-healthcheck-client May 23, 2024 01:45 UTC 364d etcd-ca no
etcd-peer May 23, 2024 01:45 UTC 364d etcd-ca no
etcd-server May 23, 2024 01:45 UTC 364d etcd-ca no
front-proxy-client May 23, 2024 01:45 UTC 364d front-proxy-ca no
scheduler.conf May 23, 2024 01:45 UTC 364d no

CERTIFICATE AUTHORITY EXPIRES RESIDUAL TIME EXTERNALLY MANAGED
ca May 20, 2032 10:20 UTC 8y no
etcd-ca May 20, 2032 10:20 UTC 8y no
front-proxy-ca May 20, 2032 10:20 UTC 8y no

### What did you expect to happen?

etcd can normal connect  to the other two node

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm alpha certs renew all

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# 3.4.3

$ etcdctl version
# paste output here
```
Kubernetes: v1.18.20 
</details>

### Etcd configuration (command line flags or environment variables)

<details>

 - etcd
    - --advertise-client-urls=https://192.16.0.1:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://192.16.0.1:2380
    - --initial-cluster=host1=https://192.16.0.1:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://192.16.0.1:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://192.16.0.1:2380
    - --name=host1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt

</details>
   

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
[master node] 192.16.0.1 etcd log
2023-05-24 02:17:33.760448 I | embed: rejected connection from "192.16.0.3:41464" (error "tls: "192.16.0.3" does not match any of DNSNames ["host1" "localhost"]", ServerName "", IPAddresses ["192.16.0.1" "127.0.0.1" "::1"], DNSNames ["host1" "localhost"])
2023-05-24 02:17:37.498451 I | embed: rejected connection from "192.16.0.2:36448" (error "tls: "192.16.0.2" does not match any of DNSNames ["host1" "localhost"]", ServerName "", IPAddresses ["192.16.0.1" "127.0.0.1" "::1"], DNSNames ["host1" "localhost"])
2023-05-24 02:17:36.357622 W | rafthttp: health check for peer c6198c3c2a184417 could not connect: x509: certificate is valid for 192.16.0.1, 127.0.0.1, ::1, not 192.16.0.3
2023-05-24 02:17:36.359115 W | rafthttp: health check for peer cde1c9316d25ba89 could not connect: x509: certificate is valid for 192.16.0.1, 127.0.0.1, ::1, not 192.16.0.2
2023-05-24 02:17:51.359023 W | rafthttp: health check for peer c6198c3c2a184417 could not connect: dial tcp 192.16.0.3:2380: connect: connection refused
2023-05-24 02:17:51.359663 W | rafthttp: health check for peer cde1c9316d25ba89 could not connect: dial tcp 192.16.0.2:2380: connect: connection refused
```

**Comment by ahrtr** [comment]
Please read https://etcd.io/docs/v3.5/op-guide/security/#notes-for-tls-authentication

**Comment by jmhbnz** [comment]
Hey @prometheus-tao - Etcd v3.4.3 is a four year old etcd release from 2019. There have been numerous significant bug fixes and security vulnerabilities that have been patched in etcd over the last four years, please update to a newer release of etcd as soon as possible.

**Comment by prometheus-tao** [comment]
Hey @ahrtr thanks, I solved about tls connect error, The peer.crt of the etcd file is incorrect

**Comment by prometheus-tao** [comment]
Hey @jmhbnz thanks, I try to it
