### ISSUE TITLE
Plan for improving etcd continuous integration

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15951]
### What would you like to be added?

This is an umbrella issue to plan a short series of work that will complete a set of improvements to etcd continuous integration, with some particular focus on our `arm64` self hosted infrastructure, along with some broader fixes.

This issue was motivated by recent discussion in https://github.com/etcd-io/etcd/pull/15927.

Below are the tasks identified, these will be created as individual issues:
- [x] https://github.com/etcd-io/etcd/pull/15886
- [x] https://github.com/etcd-io/etcd/pull/15927
- [x] https://github.com/etcd-io/etcd/issues/15986
- [x] https://github.com/etcd-io/etcd/issues/15955
- [x] https://github.com/etcd-io/etcd/issues/15995
- [x] https://github.com/etcd-io/etcd/issues/15952
- [x] https://github.com/etcd-io/etcd/issues/15953
- [x] https://github.com/etcd-io/etcd/issues/15954
- [x] https://github.com/etcd-io/etcd/issues/15832
- [x] https://github.com/etcd-io/etcd/issues/15987
- [x] https://github.com/etcd-io/etcd/issues/15956
- [x] https://github.com/etcd-io/etcd/issues/16176
- [x] https://github.com/etcd-io/etcd/issues/16315
- [x] https://github.com/etcd-io/etcd/issues/16422
- [ ] https://github.com/etcd-io/etcd/issues/16326
- [x] https://github.com/etcd-io/etcd/issues/16462

Potential additional tasks:
- [x] Consider cleanup process for maintaining etcd arm64 github runner docker installations (need to verify if this will actually be a problem or not once https://github.com/etcd-io/etcd/pull/15927 merges.)
- [x] Consider scaling up `arm64` runner capacity by installing additional runner instances on each machine (this would subsequently enable running `arm64` tests on a per pull request basis instead of only nightly.)
- [ ] Consider creating some form of documentation for etcd ci workflows, there are a lot of files under `main` now which can be hard to decipher.

### Why is this needed?

Once the above work items are complete in relation to arm64 infrastructure we should be able to progress with tier 1 support for `arm64`, and in general be in a better position when it comes to our continuous integration.

**Comment by BobyMCbobs** [comment]
Had a chat with @jmhbnz, a future improvement may be to move from a Docker-based containerised arm64 job to running these within a cluster with autoscaling on Equinix Metal.
Something like Cluster-API + node autoscaler + actions-runner-controller.

**Comment by jmhbnz** [comment]
@serathius, @ahrtr can I propose we pin this issue?  It's about to drop off page 1. I suspect there will be a few more tasks to come under this umbrella and I've found it useful to group ci/testing things under this.

**Comment by ahrtr** [comment]
> can I propose we pin this issue?


Done.

**Comment by dneary** [comment]
Does adding actuated support close the "add runners" task?

**Comment by jmhbnz** [comment]
> Does adding actuated support close the "add runners" task?

It does!  Updated, thanks :)

**Comment by jmhbnz** [comment]
Closing - the primary set of improvements originally scoped have been completed.
