### ISSUE TITLE
Document process for requesting a new etcd arm64 ci machine

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15953]
### What would you like to be added?

This is a sub issue under https://github.com/etcd-io/etcd/issues/15951.

The etcd project currently has two arm64 `c3.large.arm` machines generously contributed by[ Equinix Metal](https://metal.equinix.com/) through the [CNCF Community Infrastructure Lab](https://github.com/cncf/cluster). These machines are used to run our etcd `arm64` ci infrastructure.

Situations can emerge where the project could be required to provision new machines, for example adding more capacity or changes to underlying operating system choice or hardware types.

We currently don’t have any project documentation that steps through the process we need to follow to provision these hardware instances.

This will be a relatively small task to add some documentation to outline the process for creating new arm64 machines which currently requires creating a new github issue, for example: https://github.com/cncf/cluster/issues/227.

The documentation should be created under our newly created “infrastructure-guide” docs directory https://github.com/etcd-io/etcd/tree/main/Documentation/infrastructure-guide.

### Why is this needed?

To have confidence in our arm64 ci infrastructure so we can proceed with tier 1 support.

**Comment by hh** [comment]
I'll take a look at this this week.

**Comment by jmhbnz** [comment]
> I'll take a look at this this week.

Thanks for the pair session today @hh.  As we discussed it would be brilliant if the etcd project could have some more autonomy to be able to create new/replacement `arm64` ci runners without having to raise github issues and wait for them to be fulfilled manually, while still retaining the control of maintainer approval for new runners being created.

Let's catch up in a week or so once your initial exploration is done 🙏🏻

**Comment by jmhbnz** [comment]
Hey @HH - I raised the etcd org access requirement at the community meeting today https://youtu.be/cJ-p3IiknQ0?t=603

We need to outline a clear summary in this issue on why access is required and the proposal for what we are trying to deliver.  Can you please add a summary / proposal here for adding automation including what that would look like?
