### ISSUE TITLE
Consider migrating all etcd unit, integration, e2e and robustness tests to containers

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15956]
### What would you like to be added?

This is a sub issue under #15951.

Recent pull request https://github.com/etcd-io/etcd/pull/15927 introduced running our arm64 ci jobs in containers to prevent leaking test processes causing issues on our self hosted runners.

The github standard runners we use for non arm64 ci jobs do not have the cleanup issue as our self hosted ARM runners do so it isn't absolutely necessary to migrate all workflows into containers, however we should consider doing it on the basis that we have one unified way to run all ci workflows, and accordingly less cognitive burden in relation to these jobs.

This issue should be used to initially gather consensus from the community before proceeding with any changes. 

If we do decide to migrate all workflows, then eventually `robustness-template-arm64.yaml` and `robustness-template.yaml` should be combined back into one YAML file.

Additionally as part of this task we should ensure all ci workflows and our new devcontainer (https://github.com/etcd-io/etcd/blob/main/.devcontainer/devcontainer.json) are using a common base image and we have made a conscious decision about why that base image is preferred, taking into account factors like CVE data and update cadence.

### Why is this needed?

- Reduce maintenance and cognitive burden. 
- Have one consistent approach for isolation within all etcd test suites and platforms.
- Increase portability of test infrastructure.

**Comment by tao12345666333** [comment]
Could you please assign this issue to me?

**Comment by jmhbnz** [comment]
Hi @tao12345666333 - Thanks for offering to help! This issue needs to wait until pr https://github.com/etcd-io/etcd/pull/15927 has been merged and had some time to soak, and is also one of the higher risk items in the overall plan https://github.com/etcd-io/etcd/issues/15951.

Given this would be your first contribution to etcd and the above limitations I would suggest picking up https://github.com/etcd-io/etcd/issues/15955 first to get familiar with etcd ci workflows. If you're keen to pick it up just let me know with a comment on it and I will be most happy to assign it to you 🙏🏻

**Comment by tao12345666333** [comment]
Don't worry. I will pick up #15955

**Comment by jmhbnz** [comment]
Hey @tao12345666333 would you still be interested in helping with this?  Now that we have given https://github.com/etcd-io/etcd/pull/15927 some time to soak I think we could start proposing to migrate other test suite workflows to containers.

**Comment by sharathsivakumar** [comment]
@jmhbnz I would like to work on this. 
@tao12345666333 Hope that's fine. If you have already started to work on this, do let me know.

**Comment by tao12345666333** [comment]
@jmhbnz Thanks for the reminder, I've had a very busy few weeks and missed message reminders. 🥲

@sharathsivakumar I haven't started any work on this issue. 

Please let me know if there is anything I can do.

**Comment by tao12345666333** [comment]
Looks like there has been no progress on this issue. Can I pick it up?

**Comment by sharathsivakumar** [comment]
@tao12345666333 I started working on this yesterday, I will be finishing it this week.

**Comment by tao12345666333** [comment]
thanks

**Comment by jmhbnz** [comment]
Hey @sharathsivakumar Can I please check in on this issue, are you still working on this or can I open it up to the community once more?

**Comment by sharathsivakumar** [comment]
Hello @jmhbnz. I was sick last week. I am still working on this. I will complete this on priority this week. If am still unable to do it, I will let you know and it can be opened to the community.
