### ISSUE TITLE
how do i use client v2? i seem to get a lot of dependencies issues with routing with coreos repo etc and bbolt issues

### ISSUE THREAD

**Issue by kolinfluence** [etcd-io/etcd#15968]
### What happened?
```
pkg/models/etcd imports
        github.com/etcd-io/etcd imports
        github.com/coreos/etcd/etcdmain imports
        github.com/coreos/etcd/etcdserver imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.7: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```
with reference to https://github.com/etcd-io/etcd/issues/13559

this prank is not funny with all the redirects etc. e.g. go.etcd.io.

it took me 12 hours trying to figure out how to have v2.3
can anyone kind enough just gimme an idea how to use etcd v2.3 /client ?

no golang repo this important is this frustrating just on imports. etcd outdone them all.

i need to voice my displeasure at this. it's overly frustrating as i've spent countless hours on just trying to figure out how to import this.

### What did you expect to happen?

normal import without issues when doing go mod vendor or go mod tidy

### How can we reproduce it (as minimally and precisely as possible)?
```
pkg/models/etcd imports
        github.com/etcd-io/etcd imports
        github.com/coreos/etcd/etcdmain imports
        github.com/coreos/etcd/etcdserver imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.7: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```
### Anything else we need to know?

this import of etcd.io etc is crazy with the redirection etc etc etc.

possible to make it just "github.com/etcd-io/etcd" like most sane packages? thx in advance.

p.s. : u have no idea how much work i needed to do to change v2 to v3 and then back to v2 and then trying to figure out how to import properly. took 12 hours and i am falling back to v2 (v2.3 specifically) because v3 upgrade is too much work without KeyAPI etc. 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment]
Hi @kolinfluence - Thanks for your question. Given this is a support issue and I see we already have an active discussion https://github.com/etcd-io/etcd/discussions/15967 I will be closing this as a duplicate, refer: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md#support-requests

Please respond in the discussion with the information requested.
