### ISSUE TITLE
Etcd nightly arm64 e2e common tests state they have been cached

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15986]
### What happened?

Sub issue under https://github.com/etcd-io/etcd/issues/15951.

We recently moved to container based nightly `arm64` workflow runs which appear to be completing successfully however the e2e `common` suite is reporting unexpected caching, refer: https://github.com/etcd-io/etcd/actions/runs/5116632303/jobs/9198983536 

```bash
'e2e' started at Tue May 30 01:34:05 UTC 2023
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/e2e' '-timeout=30m')
ok  	go.etcd.io/etcd/tests/v3/e2e	529.611s
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/common' '--tags=e2e' '-timeout=30m')
ok  	go.etcd.io/etcd/tests/v3/common	(cached)
'e2e' PASSED and completed at Tue May 30 01:42:58 UTC 2023
SUCCESS
```

### What did you expect to happen?

Caching between test runs is not expected. We need to investigate if this will lead to issues and raise a fix if required.

### How can we reproduce it (as minimally and precisely as possible)?

1. Run an e2e arm64 workflow job either on demand or via standard nightly schedule.
2. Open job logs for the `Run set -euo pipefail` step.
3. Review e2e test result summary showing cache indicator at end of test ok line.

**Comment by jmhbnz** [comment]
This is an example of the docker command being run when a job starts:

```bash
  /usr/bin/docker create --name 14add6156de149daa60ccb6ffe1c939f_golang119bullseye_4fa1a9 --label d94681 --workdir /__w/etcd/etcd --network github_network_59987ababe414f769a60e7715d8ec26d  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/actions-runner/_work":"/__w" -v "/home/runner/actions-runner/externals":"/__e":ro -v "/home/runner/actions-runner/_work/_temp":"/__w/_temp" -v "/home/runner/actions-runner/_work/_actions":"/__w/_actions" -v "/home/runner/actions-runner/_work/_tool":"/__w/_tool" -v "/home/runner/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/runner/actions-runner/_work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" golang:1.19-bullseye "-f" "/dev/null"
```

As part of that command the workdir is persisted to disk via volume mount:

```bash
-v "/home/runner/actions-runner/_work":"/__w"
```

The github `setup-go` action is using a `/__w/_tool` subdirectory within that workdir for cache. Very recently in 4.0.0 cache functionality was enabled by default, refer: https://github.com/actions/setup-go/releases/tag/v4.0.0

```
Setup go version spec 1.19.9
Found in cache @ /__w/_tool/go/1.19.9/arm64
Added go to the path
Successfully set up Go version 1.19.9
/__w/_tool/go/1.19.9/arm64/bin/go env GOMODCACHE
/__w/_tool/go/1.19.9/arm64/bin/go env GOCACHE
/go/pkg/mod
/github/home/.cache/go-build
Received 239075328 of 288578851 (82.8%), 226.9 MBs/sec
Received 288578851 of 288578851 (100.0%), 226.5 MBs/sec
Cache Size: ~275 MB (288578851 B)
/bin/tar -xf /__w/_temp/b830f5f5-b769-45ad-86f9-fba0b680799d/cache.tgz -P -C /__w/etcd/etcd -z
Cache restored successfully
Cache restored from key: setup-go-Linux-go-1.19.9-a66a2536ade4f9a6ef8c5341cefed828cb15d10cad9f042832941606c1c1f679
go version go1.19.9 linux/arm64
```

Now after reading some more docs I'm not entirely convinced this is actually an issue, because golang will automatically not use the cache if there is any change to source files which of course is going to happen as part of the earlier checkout action. However, we do have the option of adding `cache: false` for our `arm64` `setup-go` actions, refer: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs 

@ahrtr, @serathius - What is your preference here? At the moment the cache is giving us a performance improvement, and when source files are updated standard golang behaviour of not using and updating cache will kick in. But if we want extra guarantees about isolation I can disable the cache feature.

**Comment by ahrtr** [comment]
Thanks @jmhbnz for the detailed analysis. I vote for disabling the cache, because we do need completely isolation between any two test suites.

**Comment by chaochn47** [comment]
Thank!! It is super helpful analysis. 

IMO, if the amd64 workflow always disables the cache, it's better to make those two workflows behavior consistent.

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/etcd/pull/15989#issuecomment-1571099422

**Comment by jmhbnz** [comment]
Closing as #15989 has merged and latest overnight run now shows no test caching. We have a separate good first issue open for rolling out the change to remaining non `arm64` test suites.
