### ISSUE TITLE
Move .golangci.yaml out of top level directory to reduce clutter

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15987]
### What would you like to be added?

Sub issue under https://github.com/etcd-io/etcd/issues/15951.

We've recently made efforts to simplify the etcd project top level directory by removing or shifting some configuration files, refer https://github.com/etcd-io/etcd/issues/15778 and https://github.com/etcd-io/etcd/pull/15966#discussion_r1209625231.

The scope of this issue is to move the `.golangci.yaml` configuration file under the `tools/` directory.

Once moved we then need to update our Makefile so it will pass the `--config` parameter when invoking `golangci-lint run`, i.e:

```diff
.PHONY: verify-lint
verify-lint:
-	golangci-lint run
+	golangci-lint --config tools/.golangci.yaml run

.PHONY: update-lint
fix-lint:
-	golangci-lint run --fix
+	golangci-lint --config tools/.golangci.yaml run --fix
```

### Why is this needed?

Reduce the noise in the top level etcd project directory.

**Comment by tao12345666333** [comment]
Please assign this to me, thanks!

**Comment by jmhbnz** [comment]
Fair point - I'm happy for either `hack` or `tools` to be used so if there is broader consensus that `hack` is the better place then we can use this issue to move all three at once.

Will wait a day or two to see if anyone has different views before I update this issue description in favor of `hack`.

**Comment by tao12345666333** [comment]
Here are some examples for reference.

* [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/hack#overview)

> The [hack](https://github.com/kubernetes/kubernetes/blob/master/hack) directory contains many scripts that ensure continuous development of kubernetes, enhance the robustness of the code, improve development efficiency, etc. The explanations and descriptions of these scripts are helpful for contributors. For details, refer to the following guidelines.

* [Docker](https://github.com/moby/moby/tree/master/hack)

> This directory contains a collection of scripts used to build and manage this repository. If there are any issues regarding the intention of a particular script (or even part of a certain script), please reach out to us. It may help us either refine our current scripts, or add on new ones that are appropriate for a given use case.


Overall, the hack directory contains some content that is useful for development projects and can be used to enhance the developer experience.

I agree with @serathius 's opinion to move these configuration files to the `hack` directory.

**Comment by jmhbnz** [comment]
Sounds good to me. I've updated our issue description to reflect `hack/` thanks! 🙂

**Comment by ahrtr** [comment]
It isn't a big deal, but it makes more sense to get `.golangci.yaml`, `.yamllint` and `.yamlfmt` and included in `tools/config`, because `golangci-lint`, `yamlfmt` and `yamllint` are tools being used by etcd, and are configured (version) under tools, it's natural to put the related configuration files for the tools under tools, e.g. `tools/config`.

**Comment by tao12345666333** [comment]
The current disagreement between us is whether to move these configuration files to the tools directory or the hack directory.

 In addition to the above comments, @ahrtr also provided additional comments in another PR review.   https://github.com/etcd-io/etcd/pull/15966#issuecomment-1575546951

>Just as I mentioned in https://github.com/etcd-io/etcd/issues/15987#issuecomment-1571393182, I don't think it's good to put the config files under hack. The utilities & scripts under hack are various hacks which are used by developers (just for developers reference); while all tools under tools are used by etcd itself. Removing anything under tools will break the etcd (e.g. build, workflow check etc), but removing anything under hack will not impact etcd itself at all.

I think as long as we reach an agreement and write it down in the document, we can follow this plan for the rest of the process.

**Comment by jmhbnz** [comment]
Hey @tao12345666333 - For now can you please proceed with moving all three files to `tools/config/<filename>`.  This is a good starting point and I see no issue with getting an initial pull request merged because we can always revisit it later if necessary.

Thanks again for your help getting this work done! 🙏🏻

**Comment by tao12345666333** [comment]
sure
