### ISSUE TITLE
Add clean of golang test cache to remaining etcd ci test suites

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#15995]
### What would you like to be added?

Sub issue under https://github.com/etcd-io/etcd/issues/15951

Recently in https://github.com/etcd-io/etcd/pull/15989 we updated our etcd `arm64` ci workflows to ensure the golang test cache was explicitly cleared before the suite ran by adding `go clean -testcache` to the workflows.

For context this was required after our move to running `arm64` etcd ci tests in containers due to the github actions runner default behaviour of mounting the workdir as a volume, which fixed our process isolation issues but still had some unexpected caching on disk, refer https://github.com/etcd-io/etcd/issues/15986#issuecomment-1570841851.

We have plans to move all remaining etcd ci workflows to containers soon under https://github.com/etcd-io/etcd/issues/15956, even if that doesn't go ahead we should probably roll the cache clean out to our other etcd ci workflows for consistency reasons.

Files that would need to be updated are:

```bash
.github/workflows/tests.yaml
.github/workflows/robustness-template.yaml
.github/workflows/e2e.yaml
````

### Why is this needed?

Have one standardised approach for etcd unit/integration, e2e and robustness tests.  Prevent unexpected cache behaviour once non arm64 ci tests migrate to running within containers.

**Comment by Azanul** [comment]
May I give this a try?

**Comment by jmhbnz** [comment]
Hi @Azanul - Absolutely! Thanks.  I've assigned it to you, please let me know here or in kubernetes slack if you have any questions 🙏🏻
