### ISSUE TITLE
Update golang patch version to latest 1.19.10 release

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16025]
### What would you like to be added?

A new go patch release has been published:

> go 1.19.10 (released 2023-06-06) includes four security fixes to the `cmd/go` and `runtime` packages, as well as bug fixes to the compiler, the go command, and the runtime. See the [Go 1.19.10 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.10+label%3ACherryPickApproved) for details.

We should update to this version by bumping the version in `.go-version` file in the `main` branch.

Once the changes have been merged in `main` we should backport the changes to `release-3.5` and `release-3.4` branches as well so the fixes can make it into our next patch releases.

### Why is this needed?

Keep etcd projects up to date with the latest patch releases and incorporate the latest security updates.

**Comment by daljitdokal** [comment]
Hey @jmhbnz, I am keen to work on this. thanks.

**Comment by jmhbnz** [comment]
Awesome thanks @daljitdokal, I've assigned it to you :)

**Comment by charles-chenzz** [comment]
are there still have any good-first-issues like this for new contributor? @jmhbnz

**Comment by jmhbnz** [comment]
> are there still have any good-first-issues like this for new contributor? @jmhbnz

Hey @charles-chenzz - There sure is, we actually need to roll out this golang patch upgrade across the `etcd-io/raft` and `etcd-io/bbolt` repositories as well.  The process is a bit longer for those repositories as there is more than one file to update but here is an example for bbolt: https://github.com/etcd-io/bbolt/pull/487 

Please feel free to have a go at those and tag me for a review when you raise a pull request.  I'm happy to answer any questions via Kubernetes slack 🙏🏻

**Comment by charles-chenzz** [comment]
will take a look at it and tag you when I'm ready to go. Thanks!

**Comment by ahrtr** [comment]
Once the changelog PR is raised & merged, we can close this issue. cc @daljitdokal @jmhbnz

**Comment by jmhbnz** [comment]
Changelog updates merged, closing 🙂
