### ISSUE TITLE
Deprecated bcrypt in favor of argon2id

### ISSUE THREAD

**Issue by yonas** [etcd-io/etcd#16101]
### What would you like to be added?

Argon2id hashes. https://pkg.go.dev/golang.org/x/crypto/argon2

### Why is this needed?

Bcrypt is outdated and deprecated. Argon2id is a highly recommended modern replacement.

**Comment by iuriatan** [comment]
It seems Bcrypt last release is from Jul 5, 2023. Why do you say it's outdated and deprecated?

**Comment by jmhbnz** [comment]
Discussed during sig-etcd replacing bcrypt is not currently a priority for the project, closing for now. We can always revisit this in future if bcrypt becomes problematic.
