### ISSUE TITLE
Latest coreos/etcd docker image seems to be broken 

### ISSUE THREAD

**Issue by jpettersson** [etcd-io/etcd#1611]
I'm using the official `coreos/etcd` docker image in some system tests. Today I cleared all my cached images and discovered that the etcd container was broken (the http API is not responding on port 4001). 

Then I realized that the description of the docker repo is "Automatic builds from master" and that the two latest builds returned "Error": https://registry.hub.docker.com/u/coreos/etcd/builds_history/4751/

Since the docker repo only contained the "latest" image I searched through the releases in this repo and found that I could get an old release directly (quay.io/coreos/etcd:v0.4.6) which works. 

Would it make sense to publish all stable tags to the docker repo? The repo is heavily used (26748 downloads) so I think it would make sense to provide real stable builds, not just the latest master.

**Comment by maplain** [comment]
@philips 
looks like it still has this problem. 
https://github.com/coreos/etcd/blob/master/Dockerfile-release#L11
still no ENTRYPOINT.
need to add /usr/local/bin/etcd after image name when 'docker run', and this one needs to be updated: https://coreos.com/etcd/docs/latest/v2/docker_guide.html.
