### ISSUE TITLE
[grpc-proxy] token expires, the new watch does not refresh the token.

### ISSUE THREAD

**Issue by JKeita** [etcd-io/etcd#16112]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When a token expires, creating a new watch will cause all other watches to become invalid.

### What did you expect to happen?

Creating a watch and waiting for the token to expire after 10 seconds, and then creating another watch will cause all watches to become invalid.

### How can we reproduce it (as minimally and precisely as possible)?

start etcd:
`
./etcd --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --auth-token-ttl 10
`

start grpc-proxy:
`
./etcd grpc-proxy start --endpoints=0.0.0.0:2379 --listen-addr=0.0.0.0:23790
`

test example:
`
package main

import (
	"context"
	"fmt"
	clientv3 "go.etcd.io/etcd/client/v3"
	"google.golang.org/grpc"
	"time"
)

func main() {
	cli, _ := clientv3.New(clientv3.Config{
		Endpoints:   []string{"centos7:23790"},
		DialTimeout: time.Second * 5,
		DialOptions: []grpc.DialOption{grpc.WithBlock()},
	})
	fmt.Println("start")
	ctx, _ := context.WithCancel(context.Background())
	ch := cli.Watch(ctx, "/key")
	for resp := range ch {
		if resp.Err() != nil {
			fmt.Println(resp.Err())
		}
		for _, e := range resp.Events {
			k, v := e.Kv.Key, e.Kv.Value
			fmt.Println(k, v)
		}
	}
}

`

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.5.4
Git SHA: 08407ff76
Go Version: go1.16.15
Go OS/Arch: linux/amd64

$ etcdctl version
# paste output here
etcdctl version: 3.5.4
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by CaojiamingAlan** [comment]
Please see https://github.com/etcd-io/etcd/issues/12385 and https://github.com/etcd-io/etcd/pull/14995.

I think currently you can fix this by the way mentioned in #14995: create a new client each time before watching.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting. @ahrtr is this a valid bug or should we close it given we have a workaround of opening new client before watch?

**Comment by ahrtr** [comment]
Duplicated to https://github.com/etcd-io/etcd/issues/15058
