### ISSUE TITLE
Tag for codeql-action/upload-sarif action not being updated by dependabot

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16147]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

The etcd project has weekly pull requests automatically raised by dependabot to bump project dependencies, this includes bumping github actions versions.

The github actions version bumps generally look something like the example below with both the git sha and tag comment being updated:

```diff
-        uses: github/codeql-action/init@6c089f53dd51dc3fc7e599c3cb5356453a52ca9e # v2.20.0
+        uses: github/codeql-action/init@f6e388ebf0efc915c6c5b165b019ee61a6746a38 # v2.20.1
```

For our `upload-sarif` action the tag comment is not being updated because it appears the tag format is incorrect and not recognized by dependabot, an example is https://github.com/etcd-io/etcd/pull/16146#discussion_r1242865077.

We should raise a quick pull request to fix the tag format in `.github/workflows/scorecards.yml` so that it matches `# v2.20.1`

### What did you expect to happen?

Tag comment should be updated automatically by dependabot.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduced historically in a number of previous dependabot prs: https://github.com/etcd-io/etcd/pulls?q=is%3Apr+is%3Amerged+%22github%2Fcodeql-action%22

**Comment by CaojiamingAlan** [comment]
Raised #16148 to fix this. BTW I don't know why 38b7406e successfully updates the tag in comment. My guess is it is because it was the only file that needed to be updated. The bot cannot recognize different patterns in one single commit.

**Comment by jmhbnz** [comment]
Related: https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions
