### ISSUE TITLE
etcdcli response cannot be parsed by given protocol

### ISSUE THREAD

**Issue by leinjay** [etcd-io/etcd#16162]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

when i send http request LeaseKeepAliveRequest to 127.0.0.1/v3/lease/keepalive, its reply is {"result":{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"18368864","raft_term":"12"},"ID":"7587866981219935711","TTL":"600"}} ,whitch can not be paresed by LeaseKeepAliveResponse

### What did you expect to happen?

can be paresed by LeaseKeepAliveResponse

### How can we reproduce it (as minimally and precisely as possible)?

fix it 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by CaojiamingAlan** [comment]
What struct are you expecting? The response you give is exactly the same as the [definition](https://github.com/etcd-io/etcd/blob/57a583d14021c3f2ffd25ceae6993a28a3a0a691/api/etcdserverpb/rpc.pb.go#L2737-L2746).

**Comment by fuweid** [comment]
@leinjay please follow the instructions when you file issue, since there is no much useful information (such as etcd version, how to file the request, how to unmarshal the request, etc) to verify the problem you are running into. Thanks

**Comment by jmhbnz** [comment]
Closing - Not enough information provided to reproduce a bug.
