### ISSUE TITLE
Add documentation for new snapshot restore flags

### ISSUE THREAD

**Issue by dusk125** [etcd-io/etcd#16160]
### What would you like to be added?

In #16029, new flags were added to `etcdutl snapshot restore` (`--bump-revision` and `--mark-compacted`) that need user documentation; this issue will add this documentation.

### Why is this needed?

The flags are a part of the effort (#16028) to enhance restore without breaking api guarantees, and should be documented so users can understand how they work and what effects they have on their restored etcd instance.

**Comment by dusk125** [comment]
I can handle this issue

**Comment by jmhbnz** [comment]
Hey @dusk125 - How are you going with this issue?  Please let us know if we should open this issue up for the community, thanks! 🙏🏻

**Comment by dusk125** [comment]
Hey @jmhbnz, this issue is still on my todo list, but feel free to open it up if someone can/wants to handle it before I get back to this. I've been working on a time sensitive project which is why this and my other PR have stalled, but that is wrapping up, so I'll be able to dedicate more time to both.

**Comment by jmhbnz** [comment]
Adding contribfest label.  This would be a good candidate for the upcoming etcd contribfest at Kubecon.

For a quick hint to whoever picks this up, the flag documentation needs to be added to https://github.com/etcd-io/etcd/blob/main/etcdutl/README.md.

**Comment by spawulski** [comment]
contribfest: I can try take on this issue
