### ISSUE TITLE
GRPC 1.26 and above are not supported

### ISSUE THREAD

**Issue by moyunnie** [etcd-io/etcd#16175]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

The code generated by protoc is dependent on GRPC 1.32, so cannot it support the latest version of GRPC

### What did you expect to happen?

Error reporting

### How can we reproduce it (as minimally and precisely as possible)?

Higher than grpc 1.26 will occur

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by wenjiaswe** [comment]
For etcd v3.4, grpc version is [1.26](https://github.com/etcd-io/etcd/blob/fee612d9008ad910d673da9b75d2c78194f153b9/go.mod#L42), but it's [1.41](https://github.com/etcd-io/etcd/blob/f3f37299e649874f8bcf410527c274dda1d78d04/go.mod#L35) in v3.5 and [1.51](https://github.com/etcd-io/etcd/blob/e887e5291aa1b5891280456ac7ffa45f06afca16/go.mod#L37) at head.

Please let us know if that doesn't answer your question.

**Comment by wonbin2011** [comment]
> 

there is vulnerability in grpc under version 1.53.1
![image](https://github.com/etcd-io/etcd/assets/7733385/89f927df-8011-4cb8-85d4-e19572e2256f)
