### ISSUE TITLE
Streamline test commands between branches

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16176]
### What would you like to be added?

Sub issue under https://github.com/etcd-io/etcd/issues/15951.

I would like to be able to run tests in github actions workflows across etcd branches using the same command.

Currently every branch is different, refer to end test suite as the example:

| Branch      | Command                                                                                                |
|-------------|--------------------------------------------------------------------------------------------------------|
| main        | `make test-e2e-release`                      |
| release-3.5 | `PASSES='build release e2e' COVER='false' ./test.sh` |
| release-3.4 | `PASSES='build release e2e' ./test`                                                       |

I would like to use this issue to explore if a minimal backport from `main` can be done to allow both `release-3.5` and perhaps also `release-3.4` to also use the same commands to run test suites.

### Why is this needed?

Currently etcd ci workflow test commands are different between branches, this creates confusion, cognitive burden and makes our github actions workflow templates brittle and over complicated.

**Comment by serathius** [comment]
Note: release-3.5 should also run `PASSES='build release e2e' ./test`

**Comment by jmhbnz** [comment]
> Note: release-3.5 should also run `PASSES='build release e2e' ./test` like release-3.4. Don't know why it's different.

Ahh I copied the command from the `arm64` files in my open pr rather than the release-3.5 existing branch workflow file.  I need to look at why none of our `arm64` workflows have it included.
