### ISSUE TITLE
Backport https://github.com/etcd-io/etcd/pull/13577 to both 3.5 and 3.4

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#16235]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

The PR hasn't been backported to 3.5, nor 3.4.

### What did you expect to happen?

We should backport the PR to both 3.5 and 3.4.

### How can we reproduce it (as minimally and precisely as possible)?

See the PR and https://github.com/etcd-io/etcd/issues/12385

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by liangyuanpeng** [comment]
I want to try it.

**Comment by jmhbnz** [comment]
Thanks @liangyuanpeng!  Please comment here or message on kubernetes slack if you have any questions 🙏🏻

**Comment by ahrtr** [comment]
I will close this ticket once the changelog is updated. https://github.com/etcd-io/etcd/pull/16241#issuecomment-1635680660
