### ISSUE TITLE
Nominating @jmhbnz as etcd reviewer

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#16233]
### Who would you like to nominate?

I would like to propose @jmhbnz for role of [reviewer](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#requirements-1).

@jmhbnz has showed contributions and leadership exceeding expectations for etcd reviewer. He is leading the whole effort for [improving etcd continuous integration and ARM64 support](https://github.com/etcd-io/etcd/issues/15951). 

He was crucial in organizing etcd presense during KubeCon, by proposing work and couching new contributors during ContribFest session and staffing the etcd booth.

He [reviewed over 200 PRs](https://github.com/etcd-io/etcd/pulls?q=is%3Apr+reviewed-by%3Ajmhbnz+is%3Aclosed) and [merged over 50](https://github.com/etcd-io/etcd/pulls?q=is%3Apr+author%3Ajmhbnz+is%3Amerged+).
 
 He is participating both in technical part of the project by being [the third most active contributor to etcd](https://github.com/etcd-io/etcd/pulls?q=is%3Apr+author%3Ajmhbnz+is%3Amerged+) and organizational part by participating and [helping organise the etcd community meetings](https://github.com/etcd-io/etcd/pull/16189). 
 
He authored the etcd triage instructions and are still are actively triaging and helping community.

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md)
- [X] The members are actively contributing to 1 or more etcd subprojects
- [X] The members are being sponsored by two current reviewers or a current maintainer.

### How do the new members meet the regular active contribution requirements?

* member for at least 3 months. [Joined April 7th](https://github.com/etcd-io/etcd/issues/15665)
* Primary reviewer for at least 5 PRs to the codebase.
  * https://github.com/etcd-io/etcd/pull/15790
  * https://github.com/etcd-io/etcd/pull/15893
  * https://github.com/etcd-io/etcd/pull/15909
  * https://github.com/etcd-io/etcd/pull/15966
  * https://github.com/etcd-io/etcd/pull/16066
  * https://github.com/etcd-io/etcd/pull/16097
  * https://github.com/etcd-io/etcd/pull/16119
  * https://github.com/etcd-io/etcd/pull/16146
* Reviewed or contributed at least 20 substantial PRs to the codebase.
  * https://github.com/etcd-io/etcd/pull/15239
  * https://github.com/etcd-io/etcd/pull/15383
  * https://github.com/etcd-io/etcd/pull/15486
  * https://github.com/etcd-io/etcd/pull/15544
  * https://github.com/etcd-io/etcd/pull/15577
  * https://github.com/etcd-io/etcd/pull/15604
  * https://github.com/etcd-io/etcd/pull/15713
  * https://github.com/etcd-io/etcd/pull/15881
  * https://github.com/etcd-io/etcd/pull/15886
  * https://github.com/etcd-io/etcd/pull/15890
  * https://github.com/etcd-io/etcd/pull/15904
  * https://github.com/etcd-io/etcd/pull/15938
  * https://github.com/etcd-io/etcd/pull/15957
  * https://github.com/etcd-io/etcd/pull/16003
  * https://github.com/etcd-io/etcd/pull/15998
  * https://github.com/etcd-io/etcd/pull/16087
  * https://github.com/etcd-io/etcd/pull/16116
  * https://github.com/etcd-io/etcd/pull/16152
  * https://github.com/etcd-io/etcd/pull/16189
* Knowledgeable about the codebase.
  * @jmhbnz is the go to person for etcd continuous integration infrastructure and ARM64 support
  * @jmhbnz defined the etcd triage policy 
* Sponsored by two active maintainers.
  * @serathius, Google
  * @ahrtr, VMware
  *  [x] Sponsors must be from multiple member companies to demonstrate integration across community.

**Comment by serathius** [comment]
cc @ahrtr @ptabor @wenjiaswe @mitake @spzala

**Comment by ahrtr** [comment]
Thanks @jmhbnz for your great contribution. Also congratulations!

**Comment by jmhbnz** [comment]
Wow thanks team, this is wonderful news! 

Absolutely looking forward to continued contribution and learning, thanks for your support! 🙏🏻

**Comment by serathius** [comment]
With both sponsors LGTM I'm closing as accepted. 

@jmhbnz Can you send PR to add yourself in https://github.com/etcd-io/etcd/blob/main/MAINTAINERS ?

**Comment by spzala** [comment]
+1 @jmhbnz thanks for your active role and great contributions! Congratulations!

**Comment by BobyMCbobs** [comment]
Woohoo! Great work and congradulations @jmhbnz!
