### ISSUE TITLE
TestPageWriterRandom fails on ARM

### ISSUE THREAD

**Issue by zaitcev** [etcd-io/etcd#16275]
### Which github workflows are flaking?

The issue occurs in CI of Fedora Linux, not on Github, and only on architectures other than x86_64, such as aarch64.

### Which tests are flaking?

TestPageWriterRandom

### Reason for failure (if possible)

The TestPageWriterRandom has 2 problems.

Problem 1: it uses rand.Intn(), but forgets rand.Seed().
As a result, it passes or fails depending on how the platform
sets up the module. This is why it passes on x86_64: the platform
happens to seed the rand module in such a way that the sequence
makes the buggy test to work.

If I adds rand.Seed(time.Now().UnixNano()), the test begins to
fail on my laptop in the exact way it fails in Koji on aarch64.

Problem 2: The test is obviously incorrect, even though it
existed with no change since it was committed in 2016,
commit 2943bf908606ccbfaeda3bdf882a11a0138a0502.

The condition it tests obviously may fail. The buffer can
contain several pages (especially if they're this small).
If the very first write is longer several pages,
  if len(p)+pw.bufferedBytes <= pw.bufWatermarkBytes { }
triggers, and Write returns, while retaining everything
written in the buffer. At that point, the as-tested
condition is obviously violated, as cw.writeBytes is zero.
I'm too lazy to construct a long scenario, but it obviously
can happen on the last write too (for example, if the
previous 4045 writes reset the buffer to zero by accident).

The tested condition needs to change to a valid one.

**Comment by fuweid** [comment]
@zaitcev Hi, I don't have arm64 linux env but I can try to reproduce it in my M1 macos. Wish me luck :)

**Comment by zaitcev** [comment]
@fyweud It may be a misunderstanding. Your fix (to the arithmetic) looks good to me and it fixes the problem. However, adding a rand.Seed() that I propose, allows to reproduce the problem on x86_64. With that in place, there is no need to use PPC or ARM.

**Comment by zaitcev** [comment]
I made a follow-up PR.

**Comment by jmhbnz** [comment]
Closing following our migration to go 1.20 where global random is now seeded automatically, this flake should no longer be occurring.

**Comment by zaitcev** [comment]
Sure, if that's the consensus. I'll make sure to withdraw the PR too unless it's already closed.
