### ISSUE TITLE
pkg/flags: UniqueURLs'Set cannot deduplicate uss(a slice)

### ISSUE THREAD

**Issue by callthingsoff** [etcd-io/etcd#16307]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Test function `UniqueURLsFromFlag`:

```go
func TestUniqueURLsFromFlag(t *testing.T) {
	const name = "test"
	urls := []string{
		"https://1.2.3.4:1",
		"https://1.2.3.4:2",
		"https://1.2.3.4:3",
		"https://1.2.3.4:1",
	}
	fs := flag.NewFlagSet(name, flag.ExitOnError)
	u := NewUniqueURLsWithExceptions(strings.Join(urls, ","))
	fs.Var(u, name, "usage")
	uss := UniqueURLsFromFlag(fs, name)

	require.Equal(t, len(u.Values), len(uss))

	um := make(map[string]struct{})
	for _, x := range uss {
		um[x.String()] = struct{}{}
	}
	require.Equal(t, u.Values, um)
}
```

```output
Error Trace:    /Users/jes/go/src/etcd/pkg/flags/unique_urls_test.go:113
                Error:          Not equal:
                                expected: 3
                                actual  : 4
                Test:           TestUniqueURLsFromFlag
```
### What did you expect to happen?

None

### How can we reproduce it (as minimally and precisely as possible)?

Run the test.

### Etcd version (please run commands below)

Sorry, I only reviewed the code and tested it. 
No more details could be provided.

**Comment by ahrtr** [comment]
Let's close this after the backport PRs are merged, and also the changelog items are added.

**Comment by serathius** [comment]
Merged.
