### ISSUE TITLE
"github.com/gyuho/gocovmerge" in tools/mod/go.mod depencies is not a public respository

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#16322]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

The impact but minimal but annoying. IDE indexing failed.. 

### What did you expect to happen?

I expect this dependency should be under `etcd-io` org instead of located in a previous maintainer's repository. 

Somehow the action workflows have access to the repository but it's a potential risk. 

### How can we reproduce it (as minimally and precisely as possible)?

```
go list -modfile=tools/mod/go.mod -m -json -mod=mod all

go: github.com/gyuho/gocovmerge@v0.0.0-20171205171859-50c7e6afd535: invalid version: git ls-remote -q origin in /Users/chaochn/go/pkg/mod/cache/vcs/516c73b4fb2f2a3afac6e6b2b379be19f37566c31ceb2ace7992c16357e2c4f8: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
go: github.com/gyuho/gocovmerge@v0.0.0-20171205171859-50c7e6afd535: invalid version: git ls-remote -q origin in /Users/chaochn/go/pkg/mod/cache/vcs/516c73b4fb2f2a3afac6e6b2b379be19f37566c31ceb2ace7992c16357e2c4f8: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

### Etcd version (please run commands below)

It's on main branch. But I assume all the other release branch is also impacted. 

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by chaochn47** [comment]
ref. https://github.com/etcd-io/etcd/issues/13684#issuecomment-1036655469

**Comment by ahrtr** [comment]
thx @chaochn47 for reporting this.

Somehow I couldn't reproduce this issue locally, but confirmed that the repo is inaccessible via browser. I am not sure whether the repo is private or it has been deleted.

I think we need find an alternative solution.

```
$ go get github.com/gyuho/gocovmerge@v0.0.0-20171205171859-50c7e6afd535
$
$ go get github.com/ahrtr/abc
go: module github.com/ahrtr/abc: git ls-remote -q origin in /Users/wachao/go/pkg/mod/cache/vcs/9191079668e0774249fc16fc0224263d40c5b221409e4800ba88ae1ba4203eb1: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

@gyuho could you please feedback on this? thx

**Comment by chaochn47** [comment]
> I think we need find an alternative solution.

I think we could dig into the module cache and copy it from there as the last resort..
