### ISSUE TITLE
Remove etcdutl backup command

### ISSUE THREAD

**Issue by geetasg** [etcd-io/etcd#16321]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

From some of the code review discussions in https://github.com/etcd-io/etcd/pull/16132, it seems like etcdutl backup command should be removed in 3.6. (etcdutl/etcdutl/backup_command.go)

This issue is meant to -
* Confirm that the command needs to be removed.
* if so then , communicate with the user base that the command will be removed in 3.6 and remove it.

### What did you expect to happen?

command should not be there if it is not used anymore.

### How can we reproduce it (as minimally and precisely as possible)?

Usage:
  etcdutl [command]

Available Commands:
  backup      [legacy] offline backup of etcd directory
  completion  Generate completion script
  defrag      Defragments the storage of the etcd
  help        Help about any command
  migrate     Migrates schema of etcd data dir files to make them compatible with different etcd version
  snapshot    Manages etcd node snapshots
  version     Prints the version of etcdutl

Remove the backup command if it should not be there in 3.6

### Anything else we need to know?

Also discussed at  https://github.com/etcd-io/etcd/pull/16132

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.6.0-alpha.0
Git SHA: fac4102ab
Go Version: go1.20.4

$ etcdctl version
# paste output here
```
etcdctl version: 3.6.0-alpha.0
API version: 3.6

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment]
Fixed in https://github.com/etcd-io/etcd/pull/16662.
