### ISSUE TITLE
Add a top level OWNERS file to top each etcd.io subproject

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#16367]
### What would you like to be added?

Add a top level OWNERS file to top each etcd.io subproject.

### Why is this needed?

It's a hard requirement to set up sig-etcd: https://github.com/kubernetes/community/pull/7372#discussion_r1282462443.

**Comment by jmhbnz** [comment]
Can I double check does this include ALL repos under `etcd-io`?  

Here is the list of all repos for reference:

- [ ] etcd-io/etcd-play (public archive)
- [ ] etcd-io/cetcd
- [ ] etcd-io/protodoc
- [ ] etcd-io/etcdlabs
- [ ] etcd-io/maintainers (is this even used, could we archive or delete?)
- [ ] etcd-io/discoveryserver
- [ ] etcd-io/govanityurls
- [ ] etcd-io/dbtester
- [ ] etcd-io/zetcd
- [ ] etcd-io/raft
- [ ] etcd-io/gofail
- [ ] etcd-io/discovery.etcd.io
- [ ] etcd-io/website
- [ ] etcd-io/bbolt
- [ ] etcd-io/jetcd
- [ ] etcd-io/etcd

Let's confirm which repos are in scope then we can start getting PR's drafted :)

**Comment by jmhbnz** [comment]
Hey Team - I've confirmed with @mrbobbytables that repositories marked as public archive do not need to be included in this work of seeding initial `OWNERS` files.

With that in mind I would like to propose @etcd-io/maintainers-etcd mark the `etcd-io/maintainers` repository as public archive, as it has not been updated/touched since 2019 and does not seem to be in any way actively used.

Based on my list above that would then leave us 14 pr's to raise.  I have made a start on the first one to get us moving: https://github.com/etcd-io/etcd/pull/16600

**Comment by jmhbnz** [comment]
Update: All required `OWNERS` files have now been merged. There were four repositories proposed for public archival, 2/4 have been completed, the other two are in progress pending maintainer majority approval.

We have an active pr in progress on the kubernetes/org repo to implement automated management for the etcd-io org: https://github.com/kubernetes/org/pull/4498.

Once that is merged we should cleanup to ensure:
1 - Any process documentation about repository access management is updated
2 - Remove the now defunct / duplicate `MAINTAINERS` files.

The following repositories will need a cleanup pr to at minimum remove old `MAINTAINERS` file:

- [ ] etcd-io/etcd
- [ ] etcd-io/website
- [ ] etcd-io/jetcd
- [ ] etcd-io/bbolt
- [ ] etcd-io/raft

**Comment by jmhbnz** [comment]
All etcd-io subprojects now have a top level `OWNERS` file where required and followup action to tidy up old `MAINTAINERS` files has also been completed, closing.

As a next step we should begin exploring more fine grained code ownership for specific aspects of `etcd-io/etcd` but that can be addressed in subsequent issues.

**Comment by jmhbnz** [comment]
Reopen to backport `OWNERS` to `release-3.5` and `release-3.4` in support of improved automation via prow.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, assigned to @thedtripp for backport https://github.com/etcd-io/etcd/pull/16794 to `release-3.5` and `release-3.4`.

/assign @thedtripp

**Comment by jmhbnz** [comment]
Hey @thedtripp - Now that we have `release-3.5` completed do you have capacity to also tackle the backport `release-3.4` so we can close this out? 🙏🏻

**Comment by thedtripp** [comment]
Hey @jmhbnz, yes, I will work on this over the next few days.

**Comment by jmhbnz** [comment]
Backports completed - closing 🎉
