### ISSUE TITLE
[Robustness - LazyFS] Failpoint beforeWritebackBuf case has low QPS 

### ISSUE THREAD

**Issue by fuweid** [etcd-io/etcd#16370]
### Which github workflows are flaking?

Robustness

### Which tests are flaking?

TestRobustnessEtcdLowTrafficClusterOfSize1LazyFS-test-0 

failpoint: `beforeWritebackBuf`

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/5752901024/job/15594917097?pr=16355

### Reason for failure (if possible)

```
traffic.go:106: Requiring minimal 100.000000 qps for test results to be reliable, got 99.731074 qps
```

It might related to disk IO.

**Comment by serathius** [comment]
Let's reduce the requires QPS to 80 for LowTraffic
