### ISSUE TITLE
etcd member read raft snapshot message 5 second timeout

### ISSUE THREAD

**Issue by huangcuiyang** [etcd-io/etcd#16377]
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [x] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?
desc:
a member cannot start up, because leader send snapshot always timeout, and i see the member failed decode raft message with io read timeout，and the leader's log view than the snapshot size is 87MB, took 5 seconds。（tips: the member's local data 【/var/lib/etcd/member】was delete by manual）

### What did you expect to happen?
the member can readful 87MB raft message in 5 seconds

### How can we reproduce it (as minimally and precisely as possible)?

1, a normal etcd cluster with >400MB local data
2, stop all members
3, delete one member's local data (/var/lib/etcd/member)
4, start all etcd members

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.3
Git SHA: 0452feec7
Go Vesion: go1.16.15
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.3
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
{"level":"info","ts":"2023-08-05T08:27:23.356Z","caller":"rafthttp/snapshot_sender.go:84","msg":"sending database snapshot","snapshot-index":60713860,"remote-peer-id":"ed6f0152646f612c","bytes":86654537,"size":"87 MB"}
{"level":"warn","ts":"2023-08-05T08:27:23.357Z","caller":"etcdserver/snapshot_merge.go:72","msg":"failed to send database snapshot to writer","size":"74 kB","error":"io: read/write on closed pipe"}
{"level":"warn","ts":"2023-08-05T08:27:23.357Z","caller":"rafthttp/snapshot_sender.go:102","msg":"failed to send database snapshot","snapshot-index":60713860,"remote-peer-id":"8b53e9be0631c484","bytes":86654537,"size":"87 MB","error":"unexpected http status Bad Request while posting to \"https://10.21.255.106:2380/raft/snapshot\""}
{"level":"warn","ts":"2023-08-05T08:27:23.357Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"8b53e9be0631c484","error":"failed to post 8b53e9be0631c484 on sendMsgSnap (unexpected http status Bad Request while posting to \"https://10.21.255.106:2380/raft/snapshot\")"}
{"level":"info","ts":"2023-08-05T08:27:23.357Z","caller":"etcdserver/server.go:2106","msg":"sent merged snapshot","from":"cda8d26d182fcbc0","to":"8b53e9be0631c484","bytes":86654537,"size":"87 MB","took":"5.002006031s"}
{"level":"warn","ts":"2023-08-05T08:27:23.403Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"ed6f0152646f612c","error":"failed to dial ed6f0152646f612c on stream MsgApp v2 (peer ed6f0152646f612c failed to find local node cda8d26d182fcbc0)"}
{"level":"warn","ts":"2023-08-05T08:27:23.548Z","caller":"etcdserver/v3_server.go:840","msg":"waiting for ReadIndex response took too long, retrying","sent-request-id":14681886263511996209,"retry-timeout":"500ms"}
{"level":"warn","ts":"2023-08-05T08:27:24.049Z","caller":"etcdserver/v3_server.go:840","msg":"waiting for ReadIndex response took too long, retrying","sent-request-id":14681886263511996209,"retry-timeout":"500ms"}
{"level":"info","ts":"2023-08-05T08:27:24.352Z","caller":"rafthttp/peer_status.go:53","msg":"peer became active","peer-id":"8b53e9be0631c484"}
{"level":"info","ts":"2023-08-05T08:27:24.352Z","caller":"rafthttp/peer_status.go:53","msg":"peer became active","peer-id":"ed6f0152646f612c"}
{"level":"info","ts":"2023-08-05T08:27:24.355Z","caller":"etcdserver/server.go:2088","msg":"sending merged snapshot","from":"cda8d26d182fcbc0","to":"8b53e9be0631c484","bytes":86654537,"size":"87 MB"}
```

**Comment by ahrtr** [comment]
> 4, start all etcd members


Set `--initial-cluster-state existing` when you starting the member (which you removed the data) again

**Comment by huangcuiyang** [comment]
> > 4, start all etcd members
> 
> Set `--initial-cluster-state existing` when you starting the member (which you removed the data) again

yes，this configuration has already been added

**Comment by kwenzh** [comment]
Is there any issue with the network communication between etcd nodes?
