### ISSUE TITLE
Consider adopting go 1.20 as go 1.19 is now out of support

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16393]
### What would you like to be added?

Golang 1.21 has now been released today: 
 - https://groups.google.com/g/golang-announce/c/Mk0Jar6hfhI 
 - https://go.dev/doc/go1.21

This means 1.19 is now out of support so we should consider adopting 1.20. This would also bring etcd in line with kubernetes/kubernetes go version.

Consider updating:
- [x] `etcd/main` https://github.com/etcd-io/etcd/pull/16394
- [x] `etcd/release-3.5` https://github.com/etcd-io/etcd/pull/16401
- [x] `etcd/release-3.4` https://github.com/etcd-io/etcd/pull/16406
- [x] `bbolt/master` https://github.com/etcd-io/bbolt/pull/555
- [x] `raft/main` https://github.com/etcd-io/raft/pull/97

### Why is this needed?

Ensure etcd is built using supported versions of golang. Ensure the project continues to apply timely security patches.

**Comment by ahrtr** [comment]
thx @jmhbnz 

- There should be no any [golang](https://go.dev/doc/go1.20) breaking change to etcd. I suggest to bump go version to 1.20 for all versions, including main/3.5/3.4;
- Can we do a simple [benchmark](https://github.com/etcd-io/etcd/tree/main/tools/benchmark) comparison on the main branch?

**Comment by jmhbnz** [comment]
>     * There should be no any [golang](https://go.dev/doc/go1.20) breaking change to etcd. I suggest to bump go version to 1.20 for all versions, including main/3.5/3.4;
> 
>     * Can we do a simple [benchmark](https://github.com/etcd-io/etcd/tree/main/tools/benchmark) comparison on the main branch?

Raised pr for `main`.  Workflows passing and benchmark comparison posted in pr is looking pretty similar.

**Comment by jmhbnz** [comment]
Note there are two deprecations in 1.20 we should stay on top of: 
- [ ] `math/rand.Read` issue to be created
- [ ] `math/rand.Seed` https://github.com/etcd-io/etcd/issues/16428

**Comment by ahrtr** [comment]
> So it would mean that go1.21 for main branch and go1.20 for release-3.4 and release-3.5.

Due to the faster release pace of golang (e.g.  around 6 months for each a minor release), we have to upgrade to golang 1.21 for all etcd supported versions on around Feb 2024.

For the etcd main branch, it shouldn't be a big problem to upgrade to 1.21 earlier. But I tend to be consistent with K8s. Currently K8s is on golang 1.20 on master (1.28 was also released on golang 1.20). WDYT?

**Comment by serathius** [comment]
Kubernetes 1.28 was cut over a month ago, they only released it recently. They are already preparing for 1.21 https://github.com/kubernetes/kubernetes/pull/119027

**Comment by jmhbnz** [comment]
My vote would be to aim that our `main` follows `k/k` `master` for go version where possible.  Based on progress that will likely mean an update to 1.21 in the next couple of months. We have a couple minor 1.20 deprecations to tidy up under https://github.com/etcd-io/etcd/issues/16428 but those won't take long.

Agree we do minor version upgrades when necessary on supported release branches to keep them on a supported golang version but otherwise we just focus on staying on latest patch release.

**Comment by jmhbnz** [comment]
Closing, 1.20 upgrade complete 🎉
