### ISSUE TITLE
Ambigiouse error message: cannot access data directory: mkdir www.etcd: permission denied

### ISSUE THREAD

**Issue by EugenKon** [etcd-io/etcd#16400]
### What would you like to be added?

Improve the message above, eg. show full path `mkdir /full/absolute/path/www.etcd`

### Why is this needed?

From the original message above I can not understand where it tries to create a folder.

**Comment by EugenKon** [comment]
Probably you need to mark `--data-dir` option as mandatory. Also I do not realize why it tries to create `www.etcd` if default datadir is `/var/lib/etcd`.

**Comment by fuweid** [comment]
please provide the information about your etcd setting or the full log information.
It's hard to understand why it is www.etcd. thanks

**Comment by EugenKon** [comment]
I just configured the `name = www` that is all. It seems it was because of default value:

![image](https://github.com/etcd-io/etcd/assets/139780495/268db7b3-e3c1-4b8b-9dd8-ea3d8efa20f1)
https://etcd.io/docs/v3.4/op-guide/configuration/

So etcd tries to create /somewhere + `www.etcd`.

**Comment by jmhbnz** [comment]
After a quick review I believe this feature request can be closed.

The code in question triggering the error message is only found in one file: https://github.com/etcd-io/etcd/blob/185ddb2e78a6f856c6151466d57ea6306ff17c57/server/etcdserver/bootstrap.go#L66

We can trigger that error as follows:

```bash
# Create a directory owned by root
sudo mkdir test

# Start etcd specifying data dir etcd cannot access
./etcd --data-dir test
```

Let's checkout `release-3-4`, `release-3.5` and `main` one by one and run the test above to see what logs output:

|Branch       |Log message                                                                                                                                               |
|----------------|---------------------------------------------------------------------------------------------------------------------------------------|
| release-3.4| `2023-10-07 22:38:47.598581 C  etcdmain: cannot access data directory: open test/.touch: permission denied` |
| release-3.5| `{"level":"fatal","ts":"2023-10-07T22:37:19.687643+1300","caller":"etcdmain/etcd.go:182","msg":"discovery failed","error":"cannot access data directory: open /home/james/Documents/etcd/bin/test/.touch: permission denied","stacktrace":"..."}` |
| main           |`{"level":"fatal","ts":"2023-10-07T22:40:11.408331+1300","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"cannot access data directory: open /home/james/Documents/etcd/bin/test/.touch: permission denied","stacktrace":"..."}` |


Reviewing the results above we can see for both `release-3.5` and `main` the full path is now output when this error is hit.

@EugenKon I will close this as the requested feature has been implemented in later versions of etcd, please update to a newer 3.5.x release when you can.
