### ISSUE TITLE
all: stop using math/rand.Seed

### ISSUE THREAD

**Issue by gocurr** [etcd-io/etcd#16428]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

It's updated to Go 1.20 minor release, however math/rand.Seed is marked "Deprecated":

> // Prior to Go 1.20, the generator was seeded like Seed(1) at program startup.
// To force the old behavior, call Seed(1) at program startup.
// Alternately, set GODEBUG=randautoseed=0 in the environment
// before making any calls to functions in this package.
//
// Deprecated: As of Go 1.20 there is no reason to call Seed with
// a random value. Programs that call Seed with a known value to get
// a specific sequence of results should use New(NewSource(seed)) to
// obtain a local random generator.

### What did you expect to happen?

Stop using math/rand.Seed.

### How can we reproduce it (as minimally and precisely as possible)?

Use the new API as suggested.

### Etcd version (please run commands below)

Versions updated to Go 1.20.

**Comment by jmhbnz** [comment]
Thanks for raising this @gocurr.  More context here for anyone interested: https://github.com/golang/go/issues/54880 

Looks like eight instances to consider updating:

```bash
 ➜ find . -name "*.go" -type f -print | xargs grep .Seed
./pkg/stringutil/rand.go:                                   rand.Seed(time.Now().UnixNano())
./pkg/adt/interval_tree_test.go:                            rand.Seed(time.Now().UnixNano())
./pkg/proxy/server.go:                                      mrand.Seed(int64(now.Nanosecond()))
./pkg/proxy/server_test.go:                                 rand.Seed(now)
./tests/integration/clientv3/snapshot/v3_snapshot_test.go:  rand.Seed(int64(time.Now().Nanosecond()))
./server/lease/lessor_bench_test.go:                        rand.Seed(time.Now().UTC().UnixNano())
./server/etcdserver/server.go:                              rand.Seed(time.Now().UnixNano())                                       
```

**Comment by gocurr** [comment]
I think perhaps you should check other deprecated APIs.

**Comment by jmhbnz** [comment]
> I think perhaps you should check other deprecated APIs.

The only other formal deprecation I can see that impacts us for 1.20 is deprecation of `math/rand.Read` in favor of `crypto/rand.Read`.  I'll raise a separate issue for that. Please let us know if you spot anything else that needs a cleanup.

**Comment by gocurr** [comment]
Anyone want to fix it?

**Comment by jmhbnz** [comment]
We welcome contributions so please feel free if you have capacity!  Happy to assign it to you just let us know.

**Comment by gocurr** [comment]
Seems to me, there are two approaches.

1. Since "If Seed is not called, the generator is seeded randomly at program startup." just remove rand.Seed calls.
2. "Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator." it depends on the situations.

**Comment by Aditya-Sood** [comment]
hi @gocurr @jmhbnz 
is the fix in-progress or open for contribution?

**Comment by jmhbnz** [comment]
I'm not working on this currently. @gocurr did you make a start on this?

> - Since "If Seed is not called, the generator is seeded randomly at program startup." just remove rand.Seed calls.
> - "Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator." it depends on the situations.

Ideally we should be just removing the `.Seed` calls.

**Comment by gocurr** [comment]
> hi @gocurr @jmhbnz
> is the fix in-progress or open for contribution?

Yes, a PR to this issue was just created.

**Comment by gocurr** [comment]
> I'm not working on this currently. @gocurr did you make a start on this?
> 
> > * Since "If Seed is not called, the generator is seeded randomly at program startup." just remove rand.Seed calls.
> > * "Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator." it depends on the situations.
> 
> Ideally we should be just removing the `.Seed` calls.

Please take a look.
