### ISSUE TITLE
Find issues links in CONTRIBUTING.md should search for all repositories under etcd-io organization

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [etcd-io/etcd#16424]
### What would you like to be added?

Adjust the links in [section "Find something to work on" in CONTRIBUTING.md](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#Find-something-to-work-on) to search for all repositories under [etcd-io](https://github.com/etcd-io)

### Why is this needed?

The current links only search for issues in the main [etcd repo](https://github.com/etcd-io/etcd).
However, I think issues in sub-repos of etcd-io should also be considered as part of the main [etcd repo](https://github.com/etcd-io/etcd) and need help too.
Please correct me if I am wrong?

**Comment by jmhbnz** [comment]
Thanks @xuan-nguyen-swe - Your suggestion makes sense, please raise a pull request if you have capacity.

**Comment by xuan-nguyen-swe** [comment]
@jmhbnz how about this sentence?
> All the work in etcd project is tracked in [github issue tracker](https://github.com/etcd-io/etcd/issues).

Should we keep it as https://github.com/etcd-io/etcd/issues or change to something like https://github.com/search?type=issues&q=org%3Aetcd-io+state%3Aopen ?

**Comment by jmhbnz** [comment]
Hmm I think this one can stay as it is, there are still de-lineations between etcd, bbolt and raft and I find the default project issue page easier to use compared to the global search page.

**Comment by ahrtr** [comment]
Completed in https://github.com/etcd-io/etcd/pull/16430
