### ISSUE TITLE
Add test cases to cover all RESTful APIs

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#16507]
### What would you like to be added?

Please read https://github.com/etcd-io/etcd/pull/16454#issuecomment-1692280452 .

- [x] Add test cases to cover all [KV REST API](https://github.com/etcd-io/etcd/blob/506e9fdde6b65b0396f35e22186b07f1783fb853/api/etcdserverpb/rpc.proto#L35).  
  - Only `/v3/kv/deleterange` and `/v3/kv/compaction` are not covered yet.
  - https://github.com/etcd-io/etcd/pull/16509
  -  https://github.com/etcd-io/etcd/pull/16511
- [x] Add test cases to cover [cluster REST API](https://github.com/etcd-io/etcd/blob/506e9fdde6b65b0396f35e22186b07f1783fb853/api/etcdserverpb/rpc.proto#L157).
  - Let's add a new file v3_curl_cluster_test.go.
  - https://github.com/etcd-io/etcd/pull/16545
- [x] Add test cases to cover [maintenance REST API](https://github.com/etcd-io/etcd/blob/506e9fdde6b65b0396f35e22186b07f1783fb853/api/etcdserverpb/rpc.proto#L199). 
  - https://github.com/etcd-io/etcd/pull/16489
- [x] Add test cases to cover [auth REST API](https://github.com/etcd-io/etcd/blob/506e9fdde6b65b0396f35e22186b07f1783fb853/api/etcdserverpb/rpc.proto#L273)
  - Some APIs have already been covered in [v3_curl_test.go](https://github.com/etcd-io/etcd/blob/main/tests/e2e/v3_curl_test.go). Let's move all auth related REST API into a separate file e.g. v3_curl_auth_test.go, and also add new cases to cover the APIs which aren't covered before.
  - https://github.com/etcd-io/etcd/pull/16518
  - https://github.com/etcd-io/etcd/pull/16527
- [x] Add test cases to cover all [election REST API](https://github.com/etcd-io/etcd/blob/60051be9908649b1a0f2d000dc75b3bd0822d53c/server/etcdserver/api/v3election/v3electionpb/v3election.proto#L15)
  - https://github.com/etcd-io/etcd/pull/16564
  - https://github.com/etcd-io/etcd/pull/16570
- [x] Add test cases to cover all [lock REST API](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto)
  - https://github.com/etcd-io/etcd/pull/16553

### Why is this needed?

See above

**Comment by serathius** [comment]
I would suggest trying to reuse small subset of existing grpc test. We should avoid duplicating code for testing as tests are already hard to maintain.

**Comment by gusandrioli** [comment]
I'll give this a try for election/lock REST APIs.

**Comment by ahrtr** [comment]
All done!
