### ISSUE TITLE
Ensure go version is only defined in one file for release-3.5

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16560]
### What would you like to be added?

Currently our `release-3.5` branch defines the project golang patch version in two places:

```bash
 ~  Documents  etcd   release-3.5  grep -RiI "1\.20\.8"
.go-version:1.20.8
Makefile:GO_VERSION ?= 1.20.8

```

We should be only relying on the version defined in `.go-version`, and removing the hardcoded version in the `Makefile` using something like `GO_VERSION ?= $(cat .go-version)`.

### Why is this needed?

Ensure we can update the golang patch version for `release-3.5` by only updating a single file.
Avoid potential confusion.

**Comment by MeenuyD** [comment]
Hello @jmhbnz I can not find the go version inside the makefile can you tell me where it is?

**Comment by jmhbnz** [comment]
Please ensure you are working with the `release-3.5` branch as mentioned above:

https://github.com/etcd-io/etcd/blob/bdae1d390fd5ec9775d3e28e2969d1720d2c0897/Makefile#L58

**Comment by MeenuyD** [comment]
Hello @jmhbnz I have created new pull request can you please review it .

**Comment by jmhbnz** [comment]
Completed in #16562, thanks @MeenuyD 👍🏻
