### ISSUE TITLE
etcd panic with: etcdserver/membership: failed to find local ID 8cb42a2d43d5e276 in cluster xxx

### ISSUE THREAD

**Issue by forrestchu** [etcd-io/etcd#16632]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

In my test environment, I have a 7-nodes cluster and I have a test case to test the cluster failure recovery with flowing steps:
1) Continuously write data to the cluster using a background script.
2) randomly kill 3 nodes
3) wait some time and start 3 nodes again
4) check the cluster status with 'etcdctl endpoint status', and make sure all nodes in cluster is reachable and consistency.
5) repeat 2~4

After running a long time, the case may fail at step 4)
a node may fail to startup with error:
2023-09-17 15:25:15.826234 C | etcdserver/membership: failed to find local ID 8cb42a2d43d5e276 in cluster 1d8747888ddf087b

### What did you expect to happen?

all nodes in the cluster is reachable and consistency for the failure recovery test.

### How can we reproduce it (as minimally and precisely as possible)?

1) Continuously write data to the cluster using a background script.
2) randomly kill 3 nodes
3) wait some time and start 3 nodes again
4) check the cluster status with 'etcdctl endpoint status', and make sure all nodes in cluster is reachable and consistency.
5) repeat 2~4

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.18
Git SHA: 72d3e382e
Go Version: go1.12.17
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.18
API version: 3.4

</details>


### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>


### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

user@mytest:~$ etcdctl --endpoints=33.254.1.2:2379,33.254.1.3:2379,33.254.1.4:2379,33.254.1.5:2379,33.254.1.6:2379,33.254.1.7:2379,33.254.1.8:2379 endpoint status -w table
{"level":"warn","ts":"2023-09-22T12:05:51.795Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///33.254.1.7:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 33.254.1.7:2379: connect: connection refused\""}
Failed to get the status of endpoint 33.254.1.7:2379 (context deadline exceeded)
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT     |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 33.254.1.2:2379 | 312b1ede66955635 |  3.4.18 |   25 MB |     false |      false |        12 |     105251 |             105251 |        |
| 33.254.1.3:2379 | 633994426835aca0 |  3.4.18 |   25 MB |     false |      false |        12 |     105251 |             105251 |        |
| 33.254.1.4:2379 | 3d6823c994066e5a |  3.4.18 |   25 MB |     false |      false |        12 |     105251 |             105251 |        |
| 33.254.1.5:2379 | 413fc40cf4870ace |  3.4.18 |   25 MB |     false |      false |        12 |     105251 |             105251 |        |
| 33.254.1.6:2379 | 35ea78d3d927f0d8 |  3.4.18 |   25 MB |     false |      false |        12 |     105251 |             105251 |        |
| 33.254.1.8:2379 | e722780b1c9b209b |  3.4.18 |   25 MB |      true |      false |        12 |     105251 |             105251 |        |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

</details>


### Relevant log output

```Shell
2023-09-17 15:25:15.745418 E | rafthttp: failed to find member 413fc40cf4870ace in cluster 1d8747888ddf087b
2023-09-17 15:25:15.745863 E | rafthttp: failed to find member 3d6823c994066e5a in cluster 1d8747888ddf087b
2023-09-17 15:25:15.745990 E | rafthttp: failed to find member 3d6823c994066e5a in cluster 1d8747888ddf087b
2023-09-17 15:25:15.746033 E | rafthttp: failed to find member 413fc40cf4870ace in cluster 1d8747888ddf087b
2023-09-17 15:25:15.803637 E | rafthttp: streaming request ignored (ID mismatch got d621434dc5972a99 want 8cb42a2d43d5e276)
2023-09-17 15:25:15.803672 E | rafthttp: streaming request ignored (ID mismatch got d621434dc5972a99 want 8cb42a2d43d5e276)
2023-09-17 15:25:15.822390 E | rafthttp: failed to find member 633994426835aca0 in cluster 1d8747888ddf087b
2023-09-17 15:25:15.822457 E | rafthttp: failed to find member 633994426835aca0 in cluster 1d8747888ddf087b
2023-09-17 15:25:15.826177 I | etcdserver: finished restoring mvcc store
2023-09-17 15:25:15.826195 I | etcdserver: recovering alarms...
2023-09-17 15:25:15.826206 I | etcdserver: closing old backend...
2023-09-17 15:25:15.826234 C | etcdserver/membership: failed to find local ID 8cb42a2d43d5e276 in cluster 1d8747888ddf087b
```

**Comment by ahrtr** [comment]
I suspect it might be related to https://github.com/etcd-io/etcd/pull/16084#issuecomment-1696362494. Could you please reproduce this issue in 3.5.9?

**Comment by serathius** [comment]
Etcd version this was reproduced is very old, so it's hard to know if this is related to the current discussion or it's some old bug that fixed.

**Comment by forrestchu** [comment]
> I suspect it might be related to [#16084 (comment)](https://github.com/etcd-io/etcd/pull/16084#issuecomment-1696362494). Could you please reproduce this issue in 3.5.9?

ahrtr, thanks for the reply. I will feedback when i reproduce it in 3.5.9.

**Comment by jmhbnz** [comment]
Closing as this hasn't be reproduced on a modern etcd release.  Happy to re-open if that is incorrect.
