### ISSUE TITLE
--experimental-wait-cluster-ready-timeout causing stale response to linearizable read

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#16666]
While working and discussing https://github.com/etcd-io/etcd/pull/16658 with @ahrtr I spotted one issue. Etcd going back in time during bootstrap. The good news is that the current reproduction limit the issue to v3.6 release. Impact on older releases is still under investigation.

As described in https://github.com/etcd-io/etcd/pull/16658#discussion_r1341346778 graceful shutdown via SIGTERM allows etcd flushing it's database to disk, however SIGKILL will mean that data on disk might be older than in memory state of etcd. While bootstrapping etcd will catch up on changes it has forgotten by replaying WAL. Etcd might go back in time if it started serving data before it caught up to state before the kill. But this doesn't happen right?

Unfortunately it's possible. In https://github.com/etcd-io/etcd/pull/13525 we have added a flag that skips the wait. Fortunately the change is only present on v3.6. `--experimental-wait-cluster-ready-timeout` goal was to skip the wait for quorum during member bootstrap allowing member to start serving serializable requests. This unfortunately also skips the wait for entries from before crash to be applied. The skip will happen by default, fortunately 5s wait is enough to prevent this happening in most cases.

After looking deeper I found more issues.
* [confirmed] --experimental-wait-cluster-ready-timeout causing member serializable responses to go back in time. Repro https://github.com/etcd-io/etcd/commit/51fb2d78ddd35c5aa08bd51466ecfebb73601293 It's done by reusing `TestCtlV3ConsistentMemberList` test introduced in https://github.com/etcd-io/etcd/pull/16658 and uses SIGKILL.
* [confirmed] --experimental-wait-cluster-ready-timeout breaking linearizability in single node cluster. In single node cluster, leader will not check readIndex the same way. It will trust it's local committed index, which is not guaranteed to be persisted before responding to user. Repro https://github.com/etcd-io/etcd/pull/16672
* Even without --experimental-wait-cluster-ready-timeout, clusterReady mechanism seems strange. It just waits for a joining member to be able to make a proposal (set it's own member attributes), however this has noting to do with replaying entries. I expect that with proper timings (injecting sleep into code) the etcd will start serving before all entries from before crash have been applied. I expect it can happen on both single and multi node cluster.

**Comment by serathius** [comment]
cc @gyuho @jpbetz @philips @hexfusion @bdarnell

Would be great if to get your opinion.

**Comment by ahrtr** [comment]
I will try to create a dedicated test case to reproduce this issue on key space next week firstly.

**Comment by serathius** [comment]
Hmm, doesn't reproduce for me. I was trying to use robustness tests on 1 node cluster with serializable request. Found a bug in the test though https://github.com/etcd-io/etcd/pull/16658#discussion_r1341959776

**Comment by serathius** [comment]
Ok, found it https://github.com/etcd-io/etcd/pull/16672

**Comment by serathius** [comment]
Summarized the current findings in the top comment. Thanks to @ahrtr who already prepared two different fix proposals (https://github.com/etcd-io/raft/pull/105, https://github.com/etcd-io/etcd/pull/16675). I think the proper solution will require making some trade-off, so I think we should revisit the design of etcd ready code.

**Comment by serathius** [comment]
Did some testing for the third case however without success. Possibly I'm missing some dependency between cluster readiness and applying raft. If there was this kind of issue in etcd, we would have caught it earlier. I will followup on this in https://github.com/etcd-io/etcd/issues/16673 to ensure we properly test and find all races in etcd bootstrap.

Still the issue of `--experimental-wait-cluster-ready-timeout` stays. @ahrtr has proposed some fixes to this, however they come with some downsides. My suggestion would be to remove `--experimental-wait-cluster-ready-timeout`  first and then reconsider it after we have a proper design for etcd bootstrap that is linearizable.

**Comment by ahrtr** [comment]
Just added[ two test cases](https://github.com/etcd-io/etcd/pull/16678) which can reproduce the issue super easily.
 
Rollbacking https://github.com/etcd-io/etcd/pull/13525 is the most pragmatic approach. It can resolve this issue, but it will also rollback the fix for the following two issues:
- etcd can't serve serializable requests after restarts if the quorum isn't satisfied;
- K8s liveness probe might restart an etcd node while other nodes are not started yet or still in progress of starting. Accordingly it will make the situation even worse, and lead to vicious circle.

The first issue seems not a big deal. But the second one is a major issue, we should take care of in the [/livez and /readyz feature](https://github.com/etcd-io/etcd/pull/16651). Specifically, when a node is blocked on the [ReadyNotify](https://github.com/etcd-io/etcd/blob/v3.5.9/server/embed/serve.go#L101), the `/livez` should NOT return not live status to client.

**Comment by chaochn47** [comment]
Thanks @serathius @ahrtr taking care of this, I believe I have seen this issue in the release-3.4. The reproduce is simple. Restart etcd server right after member reconfiguration and query the member list via HTTP `/members`, [its handler](https://github.com/etcd-io/etcd/blob/release-3.4/etcdserver/api/etcdhttp/peer.go#L107) will bypass the linearizable check. The member list response would be stale during bootstrap (restart) where the members are restored from v2 store and WAL is still replaying... 

```
# checkout code in 
# https://github.com/chaochn47/etcd/tree/v3.4.20-eks.0-reproduce-member-name-mismatch
cd integration && go test -v -run TestReproduceMemberNameMismatch
```

Adding `--experimental-wait-cluster-ready-timeout` in 3.6 seems like surfacing this issue up while it could have been protected by publishing local member attribute (name and client URL) to cluster. Note, in etcd client it assumes if the `name` or `clientURL` (the member attributes) is empty, then the server has not yet started and added to the endpoints before serving traffic. https://github.com/etcd-io/etcd/blob/979102f895d060c496103fc354168c1efcc99c57/client/v3/client.go#L185-L200. I bet I have seen this in the other code bases like `etcdctl` with this assumption. 

So my stance is rolling https://github.com/etcd-io/etcd/pull/13525 back for correctness. 

/cc @siyuanfoundation @wenjiaswe we might be impacted by the serializable check method :/

**Comment by ahrtr** [comment]
> Restart etcd server right after member reconfiguration and query the member list via HTTP `/members`, [its handler](https://github.com/etcd-io/etcd/blob/release-3.4/etcdserver/api/etcdhttp/peer.go#L107) will bypass the linearizable check.

Actually the main also has this "issue", but this might not be a problem. Two reasons:
- The `/members` is only supposed to accessed during bootstrap by a new etcd member who has just been added to the cluster;
- The `/members` is protected by peer certificate; in other words, users shouldn't be able to access this endpoint at all.

**Comment by chaochn47** [comment]
> K8s liveness probe might restart an etcd node while other nodes are not started yet or still in progress of starting. Accordingly it will make the situation even worse, and lead to vicious circle.

> But the second one is a major issue, we should take care of in the https://github.com/etcd-io/etcd/pull/16651. Specifically, when a node is blocked on the [ReadyNotify](https://github.com/etcd-io/etcd/blob/v3.5.9/server/embed/serve.go#L101), the /livez should NOT return not live status to client.

Sounds like a startup probe is needed in this case since the risk of `livez` returns not live status only happens during bootstrap. Long latency of etcd bootstrap (bbolt initialization) was also observed in one of the test clusters. https://github.com/etcd-io/etcd/discussions/15397#discussioncomment-6006142

Don't want to derail the issue and will follow this up in https://docs.google.com/document/d/1PaUAp76j1X92h3jZF47m32oVlR8Y-p-arB5XOB7Nb6U/edit?usp=sharing

**Comment by ahrtr** [comment]
We don't have to re-implement `--experimental-wait-cluster-ready-timeout`. 
- Unfortunately, I do not see a cheap solution. Indefinitely waiting for the [ReadyNotify](https://github.com/etcd-io/etcd/blob/v3.5.9/server/embed/serve.go#L101) may affect the bootstrapping time; after etcd gets started, there is no performance impact at all.
- We should be good as long as we can resolve the second major issue as I mentioned in https://github.com/etcd-io/etcd/issues/16666#issuecomment-1743122188 in the `/livez` probe.


So "Indefinitely waiting for the ReadyNotify" + "enhance /livez to take care of the corner case" on bootstrap is the safest solution I can think of.

**Comment by serathius** [comment]
I agree with the conclusion. We can revisit if needed in the future.

Thanks for great collaboration.

Closing as the main issue was fixed and remaining work will be tracked in followups:
* https://github.com/etcd-io/etcd/issues/16687
* https://github.com/etcd-io/etcd/issues/16673

**Comment by chaochn47** [comment]
> Even without --experimental-wait-cluster-ready-timeout, clusterReady mechanism seems strange. It just waits for a joining member to be able to make a proposal (set it's own member attributes), however this has noting to do with replaying entries. I expect that with proper timings (injecting sleep into code) the etcd will start serving before all entries from before crash have been applied. I expect it can happen on both single and multi node cluster.

@serathius My understanding is local node proposals will be appended at the end of the replaying entries queue. 

Only when all the previous entries have been replayed, the new proposal to publish its name and clientURLs will succeeds.  https://github.com/etcd-io/etcd/blob/aa97484166d2b3fb6afeb4390344e68b02afb566/server/etcdserver/v3_server.go#L767. So there should not have a linearizability concern. 

However, I think this default readiness is not good enough. The upcoming `/readyz` and gRPC change should further guarantee that etcd is ready to receive traffic.
