### ISSUE TITLE
The flag --host-whitelist is not working 

### ISSUE THREAD

**Issue by coderchuan** [etcd-io/etcd#16667]
### What happened?

The following are the commands for the server side, which specifies the --host-whitelist=10.21.200.146, but I am able to connect to an IP outside of 10.21.200.146 ，such as 10.21.200.192 
`etcd --name=single --initial-advertise-peer-urls=http://10.21.200.146:1200 --advertise-client-urls=http://10.21.200.146:1300 --initial-cluster=single=http://10.21.200.146:1200 --initial-cluster-state=new --listen-peer-urls=http://0.0.0.0:1200 --listen-client-urls=http://0.0.0.0:1300 --data-dir=/var/etcd/data --quota-backend-bytes=4294967296 --initial-cluster-token=abcdef --log-outputs=stdout,/var/etcd/log/log.txt --host-whitelist=10.21.200.146`

### What did you expect to happen?

Can only be connected to the IP specified in the --host-whitelist

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.9
Git SHA: bdbbde998
Go Version: go1.19.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.9
API version: 3.5
```

</details>

**Comment by xixiwang12138** [comment]
I am trying to test this issue; 
Please tell us your way to connect etcd-server(etcdctl or httpclient?) when you found this problem.

**Comment by coderchuan** [comment]
> I am trying to test this issue; Please tell us your way to connect etcd-server(etcdctl or httpclient?) when you found this problem.

etcdctl version: 3.5.9

**Comment by xixiwang12138** [comment]
> 3.5.9
Let’s briefly explain the reason why this problem occurs:
1. This version of etcdtcl uses grpc client
2. But in etcd-server, the control ability of this parameter is only effective when the client uses http request (check the Host in the HTTP request header)
3. The same problem will occur with CORS control

**Comment by xixiwang12138** [comment]
> > I am trying to test this issue; Please tell us your way to connect etcd-server(etcdctl or httpclient?) when you found this problem.
> 
> etcdctl version: 3.5.9

Let’s briefly explain the reason why this problem occurs:
1. This version of etcdtcl uses grpc client
2. But in etcd-server, the control ability of this parameter is only effective when the client uses http request (check the Host in the HTTP request header)
3. The same problem will occur with CORS control

**Comment by coderchuan** [comment]
> > > I am trying to test this issue; Please tell us your way to connect etcd-server(etcdctl or httpclient?) when you found this problem.
> > 
> > 
> > etcdctl version: 3.5.9
> 
> Let’s briefly explain the reason why this problem occurs:
> 
> 1. This version of etcdtcl uses grpc client
> 2. But in etcd-server, the control ability of this parameter is effective only when the client uses http request (check the Host in the HTTP request header)
> 3. The same problem will occur with CORS control

thanks
