### ISSUE TITLE
[release-3.5] MacOS support for `scripts/genproto.sh`

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#16760]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

```bash
# first clone
git clone git@github.com:etcd-io/etcd.git

# enter directory
cd etcd

# switch to 3.5
git checkout release-3.5

# run genproto.sh from root, from a folder named etcd
./scripts/genproto.sh

#Error Trace
.
.
.
Running swagger & grpc_gateway proto generation...
grpc & swagger for: api/etcdserverpb/rpc.proto
% protoc -I. -I/Users/x/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.6/protoc-gen-grpc-gateway/../third_party/googleapis -I/Users/x/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/..:/Users/x/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/../protobuf -I/Users/x/junkyard/etcd/etcd/.. --grpc-gateway_out=logtostderr=true,paths=source_relative:. --swagger_out=logtostderr=true:./Documentation/dev-guide/apispec/swagger/. --plugin=/Users/x/go/bin/protoc-gen-swagger --plugin=/Users/x/go/bin/protoc-gen-grpc-gateway api/etcdserverpb/rpc.proto
% sed -i -E s#package etcdserverpb#package gw#g api/etcdserverpb/rpc.pb.gw.go
% sed -i -E s#import \(#import \("go.etcd.io/etcd/api/etcdserverpb"#g api/etcdserverpb/rpc.pb.gw.go
stderr: sed: 1: "s#import \(#import \("g ...": RE error: parentheses not balanced
```

### What did you expect to happen?

Generate all the protos for etcd-3.5

### How can we reproduce it (as minimally and precisely as possible)?

Stated above

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
3.5.9

$ etcdctl version
3.5.9
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
Running swagger & grpc_gateway proto generation...
grpc & swagger for: api/etcdserverpb/rpc.proto
% protoc -I. -I/Users/x/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.6/protoc-gen-grpc-gateway/../third_party/googleapis -I/Users/x/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/..:/Users/x/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/../protobuf -I/Users/x/junkyard/etcd/etcd/.. --grpc-gateway_out=logtostderr=true,paths=source_relative:. --swagger_out=logtostderr=true:./Documentation/dev-guide/apispec/swagger/. --plugin=/Users/x/go/bin/protoc-gen-swagger --plugin=/Users/x/go/bin/protoc-gen-grpc-gateway api/etcdserverpb/rpc.proto
% sed -i -E s#package etcdserverpb#package gw#g api/etcdserverpb/rpc.pb.gw.go
% sed -i -E s#import \(#import \("go.etcd.io/etcd/api/etcdserverpb"#g api/etcdserverpb/rpc.pb.gw.go
stderr: sed: 1: "s#import \(#import \("g ...": RE error: parentheses not balanced
```

**Comment by fuweid** [comment]
Did you run it in the linux ?

**Comment by chaochn47** [comment]
How about exit the script if OS is not linux with error message that "please run it on linux"?

**Comment by jmhbnz** [comment]
Thanks for sharing the workaround @vivekpatani.   Just to make sure you're aware, as outlined in our [`CONTRIBUTING.md`](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#setup-development-environment) the only supported operating system for etcd development is `linux` currently.

However if you can do some cross platform testing between `linux` and `darwin` for this particular script and raise a pull request that sounds like a great step forward to removing friction for others in future. I'll certainly be happy to review it :)

**Comment by mjlshen** [comment]
I'm interested in working on this :D

**Comment by jmhbnz** [comment]
Assigned, thanks @mjlshen! 🎉

**Comment by wenjiaswe** [comment]
Thank you very much!
