### ISSUE TITLE
Planning etcd contribfest for kubecon

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16804]
### What would you like to be added?

Kubecon North America is fast approaching.

The etcd project has a contribfest session scheduled : [https://kccncna2023.sched.com/event/1R2p2/contribfest-etcd-learn-from-the-maintainers-and-get-involved](https://kccncna2023.sched.com/event/1R2p2/contribfest-etcd-learn-from-the-maintainers-and-get-involved-marek-siarkowicz-wenjia-zhang-google-james-blair-josh-berkus-red-hat)

> Join the contributors to Etcd, the most popular cloud-native database that backs Kubernetes. We'll be working on improving key features and testing for Etcd, and in the process we’ll teach those new to the project how to contribute. Etcd is a very useful, fun, and essential project, and welcomes both new contributors and those who want to “level up”. Attendees should be familiar with programming in Go, using GitHub, and should bring a laptop on which they can do cloud-native development: either a Linux laptop or your own Github Devcontainer setup.

This issue is intended to be the parent planning issue used to track any preparation tasks and also track the list of github issues specifically set aside to be worked on during the contribfest.

---

### Preparation tasks:**

- [x] @etcd-io/maintainers-etcd to please create `contribfest` dedicated label. A lesson learned from our kubecon eu contribfest was not to use `good first issue` label as some issues that we wanted to set aside were picked up and completed before the contribfest even happened.
- [x]  Check and update [CONTRIBUTING.md](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md) if anything out of date.

---

#### etcd

|Issue|Type|Difficulty|Completed|
|-----|-------|-------------|---|
| [ tests: increase coverage of interceptor. logUnaryRequestStats #16823 ](https://github.com/etcd-io/etcd/issues/16823)|`type/feature` `area/testing` | Medium |❔|
| [Auth performance and maintenance improvements](https://github.com/etcd-io/etcd/issues/16036) | `type/feature` `area/testing` | Hard |❔|
| [ BOM should not depend on archived repo #15747 ](https://github.com/etcd-io/etcd/issues/15747) |`area/tooling` `type/bug` | Medium |✅|
| [Trial running a small robustness workflow for arm64 on every pull request #16863](https://github.com/etcd-io/etcd/issues/16863) | `type/feature` `area/robustness-testing` | Simple |✅|
| [ Add documentation for new snapshot restore flags #16160 ](https://github.com/etcd-io/etcd/issues/16160) | `type/feature` `area/documentation` `area/etcdutl` | Simple |✅|
| [Improve comments for clientv3test.TestUnresolvableOrderViolation #16865](https://github.com/etcd-io/etcd/issues/16865) | `area/testing` `type/cleanup` | Simple |⌛|
| [ Add etcd_server_range_duration_seconds metrics #16866 ](https://github.com/etcd-io/etcd/issues/16866) | `area/performance` `type/feature` | Medium |⌛|
| [MacOS support for scripts/genproto.sh #16760](https://github.com/etcd-io/etcd/issues/16760) |`area/tooling` `type/feature` | Simple |✅|
| [ Improve comments for clientv3test.TestWatchResumeInitRev #16867 ](https://github.com/etcd-io/etcd/issues/16867) | `type/cleanup` `area/testing` | Simple |⌛|
| [ Add integration test for retry loop in lessor.KeepAliveOnce #16869 ](https://github.com/etcd-io/etcd/issues/16869) | `area/testing` | Medium |❔|

#### website

|Issue|Type|Difficulty|Completed|
|-----|-------|-------------|---|
| [ Document --auth-token flag #706 ](https://github.com/etcd-io/website/issues/706) | `enhancement` | Simple |✅|
| [ Instruction errors in Run etcd clusters inside containers #271](https://github.com/etcd-io/website/issues/271) | `bug` | Simple |❔|
| [ Clarify second entry for arm on supported platforms table #739 ](https://github.com/etcd-io/website/issues/739) |`bug` | Simple |❔|
| [Test and upgrade hugo to the latest upstream release tag #717](https://github.com/etcd-io/website/issues/717) | `dependencies` `infrastructure` | Simple |❌|
| [ Update website community page to mention fortnightly triage meeting #745 ](https://github.com/etcd-io/website/issues/745) | `enhancement` `community` | Simple |⌛|

#### bbolt

|Issue|Type|Difficulty|Completed|
|-----|-------|-------------|---|
| [ Setup workflow running on arm64 #583 ](https://github.com/etcd-io/bbolt/issues/583) | `area/testing` `type/feature` | Simple |✅|
| [ Backport concurrent_test.go to release-1.3 branch #599 ](https://github.com/etcd-io/bbolt/issues/599) | `backport/release-1.3` `area/testing` | Simple |✅|

**Comment by lavacat** [comment]
filed https://github.com/etcd-io/etcd/issues/16823

**Comment by tjungblu** [comment]
there's also still #16036 - in case you guys want to sit together and design a better way to integrate auth or how to reactor the lease package.

**Comment by BobyMCbobs** [comment]
this may be a good issue to be apart of the contribfest
https://github.com/etcd-io/etcd/issues/16828

**Comment by chaochn47** [comment]
https://github.com/etcd-io/etcd/issues/15079 is inactive for two months. If no response from the assignee, it could be a good issue for `contribfest` and improves each developer experience when debugging test failures.

**Comment by serathius** [comment]
PTAL https://github.com/etcd-io/etcd/issues/15747

**Comment by jberkus** [comment]
One more from Website:

[Add "How to conduct a leader election"](https://github.com/etcd-io/website/issues/729)  | Enhancement | Moderate |

**Comment by to-json** [comment]
interested in slowly prodding at "tests: increase coverage of interceptor. logUnaryRequestStats #16823"

**Comment by jmhbnz** [comment]
Closing as the contribfest has now concluded.


Outcomes:
- After an initial review we have 7 issues completed, with another four open pr's in progress.
- There are five issues still available for contributors to work on.
- Only one issue was blocked and unable to be progressed.

A huge welcome and congratulations to @tessapham, @etsrpl, @spawulski, @shaoqin2, @RaviHari, @mjlshen, @greenmoon55, @edragone, @ivanvc and @Richabanker who all raised their first contribution to the project! 🎉 ❤️ 

Reviewers and maintainers over the coming days now the chaos of kubecon is over, when you have a moment please review pr's in the table above marked with ⌛.
