### ISSUE TITLE
Test PrevKey in robustness test

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#16838]
### What would you like to be added?

Kubernetes establishes watches with PrevKey enabled.

TODO:
* Add WithPrevKey() to Kubernetes traffic https://github.com/etcd-io/etcd/blob/main/tests/robustness/traffic/kubernetes.go
* Add PrevKey validation to watch https://github.com/etcd-io/etcd/blob/main/tests/robustness/validate/watch.go

### Why is this needed?

To improve correctness of testing Kubernetes-etcd contract

**Comment by MadhavJivrajani** [comment]
Hey @sharathsivakumar 👋🏼 

Wanted to check in and see if you're still working on this? I'd love to work on it or maybe collaborate if you're up for it. I have a rough PR that I can put up in a couple of days in case you haven't already started 😄

**Comment by sharathsivakumar** [comment]
Hi @MadhavJivrajani I have started working on this and I will be turning in my PR sometime next week.
