### ISSUE TITLE
Trial running a small robustness workflow for `arm64` on every pull request

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16863]
### What would you like to be added?

Recently in https://github.com/etcd-io/etcd/pull/16801 we introduced on demand github actions runners for the `arm64` platform. 

Having on demand runner infrastructure in place means we should now have enough capacity to begin running `arm64` tests for every pull request.

We could test adding a new `main-arm64` job to this workflow: https://github.com/etcd-io/etcd/blob/3f6a5c0bb13b7297388b3f347d195269df03c057/.github/workflows/robustness.yaml#L1-L13

After merging we would need to confirm the job is performing well enough to continue being enabled on a per pull request basis by comparing the run time to that of the normal robustness pull request job.

### Why is this needed?

Gain greater confidence and samples of robustness tests running against `arm64` cpu architecture.

Hopefully detect issues before pull requests are merged to `main`.

**Comment by etsrpl** [comment]
contrib fest assign request
/assign

**Comment by jmhbnz** [comment]
Assigned, thanks @etsrpl! 🎉

**Comment by jmhbnz** [comment]
Closing, completed in #16884.
