### ISSUE TITLE
Replace the deprecated `x509.ParseCRL` with `x509.ParseRevocationList`

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#16861]
### What would you like to be added?

Refer to https://github.com/etcd-io/etcd/pull/16860.

We need to add a unit test at least. Please anyone feel free to continue to work on top of my PR.

### Why is this needed?

Clean up deprecated usage of `x509.ParseCRL`

**Comment by MeenuyD** [comment]
Hello @ahrtr I would like to work on this issue can you please assign it to me I have a question only need to replace parsecrl on doing something else.

**Comment by ahrtr** [comment]
Thanks @MeenuyD .  Please add an unit test as well.

**Comment by MeenuyD** [comment]
Ok

**Comment by ivanvc** [comment]
Hi @MeenuyD, I wonder if you're working on this. If you're not, I can help with this task. If so, @ahrtr, can I be assigned to it?
