### ISSUE TITLE
Add etcd_server_range_duration_seconds metrics

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#16866]
### What would you like to be added?

We already have [etcd_server_apply_duration_seconds](https://github.com/etcd-io/etcd/blob/d38f7dceb22c2aa66f749d7aa4d6a10d10bc8116/server/etcdserver/txn/metrics.go#L31) metrics.

But [Range](https://github.com/etcd-io/etcd/blob/d38f7dceb22c2aa66f749d7aa4d6a10d10bc8116/server/etcdserver/v3_server.go#L134) doesn't go through Applier. The only metrics we have about Range timing is `grpc_server_handled_total{grpc_method="Range"}` provided by grpc_middleware. Problem is that this grpc metric also includes timing of `linearizableReadNotify`.

Please add etcd_server_range_duration_seconds in [txn.Range](https://github.com/etcd-io/etcd/blob/d38f7dceb22c2aa66f749d7aa4d6a10d10bc8116/server/etcdserver/txn/txn.go#L135)

### Why is this needed?

better observability

**Comment by RaviHari** [comment]
I would like to work on this

**Comment by thedtripp** [comment]
Hello @jmhbnz. 
I'd like to take a crack at this one. I'm a new contributor looking for mentorship.

**Comment by jmhbnz** [comment]
> Hello @jmhbnz. I'd like to take a crack at this one. I'm a new contributor looking for mentorship.

Thanks for volunteering @thedtripp! Assigned to you.  Please start by recreating the earlier proposed changes from #16902. Then we need a second commit to add a basic test verifying the new metric works. Let us know how you go and if you have any questions 🙏🏻 

/assign @thedtripp

**Comment by thedtripp** [comment]
@jmhbnz 
I made a PR: https://github.com/etcd-io/etcd/pull/17983

**Comment by thedtripp** [comment]
@jmhbnz @ivanvc @ahrtr Thank you for guiding me through that first PR. Any suggestions on where I should focus for my next contribution?

**Comment by jmhbnz** [comment]
> @jmhbnz @ivanvc @ahrtr Thank you for guiding me through that first PR. Any suggestions on where I should focus for my next contribution?

Most welcome! For a much quicker next contribution we need to update our website community page https://github.com/etcd-io/website/issues/850.  If you're interested please feel free to leave a comment and I will assign it to you. Alternatively please take a look at our `help wanted` issues.

**Comment by thedtripp** [comment]
> > @jmhbnz @ivanvc @ahrtr Thank you for guiding me through that first PR. Any suggestions on where I should focus for my next contribution?
> 
> Most welcome! For a much quicker next contribution we need to update our website community page [etcd-io/website#850](https://github.com/etcd-io/website/issues/850). If you're interested please feel free to leave a comment and I will assign it to you. Alternatively please take a look at our `help wanted` issues.

Sure! I'm happy to work on this.

**Comment by thedtripp** [comment]
Hey Team,
Is this issue ready to be closed or does it need further action?

**Comment by ivanvc** [comment]
I'm closing this, as it was completed by https://github.com/etcd-io/etcd/pull/17983. Thanks, @thedtripp. Please re-open it @ahrtr / @jmhbnz if you think we need to backport this.
