### ISSUE TITLE
Improve comments for clientv3test.TestWatchResumeInitRev

### ISSUE THREAD

**Issue by lavacat** [etcd-io/etcd#16867]
### What would you like to be added?

Please review the test and provide summary at the beginning of the test.

### Why is this needed?

improving readability

**Comment by greenmoon55** [comment]
Would like to work on this!

**Comment by greenmoon55** [comment]
@jmhbnz In `TestWatchResumeInitRev`, does revision starts from 1 so we expect 4 here? 
https://github.com/etcd-io/etcd/blob/7e00a1e42b5c25b655fcd7deb1df74c4fba753ed/tests/integration/clientv3/watch_test.go#L371

**Comment by greenmoon55** [comment]
Oh I get it. 4 is the start revision.

**Comment by greenmoon55** [comment]
Shouldn't we expect 3 here if the start revision is 1?

**Comment by greenmoon55** [comment]
Nevermind, I got it. Created a pr.
