### ISSUE TITLE
Run `arm64` `e2e` tests for every pull request rather than on nightly schedule

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16893]
### What would you like to be added?

Recently in https://github.com/etcd-io/etcd/pull/16801 we introduced on demand github actions runners for the `arm64` platform.

Having on demand runner infrastructure in place means we should now have enough capacity to begin running `arm64` tests for every pull request.

We should update our `.github/workflows/e2e-arm64-nightly.yaml` workflow to switch from scheduled nightly runs to instead running `on: [push, pull_request]`: https://github.com/etcd-io/etcd/blob/main/.github/workflows/e2e-arm64-nightly.yaml#L7-L8

### Why is this needed?

Gain greater confidence and samples of e2e tests running against `arm64` cpu architecture.

Hopefully detect issues before pull requests are merged to `main`.

**Comment by mingli103** [comment]
Hi @jmhbnz please assign this issue to me.

**Comment by jmhbnz** [comment]
One further thought for this issue @mingli103.  Now that we are moving to `on: [push, pull_request]` for the e2e arm64 workflow we can actually move away from having two separate files.

Currently we have:
- `.github/workflows/e2e-arm64-template.yaml` - Shared template
- `.github/workflows/e2e-arm64-nightly.yaml` - Runs template against both `release-3.5` and `main` branches nightly.

Moving forward we can just rename `.github/workflows/e2e-arm64-template.yaml` to `.github/workflows/e2e-arm64.yaml` and delete the other file.  We can then just make the template file a standard workflow that will run on pull request.

**Comment by jmhbnz** [comment]
Closed as completed in #16950, thanks @mingli103 🙏🏻
