### ISSUE TITLE
Upgrade go to latest patch release

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16891]
### What would you like to be added?

A new go patch release has been published:

- go1.21.4 (released 2023-11-07) includes security fixes to the path/filepath package, as well as bug fixes to the linker, the runtime, the compiler, and the go/types, net/http, and runtime/cgo packages. See the [Go 1.21.4 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.4+label%3ACherryPickApproved) on our issue tracker for details.

We should update to this version by bumping the version in `.go-version` file in the `main` branch.

Once the changes have been merged in `main` we should also raise pull requests for `release-3.5` and `release-3.4` branches as well to update those branches to `1.20.11` so the fixes can make it into our next patch releases.

### Completion tracking

- [x] `main` - https://github.com/etcd-io/etcd/pull/16895
- [x] `release-3.5` https://github.com/etcd-io/etcd/pull/16915
- [x] `release-3.4` https://github.com/etcd-io/etcd/pull/16916
- [x] `etcd-io/bbolt` `master` https://github.com/etcd-io/bbolt/pull/607
- [x] `etcd-io/raft` `main` https://github.com/etcd-io/raft/pull/109

### Why is this needed?

Keep etcd projects up to date with the latest patch releases and incorporate the latest security updates.

**Comment by arjunmalhotra1** [comment]
Hey @jmhbnz!
I would be interested in taking this up as my contribfest issue.

**Comment by ahrtr** [comment]
It's breaking the workflow check and blocking other PRs, let's get this fixed & merged asap.

**Comment by vivekpatani** [comment]
@jmhbnz any plans to back port to 3.5.x as well? If needed help with that, can do.
CC: @ahrtr @serathius

**Comment by jmhbnz** [comment]
> @jmhbnz any plans to back port to 3.5.x as well? If needed help with that, can do. 

Certainly are - refer my comment in https://github.com/etcd-io/etcd/pull/16895#issuecomment-1803991685. I believe @arjunmalhotra1 will be raising the backports. However we also should be raising updates for both `etcd-io/bbolt` and `etcd-io/raft` so feel free to work on those! 🙏🏻

**Comment by ahrtr** [comment]
Please update the changelog for 3.4 and 3.5 as well, thanks.

**Comment by jmhbnz** [comment]
Hey @arjunmalhotra1 - Looks like all the update pr's have been merged.  As mentioned above can you please also raise a pull request against `main` to update our 3.4 and 3.5 changelogs for the new version.  Refer example https://github.com/etcd-io/etcd/pull/16763. Thanks! 🙏🏻

**Comment by arjunmalhotra1** [comment]
Sure @jmhbnz Here - https://github.com/etcd-io/etcd/pull/16943

**Comment by jmhbnz** [comment]
All changes completed and changelog updated, closing.
