### ISSUE TITLE
remove unnecessary else block on test

### ISSUE THREAD

**Issue by moficodes** [etcd-io/etcd#16897]
### What would you like to be added?

in etcdserver/api/v3discovery/discovery_test.go:266:9

else {
     fkv.t.Errorf("unexpected key: %s", key)
    return nil, fmt.Errorf("unexpected key: %s", key)
}

We can remove the `else` block and return right away.

### Why is this needed?

`make verify` fails with indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive).

**Comment by jmhbnz** [comment]
Hey @moficodes - Thanks for raising this, which `golangci-lint` version are you using?

The project currently uses `1.53.3` which does not flag this issue, refer https://github.com/etcd-io/etcd/blob/main/.github/workflows/static-analysis.yaml#L18

I note pull request https://github.com/etcd-io/etcd/pull/16889 is related to this.

If we proceed with fixing this which I'm not opposed to, ideally we would also bump golangci-lint to a version which identifies this issue and fix any other instances detected (if any).

**Comment by serathius** [comment]
> If we proceed with fixing this which I'm not opposed to, ideally we would also bump golangci-lint to a version which identifies this issue and fix any other instances detected (if any).

I think we kept golangci-lint old to avoid allowing go1.21 features. I think we should revisit this decision.

**Comment by moficodes** [comment]
This failed on 1.55.2. 

This is the only linting error that comes up.

**Comment by moficodes** [comment]
If we want to keep it at that version, I think we need to update [Contributing](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md) docs to make sure developers have the correct environment setup.

**Comment by jmhbnz** [comment]
> I think we kept golangci-lint old to avoid allowing go1.21 features. I think we should revisit this decision.

Based on the discussion in https://github.com/etcd-io/etcd/pull/16661#issuecomment-1740176562 the 1.21 discussion was in relation to the use of new builtins rather than updating golangci-lint specifically?

I agree we should try and update the project version and if there is a blocker update `CONTIBUTING.md` if we can't.

**Comment by jmhbnz** [comment]
With https://github.com/etcd-io/etcd/pull/16889 merged latest `golangci-lint` version `1.55.2` runs successfully for me.

@moficodes would you be able to raise a pr to propose adopting this version?
