### ISSUE TITLE
Install github app of slack for etcd-io

### ISSUE THREAD

**Issue by liangyuanpeng** [etcd-io/etcd#16890]
### What would you like to be added?

When i ask (`/github subscribe etcd-io/etcd`) the slack app of github etcd-io/etcd and it's say:
```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).
```

So this issue is a request of Install github app of slack for etcd-io

### Why is this needed?

This allows everyone to monitor github-related events on etcd-io in their own slack channel. I am currently receiving messages from multiple projects or organizations in slack, such as kubernetes, Apache pulsar ,karmada-io.

**Comment by jberkus** [comment]
Kubernetes slack restricts the available Slack apps.  I'm checking whether this one is on the approved list.

**Comment by jberkus** [comment]
So, the answer is that we do NOT allow the general Github plugin due to security concerns.

However, we do support Slack integration with Prow, which is probably more what we want anyway.

Since that's a bit different from what you're asking, I'll open a new issue for it.

**Comment by jberkus** [comment]
This issue is now replaced with issue #17882, so closing.

/close

**Comment by liangyuanpeng** [comment]
Sounds good, Thanks you for doing this.
