### ISSUE TITLE
Run `arm64` integration tests for every pull request rather than on nightly schedule

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#16905]
### What would you like to be added?

Recently in https://github.com/etcd-io/etcd/pull/16801 we introduced on demand github actions runners for the `arm64` platform.

Having on demand runner infrastructure in place means we should now have enough capacity to begin running `arm64` tests for every pull request.

We should update our `.github/workflows/tests-arm64-nightly.yaml` workflow to switch from scheduled nightly runs to instead running `on: [push, pull_request]`: https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests-arm64-nightly.yaml#L7-L8

### Why is this needed?

Gain greater confidence and samples of integration tests running against `arm64` cpu architecture.

Hopefully detect issues before pull requests are merged to `main`.

**Comment by ivanvc** [comment]
Can you assign me to this one? Thanks
