### ISSUE TITLE
add instructions to install protoc in contributing.md

### ISSUE THREAD

**Issue by moficodes** [etcd-io/etcd#16904]
### What would you like to be added?

add links / instruction to install protoc for setting up the dev environment. 

it should also mention that protoc needs to be version `3.20.3` https://github.com/etcd-io/etcd/blob/main/scripts/genproto.sh#L27

### Why is this needed?

`make verify` fails in protoc is not available in the system or the version is anything other than `3.20.3`

**Comment by vivekpatani** [comment]
I think it's to produce reproducible builds by pinning `protoc` generation to a specific version.

[Source](https://github.com/etcd-io/etcd/blob/6e30d9ed7d1d64db44a93d020e7bc57aed61c6b4/scripts/genproto.sh#L27-L30)
```
if [[ $(protoc --version | cut -f2 -d' ') != "3.20.3" ]]; then
  echo "could not find protoc 3.20.3, is it installed + in PATH?"
  exit 255
fi
```

**Comment by moficodes** [comment]
Thats reasonable. But the `contributing.md` does not mention `protoc` being a requirement. So when `make verify` is run it will fail the test.

**Comment by jmhbnz** [comment]
Thanks for raising this @moficodes - I think it makes sense to add a bullet point under https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#option-1---manually-setup-local-environment to cover installing the projects pinned version of `protoc`.  If you have time please raise a pr 🙏🏻

**Comment by moficodes** [comment]
Please assign this to me.

There is also some other requirements for this that I can add to the same pr.

e.g - yamllint

**Comment by serathius** [comment]
Would be great enhancement to add a `make install-protoc install-yamllint` commands
