### ISSUE TITLE
Integrate github workflows with Kubernetes Bot commands

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#16956]
### What would you like to be added?

Copy https://github.com/kubernetes-sigs/metrics-server/blob/master/.github/workflows/gh-workflow-approve.yaml to etcd project allowing `/ok-to-test` command to also work with github workflows.

### Why is this needed?

Allow etcd members to trigger tests on PRs from new contributors and possibly more in the future

**Comment by ivanvc** [comment]
Can you assign this to me? Thanks

**Comment by ivanvc** [comment]
I implemented this on #16965, which works for the `main` branch. Do we want to enable/implement this for the `release-3,5` (or other) branch?
