### ISSUE TITLE
Add a "memberReplace" e2e test to prevent regression

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17069]
### What would you like to be added?

https://github.com/etcd-io/etcd/commit/4fe46f92030e4381e6f9bf95adbb22a08282d297 introduced regression that was cought by robustness test https://github.com/etcd-io/etcd/issues/17052

Issue was related to how normal etcd operation, replacing a member, and was not specific to robustness testing.
We should have a normal e2e test to run this scenario.

### Why is this needed?

Prevent potential regressions when deprecating v2 store.

**Comment by ZhouJianMS** [comment]
Would like to work on this

**Comment by liangyuanpeng** [comment]
Seems like this is resolved and can be closed.
