### ISSUE TITLE
need the --hearbeat-timeout option ?

### ISSUE THREAD

**Issue by ystkfujii** [etcd-io/etcd#17129]
### What would you like to be added?

hearbeat-timeout option

### Why is this needed?

FYI: https://github.com/etcd-io/etcd/blob/4e986363a371ad88479cb8f9b248d16ea83abc87/server/embed/config.go#L169

**Comment by ystkfujii** [comment]
If the creation of the heartbeat-timeout option is necessary, I would like to address it.

**Comment by ahrtr** [comment]
Thanks for raising this, but I would suggest to keep it as it's for now, unless you have a very strong justification.
- We do not receive any complains yet
- It would need to change both etcd and raft
