### ISSUE TITLE
Add memberReplaceWithLearner e2e test and scenario to robustness tests

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17121]
### What would you like to be added?

same as test ReplaceMember but replace it with learner and then promote it after some time 

### Why is this needed?

Improve testing coverage of membership information

**Comment by nitishfy** [comment]
Hi, I'd like to take this up. Please assign this to me!

**Comment by jmhbnz** [comment]
Thanks @nitishfy, assigned. I would start by taking a look at the existing ReplaceMember tests and feel free to ask any questions here as you go.

**Comment by nitishfy** [comment]
**Update:** I've started working on this issue.
