### ISSUE TITLE
Enabling logging of current-db-size-in-use-bytes & current-db-size-in-use parameters during compaction run

### ISSUE THREAD

**Issue by IamSatyaonline** [etcd-io/etcd#17178]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When ETCD runs defragmentation internally , ETCD print the values of parameters current-db-size-in-use-bytes, current-db-size-in-use , current-db-size etc. in ETCD logs to show the available size of DB and consumption of DB. We want to see the current DB usage of ETCD at run time whenever compaction runs internally by ETCD.

### What did you expect to happen?

we want to print value of current-db-size-in-use-bytes, current-db-size-in-use , current-db-size parameters in ETCD logs during compaction ?

### How can we reproduce it (as minimally and precisely as possible)?

Every time it's reproducible. 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment]
Closing - Duplicate of https://github.com/etcd-io/etcd/issues/17179.
