### ISSUE TITLE
etcd exceeds 8G limited

### ISSUE THREAD

**Issue by tommyzhao830** [etcd-io/etcd#17170]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

etcd exceeds 8G, the cluster is unavailable, is there a way to increase this limit.

### What did you expect to happen?

I hope there can be a solution that can increase the capacity of etcd

### How can we reproduce it (as minimally and precisely as possible)?

You can try filling up the etcd store to reproduce the problem.

### Etcd version (please run commands below)

<details>

```
v3.25
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by fuweid** [comment]
Hi @tommyzhao830 you can use `--quota-backend-bytes`  to change that value. Or you can perform defragment if neccessary. And v3.3.25 is end of life. Please upgrade to v3.5 release. thanks

**Comment by tommyzhao830** [comment]
Is it possible to break through the maximum limit of 8G, because during the use of my cluster, this capacity may exceed the limit.

**Comment by ahrtr** [comment]
Please upgrade the etcd version to 3.5+, and also read https://etcd.io/blog/2023/how_to_debug_large_db_size_issue/
