### ISSUE TITLE
Enabling logging of current-db-size-in-use-bytes & current-db-size-in-use parameters during compaction run

### ISSUE THREAD

**Issue by IamSatyaonline** [etcd-io/etcd#17179]
### What would you like to be added?

When ETCD runs defragmentation internally , ETCD print the values of parameters current-db-size-in-use-bytes, current-db-size-in-use , current-db-size etc. in ETCD logs to show the available size of DB and consumption of DB. We want to see the current DB usage of ETCD at run time whenever compaction runs internally by ETCD. How can we print value of these parameters in ETCD logs during compaction ?

### Why is this needed?

When ETCD runs defragmentation internally , ETCD print the values of parameters current-db-size-in-use-bytes, current-db-size-in-use , current-db-size etc. in ETCD logs to show the available size of DB and consumption of DB. We want to see the current DB usage of ETCD at run time whenever compaction runs internally by ETCD.

**Comment by serathius** [comment]
Compaction doesn't influence `current-db-size-in-use-bytes`, `current-db-size-in-use` so there is no sense to log it. You can just read the metrics.

**Comment by IamSatyaonline** [comment]
Hi @serathius 
I agree that those parameters are not getting changed during compaction, but we have requirement to track database usage stats during every compaction which will help us to pull the metrics on every compaction and analyze database usage stats. Every time pulling the metrics and analyze the metrics data is little complex compare to checking in logs.

Thanks,
Satya

**Comment by serathius** [comment]
> we have requirement to track database usage stats during every compaction

Who is "we" in this? Please explain how this helps overall etcd users in broader terms.

**Comment by IamSatyaonline** [comment]
Hi @serathius 
The defragmentation runs every 1 hour and etcd log shows the DB usage during defragmentation.  In between 1 hour, if etcd DB gets filled up, then user needs to take corrective actions to clean up etcd DB. If etcd users want to track the DB usage at a smaller time duration e.g. during "compaction" which is executed every 5 minutes, then looking at the DB usage values from etcd log, etcd users would be able to take some proactive action (like cleanup DB) and would be able to avoid the MVCC database space exceeded error. In this use case, this DB usage log during compaction would help etcd users.

Thanks,
Satya

**Comment by IamSatyaonline** [comment]
Hi @serathius
Could you please have a look on my previous comment and share your views ?

Thanks,
Satya

**Comment by IamSatyaonline** [comment]
> Hi @serathius The defragmentation runs every 1 hour and etcd log shows the DB usage during defragmentation. In between 1 hour, if etcd DB gets filled up, then user needs to take corrective actions to clean up etcd DB. If etcd users want to track the DB usage at a smaller time duration e.g. during "compaction" which is executed every 5 minutes, then looking at the DB usage values from etcd log, etcd users would be able to take some proactive action (like cleanup DB) and would be able to avoid the MVCC database space exceeded error. In this use case, this DB usage log during compaction would help etcd users.
> 
> Thanks, Satya

Hi @serathius  @ahrtr 
Could you please share your input on my above comment ? can we go ahead to contribute and make the changes to add log line of DB usage parameters.

Thanks,
Satya

**Comment by ahrtr** [comment]
If compaction operation indeed removes some data, it will decrease the db_size_in_use, but will not change the db_total_size, which will only change when performing defragmentation. So in short, 
- compaction changes db_size_in_use;
- defragmentation changes db_total_size

I tent to agree to get the db_size_in_use included in the compaction log, at least it will not do any harm. Overall, not a big deal.

Usually you should depend on the metrics to monitor the db storage usage. 
- etcd_mvcc_db_total_size_in_bytes
- etcd_mvcc_db_total_size_in_use_in_bytes

**Comment by IamSatyaonline** [comment]
Hi @ahrtr 
Thanks for your comment.
We would need the metrics parameters current-db-size, current-db-size-bytes, current-db-size-in-use and current-db-size-in-use-bytes and their values in etcd log during "compaction". Please let us know if this is fine and pull request https://github.com/etcd-io/etcd/pull/17204 can be reviewed.

Regards,
Satya

**Comment by ahrtr** [comment]
Completed in https://github.com/etcd-io/etcd/pull/17204

**Comment by IamSatyaonline** [comment]
Thanks @ahrtr and @serathius for your support and help to process the pull request.

Regards,
Satya

**Comment by ahrtr** [comment]
@IamSatyaonline can you please backport the PR to 3.4 as well? Thanks

**Comment by jmhbnz** [comment]
Re-open, we still need to add CHANGELOG entries imo, given this touches user facing log content.
