### ISSUE TITLE
Plans to release 3.4.29

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17207]
### What would you like to be added?

- https://github.com/etcd-io/etcd/pull/17112
- https://github.com/etcd-io/etcd/pull/17128
- https://github.com/etcd-io/etcd/pull/17076

Also include a couple of backporting fixes. If there is no any objection, we can get them included in next patch 3.4.30.
- https://github.com/etcd-io/etcd/pull/17199
  - [x] https://github.com/etcd-io/etcd/pull/17208
- https://github.com/etcd-io/etcd/pull/17195
  - [ ] Need to backport
- https://github.com/etcd-io/etcd/pull/16822
  - [ ] Need to backport
- https://github.com/etcd-io/etcd/pull/17176
  - [ ] Need to backport

### Why is this needed?

It also includes a couple of CVE fixes

**Comment by ahrtr** [comment]
I will try to release 3.4.29 tomorrow to resolve the CVE asap, and get the two remaining backporting included in next patch 3.4.20. Please let me know if anyone has any comment. cc @jamesdphillips @serathius @wenjiaswe

**Comment by fuweid** [comment]
I would like to add this one [server: fix learner metric incorrect issue](https://github.com/etcd-io/etcd/pull/17176) into 3.4.30

**Comment by ahrtr** [comment]
Done https://github.com/etcd-io/etcd/releases/tag/v3.4.29.

Let's get all other fixes included in next patch 3.4.30.
