### ISSUE TITLE
Access to etcd dependency management roster document revoked

### ISSUE THREAD

**Issue by sharathsivakumar** [etcd-io/etcd#17224]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

While bumping the etcd dependency today, I needed to update the roster with the associated PR. It was not possible to access the [document](https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0)

### What did you expect to happen?

All members part of etcd-dev group should be able to access the document 

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Anything else we need to know?

NA

### Etcd version (please run commands below)

NA

### Etcd configuration (command line flags or environment variables)

NA

**Comment by sharathsivakumar** [comment]
@ahrtr Could you please check if something changed with the google docs document that tracks etcd dependency management on-call?

**Comment by ahrtr** [comment]
I forked a doc https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387, could anyone raise a PR to update the link in the dependency_management.md? thx

**Comment by jmhbnz** [comment]
Completed in https://github.com/etcd-io/etcd/pull/17225
