### ISSUE TITLE
[3.4] linux-amd64-e2e job takes more than 30min

### ISSUE THREAD

**Issue by fuweid** [etcd-io/etcd#17241]
### Which github workflows are flaking?

linux-amd64-e2e

### Which tests are flaking?

The e2e testcases need more than 30min but workflow timeout is 30min

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/7505424685/job/20453159962?pr=17238

### Reason for failure (if possible)

Need to investigate e2e runtime.

**Comment by ahrtr** [comment]
Recently we see lots of workflow timeout.

Could anyone take a look at this?

**Comment by ahrtr** [comment]
It seems that it always fails when running the following two cases.
```
	TestWatchDelayForEvent (3s)
	TestWatchDelayForEvent/NoTLS (3s)
```

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/etcd/pull/17304
