### ISSUE TITLE
MY_STS_NAME: unbound variable

### ISSUE THREAD

**Issue by wangchao732** [etcd-io/etcd#17243]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

In the etcd cluster mod, etcd2 cannot be started in the K8s cluster

### What did you expect to happen?

 etcd 17:41:07.82 INFO  ==> 

 etcd 17:41:07.82 INFO  ==> Welcome to the Bitnami etcd container

 etcd 17:41:07.82 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers

 etcd 17:41:07.82 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues

 etcd 17:41:07.82 INFO  ==> 

 etcd 17:41:07.82 INFO  ==> ** Starting etcd setup **

 etcd 17:41:07.84 INFO  ==> Validating settings in ETCD_* env vars..

 etcd 17:41:07.84 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.

 etcd 17:41:07.85 INFO  ==> Initializing etcd

 etcd 17:41:07.85 INFO  ==> Generating etcd config file using env variables

 etcd 17:41:07.87 INFO  ==> Detected data from previous deployments

 /opt/bitnami/scripts/libetcd.sh: line 269: MY_STS_NAME: unbound variable

 /opt/bitnami/scripts/libetcd.sh: line 436: ETCD_ACTIVE_ENDPOINTS: unbound variable

 etcd 17:41:07.91 DEBUG ==> Missing member data

 etcd 17:41:07.92 INFO  ==> Adding new member to existing cluster

 /opt/bitnami/scripts/libetcd.sh: line 269: MY_STS_NAME: unbound variable

### How can we reproduce it (as minimally and precisely as possible)?

 etcd 17:41:07.82 INFO  ==> 

 etcd 17:41:07.82 INFO  ==> Welcome to the Bitnami etcd container

 etcd 17:41:07.82 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers

 etcd 17:41:07.82 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues

 etcd 17:41:07.82 INFO  ==> 

 etcd 17:41:07.82 INFO  ==> ** Starting etcd setup **

 etcd 17:41:07.84 INFO  ==> Validating settings in ETCD_* env vars..

 etcd 17:41:07.84 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.

 etcd 17:41:07.85 INFO  ==> Initializing etcd

 etcd 17:41:07.85 INFO  ==> Generating etcd config file using env variables

 etcd 17:41:07.87 INFO  ==> Detected data from previous deployments

 /opt/bitnami/scripts/libetcd.sh: line 269: MY_STS_NAME: unbound variable

 /opt/bitnami/scripts/libetcd.sh: line 436: ETCD_ACTIVE_ENDPOINTS: unbound variable

 etcd 17:41:07.91 DEBUG ==> Missing member data

 etcd 17:41:07.92 INFO  ==> Adding new member to existing cluster

 /opt/bitnami/scripts/libetcd.sh: line 269: MY_STS_NAME: unbound variable

### Etcd version (please run commands below)

kind: Pod
apiVersion: v1
metadata:
  name: apisix-etcd-2
  generateName: apisix-etcd-
  namespace: ingress-apisix
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    controller-revision-hash: apisix-etcd-5bc8bc97f7
    helm.sh/chart: etcd-6.2.6
    statefulset.kubernetes.io/pod-name: apisix-etcd-2
  annotations:
    kubesphere.io/restartedAt: '2023-12-27T02:04:32.709Z'
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-apisix-etcd-2
    - name: host-time
      hostPath:
        path: /etc/localtime
        type: ''
    - name: kube-api-access-d4c7z
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: etcd
      image: 'docker.io/bitnami/etcd:3.5.11-debian-11-r2'
      ports:
        - name: client
          containerPort: 2379
          protocol: TCP
        - name: peer
          containerPort: 2380
          protocol: TCP
      env:
        - name: BITNAMI_DEBUG
          value: 'true'
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ETCDCTL_API
          value: '3'
        - name: ETCD_ON_K8S
          value: 'yes'
        - name: ETCD_START_FROM_SNAPSHOT
          value: 'no'
        - name: ETCD_DISASTER_RECOVERY
          value: 'no'
        - name: ETCD_NAME
          value: $(MY_POD_NAME)
        - name: ETCD_DATA_DIR
          value: /bitnami/etcd/data
        - name: ETCD_LOG_LEVEL
          value: debug
        - name: ALLOW_NONE_AUTHENTICATION
          value: 'yes'
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: >-
            http://$(MY_POD_NAME).apisix-etcd-headless.ingress-apisix.svc.cluster.local:2379
        - name: ETCD_LISTEN_CLIENT_URLS
          value: 'http://0.0.0.0:2379'
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: >-
            http://$(MY_POD_NAME).apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380
        - name: ETCD_LISTEN_PEER_URLS
          value: 'http://0.0.0.0:2380'
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster-k8s
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: existing
        - name: ETCD_INITIAL_CLUSTER
          value: >-
            apisix-etcd-0=http://apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380,apisix-etcd-1=http://apisix-etcd-1.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380,apisix-etcd-2=http://apisix-etcd-2.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380
        - name: ETCD_CLUSTER_DOMAIN
          value: apisix-etcd-headless.ingress-apisix.svc.cluster.local
      resources: {}
      volumeMounts:
        - name: data
          mountPath: /bitnami/etcd
        - name: host-time
          readOnly: true
          mountPath: /etc/localtime
        - name: kube-api-access-d4c7z
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        exec:
          command:
            - /opt/bitnami/scripts/etcd/healthcheck.sh
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        exec:
          command:
            - /opt/bitnami/scripts/etcd/healthcheck.sh
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 5
      lifecycle:
        preStop:
          exec:
            command:
              - /opt/bitnami/scripts/etcd/prestop.sh
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: bj13-k8s121
  securityContext:
    fsGroup: 1001
  hostname: apisix-etcd-2
  subdomain: apisix-etcd-headless
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: apisix
                app.kubernetes.io/name: etcd
            namespaces:
              - ingress-apisix
            topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by liangyuanpeng** [comment]
> etcd 17:41:07.82 INFO ==> Welcome to the Bitnami etcd container
> etcd 17:41:07.82 INFO ==> Subscribe to project updates by watching https://github.com/bitnami/containers
> etcd 17:41:07.82 INFO ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
> etcd 17:41:07.82 INFO ==>

@wangchao732 As the log say, i believe that you need create a issue to https://github.com/bitnami/containers/issues

**Comment by ahrtr** [comment]
Please create an issue for binami, thx
