### ISSUE TITLE
Duplicated watch event detected in robustness test

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17247]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

2 robustness test failures:
* https://github.com/etcd-io/etcd/actions/runs/7511619449
* https://github.com/etcd-io/etcd/actions/runs/7518298280

Common elements:
* Both failures have a duplicated watch event
* Both on Kubernetes traffic
* Both on 3 node cluster

Differences:
* Failpoints: `raftAfterSaveSnap=panic()` and `MemberReplace`

Both failures on have duplicated watch event:
```
2024-01-13T09:50:27.4782520Z     validate.go:41: Failed merging watch history to create event history, skipping further validation, err: events between clients 11 and 9 don't match, revision: 800, diff:   []model.WatchEvent{
2024-01-13T09:50:27.4786636Z           	{Event: {Type: "put-operation", Key: "/registry/pods/default/76Z51", Value: {Value: "1061"}}, Revision: 800},
2024-01-13T09:50:27.4788612Z         - 	{
2024-01-13T09:50:27.4789499Z         - 		Event: model.Event{
2024-01-13T09:50:27.4790382Z         - 			Type:  "put-operation",
2024-01-13T09:50:27.4791612Z         - 			Key:   "/registry/pods/default/76Z51",
2024-01-13T09:50:27.4792744Z         - 			Value: model.ValueOrHash{Value: "1061"},
2024-01-13T09:50:27.4793619Z         - 		},
2024-01-13T09:50:27.4794433Z         - 		Revision: 800,
2024-01-13T09:50:27.4795136Z         - 	},
2024-01-13T09:50:27.4795687Z           }
```
```
2024-01-14T10:24:58.3514126Z     validate.go:41: Failed merging watch history to create event history, skipping further validation, err: events between clients 10 and 7 don't match, revision: 1583, diff:   []model.WatchEvent{
2024-01-14T10:24:58.3518620Z           	{Event: {Type: "put-operation", Key: "/registry/pods/default/rMWB7", Value: {Value: "1915"}}, Revision: 1583},
2024-01-14T10:24:58.3520322Z         + 	{
2024-01-14T10:24:58.3529383Z         + 		Event: model.Event{
2024-01-14T10:24:58.3530681Z         + 			Type:  "put-operation",
2024-01-14T10:24:58.3532196Z         + 			Key:   "/registry/pods/default/rMWB7",
2024-01-14T10:24:58.3533517Z         + 			Value: model.ValueOrHash{Value: "1915"},
2024-01-14T10:24:58.3534544Z         + 		},
2024-01-14T10:24:58.3535281Z         + 		Revision: 1583,
2024-01-14T10:24:58.3536055Z         + 	},
2024-01-14T10:24:58.3536676Z           }
```

### What did you expect to happen?

No robustness test failure

### How can we reproduce it (as minimally and precisely as possible)?

No repro yet, I don't have access to arm64 machine to debug

cc @ahrtr @jmhbnz 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Trying repro in https://github.com/etcd-io/etcd/actions/runs/7531548184/job/20500348689?pr=17248

**Comment by serathius** [comment]
Got a repro on both `arm64` and `amd64`.

https://github.com/etcd-io/etcd/actions/runs/7539634396?pr=17248

cc @ahrtr @jmhbnz @siyuanfoundation

**Comment by serathius** [comment]
Got a one local repro.

**Comment by serathius** [comment]
Example watch request-response with a duplicated revision 882
```
{"Request":{"Key":"/registry/pods/","Revision":854,"WithPrefix":true,"WithProgressNotify":true},"Responses":[{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/zlqKy","Value":{"Value":"980","Hash":0},"Revision":854},{"Type":"put-operation","Key":"/registry/pods/default/CPWLs","Value":{"Value":"982","Hash":0},"Revision":855},{"Type":"put-operation","Key":"/registry/pods/default/n5T9S","Value":{"Value":"983","Hash":0},"Revision":856},{"Type":"put-operation","Key":"/registry/pods/default/llCqr","Value":{"Value":"984","Hash":0},"Revision":857},{"Type":"put-operation","Key":"/registry/pods/default/Gvvm7","Value":{"Value":"985","Hash":0},"Revision":858},{"Type":"put-operation","Key":"/registry/pods/default/qalpx","Value":{"Value":"986","Hash":0},"Revision":859},{"Type":"put-operation","Key":"/registry/pods/default/EQPt4","Value":{"Value":"987","Hash":0},"Revision":860},{"Type":"put-operation","Key":"/registry/pods/default/158WY","Value":{"Value":"988","Hash":0},"Revision":861},{"Type":"put-operation","Key":"/registry/pods/default/WAGPJ","Value":{"Value":"991","Hash":0},"Revision":862},{"Type":"put-operation","Key":"/registry/pods/default/gqmYo","Value":{"Value":"992","Hash":0},"Revision":863},{"Type":"put-operation","Key":"/registry/pods/default/lwMud","Value":{"Value":"993","Hash":0},"Revision":864},{"Type":"put-operation","Key":"/registry/pods/default/bbfGl","Value":{"Value":"994","Hash":0},"Revision":865},{"Type":"put-operation","Key":"/registry/pods/default/e9AyQ","Value":{"Value":"996","Hash":0},"Revision":866},{"Type":"put-operation","Key":"/registry/pods/default/mpvvr","Value":{"Value":"997","Hash":0},"Revision":867},{"Type":"put-operation","Key":"/registry/pods/default/F3TRD","Value":{"Value":"998","Hash":0},"Revision":868},{"Type":"put-operation","Key":"/registry/pods/default/OVXTy","Value":{"Value":"1000","Hash":0},"Revision":869},{"Type":"put-operation","Key":"/registry/pods/default/uZBI1","Value":{"Value":"1002","Hash":0},"Revision":870},{"Type":"put-operation","Key":"/registry/pods/default/qbvoO","Value":{"Value":"1003","Hash":0},"Revision":871},{"Type":"put-operation","Key":"/registry/pods/default/4b7V4","Value":{"Value":"1005","Hash":0},"Revision":872},{"Type":"put-operation","Key":"/registry/pods/default/WPXbR","Value":{"Value":"1006","Hash":0},"Revision":873},{"Type":"put-operation","Key":"/registry/pods/default/F3Ro3","Value":{"Value":"1007","Hash":0},"Revision":874},{"Type":"put-operation","Key":"/registry/pods/default/s2DPx","Value":{"Value":"1008","Hash":0},"Revision":875},{"Type":"put-operation","Key":"/registry/pods/default/Gvvm7","Value":{"Value":"1009","Hash":0},"Revision":876},{"Type":"put-operation","Key":"/registry/pods/default/XcZU8","Value":{"Value":"1010","Hash":0},"Revision":877},{"Type":"put-operation","Key":"/registry/pods/default/553WP","Value":{"Value":"1011","Hash":0},"Revision":878},{"Type":"put-operation","Key":"/registry/pods/default/Ft0M7","Value":{"Value":"1012","Hash":0},"Revision":879},{"Type":"put-operation","Key":"/registry/pods/default/EQPt4","Value":{"Value":"1013","Hash":0},"Revision":880},{"Type":"put-operation","Key":"/registry/pods/default/PSvk1","Value":{"Value":"1014","Hash":0},"Revision":881},{"Type":"put-operation","Key":"/registry/pods/default/gqmYo","Value":{"Value":"1015","Hash":0},"Revision":882},{"Type":"put-operation","Key":"/registry/pods/default/gqmYo","Value":{"Value":"1015","Hash":0},"Revision":882},{"Type":"put-operation","Key":"/registry/pods/default/llCqr","Value":{"Value":"1017","Hash":0},"Revision":883},{"Type":"put-operation","Key":"/registry/pods/default/vSBGf","Value":{"Value":"1019","Hash":0},"Revision":884},{"Type":"put-operation","Key":"/registry/pods/default/n5T9S","Value":{"Value":"1020","Hash":0},"Revision":885}],"IsProgressNotify":false,"Revision":885,"Time":6124853237},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/OVXTy","Value":{"Value":"1021","Hash":0},"Revision":886}],"IsProgressNotify":false,"Revision":886,"Time":6125394945},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/XcZU8","Value":{"Value":"1023","Hash":0},"Revision":887}],"IsProgressNotify":false,"Revision":887,"Time":6134684586},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/mxBK7","Value":{"Value":"1024","Hash":0},"Revision":888}],"IsProgressNotify":false,"Revision":888,"Time":6137375281},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/bbfGl","Value":{"Value":"1025","Hash":0},"Revision":889}],"IsProgressNotify":false,"Revision":889,"Time":6145422960},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/lRR85","Value":{"Value":"1026","Hash":0},"Revision":890}],"IsProgressNotify":false,"Revision":890,"Time":6147789266},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/v0Wg5","Value":{"Value":"1027","Hash":0},"Revision":891}],"IsProgressNotify":false,"Revision":891,"Time":6157548521},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/PI7s9","Value":{"Value":"1028","Hash":0},"Revision":892}],"IsProgressNotify":false,"Revision":892,"Time":6162857744},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/v0Wg5","Value":{"Value":"1029","Hash":0},"Revision":893}],"IsProgressNotify":false,"Revision":893,"Time":6173448149},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/ZsJkQ","Value":{"Value":"1030","Hash":0},"Revision":894}],"IsProgressNotify":false,"Revision":894,"Time":6177937264},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/eikdd","Value":{"Value":"1031","Hash":0},"Revision":895}],"IsProgressNotify":false,"Revision":895,"Time":6182406700},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/fNa1r","Value":{"Value":"1032","Hash":0},"Revision":896}],"IsProgressNotify":false,"Revision":896,"Time":6188104553},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/EQPt4","Value":{"Value":"1033","Hash":0},"Revision":897}],"IsProgressNotify":false,"Revision":897,"Time":6198847616},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/WAGPJ","Value":{"Value":"1035","Hash":0},"Revision":898}],"IsProgressNotify":false,"Revision":898,"Time":6212652771},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/HdoK9","Value":{"Value":"1036","Hash":0},"Revision":899}],"IsProgressNotify":false,"Revision":899,"Time":6219512628},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/bbfGl","Value":{"Value":"1037","Hash":0},"Revision":900}],"IsProgressNotify":false,"Revision":900,"Time":6225460171},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/s2DPx","Value":{"Value":"1038","Hash":0},"Revision":901}],"IsProgressNotify":false,"Revision":901,"Time":6231087364},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/4t7Cm","Value":{"Value":"1039","Hash":0},"Revision":902}],"IsProgressNotify":false,"Revision":902,"Time":6237653749},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/rwstr","Value":{"Value":"1040","Hash":0},"Revision":903}],"IsProgressNotify":false,"Revision":903,"Time":6242222081},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/vs80D","Value":{"Value":"1041","Hash":0},"Revision":904}],"IsProgressNotify":false,"Revision":904,"Time":6252938003},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/63GF1","Value":{"Value":"1042","Hash":0},"Revision":905}],"IsProgressNotify":false,"Revision":905,"Time":6259062598},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/zlqKy","Value":{"Value":"1043","Hash":0},"Revision":906}],"IsProgressNotify":false,"Revision":906,"Time":6279987619},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/PSvk1","Value":{"Value":"1044","Hash":0},"Revision":907}],"IsProgressNotify":false,"Revision":907,"Time":6280049124},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/7hGI0","Value":{"Value":"1045","Hash":0},"Revision":908}],"IsProgressNotify":false,"Revision":908,"Time":6284565610},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/9nMUa","Value":{"Value":"1046","Hash":0},"Revision":909}],"IsProgressNotify":false,"Revision":909,"Time":6287166957},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/ZVcyt","Value":{"Value":"1047","Hash":0},"Revision":910}],"IsProgressNotify":false,"Revision":910,"Time":6292679653},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/5uhDY","Value":{"Value":"1048","Hash":0},"Revision":911}],"IsProgressNotify":false,"Revision":911,"Time":6297197079},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/qalpx","Value":{"Value":"1049","Hash":0},"Revision":912}],"IsProgressNotify":false,"Revision":912,"Time":6307661469},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/PI7s9","Value":{"Value":"1050","Hash":0},"Revision":913}],"IsProgressNotify":false,"Revision":913,"Time":6313212397},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/jOxQ8","Value":{"Value":"1051","Hash":0},"Revision":914}],"IsProgressNotify":false,"Revision":914,"Time":6324605471},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/edTMh","Value":{"Value":"1052","Hash":0},"Revision":915}],"IsProgressNotify":false,"Revision":915,"Time":6328803116},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/rwZnc","Value":{"Value":"1053","Hash":0},"Revision":916}],"IsProgressNotify":false,"Revision":916,"Time":6333627710},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/UvmJr","Value":{"Value":"1054","Hash":0},"Revision":917}],"IsProgressNotify":false,"Revision":917,"Time":6340956298},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/qalpx","Value":{"Value":"1055","Hash":0},"Revision":918}],"IsProgressNotify":false,"Revision":918,"Time":6349607460},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/6Z4sD","Value":{"Value":"1056","Hash":0},"Revision":919}],"IsProgressNotify":false,"Revision":919,"Time":6352693006},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/qbvoO","Value":{"Value":"1057","Hash":0},"Revision":920}],"IsProgressNotify":false,"Revision":920,"Time":6363659529},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/F3TRD","Value":{"Value":"1058","Hash":0},"Revision":921}],"IsProgressNotify":false,"Revision":921,"Time":6371889239},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/pMgix","Value":{"Value":"1059","Hash":0},"Revision":922}],"IsProgressNotify":false,"Revision":922,"Time":6375499923},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/rwZnc","Value":{"Value":"1060","Hash":0},"Revision":923}],"IsProgressNotify":false,"Revision":923,"Time":6386067716},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/v0Wg5","Value":{"Value":"1061","Hash":0},"Revision":924}],"IsProgressNotify":false,"Revision":924,"Time":6388870782},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/0AUzn","Value":{"Value":"1062","Hash":0},"Revision":925}],"IsProgressNotify":false,"Revision":925,"Time":6392359146},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/lwMud","Value":{"Value":"1063","Hash":0},"Revision":926}],"IsProgressNotify":false,"Revision":926,"Time":6407253095},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/6Z4sD","Value":{"Value":"1064","Hash":0},"Revision":927}],"IsProgressNotify":false,"Revision":927,"Time":6417900820},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/Ft0M7","Value":{"Value":"1066","Hash":0},"Revision":928}],"IsProgressNotify":false,"Revision":928,"Time":6438074579},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/OVXTy","Value":{"Value":"1068","Hash":0},"Revision":929}],"IsProgressNotify":false,"Revision":929,"Time":6452060313},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/SOhlK","Value":{"Value":"1070","Hash":0},"Revision":930}],"IsProgressNotify":false,"Revision":930,"Time":6469929313},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/pUZix","Value":{"Value":"1071","Hash":0},"Revision":931}],"IsProgressNotify":false,"Revision":931,"Time":6477969346},{"Events":[{"Type":"put-operation","Key":"/registry/pods/default/HdoK9","Value":{"Value":"1072","Hash":0},"Revision":932}],"IsProgressNotify":false,"Revision":932,"Time":6482229480}]}
```

**Comment by serathius** [comment]
Trying to bisect in the PR responsible.

Last passing nightly https://github.com/etcd-io/etcd/actions/runs/7486757727 with commit https://github.com/etcd-io/etcd/commit/b3bf59a3557ce81fb9d4615df667b4cacc6a4f6d as a bisect start. However it's not guaranteed corrct commit, due to flakes in https://github.com/etcd-io/etcd/issues/17246 we cannot be 100% sure about error rate of this issue.

**Comment by serathius** [comment]
We should also investigate why this issue only reproduces on arm64 in CI, even though locally it also appears on amd. Issues independent of platform should be detected on both. Expect this is because of two reasons:
* arm64 has lower performance as observed in https://github.com/etcd-io/etcd/issues/17246 making issue more likely to surface
* We don't run this combination frequent enough. It takes around 5-10 minutes of running combination of KubernetesTraffic(1/1), ClusterOfSize3(1/1), `raftAfterSaveSnap=panic()` (1/35), snapshotCount=50 (1/3). So during robustness tests we in such combination only once per 13 days, while reproducing it takes around 50 repeated runs.

I think we should consider increasing number of runs of exploratory tests (`TestRobustness/Kubernetes`, `TestRobustness/Etcd`), while reducing the number of regressions tests (`TestRobustness/Issue*`)

**Comment by serathius** [comment]
Bisection pointed to https://github.com/etcd-io/etcd/commit/ed994248e08212ebfd9ba883ff6ec1ddde41e977 as first broken commit, due to not 100% reproducibility we need to more testing to confirm.

Will continue to work on confirming the results, but in the mean time we need to block backports.

**Comment by serathius** [comment]
Reproduced the issue enough time to make me sure that this is https://github.com/etcd-io/etcd/pull/17228

@siyuanfoundation Do you have time look into this soon or would you prefer to revert and fix later?

**Comment by siyuanfoundation** [comment]
I will take a look today

**Comment by ahrtr** [comment]
https://github.com/etcd-io/etcd/pull/17263#discussion_r1454808849 is a valid point. The key point is `dedupe` always increase `bb.used` by 1 at least, even there is no any write in the `key` bucket. 

https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/server/storage/backend/tx_buffer.go#L220 

Actually there shouldn't be any duplicated items,
- for key bucket, the `key` is the revision, which is always monotonically growing;
- for non key buckets, if clients insert the same key (e.g. user, role, etc.), etcd will return *AlreayExist error. The only possible case is deleting and adding an object (e.g an user) again. But etcd will commit the TXN immediately if there is any deletion operation.

Proposed actions:
- revert https://github.com/etcd-io/etcd/pull/17228
- remove the `(*bucketBuffer) dedupe` (we need to keep the `sort.Stable(bb)` after merging the write and read buffers), but let's add a verification to ensure there is no any duplicated keys. https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/server/storage/backend/tx_buffer.go#L211
- whether it's possible to simplify the `mergeWatchEventHistory`, which has 4 levels of loop? https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/tests/robustness/validate/validate.go#L63-L69

**Comment by siyuanfoundation** [comment]
> [#17263 (comment)](https://github.com/etcd-io/etcd/pull/17263#discussion_r1454808849) is a valid point. The key point is `dedupe` always increase `bb.used` by 1 at least, even there is no any write in the `key` bucket.
> 
> https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/server/storage/backend/tx_buffer.go#L220
> 
> Actually there shouldn't be any duplicated items,
> 
> * for key bucket, the `key` is the revision, which is always monotonically growing;
> * for non key buckets, if clients insert the same key (e.g. user, role, etc.), etcd will return *AlreayExist error. The only possible case is deleting and adding an object (e.g an user) again. But etcd will commit the TXN immediately if there is any deletion operation.
> 
> Proposed actions:
> 
> * revert [Fix tx buffer inconsistency if there are duplicate keys in one tx. #17228](https://github.com/etcd-io/etcd/pull/17228)
> * remove the `(*bucketBuffer) dedupe` (we need to keep the `sort.Stable(bb)` after merging the write and read buffers), but let's add a verification to ensure there is no any duplicated keys. https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/server/storage/backend/tx_buffer.go#L211
> * whether it's possible to simplify the `mergeWatchEventHistory`, which has 4 levels of loop? https://github.com/etcd-io/etcd/blob/e3c70c8a99401a417c7eb4ba4d805d6038b4707a/tests/robustness/validate/validate.go#L63-L69

I disagree with the proposal. 
1. at the buffer level, it is unnecessary and confusing to assume no duplicates in the replace path when the actual merging code does not make such assumptions. 
2. Most of dedupe (sorting) is still needed even if there is no duplicate. See `TestRangeAfterUnorderedKeyWriteMatch` in https://github.com/etcd-io/etcd/pull/17263

**Comment by ahrtr** [comment]
> at the buffer level, it is unnecessary and confusing to assume no duplicates in the replace path when the actual merging code does not make such assumptions.

Where is the assumption? I didn't make any assumption. Always remember to simplify the repo as much as possible! In this case, the `dedupe` is unnecessary, so let's remove it to reduce the complexity. Just as I mentioned above, we also need to add a verification for it to ensure we do not make any wrong decision. (Search verify.Verify in the repo)

> Most of dedupe (sorting) is still needed even if there is no duplicate

- Copied from my previous comment `we need to keep the sort.Stable(bb) after merging the write and read buffers`. 
- Again, for `key` bucket, it's always sorted (revision is always monotonically growing); for non key bucket, there is no need to be sorted, note range operation isn't allowed on non key bucket. Also we need to add a verification as mentioned above.

Anyway, let's revert https://github.com/etcd-io/etcd/pull/17228 firstly to not to fail the workflow

**Comment by siyuanfoundation** [comment]
> > at the buffer level, it is unnecessary and confusing to assume no duplicates in the replace path when the actual merging code does not make such assumptions.
> 
> Where is the assumption? I didn't make any assumption. Always remember to simplify the repo as much as possible! In this case, the `dedupe` is unnecessary, so let's remove it to reduce the complexity. Just as I mentioned above, we also need to add a verification for it to ensure we do not make any wrong decision. (Search verify.Verify in the repo)

"there shouldn't be any duplicated items" is an assumption. Or if you prefer, a constraint. This might be true on the etcd level because there is yet no use cases of putting duplicate keys between lock and unlock. But at the tx/buffer level, if `UnsafePut` is a public method, my natural assumption is that it should be possible put duplicate keys. 

Yes, adding verification could safeguard it. But it is just strange to have such a constraint. 

In addition, it does not make the code simpler, because `func (bb *bucketBuffer) merge(bbsrc *bucketBuffer)` still need the dedupe function, because there could be duplicate keys between 2 transactions. 
> 
> > Most of dedupe (sorting) is still needed even if there is no duplicate
> 
> * Copied from my previous comment `we need to keep the sort.Stable(bb) after merging the write and read buffers`.
> * Again, for `key` bucket, it's always sorted (revision is always monotonically growing); for non key bucket, there is no need to be sorted, note range operation isn't allowed on non key bucket. Also we need to add a verification as mentioned above.
> 
> Anyway, let's revert #17228 firstly to not to fail the workflow

https://github.com/etcd-io/etcd/pull/17263 will fix the workflow.

**Comment by wenjiaswe** [comment]
> Anyway, let's revert https://github.com/etcd-io/etcd/pull/17228 firstly to not to fail the workflow

Looks like we already have a fix for the failed workflow, why do we still need to revert in this case? https://github.com/etcd-io/etcd/pull/17263 is LGTMed.

**Comment by ahrtr** [comment]
> "there shouldn't be any duplicated items" is an assumption. Or if you prefer, a constraint.

It isn't an assumption, nor constraint. It's an invariant property, at least for the key space/bucket. Note etcd applys MVCC on the key space, as I mentioned above multiple times, the keys are monotonically growing revisions. There is no overwrite on any existing keys in the Key bucket. It's the key point to support concurrent & consistent read.

We should add a verification to ensure this invariant property. Refer to the verification added in the second commit in https://github.com/etcd-io/etcd/pull/17281. And it successfully identified some test issues so far,
- https://github.com/etcd-io/etcd/pull/17284
- There are also some unit test cases, which break this invariant property. e.g. TestBackendWriteback, TestConcurrentReadTx, etc.

**Comment by fuweid** [comment]
IMO there are two potential problems:

* buffer could contain duplicate keys
* buffer contains some keys which are committed into bbolt and accessable by read transaction

I think #17263 can be consided to fix first one. We don't need to introduce map for duplicate key check.
If `dedupe` changes `used` value, it should not happen for `Key` bucket. But for me, the reviewers need to pay more attentions to ensure the upper layer's component should not use `UnsafePut` for `Key` bucket.  So, we should consider to re-active #17263.

For second one, if there are overlap between buffer cache and read transacton, we should panic.
For `baseReadTx.UnsafeRange` function, we can add more comment about why we should only allow unsafe range `Key` bucket. It's helpful for new members or contributors to revisit the history.

Just my two cents.

**Comment by siyuanfoundation** [comment]
> 
> For second one, if there are overlap between buffer cache and read transacton, we should panic. For `baseReadTx.UnsafeRange` function, we can add more comment about why we should only allow unsafe range `Key` bucket. It's helpful for new members or contributors to revisit the history.
> 
For the second one, `baseReadTx.UnsafeRange` would panic if `limit > 1` for non Key buckets (https://github.com/etcd-io/etcd/blob/dd0b0526e115bfd2fd34756958262acafbfb6a80/server/storage/backend/read_tx.go#L86). Since buffer always have the latest value for other buckets, there should be no problem with overlap between buffer cache and read transacton

**Comment by siyuanfoundation** [comment]
Is there a standard benchmark process?

**Comment by ahrtr** [comment]
[benchmark](https://github.com/etcd-io/etcd/tree/main/tools/benchmark) is what we have so far. @jmhbnz may have some  thoughts on this.

**Comment by jmhbnz** [comment]
> [benchmark](https://github.com/etcd-io/etcd/tree/main/tools/benchmark) is what we have so far. @jmhbnz may have some thoughts on this.

Long story short we don't currently have a standard or easily democratised way for benchmarking.  We have two tools that are available however, `rw-heatmaps` and `benchmark`.

For a quick comparison I would suggest running benchmark with something like:

```bash
# Server
GOMAXPROCS=10 ./bin/etcd --quota-backend-bytes=17179869184 --listen-client-urls http://0.0.0.0:23790 --advertise-client-urls http://127.0.0.1:23790

# Benchmark
GOMAXPROCS=6 go run ./tools/benchmark put --conns=64 --clients=64 --key-size=256 --val-size=4096 --key-space-size=50000 --total=2000000 --endpoints "http://127.0.0.1:23790"

# make clean && make build between each run
``

For results to have any validity please run several times and ensure all runs for each branch being tested happen on the same hardware and as much as possible system load state.

**Comment by fuweid** [comment]
> Since buffer always have the latest value for other buckets, there should be no problem with overlap between buffer cache and read transacton

Hi @siyuanfoundation sorry for late reply. This issue is caused by committed key/values in buffer cache.
There is no guard between buffer cache and read transcation. Need more eyes during review.

**Comment by siyuanfoundation** [comment]
I have run benchmark 6 times as @jmhbnz suggested
```bash
# Server
GOMAXPROCS=10 ./bin/etcd --quota-backend-bytes=17179869184 --listen-client-urls http://0.0.0.0:23790 --advertise-client-urls http://127.0.0.1:23790

# Benchmark
GOMAXPROCS=6 go run ./tools/benchmark put --conns=64 --clients=64 --key-size=256 --val-size=4096 --key-space-size=50000 --total=2000000 --endpoints "http://127.0.0.1:23790"

# make clean && make build between each run
```
This is the result of the total time of each benchmark run:
![Screenshot 2024-01-24 at 12 07 30 PM](https://github.com/etcd-io/etcd/assets/10984162/c5202380-6345-48ac-a125-c983388329f0)

It is pretty noisy. But there does not seem to be much difference between https://github.com/etcd-io/etcd/pull/17281 and https://github.com/etcd-io/etcd/pull/17290.

**Comment by ahrtr** [comment]
thx for the testing. Then let's go for https://github.com/etcd-io/etcd/pull/17290, the main reason is that it's simpler & easy to understand / maintain.

We also need to backport https://github.com/etcd-io/etcd/pull/17325 to 3.5 and 3.4.

**Comment by serathius** [comment]
Just to double check. Have we expected lack of performance difference between https://github.com/etcd-io/etcd/pull/17281 and https://github.com/etcd-io/etcd/pull/17290 or is it a surprise? If that was unexpected can you double check the benchmark method? 

For example you used `./tools/benchmark put` which benchmarks only put requests, are we sure the change we are making would influence `put` latency?

**Comment by ahrtr** [comment]
> Have we expected lack of performance difference between #17281 and #17290 or is it a surprise?

In theory, #17281 should have the best performance, and #17290 have the worst performance, and `main` branch should be in between. 

 #17281 > main > #17290

So previous test result provided by @siyuanfoundation doesn't comply with our understanding. Probably there indeed isn't much performance difference. It's still better if we can double confirm,

- FYI one example I did previously https://github.com/etcd-io/etcd/pull/14394#issuecomment-1229606410
- I am thinking probably we can also develop & run some golang unit [benchmark test](https://pkg.go.dev/testing#hdr-Benchmarks)

**Comment by siyuanfoundation** [comment]
```
if !ok {
			delete(txw.buckets, k)
			wb.dedupe()
			txr.buckets[k] = wb
			continue
		}
```
is only called when the bucket does not exist yet in the read buffer, which is pretty rare. 
So I don't really expect any noticeable differences between main and https://github.com/etcd-io/etcd/pull/17290.

**Comment by ahrtr** [comment]
> is only called when the bucket does not exist yet in the read buffer, which is pretty rare

Why it's rare? Please read https://github.com/etcd-io/etcd/issues/17247#issuecomment-1911825342 and try the two proposed ways to double confirm the performance impact.

**Comment by serathius** [comment]
Meant to ask if there is anything else that needs to be addressed before I close the issue, but that works too :P.
