### ISSUE TITLE
Bump golang version to 1.20.13 and 1.21.6

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17269]
### What would you like to be added?

- Bump golang version to 1.20.13 for 3.5 and 3.4
- Bump golang version to 1.21.6 for main

### Why is this needed?

To improve stability

**Comment by jmhbnz** [comment]
Completion tracking below:

- [ ] `main`  
- [ ] `release-3.5`  (1.20.13) 
- [ ] `release-3.4`  (1.20.13) 
- [ ]  etcd-io `CHANGELOG` 
- [ ] `etcd-io/bbolt` `main`  
- [ ] `etcd-io/raft` `main`

**Comment by ivanvc** [comment]
Can you assign this to me? Thanks

**Comment by ahrtr** [comment]
All done. Thanks @ivanvc and @jmhbnz
