### ISSUE TITLE
Expose Backoff options in Client Config

### ISSUE THREAD

**Issue by dusk125** [etcd-io/etcd#17272]
### What would you like to be added?

Instead of hardcoding defaultUnaryMaxRetries, defaultBackoffWaitBetween, defaultBackoffJitterFraction Client.dialSetOpts, allow a user to provide values in the Client Config (while falling back to the defaults).

### Why is this needed?

The Kubernetes API server can fail to retry on slower platforms (non-default LEADER_ELECTION_TIMEOUT & HEARTBEAT_INTERVAL) with an "etcdserver: leader changed" error; it's possible, due to the increased timeout/heartbeat, to for the retries to fail since etcd is hardcoded to wait a maximum of 2.5s and will sometimes skip the retry wait time if there's quorum. This change would allow the retries/backoff to be configured to avoid this issue.

**Comment by dusk125** [comment]
I can take on this issue

**Comment by ahrtr** [comment]
I will close this ticket after you update the changelog for 3.5 (and probably 3.4 if you backport the fix to 3.4 as well).

**Comment by dusk125** [comment]
> I will close this ticket after you update the changelog for 3.5 (and probably 3.4 if you backport the fix to 3.4 as well).

@ahrtr would you like separate PRs for each of the changelog changes (main, 3.5, 3.4) or is it alright to combine them into a single PR?

**Comment by ahrtr** [comment]
> @ahrtr would you like separate PRs for each of the changelog changes (main, 3.5, 3.4) or is it alright to combine them into a single PR?

One PR please. I think we only need to update changlog for 3.4 and 3.5.  Usually the changelog for main only contains items which are new in 3.6.

**Comment by ahrtr** [comment]
Yes, all done. Thanks
