### ISSUE TITLE
not able to clear alarm in etcd 3.5.3 version by using etcdctl alarm disarm command

### ISSUE THREAD

**Issue by rahulbapumore** [etcd-io/etcd#17318]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Alarm was raised on ETCD cluster, but later DB size got reduced lesser than ETCD_BACKEND_QUOTA_BYTE, but still cant put values into DB because Nospace alarm still exist and not cleared.
When We try to clear it using etcdctl alarm disarm command it logs timeout error inside the ogs

### What did you expect to happen?

Alarm should be cleared and data should be able to be inserted

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Etcd version (please run commands below)

ETCD version 3.5.3

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by rahulbapumore** [comment]
Hi @ahrtr ,
We faced this issue and blocking to insert data,  Any inputs for clearing the alarm?

Thanks

**Comment by ahrtr** [comment]
Please provide detailed steps to reproduce the issue. Or the detailed steps what you did.

**Comment by ahrtr** [comment]
Please ensure you have correctly compacted & defragmented the db, and finally disalarmed.

References:
- https://etcd.io/docs/v3.5/op-guide/maintenance/#space-quota
- https://etcd.io/blog/2023/how_to_debug_large_db_size_issue/

@Elbehery could you followup this ticket until it's closed?

**Comment by Elbehery** [comment]
On it 🙏🏽

**Comment by rahulbapumore** [comment]
Hi @elbehery ,
We think our issue is similar to  https://github.com/etcd-io/etcd/issues/14379 this ticket
Any workaround to resolve this issue by performing any procedure or steps?

Thanks

**Comment by ahrtr** [comment]
Please also double confirm whether you can still see this issue on latest release 3.5.11.

**Comment by rahulbapumore** [comment]
@Elbehery ,
Also etcdctl member list does not show any alarm
also etcdctl endpoint health does not show any alarm
but etcdctl endpoint status --write-out=table shows nospace alarm in output

**Comment by Elbehery** [comment]
@rahulbapumore 

can you please give details how to reproduce ? 

also can u paste some logs ?

**Comment by rahulbapumore** [comment]
Can deleting wal folder will resolve this issue?
@Elbehery

**Comment by Elbehery** [comment]
did you try to restart the etcd pod on the node which raised the alarm ? 

so when the pod will start, it will re-read the snapshot and the wal,  this might help

**Comment by Elbehery** [comment]
@rahulbapumore ^^

**Comment by rahulbapumore** [comment]
Yes I tried deleting pods but same issue

**Comment by Elbehery** [comment]
can u upgrade to the latest release ?? 

also please describe the environment you use, and if some logs are available would be gr8

**Comment by rahulbapumore** [comment]
Hi @Elbehery ,
By upgrading this will alarm issue get resolved?

**Comment by rahulbapumore** [comment]
We are using ETCD inside kubernetes pods controlled by statefulset.
We will try to get logs and provide you

**Comment by rahulbapumore** [comment]
> Hi @Elbehery , By upgrading will alarm issue get resolved?

anything on this?

**Comment by Elbehery** [comment]
i really cant help without logs


did u try restarting the node that caused the alarm ?
