### ISSUE TITLE
Document pre-vote flag

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17328]
### What would you like to be added?

Current flag documentation in command line:
```
  --pre-vote 'true'
    Enable to run an additional Raft election phase.
```

From the original PR https://github.com/etcd-io/etcd/pull/9352

### Why is this needed?

Users are not aware of this feature https://github.com/etcd-io/etcd/issues/17326. Expect lack of proper documentation is the main reason.

**Comment by UtkarshUmre** [comment]
@serathius What needs to be done to resolve this issue?Is this a good first issue?

**Comment by UtkarshUmre** [comment]
I understand, and I will look more into this before raising a pull request soon. Where can I find more information about the Raft protocol?

**Comment by serathius** [comment]
https://raft.github.io/raft.pdf

**Comment by shreemaan-abhishek** [comment]
I would like to take this up.
