### ISSUE TITLE
Should verify&migrate storage version when received snapshot from other members

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17361]
### What would you like to be added?

If I remember correctly I implemented storage migration to be executed during etcd bootstrap. However etcd storage can be swapped during runtime. When member is too behind from leader it will download snapshot from it.  This creates a risk that leader and follower use different etcd version. 

TODO:
* Run migrate on db file everytime we reload it (including when downloading from other members)
* Add a test case where member downloads snapshots from other member using different minor version. Both higher and lower. Validate if the resulting storage version matches the member.

### Why is this needed?

To ensure storage downgrade works correctly for snapshots sent between members

**Comment by siyuanfoundation** [comment]
In [`monitorStorageVersion`](https://github.com/etcd-io/etcd/blob/0bd7008eea49b668042fea89a4b4e9926fa5518e/server/etcdserver/server.go#L2248) , `UpdateStorageVersion` would be run if there is a change in cluster version. 
Inside [`UpdateStorageVersion`](https://github.com/etcd-io/etcd/blob/0bd7008eea49b668042fea89a4b4e9926fa5518e/server/etcdserver/adapters.go#L80), the schema would be migrated if necessary. 
When downgrade is enabled, the storage version would always be downgraded first. So in theory, no snapshot higher than the target version would be sent. 

So @serathius is it still necessary to run migrate on db file everytime we reload it?

**Comment by siyuanfoundation** [comment]
Talked with Marek offline. 
For the snapshot migration, it works in normal downgrade scenarios. But for the edge cases like a new member is added between setting cluster version and storage version, a higher version snapshot can still be sent to the new member. We need to consider all the edge cases to ensure the robustness of the downgrade process.

**Comment by serathius** [comment]
I just remembered, what about upgrade cases.

**Comment by siyuanfoundation** [comment]
> I just remembered, what about upgrade cases.

During upgrade, the storage version would be updated only when the cluster version has been upgraded, which means when all the members have been upgraded to the higher version.

**Comment by serathius** [comment]
Done as part of @siyuanfoundation work on downgrade to from v3.5 to v3.4
