### ISSUE TITLE
ETCD throwing context dealine exceeded continuously and it started suddenly 

### ISSUE THREAD

**Issue by rahulbapumore** [etcd-io/etcd#17364]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

ETCD v3.5.7 is installed in container of kubernetes pod controlled by statefulset and it has only one replica. this deployment works fine for few days(2-3), but suddenly etcd starts throwing context deadline error, no etcdctl command works. When tried to recover this deployment, we tried to delete wal and snap file (but not db file), it doesnt  get recovered. But as soon as we delete db file , etcd starts again without an issue. Our primary suspect is db is being corrupted automatically or somehow. But This corruption in db is very risky loosing all data. Do you know how to recover from this? We didnt find much from logs, just keeps printing context deadline exceeded.

[filetoupload.txt](https://github.com/etcd-io/etcd/files/14149668/filetoupload.txt)

### What did you expect to happen?

Etcd to not go in unhealthy state

### How can we reproduce it (as minimally and precisely as possible)?

it happens out of sudden

### Anything else we need to know?

when we exported ETCDCTL_API=2 env variable and then run etcdctl command, we got below error ->

client: etcd cluster is unavailable or misconfigured; error #0: unsupported protocol scheme "eddc.namespace1"

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

etcdctl commands re not working

**Comment by rahulbapumore** [comment]
[anotherfiletoupload.txt](https://github.com/etcd-io/etcd/files/14150013/anotherfiletoupload.txt)
These are the logs after deleting pod

**Comment by rahulbapumore** [comment]
@elbehery

**Comment by rahulbapumore** [comment]
Hi @ahrtr ,
Any inputs on this?

**Comment by ahrtr** [comment]
> throwing context deadline error, no etcdctl command works. When tried to recover this deployment, we tried to delete wal and snap file (but not db file)

It's confusing why you tried to delete the WAL AND snapshot files instead of checking the environment (e.g. networking) on context deadline error.

**Comment by rahulbapumore** [comment]
Hi @ahrtr ,
We are not using v2 API, all etcdctl commands were faiiling for v3 API, so just trial purpose we exported ETCDCTL_API to v3 and it gave some meaningful error message
$export ETCDCTL_API=2
$ etcdctl member list
client: etcd cluster is unavailable or misconfigured; error #0: unsupported protocol scheme "edce.namespace1"

**Comment by rahulbapumore** [comment]
And also why we delete snap and wal because,
no etcdctl command was working, etcd was not accepting traffic, and we just tried to recover system by deleting wal and snap..
But didnt help.
But when we deleted db file then etcd started normally by loosing data.

**Comment by rahulbapumore** [comment]
Hi @ahrtr ,
If its networking related issue and not an etcd issue then how after deleting db file inside member/snap folder, etcd started working fine.
How its networking related issue, because after deleting db file etcd recovered and there is single replica only.
Do you by any chance think that its something related to db corruption?
Any process to check db is corrupt? No etcdctl commands work so not sure command will help...Apart from commands can we check really db is corrupted?
And Any root cause to get  into issue?

**Comment by ahrtr** [comment]
> Any process to check db is corrupt?

Please try bbolt check command. https://github.com/etcd-io/bbolt/blob/4d74483f9b108a4154e2ea5366e31838ed57779c/cmd/bbolt/main.go#L127

Closing as I do not see any etcd issue. Please raise your question in the https://github.com/etcd-io/etcd/discussions next time you have any questions.

**Comment by rahulbapumore** [comment]
Hi @ahrtr ,
Few questions we have - 
1 . We ran bbolt check command inside the container , it did not print anything simply returned the terminal prompt - 
Then we performed bbolt check command on healthy deployment  multiple times and we saw that sometimes it prints Ok after completing command, but sometimes it doesnt print anything. So is this bbolt check command reliable always?
2. Coming to unhealthy deployment, we observed one behavior that when we run etcdctl command then etcd is killed automatically and pod goes in crashloopbackoff , because etcd not able to start and killed automatically failing the liveness probe.

Please help us with these queries

Thanks
