### ISSUE TITLE
`TestPeriodicPause` failed 

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17391]
### Which github workflows are flaking?

pull-etcd-unit-test

### Which tests are flaking?

TestPeriodicPause

### Github Action link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/etcd-io_etcd/17380/pull-etcd-unit-test/1755235191778971648

### Reason for failure (if possible)

```
{Failed  === RUN   TestPeriodicPause
    periodic_test.go:167: len(actions) = 0, expected >= 1
--- FAIL: TestPeriodicPause (0.54s)
}
```

**Comment by ahrtr** [comment]
@dusk125 do you have bandwidth to take a look at this flaky test? thx

**Comment by ahrtr** [comment]
See a similar error on test case `TestPeriodicMinutes`

```
{Failed  === RUN   TestPeriodicMinutes
    logger.go:130: 2024-02-07T19:14:01.529Z	INFO	starting auto periodic compaction	{"revision": 1, "compact-period": "5m0s"}
    logger.go:130: 2024-02-07T19:14:01.539Z	INFO	completed auto periodic compaction	{"revision": 1, "compact-period": "5m0s", "took": "30s"}
    logger.go:130: 2024-02-07T19:14:01.658Z	INFO	starting auto periodic compaction	{"revision": 10, "compact-period": "5m0s"}
    logger.go:130: 2024-02-07T19:14:01.658Z	INFO	completed auto periodic compaction	{"revision": 10, "compact-period": "5m0s", "took": "0s"}
    logger.go:130: 2024-02-07T19:14:01.809Z	INFO	starting auto periodic compaction	{"revision": 20, "compact-period": "5m0s"}
    periodic_test.go:122: len(actions) = 0, expected >= 1
--- FAIL: TestPeriodicMinutes (0.48s)
}
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/etcd-io_etcd/17393/pull-etcd-unit-test/1755308321516032000

**Comment by jmhbnz** [comment]
Closing, flakes in period tests were addressed in https://github.com/etcd-io/etcd/pull/18608. Testgrid shows green for both `amd64` and `arm64` for all recent runs.
