### ISSUE TITLE
Ephemeral nodes?

### ISSUE THREAD

**Issue by derekchiang** [etcd-io/etcd#174]
ZooKeeper supports the creation of "ephemeral znodes", which are znodes (key-value pairs in etcd parlance) that are automatically deleted when the session that creates them terminates, either deliberately or due to a failure.  Do you guys think this feature is worth adding to etcd?

I'm bringing this up because I'm working on [a set of sync primitives](https://github.com/derekchiang/etcdplus), and some of them could be implemented more easily if there was this feature.  For example, in implementing distributed locks, I have to make sure that if a node dies when holding a lock, the lock gets deleted.  The way I'm doing this right now is to set TTL for the lock file and reset the file periodically, so that if the node dies the lock file will also disappear after some time.  However if etcd supported ephemeral keys, I would just make the lock file ephemeral, so that if the node dies the lock file automatically gets deleted.

There are many other potential applications of this feature of course; this is just an example.

**Comment by jolestar** [comment]
+1

**Comment by philips** [comment]
The etcd v3 API will add the concept of a lease. When the lease ttl expires multiple keys can be deleted. See https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

We have an early preview of the v3 API in the latest [etcd v2.2 release](https://github.com/coreos/etcd/releases) but leases haven't been implemented yet.

Please let us know if leases solve your use case @jolestar @m1ch1 @derekchiang @banks @kjeet
