### ISSUE TITLE
[etcd-3.5] godoc-export fails

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#17400]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I ran `GOARCH=arm64 PASSES="fmt bom dep" ./test.sh`

### What did you expect to happen?

Tests should successfully pass.

### How can we reproduce it (as minimally and precisely as possible)?

Pull down the latest `release-3.5` branch and run `GOARCH=arm64 PASSES="fmt bom dep" ./test.sh` from the root of the folder.

### Anything else we need to know?

I think it can be fixed by simply adjusting the comment: https://github.com/etcd-io/etcd/blob/ae7d49333a17633e9301966ff3144e7380edd65b/server/etcdserver/api/etcdhttp/health.go#L63

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.12
Git SHA: d0dcfd0e5
Go Version: go1.21.7
Go OS/Arch: darwin/arm64

$ etcdctl version
etcdctl version: 3.5.12
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
goword checking failed:
./etcd/server/etcdserver/api/etcdhttp/health.go.63: // HandleHealth registers metrics and health handlers for v2. (godoc-export: HandleHealth -> HandleHealthForV2?)
FAIL: 'goword' failed at Fri Feb  9 13:14:12 PST 2024
```

**Comment by ahrtr** [comment]
Thanks for raising this issue. Why our 3.5 workflow CI haven't complained this so far? Please consider to update the workflow CI to identify this issue firstly. 

cc @jmhbnz

**Comment by jmhbnz** [comment]
Agree we should be ensuring these issues are picked up by CI.

Based on the checks of the last merged PR into `release-3.5` it looks like we don't have a `make verify` style check happening on the release branch. There are probably a number of backports required.

The closest equivalent in `release-3.5` looks to be `make test-smoke` which runs `PASSES="fmt build unit" ./test.sh`.  That actually fails for me at the `shellcheck` step but if I comment that out I can recreate the issue with `goword` also failing.

@vivekpatani do you have any capacity to help tidy up these issues and backport the `make verify` recipe plus static analysis workflow to ensure stable release tests will run lint checks?

**Comment by ivanvc** [comment]
I think the issue is that the GitHub workflows don't have `fmt` in `PASSES` for the `release-3.5` branch. Running it locally these are the checks that are failing:

1. shellcheck
    ```
    % 'shellcheck' '-fgcc' 'build' 'test' 'scripts/build-release.sh' 'scripts/codecov_upload.sh' 'scripts/fix.sh' 'scripts/genproto.sh' 'scripts/install-marker.sh' 'scripts/release_mod.sh' 'scripts/test_images.sh' 'scripts/test_lib.sh' 'scripts/updatebom.sh' 'scripts/update_dep.sh' './build.sh' './test.sh'
    scripts/install-marker.sh:13:6: note: Double quote to prevent globbing and word splitting. [SC2086]
    ./build.sh:23:48: warning: This { is literal. Check expression (missing ;/\n?) or quote it. [SC1083]
    ./build.sh:23:49: warning: This { is literal. Check expression (missing ;/\n?) or quote it. [SC1083]
    ./build.sh:23:58: warning: This } is literal. Check expression (missing ;/\n?) or quote it. [SC1083]
    ./build.sh:23:59: warning: This } is literal. Check expression (missing ;/\n?) or quote it. [SC1083]
    ./build.sh:30:32: note: Double quote to prevent globbing and word splitting. [SC2086]
    ./build.sh:31:47: note: Double quote to prevent globbing and word splitting. [SC2086]
    ./build.sh:32:49: note: Double quote to prevent globbing and word splitting. [SC2086]
    ./build.sh:33:49: note: Double quote to prevent globbing and word splitting. [SC2086]
    ./build.sh:34:47: note: Double quote to prevent globbing and word splitting. [SC2086]
    ```
2. goword
    ```
    goword checking failed:
    .../etcd/server/etcdserver/api/etcdhttp/health.go.63: // HandleHealth registers metrics and health handlers for v2. (godoc-export: HandleHealth -> HandleHealthForV2?)
    FAIL: 'goword' failed at Mon Feb 12 09:12:02 PM PST 2024
    ```

3. revive
    ```
    'revive' started at Mon Feb 12 09:17:10 PM PST 2024
    % (cd tools/mod && 'go' 'install' 'github.com/mgechev/revive')
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:16:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/main.go:8:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:11:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/lint/package.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/formatter/friendly.go:10:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/rule/struct-tag.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/rule/cognitive-complexity.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    stderr: golang/1.21.5/packages/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:12:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
    stderr: go mod download go.etcd.io/gofail
    FAIL: (code:1):
      % (cd tools/mod && 'go' 'install' 'github.com/mgechev/revive')
    
    FAIL: 'run_go_tool github.com/mgechev/revive -config etcd/tests/revive.toml -exclude vendor/... ./...' checking failed (!=0 return code)
    FAIL: 'revive' failed at Mon Feb 12 09:17:10 PM PST 2024
   ```

Should we fix the issues and then enable the static analysis in a GitHub workflow? Addressing the lint issues should be straightforward and a good candidate for new contributors.

**Comment by ahrtr** [comment]
Thanks @ivanvc . 



> Should we fix the issues and then enable the static analysis in a GitHub workflow? Addressing the lint issues should be straightforward and a good candidate for new contributors.

Sounds good. Leave it to @jmhbnz to coordinate this. thx

**Comment by jmhbnz** [comment]
> Should we fix the issues and then enable the static analysis in a GitHub workflow? Addressing the lint issues should be straightforward and a good candidate for new contributors.

Absolutely.  We have a triage meeting coming up in a few days I'll make a few good first issue tasks to tidy things up.

**Comment by vivekpatani** [comment]
@ivanvc just to follow up with this, I think the first 2 issues I was able to reproduce and fix. The 3rd issue re: `revive` failing, I see you're using `go1.21.5`, can you repro this on `go1.21.6` which is what upstream uses. With `go1.21.6` I cannot seem to reproduce the issue. I'll submit a PR to fix the first two issues. Thanks.

CC: @ahrtr @jmhbnz

**Comment by vivekpatani** [comment]
All the relevant PRs in one place.

- https://github.com/etcd-io/etcd/pull/17439 - Pending Review.
- https://github.com/etcd-io/etcd/pull/17434 - Merged.
- https://github.com/etcd-io/etcd/pull/17433 - Merged.

**Comment by ahrtr** [comment]
It seems all PRs have been merged, can we close this issue?

**Comment by vivekpatani** [comment]
Yes, SGTM, thank you.
