### ISSUE TITLE
[etcd-3.5] tools/mod is not tidy

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#17401]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Once I fixed this [issue](https://github.com/etcd-io/etcd/issues/17400)
and I run `GOARCH=arm64 PASSES="fmt bom dep" ./test.sh`

### What did you expect to happen?

The test should successfully pass.

### How can we reproduce it (as minimally and precisely as possible)?

execute `GOARCH=arm64 PASSES="fmt bom dep" ./test.sh`

### Anything else we need to know?

The fix seems easy enough
- navigate to the `tools/mod`
- execute `go mod tidy`

Then run `GOARCH=arm64 PASSES="fmt bom dep" ./test.sh`

### Etcd version (please run commands below)

<details>

$ etcd --version
etcd Version: 3.5.12
Git SHA: d0dcfd0e5
Go Version: go1.21.7
Go OS/Arch: darwin/arm64

$ etcdctl version
etcdctl version: 3.5.12
API version: 3.5
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
'revive' started at Fri Feb  9 13:23:02 PST 2024
% (cd tools/mod && go install github.com/mgechev/revive)
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:16:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/main.go:8:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:11:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/lint/package.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/formatter/friendly.go:10:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/rule/struct-tag.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/rule/cognitive-complexity.go:9:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail
FAIL: (code:1):
  % (cd tools/mod && go install github.com/mgechev/revive)
stderr: /go/pkg/mod/github.com/mgechev/revive@v1.0.2/config.go:12:2: go.etcd.io/gofail@v0.1.0: missing go.sum entry for go.mod file; to add it:
stderr: go mod download go.etcd.io/gofail

FAIL: 'run_go_tool github.com/mgechev/revive -config /etcd/tests/revive.toml -exclude vendor/... ./...' checking failed (!=0 return code)
FAIL: 'revive' failed at Fri Feb  9 13:23:02 PST 2024
```

**Comment by ahrtr** [comment]
PLease make sure your local go version is consistent with https://github.com/etcd-io/etcd/blob/release-3.5/.go-version#L1

**Comment by ahrtr** [comment]
thx for the info. We need to bump the go version to 1.21.7 for 3.4 & 3.5 (and probably main for now before 1.22.1 is released), and fix this together with the golang version bumping.

**Comment by vivekpatani** [comment]
https://github.com/etcd-io/etcd/pull/17439 - closing this issue in favour of https://github.com/etcd-io/etcd/issues/17401 to avoid duplication, and tracking can exist in one single place. Thank you.
