### ISSUE TITLE
Make CGO_ENABLED Configurable

### ISSUE THREAD

**Issue by ArkaSaha30** [etcd-io/etcd#17419]
### What would you like to be added?

The value of `CGO_ENABLED` is hard-coded to `0`. I would want to make `CGO_ENABLED` optionally configurable by passing an environment variable during runtime. When no environment variable is passed it will default to `0` therefore keeping the build process intact as defined in the script.

Ref: https://github.com/etcd-io/etcd/pull/17418

### Why is this needed?

`CGO_ENABLED` is an important Environment Variable required during Go compilation and build process. Making it configurable will allow consumers to build etcd as per their requirements, specifically I have come across FIPS compilation requirement which requires the `CGO_ENABLED=1`.  The suggested PR will not hinder the existing build process but allow users to configure `CGO_ENABLED` environment variable as per their requirement.

**Comment by ahrtr** [comment]
@ArkaSaha30 Please add a changelog for both 3.5 and 3.4. thx

**Comment by ahrtr** [comment]
All done.
