### ISSUE TITLE
etcd high cpu usage

### ISSUE THREAD

**Issue by TheHippo** [etcd-io/etcd#1742]
I'm currently trying out CoreOS with 3 virtual machines via Virtual Box and found out, that the cpu usage for `etcd` grows over time. (From 35% to 90% over the course of half an hour.) This seem to be happening regardless of the CoreOS update channel I use. 

I'm not an expert with etcd, but I'm willing to provide addional data if this helps solve this issue.

**Comment by mlazarov** [comment]
I do have the same problem. The "fix" just makes the coreos cluster more stable (i.e. not electing new master every second), but still the etcd daemon takes 80-90% of one core

![screen shot 2015-03-18 at 23 14 12](https://cloud.githubusercontent.com/assets/976139/6719625/93a0b782-cdc4-11e4-9eae-26950496308a.png)

Currently the server is brand new - without any docker instances:

```
core@core-01 ~ $ fleetctl list-units
UNIT	MACHINE	ACTIVE	SUB
core@core-01 ~ $ fleetctl list-unit-files
UNIT	HASH	DSTATE	STATE	TARGET
core@core-01 ~ $
```

**Comment by yichengq** [comment]
@mlazarov We have moved to 2.0.5, and gonna release it on CoreOS very soon. Please give it a try, and it should be much stable.

**Comment by oguzbilgic** [comment]
Same issue on `coreos-stable-633-1-0-v20150414 `

**Comment by TheHippo** [comment]
@oguzbilgic Open an new issue if this problem still exists.

**Comment by dminkovsky** [comment]
I'm experiencing this problem. Had lots of logging about elections, so I wiped the data dir, thinking perhaps etcd keeps trying to reelect with old, non-extant peers. Now the logging has stopped, but etcd is still at 95% CPU. 

Not sure why a new issue needs to be opened when this issue and #868 were closed without any concrete resolution steps.
