### ISSUE TITLE
Unix Sockets broken for AdvertiseClientUrls and AdvertisePeerUrls

### ISSUE THREAD

**Issue by NHAS** [etcd-io/etcd#17443]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When trying to start an ETCd member with a unix socket for advertise peer url, or client urls the address is not accepted and required the url to be in `host:port` format.

```bash
etcd --name server0 --initial-advertise-peer-urls unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-peer-urls unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-client-urls http://127.0.0.1:2480 \
  --advertise-client-urls http://127.0.0.1:2380 \
  --initial-cluster-token wag-test \
  --initial-cluster server0=unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test
  
  invalid value "unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test" for flag -initial-advertise-peer-urls: URL address does not have the form "host:port": unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test
Usage:

<omitted>
  ```

### What did you expect to happen?

To be able to create a unix socket at any file location without requirement for the format `host:port`

### How can we reproduce it (as minimally and precisely as possible)?

```bash
etcd --name server0 --initial-advertise-peer-urls unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-peer-urls unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-client-urls http://127.0.0.1:2480 \
  --advertise-client-urls http://127.0.0.1:2380 \
  --initial-cluster-token wag-test \
  --initial-cluster server0=unix:///tmp/c139ad0d297f3e31eb4e517e7822aa64/test
  ```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
3.5.12

$ etcdctl version
3.5.11
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

etcd --name server0 --initial-advertise-peer-urls unix:///tmp/wag-c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-peer-urls unix:///tmp/wag-c139ad0d297f3e31eb4e517e7822aa64/test \
  --listen-client-urls http://127.0.0.1:2480 \
  --advertise-client-urls http://127.0.0.1:2380 \
  --initial-cluster-token wag-test \
  --initial-cluster server0=unix:///tmp/wag-c139ad0d297f3e31eb4e517e7822aa64/test

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

N/A

</details>

**Comment by ahrtr** [comment]
Unfortunately, the PR, which fixes issue, hasn't been merged.

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/etcd/pull/15940, which will be included in 3.5.13

Please try the `main` branch or `release-3.5`

**Comment by Matviy** [comment]
I don't believe that this has been fully resolved:

```shell
./etcd --listen-client-urls=unix:///tmp/socket \
       --advertise-client-urls=unix:///tmp/socket
       
{"level":"warn","ts":"2024-09-04T12:32:54.642135-0700","caller":"embed/config.go:687","msg":"Running http and grpc server on single port. This is not recommended for production."}
{"level":"info","ts":"2024-09-04T12:32:54.642234-0700","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["./etcd","--listen-client-urls=unix:///tmp/socket","--advertise-client-urls=unix:///tmp/socket"]}
{"level":"warn","ts":"2024-09-04T12:32:54.642252-0700","caller":"etcdmain/etcd.go:75","msg":"failed to verify flags","error":"--advertise-client-urls \"unix:///tmp/socket\" must be \"host:port\" (missing port in address)"}


```

**Comment by SalehBorhani** [comment]
It does not make sense to start the server on an HTTP port and then connect it with a Unix port. However, we cannot connect to the server listening on a Unix port. We need to change the code to address this issue. I think below are the necessary code changes:

server/embed/config.go (In Validate function on line 698)
```
	if err := checkBindURLs(cfg.AdvertiseClientUrls); err != nil {
		return err
	}
```
I replaced this if block with the current block and then run the below command

For Server
```
./bin/etcd --listen-peer-urls=unix:///tmp/etcd.sock --listen-client-urls=unix:///tmp/etcd.sock --advertise-client-urls=unix:///tmp/etcd.sock
```

For Client
```
./bin/etcdctl --endpoints=unix:///tmp/etcd.sock put name <name>
```
