### ISSUE TITLE
`TestPeriodicSkipRevNotChange` failed

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17487]
### Which Github Action / Prow Jobs are flaking?

pull-etcd-unit-test

### Which tests are flaking?

TestPeriodicSkipRevNotChange

### Github Action / Prow Job link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/etcd-io_etcd/17486/pull-etcd-unit-test/1761691393031409664

### Reason for failure (if possible)

```
{Failed  === RUN   TestPeriodicSkipRevNotChange
    logger.go:130: 2024-02-25T09:58:05.625Z	INFO	starting auto periodic compaction	{"revision": 101, "compact-period": "5m0s"}
    logger.go:130: 2024-02-25T09:58:05.636Z	INFO	completed auto periodic compaction	{"revision": 101, "compact-period": "5m0s", "took": "30s"}
    logger.go:130: 2024-02-25T09:58:06.574Z	INFO	starting auto periodic compaction	{"revision": 102, "compact-period": "5m0s"}
    periodic_test.go:233: len(actions) = 0, expected >= 1
--- FAIL: TestPeriodicSkipRevNotChange (1.15s)
}
```

**Comment by Rajalakshmi-Girish** [comment]
@ahrtr seems like related to https://github.com/etcd-io/etcd/issues/17054

**Comment by ghouscht** [comment]
I assume this is not yet fixed, right? At least for me this test has a high fail percentage when I run the test with `stress` (~2.4% across 5k runs).

Increasing the timeout from:
https://github.com/etcd-io/etcd/blob/2c971109267d9d29ef7cb901148931bdbd55762a/server/etcdserver/api/v3compactor/periodic_test.go#L183

to the following values yields:

- 15ms - 0.1% failures (5k runs)
- 20ms - 0 failures (5k runs)

Anyway the 10ms timeout seems like an arbitrary value to me, or is there a reason it is set to 10ms? If it is an arbitrary value we could as well increase it to 20ms to make the test stable or remove the timeout?

**Comment by ahrtr** [comment]
> * 20ms - 0 failures (5k runs)

Thanks. I do not get time digging into the test case. But I suppose that just changing the timeout from 10ms to 20ms won't change the logic of the test case. So no objection to increase the timeout to 20ms.

**Comment by ghouscht** [comment]
> > * 20ms - 0 failures (5k runs)
> 
> Thanks. I do not get time digging into the test case. But I suppose that just changing the timeout from 10ms to 20ms won't change the logic of the test case. So no objection to increase the timeout to 20ms.

👍🏻 I'm not super familiar with the compaction logic but I think for this test the timeout is not relevant. I'll open a PR.

/assign
