### ISSUE TITLE
Flaking `TestLeaseGrantKeepAliveOnce`

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17506]
### Which Github Action / Prow Jobs are flaking?

[arm64 / test (linux-arm64-integration-1-cpu)](https://github.com/etcd-io/etcd/actions/runs/8079188344/job/22073062387#logs)

### Which tests are flaking?

TestLeaseGrantKeepAliveOnce

### Github Action / Prow Job link

https://github.com/etcd-io/etcd/actions/runs/8079188344/job/22073062387

### Reason for failure (if possible)

```
    lease_test.go:180: 
        	Error Trace:	/home/runner/actions-runner/_work/etcd/etcd/tests/common/lease_test.go:180
        	            				/home/runner/actions-runner/_work/etcd/etcd/tests/framework/testutils/execute.go:38
        	            				/home/runner/actions-runner/_work/_tool/go/1.21.6/arm64/src/runtime/asm_arm64.s:1197
        	Error:      	"2" is not greater than "9223372036"
        	Test:       	TestLeaseGrantKeepAliveOnce/PeerAutoTLS
```

**Comment by serathius** [comment]
Keeping open for backport

**Comment by ahrtr** [comment]
Please also update the changelog. thx

**Comment by fuweid** [comment]
@ahrtr changelog change is here #17718. FYI

**Comment by ahrtr** [comment]
> @ahrtr changelog change is here #17718. FYI

Thanks. Please rebase that PR and resolve the comment, then I will merge it.
