### ISSUE TITLE
Etcd not respond to progress notification on newly created watch RPC until there is a event in a watch

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17507]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When trying make K8s depend on progress notification I found an broken edge case when working on https://github.com/kubernetes/kubernetes/pull/123513

What I found is that https://github.com/etcd-io/etcd/pull/15237 introduced a bug with `deferredProgress` logic.

If a progress request is send when watch [is not synced](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/storage/mvcc/watchable_store.go#L491-L495) (like when it's just newly created watch), etcd [mark progress notification as deferred](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/etcdserver/api/v3rpc/watch.go#L375), and [stop responding to progress notification request](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/etcdserver/api/v3rpc/watch.go#L371). 

Progress notification can be [later restored](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/etcdserver/api/v3rpc/watch.go#L486-L490) but only if there is an event to be sent. So if there is no event observed in the watch, etcd will never respond to progress notification requests.

### What did you expect to happen?

Don't expect event to arrive, send the progress notification when watchers become synced. 

### How can we reproduce it (as minimally and precisely as possible)?

Take PR.

Run make test WHAT=./vendor/k8s.io/apiserver/pkg/storage/... GOFLAGS="-v" KUBE_TEST_ARGS='--count 10 --run TestListWithListFromCache --failfast'

### Etcd version (please run commands below)

Reproduced on v3.5.10 embedded server

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Note, I don't expect this to be a super impactful thing, however definitely a blocker for Kubernetes to adopt and depend on manually requested progress notifications.

**Comment by ahrtr** [comment]
> What I found is that #15237 introduced a bug with `deferredProgress` logic.
> 
> If a progress request is send when watch [is not synced](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/storage/mvcc/watchable_store.go#L491-L495) (like when it's just newly created watch), etcd [mark progress notification as deferred](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/etcdserver/api/v3rpc/watch.go#L375), and [stop responding to progress notification request](https://github.com/etcd-io/etcd/blob/e68afe7eb7ce3e5f83deb2a8ad58faa3b35494b9/server/etcdserver/api/v3rpc/watch.go#L371).

Did not dig into the source code yet. But based on your input, It should be expected behaviour. I do not see any issue here. The progress notification events shouldn't be sent out until all events up to a revision have been already delivered. It's exactly what the [Bookmarkable](https://etcd.io/docs/v3.6/learning/api_guarantees/#watch-apis) means. Please let me know if I misunderstood your point.




> Take PR.
> 
> Run make test WHAT=./vendor/k8s.io/apiserver/pkg/storage/... GOFLAGS="-v" KUBE_TEST_ARGS='--count 10 --run TestListWithListFromCache --failfast'

Please do not expect every etcd contributor is familiar with K8s test case or has time to dig into K8s test case.  Please create an dedicated etcd test case to clearly clarify the issue if you still think it's an etcd issue.

**Comment by ahrtr** [comment]
Can we close this ticket?

**Comment by ahrtr** [comment]
> No, this is a big issue that blocks usage of manual progress notification in K8s.

What issue? Let me know if you have comment on https://github.com/etcd-io/etcd/issues/17507#issuecomment-1971043103

**Comment by ahrtr** [comment]
I already read your description, as I mentioned in https://github.com/etcd-io/etcd/issues/17507#issuecomment-1971043103, it's expected behaviour.

> I do not see any issue here. The progress notification events shouldn't be sent out until all events up to a revision have been already delivered. It's exactly what the [Bookmarkable](https://etcd.io/docs/v3.6/learning/api_guarantees/#watch-apis) means. Please let me know if I misunderstood your point.
