### ISSUE TITLE
Custom rpc fail fast policy at client side

### ISSUE THREAD

**Issue by finefuture** [etcd-io/etcd#17511]
### What would you like to be added?

Add a property in config: failfast

### Why is this needed?

In the scenario where we use domain names, if the domain name resolves to an incorrect address, etcd client requests will be stuck and no exception will be thrown to terminate the request, which will cause goroutine to get stuck.
Therefore, I would like to have the client customize the fail fast strategy so that errors can be quickly thrown when the above scenarios occur.

**Comment by ahrtr** [comment]
Using a context with a deadline should be able to resolve this problem.

**Comment by finefuture** [comment]
Okay, I've solved the problem. Thank you.
