### ISSUE TITLE
etcdctl put --ignore-value causes error (InvalidArgument)

### ISSUE THREAD

**Issue by 48656c6c6f** [etcd-io/etcd#17516]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

x@dev1:/etc/default$ ETCDCTL_API=3 etcdctl --endpoints=192.168.0.100:2379 put members/192.168.0.100 --ignore-value
{"level":"warn","ts":"2024-03-04T08:59:29.148005Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001a0000/192.168.0.100:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: key not found"}
Error: etcdserver: key not found

x@dev1:/etc/default$ ETCDCTL_API=3 etcdctl --endpoints=192.168.0.100:2379 put members/192.168.0.100 foo
OK
brian@dev1:/etc/default$

### What did you expect to happen?

I expected a return of "OK" as with the example that provides a value.

### How can we reproduce it (as minimally and precisely as possible)?

ETCDCTL_API=3 etcdctl --endpoints=192.168.0.100:2379 put members/192.168.0.100 --ignore-value

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

etcd Version: 3.5.10
Git SHA: 0223ca52b
Go Version: go1.20.10
Go OS/Arch: linux/amd64

$ etcdctl version
# paste output here
```

etcdctl version: 3.5.10
API version: 3.5

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

+------------------+---------+------+-----------------------+--------------------------+------------+
|        ID        | STATUS  | NAME |      PEER ADDRS       |       CLIENT ADDRS       | IS LEARNER |
+------------------+---------+------+-----------------------+--------------------------+------------+
| 8e9e05c52164694d | started | dev1 | http://localhost:2380 | http://192.168.0.100:2379 |      false |
+------------------+---------+------+-----------------------+--------------------------+------------+

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```
+-------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|     ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 192.168.0.100:2379 | 8e9e05c52164694d |  3.5.10 |   37 kB |      true |      false |         7 |        157 |                157 |        |
+-------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

</details>

**Comment by ahrtr** [comment]
`--ignore-value` means: updates the key using its current value. It requires that the key should be exist.

Refer to https://github.com/etcd-io/etcd/tree/main/etcdctl#put-options-key-value

**Comment by 48656c6c6f** [comment]
Okay, why the inconsistency between the API and the expectations of etcdctl?
