### ISSUE TITLE
Bump golang version to 1.21.8

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#17533]
### What would you like to be added?

While working on another PR, I noticed several CVEs in the dependencies, some of which were addressed in Go 1.21.8, released today.

List of CVEs fixed in 1.21.8:
* https://pkg.go.dev/vuln/GO-2024-2600
* https://pkg.go.dev/vuln/GO-2024-2599
* https://pkg.go.dev/vuln/GO-2024-2598
* https://pkg.go.dev/vuln/GO-2024-2610

### Why is this needed?

To address the published vulnerabilities.

**Comment by ahrtr** [comment]
Please also update the changelog for both 3.4 and 3.5. Thanks.

**Comment by ivanvc** [comment]
I opened two PRs to address bbolt and raft.

**Comment by ahrtr** [comment]
> I opened two PRs to address bbolt and raft.

Please read https://github.com/etcd-io/etcd/issues/17348#issuecomment-1980562728
