### ISSUE TITLE
Setup a pool of candidates for etcd releases

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17581]
### What would you like to be added?

Currently there are two release managers (@ahrtr and @serathius ), for 3.4 and 3.5 respectively. Both of us are also sig-etcd tech leads. We may be busy with different kinds of issues/PRs. So I am proposing to setup a pool of candidates for etcd releases.

Since there are permission & credentials to be shared, so the candidate only limit to etcd maintainers and sig-etcd leads.

I will provide detailed guide on how to release 3.4.x, and also I am happy to work with any candidate to get 3.4.31 released this week. @jmhbnz @serathius @spzala @wenjiaswe 

Actions:
- Add candidate into project `etcd-development` in google cloud;
- Provide detailed release guides (I will provide guide on how to release 3.4.x)
- Guide one candidate to get 3.4.31 released this week.

### Why is this needed?

- To get all etcd maintainers & sig-etcd leads share the responsibility for etcd's release
- To avoid the release to be blocked by any single release manager

**Comment by ahrtr** [comment]
> * Add candidate into project `etcd-development` in google cloud;

@ahrtr , @serathius and @wenjiaswe have already been added, so we just need to add @jmhbnz and @spzala .

**Comment by jmhbnz** [comment]
I would like to suggest we also consider release shadows at some point also.  

These would be community members who are actively contributing at the `member` or `reviewer` level who are not currently sig-etcd leads so won't have the permissions to actually cut the release.

While these community members won't have access, I think we should invite perhaps two people per release to shadow the release process so they can be ready to step up and assist in future.

We don't have to do it for `3.4.31`.  This is a suggestion for longer term as we iterate on this 🙏🏻

**Comment by dims** [comment]
please do consider @chaochn47 as well for future roles etc.

**Comment by ahrtr** [comment]
> While these community members won't have access, I think we should invite perhaps two people per release to shadow the release process so they can be ready to step up and assist in future.

Actually the release process is a very simple process, there is nothing to learn & prepare. The only concern is about security (the credentials etc.) as mentioned above.

Talked with @jmhbnz offline, I will work with him to get 3.4.31 released during the KubeCon (next) week.

**Comment by spzala** [comment]
sgtm, thank @ahrtr !!

**Comment by wenjiaswe** [comment]
Sorry for being late to the party and thank you for adding me! I will join you guys @ahrtr @jmhbnz and shadow the 3.4.31 release at KubeCon next week:)
