### ISSUE TITLE
Robustness flake due to gofailpoint deactivation timeout

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17592]
### Which Github Action / Prow Jobs are flaking?

Test Robustness nightly

### Which tests are flaking?

TestRobustnessExploratory/Kubernetes/HighTraffic/ClusterOfSize3

### Github Action / Prow Job link

https://github.com/etcd-io/etcd/actions/runs/8314445428/job/22751625109

### Reason for failure (if possible)

2024-03-17T11:27:29.9104803Z     logger.go:130: 2024-03-17T11:27:29.907Z	INFO	goFailpoint deactivate failed	{"failpoint": "raftBeforeSave=sleep(1s)", "error": "Delete \"http://127.0.0.1:12381/raftBeforeSave\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

**Comment by jamshidi799** [comment]
Hi, I am interested in this issue and in general robustness issues but I don't know exactly what should I do. In addition to that, most robustness tests fail in my local environment because the qps is lower than what expected

**Comment by serathius** [comment]
Expect this was caused by https://github.com/etcd-io/gofail/issues/64

**Comment by henrybear327** [comment]
> Expect this was caused by [etcd-io/gofail#64](https://github.com/etcd-io/gofail/issues/64)

I am on it! :)

**Comment by serathius** [comment]
This was resolved. The root cause was fact that older etcd versions were using outdated gofail version.
