### ISSUE TITLE
etcd Pod Crashes Due to Unreleased Memory Allocation

### ISSUE THREAD

**Issue by NeethithevanR** [etcd-io/etcd#17669]
### What happened?

We are running an etcd pod with PVC storage. While the application is running, heap memory allocation continuously increases, and the allocated memory is not being released. This continuous increase in RAM usage causes the pod to crash when it runs out of RAM. Any guidance to fix this issue would be greatly appreciated.

### What did you expect to happen?

Etcd need to run continuously without rapid increase in RAM usage.

### How can we reproduce it (as minimally and precisely as possible)?
Runing Etcd pod with this image
`bitnami/etcd:latest`

### Etcd version (please run commands below)

<details>

```console
etcdctl version: 3.5.12
API version: 3.5
```
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
We don't support bitnami images. Please file an issue in https://github.com/bitnami/charts

**Comment by NeethithevanR** [comment]
@serathius , Thank you so much
