### ISSUE TITLE
Update configuration doc in 3.4 op-guide

### ISSUE THREAD

**Issue by siyuanfoundation** [etcd-io/etcd#17671]
### What would you like to be added?

There have been some new flags (such as `--next-cluster-version-compatible`) added to 3.4 and the [configuration doc](https://github.com/etcd-io/website/blob/main/content/en/docs/v3.4/op-guide/configuration.md) needs to be updated.

### Why is this needed?

To keep the documentation up to date.

**Comment by madihy** [comment]
Hi @siyuanfoundation,

I'd be happy to update the documentation for this.

**Comment by madihy** [comment]
Hi @siyuanfoundation, 

I opened up a PR over on the website repo to take care of the documentation for this.
