### ISSUE TITLE
Add Prow job to run periodic performance benchmarks

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#17754]
### What would you like to be added?

As part of #16467, create a Prow job that nightly runs the rw-benchmarks. Storing the results as an artifact so results can be processed later and have an idea of how the development is affecting the project's performance.

### Why is this needed?

To start collecting performance benchmarks to establish a project perspective on performance.

**Comment by jmhbnz** [comment]
Added to our tracking under https://github.com/etcd-io/etcd/issues/16467.

**Comment by serathius** [comment]
Thanks for integrating benchmarks into the prow, however I was hoping that we will do the work in semi order describe in https://github.com/etcd-io/etcd/issues/16467#issuecomment-1691326907, so before we start running periodic benchmark we agree on what to measure first.

**Comment by ivanvc** [comment]
This makes sense, @serathius; thanks for your input. @jmhbnz, should we regroup and formalize a proposal?

**Comment by jmhbnz** [comment]
> This makes sense, @serathius; thanks for your input. @jmhbnz, should we regroup and formalize a proposal?

Certainly. I am currently taking some time off to move house but will be returning to open source work 6th May and very keen to regroup when I return. Feel free to update https://github.com/etcd-io/etcd/issues/16467 with any thoughts in the interim and thanks again for your work getting these initial tests of prow for heatmaps running @ivanvc
