### ISSUE TITLE
Update scripts/test_lib.sh to include ./tools modules

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#17760]
### What would you like to be added?

As identified in #17751, `scripts/test_lib.sh` currently doesn't include go modules nested in `./tools`.

We need to update `module_dirs()` to include them.
 https://github.com/etcd-io/etcd/blob/fbda59186605b1c1a8fc06c6e65a33dcb98e2fbd/scripts/test_lib.sh#L168-L170

### Why is this needed?

Not having these nested modules in `test_lib.sh` makes them dodge some of our CI/CD workflows.

**Comment by ivanvc** [comment]
Refer to https://github.com/etcd-io/etcd/pull/17751#issuecomment-2044315424

**Comment by ivanvc** [comment]
@jmhbnz, is this a good first-issue candidate? Or not, as there may be additional work/discussion if the proper way of doing it is just adding the two new tools in the `module_dirs()`.

**Comment by jmhbnz** [comment]
> @jmhbnz, is this a good first-issue candidate? Or not, as there may be additional work/discussion if the proper way of doing it is just adding the two new tools in the `module_dirs()`.

I think it's pretty straightforward to update the script, added labels.  Thanks @ivanvc

**Comment by ivanvc** [comment]
Hi @zhenguozhang, Thanks for your interest in working on this task. However, it has already been assigned to @tico88612, who raised PR #17770. We're finalizing an active conversation on that PR to close this issue. At this moment, there are no more tasks required for this issue.

**Comment by zhenguozhang** [comment]
Thans for your reply, @ivanvc  I've been studying etcd for a while now, and I'm ready to start helping the etcd community by fixing some bugs and iterating on new features. I'll take a look at other issues to see if I can address them.

**Comment by ivanvc** [comment]
@zhenguozhang, no worries. Keep an eye out for issues with the good first issue and help wanted labels that don't have an assignee.
