### ISSUE TITLE
Drop Measure Test Flakiness

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17774]
### What would you like to be added?

https://github.com/etcd-io/etcd/actions/workflows/measure-test-flakiness.yaml consistently fails. 

Don't think we should fix it as we building a replacement.

Before removal we should ensure that replacement is working correctly and runs every day instead of once per week.

### Why is this needed?

We are migrating to https://github.com/etcd-io/etcd/actions/workflows/measure-testgrid-flakiness.yaml

**Comment by stackbaek** [comment]
I just checked our testgrid, but it looks like there the 2 tabs we check to create issues does not have any flakiness currently: 

<img width="999" alt="image" src="https://github.com/etcd-io/etcd/assets/974645/fba7106d-2967-4940-95e0-c1d3baa72d52">

Consulting [the recent workflow ouptut](https://github.com/etcd-io/etcd/actions/runs/8863559773/job/24337756005), it does seem to pull the data correctly for both periodic and presubmit tests. 

I think we can go ahead and deprecate `measure-test-flakiness.yaml`.

**Comment by stackbaek** [comment]
It looks like https://github.com/etcd-io/etcd/pull/17893 is already ongoing. Let's proceed with the PR.
