### ISSUE TITLE
Testing with kubernetes clsuter for branch main?

### ISSUE THREAD

**Issue by liangyuanpeng** [etcd-io/etcd#17784]
### What would you like to be added?

1. build the image from branch main and run etcd
2. deploy kubernetes with `kind` and config extra etcd to running etcd.

free feel to comment and i want to work for it if possible,Thanks.

### Why is this needed?

Simple e2e verification of branch main and kubernetes .

**Comment by serathius** [comment]
Don't think just running k8s will bring any value to etcd project, the contract between two projects is too complicated. We would need to run the full k8s compliance set suite for it to be useful, but then it would push on us burden of K8s test flakes.

Please see https://github.com/etcd-io/etcd/issues/15820 for the effort in that area.

**Comment by liangyuanpeng** [comment]
Thanks for explain,make sense.
