### ISSUE TITLE
Revision decreasing after panic during compaction

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17780]
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Failure in https://github.com/etcd-io/etcd/actions/runs/8659974818

![image](https://github.com/etcd-io/etcd/assets/5873433/8508b160-c2f7-49f1-85b8-9930a1132826)

### What did you expect to happen?

Revision doesn't decrease

### How can we reproduce it (as minimally and precisely as possible)?

Follow https://github.com/etcd-io/etcd/tree/main/tests/robustness#re-evaluate-existing-report to validate report from https://github.com/etcd-io/etcd/actions/runs/8659974818

Run `TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1` with failpoint `compactBeforeSetFinishedCompact=panic()`

### Anything else we need to know?

TODO:
* [x] Try to reproduce the issue
* [x] Try to reproduce the issue on amd64

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
Hmm, still no repro. Are we so unlucky that we hit a bit flip or broken machine?

**Comment by siyuanfoundation** [comment]
I was not able to repro it on my mac (arm64) with 500 runs and failpoint `compactBeforeSetFinishedCompact=panic()`

**Comment by chaochn47** [comment]
Not be able to download the log

<img width="1727" alt="image" src="https://github.com/etcd-io/etcd/assets/54131596/da282b08-88e0-419d-843f-a94f2a04982a">

The reproduce attempts on linux amd64 machine is also not successful. 

We need a persisted audit log to easily replay the traffic. Turn on `LogUnaryInterceptor` could be a good start.

**Comment by chaochn47** [comment]
Not be able to download the log

The reproduce attempts on linux amd64 machine is also not successful.

We need a persisted audit log to easily replay the traffic. Turn on LogUnaryInterceptor could be a good start.

**Comment by serathius** [comment]
I think we need to assume that this was a hardware issue. One last thing to confirm. Could someone check the bbolt file from the report? Would be a good sanity check that the revision decrease really happen.

**Comment by dims** [comment]
@serathius i was able to download and have shared it with Chao (took a few retries .. spotty networking)

**Comment by chaochn47** [comment]
<img width="1299" alt="image" src="https://github.com/etcd-io/etcd/assets/54131596/2abf0501-96cf-4028-aa0f-f6302405b9f7">

Somehow I cannot download from the github UI..

**Comment by chaochn47** [comment]
@serathius

**Comment by dims** [comment]
spoke too soon, multiple laptops, different browsers, same issue (zip corrupted)

**Comment by serathius** [comment]
Hmm, last 4 operations before crash were deletes. Defrag removes revisions on keys that were deleted. After restart etcd went back as far as the last put operation. I have a bad feeling about this.

**Comment by serathius** [comment]
Will try to increase number of deletes done.

**Comment by serathius** [comment]
cc @ahrtr

**Comment by chaochn47** [comment]
> Hmm, last 4 operations before crash were deletes. Defrag removes revisions in Key bucket for keys that were deleted. Etcd infers the last revision based on Key bucket. After restart etcd went back as far as the last put operation. I have a bad feeling about this. cc @ahrtr

Trying to interpret the statement, the difference between the db file key bucket layout and the recorded response is due to compact & defrag after resuming from the panic, right? 

But it does not make sense `deletion` returns response with revision 298 with key `/regstry/pods/default/o95Cz` but in the db file `298` corresponds to `/registry/pods/default/vZJa5`. Either the db file is wrong or the etcd responds with incorrect revision number to client. 

`297` is supposed to be deletion but appears to be a update in the db file. 

```
rev={main:301 sub:0}, value=[key "/registry/pods/default/HhKkd" | val "207" | created 112 | mod 301 | ver 2]
rev={main:300 sub:0}, value=[key "/registry/pods/default/E7Zuy" | val "209" | created 140 | mod 300 | ver 2]
rev={main:299 sub:0}, value=[key "/registry/pods/default/5Dtb4" | val "208" | created 251 | mod 299 | ver 2]
rev={main:298 sub:0}, value=[key "/registry/pods/default/vZJa5" | val "" | created 0 | mod 0 | ver 0]
rev={main:297 sub:0}, value=[key "/registry/pods/default/obin7" | val "200" | created 141 | mod 297 | ver 2]
```

```
if(mod_rev(/registry/pods/default/NYpLu)==30).
  then(delete("/registry/pods/default/NYpLu")).
  else(get("/registry/pods/default/NYpLu")) -> success(deleted: 1), rev:296

if(mod_rev(/registry/pods/default/obin7)==141).
  then(put("/registry/pods/default/obin7", "200")).
  else(get("/registry/pods/default/obin7")) -> success(ok), rev: 297

if(mod_rev(/regstry/pods/default/o95Cz)==133).
  then(delete("/registry/pods/default/o95Cz")).
  else(get("/registry/pods/default/o95Cz")) -> success(deleted: 1), rev: 298

if(mod_rev(/registry/pods/default/OWSx2)==137).
  then(delete("/registry/pods/default/OWSx2")).
  else(get("/registry/pods/default/OWSx2")) -> success(deleted: 1), rev: 299

if(mod_rev(/registry/pods/default/V8bKj)==53).
  then(delete("/registry/pods/default/V8bKj")).
  else(get("/registry/pods/default/V8bKj")) -> success(deleted: 1), rev: 300

if(mod_rev(/registry/pods/default/Z68rD)==156).
  then(delete("/registry/pods/default/Z68rD")).
  else(get("/registry/pods/default/Z68rD")) -> success(deleted: 1), rev: 301

Compact -> `scheduledCompactRev` was set to `301`
```

**Comment by ahrtr** [comment]
> Hmm, last 4 operations before crash were deletes. Defrag removes revisions in Key bucket for keys that were deleted. Etcd infers the last revision based on Key bucket. After restart etcd went back as far as the last put operation. I have a bad feeling about this. cc @ahrtr

The workflow doesn't have any problem. Compact + defragmentation won't remove the last revision, even it's a tombstone revision.




> But it does not make sense `deletion` returns response with revision 298 with key `/regstry/pods/default/o95Cz` but in the db file `298` corresponds to `/registry/pods/default/vZJa5`. Either the db file is wrong or the etcd responds with incorrect revision number to client.

The bbolt db file should be correct.

It looks like that the report isn't consistent with regards to revision 298. So it's a bug of the test itself?

- In client-1/watch.json
```
{"Events":[{"Type":"delete-operation","Key":"/registry/pods/default/o95Cz","Value":{"Value":"","Hash":0},"Revision":298,"IsCreate":false,"PrevValue":null}],"IsProgressNotify":false,"Revision":298,"Time":919365280},
```
- In client-3/watch.json
```
{"Request":{"Key":"/registry/pods/","Revision":298,"WithPrefix":true,"WithProgressNotify":true,"WithPrevKV":true},"Responses":[{"Events":[{"Type":"delete-operation","Key":"/registry/pods/default/vZJa5","Value":{"Value":"","Hash":0},"Revision":298,"IsCreate":false,"PrevValue":{"Value":{"Value":"91","Hash":0},"ModR    evision":94}}],"IsProgressNotify":false,"Revision":298,"Time":2073785080}
```
- In client-4/watch.json
```
"Request":{"Key":"/registry/pods/","Revision":298,"WithPrefix":true,"WithProgressNotify":true,"WithPrevKV":true},"Responses":[{"Events":[{"Type":"delete-operation","Key":"/registry/pods/default/vZJa5","Value":{"Value":"","Hash":0},"Revision":298,"IsCreate":false,"PrevValue":{"Value":{"Value":"91","Hash":0},"ModRevision":94}}
```

**Comment by serathius** [comment]
> It looks like that the report isn't consistent with regards to revision 298. So it's a bug of the test itself?

Report is be just a dump of request and events observed by client. Different events for the same revision in watch means that different watch request observed different results. This is expected if there was a issue with KV store, so we don't even validate watch as it's expect results will be broken.

**Comment by serathius** [comment]
Dump from WAL logs confirms that inconsistency really happen. It includes operations that were observed by client with the same revision.

```
term         index      type    data
   2           334      norm    header:<ID:15517309547693860485 > txn:<compare:<target:MOD key:"/registry/pods/default/NYpLu" mod_revision:30 > success:<request_delete_range:<key:"/registry/pods/default/NYpLu" > > failure:<request_range:<key:"/registry/pods/default/NYpLu" > > > 
   2           335      norm    header:<ID:15517309547693860486 > txn:<compare:<target:MOD key:"/registry/pods/default/obin7" mod_revision:141 > success:<request_put:<key:"/registry/pods/default/obin7" value:"200" > > failure:<request_range:<key:"/registry/pods/default/obin7" > > > 
   2           336      norm    header:<ID:15517309547693860487 > txn:<compare:<target:MOD key:"/registry/pods/default/o95Cz" mod_revision:133 > success:<request_delete_range:<key:"/registry/pods/default/o95Cz" > > failure:<request_range:<key:"/registry/pods/default/o95Cz" > > > 
   2           337      norm    header:<ID:15517309547693860491 > txn:<compare:<target:MOD key:"/registry/pods/default/OWSx2" mod_revision:137 > success:<request_delete_range:<key:"/registry/pods/default/OWSx2" > > failure:<request_range:<key:"/registry/pods/default/OWSx2" > > > 
   2           338      norm    header:<ID:15517309547693860495 > txn:<compare:<target:MOD key:"/registry/pods/default/WjVep" mod_revision:144 > success:<request_delete_range:<key:"/registry/pods/default/WjVep" > > failure:<request_range:<key:"/registry/pods/default/WjVep" > > > 
   2           339      norm    header:<ID:15517309547693860496 > txn:<compare:<target:MOD key:"/registry/pods/default/geATU" mod_revision:71 > success:<request_delete_range:<key:"/registry/pods/default/geATU" > > failure:<request_range:<key:"/registry/pods/default/geATU" > > > 
   2           340      norm    header:<ID:15517309547693860499 > txn:<compare:<target:MOD key:"/registry/pods/default/FFgJw" mod_revision:127 > success:<request_delete_range:<key:"/registry/pods/default/FFgJw" > > failure:<request_range:<key:"/registry/pods/default/FFgJw" > > > 
   2           341      norm    header:<ID:15517309547693860500 > txn:<compare:<target:MOD key:"/registry/pods/default/SP2m4" mod_revision:95 > success:<request_delete_range:<key:"/registry/pods/default/SP2m4" > > failure:<request_range:<key:"/registry/pods/default/SP2m4" > > > 
   2           342      norm    header:<ID:15517309547693860501 > txn:<compare:<target:MOD key:"/registry/pods/default/V8bKj" mod_revision:53 > success:<request_delete_range:<key:"/registry/pods/default/V8bKj" > > failure:<request_range:<key:"/registry/pods/default/V8bKj" > > > 
   2           343      norm    header:<ID:15517309547693860502 > txn:<compare:<target:MOD key:"/registry/pods/default/Z68rD" mod_revision:156 > success:<request_delete_range:<key:"/registry/pods/default/Z68rD" > > failure:<request_range:<key:"/registry/pods/default/Z68rD" > > > 
   2           344      norm    header:<ID:15517309547693860503 > txn:<compare:<target:MOD key:"/registry/pods/default/EE7tw" mod_revision:92 > success:<request_delete_range:<key:"/registry/pods/default/EE7tw" > > failure:<request_range:<key:"/registry/pods/default/EE7tw" > > > 
   2           345      norm    header:<ID:15517309547693860506 > compaction:<revision:301 > 
   2           346      norm    header:<ID:15517309547693860511 > txn:<compare:<target:MOD key:"/registry/pods/default/n3ZPy" mod_revision:163 > success:<request_delete_range:<key:"/registry/pods/default/n3ZPy" > > failure:<request_range:<key:"/registry/pods/default/n3ZPy" > > > 
   3           347      norm    
   3           348      norm    header:<ID:15517309547694342401 > cluster_member_attr_set:<member_ID:14578408409545168728 member_attributes:<name:"TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0" client_urls:"http://localhost:20000" > > 
   3           349      norm    header:<ID:15517309547694342481 > txn:<compare:<target:MOD key:"/registry/pods/default/vZJa5" mod_revision:94 > success:<request_delete_range:<key:"/registry/pods/default/vZJa5" > > failure:<request_range:<key:"/registry/pods/default/vZJa5" > > > 
   3           350      norm    header:<ID:15517309547694342483 > txn:<compare:<target:MOD key:"/registry/pods/default/5Dtb4" mod_revision:251 > success:<request_put:<key:"/registry/pods/default/5Dtb4" value:"208" > > failure:<request_range:<key:"/registry/pods/default/5Dtb4" > > > 
   3           351      norm    header:<ID:15517309547694342485 > txn:<compare:<target:MOD key:"/registry/pods/default/E7Zuy" mod_revision:140 > success:<request_put:<key:"/registry/pods/default/E7Zuy" value:"209" > > failure:<request_range:<key:"/registry/pods/default/E7Zuy" > > > 
   3           352      norm    header:<ID:15517309547694342486 > txn:<compare:<target:MOD key:"/registry/pods/default/E7Zuy" mod_revision:140 > success:<request_put:<key:"/registry/pods/default/E7Zuy" value:"206" > > failure:<request_range:<key:"/registry/pods/default/E7Zuy" > > > 
   3           353      norm    header:<ID:15517309547694342488 > txn:<compare:<target:MOD key:"/registry/pods/default/HhKkd" mod_revision:112 > success:<request_put:<key:"/registry/pods/default/HhKkd" value:"207" > > failure:<request_range:<key:"/registry/pods/default/HhKkd" > > > 
```

The question remains, whether this inconsistency was caused by hardware or software issue. Number of deletes 
before failpoint observed in the report exceeds the number in my reproduction. 

Lack of reproduction could be caused issue only happening in rare cases of robustness traffic generation. So I think it's still worthy to try to investigate this.

**Comment by ahrtr** [comment]
> Dump from WAL logs confirms that inconsistency really happen.

To make it clearer, it's one node cluster. The bbolt db is consistent with WAL data with regard to revision 298, and also consistent with the report of client 3, 4 of the robustness test ( I only checked report of client 1, 3 and 4). 
- The key `/registry/pods/default/vZJa5` was removed at revision 298.

The only inconsistence is for client 1's report.
- The key `/registry/pods/default/o95Cz` was removed at revision 298

Theoretically, there are two possible reasons:
- The watch has issue when distributing the response.
- The robustness test has issue when generating the client report

But If I understood it correctly, all the clients in robustness test share the same gRPC watch stream, so the etcdserver sent the data (revision 298) only once to the client side, and it's just that the etcd client sdk dispatches the event to all logic sub streams/watchers.  So it's highly unlikely it's watch's issue.

**Comment by fuweid** [comment]
FYI, Reproduce it with https://github.com/etcd-io/etcd/pull/17782 after 17160.566s (8vcore, 16cpus, arm64, 5.15.0-1060-azure). 

```go
    logger.go:146: 2024-04-14T15:40:19.770Z     INFO    started server. {"name": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0", "pid": 224554}
    logger.go:146: 2024-04-14T15:40:19.770Z     INFO    Verifying cluster health after failpoint        {"failpoint": "compactBeforeSetFinishedCompact=panic()"}
    logger.go:146: 2024-04-14T15:40:20.771Z     INFO    Finished injecting failures
    logger.go:146: 2024-04-14T15:40:21.852Z     INFO    Recorded operations     {"operations": 937, "successRate": 0.7257203842049093}
    logger.go:146: 2024-04-14T15:40:21.852Z     INFO    Traffic from successful requests        {"qps": 266.3974175431209, "operations": 680, "period": "2.552577297s"}
    logger.go:146: 2024-04-14T15:40:21.852Z     INFO    Finished simulating traffic     {"max-revision": 415}
    logger.go:146: 2024-04-14T15:40:21.853Z     INFO    killing server...       {"name": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0"}
    logger.go:146: 2024-04-14T15:40:21.853Z     INFO    stopping server...      {"name": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0"}
    logger.go:146: 2024-04-14T15:40:21.856Z     INFO    stopped server. {"name": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0"}
    logger.go:146: 2024-04-14T15:40:21.858Z     INFO    Validating linearizable operations      {"timeout": "5m0s"}
    logger.go:146: 2024-04-14T15:40:25.004Z     ERROR   Linearization failed    {"duration": "3.145713744s"}
    validate.go:36: Failed linearization, skipping further validation
    logger.go:146: 2024-04-14T15:40:25.004Z     INFO    Saving robustness test report   {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1"}
    logger.go:146: 2024-04-14T15:40:25.004Z     INFO    Saving member data dir  {"member": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0", "path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/server-TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0"}
    logger.go:146: 2024-04-14T15:40:25.004Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-1/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.004Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-2/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.005Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-3/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.005Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-3/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.006Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-4/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.006Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-4/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.007Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-5/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.007Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-5/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.008Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-6/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.009Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-6/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.009Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-7/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.010Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-7/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.010Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-8/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.011Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-8/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.011Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-9/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.012Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-9/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.012Z     INFO    Saving watch operations {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-10/watch.json"}
    logger.go:146: 2024-04-14T15:40:25.013Z     INFO    Saving operation history        {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/client-10/operations.json"}
    logger.go:146: 2024-04-14T15:40:25.013Z     INFO    Saving visualization    {"path": "/tmp/results/TestRobustnessExploratory_Kubernetes_LowTraffic_ClusterOfSize1/history.html"}
    logger.go:146: 2024-04-14T15:40:25.037Z     INFO    closing test cluster...
    logger.go:146: 2024-04-14T15:40:25.037Z     INFO    closing server...       {"name": "TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0"}
    logger.go:146: 2024-04-14T15:40:25.037Z     INFO    removing directory      {"data-dir": "/tmp/TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize13457912620/001"}
    logger.go:146: 2024-04-14T15:40:25.037Z     INFO    closed test cluster.
--- FAIL: TestRobustnessExploratory (7.4FAIL: (code:1):
  % (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/robustness' '-timeout=30m' '-v' '--count' '10000' '--timeout' '2000m' '--failfast' '--run' 'TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1')
9s)
    --- FAIL: TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1 (7.48s)
FAIL
FAIL    go.etcd.io/etcd/tests/v3/robustness     17160.566s
FAIL

```
Still checking it.

**Comment by ahrtr** [comment]
> checked https://github.com/etcd-io/etcd/actions/runs/8659974818 and found `compaction encountered error","error":"mvcc: required revision is a future revision`. I also see that similar error in my local. It looks like some data is still cache before crash. Hope it can help.


Thanks @fuweid for the finding. There are two possible reasons:
- The latest revision hasn't been persisted into bbolt db when crashing. This isn't an issue, but we need to update the log to avoid confusion. See https://github.com/etcd-io/etcd/pull/17792
- The indeed revisions indeed decreased. It should be a critical issue if it's true. Added a verification. See https://github.com/etcd-io/etcd/pull/17791


We need to backport both PRs.

**Comment by serathius** [comment]
With https://github.com/etcd-io/etcd/pull/17815 this issue have been confirmed and reproduced on all supported release branches.

**Comment by ahrtr** [comment]
Based on my discussion with @fuweid today, for anyone reference on the root cause of this issue, see below summary.

- When latest revision is a tombstone revision, compacting the latest revision will remove the latest revision. **It causes the revision decreases in bbolt data file.**
- If etcd crashes right before it persists the finished compaction revision. Then the finished compact revision isn't persisted to bbolt https://github.com/etcd-io/etcd/blob/e37a67e40b3f5ff8ef81f9de6e7f475f17fda32b/server/storage/mvcc/kvstore_compaction.go#L66
- When etcd gets started again, it loads all keys and gets the latest revision (already decreased revision) from bbolt.  Usually it isn't a problem, because etcd will correct the revision based on the finished compaction revision. It's exactly the reason why previous I did not reproduce it when I raised the comment https://github.com/etcd-io/etcd/issues/17780#issuecomment-2053615731.  But if the finished compact revision hasn't been persisted, then there is no way for etcd to correct the revision. https://github.com/etcd-io/etcd/blob/e37a67e40b3f5ff8ef81f9de6e7f475f17fda32b/server/storage/mvcc/kvstore.go#L327
https://github.com/etcd-io/etcd/blob/e37a67e40b3f5ff8ef81f9de6e7f475f17fda32b/server/storage/mvcc/kvstore.go#L366-L368


One proposed solution: https://github.com/etcd-io/etcd/pull/17815#issuecomment-2061407869

The good news is that this issue should be very hard to reproduce in production environment.

**Comment by serathius** [comment]
With the issue confirmed we need to do impact assessment, check which version it affects, how often it can happen, can it cause inconsistency in multi member cluster and if it can happen in Kubernetes.

> The good news is that this issue should be very hard to reproduce in production environment.

Can you provide some context why it should very hard to reproduce, so for everyone can follow? Is it just based on small window of crash vulnerability due to infrequency of compact? How that probability looks for Kubernetes? 

Fact that last revision needs to be a tombstone, reduces the chances, but would be good to confirm what percentage do deletes constitute.

**Comment by ahrtr** [comment]
> > The good news is that this issue should be very hard to reproduce in production environment.
> 
> Can you provide some context why it should very hard to reproduce, so for everyone can follow?

Sorry for the confusion. I should be more clearer. Just updated my previous comment.

**Comment by serathius** [comment]
> Sorry for the confusion. I should be more clearer. Just updated my previous comment.

Thanks, looks great!

> Compact the latest revision;

This makes sense, compacting last revision is not expected behavior from most users. Kubernetes built in compaction should almost never do that. Almost here comes from cases where there were no writes at all for last 5 minutes.

**Comment by ahrtr** [comment]
@fuweid I am going to release etcd 3.4.32 together with @spzala tomorrow night, can you please https://github.com/etcd-io/etcd/pull/17815 to 3.5 and 3.4 ? Please feel free to let me know if you don't have bandwidth. Thanks

**Comment by fuweid** [comment]
@ahrtr working on it.

**Comment by ahrtr** [comment]
@fuweid Thanks. Please also update the changelog for 3.4 and 3.5.

**Comment by serathius** [comment]
Keeping it open until we cover it with robustness test.

**Comment by serathius** [comment]
Let's close it for now.
