### ISSUE TITLE
Setup a consistent way to manage go version

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17857]
### What would you like to be added?

Currently there are multiple places setting the go versions, for examples,
- go.mod files, including both `go` and `toolchain` directives;
- .go-version file;
- environment variable, such as https://github.com/etcd-io/etcd/pull/17734

We should set up a consistent way to manage go version. There should be only one source of truth for the go&toolchain version.

One problem is that if a dependency sets a higher go or toolchain version, then when running scripts/fix.sh will automatically update the go & toolchain version in our go.mod files.  Refer to https://github.com/etcd-io/etcd/pull/17841/files#r1575344566

References:
- https://go.dev/doc/toolchain
- https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#building-kubernetes-using-a-specific-version-of-go

cc @fuweid  @henrybear327  @ivanvc @jmhbnz  @MadhavJivrajani @serathius 

### Why is this needed?

Setup consistent way to manage go version

**Comment by ahrtr** [comment]
> In Kubernetes we added a pre-submit check to catch such accidental bumps if they occur: [kubernetes/kube-openapi#467](https://github.com/kubernetes/kube-openapi/pull/467)

Thanks @MadhavJivrajani 

I think we should do similar check for all etcd branches: including `release-3.4`, `release-3.4` and `main`.

The other potential enhancement is to automatically populate the go versions for the `go` and `toolchain` lines in all go.mod (and go.sum) files based on the `.go-version` file.

**Comment by MadhavJivrajani** [comment]
I have some ideas on how we can go about doing this. Will create a PR and we can discuss there!

**Comment by ahrtr** [comment]
Followups:
- Update document: https://github.com/etcd-io/etcd/pull/17876#discussion_r1587360706
- Refactor the ./scripts/fix.sh as mentioned in https://github.com/etcd-io/etcd/pull/17876#discussion_r1593660044

**Comment by ahrtr** [comment]
I think we also need to backport the changes to both 3.5 and 3.4

**Comment by ahrtr** [comment]
We should follow the same rule to manage go version for all repositories under etcd-io. Note we only require users to depend on a minor version supported by golang team, i.e. **1.21**, but we don't force users to depend on a patch version, i.e. **1.21.10**.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, for the next step we just need to edit the following section of https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#golang-versions

```diff
- 3. Complete the upgrade locally in your development environment.
+ 3. Complete the upgrade locally in your development environment by editing `.go-version` and running `make fix.
```

Adding good-first-issue label.

**Comment by manthanguptaa** [comment]
@jmhbnz I will take it up
