### ISSUE TITLE
Support AllowedCN and AllowedHostname through config file

### ISSUE THREAD

**Issue by clwluvw** [etcd-io/etcd#17867]
### What would you like to be added?

Allow setting AllowedCN and AllowedHostname tls fields through the config file for peer transport security.

### Why is this needed?

According to the documents, flags cannot be mixed with a config file:
> Caution: If you mix-and-match configuration options, then the following rules apply.
> Command-line flags take precedence over environment variables.
> If you provide a configuration file all command-line flags and environment variables are ignored.

**Comment by jmhbnz** [comment]
Re-opening for backport to `release-3.5`.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage, closing backport and changelog completed.
