### ISSUE TITLE
Enable Prow slack messages to SIG-etcd channel

### ISSUE THREAD

**Issue by jberkus** [etcd-io/etcd#17882]
### What would you like to be added?

Consider enabling the Prow plugin to message #sig-etcd or a new channel with Slack messages around PRs, merges, and test failures.  

### Why is this needed?

Per #16890, some contributors would like to add repo messages to Slack.  Kubernetes slack does this [via Prow plugins](https://github.com/kubernetes/test-infra/blob/82fc0af2e749607b053954405f04c9f0a0b6068b/config/prow/plugins.yaml#L359).  If we want this, then that's what we need to enable.

This opens up the questions of:

1. Do we want repository activity messages in Slack?
2. Do we want them in the main #sig-etcd channel, or in a new channel?

Please discuss.

**Comment by liangyuanpeng** [comment]
Maybe k/k also have enabled the slackk app in github org?  Because I am listening to k/k event notifications through github slack.

See 

![image](https://github.com/etcd-io/etcd/assets/28711504/52975685-ee17-4c9b-90d9-47001058cbfb)

**Comment by jberkus** [comment]
@liangyuanpeng are you saying that these notifications are from k/k, but are available in a different slack, as in not Kubernetes slack?

**Comment by liangyuanpeng** [comment]
> are you saying that these notifications are from k/k, but are available in a different slack, as in not Kubernetes slack?

correct,  It's working with https://slack.github.com/ .

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting. We agreed this would be helpful, however we need to understand which types of notifications we would want to receive. If this will be channel based we agreed a separate channel would be best so everyone can opt in to receiving them.

I think we need to review the configuration for the slack plugin https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L359 and understand the capabilities.

**Comment by ArkaSaha30** [comment]
Adding [Slack Reporter](https://docs.prow.k8s.io/docs/components/core/crier/#slack-reporterhttpsgithubcomkubernetes-sigsprowtreemainpkgcrierreportersslack) doc here as it seems relevant. It is not exactly a plugin but a crier to post job statuses in a given slack channel for a given set of prowjobs. 
At first glance, it seems like tweaking it can serve our purpose. If this is a viable option I am ready to take it up 🤚

**Comment by jmhbnz** [comment]
Stepping back from the solutions for a moment I just want to make sure we are clear on what we are requesting so we can then make a good decision about how to achieve it, based on the discussion at triage today we had:

- A new slack channel to be created for etcd notifications
- Automated notifications to be sent to the channel for issue or pr creation

This would be a good starting point I think.  Another potentially useful notification would be failures for `scheduled` or `postsubmit` etcd prow jobs.

Ideally we would configure which repositories send notifications as code.  If anyone has ideas to do something different than what I have described above or any objections please reply below.

If you have time to investigate some options @ArkaSaha30 please take a look 🙏🏻

**Comment by jberkus** [comment]
@liangyuanpeng well, if you want to use slack.github.com there's nothing preventing that.  Does the project want that though?

**Comment by jmhbnz** [comment]
Discussed again at sig-etcd triage meeting. We still need to investigate if there is an integration we can set up for notifications of new issues or pull requests being created.

We discussed notifications for failing jobs. There was not widespread support for this type of notification as it tends to be noise that gets ignored.

**Comment by jmhbnz** [comment]
Dicussed during sig-etcd triage meeting. Closing as not a priority currently, we can always revisit & re-open this in future if needed.
