### ISSUE TITLE
Bump bbolt to 1.3.10 for both 3.4 and 3.5

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#17944]
### What would you like to be added?

bbolt 1.3.10 was released!

https://github.com/etcd-io/bbolt/releases/tag/v1.3.10

### Why is this needed?

Keep up to date on the core dependency

**Comment by tjungblu** [comment]
sorry @ArkaSaha30 - I leave the 3.6 bump for you.

ref #17943 #17945

**Comment by fuweid** [comment]
Hi @tjungblu would you please file a pull request to update the changelog? thanks

**Comment by tjungblu** [comment]
absolutely will, one sec
