### ISSUE TITLE
Auto label PRs on Github

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#17970]
### What would you like to be added?

Would be nice for PR discovery to have them automatically labeled based on directory they touch.
For example if the test touches `./tests/robustness` we can always label it with `area/robustness-testing`.

I think K8s OWNERS support this https://go.k8s.io/owners

cc @jmhbnz 

### Why is this needed?

Better discovery of PRs for people interested in reviewing robustness test changes.

**Comment by jmhbnz** [comment]
Agree this would be great to start bringing online. Thanks @liangyuanpeng for drafting the initial pr.

For this to be helpful we do need to add nested `OWNERS` files with the label stanza, for example: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/OWNERS

Nested `OWNERS` we have already discussed and have consensus to progress so I will write an initial suggestion of labels here shortly so we can raise the pr.

**Comment by fuweid** [comment]
Hi @jmhbnz , as far as I know, `/lgtm` command doesn't work. Is there any plan to use OWNERS file and enable `/lgtm` as review process?

**Comment by jmhbnz** [comment]
> Hi @jmhbnz , as far as I know, `/lgtm` command doesn't work. Is there any plan to use OWNERS file and enable `/lgtm` as review process?

Yes. But we need to work carefully and set up the nested `OWNERS` files that it would depend on. It's a gradual journey adopting the k/k prow features, want to make sure we don't try to do too much at once and cause problems.  This auto labeling is a good driver for us to start creating nested `OWNERS`.

**Comment by ah8ad3** [comment]
Very nice feature to have let me know if i can help with anything.

**Comment by serathius** [comment]
@jmhbnz was https://github.com/etcd-io/etcd/pull/17979 enough to have auto labeling working? Have you tested it?

**Comment by jmhbnz** [comment]
> @jmhbnz was #17979 enough to have auto labeling working? Have you tested it?

Yes it is working now, example https://github.com/etcd-io/etcd/pull/17983:

![image](https://github.com/etcd-io/etcd/assets/39425256/c6716410-96e4-4022-92f8-8f186c071081)

I still need to check nesting for label hierarchy but basics are working :)
