### ISSUE TITLE
etcdctl --discovery-srv behavior differs between Mac and Linux versions

### ISSUE THREAD

**Issue by levin-kitty** [etcd-io/etcd#18021]
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I am trying to access the etcd cluster using --discovery-srv in etcdctl. I do not want to use TLS communication.

The Mac version succeeded, but the Linux version failed. The etcdctl version is the same, 3.5.13.

Error is
`Error: dns lookup errors: lookup _etcd-client-ssl.{} on 127.0.0.53:53: no such host and lookup {} on 127.0.0.53:53: cannot unmarshal DNS message`

I'm not sure if using --discovery-srv on the Linux version doesn't force you to use TLS only.

### What did you expect to happen?

Like the Mac version, the Linux version uses the same

### How can we reproduce it (as minimally and precisely as possible)?

1) Configure an SRV domain that does not use TLS communication
2) Access the Linux version of etcdctl

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
etcdctl version: 3.5.13
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
Error: dns lookup errors: lookup _etcd-client-ssl.{} on 127.0.0.53:53: no such host and lookup {} on 127.0.0.53:53: cannot unmarshal DNS message
```

**Comment by ahrtr** [comment]
My immediate feeling it's a configuration issue, which means most likely you did not configure correctly the discovery on linux .


Refer to https://etcd.io/docs/v3.5/op-guide/clustering/#dns-discovery

**Comment by levin-kitty** [comment]
@ahrtr 

I'm sorry. It wasn't an issue with etcdctl, it was an issue with the DNS resolver. I've been using the systemd 239 version of the server, and in this case there is an [issue](https://github.com/systemd/systemd/pull/9828) with Golang not parsing the SRV records correctly.
