### ISSUE TITLE
Nominate @ivanvc and @siyuanfoundation as etcd reviewers

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#18020]
### What would you like to be added?

I would like to propose @ivanvc and @siyuanfoundation for the global role of [reviewer](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#reviewers) across `etcd-io/etcd`.

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md)
- [X] The members are actively contributing to 1 or more etcd subprojects
- [X] The members are being sponsored by two current reviewers or a current maintainer.

---

@ivanvc has been extremely active across a number of `etcd-io` subprojects since getting involved with the project six months ago at our ContribFest in Chicago in November 2023. 

Ivan adding to your code & review contributions I am deeply appreciative of your focus on helping other community members and being active in our regular community and triage meetings. Also thanks for your help outside the `etcd-io` org with improving our workflows in `kubernetes/test-infra` and helping us progress towards better performance qualification of etcd and bbolt.

### How do the new members meet the regular active contribution requirements?

* They have personally
  * authored [over 80 pull requests](https://github.com/search?q=org%3Aetcd-io+is%3Apr+is%3Amerged+author%3Aivanvc&type=pullrequests)
  * reviewed [over 50 pull requests](https://github.com/search?q=org%3Aetcd-io+is%3Apr+reviewed-by%3Aivanvc&type=pullrequests)
* Knowledgeable about the codebase.
  * @ivanvc is the code author of our new golang version of `tools/rw-heatmaps`
  * @ivanvc is a go to person for etcd actions and prow workflows across multiple `etcd-io` repositories.
* Sponsored by two active maintainers.
  * @ahrtr, VMware
  * @jmhbnz, Red Hat
  *  [x] Sponsors must be from multiple member companies to demonstrate integration across community.

---

@siyuanfoundation has been making crucial contributions to some of our most important roadmap items for etcd, both within the `etcd-io` repository but also across a number of `kubernetes` subprojects relating to etcd.

Siyuan the amount of progress you've contributed towards etcd 3.6 since your first pr just eight months ago is extraordinary. Thank you for your help towards making etcd 3.6 a reality and hepling to bridge the divide between Kubernetes and etcd. Your efforts on livez/readyz, downgrades and feature gates are making a big difference for the project and exceed that of reviewer level.

* They have personally
  * authored [over 40 pull requests](https://github.com/search?q=org%3Aetcd-io+is%3Apr+is%3Amerged+author%3Asiyuanfoundation&type=pullrequests) (and [over 15 pull requests](https://github.com/search?q=org%3Akubernetes+is%3Apr+is%3Amerged+author%3Asiyuanfoundation&type=pullrequests) to `kubernetes` org).
  * reviewed [over 30 pull requests](https://github.com/search?q=org%3Aetcd-io+is%3Apr+reviewed-by%3Asiyuanfoundation+-author%3Asiyuanfoundation&type=pullrequests)
  * authored [2 etcd enhancement proposals](https://github.com/kubernetes/enhancements/pulls?q=is%3Apr+author%3Asiyuanfoundation)
* Knowledgeable about the codebase.
  * @siyuanfoundation has been personally responsible for making livez/readyz, downgrades a reality, and is actively designing feature gates.
* Sponsored by two active maintainers.
  * @wenjiaswe, Google
  * @jmhbnz, Red Hat
  *  [x] Sponsors must be from multiple member companies to demonstrate integration across community.

---

### Why is this needed?

Recognise the great work of our community members and support their progression.

**Comment by jmhbnz** [comment]
cc @etcd-io/maintainers-etcd

**Comment by ivanvc** [comment]
Thanks for the nomination. As I mentioned before, I'm more than happy to contribute within my areas of expertise to the project. I'm grateful to the community, other members, our maintainers, and SIG co-chairs :v: :heart:

**Comment by ahrtr** [comment]
+1 Thanks both for your great contribution!

**Comment by logicalhan** [comment]
+1 from me!!

**Comment by wenjiaswe** [comment]
+1000 so happy to see more reviewers in etcd! @ivanvc @siyuanfoundation Well deserved! Thank you for your continuous high quality contribution!

**Comment by jmhbnz** [comment]
Hi @ivanvc, @siyuanfoundation - All sponsors have +1 so please proceed with pr's to update:
- https://github.com/kubernetes/org/blob/main/config/etcd-io/sig-etcd/teams.yaml#L102
- https://github.com/etcd-io/etcd/blob/main/OWNERS#L9

/assign @siyuanfoundation
/assign @ivanvc

**Comment by fuweid** [comment]
+1. Thanks for contributions!
