### ISSUE TITLE
etcd watcher doesn't read older events

### ISSUE THREAD

**Issue by arjunsingriuber** [etcd-io/etcd#18053]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I inserted a few thousand key/values in etcd 3.5 and brought the revision to 75,000. But when I start the watcher to watch from revision 1000, I don't get any events.

This is the code I have:

```
cli, err := clientv3.New(clientv3.Config{
                Endpoints:   []string{"http://localhost:2379"},
                DialTimeout: 5 * time.Second,
        })

 watchChan := cli.Watch(context.Background(), "", clientv3.WithRev(1000))

watchResp := <-watchChan // this call is blocking, I never get past this

var count int
startTime := time.Now()

for watchResp := range watchChan {
                
                for range watchResp.Events {
                        count++

                        // Print the time taken for every 10 objects
                        if count%10 == 0 {
                                duration := time.Since(startTime)
                                fmt.Printf("Time taken to watch %d objects: %v\n", count, duration)
                                startTime = time.Now()
                        }
                }
        }
```

### What did you expect to happen?

Be able to read older events because the docs say so.

### How can we reproduce it (as minimally and precisely as possible)?

Code is above.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.0
Git SHA: 946a5a6f2
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.0
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by tjungblu** [comment]
I think you're missing the prefix option:

> 	rch := cli.Watch(context.Background(), "", clientv3.WithPrefix(), clientv3.WithRev(1000))

Otherwise you would watch on key "", which I'm not so sure you're actually creating as that code is missing.

Also note that you might not get the whole history, because a distant revision might already be compacted.
