### ISSUE TITLE
Add integration tests to prow presubmit

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18065]
### What would you like to be added?

As part of the prow migration, we need to migrate some remaining GitHub workflows. Currently, integration tests have not yet migrated. They run in a matrix approach, with one, two and four CPUs.

### Why is this needed?

Progress towards https://github.com/kubernetes/k8s.io/issues/6102 to migrate more GitHub workflows into prow jobs.

**Comment by ivanvc** [comment]
@jmhbnz, I think we're ready to remove arm64 workloads from GitHub actions. What do you think?

https://github.com/etcd-io/etcd/blob/0e8b9b2ef2f72cd0a374826fd608146432cc7d93/.github/workflows/tests.yaml#L6-L10

**Comment by jmhbnz** [comment]
> @jmhbnz, I think we're ready to remove arm64 workloads from GitHub actions. What do you think?

Do you mean `amd64`?  If so I agree these are running nicely in prow now 👍🏻

**Comment by ivanvc** [comment]
> Do you mean `amd64`?  If so I agree these are running nicely in prow now 👍🏻 


Oops, yes I meant amd
