### ISSUE TITLE
etcd panic: assertion failed: Page expected to be: 36312, but self identifies as 0

### ISSUE THREAD

**Issue by Black-max12138** [etcd-io/etcd#18096]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Etcd fails to be started after the node is powered off and then powered on.
`panic: assertion failed: Page expected to be: 36312, but self identifies as 0

goroutine 293 [running]:
go.etcd.io/bbolt._assert(...)
        go.etcd.io/bbolt@v1.3.8/db.go:1387
go.etcd.io/bbolt.(*page).fastCheck(0xfffcb0dd8000, 0x8dd8)
        go.etcd.io/bbolt@v1.3.8/page.go:57 +0x184
go.etcd.io/bbolt.(*Tx).page(0x50?, 0xffffada72fe8?)
        go.etcd.io/bbolt@v1.3.8/tx.go:534 +0x74
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0x400049a460, {0x40000402d0, 0x1, 0xa}, 0x400029f508)
        go.etcd.io/bbolt@v1.3.8/tx.go:546 +0x4c
go.etcd.io/bbolt.(*Tx).forEachPage(...)
        go.etcd.io/bbolt@v1.3.8/tx.go:542
go.etcd.io/bbolt.(*Tx).checkBucket(0x400049a460, 0x400049a478, 0x400029f748, 0x400029f688, {0xaaaac8bc65e8, 0xaaaac93ec120}, 0x4000284480)
        go.etcd.io/bbolt@v1.3.8/tx_check.go:83 +0xc8
go.etcd.io/bbolt.(*DB).freepages(0x40001e6488)
        go.etcd.io/bbolt@v1.3.8/db.go:1205 +0x168
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        go.etcd.io/bbolt@v1.3.8/db.go:417 +0xb4
sync.(*Once).doSlow(0xaaaac83417a0?, 0x40001e6650?)
        sync/once.go:74 +0x100
sync.(*Once).Do(...)
        sync/once.go:65
go.etcd.io/bbolt.(*DB).loadFreelist(0x40001e6488?)
        go.etcd.io/bbolt@v1.3.8/db.go:413 +0x48
go.etcd.io/bbolt.Open({0x40001bb2f0, 0x22}, 0x180, 0x400016eae0)
        go.etcd.io/bbolt@v1.3.8/db.go:295 +0x340
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0x40001bb2f0, 0x22}, 0x5f5e100, 0x2710, {0xaaaac8780c41, 0x7}, 0x280000000, 0x4000196190, 0x0, 0x0, ...})
        go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:187 +0x15c
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
        go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x4000423d14, 0xc}, {0x0, 0x0}, {0x0, 0x0}, {0x4000427b90, 0x1, 0x1}, {0x4000427a70, ...}, ...}, ...)
        go.etcd.io/etcd/server/v3/etcdserver/backend.go:55 +0x2cc
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
        go.etcd.io/etcd/server/v3/etcdserver/backend.go:76 +0x50
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend in goroutine 1
        go.etcd.io/etcd/server/v3/etcdserver/backend.go:75 +0x120`

### What did you expect to happen?

Etcd should start normally.

### How can we reproduce it (as minimally and precisely as possible)?

powered off and then powered on.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```
3.5.11
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by Black-max12138** [comment]
The etcdutl command is used to check whether the file is damaged. However, the etcd-dump-db command cannot be used to read data, which is consistent with the error reported in the etcd log.
etcdutl check broken --data-dir=/opt/etcd/data   --check ok
etcd-dump-db list-bucket /opt/etcd/data/   --can not read

**Comment by ahrtr** [comment]
Unfortunately, the db should have already corrupted. Could you please provide the following info,
- What's the OS and ARCH? Please run `uname -a`
- What's the OS version?
- What's the filesytem? i.e. ext4, xfs, etc.
- How often do you see this issue? Can it be easily reproduced?

Is it possible to share the db file if it isn't production environment?

**Comment by mspanc** [comment]
I have similar issue. 

macOS 15.6.1, MacBook Pro M4, using Docker Desktop.

I had something that looked like kernel panic, the screen was stuck, and the computer shut down after a few seconds. After restarting, I am unable to start Docker.

```
service containerd failed: panic detected in containerd: panic: assertion failed: Page expected to be: 638, but self identifies as 0

goroutine 70 [running]:

go.etcd.io/bbolt._assert(...)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:1387
go.etcd.io/bbolt.(*page).fastCheck(0xffff38c7e000, 0x27e)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/page.go:57 +0x184
go.etcd.io/bbolt.(*Tx).page(0xffff38bbd000?, 0xaaaadfd743c8?)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx.go:534 +0x74
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0x40001f22a0, {0x4000302d20, 0x2, 0xa
}, 0x4000057138)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx.go:546 +0x4c
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0x40001f22a0, {0x4000302d20, 0x1, 0xa}, 0x4000057138)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx.go:555 +0xb8
go.etcd.io/bbolt.(*Tx).forEachPage(...)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx.go:542
go.etcd.io/bbolt.(*Tx).checkBucket(0x40001f22a0, 0x40001f22b8, 0x4000057378, 0x40000572b8, {0xaaaadf0e08f0, 0xaaaadfdf2fe0}, 0x4000314b60)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx_check.go:83 +0xbc
go.etcd.io/bbolt.(*DB).freepages(0x4000592248)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:1205 +0x160
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:417 +0xb4
sync.(*Once).doSlow(0xaaaade0f3070?, 0x4000592410?)
	/usr/local/go/src/sync/once.go:76 +0xf8
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:67
go.etcd.io/bbolt.(*DB).loadFreelist(0x4000592248?)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:413 +0x44
go.etcd.io/bbolt.Open({0x4000302c80, 0x49}, 0x1a4, 0x4000057620)
	/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:295 +0x340
github.com/containerd/containerd/metadata/plugin.init.1.func1(0x40005c8800)
	/go/src/github.com/containerd/containerd/metadata/plugin/plugin.go:160 +0x634
github.com/containerd/containerd/plugin.(*Registration).Init(0x400011ad80, 0x40005c8800)
	/go/src/github.com/containerd/containerd/plugin/plugin.go:132 +0x30
github.com/containerd/containerd/services/server.New({0xaaaadf0ed608, 0x400031a230}, 0x4000604700)
	/go/src/github.com/containerd/containerd/services/server/server.go:251 +0x11c0
github.com/containerd/containerd/cmd/containerd/command.App.func1.1()
	/go/src/github.com/containerd/containerd/cmd/containerd/command/main.go:195 +0x64
created by github.com/containerd/containerd/cmd/containerd/command.App.func1 in goroutine 1
	/go/src/github.com/containerd/containerd/cmd/containerd/command/main.go:192 +0x62c
```

**Comment by ahrtr** [comment]
Unfortunately, the db file is corrupted. Most likely the page wasn't successfully synced to disk even the system call returned success.

**Comment by ahrtr** [comment]
@mspanc if you provide the db file, we can try to fix it using the [surgery command](https://github.com/etcd-io/bbolt/blob/main/cmd/bbolt/command/command_surgery.go), but not guaranteed.
