### ISSUE TITLE
Make linearizable renew lease  configurable

### ISSUE THREAD

**Issue by aaronjzhang** [etcd-io/etcd#18100]
### What would you like to be added?

Add a config flag to make linearizable renew lease configurable.

### Why is this needed?

The feature ["linearizable renew lease"](https://github.com/etcd-io/etcd/pull/13932) has a side affect, when "apply entries took too long" happens and the apply time took more than the TTL of a lease will cause lease keep alive failure, for some applications, they can tolerate the fake lease keep alive failure, in this case, they just need to grant a new lease and retry, but they can't tolerate the "apply entries took too long" blocks the keep alive for all leases.

**Comment by ahrtr** [comment]
It may break correctness, so there is no plan to support this. See also https://github.com/etcd-io/etcd/discussions/18091#discussioncomment-9607204
