### ISSUE TITLE
Typo in etcd data model image

### ISSUE THREAD

**Issue by lubronzhan** [etcd-io/etcd#18165]
### What would you like to be added?

Fix the typo in etcd data model image https://github.com/etcd-io/website/blob/009fe6b1cfe50ed286b0c550bb293fa66b042233/content/en/docs/v3.6/learning/img/data-model-figure-01.png

Inside the B+tree, `R4` on bottom right should be `K4`, and `R1` `R2` should be on the same node, instead of keys on two nodes.

### Why is this needed?

It's confusing for reader.

**Comment by ahrtr** [comment]
> Inside the B+tree, `R4` on bottom right should be `K4`, and `R1` `R2` should be on the same node, instead of keys on two nodes.

The keys (the real keys which are visible to users) saved in bbolt are different from the keys (actually revisions which are monotonically increasing) in the TreeIndex in etcd.
