### ISSUE TITLE
Code that relies on gRPC metadata formatting should be fixed

### ISSUE THREAD

**Issue by dfawley** [etcd-io/etcd#18303]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

This code:

https://github.com/etcd-io/etcd/blob/21e5876f7f0539509c277b4c2a3ba1b1599b1721/client/v3/watch.go#L1038-L1043

expects consistent ordering from gRPC as well as expecting all metadata to be included.

However, metadata can contain PII, so we would like to change gRPC's behavior to not print any potential PII.  https://github.com/grpc/grpc-go/issues/7395

### What did you expect to happen?

Code correctness to _not_ rely upon gRPC's `metadata.MD.String` method.

### How can we reproduce it (as minimally and precisely as possible)?

Look at the code.

### Etcd version (please run commands below)

master

**Comment by dfawley** [comment]
One trivial fix would be forcing the Go builtin formatting for the raw, underlying `map` type:

```go
return fmt.Sprint(map[string][]string(md))
```

**Comment by ahrtr** [comment]
Thanks @dfawley for raising this ticket. We should raise it long time ago.

Please read clarification below In case anyone gets confused.

- [fmt.Sprintf("%+v", md)](https://github.com/etcd-io/etcd/blob/21e5876f7f0539509c277b4c2a3ba1b1599b1721/client/v3/watch.go#L1040) will call  [(md MD) String()](https://github.com/grpc/grpc-go/blob/v1.64.0/metadata/metadata.go#L95-L106), which iterates over a map, but the iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
- Golang fmt package guarantees that Maps are printed in a consistent order, sorted by the values of the keys.

**Comment by JabulaniNgcobo** [comment]
https://github.com/etcd-io/etcd/pull/18308

**Comment by ahrtr** [comment]
@mohamedawnallah Please update changelog for both [3.5](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md) and [3.4](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.4.md). thx

**Comment by mohamedawnallah** [comment]
@ahrtr Sounds good! Updated the change log for releases `3.4` and `3.5` in the following PRs:
- CHANGELOG-3.4.md: https://github.com/etcd-io/etcd/pull/18316
- CHANGELOG-3.5.md: https://github.com/etcd-io/etcd/pull/18317

**Comment by ahrtr** [comment]
> @ahrtr Sounds good! Updated the change log for releases `3.4` and `3.5` in the following PRs:
> 
> * CHANGELOG-3.4.md: [CHANGELOG/CHANGELOG-3.4.md: update changelog for gRPC metadata printing #18316](https://github.com/etcd-io/etcd/pull/18316)
> * CHANGELOG-3.5.md: [CHANGELOG/CHANGELOG-3.5.md: update changelog for gRPC metadata printing #18317](https://github.com/etcd-io/etcd/pull/18317)

Thanks. Actually one PR should be good, there is no need to raise two separate PRs to update changelog. But not a big problem, so I won't insist on it.

**Comment by mohamedawnallah** [comment]
Thanks for the clarification! Combining into a single PR makes sense. I'll follow that approach in the future. Thanks for the flexibility on this one!

**Comment by ahrtr** [comment]
All done!

Thanks @mohamedawnallah and @dfawley

**Comment by dfawley** [comment]
Thank you for the quick fixes!
