### ISSUE TITLE
Completion command is not included in releases of etcdctl

### ISSUE THREAD

**Issue by tt-kkaiser** [etcd-io/etcd#18338]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I downloaded etcdctl using the linux commands found in the releases for v3.5.14.
After downloading I wanted to add auto completion for my bash setup.

Whilst executing the completion command, I got this error:
```bash
etcdctl completion -h
Error: unknown command "completion" for "etcdctl"

Did you mean this?
        compaction

Run 'etcdctl --help' for usage.
```

### What did you expect to happen?

I expected the completion command to exist.

### How can we reproduce it (as minimally and precisely as possible)?

1. Download the etcdctl binary from the GitHub releases.
2. Execute etcdctl completion -h

### Anything else we need to know?

Whilst the completion command is not available with the prebuilt binary found in the releases, it works with an self-built binary from source.

### Etcd version (please run commands below)

v3.5.14

**Comment by jmhbnz** [comment]
Hi @tt-kkaiser - Thanks for reporting this, I can replicate the issue you described however this isn't a bug.

The `etcdctl completion` command was introduced in https://github.com/etcd-io/etcd/pull/13133 for the `main` branch and has not been backported to the `release-3.5` stable release branch as we try to avoid backporting new features.

This feature will be included in the next minor release of etcd `v3.6.0`. Refer: https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.6.md#etcdctl-v3

> ### etcdctl v3
> Add command to generate [shell completion](https://github.com/etcd-io/etcd/pull/13133).
