### ISSUE TITLE
Etcd compilation process error

### ISSUE THREAD

**Issue by smallemployees** [etcd-io/etcd#18339]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Getting error undefined: grpc.SupportPackageIsVersion6 and undefined: grpc.ClientConnInterface

### What did you expect to happen?

How to solve compatibility issues with the GRPC library

### How can we reproduce it (as minimally and precisely as possible)?

How to solve compatibility issues with the GRPC library

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
3.4.18
$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jberkus** [comment]
Can you please try this with the latest patch revision, 3.4.33?

Even better, try this with 3.5 or 3.6.

**Comment by BoyChai** [comment]
Old versions that may be introduced during introduction, refer to
https://github.com/BoyChai/etcd-client/commit/f7394d9b54034a71f4a3ed6a2ed67470081cf973

**Comment by ahrtr** [comment]
The reason is that you were using an very old etcd version, but an new grpc-go version, and they are not compatible.
