### ISSUE TITLE
Client v3 and GRPC versions conflict

### ISSUE THREAD

**Issue by BoyChai** [etcd-io/etcd#18344]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Since the emergence of the new version of Client v3 and GRPC, there has been a conflict

### What did you expect to happen?

No dependency error

### How can we reproduce it (as minimally and precisely as possible)?

Reference warehouse https://github.com/BoyChai/etcd-client
go mod tidy

### Etcd version (please run commands below)

<details>
go.etcd.io/etcd v3.3.27+incompatible
```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
undefined: grpc.ClientConnInterface
undefined: grpc.SupportPackageIsVersion6
undefined: grpc.ClientConnInterface
undefined: grpc.ClientConnInterface
```

**Comment by jberkus** [comment]
Hey, version 3.3 is no longer supported.  Can you see if you can reproduce this problem with a supported version?

**Comment by BoyChai** [comment]
> Hey, version 3.3 is no longer supported. Can you see if you can reproduce this problem with a supported version?

Thank you very much. The version I am using is too old

**Comment by BoyChai** [comment]
https://github.com/BoyChai/etcd-client/commit/f7394d9b54034a71f4a3ed6a2ed67470081cf973
