### ISSUE TITLE
Confusing documentation for `WatchResponse.canceled`

### ISSUE THREAD

**Issue by VojtechStep** [etcd-io/etcd#18413]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

The [documentation](https://etcd.io/docs/v3.5/dev-guide/api_reference_v3/#message-watchresponse-apietcdserverpbrpcproto) of `WatchResponse.canceled` says
> canceled is set to true if the response is for a cancel watch request. No further events will be sent to the canceled watcher.

However, the `canceled` field is also set to true when sending the first progress report after watch creation, if the `start_revision` has already been compacted.

### What did you expect to happen?

The `canceled` flag to not be set in a response to a create watch request, or for the behavior to be documented. It was introduced in #8283.

### How can we reproduce it (as minimally and precisely as possible)?

Send a watch creation request with the `start_revision` field set to a compacted revision.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.1
Git SHA: e8732fb5f
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.9
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by myrat92** [comment]
Hello, I would like to work on this issue. Can you please assign it to me? @jmhbnz

**Comment by jmhbnz** [comment]
Closing, pr completed. This is a minor fix so probably doesn't meet backport criteria, we can always reopen if that changes.  Thanks @myrat92 for completing the `main` pr.
