### ISSUE TITLE
Need to update golang pkg.dev document

### ISSUE THREAD

**Issue by ah8ad3** [etcd-io/etcd#18410]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

If you go to this [url ](https://pkg.go.dev/go.etcd.io/etcd/client/v3#section-readme) which is the first thing when i googled etcd golang that pop up. The publish time of the page is for Jul 19, 2024. But the body of it is pretty outdated. 
For example:
> Warning: As etcd 3.5.0 was not yet released, the command above does not work. After first pre-release of 3.5.0 [#12498](https://github.com/etcd-io/etcd/issues/12498), etcd can be referenced using:

### What did you expect to happen?

So that page should be updated with each release of etcd.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

I don't know if we care about that page or not but i was going to introduce using etcd for golang to someone and that page came up and it was outdated so ended up giving him this https://github.com/etcd-io/etcd/blob/main/tests/integration/clientv3/examples/example_kv_test.go instead.

It is not a bug but i didn't know where to raise this issue so i used this pattern.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
Thanks @ah8ad3 for the finding.

We need to update https://github.com/etcd-io/etcd/blob/release-3.5/client/v3/README.md

Reference: https://tip.golang.org/blog/pkgsite-redesign

**Comment by ghouscht** [comment]
The PR with the doc update was merged. With the next 3.5 patch release the Go pkg site will be updated automatically.

**Comment by ahrtr** [comment]
Thanks. 

Resolved in https://github.com/etcd-io/etcd/pull/18579
