### ISSUE TITLE
something wrong with simple_token

### ISSUE THREAD

**Issue by YJ-Linson** [etcd-io/etcd#18437]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

We deployed a 3-node etcd cluster in three IDCs, and the RTT between these nodes is about 200ms

We connected to this etcd cluster through grpc with round-robin strategy, which worked normally most of the time, but we found that PUT request authentication failed occasionally

The reason for the failure was that the mapping from token to user could not be found in `func (t *tokenSimple) info(ctx context.Context, token string, revision uint64)`

By reading the code, we found that the index at the end of simple_token is not the index of token-gen entry, which caused the invalid wait of the `func (t *tokenSimple) isValidSimpleToken(ctx context.Context, token string)`

### What did you expect to happen?

`func (t *tokenSimple) isValidSimpleToken(ctx context.Context, token string)` waits for the correct index

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a 3-node etcd cluster and move leader to node1,
Then set the RTT between node1 and node2 to 200ms,
Then create 2 clients in one process, client1 only connects to leader (node1), client2 only connects to node2,
After client1 successfully get a new token, immediately let client2 initiate a PUT request with this token,
The PUT request will fail

The log output of node2 as follow
```
{"level":"warn","ts":"2024-08-14T16:23:46.08648+0800","caller":"auth/store.go:1183","msg":"invalid auth token","token":"SWECtbxJwjkaTwYs.19146856"}
{"level":"debug","ts":"2024-08-14T16:23:46.086574+0800","caller":"v3rpc/interceptor.go:182","msg":"request stats","start time":"2024-08-14T16:23:46.086429+0800","time spent":"116.966µs","remote":"10.153.108.8:44264","response type":"/etcdserverpb.KV/Put","request count":1,"request size":14,"response count":0,"response size":0,"request content":"key:\"test\" value_size:4 prev_kv:true "}
{"level":"info","ts":"2024-08-14T16:23:46.087349+0800","caller":"zapgrpc/zapgrpc.go:174","msg":"[transport] [server-transport 0xc0016ba340] Closing: EOF"}
{"level":"info","ts":"2024-08-14T16:23:46.087429+0800","caller":"zapgrpc/zapgrpc.go:174","msg":"[transport] [server-transport 0xc0016ba340] loopyWriter exiting with error: transport closed by client"}
{"level":"debug","ts":"2024-08-14T16:23:46.284641+0800","caller":"etcdserver/server.go:2198","msg":"Applying entries","num-entries":1}
{"level":"debug","ts":"2024-08-14T16:23:46.28468+0800","caller":"etcdserver/server.go:2201","msg":"Applying entry","index":19146857,"term":10,"type":"EntryNormal"}
{"level":"debug","ts":"2024-08-14T16:23:46.284692+0800","caller":"etcdserver/server.go:2261","msg":"apply entry normal","consistent-index":19146856,"entry-index":19146857,"should-applyV3":true}
{"level":"debug","ts":"2024-08-14T16:23:46.28471+0800","caller":"etcdserver/server.go:2288","msg":"applyEntryNormal","raftReq":"header:<ID:15880977958643859726 > authenticate:<name:\"linyujun\" simple_token:\"SWECtbxJwjkaTwYs\" > "}
{"level":"debug","ts":"2024-08-14T16:23:46.284808+0800","caller":"auth/store.go:317","msg":"authenticated a user","user-name":"linyujun","token":"SWECtbxJwjkaTwYs.19146856"}
```
We can find that the token `SWECtbxJwjkaTwYs.19146856` is generated after PUT request authentication

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

etcd Version: 3.5.14    

Git SHA: bf51a53a7    

Go Version: go1.21.10    

Go OS/Arch: linux/amd64    

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

data-dir: '../data'
name: 'node1'

heartbeat-interval: 1000 
election-timeout: 5000

listen-peer-urls: http://x.x.x.x:16380
listen-client-urls: http://x.x.x.x:16379

initial-cluster-state: 'new'
initial-cluster-token: 'xxx-test-etcd-cluster'
advertise-client-urls: http://x.x.x.x:16379
initial-advertise-peer-urls: http://x.x.x.x:16380
initial-cluster: node1=http://x.x.x.x:16380,node2=http://x.x.x.x:16380,node3=http://x.x.x.x:16380
auto-compaction-mode: periodic
auto-compaction-retention: 20m

max-txn-ops: 40000

max-request-bytes: 10485760
quota-backend-bytes: 8589934592

> config of node2 and node3 are similar to the above.

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

+------------------+---------+-------+----------------------------+----------------------------+
|        ID        | STATUS  | NAME  |         PEER ADDRS         |        CLIENT ADDRS        |
+------------------+---------+-------+----------------------------+----------------------------+
| 1e1608112c13dc64 | started | node3 | http://ip1:16380 | http://ip1:16379 |
| c94c3fe9389742a9 | started | node1 |  http://ip2:16380 |  http://ip2:16379 |
| ceec693a583d2500 | started | node2 | http://ip3:16380 | http://ip3:16379 |
+------------------+---------+-------+----------------------------+----------------------------+

+---------------------+------------------+---------+---------+-----------+-----------+------------+
|      ENDPOINT       |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+---------------------+------------------+---------+---------+-----------+-----------+------------+
|  ip2:16379 | c94c3fe9389742a9 |  3.5.14 |  1.4 GB |     false |         8 |   19146684 |
| ip3:16379 | ceec693a583d2500 |  3.5.14 |  1.4 GB |     false |         8 |   19146685 |
| ip1:16379 | 1e1608112c13dc64 |  3.5.14 |  1.4 GB |      true |         8 |   19146686 |
+---------------------+------------------+---------+---------+-----------+-----------+------------+

**Comment by ahrtr** [comment]
Thanks for raising this issue, which I can confirm is a valid issue.

The root cause is the authentication process is processed via raft; but the validation on the token is performed on the API layer, and it isn't guarded by linearizable check. It means that when the etcdserver (node2 in your example) might have't finished the previous authentication process when it receives next Put request, accordingly you see the "invalid auth token" error.

The `applyWait.Wait` (see below) can mitigate this issue, but it can't completely resolve this especially when there is big latency between members communication.
https://github.com/etcd-io/etcd/blob/c147425c519652014df09325692a063e07fc69f2/server/etcdserver/server.go#L359

Please note that the simple token isn't recommended for production, and it's also stateful. It's recommended to use JWT token in production.

If you want to continue to use simple token, one simple workaround is to retry (e.g. up to 3 times) when you receive an "`invalid auth token`" error.

We may not spend too much effort to resolve this issue, but of course we need to update the document to clarify this.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, need to confirm which area of docs we should update for this to make it easier for a new contributor to pick up. We cover simple auth in a few places currently:

- https://etcd.io/docs/v3.5/learning/design-auth-v3/#two-types-of-tokens-simple-and-jwt 

> There are two kinds of token types: simple and JWT. The simple token isn’t designed for production use cases. Its tokens aren’t cryptographically signed and servers must statefully track token-user correspondence; it is meant for development testing. JWT tokens should be used for production deployments since it is cryptographically signed and verified. From the implementation perspective, JWT is stateless. Its token can include metadata including username and revision, so servers don’t need to remember correspondence between tokens and the metadata.

- https://etcd.io/docs/v3.5/op-guide/authentication/authentication/

- https://etcd.io/docs/v3.5/op-guide/configuration/#auth

@ahrtr can you please confirm where you wanted these docs updates to be made, or are we talking about clarifying comments in code? Thanks

**Comment by ahrtr** [comment]
@jmhbnz we definitely need to update docs instead of adding comments in source code. 

> https://etcd.io/docs/v3.5/learning/design-auth-v3/#two-types-of-tokens-simple-and-jwt

Yes, we can update this section to clarify this known issue. Something like below,

```
Note that there is a known issue (add link to this issue) on simple token. Since etcdsever resolves in the API layer and isn't guarded by linearizable check, and also simple token is stateful. So an etcd member may haven't processed previously authentication request before it receives next request, accordingly it will return an "invalid auth token" error back to client.
```

**Comment by akshaym-3255** [comment]
@jmhbnz I am interested to working on this. can you assign this to me.

**Comment by jmhbnz** [comment]
Awesome, thanks!

/assign @akshaym-3255

**Comment by jmhbnz** [comment]
Documentation has been updated, many thanks @akshaym-3255 🙏🏻 

@ahrtr I would lean towards closing this now, as I don't believe it's a priority to review design for simple token auth any time soon, do you agree?  We can always revisit in future if there is a desire to revisit simple token auth.

**Comment by ahrtr** [comment]
OK, Closing

**Comment by nic-chen** [comment]
Hi, @ahrtr 

Since The simple token isn’t designed for production, why is the simple token still used by default? Are there any special considerations? Thanks.

**Comment by ahrtr** [comment]
> Hi, [@ahrtr](https://github.com/ahrtr)
> 
> Since The simple token isn’t designed for production, why is the simple token still used by default? Are there any special considerations? Thanks.

@nic-chen 

I think it's easier / simpler to do a quick test/evaluation with the simple token as it doesn't require any setup on the server side.

Note by default, the auth isn't enabled at all. Also not all users enable auth in their production environment. i.e. AFAIK, Kubernetes doesn't enable the etcd auth.
