### ISSUE TITLE
How to fix etcd cluster misconfigured error

### ISSUE THREAD

**Issue by lijie123bes** [etcd-io/etcd#18473]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Have two servers : pg1: 10.80.80.195 and pg2: 10.80.80.196
I'm trying to run like this :

pg1 server :
etcd --name infra0 --initial-advertise-peer-urls http://10.80.80.195:2380   --listen-peer-urls http://10.80.80.195:2380   --listen-client-urls http://10.80.80.195:2379,http://127.0.0.1:2379   --advertise-client-urls http://10.80.80.195:2379   --initial-cluster-token etcd-cluster-1   --initial-cluster infra0=http://10.80.80.195:2380,infra1=http://10.80.80.196:2380   --initial-cluster-state new

pg2 server :
etcd --name infra1 --initial-advertise-peer-urls http://10.80.80.196:2380   --listen-peer-urls http://10.80.80.196:2380   --listen-client-urls http://10.80.80.196:2379,http://127.0.0.1:2379   --advertise-client-urls http://10.80.80.196:2379   --initial-cluster-token etcd-cluster-1   --initial-cluster infra0=http://10.80.80.195:2380,infra1=http://10.80.80.196:2380   --initial-cluster-state new

When trying to cherck health state on pg1:
etcdctl cluster-health
have an error :
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://127.0.0.1:2379 exceeded header timeout
; error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

error #0: client: endpoint http://127.0.0.1:2379 exceeded header timeout
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

### What did you expect to happen?

just gives a healthy result.

### How can we reproduce it (as minimally and precisely as possible)?

none

### Etcd version (please run commands below)

<details>

```console
etcd Version: 3.2.0
Git SHA: 66722b1
Go Version: go1.8.3
Go OS/Arch: linux/amd64
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
etcd 3.3.x is out of support. 

Please also raise question in https://github.com/etcd-io/etcd/discussions.

Also you can diagnose the etcd cluster using https://github.com/ahrtr/etcd-diagnosis
