### ISSUE TITLE
Include and stabilize `experimental-compaction-sleep-interval` flag in releases

### ISSUE THREAD

**Issue by JalinWang** [etcd-io/etcd#18481]
### What would you like to be added?

Two parameters govern the auto compaction process: `experimental-compaction-batch-limit` and `experimental-compaction-sleep-interval`. Despite being added three years ago in this [PR](https://github.com/etcd-io/etcd/pull/13018) [commit](https://github.com/etcd-io/etcd/commit/05674c87fb73980d5af67d00be62405c2fc49ddc), the sleep interval flag has yet to be included in any releases. Meanwhile, the batch limit flag is under stabilization consideration in [issue](https://github.com/etcd-io/etcd/issues/13777), and I propose stabilizing the `experimental-compaction-sleep-interval` as well.

### Why is this needed?

Compaction significantly affects service response time. Distributing pressure more evenly is desired, where these two params serve. While workarounds exist currently, retention window size has limit flexibility and it's better to utilize the built-in mechanism over additional independent maintenance scripts.

![image](https://github.com/user-attachments/assets/bb59755b-43ba-4ce3-8d58-58d9ee010463)
![image](https://github.com/user-attachments/assets/22fbec54-e7e7-4a5c-bc0a-146f81120cbe)

**Comment by ivanvc** [comment]
Discussed during the fortnightly triage meeting. I'll review the PR.

**Comment by JalinWang** [comment]
> Discussed during the fortnightly triage meeting. I'll review the PR.

Thanks for the update! I'm looking forward to your feedback~

Also, the following PR for bbolt can greatly improve etcd performance in our scenario where free space is considerable (dbSize - dbSizeInUse) in some time. If possible, could you also mention [the release for 1.4.0](https://github.com/etcd-io/bbolt/issues/553#issuecomment-1680335116)? The bbolt1.4.0 alpha0 released in Jan and alpha1 released May. According to this pace, the next version could be released in Sept?  That could be a great step towards the stable 1.4.0 😄 

```
## v1.4.0-alpha.0(2024-01-12) change log
- [Record the count of free page to improve the performance of hashmapFreeCount]
([https://github.com/etcd-io/bbolt/pull/585 ](https://github.com/etcd-io/bbolt/pull/585)).
```

Attachment: our pprof result screenshot ( dbSize ~11GB, dbSizeInUse ~6GB)
![image](https://github.com/user-attachments/assets/3623d466-5c91-455f-a3bb-d7dc0949072f)

**Comment by ivanvc** [comment]
@JalinWang, can you help with the CHANGELOG pull request to mention #18514?

Regarding the bbolt change, I'd suggest opening an issue on its repository.

Thanks!

**Comment by JalinWang** [comment]
> @JalinWang, can you help with the CHANGELOG pull request to mention #18514?

Sorry for the late PR. Plz review: https://github.com/etcd-io/etcd/pull/18556 :)

> Regarding the bbolt change, I'd suggest opening an issue on its repository.

okkkkk~

**Comment by elias-dbx** [comment]
Hello, is there any guidance on how to tweak `--experimental-compaction-batch-limit` and `--experimental-compaction-sleep-interval` for large clusters?

We have ~40GB etcd databases which create around 2000 new revisions per second. We run compaction once every 30 minutes but see availability drops due to pauses during compaction time.

**Comment by JalinWang** [comment]
> Hello, is there any guidance on how to tweak `--experimental-compaction-batch-limit` and `--experimental-compaction-sleep-interval` for large clusters?

Hi~
Personally, I suggest adjusting --experimental-compaction-sleep-interval to a higher value and decreasing --experimental-compaction-batch-limit to distribute the compaction load evenly across the whole auto compaction interval (typcial 1h) . This should minimize availability drops due to compaction pauses. 

I found an article online [link](https://developer.aliyun.com/article/786245) (in Chinese, use google translater maybe) about optimizeing etcd for large clusters(~10k nodes), which mentioned the "compaction-sleep-interval" param. However, it doesn't provide specific guidance on tuning these two parameters. If you come across any other resources, please share with me :)

**Comment by elias-dbx** [comment]
Once we upgrade to 3.5.16 I will try tweaking the compaction sleep interval and report back. We run up to 15k nodes in our k8s clusters.

**Comment by ivanvc** [comment]
I'll close this issue as the backport is complete and is already part of the 3.5.16 release. Please reopen if you feel there's more work to do.

Thanks, @JalinWang, for your contribution.
