### ISSUE TITLE
Bump bbolt to 1.3.11 for both 3.4 and 3.5

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#18480]
### What would you like to be added?

[bbolt v1.3.11](https://github.com/etcd-io/bbolt/releases/tag/v1.3.11) is available now.

### Why is this needed?

Bump to the latest patch version.

**Comment by ahrtr** [comment]
/assign @akshaym-3255 

Thanks

**Comment by ahrtr** [comment]
@akshaym-3255 could you update changelog for both 3.5 and 3.4?

or leave it to @ivanvc or @jmhbnz to update changelog when they release next patches?

**Comment by akshaym-3255** [comment]
update changelog here https://github.com/etcd-io/etcd/pull/18512

**Comment by ahrtr** [comment]
all done. Thanks @akshaym-3255
