### ISSUE TITLE
cannot retrieve the same struct after setting in endpoint and added to etcd by endpointManager

### ISSUE THREAD

**Issue by cruvie** [etcd-io/etcd#18520]
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

```go

import (
	"context"
	clientv3 "go.etcd.io/etcd/client/v3"
	"go.etcd.io/etcd/client/v3/naming/endpoints"
	"log"
	"testing"
	"time"
)

type MyMeta struct {
	Name string
}

func TestBug(t *testing.T) {
	client, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"http://127.0.0.1:2379"},
		DialTimeout: 5 * time.Second,
		Username:    "root",
		Password:    "root",
	})
	if err != nil {
		panic(err)
	}
	endpointManager, err := endpoints.NewManager(client, "mytarget")
	if err != nil {
		panic(err)
	}
	info := MyMeta{Name: "myname"}
	endpoint := endpoints.Endpoint{
		Addr:     "127.0.0.1:6666",
		Metadata: info,//custom meta struct
	}

	err = endpointManager.AddEndpoint(
		context.Background(),
		"mytarget/service",
		endpoint)
	if err != nil {
		panic(err)
	}
	endpointMap, err := endpointManager.List(context.Background())
	if err != nil {
		panic(err)
	}
	for _, v := range endpointMap {
                //why  ok is false?
		out, ok := v.Metadata.(MyMeta)
		log.Println(out, ok) // {} false
	}
}
// but this works fine
func TestConvert(t *testing.T) {
	info := MyMeta{Name: "myname"}

	meta := endpoints.Endpoint{
		Addr:     "127.0.0.1:6666",
		Metadata: info,
	}
	out, ok := meta.Metadata.(MyMeta)
	log.Println(out, ok) //{myname} true
}
```

### What did you expect to happen?

use 
```go
out, ok := v.Metadata.(MyMeta)
```
to retrieve meta stored in the endpoint

### How can we reproduce it (as minimally and precisely as possible)?

run the code above
1 add a endpoint with a custom struct meta
2 get the endpoint and retrieve the meta by assertion

### Etcd version (please run commands below)

<details>

```console
etcd version
v3.5.13

go sdk version
go.etcd.io/etcd/client/v3 v3.5.15
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
This isn't an etcd issue; instead, it's a golang problem.

When you `json.Marshal` a struct, and then `json.Unmarshal` the data and assign to a variable of `any` type, you will lose the original struct type, because `json.Unmarshal` can only generate a generic `map[string]interface{} ` in such case.

You can resolve this "issue" using code something like below,
```
		if m, ok := v.Metadata.(map[string]any); ok {
			var meta MyMeta
			meta.Name = m["Name"].(string)
			log.Println(meta)
		}
```

**Comment by cruvie** [comment]
thank you @ahrtr, I find a better way to retrieve data from endpoint.Metadata
```go
        bytes, err := json.Marshal(endpoint.Metadata)
	if err != nil {
		return err
	}
        var meta MyMeta
	err = json.Unmarshal(bytes, &meta)
	if err != nil {
		return err
	}
```

**Comment by ahrtr** [comment]
> thank you @ahrtr, I find a better way to retrieve data from endpoint.Metadata
> 
> ```go
>         bytes, err := json.Marshal(endpoint.Metadata)
> 	if err != nil {
> 		return err
> 	}
>         var meta MyMeta
> 	err = json.Unmarshal(bytes, &meta)
> 	if err != nil {
> 		return err
> 	}
> ```

Yes, it works. But It has an extra `json.Marshal & json.Unmarshal`, so it will have performance penalty.
