### ISSUE TITLE
Python etcd3 client library is not able to read ca cert

### ISSUE THREAD

**Issue by oshi36** [etcd-io/etcd#18535]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I am trying to take a snapshot of etcd via etcd3 python client library and my code looks like this :

 ```
 import etcd3
  etcd = etcd3.client(
                  host='xx.xx.xx.xx',
                  port='2379',
                  cert_cert='/etc/kubernetes/pki/etcd/server.crt',
                  cert_key='/etc/kubernetes/pki/etcd/server.key',
                  ca_cert='/etc/kubernetes/pki/etcd/ca.crt'
                )
            print("Client connected:", etcd)
            etcd.snapshot('etcd_backup.db')
            print("Snapshot taken successfully.")
    except Exception as e:
             print("Error:", e)
```
          
I am getting this error 
<img width="507" alt="image" src="https://github.com/user-attachments/assets/1a750de8-0f96-425c-a4cb-e1150b8b3191">

And if I remove the ca_cert path then I get `ETCD connection failed`.

### What did you expect to happen?

I expect etcd3 client to recognize ca cert and get connected to etcd

### How can we reproduce it (as minimally and precisely as possible)?

Install `pip install etcd3` python etcd client library

### Etcd version (please run commands below)

<img width="606" alt="image" src="https://github.com/user-attachments/assets/8594befa-1e1d-43b4-b067-fe7156298cf4">

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ivanvc** [comment]
Hi, @oshi36. Thanks for opening this issue. However, we don't support Python's etcd3 library. By checking [PyPI](https://pypi.org/project/etcd3/), it looks like its repository is https://github.com/kragniz/python-etcd3.

I suggest opening an issue there so that you can get support from the maintainers of that project.
