### ISSUE TITLE
`scripts/release.sh` is not signing off release version bump commits

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/etcd#18581]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

For a long time now `scripts/release.sh` has been used on the `release-3.5` branch to automate bumping versions, committing this bump and pushing it to the git remote.

Recent examples of these partially-automated commits are:

|Version|Link|
|-----------|------|
| `v3.5.16` | https://github.com/etcd-io/etcd/commit/f20bbadd404b57c776d1e8876cefd1ac29b03fb5 |
| `v3.5.15` | https://github.com/etcd-io/etcd/commit/9a5533382d84999e4e79642e1ec0f8bfa9b70ba8 |
| `v3.5.14` | https://github.com/etcd-io/etcd/commit/bf51a53a7e0452a7e44783c24ec048e6981dd2d7 |
| `v3.5.13` | https://github.com/etcd-io/etcd/commit/c9063a0dcd963c89bea870eaef1d6d3af40ae26d |
| `v3.5.12` | https://github.com/etcd-io/etcd/commit/e7b3bb6ccac840770f108ef9a0f013fa51b83256 |

### What did you expect to happen?

These commits should be signed off for Developer Certificate of Origin reasons.

### How can we reproduce it (as minimally and precisely as possible)?

Produce a release with `scripts/release.sh` on the `release-3.5` branch.

### Anything else we need to know?

This has not impacted `release-3.4` branch as we have had a historic practice of creating release commits and tags manually on that branch.

The relevant section of code is: https://github.com/etcd-io/etcd/blob/9aaaafe8d9b227f8401e13bda658fa35df39fbb8/scripts/release.sh#L151-L159

We should be adding the `--signoff` flag to the `git commit` command.

**Comment by jmhbnz** [comment]
/assign

cc @serathius, @ahrtr for your awareness. Let's fix this before our next set of releases.

**Comment by ivanvc** [comment]
@jmhbnz, jfyi, the code is also in the main branch (although there haven't been any recent v3.6 releases, it's affected, too).

Ref:
https://github.com/etcd-io/etcd/blob/f0246a9f84f7839825d68511ac65eb52eb24e81d/scripts/release.sh#L157

**Comment by ahrtr** [comment]
Thanks for the catch!

**Comment by jmhbnz** [comment]
Closed backport completed in https://github.com/etcd-io/etcd/pull/18599
