### ISSUE TITLE
Manage credentials using 1Password

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#18611]
### What would you like to be added?

Currently credentials (i.e. `quay.io` password) are not properly managed & shared between maintains. Propose to using 
[1Password’s free open source plan](https://github.com/1Password/for-open-source) to manage & share all such credentials

### Why is this needed?

To improve security

**Comment by ahrtr** [comment]
cc @ivanvc @jmhbnz @serathius

**Comment by ivanvc** [comment]
This sounds reasonable; thanks for raising this, @ahrtr. I don't have much expertise with password management tools. I personally use Password Store, but I'd consider it out of the scope. The other CNCF suggestion is to use Keybase, but in my experience, after they were acquired by Zoom, the product support was subpar.

So, 1Password for Open Source sounds good to me.

**Comment by jmhbnz** [comment]
Sounds good to me. Would be great to have proper management in place rather than sharing person to person.

**Comment by ahrtr** [comment]
Raised an issue https://github.com/1Password/for-open-source/issues/1016
