### ISSUE TITLE
add key size histogram metrics

### ISSUE THREAD

**Issue by gojoy** [etcd-io/etcd#18646]
### What would you like to be added?

add etcd_debugging_mvcc_key_size_bucket histogram metric. 

### Why is this needed?

For better observability, we can observe the distribution of key sizes  and detect an increase in key size at the first time in the etcd cluster.

**Comment by gojoy** [comment]
please assign to me

**Comment by gojoy** [comment]
@jmhbnz Hi. Could you  assign it to me? thinks

**Comment by gojoy** [comment]
I found that this problem can be solved by using `irate(etcd_debugging_mvcc_total_put_size_in_bytes{}[$__interval]) / irate(etcd_mvcc_put_total{}[$__interval])`. Therefore, there is no need to add new functions anymore. What do you think? @jmhbnz

**Comment by jmhbnz** [comment]
Closing as we have an alternative approach, thanks @gojoy
