### ISSUE TITLE
Document deflaking process

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18650]
### What would you like to be added?

This is a follow-up to a comment from our latest triage meeting (September 26th, 2024).

We've been ensuring that tests are flakes by running `stress` against tests. However, no official documentation exists on how a contributor must run it. There are references in the community meeting document and traces in some pull request comments.

We should add a document in `Documentation/contributor-guide` so we can refer contributors who want to help identify flakes.

### Why is this needed?

To improve the contributor experience and our documentation stance.

**Comment by lucasrod16** [comment]
Just responded to a comment on this topic: https://github.com/etcd-io/etcd/issues/18585#issuecomment-2380249258

@ghouscht expressed interest in adding this information to the contributing guide

**Comment by ivanvc** [comment]
Oh, I didn't realize we had a section in `CONTRIBUTING.md`. We just need to improve it. Thanks, @lucasrod16.

@ghouscht, can you comment on this issue so we can assign it to you? (You can also comment `/assign`, and the k8s bot will assign it to you).

Thanks, team.

**Comment by ivanvc** [comment]
@ghouscth, refer to:

* https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit?pli=1#heading=h.e48w90nud901
* https://github.com/etcd-io/etcd/pull/17983#discussion_r1600895216
* https://gist.github.com/liggitt/6a3a2217fa5f846b52519acfc0ffece0#running-unit-tests-to-reproduce-flakes

**Comment by ghouscht** [comment]
/assign

Thank you, will look into this today!
