### ISSUE TITLE
workflow `trivy-scan` fails due to `TOOMANYREQUESTS`

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#18671]
### Which Github Action / Prow Jobs are flaking?

Release/trivy-scan keeps failing from time to time.

```
2024-10-02T18:20:08Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: database download error: oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:2e2dbebf85b254a1008bef9312a32827978d7583376082eff2741551f01a7eb6: TOOMANYREQUESTS: retry-after: 805.675µs, allowed: 44000/minute
```

### Which tests are flaking?

workflow `trivy-scan` in release.yaml

### Github Action / Prow Job link

https://github.com/etcd-io/etcd/actions/runs/11149273467/job/30988049859

### Reason for failure (if possible)

The error appears to be caused by rate limiting.

**Comment by ahrtr** [comment]
cc @ivanvc @jmhbnz

**Comment by ivanvc** [comment]
It looks like there are more people affected by the GHCR's quota. Looking at Trivy's discussions, there are new posts in recent weeks: https://github.com/search?q=repo%3Aaquasecurity%2Ftrivy+toomanyrequests&type=discussions, and issues across the aquasecurity organization: https://github.com/search?q=org%3Aaquasecurity+TOOMANYREQUESTS&type=issues

This seems to be a possible solution: https://github.com/aquasecurity/trivy-action/issues/389#issuecomment-2385416577

**Comment by jmhbnz** [comment]
Backports completed, closing. Thanks @ivanvc for the quick fix 🙏

**Comment by ivanvc** [comment]
Thanks, @jmhbnz. I keep forgetting we have the cherry-pick command :sweat_smile:
