### ISSUE TITLE
Etcd doesn't provide a token refresh 

### ISSUE THREAD

**Issue by HamidIdifi** [etcd-io/etcd#18778]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

ETCD is no't supporting the regular OAUTH2 standards, and it's not provide a way to refresh the token automatically

### What did you expect to happen?

I expect ETCD to refresh the token for me the request will be successful

### How can we reproduce it (as minimally and precisely as possible)?

i send a request to the GrpcGateway to get a token:
```
curl -L http://dbtools-ops.oraclecorp.com:2379/v3/auth/authenticate \
  -X POST -d '{"name": "root", "password": "root"}'
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"6","raft_term":"2"},"token":"wwhspQQcNCzmFvEU.53"}%
```
and then i use that token to get the key:
it works fine:
```
curl -L http://dbtools-ops.oraclecorp.com:2379/v3/kv/range \
  -H 'Authorization: wwhspQQcNCzmFvEU.53' \
  -X POST -d '{"key": "Zm9v"}'                 
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"7","raft_term":"2"},"kvs":[{"key":"Zm9v","create_revision":"7","mod_revision":"7","version":"1","value":"YmFy"}],"count":"1"}%  
```    

after 5 min i send the same request, i get an invalid token:

```
curl -L http://dbtools-ops.oraclecorp.com:2379/v3/kv/range \
  -H 'Authorization: wwhspQQcNCzmFvEU.53' \
  -X POST -d '{"key": "Zm9v"}'
{"error":"etcdserver: invalid auth token","code":16,"message":"etcdserver: invalid auth token"}%
```

is there is a way so the token can be refrshed without sending a new request to get a new one.

### Etcd version (please run commands below)

VERSION:
	3.5.15

API VERSION:
	3.5

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
If you use etcd client SDK, it will automatically re-authenticate for you. If you use etcdctl command, then you have to take care of it yourself.

https://github.com/etcd-io/etcd/blob/18eb5c6881d43064f4559034bf12c3ef6ce89e4b/client/v3/retry_interceptor.go#L81

**Comment by HamidIdifi** [comment]
@ahrtr thanks for your response, i see that i can customize the ttl fo the token when running etcd, is that works with ETCD GrpcGateway as well:
https://etcd.io/docs/v3.5/op-guide/configuration/

i run it etcd --auth-token=simple --auth-token-ttl=60
and it doesn't work
