### ISSUE TITLE
ETCD frequently switches between hosts

### ISSUE THREAD

**Issue by smallemployees** [etcd-io/etcd#18783]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

"caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"2.11381069s","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/configmaps/test/ingress-controller-leader\" ","response":"","error":"etcdserver: leader changed"

### What did you expect to happen?

When the utilization rate of host resources is not high and the db is also small, how to locate it

### How can we reproduce it (as minimally and precisely as possible)?

When the utilization rate of host resources is not high and the db is also small, how to locate it

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```
3.5.4
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
`2.11381069s` is an indication that your environment is not good, i.e. terrible network delay or disk I/O

Refer to https://github.com/ahrtr/etcd-issues/blob/master/docs/troubleshooting/how_to_debug_performance_issue.md
