### ISSUE TITLE
Learners do not implement GRPC health checks

### ISSUE THREAD

**Issue by elias-dbx** [etcd-io/etcd#18801]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I was testing out the new experimental health checks: https://github.com/etcd-io/etcd/pull/17914

What I found is that if there was a learner in the cluster, the RPCs would fail with:
```
{"level":"warn","ts":"2024-10-05T01:35:11.309621Z","logger":"etcd-client","caller":"io_etcd_go_etcd_client_v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0011bc780/10.247.133.150:5000","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection active but received health check RPC error: rpc error: code = Unavailable desc = etcdserver: rpc not supported for learner"}
```

I believe this comes from here where we modify what RPCs learners implement:
https://github.com/etcd-io/etcd/blob/7cded36ba87fa2308d76e8f3eb0aeb06b21c0fb6/server/etcdserver/api/v3rpc/util.go#L142

Should we allow learners to receive grpc health checks?

### What did you expect to happen?

Learners do not cause RPCs to fail when `experimental-stop-grpc-service-on-defrag` is enabled.

### How can we reproduce it (as minimally and precisely as possible)?

Enable `experimental-stop-grpc-service-on-defrag`, make a learner, create an etcd client with the following grpc service config:
```
`{"loadBalancingPolicy": "round_robin", "healthCheckConfig": {"serviceName": ""}}`
```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
v3.5.14
$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
cc @tjungblu @chaochn47 do you have time to take a look at this ticket? thx

**Comment by tjungblu** [comment]
> Learners do not cause RPCs to fail when experimental-stop-grpc-service-on-defrag is enabled.

are you sure that is related? I would assume you just have a learner member in your client and you hit it with a linearized read/write call.

**Comment by ahrtr** [comment]
Thanks @tjungblu for the comment.

@elias-dbx if you still have any questions, please raise them in [discussions](https://github.com/etcd-io/etcd/discussions).
