### ISSUE TITLE
etcdserver: data corruption detected, unable to start etcd member

### ISSUE THREAD

**Issue by rockswe** [etcd-io/etcd#18881]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

After a sudden power outage in our on-premises data center, our Kubernetes cluster failed to recover upon reboot. The etcd server could not start and logged the following error: `etcdserver: data corruption detected, unable to start etcd member`
So the Kubernetes API server was unavailable, and the entire cluster became non-operational.

### What did you expect to happen?

I expected etcd to handle the abrupt shutdown gracefully and recover its data upon restart which allows the k8s control plane to become available again.

### How can we reproduce it (as minimally and precisely as possible)?

While I think this issue is rare and difficult to reproduce, the following steps simulate a similar scenario:
Set up a single-node Kubernetes cluster using kubeadm, deploy some resources to populate etcd, simulate an abrupt power loss, attempt to restart etcd, check the etcd logs for the data corruption error

### Anything else we need to know?

Ubuntu 20.04.6 LTS (Focal Fossa) 
Kernel Version: 5.4.0-91-generic

### Etcd version (please run commands below)

etcd Version: 3.5.0
Git SHA: Not provided
Go Version: go1.16.5
Go OS/Arch: linux/amd64

### Etcd configuration (command line flags or environment variables)

--name=etcd-node1
--data-dir=/var/lib/etcd
--listen-peer-urls=https://192.168.1.10:2380
--listen-client-urls=https://192.168.1.10:2379
--advertise-client-urls=https://192.168.1.10:2379
--initial-advertise-peer-urls=https://192.168.1.10:2380
--initial-cluster=etcd-node1=https://192.168.1.10:2380,etcd-node2=https://192.168.1.11:2380,etcd-node3=https://192.168.1.12:2380
--initial-cluster-state=existing
--client-cert-auth=true
--trusted-ca-file=/etc/etcd/ssl/ca.pem
--cert-file=/etc/etcd/ssl/server.pem
--key-file=/etc/etcd/ssl/server-key.pem
--peer-client-cert-auth=true
--peer-trusted-ca-file=/etc/etcd/ssl/ca.pem
--peer-cert-file=/etc/etcd/ssl/peer.pem
--peer-key-file=/etc/etcd/ssl/peer-key.pem

Environment Variables:
ETCD_UNSUPPORTED_ARCH=amd64

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

Since the etcd member fails to start, runtime debug information is limited. Here are the logs from the last attempted start (IP addresses obfuscated):

Nov 11 10:15:00 etcd-node1 etcd[1234]: etcdserver: starting server... [version: 3.5.0, cluster version: to_be_decided]
Nov 11 10:15:00 etcd-node1 etcd[1234]: rafthttp: starting peer 1234567890abcdef...
Nov 11 10:15:01 etcd-node1 etcd[1234]: etcdserver: data corruption detected, unable to start etcd member
Nov 11 10:15:01 etcd-node1 etcd[1234]: member 1234567890abcdef has already been bootstrapped
Nov 11 10:15:01 etcd-node1 etcd[1234]: panic: corrupted data detected

**Comment by ahrtr** [comment]
> etcd Version: 3.5.0

3.5.0 is known to have corruption issues. Please try the latest version, and also provide the complete log & call stack next time when you run into the issue
