### ISSUE TITLE
Enable prow postsubmit jobs

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18885]
### What would you like to be added?

After the prow migration, we deleted the CI checks against the main branch. We should restore some of the jobs as postsubmit jobs.

Refer to our current [presubmit job configurations](https://github.com/kubernetes/test-infra/blob/adfebac75b6b02e9fc284fc38eeece3e16f616d0/config/jobs/etcd/etcd-presubmits.yaml) and [postubmit's](https://github.com/kubernetes/test-infra/blob/adfebac75b6b02e9fc284fc38eeece3e16f616d0/config/jobs/etcd/etcd-postsubmits.yaml)

- [x] post-etcd-verify (based on pull-etcd-verify)
- [x] post-etcd-govulncheck (based on pull-etcd-govulncheck)

### Why is this needed?

To improve the code quality, and ensure the main branch doesn't have static analysis issues and vulnerabilities.

**Comment by jmhbnz** [comment]
Agree the two listed jobs are a great start let's focus on those for now.

**Comment by samuelbartels20** [comment]
@ivanvc Please assign me to this ticket, I will get it done

**Comment by ahrtr** [comment]
/assign @samuelbartels20 

Thank you!

**Comment by samuelbartels20** [comment]
@ivanvc @ahrtr @jmhbnz Please i have raised a PR for this issue

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, https://github.com/kubernetes/test-infra/pull/33806 is now merged so @ivanvc 
 should we close this issue now as the new jobs appear to be running nicely https://testgrid.k8s.io/sig-etcd-postsubmits?

**Comment by ivanvc** [comment]
Ah, thank you. I wasn't aware of that PR. Closing now, thanks, @samuelbartels20.
