### ISSUE TITLE
Enable grpc interceptors in serve Context like userHandlers are enabled

### ISSUE THREAD

**Issue by nicolaslopezbravo** [etcd-io/etcd#18896]
### What would you like to be added?

embed's [serve](https://github.com/etcd-io/etcd/blob/main/server/embed/serve.go#L205) creates a new v3rpc grpc server but doesn't make use of the [interceptor option](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/api/v3rpc/grpc.go#L48-L51).  Could serve context have userInterceptors similar to [userHandlers](https://github.com/etcd-io/etcd/blob/main/server/embed/serve.go#L65) so the user can add & pass in interceptors to the grpc server?

### Why is this needed?

Extends existing capability, allows for user to add all sorts of useful middleware, monitoring, auth, etc.

**Comment by nicolaslopezbravo** [comment]
CC @ahrtr just want to check if this is reasonable, I can implement it if necessary

**Comment by jmhbnz** [comment]
Hey @nicolaslopezbravo thanks for your question - for etcd 3.6 we need to address the remaining items in this roadmap: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/roadmap.md#v360

I'll close this now given the feature is ready and will be published in 3.6.
