### ISSUE TITLE
Etcd writing error in tests about missing confstate

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#18978]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Periodic failures in https://testgrid.k8s.io/sig-etcd-periodics#ci-etcd-e2e-amd64
`TestNoErrorLogsDuringNormalOperations/three_node_cluster_with_auto_tls_(peers)` is failing with:

```
Messages:   	error level log message found: {"level":"error","ts":"2024-11-16T20:58:00.500222Z","caller":"version/monitor.go:120","msg":"failed to update storage version","cluster-version":"3.6.0","error":"cannot detect storage schema version: missing confstate information","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver/version.(*Monitor).UpdateStorageVersionIfNeeded\n\tgo.etcd.io/etcd/server/v3/etcdserver/version/monitor.go:120\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).monitorStorageVersion\n\tgo.etcd.io/etcd/server/v3/etcdserver/server.go:2286\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).GoAttach.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/server.go:2467"}
```

Started at least before 16 Nov based on testgrid history
Example: 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-etcd-e2e-amd64/1857887040968855552

### What did you expect to happen?

Etcd should not write errors during startup

### How can we reproduce it (as minimally and precisely as possible)?

Return test

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment]
cc @ghouscht @ahrtr

**Comment by ghouscht** [comment]
I‘ll have a look later this week, thanks for notifying.

/assign

**Comment by ahrtr** [comment]
@ghouscht Please follow https://github.com/etcd-io/etcd/pull/19040#issuecomment-2539173800 to update the test case. Please let me know if you don't have the bandwidth, so that others can take over.  Recently I see that lots of failures were caused by this, so I really want to get it resolved asap.
