### ISSUE TITLE
Possible missing nil checks

### ISSUE THREAD

**Issue by Bbulatov** [etcd-io/etcd#19015]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

After having been compared to a nil value at backend.go:515, pointer 'b.lg' is passed as implicit 'this' parameter in call to function 'Error' at backend.go:545 or pointer 'b.lg' is passed as implicit 'this' parameter in call to function 'Fatal' at backend.go:532. 
```
if b.lg != nil {
		b.lg.Info(
			"defragmenting",
			zap.String("path", dbp),
			zap.Int64("current-db-size-bytes", size1),
			zap.String("current-db-size", humanize.Bytes(uint64(size1))),
			zap.Int64("current-db-size-in-use-bytes", sizeInUse1),
			zap.String("current-db-size-in-use", humanize.Bytes(uint64(sizeInUse1))),
		)
	}

	defer func() {
		// NOTE: We should exit as soon as possible because that tx
		// might be closed. The inflight request might use invalid
		// tx and then panic as well. The real panic reason might be
		// shadowed by new panic. So, we should fatal here with lock.
		if rerr := recover(); rerr != nil {
			b.lg.Fatal("unexpected panic during defrag", zap.Any("panic", rerr))
		}
	}()

	// Commit/stop and then reset current transactions (including the readTx)
	b.batchTx.unsafeCommit(true)
	b.batchTx.tx = nil

	// gofail: var defragBeforeCopy struct{}
	err = defragdb(b.db, tmpdb, defragLimit)
	if err != nil {
		tmpdb.Close()
		if rmErr := os.RemoveAll(tmpdb.Path()); rmErr != nil {
			b.lg.Error("failed to remove db.tmp after defragmentation completed", zap.Error(rmErr))
		}

		// restore the bbolt transactions if defragmentation fails
		b.batchTx.tx = b.unsafeBegin(true)
		b.readTx.tx = b.unsafeBegin(false)

		return err
	}
```
Please clarify whether verification is required in this case? Do you need to make any changes/corrections to the code?

### What did you expect to happen?

It might be worth adding additional checks for b.lg, if required.

### How can we reproduce it (as minimally and precisely as possible)?

Checking code

### Etcd version (please run commands below)

Latest

### Etcd configuration (command line flags or environment variables)

<details>

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

</details>

**Comment by ahrtr** [comment]
We can ensure that `newBackend` (see below) always returns a backend instance with a non-nil [lg](https://github.com/etcd-io/etcd/blob/3cf550d3a47ecee743eaadec1ebd183a0fa88383/server/storage/backend/backend.go#L129). If users pass in a nil lg, then we assign it a `zap.NewNop()`.

Afterwards, we can remove all the ugly nil check.


https://github.com/etcd-io/etcd/blob/3cf550d3a47ecee743eaadec1ebd183a0fa88383/server/storage/backend/backend.go#L185

**Comment by srujangit123** [comment]
Hey, I can take this up!
