### ISSUE TITLE
Inconsistency between etcd cluster version and etcdserver version?

### ISSUE THREAD

**Issue by MagicStarTrace** [etcd-io/etcd#19039]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I used the command to get the relevant version information and saw that the etcd cluster version is lower than the etcdserver version

```
curl -k -L http://localhost:2379/version
{"etcdserver":"3.5.16","etcdcluster":"3.5.0"}
```

### What did you expect to happen?

Shouldn't it be the same?

### How can we reproduce it (as minimally and precisely as possible)?

```
curl -k -L http://localhost:2379/version

```

### Etcd version (please run commands below)

etcd --version
etcd Version: 3.5.16
Git SHA: f20bbad
Go Version: go1.22.7
Go OS/Arch: linux/amd64

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment]
It's by design, the cluster version doesn't care about the patch version.
