### ISSUE TITLE
migrate experimental-txn-mode-write-with-shared-buffer flag to feature gate

### ISSUE THREAD

**Issue by siyuanfoundation** [etcd-io/etcd#19063]
### What would you like to be added?

Migrate `--experimental-txn-mode-write-with-shared-buffer` flag to use feature gate

Example for migrating an experimental flag: https://github.com/etcd-io/etcd/pull/18478

### Why is this needed?

part of https://github.com/etcd-io/etcd/issues/18023

**Comment by ishan16696** [comment]
I would like to pick this, can you please assign this to me @siyuanfoundation ?
