### ISSUE TITLE
v3 API: Support scripting instead of (or in addition to) range-read, CAS, CAD, multi-object transactions

### ISSUE THREAD

**Issue by inconshreveable** [etcd-io/etcd#3488]
I've encountered a number of applications where etcd would be an excellent fit if I were able to range query or atomically manipulate multiple keys. That makes the proposal for the v3 API very exciting!

While transactions and range queries are general purpose, I wonder whether you will increasingly encounter applications and use-cases which demand ever more specialized operations. For example, I have a use-case in which I would like to range-delete with a filter.

This would be possible with the new primitives but will not be optimal. For example, a range-delete will require a large number of client-server round trips to make the performance unacceptable.

Instead, would you consider adding the ability to write custom operations in a scripting language? This would provide an incredibly powerful, robust way to build completely customizable operations on top of etcd. It would allow high-performance multi-object operations without additional network round trips. It would have the possibility to transform etcd into an _application platform_ for distributed, highly-consistent applications.

This is the approach that Redis took with 2.6 when it added Lua scripting and it has seen a great amount of success and enabled an entire class of powerful new applications to be built on top of it.

Implementation-wise, there are high-quality pure-Go implementations of both the Javascript and Lua scripting languages that could be leveraged for this purpose.

Thoughts?

**Comment by xiang90** [comment]
@inconshreveable 

I like the idea and believe this is a really powerful feature. However, this would also complicate the design of the storage system and API. 

I would love to see more feedbacks/requirements from etcd community before considering to implement this feature. 

/cc @yichengq @philips @kelseyhightower

**Comment by inconshreveable** [comment]
@xiang90 

Absolutely, this would be a huge change of direction for etcd both in terms of API and implementation. A lot of feedback from the community would be warranted before pursuing this route.

I do not know the internals of etcd enough to understand the ramifications of the storage system, but I do think this could potentially *reduce* API surface area and make it simpler. If the core guarantee is that a script execution is a single operation in the raft log and guaranteed to execute atomatically, then higher level APIs like multi-object PUT (transactions), range queries, and CAS/CAD could all be removed from the core of etcd and instead be built as plugabble 'scripts'. For example, a hypothetical new user-defined implementation of CAS is very straightforward:

```js
// assume that a script defines an etcd client object called 'etcd'
// assume that a script receives its arguments in a dictionary object called 'args'
var resp = etcd.call("GET", args.key)
if resp.value == args.prevValue {
    etcd.call("PUT", args.key, args.newValue, {TTL: "10s"})
}
```

This single API `call` is also cribbed from the redis' design. They found that a single, permissive low-level interface between scripts and the execution engine allowed both easy forward-compatibility and simplicity of implementation because the existing command parsing and dispatch layer could be reused. Again, I'm unsure whether that would be similarly applicable for etcd's internals, but thought it worth mentioning.

**Comment by heyitsanthony** [comment]
I suspect this would be too slow to replace CAS-like primitives, but it would probably have benefits similar to stored procedures.

**Comment by jpbetz** [comment]
This issue appears hopelessly stale. Closing. Please reopen if there is interest in pursuing development.
