### ISSUE TITLE
 best effort snapshot pre-fetch when starting/restarting

### ISSUE THREAD

**Issue by jonboulle** [etcd-io/etcd#3715]

**Comment by xiang90** [comment]
Change this to unplanned. We have not found a problem for large snapshot so far. We will keep tracking this issue.

We want to per-fetch snapshot since it 100% has no side effect to raft pipeline. And if a node cannot catch up for some reason, we can ignore it early.

/cc @heyitsanthony

**Comment by philips** [comment]
Xiang, can you add more description into this? I understand what we are
trying to say with the title but it is unlikely everyone else does.

**Comment by jpbetz** [comment]
Closing this one.  Issues with snapshots is being discussed/address with https://github.com/etcd-io/etcd/issues/9161
