### ISSUE TITLE
createdIndex is a bit odd

### ISSUE THREAD

**Issue by philips** [etcd-io/etcd#407]
It is a bit suprising that a key without a TTL that never gets deleted has a createdIndex that always updates unless we add the prevExist=true invariant. 

```
$ curl -X PUT http://127.0.0.1:4001/v2/keys/asdf2 -d value=asdf -d prevExist=true
```

``` json
{
    "action": "update",
    "node": {
        "createdIndex": 214123,
        "key": "/asdf2",
        "modifiedIndex": 214125,
        "value": "asdf"
    }
}
```

```
$ curl -X PUT http://127.0.0.1:4001/v2/keys/asdf2 -d value=asdf
```

``` json
{
    "action": "set",
    "node": {
        "createdIndex": 214126,
        "key": "/asdf2",
        "modifiedIndex": 214126,
        "value": "asdf"
    }
}
```

**Comment by titanous** [comment]
Just ran into this again.

**Comment by xiang90** [comment]
@titanous PUT without a para is a `Set. Set` is `create` or `replace`. In both cases, `createIndex` should be updated. It is expected.

**Comment by titanous** [comment]
`replace` is not `create`, so if `Set` does a `replace` it should not update `createdIndex`

**Comment by xiang90** [comment]
@titanous Why not? What you want is `update`. just use `update`.

**Comment by titanous** [comment]
No, what I want is "set". Otherwise I have to do this: https://github.com/flynn/flynn/commit/f7a99cbe10cf3408c02ee7d9f016a4687e974fdf which is completely unexpected.

**Comment by xiang90** [comment]
@titanous What you are doing now is correct. If you do not want to increase the createIndex, you need to always try update first. It is not a work around. It is the right way to do it.

**Comment by yichengq** [comment]
@titanous The `set` is a combination of `create` and `replace`. If there is no key, it will create a key. If there is existing key, it will replace it with a new key (think it as remove then add back). In both cases, it will change the createIndex.
`update` changes only the modifiedIndex, but not createIndex.

**Comment by heavenlyhash** [comment]
There should be a path through this where one can idempotently create or update the value without changing the createIndex.

If the only way to do that involves two separate calls, that seems like a very strange workaround, and also begging for additional distributed races unless it's loaded in even more careful compare-and-swap type operations.  Idempotent 'put' without createIndex mutation seems like a very foundational operation and should not be that hard.

**Comment by xiang90** [comment]
@heavenlyhash 
> There should be a path through this where one can idempotently create or update the value without changing the createIndex.

This is not possible. 1) there is a modification index 2) create can never be idempotent in toady's v2 api.

What @titanous suggest might work.

To be clear, the api works as expected and documented. 

We are open to add a feature as you suggest. If you want, can you please send us a feature request?

**Comment by titanous** [comment]
@xiang90 AFAIK this behavior of createdIndex is not documented.

**Comment by xiang90** [comment]
@titanous 
https://github.com/coreos/etcd/blob/master/Documentation/api.md#changing-the-value-of-a-key
Here is an example that show the exact behavior. 

We document created.index above. If you feel we should do better for the doc, we are welcome for pull requests. And we will appreciate your help.

Again, we are not going to change the default behavior at this point. If you want the feature, send us feature request would be more helpful.
