### ISSUE TITLE
storage: watchStore.txnEnd does too many allocations

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#4816]
txnEnd does a lot of allocation even if there is no any watchers.

**Comment by xiang90** [comment]
It takes more than 4% of unnecessary CPU in critical path.

**Comment by ajityagaty** [comment]
@xiang90 Is this too involved for a newbie? If there is anything that I can help with please let me know.

**Comment by xiang90** [comment]
@ajityagaty Ha. No actually. 

So we have a benchmark function here
https://github.com/coreos/etcd/blob/master/mvcc/kvstore_bench_test.go#L25-L39

You can run the benchmark with --bench.mem option. It will print out the memory allocation per operation.

We can add another test with watchableStore by changing https://github.com/coreos/etcd/blob/master/mvcc/kvstore_bench_test.go#L27 to use https://github.com/coreos/etcd/blob/master/mvcc/watchable_store.go#L61 to create a watchable store.

Then we can run the benchmark again with --bench.mem. Then you might notice there are a few additional allocations.

We should be able to reduce the total allocations per operation. At least we should understand where these allocation comes from. Right now it is about 20 allocations per PUT, which is pretty extensive :(.

**Comment by ajityagaty** [comment]
@xiang90 Thanks for the pointers! I'll try to investigate this further.

**Comment by ajityagaty** [comment]
When I ran the memory benchmark I saw that using store directly led to 11 allocations/operation and using `watchableStore` led to 17 allocations/operations.

I tried to follow the call sequence when a `Put` is called. Internally a call to `mvcc.store.put` is anyway needed when we use either the `store` directly or a `watchableStore`. So until that point the number of allocations would be the same for both the cases.

We do the notifying work in `watchableStore.Put` case and that is where the additional allocations are taking place. So, I put in hack at [https://github.com/coreos/etcd/blob/master/mvcc/watcher_group.go#L85](https://github.com/coreos/etcd/blob/master/mvcc/watcher_group.go#L85) to return immediately if the length of `wg.keyWatchers` is 0. This decreased the number of allocations from 17 to 12.

I am not sure of the implication of this change. Would that be a right thing to do?

**Comment by heyitsanthony** [comment]
@ajityagaty that should be `wg.watchers` instead of `wg.keyWatchers`, otherwise it'll ignore range watches

**Comment by ajityagaty** [comment]
@heyitsanthony Ok, I was not sure if looking at `keyWatchers` would suffice. Thanks for clarifying it!
So, a change to check the length of `watchers` and return early if it's 0 would be good enough? Shall I put out a PR?

**Comment by heyitsanthony** [comment]
@ajityagaty yeah I guess it's OK. I don't think it's a very effective optimization though since it's probably safe to assume an etcd server will always have some watcher attached.

**Comment by ajityagaty** [comment]
@heyitsanthony I agree !

**Comment by nekto0n** [comment]
Maybe it is worth investigating places where we use values instead of pointers in slices and as function arguments.
E.g. in [watcher.go](https://github.com/coreos/etcd/blob/master/mvcc/watcher.go#L69) every time we add something to `Events` there will be a copy. Another example is [watcher_group.go](https://github.com/coreos/etcd/blob/master/mvcc/watcher_group.go#L33). There are function like
```
func (eb *eventBatch) add(ev mvccpb.Event)
``` 
which will allocate a copy of `mvccpb.Event` on every call to `add()`.
There is another similar one
```
func (wb watcherBatch) add(w *watcher, ev mvccpb.Event) {
	eb := wb[w]
	if eb == nil {
		eb = &eventBatch{}
		wb[w] = eb
	}
	eb.add(ev)
}
```
Which will allocate a copy ev upon call, put pointer to it into hashmap and then make a copy during `eb.add(ev)` call.

**Comment by nekto0n** [comment]
Did some digging and wrote [a benchmark](https://github.com/nekto0n/etcd/commit/ec30adfa486ba3eb75a1b8aa48344d644ee535a3)
Here's interesting profile output: http://pastebin.com/wLPB03qe (started from `TxnEnd` and went deeper). Not quite sure if benchmark itself is right.

**Comment by ajityagaty** [comment]
Apologies from my side... I have not been able to spend much time on this. Will try to see if I can find some during the weekend.

**Comment by sinsharat** [comment]
@xiang90 will look into this once once i am done with logging issue and etcd-runner watcher implementation. In the mean time if @vimal78 is interested he can take it up, else i will take up.

**Comment by vimalk78** [comment]
is this issue still open

**Comment by xiang90** [comment]
@vimalk78 yes it is.

**Comment by xiang90** [comment]
this does not really cause performance issues in large deployments. closing for now.
