### ISSUE TITLE
Why 1000 for the event history limit?

### ISSUE THREAD

**Issue by vito** [etcd-io/etcd#494]
If there are 1002 events and a client tries to watch starting from index 1, the client will get a EcodeEventIndexCleared error (401). So why 1000? Is this going to be made configurable some day? What necessitates the limit in the first place?

Also, how do watches play with the snapshot feature?  If a snapshot happens and I request an event from _before_ the snapshot was taken, is it lost forever?

**Comment by DanielYWoo** [comment]
Hi @vito you can set read timeout to 30 seconds or even 3 seconds, then even no updates on the watched keys, you still have a chance to get a 200 response with empty body, then you can get the latest index from the response header. This is the current workaround for v2 API. For v3, etcd guys have a progress watch but it's not production ready yet.

**Comment by max-lobur** [comment]
Is this configurable currently?

**Comment by heyitsanthony** [comment]
It's hardcoded: https://github.com/coreos/etcd/blob/3d7539587557dfce8638c826e246f26c57d80d28/store/store.go#L100
