### ISSUE TITLE
raft: leader transfer optimzation

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#5020]
When we start to transfer the leader, we need to make sure the transferee has all log entries as current leader. Right now, we wait for the transferee to ack back the index before sending the timeout now message to trigger the actual transfer. One optimization is to append the timenow message right after the messages to help transferee to catch with the hope that the message will deliver in time.

**Comment by xiang90** [comment]
For more context:

bdarnell     CoreOS member
If we assume that the transport (usually) preserves order, we could send the MsgTimeoutNow as soon as we have sent a MsgApp containing the last index, without waiting for the MsgAppResp. This is similar to the way we optimistically increase Progress.Next when sending MsgApp.

es-chow     
es-chow added a note 15 hours ago
@bdarnell, @xiang90, I feel we cannot send MsgTimeoutNow as soon as we have sent a MsgApp containing the last index in all cases, if we add that code and remove the code to send MsgTimeoutNow when a MsgAppResp is received, the test case TestLeaderTransferToSlowFollower cannot be passed as node 3 will reject that MsgApp just before the MsgTimeoutNow triggered by pb.MsgTransferLeader as its log is not up-to-date, but the following MsgTimeoutNow will trigger node3 to start an election which also will fail.

Maybe one way is we keep the code which send MsgTimeoutNow as receiving MsgAppResp, but add one optimistic sending MsgTimeoutNow only when we optimistically update the pr.Next, but this may also have the risk that peer may reject that MsgApp and MsgTimeoutNow will make the group unavailable for one election timeout. And also we have to keep the timeoutNowSent flag.

We keep the current code as we can also remove the timeoutNowSent flag. This is the updated commit.

xiang90     CoreOS member
xiang90 added a note 9 hours ago
I feel this is an optimization. We can think this more and do it in another pr. @es-chow Can you set up another issue to track this potential optimization?

bdarnell     CoreOS member
bdarnell added a note 3 hours ago
Yeah, this optimization can wait. One thing we could do to avoid the scenario in which the follower rejects the MsgApp and then starts an election that fails is to include the leader's last log index in the MsgTimeoutNow. The follower would only start campaigning if it matches the index; if it doesn't then it knows it can't win.

@bdarnell @es-chow @ngaut

**Comment by gyuho** [comment]
Just to add a note, currently when follower receives timeout-now, it `r.becomeCandidate()` losing the leader while campaigning. Another optimization would have current leader be transferred without any downtime.

**Comment by cjl3080434008** [comment]
hello guys, i am a newbee in raft and etcd. I get confused of what etcdserver.EtcdServer.Lead() will be return in leader transfer. Because i see that when transferee became leader and had not send MsgApp to the old leader, so old leader had not call becomeFollower(). If at this point i call Lead() on the old leader server, what leadId will i get?  If i call Lead() on new leader server, it will return the new leader's Id i think.  And sorry for disrupt on this open issue.

**Comment by riking** [comment]
A combined message -- transfer + timeoutNow iff transfer complete - sounds like it would work?

**Comment by liubog2008** [comment]
Is this optimization not valid in theory?
