### ISSUE TITLE
[feat] Webhook for wait changes?

### ISSUE THREAD

**Issue by SEJeff** [etcd-io/etcd#509]
It would be nice if there was a way to register a callback ie: "Hey etcd, can you submit a http post to url XX when YY changes? kthxbye!"

The best method for doing this is via a [webhook](https://webhooks.pbworks.com/w/page/13385124/FrontPage) and in a perfect world, clients would be able to register these themselves instead of adding `&wait=true` + keeping open a long http connection. Here is the [tentative webhook spec](https://webhooks.pbworks.com/w/page/13385128/RESTful%20WebHooks).

**Comment by atgreen** [comment]
> @SEJeff @gleicon We are going to close this out, but my offer still stands. If anyone wants help building something like this on top of etcd please feel free to reach out.

It turns out that you can abuse confd to do this for you:  https://github.com/atgreen/s2i-confd
