### ISSUE TITLE
raft library should be its own repo

### ISSUE THREAD

**Issue by ongardie** [etcd-io/etcd#5108]
If the raft/ directory is intended to be a stand-alone library used by other projects than etcd, I think it should live in a separate repository. This would help push it towards being usable without understanding pieces of etcd. For example, #5063, that there is no README, would be an obvious problem with a standalone repo. Any requirements to depend on other things in the etcd repo would also be out in the open, like the stuff that [contrib/raftexample uses](https://github.com/coreos/etcd/blob/v2.3.1/contrib/raftexample/raft.go#L27-34).

**Comment by ongardie** [comment]
and separate issue tracker, making it easier for others to find existing issues before filing duplicates :)

**Comment by xiang90** [comment]
@ongardie The readme of raft is here: https://godoc.org/github.com/coreos/etcd/raft. But yea, I agree it is hard to find.

**Comment by ongardie** [comment]
@xiang90 I didn't know of that. I personally prefer to have high-level concepts in a README file, then low-level details like function arguments in inline code docs.

Some high-level stuff you may want to include (this should maybe go into #5063 instead):
 - What does this library do you for you? What does it not do for you? For example, who is responsible for storage? For networking? For log compaction?
 - When is this library suitable vs unsuitable? For example, would it be suitable for replicating TBs of data stored on disk?
 - Who are the major users of the library? (#5063)
 - How does the library do versioning and releases? What are the compatibility guarantees? What versions of Go are supported?
 - Without getting into the details of Raft, what optional features does the library implement and which does it leave out? For example, are no-ops implemented? Log compaction approach? Pre-vote? Leadership transfer?
 - Given that your membership change algorithm is not described in the Raft paper or my PhD thesis, how does it work?

You probably have written some words about some of this stuff in some places, but I'm not interested in pointers to those at this time. I opened this issue to try to help you make this project look more like a library that others should use.

**Comment by bbbmmmlll** [comment]
This would make the raft library much more accessible.
