### ISSUE TITLE
Evaluate compression layer

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#5186]
#### 2016.04.26 ~
- [X] try other different compression algorithms
  - [X] no compression
  - [X] [`github.com/bkaradzic/go-lz4`](https://godoc.org/github.com/bkaradzic/go-lz4)
  - [X] [`github.com/cloudflare/golz4`](https://godoc.org/github.com/cloudflare/golz4)
  - [X] [`github.com/golang/snappy`](https://godoc.org/github.com/golang/snappy)
  - [X] [`github.com/klauspost/compress/snappy`](https://godoc.org/github.com/klauspost/compress/snappy)
  - [X] [`compress/gzip`](https://golang.org/pkg/compress/gzip) with different compression levels
  - [X] [`github.com/klauspost/compress/gzip`](https://godoc.org/github.com/klauspost/compress/gzip) with different compression levels
  - [X] [`compress/zlib`](https://golang.org/pkg/compress/zlib/)
  - [X] [`github.com/klauspost/compress/zlib`](https://godoc.org/github.com/klauspost/compress/zlib)
  - [X] [`compress/bzip2`](https://golang.org/pkg/compress/bzip2/)
  - [X] evaluate `sync.Pool` performance effect
  - [X] measure compression rate
- [X] maximize CPU usage
  ![03-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/14796278/5f9fbc16-0ae1-11e6-8b4e-0819623705a4.png)
- try different compression path
  - [X] gRPC layer
  - [X] rafthttp layer
  - storage layer
    - [ ] `wal`
    - [ ] `storage`

<br><br><hr>
#### 2016.05.10: gRPC layer (READ)

![01-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/15150751/56e9f368-1683-11e6-893c-4f80c2bff6b1.png)
![01-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/15150752/56eef4a8-1683-11e6-86e4-82f0bd87abf6.png)
![01-avg-memory](https://cloud.githubusercontent.com/assets/6799218/15150750/56dfec6a-1683-11e6-972c-aea0a93ac1cc.png)
![01-throughput](https://cloud.githubusercontent.com/assets/6799218/15150749/56dec074-1683-11e6-926e-1c01cd01059b.png)

<br><br><hr>
#### 2016.05.01: gRPC layer (WRITE)

https://github.com/coreos/etcd/pull/5243

![01-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/15053630/6043c1ec-12b8-11e6-9f16-7de9c2976cbc.png)
![01-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/15053633/6044603e-12b8-11e6-8aee-bcdea94a556b.png)
![01-avg-memory](https://cloud.githubusercontent.com/assets/6799218/15053632/60442eb6-12b8-11e6-8bc0-6491b57e013d.png)
![01-throughput](https://cloud.githubusercontent.com/assets/6799218/15053631/60440878-12b8-11e6-8d12-d55d4c013d31.png)

<br><br><hr>
#### 2016.04.25: gRPC layer (WRITE)

https://github.com/coreos/etcd/pull/5183

![01-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/14796246/33001d4a-0ae1-11e6-9690-ffa2e09bd168.png)
![01-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/14796249/330190d0-0ae1-11e6-8c59-1ef9ebb28d79.png)
![01-avg-memory](https://cloud.githubusercontent.com/assets/6799218/14796247/33007c04-0ae1-11e6-9be7-52923f8f2c5e.png)
![01-throughput](https://cloud.githubusercontent.com/assets/6799218/14796248/3300b87c-0ae1-11e6-9054-6517fee51b0e.png)

```
# fastest to the right
gzip < cgzip < cgzip level 2 < snappy C++ < snappy (fastest) == no compression
# cgzip, snappy C++ need CGO, so we might skip them
```

**Comment by gyuho** [comment]
Previous experiments just pass random bytes that weren't compressible, as seen here https://github.com/gyuho/compress/blob/master/compress_test.go#L44:

```
func TestCompressPlainBytes(t *testing.T) {
	var (
		bytesN = 10 * 1024 * 1024 // 10MB
		tBts   = randBytes(bytesN)
	)
	var rs []result

=== RUN   TestCompressPlainBytes
Fastest:
                 "snappy-pool" compressed   10 MB  to 10 MB (compression ratio +0.012%, compression took      7.681172ms, decompression took      9.384419ms)
                      "snappy" compressed   10 MB  to 10 MB (compression ratio +0.012%, compression took      7.586817ms, decompression took      9.620686ms)
        "snappy-klaupost-pool" compressed   10 MB  to 10 MB (compression ratio +0.012%, compression took       9.54623ms, decompression took      8.122632ms)
             "snappy-klaupost" compressed   10 MB  to 10 MB (compression ratio +0.012%, compression took     10.704251ms, decompression took      8.823201ms)
     "gzip-klaupost-bestspeed" compressed   10 MB  to 10 MB (compression ratio +0.008%, compression took     23.726717ms, decompression took      8.068851ms)
"gzip-klaupost-bestspeed-pool" compressed   10 MB  to 10 MB (compression ratio +0.008%, compression took     23.844113ms, decompression took      8.076776ms)
                         "lz4" compressed   10 MB  to 10 MB (compression ratio +0.386%, compression took     53.613541ms, decompression took     33.608426ms)
          "gzip-klaupost-pool" compressed   10 MB  to 7.6 MB (compression ratio -27.740%, compression took      88.72229ms, decompression took    147.744527ms)
               "gzip-klaupost" compressed   10 MB  to 7.6 MB (compression ratio -27.740%, compression took     91.817334ms, decompression took    151.092575ms)
                        "gzip" compressed   10 MB  to 7.6 MB (compression ratio -27.164%, compression took    453.350002ms, decompression took    152.647082ms)
                   "gzip-pool" compressed   10 MB  to 7.6 MB (compression ratio -27.164%, compression took    456.360373ms, decompression took    167.454898ms)
```

- So this time, I chose real text data that are compressible up to 40% by snappy and lz4 compression algorithms, and the compression latency is only a few milliseconds.

```
compressing "great_expectation.txt" (1.0 MB)

Fastest:
                 "snappy-pool" compressed  1.0 MB  to 643 kB (compression ratio -37.80%, compression took      3.687957ms, decompression took      2.457321ms)
                      "snappy" compressed  1.0 MB  to 643 kB (compression ratio -37.80%, compression took      4.093305ms, decompression took      2.856134ms)
        "snappy-klaupost-pool" compressed  1.0 MB  to 643 kB (compression ratio -37.80%, compression took      3.822538ms, decompression took      3.142324ms)
             "snappy-klaupost" compressed  1.0 MB  to 673 kB (compression ratio -34.91%, compression took      9.424191ms, decompression took      5.163605ms)
                         "lz4" compressed  1.0 MB  to 632 kB (compression ratio -38.84%, compression took      9.695829ms, decompression took      5.876207ms)
     "gzip-klaupost-bestspeed" compressed  1.0 MB  to 486 kB (compression ratio -52.95%, compression took     15.999024ms, decompression took     14.437435ms)
"gzip-klaupost-bestspeed-pool" compressed  1.0 MB  to 486 kB (compression ratio -52.95%, compression took     17.197894ms, decompression took     14.453576ms)
               "gzip-klaupost" compressed  1.0 MB  to 421 kB (compression ratio -59.27%, compression took     29.240275ms, decompression took      12.30539ms)
          "gzip-klaupost-pool" compressed  1.0 MB  to 421 kB (compression ratio -59.27%, compression took     30.307311ms, decompression took     12.421584ms)
                        "gzip" compressed  1.0 MB  to 393 kB (compression ratio -61.94%, compression took    136.795781ms, decompression took     11.623531ms)
                   "gzip-pool" compressed  1.0 MB  to 393 kB (compression ratio -61.94%, compression took    141.902319ms, decompression took     12.551381ms)
```

- I experimented all those compression algorithms here https://github.com/gyuho/compress/blob/master/results/2016043001.txt, and chose lz4 and snappy for etcd use case (which were top-performing one).
- Code that implements this on etcd is here https://github.com/coreos/etcd/pull/5243.
- Compression are only enabled for gRPC layer.


<br><hr>
#### Result 1

![01-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/14943877/896b9c24-0f99-11e6-93b0-f422ba9b8789.png)
![01-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/14943879/896c1a96-0f99-11e6-896e-445c1947bade.png)
![01-avg-memory](https://cloud.githubusercontent.com/assets/6799218/14943880/896c33b4-0f99-11e6-9de8-75fb2e188726.png)
![01-throughput](https://cloud.githubusercontent.com/assets/6799218/14943881/896d22c4-0f99-11e6-87fe-feaad9d2298c.png)


<br><hr>
#### Result 2

![02-avg-cpu](https://cloud.githubusercontent.com/assets/6799218/14943878/896bbbdc-0f99-11e6-93eb-0a9dbbf99f8a.png)
![02-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/14943876/896babce-0f99-11e6-991a-53360f555a4e.png)
![02-avg-memory](https://cloud.githubusercontent.com/assets/6799218/14943882/8980da4e-0f99-11e6-9620-af64b5823f67.png)
![02-throughput](https://cloud.githubusercontent.com/assets/6799218/14943883/8981038e-0f99-11e6-9b90-ce3de0f9fee9.png)


<br><hr>
#### Conclusion

etcd has max request limit of only 1.5MB, so I tested nearing-limit requests between 800kb and 1MB (saving hundreds Kbs with compression) to maximize the compression benefit, but still I don't see much performance gain. I think it will be similar even if we compress in other network layers? We can consider storage layer compression to save I/O, but I am not sure where to experiment and what other etcd parts are worth trying the compression latency of (3~5ms).

**Comment by xiang90** [comment]
@gyuho I do not really understand the huge drop in the last benchmark at time 20 second. Can you please explain it?

**Comment by gyuho** [comment]
@xiang90 That's when etcd servers are overloaded:

```
# throughput drops from 30+/- to <10 at 08:25:27
2016-05-01 08:25:30.672167 W | etcdserver: failed to send out heartbeat on time (deadline exceeded for 147.057876ms)
2016-05-01 08:25:30.672197 W | etcdserver: server is likely overloaded
```

**Comment by xiang90** [comment]
@gyuho Then we should not make etcd overloaded. Or the benchmark does not make really sense to me. In another word, we need to understand why adding compression overloads etcd server. It seems the CPU load actually also drops.

**Comment by gyuho** [comment]
@xiang90 You are right. I will find better test data that do not overload etcd (logs show that my test data overload the ones without compression). Thanks.

**Comment by xiang90** [comment]
@gyuho More importantly, I want to know why that set of data does make etcd overloaded.

**Comment by gyuho** [comment]
@xiang90 Ok, I will investigate more on that too.

**Comment by xiang90** [comment]
@gyuho Even without any compression, etcd becomes slow after putting 1MB keys for 10s of seconds. We need to understand why.

**Comment by gyuho** [comment]
Tried <300kb values and still no benefit https://github.com/coreos/dbtester/blob/master/bench-results/2016050101/README.md.

If users deploy etcd across different data center or messages over 1.5MB are allowed, compression might be useful. But current etcd is designed for small-size messages, so compression layer only introduces additional latency.

What do you think? /cc @heyitsanthony @xiang90 

If we agree, I will close the PR and this issue, and maybe try again later when needed.

Regarding overloaded issue, I will investigate separately here https://github.com/coreos/etcd/issues/5245.

**Comment by heyitsanthony** [comment]
This is typical of compression-- the CPU cost is real.

I can see compression on `wal/` or `storage/` being wins, but it depends on the sync rate, IO bandwidth utilization, and general usage patterns.

**Comment by xiang90** [comment]
Yea... I do not think the compression at rpc layer can buy us a lot. etcd mostly deal with small values. The rpc layer saves us some bandwidth with cpu cost, but bandwidth is cheap actually. For storage, the benefits is real since memory is not cheap and it limits the scalability of etcd.

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony  I will play with storage layer compression when we are not busy.

Thanks for feedback!

**Comment by chancez** [comment]
Is it possible to remove the 1.5MB limit from v3 for the tests and try slightly more significant value sizes? Something on the order of 5MB, or 10MB? Even if it's not useful now, it would be good to have to compare to if you wish revisit larger files, or compression again.

**Comment by gyuho** [comment]
@chancez Good suggestion. It's unlikely we remove that request limit, but think it's worth trying.

Will experiment with that next time.

**Comment by chancez** [comment]
@gyuho Yeah, I think keeping the limit for now is a completely reasonable, and wise decision. I do think we should see how much compression helps with larger data though, it might allow relaxing the request size limit more in the future.

**Comment by gyuho** [comment]
![01-avg-latency-ms](https://cloud.githubusercontent.com/assets/6799218/15623937/c235ef5e-2430-11e6-807f-962eac599c3a.png)

Tried without request limit with text data 40% compressible by snappy (3.3 MB  to 2.0 MB), but still no benefit. I tried to hit etcd harder (more clients, more keys) and there was a slight benefit of doing compression, but at the same time etcd was being overloaded, so it's not worth.

I will experiment with storage layer.

**Comment by mqliang** [comment]
@gyuho Do we have a plan to implement compression at storage layer or at gRPC layer? I think compression may be helpful for LIST request. Since LIST request may return a large number of datas, and keys under a dir are often similar, so we may get a good compression ratio.

**Comment by gyuho** [comment]
@mqliang Yeah I experimented transportation layer but not much worth doing that. I am experimenting in storage layer, and I will keep updates here. I will take a look at that part you suggested. Thanks!

**Comment by xiang90** [comment]
I tried with storage lever. No significant improvement either. Probably not worth the effort.

**Comment by smarterclayton** [comment]
For very large data sets we are seeing where compression would be a *massive* improvement for Kubernetes.

Consider large chunks of service account secrets or pods.  The majority of their strings are similar.  In a list call, we've observed possible compression advantages of 90% or more for secrets, and 70% or more for pods.  That has a significant impact in reducing tail latency.  

I'd like to be able to on a per kubernetes resource (in large scale clusters) be able to turn compression on from etcd on.  Can we reopen this to discuss?

**Comment by smarterclayton** [comment]
@gmarek @wojtek-t

**Comment by wojtek-t** [comment]
Yeah - though the crucial requirement here is begin able to enable it only for some resources (prefixes of keys), not for everything (I think enabling it for some objects could have an opposite effect...)

**Comment by smarterclayton** [comment]
For example, we have several clusters with 1 gb of secret values.  I'd like to enable the storage layer to use compression only for secrets when transferring from etcd to master.

**Comment by gmarek** [comment]
OTOH we know that gzip compression can cause server CPU starvation, which is a reason why we disabled it by default in 1.7. We won't be able to enable it again if this problem won't be solved.

**Comment by heyitsanthony** [comment]
Reopening since there are a lot of ways to handle compression and I don't think it's been given a fair shake.

@smarterclayton How is the compression advantage being computed? Is there a simple model for the etcd usage patterns / how the data is structured? Can the compression be done client-side (e.g., through a client wrapper) or is there a compelling need to have it server-side?

**Comment by xiang90** [comment]
> OTOH we know that gzip compression can cause server CPU starvation, which is a reason why we disabled it by default in 1.7. We won't be able to enable it again if this problem won't be solved.

I do not want to start with, it is too CPU intensive. snappy might worth trying. 

@smarterclayton we should like to add the support if there is a reasonable improvement for at least some meaningful use cases.

**Comment by armstrongli** [comment]
@xiang90 do we have plan to set up compression support in etcd as an option for end user?
