### ISSUE TITLE
discovery: etcd discovery subcommand

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#5208]
User might want to add different discovery mechanisms (A records, kubernetes) into etcd besides DNS SRV, public discovery services. 

Right now, the discovery process is inside etcd server. But actually, it does not need to be inside core etcd server at all. All discovery needs to is to find the peers and write initial configuration into WAL. We should separate that out completely from etcd server. Then users can easily add whatever discovery mechanisms they want easily.

Also we want to provide a new subcommand of etcd to do the discovery. After finishing the discovery, user can start etcd as before without any cluster configuration, and it should just work.

**Comment by politician** [comment]
> We should separate that out completely from etcd server.

https://github.com/lyft/envoy uses a standardized Service Discovery API to outsource its need for discovery.  It might be valuable to see if their SD API would work for etcd; if so, we might see the emergence of a standardized SD component.  As someone who operates service meshes, let me tell you, that would be nice.
