### ISSUE TITLE
Can etcd discover the host IP on its own?

### ISSUE THREAD

**Issue by wrouesnel** [etcd-io/etcd#5315]
DNS-SRV discovery eases some of the bootstrapping pain with etcd and mass-deployed systems, but it seems like it still leaves some considerably fiddly edges to it.

The big one is getting past the need to have slightly different configurations for bootstrapping on each node - ideally I'd simply point them all at the one DNS entry, and etcd would be smart enough to examine it, examine it's local IPs, and figure out which node it should be.

Would it be possible to explicitly make this an option with DNS-SRV discovery? i.e. enumerate local IPs, determine cluster membership then advertise / peer / listen on the publicly resolvable IPs + whatever is listed?

**Comment by xiang90** [comment]
I think this is a reasonable thing to do. But you can achieve this outside etcd too. The current problem is there are too many requirements for discovery. We need to get https://github.com/coreos/etcd/issues/5208 sorted out before adding more features into discovery.

**Comment by xiang90** [comment]
Do you have interest in moving all the discovery logic out of etcdserver pkg so that we can start make it more fancy?

**Comment by hexfusion** [comment]
@xiang90 @gyuho I find this interesting any objections to me seeing where I can go with it? Any additional input since details above you could offer?
