### ISSUE TITLE
The event in requested index is outdated and cleared

### ISSUE THREAD

**Issue by nbarrientos** [etcd-io/etcd#587]
Hi,

I'm not sure this is the right place to ask about this, but haven't found any other "support line" :)

I'm running etcd 0.3.0 in a small three-node cluster which is being mainly used as a locking mechanism for an external application. Basically, different instances of the application compete for a lock every time they run. The setup was working fine until a few days I ago when I started to see an error message on the application log when trying to get an already-acquired lock:

```
Etcd locking failed: 'lock watch error: 401: The event in requested index is outdated and cleared (the requested history has been cleared [47/10]) [1046]
```

The app uses python-etcd (0.3.0) to chat with the etcd cluster, and it essentially tries to get the lock and gives up after a reasonable timeout before doing any actual work involving a critical section. However, the behaviour can be easily reproduced using curl:

```
~ $ curl http://foo.example.org:4001/mod/v2/lock/bar -XPOST -d ttl=10 -m 3 -v
* About to connect() to foo.example.org port 4001 (#0)
*   Trying 192.168.0.4... connected
* Connected to foo.example.org (192.168.0.4) port 4001 (#0)
> POST /mod/v2/lock/bar HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: foo.example.org:4001
> Accept: */*
> Content-Length: 6
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 21 Feb 2014 09:01:23 GMT
< Content-Length: 132
< 
lock watch error: 401: The event in requested index is outdated and cleared (the requested history has been cleared [56/10]) [1055]
* Connection #0 to host foo.example.org left intact
* Closing connection #0
```

I don't see anything weird in the server logs with the default logging level. Haven't restated any of the etcd deamons yet so I'm happy to provide any other debugging information you may need.

Feel free to reroute me somewhere else if this is not the place to drop user questions :)

**Comment by wangyumi** [comment]
I met the same issue when I ran 100 watches concurrently. Should I expect that the fix will be shipped in etcd 2.1?
