### ISSUE TITLE
test: performance regression tests

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#6002]
It's often unclear whether a change to etcd will significantly impact performance. To catch performance issues early, etcd should have performance regression testing including historical data. The performance data could be t-tested for some statistical confidence.

I don't expect this to need significant amounts of new code, a lot of resources, or much time to run-- it would launch a cluster, run tools/benchmark, store the results somewhere, and calculate the change in performance. It'd be neat if this could be integrated with CI (but, obviously, it wouldn't be able to run directly on travis/semaphore) so that performance regressions are gated before commit.

**Comment by xiang90** [comment]
not urgent. moving to 3.3

**Comment by hexfusion** [comment]
@heyitsanthony so are you thinking of using something like Terraform with Matchbox to automate the cluster creation? Then use @gyuho's dbtester against that cluster for data? Would this be touched off/managed by Jenkins pipeline? I find this project interesting and would lend a hand if it makes sense.

**Comment by heyitsanthony** [comment]
no, it would just be running the cmd/tools/benchmark against every commit and having a way to track the results; dbtester wouldn't be involved and terraform seems like overkill
