### ISSUE TITLE
Lets Encrypt Support

### ISSUE THREAD

**Issue by jwaldrip** [etcd-io/etcd#6508]
# Feature Request

It would be AMAZING if etcd was https by default and leveraged lets encrypt to generate certs for the client.

**Comment by xiang90** [comment]
@jwaldrip 

Do you want this for client side or server side? Have you thought about how would this work? What is the ideal workflow in your mind?

**Comment by xiang90** [comment]
@jwaldrip kindly ping. We need to hear about the use case to prioritize the issue.

**Comment by serussell** [comment]
I can chip in here.  A good use case would be modeled after https://caddyserver.com[Caddy], where TLS is enabled on the server by default.

* All client connections would be TLS by default, ensuring, at the very least, secure communication of data between client and server.
* Client verification through client certs would be out-of-scope.
* TLS would need to be specifically _disabled_ by configuration on the server if the user does not want it.

Is that sufficient description of use case?
