### ISSUE TITLE
Document backup strategies

### ISSUE THREAD

**Issue by bmizerany** [etcd-io/etcd#683]

**Comment by Dynom** [comment]
The link is outdated, but this should work for a while: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#backing-up-the-datastore

**Comment by sukrit007** [comment]
Looks like master branch no longer has admin_guide.  But https://github.com/coreos/etcd/blob/release-2.3/Documentation/admin_guide.md#backing-up-the-datastore worked.

**Comment by sukrit007** [comment]
Looks like https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html#etcd-disaster-recovery-on-coreos is the best place for those who are using cloud-config to bootstrap etcd. With few tweaks, instructions worked like a charm.
