### ISSUE TITLE
proxy: emulate v2 with v3 rpc's

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#6925]
The v2 backend is a lot of baggage, but there's still a lot of v2 code out there. The v2 backend will eventually have to go, but it'd be nice to emulate v2 for older apps.

**Comment by raoofm** [comment]
This is great. Any timeline for 3.3.0 yet?

**Comment by heyitsanthony** [comment]
@raoofm the plan is to target september because there are some important boltdb performance fixes that can't be merged into 3.2.0 without breakage across bugfix releases. May push back some features to 3.4.0. I would like to get this at least in an experimental state by 3.3.0, though.

**Comment by xiang90** [comment]
we have done the initial work. but needs more testing and stability work. see https://github.com/coreos/etcd/issues/8473.

moving to 3.4 milestone.
