### ISSUE TITLE
proxy: local grpc proxying

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#6931]
The features in the grpcproxy (coalescing, key caching) also make sense when run directly on the client instead of making a network hop to separate proxy. 

This is already exists to some extent for the integration/ tests, but it's still not ready for prime time.

What's missing:
* clientv3 CallOption pass-through; needed for correct FailFast handling
* `-tag cluster_proxy` for client integration tests

**Comment by xiang90** [comment]
@heyitsanthony This is already possible?

**Comment by heyitsanthony** [comment]
Needs testing to close. `-tags cluster_proxy` will work on clientv3 integration but that gets the client connecting to a proxy, not the client with a local proxy connecting to the core cluster. Still needs the CallOption support for some failure cases IIRC
