### ISSUE TITLE
put performance for 1 client

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#7156]
GCE Standard8 with SSD

Hardware stats:

1. fsync 256B ~ 600us
2. ping RTT ~ 300 us
3. gRPC pingpong ~ 300us

The idea throughput of 1 client 256B put is roughly: 

1second/ [RTT (between client + leader) + RTT (between leader + follower) + fsync (blocking to wait for entry to be persisted to ack back to leader)]

= 1second / (300 + 300 + 600 ) us = 1 second / 1200 us = 833 requests/second.

There will be CPU cost but ideally it should be negligible.

The benchmark results from dbtester show that the max throughput for 3 members

- ZooKeeper 700 requests / second [84% optimal]
- etcd 580 requests / second [69% optimal]

Baseline-1 (one member + one client on the same machine)

- etcd 1000 requests / second (1000us each / fsync 60% optimal)

Baseline-2  (one member + one remote client)

- etcd 819 requests / second (1200us each / fsync + RTT 75% optimal)

I feel there may be some low hanging fruits for us to improve.

I modified the data since I found a bug in one member case. I will get it fixed.

**Comment by xiang90** [comment]
gRPC pingpong tests show that gRPC introduces ~200us latency.

**Comment by xiang90** [comment]
@sinsharat It would be great if you can get some data on your hardware with HDD. We need fsync duration(https://github.com/ongardie/diskbenchmark) + rtt (netperf) besides etcd data. This can help us improve etcd performance under light load.

**Comment by xiang90** [comment]
Now I tried a two member cluster on the same GCE environment with remote client:

Performance drops dramatically:

- To leader : 575 requests / second (1.7ms)
- To follower: 475 requests / second (2.1ms)

**Comment by xiang90** [comment]
I traced down everything.

So

0 client -> leader put
50 leader receives put
50 leader sent append to follower
50 leader -> fsync
450 follower received append from leader (This is unexpected. This should be equal to client -> leader ~ 50us)
650 leader finished fsync
1060 follower finished fsync
1060 follower sent append response back to the leader
1460 leader received append response
1460 leader committed
1510 client received put response

The total io waiting time is round 1.5ms. The total request life time is 1.65ms. 

The communication between follower and leader is unexpected. I am investigating rafthttp now.

**Comment by xiang90** [comment]
I can reproduce this locally on my machine using rafthttp/BenchmarkSendingMsgApp. Even on local network the delay is 300us... this is clearly wrong.

**Comment by sinsharat** [comment]
@xiang90 Sure will try to provide you with the details.

**Comment by sinsharat** [comment]
@xiang90 for our hardware please find below the details:
Hardware stats:
fsync ~ 70MB/s
ping RTT ~ 220 us
gRPC pingpong ~ How did you get this data? I tried https://github.com/denderello/ping-pong-grpc but it doesn't give the time.

**Comment by gyuho** [comment]
Did another set of benchmarks with latest Zookeeper https://github.com/coreos/dbtester/tree/master/test-results/2018Q1-04-etcd-zookeeper#write-100k-keys-256-byte-key-1kb-value-1-client with 1-client.

```
+---------------------------------------+---------------------+-----------------------------+
|                                       | etcd-v3.3.0-go1.9.3 | zookeeper-r3.5.3-beta-java8 |
+---------------------------------------+---------------------+-----------------------------+
|                         TOTAL-SECONDS |        175.1067 sec |                193.2046 sec |
|                  TOTAL-REQUEST-NUMBER |             100,000 |                     100,000 |
|                        MAX-THROUGHPUT |         632 req/sec |                 594 req/sec |
|                        AVG-THROUGHPUT |         571 req/sec |                 517 req/sec |
|                        MIN-THROUGHPUT |         166 req/sec |                 213 req/sec |
|                       FASTEST-LATENCY |           0.9618 ms |                   1.1486 ms |
|                           AVG-LATENCY |           1.7462 ms |                   1.9308 ms |
|                       SLOWEST-LATENCY |          17.2672 ms |                 110.7389 ms |
|                           Latency p10 |         1.218092 ms |                 1.402825 ms |
|                           Latency p25 |         1.305288 ms |                 1.478765 ms |
|                           Latency p50 |         1.513458 ms |                 1.600954 ms |
|                           Latency p75 |         2.123979 ms |                 2.601295 ms |
|                           Latency p90 |         2.366836 ms |                 2.793483 ms |
|                           Latency p95 |         2.499598 ms |                 2.890841 ms |
|                           Latency p99 |         3.991311 ms |                 3.223381 ms |
|                         Latency p99.9 |         5.451962 ms |                 3.994881 ms |
|      SERVER-TOTAL-NETWORK-RX-DATA-SUM |              557 MB |                      617 MB |
|      SERVER-TOTAL-NETWORK-TX-DATA-SUM |              427 MB |                      511 MB |
|           CLIENT-TOTAL-NETWORK-RX-SUM |               31 MB |                       35 MB |
|           CLIENT-TOTAL-NETWORK-TX-SUM |              161 MB |                      140 MB |
|                  SERVER-MAX-CPU-USAGE |             53.20 % |                     91.33 % |
|               SERVER-MAX-MEMORY-USAGE |              456 MB |                      3.4 GB |
|                  CLIENT-MAX-CPU-USAGE |             24.00 % |                     10.00 % |
|               CLIENT-MAX-MEMORY-USAGE |               19 MB |                       22 MB |
|                    CLIENT-ERROR-COUNT |                   0 |                           0 |
|  SERVER-AVG-READS-COMPLETED-DELTA-SUM |                  18 |                          70 |
|    SERVER-AVG-SECTORS-READS-DELTA-SUM |                   0 |                           0 |
| SERVER-AVG-WRITES-COMPLETED-DELTA-SUM |             729,968 |                     699,827 |
|  SERVER-AVG-SECTORS-WRITTEN-DELTA-SUM |           7,266,272 |                   7,540,328 |
|           SERVER-AVG-DISK-SPACE-USAGE |              399 MB |                      317 MB |
+---------------------------------------+---------------------+-----------------------------+
```

Zookeeper is now slower than etcd. Would love to have someone else cross-check on this.

Still, etcd should have some low hanging fruits to improve. If we look at this test:

<img src="https://storage.googleapis.com/dbtester-results/2017Q2-02-etcd-zookeeper-consul/2017Q2-01-write-1M-throughput-client-scaling.png" alt="2017Q2-01-write-1M-throughput-client-scaling">

Ideally, etcd should scale as fast as Zookeeper with <100 clients. etcd could use more CPUs (53.20% vs 91.33% Zookeeper).

See https://github.com/coreos/dbtester/tree/master/test-results/2018Q1-02-etcd-zookeeper-consul for other results.
