### ISSUE TITLE
client/gRPC-proxy: optionally batch raw put requests into transcation

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#7228]
Like what Kafka client does, etcd client can optionally batch simple put requests into one transaction. I assume that would improve write performance significantly when there are highly concurrent writes from one single client (or through one gRPC proxy). 

/cc @heyitsanthony

**Comment by xiang90** [comment]
> then gets confused when watches turn up multiple puts in a single txn.

If we want it to be transparent, we could add an option (batched_put) into txn. server can increase rev N time if there are N puts in on Txn.

**Comment by xiang90** [comment]
@vimalk78 

Do you want to give this a try? We can start with client library. But note that there is a max number of txn and max request size limit, we need to commit the batched txn before reaching to these limit.

**Comment by vimalk78** [comment]
@xiang90 

yes, i would like to work on this one.

**Comment by xiang90** [comment]
@vimalk78 OK. Awesome.
