### ISSUE TITLE
How to install *just* etcdctl tool?

### ISSUE THREAD

**Issue by jaypipes** [etcd-io/etcd#7487]
Hi! I'm wondering how I can install only the `etcdctl` tool? I don't want to install the etcd service, only the client tool. Is there a way to do this?

Thanks in advance!
-jay

**Comment by gyuho** [comment]
We don't ship separate binary for `etcdctl`. Currently easiest way is just untar release binaries from https://github.com/coreos/etcd/releases and just pick the `etcdctl`. Or if you want to build on your own, here's how we build `etcdctl` binary https://github.com/coreos/etcd/blob/master/build#L39.

**Comment by heyitsanthony** [comment]
`go get github.com/coreos/etcd/cmd/etcdctl` will install the latest `etcdctl`, but it'll build from master, so don't expect it to be stable.

**Comment by Ambujk9** [comment]
on MacBook try - 
brew install etcd

**Comment by pandeyvinod** [comment]
> By now this is `go get github.com/coreos/etcd/etcdctl`.
> 
> You can also do:
> 
> ```
> go get github.com/coreos/etcd/etcdctl
> cd <go-dir>/src/github.com/coreos/etcd/
> git checkout -b v3.3.4
> CFLAGS="-Wno-error" go install .
> ```

what about the conflict of the version. will it create any issue like your etcd service is running on older version but we have installed new version of etcdctl?

**Comment by ptabor** [comment]
0. In etcd-3.5 you will be able to install etcdctl alone: 
go get go.etcd.io/etcdctl/v3

1. Majority of etcdctl commands work over the network protocol [exceptions etcdctl snapshot & etcdctl migrate]. They are compatible in practice as long as you don't use a new future implemented in e.g. 3.4 server, client, etcdctl, but later you are trying to use it through etcdctl 3.4 client, but on etcd server 3.2.

**Comment by abdennour** [comment]
```sh
go get go.etcd.io/etcd/etcdctl/ctlv3
```

**Comment by chokhareganesh** [comment]
generate **etcdctl** executable from go code and move to executable directory ( /usr/local/bin)

```
go get github.com/coreos/etcd/etcdctl
cd <go-dir>/src/github.com/coreos/etcd/etcdctl
go build .
ls | grep etcdctl         #check etcdctl is grenerated 
sudo mv etcdctl /usr/local/bin
```

**Comment by ptabor** [comment]
With 3.5 it should as as simple as: 

```
%go get go.etcd.io/etcd/etcdctl/v3
etcdctl --help
```
or 
```   
% gobin --run go.etcd.io/etcd/etcdctl/v3 --help
```

**Comment by abdennour** [comment]
debian has ready package called `etcd-client`. However, Redhat has not with yum package manager :(
