### ISSUE TITLE
grpcproxy: plans to support client whitelisting?

### ISSUE THREAD

**Issue by davissp14** [etcd-io/etcd#7527]
Are there any plans to add ip whitelisting / ACL to restrict client connections to specific ip addresses?

**Comment by heyitsanthony** [comment]
No plans, but this feature seems like it would belong in the etcd gateway. What's your use case?

**Comment by davissp14** [comment]
We actually are not using the etcd gateway.  This is out of scope, but what would be the advantage of using the gateway instead of grpc-proxy in the event we only need gRPC?

>  What's your use case?

It's an added security measure.  While user based auth is fine when you're connecting locally, when the grpc proxy is exposed to the open internet, ip based whitelisting is a pretty huge bonus.

**Comment by heyitsanthony** [comment]
> what would be the advantage of using the gateway instead of grpc-proxy in the event we only need gRPC?

It's to keep separate layers of the OSI stack from bleeding into each other. Internally, gprcproxy doesn't care about where connections are coming from and is written in such a way it can be used without a network at all. On the other hand, the gateway explicitly reasons about tcp and client connections.
