### ISSUE TITLE
grpcproxy / gateway: composed operation

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#7619]
There are cases where a single node wants both proxy and gateway behavior. Currently, to get both feature sets, grpcproxy and gateway must run as separate processes. This is both inconvenient and potentially inefficient. As an alternative, etcd could possibly have a gateway-grpcproxy mode that manages both connection-level proxying and protocol-level proxying.

cf. #7522 #7527

**Comment by pizzarabe** [comment]
Is there a way to prioritize (at least https) that feature? The etcd3 gateway is not really working in a https environment without making changes to the certificates or by disabling the certificate checking in the etcd clients. 
I know there are a bunch of other things to do, I just wanted to ask nicely :)

**Comment by heyitsanthony** [comment]
@pizzarabe tls termination works right now by having client <-> proxy <-> gateway <-> etcd. It's just a little unwieldy / has an extra hop, which is what this issue is meant to address.

**Comment by heyitsanthony** [comment]
Oh, actually, judging by the grpcproxy listener path maybe it doesn't terminate... I'll need to test this.

**Comment by pizzarabe** [comment]
> tls termination works right now by having client <-> proxy <-> gateway <-> etcd

Yeah, but if you have to work with both v2 and v3 API you need to use the grpc proxy and the v2 proxy, correct? The grpc proxy seems to work only with the v3 API. 
If I understand the docs correctly, the gateway is not inspecting the traffic so I can use it for both api versions and I only have to run the gateway (If I want to move from v2 to v3 etcd (and using both api versions), I only need to replace my v2 proxy with the v3 gateway and everything should work fine).
In that case tls termination would be very nice.

Please correct me, if I am wrong here!

**Comment by heyitsanthony** [comment]
@pizzarabe that's gateway tls termination, which isn't what this issue covers.

**Comment by pizzarabe** [comment]
@heyitsanthony but https://github.com/coreos/etcd/issues/7522 is talking about tls termination and it is mentioned in that issue.

**Comment by heyitsanthony** [comment]
@pizzarabe tls termination with respect to v3, not tls termination in general.
