### ISSUE TITLE
tools/redact: remove sensitive information from member directory

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#7620]
Sometimes wal logs and boltdb data have sensitive data that can't be shared. This is bad for debugging since the metadata is useful for finding why a cluster has broken.

To get that metadata, etcd needs a tool that will redact keys/values/cluster info from a member directory while preserving everything else (raft indexes, etcd revisions, etc).

**Comment by xiang90** [comment]
@jpbetz do you want to work on this for the next release cycle?
