### ISSUE TITLE
AuthUserGrantRoleRequest: naming

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#7836]
AuthUserGrantRoleRequest uses **User** to define the name of the user and AuthUserRevokeRoleRequest instead uses **Name**.  I understand that it could be problematic to change at this point and perhaps there is a valid reason but it seems wrong. If we could make the use of **Name** consistent it would make coding around it much cleaner and logical.  Looking for input before I did anything more.

[AuthUserGrantRoleRequest](https://github.com/coreos/etcd/blob/d3456b5ecdd58ea96edbf83e37e9bea6804e0020/auth/store.go#L424,L458)
```
  func (as *authStore) UserGrantRole(r *pb.AuthUserGrantRoleRequest) (*pb.AuthUserGrantRoleResponse, error) {
	tx := as.be.BatchTx()
	tx.Lock()
	defer tx.Unlock()

	user := getUser(tx, r.User)
	if user == nil {
		return nil, ErrUserNotFound
	}

	if r.Role != rootRole {
		role := getRole(tx, r.Role)
		if role == nil {
			return nil, ErrRoleNotFound
		}
	}

	idx := sort.SearchStrings(user.Roles, r.Role)
	if idx < len(user.Roles) && strings.Compare(user.Roles[idx], r.Role) == 0 {
		plog.Warningf("user %s is already granted role %s", r.User, r.Role)
		return &pb.AuthUserGrantRoleResponse{}, nil
	}

	user.Roles = append(user.Roles, r.Role)
	sort.Sort(sort.StringSlice(user.Roles))

	putUser(tx, user)

	as.invalidateCachedPerm(r.User)

	as.commitRevision(tx)

	plog.Noticef("granted role %s to user %s", r.Role, r.User)
	return &pb.AuthUserGrantRoleResponse{}, nil
}
```

**Comment by hexfusion** [comment]
Similar situation with AuthRole{Add,Delete}Request etc and the swapping of **name** and **role** to define the name of a role.

**Comment by heyitsanthony** [comment]
/cc @mitake 

This change would be wire compatible but it would break anything generating stubs from the protobuf files or using the json grpc gateway.

**Comment by mitake** [comment]
@hexfusion thanks for pointing out, yes, the naming is really inconsistent and I'm glad if you can fix them.
