### ISSUE TITLE
raft: bootstrapping flow

### ISSUE THREAD

**Issue by jbowens** [etcd-io/etcd#7985]
The changes to StartNode introduced (long ago) in #1874 are [still present on master](https://github.com/coreos/etcd/blob/master/raft/node.go#L195-L206), but I don't believe they achieve their stated purpose anymore. It looks like tests now explicitly call Ready, Append and Advance before calling Campaign: [TestNodeAdvance example](https://github.com/coreos/etcd/blob/master/raft/node_test.go#L642-L646)

1. Are the changes from #1874 still relevant? If not, should they be removed?
2. Is the caller guaranteed that the first Ready after StartNode will have all the initial configuration entries and that's it?
3. Is a synchronous Ready, Append, Advance, Campaign the recommended way to immediately campaign when starting a new cluster?

(copied this post from https://github.com/coreos/etcd/pull/1874#issuecomment-303873639)

**Comment by bdarnell** [comment]
1. As the original author of this change, we don't rely on it any more in CockroachDB. I don't know if anyone else might be depending on this outside of the raft package's own tests.
2. Not sure if that's guaranteed or not. There could also be the empty entries created by a leader election (if there's just one node I think this would be in the first `Ready`). 
3. I think if #1874 were reverted you'd also need `ApplyConfChange`.

**Comment by jbowens** [comment]
Thanks @bdarnell, that makes sense.

It looks like etcd forces `electionTicks-1` ticks on start to ensure a quick start to a new cluster: https://github.com/coreos/etcd/blob/750dc7f157c2d13e9b7d229ad749c1a4d62b0def/etcdserver/raft.go#L371-L379 That might be the best solution if not using RawNode.
