### ISSUE TITLE
raft example: snapshot may be not intact 

### ISSUE THREAD

**Issue by cheung-chifung** [etcd-io/etcd#8091]
When getSnapshot() is called,  parts of changes through `commitC` may be still not applied.
these commits will be lost when restart from snapshot.

It can be simply reproduce with  small `snapCount` and `snapshotCatchUpEntriesN` (says `3`).

A simple way to solve it is to save one more state `committedIndex` to record how many entries and  actually committed to kvstore and extend `commitC` with entry index to sync them. Then make `getSnapshot` blocks if `committedIndex` not catch up `appliedIndex`.

I would like to submit  a pull request this weekend of this issue.

**Comment by gyuho** [comment]
@keekun Could you send a pull request so that we can discuss more?

Thanks!
