### ISSUE TITLE
v3: proxy + rolling member update

### ISSUE THREAD

**Issue by vboginskey** [etcd-io/etcd#8132]
Background: we run etcd on AWS, with a cluster of 3 servers and local proxies on each worker.

With etcd v2, the proxy behaved like this (quoting documentation):

> After establishing a list of peer URLs in this manner, the proxy retrieves the list of client URLs from the first reachable peer. These client URLs are specified by the advertise-client-urls option to etcd peers. The proxy then continues to connect to the first reachable etcd cluster member every thirty seconds to refresh the list of client URLs.

This allowed us to do a rolling update of etcd servers without losing connectivity on any of the clients. Is this no longer possible with v3? The available discovery mechanisms in both etcd gateway and grpc proxy only resolve the list of endpoints at startup, but do not keep them updated, which means that replacing all of the initial cluster members results in loss of connectivity.

Also, the v2 proxy was able to terminate TLS, but this doesn't seem to be the case with v3.

So, what strategy is recommended to keep the list of endpoints up to date on v3 proxies, and are there plans to port TLS termination to v3?

**Comment by gyuho** [comment]
> keep the list of endpoints up to date on v3 proxies

v3 grpc proxy supports endpoints discovery. See https://github.com/coreos/etcd/blob/master/Documentation/op-guide/grpc_proxy.md#client-endpoint-synchronization-and-name-resolution for more detail.

**Comment by vboginskey** [comment]
I'm not sure that solves the issue at hand. The problem is not that clients need to discover the proxy/proxies, it's that the proxies need to discover new servers. Is that possible with v3 endpoint discovery?

**Comment by heyitsanthony** [comment]
The proxy needs to support `--auto-sync` and TLS termination, but doesn't yet.
