### ISSUE TITLE
Provide mechanism for read lock on the cluster

### ISSUE THREAD

**Issue by brianredbeard** [etcd-io/etcd#8134]
As an administrator in need of performing atomic operations on the state of a cluster it would be useful to perform an atomic lock on the cluster.  This would then allow the use of external utilities like LVM/BTRFS snapshotting to assist with the backup recovery process which would be nice for extremely large data sets.

This is a [common operation with relational databases][lvm-snapshot-mysql].  From a historic perspective, this was the _only_ way to back up some pieces of software without proprietary tools like InnoDB.

[lvm-snapshot-mysql]: https://www.percona.com/blog/2006/08/21/using-lvm-for-mysql-backup-and-replication-setup/

**Comment by heyitsanthony** [comment]
To some extent etcd has similar functionality with quota alarms. The lock feature could probably be merged into the alarm system (e.g., a user-triggered "maintenance" alarm that locks writes). I'm assuming the expectation is writes would block server-side until the lock is lifted? Or is it OK to fail them?

**Comment by xiang90** [comment]
>  I'm assuming the expectation is writes would block server-side until the lock is lifted? Or is it OK to fail them?

I would follow what mysql does. I can do some research on it.

**Comment by brianredbeard** [comment]
I could go a few different ways here.  I think that a timeout is actually
fine for this.  I don't know the level of code complexity, but being able
to say "while (client has not released lock) or (client connection timeout)
hold lock" would be fine. Let's walk through two (over engineered) use
cases:

1) "etcd large backup operator" -
In situations where gigabytes of data are stored in etcd (despite pleas not
to do this) an operator could write a snap request to
/_etcd/snapshot/request. Provocateurs/operator agents could then respond
with a nonce to /_etcd/snapshot/member_name which they will send via TCP to
the operator on snapshot completion.

Once all provocateurs have written their nonce, the operator locks. Members
take their snapshot and respond. When all participants complete, the
operator releases the lock.

2) the operator locks for snapshot and holds the lock until it has
confirmation that the operation completes.  If the client connection breaks
the server kicks off a hold off period after which it automatically
releases the lock, in effect creating a dead man's switch.

These are just two off the cuff ideas. Curious as to your thoughts.
