### ISSUE TITLE
raft: commit message can be broadcast lazily

### ISSUE THREAD

**Issue by BusyJay** [etcd-io/etcd#8190]
Raft [broadcasts](https://github.com/coreos/etcd/blob/master/raft/raft.go#L902) a MsgAppend message to commit a Raft entry eagerly. This means for every entry in a cluster with n nodes, there will be probably (n - 1) * 2 messages from proposal to commit. Actually the committed index is constantly updated via heartbeat and further proposals, hence the broadcast can be omitted if the application is not sensitive to the followers' apply time. In our tests, the number of messages becomes half as before after commenting out the `r.bcastAppend()` line.

My suggestion is to use a configuration to indicate whether to broadcast a MsgAppend message to commit an entry explicitly.

This change may affect the proposal redirection and follower read features.

**Comment by siddontang** [comment]
/cc @xiang90 

In our high write load test, disabling it can reduce 100% messages and at lease 40% latency.

For backward compatibility, we can use a configuration to control it.

**Comment by xiang90** [comment]
> In our high write load test, disabling it can reduce 50% messages and at lease 40% latency.

you can drop the message before you decide to send them out in the network layer. i am curious about what is the actual cost here. is it the network + serialization/deserialization cost or the cost of generating the in memory messages at raft layer? it it is the former, we can solve it at application layer without changing raft. and, yes, we have done that at etcd side.

**Comment by siddontang** [comment]
@xiang90 

Of course, the high cost is for network and protobuf codec. If we will discard them at the application layer, it is not necessary to still add them in the raft layer and I think using a configuration is easier to do this.

**Comment by xiang90** [comment]
@siddontang 

send a pr and we can accept it. i have no strong opinion on this one.

**Comment by BusyJay** [comment]
I will make up a PR in the following days.
