### ISSUE TITLE
virtualized auth

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#8217]
Currently auth configuration is cluster-wide; there is a single root role that manages access to all auth resources. Furthermore, since auth is system wide, the metadata is baked into boltdb, making observing updates to authentication unwieldy and introducing extra paths to reason about revisions to avoid inconsistencies.

There have been requests for other sorts of authentication backends (e.g., LDAP); what's there now isn't enough to satisfy all use cases. The differences in semantics mean the auth API would need special extensions that would not apply to all auth subsystems. Likewise, the effects of switching between backends is unclear.

Instead, auth can be virtualized via proxies and nested txns. All auth data that must be consistent would be stored under some prefix under etcd's mvcc. All user requests can be wrapped in a nested txn to check to see if the permissions are still valid when processed on the etcd server. The authentication mechanism becomes virtualized since there can be many different authentication proxies connected to the etcd cluster at once, each serving separate policies. Likewise, since this is through proxies, there's less code in the core server than can break, so that's a case for better cluster reliability.

The first step would be implementing the current auth API over a proxy; future backends can follow.

/cc @mitake @hsluoyz

**Comment by mitake** [comment]
@heyitsanthony the idea seems to be good. I'll work on implementing the first step.

**Comment by heyitsanthony** [comment]
@mitake I have some patches already that are WIP at https://github.com/heyitsanthony/etcd/tree/auth-emu. I had to do some modest refactoring of the auth package internals so it's less reliant on batchtx in order to reuse the checking logic. I'll try to get something reasonable up by tomorrow evening or the day after.

**Comment by mitake** [comment]
@heyitsanthony I see, thanks a lot for doing it!

**Comment by hsluoyz** [comment]
Any progress/update to add authorization support on etcd?
