### ISSUE TITLE
Can't use http api to get data from a authorized cluster

### ISSUE THREAD

**Issue by zhuqunzhou** [etcd-io/etcd#8398]
etcd:3.2.0

1.I create a token
![createtoken](https://user-images.githubusercontent.com/10348876/29257204-a5d927bc-80e2-11e7-8142-545817fcb3fd.png)
2.Get data error. response `user name is empty`
![getdata](https://user-images.githubusercontent.com/10348876/29257213-c8d2847a-80e2-11e7-81e7-883ffc468472.png)

**Comment by mitake** [comment]
@zhuqunzhou this issue will be resolved after finishing this PR: https://github.com/coreos/etcd/pull/8289 . Please wait for a while.

**Comment by zhuqunzhou** [comment]
@mitake ,I can use V2 rest api to get data from a authorized v3 cluster now?

**Comment by heyitsanthony** [comment]
@zhuqunzhou I believe this was fixed by #7999

**Comment by mitake** [comment]
@heyitsanthony @zhuqunzhou sorry, like https://github.com/coreos/etcd/issues/8399, this issue was solved by https://github.com/coreos/etcd/pull/7999. Could you try the latest master, @zhuqunzhou ?

**Comment by zhuqunzhou** [comment]
@mitake ,Ok,thanks,I will try it in a few days.

**Comment by heyitsanthony** [comment]
@zhuqunzhou did master solve the problem?

**Comment by zhuqunzhou** [comment]
@heyitsanthony ,Yes,but i just used the master code in my small  test cluster.
