### ISSUE TITLE
Instance failing to join a cluster described by an empty yet initialized discovery token should not register

### ISSUE THREAD

**Issue by bjaglin** [etcd-io/etcd#842]
We started 3 CoreOS instances (alpha 343.0.0 with etcd 0.4.3) against a discovery prefix which had been used in the past but was empty (since the TTL of all previous instances had expired), but that new set of instances never came up (although they now show up under in the discovery prefix) because the agressive etcd timeout resulted in the instances never exactly running at the same time and thus finding each other.

The root cause seems to be the very first instance, which failed to boot, but registered itself anyway, causing further other nodes to fail connecting.

```
Jun 10 13:02:46 ip-10-0-101-160 systemd[1]: Starting etcd...
Jun 10 13:02:46 ip-10-0-101-160 systemd[1]: Started etcd.
Jun 10 13:02:48 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:48.749 INFO | The path /var/lib/etcd/log is in btrfs
Jun 10 13:02:48 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:48.749 INFO | Set NOCOW to path /var/lib/etcd/log succeeded
Jun 10 13:02:48 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:48.749 INFO | Discovery via https://discovery.etcd.io using prefix /bf394045f45fe54b65f6182dc077cbca.
Jun 10 13:02:49 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:49.851 WARNING | Discovery encountered an e
rror: Discovery found an initialized cluster but no reachable peers are registered.
Jun 10 13:02:49 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:49.851 WARNING   | a1433478ab9548dba9d3e97ec5838b22 failed to connect discovery service[https://discovery.etcd.io/bf394045f45fe54b65f6182dc077cbca]: Discovery found an initia
Jun 10 13:02:49 ip-10-0-101-160 etcd[3099]: [etcd] Jun 10 13:02:49.851 CRITICAL  | a1433478ab9548dba9d3e97ec5838b22, the new instance, must register itself to discovery service as required
```

I am not sure what should be the behavior wrt to initialized yet empty seed, but it feels wrong to leave a trace when an etcd instance couldn't connect anyway. After a quick look at the code, shouldn't https://github.com/coreos/etcd/blob/d7768635fd392c18341b597d538a07f8b180f915/etcd/etcd.go#L245 early-return somehow?

**Comment by chrissnell** [comment]
I'm running into this same problem.   To help debug, I'm starting etcd manually on the command line.  Here's what I'm doing:

1. Generated a fresh token:
```curl https://discovery.etcd.io/new```

2. ```rm -rf /var/lib/etcd``` on all nodes

3. Source the network-environment file on node1 with the IP addresses defined:
```. /etc/network-environment```

4. Start etcd on node1.  Log messages look healthy.
```
/usr/bin/etcd -vv -name etcd -cluster-active-size 3 -peer-bind-addr 0.0.0.0 -bind-addr 0.0.0.0 -addr ${DEFAULT_IPV4}:4001 -peer-addr ${DEFAULT_IPV4}:7001 -data-dir /var/lib/etcd -max-retry-attempts 20 -discovery -discoverhttps://discovery.etcd.io/TOKEN_GOES_HERE
```

5. Repeat steps 3 and 4 on node 2.  When I do this, it immediately dies with this error:
```
[etcd] Mar 11 00:49:42.174 DEBUG     | open /var/lib/etcd/snapshot: no such file or directory
[raft]00:49:42.175401 log.open.open  /var/lib/etcd/log
[raft]00:49:42.175512 log.open.create  /var/lib/etcd/log
[etcd] Mar 11 00:49:42.175 DEBUG     | The type of path /var/lib/etcd/log is 2435016766
[etcd] Mar 11 00:49:42.175 INFO      | The path /var/lib/etcd/log is in btrfs
[etcd] Mar 11 00:49:42.175 INFO      | Set NOCOW to path /var/lib/etcd/log succeeded
[etcd] Mar 11 00:49:42.176 INFO      | Discovery via https://discovery.etcd.io using prefix /TOKEN_GOES_HERE.
[etcd] Mar 11 00:49:42.881 WARNING   | Discovery encountered an error: Discovery found an initialized cluster but no reachable peers are registered.
[etcd] Mar 11 00:49:42.881 WARNING   | etcd failed to connect discovery service[https://discovery.etcd.io/TOKEN_GOES_HERE]: Discovery found an initialized cluster but no reachable peers are registered.
[etcd] Mar 11 00:49:42.881 CRITICAL  | etcd, the new instance, must register itself to discovery service as required
```

I'm totally stumped.

**Comment by yichengq** [comment]
@chrissnell Could you do this again and check whether etcd runs well? If not, please open a new issue for discussion.

**Comment by chrissnell** [comment]
It does the same thing, repeatably.  Will open a new issue.
