### ISSUE TITLE
v2v3: stabilize v2 emulation

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#8473]
- [ ] pass all e2e tests
- [ ] pass integration tests
- [ ] TTLs
- [ ] migration
- [ ] document v2 schema

and a cross-checker would be nice

**Comment by raoofm** [comment]
#8407

**Comment by philips** [comment]
Is this actively being worked on? Trying to decide on the plan of attack for https://github.com/coreos/discovery.etcd.io/issues/52

**Comment by gyuho** [comment]
@philips Nobody is actively working on this, right now.
