### ISSUE TITLE
kv RPC QoS

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#8483]
Many concurrent expensive kv operations (e.g., full keyspace fetch) can eat a lot of memory / cpu cycles. To avoid accidentally overloading the system, etcd could potentially classify, bucket, and queue expensive RPCs. For example, QoS would limit keyspace fetches to one at a time.

Sketch of possible implementation:
1. Hash incoming RPC byte slice in the server's grpc codec
2. Create queue for the hash, if first time seen
3. Map RPC structure pointer to hash/queue; enter queue if overloaded
4. Record time/resources to process RPC
5. Update hash queue with runtime info
6. Hash queue dynamically adjusts admission rate to throttle expensive RPCs

**Comment by xiang90** [comment]
moved this to 3.5 from unplanned. QOS becomes a common issue for users with heavy usage.

**Comment by tangcong** [comment]
https://docs.google.com/document/d/122e-uLqngbL9qUEHx4pWcxQj8WO4PCbItTZ-jtkt7ik/edit#

**Comment by tangcong** [comment]
hi,I am interested in implementing the QoS feature and wrote a simple [design solution](https://docs.google.com/document/d/122e-uLqngbL9qUEHx4pWcxQj8WO4PCbItTZ-jtkt7ik/edit#heading=h.vp5jrk2kgj3p). Could you give me some suggestions? thanks. 
https://docs.google.com/document/d/122e-uLqngbL9qUEHx4pWcxQj8WO4PCbItTZ-jtkt7ik/edit#heading=h.vp5jrk2kgj3p

**Comment by tangcong** [comment]
@xiang90 @gyuho @jingyih @heyitsanthony Thank you for taking free time to review the design proposal(WIP). if you roughly agree
 to this feature and design proposal（I am very happy to optimize it  based on your suggestions), i will open a task list issue and use weekend free time to start implementing this feature. thanks.

**Comment by xiang90** [comment]
I will take a look this week, and get back to you. If not, please ping me.

**Comment by plsnotracking** [comment]
@xiang90 pinging you for the review (not op but interested in this feature).
