### ISSUE TITLE
[raft] progress: optimize set pr.next when receive reject MsgAppResp

### ISSUE THREAD

**Issue by shenlanse** [etcd-io/etcd#8544]
**1. Processing Steps** 

When leader sends MsgApp message, it will set `m.Index `and `m.LogTerm`, which are index and term of last sent entry.
https://github.com/coreos/etcd/blob/master/raft/raft.go#L390

when follower receive MsgApp message , it will first check `m.Index `and `m.LogTerm` is matched.
https://github.com/coreos/etcd/blob/master/raft/raft.go#L1119
https://github.com/coreos/etcd/blob/master/raft/log.go#L76

If `matchTerm(m.Index, m.LogTerm)` return false. Follower will return reject MsgAppResp:
`r.send(pb.Message{To: m.From, Type: pb.MsgAppResp, Index: m.Index, Reject: true, RejectHint: r.raftLog.lastIndex()})`

When leader receive reject `MsgAppResp`, leader will call `pr.maybeDecrTo(m.Index, m.RejectHint)`.
```
func (pr *Progress) maybeDecrTo(rejected, last uint64) bool {
	if pr.State == ProgressStateReplicate {
		// the rejection must be stale if the progress has matched and "rejected"
		// is smaller than "match".
		if rejected <= pr.Match {
			return false
		}
		// directly decrease next to match + 1
		pr.Next = pr.Match + 1
		return true
	}

	// the rejection must be stale if "rejected" does not match next - 1
	if pr.Next-1 != rejected {
		return false
	}

	if pr.Next = min(rejected, last+1); pr.Next < 1 {
		pr.Next = 1
	}
	pr.resume()
	return true
}
```
**2. Proposal**
Suppose leader is in `ProgressStateReplicate`.
When follower reject `MsgApp `, it should not only set `RejectHint `but also set corresponding term `RejectTerm`.
`RejectHint `and `RejectTerm `is the last entry of this follower.

Progress should have raftLog reference. when leader receive this reject message, it should call raftLog.matchTerm(RejectHint,RejectTerm ), if return true, we should set:
```
pr.Next = RejectHint + 1
```
If return false, we set:
```
pr.Next = pr.Match + 1
```

**3. Theoretical Foundation**
There is only one leader in one term. 

So entry of (index,term) is also unique. There are not different entries with same term and index. I don't know whether it is right or not. I think it is right

**Comment by shenlanse** [comment]
@heyitsanthony @xiang90

**Comment by xiang90** [comment]
@shenlanse 

The optimization seems safe. However, have you seen this became a problem in any real world use cases?

**Comment by shenlanse** [comment]
@xiang90 Haven't honestly. In some special cases, it will avoid redundant retransmission.

**Comment by xiang90** [comment]
@shenlanse 

I would like to move this forward with real world problems. Or I prefer keeping this as it is, and not complicating the code path.

**Comment by xiang90** [comment]
Any performance measurement against simulated failure cases would also be valuable.
