### ISSUE TITLE
Is there anyway to update lease in a txn?

### ISSUE THREAD

**Issue by xiaoyulei** [etcd-io/etcd#8550]
It looks like there is no lease interface in txn.

**Comment by heyitsanthony** [comment]
@YuleiXiao refresh a lease in a txn? no. What is the use case?

**Comment by YuleiXiao** [comment]
@heyitsanthony 
txn like this:
```
if value==A
then
     extend the lease time
else
    OpPut(key, B)
```

**Comment by heyitsanthony** [comment]
OK, if this feature is going to be supported, it'd be as a flag to Put that would refresh the lease. The Txn interface shouldn't need to change.

**Comment by lorneli** [comment]
How about adding a function `func WithRenewLease(leaseID LeaseID) OpOption`? Similar to [WithIgnoreLease](https://godoc.org/github.com/coreos/etcd/clientv3#WithIgnoreLease) in format.

**Comment by anvinjain** [comment]
An option to update lease associated with a key will be welcome. This is a common pattern for LRU eviction. Right now, I will have to resort to:
> Start transaction
> Check if key exists
> Yes: Get lease associated with key, renew lease
> No: Create lease, put key with new lease
> Commit

**Comment by ssigut** [comment]
Was this implemented or is there any other supported way of doing this?
