### ISSUE TITLE
etcdserver: move accessor auth RPCs out of applier

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#8561]
There are auth RPCs in the etcdserver applier that can have linearization at the API level using the read index facility from 3.1. The RPCs should be moved out of the applier since there's no need to have them there any more and the applier is a critical path. Ideally the API level handling would be in 3.3 and the full removal from the applier path would be in 3.4.

/cc @mitake

**Comment by mitake** [comment]
@heyitsanthony I see, I'll work on it.
