### ISSUE TITLE
Read-Only option for V3 Proxy

### ISSUE THREAD

**Issue by keyankay** [etcd-io/etcd#8622]
https://coreos.com/etcd/docs/latest/v2/proxy.html

The v2 etcd proxy supports two proxy modes: readwrite and readonly. The default mode is readwrite, which forwards both read and write requests to the etcd cluster. A readonly etcd proxy only forwards read requests to the etcd cluster, and returns HTTP 501 to all write requests.

However, I do not see the same in v3 gRPC proxy. Is such an option available in V3 ?

**Comment by gyuho** [comment]
No, it's not supported yet. Do you have read-only gRPC-proxy use case?

**Comment by keyankay** [comment]
Our use case: 
Some etcd client should have write privileges in the internal network, but some etcd clients would not have write privileges which connect from external network.

We were planning to achieve it using ETCD proxy. External clients should go through proxy (readonly privileges), where as the internal clients directly connect to the internal network having readwrite privileges.

**Comment by xiang90** [comment]
@keyankay seems like a useful feature. would you like to work on this feature?

**Comment by keyankay** [comment]
@xiang90 Considering my current work commitments, i dont think i will be able to contribute.

**Comment by lorneli** [comment]
I'm thinking about clearer definition of read-only gRPC proxy. Does it only allows `KVServer.Range`, or it also supports other read type methods like `ClusterServer.MemberList` ?

**Comment by xiang90** [comment]
RPCs that do not change any etcd state.

**Comment by lorneli** [comment]
I wrote code of read-only gRPC proxy locally and plan to add related test. 

Package `grpcproxy` is well tested.(https://codecov.io/gh/coreos/etcd/tree/master/proxy/grpcproxy) But I haven't found where these test code locates . For example, the test of `grpcproxy/auth.go`, and `grpcproxy/election.go`.
