### ISSUE TITLE
grpc-proxy Failed to dial when passing multiple endpoints 

### ISSUE THREAD

**Issue by pritam620** [etcd-io/etcd#8631]
I have a cluster of 3 instance running etcd 3.2.7 on coreos machine on amazon aws.
On 4th ec2 instance I have built etcd latest version (master branch) but when I am trying to run
grpc-proxy with multiple endpoints given below
```
./bin/etcd grpc-proxy start --endpoints=Machine1Ip:2379,Machine2Ip:2379
I am getting following logs
2017-09-30 08:25:38.632975 I | etcdmain: listening for grpc-proxy client requests on 127.0.0.1:23790
WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.
WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.
```

Its working, but only connected to one of the machine.

**Comment by gyuho** [comment]
How did you configure etcd cluster? Master branch works as expected for me.

**Comment by pritam620** [comment]
I have configured etd-cluster using cloud config on coreos machine on aws
```
- name: etcd3.service
     command: start
     runtime: true
     content: |
        [Unit]
        Description=Description=ETCD3
        After=docker.service
        Requires=docker.service

        [Service]
        Restart=on-failure
        RestartSec=30
        ExecStartPre=-/usr/bin/docker kill etcd3
        ExecStartPre=-/usr/bin/docker rm etcd3
        ExecStartPre=/usr/bin/docker pull gcr.io/etcd-development/etcd:latest
        ExecStart=/usr/bin/docker run -p 2379:2379 -p 2380:2380 --volume=/var/lib/etcd:/etcd-data --name etcd3  \
                              gcr.io/etcd-development/etcd:latest \
                              /usr/local/bin/etcd --name etcd3-$private_ipv4 --data-dir=/etcd-data --initial-advertise-peer-urls http://$private_ipv4:2380 --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://$private_ipv4:2379 --discovery http://discovery.etcd.io/<token>
        ExecStop=/usr/bin/docker stop -t 30 etcd3
```

**Comment by gyuho** [comment]
> --discovery http://discovery.etcd.io/<token>

Is your token valid?

**Comment by pritam620** [comment]
My token is valid and cluster is working fine without any issue the problem is only when I try to run

```
etcd grpc-proxy start --endpoints=coreOsMachine1:Ip .... 
```
from other machine then I get warning.
```
2017-09-30 08:25:38.632975 I | etcdmain: listening for grpc-proxy client requests on 127.0.0.1:23790
WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.
WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.
```

**But If I use one endpoint it works without warning.**

**Comment by CHIENPINNWU** [comment]
I suffered the same problem like you; there's an only different part that is I did not use service discovery.

3 etcd members and 1 etcd proxy on AWS ec2 t2.small. (CentOS 7 x86_64)

My main configuration as follows:

[Unit]
Description=etcd
[Service]
Environment=ETCD_NAME=mycluster-etcd-01
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_LISTEN_CLIENT_URLS=http://172.31.26.224:2379,http://127.0.0.1:2379
Environment=ETCD_LISTEN_PEER_URLS=http://172.31.26.224:2380,http://127.0.0.1:2380
Environment=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.31.26.224:2380
Environment=ETCD_ADVERTISE_CLIENT_URLS=http://172.31.26.224:2379
Environment=ETCD_INITIAL_CLUSTER_STATE=new
Environment=ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
Environment=ETCD_INITIAL_CLUSTER=mycluster-etcd-01=http://172.31.26.224:2380,mycluster-etcd-02=http://172.31.24.150:2380,mycluster-etcd-03=http://172.31.23.27:2380
ExecStart=/opt/etcd/bin/etcd
[Install]
WantedBy=multi-user.target 

and two other etcd members with the same configuration besides ETCD_NAME.

**Comment by gyuho** [comment]
@CHIENPINNWU What's the etcd version?

**Comment by CHIENPINNWU** [comment]
@gyuho sorry, I forgot to post the etcd version what it is. The version is 3.2.7.

**Comment by xiang90** [comment]
can you guys try master? maybe this is fixed on master.

@gyuho can you try to reproduce on 3.2.7 too? maybe it is a bug fix worth backporting.

**Comment by gyuho** [comment]
> Failed to dial when passing multiple endpoints

@CHIENPINNWU @pritam620 @xiang90 I believe nothing is broken here. I tried v3.2.8 as well. Works as expected.

Those warnings

> WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.
WARNING: 2017/09/30 08:25:38 Failed to dial Machine1Ip:2379: grpc: the connection is closing; please retry.

are from our client balancer (only master branch) closing out other endpoints after pinning one. So you should be able to connect to `Machine2Ip:2379`. etcd clientv3 does this because there's no need to maintaining multiple TCP connections, switching only when needed.

**Comment by xiang90** [comment]
Can we mute the warning somehow if they are expected

**Comment by xiang90** [comment]
Also it is not clear to me why we still try to use the closed connection and why we created them at the first place

**Comment by gyuho** [comment]
We try all endpoints in the first place, and pin whichever connected first, and close other ones. So other connections may have been created but not pinned so closed. I will see if I can reproduce that warnings.

@pritam620 Which commit in master branch did you run with? Are you running master branch grpc-proxy against 3.2.7 etcd cluster?

**Comment by pritam620** [comment]
@gyuho Yes I am running master with following commit 
```
commit 46223a2202228359b59b1ce65423a4364fd347d4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 8b7fc3e28 530d421f6
Author: Gyu-Ho Lee <gyuhox@gmail.com>
Date:   Mon Oct 2 16:47:22 2017 -0700

    Merge pull request #8638 from gyuho/typo

    Documentation/op-guide: fix typo in configuration.md
```

**Comment by thejmazz** [comment]
> Those warnings are from our client balancer (only master branch) closing out other endpoints after pinning one. So you should be able to connect to Machine2Ip:2379. etcd clientv3 does this because there's no need to maintaining multiple TCP connections, switching only when needed.

Ahh, OK makes sense.

FWIW, from the error message

```
WARNING: 2018/08/15 23:56:00 Failed to dial 10.210.0.12:2379: grpc: the connection is closing; please retry.
```

I thought there was something wrong (v3.3.9). 

> Can we mute the warning somehow if they are expected

Or even just add a log earlier something like "extra connections will be closed, you can ignore warnings"
