### ISSUE TITLE
Improve client v3 API by making options type-safe

### ISSUE THREAD

**Issue by derekchiang** [etcd-io/etcd#8731]
Currently, options are not type-safe in that you can pass the wrong option and the error won't be caught until run time (as opposed to compile time).  For instance:

```go
// `Put` doesn't actually accept `WithRev`!
kvc.Put(ctx, "sample_key", "sample_value", WithRev(1)) 
```

I had an idea where you could make the options type-safe.  I wrote [a blog post here](https://derekchiang.com/posts/reusable-and-type-safe-options-for-go-apis/) and [an example here](https://gist.github.com/derekchiang/c9709eace4b588353ec9df32d845ac9c), but basically the idea is that options like `WithRev` would return a `struct` which implements one `interface` per API that it supports.  Then, APIs like `Put` would accept options of a particular interface.

Would you guys be interested in adopting this pattern?  I don't mind doing the grunt work of actually implementing it, but wanted to check with you guys first.

**Comment by wenjiaswe** [comment]
@jingyih

**Comment by jingyih** [comment]
I think it is a nice improvement if the wrong options can be caught in compile time.  However we need to be very careful about backward compatibility.  For example, the current `put` API is 

https://github.com/etcd-io/etcd/blob/3c6c05be8a4d0070c10f6cfe563b73e7b655fa33/clientv3/kv.go#L38

And I do not think we should change it.
