### ISSUE TITLE
How does one interpret /v2/stats/store JSON data?

### ISSUE THREAD

**Issue by marc-barry** [etcd-io/etcd#878]
Below is some example store JSON data from one of our nodes (i.e. URL /v2/stats/store). Can someone help me interpret exactly what the values mean?

For example, how does one interpret a `getsSuccess` versus a `getsFail`? It would appear `getsSuccess` are a count of the number of key gets. But what does `gtesFail` mean? Isn't it only a client who knows if a key get failed or is this metric the result of an internal `etcd` failure?

I think `watchers` is self-explanatory and does correspond to the number of watchers on this node.

``` json
{
"getsSuccess": 2538969,
"getsFail": 7249604,
"setsSuccess": 905188,
"setsFail": 853,
"deleteSuccess": 4752,
"deleteFail": 4885,
"updateSuccess": 643812,
"updateFail": 340,
"createSuccess": 3461,
"createFail": 43555,
"compareAndSwapSuccess": 0,
"compareAndSwapFail": 0,
"compareAndDeleteSuccess": 1948,
"compareAndDeleteFail": 26,
"expireCount": 0,
"watchers": 2
}
```

**Comment by veverjak** [comment]
May I post additional question? 

I am having quite high number of `"getsFail": 7249604,` and its rising rapidly. I would like to find out which key is not found. 

I've ran etcd with -vv flags but it didn't tell me which keys have failed. Is there some way to find out. 

I am runnig etcd 0.4.7

**Comment by yichengq** [comment]
@veverjak

There is no easy way to find the missed key in server side. The clients
should know more about the failure IMO. In etcd 2.1, it supports to print
out all HTTP requests when running in debug mode, which may be helpful for
your case.

**Comment by veverjak** [comment]
ok, thanks, 

the question is which client it is :) 

Hopefully we will get to using etcd 2.1 soon too... Thanks for info

**Comment by philips** [comment]
We should improve the docs, I was confused by getFails too. Can someone take a swing at this?
