### ISSUE TITLE
tests: clean up random sleep time values

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#8781]
https://github.com/coreos/etcd/pull/8762#discussion_r147490173

> To help maintain the tests and keep flakiness to a minimum, should we establish a set of constants that we references from the integration tests instead? E.g instead of 3 here, maybe have a constant like maxLeaderChangeWait. Once we have a reasonable set of constants, then developers don't need to try to figure out what a good number of seconds is each time they write a test, and if we determine we need to increase the number to minimize test flakes based, we can change it in one place...

https://github.com/coreos/etcd/pull/8779#discussion_r147491093

> as @jpbetz mentioned in other pr, we should define leader election timeout as a const somehere. and normal waiting timeout too. so this could be rewritten to electionWait + retryWait

Also https://github.com/coreos/etcd/issues/8757#issuecomment-340824525 and https://github.com/coreos/etcd/pull/8795.

/cc @jpbetz @xiang90

**Comment by hexfusion** [comment]
If this is not been picked up I would like to give it a go.

**Comment by xiang90** [comment]
@hexfusion sure. thanks.
