### ISSUE TITLE
etcd on reboot fails to form a cluster

### ISSUE THREAD

**Issue by fleiner** [etcd-io/etcd#884]
This is with four etcd instances, running in a cluster, then power cycling all four machines. After reboot and restart I end up with three machines waiting to 
    WARNING | fail getting leader from cluster
and one that claims
    WARNING | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field

All of them start with the following command line (the first time they got started with the appropriate -peers option):

etcd -name n3 -data-dir /var/etcd -addr 172.28.254.23:4001 -peer-addr 172.28.254.23:7001 -peer-heartbeat-interval 200

(the IP address is of course the local one)

Any idea what might be wrong, especially with the one that complains about the mismatch?

thanks

**Comment by devurandom** [comment]
I have the same issue as @fleiner after updating from 647.2.0 (last stable) to 681.0.0 (current stable): `sudo find / -name standby_info` finds no standby_info file at all in the entire system…
