### ISSUE TITLE
keep CI runs under 10 minutes

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#8862]
Now CI takes ~30 minutes to finish. This impacts the developer experience and affects productivity. We should run tests in parallel, and remove unnecessary internal waits to significantly decrease CI run duration.

**Comment by gyuho** [comment]
We got to reduce it to <15-minute for critical tests (unit, integration, <20-min for functional tests). But, tests running in Jenkins (proxy, coverage, etc.) still takes >30-min. Will reduce it more in v3.5 release cycle.

**Comment by gyuho** [comment]
Moving this to https://github.com/etcd-io/etcd/issues/10192. Once we integrate Prow, all test suites can be parallelized. Currently, it's limited by travis (or sempahore) free tier worker node limits (only supports up to 4 worker nodes).
