### ISSUE TITLE
rogue followers containing keys with negative TTL

### ISSUE THREAD

**Issue by jcamelon** [etcd-io/etcd#894]
We are running etcd 0.45.  

Today we installed a new build to our test cluster and everything seemed to come up fine.  Over time while testing, I noticed that some of the keys were out of sync ... trying to delete key /x/abc from follower 1 would redirect to leader and get a 404 because /x/abc  did not exist.   What seemed to be happening was that the follower believed it was part of the cluster but not receiving updates.  Many of the keys that we were PUT-ing now had negative TTL's and were not expiring.   Restarting the follower node made it come back into line with the rest of the cluster.   

I recognize that there is a fair amount of information I would need to provide to reproduce a problem like this ... and I will if you ask.  It may take some work to generalize what we are experiencing to be something that can be reproduced without our applciation.   

In order to mitigate this kind of problem, I am wondering if there is some simple /stats/store/log_is_at_version call I can make to see how far out of sync my followers are, so that I can detect when something like this is happening and restart that follower.

**Comment by garo** [comment]
Just got my production cluster into negative ttl after the cluster was under pretty heavy load. Trying to delete the records with negative ttl just returned Internal Server Error. I had to relaunch the cluster from snapshot to fix.

etcd 2.0.10
