### ISSUE TITLE
Failed to save KV snapshot results in data directory to be cluttered with temp files

### ISSUE THREAD

**Issue by nvtkaszpir** [etcd-io/etcd#8964]
# Description
When ETCD executes snapshot it creates temporary file in `data` directory.
If snapshot operation ends with error, then that temporary file stays in the `data` directory, but it will contain corrupted snapshot.

On next start ETCD scans files in `data` directory, and shows the following messages:
```text
2017-12-02 20:42:39.630064 W | snap: skipped unexpected non snapshot file tmp807356670
2017-12-02 20:42:39.630098 W | snap: skipped unexpected non snapshot file tmp724762870
2017-12-02 20:42:39.630102 W | snap: skipped unexpected non snapshot file tmp995085740
2017-12-02 20:42:39.630105 W | snap: skipped unexpected non snapshot file tmp005122525
2017-12-02 20:42:39.630107 W | snap: skipped unexpected non snapshot file tmp292930387
2017-12-02 20:42:39.630111 W | snap: skipped unexpected non snapshot file tmp271606753
```
This is expected, that it leaves files intact.

Either way etcd when doing snapshot (which will fail from any reason) will leave such file. This easily leads to disk filling with temp files stuffed with garbage inside.

# Question
Wouldn't it better so that ectd would remove temporary file if snapshot creation failed?
Or do you think it is in the admin hands to manage that temporary files, because they may contain valid data for recovery on crash or debugging purposes?
Another idea, maybe etcd should check free disk space before doing snapshot? Although with thin provisioned storages this may be problematic...

# Versions:
```text
2017-12-02 20:42:36.713865 I | etcdmain: etcd Version: 3.2.6
2017-12-02 20:42:36.713894 I | etcdmain: Git SHA: 9d43462
2017-12-02 20:42:36.713905 I | etcdmain: Go Version: go1.8.3
2017-12-02 20:42:36.713917 I | etcdmain: Go OS/Arch: linux/amd64
```

**Comment by xiang90** [comment]
the tmp file might contain valid data (for example rename failed). and, yes, for debugging purpose we leave them there. however, if etcd starts successfully with a valid snapshot, it can clean tmp files up automatically with very low risk.

do you want to help on this one?

**Comment by nvtkaszpir** [comment]
I'v just tested another scenario: 
- stopped etcd
- copied one of *.snap file as `copy_of_last_snap` file name
-  started etcd again.
Looks like etcd actually skips this file, even though this is a snapshot file (looks like it prefers properly named filenames?)
```text
2017-12-02 21:24:41.292290 W | snap: skipped unexpected non snapshot file copy_of_last_snap
```

So I think the best solution would be to leave info in etcd docs that for maintenace reasons admins should add something like cron job to delete files from `data` directory which are not named `db` or 
 `*.snap`,  and are older than let say 24h.

**Comment by xiang90** [comment]
> copied one of *.snap file as copy_of_last_snap file name

we do not expect users to touch the data dir owned by etcd.

**Comment by nvtkaszpir** [comment]
Yes I know, I did that on purpose, but in normal circumstances I've experienced that new node which connected to etcd cluster received snapshot so large it was impossible to fit it in the `data` storage. Maybe it should be done in smaller chunks, then?

**Comment by xiang90** [comment]
> Maybe it should be done in smaller chunks, then?

even if we chunk it, it makes no difference. the other side cannot receive full data and cannot reload it. all the data needs to be on disk. you should prepare for enough disk space.

**Comment by nvtkaszpir** [comment]
Leaving temporary files - due to failure taking snapshot because of lack of space - then it's capacity planning issue which is out of scope of the etcd.

In any other scenario - leaving temp dump is for helping debugging issue to discover what was the cause of the failure - and then deleting file automaically is not advised, and means it requires manual intervention of th operator.

Either way it's "won't do", but maybe it is worth to note in the docs about how etcd reacts on low disk space during snapshots.

**Comment by jpbetz** [comment]
@xiang90 Sounds good. I'll have a look.
