### ISSUE TITLE
Use gossip protocol for real service discovery

### ISSUE THREAD

**Issue by pkieltyka** [etcd-io/etcd#902]
Hello,

I feel a simplification in the design of etcd would be if it didnt require a discovery node... just like a real/fully distributed system and would move over to a design like consul. Etcd has a nice http interface, and is already established in coreos.. I get that.. but I feel consul has a superior design. Perhaps, use the serf project right in etcd? ..

**Comment by anhldbk** [comment]
@pkieltyka Almost 3 years :+1: 

>  I just feel the service discovery should be gossip based
