### ISSUE TITLE
etcd's maintenance snapshot api doesn't return etcd kv revision.

### ISSUE THREAD

**Issue by fanminshi** [etcd-io/etcd#9037]
Currently, there isn't good way get the kv store revision of the snapshot return by maintenance snapshot api without opening it up using boltdb. In etcd operator, we want to know the snapshot's kv store revision when we perform an backup. The current way to achieve that is to first made a GET call to etcd server and use the header from the resp as the kv store revision. However, this approach is not correct. Suppose that if there are additional mutating calls made to etcd server after the GET and before snapshot api, then the supposed kv store revision from initial GET doesn't represent the kv store revision inside the snapshot returned by the snapshot api call.

It will be nice to have a easy mechanism to determine kv store revision of snapshot returned by the maintenance's snapshot API.

**Comment by hexfusion** [comment]
> It will be nice to have a easy mechanism to determine kv store revision of snapshot returned by the maintenance's snapshot API.

Hi @fanminshi, this sounds interesting, I have a couple questions. What does the revision represent exactly? The state of KV at point X? How would that revision be transferable? Meaning once you have $revision, what can you do with it, independent from the snapshot itself. I am trying to understand the big picture :).

**Comment by fanminshi** [comment]
`What does the revision represent exactly`
it is state of KV when snapshot begins.

`How would that revision be transferable? Meaning once you have $revision, what can you do with it`
Suppose that I want to back up of an etcd server. At T= 0, it has revision == 100. I call snapshot and back up the kv-state at 100. After a while at T = 100, nothing changes and it still has revision == 100. If I am smart, I know that the previous snapshot contains rev=100, then I don't have to get snapshot from server and perform an additional backup. That's why knowing the revision of snapshot allowing me to create an optimized on backing up strategy.

**Comment by hexfusion** [comment]
> That's why knowing the revision of snapshot allowing me to create an optimized on backing up strategy.

@fanminshi, so if the KV is unchanged why backup same data again? That makes sense. What about time-based data like Lease TTL. Does a snapshot also represent that data? I just wonder if time is another component of a snapshot, and how that is handled? Thank you for your answers!

**Comment by fanminshi** [comment]
`Does a snapshot also represent that data?`
Yes, snapshot does contain all the Leases.

`I just wonder if time is another component of a snapshot, and how that is handled? Thank you for your answers!`
If I remember correctly, the Lease TTL saved snapshot will be renewed when snapshot is restored into a new cluster. I am unaware of any other time based information that's saved in snapshot.

**Comment by hexfusion** [comment]
> If I remember correctly, the Lease TTL saved snapshot will be renewed when snapshot is restored into a new cluster. 

Nice, so all existing Lease TTL are renewed and if a Lease expires KV revision is no longer the same. 👍

**Comment by fanminshi** [comment]
`if a Lease expires KV revision is no longer the same. `
actually, Leases are not revisioned. If an lease is expired and it is not associated with a key, it will not change KV's revision.

**Comment by fanminshi** [comment]
@hexfusion snapshot is basically a boltdb file. kv is under a bucket and it is versioned. lease is under another bucket and is not versioned.

**Comment by hexfusion** [comment]
@fanminshi so is the only guarantee with a snapshot KV state? The issue I see is 2 snapshots with same KV state but Lease is not the same. So in this case are these two snapshots the same snapshot revision? Is that something we should be concerned with? I guess as long as that is documented but it seems an easy thing to assume, that all state is the same if snapshot revision's are the same.

**Comment by fanminshi** [comment]
@hexfusion 
A snapshot from maintenance snapshot api will return current KV state, leases, and everything else that's stored in etcd server. 
`so is the only guarantee with a snapshot KV state?`
my proposed back strategy only guarantee KV state. But there can be other backup strategy that just backup everything every 5 minutes regardless of kv store revision. So that the lease state is at least 5 minutes out of sync.

`So in this case are these two snapshots the same snapshot revision? Is that something we should be concerned with?`
My proposed backup strategy only cares about KV state.  If we care about time based data, then we might consider using different backup strategy to make sure that time based data is out of sync at a minimum. However, I am unsure what's best way to reason about time based data in a backup. 

`it seems an easy thing to assume, that all state is the same if snapshot revision's are the same.`
Yeah, we should be more clear on this. revision only applies to KV state not leases.

**Comment by wenjiaswe** [comment]
cc @jingyih

**Comment by jingyih** [comment]
@fanminshi is the revision returned by `etcdctl snapshot status` the one you are looking for?

**Comment by jingyih** [comment]
@fanminshi I am closing this issue now (in attempt to reduce the number of open issues).  If you think it is not resolved, please reopen it.
