### ISSUE TITLE
raft err :unexpected error getting unapplied entries 

### ISSUE THREAD

**Issue by theleft2018** [etcd-io/etcd#9079]
`2017-12-19 06:44:13.710498 I | rafthttp: peer 25983019632d3b71 became inactive`

`2017-12-19 06:46:11.027139 W | wal: sync duration of 53.623726271s, expected less than 1s`
`2017-12-19 06:47:38.644871 W | rafthttp: lost the TCP streaming connection with peer` `25983019632d3b71 (stream MsgApp v2 writer)`
`2017-12-19 06:47:38.662303 W | rafthttp: dropped internal raft message from 6c36ea01f4c3ff97 since receiving buffer is full (overloaded network)`
`2017-12-19 06:47:38.701115 I | pkg/fileutil: purged file /var/etcd-data/etcd-event/etcd-event-1/member/snap/000000000000073d-000000001c261685.snap successfully`
`2017-12-19 06:47:38.703887 E | rafthttp: failed to heartbeat 6c36ea01f4c3ff97 on stream Message (write tcp 192.145.18.176:2381->192.145.18.175:44366: write: broken pipe)`
`2017-12-19 06:47:38.703907 I | rafthttp: peer 6c36ea01f4c3ff97 became inactive`
`2017-12-19 06:47:38.704804 W | rafthttp: lost the TCP streaming connection with peer 6c36ea01f4c3ff97 (stream Message writer)`
`2017-12-19 06:47:38.943486 I | etcdserver: saved snapshot at index 472308405`
`2017-12-19 06:47:39.219011 I | etcdserver: compacted raft log at 472303405`
`2017-12-19 06:47:39.219045 I | rafthttp: peer 6c36ea01f4c3ff97 became active`
`2017-12-19 06:47:39.266049 I | rafthttp: receiving database snapshot [index:472372997, from 6c36ea01f4c3ff97] ...`
`2017-12-19 06:47:39.365210 W | rafthttp: dropped internal raft message to 6c36ea01f4c3ff97 since pipeline's sending buffer is full (bad/overloaded network)`
`2017-12-19 06:47:39.366098 I | rafthttp: established a TCP streaming connection with peer 6c36ea01f4c3ff97 (stream Message writer)`
`2017-12-19 06:47:39.368577 W | rafthttp: dropped internal raft message to 6c36ea01f4c3ff97 since streamMsg's sending buffer is full (bad/overloaded network)`
`2017-12-19 06:47:39.424429 W | rafthttp: closed an existing TCP streaming connection with peer 6c36ea01f4c3ff97 (stream MsgApp v2 writer)`
`2017-12-19 06:47:39.424456 I | rafthttp: established a TCP streaming connection with peer 6c36ea01f4c3ff97 (stream MsgApp v2 writer)`
`2017-12-19 06:47:39.425430 I | rafthttp: peer 25983019632d3b71 became active`
`2017-12-19 06:47:39.425451 I | rafthttp: established a TCP streaming connection with peer 25983019632d3b71 (stream MsgApp v2 writer)`
`2017-12-19 06:47:39.473548 W | rafthttp: closed an existing TCP streaming connection with peer 25983019632d3b71 (stream Message writer)`
`2017-12-19 06:47:39.473575 I | rafthttp: established a TCP streaming connection with peer 25983019632d3b71 (stream Message writer)`
`2017-12-19 06:47:47.235357 I | snap: saved database snapshot to disk [total bytes: 128724992]`
`2017-12-19 06:47:48.549659 I | rafthttp: received and saved database snapshot [index: 472372997, from: 6c36ea01f4c3ff97] successfully`
`2017-12-19 06:47:48.549804 I | raft: bda4ffc1bc48207d [commit: 472310039, lastindex: 472310039, lastterm: 1853] starts to restore snapshot [index: 472372997, term: 1853]`
`2017-12-19 06:47:48.549823 I | raft: log [committed=472310039, applied=472310039, unstable.offset=472310040, len(unstable.Entries)=0] starts to restore snapshot [index: 472372997, term: 1853]`
`2017-12-19 06:48:07.671516 W | rafthttp: dropped internal raft message from 6c36ea01f4c3ff97 since receiving buffer is full (overloaded network) [merged 273 repeated lines in 1.23s]`
`2017-12-19 06:48:07.671574 W | rafthttp: dropped internal raft message to 6c36ea01f4c3ff97 since streamMsg's sending buffer is full (bad/overloaded network) [merged 4574 repeated lines in 1.52s]`
`2017-12-19 06:48:07.689540 I | raft: bda4ffc1bc48207d restored progress of 25983019632d3b71 [next = 472372998, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]`
`2017-12-19 06:48:07.689574 I | raft: bda4ffc1bc48207d restored progress of 6c36ea01f4c3ff97 [next = 472372998, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]`
`2017-12-19 06:48:07.689583 I | raft: bda4ffc1bc48207d restored progress of bda4ffc1bc48207d [next = 472372998, match = 472372997, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]`
`2017-12-19 06:48:07.689594 I | raft: bda4ffc1bc48207d [commit: 472372997] restored snapshot [index: 472372997, term: 1853]`
`2017-12-19 06:48:07.689643 C | raft: unexpected error getting unapplied entries (requested index is unavailable due to compaction)`
`panic: unexpected error getting unapplied entries (requested index is unavailable due to compaction)`

`goroutine 97 [running]:
panic(0xcf25a0, 0xc427689990)
        /opt/env/go1.7.4/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201cf7c0, 0xea916a, 0x2f, 0xc427689920, 0x1, 0x1)`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x16a`
`github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4201061e0, 0x0, 0x0, 0xbda4ffc1bc48207d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:742 +0x57b`
`github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).tickElection(0xc4201061e0)`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:531 +0x129`
`github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).(github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.tickElection)-fm()`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:564 +0x2a`
`github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).run(0xc4203cc300, 0xc4201061e0)`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:350 +0xb52`
`created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode`
        `/opt/go/src/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:219 +0x33c`

**Comment by hexfusion** [comment]
@theleft2018 can you display the output of `etcd --version` please and can you replicate the issue using a simple script? Any other details you can provide outside of the log entry will be helpful.

**Comment by theleft2018** [comment]
etcd version :3.1.9

**Comment by xiang90** [comment]
@theleft2018 are you able to reproduce this problem reliably?

**Comment by theleft2018** [comment]
@xiang90 no,we only find this issue once.

**Comment by berlinsaint** [comment]
i find this iusse again and again:
and i don't think my server is overloaded
[etcd.log](https://github.com/coreos/etcd/files/1676624/etcd.log)
