### ISSUE TITLE
Unrecoverable Cluster after ETCD process was being killed by the OS

### ISSUE THREAD

**Issue by ThomasAlxDmy** [etcd-io/etcd#910]
During a big benchmark of my ETCD cluster, I reached the limit of my instances' memory which caused the OS to kill the etcd process on two of the 3 machines(1 leader and 1 follower.). 

After that, I haven't been able to restart my cluster, getting a go `index out of range` error. Here's what I got in the log, notice the `Killed` during the election process:

[etcd] Jul 29 17:24:56.348 INFO      | etcd-dev-1400.com: term #1394 started.
[etcd] Jul 29 17:24:56.814 INFO      | etcd-dev-1400.com: state changed from 'follower' to 'candidate'.
[etcd] Jul 29 17:24:56.814 INFO      | etcd-dev-1400.com: leader changed from 'etcd-dev-1100.com' to ''.
Killed
[etcd] Jul 29 18:29:42.313 INFO      | Peer URLs in log:  / etcd-dev-1400.com ()
[etcd] Jul 29 18:29:42.314 INFO      | etcd server [name etcd-dev-1400.com, listen on :4001, advertised url http://etcd-dev-1400.com:4001]
[etcd] Jul 29 18:29:42.315 INFO      | peer server [name etcd-dev-1400.com, listen on :7001, advertised url http://etcd-dev-1400.com:7001]
[etcd] Jul 29 18:29:42.315 INFO      | etcd-dev-1400.com starting in peer mode
[etcd] Jul 29 18:29:42.315 INFO      | etcd-dev-1400.com: state changed from 'initialized' to 'follower'.
[etcd] Jul 29 18:29:42.643 INFO      | etcd-dev-1400.com: state changed from 'follower' to 'candidate'.
[etcd] Jul 29 18:29:42.643 INFO      | etcd-dev-1400.com: state changed from 'candidate' to 'leader'.
[etcd] Jul 29 18:29:42.643 INFO      | etcd-dev-1400.com: leader changed from '' to 'etcd-dev-1400.com'.
panic: runtime error: index out of range

goroutine 29 [running]:
runtime.panic(0x896820, 0xcb0cbc)
  /home/ubuntu/goroot/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_Log).commitInfo(0xc208022770, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/log.go:301 +0x33a
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).TakeSnapshot(0xc208003e60, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:1203 +0x2aa
github.com/coreos/etcd/server.(_PeerServer).monitorSnapshot(0xc2080ae200)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:785 +0x15c
github.com/coreos/etcd/server._PeerServer.(github.com/coreos/etcd/server.monitorSnapshot)·fm()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:298 +0x26
github.com/coreos/etcd/server.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4

goroutine 16 [select]:
github.com/coreos/etcd/etcd.(_Etcd).runServer(0xc20804e400)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:327 +0xa4a
github.com/coreos/etcd/etcd.(_Etcd).Run(0xc20804e400)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:298 +0x3352
main.main()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/main.go:43 +0x2b8

goroutine 19 [finalizer wait]:
runtime.park(0x4139d0, 0xcb72d0, 0xcb4d89)
  /home/ubuntu/goroot/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xcb72d0, 0xcb4d89)
  /home/ubuntu/goroot/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
  /home/ubuntu/goroot/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
  /home/ubuntu/goroot/go/src/pkg/runtime/proc.c:1445

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7fa9d5506660, 0x72, 0x0)
  /home/ubuntu/goroot/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(_pollDesc).Wait(0xc20855c140, 0x72, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(_pollDesc).WaitRead(0xc20855c140, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(_netFD).accept(0xc20855c0e0, 0x9fa220, 0x0, 0x7fa9d5505418, 0xb)
  /home/ubuntu/goroot/go/src/pkg/net/fd_unix.go:409 +0x343
net.(_TCPListener).AcceptTCP(0xc208038648, 0xc20803f728, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(_TCPListener).Accept(0xc208038648, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(_Server).Serve(0xc208517f20, 0x7fa9d5518178, 0xc208038648, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcd.func·001()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:282 +0xa2
created by github.com/coreos/etcd/etcd.(*Etcd).Run
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:287 +0x32c4

goroutine 21 [syscall]:
os/signal.loop()
  /home/ubuntu/goroot/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
  /home/ubuntu/goroot/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 23 [IO wait]:
net.runtime_pollWait(0x7fa9d55065b0, 0x72, 0x0)
  /home/ubuntu/goroot/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(_pollDesc).Wait(0xc20855c290, 0x72, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(_pollDesc).WaitRead(0xc20855c290, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(_netFD).accept(0xc20855c230, 0x9fa220, 0x0, 0x7fa9d5505418, 0xb)
  /home/ubuntu/goroot/go/src/pkg/net/fd_unix.go:409 +0x343
net.(_TCPListener).AcceptTCP(0xc208038650, 0xc20850bbe8, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(_TCPListener).Accept(0xc208038650, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(_Server).Serve(0xc208517f80, 0x7fa9d5518178, 0xc208038650, 0x0, 0x0)
  /home/ubuntu/goroot/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcd.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:291 +0xa2
created by github.com/coreos/etcd/etcd.(*Etcd).Run
  /home/ubuntu/goroot/src/github.com/coreos/etcd/etcd/etcd.go:296 +0x333c

goroutine 24 [select]:
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).leaderLoop(0xc208003e60)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:835 +0x6c5
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).loop(0xc208003e60)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:610 +0x3d1
github.com/coreos/etcd/third_party/github.com/goraft/raft.func·007()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:471 +0x5d
created by github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).Start
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:472 +0x3b8

goroutine 25 [select]:
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).send(0xc208003e60, 0x872060, 0xc20888e3a0, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:631 +0x279
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).Do(0xc208003e60, 0x7fa9d55069d8, 0xc20888e3a0, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:898 +0x7c
github.com/coreos/etcd/server.(_PeerServer).monitorSync(0xc2080ae200)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:801 +0x282
github.com/coreos/etcd/server._PeerServer.(github.com/coreos/etcd/server.monitorSync)·fm()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:291 +0x26
github.com/coreos/etcd/server.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4

goroutine 26 [select]:
github.com/coreos/etcd/server.(_PeerServer).monitorTimeoutThreshold(0xc2080ae200)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:813 +0x27c
github.com/coreos/etcd/server._PeerServer.(github.com/coreos/etcd/server.monitorTimeoutThreshold)·fm()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:292 +0x26
github.com/coreos/etcd/server.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4

goroutine 27 [select]:
github.com/coreos/etcd/server.(_PeerServer).monitorActiveSize(0xc2080ae200)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:834 +0x81a
github.com/coreos/etcd/server._PeerServer.(github.com/coreos/etcd/server.monitorActiveSize)·fm()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:293 +0x26
github.com/coreos/etcd/server.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4

goroutine 28 [select]:
github.com/coreos/etcd/server.(_PeerServer).monitorPeerActivity(0xc2080ae200)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:870 +0x756
github.com/coreos/etcd/server._PeerServer.(github.com/coreos/etcd/server.monitorPeerActivity)·fm()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:294 +0x26
github.com/coreos/etcd/server.func·002()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
  /home/ubuntu/goroot/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4

goroutine 31 [select]:
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).send(0xc208003e60, 0x8a2680, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:631 +0x279
github.com/coreos/etcd/third_party/github.com/goraft/raft.(_server).Do(0xc208003e60, 0x7fa9d55182b8, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:898 +0x7c
github.com/coreos/etcd/third_party/github.com/goraft/raft.func·010()
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:829 +0xab
created by github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).leaderLoop
  /home/ubuntu/goroot/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:830 +0x257

**Comment by Vish0007** [comment]
@kelseyhightower , is this fix available in some CoreOS version?
