### ISSUE TITLE
RFC : TXT DNS discovery

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#9128]
TXT based DNS discovery allows for discovery based on TXT record. The token name will be used as the TXT and A record name. This not only binds the cluster to a specific domain but also uses the token name to anchor the discovery process.

The TXT record could define various key/value pairs but scheme and client/server port are required. 

At this point I am curious if this could be useful alternative to SRV discovery. Any input is welcome. 

### Create DNS TXT records
```
; TXT record
etcd-cluster-1                300 IN  TXT  "scheme=https" "server=2379" "client=2380"
```
```
$ dig +short -t txt etcd-cluster-1.sub.hexfusion.local
"scheme=https" "server=2379" "client=2380"
```
```
; A records
$ORIGIN sub.hexfusion.local.

infra0     IN       A      10.0.1.10
infra1     IN       A      10.0.1.11
infra2     IN       A      10.0.1.12

etcd-cluster-1   IN       A      10.0.1.10
etcd-cluster-1   IN       A      10.0.1.11
etcd-cluster-1   IN       A      10.0.1.12
```
```
$ dig +short etcd-cluster-1.sub.hexfusion.local
10.0.1.10
10.0.1.11
10.0.1.12
```
```
;PTR Record IP address to HostName
10     IN      PTR    infra0.sub.hexfusion.local.
11     IN      PTR    infra1.sub.hexfusion.local.
12     IN      PTR    infra2.sub.hexfusion.local.
```
```
$ dig +short -x 10.0.1.10
infra0.sub.hexfusion.local.
```

### Bootstrap the etcd cluster using DNS
```
$ etcd --name infra0 \
--discovery-txt sub.hexfusion.local \
--initial-advertise-peer-urls http://10.0.1.10:2380 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster-state new \
--advertise-client-urls http://10.0.1.10:2379 \
--listen-client-urls http://10.0.1.10:2379 \
--listen-peer-urls http://10.0.1.10:2380
```
```
$ etcd --name infra1 \
--discovery-txt sub.hexfusion.local \
--initial-advertise-peer-urls http://10.0.1.11:2380 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster-state new \
--advertise-client-urls http://10.0.1.11:2379 \
--listen-client-urls http://10.0.1.11:2379 \
--listen-peer-urls http://10.0.1.11:2380
```
```
$ etcd --name infra2 \
--discovery-txt sub.hexfusion.local \
--initial-advertise-peer-urls http://10.0.1.12:2380 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster-state new \
--advertise-client-urls http://10.0.1.12:2379 \
--listen-client-urls http://10.0.1.12:2379 \
--listen-peer-urls http://10.0.1.12:2380
```

**Comment by hexfusion** [comment]
@gyuho @xiang90 does this make any sense? The only thing I find of interest here is the possible ability to add metadata in the TXT record about the cluster vs SRV. The downside would be standardizing/validating the format of the metadata records. So supporting could be more "work".  But perhaps it could facilitate more complex bootstrapping workflows. Workflows perhaps yet to be identified.

**Comment by hexfusion** [comment]
I will work on a PR if you find the basic concept reasonable.

**Comment by xiang90** [comment]
the concept looks fine to me. but do we hear any user wants this feature? i want some validation on this use case before commit to it.

**Comment by hexfusion** [comment]
Valid point no user has commented. As the idea is valid, please leave this open for a while and we can see if it gets any comment.

**Comment by xiang90** [comment]
@hexfusion sure. we will leave this open. users can +1 on this issue if they see a fit.
