### ISSUE TITLE
Improve e2e test coverage

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#9149]
While etcd `integration`  and `clientv3/integration` test its functionalities to ensure its correctness, [`e2e`](https://github.com/coreos/etcd/tree/master/e2e) verifies `etcdctl` output on each command with various user inputs.

Most of the commands are already covered, but not all possible cases (e.g., `endpoint health` with auth enabled, TLS enabled).

Improve e2e test coverage by:

1. check what's missing/tested in e2e
2. add more tests to cover those missing cases

**Comment by gyuho** [comment]
@hexfusion Do you want to work on this?

**Comment by hexfusion** [comment]
@gyuho I do.

**Comment by hexfusion** [comment]
started a [doc](https://docs.google.com/spreadsheets/d/1XQ0H7rS3TPnLOE1SxnbykU68WXWIm-on-aWMOIAN8Mk/edit?usp=sharing) to try and flush out coverage. Anyone can feel free to update.
