### ISSUE TITLE
etcd v3 clients feature/maturity matrix

### ISSUE THREAD

**Issue by xiang90** [etcd-io/etcd#9156]
There are currently two "official" etcd v3 clients, written in go and java. Our users want us to  provide help on the etcd clients written in other languages (python, ruby, etc.)

To get started, I propose to start define the functionalities that a client should support, and a way to measure the maturity. At least, our users can choose external client more wisely. Also we can encourage the client writers to stabilize their client when there is a guideline.

/cc @davissp14 @jpbetz

**Comment by davissp14** [comment]
@xiang90 What are your thoughts on `etcd-io` absorbing my `etcdv3-ruby` client?  https://github.com/davissp14/etcdv3-ruby
