### ISSUE TITLE
At private lan discovery, servers fail to re-join after reboot

### ISSUE THREAD

**Issue by ghost** [etcd-io/etcd#919]
Hello,

I found coreos such a great project, so I start exploring it with very possitive results. I have one problem with the following scenario. I have 3 bare metal servers, which all are started though ipxe/apache because it is faster than the classic pxe. 
    core01  10.25.100.247
    core02  10.25.100.248
    core03  10.25.100.249
I choose to have "my Own Discovery" using the token test-cluster
I use the core01 only for the initial cluster , so only the other two core02,core03 are active cluster members. The core01 cloud-config is
# cloud-config

hostname: core01
....
coreos:
  etcd:
    name: core01
    addr: 10.25.100.247:4001
    peer-addr: 10.25.100.247:7001  
  fleet:
    public-ip: 10.25.100.247
    metadata: region=us-west

I am starting core01 and after it is fully started, I start the other two with the following cloud-config ( core02 sample) 
# cloud-config

hostname: core02
...
coreos:
  etcd:
    name: core02
    addr: 10.25.100.248:4001
    peer-addr: 10.25.100.248:7001  
    discovery: http://10.25.100.247:4001/v2/keys/test-cluster
  fleet:
    public-ip: 10.25.100.248
    metadata: region=us-west
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

write_files:
- path: /etc/hosts
  permissions: 0644
  content: |
    10.25.100.247 core01
    10.25.100.248 core02
    10.25.100.248 core03

Both core02, core03 become members of the cluster, and everything working fine, all commands and tests are successfull.

The problem occurs if I decide to reboot one of the servers (core02,core03) . For example if I reboot the core03 it tries to join again the cluster but never succeed, so core02 is left alone.
I am giviing you the output of some commands after the reboot to understand better the situation.
## At core01  tail -f  /var/lib/etcd/log

etcd:set"}{"key":"/test-cluster/core03","value":"http://10.25.100.249:7001","expireTime":"2014-08-15T14:03:36.963991,"dir":false}
etcd:create"p{"key":"/test-cluster/_state","value":"started","expireTime":"0001-01-01T00:00:00Z","unique":false,"dilse}
## At core02  journalctl -f -u etcd

Aug 08 14:08:42 core02 etcd[492]: [etcd] Aug  8 14:08:42.581 INFO      | core02: warning: heartbeat time out peer="core03" missed=8362 backoff="15s"
Aug 08 14:08:57 core02 etcd[492]: [etcd] Aug  8 14:08:57.629 INFO      | core02: warning: heartbeat time out peer="core03" missed=8662 backoff="15s"
Aug 08 14:06:53 core02 fleet[493]: E0808 14:06:53.551301 00493 agent.go:232] Failed heartbeat after 3 attempts: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
## At core02  fleetctl list-machines

MACHINE     IP      METADATA
7febd974... 10.25.100.248   region=us-west
## At core03  journalctl -f -u etcd

Aug 08 14:14:04 core03 etcd[784]: [etcd] Aug  8 14:14:04.212 INFO      | core03 attempted to join via 10.25.100.248:7001 failed: fail on join request: Client Internal Error (Put http://10.25.100.248:7001/join: net/http: timeout awaiting response headers)
Aug 08 14:14:04 core03 etcd[784]: [etcd] Aug  8 14:14:04.212 INFO      | core03 is unable to join the cluster using any of the peers [10.25.100.248:7001] at 1th time. Retrying in 3.2 seconds
Aug 08 14:14:07 core03 etcd[784]: [etcd] Aug  8 14:14:07.216 INFO      | Send Join Request to http://10.25.100.248:7001/join
Aug 08 14:14:08 core03 etcd[784]: [etcd] Aug  8 14:14:08.567 INFO      | core03 attempted to join via 10.25.100.248:7001 failed: fail on join request: Client Internal Error (Put http://10.25.100.248:7001/join: net/http: timeout awaiting response headers)
Aug 08 14:14:08 core03 etcd[784]: [etcd] Aug  8 14:14:08.567 WARNING   | core03 cannot connect to existing peers [10.25.100.248:7001]: fail joining the cluster via given peers after 3 retries
Aug 08 14:14:08 core03 etcd[784]: [etcd] Aug  8 14:14:08.567 CRITICAL  | fail joining the cluster via given peers after 3 retries
Aug 08 14:14:08 core03 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 08 14:14:08 core03 systemd[1]: Unit etcd.service entered failed state
## At core03  fleetctl list-machines

E0808 14:45:23.933150 01445 fleetctl.go:141] error attempting to check latest fleet version in Registry: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error retrieving list of active machines: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Thanks for your patience,
George Mpouras

**Comment by hs3180** [comment]
I encountered same problem. my coreos nodes cannot re-join cluster when I reboot and boot from iPXE. etcd logs are same to yours.

Have you solved this problem? Thanks.

**Comment by yichengq** [comment]
etcd assumes that data dir should be stable and permanently saved.
Check
https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery
for disaster recovery.
