### ISSUE TITLE
hack: docker-compose cluster examples.

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/etcd#9221]
I have a fair number of docker-compose examples I would like to organize into hack/. @gyuho do you mind if I add some stuff to your playground? :)

**Comment by gyuho** [comment]
@hexfusion Sure. Sounds good under hack directory.

**Comment by marciorf** [comment]
I would like this!

**Comment by hexfusion** [comment]
@marciorf thanks for the nudge, I will get things organized soon.
