### ISSUE TITLE
Possible for gRPC-proxy to aggregate data from mulitple clusters?

### ISSUE THREAD

**Issue by acxlam** [etcd-io/etcd#9266]
Greetings,  is it possible to do this now? Could it be yet another solution for multi data center deployment ? 

My colleague mentioned Eureka 2 reader, which share some similarities with gRPC-proxy, the former aggregates data from other clusters. 
https://raw.githubusercontent.com/wiki/Netflix/eureka/images/eureka2_architecture.png 
If it's possible, I believe it might boost ETCD adoption even further. gRPC proxy might sill cache only those data that concerns its clients.

We are using ETCD as our service registering with some success and decide to switch all of our service discovery facilities from zookeeper to ETCD.  Many thanks.

**Comment by gyuho** [comment]
> aggregate data from mulitple clusters

What do you mean?

And grpc-proxy is just another layer on top of etcd, to coalesce requests and reduce traffic to core etcd cluster. All major work (watch, notify) is still done in etcd. Why not just pure etcd?

**Comment by xiang90** [comment]
we had the idea about registering multiple etcd clusters to gRPC-proxy with different prefix namespaces.

**Comment by acxlam** [comment]
@xiang90  Really? May I have the guide please. From what I read from 3.2 announcement, gRPC proxy is another layer to scale performance for the one core cluster, as pointed out by @gyuho.

This is nice.  But my colleagues would like to know if it's possible for one grpc proxy to get view of data (maybe under difference prefixes) from multiple clusters as they were from the same cluster. They would like to have an ETCD cluster per data center but with a single view on proxy

**Comment by acxlam** [comment]
Sir, Greetings again, I come to understand that the idea of a "multi-broker proxy" might somewhat hurt the purity of the proxy after some readings into source code of the grpc proxy.

Just my 2 cents. How about the idea of a multi-client manager that is a layer on top of the client? That would legitimate the idea of grpc proxy running in "enhanced multi-broker mode". 

Not sure this is very suggestive, pls close this ticket if it doesn't sound feasible for the moment.

**Comment by xiang90** [comment]
> Just my 2 cents. How about the idea of a multi-client manager lib that is a layer on top of some clients? 

I would rather put this into the proxy code. Or we will force every clients to implement the same switching/discovering logic in multiple different languages. We already start to move high level client code like locking into the server side for the same purpose.

**Comment by xiang90** [comment]
@acxlam 

We can start with something very simple.

1. provide a static list of tuples (etcd cluster endpoints, prefix) to gRPC proxy.
2. gRPC proxy redirect the key with a known prefix to the right etcd cluster
3. gRPC proxy detects any cross cluster transaction, and reports `cross cluster transaction not supported` error

I think it is fairly easy to implement. We can add dynamic cluster register and discovery later on. If needed, we can implement transaction over multiple etcd cluster too.

**Comment by yudai** [comment]
@xiang90 Thanks for CC. As I mentioned on twitter (sorry, I've not created a ticket, because I came up to some too big ideas like scaling out etcd cluster by sharding data by namespaces while writing the ticket...), some federation/inter-cluster-namespaces capability would be useful for various use cases.

I once implemented something similar to do sharding on key space. What I found was lease handling was a bit tricky because they were not tied to the key space when created.

**Comment by xiang90** [comment]
> What I found was lease handling was a bit tricky because they were not tied to the key space when created.

Yes. Initially we probably want the proxy to remember which leases belong to which clusters in a cache. We can do something smarter though.

**Comment by cw9** [comment]
The clustering features would be very helpful, right now we are basically managing the mapping (from zone/namespaces to etcd clusters) ourselves in a similar way. It makes sense to error on cross cluster transactions.

**Comment by xiang90** [comment]
@yudai 

> What I found was lease handling was a bit tricky because they were not tied to the key space when created.

maybe you can share some thoughts on how you handled this.

**Comment by yudai** [comment]
I actually could not find a good way to solve this on the pure etcd KV layer.

In my case, each client had its own client cert and I could workaround the issue by using the CN of the cert as the distribution key. So it's not key-name-based sharding, it's client-name-based sharding, which you can always tell where leases should go to without key names just by checking client certs.

This was possible because there was no cross-client data or cross-cluster requests in my use case. I think this assumption is not always true. I therefore don't think it's a generic way that we can apply to etcd itself. Only possibility I can imagine is that using username or roles as the distribution key. But I'm not sure how much people will be happy with this solution.

**Comment by xiang90** [comment]
@yudai 

one possibility is to make it possible to attach name as a metadata to leases. probably we need to put more thoughts onto it.

**Comment by acxlam** [comment]
@xiang90 Despite my limited Golang knowledge, I've a feeling that a new service interface, i,e an additional rpc-multi.proto might be needed to allow for cluster key/metadata transfer.

Clients can progressively update to support this feature without breaking anything with current versions.

**Comment by acxlam** [comment]
@xiang90 @yudai  May I know if there was discussion about multi data table support by other followers before? Appears to us that ETCD is positioned as a special kind database and it may be natural for databases to have more than one table/collection.  By this means, it may also be natrual for proxy to retrieve data  from different clusters as different tables, too? Compatibility would still be preserved if current clients are just restricted to the default table/collection.

It is never trivial since it requires protocol/client update and I don't know of a raft database with such facilites, either. 

Forgive me for not being able to follow up issues since struggling with my life recently. Still can't help but put my two cents.

**Comment by arjunsingri** [comment]
What is the status on this? Does etcd  have plans of supporting multiple clusters for a single grpc proxy?
