### ISSUE TITLE
Improve automation of downstream testing kubernetes

### ISSUE THREAD

**Issue by jpbetz** [etcd-io/etcd#9280]
The etcd server is manually tested against kubernetes for each release. Recently, we also have [manually tested the etcd client](https://github.com/kubernetes/kubernetes/pull/58551) against kubernetes:master.

We would like to increase the level automation for this tests both to reduce the amount of manual effort required to release etcd and allow the tests to be run more often.

**Comment by xiang90** [comment]
maybe it is a good time for us to create etcd-jenkins repo to move jenkins file to an open place, and also facilitate this kind of workload testing.

/cc @gyuho

**Comment by gyuho** [comment]
@jpbetz I will be starting to work on this, in the next few weeks. I think this has to be done in two phases. One is to simulate and automate API server load testing on specified etcd version (more focused on etcd core performance). Second is to automate etcd version pick for all scalability tests (focused on etcd + other control plane performance). I will document action items and share them for review.

**Comment by gyuho** [comment]
ref. https://github.com/kubernetes/kubernetes/issues/63245
