### ISSUE TITLE
"all at once" upgrade stategy leads to broken cluster

### ISSUE THREAD

**Issue by mark-kubacki** [etcd-io/etcd#940]
Shut down a previously working cluster of three nodes A B C, using discovery, and given network delay.

When bringing them up the cluster should "work".

But the behavior is this indeed, resulting in a deadlocked cluster:
- A (previously the leader) cannot reach B and C due whatever delay. Won't listen on ports `:4001` and `:7001`.
- B cannot reach A (and C). Won't listen on ports `:4001` and `:7001`.
- C cannot reach A (and B) due to closed ports. Won't listen on ports `:4001` and `:7001`.

---

Re https://github.com/coreos/etcd/blob/master/Documentation/upgrade.md

You can simulate network delay (and packet loss) for example by:

```
tc qdisc add dev eth0 root netem delay 70ms 5ms
tc qdisc change dev eth0 root netem loss 0.5% 15%

#ETCD_PEER_HEARTBEAT_INTERVAL=80
#ETCD_PEER_ELECTION_TIMEOUT=400
```

**Comment by rca** [comment]
I just ran into this with a 3-node cluster on AWS.  I terminated a machine that was acting up, which dropped the cluster to 2 nodes.  I fired up a new machine to take its place, however the cluster is not usable.  I tried rebooting all the machines as suggested above, but no go.  Thanks.

**Comment by rca** [comment]
More info in case it helps.  Not sure this is the redirect issue, but somehow all the machines that etcd knows about are listed as followers:

```
core@ip-172-30-0-125 ~ $ curl http://127.0.0.1:7001/v2/admin/machines
[{"name":"35503004937c44ffb87d6ba3d4ad8570","state":"follower","clientURL":"http://172.30.0.99:4001","peerURL":"http://172.30.0.99:7001"},{"name":"55feb942c50942aebc9406fa236d62c6","state":"follower","clientURL":"http://172.30.0.125:4001","peerURL":"http://172.30.0.125:7001"},{"name":"7e2fba0ba5e844d8aaf60efbf3c64a12","state":"follower","clientURL":"http://172.30.0.11:4001","peerURL":"http://172.30.0.11:7001"},{"name":"a1bf697a02ee430cad48ec49427fe413","state":"follower","clientURL":"http://172.30.0.100:4001","peerURL":"http://172.30.0.100:7001"}]
```

**Comment by wmark** [comment]
@kelseyhightower Thanks for trying to reproduce this issue. In the meanwhile we don't use *etcd* anymore but have written an adapter to another dDBMS.

I can rule out duplicate names: I've used a script for the nodes which works with variables for names. (It's been "core-test{,-1,-2}" as described on 2014-09-10.)

I believe the breaking point is shutting down the nodes in the right order, "whacking the [then new] leader".

What do you use for integration tests? I would like to contribute one for this and two other issues.
