### ISSUE TITLE
I forgot the admin password in production environment, what should I do???

### ISSUE THREAD

**Issue by ckeyer** [etcd-io/etcd#9420]
v3

**Comment by gyuho** [comment]
We encrypt auth passwords with bcrypt, and do not support password recovery.
I would restore from recent snapshot to create a new cluster. /cc @mitake

**Comment by mitake** [comment]
@gyuho probably adding a salvation tool like etcd-dump-db to etcdctl would be helpful?

**Comment by gyuho** [comment]
@mitake How would it work? Is it to reset root password?

**Comment by mitake** [comment]
@gyuho probably draining all the data from existing files of snapshot and wal and put them to a new cluster as an ordinary etcd cluster would be straightforward. Modifying the data (in this case, bcrypted password) in the files is a little bit risky because the tool can bypass the consensus process of Raft.

**Comment by danielalbertolopezz** [comment]
![14257669_1101474016566642_1298855904782809037_o](https://user-images.githubusercontent.com/38170631/38462271-9731be08-3aba-11e8-9e72-72adede3174d.jpg)

**Comment by wenjiaswe** [comment]
@joelegasse Hi Joe, just a friendly reminder, just wondering is there any progress on this one, or is there a plan? Thanks!

**Comment by joelegasse** [comment]
I'm not sure why I got assigned this. I can take a look and see what it would take as far as a recovery plan, though.

**Comment by devinrsmith** [comment]
It seems like there should be a way for a local administrator to overwrite the relevant password(s) on each of the member nodes (writing into the nodes' local db) without needing to know the original password. That is, of course, assuming that the password is not being used to encrypt at-rest data.

**Comment by liuxuc63** [comment]
I got the same problem. Fortunately, It's test environment.
If there is a safe_mode=on to  start only listen on 127.0.0.1 without auth will be kindly.
