### ISSUE TITLE
Change of port numbers

### ISSUE THREAD

**Issue by brianredbeard** [etcd-io/etcd#948]
IANA has officially assigned the following ports to etcd:
- 2379/tcp:  etcd-client (Client facing communication)
- 2380/tcp:  etcd-server (Server to server communication)

The default ports should be changed and documentation updated.

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=etcd

**Comment by nixn** [comment]
etcdctl still uses only `localhost:4001` by default. this is annoying when using only the new (IANA-assigned) ports, one has always to type `etcdctl -C http://localhost:2379 ...`.

Further I would like to have the possibility to use the same DNS discovery as with confd, which is the SRV entry `_etcd._tcp.example.com`. For example `etcdctl -D example.com ...`, which is fault-tolerant and much faster than `etcdctl -C http://etcd1.example.com:2379,http://etcd2.example.com:2379 ...`. You get the point.

**Comment by yichengq** [comment]
@nixn Have just updated etcdctl default setting: https://github.com/coreos/etcd/pull/2611 :)

**Comment by nixn** [comment]
Nice, thank you. What about the second one (DNS discovery)?

**Comment by yichengq** [comment]
@nixn I think it is a good point. Please open a new issue and we can discuss and track about it there.

**Comment by nixn** [comment]
Done: #2636
