### ISSUE TITLE
We do not need to call `Seek()` in wal.Create, since the file is new created.

### ISSUE THREAD

**Issue by oops-oom** [etcd-io/etcd#9527]
We do not need to call `Seek()` in wal.Create, since the file is new created.

And why do we open and close dir in wal.Create ?

```go
	// directory was renamed; sync parent dir to persist rename
	pdir, perr := fileutil.OpenDir(filepath.Dir(w.dir))
	if perr != nil {
		return nil, perr
	}
	if perr = fileutil.Fsync(pdir); perr != nil {
		return nil, perr
	}
	if perr = pdir.Close(); err != nil {
		return nil, perr
	}
```

**Comment by xiang90** [comment]
@binnnliu We open, sync, close it to persist the metadata info. For the seek issue, if you feel it is a small fix please send a PR.

**Comment by binnnliu** [comment]
metadata info here means `directory entry` ?
