### ISSUE TITLE
`etcdctl member list` should return member IDs in a consistent format

### ISSUE THREAD

**Issue by omkensey** [etcd-io/etcd#9535]
When I run `etcdctl member list`, i get the member ID back as a hex string.   However, when I run `etcdctl member list -w json`, I get the member IDs as decimal strings.  This is especially unfortunate when using jq to parse the output as jq mangles anything that looks like a large integer to a double-size int, meaning that the etcd member ID breaks (and this has been raised with the jq team and they insist the behavior of jq is allowed, see for example stedolan/jq#369).

Using `--hex=true` or `--hex=false` seems to have no effect on the etcdctl output.

etcdctl should return the member ID in a consistent number format regardless of the output format.  Ideally it should always default to hex strings since that gets around the jq number-parsing issue.

**Comment by omkensey** [comment]
Also, the member ID probably should be quoted as a string rather than left bare as a number, even if in decimal form.

**Comment by omkensey** [comment]
We can get the member ID from the text listing, but we have to treat it as unstructured data (apart from comma-separation) rather than having a nice solid jq pipeline for it.  Other JSON parsers exist but jq is pretty universal so we'd like to be able to use it for this too instead of using a different tool just for this one thing.  It also makes things harder in this specific instance because what we're doing is parsing out the member ID based on the endpoint URL using jq, and then using that member ID to operate on the peer in question.  If the member ID gets mangled by jq then we can't do that in one step like we could otherwise.

Just to throw out some ideas:

* Can `--hex` be made to work here?
* Maybe a new CLI flag like `--ids-as-strings` can be introduced for JSON output to trigger id-quoting behavior?
* Can "short ID" support be added to etcd (with a flag like `--short-ids` to enable the behavior), like what Docker allows with container IDs or git allows with commit hashes?  Numbers less than 2^53 won't be mangled by jq, so if the ID can be output and input as a number less than that value then it'll work fine.

**Comment by gyuho** [comment]
Moving discussion to https://github.com/etcd-io/etcd/issues/9975.
