### ISSUE TITLE
Operation fails with v2 emulation when API v3 authentication is enabled

### ISSUE THREAD

**Issue by summerwind** [etcd-io/etcd#9608]
We are trying to use the v2 emulation to use the etcd plugin of CoreDNS with v3 backend.

We found that any operation to the v2 emulation fails when v3 authentication enabled. We are testing with etcd v3.3.3. Is this the intended behavior?

```shell
# Check etcdctl version
$ ETCDCTL_API=3 etcdctl version
etcdctl version: 3.3.3
API version: 3.3

# Start etcd with v2 emulation
$ docker run -it --rm -p 2379:2379 gcr.io/etcd-development/etcd:v3.3.3 \
    etcd --advertise-client-urls="http://127.0.0.1:2379" --listen-client-urls="http://0.0.0.0:2379" --experimental-enable-v2v3="/v2" 

# Enable authentication
$ ETCDCTL_API=3 etcdctl user add root 
Password of root:
Type password of root again for confirmation:
User root created
$ ETCDCTL_API=3 etcdctl auth enable
Authentication Enabled

# We can write a key/value as root via v3 API
$ ETCDCTL_API=3 etcdctl --user root:test put /etcd "v3"
OK
$ ETCDCTL_API=3 etcdctl --user root:test get /etcd
/etcd
v3

# We can't write a key/value as root via v2 emulation
$ etcdctl -u root:test set /etcd "v2"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: connect: connection refused
; error #1: client: etcd member http://127.0.0.1:2379 has no leader

error #0: dial tcp 127.0.0.1:4001: connect: connection refused
error #1: client: etcd member http://127.0.0.1:2379 has no leader

# We can write a key/value via v2 emulation when authentication disabled
$ ETCDCTL_API=3 etcdctl --user root:test auth disable
Authentication Disabled
$ etcdctl set /etcd "v2"
v2
```

**Comment by mitake** [comment]
@summerwind thanks for your report. Currently the auth mechanism of v3 cannot care about the v2 emulation feature. Also it is hard to provide a unified auth mechanism which can cover both v2 and v3 keys because of their completely different data models.

As an adhoc fix, giving privilege of accessing to v2 key space only to root user would be possible (although it isn't easy because of the complex nature of the emulation layer). How do you think? Is it suitable for your use case?

**Comment by summerwind** [comment]
@mitake Thank you for the suggestion! 

In our use case, it is only the specific system (CoreDNS) that uses v2 emulation, so applying the privilege of v2 emulation to a specific user will fit.

However, if the user is shared with v2 emulation and v3, it will be difficult to separate privileges by applying it to root, so it is better to apply it to user dedicated to v2 emulation like `emulation` user.

**Comment by mitake** [comment]
@heyitsanthony v2 auth is built on basic auth of http. So it doesn't have credentials.

@summerwind I see. I'll consider the design of unified auth (errors in the design would introduce security holes so I need to be careful). Of course your PRs are welcomed :)
