### ISSUE TITLE
v3client.New creates an invalid *clientv3.Client, missing healthBalancer

### ISSUE THREAD

**Issue by echlebek** [etcd-io/etcd#9621]
`v3client.New` is intended to provide a valid `*clientv3.Client`, but it does not call `clientv3.New`, and therefore does not populate the unexported `balancer` field.

Throughout the code in `retry.go`, the `balancer` field is assumed to not be nil.

The following program reproduces the issue and panics on line 24. (kv.Put)

```
package main

import (
    "context"
    "log"

    "github.com/coreos/etcd/clientv3"
    "github.com/coreos/etcd/embed"
    "github.com/coreos/etcd/etcdserver/api/v3client"
)

func main() {
    cfg := embed.NewConfig()
    cfg.Dir = "."
    e, err := embed.StartEtcd(cfg)
    if err != nil {
        log.Fatal(err)
    }

    cli := v3client.New(e.Server)

    kv := clientv3.NewKV(cli)

    _, err = kv.Put(context.TODO(), "foo", "bar")
    if err != nil {
        log.Fatal(err)
    }
}
```

**Comment by vimalk78** [comment]
@echlebek , slight modification to the test code works for me.

```
package v3client_test

import (
	"context"
	"log"
	"testing"

	"go.etcd.io/etcd/embed"
	"go.etcd.io/etcd/etcdserver/api/v3client"
)

func TestNewClient(t *testing.T) {
	cfg := embed.NewConfig()
	cfg.Dir = "."
	e, err := embed.StartEtcd(cfg)
	if err != nil {
		log.Fatal(err)
	}

	cli := v3client.New(e.Server)

	kv := cli.KV

	_, err = kv.Put(context.TODO(), "foo", "bar")
	if err != nil {
		t.Errorf("could not Put")
	}
	resp, err := kv.Get(context.TODO(), "foo")
	if err != nil {
		t.Errorf("could not Get")
	}
	if string(resp.Kvs[0].Value) != "bar" {
		t.Errorf("could not Get")
	}
}

```

only difference is how to get `kv`, instead of creating newly with `kv := clientv3.NewKV(cli)`, use the kv client already created as part of `clientv3.Client` 
i.e. use `kv := cli.KV`.

**Comment by echlebek** [comment]
@vimalk78 thanks!

**Comment by xiang90** [comment]
@vimalk78 

shall we fix `clientv3.NewKV(cli)`?

**Comment by echlebek** [comment]
FYI this is also a problem for `clientv3.NewCluster`, `clientv3.NewMaintenance`, etcetera.

**Comment by vimalk78** [comment]
@xiang90 
i think that since `clientv3.Client` embeds `clientv3.KV` , `clientv3.Cluster` , `clientv3.Maintanence` etc, there should be no need to call `clientv3.NewKV(*clientv3.Client)` after creating a `clientv3.Client`

But some examples in etcd client show it this way `clientv3.ExampleKV_txn` and `clientv3/clientv3util/clientv3util_test`

**Comment by vimalk78** [comment]
> shall we fix `clientv3.NewKV(cli)`?

I may be wrong here, but I think there is nothing to fix. The `clientv3.KV`  is already created when `clientv3.Client` is created. No matter how it is created, a remote client is created using `clientv3.NewClient()` or an embedded client  created via `etcdserver/api/v3client.New`. 
We should just update examples/Documentation about this. And perhaps should not export `clientv3.NewKV(*clientv3.Client)` if there is no specific use case.

**Comment by echlebek** [comment]
It may be redundant, but `clientv3.NewKV` and friends form part of the public API of the `clientv3` package. Unexporting these functions would break the API of the `clientv3` package, as they work correctly in the common case.
