### ISSUE TITLE
Enable etcd-dump-logs tool to decode kubernetes data objects in WAL log

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/etcd#9631]
etcd-dump-logs now is a great tool for wal log analysis. However, some kubernetes data in wal log is stored in a binary storage representation (starting kubernetes 1.6+). Output from etcd-dump-logs could not reveal kubernetes object. If we could provide an option for etcd-dump-logs to decode kubernetes object data at the same time of wal log dump, it would be very helpful for kubernetes users.

@jpbetz

**Comment by xiang90** [comment]
it seems that this should not belong to etcd repo. Or we need to provide a generic way to hook a decoder into the wal analysis tool.

**Comment by jingyih** [comment]
Addressed by #9790.
