### ISSUE TITLE
etcd prints password to logs

### ISSUE THREAD

**Issue by YeruchamB** [etcd-io/etcd#9635]
Hi, 
I'm not sure what the underlying problem that caused this but while trying unsuccessfully to add members to a cluster, I noticed that my role authentication information was printed to the logs. 

W | etcdserver: request "header:<ID:10856880162570804175 > authenticate:<name:\"root\" password:\"<my password>\" simple_token:\"iTlQlPRxBOgeubfQ\" > " took too long (123.009328ms) to execute

This information should remain secret.

**Comment by mitake** [comment]
@YeruchamB thanks for the report. The problem must be fixed.
