### ISSUE TITLE
etcd db size does not change after created 20000 pods 

### ISSUE THREAD

**Issue by gyliu513** [etcd-io/etcd#9648]
I was using etcd v3.2.14, after created 20000 pods in my cluster, I found that the etcd DB size does not change, but keeps one value for 3 hours.

From below diagram, I submit the 20000 pods from 14:00 to 15:00, after all pods ready, the etcd DB size does not change.

![image](https://user-images.githubusercontent.com/4461983/39356474-a99707c8-4a42-11e8-9b98-d2bd6eaa6d73.png)

**Comment by gyliu513** [comment]
Thanks @yudai let me check more for how kubernetes handle this.

When will 3.4 be released? I found that the latest version is 3.3.4 https://github.com/coreos/etcd/releases/tag/v3.3.4

**Comment by gyuho** [comment]
> When will 3.4 be released?

No, it's planned for summer.

Can you try v3.3.4?

**Comment by gyliu513** [comment]
@gyuho @yudai can you help confirm if this parameter `etcd_debugging_mvcc_db_total_size_in_use_in_bytes` was also included in etcd v3.3.4?

**Comment by gyliu513** [comment]
Thanks @gyuho , this is not a critical issue for me, and I will wait for the new release to test.

**Comment by yudai** [comment]
I think that an easier way with v3.3.4 is to run `etcdctl defrag` and see if the DB sizes decrease.

**Comment by spzala** [comment]
@gyuho @gyliu513 I will be spending sometime on it for further investigation.

**Comment by spzala** [comment]
@gyliu513 I am closing this one. Let's reopen if we needed. Thanks!
