### ISSUE TITLE
ErrCompacted when acquiring mutex leaves behind stale lock nodes

### ISSUE THREAD

**Issue by obeattie** [etcd-io/etcd#9715]
The `concurrency` library may return `ErrCompacted` when trying to acquiring a lock, but leave stale lock entries behind. My understanding is that this is because the following can happen:

1. `Mutex.Lock()` creates a lock node
2. Another session already holds a lock node with a lower revision, so we must wait for it to be deleted
3. A watch is established in to watch for deletion
4. A compaction is triggered
5. The watch terminates with `ErrCompacted` because the revision being used to watch from has been compacted in the previous step
6. `ErrCompacted` is returned to the caller with no cleanup

This means the lock node that has been created is now stale. Any other session that tries to acquire the lock will block until our session goes away. A caller can cleanup from this by deliberately calling `Mutex.Unlock()` if `Mutex.Lock()` fails, but that is not what I think most users expect to do if it looks like they failed to acquire the lock.

Is there a way here that the `concurrency` library can handle the `ErrCompacted` itself? This is a similar question to #9386.

**Comment by yudai** [comment]
https://github.com/coreos/etcd/blob/master/clientv3/concurrency/mutex.go#L70

When `werr` is non nil, `m.Unlock(client.Ctx())` should be called?

**Comment by gyuho** [comment]
@yudai Yeah, I think we should do that, as we do

https://github.com/coreos/etcd/blob/610dd0911dace1c6a5d637e1d9c7c7bcb2bec4aa/clientv3/concurrency/mutex.go#L73-L74

Do you want to work on it with a test case?

**Comment by yudai** [comment]
Ultimately, if `Unlock()` fails, the stale data can left behind? I think `Unlock()` can fail when an etcd node goes down since there is no retry for `Delete()`. 
We might want to renew the lease itself to make sure that stale lock entries are deleted.

**Comment by gyuho** [comment]
@yudai I will double-check on such case. Currently, working on something else. Thanks.

**Comment by vimalk78** [comment]
Should this be closed? 
`Mutex.Lock` calls `Mutex.Unlock` if `waitDeletes` returns in error. 
https://github.com/etcd-io/etcd/blob/master/clientv3/concurrency/mutex.go#L70-L76

**Comment by xiang90** [comment]
it should be fixed. so closing. thanks @vimalk78 for pointing this out.
