### ISSUE TITLE
[question] Should member add/remove commands require peer certificate?

### ISSUE THREAD

**Issue by tamalsaha** [etcd-io/etcd#9719]
I am trying to setup a secure and encrypted etcd cluster. One thing I noticed that when the second member is added to a cluster, a `AddMember` api call is made. This call is exposed over client port. To me this seems some sort of authorization violation. Because if I am using peer certificate with auth enabled, no one who has a valid peer certificate should be able to add/remove members . I am new to etcd. So, it is possible that I am just not seeing it right. I would like to hear your comments. 

Thanks.

**Comment by gyuho** [comment]
> This call is exposed over client port.

Could you clarify on this?

You would add a member with peer URLs with https scheme, not client URL. So, the new member is technically exposing client ports. The new member would still need to start with client TLS.

**Comment by tamalsaha** [comment]
I meant to say that any client can add a Member. I wonder if the `AddMember` should be supported via a separate privileged endpoint where peer certs are required.

The other way to ask the question is is there any downside of adding lots of members (assuming one of my client is rouge)?

**Comment by gyuho** [comment]
> I meant to say that any client can add a Member.

Yes. Any client can add a member.

> I wonder if the AddMember should be supported via a separate privileged endpoint where peer certs are required.

Current authentication design does not support this (it only supports roles for key ranges). I think it's reasonable to support roles for member APIs, since member add can easily affect the cluster availabilities.
