### ISSUE TITLE
Error: etcdserver: requested lease not found

### ISSUE THREAD

**Issue by pjmike** [etcd-io/etcd#9726]
[root@iz2zeaf3cg1099kiidi06mz etcd]# export ETCDCTL_API=3
[root@iz2zeaf3cg1099kiidi06mz etcd]# etcdctl put test hello
OK
[root@iz2zeaf3cg1099kiidi06mz etcd]# etcdctl lease grant 10
lease 694d6368b4edc60e granted with TTL(10s)
[root@iz2zeaf3cg1099kiidi06mz etcd]# etcdctl put --lease=694d6368b4edc60e test2 world
Error: etcdserver: requested lease not found
[root@iz2zeaf3cg1099kiidi06mz etcd]# 

how to deal with it?

**Comment by hexfusion** [comment]
@pjmike try

`etcdctl put --lease 694d6368b4edc60e test2 world`

**Comment by hexfusion** [comment]
it is interesting though as we do document your usage [Grant Lease](https://github.com/coreos/etcd/blob/abe5c9c63eeff89396d027fcbde98d1e137358d0/Documentation/dev-guide/interacting_v3.md#grant-leases)

**Comment by hexfusion** [comment]
>[root@iz2zeaf3cg1099kiidi06mz etcd]# etcdctl lease list
>found 0 leases
>
>the lease soon disappeared.

@pjmike yes but this is because your TTL "time to live" is only 10 seconds right so to me this is expected.

Try this `etcdctl lease grant 240`

**Comment by pjmike** [comment]
@hexfusion yes ,it did.Thank you.

**Comment by hexfusion** [comment]
@pjmike you are welcome remember TTL begins count as soon as it is granted.

```
etcdctl lease timetolive 694d6368dd6da003
lease 694d6368dd6da003 granted with TTL(240s), remaining(219s)
```

**Comment by hexfusion** [comment]
I will fix up the documenation unless you would like to issue PR @pjmike ?

**Comment by pjmike** [comment]
No,I wouldn't like to issure PR.I just hope the documenation can be fixed up.Thank you once again.
