### ISSUE TITLE
auth: improve test coverage

### ISSUE THREAD

**Issue by gyuho** [etcd-io/etcd#9734]
Package auth current test coverage is 56% https://codecov.io/gh/coreos/etcd. Improve coverage *where it makes sense*. For example, `HasRole` is not being tested https://codecov.io/gh/coreos/etcd/tree/master/auth. And panic from JWT token https://github.com/coreos/etcd/issues/9695 should have been prevented by unit tests.

**Comment by essamhassan** [comment]
I'd love to contribute in this issue if possible maybe pair with @joelegasse

**Comment by essamhassan** [comment]
I'd love to help with this issue

**Comment by hexfusion** [comment]
@essamhassan great, love to have you on this. Could you coordinate with @joelegasse to make sure there is no overlap in work etc? Thanks!

**Comment by essamhassan** [comment]
Great, will do. Is there a slack team chat or any similar way to contact @joelegasse ? we can coordinate the work there

**Comment by hexfusion** [comment]
@essamhassan I spoke with Joe and he has nothing pending so full steam ahead!
