### ISSUE TITLE
client cancel watch then the server always log "no leader"

### ISSUE THREAD

**Issue by crazyleeyang** [etcd-io/etcd#9739]
when cancel watch by client, the server always log "no leader".then i read the file https://github.com/coreos/etcd/blob/master/etcdserver/api/v3rpc/watch.go, and found the follow logic always hit **case <-stream.Context().Done()**. The original code as follow:
```
	select {
	case err = <-errc:
		close(sws.ctrlStream)

	case <-stream.Context().Done():
		err = stream.Context().Err()
		// the only server-side cancellation is noleader for now.
		if err == context.Canceled {
			err = rpctypes.ErrGRPCNoLeader
		}
	}
```

then i modify the code as follow:
```
	select {
	case err = <-errc:
		close(sws.ctrlStream)
        /*
	case <-stream.Context().Done():
		err = stream.Context().Err()
		// the only server-side cancellation is noleader for now.
		if err == context.Canceled {
			err = rpctypes.ErrGRPCNoLeader
		}
        */
	}
```
then the logic can hit **case err = <-errc**.

I think the select will randomly hit a branch, but the result is not as expected.

**VERSION**: 3.3.0+git
**API VERSION**: 3.3

**Comment by spzala** [comment]
@crazyleeyang can you please provide steps to reproduce the error? I will be happy to work on this. I just couldn't reproduce through close/cancel. Thanks!

**Comment by spzala** [comment]
Closing the issuer per guidelines https://github.com/etcd-io/etcd/blob/master/Documentation/triage/issues.md#inactive-issues Also I could not reproduce the behavior as mentioned previously. Please reopen or open a new issue if needed. Thanks!
