### ISSUE TITLE
Transaction HTTP API not working to update key after upgrading to 3.3.5

### ISSUE THREAD

**Issue by safm** [etcd-io/etcd#9741]
After upgrading my local etcd to 3.3.5, the transaction HTTP API is not working to update the value of a key. Inserting a new one is working but update is not.

url: http://localhost:2379/v3alpha/kv/txn
```javascript
{
  "compare": [{
    "target": "CREATE",
    "key": "{{setKeyName}}"
  }],
  "success": [{
    "requestPut": {
      "key": "{{setKeyName}}",
      "value": "{{setKeyValue}}"
    }
  }]
}
```

I am getting the below response
```javascript
{
    "header": {
        "cluster_id": "14841639068965178418",
        "member_id": "10276657743932975437",
        "revision": "431",
        "raft_term": "14"
    }
}
```

Note: I am trying using Postman so `{{setKeyName}}` is created using pre-request script.

**Comment by gyuho** [comment]
Can you provide reproducible steps?

**Comment by hexfusion** [comment]
@safm any update here if we can see clear simple example to reproduce we can try to resolve.

**Comment by safm** [comment]
@gyuho 

Upgrade to ETCD v3.3.5 from v3.2. Then make a HTTP POST call using [Postman](https://www.getpostman.com). 

Since ETCD is installed locally the URL that I am making HTTP POST call is http://localhost:2379/v3alpha/kv/txn. In the POST call I am passing the below mentioned JSON as the body.

```javascript
{
  "compare": [{
    "target": "CREATE",
    "key": "L2xvY2FsL25vZGVhcHAva2V5"
  }],
  "success": [{
    "requestPut": {
      "key": "L2xvY2FsL25vZGVhcHAva2V5",
      "value": "dHJ1ZQ=="
    }
  }]
}
```

The POST call is adding a key to the ETCD if is not already present. If the key already exists it is not updating it's value with the new passed value. This was working in v3.2 but have stopped working in v3.3.
