### ISSUE TITLE
When rejoin cluster, the instance used the old ID 

### ISSUE THREAD

**Issue by wenxuwan** [etcd-io/etcd#9776]
Hi

The issue occured again(#9613). I have three instance mn-0,mn-1,sn-2. Then reboot mn-1(The folder will be removed, and use etcdctl remove/add the member mn-1 into the cluster).

May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: The member in cluster, we need remove it and join again
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: The member have in cluster, we will remove it first
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: The remove operation result is: Removed member 27e7a5bb5462117a from cluster
**Removed member 27e7a5bb5462117a from cluster**
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]:  success!!
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: **Remove the old member success, we will add it now!!**
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: The add method result is:
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: **Added member named nokia-rcp2-redundant-memory-fci2-0522mn-1 with ID b8959a3f0db88d0b to cluster**
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: ETCD_NAME="nokia-rcp2-redundant-memory-fci2-0522mn-1"
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: ETCD_INITIAL_CLUSTER="nokia-rcp2-redundant-memory-fci2-0522mn-0=http://nokia-rcp2-redundant-memory-fci2-0522mn-0.local:2380,nokia-rcp2-redundant-memory-fci2-0522sn-2=http://nokia-rcp2-redundant-memory-fci2-0522sn-2.local:2380,nokia-rcp2-redundant-memory-fci2-0522mn-1=http://nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380"
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: ETCD_INITIAL_CLUSTER_STATE="existing"
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: add success
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: nokia-rcp2-redundant-memory-fci2-0522mn-0=http://nokia-rcp2-redundant-memory-fci2-0522mn-0.local:2380,nokia-rcp2-redundant-memory-fci2-0522sn-2=http://nokia-rcp2-redundant-memory-fci2-0522sn-2.local:2380,nokia-rcp2-redundant-memory-fci2-0522mn-1=http://nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: Add the member success
May 22 21:02:40.910031 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 create-etcd-conf[1082]: The etcd configure fished with ETCD_INITIAL_CLUSTER_STATE existing

May 22 21:02:41.446081 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.3:2379
May 22 21:02:41.446108 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_DATA_DIR=/mnt/rcpha/etcd/rcp20.etcd
May 22 21:02:41.446121 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1500
May 22 21:02:41.446128 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=300
May 22 21:02:41.446136 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.1.3:2380
May 22 21:02:41.446148 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_INITIAL_CLUSTER=nokia-rcp2-redundant-memory-fci2-0522mn-0=http://nokia-rcp2-redundant-memory-fci2-0522mn-0.local:2380,nokia-rcp2-redundant-memory-fci2-0522mn-1=http://nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380,nokia-rcp2-redundant-memory-fci2-0522sn-2=http://nokia-rcp2-redundant-memory-fci2-0522sn-2.local:2380
May 22 21:02:41.446153 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
May 22 21:02:41.446158 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=RCP2.0_18.21.0_180521111210
May 22 21:02:41.446169 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://192.168.1.3:2379,http://127.0.0.1:2379
May 22 21:02:41.446175 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.1.3:2380
May 22 21:02:41.446185 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_MAX_SNAPSHOTS=1
May 22 21:02:41.446191 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_MAX_WALS=1
May 22 21:02:41.446196 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: recognized and used environment variable ETCD_NAME=nokia-rcp2-redundant-memory-fci2-0522mn-1
May 22 21:02:41.446233 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: etcd Version: 3.1.4
May 22 21:02:41.446241 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: Git SHA: 4e1824f
May 22 21:02:41.446245 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: Go Version: go1.9.2
May 22 21:02:41.446249 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: Go OS/Arch: linux/amd64
May 22 21:02:41.446253 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: setting maximum number of CPUs to 4, total number of available CPUs is 4
May 22 21:02:41.446289 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: listening for peers on http://192.168.1.3:2380
May 22 21:02:41.446307 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: listening for client requests on 127.0.0.1:2379
May 22 21:02:41.446320 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: listening for client requests on 192.168.1.3:2379
May 22 21:02:41.446719 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 iomon[561]: read requests: 5586, read data: 130747 KiB, wait time for read requests: 80373 ms, write requests: 662, write data: 26496 KiB, wait time for write requests: 18303 ms
May 22 21:02:41.465450 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522mn-0.local:2380 to 192.168.1.4:2380
May 22 21:02:41.465641 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522mn-0.local:2380 to 192.168.1.4:2380
May 22 21:02:41.465840 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380 to 192.168.1.3:2380
May 22 21:02:41.466029 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380 to 192.168.1.3:2380
May 22 21:02:41.532519 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Bus n/a: changing state UNSET → OPENING
May 22 21:02:41.532540 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Bus n/a: changing state OPENING → AUTHENTICATING
May 22 21:02:41.533569 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Accepted new private connection.
May 22 21:02:41.533649 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Bus n/a: changing state AUTHENTICATING → RUNNING
May 22 21:02:41.533691 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=Get cookie=1 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
May 22 21:02:41.533717 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Sent message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=v error-name=n/a error-message=n/a
May 22 21:02:41.533753 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Bus n/a: changing state RUNNING → CLOSING
May 22 21:02:41.533799 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Bus n/a: changing state CLOSING → CLOSED
May 22 21:02:41.533834 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 systemd[1]: Got disconnect on private connection.
May 22 21:02:41.534136 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 local_storage_agent.sh[676]: command "systemctl is-system-running" execution failed, stdout=starting
May 22 21:02:41.534136 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 local_storage_agent.sh[676]: , stderr= returncode is 1
May 22 21:02:41.566788 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522sn-2.local:2380 to 192.168.1.7:2380
May 22 21:02:41.567017 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: resolving nokia-rcp2-redundant-memory-fci2-0522sn-2.local:2380 to 192.168.1.7:2380
May 22 21:02:41.567996 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: name = nokia-rcp2-redundant-memory-fci2-0522mn-1
May 22 21:02:41.568013 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: data dir = /mnt/rcpha/etcd/rcp20.etcd
May 22 21:02:41.568021 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: member dir = /mnt/rcpha/etcd/rcp20.etcd/member
May 22 21:02:41.568027 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: heartbeat = 300ms
May 22 21:02:41.568032 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: election = 1500ms
May 22 21:02:41.568038 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: snapshot count = 10000
May 22 21:02:41.568050 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: advertise client URLs = http://192.168.1.3:2379
May 22 21:02:41.595364 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: **starting member 27e7a5bb5462117a in cluster 90c0ae66e7490506**
May 22 21:02:41.596218 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: 27e7a5bb5462117a became follower at term 0
May 22 21:02:41.596241 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: newRaft 27e7a5bb5462117a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
May 22 21:02:41.596250 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: 27e7a5bb5462117a became follower at term 1
May 22 21:02:41.603703 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started HTTP pipelining with peer 3383cb46b462d623
May 22 21:02:41.603873 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started HTTP pipelining with peer b13ed5865df0d655
May 22 21:02:41.604652 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: starting peer 3383cb46b462d623...
May 22 21:02:41.604690 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started HTTP pipelining with peer 3383cb46b462d623
May 22 21:02:41.605168 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer 3383cb46b462d623 (writer)
May 22 21:02:41.606284 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer 3383cb46b462d623 (writer)
May 22 21:02:41.607189 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started peer 3383cb46b462d623
May 22 21:02:41.607236 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: added peer 3383cb46b462d623
May 22 21:02:41.607268 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: starting peer b13ed5865df0d655...
May 22 21:02:41.607305 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started HTTP pipelining with peer b13ed5865df0d655
May 22 21:02:41.609897 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer 3383cb46b462d623 (stream MsgApp v2 reader)
May 22 21:02:41.610134 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer 3383cb46b462d623 (stream Message reader)
May 22 21:02:41.610382 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer b13ed5865df0d655 (writer)
May 22 21:02:41.612458 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer b13ed5865df0d655 (writer)
May 22 21:02:41.617042 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started peer b13ed5865df0d655
May 22 21:02:41.617153 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: added peer b13ed5865df0d655
May 22 21:02:41.617300 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: starting server... [version: 3.1.4, cluster version: to_be_decided]
May 22 21:02:41.617410 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer b13ed5865df0d655 (stream Message reader)
May 22 21:02:41.620550 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: started streaming with peer b13ed5865df0d655 (stream MsgApp v2 reader)
May 22 21:02:41.620950 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: the member has been permanently removed from the cluster
May 22 21:02:41.620965 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: the data-dir used by this member must be removed.
May 22 21:02:41.630868 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: streaming request ignored (ID mismatch got b8959a3f0db88d0b want 27e7a5bb5462117a)
May 22 21:02:41.631086 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: streaming request ignored (ID mismatch got b8959a3f0db88d0b want 27e7a5bb5462117a)
May 22 21:02:41.631213 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: peer 3383cb46b462d623 became active
May 22 21:02:41.631250 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: established a TCP streaming connection with peer 3383cb46b462d623 (stream Message writer)
May 22 21:02:41.631745 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: established a TCP streaming connection with peer 3383cb46b462d623 (stream MsgApp v2 writer)
May 22 21:02:41.699072 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: 27e7a5bb5462117a [term: 1] received a MsgHeartbeat message with higher term from b13ed5865df0d655 [term: 19]
May 22 21:02:41.699128 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: 27e7a5bb5462117a became follower at term 19
May 22 21:02:41.699140 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: raft.node: 27e7a5bb5462117a elected leader b13ed5865df0d655 at term 19
May 22 21:02:41.699163 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: aborting publish because server is stopped
May 22 21:02:41.699187 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped HTTP pipelining with peer 3383cb46b462d623
May 22 21:02:41.699200 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped HTTP pipelining with peer b13ed5865df0d655
May 22 21:02:41.699208 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopping peer 3383cb46b462d623...
May 22 21:02:41.700103 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: closed the TCP streaming connection with peer 3383cb46b462d623 (stream MsgApp v2 writer)
May 22 21:02:41.700117 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer 3383cb46b462d623 (writer)
May 22 21:02:41.700917 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: closed the TCP streaming connection with peer 3383cb46b462d623 (stream Message writer)
May 22 21:02:41.700929 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer 3383cb46b462d623 (writer)
May 22 21:02:41.700972 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped HTTP pipelining with peer 3383cb46b462d623
May 22 21:02:41.701002 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: failed to dial 3383cb46b462d623 on stream MsgApp v2 (net/http: request canceled)
May 22 21:02:41.701010 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: peer 3383cb46b462d623 became inactive
May 22 21:02:41.701028 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer 3383cb46b462d623 (stream MsgApp v2 reader)
May 22 21:02:41.701048 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer 3383cb46b462d623 (stream Message reader)
May 22 21:02:41.701056 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped peer 3383cb46b462d623
May 22 21:02:41.701063 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopping peer b13ed5865df0d655...
May 22 21:02:41.701073 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer b13ed5865df0d655 (writer)
May 22 21:02:41.701082 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer b13ed5865df0d655 (writer)
May 22 21:02:41.701125 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped HTTP pipelining with peer b13ed5865df0d655
May 22 21:02:41.701136 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer b13ed5865df0d655 (stream MsgApp v2 reader)
May 22 21:02:41.701144 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped streaming with peer b13ed5865df0d655 (stream Message reader)
May 22 21:02:41.701152 Nokia-RCP2-Redundant-MEMORY-FCI2-0522mn-1 etcd[2081]: stopped peer b13ed5865df0d655

The mn-1 started etcd with the old ID 27e7a5bb5462117a but the new ID for mn-1 is b8959a3f0db88d0b .

SN-2 log:

May 22 21:02:41.268777 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: removed member 27e7a5bb5462117a from cluster 90c0ae66e7490506
May 22 21:02:41.269112 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopping peer 27e7a5bb5462117a...
May 22 21:02:41.269220 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped streaming with peer 27e7a5bb5462117a (writer)
May 22 21:02:41.269241 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped streaming with peer 27e7a5bb5462117a (writer)
May 22 21:02:41.269260 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped HTTP pipelining with peer 27e7a5bb5462117a
May 22 21:02:41.269271 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped streaming with peer 27e7a5bb5462117a (stream MsgApp v2 reader)
May 22 21:02:41.269282 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped streaming with peer 27e7a5bb5462117a (stream Message reader)
**May 22 21:02:41.269290 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: stopped peer 27e7a5bb5462117a
May 22 21:02:41.269302 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: removed peer 27e7a5bb5462117a**
May 22 21:02:41.282830 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: **added member b8959a3f0db88d0b [http://nokia-rcp2-redundant-memory-fci2-0522mn-1.local:2380] to cluster 90c0ae66e7490506**
May 22 21:02:41.282850 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: starting peer b8959a3f0db88d0b...
May 22 21:02:41.282885 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started HTTP pipelining with peer b8959a3f0db88d0b
May 22 21:02:41.284273 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started peer b8959a3f0db88d0b
May 22 21:02:41.284295 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: added peer b8959a3f0db88d0b
May 22 21:02:41.284379 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started streaming with peer b8959a3f0db88d0b (writer)
May 22 21:02:41.284394 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started streaming with peer b8959a3f0db88d0b (writer)
May 22 21:02:41.284432 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started streaming with peer b8959a3f0db88d0b (stream MsgApp v2 reader)
May 22 21:02:41.284742 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: started streaming with peer b8959a3f0db88d0b (stream Message reader)
May 22 21:02:42.001321 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: rejected the stream from peer 27e7a5bb5462117a since it was removed
May 22 21:02:42.002858 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: rejected the stream from peer 27e7a5bb5462117a since it was removed
May 22 21:02:42.080839 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: peer b8959a3f0db88d0b became active
May 22 21:02:42.113497 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: failed to dial b8959a3f0db88d0b on stream Message (dial tcp 192.168.1.3:2380: getsockopt: connection refused)
May 22 21:02:42.113513 Nokia-RCP2-Redundant-MEMORY-FCI2-0522sn-2 etcd[28765]: peer b8959a3f0db88d0b became inactive

The etcd version  is etcd Version: 3.1.4

**Comment by jukka413** [comment]
Hi
how you solve this problem?
