### ISSUE TITLE
problem on adding controller-2 machine to existing 2 controller-0 and controller-1 cluster  

### ISSUE THREAD

**Issue by prabhatpankaj** [etcd-io/etcd#9782]
```
cat > etcd.service <<EOF
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
ExecStart=/usr/local/bin/etcd \\
  --name ${ETCD_NAME} \\
  --cert-file=/etc/etcd/kubernetes.pem \\
  --key-file=/etc/etcd/kubernetes-key.pem \\
  --peer-cert-file=/etc/etcd/kubernetes.pem \\
  --peer-key-file=/etc/etcd/kubernetes-key.pem \\
  --trusted-ca-file=/etc/etcd/ca.pem \\
  --peer-trusted-ca-file=/etc/etcd/ca.pem \\
  --peer-client-cert-auth \\
  --client-cert-auth \\
  --initial-advertise-peer-urls https://${INTERNAL_IP}:2380 \\
  --listen-peer-urls https://${INTERNAL_IP}:2380 \\
  --listen-client-urls https://${INTERNAL_IP}:2379,http://127.0.0.1:2379 \\
  --advertise-client-urls https://${INTERNAL_IP}:2379 \\
  --initial-cluster-token etcd-cluster-0 \\
  --initial-cluster controller-0=https://10.240.0.10:2380,controller-1=https://10.240.0.11:2380 \\
  --initial-cluster-state new \\
  --data-dir=/var/lib/etcd
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

```
I updated initial-cluster controller-0 by adding controller-2 as 
```
--initial-cluster controller-0=https://10.240.0.10:2380,controller-1=https://10.240.0.11:2380,controller-2=https://10.240.0.12:2380 \\
```

I followed the the steps as per  https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure
. my initial multi controller cluster worked perfectly . 

but after adding more controller and then i updated all pem file and its settings file , 

still i am getting errors for controller-2 machine as .

```
ETCDCTL_API=3 etcdctl member list
```
```
 Error: context deadline exceeded
```

Please help me out .

**Comment by hexfusion** [comment]
> ETCDCTL_API=3 etcdctl member list
>  Error: context deadline exceeded

This error means that the client can not connect to the server and times out.

>  --listen-client-urls https://${INTERNAL_IP}:2379,http://127.0.0.1:2379 \\

If your cluster is using TLS you need to listen on https ^ .Also you will need to pass --cacert, --cert, --key flags to etcdctl.

`ETCDCTL_API=3 etcdctl --cacert /path/ca.pem --key /path/key.pem --cert /path/cert.pem etcdctl member list.` 

You can also choose to set the flags with ENV variables as outlined here.

https://github.com/coreos/etcd/tree/master/etcdctl#etcdctl
