### ISSUE TITLE
How to understand the destination of each GRPC request from clientv3 to etcd server ? 

### ISSUE THREAD

**Issue by ahakanbaba** [etcd-io/etcd#9802]
We are running clientv3 v3.0.17 and etcd server 3.1.13. 

There are 3 etcd servers in our cluster. As far as we know, the etcd clientv3 pins to a particular etcd server as long as the "connection is healthy". 

We would like to understand which etcd server process is used for each gRPC call.  Is there a way to achieve this ? 

## Some context. 

We run etcd in kubernetes 1.6.13 as its storage backend.  In kubernetes, only the [apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) has direct access to etcd. ApiServer code in kube1.6.3  uses etcd client version 3.0.17 
Our etcd  cluster for kubernetes uses etcd 3.1.13. 

Under some circumstances the kubernetes apiserver  (etcdv3 client) responds back to its own clients (e.g kubelet, kubectl) with continuous 5XX requests. During that time, we want to understand which member of the etcd cluster is used by kube apiserver. What is the pinned etcd endpoint in the clientv3 ?

Is there a way to log the grpc requests between etcdv3 client 3.0.17 and etcd server 3.1.13 ? Or any other way to get the information about the endpoints ? 

### On the clientv3 side: 
I think the `grpc.Balancer.Get` function returns the endpoint address used for each grpc request in clientv3. I think one could add a log print [here](https://github.com/kubernetes/kubernetes/blob/14ea65f53cdae4a5657cf38cfc8d7349b75b5512/vendor/github.com/coreos/etcd/clientv3/balancer.go#L136) and make apiserver log the etcd address per request. That unfortunately requires code change. 

### On etcd Server 3.1.14 side: 

1. On the etcd server side, the --debug option as mentioned [here](https://coreos.com/etcd/docs/latest/v2/admin_guide.html) only mentions v2 keystore . Even though there are a lot of requests to the v3 store happening, the etcd logs only have these debug messages 

```
2018-05-15 23:44:15.896975 D | etcdserver/api/v2http: [GET] /v2/keys/coreos.com/network/subnets?recursive=true&wait=true&waitIndex=1201704305 remote:10.228.94.132:37415
2018-05-15 23:44:15.927859 D | etcdserver/api/v2http: [GET] /v2/keys/coreos.com/network/subnets?recursive=true&wait=true&waitIndex=1201704305 remote:10.228.94.132:37417
2018-05-15 23:44:16.007575 D | etcdserver/api/v2http: [GET] /v2/keys/coreos.com/network/subnets?recursive=true&wait=true&waitIndex=1201704305 remote:10.228.94.132:37419

```
Is this expected, the debug messages not mentioning the requests to the V3 store ? 

2. This [issue](https://github.com/coreos/etcd/issues/8418#issuecomment-323440622) mentions a http://etcd:2379/debug/requests/  endpoint but I do not think it is available in version 3.1.13 yet on the server.

### Other approaches ourside of etcd. 

We have tried logging at gRPC level or http2 level as well as Linux tools like tcpdump or lsof. They did not reveal the required information. We detail the experience in [stackoverflow](https://stackoverflow.com/q/50345829/5771861).

Using gRPC metrics was suggested in [etcd-dev](https://groups.google.com/forum/#!topic/etcd-dev/ZYCU50JMbYo) . That also does not provide the per request fine level granularity.

**Comment by gyuho** [comment]
> We would like to understand which etcd server process is used for each gRPC call. Is there a way to achieve this ?

We do not expose that information, since it does not really matter. All requests are forwarded to leader automatically.

Why do you need this information?

**Comment by ahakanbaba** [comment]
@gyuho  For this use-case it is mostly debugging. We think there is a system level issue and this information would help. 

We believe something funky is happening between the kube-api-server and the etcd.
In order to increase understanding it would help significantly if we know to which etcd server the api-server is talking for each request.
