### ISSUE TITLE
ProgressNotification failures

### ISSUE THREAD

**Issue by YeruchamB** [etcd-io/etcd#9803]
Hey, I'm running my own agent which is a wrapper for an etcd client watching for changes.
The code seems to be working and when i update keys i can see that the watcher catches those updates but for some reason, every 6-11 minutes or so, the watcher will return an empty response.. 
This response isn't a progress notification, or at least wresp.IsProgressNotify() return false since the wr.Header.Revision equals 0.
Also, no progress notification is received as you can see by the timeout...

All im seeing in the etcd logs is the usual "Invalid auth tokens", "deleting token" messages but like i said, it seems to be behaving correctly except for this.

Any ideas?

My logs:
Jun  5 00:53:21: level=info msg="Configurations updated successfully"
Jun  5 00:53:21: level=info msg="Watching from revision 10"
Jun  5 00:59:19: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 00:59:19: level=info msg="Configurations updated successfully"
Jun  5 00:59:19: level=info msg="Watching from revision 10"
Jun  5 01:06:18: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:06:18: level=info msg="Configurations updated successfully"
Jun  5 01:06:18: level=info msg="Watching from revision 10"
Jun  5 01:14:16: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:14:16: level=info msg="Configurations updated successfully"
Jun  5 01:14:16: level=info msg="Watching from revision 10"
Jun  5 01:21:13: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:21:13: level=info msg="Configurations updated successfully"
Jun  5 01:21:13: level=info msg="Watching from revision 10"
Jun  5 01:29:12: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:29:12: level=info msg="Configurations updated successfully"
Jun  5 01:29:12: level=info msg="Watching from revision 10"
Jun  5 01:35:10: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:35:10: level=info msg="Configurations updated successfully"
Jun  5 01:35:10: level=info msg="Watching from revision 10"
Jun  5 01:46:10: level=info msg="Timeout waiting for message from Confucius"
Jun  5 01:46:10: level=info msg="Restarting client and watcher"
Jun  5 01:46:12: level=info msg="Watching from revision 10"
Jun  5 01:52:09: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:52:09: level=info msg="Configurations updated successfully"
Jun  5 01:52:09: level=info msg="Watching from revision 10"
Jun  5 01:58:08: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 01:58:08: level=info msg="Configurations updated successfully"
Jun  5 01:58:08: level=info msg="Watching from revision 10"
Jun  5 02:08:05: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:08:05: level=info msg="Configurations updated successfully"
Jun  5 02:08:05: level=info msg="Watching from revision 10"
Jun  5 02:15:01: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:15:01: level=info msg="Configurations updated successfully"
Jun  5 02:15:01: level=info msg="Watching from revision 10"
Jun  5 02:22:58: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:22:58: level=info msg="Configurations updated successfully"
Jun  5 02:22:58: level=info msg="Watching from revision 10"
Jun  5 02:30:56: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:30:56: level=info msg="Configurations updated successfully"
Jun  5 02:30:56: level=info msg="Watching from revision 10"
Jun  5 02:39:53: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:39:53: level=info msg="Configurations updated successfully"
Jun  5 02:39:53: level=info msg="Watching from revision 10"
Jun  5 02:46:50: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:46:50: level=info msg="Configurations updated successfully"
Jun  5 02:46:50: level=info msg="Watching from revision 10"
Jun  5 02:52:48: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 02:52:48: level=info msg="Configurations updated successfully"
Jun  5 02:52:48: level=info msg="Watching from revision 10"
Jun  5 03:02:45: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:02:45: level=info msg="Configurations updated successfully"
Jun  5 03:02:45: level=info msg="Watching from revision 10"
Jun  5 03:10:42: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:10:42: level=info msg="Configurations updated successfully"
Jun  5 03:10:42: level=info msg="Watching from revision 10"
Jun  5 03:17:39: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:17:39: level=info msg="Configurations updated successfully"
Jun  5 03:17:39: level=info msg="Watching from revision 10"
Jun  5 03:25:37: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:25:37: level=info msg="Configurations updated successfully"
Jun  5 03:25:37: level=info msg="Watching from revision 10"
Jun  5 03:32:35: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:32:35: level=info msg="Configurations updated successfully"
Jun  5 03:32:35: level=info msg="Watching from revision 10"
Jun  5 03:38:32: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:38:32: level=info msg="Configurations updated successfully"
Jun  5 03:38:32: level=info msg="Watching from revision 10"
Jun  5 03:46:29: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:46:29: level=info msg="Configurations updated successfully"
Jun  5 03:46:29: level=info msg="Watching from revision 10"
Jun  5 03:53:27: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 03:53:27: level=info msg="Configurations updated successfully"
Jun  5 03:53:27: level=info msg="Watching from revision 10"
Jun  5 04:01:23: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:01:23: level=info msg="Configurations updated successfully"
Jun  5 04:01:23: level=info msg="Watching from revision 10"
Jun  5 04:12:20: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:12:20: level=info msg="Configurations updated successfully"
Jun  5 04:12:20: level=info msg="Watching from revision 10"
Jun  5 04:19:18: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:19:18: level=info msg="Configurations updated successfully"
Jun  5 04:19:18: level=info msg="Watching from revision 10"
Jun  5 04:25:17: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:25:17: level=info msg="Configurations updated successfully"
Jun  5 04:25:17: level=info msg="Watching from revision 10"
Jun  5 04:34:15: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:34:15: level=info msg="Configurations updated successfully"
Jun  5 04:34:15: level=info msg="Watching from revision 10"
Jun  5 04:45:13: level=info msg="wresp: {Header:{ClusterId:0 MemberId:0 Revision:0 RaftTerm:0} Events:[] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}"
Jun  5 04:45:13: level=info msg="Configurations updated successfully"

My code:
Watch:
	for {
		resp, err := etcdClient.GetKey(user.KeyPrefix, append(clientv3.WithLastRev(), clientv3.WithPrefix())...)
		PanicOn(err, "Failed getting revision")
		revision := resp.Header.Revision
		log.Info("Watching from revision %d", revision)

		client, err := etcdClient.GetClient()
		PanicOn(err, "Failed getting etcd client")

		timer := time.NewTimer(time.Minute * WatchTimeout)

		defer func() {
			client.Close()
			timer.Stop()
			if r := recover(); r != nil {
				handleError(r)
			}
		}()

		//Watch for all changes since the previous revision
		ops := []clientv3.OpOption{clientv3.WithPrefix(), clientv3.WithProgressNotify(), clientv3.WithPrevKV(), clientv3.WithRev(revision + 1)}
		rch := client.Watch(context.TODO(), user.KeyPrefix, ops...)
		select {
		case wresp := <-rch:
			log.Info("wresp: %+v", wresp)
			for _, ev := range wresp.Events {
				log.Info("Event: %+v", *ev)
			}
			//If the response is just a progress notification (sent every 10 minutes when no new events occur)
			if wresp.IsProgressNotify() || wresp.Header.Revision == revision {
				//Check if error occurred
				PanicOn(wresp.Err(), "Watch failed")
				log.Info("No updates to '%s'", user.KeyPrefix)
				continue
			}

			//Update the revision
			revision = wresp.Header.Revision

			//Process the updates
			for _, ev := range wresp.Events {
				log.Info("Event: %+v", *ev)
				if err := processEvent(ev); err != nil {
					panic(err.Error())
				}
			}

			//If successful in updating configurations, store the new commit id
			WriteTextFile(CONFIG_COMMIT_FILE, commitId)
			log.Info("Configurations updated successfully")

		// During failover and Restack, the service may shut down without closing the channel and the client will continue watching forever
		// Therefore, we restart the watcher if no channel responses are returned within the timeout period
		case <-timer.C:
			log.Info(TimeOutMessage)
			log.Info("Restarting client and watcher")
			break Watch
		}
	}

**Comment by hexfusion** [comment]
> Jun 5 01:14:16: level=info msg="Watching from revision 10"
> // Therefore, we restart the watcher if no channel responses are returned within the timeout period

Hi, @YeruchamB I believe this is caused by watching on a compacted revision? So in this case revision 10 is no longer available but your code restarts the watcher thinking it is recovering from other issue and fails because revision does not exist? Have not really dug into this but perhaps it's a theory to explore further.

ref: https://github.com/coreos/etcd/issues/8668

**Comment by YeruchamB** [comment]
Hi @hexfusion, we don't compact the kv store so that shouldn't be the cause... I took a look at the #8668 and I don't believe this is the same issue...

The reason I have that functionality written into the code is that when we redeploy our service or during rare failure states, the etcd cluster may shut down non-gracefully and no response is ever returned by the watcher. This way, the watcher will restart itself and connect to the restarted service.
When this happens, the revision is reset:
_resp, err := etcdClient.GetKey(user.KeyPrefix, append(clientv3.WithLastRev(), clientv3.WithPrefix())...)
PanicOn(err, "Failed getting revision")
revision := resp.Header.Revision_

**Comment by YeruchamB** [comment]
I think i might have some idea of what going on...
Is it possible that when auth is enabled, once a token becomes invalid, the watch returns and the authentication token isn't renewed?
I've changed my code around a bit and now notice that after a while, the watch just keeps being bombarded with this empty response. At the same time, i'm seeing a whole lot of invalid token warnings on the servers.
