### ISSUE TITLE
Empty key not allowed during get with prefix/fromKey using namespace in golang, 3.3.7

### ISSUE THREAD

**Issue by LogicalChaos** [etcd-io/etcd#9833]
Looking at this issue, https://github.com/coreos/etcd/issues/5323, I would expect to be able Get using an empty key both WithPrefix and WithFromKey within a namespace enabled client.  Etcd (version 3.3.7) server launched with no parameters`etcd`.

Without namespace:

1.   Works: clientv3.Get WithPrefix
1.   Works: clientv3.Get WithFromKey
2.   Works: ETCDCTL_API=3 etcdctl get ""  --prefix
3.   Works: ETCDCTL_API=3 etcdctl get ""  --from-key

With namespace (etcd namespace server launched with `etcd grpc-proxy start --endpoints=http://localhost:2379 --listen-addr=localhost:23790 --namespace partition`):

1.   Fails: clientv3.Get WithPrefix (etcdserver: key is not provided)
2.   Fails: clientv3.Get WithFromKey (etcdserver: key is not provided)
3.   Works: ETCDCTL_API=3 etcdctl get ""  --prefix
4.   Works: ETCDCTL_API=3 etcdctl --endpoints=http://localhost:23790 get "" --prefix
5.   Works: ETCDCTL_API=3 etcdctl get ""  --from-key
6.   Works: ETCDCTL_API=3 etcdctl --endpoints=http://localhost:23790 get "" --fromkey

Example code:
```
package main

import (
	"github.com/coreos/etcd/clientv3"
	"fmt"
	"context"
	)

func main() {
	db, _ := clientv3.New(clientv3.Config{
		Endpoints: []string{"localhost:2379"}})

	//client := db.KV
	client := namespace.NewKV(db.KV, "partition")

	//defer func() {
	//	for i := 0; i < 10; i++ {
	//		key := fmt.Sprintf("key-%d", i)
	//		client.Delete(context.TODO(), key)
	//	}
	//}()

	for i := 0; i < 10; i++ {
		key := fmt.Sprintf("key-%d", i)
		value := fmt.Sprintf("value-%d", i)
		client.Put(context.TODO(), key, value)
	}

	resp, err := client.Get(context.TODO(), "",
		//clientv3.WithPrefix(), clientv3.WithSort(clientv3.SortByKey, clientv3.SortAscend))
		clientv3.WithFromKey(), clientv3.WithSort(clientv3.SortByKey, clientv3.SortAscend))

	if err == nil {
		for _, item := range resp.Kvs {
			fmt.Println(string(item.Key), string(item.Value))
		}
	} else {
		fmt.Println(err)
	}
}
```
Startup log:

> 2018-06-11 13:31:08.514866 I | etcdmain: etcd Version: 3.3.7
> 2018-06-11 13:31:08.514990 I | etcdmain: Git SHA: 56536de55
> 2018-06-11 13:31:08.515000 I | etcdmain: Go Version: go1.9.6
> 2018-06-11 13:31:08.515006 I | etcdmain: Go OS/Arch: darwin/amd64
> 2018-06-11 13:31:08.515017 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8                                                                                      
> 2018-06-11 13:31:08.515072 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)                                                                                    
> 2018-06-11 13:31:08.515087 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd                                                                                                   
> 2018-06-11 13:31:08.515180 N | etcdmain: the server is already initialized as member before, starting as etcd member...                                                                                
> 2018-06-11 13:31:08.515717 I | embed: listening for peers on http://localhost:2380
> 2018-06-11 13:31:08.515981 I | embed: listening for client requests on localhost:2379
> 2018-06-11 13:31:08.517309 I | etcdserver: name = default
> 2018-06-11 13:31:08.517325 I | etcdserver: data dir = default.etcd
> 2018-06-11 13:31:08.517338 I | etcdserver: member dir = default.etcd/member
> 2018-06-11 13:31:08.517347 I | etcdserver: heartbeat = 100ms
> 2018-06-11 13:31:08.517353 I | etcdserver: election = 1000ms
> 2018-06-11 13:31:08.517358 I | etcdserver: snapshot count = 100000
> 2018-06-11 13:31:08.517370 I | etcdserver: advertise client URLs = http://localhost:2379
> 2018-06-11 13:31:08.661617 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 73725                                                                        
> 2018-06-11 13:31:08.685914 I | raft: 8e9e05c52164694d became follower at term 8
> 2018-06-11 13:31:08.685982 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 8, commit: 73725, applied: 0, lastindex: 73725, lastterm: 8]                                                           
> 2018-06-11 13:31:08.742909 W | auth: simple token is not cryptographically signed
> 2018-06-11 13:31:08.745597 I | etcdserver: starting server... [version: 3.3.7, cluster version: to_be_decided]                                                                                         
> 2018-06-11 13:31:08.745791 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)                                                                                         
> 2018-06-11 13:31:08.746398 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32                                                                
> 2018-06-11 13:31:08.746553 N | etcdserver/membership: set the initial cluster version to 3.3
> 2018-06-11 13:31:08.746649 I | etcdserver/api: enabled capabilities for version 3.3
> 2018-06-11 13:31:10.187248 I | raft: 8e9e05c52164694d is starting a new election at term 8
> 2018-06-11 13:31:10.187293 I | raft: 8e9e05c52164694d became candidate at term 9
> 2018-06-11 13:31:10.187322 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 9                                                                                             
> 2018-06-11 13:31:10.187359 I | raft: 8e9e05c52164694d became leader at term 9
> 2018-06-11 13:31:10.187388 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 9                                                                                             
> 2018-06-11 13:31:10.197026 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32                                                                     
> 2018-06-11 13:31:10.197050 I | embed: ready to serve client requests
> 2018-06-11 13:31:10.197678 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!                                                                                
>

**Comment by gyuho** [comment]
Try `kv.Get(context.Background(), "\x00", clientv3.WithFromKey())`?

**Comment by LogicalChaos** [comment]
Neither fails anymore by using a key of `\x00`.  But, `WithPrefix()` returns no data, `WithFromKey()` returns all the data.  That does matche the etcdctl behavior if the key `\x00` is passed, but is not what I'd expect.

**Comment by spzala** [comment]
Assigning to myself for further investigation as I am looking into a related issue on the behavior of ```WithFromKey``` and ```WithPrefix```

**Comment by spzala** [comment]
@LogicalChaos hello, the ```WithPrefix``` seems working fine for me with the latest code. But I could reproduce the issue for  ```WithFromKey```. I am working on creating a PR, meanwhile can you please try the github code and see if ```WithPrefix``` still gives you error. Thanks!
