### ISSUE TITLE
etcd 3.2.20 single node cannot start, logging 'etcdserver: publish error: etcdserver: request timed out'

### ISSUE THREAD

**Issue by nvtkaszpir** [etcd-io/etcd#9851]
**etcd version:** v3.2.20
**docker version:** Docker version 18.03.1-ce, build 9ee9f40
**host info:**
```bash
Linux daffodil-loc 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@daffodil-loc:/srv/docker/volumes/etcd# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Symptoms:**
Unfortunately this happens randomly, but we noticed this happens on fresh ectd start, when data directories are empty.
Sometimes fresh single node etcd in docker cannot start, logs are spammed with message:
```text
etcdserver: publish error: etcdserver: request timed out
```
Moreover, any etcdctl commands end with `Error:  context deadline exceeded`.

**Attached etcd logs, data and config:**
[etcd.bug.tar.gz](https://github.com/coreos/etcd/files/2102593/etcd.bug.tar.gz)
In general we run etcd under docker with dedicated moutpoint for etcd under lvm, something like 10GB, while there is about 500MB of data.

**Fix:**
Delete data dir, so that it is empty, and start container again. Which may be problematic during docker deployments....

**Comment by gyuho** [comment]
What's your configuration?

**Comment by nvtkaszpir** [comment]
Just edited first post, see attached .tar.gz.

**Comment by nvtkaszpir** [comment]
also noticed that when tried to run etcd v3.2.22 on the same data, then etcd also cannot start.

**Comment by gyuho** [comment]
Where do you configure `192.168.7.121` and what flags do you pass to etcd? Please try without docker. Pretty sure this is something with docker. Also check out https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md.

**Comment by nvtkaszpir** [comment]
192.168.7.121 is a second network interface dedicated for communication between certain apps, etcd is one of them.
within tar.gz file there is ```volumes/etcd/config.yml``` which is used by etcd to load its vars.

**Comment by nvtkaszpir** [comment]
@gyuho I strongly suggest to reopen the issue.

[etcd.bug.3.zip](https://github.com/coreos/etcd/files/2144984/etcd.bug.3.zip)

I had time to test it on standalone etcd process which is not within docker - just as standalone etcd process downloaded from official release channels. (see install.sh)
The same issue persists if using given data created on initial etcd start, so looks like this is related to the created data within storage.

See attached archive more data to debug issue.
It contains:
- install.sh to download specific etcd version from official releases.
- contents of the /srv/docker/volumes/etcd used on the host
- strace command used to start etcd, which was killed after manually after about 60s
- strace log from above.
- basic system info (uname/lsb_release)

**Comment by nvtkaszpir** [comment]
OK, below archive should provide reproductible setup.
[etcd.bug.4.tar.gz](https://github.com/coreos/etcd/files/2145012/etcd.bug.4.tar.gz)

**Comment by nvtkaszpir** [comment]
@gyuho any progress on this?

**Comment by xdk25d** [comment]
I seem to have encountered a problem similar to yours.
https://github.com/coreos/etcd/issues/9931

**Comment by Tutotu** [comment]
my  etcd version 3.3.9 ,i have the same problem. why？ i think ，because the sync snapshot to big。

**Comment by nvtkaszpir** [comment]
Can we get an update in this issue?
