### ISSUE TITLE
unexpectedly high leader election rate

### ISSUE THREAD

**Issue by peradel** [etcd-io/etcd#9873]
In our Kubernetes Cluster we observe a leader election rate of about 150 per day. 

After moving the etcd from VMs to bare metal, the rate of ca.3-5/day increased to  150. In general, the latencies have improved by around a factor of 10, just not the leader elections. We have 5 nodes running version 3.3.3.

How many leader elections are normal?

**Comment by jiaxuanzhou** [comment]
leader election  is impacted by io of network and disk, i think you need to check the latency of the disk io and rtt of the network.

**Comment by peradel** [comment]
As described above, the latency has dropped.
DBsyn are 7ms
WALsync is 1ms
ping icmp_seq = 7 ttl = 64 time = 0.117 ms

Unfortunately, the leader elections have risen

**Comment by christianhuening** [comment]
Here's the past 7 days of metrics in our dashboard:
<img width="2384" alt="bildschirmfoto 2018-06-26 um 14 59 10" src="https://user-images.githubusercontent.com/738953/41913789-8af0546c-7951-11e8-84db-78cb62f36a2b.png">

**Comment by xarses** [comment]
There should be logs in the form of stdout and stdin. The member status and elections should be in the stdout stream

**Comment by lafolle** [comment]
Is it possible this is related to #9962 ?
