### ISSUE TITLE
potential issue in unstable.maybeTerm function?

### ISSUE THREAD

**Issue by omnimose** [etcd-io/etcd#9881]
In func maybeTerm:

```go
        func (u *unstable) maybeTerm(i uint64) (uint64, bool) {
	if i < u.offset {
		if u.snapshot == nil {
			return 0, false
		}
		if u.snapshot.Metadata.Index == i {
			return u.snapshot.Metadata.Term, true
		}
		return 0, false
	}

	last, ok := u.maybeLastIndex()
	if !ok {
		return 0, false
	}
	if i > last {
		return 0, false
	}
	return u.entries[i-u.offset].Term, true
}
```
If unstable has snapshot, u.maybeLastIndex may return (u.snapshot.Metadata.Index, true) as below:

```go
        if u.snapshot != nil {
		return u.snapshot.Metadata.Index, true
	}
```
for this case, unstable should not have any entries, so below line of maybeTerm may fail?

```go
     return u.entries[i-u.offset].Term, true
```

**Comment by gyuho** [comment]
> so below line of maybeTerm may fail?

I am not clear about your question.
Could you write a simple test case to explain the issue?

**Comment by omnimose** [comment]
Thanks for the reply, I am not sure to trigger this, it is based on my understanding of the code so please correct me if I am wrong:

1. for the unstable type, it could have either entries or snapshot, but it could have both at the same time.

2. say the unstable type have snapshot and we call maybeTerm, in this function, we may run to below code:

        last, ok := u.maybeLastIndex()
	if !ok {
		return 0, false
	}
	if i > last {
		return 0, false
	}
	return u.entries[i-u.offset].Term, true

3. since unstable only have snapshot, maybeLastIndex function runs to below code:

        if u.snapshot != nil {
		return u.snapshot.Metadata.Index, true
	}

4. then go back to maybeTerm, we run to this line of code:

       return u.entries[i-u.offset].Term, true

which may fail since unstable only have snapshot.

Just reading from code, seems the issue is possible to occur, please correct me if I am wrong.

**Comment by omnimose** [comment]
Any thought on this issue?
