### ISSUE TITLE
client v3 queue recipe seems to leak memory

### ISSUE THREAD

**Issue by Funcan** [etcd-io/etcd#9882]
Using the following to stuff items into a queue:
```golang
package main
import (
	"log"
	"github.com/coreos/etcd/clientv3"
	recipe "github.com/coreos/etcd/contrib/recipes"
)

func main() {
	cfg := clientv3.Config{Endpoints: []string{"localhost:2379"}}
	client, err := clientv3.New(cfg)
	if err != nil {
		panic(err)
	}
	queue := recipe.NewQueue(client, "testqueue")
	count := 0
	for {
		queue.Enqueue("foo")
		count++
		if count%100 == 0 {
			log.Printf("Done %d loops", count)
		}
	}
}
```

And the following to pull them out:
```golang
package main

import (
	"log"

	"github.com/coreos/etcd/clientv3"
	recipe "github.com/coreos/etcd/contrib/recipes"
)

func main() {
	cfg := clientv3.Config{Endpoints: []string{"localhost:2379"}}

	client, err := clientv3.New(cfg)
	if err != nil {
		panic(err)
	}

	queue := recipe.NewQueue(client, "testqueue")

	count := 0
	for {
		_, err = queue.Dequeue()
		if err != nil {
			panic(err)
		}
		count++
		if count%100 == 0 {
			log.Printf("Done %d loops", count)
		}
	}
}
```

(The source runs faster than the sink so kill it once there's a good number of items in the queue)

When I run this, I see that both the RSS and the virtual size of the sink process rises continuously.

Basic attempts looking for the memory leak pointed me at a malloc inside the V3 client, though I'm still learning the go leak finding tools; I'll add more notes when I have something coherent on that front

Any help appreciated

**Comment by gyuho** [comment]
What is your etcd server and client version?

**Comment by Funcan** [comment]
# ./etcd --version
etcd Version: 3.2.18
Git SHA: eddf599c6
Go Version: go1.8.7
Go OS/Arch: linux/amd64

Client is on master branch, commit bb744f6d2b2715ec4aac696e0de51c75955334a8 (June 8th 2018) - if there's a better way to find/specify the version, please let me know

**Comment by gyuho** [comment]
@Funcan There are still issues with master branch client. Please use 3.2 or 3.3 client for now. We are working to fix it.

**Comment by Funcan** [comment]
The 3.3 client is definitely better, but still growing... taken every minute:

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
duncan   10289  2.7  0.0 359996 12492 pts/17   Sl+  17:48   0:00 ./sink
duncan   10289  2.5  0.0 845000 13736 pts/17   Sl+  17:48   0:01 ./sink
duncan   10289  2.5  0.0 1001172 13736 pts/17  Sl+  17:48   0:02 ./sink
duncan   10289  2.6  0.0 1001172 13956 pts/17  Sl+  17:48   0:03 ./sink
duncan   10289  2.5  0.0 1074904 13956 pts/17  Sl+  17:48   0:04 ./sink
duncan   10289  2.7  0.0 1166340 13956 pts/17  Sl+  17:48   0:05 ./sink
duncan   10289  2.7  0.0 1167396 14872 pts/17  Sl+  17:48   0:06 ./sink
duncan   10289  2.7  0.0 1168456 16360 pts/17  Sl+  17:48   0:07 ./sink
duncan   10289  2.8  0.0 1243500 17120 pts/17  Sl+  17:48   0:08 ./sink



In my real program exhibiting this, the CPU usage also ramps up slowly; I guess because the GC is working harder but I will profile to find out

**Comment by gyuho** [comment]
@Funcan Thanks for reproduce. We will make sure to address this before 3.4.

**Comment by vimalk78** [comment]
@Funcan , can you check with changes in this PR, and verify if it fixes the memleak? i have observed for 20 minutes and multiple clients. the memory did not increase.
thx!
