### ISSUE TITLE
deploy ha etcd on kubernetes 

### ISSUE THREAD

**Issue by raoofm** [etcd-io/etcd#9895]
I know we have etcd-operator to handle this, but it is not truly functional for prod use cases and doesn't seem to be actively worked on. 

It will be great to have a documented way of deploying robust ha etcd cluster on top of kubernetes with/without pv. This should be common usecase that many encounter and can be pretty useful. I was searching on the web but was surprised not to find something documented for such an amazing project.

I think we could leave backup and restore as it could be different for different organizations. 

There can be reconfiguration to replace a down node which doesn't respond for configurable time t.

**Comment by raoofm** [comment]
@gyuho Is there any recommendyed way of deploying etcd on kubernetes? Seems like the operator development has stalled.

**Comment by hexfusion** [comment]
I am also curious what the future of operator project is. I understand the team is working on other projects currently. I would be interested in getting more involved but the general feeling is this is a less open project and more in-house. People have proposed forking it before, perhaps this would be more realistic now that we are moving to a new org and operator is staying in coreos?

@raoofm maybe we should move this to https://github.com/coreos/etcd/issues/9965 ?

**Comment by raoofm** [comment]
From #9965

> We are moving etcd and other sub-projects to its own GitHub organization.

@hexfusion what makes you think operator stays in coreos, i think operator would move along with etcd to the new org.

**Comment by hexfusion** [comment]
@raoofm per that issue.

>Projects that won't be moved:
>https://github.com/coreos/etcd-operator
>https://github.com/coreos/discovery.etcd.io

**Comment by raoofm** [comment]
😃 my bad

**Comment by gyuho** [comment]
@raoofm @hexfusion "etcd" team is not working on etcd-operator right now. And operator SDK team will be working on etcd-operator.

> Seems like the operator development has stalled.

Correct. Nobody is actively working on it. We are looking for ways to revive that project.

**Comment by gyuho** [comment]
@raoofm If you can contribute to this, it would be great. No one in etcd team has plan to work on this in the near future.
