### ISSUE TITLE
etcd server lease timeout occasionly

### ISSUE THREAD

**Issue by jiajialijiajiali** [etcd-io/etcd#9899]
There is a product on cloud that I am testing which uses etcd. 
Recently met etcd server lease timeout issue frequently without any call load. 
The etcd client refresh the etcd key lease every 5 second to ensure that the client etcd key is not expired, the key of the etcd client is one single record in etcd. 
However, for uncertain reason, etcd lease timeout, see below etcd log and metrics
could you please comment why etcd timeout for single entry lease and any method resolve this issue? 
There is no any call load running and the CPU occupy is not high (idle ~35%), 4 vCPU in total for all.

# HELP etcd_debugging_server_lease_expired_total The total number of expired leases.
# TYPE etcd_debugging_server_lease_expired_total counter
etcd_debugging_server_lease_expired_total 390

# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 13637
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 13653
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 13658
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 13666
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 13666
etcd_disk_backend_commit_duration_seconds_sum 2.3070954790000044
etcd_disk_backend_commit_duration_seconds_count 13666
2018-07-03 00:38:11.992380 W | etcdserver: apply entries took too long [246.755688ms for 1 entries]
2018-07-03 00:38:11.992474 W | etcdserver: avoid queries with large range/delete range!

/ # etcd --version
etcd Version: 3.2.7
Git SHA: 9ce8513b6f
Go Version: go1.8.3
Go OS/Arch: linux/amd64

**Comment by gyuho** [comment]
> lease timeout issue frequently without any call load

Do you mean leases are being expired while sending keepalive requests?

**Comment by jiajialijiajiali** [comment]
i do not know how to check the question's answer, but from etcd log and etcd metric, etcd side is ubnormal.
etcd_debugging_server_lease_expired_total 390
2018-07-03 00:38:11.992380 W | etcdserver: apply entries took too long [246.755688ms for 1 entries]
2018-07-03 00:38:11.992474 W | etcdserver: avoid queries with large range/delete range!

**Comment by gyuho** [comment]
Those warnings keep happening? Can you also provide fsync metrics? You can just `curl ENDPOINT | grep fsync`.

**Comment by jiajialijiajiali** [comment]
Those warnings do not keep happen. However, lease timeout keeps happen. 

# HELP etcd_debugging_server_lease_expired_total The total number of expired leases.
# TYPE etcd_debugging_server_lease_expired_total counter
etcd_debugging_server_lease_expired_total 224

# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 9280
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 9280
etcd_disk_wal_fsync_duration_seconds_sum 0.02352618800000004
etcd_disk_wal_fsync_duration_seconds_count 9280

**Comment by gyuho** [comment]
Hmm, latency numbers look good, which means it should be from something else.

> etcdserver: avoid queries with large range/delete range!

Can you try trigger this warning again? By sending similar requests to etcd server?

**Comment by gyuho** [comment]
I will also improve the warning messages.

**Comment by jiajialijiajiali** [comment]
Can you try trigger this warning again? By sending similar requests to etcd server?
=>Not yet, this warning log does not occur again so far, but lease timeout still exist.

**Comment by cfc4n** [comment]
well, I mean ...number of all leases , not of "expired lease".

**Comment by jiajialijiajiali** [comment]
so you want to know the number from all clients? can this be seen in etcd metric?

**Comment by cfc4n** [comment]
yep, value of "sum(grpc_server_started_total{grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"}) - sum(grpc_server_handled_total{grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"})".

**Comment by jiajialijiajiali** [comment]
Thank you. Here is the metric, i do not know how to caculate for 1.xxxxxxxe+06

grpc_server_started_total{grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 1.734624e+06

grpc_server_handled_total{grpc_code="Canceled",grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 712
grpc_server_handled_total{grpc_code="OK",grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 1.129258e+06
grpc_server_handled_total{grpc_code="Unavailable",grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 604648
grpc_server_handled_total{grpc_code="Unknown",grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 6

**Comment by cfc4n** [comment]
「Are they all of leases keepalive? and how many clients to keepalive that?」 ？？？

**Comment by jiajialijiajiali** [comment]
I guess so, there is only LeaseKeepAlive method which meets your listed caculation:
grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"
The number of total clients would not be too many, <10? i do not know the actual number. As I know the client that I find frequently meet timeout sends lease request every 5seconds to etcd server.
What do you doubt? 

# HELP grpc_server_started_total Total number of RPCs started on the server.
# TYPE grpc_server_started_total counter
grpc_server_started_total{grpc_method="DeleteRange",grpc_service="etcdserverpb.KV",grpc_type="unary"} 44
grpc_server_started_total{grpc_method="LeaseGrant",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 238
grpc_server_started_total{grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"} 1.734624e+06
grpc_server_started_total{grpc_method="LeaseRevoke",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 1
grpc_server_started_total{grpc_method="LeaseTimeToLive",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 1.492175e+06
grpc_server_started_total{grpc_method="MemberList",grpc_service="etcdserverpb.Cluster",grpc_type="unary"} 21037
grpc_server_started_total{grpc_method="Put",grpc_service="etcdserverpb.KV",grpc_type="unary"} 329
grpc_server_started_total{grpc_method="Range",grpc_service="etcdserverpb.KV",grpc_type="unary"} 4.703231e+06
grpc_server_started_total{grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 2784
grpc_server_started_total{grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 166
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
