### ISSUE TITLE
permission denied using grpc gateway through authentication (etcd version 3.0.10) 

### ISSUE THREAD

**Issue by amyXia1994** [etcd-io/etcd#9959]
I visit etcd server through grpc gateway with etcd auth enabled. I can get correct token but when use token to fetch key, it returns "etcdserver: permission denied". My etcd version is 3.0.10.

This problem does not occur when I test with etcd 3.3.8.

Does previous etcd version before 3.3 support **fetching key with token via grpc gateway**? Or can you please provide a way to config my 3.0.10 etcd to support that? 
Solution besides updating etcd version is preferred since that takes extra efforts.

Here are my visit requests:
I can get correct token from username and password:
```
curl -s  http://host:port/v3alpha/auth/authenticate  -X POST -d '{ "name":"userName", "password":"pw" }'
```                    
but when I use the token to fetch key, I got "permission denied"
```
curl -L http://host:port/v3alpha/kv/range -H "Authorization : tokenIJustGot" -X POST -d '{"key": "bmFtZQ=="}'
```
That's the response:
```
{"Error":"etcdserver: permission denied","Code":9}
```

**Comment by hexfusion** [comment]
@amyXia1994 auth was enabled with gRPC gateway as of v3.3 I am not sure if a plan exists to backport.

ref: https://github.com/coreos/etcd/pull/7999

**Comment by hexfusion** [comment]
@gyuho is backporting this feature something we are considering? If not this issue can be closed.
