### ISSUE TITLE
The number of goroutines  continues to grow for v3.2.7 on docker

### ISSUE THREAD

**Issue by plpan** [etcd-io/etcd#9996]
Hi,

We've noticed an issue where clientv3 behaves differently for docker and physical machine. Two isolated clusters are setup with 3 physical machines and 5 containers. The number of goroutines continues to grow in docker container.
### etcd version
3.2.7
### configuration
/home/test/etcd/etcd --name "etcd03" --data-dir "/home/test/etcd/data" --advertise-client-urls "http://10.156.42.183:2379" --initial-advertise-peer-urls "http://10.156.42.183:2380" --initial-cluster "etcd00=http://10.156.11.240:2380,etcd02=http://10.156.91.239:2380,etcd03=http://10.156.42.183:2380,etcd04=http://10.156.3.238:2380,etcd05=http://10.156.11.239:2380" --initial-cluster-state "existing" --initial-cluster-token "token" --listen-client-urls "http://10.156.42.183:2379,http://127.0.0.1:2379" --listen-peer-urls "http://10.156.42.183:2380"
### metrics
[etcd-metrics.zip](https://github.com/coreos/etcd/files/2280084/etcd-metrics.zip)
### interactive with etcd
get, put, del, and put with lease!

Need help! and thanks!

**Comment by gyuho** [comment]
Do you have exact same workloads between two?

**Comment by plpan** [comment]
@gyuho yeal, the workload is exactly the same. Details are given in https://github.com/etcd-io/etcd/issues/10009.

**Comment by vimalk78** [comment]
do you have logs that you can share?

**Comment by wenjiaswe** [comment]
@jpbetz @wenjiaswe
